### ISSUE TITLE
Farmable hemp for bow strings.

### ISSUE THREAD

**Issue by mrDLSable** [MelvorIdle/melvoridle.github.io#10]
A plant that can be crafted into bow strings. This would allow for the removal of bow strings from the store. I am of the opinion that as few items as possible have to be bought from the store.

Later on hemp can also be used to craft bags.

**Comment by RedSparr0w** [comment]
In RuneScape `Flax` is used to craft bowstrings.

**Comment by mrDLSable** [comment]
Very true. I misremembered. In the end the name of the crop doesn't really matter though.
