### ISSUE TITLE
Incorrect Mithril Smelting Values

### ISSUE THREAD

**Issue by Ryukinash** [MelvorIdle/melvoridle.github.io#1000]
**Describe the bug**
When smelting Mithril Bar, 4 Mithril Ore are consumed and only 1 coal.

**To Reproduce**
1. Go to smithing page
2. Select Mithril Bar
3. Create Mithril Bar
4. Values are subtracted

**Expected behavior**
I expected 4 coal to be consumed and 1 mithril ore

**ScreenshotsIf applicable, add screenshots to help explain your problem.**
![Before Bar](https://user-images.githubusercontent.com/85725849/121636292-88fc0b80-ca3c-11eb-923a-aa412603644d.PNG)

![After Bar](https://user-images.githubusercontent.com/85725849/121636379-adf07e80-ca3c-11eb-9d10-32183301702d.PNG)

**Browser**
Steam Alpha V0.20 (?904)

**Comment by MelvorIdle** [comment]
This is confirmed hotfixed
