### ISSUE TITLE
Skilled Fletching Potion III says 15%, but acts at 10%

### ISSUE THREAD

**Issue by JLMonk** [MelvorIdle/melvoridle.github.io#1002]
Using the Skilled Fletching Potion III only gives 10% chance to receive 2x items, rather than the 15% it says it gives when selecting the potion to use.

1. Have at least a couple of Skilled Fletching Potion III.
2. Go to fletching and clear out any current potion you may have, don't auto-reuse.
3. Click on a item to fletch and make note of your change to double items.
4. Click on the potions icon, note that Skilled Fletching Potion III specifies 15% chance to double items.
5. Use the Skilled Fletching Potion III - note that the chance to double make the item you have selected only goes up 10%.

**Expected behavior**
Skilled Fletching Potion III should increase the chance to double make a fletching item by 15%, or the text should specify 10%.

**Screenshots**
![image](https://user-images.githubusercontent.com/2006677/121673674-0a898300-caa9-11eb-8499-948a8b585eec.png)
![image](https://user-images.githubusercontent.com/2006677/121673691-11b09100-caa9-11eb-8650-9dadef2545ae.png)
![image](https://user-images.githubusercontent.com/2006677/121673709-18d79f00-caa9-11eb-8ae5-a2fc563f135e.png)

**Browser**
Chrome 92, opened as it's own window.

**Console output**
No logs of note.

**Are you using any scripts?**
Combat simulator installed, but disabled to test this.

**Comment by Sundwalltanner** [comment]
I'm seeing this for `Skilled Fletching Potion III` as well.

The weird part is I'm fairly certain it works correctly for `Skilled Fletching Potion IV`.
