### ISSUE TITLE
Centaurs require 50 redwood bows

### ISSUE THREAD

**Issue by imthe666st** [MelvorIdle/melvoridle.github.io#1003]
**Describe the bug**
Centaurs currently require 50 redwood bows to create summoning tablets. Other familiars require only one of the top tier item to summon.

**To Reproduce**
1. Unlock The Centaur Familiar
2. Look at recipe list
3. See that it requires 50 redwood bows.

**Expected behavior**
The Centaur Familiar should only require one redwood bow, similar to other familiars. 

**Screenshots**
![image](https://user-images.githubusercontent.com/7377849/121676763-517d7580-cab5-11eb-8714-67efd4985e4d.png)

**Browser**
Steam Version

**Comment by MelvorIdle** [comment]
Check the patch notes to see how material costs are determined. It's not based on "Level"

**Comment by imthe666st** [comment]
Ah! Seems like I misunderstood it then. 
Thanks for clarifying again.
