### ISSUE TITLE
Magic, Prayer, and Slayer not changing colour in left-hand menu when being used

### ISSUE THREAD

**Issue by FidgetStick** [MelvorIdle/melvoridle.github.io#1004]
**Describe the bug**
Magic, Prayer, and Slayer titles in left-hand menu are not changing to green when being used in combat.

**To Reproduce**
1. start combat with magic attack or ...
2. start Slayer task or ...
3. change/start using Prayer while in combat
4. colours of these headings don't change as expected

**Expected behavior**
when using the Magic attack, Fighting a Slayer task or using Payer in combat should result in the colour of this text changing to green

**Browser**
firefox

**Console output**
Loading failed for the <script> with source “https://ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js”. melvoridle.com:24:1
Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-129674422-1”. melvoridle.com:6:1
Loading failed for the <script> with source “https://static.cloudflareinsights.com/beacon.min.js”. melvoridle.com:490:1
MICSR: playerSpecialNames is waiting for util MICSR.js:26:31
MICSR: statNames is waiting for util MICSR.js:26:31
MICSR: setting up util MICSR.js:26:31
MICSR: main is waiting for App MICSR.js:26:31
MICSR: setting up Plotter MICSR.js:26:31
MICSR: TabCard is waiting for Card MICSR.js:26:31
MICSR: setting up Menu MICSR.js:26:31
MICSR: Simulator is waiting for statNames MICSR.js:26:31
MICSR: setting up Loot MICSR.js:26:31
MICSR: setting up Import MICSR.js:26:31
MICSR: setting up Card MICSR.js:26:31
MICSR: CombatData is waiting for statNames MICSR.js:26:31
MICSR: setting up modifierNames MICSR.js:26:31
MICSR: no unknown modifiers detected! modifierNames.js:417:25
MICSR: App is waiting for statNames MICSR.js:26:31
MICSR: App is waiting for CombatData MICSR.js:26:31
MICSR: App is waiting for Simulator MICSR.js:26:31
MICSR: App is waiting for TabCard MICSR.js:26:31
loadCharacterSelection main.js:266:594
MICSR: setting up playerSpecialNames MICSR.js:26:31
MICSR: setting up statNames MICSR.js:26:31
MICSR: unknown item property slayerAreaEffectNegationFlat MICSR.js:26:31
MICSR: unknown item property fishingBonusXP MICSR.js:26:31
MICSR: setting up TabCard MICSR.js:26:31
MICSR: setting up Simulator MICSR.js:26:31
MICSR: setting up CombatData MICSR.js:26:31
MICSR: setting up App MICSR.js:26:31
MICSR: setting up main MICSR.js:26:31
Connected to PlayFab successfully cloud.js:76:144
selectCharacter main.js:322:44
set force reload to 0 save.js:71:60
selectCharacter main.js:322:44
Loading Save Game... save.js:13:9
Save Game Loaded... save.js:29:95
Game Loaded main.js:20:405
Array [ 0, 0 ]
main.js:118:817
Connected to PlayFab successfully cloud.js:76:144
MICSR: Melvor Combat Sim v1.3.14 Loaded, but simulation results may be inaccurate. MICSR.js:26:31
Synchronising with Cloud cloud.js:8:154
Loading failed for the <script> with source “https://static.cloudflareinsights.com/beacon.min.js”. index.html:565:1
Loading failed for the <script> with source “https://static.cloudflareinsights.com/beacon.min.js”. update_v020.html:928:1
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features! melvoridle.com

**Are you using any scripts?**
Combat Simulator Reloaded v1.3.14 (outdated)

**Comment by Sachbir** [comment]
A similar issue occurs for Meelee combat. When switching attack styles, the next skill does not turn green until the current enemy is slain. 

For example, if switching from "_Stab_" to "_Slash_", the "_Attack_" skill will turn white, but only after the current enemy is killed does the "_Strength_" skill turn green.

**Comment by coolrox95** [comment]
Fixed with update v0.21
