### ISSUE TITLE
New Artisan UI displays incorrect Mastery XP values

### ISSUE THREAD

**Issue by Sachbir** [MelvorIdle/melvoridle.github.io#1005]
**Describe the bug**
The Mastery and Mastery Pool XP displayed in the new Artisan UI is different from the values I see being added to the respective Mastery totals. 

**To Reproduce**
May apply to any/every Artisan crafting, but in my specific example: 
1. Go to the Crafting skill. 
2. Click on Dragonhide, then Green D-hide Body. Start crafting. 
3. Compare value in the UI (under "Grants") with the value being added to the Mastery or Mastery Pool totals (I had to calculate the difference manually). 

**Expected behavior**
The value in the new Artisan UI should match the values being added to the Mastery and Mastery Pool XP totals. 

**Browser**
Firefox Version 78

**Console output**
Should be irrelevant, but: 

Navigated to https://melvoridle.com/
GEThttps://cdn.melvor.net/core/v018/assets/media/favicons/favicon-192x19.svg
[HTTP/2 403 Forbidden 54ms]

GEThttps://cdn.melvor.net/core/v018/assets/media/favicons/favicon-192x19.svg
[HTTP/2 403 Forbidden 57ms]

Some cookies are misusing the recommended “SameSite“ attribute 2
loadCharacterSelection main.js:266:594
fun-hooks: referenced 'registerAdserver' but it was never created prebid.min.js:3:46240
Request to access cookie or storage on “https://sb.scorecardresearch.com/b?c1=2&c2=20567959&ns__t=1623429502000&ns_c=UTF-8&cv=3.5&c8=Melvor%20Idle%20%3A%3A%20Alpha%20v0.20&c7=https%3A%2F%2Fmelvoridle.com%2F&c9=” was blocked because it came from a tracker and content blocking is enabled.
Connected to PlayFab successfully cloud.js:76:144
selectCharacter main.js:322:44
set force reload to 0 save.js:71:60
selectCharacter main.js:322:44
Loading Save Game... save.js:13:9
Save Game Loaded... save.js:29:95
Game Loaded main.js:20:405
Array [ 0, 0 ]
main.js:118:817
Synchronising with Cloud cloud.js:8:154
Connected to PlayFab successfully cloud.js:76:144
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features! melvoridle.com

**Are you using any scripts?**
No scripts used.

**Comment by MelvorIdle** [comment]
This is now confirmed hotfixed
