### ISSUE TITLE
404s on icon GET

### ISSUE THREAD

**Issue by Balake** [MelvorIdle/melvoridle.github.io#1006]
**Describe the bug**
New agility obstacle icons not showing in mastery.

**To Reproduce**
1. Go to 'Agility'
2. Click on 'Spend XP'
3. Scroll down to last items
4. See images missing

**Expected behavior**
Icon describing which obstacle it is to be visible

**Screenshots**
<img width="1426" alt="Screen Shot 2021-06-11 at 10 25 13 AM" src="https://user-images.githubusercontent.com/12928604/121726850-f55c2680-ca9f-11eb-9f38-0a4b0f20e4b4.png">

**Browser**
Brave Version 1.24.86 Chromium: 90.0.4430.212 (Official Build) (x86_64)

**Console output**
404s on image GET
https://melvoridle.com/assets/media/skills/agility/6FT.svg
https://melvoridle.com/assets/media/skills/agility/8RT.svg

**Are you using any scripts?**
Combat sim extension

**Comment by coolrox95** [comment]
Fixed in update v0.21
