### ISSUE TITLE
Previewed XP from new UI is incorrect. 

### ISSUE THREAD

**Issue by Blasdf21** [MelvorIdle/melvoridle.github.io#1007]
**Describe the bug**
Checking the numbers, from the new UI to the actual given XP, using Mastery XP for this example, it states that I would be granted 911 Mastery XP (Using 99 nature rune, no ring of mastery on, only bonus from Ty, no debuffs or buffs from agility courses), but only receiving 774 mastery xp into the nature rune. 

**To Reproduce**
1. Have 99 mastery Nature rune.
2. Check current mastery xp.
3. Craft one.
4. Check mastery xp after.
5. The values from what was received, rather than the previewed xp that you should receive, are two different values.

**Expected behavior**
What I expected to happen was receiving 911 mastery xp after creating a rune, but doing the math, received a different value than what is shown on the rune crafting screen. 

**Screenshots**
https://gyazo.com/8eb0a77fcc46b7e34b1bb110af9cb0c4
https://gyazo.com/feae3cbe759babe0c042a3fa93b70355

**Browser**
Opera on Desktop, version 76.0.4017.177

**Console output**
I can't open the console, pressing F12 results in nothing happening on the web page. 

**Are you using any scripts?**
I am not. 

EDIT:
The screenshot attached has the current mastery xp value (not adding into the millions value, because is is not relevant when putting these numbers together, with the other number being shown the previous amount of mastery XP I have. I'm adding another screenshot to this with the current mastery value you can see in the first, with another rune being created, and showing the new mastery XP. This is to just give clarification that any numbers aren't being changed or messed with.

**Comment by MelvorIdle** [comment]
Can confirm this is now hotfixed :)
