### ISSUE TITLE
Loading your progress infinite loop

### ISSUE THREAD

**Issue by candybomberz** [MelvorIdle/melvoridle.github.io#1008]
Sometimes when I come back to the melvor website,
instead of showing offline progress normally,
the site gets stuck in an infinite loop showing me:

https://prnt.sc/153cm06

without ever resolving.

Also when I click ok,
the prompt shows up again.

**Comment by Fuvias** [comment]
That seems to be a minor bug, just pressing okay seems to resolve the problem for me at least. (just a rando though so ye)

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
