### ISSUE TITLE
Chaos Summoning Synergy - 1000x synergy gold

### ISSUE THREAD

**Issue by Valericoe** [MelvorIdle/melvoridle.github.io#1010]
This is in Chaos mode, but when you use the Synergy of Goblin Thief + Minotaur you get far more than full amount of your Chaos mode hits.

Using Infernium my max hit is 27,195,966, but the amount of gold received varies from 39,000,000,000 to 67,000,000,000.

I do have a lot of Corruption modifiers, such as double looting and % chance to double items globally.
It's worth noting that my Goblin Thief and Minotaur are both level 4.

**To Reproduce**
1. Play as a Chaos mode character
2. Equip the Goblin Thief + Minotaur from the synergy menu
3. Begin attacking enemies with melee

**Expected behavior**
Ideally: The normal mode amount of gold
Reasonably: 25% of hits as gold (Still in the millions, but I'm a bit puzzled why it's 1000x higher than expected)

**Screenshots**
![image](https://user-images.githubusercontent.com/43940984/121752682-a681b180-cade-11eb-8044-02031b7c2969.png)

**Browser**
Steam v0.20

**Console output**
Unsure how to access via Steam

**Are you using any scripts?**
None

**Comment by MelvorIdle** [comment]
Chaos mode bugs will be a thing. It's a gamemode that ended a long time ago and is no longer managed.
