### ISSUE TITLE
Alt Magic doesn't give marks while offline

### ISSUE THREAD

**Issue by sylhaern** [MelvorIdle/melvoridle.github.io#1011]
**Describe the bug**
Alt magic gives marks as expected while online, but doesn't give any from offline progress

**To Reproduce**
Run alt magic online - get marks as expected
Log off, log back in 12 hours later - get no marks from alt magic that happened while idling offline

**Expected behavior**
Expect alt magic to give marks offline like other non-combat skills do - maybe it's because magic is a combat skill?

**Browser**
Steam 20.913
Chrome 20.913

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Did you create the tablet after getting the first Mark, so subsequent Marks were able to roll?

**Comment by sylhaern** [comment]
I did - I made two copies of the same save, and left one running on the steam client on my desktop.  The online one got marks, the offline one did not

**Comment by MelvorIdle** [comment]
> I did - I made two copies of the same save, and left one running on the steam client on my desktop. The online one got marks, the offline one did not

Thanks for confirming. I will look into it an apply a hotfix asap

**Comment by yugo0075** [comment]
Just wanted to mention that I came accross a similar problem just a few minutes ago.
To be more specific : while I was using Alt. Magic offline (equiped with occultist and witch tablets) no tablets were consumed, no exp gained and no mark found.
And I'm playing on mozilla.
Thanks again for your efforts, good luck tracking all the new bugs for the new patch !  ;)
