### ISSUE TITLE
Can't play the game

### ISSUE THREAD

**Issue by Helvenea** [MelvorIdle/melvoridle.github.io#1012]
everytime im playing I can't seem to access any save files after i exit the game, everytime i click it nothing happens, i also cant find the folder of cloud saves in steam user data (planning to delete it and reset everything), im thinking that's the root of the problem the folder that holds the save is missing, i already uninstall-install it for numerous times and restart my pc nothing works

ps. it's fine even I can't access my older saves just let me play the game

**Comment by MelvorIdle** [comment]
Delete the contents of the folder C:\Users\<username>\AppData\Local\Melvor Idle\

**Comment by Helvenea** [comment]
it doesn't exist

**Comment by Helvenea** [comment]
> Delete the contents of the folder C:\Users<username>\AppData\Local\Melvor Idle\
> 
> And then load up the game

it didn't exist

**Comment by MelvorIdle** [comment]
> > Delete the contents of the folder C:\Users\AppData\Local\Melvor Idle\
> > And then load up the game
> 
> it didn't exist

The full location is C:\Users\<yourusername>\AppData\Local\Melvor Idle\

Can you double check?

**Comment by Helvenea** [comment]
> > > Delete the contents of the folder C:\Users\AppData\Local\Melvor Idle
> > > And then load up the game
> > 
> > 
> > it didn't exist
> 
> The full location is C:\Users\your_username\AppData\Local\Melvor Idle\
> 
> Can you double check?

found it, do i have to delete all content?

**Comment by Helvenea** [comment]
> > > Delete the contents of the folder C:\Users\AppData\Local\Melvor Idle
> > > And then load up the game
> > 
> > 
> > it didn't exist
> 
> The full location is C:\Users\your_username\AppData\Local\Melvor Idle\
> 
> Can you double check?

it's working now, thanks!~
