### ISSUE TITLE
Fishing treasure chests are back to giving junk

### ISSUE THREAD

**Issue by jbkingjr** [MelvorIdle/melvoridle.github.io#1013]
**Describe the bug**
Fishing treasure chests are back to giving me junk even thought my mastery XP has been maxed for awhile.

**To Reproduce**
1. Ensure level 65 mastery for a fish or 25% for Fishing mastery XP
2. Wait for fishing activities to give you treasure chests
3. Open fishing treasure chests
4. See that junk is awarded

**Expected behavior**
After a certain point of overall mastery XP or certain percentage per fish, junk should stop being rewarded from the fishing treasure chests.

**Screenshots**
See attached

**Browser**
iOS app

**Console output**
iOS app, so no console output

**Are you using any scripts?**
No

**Comment by jbkingjr** [comment]
![B31DFB88-7869-4830-B30E-24B96B86EF7D](https://user-images.githubusercontent.com/7727419/121757388-379e5b80-cad2-11eb-9e1c-bee31f277881.png)
![71E06637-FE98-41EB-B650-4133CC01B192](https://user-images.githubusercontent.com/7727419/121757389-3a00b580-cad2-11eb-9c2f-23546da2d405.png)

**Comment by Fuvias** [comment]
Thats just a thing treasure chests can do indenpently from your stats. Nothing effects the drop rates from treasure chests.

**Comment by MelvorIdle** [comment]
This is intended as per the new change to Fishing. The Mastery bonus has no affect on the contents of the chest.
