### ISSUE TITLE
Burning kills you after respawn #930

### ISSUE THREAD

**Issue by Valericoe** [MelvorIdle/melvoridle.github.io#1014]
I believe this is the same issue as #930.

Dying with the burning debuff kills you upon respawn.

Protect item is disabled upon the first death, so you can lose items on the second. (RIP FeZ #2)

**To Reproduce**
1. First a monster that inflicts burning (e.g. Umbora)
2. Die
3. Die a second time

**Expected behavior**
Disable/pause the fire debuff upon death
Potentially respawn with full health as this would fix most cases

**Screenshots**

**Browser**
Steam v0.20

**Console output**
N/A

**Are you using any scripts?**
No

**Comment by coolrox95** [comment]
Fixed in v0.21. All effects including DOTs are now removed on player death.
