### ISSUE TITLE
Octopus and Pig Mark Synergy doesn't work while offline, but still uses marks

### ISSUE THREAD

**Issue by Sundwalltanner** [MelvorIdle/melvoridle.github.io#1015]
**Describe the bug**
The Synergy between the `Octopus` and `Pig` marks is supposed to:

```
+75% chance to receive an extra Fish as a Cooked version while Fishing.
```

But there's no way it's actually doing that while offline. I'm fairly certain it caps out at like 1 cooked version of that fish. This would be okay if not for the fact that it still eats through all of your marks.

**To Reproduce**
1. Equip `Octopus` and `Pig` Summoning marks at required levels for Synergy
2. Start fishing
3. Go offline
4. Come back online for disappointment

**Expected behavior**
Significantly more cooked versions of the fish I was fishing for.

**Screenshots**

![image](https://user-images.githubusercontent.com/11891490/121770578-42371000-cb27-11eb-9708-a89a04084c46.png)

**Browser**
Chrome Version 91.0.4472.77 (Official Build) (64-bit)

**Console output**
I'm fairly certain there wasn't anything important in here, and am not wasting any additional marks on this.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Hey! A hotfix has just been applied to the game
