### ISSUE TITLE
Crow + Salamander Synergy isn't using charges

### ISSUE THREAD

**Issue by 47Y** [MelvorIdle/melvoridle.github.io#1016]
**Describe the bug**
Since there is no call to check the synergy directly the tablets are not used and therefor no additional XP is given.

**To Reproduce**
1. Equip the Crow and Salamander with synergy unlocked between them.
2. Runecraft or Smith.
3. Gain the preservation benefits without using additional charges for the synergy.

**Expected behavior**
The synergy should be checked and charges should be used if applicable.

**Browser**
Applies to all.

**Are you using any scripts?**
Yes, however none of them affect the functions used.

**Comment by MJ90-sudo** [comment]
I'm having exactly the same issue with crow x salamander synergy
