### ISSUE TITLE
Steam - Mouse Dragging Hard to the Left

### ISSUE THREAD

**Issue by dyll91** [MelvorIdle/melvoridle.github.io#1019]
**Describe the bug**
When I open the game the cursor is dragged hard to the left and I can't drag enough to counteract it

**To Reproduce**

*shrug* 

**Expected behavior**

**Screenshots**
Feel free to DM me back and I can screenshare it?

**Browser**
Please tell us what browser you are using and what version.
Steam, latest version

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

**Comment by MelvorIdle** [comment]
This is due to a controller that is plugged into your computer.
