### ISSUE TITLE
Loading offline progress for WC never finishes loading.

### ISSUE THREAD

**Issue by Supergamed** [MelvorIdle/melvoridle.github.io#1022]
**Describe the bug**
Loading offline progress for WC never finishes loading.

**To Reproduce**
1. Go to Melvoridle.com
2. Click on Current character, I actually have the text file for the save that's messed up. 
4. See error, character will never load in.

**Expected behavior**
I was hoping to actually be able to train combat, and possibly get the defence familiar.

**Screenshots**

![Bug Report](https://user-images.githubusercontent.com/15164021/121795854-89360b80-cbe2-11eb-8369-dc70736335d3.png)

**Browser**
Chrome Version 91.0.4472.77 (Official Build) (64-bit)

**Console output**
selectCharacter
save.js?915:71 set force reload to 1
main.js?915:322 selectCharacter
save.js?915:13 Loading Save Game...
save.js?915:29 Save Game Loaded...
main.js?915:20 Game Loaded
main.js?915:118 (2) [0, 0]
woodcutting.js?915:2 Uncaught TypeError: Cannot read property 'interval' of undefined
    at getBaseWoodcuttingInterval (woodcutting.js?915:2)
    at main.js?915:118
getBaseWoodcuttingInterval @ woodcutting.js?915:2
(anonymous) @ main.js?915:118
setTimeout (async)
updateOffline @ main.js?915:118
finaliseLoad @ main.js?915:333
selectCharacter @ main.js?915:322
onloadEvent @ save.js?915:74
(anonymous) @ save.js?915:77
(anonymous) @ oneui.core.min.js:6
each @ oneui.core.min.js:6
each @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
r @ oneui.core.min.js:6
fireWith @ oneui.core.min.js:6
c @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
load (async)
send @ oneui.core.min.js:6
ajax @ oneui.core.min.js:6
C.fn.load @ oneui.core.min.js:6
resetEntirePage @ save.js?915:77
setForceReload @ save.js?915:71
selectCharacter @ main.js?915:322
onclick @ (index):1
2DevTools failed to load source map: Could not load content for chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/chrome/iframe_handler.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
main.js?915:256 true
woodcutting.js?915:7 Uncaught TypeError: Cannot read property 'level' of undefined
    at cutTree (woodcutting.js?915:7)
    at pauseOfflineAction (main.js?915:256)
    at save.js?915:75
    at ifvisible.js:5
    at Array.forEach (<anonymous>)
    at Object.t.fire (ifvisible.js:5)
    at e.IfVisible.blur (ifvisible.js:9)
    at HTMLDocument.t (ifvisible.js:9)
**Are you using any scripts?**
No, base game, no scripts, i downloaded a script afterwords, but it didn't help so i immedately uninstalled it.

**Comment by keving452** [comment]
<button type="button" class="swal2-confirm swal2-styled" aria-label="" style="display: inline-block; border-left-color: rgb(48, 133, 214); border-right-color: rgb(48, 133, 214);">OK</button> 
this will have disabled in it just delete the disabled and it will start working i would also suggest catching a fish then refreshing  to fix the wood cutting

**Comment by Supergamed** [comment]
I apologize, i don't fully understand. I attempted to copy the code and apply it in console but kept getting [Uncaught SyntaxError: Unexpected token '<']  Deleting the unexpected token just caused it to error out with something else. I'm not entirely sure what i'm doing wrong as my knowledge of this is extremely limited.

**Comment by keving452** [comment]
your looking for the button logs and it will say its disabled when it is trying to load itself when you find it then it should be like what mine said but with the word disabled inside it you just have to delete the word disabled
