### ISSUE TITLE
Issue with 'Multi-Tree' Passive Skill

### ISSUE THREAD

**Issue by Krapby** [MelvorIdle/melvoridle.github.io#1025]
**Describe the bug**
Since the new update: when selecting 2 different tree types it wont cut the tree's seperate to their time allotment but to the time of the one with the highest value. e.g. Cutting both Mahogany Tree's (3.5 seconds), and Magic Tree's (6.8 seconds). It will then proceed to cut to the Magic Tree's time allotment. Reducing a Mahogany Log recieved by 1 after repeated completions. Since this change, you're losing 1 log every 30 seconds or so. Which over a couple hours is difference between 100-200 logs recieved potentially (as well as both 'skill/mastery EXP' and 'Mastery Points'. Which can potentially equal 100,000 EXP differences).

**To Reproduce**
1. Purchase the Passive Skill 'Multi-Tree' within the shop menu.
2. Proceed to the 'Woodcutting Skill' menu.
3. Click on two different wood variants.

**Expected behavior**
Before the update V0.20 (?923), when using this skill, both trees would be cut seperately, to their own time value.

**Screenshots**
![Melvor Issue](https://user-images.githubusercontent.com/85844889/121818665-e6f25280-cccb-11eb-967d-948aee865e4d.JPG)

**Browser**
Version: V0.20 (?923) Fresh after the recent 'Big Patch'

**Comment by coolrox95** [comment]
This behavior is intended, as per the Changelog for Alpha v0.20.
