### ISSUE TITLE
(increased|decreased)EnemyAccuracy modifiers are not implemented

### ISSUE THREAD

**Issue by gmiclotte** [MelvorIdle/melvoridle.github.io#1026]
**Describe the bug**
Looks like `increasedEnemyAccuracy` and `decreasedEnemyAccuracy` modifiers are not implemented (0.20?926).

`decreasedEnemyAccuracy` is used by synergy 1-12 Occultist-Cyclops, checking in game, I also don't see a change in monster accuracy with/without the synergy equipped.

There are no other uses of these modifiers

This synergy has as modifiers `{summoningSynergy_1_12: 15}`. Could probably set this to `{decreasedEnemyAccuracy: 15}` and get rid of the `summoningSynergy_1_12`, and the same goes for most of `calculateMiscSummoningModifiers`.

**To Reproduce**
1. Equip Occultist-Cyclops
2. Fight something
3. Unequip summons
4. See that enemy acc rating didn't change

**Expected behavior**
`decreasedEnemyAccuracy` decreases enemy accuracy 

**Screenshots**
no

**Browser**
no

**Console output**
no

**Are you using any scripts?**
yes

**Comment by coolrox95** [comment]
These modifiers have been removed, and replaced with enemies having their own modifiers as of v0.21.
