### ISSUE TITLE
Pig + Mole Synergy Always Reports 100 Coal Received While Offline - Regardless of usage

### ISSUE THREAD

**Issue by Luxapodular** [MelvorIdle/melvoridle.github.io#1027]
**Describe the bug**
When using Pig + Mole Synergy, the "Welcome Back" Screen always reports 100 coal ore received, regardless of the number of items cooked.

**To Reproduce**
1. Equip Pig + Mole Synergy
2. Begin Cooking
3. Go offline
4. Return to the game, should receive Welcome Back message with only 100 coal ore.

**Expected behavior**
It should provide a roughly 25% coal ore return (I believe).

**Screenshots**
<img width="361" alt="Screen Shot 2021-06-13 at 4 45 56 PM" src="https://user-images.githubusercontent.com/8699557/121821451-158a1200-cc67-11eb-8a3b-228e2d33d610.png">

**Browser**
Mobile Android, Firefox Mobile, Firefox Mac

**Console output**
N/A

**Are you using any scripts?**
N/A

**Comment by MelvorIdle** [comment]
Thanks, a hotfix is being released today to fix this
