### ISSUE TITLE
Signet Ring does not increase GP earned from Golbin Familiar

### ISSUE THREAD

**Issue by iang2** [MelvorIdle/melvoridle.github.io#1028]
**Describe the bug**
Signet Ring does not increase GP earned from Golbin Familiar.

Golbin Familiar gives 30 GP per hit with or without Ring equipped.

**To Reproduce**
1. Equip Golbin Familiar
2. Attack something, note GP earned.
3. Equip Aorphat's Signet Ring
4. Attack something, note GP earned.

**Expected behavior**
After equipping the Signet Ring the Golbin Familiar should produce 60 GP per hit instead of 30.

**Browser**
Steam

**Are you using any scripts?**
No

**Comment by aaronhealey** [comment]
Can confirm that this is an issue on the web version as well.

**Comment by coolrox95** [comment]
Fixed in update v0.21
