### ISSUE TITLE
[Summoning] ent+octopus synergy using a total of 5 tablets for each fishing action

### ISSUE THREAD

**Issue by dhdco** [MelvorIdle/melvoridle.github.io#1029]
**Describe the bug**
Ent + Octopus synergy uses 5 tablets (2 from ent, 3 from octopus) for each fishing action.

**To Reproduce**
1) Equip "Ent" in summoning slot (1)
2) Equip "Octopus" in summoning slot (2)
3) Start fishing (tested on whale and skeleton fish)
4) Go to equipment page and watch how many tablets are consumed for each action.

**Expected behavior**
Each fishing action consumes 2 Ent tablets and 3 Octopus tablets.

**Screenshots**
N/A

**Browser**
Steam, Firefox

**Console output**
N/A

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Thanks, a hotfix is being released today for this
