### ISSUE TITLE
food drops can't be cooked

### ISSUE THREAD

**Issue by fausing** [MelvorIdle/melvoridle.github.io#103]
**Describe the bug**

**To Reproduce**
1. Go to 'Sandy shores'
2. Click on 'tentacle'
3. Scroll down to 'drop food, and go to cooking and it's not available'

**Expected behavior**
i expected to be able to cook the food, which i wasn't.
**Screenshots**

**Browser**
Please tell us what browser you are using and what version.
Google chrome
**Console output**
Please open the console by pressing F12 and copy it here.

**Comment by MelvorIdle** [comment]
Easy fix. I'll get one out for the next update.

**Comment by MelvorIdle** [comment]
Confirmed fixed in v0.13
