### ISSUE TITLE
When using combination runes, you cannot cast "Wind" spells

### ISSUE THREAD

**Issue by olivertren** [MelvorIdle/melvoridle.github.io#1034]
**Describe the bug**
It appears that you cannot cast any `Wind` spells when you have `Use Combination Runes` selected.

**To Reproduce**
1. Go to combat.
2. Use any wind spell.
3. Select `Use Combination Runes`
4. You will get a pop up that says `You don't have enough combination runes` and the spell won't cast.

**Expected behavior**
I expected that if the spell cost doesn't actually call for any combination runes, it wouldn't try to use combination runes. I expected the spells to cast properly instead of failing.

**Screenshots**
![E670A066-77D7-4D52-9B59-75B1CC449814](https://user-images.githubusercontent.com/16725190/122074417-0cf02380-cdae-11eb-9100-423d872cb322.png)

**Browser**
I was using the Steam local client - but I got the same thing when using Chrome Version 91.0.4472.101 (Official Build) (x86_64)

**Console output**
There was nothing there.

**Are you using any scripts?**
No

**Comment by coolrox95** [comment]
Fixed in update v0.21
