### ISSUE TITLE
Steam - First pet achievement bugged

### ISSUE THREAD

**Issue by joseanjim** [MelvorIdle/melvoridle.github.io#1037]
I got my first pet (Ty) during offline progress and didn't get the Steam achievement... v0.20 Steam
edit: the achievement already jumped up when closing the game and reopening it...

**Comment by kellewic** [comment]
Came to leave the same comment. Can confirm closing the game and re-opening immediately gives achievements "pending". I had "My Little Companion" and "8" that didn't appear until I closed and re-opened the game.

**Comment by MelvorIdle** [comment]
Achievements are awarded when loading a character. Any missing achievements - please reload the character
