### ISSUE TITLE
Leprechaun-Monkey synergy 

### ISSUE THREAD

**Issue by blastedt** [MelvorIdle/melvoridle.github.io#1038]
**Describe the bug**
The Leprechaun-Monkey synergy does not activate.

**To Reproduce**
1. Create and equip Leprechaun and Monkey tablets with enough Mark level to activate the synergy.
2. Thieve from a farmer until you receive an item.

**Expected behavior**
1 monkey tablet and 2 leprechaun tablets are removed from your equipped tablets.  You receive 20x the value of the dropped item in gp.

**Current behavior**
1 leprechaun tablet is removed from your equipped tablets.  You do not receive additional gold while thieving an item. Tree seeds is the easiest way to see this - you should get an 8k gold drop when you thieve an oak tree seed.

**Browser**
Chrome 91
**Console output**
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
main.js?935:265 loadCharacterSelection
main.js?935:321 selectCharacter
save.js?935:71 set force reload to 0
main.js?935:321 selectCharacter
save.js?935:13 Loading Save Game...
save.js?935:29 Save Game Loaded...
main.js?935:20 Game Loaded
main.js?935:118 Array(2)
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
No.

**Comment by Audiowurm** [comment]
Having the same issue. Attempted multiple methods to get it to work, unequipped and re-equipped the tablets, refreshed the browser, and emptied my tablets and then selected the synergy itself from the Synergy page in the Summoning skill.

**Comment by blastedt** [comment]
Resolved in production.
