### ISSUE TITLE
Message/Notification History

### ISSUE THREAD

**Issue by Axemagus** [MelvorIdle/melvoridle.github.io#1039]
Hi, 
Would it be possible to have a tab or panel that contains message history for all of the notifications that pop up at the bottom of the screen?  Perhaps display the last 50 or so?  I looked around and didn't see anything in the game or wiki.

Thanks!

**Comment by kfbest** [comment]
Would love this. So many times I want to see the history of what I did. Mostly because I sorta default to clicking "OK" without reading all of it.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
