### ISSUE TITLE
Stance swapping back to stab too frequently

### ISSUE THREAD

**Issue by Dwake5** [MelvorIdle/melvoridle.github.io#104]
**Describe the bug**
Swapping any piece of gear when using melee, changes the stance to stab.

**To Reproduce**
Use either slash or block and then change a piece of armour. 

**Expected behavior**
I expect my stance to not change when switching non weapon equips

**Screenshots**
Not needed for this bug

**Browser**
Chrome, current version

**Console output**
No console error messages

**Comment by MelvorIdle** [comment]
Will have a fix out next update.

**Comment by MelvorIdle** [comment]
Fixed in v0.13
