### ISSUE TITLE
Infinite loop of misses

### ISSUE THREAD

**Issue by lachiu** [MelvorIdle/melvoridle.github.io#1040]
**Describe the bug**
So I made 10k+ javelins last night. 
I started the chicken coop dungeon.
I died while looking away. Got a pop up "you lost javelin". I got a heart attacking while thinking about losing 10k javelins to a chicken. I checked, lost 1k. However, I didn't see that the javelin was missing in my left hand because of this. so it went on to loop with misses for both sides. Didn't take a single hit, despite my evasion only being 3k. 

I tried to reproduce it to report it, but this time I lost the remaining 8k :(

**To Reproduce**
1. Start any dungeon.
2. Die with x k javelin 
3. Repeat step 1.
3. See error

**Expected behavior**
To still have it in the left hand if sufficient quantity.

**Screenshots**
![image](https://user-images.githubusercontent.com/47612742/122139963-69088580-ce4a-11eb-9bbc-34d625e4a4dd.png)

**Browser**
Steam app, windows 10.

**Console output**
Please open the console by pressing F12 and copy it here.
-> f12 makes a screenshot, doesn't open a console?

**Are you using any scripts?**
Nothing extra.

**Comment by coolrox95** [comment]
Combat has been entirely rewritten as of Alpha v0.21. If you encounter this error again and can consistently reproduce it please submit a new report.
