### ISSUE TITLE
Wicked Greater Dragon Confusion attack damage lower than expected

### ISSUE THREAD

**Issue by thephoenixlodge** [MelvorIdle/melvoridle.github.io#1042]
**Describe the bug**
Damage output from the confusion attack of Wicked Greater Dragons seems to be about 1/3 of what would be expected from the calculation (Player Max hit * 0.75 * (1 - DR%)). With a max hit of 200 (using gust) and DR of 48%, I expected to take 78 damage, but instead only took 26 damage. Similarly with max of hit 540 I only took 70 damage. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Fight Wicked Greater Dragon
2. Be attacked with Confusion
3. Record Damage received
4. Compare to calculation based on max hit and see error

**Expected behaviour**
Damage should be 75% of player max hit reduced 

**Screenshots**

**Browser**
Steam

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
No Scripts

**Comment by coolrox95** [comment]
Fixed as of v0.21
