### ISSUE TITLE
Bank "Sell Item" quantity text box laggy

### ISSUE THREAD

**Issue by kellewic** [MelvorIdle/melvoridle.github.io#1044]
**Describe the bug**
The sell item UI text box that has the item quantity has about a 4 second lag when interacting with it.

**To Reproduce**
1. Click at the end of the number in the text box
2. Press Backspace to erase last number
3. Wait about 4 seconds

**Expected behavior**
Little to no lag

**Screenshots**
![sell_item_textbox](https://user-images.githubusercontent.com/3178267/122227930-353e5780-ce6c-11eb-9c11-0d3429de31bd.jpg)

**Browser**
Steam

**Are you using any scripts?**
No

**Comment by NineRed** [comment]
Do you have a specific version? 
I USED to have this problem on web browser Melvor, but as of the Summoning update this issue seems to have disappeared for me. I'm using Firefox 78.11.0

**Comment by kellewic** [comment]
Current version 0.20, but your comment made me think of something. I closed out the game just now and re-tested and it's fine. Seems to happen over time. Before I closed it just now, it had about a 2 second lag because I closed it earlier this morning and re-opened it so it would recognize some achievements. I tend to just leave it running all day and night.

**Comment by NineRed** [comment]
Could be memory leak related. I'll update if it crops up again.

**Comment by NineRed** [comment]
Hm, this does appear to still be happening.  The sell _slider_ is fine, but the text box causes some serious lag any time its messed with.
There are no console messages associated with this lag spike, so I can't really provide further details.

When the page is reloaded the lag no longer occurs, so I have reason to believe this is indeed memory leak associated.
