### ISSUE TITLE
Non-combat max reached new notifier not being removed upon new max

### ISSUE THREAD

**Issue by Fuvias** [MelvorIdle/melvoridle.github.io#1045]
**Describe the bug**
(For newest update)
In adventure mode when your non-combat level has been reached, for example level 50 and max said non-combat skill to level 50 with your max combat level being 50. And then when you level your combat skill to 51 and then look at said skill that was previously capped at 50, it will still say that said non-combat skill has reached its limit and does not remove the red text. This bug is PURELY visual and if you get 1 exp more it will remove and you will promptly level up however.

**To Reproduce**
Not applicable, read bug description.

**Expected behavior**
Red text saying you have reached the max is expected to be removed once the maximum cap has been raised. This could confuse more novice players potentially.

**Screenshots**
![image](https://user-images.githubusercontent.com/85263051/122228086-21e7b800-ce7d-11eb-9fb0-26378e46156e.png)

**Browser**
https://melvoridle.com/ (Newest version)

**Console output**
Not applicable

**Are you using any scripts?**
No

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
