### ISSUE TITLE
Ice Shortbow Spec

### ISSUE THREAD

**Issue by klankin** [MelvorIdle/melvoridle.github.io#1046]
**Describe the bug**
Ice Shortbow was listed as having a spec change in the patch notes, it does not reflect this in the game.

**To Reproduce**
1. View Ice Shortbow spec

![21a68c5d08f700b575f1159b92ab44a4](https://user-images.githubusercontent.com/17366512/122234305-1320f580-cebd-11eb-90b1-a7b1c7fdf84f.png)
![bc593a4d8f661424f58fcee1134dba5d](https://user-images.githubusercontent.com/17366512/122234320-16b47c80-cebd-11eb-8035-44f3b499a724.png)

**Comment by MelvorIdle** [comment]
I believe the changelog there reflected a change we decided not to add, hence it not being in game. We forgot to remove the note from the changelog
