### ISSUE TITLE
Rune count on runecrafting page loses formatting

### ISSUE THREAD

**Issue by Lanny** [MelvorIdle/melvoridle.github.io#1048]
**Describe the bug**
On the rune crafting page, with a given rune selected, the count of that rune in the bank is initially displayed with commas (e.g. 1,000) but as soon as a rune is crafted and that number goes up, the formatting is lost (e.g. on crafting 16 runes it becomes 1016 rather than 1,016). On leaving the runecrafting skill page and returning it is correct again, until the next rune is crafted.

**To Reproduce**
1. Go to rune crafting
2. Select a rune where more than 1000 are currently in the bank
3. Observe the formatted number under the selected rune icon
4. Craft that rune
5. Observe the number is no longer formatted in the way that it was

**Expected behavior**
After crafting a rune, the formatting should be the same, i.e. include a comma every three digits

**Browser**
Chrome 91

**Are you using any scripts?**
No

**Comment by NineRed** [comment]
Can confirm. Before and after:
![Untitled](https://user-images.githubusercontent.com/20262747/122482032-0b308680-cf8d-11eb-906b-acc669d8b8d2.png)

Firefox 78.11.0

**Comment by coolrox95** [comment]
Issue was resolved with Alpha v0.21.
