### ISSUE TITLE
More tabs in the bank

### ISSUE THREAD

**Issue by orc4n** [MelvorIdle/melvoridle.github.io#1052]
### Adding more tabs in the inventory in order to organize the inventory more easily.

With the addition of another skill, I think it'll make all our inventories look a bit tidier. Right now there are several things stuffed together into the same tab, as there are multiple skills (such as runecrafting, herblore, farming and now summoning) that produce a lot of items that could be categorized nicely into a single tab, but 10 tabs are you not enough IMO.

It could possibly be implemented with some sort of requirement, either by paying for it like bank slots (but maybe with slayer coins?) or some other form of milestone.

**Comment by Blackwolfe5** [comment]
I fully support this. It's been something I've wanted for a long time now. And with new items coming in the thieving/cooking rework, this feels even more needed. 

Every single update I keep hoping for this. It would be a big QoL addition for a lot of people.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
