### ISSUE TITLE
Cloudburst Staff uses runes for every hit during its special.

### ISSUE THREAD

**Issue by Glathnarr** [MelvorIdle/melvoridle.github.io#1053]
**Describe the bug**
Every cast the staff uses runes as if you were casting your currently selected spell for all 10 hits of the special.

**To Reproduce**
1. Start combat with Cloudburst equipped
2. Use any spell
3. Uses runes required 10x during the special 

**Expected behavior**
If the change to Sandstorm rune usage is something to go by, the actual cast of the special should be the only time runes are used.

**Screenshots**
n/a

**Browser**
Any

**Console output**
n/a

**Are you using any scripts?**
Occurs with or without scripts.

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
