### ISSUE TITLE
Chaos Mode: Buff has turned from +31% to +undefined%

### ISSUE THREAD

**Issue by XyroGod** [MelvorIdle/melvoridle.github.io#1054]
**Describe the bug**
I have upgraded my tier 2 gloves in item corruption and got +31% Firemaking Skill XP and +2 Stamina per Agility Obstacle completion. After saving and going to a different character, I returned to find having +undefined% undefined Skill XP instead...

![image](https://user-images.githubusercontent.com/44085092/122449527-3a9fbd00-cfa6-11eb-80aa-e545ca58c245.png)

**To Reproduce**
1. Enter a chaos mode save
2. Corrupt gloves and get +x% on Skill y XP
3. Save to cloud and change character
4. In my case, return 2 hours later and 

**Expected behavior**
The buff stays

**Screenshots**
![image](https://user-images.githubusercontent.com/44085092/122454638-e8619a80-cfab-11eb-9c25-861961aa10c0.png)

**Browser**
I've used the steam version

**Console output**
I cant open the console on steam version :(

**Are you using any scripts?**
No, have never with this save file.

**Comment by coolrox95** [comment]
Chaos mode has been discontinued.
