### ISSUE TITLE
Item's Mouseover Preview Does not show properly

### ISSUE THREAD

**Issue by KS-Wu** [MelvorIdle/melvoridle.github.io#1057]
**Describe the bug**
Item's Mouseover preview does not show properly after being move from initial tab to new tab in Bank menu, or the other way round.
The item preview can be fix by clicking on any menu option at side bar, even the original Bank menu.

**To Reproduce**
1. Go to 'Bank', drag any items on the original tab. 
2. Drag the selected item to any new tab other than the origin.
3. Go to new tab, and mouseover the dropped item

**Expected behavior**
Usually, when you mouseover an item in any tabs, there will be a preview of the item name and selling price.

**Browser**
Steam Version

**Are you using any scripts?**
Nope, I used original version.

**Comment by MelvorIdle** [comment]
Fixes applied to game - Alpha v0.21 (?1119)
