### ISSUE TITLE
Infinite Prayer

### ISSUE THREAD

**Issue by midol123** [MelvorIdle/melvoridle.github.io#1058]
**Describe the bug**
I left my alt magic overnight doing blessed offerings. I have an earth battle staff and 223000 nature runes woke up and it hasn't consumed a single nature rune I'm still at the same I was yesterday, but I now have 30k blessed offerings and 700kish more XP in alt magic. Now that I am logged in it seems to be using my runes, but not when I log out.
**To Reproduce**
1. Go to  alt magic
2. Click on blessed offering
3. Log out
4. Free Magic?

**Expected behavior**
I expected to be down to around 190 runes after running for 10 hours at 36k an hour

**Browser**
Chrome

**Are you using any scripts?**
No scripts

**Comment by BinarySpike** [comment]
I do not experience this.  However, I will try it out tonight as I'm about to make an overnight blessed offering run.

**Comment by BinarySpike** [comment]
Did not reproduce successfully.

Started with 128468 nature runes and a "staff of earth" and began alt magic blessed offering.  Then logged off.
~13 hours later I had 43,220 blessed offering and 85,250 nature runes.

That calculates to ~43k nature runes used and ~43k blessed offerings created.

2 nature runes makes 2 blessed offering for a 1:1 ratio

I'll try an earth battlestaff next.
