### ISSUE TITLE
Numbers misformatted above 1,000

### ISSUE THREAD

**Issue by BinarySpike** [MelvorIdle/melvoridle.github.io#1060]
**Describe the bug**
When you select an item to craft, such as a nature rune, and your current supply is 11,234.  It will display 11,234. (Note the locale specific comma).  If you then begin crafting nature runes, it will then display a number like 11241 (note, no comma).

**To Reproduce**

- Select nature rune.
- Look at amount owned.
- Begin crafting
- Look at amount owned.

**Expected behavior**
Numbers remain consistently formatted

**Browser**
Steam client

**Comment by Lanny** [comment]
Also reproducible on web, same issue as #1048

**Comment by coolrox95** [comment]
Duplicate of #1048
