### ISSUE TITLE
Cyclops / Witch Synergy with Gust

### ISSUE THREAD

**Issue by sylhaern** [MelvorIdle/melvoridle.github.io#1061]
**Describe the bug**
Using Gust on a slayer task with the Cyclops / Witch Synergy equipped and unlocked, I'm only getting slayer coins on the first hit for each spell

**To Reproduce**
20k+ Accuracy
Equip Cyclops / Witch, with synergy unlocked
Cast Gust on slayer task

**Expected behavior**
Expect to get slayer coins for all magic damage done

**Comment by coolrox95** [comment]
Fixed as of v0.21
