### ISSUE TITLE
Golbin + Minotaur Synergy grants FAR too much GP in Adventure mode.

### ISSUE THREAD

**Issue by NineRed** [MelvorIdle/melvoridle.github.io#1064]
**Describe the bug**
In Adventure Mode, the Golbin + Minotaur synergy grants **250%** your melee damage dealt in GP, which is likely far more than intended.
>This may extend to the Golbin + Centaur and Golbin + Witch synergies, but I do not have these unlocked yet to test.

Edit: The Golbin + Witch synergy suffers from the same problem. It's likely this issue affects all three %-damage-as-GP synergies.

**To Reproduce**
1. Be in Adventure Mode.
2. With the synergy unlocked, equip the Golbin + Minotaur synergy.
3. Fight an enemy.
4. Observe that you are granted 2.5x your damage as GP on every hit.

**Expected behavior**
Since Adventure Mode damage numbers are 10x that of Normal Mode, it would be expected that the GP granted would be 1/10 as much in order to compensate, thus giving 2.5% of your melee damage as GP.
The description of the synergy in Adventure Mode should also probably indicate the reduced GP gain due to the increased health/damage numbers (i.e. should say "Grants GP equal to 2.5% of your MELEE damage dealt." in Adventure Mode)

**Screenshots**
![2x](https://user-images.githubusercontent.com/20262747/122627516-2ffc2b00-d06d-11eb-9f0a-8ecaa985a432.png)

**Browser**
Firefox 89.0 64-bit, Melvor (?936)

**Are you using any scripts?**
No.

**Comment by coolrox95** [comment]
Fixed as of v0.21
