### ISSUE TITLE
Passive slot item showing an increase of stats 

### ISSUE THREAD

**Issue by Pepipito** [MelvorIdle/melvoridle.github.io#1068]
The passive item doesn't give stats, as intended, but it's not what the stat page shows.
![unknown](https://user-images.githubusercontent.com/86157296/122659675-9a4ec180-d17a-11eb-83ba-03280f261b8c.png)

**Comment by coolrox95** [comment]
Hotfixed pushed to live game. Alpha v0.21 (?1093)
