### ISSUE TITLE
Can’t open iOS app

### ISSUE THREAD

**Issue by OrangeOtter** [MelvorIdle/melvoridle.github.io#1072]
**Describe the bug**
When trying to open iOS app, I get the melvor loading screen, with the circle around the M, and sometimes for a small fraction of a second, I can see the save files, but then the app closes itself.  Cannot get to open with restart.  Lost weeklong free play and 3 day old adventure game, bc they weren’t backed up to the cloud, but new game is backed up to the cloud and can access via website.

**To Reproduce**
Honestly no idea, but seeing similar errors, It could be changing changing internet connection points, work vs home.  I also tried moving the file originally to my games folder, so maybe it is a pathway error. But reloading app and leaving it where it loads still experiences error.

can confirm with friend that introduced me to game that their iOS version loads correctly, so maybe it is a conflict with another app I have installed, that they do not.

**Expected behavior**
Open the app to see saved files and select a character to load game 

**Screenshots**
If needed, I can clip video, but all I have is the loading screen and then it backs out.

**Browser**
Current iOS version after hot fix patch.

**Console output**
I am new to iPhone and don’t know how

**Are you using any scripts?**
Not to my knowledge, at least nothing that is not already running on iPhone

**Comment by kpwn243** [comment]
I am having the same issue. I am not sure what triggered it. After looking through my phone analytics files I found the crash logs. I have direct messaged you on discord as I'm on my phone and can't upload files here.
