### ISSUE TITLE
Collected a Red Hering in Goblin Raid, now my Game is completly bugged out

### ISSUE THREAD

**Issue by Shioshishio1** [MelvorIdle/melvoridle.github.io#1077]
**Describe the bug**
at Wave 17 my game "paused" nothings happening, my oponnent got 0hp, wave is not continueing i can't leave the raid, 
i can't buy from the shop, i can literaly do nothing, im like hard locked.

**To Reproduce**
1. go to Goblin Raid 
2. After selecting reward " Armor " there was a Red Hering to select, i was like ok? why not
3. Game continued attacking the oponnent but he won't attack me after he is on 0 hp i could do nothing more

**Expected behavior**
idk i wanna continue with my save file and don't wanna delete my hard progress.

**Screenshots**
hard to send screenshots

**Browser**
Please tell us what browser you are using and what version.

**Console output**
Please open the console by pressing F12 and copy it here. <--- can't open the console

**Are you using any scripts?**
No.

**Comment by coolrox95** [comment]
Issue was fixed in Alpha v0.21.
