### ISSUE TITLE
Summons missing in combat have no associated miss message 

### ISSUE THREAD

**Issue by hugglesthemerciless** [MelvorIdle/melvoridle.github.io#1080]
**Describe the bug**
A summon missing an attack does not show a "Miss!" message ingame, there's no feedback at all, the space where damage numbers normally show up is just blank when that happens. Seems to happen every single time a summon misses

**To Reproduce**
1. Have low hit chance and a slow attacking weapon (to avoid clutter) and the damage numbers

**Expected behavior**
I'd expect a "Miss!" message like normal attacks have, instead of nothing

**Screenshots**
https://imgur.com/OSCDJvg
there's just nothing

**Browser**
Steam, melvor alpha v0.20 (?942)

**Console output**
No clue how to do that on steam sorry

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
