### ISSUE TITLE
Summoning Synergy dialog not priroitzing equipped tablets over banked.

### ISSUE THREAD

**Issue by Silberdrachi** [MelvorIdle/melvoridle.github.io#1085]
**Describe the bug**
When you have a tablet equipped and also have some of it in the bank, in the summoning synergy dialog it shows the count of the items in the bank.

**To Reproduce**
1. Equip a number of tablets, while leaving some lower number of them in the bank
2. Open Summoning Synergy dialog 
3. Find a synergy using the same tablet equipped
4. Note that the number does not highlight green, and shows the number of tablets in the bank instead of the ones equipped

**Expected behavior**
Should always prioritize the tablets equipped when showing active and banked tablets.

**Screenshots**
![image](https://user-images.githubusercontent.com/76179203/123498873-81259500-d600-11eb-9de0-b5780e4f0789.png)

**Browser**
All

**Console output**
None

**Are you using any scripts?**
None

**Comment by MelvorIdle** [comment]
This is now fixed as of ?1318
