### ISSUE TITLE
Summoning skill not reflected properly

### ISSUE THREAD

**Issue by RGPhoenix** [MelvorIdle/melvoridle.github.io#1086]
**Describe the bug**
Used Ent Familiar overnight, Summoning skill reflects I have passed level 15 in the "Milestones" tab, but only shows level 3 on the side bar.

**To Reproduce**
Used Summoning skill while AFK woodcutting. Does not reflect on all trackers?

**Expected behavior**
Side tab to properly reflect skill level.

**Screenshots**
![image](https://user-images.githubusercontent.com/86523177/123514593-c201c600-d661-11eb-835e-deb28ea7f887.png)
![image](https://user-images.githubusercontent.com/86523177/123514608-d47bff80-d661-11eb-8a1a-ba3bf4b017c5.png)

**Browser**
Steam Client ALPHA V0.20 (?942)

**Console output**
![image](https://user-images.githubusercontent.com/86523177/123514627-ee1d4700-d661-11eb-866d-f91b956079e6.png)

**Are you using any scripts?**
No.

**DISCORD INFO**
"| Phoenix |#0001" I am in the Discord Server as well. Will be available for more info if needed. Love the game btw <3

**Comment by Erico9002** [comment]
I had this same issue happen to me on receiving level 99 summoning while training it through smithing. Unsure if relevant or not, but one of my familiars ran out of tablets while I was AFK training it. On coming back, I was met with:
![image](https://user-images.githubusercontent.com/57814950/124009657-7aea3c80-d9a3-11eb-86ba-fe7e251658d0.png)
but yet
![image](https://user-images.githubusercontent.com/57814950/124009677-83427780-d9a3-11eb-834c-1b5d4efec4dd.png)
