### ISSUE TITLE
Absurd CPU usage when there is a progress bar on the screen 

### ISSUE THREAD

**Issue by naoliv** [MelvorIdle/melvoridle.github.io#1087]
**Describe the bug**
While we have some running progress bars on screen, the CPU usage is is much bigger than the expected.

**To Reproduce**
1. Go to any combat
2. Open the Skill Progress panel (so we have more progress bars on screen)
3. Start some attack
4. Now that we have multiple progress bars running on screen, take a look at the CPU usage

**Expected behavior**
It should not really eat CPU like this; probably there is some kind of too-much complex (or inefficient) calculation being used to animate the progress bars.

If I let the attack running and I change to another tab (Bank, por example), the CPU usage gets back to a normal state again.

So it's really related with how progress bars are being calculated/drawn on screen.

**Browser**
Steam version

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21

**Comment by naoliv** [comment]
It doesn't seem that it was fully fixed.
With version `1012`, while a combat is active and I am at the Bank tab, I see it using roughly 26% of CPU.
When switching to the Combat tab it jumps to +349% of CPU.
