### ISSUE TITLE
Crow + Bear synergy doesn't function as written

### ISSUE THREAD

**Issue by tmelucci** [MelvorIdle/melvoridle.github.io#1089]
**Describe the bug**
The Crow + Bear synergy states: While the Elemental Potion is active in Runecrafting, grants a chance to get random Combination Runes.  The chance and quantity is equal to that of the Elemental Potion.

To me, this means that when I have Tier 4 Elemental potions active I should have a 50% chance to recieve 8 Elemental Runes and a separate 50% chance to receive 8 Combination Runes.  But I've been watching the game for about an hour and I've only recieved the extra Combination Runes at the same time as getting the extra Elemental Runes.

What I believe is happening is that the game is applying the 50% chance for extra Elemental Runes, and if that hits, then it applies another 50% chance to get extra Combination runes.  
This results in:
50% No extra Runes
25% Extra Elemental Runes
25% Extra Elemental Runes and extra Combination Runes

It's possible this is the intended behavior, but if that is the case I'd argue that the synergy ability should be reworded to something like:
When the Elemental Potion grants random Elemental Runes in Runecrafting, grants a chance to get random Combination Runes.  The chance and quantity is equal to that of the Elemental Potion.

**To Reproduce**
Equip Crow + Bear synergy and farm any Runes (I was farming Ancient Runes if it happens to be a Rune specific issue).

**Expected behavior**
I would expect a breakdown closer to:
25% No extra Runes
25% Extra Elemental Runes
25% Extra Combination Runes
25% Extra Elemental Runes and extra Combination Runes

**Browser**
Chrome

**Are you using any scripts?**
No

**Comment by sylhaern** [comment]
I also got unexpected results from the Crow / Bear synergy - it doesn't appear to give any mud runes at all:  https://i.imgur.com/hErq3xg.png  

In 12 hours idle, so ~25,400 crafts.  Same as you, 50% of crafts giving elemental runes, but only 25% giving combination runes

I also noticed that I got 0 Mud runes.  I'd understand if Steam runes were disabled, since they don't have a use right now, but Mud runes not being given out seems like a bug as well.

**Comment by NineRed** [comment]
Can concur that this bug is still ongoing.
Crafted runes will grant just the target rune, the target rune + elemental rune, or target + elemental + combination.  Combination runes are dependent on an elemental rune drop to have their chance checked, which significantly weakens this synergy.

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
