### ISSUE TITLE
"Rock check" timer creates artificial delay when mining

### ISSUE THREAD

**Issue by iPeer** [MelvorIdle/melvoridle.github.io#109]
**Describe the bug**
**This is not exclusive to Rune Essence, but I will use it as the example as it's most noticeable**: When a Rune Essence mining node is depleted, the game will wait for 5 seconds before starting to mine again, despite Rune Essence respawning after 1 second, creating an artificial delay of 4 seconds.

**To Reproduce**
1. Mine an ore to depletion
2. Note that the time before mining resumes is up to 5 seconds longer than it takes the ore to respawn.

**Expected behavior**
The game automatically starts as soon as the ore respawns.

**Browser**
Chrome; 80.0.3987.122

**Comment by MelvorIdle** [comment]
This is currently an intended addition to the game. I may change it in the near future.
