### ISSUE TITLE
Lemonade is healing for 100 base

### ISSUE THREAD

**Issue by Silberdrachi** [MelvorIdle/melvoridle.github.io#1090]
**Describe the bug**
Lemonade is healing for 100 base

**To Reproduce**
1. Spawn in lemonade
2. Check amount of healing

**Expected behavior**
Heals for 1hp

![image](https://user-images.githubusercontent.com/76179203/123530069-83512780-d6c4-11eb-8c13-67a665cbe0f5.png)

https://wiki.melvoridle.com/w/Lemonade

**Comment by coolrox95** [comment]
Lemonade has been changed back to healing 10 HP.
