### ISSUE TITLE
Jewel of Rhaelyx cannot be obtained from offline Summoning

### ISSUE THREAD

**Issue by Auron956** [MelvorIdle/melvoridle.github.io#1095]
**Describe the bug**
The function `getRhaelyxPiece` does not include Summoning as part of the `gemSkills` array, therefore it is not possible to obtain the Jewel of Rhaelyx from offline Summoning (although _can_ be obtained from online Summoning as the `gemSkills` array is declared as expected within `rollForRhaelyx`).

**Expected behavior**
The jewel should be possible to acquire from both offline & online Summoning.

**Screenshots**
N/A

**Browser**
Issue is browser independent.

**Console output**
N/A

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Hotfixed
