### ISSUE TITLE
Finn, the Cat Typo

### ISSUE THREAD

**Issue by xpanda96** [MelvorIdle/melvoridle.github.io#1097]
In adventure mode there's a type for pet "Fin, the Cat". It should be +100 instead of +10 as it's 10x.
![image](https://user-images.githubusercontent.com/7659410/123824066-a0207180-d8f5-11eb-91b0-580f9e2edc26.png)

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
