### ISSUE TITLE
10% potion doubling from 95% mastery is not shown in cumulative doubling chance for Herblore

### ISSUE THREAD

**Issue by PaulCanada** [MelvorIdle/melvoridle.github.io#1098]
**Describe the bug**
When having 95% mastery for herblore, the 10% potion doubling bonus is not shown in the cumulative doubling chance shown when selecting a potion. As per discord - this is purely visual and the 10% chance is actually added.

**To Reproduce**
1. Get 94% mastery in herblore
2. Take note of doubling chance
3. Get 95% mastery in herblore
4. Doubling chance is the same as in step 2

**Expected behavior**
The doubling rate should be accurately shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/7876595/123859367-8d586d80-d8f2-11eb-84cf-c93dc70e0139.png)

**Browser**
Steam client

**Console output**
N/A

**Are you using any scripts?**
No

**Comment by PieterSar** [comment]
The Mastery exp displayed in the Granted part of that interface seems to be inaccurate as well, I think it's missing the bonus from Firemaking Mastery pool checkpoint bonus similar to the doubling missing it.

**Comment by MelvorIdle** [comment]
Hotfixed has been pushed for this one. Alpha v0.21 (?1093)
