### ISSUE TITLE
Herblore potion only gives 1 potion on activation

### ISSUE THREAD

**Issue by AnthonyGlick** [MelvorIdle/melvoridle.github.io#110]
**Describe the bug**
Herblore potions state 'x% chance to gain a second potion of a random tier', but only gives the random potion.

**To Reproduce**
1. Use a herbalore potion
2. Wait for it to proc
3. See the output of the proc

**Expected behavior**
I expected to get 1 potion of the level I'm crafting at in addition to the random potion.

**Browser**
Firefox 73.0.1 (64-bit)

**Comment by MelvorIdle** [comment]
I removed the "2nd potion" just prior to release, but forgot to change the wording on the potion.

In v0.13, I have reverted this change, so the potion will now provide a 2nd potion as the description states.
