### ISSUE TITLE
Aorpheat's Signet Ring doesn't affect on GP from Golbin Thief summoning tablets.

### ISSUE THREAD

**Issue by AndreevArkady** [MelvorIdle/melvoridle.github.io#1101]
**Describe the bug**
The Aorpheat's Signet Ring does not give bonus GP when using Golbin Thief summoning tablets.

**To Reproduce**

1. Equip the Aorpheat's Signet Ring.
2. Equip the Golbin Thief summoning tablets.
3. Go to any monster location.
4. Hit an enemy.
5. Get +30 GP on that successful Enemy Hit. (It is the effect of Golbin Thief summoning tablet)

**Expected behavior**
The ring description says +100% GP from all sources excluding Alt. Magic and Item Selling.
Was expecting to receive +60 GP instead of +30 GP.

**Screenshots**

**Browser**
Firefox browser 89.0.2

**Console output**

**Are you using any scripts?**
No

**P.S.**
Maybe the ring also doesn't affect the other summoning tablets that give GP. Haven't unlocked them, couldn't test it.

**Comment by coolrox95** [comment]
Fixed as of update v0.21.
