### ISSUE TITLE
Crafting is currently using combat doubling chance.

### ISSUE THREAD

**Issue by Glathnarr** [MelvorIdle/melvoridle.github.io#1103]
**Describe the bug**
Crafting is currently sending `isCombat=true` to `calculateChanceToDouble()` for the actual crafting. The displayed value in the UI is calculated correctly. Since signet is currently implemented to have -5% for combat and +10% for global doubling, crafting is only receiving the -5% and being unaffected by global doubling since the above function has an if-else for combat-global.

**To Reproduce**
Perform any crafting, the amount crafted is always lower than expected.

**Expected behavior**
This line should have `false` as its second parameter.
```js
let chanceToDouble = calculateChanceToDouble(CONSTANTS.skill.Crafting, true, 0, items[item].masteryID[1], item, true, craftInterval);
```

**Screenshots**
n/a

**Browser**
Occurs on any.

**Console output**
n/a

**Are you using any scripts?**
n/a

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
