### ISSUE TITLE
Monkey + Pig synergy doesn't work when the craft gets doubled and/or preserved

### ISSUE THREAD

**Issue by PieterSar** [MelvorIdle/melvoridle.github.io#1109]
**Describe the bug**

With Monkey + Pig equipped and the synergy active and working properly when 1 item is crafted and no resources preserved, whenever the craft gets doubled or preserved or both the synergy doesn't proc, this might be intended to not proc when it is being preserved because the -1 hide cost per item cannot take the cost below 1 hide and 0 - 1 = -1 < 1 however when it is only being doubled there is no reason i can think of why it shouldn't work.

**To Reproduce**
1. Go to Crafting with Monkey + Pig tablets equipped
2. Click on 'Red Dragonhide Body' and press craft
3. Whenever it is doubled (and/or preserved) you will see that only 1 monkey tablet is being used and thus only summoning exp for said tablet as well.

**Expected behavior**
With Monkey + Pig equipped whenever the craft is doubled i expect the synergy to proc.
Whenever the craft is being preserved the synergy might still be intended to proc, not sure on this.

**Screenshots**
N/A

**Browser**
Steam Client

**Console output**
N/A

**Are you using any scripts?**
None, i haven't even gotten access to console on the steam client

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
