### ISSUE TITLE
Names of items in their labels in the Bank.

### ISSUE THREAD

**Issue by radoslawkalamon** [MelvorIdle/melvoridle.github.io#1110]
**Describe the bug**
After update to Alpha v0.20 Build 953 items in the Bank have their name in labels. See screenshot below. After selling a one item from a item type (like a 1 log from 2k logs), labels returns to its correct form.

**To Reproduce**
1. Open Game.
2. Go to 'Bank'.

**Expected behavior**
Items should have only quantity in their labels.

**Screenshots**
![image](https://user-images.githubusercontent.com/16870210/124367270-012da980-dc56-11eb-91c0-e2df070c89e3.png)

**Browser**
Microsoft Edge 91.0.864.64
Android App 0.03.8

**Console output**
Please see screenshot above.

**Are you using any scripts?**
No

**Comment by radoslawkalamon** [comment]
Disabling "Minor accessibility Features" resolved my problem, but should it look like this when this feature is enabled?

**Comment by coolrox95** [comment]
Displaying the item names like this allows screen-readers to interact with the bank.
