### ISSUE TITLE
offline variable has null values for Fletching when using Experimental Setting for offline progress

### ISSUE THREAD

**Issue by Sundwalltanner** [MelvorIdle/melvoridle.github.io#1111]
**Describe the bug**
I'm AFK fletching `Yew Longbow (u)` in a Chrome tab, and while tabbed out for probably less than a minute, it swapped to offline due to this experimental feature being enabled:

![image](https://user-images.githubusercontent.com/11891490/124367597-dfaccd80-dc15-11eb-8828-d82a2cfc72fc.png)

And when I tabbed back in, I was greeted with this message in place of the one that would normally summarize what happened while I was offline:

![image](https://user-images.githubusercontent.com/11891490/124367613-07039a80-dc16-11eb-8aa5-2e1375bd7a9f.png)

Also, this instance of Melvor Idle appears to be bugged now, as navigating to another tab and then navigating back to the one containing Melvor Idle doesn't appear to be putting it into an `Offline` state like it should be with that experimental feature enabled. I could only fix this by closing that tab and opening a new one for Melvor Idle. I have yet to see the error message again, but offline progress appears to be working.

**To Reproduce**
I have absolutely no idea. I've never seen this before.

**Expected behavior**
I expected the message to inform me of what happened while I was offline, but instead it was an error message.

**Screenshots**
All the screenshots are in the `Describe the bug` section.

**Browser**
Google Chrome Version 91.0.4472.124 (Official Build) (64-bit)

**Console output**
I was unable to get this. Whoops.

**Are you using any scripts?**
Nope.

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
