### ISSUE TITLE
Synergy Bug

### ISSUE THREAD

**Issue by VyrilWasTaken** [MelvorIdle/melvoridle.github.io#1118]
**Describe the bug**
None or barely any summoning charges are used up during offline progression for this specific synergy (pig and salamander). This happens consistently as well, but they function properly on their own.

**To Reproduce**
Steps to reproduce the behaviour:
1. Equipping the pig and salamander familiars.  
2. Start smiting before saving and closing the game.
3. Opening the game and seeing the offline progression pop up. 
4. It shows that next to no summoning charges were used up for one or both of the familiars. (Mostly seems to affect the pig familiar.)

**Expected behaviour**
That more summoning charges would be used up based on the time that has passed.

**Screenshots**
Before offline progression
![before](https://user-images.githubusercontent.com/87042472/124678178-e8bdc900-deb9-11eb-9362-545a07f6b4e3.png)

After 2 hours of offline progression
![After](https://user-images.githubusercontent.com/87042472/124678193-f1160400-deb9-11eb-8e15-d769c3a2f881.png)
![After2](https://user-images.githubusercontent.com/87042472/124678223-fd01c600-deb9-11eb-99a7-ee3241e20a9e.png)

**Browser**
Google Chrome

**Console output**
![Screenshot_3](https://user-images.githubusercontent.com/87042472/124678507-8e713800-deba-11eb-9001-9b3a5ef48e16.png)

**Are you using any scripts?**
Nope

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
