### ISSUE TITLE
Double clicking loot will give both the clicked loot and the loot to the right without removing the right side loot allowing infinite duplication.

### ISSUE THREAD

**Issue by DragonHeart000** [MelvorIdle/melvoridle.github.io#1119]
**Describe the bug**
Double-clicking loot will give both the clicked loot and the loot to the right without removing it allowing infinite duplication.

**Note**
Some hardware seems incapable of clicking fast enough to do this. My laptop has 100% repro rate, however, my partner's laptop and my PC are unable to repro this on their respective hardware. If it can not be reproed due to hardware then a script that double clicks faster for you can be used for 100% repro rate.

**To Reproduce**
1. Open the latest live version of Melvor Idle in the steam client.
2. Enter the combat area and start fighting any enemy.
3. After obtaining at least two things in the dropped loot double click one that has more loot to the right.
4. Notice that you will see the gained loot of the item you double-clicked and the item to the right, however, the item to the right will remain there allowing you to duplicate rare drops.

**Expected behavior**
Both looted items to be removed from the loot to collect section when looted preventing duplication.

**Media**
[VID_duplicating_maple_tree_seeds_drop](https://www.youtube.com/watch?v=dRtXT6YfOnc)

![IMG_duplicate_maple_tree_seeds](https://user-images.githubusercontent.com/31231968/124692223-c9677180-dea2-11eb-8715-5ec9d4059e24.jpg)

**Browser**
Steam version

**Are you using any scripts?**
Just a script to double click with a 0ms delay between clicks. This is not required on all hardware.

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
