### ISSUE TITLE
Odd level up pop-ups

### ISSUE THREAD

**Issue by Cinomed** [MelvorIdle/melvoridle.github.io#112]
**Describe the bug**
When a mastery levels up, another level up pop up occurs right before the last craft before a level up. For example, willow shortbow is lvl 11. I craft until it is 2 shortbows away from 12. On the next shortbow I get the level 11 pop up. When I craft one more it levels up and I get the level 12 pop up like normal. 

**To Reproduce**
I don't know where "..." is sorry

**Expected behavior**
The pop up should not happen

**Screenshots**
Notice the mastery bar is almost full here:
![Screen Shot 2020-03-04 at 12 40 29 PM](https://user-images.githubusercontent.com/11525400/75906927-75afc880-5e15-11ea-9970-32cb0e0ef5ea.png)

Notice the level 11 pop up occurring right before mastery level up:
![Screen Shot 2020-03-04 at 12 40 31 PM](https://user-images.githubusercontent.com/11525400/75907211-ef47b680-5e15-11ea-8c9b-984248782df9.png)

**Browser**
Chrome version 80.0.3987.132 (latest build)

**Console output**
A cookie associated with a cross-site resource at http://google.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
index.php:1 A cookie associated with a cross-site resource at https://google.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
save.js?200:45 Loading Save Game...
save.js?200:212 Save Game Loaded...
save.js?200:45 Loading Save Game...
save.js?200:212 Save Game Loaded...
mastery.js?200:200 Updating Masteries
mastery.js?200:36 Loading Masteries...
smithing2.js?200:217 Loading Smithing...
main.js?203:1022 Game Loaded
cloud.js?203:50 Melvor Cloud Connection: Success
save.js?200:45 Loading Save Game...
save.js?200:212 Save Game Loaded...
index.php:1 A cookie associated with a cross-site resource at http://googlesyndication.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
cloud.js?203:167 Cloud synced

**Comment by MelvorIdle** [comment]
I'll look into fixing this for v0.13.1
