### ISSUE TITLE
Firemaking Interval

### ISSUE THREAD

**Issue by igniteice** [MelvorIdle/melvoridle.github.io#1123]
**Describe the bug**
In game my burn time is listed as 7.37 seconds for Magic Logs. However, calculating the time should give me 7.34 seconds.

**To Reproduce**
1. Go to Firemaking
2. Click on Magic Logs
3. Scroll down to Interval to Burn Logs
4. See time to burn vs calculations.

**Expected behavior**
I have a base burn time of 10 seconds for Magic Logs. I have the following bonuses: 25% Mastery (10%), Devil tablet (5%), and Monkey Bars Agility Course (4%). My Magic Logs are mastery level 76. Using this formula:

10x(1-(0.076)-(0.1+0.04+0.05)) I get 7.34, but in game I have 7.37.

**Screenshots**
![image](https://user-images.githubusercontent.com/82608055/124995782-81189280-e00d-11eb-81d4-f81d554490aa.png)
![image](https://user-images.githubusercontent.com/82608055/124995711-5c241f80-e00d-11eb-83da-0f7e612d0f7d.png)
![image](https://user-images.githubusercontent.com/82608055/124995726-6514f100-e00d-11eb-9e03-c5fbb7960f6f.png)

**Browser**
Steam

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
No

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
