### ISSUE TITLE
Slayer Platebody (Elite) not giving correct bonuses in modifier system.

### ISSUE THREAD

**Issue by Silverfyree** [MelvorIdle/melvoridle.github.io#1125]
Slayer Platebody (Elite) only giving 15% bonus exp to slayer and not the full 30% it is supposed to give.

https://wiki.melvoridle.com/w/Slayer_Platebody_(Elite)

![image](https://user-images.githubusercontent.com/77082862/125018570-f638a600-e0a7-11eb-8a8a-12e0b4670562.png)

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
