### ISSUE TITLE
Mining Offline Progression Stunted

### ISSUE THREAD

**Issue by GreyXephos** [MelvorIdle/melvoridle.github.io#1126]
**Describe the bug**
On my Adventure mode character, offline mining only produces 38% of what it should.
In 30 minutes of offline mining, I expect to produce at least 847 ore based on my rock HP and action time.
(30*60) / (83 * 1.8 + 27) * 83 = 847. However, in the screenshot I only produced 329 while my Standard mode character produced the expected amount.
The issue exists on Steam and browser, as well as mobile if I go back to character selection before closing the app.
If I start mining on mobile and run the app in the background without going to character select, it produces as expected.

**To Reproduce**
1. Start mining
2. Close app/tab
3. Load save after whatever amount of time
4. See offline mining produced 62% less than it should

**Expected behavior**
I expected to receive more items during offline mining based on my calculations.

**Screenshots**
![image](https://user-images.githubusercontent.com/40639858/125043690-34fb3b80-e069-11eb-9ee4-1e7b48825144.png)

**Browser**
Mozilla Firefox v89.0.2

**Console output**
Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-129674422-1”. index.php:6:1
Loading failed for the <script> with source “https://ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js”. index.php:24:1
Loading failed for the <script> with source “https://static.cloudflareinsights.com/beacon.min.js”. index.php:491:1
loadCharacterSelection main.js:262:594
Connected to PlayFab successfully cloud.js:76:144
set force reload to 1 save.js:71:60
Loading Save Game... save.js:13:9
Save Game Loaded... save.js:29:95
Game Loaded main.js:20:405
Array [ 0, 0 ]
main.js:118:817
Loading failed for the <script> with source “https://static.cloudflareinsights.com/beacon.min.js”. update_v020.html:928:1
Synchronising with Cloud cloud.js:8:154
Loading failed for the <script> with source “https://static.cloudflareinsights.com/beacon.min.js”. index.html:565:1
Connected to PlayFab successfully

**Are you using any scripts?**
No

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
