### ISSUE TITLE
Thieving restoration on browser tab change

### ISSUE THREAD

**Issue by Zaflis** [MelvorIdle/melvoridle.github.io#1130]
**Describe the bug**
When you return to MelvorIdle window and last thing you were doing was thieving:
1) You get notified that 0 xp was given. (This is not actually true, i checked how much XP i had before and after minimizing)
2) Thieving stops.

**To Reproduce**
1. Start thieving
2. Minimize browser (Google Chrome)
3. Wait 10+ seconds
4. Restore browser

**Expected behavior**
Expect actual XP gain to be shown and continue thieving.

**Browser**
Google Chrome.

**Console output**
Please open the console by pressing F12 and copy it here.
?

**Are you using any scripts?**
SEMI v0.6.4 but none of its options are enabled.

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
