### ISSUE TITLE
Golbin Raid removes Agility bank increase, can't equip new items if all bank slots are filled

### ISSUE THREAD

**Issue by fradigit** [MelvorIdle/melvoridle.github.io#1132]
**Describe the bug**
I have the Agility Pillar of Generosity on my hardcore character (giving +10 bank space), and no free bank spaces. I attempted to do Golbin Raid, and it would not let me equip new weapons or armor after defeating a wave. I sold an items so my inventory was 111/112 and reattempted Golbin Raid, but encountered the same issue. I noticed at that point that my inventory was 111/102. This makes Golbin Raid virtually unplayable on a hardcore character with Pillar of Generosity, as I would have to get rid of 10 items to play it. 

**To Reproduce**
1. Play a hardcore character with Agility Pillar of Generosity and a full bank
2. Attempt to select a weapon or armor after defeating a wave in Golbin Raid

**Expected behavior**
I would not expect to need any open bank space to play Golbin Raid. I would also not expect to lose buffs from Agility that are not combat-focused.

**Screenshots**
![image](https://user-images.githubusercontent.com/76832865/125184595-e918d580-e1d3-11eb-98a9-2e834828cad5.png)
![image](https://user-images.githubusercontent.com/76832865/125184596-efa74d00-e1d3-11eb-966e-0e708ddf335a.png)

**Browser**
Steam - Alpha V0.20 (?960)

**Console output**
This does not work on Steam

**Are you using any scripts?**
No

**Comment by coolrox95** [comment]
Golbin raid no longer checks for bank space to equip items as of v0.21
