### ISSUE TITLE
Leprechaun-Devil synergy

### ISSUE THREAD

**Issue by rudymeow** [MelvorIdle/melvoridle.github.io#1133]
**Describe the bug**
Leprechaun-Devil synergy doesn't give 4x items at farmer

**To Reproduce**

1. Go to Thieving tab
2. Click on farmer
3. Click on Summoning Synergy Search Tab
4. Click Leprechaun-Devil to equip both tablet
5. Look at the item-received pop up, no 4x item received over hundreds success, tablet consume and the +100% GP effect seems normal for synergy.

**Expected behavior**
At least few 4x items received over few dozen of success, close to 35% if sample size is big enough.

**Screenshots**
![20210712090722_1](https://user-images.githubusercontent.com/36542904/125216379-9da81980-e2f0-11eb-92e3-3eee5c797b4b.jpg)

**Browser**
Steam version

**Console output**
How do we get the Console output from Steam version?

**Are you using any scripts?**
No, vanilla steam client.

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
