### ISSUE TITLE
Suggestion: Add a "Set Tab Icon" button in the bank UI. Clicking it will pull up all unlocked skill/item/monster icons (basically a combined 'completion log' minus the ?'s). Clicking an icon will highlight it and toggle that icon as the tab's default, regardless of which item is in the first slot.

### ISSUE THREAD

**Issue by Haltus-Kain** [MelvorIdle/melvoridle.github.io#1134]
![Icon](https://user-images.githubusercontent.com/87287845/125218003-94369700-e287-11eb-9c09-9a687d8c5e00.png)

Keeping a dedicated icon-item in the first slot is the current closest option; but the item that has the best looking icon may not be one that's actually useful - i.e., if you want standard looking gear for weapons and armor tabs, you might shoot for Steel Sword and Steel Shield; but steel becomes obsolete fairly early so you'd be using an inventory slot just for its icon, which is kind of a waste; and the opposite issue, the icon you want might be from an item you want to actively use, so you'd have to be careful not to let it fall below zero, or if its a piece of gear, you'd have to farm multiple pieces just to have one collect dust in the first slot (and who wants to farm an extra Ancient Sword just because it has a pretty icon? :P).

Another facet of this suggestion is that by tying it into the icons unlocked by the completion log, you'd be able to use icons not associated with items. I.E., the Woodcutting or Farming icon would be a great option for all-things-plants; as would the level 1 "Plant" mob from the Farmlands, or even the "Farmlands" icon itself! "Rune Knight" would be great for your melee gear; Frozen Archer for ranged; one of the Wizards for Magic.

Hell, the Seagull would be a great option for a vendor trash tab, since seagulls are known for digging through trash. :P

This QoL improvement would focus on not tying up inventory space with items you don't intend to use / losing your icon because you did use something; and if opens up a lot of options for icon selection that items alone can't offer.

If you guys follow the Melvor subreddit, I've got a thread rolling there on this topic as well:

https://www.reddit.com/r/MelvorIdle/comments/ofgfmc/suggestion_add_a_set_tab_icon_button_in_the_bank/

**Comment by Blackwolfe5** [comment]
I fully agree, together with having more bank tabs available this would be great!

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
