### ISSUE TITLE
Crash in splash screen on iPhone 12 Pro

### ISSUE THREAD

**Issue by daria-mianne** [MelvorIdle/melvoridle.github.io#1136]
I just downloaded the game on my phone (iPhone 12 Pro) but am completely unable to open the app. The game shows a short splash screen  - maybe half a second -  before crashing. The issue reproduced on 100% of attempts - approx 15 attempts made on first install and another 15 after a delete&reinstall.

The splash screen crashes quickly enough that the popup asking to allow notifications appears after the game has already crashed. It occurs regardless of whether this permission is given or not.

**Comment by daria-mianne** [comment]
Forgot to mention in the report: I’m running iOS 14.6

**Comment by InfinityBMX** [comment]
This happens fairly often for me. It crashes too fast to see anything useful. I usually fix it by turning on airplane mode and turning off wifi. When the save screen says "No connection to internet" I turn everything back on and it loads fine.

**Comment by joeality** [comment]
I have this same issue

**Comment by joeality** [comment]
> 
> 
> This happens fairly often for me. It crashes too fast to see anything useful. I usually fix it by turning on airplane mode and turning off wifi. When the save screen says "No connection to internet" I turn everything back on and it loads fine.

This fix worked for me
