### ISSUE TITLE
Max / Comp Capes give +100 HP regen, vs +10 from HP Skillcape

### ISSUE THREAD

**Issue by sylhaern** [MelvorIdle/melvoridle.github.io#1138]
**Describe the bug**
Previously, the increasedHPRegenFlat for the HP Skillcape was fixed from being 10 to 1, correcting the hp regen per interval from +100 to +10.  This change wasn't made to the Max Skillcape or the Cape of Completion, so they both still give +100 hp regen per interval.

This also interacts with the Unicorn / Goblin Thief synergy, giving a marginal max of ~15m gp per hour vs the ~7m that it should give

**To Fix**
Change `increasedHPRegenFlat: 10,` to `increasedHPRegenFlat: 1,` for the Max Skillcape and Cape of Completion

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
