### ISSUE TITLE
offline progress bug

### ISSUE THREAD

**Issue by levgre** [MelvorIdle/melvoridle.github.io#1139]
**Describe the bug**
was doing alt magic offline and got the bug in the screenshot below

**Screenshots**
![image](https://user-images.githubusercontent.com/14255060/126045250-9d3dc99d-ce35-4e21-bd4a-911c4f2a9066.png)

**Browser**
Firefox 90.0

**Are you using any scripts?**
Combat Simulator Reloaded
Melvor Completion Log Helper

**Comment by levgre** [comment]
Okay so this only happened when my pc had been on sleep, with the Melvor character selection screen opened, and then I woke my pc and tried to select my character. 

Once I refreshed and tried loading my  character again, I had no errors and it fully gave me my offline progress.

**Comment by MelvorIdle** [comment]
Changes have been made to address this over the last few months. Please open a new bug report if issue persists.
