### ISSUE TITLE
Green Dragon Artwork

### ISSUE THREAD

**Issue by CDestr0yer** [MelvorIdle/melvoridle.github.io#1140]
I was looking through the monsters and noticed that the green dragon was missing a front leg resulting in 3 legs but the rest have all 4. Something small but I figured you would like to know. Unless this is intentional.
![4A557AB8-F2BF-4404-9647-352D71BB2641](https://user-images.githubusercontent.com/65835562/126056822-c2904c80-e070-41b0-a935-af9a52faae10.png)

**Comment by MelvorIdle** [comment]
He's a special green dragon
