### ISSUE TITLE
Offline Woodcutting doesn't Account for Double Log Chance

### ISSUE THREAD

**Issue by ryan-sit** [MelvorIdle/melvoridle.github.io#1142]
**Describe the bug**
When doing woodcutting offline, bonuses for double logs (e.g. item mastery) don't apply.

**To Reproduce**
1. Start woodcutting.
2. Go offline.
3. Wait a while.
4. Come back and observe the number of logs does not reflect log doubling chance from mastery.

**Expected behavior**
Double log bonuses, such as those from mastery, should apply when offline.

**Screenshots**
See https://imgur.com/a/o5BVx3t. The number of redwood logs harvested and potion charges is the same, despite me having max item and woodcutting mastery.

The source of the bug looks obvious. doubleLogChance is initialized to 0.0 but never updated to the actual chance before being used: https://imgur.com/a/3ZoNB6r.

**Browser**
Chrome Version 91.0.4472.114 (Official Build) (x86_64)

**Console output**
www.googletagmanager.com/gtag/js?id=UA-129674422-1:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
main.js?964:formatted:3682 loadCharacterSelection
cloud.js?964:76 Connected to PlayFab successfully
main.js?964:formatted:3964 selectCharacter
save.js?964:71 set force reload to 0
main.js?964:formatted:3964 selectCharacter
save.js?964:13 Loading Save Game...
save.js?964:29 Save Game Loaded...
main.js?964:formatted:475 Game Loaded
main.js?964:formatted:1594 Array(2)
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloud.js?964:8 Synchronising with Cloud
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloud.js?964:76 Connected to PlayFab successfully
main.js?964:formatted:3392 true
main.js?964:formatted:1594 Array(2)0: 01: 0length: 2__proto__: Array(0)
main.js?964:formatted:3392 true
main.js?964:formatted:1594 Array(2)
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
No scripts.

**Comment by ryan-sit** [comment]
This got fixed in the latest patch.

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
