### ISSUE TITLE
Herbs in bank while doing golbin raid

### ISSUE THREAD

**Issue by Ripjack** [MelvorIdle/melvoridle.github.io#1144]
**Describe the bug**
The numbers of herb in bank is zero while in golbin raid, even though i do have them.

**To Reproduce**
1. Go to 'farming while in a golbin raid
2. Click on 'plant a herb, select a seed
3. Scroll down to 'you have zero ... Herb in bank
4. See error: herbs in bank is 0 even if you have herbs in bank.

**Expected behavior**
Seeing the actual number of herbs in bank

**Screenshots**
![Screenshot_2021-07-21-13-37-29-302_com malcs melvoridle](https://user-images.githubusercontent.com/87760780/126482746-8739742f-532f-457f-b994-726d8588dfa2.jpg)

**Browser**
Mobile version

**Console output**
Mobile version

**Are you using any scripts?**
No

**Comment by skylarkblue1** [comment]
This also happens on the steam version

![Melvor_Idle_2021-11-09_10-34-47](https://user-images.githubusercontent.com/15182062/140908966-3b92fbcc-88a7-43eb-8dd6-d9f6f0971f00.png)
![Melvor_Idle_2021-11-09_10-36-56](https://user-images.githubusercontent.com/15182062/140909004-733b802f-cb03-47b2-8f40-c8222463d320.png)

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
