### ISSUE TITLE
Priest hat increases prayer cost by 1 and not reduce it by 1.

### ISSUE THREAD

**Issue by Oliverxll** [MelvorIdle/melvoridle.github.io#1145]
**Describe the bug**
Priest hat increases prayer cost by 1 and not reduce it by 1.

**To Reproduce**

Just put it on and use prayer

**Browser**
Chrome

**Are you using any scripts?**
No

**Comment by Oliverxll** [comment]
I completely forgot about agility courses

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
