### ISSUE TITLE
No comma notation on runecrafting screen

### ISSUE THREAD

**Issue by radoslawkalamon** [MelvorIdle/melvoridle.github.io#1149]
**To Reproduce**
1. Have at least 1000 Mind Runes in the bank. 
2. Go to the Runecrafting.
3. Go to the Mind Rune crafting screen. 
4. See the rune amount (with comma) 
5. Click on the Create. 
6. Wait till the end of the rune creation process.
7. See error - amount without comma. 

**Expected behavior**
Amount should always be comma separated. 

**Screenshots**
Before
![Screenshot_20210724-155838_9737de6f3e36012ce6703231c8d3c3a2.jpg](https://user-images.githubusercontent.com/16870210/126871037-866cb97f-10c6-4597-ada0-0a983182b955.jpg)

After
![Screenshot_20210724-155844_9737de6f3e36012ce6703231c8d3c3a2.jpg](https://user-images.githubusercontent.com/16870210/126871039-c94f1a13-47ce-43ec-afa5-f5d1778816f9.jpg)

**Browser**
Melvor Idle on Android Alpha v0.20 build 966

**Console output**
Not possible :(

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
