### ISSUE TITLE
Gold still shows 3'000k even though i have the 1m setting selected.

### ISSUE THREAD

**Issue by Trippledot** [MelvorIdle/melvoridle.github.io#115]
Gold still shows 3'000k even though i have the 1m setting selected.
Have selected the setting and refreshed multiple times, have tried the "fix save" option to see if that fixed it or not.

![image](https://user-images.githubusercontent.com/61903107/76140714-41980a00-6098-11ea-9a58-28dca13b1874.png)
![image](https://user-images.githubusercontent.com/61903107/76140720-4bba0880-6098-11ea-8c21-4c98481cb80a.png)
![image](https://user-images.githubusercontent.com/61903107/76140736-6c825e00-6098-11ea-9080-c14e0241d039.png)

Bank worth has the expected behaviour
![image](https://user-images.githubusercontent.com/61903107/76140800-f3373b00-6098-11ea-84ca-6155e7ada01b.png)

Chrome Version 80.0.3987.122 (Official Build) (64-bit)

```
8A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.
save.js?225:44 Loading Save Game...
save.js?225:206 Save Game Loaded...
save.js?225:44 Loading Save Game...
save.js?225:206 Save Game Loaded...
mastery.js?203:156 Updating Masteries
mastery.js?203:23 Loading Masteries...
smithing2.js?205:185 Loading Smithing...
main.js?237:990 Game Loaded
cloud.js?209:45 Melvor Cloud Connection: Success
save.js?225:44 Loading Save Game...
save.js?225:206 Save Game Loaded...
save.js?225:44 Loading Save Game...
save.js?225:206 

```

**Comment by MelvorIdle** [comment]
Hotfixed.
