### ISSUE TITLE
Visual bug: Ranged Strength calculated twice if Throwing Knives/Javelins equipped.

### ISSUE THREAD

**Issue by Rekkone** [MelvorIdle/melvoridle.github.io#1153]
**Describe the bug**
When Throwing Knives/Javelins are equipped, "View equipment stats" menu shows "Strength Bonus" as if they calculated twice from both Weapon slot and Ammo slot, while "Max Hit" stat shows that it's calculated only once.
For example: 
Mithril Throwing Knives have "+23 Ranged Strength" stat. Equipment stats menu shows "Strength Bonus: 46", twice of that.
At skill level "Ranged 39" and "Strength Bonus: 46" supposed Max Hit is 87.5, according to the [formula from wiki](https://wiki.melvoridle.com/index.php?title=Combat). While in reality, game calculates "Max Hit" as 68, which is closer to what would be if we had "Strength Bonus: 23".

**To Reproduce**
1. Equip Throwing Knives/Javelins.
2. Check "Strength Bonus" in "View equipment stats" menu.
3. Calculate "Max Hit" based on that.
4. Compare to the "Max Hit" value in game.
5. Notice the difference.

**Expected behavior**
Strength Bonus should be calculated once, which is in line with Max Hit calculation(and DPS numbers of ranged weapons from the same tier).

**Screenshots**
1) [Ranged Strength from Mithril Knives, twice the Strength Bonus.](https://imgur.com/qs3oKVm)
2) [Calculated Max Hit by the game.](https://imgur.com/ihHOf85)
3) [Calculations of Max Hit in a spreadsheet, 23 Strength vs 46 Strength(without rounding, so might a bit differ from in-game values).](https://imgur.com/CN79s2M)

**Browser**
Firefox 84.0.2 (64-bit)

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Nope.

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
