### ISSUE TITLE
Error calculating offline progress

### ISSUE THREAD

**Issue by MRBlazed90** [MelvorIdle/melvoridle.github.io#1154]
![A50188C6-958C-434A-9087-DFA00DFAABA9](https://user-images.githubusercontent.com/57635920/127241257-9f4f0855-1489-4127-a2e3-de7ce105f5ba.jpeg)

**Comment by Butcher91** [comment]
got this same error but i wasnt offline i was just idling and all values said Null.

**Comment by SmokedBeef** [comment]
just got this error about an hour ago, imagine if it's an overnight progress 

![971027](https://user-images.githubusercontent.com/20703867/127779223-79633590-9ccd-4758-abd2-dd3a521ac333.jpg)
