### ISSUE TITLE
Burning status is displayed on player (in Fire Dungeon) permanently, without taking burn damage

### ISSUE THREAD

**Issue by levgre** [MelvorIdle/melvoridle.github.io#1155]
**Describe the bug**
I have the burn status displayed 100% of the time in Fire Dungeon, no matter how long it's been since the last time a burn effect hit me. I don't take any burn damage after the normal burn time (i.e. 5s for Scorching Ray) has elapsed.

**Screenshots**
![image](https://user-images.githubusercontent.com/14255060/127266987-678d45e8-ad43-41d3-9cd4-d9025ef1f798.png)

**Browser**
Firefox 90.0.1
**Console output**
INS: content-ads.js loaded:  https://melvoridle.com/ content-ads.js:1:131452
TSS: content-tss.js loaded:  https://melvoridle.com/ content-tss.js:1:131474
TSS: Excluding content tss (trigger: send-mesage) content-tss.js:1:132891
loadCharacterSelection main.js:262:594
MICSR: playerSpecialNames is waiting for util MICSR.js:26:31
MICSR: setting up util MICSR.js:26:31
MICSR: setting up statNames MICSR.js:26:31
MICSR: AgilityCourse is waiting for modifierNames MICSR.js:26:31
MICSR: AgilityCourse is waiting for Card MICSR.js:26:31
MICSR: setting up modifierNames MICSR.js:26:31
MICSR: no unknown modifiers detected! modifierNames.js:543:25
MICSR: setting up Card MICSR.js:26:31
MICSR: setting up Import MICSR.js:26:31
MICSR: setting up Menu MICSR.js:26:31
MICSR: setting up CombatData MICSR.js:26:31
MICSR: setting up Loot MICSR.js:26:31
MICSR: setting up Plotter MICSR.js:26:31
MICSR: setting up TabCard MICSR.js:26:31
MICSR: main is waiting for App MICSR.js:26:31
MICSR: setting up Simulator MICSR.js:26:31
MICSR: App is waiting for AgilityCourse MICSR.js:26:31
MICSR: setting up playerSpecialNames MICSR.js:26:31
MICSR: setting up AgilityCourse MICSR.js:26:31
MICSR: setting up App MICSR.js:26:31
MICSR: setting up main MICSR.js:26:31
Connected to PlayFab successfully cloud.js:76:144
selectCharacter main.js:318:44
set force reload to 0 save.js:71:60
selectCharacter main.js:318:44
Loading Save Game... save.js:13:9
Save Game Loaded... save.js:29:95
Game Loaded main.js:20:405
Array [ 999213, 732182 ]
main.js:118:817
Melvor Completion Log Helper Loaded line 24 > injectedScript:3:17
Melvor ETA: loading... line 2483 > injectedScript:118:21
Melvor ETA: loaded! line 2483 > injectedScript:118:21
INS: content-ads.js loaded:  https://melvoridle.com/update/update_v020.html content-ads.js:1:131452
TSS: content-tss.js loaded:  https://melvoridle.com/update/update_v020.html content-tss.js:1:131474
INS: content-ads.js loaded:  https://melvoridle.com/roadmap/index.html content-ads.js:1:131452
TSS: content-tss.js loaded:  https://melvoridle.com/roadmap/index.html content-tss.js:1:131474
MICSR: Melvor Combat Sim v1.4.3 Loaded MICSR.js:26:31
TSS: Excluding content tss (trigger: send-mesage) content-tss.js:1:132891
Synchronising with Cloud cloud.js:8:154
TSS: Excluding content tss (trigger: send-mesage) content-tss.js:1:132891
Melvor ETA: added settings menu! line 2483 > injectedScript:118:21
Connected to PlayFab successfully cloud.js:76:144
Synchronising with Cloud 16 cloud.js:8:154
MICSR: Elapsed Simulation Time: 2471ms MICSR.js:26:31
Synchronising with Cloud cloud.js:8:154
MICSR: Elapsed Simulation Time: 1661ms MICSR.js:26:31
Synchronising with Cloud cloud.js:8:154
MICSR: Elapsed Simulation Time: 1623ms MICSR.js:26:31
MICSR: Elapsed Simulation Time: 1570ms MICSR.js:26:31
Synchronising with Cloud 3 cloud.js:8:154
MICSR: Elapsed Simulation Time: 1691ms MICSR.js:26:31
Synchronising with Cloud 2 cloud.js:8:154
MICSR: Elapsed Simulation Time: 3142ms MICSR.js:26:31
Synchronising with Cloud 2 cloud.js:8:154
MICSR: Elapsed Simulation Time: 3216ms MICSR.js:26:31
Synchronising with Cloud cloud.js:8:154
MICSR: Elapsed Simulation Time: 2817ms MICSR.js:26:31
Synchronising with Cloud cloud.js:8:154
MICSR: Elapsed Simulation Time: 1747ms MICSR.js:26:31
MICSR: Elapsed Simulation Time: 1714ms MICSR.js:26:31
Synchronising with Cloud cloud.js:8:154
MICSR: 
Object { simSuccess: false, reason: "simulation cancelled" }
MICSR.js:26:31
MICSR: Elapsed Simulation Time: 59046ms MICSR.js:26:31
MICSR: Elapsed Simulation Time: 2279ms MICSR.js:26:31
MICSR: Elapsed Simulation Time: 2463ms MICSR.js:26:31
MICSR: Elapsed Simulation Time: 2012ms MICSR.js:26:31
Synchronising with Cloud cloud.js:8:154
MICSR: Elapsed Simulation Time: 2261ms MICSR.js:26:31
MICSR: Elapsed Simulation Time: 2163ms MICSR.js:26:31
MICSR: Elapsed Simulation Time: 1366ms MICSR.js:26:31
Synchronising with Cloud cloud.js:8:154
MICSR: Elapsed Simulation Time: 2200ms MICSR.js:26:31
Synchronising with Cloud cloud.js:8:154
MICSR: Elapsed Simulation Time: 1920ms MICSR.js:26:31
MICSR: Elapsed Simulation Time: 1906ms MICSR.js:26:31
MICSR: Elapsed Simulation Time: 2184ms MICSR.js:26:31
MICSR: Elapsed Simulation Time: 2121ms MICSR.js:26:31
Melvor ETA: Remaking Agility display 2 line 2483 > injectedScript:118:21
Synchronising with Cloud cloud.js:8:154
MICSR: 
Object { simSuccess: false, reason: "simulation cancelled" }
MICSR.js:26:31
MICSR: 
Object { simSuccess: false, reason: "simulation cancelled" }
MICSR.js:26:31
MICSR: 
Object { simSuccess: false, reason: "simulation cancelled" }
MICSR.js:26:31
MICSR: 
Object { simSuccess: false, reason: "simulation cancelled" }
MICSR.js:26:31
MICSR: Elapsed Simulation Time: 887ms MICSR.js:26:31
MICSR: Elapsed Simulation Time: 2407ms MICSR.js:26:31
MICSR: Elapsed Simulation Time: 2270ms MICSR.js:26:31
Synchronising with Cloud cloud.js:8:154
MICSR: Elapsed Simulation Time: 2431ms MICSR.js:26:31
Synchronising with Cloud 18 cloud.js:8:154
MICSR: Elapsed Simulation Time: 2126ms MICSR.js:26:31
MICSR: Elapsed Simulation Time: 2185ms MICSR.js:26:31
Synchronising with Cloud cloud.js:8:154
MICSR: Elapsed Simulation Time: 2434ms MICSR.js:26:31
MICSR: Elapsed Simulation Time: 2437ms MICSR.js:26:31
MICSR: Elapsed Simulation Time: 2834ms MICSR.js:26:31
MICSR: Elapsed Simulation Time: 2246ms MICSR.js:26:31
Synchronising with Cloud 12 cloud.js:8:154
Error: Promised response from onMessage listener went out of scope 36 common.js:4:491
Synchronising with Cloud cloud.js:8:154
Error: Promised response from onMessage listener went out of scope 2 common.js:4:491
Synchronising with Cloud 3 cloud.js:8:154
Error: Promised response from onMessage listener went out of scope 41 common.js:4:491
Synchronising with Cloud cloud.js:8:154
Error: Promised response from onMessage listener went out of scope 2 common.js:4:491
Synchronising with Cloud 6 cloud.js:8:154
Error: Promised response from onMessage listener went out of scope 89 common.js:4:491
Synchronising with Cloud cloud.js:8:154
Error: Promised response from onMessage listener went out of scope 5 common.js:4:491
Synchronising with Cloud 5 cloud.js:8:154
Error: Promised response from onMessage listener went out of scope 28 common.js:4:491

**Are you using any scripts?**
Combat Simulator Reloaded
Melvor Completion Log Helper
Melvor ETA

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
