### ISSUE TITLE
Fletching Potion III only gives 10% bonus, not 15%

### ISSUE THREAD

**Issue by sylhaern** [MelvorIdle/melvoridle.github.io#1156]
In items.js:

{category:"Herblore",type:"Potion",tier:"fletching",name:"Skilled Fletching Potion III",description:"15% chance to receive 2x items per Fletch",sellsFor:90,media:"assets/media/bank/potion_fletching_iii.svg",masteryID:[CONSTANTS.skill.Herblore,15],herbloreMasteryID:15,herbloreReq:[{id:CONSTANTS.item.Lemontyle_Herb,qty:2},{id:CONSTANTS.item.Bowstring,qty:2},],isPotion:true,potionSkill:CONSTANTS.skill.Fletching,potionBonus:15,potionBonusID:0,potionCharges:40,potionPage:16,canUpgrade:true,potionTier:2,trimmedItemID:CONSTANTS.item.Fletching_Potion_IV,itemsRequired:[[CONSTANTS.item.Fletching_Potion_II,3]],modifiers:{increasedChanceToDoubleItemsSkill:[[CONSTANTS.skill.Fletching,10]],},},

modifiers:{increasedChanceToDoubleItemsSkill:[[CONSTANTS.skill.Fletching,10]],} should be 15, not 10

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
