### ISSUE TITLE
Toggling  "use combination runes" doesn't update display of runes used in "my runes" section

### ISSUE THREAD

**Issue by levgre** [MelvorIdle/melvoridle.github.io#1158]
**Describe the bug**
For example, toggling "use combination" on for fire surge will keep showing fire runes as being used (as indicated by a green outline), and will not show smoke runes as being used.  To update it, you need to change your active spell, curse, or aurora.  It appears the actual rune usage for the spell is accurate though. 

Referring to this window for "my runes" (combo runes are being used but smoke is not outlined and fire runes are)

![image](https://user-images.githubusercontent.com/14255060/127787737-3e79c259-46aa-486c-adf8-c1814f470c3c.png)

**Browser**
Firefox 90.0.2

**Console output**

INS: content-ads.js loaded:  https://melvoridle.com/ content-ads.js:1:131452
TSS: content-tss.js loaded:  https://melvoridle.com/ content-tss.js:1:131474
TSS: Excluding content tss (trigger: send-mesage) content-tss.js:1:132891
Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-129674422-1”. melvoridle.com:6:1
Loading failed for the <script> with source “https://ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js”. melvoridle.com:24:1
loadCharacterSelection main.js:262:594
MICSR: playerSpecialNames is waiting for util MICSR.js:26:31
MICSR: statNames is waiting for util MICSR.js:26:31
MICSR: setting up util MICSR.js:26:31
MICSR: AgilityCourse is waiting for modifierNames MICSR.js:26:31
MICSR: AgilityCourse is waiting for Card MICSR.js:26:31
MICSR: setting up modifierNames MICSR.js:26:31
MICSR: no unknown modifiers detected! modifierNames.js:543:25
MICSR: setting up Card MICSR.js:26:31
MICSR: setting up Import MICSR.js:26:31
MICSR: setting up Menu MICSR.js:26:31
MICSR: setting up TabCard MICSR.js:26:31
MICSR: setting up Plotter MICSR.js:26:31
MICSR: setting up Loot MICSR.js:26:31
MICSR: CombatData is waiting for statNames MICSR.js:26:31
MICSR: main is waiting for App MICSR.js:26:31
MICSR: Simulator is waiting for statNames MICSR.js:26:31
MICSR: App is waiting for statNames MICSR.js:26:31
MICSR: App is waiting for AgilityCourse MICSR.js:26:31
MICSR: App is waiting for CombatData MICSR.js:26:31
MICSR: App is waiting for Simulator MICSR.js:26:31
MICSR: setting up playerSpecialNames MICSR.js:26:31
MICSR: setting up statNames MICSR.js:26:31
MICSR: setting up AgilityCourse MICSR.js:26:31
MICSR: setting up CombatData MICSR.js:26:31
MICSR: setting up Simulator MICSR.js:26:31
MICSR: setting up App MICSR.js:26:31
MICSR: setting up main MICSR.js:26:31
Connected to PlayFab successfully cloud.js:76:144
selectCharacter main.js:318:44
set force reload to 0 save.js:71:60
selectCharacter main.js:318:44
Loading Save Game... save.js:13:9
Save Game Loaded... save.js:29:95
Game Loaded main.js:20:405
Array [ 54810, 50832 ]
main.js:118:817
Melvor Completion Log Helper Loaded line 24 > injectedScript:3:17
INS: content-ads.js loaded:  https://melvoridle.com/roadmap/index.html content-ads.js:1:131452
TSS: content-tss.js loaded:  https://melvoridle.com/roadmap/index.html content-tss.js:1:131474
INS: content-ads.js loaded:  https://melvoridle.com/update/update_v020.html content-ads.js:1:131452
TSS: content-tss.js loaded:  https://melvoridle.com/update/update_v020.html content-tss.js:1:131474
TSS: Excluding content tss (trigger: send-mesage) 2 content-tss.js:1:132891
Melvor ETA: loading... line 2483 > injectedScript:118:21
Melvor ETA: loaded! line 2483 > injectedScript:118:21
MICSR: Melvor Combat Sim v1.4.3 Loaded MICSR.js:26:31
Synchronising with Cloud cloud.js:8:154
Melvor ETA: added settings menu! line 2483 > injectedScript:118:21
Error: Promised response from onMessage listener went out of scope 2 common.js:4:491
Connected to PlayFab successfully cloud.js:76:144
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features! melvoridle.com
Error: Promised response from onMessage listener went out of scope 3 common.js:4:491
Synchronising with Cloud 2 cloud.js:8:154
Scroll anchoring was disabled in a scroll container because of too many consecutive adjustments (10) with too little total distance (0 px average, 0 px total). oneui.core.min.js:6:51588
Synchronising with Cloud cloud.js:8:154
Error: Promised response from onMessage listener went out of scope 11 common.js:4:491
Synchronising with Cloud 8 cloud.js:8:154
Error: Promised response from onMessage listener went out of scope 26 common.js:4:491
Synchronising with Cloud cloud.js:8:154
Error: Promised response from onMessage listener went out of scope 19 common.js:4:491
Source map error: Error: request failed with status 403
Resource URL: https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js
Source Map URL: tippy-bundle.umd.min.js.map

Source map error: Error: request failed with status 403
Resource URL: https://cdn.melvor.net/core/v018/assets/js/popper.min.js
Source Map URL: popper.min.js.map

**Are you using any scripts?**
Combat Simulator Reloaded
Melvor Completion Log Helper
Melvor ETA

**Comment by coolrox95** [comment]
Fixed as of v0.21
