### ISSUE TITLE
Bear+Crow will never produce Mud Runes.

### ISSUE THREAD

**Issue by ghost** [MelvorIdle/melvoridle.github.io#1162]
**Describe the bug**
Mud runes are missing from the array of combination runes, which means Bear/Crow synergy can never produce them.

Currently in `runecrafting.js`:
```js
const combinations = [
CONSTANTS.item.Mist_Rune, 
CONSTANTS.item.Dust_Rune, 
CONSTANTS.item.Smoke_Rune, 
CONSTANTS.item.Steam_Rune, 
CONSTANTS.item.Lava_Rune
];
```

**Comment by coolrox95** [comment]
Issue was resolved in an update.
