### ISSUE TITLE
Make wiki instructions for auto-loading scripts in steam check window.location

### ISSUE THREAD

**Issue by gruberben** [MelvorIdle/melvoridle.github.io#1164]
The autorun.js at https://wiki.melvoridle.com/w/Scripting_and_Extensions_Instructions#Auto-loading_Scripts_in_Steam should probably check window.location before loading scripts to prevent errors.
May want to change to something like:
```
setTimeout(function(){ 
    if (window.location.href === "https://steam.melvoridle.com/") {
        /*insert all of the commands you would normally put in the console to load your scripts*/
    }
}, 15000);
```

**Comment by coolrox95** [comment]
This issue tracker is only for bugs or suggestions for the game. Please take any wiki suggestions to the #wiki-discussion channel of our [community discord](https://discord.gg/melvoridle).
