### ISSUE TITLE
Multiplayer Combat Update

### ISSUE THREAD

**Issue by ImMonkeyMob** [MelvorIdle/melvoridle.github.io#1165]
**Please be as detailed as possible when making suggestions.**

I believe after the official release of the game a Multiplayer Combat Update would be super awesome. An addition of a new tab that requires you to beat "Into The Mist". This new tab would have new dungeons with gear much better or it could just be something cool like "Cleared Dungeon of the Heavens you now unlocked [ Thing that adds something new to any skill like a new log or ore for example to craft many things." New gear would also be super cool.

**Why are you suggesting this?**

It would be awesome and cool and allow more content to expand on as well as playing with friends or people in this cool community to party up to beat a boss for new additions to their inventory or game.

**How does your suggestion benefit the game?**

Would be cool with some super nice touches as mine is just a rough draft idea. 

~ Allow people to play together
~ New items
~ Defeating Multiplayer Dungeon could allow new drops in skills such as [New logs "Elder Log"] [New ore "Heavens Touch"] 
~ 4 Player Raids are cool

**It is suggested that you provide (mockup) art to illustrate things where relevant in order to make your suggestion more clear.**

Don't really know how to draw this. But I copy pasted a image to show how you could show your teammates health at the bottom of the screen. This could obviously be changed but this is a thing I would possibly like to see.
![Melvor Idle](https://user-images.githubusercontent.com/45349139/128727928-da1b5834-70b3-404f-a762-e9dca584d069.png)

~ Monkey Mob

**Comment by coolrox95** [comment]
As per the #frequent-suggestions of our [community discord](https://discord.gg/melvoridle):

> 1) Multiplayer Elements (PvP, Raids, Guilds, Ingame Chat, Player Trading)
> 
> This won't be happening. 
> 
> As the game runs completely on the Client, transitioning the game over to the server would be extremely time-consuming and expensive. For a Solo Developer, this is just not feasible.
> 
> A multiplayer game will require me to spend all my time implementing anti-cheat measures and dealing with server issues and lag. My time would be spent dealing with this stuff, rather than actually updating the game and adding more content for everyone to enjoy.
> 
> On top of this, the cost to actually run the game completely on the server would be too expensive. I'd need to look at other methods funding the development, which means the inclusion of Microtransactions. This is something that won't be coming to Melvor Idle, so that won't be happening.
