### ISSUE TITLE
Dragons not dropping Dragon Bones

### ISSUE THREAD

**Issue by Shinhan** [MelvorIdle/melvoridle.github.io#1169]
**Describe the bug**
These days I'm mostly doing Volcanic Cave for ancient gear. I got a shield so decided to pop back to Dragons Den to get enough Dragon Bones to upgrade the shield. I had 3 Dragon bones from before. After finishing the dungeon once there was still only 3 dragon bones. 
That was yesterday. Today I started the game in a new window, load from cloud, bury those 3 Dragon Bones and then do the whole dungeon again. Still nothing.

**To Reproduce**
1. Go to Dragons Den
2. Click on Start Dungeon
3. Scroll down to Loot to Collect
4. Not see Dragon Bones

**Browser**
Chrome 92, desktop. 

**Expected behavior**
Dragon Bones. Wiki says they are 100% drops for Dragons. 

**Are you using any scripts?**
SEMI. But auto bury is off and besides I did have those 3 Dragon Bones from before.

**Comment by coolrox95** [comment]
Bones and regular loot items do not drop from enemies in dungeons. This behavior is intended.
