### ISSUE TITLE
"Enable Offline Combat" and "Ignore Bank Full" enable/disable options seems to be linked

### ISSUE THREAD

**Issue by Theophiphile** [MelvorIdle/melvoridle.github.io#1171]
**Describe the bug**
"Enable Offline Combat" and "Ignore Bank Full" enable/disable options seems to be linked, so I can only chose enable or disable for one setting, the other one becomes blank.

**To Reproduce**
Click on enable or disable in front of "Enable Offline Combat" or "Ignore Bank Full"

**Expected behavior**
I can chose enable/disable for both options.

**Screenshots**
[https://paste.pics/c75e6e975414998612da58a13784ea92](https://paste.pics/c75e6e975414998612da58a13784ea92)
[https://paste.pics/f766196e441c7ba2b5fbe3b9e03f3cd2](https://paste.pics/f766196e441c7ba2b5fbe3b9e03f3cd2)

**Browser**
Firefox 90.0.2

**Console output** (Lots of French...)
Échec du chargement pour l’élément <script> dont la source est « https://www.googletagmanager.com/gtag/js?id=UA-129674422-1 ». index.php:7:1
Échec du chargement pour l’élément <script> dont la source est « https://ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js ». index.php:25:1
Échec du chargement pour l’élément <script> dont la source est « https://static.cloudflareinsights.com/beacon.min.js ». index.php:528:1
loadCharacterSelection main.js:256:594
Connected to PlayFab successfully cloud.js:76:144
set force reload to 0 save.js:57:60
Combat Manager Built... combatManager.js:1:666
Golbin Raid Manager Built... raidManager.js:1:949
Loading Save Game... save.js:14:29
Save Game Loaded... save.js:14:140
Game Loaded main.js:5:355
GEThttps://cdn.melvor.net/core/v018/assets/media/skills/runecrafting/rune_fire.png
[HTTP/3 403 Forbidden 116ms]

Ce site semble utiliser un effet de positionnement lié au défilement. Cet effet pourrait ne pas fonctionner correctement avec le défilement asynchrone. Consultez https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects pour obtenir davantage de détails ou discuter des outils et des fonctionnalités liés. index.php
GEThttps://melvoridle.com/assets/media/bank/bones.svg
[HTTP/2 404 Not Found 192ms]

GEThttps://melvoridle.com/assets/media/bank/holy_dust.svg
[HTTP/2 404 Not Found 204ms]

Synchronising with Cloud cloud.js:8:109
Échec du chargement pour l’élément <script> dont la source est « https://static.cloudflareinsights.com/beacon.min.js ». update_v021.html:306:1
Échec du chargement pour l’élément <script> dont la source est « https://static.cloudflareinsights.com/beacon.min.js ». index.html:565:1
GEThttps://cdn.melvor.net/core/v018/assets/media/main/cloud.svg
[HTTP/3 403 Forbidden 20ms]

GEThttps://cdn.melvor.net/core/v018/assets/media/main/cloud.svg
[HTTP/3 403 Forbidden 12ms]

Connected to PlayFab successfully cloud.js:76:144
true 4 main.js:245:116

​

**Are you using any scripts?**
No

**Comment by trentks** [comment]
Can confirm. Also on firefox/linux.

**Comment by trentks** [comment]
This appears to be solved sometime of/before 0.21.1094.
