### ISSUE TITLE
Unequipped items go to first bank tab instead of the one they were assigned to. Everything equippable is affected.

### ISSUE THREAD

**Issue by MiddleNipple** [MelvorIdle/melvoridle.github.io#1174]
**Describe the bug**
When you unequip an item it goes to the default bank tab instead of the one it was already sorted to. This has been the case for every equippable slot and item i could try it with

**To Reproduce**
1. Go to 'any tab'
2. Click on 'your equipment at the top right or one of the combat related buttons on the side'
3.  Unequip any item
4. it will go to your default bank tab instead of the one it was sorted to before

**Expected behavior**
The unequipped item would go to the bank tab it was in before, it does not
**Screenshots**

**Browser**
Steam version

**Console output**
pressing F12 did nothing

**Are you using any scripts?**
I am not using scripts

**Comment by NototoHoshi** [comment]
I dont think its only equippable items... when I checked my items with the "cog" setting (item setting menu), it shows default tab "0" for ALL my items. It looks like one of the latest updates wiped the saved values for default tabs for all items.

**Comment by delmain** [comment]
Yep, came here to say what NototoHoshi said, it appears that the latest update wiped all saved tab info. If an item was in the tab, it stayed, but anything new (including being unequipped) now reverts to 0.

**Comment by coolrox95** [comment]
This issue has been hotfixed, as of Alpha v0.21 (1033). Please refresh your game for the changes to take place.
