### ISSUE TITLE
"Report a Bug" feature does not work

### ISSUE THREAD

**Issue by MiddleNipple** [MelvorIdle/melvoridle.github.io#1175]
**Describe the bug**
When you click on "Report a bug" it takes you to a screen that tells you it cannot connect to github
**To Reproduce**
1. Open Melvor Idle
2. Click on "Report A Bug"
3. See a screen saying "github.com refused to connect"

**Expected behavior**
some sort of transfer to github to report a bug
**Screenshots**
![report a bug](https://user-images.githubusercontent.com/88880856/129333773-0b0915e7-b8c2-448e-a5e6-cadf6fd6eb57.png)

**Browser**
Steam V0.21

**Console output**
F12 does nothing
**Are you using any scripts?**
no scripts

**Comment by shadestalker** [comment]
Verified just now on Steam version ?1038
