### ISSUE TITLE
Item icons not appearing

### ISSUE THREAD

**Issue by haggishunt56** [MelvorIdle/melvoridle.github.io#1177]
![7478CE54-8C65-4720-863E-D48FA3742758](https://user-images.githubusercontent.com/54241835/129336964-364cc5c0-11fa-4c8d-8d17-28828708d5af.png)
![8CACC3AF-EF22-4B6B-97E1-731F55D958D1](https://user-images.githubusercontent.com/54241835/129336974-e0f482c9-5dec-4318-97bd-ddc87a1ea25f.png)
After 0.21 update, some Items either equipped or in the bank do not show their icons on iOS app

**Comment by Minichurro5** [comment]
Bump. I am also having this issue.
