### ISSUE TITLE
Offline progress didn't work when browser was left open on PC sleep

### ISSUE THREAD

**Issue by levgre** [MelvorIdle/melvoridle.github.io#118]
**Describe the bug**
I left my browser with Melvor Idle open overnight and put my pc to sleep and didn't get offline progress.  Melvor Idle was the only tab in the browser.

**Browser**
Chrome version Version 80.0.3987.132 (up to date)

**Console output**

www.googletagmanager.com/gtag/js?id=UA-129674422-1:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
2pagead2.googlesyndication.com/pagead/js/adsbygoogle.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
(index):1 A cookie associated with a cross-site resource at http://cloudflare.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
save.js?225:42 MI-A04farmingAreas variable Removed Successfully
save.js?225:44 Loading Save Game...
save.js?225:206 Save Game Loaded...
save.js?225:44 Loading Save Game...
save.js?225:206 Save Game Loaded...
mastery.js?203:156 Updating Masteries
mastery.js?203:23 Loading Masteries...
smithing2.js?205:185 Loading Smithing...
main.js?237:990 Game Loaded
cloud.js?209:79 Melvor Cloud Connection: Failed
/cloud/versionCheck.php:1 Failed to load resource:

**Comment by Captiv8** [comment]
Can confirm same results in Firefox. Left tab opened and put directly to sleep. Turned on in the morning and it picked up where It had left off last night

**Comment by MelvorIdle** [comment]
I'll look into this one.

Maybe just close the game for now to get the offline progress until a fix is released.
