### ISSUE TITLE
Raw Shrinps not being received from combat.

### ISSUE THREAD

**Issue by VictorHugoLeme** [MelvorIdle/melvoridle.github.io#1180]
**Describe the bug**

**To Reproduce**
1. Use Amulet of Looting
2. Battle against Ranged Golbin.

Receive the raw shrinps at my bonk :)

**Screenshots**
![image](https://user-images.githubusercontent.com/76635730/129371220-cc4c497d-bd87-4654-af4b-f0b30b721736.png)

**Browser**
Opera

**Console output**
Please open t
he console by pressing F12 and copy it here.

**Are you using any scripts?**
no

**Comment by coolrox95** [comment]
This issue has been hotfixed, as of Alpha v0.21 (?1033). Please refresh your game for the changes to take place. (Your raw shrimps should appear in the first tab of your bank upon doing so).
