### ISSUE TITLE
View Item Stats no working in Crafting

### ISSUE THREAD

**Issue by Deamo-J** [MelvorIdle/melvoridle.github.io#1184]
**Describe the bug**

**To Reproduce**
1. Go to 'The profession Crafting, select any item'
2. Click on 'View Item Stats'
3. No pop-up

**Expected behavior**
A screen like this:
![image](https://user-images.githubusercontent.com/88897818/129385133-f52d2403-407a-4317-abc5-73ced13478ea.png)

**Browser**
Steam Application version ?1012

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Hotfixed pushed to live game. Alpha v0.21 (?1093)
