### ISSUE TITLE
Auto-swap to another food slot if the current one is depleted

### ISSUE THREAD

**Issue by Sundwalltanner** [MelvorIdle/melvoridle.github.io#1185]
This is mostly coming from something that happened when I tried out afk-combat overnight, and for whatever reason, my stack of 1,000 or so potatoes was selected rather than my 400,000 carrots, so I died overnight. I honestly don't know how that happened, because I never swap food, so that's a separate issue in itself.

Anyways. What purpose does having 3 different food slots serve if auto-eat doesn't take either of the other 2 slots into consideration?

At the very least, there should be an upgrade in the shop that we can buy and then toggle elsewhere in order to allow auto-eat to swap to another slot if the current slot is depleted.

**Comment by jvmcarneiro** [comment]
Strongly agree with this one, even more so now that we have offline combat. Makes no sense to die and lose equipment or even your character when you have another 2 food options equipped.

**Comment by coolrox95** [comment]
This has been implemented as of Alpha v0.22.
