### ISSUE TITLE
Broken current pickaxe banner

### ISSUE THREAD

**Issue by Yiuloon** [MelvorIdle/melvoridle.github.io#1188]
**Describe the bug**
The banner is broken in 2 for my adamant pickaxe in my mining section. Attached an image below.

**To Reproduce**
-

**Expected behavior**
-

**Screenshots**
![broken](https://user-images.githubusercontent.com/88902999/129400559-b6c51d79-44e5-4b7d-92e2-60abd938d76f.PNG)

**Browser**
Steam version.

**Console output**
-

**Are you using any scripts?**
Nope.

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
