### ISSUE TITLE
Offline mining calculation appears to be incorrect

### ISSUE THREAD

**Issue by Pwootage** [MelvorIdle/melvoridle.github.io#119]
**Describe the bug**
I offline mined rune ore for roughly 10 hours, and got no ore or gems. Upon debugging, it appears the totalActions calculated is roughly negative 14,000, which is most definitely incorrect. It's roughly what I was calculating manually, except negative instead of positive. This could be a coincidence? When manually editing totalActions in a debugger to be my calculated value, it worked as expected.

I haven't checked with other ores, but it presumably is incorrect for them as well.

**To Reproduce**
Level 86 mining, 36 mastery, offline mine rune. Any period of time works, but it's more obvious with longer time periods.

**Expected behavior**
If not accounting for increasing rock HP as mastery increases, roughly positive 14,000 actions, if my math is correct.

**Screenshots**
N/A

**Browser**
Firefox 73.0.1, macOS

**Console output**
```Loading Save Game... save.js:44:13
Save Game Loaded... save.js:206:13
Loading Save Game... save.js:44:13
Save Game Loaded... save.js:206:13
Updating Masteries mastery.js:156:13
Loading Masteries... mastery.js:23:13
Loading Smithing... smithing2.js:185:13
Game Loaded main.js:990:17
Melvor Cloud Connection: Success cloud.js:45:29
Loading Save Game... save.js:44:13
Save Game Loaded... save.js:206:13
Loading Save Game... save.js:44:13
Save Game Loaded... save.js:206:13
Cloud synced 3 cloud.js:158:21
```

**Comment by MelvorIdle** [comment]
So it seems like my mastery calculation is off?

**Comment by MelvorIdle** [comment]
Hotfixed. Further confirmation required.

**Comment by Pwootage** [comment]
AFK'd an hour of rune, and it appears to be working exactly as expected now. I'll be running it overnight and I'll edit this comment with the results in the morning, but I expect it will be correct.
