### ISSUE TITLE
Idle bug when Fletching

### ISSUE THREAD

**Issue by NototoHoshi** [MelvorIdle/melvoridle.github.io#1190]
I've setup Topaz Bolts to build (with around 1,500 Topaz and 20k+ bolts) and went to the store to get some groceries. Returned about 40 minutes later to find this screen (see attached image):

![MelvorBug](https://user-images.githubusercontent.com/31606420/129403463-e43f41f7-9500-4670-a4c2-06978c83b0a8.jpg)

As you can see it bugged out at around 140 Topazes left.

I am using no scripts, browser version of melvoridle.com (OS: Windows 10, Browser: Opera 77.0.4054.277)

I was not playing offline (the browser was open), although after 30 minutes my PC automatically goes to the windows title login screen to enter sleep mode.

**Comment by coolrox95** [comment]
Issue seems related to #1111

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
