### ISSUE TITLE
Golbin Raid models have stopped diversifying

### ISSUE THREAD

**Issue by jvmcarneiro** [MelvorIdle/melvoridle.github.io#1191]
**Describe the bug**
Golbin models in Golbin Raid mode are always the same: a basic green golbin with no accessories or unique characteristics.

**To Reproduce**
1. Start a Golbin Raid run
2. As you kill golbins you'll notice they all have the same basic green model

**Expected behavior**
Before Alpha V0.21 each golbin would have different characteristics on its model.

**Screenshots**
![image](https://user-images.githubusercontent.com/7219775/129409005-9e52e3d5-5f39-4831-83e5-7470ccb01c3a.png)

**Browser**
Firefox 91.0 and Android app.

**Console output**
No useful info in console.

**Are you using any scripts?**
No scripts.

**Comment by coolrox95** [comment]
Hotfixed, pushed to live game. Alpha v0.21 (?1093)
