### ISSUE TITLE
Willow Logs Don't Appear in Bank.

### ISSUE THREAD

**Issue by glassa** [MelvorIdle/melvoridle.github.io#1193]
**Describe the bug**
When gathering willow logs via woodcutting, they do not show up in your bank. They appear as a selectable material for fletching.

**To Reproduce**
1. Go to 'woodcutting'
2. Click on 'cut willow tree'
2.5. Cut several willow logs
3. Go to 'bank'
4. Willow logs are not in the bank
5. Go to 'fletching'
6. Select 'Arrow Shafts'
7. Select 'Willow' as the material
8. See that willow logs are available for use, and are being tracked.

**Expected behavior**
The bank tab should show the current count of willow logs, if they player has any. This count should match the value that are useable in other skills as a resource.

**Screenshots**
![image](https://user-images.githubusercontent.com/12737283/129415336-a834c1f3-6826-440c-9625-3a43ff0be536.png)
![image](https://user-images.githubusercontent.com/12737283/129415362-d543ee03-c528-4704-9fbc-8c62de005683.png)

**Browser**
Bug appears on both the steam version of the game, and on my android tablet.

**Are you using any scripts?**
No scripts are being used. Logged into melvor cloud. Standard gamemode character.

**Comment by elestora** [comment]
The same problem occurred for me after harvesting Yew Tree seeds in farming. I can see that I have Yew logs available in firemaking, but they don't appear in my bank.

**Comment by glassa** [comment]
Most recent patch fixed it. Impressive turn around time!
