### ISSUE TITLE
"Undefined" in Recoil Shield description

### ISSUE THREAD

**Issue by Raptord** [MelvorIdle/melvoridle.github.io#1194]
**Describe the bug**
The description of the Recoil Shield displays "undefined%" instead of the actual % of damage that is reflected.

**Screenshots**
![image](https://user-images.githubusercontent.com/2872199/129416479-2e8a0b6d-b32f-4ce0-854d-9d95292f10ae.png)

**Browser**
Firefox 91.0

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
This has now been hotfixed
