### ISSUE TITLE
Mastery Token Chance Bugged

### ISSUE THREAD

**Issue by sylhaern** [MelvorIdle/melvoridle.github.io#1195]
It looks like online, mastery token chance is significantly lower than it should be.  Looking at main.js, 

`function getMasteryToken(skill,offline=false){const tokenChance=getMasteryTokenChance(skill);let item=0;if(rollPercentage(tokenChance)) ... ...`

`function getMasteryTokenChance(skill){let chance=getTotalUnlockedItems(skill)/18500;chance*=1+playerModifiers.increasedOffItemChance/100;return chance;}`

`function rollPercentage(chance){return chance>Math.random()*100;}`

It looks like getMasteryTokenChance is being calculated as a decimal, but then it's using rollPercentage to roll against that decimal, so the chance is 100x as rare as it should be.  I don't think it's affecting offline though, since that's still using the same sample_from_binomial that it did last patch

**Comment by MelvorIdle** [comment]
This is now hotfixed
