### ISSUE TITLE
Golbin Raid Combat Passive Slot Not Visible

### ISSUE THREAD

**Issue by snypex24** [MelvorIdle/melvoridle.github.io#1196]
**Describe the bug**
Unlocking the Combat Passive Slot in Golbin Raid and its not visible in any interface, Can still roll for one at boss rounds but it still doesn't show up, but is visibly there when you die in the death screen (Something does get rolled but you don't get options, it just picks something at random)
**To Reproduce**
1. Golbin Raid without anything else unlocked
2. Unlock Combat Passive Slot
3. Start Golbin Raid, slot not visible in any interface
4. Make way to round 10, can roll for passive slot but don't get any options, it just starts the next round
5. Die, and see that a passive item was in the slot but not visible whilst in the Golbin Raid itself

**Expected behavior**
Be able to see the combat passive slot, and get options to when you roll for it on boss waves

**Browser**
Steam Version

**Console output**
Not sure how to do this on steam :D Here is my save stuff though H4sIAAAAAAAAA+1cS28cOZL+K4s6pwQyggySvi2w173sHm0f1LaMNcbjbox7Glg0+r/v90UwS1mqKpXkltuehURlJZOv5CMYb+bvu992r3TZfd69ep2WtOSUm8nSGEUoSEhLa7pk4XM26X0UTdZ7RZlecpHlKr9ddj95C3lW5D3N+JqSD3IS6nxBnddmzROtpUVwVx3+3HuJdBueXtpSdTCt9EXEc2teJNXKmC3ZMyta08xYVl2qJ3Vk8811LB3lFsOYOu+ozpdjxGxD0IORu/dXevRWRtwVqdXMo7ha9nzFVA1BTHtfSmFJs7IUZRdRAYOqjLRFmCADJXpjimCAPiyMA7OL0eLG1nDTpQjvBcMsjKBztWe8ZTG+Hm0qlshGZ2bOY6k1MVZwtaQeRWVLkYouJI0o6ht6wygGnsU8irHMBjDV6tl4BiSwE5h+DJFJ6HhK3l3MqFb+YFUwBAIHesm5jG5WTp+OiGIGxZuv6ESXiCGrRQzTkrrH1KGNMa4a7hiZjOKNADZaxAiFNaKYR1OvK7i8u1WKTzNjGHcePkVY8Mz+M4q8mYg35+4xJWgwghfHWMfi3TMsSFSshuYaF6UaBpeMsSaYgO6xgD/EsKCCKWYMOcLIsAVQVZaB8r0WjxUuOSLI6GoeE64gct8ur1VrAYgDTjVX5WZ5LQPQEJuq9Kblupbhf6iD7NIHwKQ1AxAIlq9fl9aiwMAy55yTKsphrRRLiu5YA1hcq7FUQ89qr5h+AVhVAhGGg97mzkqN8zjQHQE0eSuF25QxLIstDfNvA0vhHSXwDcOkK5e2Y6pq6dzKmjLBspp6ucq+qqBuSQMwMLDVU/IsDJuzg15KUUAdKw9/ccIwVYB9ivYoXLrD+6zqmOW1VsxrQxfwh8XBnGGQlfUBgX1FQSuKkmbMqr4hcWtxS195syU6QpDxBOyJ5mCTuJW58wk5yREsNm/zYsR+mS1cZf4TYh2YkM6Zw37a5gV4RbUa797n2fahbR/69mFsHmRbRzbFfCAbrO5TGOh1JraJ0gm+Pth9CBQ6EehsweI2i0jcWtyifKTJLKHe+iwQTelKmlhsltZ9d9LaQBSI/si8xdslmnNKwE7ux3hIqe49ByUIuqBpYv9JDkic8FMnJchzNQHsoAeO170UiZRTmew4yqndYpUFjKgX8eS/4ind494ICR1+CaHCTGUqhkP8k/23+ru8im9vUhhxakhyxxdOQsR5FuI7J6ROQ/HjwLif31ImiVCnojnQ5iKTWqDTRrhS7xWpKGksSrBrRNqLTnIU5IdYM7BwkCsi2DzpEakb2zNvisMiIizOBiSnPoGgdaVRxtZL91cF1nYaabLi68Djk8g4VQqCFLQoyFCQmyA/QXCIq7zJwP866U/QHqawSIn1keAdCD7MqZMuMW6TMAVNCno0CeaekDiZaHklII4AiAjECUQQh6AMQVi413WSFlKTOokQf0loss+F7xyuUbbgPYSAjp5odQDxQY9obU+eFvbo8z8/fYof0swgdcUTAp++hJfwLxkgGyhQBxiXBHxT8ujcJjq4p8jBlzoaUYORKx/E16da4eZF1Q70xDZDsMhg9oFTHOGqEId2qZRL2IaSMiRgko72iYxEnQn43vPxLQMpUjBWsqHC37tXL+ElvISX8BJewkv4JiE0ApuUh6j+kzkCtB66r5F0XEMOwp9QxDbptQ27rhBXTMDZSSoQma91rH9kSFACvF5XCKE1Wbpu+1xwZqVkuXZ+rVe9rrbPQV7TAjbvOkdKp3idmras15TapUFEy1mbei+lprXkLL5Qc2dar0ta/yh45+uim3KFsmgTuYaAm4v0bHZZ4kIJqsapLqcUTmkfsjL1YMHfgo9VV8u3VOsg5ynodhGqSqgBiwX71iDx9u2y++z6/deU4anYdeNB57QWStCunp5mhhMlysUSdrFEu1iiXypBZc2FEvliiYujdQPLwyUuzkc7nI/7C+JK9bsaqdmgVqyUfY1TJexiiX6pBHVlF0rkiyX0YolyscThWO7Pj+v+1xoFO7GO7kaFfY1TJcrFEnZQInn+igszdslr7HcpCYsxrrEg1mlayBm9pq4MSKkuCgkUMGQdmxhPeChu5bAqrvNPo2pbEXEaHQiRUNvdsAPoG+aGPfU58ZsAlRVdysg+BqBX35K9US8nBdCWaBxR4NROdVQSxT2ZGBW4B02dbBi4sontH/OgTYCICYVE12Tg2TzceEH9FFDUNdEsRWqq34z2PpqbEkRrzEGjmJ5UQo6mjh8dBux4rUbbS620BcbkFuDmDsRIleIp/ETbWh6BQ1DdMBmac6ahplKfSO2rCWbBQHD21swyhu+lBfhfR+ebDTNOy54Q01bJxies3+h3qmPgmTqoCB/ejEdTKPtztCyh8c7fQksw2PTdo3VgG9GRqh0UyjT0Hj6fC622w1lVOyzhhhrqTxNIXqPuQ9wO6NVyy42G3G6im/K0A2gBSFwrLXcpVNihl0nEVNS0Sxm1k+Rnmu4AdJ2WJU0d5JaVaKPSlrKhlT3lJUyAf2jYZjTc0WBFaxiVx4BTWodra2gVa07lNVKo3qVdLXpGdbP5WgMy1uu5V+lscGsb7aDgf7g/2FGCvpHA066ITZr62fp3C9UfjJ3eJrkeJ/+ogd0dCxYvyb0swklty+hYSvBKjlnVLWMAo+IWE05EqePkPBJBYUcUTr+2b7z0bkClcbY6YotUIEKiomWAe1z3ss3rsDYJiqS7lKJ3e1/sbmKkho2K1958QNuBJbffdMwkjfEjz7vMu8574t1nZvuy/sDLnNMOy1AYiMCSRuzJL+tV9mNrQ8+8kI4HS/VAeylvglKNFqdHvLK4wdht4sKFUF+OtoEuxsue5MwpbcSGgd6zW1kjol1Iujz2lOEWCjvAdd2S9yHeTmIYQy57XBQWqEbs0D0g7jdwI/TSePSLHYayRbvSNQYIZB0p2lMgi0pfhnhz3lu/bRI5905Jm6nK4aVBaz95jkIXAyGwUZNO1xnnJenDQ5ePnEr4qNDthzZECFvuRkFJTsR5V60B22YOw429bxwaWQ4Fq0KgowOJ/0AUEi6F0v0Dv8ACnZ2k6bPSd2H+ZnBT1alPnUBdz9FkoXdBXkAumlugN7xdjgu0qK1pABT8l0LurKr/F6HfxfpPcrhex4F24vUKoH4Yk0AWwJajXNzcqg4eJHZnSSWWTefyFbM5nHquUXoF0dzZpo4frGFEwschLd0mXEbxYCQmTEyzviyHeDnfCzKtz3e5h9hYVpP33i3gK/QJ/y8COKiYSunTI+huAi+BBegjbb8UMjSZ0qbuJnra/HOqSiYJzTYXIJZGfxtsNSLcDH4IbC9RCTchIDFx8xQ5bTZ7XCiTnye4ToST5n6DNDUjebKqbSag4wfDt/Uf/cL/YJXmF5nFXNY35LhSd6F13P2k8GzztuvcJjlPJjdnm31Nk9JIzL7Ngv9CPNJL+MGD+7c9ubB7rT6h/F2EVE597zxXsElEij3MKVd3PQJbVFfptzp/zX9pLm3xv/TkHnDCjcYoPX+6y9j1Gaed4YE5dNR6WjrY50s6T41Iu8oDEvVxza0X2kt4ONRBxP/du/F9w9bvEkLA5S0t/c9D13PB54YP1AtFdcoj7nXOSDvqyUxv26Rts7NGPKwijPjViW+eZ0w/YsgQOdbIZNWBgT2iaTJydDn0nKlqcCf6TRN9qiXoCh4Rnexo79EmBUmvKbPKfFfersiPH6TERPjRAbLXeqBZkqn1zO0YZGX6Aruj6nFmaFziyMDje+OGn+SHFo4y3ak30zH7CZPsbmmLteVR3MNfGajJPZPFWWiXeKS/UjoUCL1+0flP6KPNK3Gl6LzNK9Ez+uCBp4B4yTAv7w3xhI2fsoG8s0or4ErSJZWjuMbcf0TlDn8ZtSX+0/Bm6ioSuSmjwWkWKejA3MWuBMxDXPmR4mQBFVC20B3c1enLMTA/JtRn5NSeP3AfWpya+BGDWlxNvndPXsJLeAnb8CKevYRtMEvOh93ZAR4lS4wmKwcQtcp53YbUcw+PD88Ktvc81qTxTJIu8oC25C60ArbDhh9z+7M98fNSF8XHc0EHD6PxtOiR+XgzccMNwXQ8Od8NP9J2mOaH/f464QcSW5zH7M/J1Fivfmxezjfajao8sMHlhEx0HGjTo5RId4uncZbmZ+Gfb2wQxPy0PVZ/1aiOxjN+Np+Fxx6NxyYf0VhS/3KCP2icFmLkaV1ib9q6w4sprTGUKq08N6eaT8QeE6xqN5dYTB+LiJ4T9bQy/DsHbkTVuTQZf8pZd7Owp/CBH5V4lGQM8cy6fzdCz4NwN9r4+cGBctDmxIV0eUzMGLMH1ANE+v1Q4tTZ/uhZXdIJyy6PqDXhAOM3xanPtDxx23zLABFlEDJ/DCWPr0RQlfiFLK3bmy/cvGlZfxjqKZfBg0B/6gtFgNpW+jdEN704ABiA5DmEAjR7f58Djr926wNrnEqurmUBrPqJ8bQflaVtL7VLWeFMhxwoA8MrJcfJSIfIFCiU3qPnkILp3n/w/ASkaPJISU2vzPt1cj0iyLm0U2u0uqfMp6FbLiWDaTlrzZYx1P367UD7lLObq2tdZ8h1aW1dqFylPWVDaFmxzmhNT81Nq3tHpyylrN1VPVITSdHDdTw1tNHKOUaNDvKbx6pnsY2Mk+o6sbHWEHTlLDi4U5MeuL4W8xZVkm3RsH9Jhgi17EdG5ezj53ff/ngKo5iHxjc6ZOypuOT9klve+wDYpmPatz2r/WA5i7gTA6b4/suq63ctDe8iPVVPTW0b7TjVLcFfMRsWnhQjN9+7ZTj8gmtZV7Udd3MbLqLDc6F9NUa7FFRbOtV2705rh+oDfOzDQQ6QTTnapaWJ3Mda9Nw8tY7ugz6jgcT2CEh9b4NeHXgbtz1ChKDizleajmwMHev1tYLQY0I5MHVLLl9L83O+SGz/THAKVMp03DzAhdknLWfp64bJFpsHW9y9gXMwjMA1B8KMf10sorXISRS9BuuHnbHvyq25kz1dJdsx4J+3t9AFdh5g4YfN5reYqNjoHqWfVY3UDkiwsD7Q+9+PvsUigBWPkzdgheiIH40YGMZZhM5lswSd8mW+r1uJAussg+eeKfyeSanRMXXT3KzPD7FZxNUFyyjPwymb3oFqx0toKC8xlHXnYcjhS+ZeZGXaYegrFt8/o4dYc/uy+gEp537cHO3mVTetulnVTao0p/rXftyMykXg512o8aEvN6RCfiNioP6EmUQnXVI/fkkIAnILObROAwWPMmJQurdh556PYbDxpESUZ+s8I0HH2jEtlti+vU63OBDfVuhXiTo8JEUPnDGZV7rS9x6OPE/5FsxbHv/7effq9e73N7svf/v46dOb3au0vNndvPv148+f8cAzNG+R8OvHv99++fXm778gbfN1wZb/2C271292BhbtVqVd/fThNl2Vru3q5sO4vdJxU+iwKzetv9mhIexnhHJ79f5dlquSm17djJufrtKH0W5/+mDvbzW/2b1Fq7+z6Te7//78v7/cvtl5/N8//fI/N//2W7qW7Cno9X/e/ONvX/7j45d3P/92+4/b9+geEtMcRp53mXfFHcD2ZlcQEdzrmmCzRJv3Pu9jFsz7JtlmZ2RtNOsaKWukrpG12by2m9eGM1tOfyD2/vbDzT8//fpft+8+cqCv5vI5Snxw8f7YYfXevUeNrPzs20INhqOyu49sbSX59bth4Bb92M4sduayWf4qvH15AquPiZt5PIN7QKeZt7vZvTUvyQOOjoPo/Ou+/O6SrP5xL+5F98V2/xB+dYzO8e7nRi/wuva3L+vXnCjDcfsObEt+sEltOxZuBF0kPdOo1zCs0ol1rbtmXu3L8uZnKu+vyf8BOuCy2KpTAAA=

**Are you using any scripts?**
Nope, running the game completely natively on steam

**Comment by jvmcarneiro** [comment]
Also happening in browser and Android app.

**Comment by coolrox95** [comment]
Issue has been hotfixed.
