### ISSUE TITLE
Teak logs not showing up in bank

### ISSUE THREAD

**Issue by DarkenTheSun807** [MelvorIdle/melvoridle.github.io#1197]
Summary: I've started cutting teak trees and while it's giving me +1 teak log notification I can't see them in my bank. It even says I have 43 items in my bank while I've counted only 42 (Checked several times). I've reloaded twice, no change. 

To Reproduce:
Got to woodcutting
click "cut teak tree"
watch barfill and notification on bottom of screen pop up
go to bank
see no item

Expected behavior:
Item should appear in bank
Nests do, normal, oak and willow logs do, teak logs don't

![uh](https://user-images.githubusercontent.com/28941164/129426152-c7e54edd-8f1b-42a3-8d77-c7ee48a09f50.PNG)

Using Chrome
Version 92.0.4515.131 (Official Build) (64-bit)

net::ERR_BLOCKED_BY_CLIENT
ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
main.js?1012:256 loadCharacterSelection
cloud.js?1012:76 Connected to PlayFab successfully
save.js?1012:57 set force reload to 0
combatManager.js?1012:1 Combat Manager Built...
raidManager.js?1012:1 Golbin Raid Manager Built...
save.js?1012:14 Loading Save Game...
save.js?1012:14 Save Game Loaded...
main.js?1012:5 Game Loaded
rune_fire.png:1 Failed to load resource: the server responded with a status of 403 ()
bones.svg:1 Failed to load resource: the server responded with a status of 404 ()
cloud.js?1012:8 Synchronising with Cloud
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloud.js?1012:76 Connected to PlayFab successfully
3main.js?1012:245 true

No Scripts

**Comment by MelvorIdle** [comment]
This one should be hotfixed now
