### ISSUE TITLE
A more vertically compact menu.

### ISSUE THREAD

**Issue by mrDLSable** [MelvorIdle/melvoridle.github.io#12]
The menu on the left side of the screen is too tall in my opinion. I think you should be able to see all your levels when you load the page.

This can be easily accomplished on a 1080p screen by setting the vertical padding of the nav-main-link class to 0. This will result in the menu looking like this, which is perfectly reasonable in my opinion.

![image](https://user-images.githubusercontent.com/1783781/68632161-decda200-04ed-11ea-9eb9-9e1e6454965f.png)

If you dislike the aesthetic of it, perhaps it could be added as an option in the options menu?

**Comment by MelvorIdle** [comment]
Good suggestion. Added into the game for next update that gets pushed.
