### ISSUE TITLE
Summoning text display as green when leveling it

### ISSUE THREAD

**Issue by NototoHoshi** [MelvorIdle/melvoridle.github.io#1200]
I understand that the development is in progress and many things are certainly planned to be added, including some way to displays for summoning (for instance a number of tablet charges remaining - perhaps in a similar way remaining charges for Gem Gloves are displayed when mining), but one thing that I think would actually be pretty easy (programming-vise) and simultaneously extremely useful to add right now would be the following:

Similar to how other skills works when youre performing their action / leveling them up, I believe it would be very useful if the text for "Summoning" in the left action bar turned green when youre leveling it up. Simply - if youre doing something and have the corresponding summoning tablet equipped turn the text green. 

So for example when woodcutting with Ent tablets, both woodcutting and summoning would be green. Similar to how when youre doing combat, multiple things can be green at once (slayer / prayer / hitpoints / attack / strength / defense etc) depending on whats happening in the combat.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
