### ISSUE TITLE
Gem glove charges are used on rune essence.

### ISSUE THREAD

**Issue by Makoprima** [MelvorIdle/melvoridle.github.io#1201]
**Describe the bug**
Gem glove charges are used when mining rune essence, despite gem gloves not working on mining rune essence.

**To Reproduce**
1. Equip gem gloves
2. Mine rune essence (online or offline, it works on both)
3. Your charges should drain, despite gem gloves supposedly not functioning on rune essence.

**Expected behavior**
Gem gloves do not use charges when mining rune essence.

**Browser**
Firefox, latest version.

**Console output**
I don't think this is necessary for this bug.

**Are you using any scripts?**
Nope.

**Comment by MelvorIdle** [comment]
Hotfixed pushed to live game. Alpha v0.21 (?1093)
