### ISSUE TITLE
Extremely slowed down combat progress when phone is locked while the game is open

### ISSUE THREAD

**Issue by krexaim** [MelvorIdle/melvoridle.github.io#1207]
**Describe the bug**
Locking the phone while the app is open results in no progress until the phone is unlocked again. Other skills progress normally. Offline combat is enabled.

**To Reproduce**
1. Start offline combat
2. Lock phone 
3. Wait a few minutes at least
4. Unlock phone and see significantly less progression than expected

**Expected behavior**
Expect a "Welcome back" message with a summary of XP and drops obtained but nothing shows up instead

**Screenshots**
N/A

**Browser**
Android 11, game version 0.21(?1034)

**Console output**
N/A

**Are you using any scripts?**
No.

**Comment by coolrox95** [comment]
Issue has been resolved as of Alpha v0.21 (?1112).
