### ISSUE TITLE
Normal Logs are added to bank during combat

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#121]
**Describe the bug**
When combat experience is earned, getMasteryToken is called, which results in a 1 in 1000 chance to add a normal log to your bank.

**To Reproduce**
1. Earn combat xp
2. Wait for addXP to call getMasteryToken and roll to give a token
3. Normal logs are added to the bank

**Expected behavior**
Combat skills should not earn Normal Logs as mastery tokens

**Screenshots**
![image](https://user-images.githubusercontent.com/58208131/76152743-7a2be980-6080-11ea-961b-a4afce91b45c.png)

Line 1774 is what adds the logs, line 1733 is what sets it to normal logs.

**Comment by MelvorIdle** [comment]
Hotfixed.
