### ISSUE TITLE
Occultist summon not working

### ISSUE THREAD

**Issue by remisthb** [MelvorIdle/melvoridle.github.io#1211]
**Describe the bug**
Occultist summon not reducing evasion ratings. Both base value and from synergies.

**To Reproduce**
If you add a occultist summon to your equip it lowers evasion initially but does not after the next enemy.

**Browser**
Steam client

**Comment by coolrox95** [comment]
Hotfixed as of Alpha v0.21 (?1105). Please restart your game for the changes to take effect.
