### ISSUE TITLE
unavoidable and fixed damage attacks consumes potion charges

### ISSUE THREAD

**Issue by AkylaZWN** [MelvorIdle/melvoridle.github.io#1212]
For example, when using sandstorm ring, each attack will consume an accuracy potion charge, which does not make sense since it is unavoidable. Plus, this causes the potions to run out exceedingly fast.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
