### ISSUE TITLE
Download Save timestamp

### ISSUE THREAD

**Issue by Rekkone** [MelvorIdle/melvoridle.github.io#1216]
Add timestamp to the name of Downloaded Savefiles.

**Why are you suggesting this?
How does your suggestion benefit the game?**
Small quality of life feature that removes the need to manually alter the name of save file before downloading it.

**It is suggested that you provide (mockup) art to ilustrate things where relevant in order to make your suggestion more clear.**
melvoridlesave_Charactername_dd.MM.yyyy_kk:mm.txt

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
