### ISSUE TITLE
Auto-Eat does not actually fill health to threshold with low efficiency

### ISSUE THREAD

**Issue by gridster2** [MelvorIdle/melvoridle.github.io#1217]
Auto-Eat does not factor in the auto-eat efficiency modifier when determining how much food should be eaten, potentially leaving the player's health below the auto-eat threshold.

**This potentially kills players using offline combat.**

In `player.js`, see the function `autoEat()`:

```
  autoEat() {
    if (
      this.hitpoints < this.autoEatThreshold &&
      this.food.currentSlot.item !== emptyFood
    ) {
      let foodQty = Math.ceil(
        (this.autoEatHPLimit - this.hitpoints) /
          this.getFoodHealing(this.food.currentSlot.item)
      );
      foodQty = Math.min(foodQty, this.food.currentSlot.quantity);
      this.eatFood(foodQty, false, this.autoEatEfficiency);
    }
  }
```

`foodQty ` is calculated based on the food's supposed healing value, which does not factor in auto-eat efficiency. Thus calling `this.eatFood` with `foodQty` can, for certain values of food healing and auto-eat efficiency, leave the player with too few hitpoints.

The easy fix is to just change `autoEat()` to a while loop:

```
  autoEat() {
    while (
      this.hitpoints < this.autoEatThreshold &&
      this.food.currentSlot.item !== emptyFood
    ) {
      this.eatFood(1, false, this.autoEatEfficiency);
    }
  }
```

Auto-Eat efficiency should increase the amount of food required to reach the threshold, but still ensure that the player's health is above the threshold.

**Comment by MelvorIdle** [comment]
Hotfixed pushed to live game. Alpha v0.21 (?1093)
