### ISSUE TITLE
Rolling for Signet Ring Half B causes combat to Error

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#122]
**Describe the bug**
Gaining the Signet Ring Half B from combat causes combat to error out.

**To Reproduce**
1. Equip the Gold Topaz Ring
2. Kill monsters until you roll for the Signet Ring Half B
3. Combat errors out

**Expected behavior**
The signet ring half B should be added to the bank

**Screenshot**
![image](https://user-images.githubusercontent.com/58208131/76152870-ea873a80-6081-11ea-92c0-fa036ef86135.png)

After rolling for the ring part, the loot code tries to find the index for the item in the monster loot table to get the quantity, but since it doesn't exist in the loot table it errors out on line 1872 of combat.js, as MONSTERS[enemy].lootTable[count][2] is undefined.

**Comment by MelvorIdle** [comment]
Hotifxed.
It now simply adds the ring half to the bank.
