### ISSUE TITLE
Items “missing” from inventory 

### ISSUE THREAD

**Issue by Elbrto** [MelvorIdle/melvoridle.github.io#1220]
![D2A8BD42-9018-483A-81B4-5B9EBF1F0888](https://user-images.githubusercontent.com/61185972/129489847-03dbe063-297d-46f4-9f37-df90a6da4754.png)
Hello I just noticed some of my items are not showing in inventory, it’s only some items not all of them
Playing on IOS

**Comment by nanobotkemo** [comment]
Had same issue happen today logged on got my offline progress from thieving. Came.back a second time and lost my crown and the progress up to it for a 16hr period
