### ISSUE TITLE
Oak Logs missing

### ISSUE THREAD

**Issue by Hyasuke** [MelvorIdle/melvoridle.github.io#1223]
During usual play I noticed after offline harvesting woodcutting, I never received any of my oak logs. 

Days have gone by and only now did I notice that none of my oak logs register once collected.

I still receive the “+1” and picture of the oak log at the bottom, but when I search my inventory nothing to be found. I have even attempted to type it in but not one single oak log appears in my inventory

**Comment by ngarcia610** [comment]
Confirming this issue on Firefox 91.0 (64-bit) for Ubuntu. The item takes up a spot in the bank, but is invisible and can't be sold. It does show up for firemaking, however.

**Comment by coolrox95** [comment]
Issue was resolved in an update.
