### ISSUE TITLE
View Equipment Stats in Golbin Raid is showing the equipment stats outside of raid

### ISSUE THREAD

**Issue by LvanderRijk** [MelvorIdle/melvoridle.github.io#1225]
**Describe the bug**
I went with a melee route in the Golbin raid and was trying to focus getting magic defense, since the magic users hit the hardest and most often. Yet when I had some nice magic defense going, it stayed on -1.

**To Reproduce**
1. Go to 'Golbin Raid'.
2. Select 'Magic defense oriented gear'.
3. See no positive change in magic defense.

**Expected behavior**
I expected to have a magic defense of about +50 to +100.

**Screenshots**
![Magic def bug Melvor Idle](https://user-images.githubusercontent.com/60172726/129528726-c0daf10c-afb4-42a8-91f9-054ccd5df414.PNG)

**Browser**
Google Chrome version 92.0.4515.131 (64-bits)

**Console output**
I had no time to do this.

**Are you using any scripts?**
I was not.

**Comment by LvanderRijk** [comment]
After reviewing myself a bit further, I can see that the equipment stats are from my main gear and not from my Golbin raid gear.
Do I have to close the thread and make a new one?

**Comment by coolrox95** [comment]
Issue has been resolved as of Alpha v0.21 (?1112).
