### ISSUE TITLE
gloves in store not shwoing the right numbers

### ISSUE THREAD

**Issue by AkylaZWN** [MelvorIdle/melvoridle.github.io#1226]
As shown in the screenshot, the display of the number of gloves and charges does not change and always shwo 1200. however this does not affect my purchase of different amount of gloves, just the display is wrong.

![image](https://user-images.githubusercontent.com/88955033/129529918-762775cf-2da1-4f56-a22e-e3cb8ca6b037.png)

**Comment by coolrox95** [comment]
Duplicate of #1210
