### ISSUE TITLE
Error calculating offline progress

### ISSUE THREAD

**Issue by Jdewey95** [MelvorIdle/melvoridle.github.io#1228]
Was casting superheat 3 for dragon bars in the background and it failed to calculate the progress once I moved back to the tab. Similar issue happened yesterday while I was fletching rune javs. Refreshing the page allows progress to continue.

<img width="415" alt="Screen Shot 2021-08-16 at 10 56 12 AM" src="https://user-images.githubusercontent.com/50993959/129584222-8181a7d6-d917-4765-9dbf-d9aae587e403.png">

**Comment by sekushi18** [comment]
Only came to +1 though mine happened from letting rags to riches go on for a long while.

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
