### ISSUE TITLE
Catching a chest while fishing can cause fishing to error and stop

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#123]
**Describe the bug**
Catching a chest can cause fishing to bug out due to the ring half check

**To Reproduce**
1. Start Fishing
2. Catch a chest
3. Fishing console errors and stops working

**Expected behavior**
Fishing should continue normally

**Screenshots**
![image](https://user-images.githubusercontent.com/58208131/76154583-08fa2f80-609c-11ea-8810-8b57c103ffa7.png)

This issue is caused by chests being removed from the fishingArea.currentFish array on line 233 of fishing.js . As a result the call to dropRingHalfA on line 236 causes an undefined error as fishingArea[a].currentFish[fish] no longer exists.

![image](https://user-images.githubusercontent.com/58208131/76154597-4b237100-609c-11ea-9524-952d11fc0287.png)

**Comment by MelvorIdle** [comment]
Hotfixed
