### ISSUE TITLE
Centaur summon cost 50 redwood bows

### ISSUE THREAD

**Issue by MrKomplex** [MelvorIdle/melvoridle.github.io#1232]
Im not sure if this intended but it cost 50 redwood bows (the rarest crafted bow) to produce centaur summon. Why is this? I feel like it should be just 1, just like the other summon recipe patterns. This is on iOS. 

*To Reproduce**

**Expected behavior**

**Screenshots**

**Browser**
Please tell us what browser you are using and what version.

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

**Comment by sylhaern** [comment]
This is intended, it's based on item sell price, not level

https://github.com/MelvorIdle/melvoridle.github.io/issues/1003
