### ISSUE TITLE
Alt-magic spells not unlocking on level up

### ISSUE THREAD

**Issue by kellewic** [MelvorIdle/melvoridle.github.io#1233]
**Describe the bug**
When I hit a level where a skill should unlock, I see the milestone message, but the skill is still listed as "Unlocked at Magic Level X". If I restart the game in Steam, the skills do unlock.

**To Reproduce**
Run alt-magic until a level that should unlock a skill.

**Expected behavior**
The skill should unlock

**Screenshots**
![Clipboard01](https://user-images.githubusercontent.com/3178267/129638625-fd39046a-fae7-49a4-a700-147f7eca8430.jpg)

**Browser**
Steam

**Console output**
Only works in browser. I'm using Steam client.

**Are you using any scripts?**
No

**Comment by coolrox95** [comment]
Issue has been hotfixed.
