### ISSUE TITLE
Summoning still has incorrect cost reduction at 99 mastery

### ISSUE THREAD

**Issue by Tykothorpe** [MelvorIdle/melvoridle.github.io#1234]
**Describe the bug**
Issue reported previously was listed as fixed in Alpha v0.21 but fix has not worked.
Previous issue: [1137](https://github.com/MelvorIdle/melvoridle.github.io/issues/1137)

Details exactly the same as previous bug report.

**Comment by MelvorIdle** [comment]
This is now fixed as of ?1318
