### ISSUE TITLE
Offline Combat Loot

### ISSUE THREAD

**Issue by bbussoli** [MelvorIdle/melvoridle.github.io#1235]
**Describe the bug**
Offline combat loot is being lost because of the lootbox acting as though it is full when it is emptied before closing the app.

**To Reproduce**
1. Start any combat training before closing app
2. Let some time pass to kill a few monsters at least
3. check loot that was dropped when opening the app
4. look for duplicate entries for the same item in the list. For example: looted 2 bronze daggers but lost X amount of bronze daggers due to a "full" lootbox

**Expected behavior**
All similar loot and loot up to the maximum allowed loot in the lootbox should be kept and any new items after that should be lost.

**Screenshots**
I have attached one screenshot that shows I have mithril items in my loot box but similar items were lost after closing the app.

**Browser**
Android, Alpha version (?1095)

**Are you using any scripts?**
No scripts are being run

**Comment by bbussoli** [comment]
![Melvor Idle_2021-08-16-17-26-59](https://user-images.githubusercontent.com/55526679/129647179-9b9097ad-94b0-4dd5-bc35-5d91099b2f76.jpg)

**Comment by MelvorIdle** [comment]
This is not a bug.

Loot does not stack inside the Loot container. Only Bones and Shards do.

Each dropped loot takes up 1 out of the 16 allocated slots. Once those slots are full, all other dropped items are lost.

**Comment by bbussoli** [comment]
Ah okay. I thought I had seen certain things stack.
