### ISSUE TITLE
Shop buy count not updating when changing buy value

### ISSUE THREAD

**Issue by TheRealPandaa** [MelvorIdle/melvoridle.github.io#1236]
**Describe the bug**
When changing the buy value of items in the shop, the count at the item doesn't change, the buy price does.
Noticed this since the latest update.
Restarting the client / pc had no effect to fixing this. 
But if I placed the buy count on 100 and restart the client. The item counter does change to a 100 and remains on that when swapping value again.

**To Reproduce**
No clue, play on the latest update?

**Expected behavior**
I expect, when changing the value of the buy count, it auto updates the item count

**Screenshots**
http://prntscr.com/1q1qxi5
http://prntscr.com/1q1r8lg

**Browser**
none / Client from steam

**Console output**
F12 doenst work on steam client?

**Are you using any scripts?**
Nope, wasn't even aware there were scripts for this...

**Comment by coolrox95** [comment]
Hotfixed as of Alpha v0.21 (?1105). Please restart your game for the changes to take effect.
