### ISSUE TITLE
Idling takes over Raid.

### ISSUE THREAD

**Issue by AWetSalmon** [MelvorIdle/melvoridle.github.io#1237]
I was doing raids and chose some really nice gear, even bought more bank space just so they would fit when I was done. 

After leaving the raid the farming thieving took presidency even though it was in the background while raiding (and had crap rewards) and filled my bank with seeds pushing out all my nice rare gear that I'm only supposed to be able to get once? 

Pretty upset with that tbh...

**Comment by MelvorIdle** [comment]
The Golbin Raid is a minigame and you cannot keep items you get from it.

**Comment by AWetSalmon** [comment]
Figured that out after a while haha sry
