### ISSUE TITLE
Item Alchemy not working with Woodcutting Mastery Pool +50% GP Value

### ISSUE THREAD

**Issue by Dresovious** [MelvorIdle/melvoridle.github.io#1239]
**Describe the bug**
While using Item Alchemy II in Alt. Magic on logs from Woodcutting, I was not receiving their total value when Woodcutting is over 50% Mastery.

**To Reproduce**
1. Go to Alt. Magic and select Item Alchemy II, choose any log item in bank as the target.
2. Click cast.
3. Compare spell GP gained with log value in bank.
4. See error.

**Expected behavior**
I expected the Woodcutting Mastery Pool benefit of increasing all log values increased by 50% to also apply when using Item Alchemy on them.

**Screenshots**

**Browser**
Chrome, most up to date version as of 8/17/2021

**Console output**
![Melvor Bug Report 3 of 3 2021-08-17](https://user-images.githubusercontent.com/89102881/129790763-3e372913-28e7-439e-84bd-01b8c777d2cc.png)
![Melvor Bug Report 1 of 3 2021-08-17](https://user-images.githubusercontent.com/89102881/129790767-c8adbf88-0459-4b37-902c-7c5b1b28cb29.png)
![Melvor Bug Report 2 of 3 2021-08-17](https://user-images.githubusercontent.com/89102881/129790768-4b2bf767-f385-475b-9b94-ddf0e861cbfd.png)

**Are you using any scripts?**
No.

**Comment by coolrox95** [comment]
Item alchemy only works on an items base sale price. This is intended.
