### ISSUE TITLE
Slayer task bug

### ISSUE THREAD

**Issue by Saviticus** [MelvorIdle/melvoridle.github.io#124]
**Describe the bug**
Getting into slayer zoned that have equiped item requirements without the items equipped
**To Reproduce**
1. Make sure you have no required items to get into strange cave or highlands  
2. Click on new task in slayer task pannel till a monster from either afforementioned  zone shows up
3. Click on the monster's name to go into combat

**Expected behavior**
I expected not to go into combat because I didn't have the mirror shield equipped
**Screenshots**
N/A
**Browser**
Please tell us what browser you are using and what version.
Chrome version 80.0.3987.132
**Console output**
Please open the console by pressing F12 and copy it here.
VM3042 index.php:17 GET https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js net::ERR_BLOCKED_BY_CLIENT
DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map
VM3042 index.php:391 GET https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js net::ERR_BLOCKED_BY_CLIENT
DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map
save.js?225:44 Loading Save Game...
save.js?225:206 Save Game Loaded...
save.js?225:44 Loading Save Game...
save.js?225:206 Save Game Loaded...
mastery.js?203:156 Updating Masteries
mastery.js?203:23 Loading Masteries...
smithing2.js?206:188 Loading Smithing...
main.js?240:990 Game Loaded
cloud.js?209:45 Melvor Cloud Connection: Success
save.js?225:44 Loading Save Game...
save.js?225:206 Save Game Loaded...
mastery.js?203:156 Updating Masteries
mastery.js?203:23 Loading Masteries...
smithing2.js?206:188 Loading Smithing...
main.js?240:990 Game Loaded
2farming.js?206:595 Uncaught TypeError: Cannot read property 'mastery' of undefined
    at growCrops (farming.js?206:595)
    at farming.js?206:586
growCrops @ farming.js?206:595
(anonymous) @ farming.js?206:586
setTimeout (async)
startSeedTimer @ farming.js?206:585
startSeedTimer @ farming.js?206:577
updateWindow @ main.js?240:952
loadGame @ save.js?225:285
onclick @ VM3203 index.php:6587

**Comment by MelvorIdle** [comment]
Hotfixed
