### ISSUE TITLE
Agility debuffs no longer halved on 99 mastery

### ISSUE THREAD

**Issue by Coresfx** [MelvorIdle/melvoridle.github.io#1240]
After the new version all of my agility red debuffs are full values at 99 mastery.

I tried loading an older version of my save incase something went wrong with it, but same result.

Using Steam version.

No other scripts in use.
![agility](https://user-images.githubusercontent.com/63090934/129811085-f180036e-f9f6-4667-a30f-3a846b132988.jpg)

**Comment by coolrox95** [comment]
Duplicate of #1202
