### ISSUE TITLE
Lucky Herb Potion III moves a different item when clicking and dragging to a different bank tab

### ISSUE THREAD

**Issue by marth138** [MelvorIdle/melvoridle.github.io#1241]
When clicking and dragging the Lucky Herb Potion III to a different bank tab it will not move the potion, but instead a different item in the same tab. I was eventually able to move the potion after trying ~15 times and moving most of the bank tab. 

**To Reproduce**
1. Have Lucky Herb Potion III in a bank tab, mine was in my first tab after getting reset from the previous update.
2. Click on Lucky Herb Potion III, hold and drag to an existing bank tab
3. Release mouse while over a different bank tab

**Expected behavior**
I expected the Lucky Herb Potion III to move to the other bank tab

**Screenshots**

**Browser**
Google Chrome Version 92.0.4515.131

**Console output**
www.googletagmanager.com/gtag/js?id=UA-129674422-1:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
MICSR.js:26 MICSR: setting up util
MICSR.js:26 MICSR: setting up playerSpecialNames
specialNames.js:138 Uncaught ReferenceError: playerSpecialAttacks is not defined
    at setup (specialNames.js:138)
    at waitLoadOrder (specialNames.js:177)
    at specialNames.js:181
    at specialNames.js:183
MICSR.js:26 MICSR: setting up statNames
MICSR.js:26 MICSR: unknown item property attackSpeed
MICSR.js:26 MICSR: unknown item property isTwoHanded
MICSR.js:26 MICSR: unknown item property specialAttackID
MICSR.js:26 MICSR: unknown item property equipmentSlot
MICSR.js:26 MICSR: unknown item property isPassiveItem
MICSR.js:26 MICSR: unknown item property damageReduction
MICSR.js:26 MICSR: unknown item property defenceBonus
MICSR.js:26 MICSR: unknown item property magicDefenceBonus
MICSR.js:26 MICSR: unknown item property rangedDefenceBonus
MICSR.js:26 MICSR: unknown item property attackBonus
MICSR.js:26 MICSR: unknown item property strengthBonus
MICSR.js:26 MICSR: unknown item property isAmmo
MICSR.js:26 MICSR: unknown item property rangedAttackBonus
MICSR.js:26 MICSR: unknown item property rangedStrengthBonus
MICSR.js:26 MICSR: unknown item property isMagic
MICSR.js:26 MICSR: unknown item property magicAttackBonus
MICSR.js:26 MICSR: unknown item property magicDamageBonus
MICSR.js:26 MICSR: unknown item property slayerBonusXP
MICSR.js:26 MICSR: unknown item property canUseMagic
MICSR.js:26 MICSR: unknown item property increasedWaterSpellDamage
MICSR.js:26 MICSR: unknown item property gpMultiplierCap
MICSR.js:26 MICSR: unknown item property gpMultiplierMin
MICSR.js:26 MICSR: unknown item property chanceToCrit
MICSR.js:26 MICSR: unknown item property critDamage
MICSR.js:26 MICSR: unknown item property decreasedAttackSpeed
MICSR.js:26 MICSR: unknown item property reflectDamage
MICSR.js:26 MICSR: unknown item property chanceToDoubleLoot
MICSR.js:26 MICSR: unknown item property gpMultiplier
MICSR.js:26 MICSR: unknown item property increasedGP
MICSR.js:26 MICSR: unknown item property ammoPreservation
MICSR.js:26 MICSR: unknown item property spellHeal
MICSR.js:26 MICSR: unknown item property hpRegenBonus
MICSR.js:26 MICSR: unknown item property increasedHPRegen
MICSR.js:26 MICSR: unknown item property increasedMaxHitpoints
MICSR.js:26 MICSR: unknown item property lifesteal
MICSR.js:26 MICSR: unknown item property decreasedAutoEatEfficiency
MICSR.js:26 MICSR: unknown item property increasedAutoEat
MICSR.js:26 MICSR: unknown item property prayerCostReduction
MICSR.js:26 MICSR: unknown item property summoningMaxHit
MICSR.js:26 MICSR: unknown item property attackLevelRequired
MICSR.js:26 MICSR: unknown item property defenceLevelRequired
MICSR.js:26 MICSR: unknown item property magicLevelRequired
MICSR.js:26 MICSR: unknown item property rangedLevelRequired
MICSR.js:26 MICSR: unknown item property slayerLevelRequired
MICSR.js:26 MICSR: unknown item property prayerBonus
MICSR.js:26 MICSR: unknown item property slayerAreaEffectNegationPercent
MICSR.js:26 MICSR: unknown item property increasedMinAirSpellDmg
MICSR.js:26 MICSR: unknown item property increasedMinEarthSpellDmg
MICSR.js:26 MICSR: unknown item property increasedMinFireSpellDmg
MICSR.js:26 MICSR: unknown item property increasedMinWaterSpellDmg
MICSR.js:26 MICSR: unknown item property craftingID
MICSR.js:26 MICSR: unknown item property fishingSpeedBonus
MICSR.js:26 MICSR: unknown item property fletchingID
MICSR.js:26 MICSR: unknown item property smithingID
MICSR.js:26 MICSR: unknown item property increasedSuccessRate
MICSR.js:26 MICSR: unknown item property baseChanceToPreserve
MICSR.js:26 MICSR: unknown item property bonusMasteryXP
MICSR.js:26 MICSR: unknown item property bonusSkillXP
MICSR.js:26 MICSR: unknown item property canEquip
MICSR.js:26 MICSR: unknown item property chanceToDoubleResources
MICSR.js:26 MICSR: unknown item property chanceToPreserve
MICSR.js:26 MICSR: unknown item property slayerCost
MICSR.js:26 MICSR: unknown item property slayerTaskRequirement
MICSR.js:26 MICSR: setting up modifierNames
modifierNames.js:342 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyNames (<anonymous>)
    at new MICSR.ShowModifiers (modifierNames.js:342)
    at setup (modifierNames.js:848)
    at waitLoadOrder (modifierNames.js:895)
    at modifierNames.js:899
    at modifierNames.js:901
MICSR.js:26 MICSR: AgilityCourse is waiting for modifierNames
MICSR.js:26 MICSR: AgilityCourse is waiting for Card
MICSR.js:26 MICSR: setting up Card
MICSR.js:26 MICSR: setting up Import
MICSR.js:26 MICSR: setting up Loot
MICSR.js:26 MICSR: setting up Plotter
MICSR.js:26 MICSR: setting up Menu
MICSR.js:26 MICSR: setting up Simulator
MICSR.js:26 MICSR: setting up TabCard
MICSR.js:26 MICSR: main is waiting for App
MICSR.js:26 MICSR: setting up CombatData
MICSR.js:26 MICSR: App is waiting for AgilityCourse
MICSR.js:26 MICSR: App is waiting for modifierNames
app.bundle.js:30 Uncaught Unable to find #nav-menu-show. Cannot create stat-tracker-container
cloud.js?1095:76 Connected to PlayFab successfully
​ Failed to load AgilityCourse
​ Failed to load main
​ Failed to load App
save.js?1095:57 set force reload to 0
combatManager.js?1095:1 Combat Manager Built...
raidManager.js?1095:1 Golbin Raid Manager Built...
save.js?1095:14 Loading Save Game...
save.js?1095:14 Save Game Loaded...
main.js?1095:5 Game Loaded
baseManager.js?1095:17 Took 0.4265s to process 382394 ticks. 0.0011153417679147686ms per tick.
cloud.js?1095:8 Synchronising with Cloud
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloud.js?1095:76 Connected to PlayFab successfully
bank.js?1095:137 Helmet
bank.js?1095:137 Passive
bank.js?1095:137 Helmet
bank.js?1095:137 Passive
bank.js?1095:137 Helmet
bank.js?1095:137 Passive
bank.js?1095:137 Platelegs
bank.js?1095:137 Passive
bank.js?1095:137 Platelegs
bank.js?1095:137 Passive
bank.js?1095:137 Platelegs
bank.js?1095:137 Passive
bank.js?1095:137 Boots
bank.js?1095:137 Passive
bank.js?1095:137 Boots
bank.js?1095:137 Passive
bank.js?1095:137 Boots
bank.js?1095:137 Passive
bank.js?1095:137 Gloves
bank.js?1095:137 Passive
bank.js?1095:137 Gloves
bank.js?1095:137 Passive
bank.js?1095:137 Gloves
bank.js?1095:137 Passive
4bank.js?1095:137 Ring
2bank.js?1095:137 Weapon
bank.js?1095:137 Platebody
bank.js?1095:137 Passive
bank.js?1095:137 Platebody
bank.js?1095:137 Passive
2bank.js?1095:137 Weapon
2bank.js?1095:137 Cape
3bank.js?1095:137 Weapon
main.js?1095:245 true
bank.js?1095:137 Weapon
main.js?1095:245 true
bank.js?1095:137 Ring
35bank.js?1095:193 Set Timeout: updateSummonRecipeSelection
main.js?1095:245 true
main.js?1095:234 You found 3 Marks Offline
bank.js?1095:137 Shield
bank.js?1095:137 Passive
bank.js?1095:137 Shield
bank.js?1095:137 Passive
3bank.js?1095:137 Cape
2bank.js?1095:137 Helmet
4bank.js?1095:137 Platebody
bank.js?1095:137 Shield
bank.js?1095:137 Passive
bank.js?1095:137 Shield
bank.js?1095:137 Passive
2bank.js?1095:137 Platelegs
2bank.js?1095:137 Boots
2bank.js?1095:137 Weapon
bank.js?1095:137 Shield
bank.js?1095:137 Passive
bank.js?1095:137 Shield
bank.js?1095:137 Passive
bank.js?1095:137 Ring
bank.js?1095:137 Passive
bank.js?1095:137 Ring
bank.js?1095:137 Passive
bank.js?1095:137 Amulet
bank.js?1095:137 Passive
bank.js?1095:137 Amulet
bank.js?1095:137 Passive
bank.js?1095:137 Shield
bank.js?1095:137 Passive
bank.js?1095:137 Shield
bank.js?1095:137 Passive
bank.js?1095:137 Platebody
bank.js?1095:137 Passive
bank.js?1095:137 Platebody
bank.js?1095:137 Passive
bank.js?1095:137 Helmet
bank.js?1095:137 Passive
bank.js?1095:137 Helmet
bank.js?1095:137 Passive
5bank.js?1095:137 Gloves
bank.js?1095:137 Passive
3bank.js?1095:137 Gloves
3main.js?1095:245 true
cloud.js?1095:76 Connected to PlayFab successfully
main.js?1095:245 true
3bank.js?1095:137 Helmet
11main.js?1095:245 true
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
main.js?1095:245 

**Are you using any scripts?**
No Scripts, but I have the Combat sim and Stat Tracker plugins, but they aren't working currently with the new update.

**Comment by coolrox95** [comment]
Issue was resolved with Alpha V0.22.1.
