### ISSUE TITLE
Bug: food consumption 100x higher

### ISSUE THREAD

**Issue by Getknived** [MelvorIdle/melvoridle.github.io#1242]
https://user-images.githubusercontent.com/89134896/129883389-4865aaff-1eda-45cd-9ff1-739b188ff5b8.MOV

**Describe the bug**
Food intake is approximately 100x higher with auto eat against turkul giant. 

**To Reproduce**
Equipment worn: 
- Desert hat
- (g) mithril platebody
- (G) mithril shield
- (G) mithril boots
- (G) mithril legs
- Rune gloves
- Elite amulet of strength
- Rune scimitar
- Silver diamond ring

auto eat II

Adventure mode

Discovered it with strawberries (~1200 eaten in 9 minutes offline progression)

reproduced it with snapegrass (see video)

**Expected behavior**
Food consumption should be ~100 times lower

**Screenshots

**Browser**
Mobile app

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

**Comment by coolrox95** [comment]
Hotfixed as of Alpha v0.21 (?1105). Please restart your game for the changes to take effect.
