### ISSUE TITLE
Incorrect monster drops shown in Infernal Stronghold.

### ISSUE THREAD

**Issue by AbyssionQC** [MelvorIdle/melvoridle.github.io#1245]
**Describe the bug**
The "View Monster Drops" button shows incorrect drops for Infernal Stronghold monsters (except for Malcs). It shows a guaranteed bone drop and up to 1x Lemon as a possible extra drop.

**To Reproduce**
1. Go to 'Infernal Stronghold'
2. Click on 'View Monster Drops'

**Expected behavior**
No item should appear in the drop table.

**Screenshots**

![](https://i.imgur.com/oGe3Jo3.png)

**Browser**
I am playing on the Steam version.

**Console output**
Can't get the console output.

**Are you using any scripts?**
No scripts.

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
