### ISSUE TITLE
Ranged Strength Potion not using charges with centaur/dragon equipped

### ISSUE THREAD

**Issue by mjsterling** [MelvorIdle/melvoridle.github.io#1247]
Ranged Strength Potion is applying it's full effect but not using any charges when centaur/dragon synergy is equipped

1. Equip centaur dragon synergy
2. Equip Ranged Strength Potion (any tier)
3. Go shoot shit

Expected Behaviour: potion charges should deplete every attack and they are not.

Android app. No scripts/extensions.

![Screenshot_20210819-123503_Melvor Idle.jpg](https://user-images.githubusercontent.com/34150671/129998842-2b16d548-bf7a-4107-bf1c-dcf18ba223d5.jpg)

**Comment by coolrox95** [comment]
Issue was resolved in an update.
