### ISSUE TITLE
Malc's sealing attack does not reduce damage reduction, but increases its own attack damage

### ISSUE THREAD

**Issue by AkylaZWN** [MelvorIdle/melvoridle.github.io#1248]
**Describe the bug**
shown in screenshots, comparing malc's damage before and after the player is sealed. My DR is 47%, Malc's max damage (tail whip) is 365, but becomes 475 after sealing.

**To Reproduce**
not too sure, this is just my 5th run in infernal stronghold, and I died the 2nd around....

**Screenshots**
![1](https://user-images.githubusercontent.com/88955033/130004374-992b30b4-fee1-4e3b-85d4-8f1fe2f29881.png)
![3](https://user-images.githubusercontent.com/88955033/130004379-3365d280-c632-4766-916f-8c95840cda21.png)

**Browser**
I play from steam, Ver 0.21 (?1101)

**Comment by coolrox95** [comment]
Sealing applies a stun effect to character, which increases the damage you take from attacks by +30%. (See the tooltip when you hover over the yellow sparks icon under your hitpoints bar). This behavior is intended.
