### ISSUE TITLE
Creating the Signet Ring Consumes 2million GP instead of 1million

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#125]
**Describe the bug**
Upgrading items with multiple ingredients causes the game to charge gp once per ingredient.

**To Reproduce**
1. Collect the parts for the signet ring
2. Upgrade them in the bank
3. 2 Million GP is charged

**Expected behavior**
Only 1 Million Gp should be charged

**Screenshots**
![image](https://user-images.githubusercontent.com/58208131/76168966-c25b1280-6139-11ea-809b-e1648f9b9560.png)

This error lies on line 1065 of bank.js. The gp reduction should be moved outside of the for loop.

**Comment by MelvorIdle** [comment]
Hotfixed
