### ISSUE TITLE
[Adventure] Alt. Magic "Just Learning" Finds "That item doesn't exist."

### ISSUE THREAD

**Issue by nickolaos** [MelvorIdle/melvoridle.github.io#1250]
**Describe the bug**
In Adventure Mode: while attempting to use _Just Learning_ in Alt. Magic, the game throws back, "that item doesn't exist." 

Screenshot will indicate the input items exist. The second screenshot shows what is currently unlocked in my playthrough.

**To Reproduce**
1. Go to 'Alt. Magic'
2. Click on 'Just Learning'
3. Click on 'Cast'

**Expected behavior**
After clicking 'Cast', rune essences would be produced and input items would be consumed.

**Screenshots**
![Melvor_Idle_gmP3hVXaQ8](https://user-images.githubusercontent.com/18318058/130100333-7dc679d5-eebd-4b50-bd20-0195e1063591.png)
![Melvor_Idle_oNCx66usdR](https://user-images.githubusercontent.com/18318058/130100925-71748896-de5d-4af7-aa99-853be94b45a1.png)

**Browser**
1. Latest Steam Version
2. Game v0.21 (?1103)

**Comment by coolrox95** [comment]
You need to click the image and select an item to transform into rune essence first in order to cast this spell.
