### ISSUE TITLE
Thieving stun at level 99

### ISSUE THREAD

**Issue by mitsushiragnarok** [MelvorIdle/melvoridle.github.io#1252]
**Describe the bug**
In the description of thieving it says max is 95% unless 99 because at 99 you have no fail attempts but in the photo I am being stunned but am also already 99 thieving.

**To Reproduce**
I'm level 99 thieving and still getting stunned that's what the photo is below.

**Expected behavior**
Not be stunned

**Screenshots**
![image](https://user-images.githubusercontent.com/70246556/130183905-e19989b7-59e1-4d59-ad37-f2e475573a93.png)

**Browser**
Steam browser and version ?1103

**Console output**
F12 isn't opening anything for me

**Are you using any scripts?**
nope it's just the stock game

**Comment by coolrox95** [comment]
The description says "Level 99 Mastery", which is the individual mastery level for that NPC (the number to the right  of the trophy icon in the bottom left of the NPC). Working as intended.
