### ISSUE TITLE
Purchasing 100x of 100x of Compost only gives 100x Compost.

### ISSUE THREAD

**Issue by lob-star** [MelvorIdle/melvoridle.github.io#1253]
By changing the blue 'Buy 1x' button to 'Buy 100x' the price on compost changes to 50,000 and the confirmation screen shows 100x for 50,000 and it withdraws the 50K but you only get 100 Compost and not the expected (100x100) Compost.

**Comment by coolrox95** [comment]
I'm assuming this is just confusion over the item quantities and prices not updating properly as per #1236 (this has since been fixed) Setting the buy button to 100x is meant to allow you to purchase 100 compost at once.
