### ISSUE TITLE
Clearing a specific website's "cookies and site data" in Firefox deletes local save game data on Melvor's website, even if I didn't clear the data on Melvor's website. 

### ISSUE THREAD

**Issue by johnyuki** [MelvorIdle/melvoridle.github.io#1254]
**Describe the bug**
See title

**To Reproduce**
1. Open Firefox browser. 
2. Go to Melvor website and create a local save, let it run for a bit, and then close and re-open to site to make sure the save is 100% saved fine.
3. Go to any site that isn't Melvor. I used the BBC website as an example. 
4. On the left hand side of the address bar, press the padlock icon, followed by "clear cookies and site data".
5. You'll notice the dialog box says that only the data for that specific website will be deleted. Go ahead and press the "remove" button.
6. Go back to Melvor's website, and you'll notice that the save game is now deleted.

**Expected behavior**
Melvor's local save game doesn't get deleted

**Screenshots**

**Browser**
Firefox 91.0.1

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
No.

**Comment by coolrox95** [comment]
This is an issue with Firefox itself and not the game. Please direct your report to their [bugtracker](https://bugzilla.mozilla.org/) .

**Comment by johnyuki** [comment]
But this doesn't happen with any other site? It only happens with Melvor's site. If it's only happening with Melvor's site then surely it's something to do with the site and not the entire browser?
