### ISSUE TITLE
an upgrade to automatically change equipment sets based on next monster battle type

### ISSUE THREAD

**Issue by Hellenme** [MelvorIdle/melvoridle.github.io#1255]
I think it would be nice to be able to buy an upgrade which gives the option to automatically swap equipment set when you get a new monster, and choose which equipment set is swapped to, based on monster battle style. for example, if monster is melee, change to set #1, if monster is ranged, change to set #3, etc.  
Of course, you'd still have to make sure all the sets are appropriately equipped, you have sufficient ammo/ runes/ food, etc.

![auto change equipment set](https://user-images.githubusercontent.com/89260346/130249620-261d7b6b-9a4a-42e8-bfb3-b2f544085655.png)

**Why are you suggesting this?**
I think it ties in nicely with the new ability to combat offline.

**How does your suggestion benefit the game?**
It will help make offline completion of slayer tasks and dungeons more efficient, and will reduce the chance to die offline due to getting debuffed modifiers because you had a disadvantaged battle style to a monster you got automatically in a new slayer task/ next monster in a dungeon.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
