### ISSUE TITLE
Sent Back to Menu

### ISSUE THREAD

**Issue by Wardyyy** [MelvorIdle/melvoridle.github.io#1256]
Today I experienced an issue with  being sent back to the menu several times and doesn’t seem to follow a specific pattern. I’m playing on my iPad and while smithing, it sends me back to the main screen.  I haven’t tried any other skill but has only happened with smithing.

**Comment by Wardyyy** [comment]
When it sends me back to the main menu, it’ll reload me back to the main menu again. Almost like an endless loop of refreshing.

**Comment by coolrox95** [comment]
Issue was resolved with iOS app update.
