### ISSUE TITLE
Ranged has increased damage against Slayer Area monsters

### ISSUE THREAD

**Issue by Rekkone** [MelvorIdle/melvoridle.github.io#1258]
**Describe the bug**
When using Ranged weapons and fighting against Slayer Area monsters, damage is increased.

**To Reproduce**
1. Equip ranged weapon.
2. Fight against any Slayer Area monsters.
3. Damage is being increased for no reason.

**Expected behavior**
Damage should stay the same. No such issue with Melee and Magic combat skills.

**Screenshots**
1. [Normal Bow damage](https://i.imgur.com/nLrfNVV.png)
2. [Bow damage against Slayer Area monster](https://i.imgur.com/Fv4qNFT.png)
3. [Normal Javelin damage](https://i.imgur.com/9BqQYWq.png)
4. [Javelin damage against Slayer Area monster](https://i.imgur.com/JzPfMnk.png)
5. [Fresh account, Throwing Knives normal damage](https://i.imgur.com/jEmbGTo.png)
6. [Fresh account, Throwing Knives increased damage in Slayer Area](https://i.imgur.com/LuxBq1K.png)

**Browser**
Firefox 84.0.2

**Are you using any scripts?**
Nope.

**Comment by Rekkone** [comment]
Looks like [Slayer's Crossbow bonus](https://i.imgur.com/aJOXcwv.png) is being applied there.


Probably should be a Slayer's Crossbow check somewhere there.
`strengthBonus+=this.modifiers.summoningSynergy_7_8;if(this.manager.onSlayerTask||this.manager.areaType==="Slayer")`

**Comment by coolrox95** [comment]
Issue has been resolved as of Alpha v0.21 (?1112).
