### ISSUE TITLE
Alt. Magic doesn't highlight in sidebar when being trained

### ISSUE THREAD

**Issue by smithk58** [MelvorIdle/melvoridle.github.io#1262]
**Describe the bug**
When training Alt. Magic it doesn't highlight the skill green in the sidebar. Magic skill in the combat section is highlighted though.

**To Reproduce**
1. Use any Alt. Magic spell.
2. In your sidebar Alt. Magic won't be highlighted green.

**Expected behavior**
It seems like either Alt. Magic should be highlighted or perhaps both Alt. Magic and Magic.

**Browser**
Steam version Alpha V0.21 (?1106)

**Are you using any scripts?**
No

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
