### ISSUE TITLE
Golbin Raid Rune cost reduction using reduction from outside raid

### ISSUE THREAD

**Issue by ermoir** [MelvorIdle/melvoridle.github.io#1266]
While in the Golbin Raid, weapons that reduce the rune cost of spells are not reducing the costs properly. It looks like the rune spell reduction that's on your main character is affecting the rune cost of spells, not the rune cost reduction of what is on your character in the raid.
I'm using a Fire Imbued wand in the Golbin Raid and it doesn't reduce the cost of any fire spell, but my character outside of the raid is using the Ocean Song weapon with the Completionist cape and it's reducing the cost of water spells while in the Golbin Raid by 8.

**Comment by coolrox95** [comment]
Issue has been resolved as of Alpha v0.21 (?1112).
