### ISSUE TITLE
Typo in settings

### ISSUE THREAD

**Issue by delster** [MelvorIdle/melvoridle.github.io#1267]
Under _Notification Settings_...

Current string: _Show "You are now Alseep" Notifications in Combat._
Correct string: _Show "You are now Asleep" Notifications in Combat._

The word **asleep** is misspelled. 

![image](https://user-images.githubusercontent.com/3092124/130545147-9d43d25c-3c26-4593-81c8-d1760d3b0395.png)

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
