### ISSUE TITLE
The way local/cloud saves function can cause data loss in through cloud backups and hardcore deaths when interacted with in strange ways.

### ISSUE THREAD

**Issue by Makoprima** [MelvorIdle/melvoridle.github.io#1268]
**Describe the bug**
Because local saves interact with cloud saves based on their number slot (eg #1, #2, #3) and vice versa, this can cause several issues regarding save data and the loss of such.

Some examples include:
Backing up a local save listed as file 1, which will overwrite the save on cloud 1.
Dying on a local hardcore save listed as file 2, which will delete both itself and the save on cloud 2.
Dying on a **CLOUD**  hardcore save listed as file 3, which will delete both itself and the save on local 3.

The last two examples even apply if the other save is not a hardcore character.

**To Reproduce**
An example of how a normal player can encounter this and lose data is
1. A player uses a new device and creates a local character. This creates said character in file 1.
2. The player decides to back up their save after logging in.
3. This overwrites their cloud data in file 1, though this can happen with other files if multiple saves are created.

**Expected behavior**
I expect that differing saves should not interact with one another in this way, the fact that hardcore deaths and cloud backups are tied to save slots cause some strange interactions like this.

A possible fix could be being able to choose and adjust the slot of saves when backing them up to the cloud, or not having hardcore saves delete non-hardcore cloud/local saves upon death.

**Screenshots**
Likely not applicable.

**Browser**
I used the latest version of firefox and steam to test this.

**Console output**
I don't believe this is necessary for this.

**Are you using any scripts?**
None.

**Comment by MelvorIdle** [comment]
We are looking to implement a new save "slot" system to resolve this issue. Closing now as it is a WIP
