### ISSUE TITLE
Fishing Amulet in Golbin Raid is Broken

### ISSUE THREAD

**Issue by agent8364** [MelvorIdle/melvoridle.github.io#1269]
I was in a golbin raid, and equipped my fishing amulet so I could fish while doing it, I went back to the raid and all the equipment was replaced with my combat setup and I could unequip it all. (I was not given the stats from the items, and all gear was reset after taking a new item)
1. Begin a Golbin raid
2. Equip a fishing amulet, or barbarian gloves
3. Go back to the raid
4. You should see whatever equipment you have without being in the raid.
I expect to see my normal raid gear after going back into it.
I am using the newest version and on google browser
**Console output**
ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
www.googletagmanager.com/gtag/js?id=UA-129674422-1:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
oneui.core.min.js:6 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ oneui.core.min.js:6
combatManager.js?1106:1 Combat Manager Built...
raidManager.js?1106:1 Golbin Raid Manager Built...
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
Chart.bundle.min.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
cloud.js?1106:76 Connected to PlayFab successfully
Chart.bundle.min.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
​ jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
save.js?1106:57 set force reload to 0
combatManager.js?1106:1 Combat Manager Built...
raidManager.js?1106:1 Golbin Raid Manager Built...
save.js?1106:14 Loading Save Game...
save.js?1106:14 Save Game Loaded...
main.js?1106:5 Game Loaded
baseManager.js?1106:17 Took 1.0355s to process 864000 ticks. 0.0011984953703703704ms per tick.
cloud.js?1106:8 Synchronising with Cloud
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
Chart.bundle.min.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
cloud.js?1106:76 Connected to PlayFab successfully
Chart.bundle.min.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
bank.js?1106:137 Helmet
bank.js?1106:137 Weapon
bank.js?1106:137 Helmet
2bank.js?1106:137 Weapon
bank.js?1106:137 Helmet
2bank.js?1106:137 Weapon
bank.js?1106:137 Amulet
2bank.js?1106:137 Ring
22main.js?1106:245 true
cloud.js?1106:8 Synchronising with Cloud
2main.js?1106:245 true
bank.js?1106:137 Amulet
main.js?1106:245 true
2bank.js?1106:137 Boots
bank.js?1106:137 Shield
2bank.js?1106:137 Helmet
bank.js?1106:137 Shield
bank.js?1106:137 Boots
bank.js?1106:137 Helmet
bank.js?1106:137 Shield
bank.js?1106:137 Boots
3bank.js?1106:137 Shield
8bank.js?1106:137 Platebody
11main.js?1106:245 true
bank.js?1106:137 Amulet
main.js?1106:245 true
bank.js?1106:137 Platebody
73main.js?1106:245 true
3bank.js?1106:137 Platebody
bank.js?1106:137 Cape
bank.js?1106:137 Boots
2bank.js?1106:137 Quiver
bank.js?1106:137 Platelegs
bank.js?1106:137 Cape
bank.js?1106:137 Boots
bank.js?1106:137 Platebody
bank.js?1106:137 Boots
2bank.js?1106:137 Platebody
bank.js?1106:137 Platelegs
bank.js?1106:137 Platebody
bank.js?1106:137 Gloves
bank.js?1106:137 Platebody
bank.js?1106:137 Gloves
bank.js?1106:137 Shield
bank.js?1106:137 Platelegs
bank.js?1106:137 Platebody
bank.js?1106:137 Gloves
bank.js?1106:137 Cape
bank.js?1106:137 Weapon
2bank.js?1106:137 Quiver
bank.js?1106:137 Boots
bank.js?1106:137 Summon1
bank.js?1106:137 Summon2
bank.js?1106:137 Quiver
baseManager.js?1106:17 Took 2.1659000000357627s to process 864000 ticks. 0.0025068287037450956ms per tick.
cloud.js?1106:76 Connected to PlayFab successfully
3bank.js?1106:137 Boots
8main.js?1106:245 true
bank.js?1106:137 Cape
bank.js?1106:137 Platelegs
2main.js?1106:245 true
2bank.js?1106:137 Amulet
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
No I am not using any scripts

![image](https://user-images.githubusercontent.com/43283317/130660074-e4888001-d538-473d-9a67-7f238b677d97.png)

**Comment by coolrox95** [comment]
Issue has been resolved as of Alpha v0.21 (?1112).
