### ISSUE TITLE
Goblin raid glitch

### ISSUE THREAD

**Issue by Compromised1111** [MelvorIdle/melvoridle.github.io#1270]
**Describe the bug**
I was in the middle of goblin raid, was at round 46 or so and I got a phone call. After trying to go back to melvor idle it sent me back to the skills page and gave me no credit besides the amount of goblins killed. After spending over 30 minutes playing it was definitely annoying. I tried to go start goblin raid again in hopes id be back to where I was but it restarted me. 
![Screenshot_20210824-120427_Melvor Idle](https://user-images.githubusercontent.com/89476877/130660456-09957136-b4c0-4e42-905b-7441a42e15bf.jpg)
![Screenshot_20210824-113913_Melvor Idle](https://user-images.githubusercontent.com/89476877/130660480-f3001619-4206-4b32-903a-fb4e6e5e49f6.jpg)

**Comment by MelvorIdle** [comment]
A few fixes to address this was added in the last few patches. Please reopen a new report if issue persists.
