### ISSUE TITLE
Align Agility Milestones with Other Skills

### ISSUE THREAD

**Issue by sylhaern** [MelvorIdle/melvoridle.github.io#1271]
The formula for mastery experience scales partially off of unlocked milestones in a skill * % of skill mastery completed

For every other skills with Mastery, there is 1 milestone for each item to master, + 1 for level 99.  For Agility, there are 12 total milestones for 48 items with mastery.  This results in Agility giving less slower mastery xp than other skills

Suggestion:  Change the milestones from Agility from Obstacle 1, Obstacle 2, Obstacle 3 etc. to having 1 milestone for each obstacle

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
