### ISSUE TITLE
Tweak Firemaking Mastery

### ISSUE THREAD

**Issue by sylhaern** [MelvorIdle/melvoridle.github.io#1272]
Firemaking is one of the skills that scales Mastery XP against the lowest possible seconds per action, but it's fixed at 60% of base burn interval now, while with the addition of summoning, you can get firemaking interval down to 56.1% of base.  This lets you get mastery xp ~7% faster than intended / other skills

Suggestion 1:  Set the firemaking interval for mastery xp calculations to 56% or 56.1% of base interval OR PREFERRED
Suggestion 2:  Simplify mastery xp calculations to work off of actual skill intervals for all skills

As is, Firemaking, Cooking, Smithing, Fletching, Crafting, Runecrafting, Herblore, and Summoning use a fixed interval, while Woodcutting, Mining, Fishing, Thieving, and Agility use whatever the current actual skill interval is.  Using actual skill interval for all skills (besides Farming) could be more straightforward

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
