### ISSUE TITLE
Woodcutting interval reduction has bad rounding

### ISSUE THREAD

**Issue by clay-sutherland** [MelvorIdle/melvoridle.github.io#1275]
When agility is used to decrease woodcutting interval on top of axes and the cape, certain log cutting times are not calculated correctly, causing good log "pairings" to no longer work because the cutting times are off by a tiny fraction of a second.

**Comment by sylhaern** [comment]
It seems to be something with calculateSkillInterval in main.js:

This seems to be the offending section:  

`interval = interval * (1 + (increasedSkillIntervalPercent - decreasedSkillIntervalPercent) / 100);
interval -= decreasedSkillInterval;
    interval += increasedSkillInterval;
    if (interval < 250)
        interval = 250;
    return Math.ceil(interval);`

The first line introduces a rounding error, which is then rounded up by Math.ceil(interval)

This change to the first line fixed the problem for me:

`interval = interval * (100 + increasedSkillIntervalPercent - decreasedSkillIntervalPercent) / 100;`

**Comment by MelvorIdle** [comment]
This is now fixed as of ?1318
