### ISSUE TITLE
Levelling up during offline progress doesn't show offline loot for non-combat skills

### ISSUE THREAD

**Issue by RiRupp** [MelvorIdle/melvoridle.github.io#1276]
If you level up during offline combat you'll get a list saying for example, Defence 1 levelled up to 2, followed by a list of the items you looted during offline progress. I believe that's how offline progress is intended to be shown.

If you level up a non-combat skill during offline play there won't be a notification showing you what items you gained doing the non-combat skill. It will instead only show you a notification saying that you levelled up.

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
