### ISSUE TITLE
Lost progress

### ISSUE THREAD

**Issue by Trevis91** [MelvorIdle/melvoridle.github.io#1278]
**Describe the bug**
I logged on, said I had been away for 4 hours. When I clicked to log in, it took me back to a save from 2-3 weeks ago and copied over my old save. Unable to get my lost data back myself, unsure if someone else is able to.

**To Reproduce**
1. Go to 'unsure how to'

**Expected behavior**

Expected to have my 4 hours of progress as the game indicated I should have.

**Screenshots**

**Browser**
Please tell us what browser you are using and what version.

Mobile version 0.03.8

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

**Comment by Ixxyballs** [comment]
This just happened to me. I have solely played mobile for months with no issue, logging on the app every 30-600 mins depending on my day, and tonight logging on reset my progress by multiple weeks, at least 4+. Is there not a way to rollback a day or two? I'm running zero scripts/mods/anything. Absolute base game. How would some shit like this happen? Maybe a local/cloud save fuck up client/server side? Honestly total bullshit.

**Comment by JurdMcBurd** [comment]
This happened to me today - reset me to september 6th.
It was the only save listed, and I should have local and cloud saves many, many times since then - I play this daily.
To be honest, with a month of progress lost playing as much as I do, I may not want to play anymore.

**Comment by Ixxyballs** [comment]
I haven't found anyway to reverse the month or so loss in progress. I just changed goals around a bit and caught back up. 🤷‍♂️ Still feels like shit losing so much progress. Good luck to ya mate.
