### ISSUE TITLE
Aorpheats Signet Ring does not provide the bonuses listed

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#128]
**Describe the bug**
The bonuses listed in the description for Aorpheats Signet Ring are not correctly implemented in game.

Correctly Implemented Bonuses:
GP doubling functions as intended.
5% loot bonus applies correctly to thieving.
Incorrect Bonuses:
Skill item bonus provided is 5% instead of 10%.
5% Monster drop bonus provided only applies to bones and not normal drops.

**Expected behavior**
The rings should provide the bonuses as written.

**Screenshots**
![image](https://user-images.githubusercontent.com/58208131/76171516-f6423200-6151-11ea-8afd-bb63448cb490.png)

Most of the double chances for skills are referencing chanceToDoubleLoot instead of chanceToDoubleResources, causing the skill item bonus to be 5%.

![image](https://user-images.githubusercontent.com/58208131/76171557-56d16f00-6152-11ea-85e5-d3c5ab0a534c.png)
Line 1873 of combat.js, which controls monster loot doubling, should be replaced with similar logic to line 1827 of combat.js, which controls monster bone doubling.

**Comment by MelvorIdle** [comment]
Hotfixed
