### ISSUE TITLE
Golbin Raid Suggestions

### ISSUE THREAD

**Issue by Natro42** [MelvorIdle/melvoridle.github.io#1283]
1) Upon wave completion Display the completed wave # on the pop-up window.
2) In the shop, show how many times each upgrade has been purchased already.
3) Default starting spell to Wind Strike upon initial raid startup.  Currently the selection from the previous raid is remembered.  This can cause you to immediately lose any wands or staves that are selected if the previously selected spell requires runes that you do not currently posses.
4) Limit passive items to those that have an impact to the raid environment.  It seems that nearly half of the passives do not have any affect in a goblin raid, such as slayer items.  As an alternate suggestion, allow a passive re-roll every round instead of every 10th round.
5) Provide a wave combat summary.  Data such as number of attacks, hits, misses, goblin attack types, amount of time the round took, how many prayer points were used, how many runes were used, etc.  This will be useful in determining how to optimize or balance resource use.
6) Either provide a tooltip indication that runes are unavailable for the targeted spell or disallow the player to select a spell they do not have sufficient runes to cast.  This will help prevent the accidental loss of wands or staves if the wrong spell was clicked inadvertantly.
7) Provide the ability to manage your character (non-raid character) without having to exit raid.  The inability to do this can be problematic if the raid begins to approach the 12 hour offline cap (somewhere in the early wave 200's range based on my experience).
8) Show raid currency on the sidebar similar to prayer and slayer points.
9) Display the cumulative amount of raid currency has been earned so far.  Possibly as part of the wave header information?

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
