### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by Kodyzz1** [MelvorIdle/melvoridle.github.io#1287]
**Describe the bug**
In the Goblin Raid shop the word Goblin is spelled as Golbin

**To Reproduce**
It's just a misspelling

**Expected behavior**
Not spelled correctly

**Screenshots**
![Screenshot_20210828-180641_Melvor Idle](https://user-images.githubusercontent.com/89710801/131232242-ebaf82ff-1c3b-4c78-ba7d-da7dcf2f01ec.jpg)

**Browser**
Mobile version, most current

**Are you using any scripts?**
No

**Comment by coolrox95** [comment]
This is intentional, Golbins are Melvor Idle's unique take on Goblins.
