### ISSUE TITLE
Mining changes current ore when app is exited

### ISSUE THREAD

**Issue by JimmyJammm** [MelvorIdle/melvoridle.github.io#1291]
**Describe the bug**
When exiting out of a character while mining a specific ore, there is a chance for the ore to change to something else after exiting from the app. Verified occurrence on two separate characters at different times. First occurrence changes from coal to copper, second occurrence on a different account went from adamant to essence; upon reviewing mining section after opening the account, adamant ore was depleted but unsure if it’s related to the change of ore.

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
