### ISSUE TITLE
Smithing Gloves in Shop say +60% but tapping the glove while in the smithing view pops up +50%

### ISSUE THREAD

**Issue by richard-braindropsoftware** [MelvorIdle/melvoridle.github.io#1294]
Smithing Gloves in Shop say +60% but tapping the glove while in the smithing view pops up +50%

![Screenshot_20210829-183855](https://user-images.githubusercontent.com/66473861/131267607-3af376d8-e050-4c3a-8dcc-3dcbe7990c0f.png)

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
