### ISSUE TITLE
Affordability colors not updating when changing quantities

### ISSUE THREAD

**Issue by richard-braindropsoftware** [MelvorIdle/melvoridle.github.io#1298]
I could afford 1 compost, that the window was set at to start, switching to other quantities updates the cost, but not the color indication of affordability.

![Screenshot_20210829-205025](https://user-images.githubusercontent.com/66473861/131272431-95945130-159c-40cc-ba5a-385d584a12fd.png)

**Comment by coolrox95** [comment]
Issue was resolved in an update.
