### ISSUE TITLE
Compost count UI on farming screen not updating after purchase

### ISSUE THREAD

**Issue by richard-braindropsoftware** [MelvorIdle/melvoridle.github.io#1299]
Purchasing 10 compost successfully added then to my bank and usable compost, but the UI on the farming screen did not update (I had 21, but UI still said 11)

![Screenshot_20210829-205107](https://user-images.githubusercontent.com/66473861/131272644-b03801ff-6b78-4cb9-944c-d5075e6dea91.png)

**Comment by coolrox95** [comment]
Duplicate of #1257
