### ISSUE TITLE
Affordability colors not updating in the shop based after selling stuff to make the gp

### ISSUE THREAD

**Issue by richard-braindropsoftware** [MelvorIdle/melvoridle.github.io#1300]
Probably similar to the affordability colors not updating correctly on the compost purchase popup; but I didn't have enough gp for a new bank slot so I sold some stuff to get some gp and when going back to the shop the color hasn't updated although I have the gp now and it is usable.

![Screenshot_20210829-211055](https://user-images.githubusercontent.com/66473861/131272836-7c6166d3-026f-4902-95bd-880b1be0f4ba.png)

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
