### ISSUE TITLE
Welcome back offline error

### ISSUE THREAD

**Issue by cdemar** [MelvorIdle/melvoridle.github.io#1303]
**Describe the bug**
"We ran into an error calculating your Offline Progress! >:( Your Skill was also stoped in the progress."

**To Reproduce**
1. I went to a different screen for a sec to have side by side view.
2. When I got back It presented that error

**Expected behavior**

**Screenshots**
[](url)

**Browser**
Crome
<img width="515" alt="Screen Shot 2021-08-30 at 8 29 51 AM" src="https://user-images.githubusercontent.com/31713295/131365191-2d46a890-83a6-410c-96e9-af2302107bae.png">

**Console output**
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)

**Are you using any scripts?**
no

**Comment by kfbest** [comment]
Had similar issue - but different cause (I think). Just put iPad to sleep and got error when came back.

**Comment by Allekseev** [comment]
![Screenshot_20210921-131310](https://user-images.githubusercontent.com/55903749/134141735-4bac34b5-cb12-41bc-ac87-2fd1fce3cf58.png)

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
