### ISSUE TITLE
Green text when requirement is incomplete in shop

### ISSUE THREAD

**Issue by abcras** [MelvorIdle/melvoridle.github.io#1304]
**Describe the bug**
The cape of completions text: "Requires 100% completion" should be in red but is in green. Falsely signifying that I have 100% completion.

**To Reproduce**
I have no idea how to reproduce it.

**Screenshots**

![image](https://user-images.githubusercontent.com/3748122/131374934-d9eaa1b6-d926-48e0-9a15-d484caca3938.png)

**Other notes**
I loaded up an old save from 1000 hours ago (and in another browser Firefox) and that save too had the same problem.
So it might be my save that is weird.

Fix my save didn't solve the issue.

**Browser**
Brave 1.28.106

**Are you using any scripts?**
Melvor Combat Simulator extension is installed. But I loaded up a new save in the browser and the text was the typical/expected red, so I doubt it is the extension.

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
