### ISSUE TITLE
Red text in Goblin Raid shop when the requirements are met

### ISSUE THREAD

**Issue by TommyD-GoblinSlayer** [MelvorIdle/melvoridle.github.io#1305]
Have plenty of coins, 100k+, but the prayer skill and passive item unlock shop items show up as red. I was still then able to buy both.
![Screenshot (24)](https://user-images.githubusercontent.com/89838952/131475743-30ce4ca4-2723-48f1-a44e-cf1c0a6833c2.png)

(also Goblin is misspelled ;) )

**Comment by coolrox95** [comment]
Issue was resolved in an update.
