### ISSUE TITLE
Quick buy summoning shard menu not disappearing

### ISSUE THREAD

**Issue by TommyD-GoblinSlayer** [MelvorIdle/melvoridle.github.io#1306]
When buying summoning shards from the tablets/familiars page, the first menu to input how many shards I want doesn't disappear after I click buy, so that the next confirmation menu is under it and covered by it.

The issue was consistent, but went away when I restarted the game.

![Screenshot (22)](https://user-images.githubusercontent.com/89838952/131476337-583986ea-396b-4931-8182-e19ce8ee9c42.png)

**Comment by kfbest** [comment]
Had same problem. Force quitting app resolved it. 

iPad OS 15.1
Melvor app version 2.2
Public Beta 1.0 (?1285)
