### ISSUE TITLE
Equipment bugs after Goblin Raid

### ISSUE THREAD

**Issue by TommyD-GoblinSlayer** [MelvorIdle/melvoridle.github.io#1308]
I've finished a goblin (golbin to some) raid, and first my equipment menu in the top right only showed the equipment I died with in the raid. I think by equipping different items it changed back to normal, but now when I try to equip anything to sets 2 or 3, it just equips them to set 1.
The 'select equipment set' option of the bank menu only shows equipment set 1, and the 'will replace' is stuck on what I had in the goblin raid, apart from my cape which is stuck on the woodcutting cape, the first thing I tried to equip.
On the woodcutting menu the game thinks I have the woodcutting cape equipped even when it isn't.

**Comment by TommyD-GoblinSlayer** [comment]
Later after closing the game and doing some more goblin raid, the problem returned (I don't even have an Earth Layered Shield in the main game)
![Screenshot (26)](https://user-images.githubusercontent.com/89838952/131574081-19f2eab3-9faf-4c92-aa6b-372120b33ae9.png)

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
