### ISSUE TITLE
Aorpheats Signet Ring halts crafting

### ISSUE THREAD

**Issue by NotArcanus** [MelvorIdle/melvoridle.github.io#131]
**Describe the bug**
Aorpheats Signet Ring just stops crafting instead of doubling when the rng is rolled to double

**To Reproduce**
1. Go to Crafting Skill with Aorpheats Signet Ring Equipped
2. Start crafting anything
3. Wait till game just stops crafting

**Expected behavior**
The item being crafted to drop double

**Screenshots**
![image](https://user-images.githubusercontent.com/57652554/76182320-cec38780-619a-11ea-8acc-1a3f57cc26ca.png)

This should be fixed if the variable that gets multiplied by 2 is qtyToAdd not craftQty

**Console output**
ReferenceError: craftQty is not defined2 crafting.js:63:119
    craftingTimeout https://www.melvoridle.com/assets/js/game/crafting.js?207:63

**Comment by MelvorIdle** [comment]
Hotfixed
