### ISSUE TITLE
Stuck on 6 More Normal Tasks

### ISSUE THREAD

**Issue by epicurist** [MelvorIdle/melvoridle.github.io#1311]
**Describe the bug**

I haven’t been able to purchase the slayer equipment because it says I need to complete 6 more normal slayer tasks. But I’ve been completing nothing but normal tasks and it won’t change.

see screenshots attached. 
![30BB63CA-C52F-45C4-8122-505B90682BF7](https://user-images.githubusercontent.com/89946566/131760589-17cef0b3-ee16-46ba-a951-8f454e3e426d.png)
![AEFA9A78-6F7A-4AC9-8E41-9AB13C53296E](https://user-images.githubusercontent.com/89946566/131760595-85bd9bc2-6170-4985-9426-4bba79197c0b.png)

I should be able to complete a normal level slayer task, it switch over to a new monster and I go to check the shop and the number of slayer tasks should lower. 

I’m a mobile user.

**Comment by Asphoron** [comment]
I'd like to add this is happening to me as well with Elite stuck at 14 left to buy the upgrade token. I have been running Elites for a while, so I know I've done enough by now. I am a web user.

**Comment by Luckyman353** [comment]
I'd like to add I'm stuck on 28 left with elite been doing slayer for 3 days now and it's not going down
