### ISSUE TITLE
Alt Magic spells do not unlock until refresh

### ISSUE THREAD

**Issue by Derekmod** [MelvorIdle/melvoridle.github.io#1312]
Was training alt magic (in a background tab, unclear if that's relevant). Whenever I went back to the tab, newly unlocked alt magic spells were still locked. Issue persisted after going to a different tab (e.g. herblore) and back. Clicking on the erroneously locked spells had no effect.

Issue resolved after refreshing the chrome tab.

Issue reproduced 4 times in a row, with several of those times unlocking multiple spells.

**Comment by coolrox95** [comment]
Issue appears to only happen when using the "Pause actions for skills" settings, and returning to the tab, or when returning from offline progress.

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
