### ISSUE TITLE
Spelling Mistake on Synergy 

### ISSUE THREAD

**Issue by Azemari** [MelvorIdle/melvoridle.github.io#1313]
**Describe the bug**
Simple spelling error 'verion' instead of 'version'.

**To Reproduce**
1. Go to summoning / synergies
2. locate the mole / salamander synergy

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/55991839/131834024-7c449b02-8368-4438-b492-e1102bc1d1ce.png)

**Browser**
Please tell us what browser you are using and what version.
Steam version of game - Alpha v0.21 (?1118)

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
