### ISSUE TITLE
Bleed effect freezes

### ISSUE THREAD

**Issue by mikkopresents** [MelvorIdle/melvoridle.github.io#1315]
**Describe the bug**
When successfully hitting a bleed with the Sunset Rapier, the blood symbol SOMETIMES freezes and no damage is taken.
**To Reproduce**
1. Go to '...' fight something (I was in Dragons Den) with Sunset Rapier equipped
2. Click on '....' start dungeon
3. Scroll down to '....' look at enemy the blood drop sometimes freezes and the number doesn't increment down 

**Expected behavior**
A clear and concise description of what you expected to happen. I expect the monster to cycle hp down twenty times

**Screenshots**

**Browser**
Please tell us what browser you are using and what version. 
92.0.4515.159 (Official Build) (64-bit)
**Console output**
Please open the console by pressing F12 and copy it here.
not sure how to do this - i get the screen but i can't copy it
**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.
no

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
