### ISSUE TITLE
Upgrade Bug

### ISSUE THREAD

**Issue by NotArcanus** [MelvorIdle/melvoridle.github.io#132]
**Describe the bug**
Upgrading to Aorpheats Ring does not always consume both halves

**To Reproduce**
1. Get Signet Ring Half (a) + Signet Ring Half (b) + 1M gp
2. Click on Signet Ring Half (a) > 
3. Click on Upgrade Item
4. Click 1x

**Expected behavior**
Both Ring halves to be removed from bank and Aorpheats Signet Ring to be added

**Screenshots**
![image](https://user-images.githubusercontent.com/57652554/76183550-3380e100-619f-11ea-81fd-4b1b588d2ce6.png)

For loop should not be stopping at < length not < length - 1, the only reason it works if you use B is that it does the armor check and removes b afterwards. In fact, I think this might break all upgrades.

Edit: Tested trimming armor, it no longer costs any gold/silver bars

**Comment by MelvorIdle** [comment]
Hotfixed
