### ISSUE TITLE
Pet Master steam acheivements require Ripper, Jerry, Preston

### ISSUE THREAD

**Issue by Nomeru** [MelvorIdle/melvoridle.github.io#1322]
**Describe the bug**
Ripper, Jerry, Preston don't count towards completion and currently Ripper can't be obtained. However these 3 are currently required for the achievement to unlock. At least on hardcore, I can't say for standard since that one's already unlocked for me.

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
