### ISSUE TITLE
Offline progress window gets removed by levelling a familiar (seen on android)

### ISSUE THREAD

**Issue by abcras** [MelvorIdle/melvoridle.github.io#1324]
**Describe the bug**
When you load back into the game after being offline the offline progress window gets removed/dismissed automatically if a summoning familiar leveled up a tier, leading to the player not knowing the results of the offline session.

**To Reproduce**
Level a summoning familiar a tier while the game is closed.

**Expected behavior**
I think the intended behaviour is for the summoning leveling window to appear after the offline progress window has been dismissed. 

**Browser**
Mobile android phone.

**Are you using any scripts?**
No scripts

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
