### ISSUE TITLE
Holy Dust Showing “0” Prayer Points

### ISSUE THREAD

**Issue by Slangwhangers** [MelvorIdle/melvoridle.github.io#1327]
*EDIT* I found out recently that you do NOT need to use Blessed Offering. **ALL** items that can be buried for Prayer Points show they provide 0 points each.

1. Go to 'Alt. Magic'
2. Click on & cast 'Blessed Offering'
3. Go to your bank 
4. Click on 'Holy Dust'
5. See “Grants 0 Prayer Points each”

It is supposed to show “Grants 3 Prayer Points each”

![E822FB6D-0DE8-4732-A93E-CFBD17B3E3D5](https://user-images.githubusercontent.com/90223713/132265181-7f7f1df2-d565-4285-8cf6-77f95a04885b.jpeg)

IOS App - Alpha V0.21 (?1120)

**Comment by Slangwhangers** [comment]
Actually on a side note, I have discovered that all burial items seem to give "0" Prayer Points each

**Comment by Stevieroy94** [comment]
I haven't used any Alt. Magic offering spells, and I seem to have this same bug where all prayer offerings show they restore 0 pts.

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
