### ISSUE TITLE
TypeError: bank[i] is null

### ISSUE THREAD

**Issue by Goldanfrost** [MelvorIdle/melvoridle.github.io#133]
**Describe the bug**
Was akfing thieving and came back to error screen, tried reloading the page aswell with starting a new tab, but only loads back into the same error. On the sidebar my bank shows I have 0/1 items, but all other stats seem uneffected

**To Reproduce**
1)Load into game
2) Get error
**Expected behavior**
Unable to get into game, error comes up immediately 
**Screenshots**
https://gyazo.com/4e107cac16f28a202b663322658ee146

**Browser**
Using Firefox Quantum 68.5.0esr (64-bit)

**Console output**
Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-129674422-1”. index.php:6:1
Loading failed for the <script> with source “https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js”. index.php:17:1
Loading failed for the <script> with source “https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js”. index.php:391:1
Loading Save Game... save.js:44:13
Save Game Loaded... save.js:206:13
Loading Save Game... save.js:44:13
Save Game Loaded... save.js:206:13
Updating Masteries mastery.js:156:13
Loading Masteries... mastery.js:23:13
TypeError: "bank[i] is null"
    checkBankForItem https://melvoridle.com/assets/js/game/bank.js?207:139
    updateShop https://melvoridle.com/assets/js/game/shop.js?203:412
    updateWindow https://melvoridle.com/assets/js/game/main.js?242:948
    loadGame https://melvoridle.com/assets/js/game/save.js?225:285
    initiateLoad https://melvoridle.com/assets/js/game/save.js?225:347
    onload https://melvoridle.com/assets/js/game/save.js?225:399
main.js:1005:17

​

**Comment by MelvorIdle** [comment]
Are you able to provide a copy of your save?

When you see the error, press F12 to open console and type downloadSave(); in console. This will give you a text file. Can you send it to me?

**Comment by Goldanfrost** [comment]
[melvoridlesave.txt](https://github.com/MelvorIdle/melvoridle.github.io/files/4309665/melvoridlesave.txt)

Thanks for the help

**Comment by MelvorIdle** [comment]
[melvoridlesave (24).txt](https://github.com/MelvorIdle/melvoridle.github.io/files/4310586/melvoridlesave.24.txt)

Here you go. To import it type this in console:
$("#modal-game-broke").modal("hide");
$("#modal-import-export").modal("show");

This will bring up the import box for you

**Comment by Goldanfrost** [comment]
That worked perfectly. Thank you!
