### ISSUE TITLE
Cooking Fire Shop upgrade requirements are coloured as not met for Logs

### ISSUE THREAD

**Issue by eastanciu** [MelvorIdle/melvoridle.github.io#1331]
**Describe the bug**
In the shop, the cooking fire upgrades appears as not available for purchase as wood requirements are not met.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Shop'
2. Click on 'Skill Upgrades'
3. Scroll down to 'Cooking Fire upgrades'
4. Notice that the wood requirements appear as unmet (are coloured as red)
5. Issue encountered for all tiers, not just the one presented in screenshots (Willow Logs)

**Expected behaviour**
The wood requirements should appear as green if the amount of wood is available in the inventory(bank).

**Screenshots**
<img width="361" alt="Screenshot 2021-09-08 at 00 20 18" src="https://user-images.githubusercontent.com/6085196/132465794-fd4b45c8-fd97-4f1c-957c-fc804366dcc4.png">
<img width="87" alt="Screenshot 2021-09-08 at 00 20 34" src="https://user-images.githubusercontent.com/6085196/132465803-1f50a098-4fef-449e-83fd-f587fddf2ef9.png">

**Browser**
Steam app

**Are you using any scripts?**
No

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
