### ISSUE TITLE
Skill Gloves not recieving charges on purchase

### ISSUE THREAD

**Issue by RB200** [MelvorIdle/melvoridle.github.io#1332]
**Describe the bug**
I had ran out of mining glove charges and it said 0, so I bought more and it didn’t add to the 0. They didn’t do anything.

**To Reproduce**
Run out of mining glove charges and buy more

**Expected behavior**
I’d expect it to add to the 0 instead of doing nothing

**Browser**
I’m on mobile

**Are you using any scripts?**
No

**Comment by jpdeveau** [comment]
Just to add a note to this from my duplicate. I DID in fact get the charges. I just didn't get a glove to wear to use the charges!
