### ISSUE TITLE
EXP from cooking a Sword Fish is wrong

### ISSUE THREAD

**Issue by TragicSeriously** [MelvorIdle/melvoridle.github.io#1337]
**Describe the bug**
The screen displays 50exp when you select to cook a Sword Fish. But each fish cooked is only providing 48exp. 
**To Reproduce**
1. Go to 'Cooking'
2. Click on 'Food type to cook'
3. Scroll down to 'Sword Fish' and then cook one and....

**Expected behavior**
Expected to see exp increase by 50, not 48.

**Browser**
Please tell us what browser you are using and what version.
Steam App
**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.
None

**Comment by MiccWan** [comment]
It works fine for me which gives me 50 **base** cooking XP correctly. Maybe your global XP boost are negative(some of agility obstacles has this debuff)?
