### ISSUE TITLE
Error message received during alt.magic while coming back to the game tab from another tab

### ISSUE THREAD

**Issue by ozakinci** [MelvorIdle/melvoridle.github.io#1338]
**Describe the bug**
While doing alt.magic had an error saying "let dev know"

**To Reproduce**
do alt.magic and go idle
in my case the game was open but on a tab in the background

**Expected behavior**
i expected this not to happen

**Screenshots**
![image](https://user-images.githubusercontent.com/26277755/132824359-fcddaa5d-2731-44be-9421-e4375945e607.png)

**Browser**
chrome Version 93.0.4577.63 (Official Build) (64-bit)

**Console output**
if this is for the output when the issue happened i've closed that window, so don't have it

**Are you using any scripts?**
no

Thanks for the game!

Cheers,

Tayfun

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
