### ISSUE TITLE
See potential monster drops whilst in combat

### ISSUE THREAD

**Issue by Cadbury847** [MelvorIdle/melvoridle.github.io#134]
Currently, it seems you have to run away (leave combat) then re-select the area to view a monsters drops. It would be incredibly convenient (QoL change) to be able to see the list of potential drops of the monster you're currently fighting in the combat interface without running waay.
![image](https://user-images.githubusercontent.com/56396053/76322725-a7c09f00-62db-11ea-8bfa-a2f2771db98b.png)
Highlighted in blue are two potential locations to put this button. Its no new content, just a new way to access pre-existing GUIs.

**Comment by ATaylor1027** [comment]
@TheMalcs This please!

**Comment by MelvorIdle** [comment]
Added in the coming update
