### ISSUE TITLE
Loss of idle actions

### ISSUE THREAD

**Issue by Aggiepatten** [MelvorIdle/melvoridle.github.io#1340]
**No idle action or EXP**
Sometimes when the app is closed the profile you were just in does not continue it’s action. This results in no Co and no obtained items until you reopen the app. As soon as the app is reopened it continues action. I have seen this multiple times overnight (8 hours of lost action)

**To Reproduce**
It seems to happen more when the phone is shut off rather than going back to the Home Screen first or switching to a different app.

**Expected behavior**
When not in the app, you should always perform idle action as long as one is selected. Maybe the game should even warn you if you don’t have an action selected.

**Screenshots**

**Browser**
Please tell us what browser you are using and what version.

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

**Comment by sbabudro** [comment]
I've had the same problem, it's why I stopped playing on mobile and only play on PC now.

I had a hunch it had something to do with how I was exiting the app, since I normally would just hit the power button to turn the screen off instead of pressing home first, but I never tested it. Just got fed up and starting playing on PC.

**Comment by MelvorIdle** [comment]
There is a setting that you need to enable that allows progress to be gained when the app is minimized.

Be sure to minimize the app. But it is always preferred that the app is forced closed as Mobile Devices are always changing the methods of how to detect if an app is in the background.
