### ISSUE TITLE
Pig + Devil doesnt consume charges when cooking

### ISSUE THREAD

**Issue by NototoHoshi** [MelvorIdle/melvoridle.github.io#1342]
When cooking, using the Pig / Devil combo doesnt reduce the amount of charges when playing online. It is supposed to do -1 to devil charges and -2 to pig charges, but it only does -1 to pig.

This only happens when online, offline progress seems to deduct the charges correctly.

**Comment by MelvorIdle** [comment]
I believe this is now fixed
