### ISSUE TITLE
App crashes multiple times when loading up on iPad

### ISSUE THREAD

**Issue by TucCrackers** [MelvorIdle/melvoridle.github.io#1346]
**Describe the bug**
When the app is closed completely and trying to to open the app it will crash around 3/5 times before allowing the app to fully start. 

**To Reproduce**
1, Fully close the app
2, Attempt to open the app
3, After 3/5 times the app will fully open.

**Expected behavior**
Expect the app to open first time

**Browser**
Seems to be iPad only, works fine on my iPhone

**Console output**
Cannot do that on iPad.

**Are you using any scripts?**
No

https://user-images.githubusercontent.com/29133066/133004412-62e4720a-abed-4ab1-8ba9-b81e100483ec.mp4

**Comment by MelvorIdle** [comment]
This should be now fixed in the latest update
