### ISSUE TITLE
[Request] Option to disable the bank item sliding panel on item select

### ISSUE THREAD

**Issue by richard-braindropsoftware** [MelvorIdle/melvoridle.github.io#1348]
### Why are you suggesting this?
It drives me nuts that every time I want to interact with a bank item it has to open that sliding popup panel with the same information that is displayed right underneath it without locking the bank UI interaction to that panel.

**How does your suggestion benefit the game?**
Should be a simple checkbox option in the settings and a guarded call to open that panel, I would think based on experience.

That slight annoyance is just about my only gripe so far, I can't imagine I'm the only one this is annoying for.

Amazing job in any case, loving the game!

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
