### ISSUE TITLE
Drag and drop item to new tab on Android not working

### ISSUE THREAD

**Issue by richard-braindropsoftware** [MelvorIdle/melvoridle.github.io#1349]
**Describe the bug**
When dragging bank items from one tab to another it works as expected on desktop, but on Android, the item drags around but it never seems to recognize it's over a tab so it can't be drag and drop moved around.

**To Reproduce**
The description is reproduction steps.

**Expected behavior**
Should be able to drag and drop reorganize items in the bank on any platform.

**Browser**
Android (Google Play), Desktop (Brave Version 1.29.80 Chromium: 93.0.4577.63)

**Console output**
I don't have time to hook my phone up and get the cli tools to check logcat at the moment, sorry.

**Are you using any scripts?**
Nope.

**Comment by MelvorIdle** [comment]
Drag and drop is unfortunately not natively supported on mobile devices.
