### ISSUE TITLE
New update popup shows every refresh

### ISSUE THREAD

**Issue by Benthem** [MelvorIdle/melvoridle.github.io#135]
**Describe the bug**
Update popup shows every time I refresh as of 0.13

**To Reproduce**
1. Refresh
2. Click Export Save
3. Continue
4. Load Local save
5. Refresh
6. Popup shows still

**Expected behavior**
Popup doesn't show at 6.

**Browser**
Chrome Version 80.0.3987.132 (Official Build) (64-bit)

**Console output**
No errors

**Comment by MelvorIdle** [comment]
Does this still pop up as of today?

**Comment by Benthem** [comment]
Just refreshed, yes.
