### ISSUE TITLE
Graveyard pet disappeared

### ISSUE THREAD

**Issue by TierreAsh** [MelvorIdle/melvoridle.github.io#1351]
**Describe the bug**
I was grinding Graveyard to get the pet and got a message that i got it. I pressed OK and went into other activities. Then i checked my pets a few hours later - graveyard pet wasn't there. Next day and reboot - pet isn't there.

**To Reproduce**
1 grind graveyard
2 receive message tha you got the pet
3 Keep doing something else
4 Realise that you don't have this pet.

**Expected behavior**
Then i get message that i get the pet i expect to really get it.

**Screenshots**
None were taken

**Browser**
Steam

**Console output**
No console - steam

**Are you using any scripts?**
No - steam

**Comment by DarkenTheSun807** [comment]
To add some information, I've got the same problem but I still have the 10+ health buff from it. The pet isn't gone, it's just not showing up in the log. I'm also on steam.
