### ISSUE TITLE
Discord is not opening from Steam

### ISSUE THREAD

**Issue by TierreAsh** [MelvorIdle/melvoridle.github.io#1352]
**Describe the bug**
Then i try to open discord link from steam client it just leaves a window with white screen

**To Reproduce**
1. Press Discord button on steam client
2. Opening window is blank white
3. wait 10 minutes and close it
4. Press again Discord button in client
5. See the "you have been inveted" and press "accept"
6. Briefly see the message "Opening discord app'
7. After 1 second the same blank window
8. Repeat from step 4

**Expected behavior**
Discord is opened if you press discord button

**Screenshots**

![изображение](https://user-images.githubusercontent.com/90751011/133385511-34ed9285-a1ad-43ed-ad18-f7ae591d84fc.png)

**Browser**
Steam client

**Console output**
No console - steam

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Hotfix applied
