### ISSUE TITLE
Death Rune gives less runecrafting exp than Havoc Rune

### ISSUE THREAD

**Issue by Gholdnor** [MelvorIdle/melvoridle.github.io#1358]
**Describe the bug**
When leveling runecrafting, I noticed that the death rune gives 2 less exp than the Havoc rune. 18 exp vs. 20 exp respectively. Thus far the other runes have increased in exp given as you unlock more. I’m assuming this is unintentional.

**Expected behavior**
I would expect the death rune to unlock before the havoc rune if it gives less exp or provide more exp.

**Screenshots**

**Browser**
IOS

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Combat Simulator

**Comment by MelvorIdle** [comment]
This is due to mastery. Intended mechanic.
