### ISSUE TITLE
Firemaking not tracking time spent correctly

### ISSUE THREAD

**Issue by sbabudro** [MelvorIdle/melvoridle.github.io#1359]
**Describe the bug**
Firemaking isn't tracking the time spent burning logs.

My stats page tells me (I believe correctly, matches my perception of how many I used to have) I burned 31k logs, but that I somehow accomplished it in under 3k seconds? First of all, no logs burn in under a second, and you can't use bonfires that often. Second, I have largely trained this skill offline mode with no bonfire. Third, I spent 10 hours JUST LAST NIGHT training the skill, which is 36k seconds alone, not to mention the other time spent on the skill, which should be at least another 5 hours.

**Browser**
Chrome, Version 93.0.4577.82 (Official Build) (64-bit)

**Console output**
www.googletagmanager.com/gtag/js?id=UA-129674422-1:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloud.js?1120:76 Connected to PlayFab successfully
cloud.js?1120:76 PlayFab Connection Events Succeessful.
cloud.js?1120:76 PlayFab Connected: Vakontation
save.js?1120:57 set force reload to 2
combatManager.js?1120:1 Combat Manager Built...
raidManager.js?1120:1 Golbin Raid Manager Built...
save.js?1120:14 Loading Save Game...
save.js?1120:14 Save Game Loaded...
main.js?1120:5 Game Loaded
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
Chart.bundle.min.js:1 Failed to load resource: the server responded with a status of 404 ()
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
Chart.bundle.min.js:1 Failed to load resource: the server responded with a status of 404 ()
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
cloud.js?1120:8 Synchronising with Cloud
cloud.js?1120:76 Connected to PlayFab successfully
cloud.js?1120:76 PlayFab Connection Events Succeessful.
cloud.js?1120:76 PlayFab Connected: Vakontation
3main.js?1120:245 true
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
main.js?1120:245 true
![Firemaking_Bug](https://user-images.githubusercontent.com/54855019/133802719-5183430e-f89d-42cb-9464-d5963b2ca0d6.png)

**Comment by sbabudro** [comment]
After spending another hour offline firemaking, I can see that the time has not changed. It appears that it is only tracking time spent online.

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
