### ISSUE TITLE
Mining and Smithing rework

### ISSUE THREAD

**Issue by sbabudro** [MelvorIdle/melvoridle.github.io#1360]
In OSRS, and in Runescape prior to the Mining and Smithing rework of January 2019, the levels were the same (pretty much) as in Melvor. Obviously one major difference is that Melvor made it possible to mine and smith dragon armour.

One significant benefit of the M&S rework in Runescape was the alignment of the skill levels. No longer was 85 mining and 99 smithing required to obtain level (now 50) 40 armour.

I would like to suggest that Melvor consider a similar rework to mining and smithing, so that someone with level 40 defence isn't bum outta luck until they get 87 smithing.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
