### ISSUE TITLE
Hardcore downgrade upon death

### ISSUE THREAD

**Issue by sbabudro** [MelvorIdle/melvoridle.github.io#1361]
The concept of a hardcore character is very OG. Games used to be very unforgiving, and some games still are made that way.

The appeal of the prestige of having never died is obvious. However in a game like Melvor, this basically just prompts excessively cautious gameplay.

Personally - for whatever god forsaken reason - my first character I ever made is a hardcore. I left it training combat overnight several weeks ago and woke up to find that I had just dumped weeks of progress in the dumpster. I had the bizarre fortune to discover that my local save on my cell phone had not been erased, perhaps due to internet connectivity, I don't know. At any rate, I was able to recover a save from several nights ago. I still lost progress, but substantially less.

This prompted me to make two more characters, one for each game type, so as not to feel quite so devastated if this were to happen again. I have been enjoying those characters significantly more, despite having lower levels, because I feel I can actually do what I want to in the game without fear of crushing loss again.

I think that it would be a small boon to offer players who lose a hardcore to convert it into a regular account at that point. I can understand how this might seem cowardly and weak, but it retains the prestige of having a high level hardcore character without utterly devastating people foolish enough to make a mistake like I did and who didn't get lucky like I did.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
