### ISSUE TITLE
I can't load my Adventurer character

### ISSUE THREAD

**Issue by ZbLorG1** [MelvorIdle/melvoridle.github.io#1363]
**Describe the bug**
Around one out of two days (the other day everything works fine), after getting logged into the cloud, I'm trying to load my adventurer save and the blue circle appears and keep turning forever.
If I try to load the save I kept on my computer (the one I did the last night using the "download save" button in the settings menu) I get a message saying "Oops! Something went wrong trying to import the save. Please doublecheck everything was pasted correctly, and the the save is compatible with this version of the game".
On days when I can't load the save of this character, I can still load and plya normally to the other ones (1 Hardcore character and 1 normal).

**To Reproduce**
1. Go to "Show Cloud Saves"
2. Click on the save
3. The blue circle appears and turns

**Expected behavior**
The save loads

**Browser**
Mozilla Firefox 92.0

**Console output**
Uncaught (in promise) DOMException: The quota has been exceeded.

**Are you using any scripts?**
I don't know if it's a script, but I'm using the combat simulator extension

Thank you for this amazing game, keep the great work !

**Comment by coolrox95** [comment]
Closing this issue as the root problem is issue #1562
