### ISSUE TITLE
Cooking SkillUpgrade in shop shows red

### ISSUE THREAD

**Issue by Munkeywaxx** [MelvorIdle/melvoridle.github.io#1364]
**Describe the bug**
In the Shop, adding logs to the cooking fire, shows the "Needed" logs as red.

**To Reproduce**
1. Click on Shop
2. Click on Cooking fire upgrade

**Expected behavior**

**Screenshots**
Unable to reproduce, I upgraded to the highest available at the time. Will update when I hit 75 Firemaking

**Browser**
Steam Client

**Console output**
N/A

**Are you using any scripts?**
No Scripts

**Comment by dubesor** [comment]
Can confirm this. The needed lumber is always shown as red, regardless of amount in bank and regardless of which exact cooking fire. Happened to me for every single one. 
Here is an example gif for Yew Cooking Fire/Yew Logs:
![test](https://user-images.githubusercontent.com/33842233/133887293-d98ccf3f-4d29-4d5d-8e32-08b31310bcdf.gif)

**Comment by MelvorIdle** [comment]
This should now be fixed in Alpha v0.22
