### ISSUE TITLE
Paladin Gloves not applying or not displaying correct DR

### ISSUE THREAD

**Issue by erwzchan** [MelvorIdle/melvoridle.github.io#1366]
**Describe the bug**

With Paladin Gloves equipped, DR bonus displays correctly in "View All Equipment Stats" screen, but not in "Stats" section in the combat tab. Additionally, the displayed Max Hit for monsters does not change when I equip/un-equip the gloves.

**To Reproduce**

1. Equip Paladin Gloves.

**Expected behavior**

Paladin Gloves should apply a 4% bonus to damage reduction in combat.

**Screenshots**

(All screenshots taken on MacOS in Safari)

<img width="1143" alt="Screenshot 2021-09-21 at 20 47 26" src="https://user-images.githubusercontent.com/91156873/134239968-0e99e5c2-43e8-4b7f-9c06-9425807e73a9.png">

<img width="719" alt="Screenshot 2021-09-21 at 20 48 16" src="https://user-images.githubusercontent.com/91156873/134239990-ba6b8988-a0a5-476f-8feb-a2bcfd361824.png">

<img width="714" alt="Screenshot 2021-09-21 at 20 48 34" src="https://user-images.githubusercontent.com/91156873/134240014-a6dd3d76-002c-4463-b89a-25eecee09af5.png">

**Browser**
Please tell us what browser you are using and what version.

First noticed the issue on iOS. Reproduced the issue on macOS in Safari. In both cases, the version is **Alpha V0.21**.

**Console output**
Please open the console by pressing F12 and copy it here.

[Error] Failed to load resource: the server responded with a status of 403 () (popper.min.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 403 () (tippy-bundle.umd.min.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 403 () (57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map, line 0)

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

No, I am not using any scripts.

**Comment by erwzchan** [comment]
After messing around with some different equipment pieces, I now think the issue is not with the Paladin Gloves specifically, but instead that the DR displayed for me in the combat tab is a flat 4% lower than the expected total, down to a minimum of 0%. E.g. equipping a single piece of gold dragon armour (expected DR of 6%) gives a DR of 2% instead.

Screenshot provided below of combat with the kraken using my current equipment. Combat triangle indicates melee vs melee isn't expected to have any modifier to DR. Equipment pictured (full gold dragon armour + paladin gloves + silver diamond necklace + silver diamond ring) is expected to yield a total of 37% damage reduction, but the displayed value is only 33%, ie. 4% lower than expected.

<img width="613" alt="Screenshot 2021-09-22 at 11 50 10" src="https://user-images.githubusercontent.com/91156873/134330915-bb70905a-01d4-47d1-896c-606819dde578.png">

**Comment by kevolaf** [comment]
Do you have the Mud Dive obstacle active in the Agility screen? It has a -4% DR attribute.

**Comment by erwzchan** [comment]
> Do you have the Mud Dive obstacle active in the Agility screen? It has a -4% DR attribute.

Oh, yes that's what it is. Thanks for the info. My apologies for the mistake, I only recently started playing again after a bit of a break and the agility skill is new to me.
