### ISSUE TITLE
[Agility] Heat Trap doesn't show the effects of 99 Mastery

### ISSUE THREAD

**Issue by DarkenTheSun807** [MelvorIdle/melvoridle.github.io#1367]
Description:
Mastery 99 for Heat Trap doesn't display the halved effect on the card. After reloading it is visible under the "All global Active Passives" button, but not both. To be clear, I needed to reload to update the list. It didn't do it automatically. This didn't work on the obstacle card. I also restarted my web browser and nothing changed.

If this is not a bug, it should be changed regardless. It should be made clear that the effect is working.

I can't tell if this the same for other obstacles or specific to this one. I don't have any others 99'd.

Card:
![image](https://user-images.githubusercontent.com/28941164/134249570-42d8391e-95bd-49ba-9c07-d08c8c7fcd60.png)
List:
![image](https://user-images.githubusercontent.com/28941164/134249661-1faf0f95-6dfd-4b63-893b-aefeefd83f6a.png)

Browser: Chrome Version 93.0.4577.82 (Official Build) (64-bit)

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
