### ISSUE TITLE
Spider Cave Pet Bug?

### ISSUE THREAD

**Issue by TehTurkey** [MelvorIdle/melvoridle.github.io#1368]
**Describe the bug**
Hello! My name is TehTurkey and I'm somewhat new to Melvor Idle. I really really enjoy the game! Thank you. I am sending this message in regards to a possible bug in the game. I am at the point in Melvor where I can afk combat, so I decided to do some dungeon boss hunting. Over the past 2 weeks, I've acquired the Chicken Coop, Undead Graveyard, and Bandit Boss Dungeon Pets. Each one took 500-700 KC. Now I am on Spider Cave, with a current KC of 2000+ with no pet. When I got to 800 I thought "Man I'm getting unlucky with this one", but at this point where I've gotten 2k kills, I can't help to wonder maybe the drop rate or the spider dungeon may be bugged or possibly my account is bugged out? I'm hoping you can give some insight. Hoping I'm just really unlucky, haha. I hope to hear from you soon! Thank you for your time.

**Expected behavior**
The Wiki says all pets in the early dungeon stages are 1/350. I understand I could just be getting unlucky with the pulls, but at this point it seems extreme. Might be worth looking into the code and see if anything is messed up

**Browser**
I am just on Melvoridle.com/index.php. Early Access Alpha V0.21 (?1121). I am on Adventure Mode, not hardcore just regular.

**Are you using any scripts?**
Nope, just regular Melvor.

**Comment by MelvorIdle** [comment]
This is just bad RNG, the pet drops aren't broken.
