### ISSUE TITLE
ENT + MONKEY synergy not using monkey tablets while woodcutting online

### ISSUE THREAD

**Issue by kevolaf** [MelvorIdle/melvoridle.github.io#1369]
**Describe the bug**
ENT + MONKEY tablets in synergy while woodcutting does not use up the monkey tablets while online, but still gives the find 30% jewelry bonus. The monkey tablets ARE used up while offline.

**To Reproduce**
1. Equip Ent + Monkey synergy tablets
2. Chop down trees while online. This bug can't be replicated while offline.
3. Monkey tablets are not used up, but jewelry is still given to the player.

**Expected behavior**
Ent and Monkey tablets should be used when the synergy is active and while woodcutting online.

**Browser**
Steam

**Console output**
cloud.js?1121:76 Connected to PlayFab successfully
cloud.js?1121:76 PlayFab Connection Events Succeessful.
cloud.js?1121:76 PlayFab Connected: kevinolaf
save.js?1121:57 set force reload to 0
combatManager.js?1121:1 Combat Manager Built...
raidManager.js?1121:1 Golbin Raid Manager Built...
save.js?1121:14 Loading Save Game...
save.js?1121:14 Save Game Loaded...
main.js?1121:345 There was an error connecting to Steam. Steam Achievement functionality will not work.
main.js?1121:5 Game Loaded
Chart.bundle.min.js:1 Failed to load resource: the server responded with a status of 404 ()
Chart.bundle.min.js:1 Failed to load resource: the server responded with a status of 404 ()
cloud.js?1121:8 Synchronising with Cloud
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
cloud.js?1121:76 Connected to PlayFab successfully
cloud.js?1121:76 PlayFab Connection Events Succeessful.
cloud.js?1121:76 PlayFab Connected: kevinolaf
5cloud.js?1121:8 Synchronising with Cloud
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
No

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
