### ISSUE TITLE
Smithing Bug with Gloves 

### ISSUE THREAD

**Issue by Wildigw** [MelvorIdle/melvoridle.github.io#1371]
**Describe the bug**
If you wear the Smithing Gloves with Active Charges and Start Smithing you wont deplete/lose any stacks of the glove if you just tab out. You are still getting the 60% Bonus XP but the Glove Stacks dont deplete

**To Reproduce**
1. Equip the Glove
2. Create any Item on the Smithing Tab
3. Tab out the Game / Tab to a different Tab
4. Benefit from the 60% XP Endless 

**Expected behavior**
I expected the Charges to deplete

**Screenshots**
Impossible to Screenshot

**Browser**
Google Chrome

**Comment by coolrox95** [comment]
Issue was resolved in an update.
