### ISSUE TITLE
Re-plant all when crops ready

### ISSUE THREAD

**Issue by raiddn** [MelvorIdle/melvoridle.github.io#1372]
It would be great to have a "Re-plant all" button for farming when the current crop is ready. This could replant as many of the current crops with their seed as possible. Maybe options to auto-apply compost/gloop as well, and auto-buy if you don't have enough?

Thanks for your time and the great fun :)

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
