### ISSUE TITLE
Offline progress error

### ISSUE THREAD

**Issue by Gentlehawk** [MelvorIdle/melvoridle.github.io#1373]
**Describe the bug**

when On mobile any time I close the app or leave it open in the background it brings up an error that states “we ran into an error when calculating your offline progress” 

![5D983A16-EEDB-4BD3-A409-46FBAA3FCE61](https://user-images.githubusercontent.com/91307050/134624337-e216dc2f-9b63-4afc-851e-d78ab0c26a3c.png)

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
