### ISSUE TITLE
ModalQueue does not work as intended, always empty array

### ISSUE THREAD

**Issue by elverange** [MelvorIdle/melvoridle.github.io#1378]
**Describe the bug**
ModalQueue doesn't seem to be working as intended
For example, if you unlock pets while offline only the modal for the last unlocked pet will be displayed
The other modals (other pets unlocked, or the welcomeBackModal) are being superseded so there is no way to know what all happened while offline. ModalQueue is always an empty array.

**To Reproduce**
1. Take a fully maxed character save with no pets unlocked
2. Do Chicken Coop for 12h offline
3. When you get back, it's likely that several pets will be unlocked
4. Only one modal is displayed: the last one created. The other ones are discarded (included the WelcomeBackModal).

**Here is the save file for a no pet unlocked max character doing chicken coop for the past 12+ hours:** 
`H4sIAAAAAAAAA+1cy1IcuRL9lYleqwml3mI3EbO9mxt3BywYaMcQw9iOweONw/9+z8lUQQHduME8xo4ioUtSSalUKvMoS5T6y+rz6jC61fvV4ZF33iWRLKGJk+jEJZbgKswFQU5KDDnF0kLI2bHFWk7c6ndtLoP8Nd1Oz+6hzRXaHMVUyLOgLJboqlchUmD/KGpISKEYVaoLLOrN5dRa93q/u9R7Spm5nq3DWMK4Woc9j2sSVzQf7Br7qIc0rk3HjO6LjTxCDZmiHomPOYQek+u9asn1MO6nbufteqteAK/sGlimKg7KBnsXKgbdHEbmQqi+9F2stzHeLcZ1adHUd3wOzmvhL+Zjlm6zdJ+lZd5AZJ6J80yaZ/I8U+aZeZcy71PmnYZ5mzCrpgO4MUgZA8oybBO1zRzMCPSz6GcelafGcsfSZbvWF/pBSTpsQJIPas3wTbonrKC/uWTPOEafXEvekA6Gr4hbNbcvBWqq1AQ3yZmOBhcvJQBcS068W3Lt5urbCFCX6OLqo0yk5Eqn+5VATXfAMCA5dS2hVwMtY/D8aCgjqpdAUMACEbNHlUpGuOWzyxxLDRhajq55bygFuNWlLWgukGHymGeFoOpqdLESWyQNJd1ewgwggr+7sOlwtpZC3qhYOWEM06GxSx+GgQG+AHQZ8nYdDDISPcapNyOkDWjWNZs9aobA8QTfOAgsSqFD3o61UJoWc1mLEYuJVFaUqItl4ODRvCXgWbopDj3TGiQCeiUqT/ENiuDi5KlbKFm41EK4CF9gJfItXW0HuJzAGNrEbKc6lVOkWouBM6eKv+pLkfcwR36gvRCzIV20LEXjPbuVFYk1jfs1ZFtiRMeNX9NKdOVmilER4lsGYyuMDwLq12DKTpka4BoMFbC8AecjzckjsPFUadaABJGGdDaBXGp3CVZFpfQOk8oMVhguqcJw11dwLJWaSNMNKjsVzwhnlMDEMX2VqkUZhZAczFY4BDO8TE1BKvVKxCdWTouoIyzTiYsujOqsGkekFmiKOlboQBTAHg0Pdz29IvDyNgfgl9RHOF3ynZzvU4ahRyBJ4hQk2ktp9GIOu3A2dIqSjg9qyvR+sXwQTmzP14KiWUI0SXmpM5gwLVctg8ZkqD6cqKpbm9qKBRuWQwyq9ywY7hoTPAYmxXeau8JMGHZMkYIJKRRakZhddtYhGDBTBcbStaFij6j5KqQqJ0JnbkO0MlxFkSxi0KIoQc8JRAbHPtWPBIaX/YCrdo1OKikcIkDDVjN1p/gqMgKhLbMFeIotmfDUptA61DgCoESkpmaeSN9QATUXOpEO2Ji1HZEha5wJhIqM5C1UD9F4WU44F3juoEIUiAMraHe77FCqQoOpJdsaZ5nOdcoPaCGD5gbm1JbH8l9UQTTGa+kyYVTXDKoEq0XSOBd6ogZy0RJ2qMFvRNOm4C27DQQGbWLMOuOkqU3aHY6Sbsx058IovQE0FQmzhrmJGrY8uspUYHCGDHEgQK4Jg5euDqHxNCeFneYdknX6lvgxGaJtyFGfnoDtfUIsUTCIKudOEOnih7GZAN1ASgZa3UTh3o0lwJJBr/pHYM1h0m5RT6DCHtDu0wmLMOam2Do8rKy9WhBY8KSJZcXb4xdnjh5uZphy5DKURowA44smmuUQ2sHvsgUeROqumKb4krg+BM6VH4tG1zTUioxwqWE94ClCOix3wQACbokHb6xZA6fwzM7lt7o6IpqsZsjARvEUvk8oodAWGWahxN5PQqnUGmjVV1Lo/qQLroWtojFfNLUyjgymHtdUe0zHyJhS2tBMZHv1lTyGytAnxQm04ELRFoHxTBwb9x/KFIqrRXO6dnlS5uYLA21GIXTtxqlgEMbFr9pSF1LCTMc8rSsQgOtoL/zU2Be+y9UjDQMLmOse1OZrUZDcU1sv8Ow76xvcuf/C5UpXrN2J22UIjkI5qH38YJJ8Sr32A8tnhGrRj+qINrBWxnBQUugtxnyXV6utHMTBKj8kBLwoIdwLB4M3pznXUGNto2c+zTwwCA4WXkSHYaCdiwYo3CCSCVuDPZYoCMpIF9PTTHVTwYsSeuAGHnfuuGfH7To+J3Ajjptw3IDj5hs33BhZcKONm2zcYItNTk7c6r3uAs7kfP6A8nnH+4P2D10fbW9Li3uCHFsfKWgPbr4/tpVQa2eUgHt5K4cX1+3rk24sby+e9iT3JDbZtc3ywgN4zJPQd3SzK0L9FxLFfWKQSL96HQnDIzzqxNaSH36LO1uYsNBCCy200EILPR+N1ziemyyUktlnfdVl3CLP8RbKnk2utySe0F1+ctOfg+4r7w0ebV7hqWahhRZaaKE3JNn1yRWI73rib2zRP1j/Z6L8jfDj4RG/hD4e1v0+8/BW8zb9X/u1NbbQY2mZhV20+31+/XzoUWde/Wlb4nNnfYmny4WU3vofmwsttNBPRLWUnhtf303ZBaSaC0k6IbzwNdPE16Wd8N1rfSteOl/TFxel8Q3gLSwXiHpVupmLKHHR/UILLfRTUqi+1T2ukpOe/t0r8VaD2EbdN1/2uH57wHdb3JBsKXtDdbwUveqALCi67pqHaVp/g9f8Hk+Pixf+HdHFi8rMY/2IfqV8t+1ox8Hffx8ybd3BOuFL1h9Wh0erL8erqz8vLi+PV4fdHa9Ozz5dfHiPzPt/Li+R/3Tx1+bq0+lfH1E0+5IHKV9XbnV0vJIzaaH+3tYNsfw6SZV1Oz3frEvbtJbfxehPN8crMOobOd8AQNapbc7WKeS8Pn13frYu521zXnw87+3d8eoEXL+Q9fHqfxt2qslfLz/+cfrLZ38QREsg839O//7z6reLq7MPnzd/b84hHQo9hURfqHXocQ3jGsc1jWse1zKudVzbuPZxFT8lJo4ysZSJp0xMZeIqE1uZ+MrEWJTzV6TON+9O/7n89N/N2cVHKOhwX7M5+brCzJ2do4Wed8rFxei6HtkVd7O1djPrObhsB6rGCWWZVb33V8bXIqxFz8MVPJ61CDPl2ZDrf3pEHlUBEDV7z7jy2DVPvTQ7FFObHTjsPNDCgwo8Rc6DRjwkwZNB3c776YE6nnfhN3DI4GknSHnEzXjqISXwDDJ4BuOpfZJnHDyD8QzBeDZlFKPyjMZTD6aSZzKeUgZPO0tcSzWerRrPVownj8TxFFXMPGXHu5PMdmQUMqWMQa7Hd1noYYzMg1DTF07EYqLsmiSM1o4h6wngb81SEj2hpQdEEpQYqyvWxvqIdaq8w4b+DwmUK0bfRQAA`

**Expected behavior**
All modals should be shown in a stack to know what all happened while offline

**Are you using any scripts?**
This happens with or without script

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
