### ISSUE TITLE
Defence atribute visual bug

### ISSUE THREAD

**Issue by Gigasx** [MelvorIdle/melvoridle.github.io#138]
**Describe the bug**
On the stats screen and skill progress, it appears that the defence stat is not levelling up even with the defensive stance active, but it shows at bottom of screen it levelling up as it appear in the millestone.

**To Reproduce**
Just toggle the defensive stance fighting or click on combat screen "toggle skill proccess". it doenst show any exp gains.

**Expected behavior**
It should appear the correct level you are and the exp gains.

**Screenshots**
![image](https://user-images.githubusercontent.com/47761523/76455106-36a0ea80-63b4-11ea-86f2-f455af0f1ae1.png)
![image](https://user-images.githubusercontent.com/47761523/76455131-3d2f6200-63b4-11ea-9594-233bd2836a28.png)

**Browser**
Google Chrome Version 80.0.3987.132 64bits

Please tell us what browser you are using and what version.

**Comment by MelvorIdle** [comment]
Fixed in the next update.
