### ISSUE TITLE
Changing the header's position to sticky so it scrolls with the page

### ISSUE THREAD

**Issue by notpab** [MelvorIdle/melvoridle.github.io#1380]
Scrolling back and fourth to get to the menu has been one of the most annoying parts of this game for me so I wrote a fix in CSS.

```
#page-header {
    position: sticky;
    top: 0;
    z-index: 999;
}
```

In my case this is a 10/10 QOL improvement as I play in a ~500px wide window.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
