### ISSUE TITLE
Skeleton Fish Prayer Points

### ISSUE THREAD

**Issue by Munkeywaxx** [MelvorIdle/melvoridle.github.io#1382]
**Describe the bug**
Skeleton Fish showing 2 values for restoring prayer points.

**To Reproduce**
1. Go to Bank
2. Click on Skeleton Fish

![image](https://user-images.githubusercontent.com/3329277/134916549-1735b0fb-dd64-496b-9460-4dd33bec6db6.png)

**Browser**
Steam

**Are you using any scripts?**
No

**Comment by coolrox95** [comment]
Duplicate of #1327
