### ISSUE TITLE
Alt. Magic Offline Progression Calculation Failure

### ISSUE THREAD

**Issue by ThorvaldSpear** [MelvorIdle/melvoridle.github.io#1383]
**Describe the bug**
Offline progress of alt. magic skill did not calculate correctly.

**To Reproduce**
1. Start using Alt. Magic (I was using Bone Offering)
2. Leave the game open, open another tab
3. Wait some amount of time
4. Click back into Melvor
5. See bug

**Expected behavior**
Expected offline progress to calculate as usual

**Screenshots**
In-game bug message:
![image](https://user-images.githubusercontent.com/12387230/135113940-c599b1c2-08b7-4554-87cd-477470560d02.png)

**Browser**
Google Chrome Version 94.0.4606.61 (Official Build) (64-bit)

**Console output**
![image](https://user-images.githubusercontent.com/12387230/135114128-f00b42e2-a7d3-4b5b-a631-55323996f73c.png)

**Are you using any scripts?**
No

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
