### ISSUE TITLE
character select/splash screen issues at certain window widths

### ISSUE THREAD

**Issue by justzisguy** [MelvorIdle/melvoridle.github.io#1384]
**Describe the bug**
There are two bands of window width with awkward behavior.  

**To Reproduce**
Resize window width and note behavior, or just look at the screenshots.

**Expected behavior**
Account and character management always visible on character select/splash screen.

**Screenshots**
Widest to narrowest: 

* Working properly, wide window: ![OK_wide](https://user-images.githubusercontent.com/91563946/135149426-ea8e04b7-ba11-491b-ab38-d498a9a361da.png)
* Functional but probably not what you were hoping for (shown partly scrolled): ![awkward](https://user-images.githubusercontent.com/91563946/135149434-3b7e970e-fa7a-48d0-86e4-4f44e334e82f.png)

* No way to sign in without resizing window: ![broken](https://user-images.githubusercontent.com/91563946/135149437-cac5f9c9-fee6-4566-868e-ff99792e79a7.png)

* Working properly, narrow window: ![OK_narrow](https://user-images.githubusercontent.com/91563946/135149441-d22b49fa-bb15-4a42-8c6f-ca6b5818c0d5.png)

**Browser**
Issue appears in Firefox, Chrome, Edge, Opera, and the Steam version of the game, so I'm pretty sure it's universal.  

**Console output**
Here's Firefox's:

Google Analytics is being shimmed by Firefox. See https://bugzilla.mozilla.org/show_bug.cgi?id=1493602 for details. sandbox eval code:1:9
Some cookies are misusing the recommended “SameSite“ attribute 2
Cookie “PHPSESSID” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite checkCloudConnection.php
Cookie “PHPSESSID” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite checkCloudConnection.php
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ oneui.core.min.js:6:81449
Expected media feature name but found ‘-ms-high-contrast’. sweetalert2.min.css:1:815
Expected media feature name but found ‘-ms-high-contrast’. sweetalert2.min.css:1:840
Expected media feature name but found ‘-ms-high-contrast’. sweetalert2.min.css:1:6565
Expected media feature name but found ‘-ms-high-contrast’. sweetalert2.min.css:1:6590
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. sweetalert2.min.css:1:10913
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. sweetalert2.min.css:1:11031
Expected media feature name but found ‘-ms-high-contrast’. sweetalert2.min.css:1:16971
Expected media feature name but found ‘-ms-high-contrast’. sweetalert2.min.css:1:16996
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. ion.rangeSlider.css:1:1301
Error in parsing value for ‘-webkit-text-size-adjust’.  Declaration dropped. oneui.css:3:136
Unknown pseudo-class or pseudo-element ‘-ms-expand’.  Ruleset ignored due to bad selector. oneui.css:3:24072
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. oneui.css:3:24461
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. oneui.css:3:24521
Unknown pseudo-class or pseudo-element ‘-ms-value’.  Ruleset ignored due to bad selector. oneui.css:3:24919
Unknown pseudo-class or pseudo-element ‘-ms-value’.  Ruleset ignored due to bad selector. oneui.css:3:62124
Unknown pseudo-class or pseudo-element ‘-ms-expand’.  Ruleset ignored due to bad selector. oneui.css:3:62366
Unknown pseudo-class or pseudo-element ‘-ms-thumb’.  Ruleset ignored due to bad selector. oneui.css:3:64230
Unknown pseudo-class or pseudo-element ‘-moz-focus-outer’.  Ruleset ignored due to bad selector. oneui.css:3:64317
Ruleset ignored due to bad selector. oneui.css:3:64880
Unknown pseudo-class or pseudo-element ‘-ms-thumb’.  Ruleset ignored due to bad selector. oneui.css:3:65783
Unknown pseudo-class or pseudo-element ‘-ms-thumb’.  Ruleset ignored due to bad selector. oneui.css:3:66198
Unknown pseudo-class or pseudo-element ‘-ms-thumb’.  Ruleset ignored due to bad selector. oneui.css:3:66260
Unknown pseudo-class or pseudo-element ‘-ms-track’.  Ruleset ignored due to bad selector. oneui.css:3:66317
Unknown pseudo-class or pseudo-element ‘-ms-fill-lower’.  Ruleset ignored due to bad selector. oneui.css:3:66472
Unknown pseudo-class or pseudo-element ‘-ms-fill-upper’.  Ruleset ignored due to bad selector. oneui.css:3:66546
Unknown pseudo-class or pseudo-element ‘-ms-thumb’.  Ruleset ignored due to bad selector. oneui.css:3:66908
Unknown property ‘-moz-column-count’.  Declaration dropped. oneui.css:3:71860
Unknown property ‘-moz-column-gap’.  Declaration dropped. oneui.css:3:71920
Unknown property ‘orphans’.  Declaration dropped. oneui.css:3:71955
Unknown property ‘widows’.  Declaration dropped. oneui.css:3:71964
Unknown property ‘orphans’.  Declaration dropped. oneui.css:3:161108
Unknown property ‘widows’.  Declaration dropped. oneui.css:3:161117
Unknown property ‘size’.  Declaration dropped. oneui.css:3:161159
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. oneui.css:3:161745
Error in parsing value for ‘font-weight’.  Declaration dropped. oneui.css:3:210538
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. oneui.css:4:162
Unknown property ‘speak’.  Declaration dropped. oneui.css:7:1266
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. oneui.css:7:1418
Error in parsing value for ‘padding-left’.  Declaration dropped. oneui.css:7:27682
Error in parsing value for ‘padding-left’.  Declaration dropped. oneui.css:7:29061
Unknown property ‘-moz-font-smoothing’.  Declaration dropped. game.css:1:151
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. game.css:1:217
Unknown property ‘-moz-background-size’.  Declaration dropped. game.css:1:355
Unknown property ‘-moz-box-shadow’.  Declaration dropped. game.css:1:7326
Unknown property ‘-moz-box-shadow’.  Declaration dropped. game.css:1:7658
Unknown pseudo-class or pseudo-element ‘last’.  Ruleset ignored due to bad selector. game.css:1:16818
Error in parsing value for ‘max-width’.  Declaration dropped. toastify.min.css:14:779
Error in parsing value for ‘max-width’.  Declaration dropped. toastify.min.css:14:923
Error in parsing value for ‘border’.  Declaration dropped. style.css:1:1070
Source map error: Error: request failed with status 403
Resource URL: https://cdn.melvor.net/core/v018/as
sets/css/lib/toastify.min.css?1129
Source Map URL: /sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map

**Are you using any scripts?**
Not in most of the browsers I tested with.

**Comment by MelvorIdle** [comment]
I believe this has been fixed. Please open a new bug report if it has not
