### ISSUE TITLE
"Toggle Mini Sidebar Mode" cuts off the logo in Steam version

### ISSUE THREAD

**Issue by kaidejager** [MelvorIdle/melvoridle.github.io#1385]
When Toggle Mini Sidebar Mode is on in the Steam App it cuts off part of the M

**To Reproduce**
1. Toggle Toggle Mini Sidebar Mode
2. Look at logo in top right corner

Should shrink to center of the sidebar

![Annotation 2021-09-28 215519](https://user-images.githubusercontent.com/51215548/135157020-a414e513-b868-4464-92f1-c57aa68f2c6a.jpg)

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
