### ISSUE TITLE
"Welcome back!" summary popup gets omitted if any kill rose a level upon return ("Level Up Notification" >   LARGE)

### ISSUE THREAD

**Issue by NiIex** [MelvorIdle/melvoridle.github.io#1386]
**Describe the bug**
Upon reopening Melvor, Welcome back! summary is simply not shown if any skill leveled up since closing the game.

**To Reproduce**
1. Set "Level Up Notification" > LARGE
2. Be active in any skill and close the game before it or any other levels up.
3. Open Melvor again and get greeted with skill level up.
4. Welcome back! summary is never shown.

**Expected behavior**
Welcome back! summary should always be shown, regardless of "Level Up Notification" setting. Preferably before anything else. Saves us the burden of having to manually check every piece of accumulated loot while retaining the comfort of not missing skill level up notification.

**Browser**
Latest Opera (chromium based, RIP Presto). Melvor is v0.21 (?1129)

**Are you using any scripts?**
SEMI & Combat Simulator Reloaded. Issue persists with extensions disabled as well.

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
