### ISSUE TITLE
Unable to load old cloud save

### ISSUE THREAD

**Issue by MoMullet** [MelvorIdle/melvoridle.github.io#1387]
Error Code:
https://ios.melvoridle.com/assets/js/built/serializeSave.js?1168:177:182
forEach@[native code]
convertOldMastery@https://ios.melvoridle.com/assets/js/built/serializeSave.js?1168:177:88
setGlobalsFromSaveGame@https://ios.melvoridle.com/assets/js/game/save.js?1168:45:212
loadData@https://ios.melvoridle.com/assets/js/game/save.js?1168:14:121
finaliseLoad@https://ios.melvoridle.com/assets/js/game/main.js?1168:339:88
selectCharacter@https://ios.melvoridle.com/assets/js/game/main.js?1168:331:302
onloadEvent@https://ios.melvoridle.com/assets/js/game/save.js?1168:60:282
https://ios.melvoridle.com/assets/js/game/save.js?1168:64:297
https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84826
each@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:2971
https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84807
r@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:28088
fireWith@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:28852
c@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:79495
https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:81938

**Comment by MelvorIdle** [comment]
I believe this has been fixed. Please open a new bug report if it has not
