### ISSUE TITLE
Automatic cloud saving although it is disabled

### ISSUE THREAD

**Issue by alaaneme** [MelvorIdle/melvoridle.github.io#1388]
**Describe the bug**
After loading a savegame, in a few seconds it automatically saves to cloud. It does not seem to do it later automatically. Just once. This is not expected as I have not enabled automatic cloud saving in the settings.
Started happening today, after major update to cooking and thieving (V0.22 ?1169)

**To Reproduce**
1. Load savegame
2. Wait 10 seconds (seems like exactly)
3. See the pop-up that cloud save was completed
4. To confirm that it was an actual save to cloud not just a pop-up message log go back to character selection screen and see that it has indeed saved.
5. This is replicable every time.

**Expected behavior**
It should never automatically cloud save if cloud saving is not enabled in settings.

**Screenshots**
Not applicable

**Browser**
Chrome Version 94.0.4606.61 (Official Build) (64-bit), Windows 10 64bit

**Console output**
https://pastebin.com/raw/v1NFXTck

**Are you using any scripts?**
No scripts.

**Comment by NiIex** [comment]
Can confirm. Using latest Opera browser. Feels unintentional since not mentioned in changelog.

**Comment by MelvorIdle** [comment]
This is now hotfixed.
