### ISSUE TITLE
Cannot equip \ Farm plots dissapeared

### ISSUE THREAD

**Issue by Groknik** [MelvorIdle/melvoridle.github.io#139]
**Describe the bug**
I cannot cycle gear onto my equipment set, I have had this issue once before and it had to be fixed by you.

Also I lost my auto eat rank 2 and now have no auto eat

also at the same time my farming plots disappeared, I bought them all back again its not a huge issue to me but maybe it helps with a fix. 

**To Reproduce**
1. Go to any gear
2. Click on "1" to equip an item
3. Scroll down to
4. See nothing happens.

**Expected behavior**
The item would equip, I had required stats and plenty of bag space.

**Browser**
Edge 44.18362.449.0

**Console output**
Please open the console by pressing F12 and copy it here. I'm not exactly sure what part you want me to copy it did not seem very copy pastable.

**Comment by Groknik** [comment]
![image](https://user-images.githubusercontent.com/62079602/76760605-b4764480-676c-11ea-8867-a58c58368258.png)
now I can't even play

**Comment by MelvorIdle** [comment]
Are you still locked out of the game?
