### ISSUE TITLE
When playing I have the crafting unlocked but I cannot wear the leather armor in less I have range combat unlocked I do not understand that am I not allowed to wear leather armor and less I'm attacking with a bow I think you should be able to wear leather armor no matter what you're attacking with that's just my thought I was very upset to find out that I have to unlock something else to be able to wear leather armor

### ISSUE THREAD

**Issue by Litlbigbro** [MelvorIdle/melvoridle.github.io#1390]
Please be as detailed as possible when making suggestions.

Why are you suggesting this?

How does your suggestion benefit the game?

It is suggested that you provide (mockup) art to ilustrate things where relevant in order to make your suggestion more clear.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
