### ISSUE TITLE
Can't buy auto eat

### ISSUE THREAD

**Issue by commoncat** [MelvorIdle/melvoridle.github.io#1391]
I have enough money but auto eat is still not available?

![image](https://user-images.githubusercontent.com/91627063/135318725-16156006-6ce0-44fd-be7f-9b6e66408b0a.png)

**Comment by NiIex** [comment]
You are missing a "K" (K=1000). Actual price is 1M (million).
You can change GP notation in Settings to more familiar system. Or simply get used to this one.
