### ISSUE TITLE
Passive combat

### ISSUE THREAD

**Issue by Lewisdoran28** [MelvorIdle/melvoridle.github.io#1395]
When fighting in dungeons specifically volcanic dungeon which I have completed over 100 times before without issue since the update its randomly killing me when on passive despite using same food same armour as always and the same with the dungeon below the volcanic one except this wasn't on passive it was the last monster and I had nearly full health and it just said I had died.

**Comment by MelvorIdle** [comment]
Please be sure to take note of combat changes during updates
