### ISSUE TITLE
Seed Bag milestone seems to display wrong level requirement 

### ISSUE THREAD

**Issue by elestora** [MelvorIdle/melvoridle.github.io#1396]
**Describe the bug**
The milestones tab of crafting shows the level requirement for the new Seed Bag to be 35, but the crafting page seems to have it locked behind a level 42 wall

**To Reproduce**
1. Go to 'Crafting - Bags' with crafting level below 42
2. See that the Seed Pouch (second pouch available) is locked behind level 42 requirement
2. Click on 'Milestones' 
3. Scroll down to 'Seed Pouch'
4. See that the specified level requirement is 35

**Expected behavior**
The milestones tab and the crafting page should agree on level requirements

**Screenshots**
![Screenshot_20210929-192206_Melvor Idle](https://user-images.githubusercontent.com/68196988/135361761-cacbbd37-59c5-4208-9d95-f0543da39754.jpg)
![Screenshot_20210929-192216_Melvor Idle](https://user-images.githubusercontent.com/68196988/135361770-5abbd7ef-4fb2-4480-bd1b-bf5c3cebaf93.jpg)

**Browser**
Android

**Console output**
N/A

**Are you using any scripts?**
N/A

**Comment by Largartor** [comment]
I can confirm that it is happening in steam version either.

**Comment by MelvorIdle** [comment]
This is now hotfixed
