### ISSUE TITLE
Unable to load offline progress 

### ISSUE THREAD

**Issue by HoodieG** [MelvorIdle/melvoridle.github.io#1398]
Unable to load offline progress 

**To Reproduce**
1. Open app
2. Receive error

**Expected behavior**
1. Open app
2. Receive total offline production 

**Screenshots**
Unable to add screenshot via iOS but error is as follows:

"Please let the dev know of this error: 
Skill: 13
Action: 55
Timestamp: 1632914514382

selectFletch@https://ios.melvoridle.com/assets/js/game/fletching.js?1129:5:1089@https://ios.melvoridle.com/assets/js/game/main.js?1129:182:555"

**Browser**
Safari, iOS 15.0

**Console output**
N/A

**Are you using any scripts?**
NO

**Comment by HoodieG** [comment]
@TheMalcs - seems I'm not the only one...any resolution?

**Comment by MelvorIdle** [comment]
I believe this has been fixed. Please open a new bug report if it has not
