### ISSUE TITLE
Cant log in 

### ISSUE THREAD

**Issue by Zambookie** [MelvorIdle/melvoridle.github.io#1399]
**Describe the bug**
Started afk thieving after update now can't log back in just white screen on mobile

**To Reproduce**
1. Go to 

**Expected behavior**

**Screenshots**

**Browser**
Please tell us what browser you are using and what version.

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

**Comment by MelvorIdle** [comment]
I believe this has been fixed. Please open a new bug report if it has not
