### ISSUE TITLE
Lost progress

### ISSUE THREAD

**Issue by Tripleoseven** [MelvorIdle/melvoridle.github.io#1400]
**Describe the bug**
This morning I logged in and could continue where I left off. The game crashed and I wasn't able to log in. After an hour I was able to login but the last save was 83 hours ago. I lost a lot of progress during that time. For example 12 agility levels and 200 mastery levels. I only play on the app on Android.

Kind regards

**Comment by MelvorIdle** [comment]
Unfortunately there is not much we can do about lost progress due to bugs.
