### ISSUE TITLE
Fisherman summoning synergy while pickpocketing

### ISSUE THREAD

**Issue by Bdogmeister** [MelvorIdle/melvoridle.github.io#1401]
**Describe the bug**
While using the Octopus and Leprechaun familiar tablets when pickpocketing the Fisherman, it changes the interaction to 3.5 seconds from 2.0 seconds as well as increase the mastery xp.

**To Reproduce**
1. Go to 'Thieving - Fisherman'
2. Click on 'View Summoning Synergy Search'
3. Scroll down to 'Octopus + Leprechaun Familiars'

**Expected behavior**
The action length to be decreased by 50% and keep master xp the same.

**Screenshots**
![cdsonkflcR](https://user-images.githubusercontent.com/91660033/135417862-bdf82284-145d-48e6-968e-7f327d8caa7d.png)
![fNdsgDi84i](https://user-images.githubusercontent.com/91660033/135417875-a771ac98-b3ba-460a-a8b8-41068338ddf2.png)

**Browser**
Brave Version 1.29.81 Chromium: 93.0.4577.82

**Console output**
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
style.css:1 Failed to load resource: the server responded with a status of 404 ()
ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
​ jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
cloud.js?1176:66 Connected to PlayFab successfully
cloud.js?1176:67 PlayFab Connected: Bdogmeister
save.js?1176:57 set force reload to 1
combatManager.js?1176:1 Combat Manager Built...
raidManager.js?1176:1 Golbin Raid Manager Built...
save.js?1176:14 Loading Save Game...
save.js?1176:14 Save Game Loaded...
main.js?1176:5 Game Loaded
SEMI.js:172 good
cloud.js?1176:8 Synchronising with Cloud
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
utils.js:532 Game Loaded. SEMIUtils ready.
event-bus.js:59 Starting Event Bus
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
cloud.js?1176:66 Connected to PlayFab successfully
cloud.js?1176:67 PlayFab Connected: Bdogmeister
menus.js:99 SEMI v0.8.1 Loaded!
VM5088:85 Melvor ETA: loading...
VM5088:85 Melvor ETA: loaded!
mastery-enhancements.js:88 Loading Mastery Enhancements
core.js:259 auto-master enabled at 9/30/2021, 2:32:35 AM
core.js:259 auto-sell enabled at 9/30/2021, 2:32:35 AM
core.js:259 auto-farm enabled at 9/30/2021, 2:32:35 AM
core.js:259 drop-chances enabled at 9/30/2021, 2:32:35 AM
core.js:259 save-on-close enabled at 9/30/2021, 2:32:35 AM
sort-override.js:1146 Attempting to modify Main.js sortBank
sort-override.js:1150 Successfully adjusted bank sort order.
core.js:259 sort-override enabled at 9/30/2021, 2:32:35 AM
VM5088:85 Melvor ETA: Failed to add settings menu! Melvor ETA will work fine without it. Install the "Melvor Idle Combat Simulator Reloaded" extension to use the settings interface.
VM5088:85 Melvor ETA: Find it here: https://github.com/visua0/Melvor-Idle-Combat-Simulator-Reloaded
core.js:259 destroy-crops enabled at 9/30/2021, 2:32:51 AM
core.js:238 destroy-crops Disabled!
cloud.js?1176:8 Synchronising with Cloud
style.css:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
SEMI v0.8,1 After disabling the script the bug still occurred

**Comment by MelvorIdle** [comment]
This is the intended mechanic, the Synergy increases the time it takes to pickpocket the Fisherman.

I believe the refactor of language strings behind the scenes produced the incorrect description. This has now been hotfixed.
