### ISSUE TITLE
Add current level to the Milestones tab

### ISSUE THREAD

**Issue by kaidejager** [MelvorIdle/melvoridle.github.io#1404]
Add your current level in each skill to the Milestones tab

For a better screenshot of current skills, if nothing else

This would allow a better format of screenshot for sharing your accomplishments with friends and possibly lead to more recruitments. 

![Milestones](https://user-images.githubusercontent.com/51215548/135538939-f77d1bed-ecc4-4361-98da-97c416332ed4.jpg)

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
