### ISSUE TITLE
GP Burned on the firemaking statistics incorrect 

### ISSUE THREAD

**Issue by CapitalDave** [MelvorIdle/melvoridle.github.io#1407]
When I check the statistic for GP burned, I noticed that it is increasing incorrectly. My Magic Logs sell for 600gp, and it increases by 400gp each time I burn one. 

**To Reproduce**
1. Achieve the woodcutting milestone to sell logs for 50% extra
2. do firemaking
3. check the statistics screen for firemaking

**Expected behavior**
It should increase by the value you can sell for, accounting for woodcutting mastery. I also wonder if it subtracts the amount gained from FM mastery (I don't have that much mastery xp yet)

**Browser**
I'm using the android app.

**Comment by MelvorIdle** [comment]
I believe this has been fixed. Please open a new bug report if it has not
