### ISSUE TITLE
Passive cooking "Speedhack"-Bug

### ISSUE THREAD

**Issue by Pandadoxon** [MelvorIdle/melvoridle.github.io#1408]
**Describe the bug**
Offline passive stockpile is added over and over again, after switching tabs in browser or on mobile between apps. Passive cooking ingredients are used for the added stockpile meals. 

**To Reproduce**
1. Go to Cooking
2. Use active and passive cooking
3. Switch browser tab or on mobile change to another app
3. Wait until a passive cooking meal is finished
4. Switch back to melvor
5. Stop active cooking
6. Switch tab or app
7. Switch back to melvor
8. Get offline message, that passive cooking is in stockpile
9. Repeat switching tabs and back to melvor
10. Empty stockpile
11. Start over switching tabs

**Expected behavior**
Cooked meals are not cooked and added to stockpile again, after triggering offline process

**Browser**
Chrome 93.0.4577.82 (Official Build)
Melvor App

**Console output**
main.js?1180:411 
Uncaught TypeError: Cannot read properties of null (reading 'style')
    at resetProgressAnimation (main.js?1180:411)
    at stopActiveCookTimer (cooking2.js?1180:9)
    at pauseOfflineAction (main.js?1180:261)
    at Game.pauseActiveSkill (game.js?1180:15)
    at save.js?1180:61
    at ifvisible.js:5
    at Array.forEach (<anonymous>)
    at Object.t.fire (ifvisible.js:5)
    at e.IfVisible.blur (ifvisible.js:9)
    at HTMLDocument.t (ifvisible.js:9)

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
This kind of issue will be addressed when cooking is eventually made tick-based
