### ISSUE TITLE
Pile of Oress - Plural grammar on most new openable items

### ISSUE THREAD

**Issue by snell-matthew-a** [MelvorIdle/melvoridle.github.io#1409]
![image](https://user-images.githubusercontent.com/63681084/135623290-3569ac8d-55d1-4272-a626-1c3a70720fdc.png)

Default behavior of adding an s to the end of the string to make it plural is not working great here.  Either needs more robust solution around that, or to rename the items.  So "Crate of Basic Supplies" becomes "Basic Supply Crate," etc.

This affects:

- Crate of Basic Supplies
- Crate of Food
- Stack of Bones
- Pile of Logs
- Pile of Ores
- Chest of Gems

Also, the grammar with "opening" a pile of items is unnatural, "sorting" might be better.  Probably an additional variable for anything with `canOpen: true` describing the syntax to use would be good?  Or using a string in place of `true`: `canOpen: "pilfer"` -> "You pilfer 100 Pirate Booty"

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
