### ISSUE TITLE
Smithing Gloves (50% Exp) Not giving 50% after last patch.

### ISSUE THREAD

**Issue by Katako1** [MelvorIdle/melvoridle.github.io#141]
**Describe the bug**
The Smithing Gloves which suppose to give extra 50% experience are giving less than 50% for example if you craft Rune Gloves which give 150 exp, when you equip the Smith Gloves you get 225 exp and not 300 like before.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser**
Please tell us what browser you are using and what version.

**Console output**
Please open the console by pressing F12 and copy it here.

**Comment by ATaylor1027** [comment]
225 is in fact 50% more then 150, if you were to get 300xp for smithing rune gloves, that would be 100% more xp.

**Comment by amicloud** [comment]
Uh yeah the gloves are definitely working as intended.
