### ISSUE TITLE
Potatoes not dropping from Plants at 100% chance

### ISSUE THREAD

**Issue by jvmcarneiro** [MelvorIdle/melvoridle.github.io#1410]
**Describe the bug**
Version Alpha v0.22 states that "The Plant now has a 100% chance to drop an item on death, up from 75%", but potatoes are still not dropping at 100% chance.

**To Reproduce**
1. Kill some plants
2. See that not every plant drops potatoes.

**Expected behavior**
Plants should drop potatoes every time they're killed.

**Are you using any scripts?**
No.

**Comment by coolrox95** [comment]
Issue was resolved with Alpha V0.22.1.
