### ISSUE TITLE
Thieving interrupted with full inventory even with Enable Ignore Bank Full

### ISSUE THREAD

**Issue by jvmcarneiro** [MelvorIdle/melvoridle.github.io#1412]
**Describe the bug**
Thieving gets automatically interrupted offline when the inventory gets full, wasting progress. The option "Enable Ignore Bank Full" seems to describe the issue and is disabled by default, but enabling it doesn't change the behavior (I don't even see a reason for having it disabled, much less by default).

**To Reproduce**
1. Start offline thieving
2. Get a full inventory while offline
3. Come back later to full bank message
4. Realize you got way less loot than you should (only up to the point where your bank got full)

**Expected behavior**
When you get a full inventory while offline skilling you should continue skilling and receiving loot you can still carry, much like when autolooting in offline combat, instead of having it interrupted and having potential progress wasted.

**Screenshots**
![image](https://user-images.githubusercontent.com/7219775/135670789-904e4606-03e4-4f04-be0f-bbc713c05dc8.png)

**Are you using any scripts?**
No.

**Comment by coolrox95** [comment]
I cannot reproduce this behavior using the provided steps.
Here is some example offline progress with both the Continue Thieving while stunned and Ignore Bank Full settings enabled.
Started with 3 bank slots available in testing, and it is functioning as intended
![image](https://user-images.githubusercontent.com/58208131/135768686-1e4a3d41-af32-4c6a-8af0-060ae010655d.png)
