### ISSUE TITLE
Degrading performance while summoning

### ISSUE THREAD

**Issue by Orksork** [MelvorIdle/melvoridle.github.io#1413]
**Describe the bug**
While summoning, the time between task completion and the screen updating with the items gained grows longer and longer until the summoning screen seems to be completely frozen. This also seems to apply to selecting certain items in the "Crafting" tab, namely anything in the 'ring', 'necklace', or 'bag' categories.

Restarting the game seems to reset this setting it back to the expected behavior, but it did reappear after a little bit of time.

I tried out the chromium profiler and saw a "Long Task" that was at 500ms when I first noticed the bug the 2nd time, and over the course of 30 minutes it profiled at 1s+. When I had it completely frozen I had had the game open for ~20 hours at once.

**To Reproduce**
1. Start summoning
2. Over time the time between completed tasks and seeing the progress bar moving will extend

**Expected behavior**
The screen to refresh as quickly as it does in other skills.

**Screenshots**
Profile view
![image](https://user-images.githubusercontent.com/30049372/135672796-f9bcb767-c4d4-4fde-9b6a-9f867730a010.png)

Took a video of the problem in process:
https://youtu.be/O2vONrZHfyY

**Browser**
Melvor App

**Are you using any scripts?**
No scripts

**Comment by MelvorIdle** [comment]
I believe this has been addressed somewhat. Please open a new bug report if it has not
