### ISSUE TITLE
offline cooking not automatically equipping food when made

### ISSUE THREAD

**Issue by Ymabean** [MelvorIdle/melvoridle.github.io#1416]
**Describe the bug**
When offline, food will not automatically equip and will be lost if bank is full.

**To Reproduce**
1. Start cooking with one or zero remaining bank slots (and produced food/perfectly cooked food not taking a bank slot)
2. go offline
3. food will be sent to inventory instead of equip automatically and if bank is full, food will be lost.

**Expected behavior**
offline cooking of food should automatically send completed food to equip like when cooking online

**Screenshots**
N/A

**Browser**
Steam client

**Are you using any scripts?**
no

**Comment by coolrox95** [comment]
Issue has been fixed as of update v1.0.3.
