### ISSUE TITLE
Stockpile not showing current stock

### ISSUE THREAD

**Issue by kfbest** [MelvorIdle/melvoridle.github.io#1418]
Coming back from offline, get notice I have food in stockpiles. But when going into the cooking section, the stockpiles show as 0 with a blank square. Doesn’t happen all the time, but often. 

Not sure if related, but sometimes quantities of items in my bank are not updating until I tap on them. 

Running on iPad OS 14.

**Comment by MelvorIdle** [comment]
I believe this has been fixed. Please open a new bug report if it has not
