### ISSUE TITLE
Summoning Synergy XP Incorrect

### ISSUE THREAD

**Issue by Bian18** [MelvorIdle/melvoridle.github.io#1419]
**Describe the bug**
I've noticed when using the Leprechaun + Salamander synergy that I have only been gaining the amount of XP that I would usually gain from just the Leprechaun tablet (approximately 24xp). Though I am receiving the benefits of the synergy (bars) and it is using my salamanders.

**To Reproduce**
1. Equip Leprechaun + Salamander synergy
2. Pickpocket miner
3. Go to summoning page to watch xp increase
4. See decreased xp gain

**Expected behavior**
I expected to be earning XP for the 2 leprechaun tablets and 1 salamander tablet (approx 75xp) per action

**Screenshots**
![IMG_1217](https://user-images.githubusercontent.com/91816701/135740294-e6164aa2-b99b-4155-a2fe-3d90a10a033b.PNG)
![IMG_1218](https://user-images.githubusercontent.com/91816701/135740298-294aecd0-6e5a-4b42-b6ca-6f21fad5e302.PNG)
[](url)

**Browser**
IOS V0.22 (?1180)

**Console output**
Unsure how to do this on IOS

**Are you using any scripts?**
Not using any scripts

**Comment by coolrox95** [comment]
Issue was resolved with Alpha V0.22.1.
