### ISSUE TITLE
TypeError: bank[i] is null

### ISSUE THREAD

**Issue by elebascle** [MelvorIdle/melvoridle.github.io#142]
While mining, got a second runite stack in the bank with only 1 item in it.
I tried to drag and drop this stack on the other stack (stupid me).
Instantly I got this error : TypeError: bank[i] is null

I cannot play anymore, my save seems corrupted, each time I refresh the page I have the same error.

Please Help !

**Comment by MelvorIdle** [comment]
Reload the game and click the blue "Fix my Save" button at the bottom of the error box. This should fix your issue.

**Comment by elebascle** [comment]
First, thanks for your email, I really appreciate it !

There was no button at the bottom, just the error message.

I managed to edit the bank content directly and removed the null at the end
of the array and it worked :-)

I really like your game !
Quick question : will there be a reset after the alpha ?

Thank.

**Comment by MelvorIdle** [comment]
No reset will be occurring :)

**Comment by GeneReyva** [comment]
I am now having this issue, as are a few other people. If "edit the bank content directly and removed the null at the end of the array" works as a fix then how do we do that?
