### ISSUE TITLE
Sunset Rapier showing Special Attack as Sandstorm in Goblin Raid

### ISSUE THREAD

**Issue by linkinprk1981** [MelvorIdle/melvoridle.github.io#1422]
**Describe the bug**
**To Reproduce**
I started the Goblin raid today, at one point I was offered the Sunset Rapier as a weapon.  Upon equipping it, my attack icon changed and the hover tooltip indicates it is for Sandstorm. I do NOT have the sandstorm ring (owned nor equipped). I have not used this item in standard game to know if it exists there too or isolated to Goblin Raid

**Expected behavior**
To be Sunset Stab, not Sandstorm

**Screenshots**
Empty Finger slot: https://imgur.com/a/aaVyvnu

Sunset Rapier: https://imgur.com/cJdPy8O

Special Attack: Sandstorm:  https://imgur.com/AWu2axU

Using Sandstorm: https://imgur.com/XEyGlfS

All EQ equipped:
Elder Crown
Infernal Cape
Gold Diamond Necklace
Bronze Arrows
Ancient Bodyplate
Recoil Shield
Miolite Legplates
Dragon Gloves
(S) Dragon Boots

No additional runes or ranged 

**Browser**
Firefox 92.0.1 (64-Bit)

**Console output**
Connected to PlayFab successfully cloud.js:66:335
PlayFab Connected: linkinprk1981 cloud.js:67:98
set force reload to 0 save.js:57:60
Combat Manager Built... combatManager.js:1:636
Golbin Raid Manager Built... raidManager.js:1:975
Loading Save Game... save.js:14:29
Save Game Loaded... save.js:14:140
Game Loaded main.js:5:376
Loading failed for the <script> with source “https://static.cloudflareinsights.com/beacon.min.js”. update_v022.html:485:1
Loading failed for the <script> with source “https://static.cloudflareinsights.com/beacon.min.js”. index.html:563:1
1429.8076923076924 main.js:166:472
jQuery.Deferred exception: Chart is not defined value@https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316
value@https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626
@https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705
e@https://melvoridle.com/assets/js/oneui.core.min.js:6:29792
c/</t<@https://melvoridle.com/assets/js/oneui.core.min.js:6:30116
 undefined oneui.core.min.js:6:31368
Connected to PlayFab successfully cloud.js:66:335
Uncaught ReferenceError: Chart is not defined
    value https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6
    value https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6
    <anonymous> https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6
    e https://melvoridle.com/assets/js/oneui.core.min.js:6
    t https://melvoridle.com/assets/js/oneui.core.min.js:6
be_pages_dashboard.min.js:6:1316
PlayFab Connected: linkinprk1981 cloud.js:67:98
Synchronising with Cloud cloud.js:8:109
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features! melvoridle.com
Synchronising with Cloud 2 cloud.js:8:109

​**Are you using any scripts?**
No scripts

**Comment by coolrox95** [comment]
You selected an (ALT) Sunset Rapier. This is a weapon that has a random special attack instead of the original one for the weapon.
