### ISSUE TITLE
Current Character save file is not working properly

### ISSUE THREAD

**Issue by Rattlesnayk** [MelvorIdle/melvoridle.github.io#1423]
**Describe the bug**

Characters save file cannot progress offline, nor can it currently Cook, or Theive. when signing into the character an error pops up asking to fix my save, I have attempted this numerous times to no avail. Created a new character to see if it was game wide, and its just my main character save, have tried Cloud saves vs local saves and nothing changes. any help is greatly appreciated

**To Reproduce**

1. Log on to character via browser
2. as character loads an error pops up
3. follow the prompt to fix my save
4. prompt logs me out, re log in
5. same error occurs, this loop happens endlessly
6. attempt to start thieving or cooking
7. no progress bar happens, almost as if it didnt register the action even after multiple clicks/attempts
8. ALL OTHER SKILLS WORK, only skills I cannot access are the 2 updated ones

**Expected behavior**

1. log into character
2. character loads properly showing any offline progress made
3. click on either cooking or thieving, and begin training whichever skill.
4. continue having fun

**Screenshots**

![Errordisplay](https://user-images.githubusercontent.com/91847987/135768741-57c70d55-2b98-4fb1-8c7b-c1dd99216d20.png)

**Browser**
Please tell us what browser you are using and what version.

Current Browser is Google Chrome, and version of game is v0.22

**Console output*
Please open the console by pressing F12 and copy it here.

![Consolestatus](https://user-images.githubusercontent.com/91847987/135768927-b989bae9-144f-4ae7-ab04-5e12dfc0f7a6.png)

**Comment by MelvorIdle** [comment]
I believe this has been fixed. Please open a new bug report if it has not
