### ISSUE TITLE
Passive cooking without products (apple)

### ISSUE THREAD

**Issue by bamp3r** [MelvorIdle/melvoridle.github.io#1424]
**Describe the bug**
Ability to create apple pies without apples

**To Reproduce**
1. Go to 'Cooking'
2. Click on 'Select recipe to cook' in Furnace
3. Choose Apple pie
4. Start any active cookin (I cooked sharks)
5. Start passive cooking Apple pie without apples
6. A message will appear that it is impossible to cook apple pie without apples
7. Wait
8. Collect apple pies from stockpile

**Expected behavior**

**Screenshots**

**Browser**
Chrome latest

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

**Comment by coolrox95** [comment]
Duplicate of #1393
