### ISSUE TITLE
Cooking Pot and Furnace not there, 

### ISSUE THREAD

**Issue by fukasz2000** [MelvorIdle/melvoridle.github.io#1428]
**Describe the bug**

**To Reproduce**
The cooking pot is not active looks like I never bought it, it took my money and never appeared.

**Expected behavior**
Well I wish I could use the furnace and cooking pot to cook some food.

**Screenshots**

**Browser**
iOS 15

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

**Comment by MelvorIdle** [comment]
I believe this has been fixed. Please open a new bug report if it has not
