### ISSUE TITLE
Longrange and Defensive (magic) attack styles do not update defence skill display

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#143]
**Describe the bug**
When using the Longrange and Defensive (magic) attack styles the display for defence does not update to show the increases in experience.
**To Reproduce**
1. Equip a ranged or magic weapon.
2. Select the longrange or defensive attack style
3. Attack something and earn xp
4. The experience for the defence skill doesn't update

**Expected behavior**
Experience for the defence skill should update when using defensive attack styles

**Screenshots**

![image](https://user-images.githubusercontent.com/58208131/76789807-307b8700-6783-11ea-86a9-e8890525faa0.png)

Appears that the Longrange and Defensive styles require calls to updateSkillWindow(CONSTANTS.skill.Defence) to update the display in combat.js on lines 637 and 649

**Comment by Tpg9296** [comment]
This is happening with the Ranged skill in Android as well - started as using accurate, tried rapid to see the difference and now can't go back to accurate, or long distance for that matter. Stuck on rapid.

**Comment by MelvorIdle** [comment]
Fixed in the coming update.
