### ISSUE TITLE
Infernal Stronghold Typo

### ISSUE THREAD

**Issue by VelvetShadow** [MelvorIdle/melvoridle.github.io#1430]
**Describe the bug**
On wave 15 of the Infernal Stronghold, there is a typo in Incendius' Special Attacks description. Under "Burning Trail", it says "Charge at the you".

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser**
Using Steam version

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
No scripts being used

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
