### ISSUE TITLE
Some fish aren't cookable

### ISSUE THREAD

**Issue by fasontales** [MelvorIdle/melvoridle.github.io#1433]
There are a bunch of fish that aren't cookable, such as the barbarian fish. I'm labeling this as a bug and not a suggestion because clearly these fish should be cookable and be usable as food. 

Yes I have 137k leaping broadfish banked 
Yes I created an account just to post this
Yes I'm mad

**Comment by Pwusa** [comment]
:(

**Comment by fasontales** [comment]
@coolrox95 can you please explain to me how this is 'not a bug' ?
