### ISSUE TITLE
All videos in FIREFOX are stuttering when running the game

### ISSUE THREAD

**Issue by alextoma-QE** [MelvorIdle/melvoridle.github.io#1434]
**Describe the bug**
All videos in browser are stuttering when running the game. Doesn't seem like an internet issue since it's loading properly, the video itself is stuttering.

**To Reproduce**
1. Open Melvor Idle Steam version
2. Have a task ongoing in game
3. Go to any streaming/video website (Youtube)
4. Watch the video

**Expected behavior**
All videos in FIREFOX are stuttering when running the game

**Browser**
Firefox 92.0.1

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
I believe this has been fixed. Please open a new bug report if it has not
