### ISSUE TITLE
Offline progress error

### ISSUE THREAD

**Issue by MtKolvir** [MelvorIdle/melvoridle.github.io#1435]
Error message on startup.  No offline progress occurred overnight.  See screenshot

**To Reproduce**
Seems to be a one time thing.  I'm getting offline progress again

**Expected behavior**
I went to bed cooking cherry cupcakes.

**Screenshots**
![Screenshot_20211006-055654_2b8eea6112cc876d6c442b74a1d27a81](https://user-images.githubusercontent.com/92034509/136209163-b35d2f60-0d58-4f16-b821-763d3cb4bdcc.jpg)

**Browser**
Playing on mobile app.  Android.  OnePlus 9 phone

**Console output**
Not sure how to capture this on a phone

**Are you using any scripts?**
No scripts

**Comment by MelvorIdle** [comment]
I believe this has been fixed. Please open a new bug report if it has not
