### ISSUE TITLE
No steel bar recipe option for Salamander scrolls

### ISSUE THREAD

**Issue by iiNvict** [MelvorIdle/melvoridle.github.io#1438]
**Describe the bug**

**To Reproduce**
1. Go to Crate Summing Tablets/Scrolls
2. Click on Salamander
3. Scroll down to Recipes
4. See error that there is no option to use steel bars

**Expected behavior**
As above

**Screenshots**

**Browser**
Please tell us what browser you are using and what version.
Google Chrome Version 94.0.4606.71 (Official Build) (64-bit)

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.
Negative

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
