### ISSUE TITLE
Cloud vs Local Saves

### ISSUE THREAD

**Issue by sbabudro** [MelvorIdle/melvoridle.github.io#1443]
I expect that the Cloud/Local system currently in place is not intended to be permanent.

It's a bit weird when you first use it, especially if you go back and forth between Mobile and PC.

To me it seems pretty straightforward that the save which should show up first should be the most recent. I should not have to change tabs to Cloud Saves in order to see my most recent save. Cloud should be the first I see if it's the most recent.

There is definitely good reason to revert to an older save but this should be done on purpose with extra clicks, not by default. I can't tell you how many times now I've clicked to change character, instantly clicked on the next character in my list, then realized I am on an old save and quickly log back out and log in on my Cloud before losing work to autosave. (I have since disabled autosave on all my characters)

In my opinion instead of Cloud/Local, it should be Current Save/Backups. If possible it would be great to set a default location on the hard disk where backups are stored and then if you click to load a backup it will show you the backups you have made with timestamps, total level, etc.

The distinction between Cloud and Local is rarely if ever a benefit and is almost always just the potential to make a mistake and overwrite your latest save with an older one.

I don't really see a good reason why I should have the option not to sync to cloud. If cloud sync was simply the default and the default load was for the cloud save then the only time you'd run into problems would be if you did a bunch of offline progress on mobile, didn't save/reconnect to the internet, and then tried to play on PC. But this already would be a problem even the way things are now, it wouldn't make it any worse.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
