### ISSUE TITLE
Mole Pig Cooking Synergy consuming 4-5 familiar charges per cooking action

### ISSUE THREAD

**Issue by SirFermi** [MelvorIdle/melvoridle.github.io#1445]
**Describe the bug**
Each cooking action on a 1x fish (seahorse) consuming 4-5 pig and 3-4 mole charges per cook action

**To Reproduce**
1. equip pig/mole or mole/pig in familiar slots
2. go to cooking
3. start active cooking of fish
4. no passive cooking
5. each cooking action consumes 4-5 pig and 3-4 mole charges

**Expected behavior**
2 pig charges, 1 mole charge used per action

**Screenshots**
n/a

**Browser**
Chrome Version 94.0.4606.61 (Official Build) (64-bit)

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
No

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
