### ISSUE TITLE
Clears for the Ancient Magiks of the Water Dungeon is Negative, cannot unlock

### ISSUE THREAD

**Issue by Merphini** [MelvorIdle/melvoridle.github.io#1446]
**Describe the bug**
I am trying to unlock the Ancient Magik for completing the Water Dungeon 100 times. I didn't even know I went over 100, and now I have completed it 152 times and it says it requires "-52 Water God Dungeon" clear to unlock.

**To Reproduce**
I'm not even sure how to reproduce the error. I have even tried the fix save button from the options menu.

**Expected behavior**
What is supposed to happen, is that after reaching 100 Water God Dungeon clears, the respective Ancient Magik should be unlocked for me to use. Instead, the amount of clears has gone into the negatives, and it seems I will no longer be able to unlock it now.

**Screenshots**
![melvorbug](https://user-images.githubusercontent.com/81184721/136581873-d9966096-3efc-4136-9a4a-3cce8ec8f36f.png)

**Browser**
I am using the steam version of the game.

**Are you using any scripts?**
Not using scripts. Vanilla game.

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
