### ISSUE TITLE
Spellbook shows red 'Magic weapon required' if I equip a staff

### ISSUE THREAD

**Issue by sopindm** [MelvorIdle/melvoridle.github.io#1447]
**Describe the bug**

**To Reproduce**
1. Equip a staff (I used Staff of Earth)
2. Go to Spellbook in Combat page
3. You'll see red 'Magic weapon required' text

**Expected behavior**
I would expect to see that text if I don't have a magic weapon

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
