### ISSUE TITLE
Cant access High Lands without refreshing

### ISSUE THREAD

**Issue by Cadbury847** [MelvorIdle/melvoridle.github.io#145]
**The bug and the steps taken**
Even with all conditions to enter the High Lands met, I couldn't enter without refreshing the game so that it recognised that the ring was worn.

Was doing combat, fled from current target (Green goo monsters, on a slayer task). Hit 60 slayer then went to the bank tab and equipped the Magical Ring. Went back to combat, went to select the high lands but access was denied as it thought I hadn't got the ring worn. See first screenshot below.
Refreshed the page, loaded local save and it was fine, looked like the second screenshot and all was working as expected.

**Expected behaviour**
When doing the above you'd expect to be allowed access to the High Lands (as in the second screenshot) as all conditions were met

**Screenshots**
First:
![image](https://user-images.githubusercontent.com/56396053/76896681-3740f180-688a-11ea-8f2c-099f7dc11c39.png)
Second: 
![image](https://user-images.githubusercontent.com/56396053/76897023-dbc33380-688a-11ea-8dd0-33a38532766a.png)

**Browser**
Most recent version of Google Chrome for Windows as of 17/03/2020

**Console output**
Refreshed before reported, no console output of the event.

**Comment by MelvorIdle** [comment]
Fixed in the next update
