### ISSUE TITLE
[Crash] Error loading offline progress while cooking

### ISSUE THREAD

**Issue by MasterEric** [MelvorIdle/melvoridle.github.io#1451]
![Screenshot_20211010-163821](https://user-images.githubusercontent.com/4635334/136713516-d19b258e-7195-4205-b405-b790565f9a96.png)

**Comment by MelvorIdle** [comment]
I believe this has been fixed. Please open a new bug report if it has not

**Comment by MasterEric** [comment]
Probably is, I haven't seen the issue since. 👍
