### ISSUE TITLE
Add amount of essence used to offline runecrafting

### ISSUE THREAD

**Issue by mattrunyon** [MelvorIdle/melvoridle.github.io#1452]
### Why are you suggesting this?

I want to know how much essence I use while offline runecrafting.

### How does your suggestion benefit the game?

Others can see how much essence they use while offline runecrafting.

### Suggestion

Fairly simple (and not sure if this is a bug or not), but adding the amount of essence used when returning from offline runecrafting. Currently, you are notified of how many potion charges are used, but not how much essence is used while you were offline. Screenshot below showing potion charges used, but no essence

![image](https://user-images.githubusercontent.com/8619789/136720619-4f29ad9f-0323-4985-a73b-85f7907f7d85.png)

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
