### ISSUE TITLE
Game crashing/freezing

### ISSUE THREAD

**Issue by AckeMclovin** [MelvorIdle/melvoridle.github.io#1453]
**Describe the bug**
If I have cloud save enabled my whole computer seizes up in 30minutes.
If I play offline the game seizes after a couple of hours.
Moments before it seizes up completly Melvor idle starts lagging a lot.
Combat is fine.

**To Reproduce**
1. Start the game via Steam.
2. Start skilling.

**Expected behavior**
Not seize?

**Screenshots**
-

**Browser**
-

**Console output**
Unfortunately not possible.

**Are you using any scripts?**
-

**Comment by MelvorIdle** [comment]
I believe this has been fixed. Please open a new bug report if it has not
