### ISSUE TITLE
Notification appearing on top of the game

### ISSUE THREAD

**Issue by Rrrakot** [MelvorIdle/melvoridle.github.io#1458]
**Describe the bug**
Notification started appearing on top of the screen on Steam version. Whenever they appear, they "push" everything down resulting in screen bouncing.
Two things slightly help - scrolling down to avoid seeing top row (no more bouncing untill I scroll up again) and turning off Item and GP notifications (but only because there are fewer notifications).
I tested on Chrome and Android versions - they both work fine.
I reset PC, reinstalled the game - but it didn't help.
This bug appeared ~2h ago, when I checked the game 6h it worked fine.

**To Reproduce**
Open it on my PC?

**Expected behavior**
Notification appearing at the bottom and no screen bouncing.

**Screenshots**
https://imgur.com/a/vTFsFfk

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
I believe this has been fixed. Please open a new bug report if it has not
