### ISSUE TITLE
Cant Load game whatsoever

### ISSUE THREAD

**Issue by K4apro** [MelvorIdle/melvoridle.github.io#1459]
**Describe the bug**
Playing on Steam. When i start the game i am stuck on the Melvor Idle Loading page with the logo in the middle of the screen with the spinning wheel around it. I have tried uninstalling and reinstalling the game and rebooting my PC on multiple occasions. This problem has been going on for almost a week. Im not using any scripts or external software.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser**
Please tell us what browser you are using and what version.

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

**Comment by MelvorIdle** [comment]
I believe this has been fixed. Please open a new bug report if it has not
