### ISSUE TITLE
Controlled Heat potions with auto-reuse enabled wastes potions and charges when no regular fires are being lit

### ISSUE THREAD

**Issue by gendelbendel** [MelvorIdle/melvoridle.github.io#146]
**Description**
When using a controlled heat potion (to auto create bonfires) to level firemaking, once the bonfire is lit, it will continue auto relighting it and consuming potion charges and potions even if the user is not actively burning fires. 

**To Reproduce**
1. Create a few Controlled Heat potions.
2. Obtain 10 of your choosing that you have a firemaking level to burn.
3. Ensure that "Auto-reuse potion when it depletes" in the Settings menu is enabled.
4. Go to the Firemaking tab and select the Controlled Heat potion to be enabled.
5. Light your first bonfire.
6. Once bonfire completes, observe that the bonfire relights itself and consumes a charge.

**Expected behavior**
Once the bonfire completes, if the user is not actively burning logs, the bonfire should not relight itself. The bonfire should only relight once the user begins lighting logs or manually clicks the Light Bonfire button (consuming 10 logs in the process and not a potion charge).

**Screenshots**
N/A

**Browser**
Chrome 80, but N/A

**Console output**
N/A; bug in behavior, not error in code.

**Comment by MelvorIdle** [comment]
Fixed for next update. Potions will only use if you are actually burning a log at the time.
