### ISSUE TITLE
Slayer 'Jump to Enemy' unnecessarily clears Loot to collect

### ISSUE THREAD

**Issue by SustainableBlueDuck** [MelvorIdle/melvoridle.github.io#1460]
**Please be as detailed as possible when making suggestions.**

When performing slayer you are able to press a button "Jump to Enemy". When you do this, your Loot in the "Loot to Collect" tab will dissapear.

The issue is that also when you're already fighting the same monster as where you can jump to, your "Loot to Collect" will be cleared. I suggest to not clear the loot tab when not switching monsters, since assuming the Loot to Collect suggests loot that is 'on the ground' to be picked up.

_note: On mobile this might be overseen more easily compared to other platforms with larger screen real estate._

**Why are you suggesting this?**

It is ilogical that the loot dissapears if you don't move location/monster.

**How does your suggestion benefit the game?**

Potentially higher satisfaction doing slayer for early players.

**It is suggested that you provide (mockup) art to ilustrate things where relevant in order to make your suggestion more clear.**

---

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
