### ISSUE TITLE
Christmas Cracker ‘Find A Friend’

### ISSUE THREAD

**Issue by sonoflucien** [MelvorIdle/melvoridle.github.io#1461]
**Describe the bug**
‘Find a friend’ option for Christmas cracker displays notification for ‘Merchant’s Permit’

**To Reproduce**
1. Go to cracker and select
2. Click on ‘Find A Friend’
3. ???
4. See  merchant’s permit

**Expected behavior**
I thought it gave me party hat

**Screenshots**

**Browser**
Newest chrome and iOS 15.1

**Console output**

**Are you using any scripts?**
Vanilla

**Comment by coolrox95** [comment]
Duplicate of #595
