### ISSUE TITLE
Game failed to load

### ISSUE THREAD

**Issue by legalmedicine** [MelvorIdle/melvoridle.github.io#1462]
**Describe the bug**

the game failed to load

**To Reproduce**
I don’t know how or what caused it

**Screenshots**

![4F0D216D-0090-4DFC-8AD8-10F02A61D264](https://user-images.githubusercontent.com/56705254/137220336-09d0048b-f5e8-40aa-bf7c-b86cad8fd170.jpeg)

![IMG_6712](https://user-images.githubusercontent.com/56705254/137220388-0369a0e2-896d-49f2-be14-33821c941971.jpg)

I hope these work

**Browser**
Please tell us what browser you are using and what version.

I am using the  most recent version of Melvor on the latest IOS update

specifically version Alpha V0.22.1 (?1185) 

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

**Comment by MelvorIdle** [comment]
I believe this has been fixed. Please open a new bug report if it has not
