### ISSUE TITLE
Lost crown of rhaelyx

### ISSUE THREAD

**Issue by Jammey123** [MelvorIdle/melvoridle.github.io#1464]
**Describe the bug**

I died and lost the crown of rhaelyx during combat. I now believe the parts are unable to obtain as it believes I've already had them. I am still earning mysterious stones despite not owning the crown which backs up my theory

**To Reproduce**
1. Go to '.
Die and loose crown of rhaelyx,
Any skill to earn a stone and will still be earning despite not owning it anymore.

**Expected behavior**
Expect to earn mysterious stones without owning the crown and the parts to no longer be obtainable.

**Screenshots**

**Browser**
Please tell us what browser you are using and what version. Mobile app 23rd Dec 2020 latest update

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.
No scripts

**Comment by MelvorIdle** [comment]
There is no limit to the amount of Rhaelyx pieces you can obtain.
