### ISSUE TITLE
Witch tablet used when doing alt magic

### ISSUE THREAD

**Issue by Boomoo92** [MelvorIdle/melvoridle.github.io#1466]
When doing anything in alt magic, if the witch tablets are equipped, they will be used while doing alt magic even though they do not provide anything to alt magic by themselves.

I don't know if this is just a bug for me but it should be very easy to replicate. I have only noticed it on android but it very well could be on the pc version as well.

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
