### ISSUE TITLE
No hp regen while offline (on mobile)

### ISSUE THREAD

**Issue by kharybdys** [MelvorIdle/melvoridle.github.io#1469]
**Describe the bug**
I'm not seeing my standard or adventure character regenerate hitpoints while being offline, skills do progress (option pause action on skills on).

**To Reproduce**
1. Get your character damaged.
2. Go offline (both killing app or putting it on background work). Ofcourse do not keep offline combat or thieving running.
3. Return after a serious amount of time and see no change in hps.

**Expected behavior**
Return with a fully healed character after a night's sleep, aside from the 18K Mithril Ore mined, eg.

**Screenshots**
See hitpoints and time on the two screenshots.

**Browser**
iPad Mini 4.

**Console output**
Mobile, so can't, unfortunately.

**Are you using any scripts?**
Mobile, so no.

Let me know if you want me to try a scenario

**Comment by kharybdys** [comment]
![image](https://user-images.githubusercontent.com/3205437/137531680-b357265c-582b-43a3-92a9-df2df2b6a8de.png)

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.1.
