### ISSUE TITLE
Mastery recorded incorrectly 

### ISSUE THREAD

**Issue by Cartridge512** [MelvorIdle/melvoridle.github.io#1470]
**Describe the bug**
Cooking displaying the incorrect amount of mastery in the mastery tab. 

**To Reproduce**
 - Open the mastery tab
 - See that cooking is missing 4 mastery levels somewhere
 - Click "Progress"
 - See that there is nothing that still needs mastery 

**Expected behavior**
I have completed all 31 recipes to 99 mastery, 31*99 = 3069, so somewhere 4 levels that have not counted should be counted. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6137514/137575077-06566d94-906d-41b0-8dc7-841e66d48d59.png)
![image](https://user-images.githubusercontent.com/6137514/137575085-32cabd21-933c-48dd-9d8d-fdb37a9ccb92.png)

**Browser**
Chrome 79

**Are you using any scripts?**
Melvor Action Queue

**Comment by Cartridge512** [comment]
Logged in again this morning, the correct mastery had been applied. Bug seems to then be with how the tracker is updated rather than if the mastery actually counted

**Comment by MelvorIdle** [comment]
I believe this has been fixed. Please open a new bug report if it has not
