### ISSUE TITLE
Offline cooking not functioning

### ISSUE THREAD

**Issue by Nick-Colclasure** [MelvorIdle/melvoridle.github.io#1471]
**Describe the bug**
Cooking offline not functioning, possibly just for specific items.

**To Reproduce**
Set lobsters to cook, go offline, come back to a notification that I've been cooking for x amount of time but have received 0 experience

**Expected behavior**
I should have received experience and the lobsters should have been cooked

**Screenshots**
![image](https://user-images.githubusercontent.com/796898/137577084-2f231d23-5230-480e-9760-0269297f9fa8.png)
![image](https://user-images.githubusercontent.com/796898/137577106-954efb0d-b6ff-41d3-bdd5-dee1e9a98b63.png)

**Browser**
I'm using the steam version.

**Console output**
F12 does not seem to work in the steam version...
Edit: grabbed the output from the browser through a cloud save:
`Failed to load resource: the server responded with a status of 404 ()
​ jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
c.amazon-adsystem.com/aax2/apstag.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
adthrive.min.js?threshold=0&deployment=ad-1257:pr1891:flex-02:2dab872:con&cb=1634367231822:3 AmazonBootstrap::load  Error: Failed to import script https://c.amazon-adsystem.com/aax2/apstag.js
    at HTMLScriptElement.<anonymous> (adthrive.min.js?threshold=0&deployment=ad-1257:pr1891:flex-02:2dab872:con&cb=1634367231822:3)
e.call @ adthrive.min.js?threshold=0&deployment=ad-1257:pr1891:flex-02:2dab872:con&cb=1634367231822:3
prebid.min.js:1 fun-hooks: referenced 'registerAdserver' but it was never created
(anonymous) @ prebid.min.js:1
prebid.min.js:1 fun-hooks: referenced 'adpod' but it was never created
(anonymous) @ prebid.min.js:1
securepubads.g.doubleclick.net/pagead/ppub_config?ippd=melvoridle.com:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
pubads_impl_2021101201.js:10 Error: s:0 rs:4
    at XMLHttpRequest.c.onerror (gpt.js:10)
X.T @ pubads_impl_2021101201.js:10
confiant-integrations.global.ssl.fastly.net/mOinGM9MTu5v-Lto835XLhlrSPY/gpt_and_prebid_v3l/config.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
adthrive.min.js?threshold=0&deployment=ad-1257:pr1891:flex-02:2dab872:con&cb=1634367231822:3 FloorsRubiconComponent::getRubiconFloorData  Error: Request failed
    at XMLHttpRequest.<anonymous> (adthrive.min.js?threshold=0&deployment=ad-1257:pr1891:flex-02:2dab872:con&cb=1634367231822:3)
e.call @ adthrive.min.js?threshold=0&deployment=ad-1257:pr1891:flex-02:2dab872:con&cb=1634367231822:3
adthrive.min.js?threshold=0&deployment=ad-1257:pr1891:flex-02:2dab872:con&cb=1634367231822:3 RubiconFloorsComponent::getRubiconFloorData  Error: Request failed
    at XMLHttpRequest.<anonymous> (adthrive.min.js?threshold=0&deployment=ad-1257:pr1891:flex-02:2dab872:con&cb=1634367231822:3)
e.call @ adthrive.min.js?threshold=0&deployment=ad-1257:pr1891:flex-02:2dab872:con&cb=1634367231822:3
ads.adthrive.com/api/v1/host/floors/melvoridle.com:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
prebid.adnxs.com/pbs/v1/cookie_sync:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
prebid.adnxs.com/pbs/v1/openrtb2/auction:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
mpbs.rubiconproject.com/cookie_sync:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
mpbs.rubiconproject.com/openrtb2/auction:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
tlx.3lift.com/header/auction?lib=prebid&v=4.43.2&referrer=https%3A%2F%2Fmelvoridle.com%2F&tmax=2200&us_privacy=1YNY:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
htlb.casalemedia.com/cygnus?s=404607&v=7.2&ac=j&sd=1&r=%7B%22id%22%3A%222778538fd2e2e6d%22%2C%22site%22%3A%7B%22ref%22%3A%22https%3A%2F%2Fwww.google.com%2F%22%2C%22page%22%3A%22https%3A%2F%2Fmelvoridle.com%2F%3F%23PD%3Anodesktop%23Source%3Awww.google.com%23Browser%3AChrome%23Topic%3ATech%23MCMP%3A%23Sens%3Aalc%23Sens%3Aconl%23Sens%3Adat%23Sens%3Adrg%23Sens%3Agamc%23Sens%3Agamv%23Sens%3Atob%23Sens%3Awtl%23vp%3A0%23AFOI_2020%3ATrue%23TYS_062019%3ATrue%22%7D%2C%22ext%22%3A%7B%22source%22%3A%22prebid%22%2C%22ixdiag%22%3A%7B%22mfu%22%3A0%2C%22bu%22%3A1%2C%22iu%22%3A0%2C%22nu%22%3A0%2C%22ou%22%3A0%2C%22allu%22%3A1%2C%22ren%22%3Afalse%2C%22version%22%3A%224.43.2%22%2C%22userIds%22%3A%5B%22id5id%22%2C%22criteoId%22%5D%2C%22dms%22%3Atrue%2C%22msd%22%3A0%2C%22msi%22%3A0%7D%7D%2C%22source%22%3A%7B%22ext%22%3A%7B%22schain%22%3A%7B%22ver%22%3A%221.0%22%2C%22complete%22%3A1%2C%22nodes%22%3A%5B%7B%22asi%22%3A%22cafemedia.com%22%2C%22sid%22%3A%225ea18421f87fa26d37d8fb62%22%2C%22hp%22%3A1%7D%5D%7D%7D%7D%2C%22user%22%3A%7B%22eids%22%3A%5B%7B%22source%22%3A%22liveramp.com%22%2C%22uids%22%3A%5B%7B%22id%22%3A%22AqYyAL-k16nZ4ROUPDbRVqITLBuaIDVE-utRATz5uyWCCWdcJ-C3Imn-U9k222x9_53ncFNDMtL76Lp6uBXkgQPV18YaMqsOvCPBif736fcdgh7bv3FVx1cTsossZYhrv4ukeLaT31v2h2KCsQgmb53b6Q_AS2x-7rxk-zhE2vMyLyxujdHVPYrLE1UC%22%2C%22ext%22%3A%7B%22rtiPartner%22%3A%22idl%22%7D%7D%5D%7D%2C%7B%22source%22%3A%22adserver.org%22%2C%22uids%22%3A%5B%7B%22id%22%3A%2278a4e83a-db79-4bb7-bf68-0cc7f0598aca%22%2C%22ext%22%3A%7B%22rtiPartner%22%3A%22TDID%22%7D%7D%5D%7D%5D%7D%2C%22regs%22%3A%7B%22ext%22%3A%7B%22us_privacy%22%3A%221YNY%22%7D%7D%2C%22imp%22%3A%5B%7B%22id%22%3A%2228fbd39fae8d452%22%2C%22ext%22%3A%7B%22siteID%22%3A%22404607%22%2C%22sid%22%3A%2215_4%22%2C%22dfp_ad_unit_code%22%3A%22%2F18190176%2FAdThrive_Header_1%2F5ea18421f87fa26d37d8fb62%22%7D%2C%22banner%22%3A%7B%22w%22%3A320%2C%22h%22%3A50%2C%22topframe%22%3A1%7D%7D%2C%7B%22id%22%3A%222911789325f1854%22%2C%22ext%22%3A%7B%22siteID%22%3A%22185774%22%2C%22sid%22%3A%2215_4%22%2C%22dfp_ad_unit_code%22%3A%22%2F18190176%2FAdThrive_Header_1%2F5ea18421f87fa26d37d8fb62%22%7D%2C%22banner%22%3A%7B%22w%22%3A320%2C%22h%22%3A50%2C%22topframe%22%3A1%7D%7D%2C%7B%22id%22%3A%22307f7bbd2ba189e%22%2C%22ext%22%3A%7B%22siteID%22%3A%22404607%22%2C%22sid%22%3A%2215_5%22%2C%22dfp_ad_unit_code%22%3A%22%2F18190176%2FAdThrive_Header_1%2F5ea18421f87fa26d37d8fb62%22%7D%2C%22banner%22%3A%7B%22w%22%3A320%2C%22h%22%3A100%2C%22topframe%22%3A1%7D%7D%2C%7B%22id%22%3A%22311fcbace3916be%22%2C%22ext%22%3A%7B%22siteID%22%3A%22185774%22%2C%22sid%22%3A%2215_5%22%2C%22dfp_ad_unit_code%22%3A%22%2F18190176%2FAdThrive_Header_1%2F5ea18421f87fa26d37d8fb62%22%7D%2C%22banner%22%3A%7B%22w%22%3A320%2C%22h%22%3A100%2C%22topframe%22%3A1%7D%7D%2C%7B%22id%22%3A%22321e6e40fdbcc2d%22%2C%22ext%22%3A%7B%22siteID%22%3A%22404607%22%2C%22sid%22%3A%2215_6%22%2C%22dfp_ad_unit_code%22%3A%22%2F18190176%2FAdThrive_Header_1%2F5ea18421f87fa26d37d8fb62%22%7D%2C%22banner%22%3A%7B%22w%22%3A300%2C%22h%22%3A50%2C%22topframe%22%3A1%7D%7D%2C%7B%22id%22%3A%22334f2b029d1ddca%22%2C%22ext%22%3A%7B%22siteID%22%3A%22185774%22%2C%22sid%22%3A%2215_6%22%2C%22dfp_ad_unit_code%22%3A%22%2F18190176%2FAdThrive_Header_1%2F5ea18421f87fa26d37d8fb62%22%7D%2C%22banner%22%3A%7B%22w%22%3A300%2C%22h%22%3A50%2C%22topframe%22%3A1%7D%7D%5D%7D:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
a.teads.tv/hb/bid-request:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ib.adnxs.com/ut/v3/prebid:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
fastlane.rubiconproject.com/a/api/fastlane.json?account_id=9262&site_id=180726&zone_id=881422&size_id=43&alt_size_ids=44%2C117&p_pos=atf&us_privacy=1YNY&rp_schain=1.0,1!cafemedia.com,5ea18421f87fa26d37d8fb62,1,,,&eid_criteo.com=u1vRO19aVG1wRSUyQjlLTjUzQmpjTXpIQ1Q1bERXJTJGbWVycHBPWCUyRlFpMUpKME5QY0NMZVclMkZIdTRBUExSbDBaR3Frd2xUUmdYWXRQalFyN0VNYnclMkJYcTh2V1phZjRvU0U0T3ZkVENKS3lrUFhTVnluTEhXRmtlWDJ1dXpBZnFFQTUwUkdSNlY%5E1&eid_id5-sync.com=ID5*1_VrDO5k2MxJF6Ni8gY9hjh10ZkE5AkLT8hSTML6DK0AAKI3iHvPajNywtHZbtXY%5E1%5E2&tpid_tdid=78a4e83a-db79-4bb7-bf68-0cc7f0598aca&eid_adserver.org=78a4e83a-db79-4bb7-bf68-0cc7f0598aca&x_liverampidl=AqYyAL-k16nZ4ROUPDbRVqITLBuaIDVE-utRATz5uyWCCWdcJ-C3Imn-U9k222x9_53ncFNDMtL76Lp6uBXkgQPV18YaMqsOvCPBif736fcdgh7bv3FVx1cTsossZYhrv4ukeLaT31v2h2KCsQgmb53b6Q_AS2x-7rxk-zhE2vMyLyxujdHVPYrLE1UC&rf=https%3A%2F%2Fmelvoridle.com%2F&tg_i.site_code=AFOI_2020%2CTYS_062019&tg_i.site_id=5ea18421f87fa26d37d8fb62&tg_i.sens=alc%2Cconl%2Cdat%2Cdrg%2Cgamc%2Cgamv%2Ctob%2Cwtl&tg_i.verticals=Tech&tg_i.pmp_elig=false&tg_i.refresh=false&tg_i.vp=0&tg_i.pos=atf&tg_i.dfp_ad_unit_code=18190176%2FAdThrive_Header_1%2F5ea18421f87fa26d37d8fb62&tg_i.pbadslot=18190176%2FAdThrive_Header_1%2F5ea18421f87fa26d37d8fb62&tk_flint=pbjs_lite_v4.43.2&x_source.tid=f10c25a2-9d33-44cb-87ba-88a4d42ece69&p_screen_res=2048x1152&rp_secure=1&rp_maxbids=1&slots=1&rand=0.5845827329915758:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
hbopenbid.pubmatic.com/translator?source=prebid-client:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
bidder.criteo.com/cdb?ptv=113&profileId=185&av=33&wv=4.43.2&bundle=1fhkKF9tY3VVM1FwVUlWczBJbnNIMUZ5ZFFjJTJCUzBhUXhCaVA3bHl5QSUyRlRCMWdSbFNWS1Mwb2oxWnRBMTNEVm9YTFBOTEZncUJiRnZQaHhvT3dtSCUyQnBndXIzZ1ZuOWZOdkYzVk5rMiUyRjhQdXFZeUNUR1poeGF5RzhvQnlNOHJoRkthOTR5RWZla3kwcW43Tm9yMVdCJTJGbVBPcElRJTNEJTNE&cb=99714821626:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cafemedia-d.openx.net/w/1.0/arj?ju=https%3A%2F%2Fmelvoridle.com%2F&ch=UTF-8&res=2048x1152x24&ifr=false&tz=420&tws=1240x714&be=1&bc=hb_pb_3.0.3&dddid=f10c25a2-9d33-44cb-87ba-88a4d42ece69&nocache=1634367232853&us_privacy=1YNY&criteoid=u1vRO19aVG1wRSUyQjlLTjUzQmpjTXpIQ1Q1bERXJTJGbWVycHBPWCUyRlFpMUpKME5QY0NMZVclMkZIdTRBUExSbDBaR3Frd2xUUmdYWXRQalFyN0VNYnclMkJYcTh2V1phZjRvU0U0T3ZkVENKS3lrUFhTVnluTEhXRmtlWDJ1dXpBZnFFQTUwUkdSNlY&id5id=ID5*1_VrDO5k2MxJF6Ni8gY9hjh10ZkE5AkLT8hSTML6DK0AAKI3iHvPajNywtHZbtXY&lre=AqYyAL-k16nZ4ROUPDbRVqITLBuaIDVE-utRATz5uyWCCWdcJ-C3Imn-U9k222x9_53ncFNDMtL76Lp6uBXkgQPV18YaMqsOvCPBif736fcdgh7bv3FVx1cTsossZYhrv4ukeLaT31v2h2KCsQgmb53b6Q_AS2x-7rxk-zhE2vMyLyxujdHVPYrLE1UC&ttduuid=78a4e83a-db79-4bb7-bf68-0cc7f0598aca&schain=1.0%2C1!cafemedia.com%2C5ea18421f87fa26d37d8fb62%2C1%2C%2C%2C&aus=320x50%2C300x50%2C320x100&divids=AdThrive_Header_1_desktop&aucs=%252F18190176%252FAdThrive_Header_1%252F5ea18421f87fa26d37d8fb62&auid=538699873&tps=c2Vucz1hbGMsY29ubCxkYXQsZHJnLGdhbWMsZ2Ftdix0b2Isd3RsJmJ1Y2tldD1mbGV4LTAyOmNvbiZoaV9hdT0%3D:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ib.adnxs.com/ut/v3/prebid:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
dmx.districtm.io/b/v1:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
htlb.casalemedia.com/cygnus?s=377190&v=7.2&ac=j&sd=1&r=%7B%22id%22%3A%2252bfc46566114c8%22%2C%22site%22%3A%7B%22ref%22%3A%22https%3A%2F%2Fwww.google.com%2F%22%2C%22page%22%3A%22https%3A%2F%2Fmelvoridle.com%2F%22%7D%2C%22ext%22%3A%7B%22source%22%3A%22prebid%22%2C%22ixdiag%22%3A%7B%22mfu%22%3A0%2C%22bu%22%3A1%2C%22iu%22%3A0%2C%22nu%22%3A0%2C%22ou%22%3A0%2C%22allu%22%3A1%2C%22ren%22%3Afalse%2C%22version%22%3A%224.43.2%22%2C%22userIds%22%3A%5B%22id5id%22%2C%22criteoId%22%5D%2C%22msd%22%3A1%2C%22msi%22%3A1%7D%7D%2C%22source%22%3A%7B%22ext%22%3A%7B%22schain%22%3A%7B%22ver%22%3A%221.0%22%2C%22complete%22%3A1%2C%22nodes%22%3A%5B%7B%22asi%22%3A%22cafemedia.com%22%2C%22sid%22%3A%225ea18421f87fa26d37d8fb62%22%2C%22hp%22%3A1%7D%5D%7D%7D%7D%2C%22user%22%3A%7B%22eids%22%3A%5B%7B%22source%22%3A%22liveramp.com%22%2C%22uids%22%3A%5B%7B%22id%22%3A%22AqYyAL-k16nZ4ROUPDbRVqITLBuaIDVE-utRATz5uyWCCWdcJ-C3Imn-U9k222x9_53ncFNDMtL76Lp6uBXkgQPV18YaMqsOvCPBif736fcdgh7bv3FVx1cTsossZYhrv4ukeLaT31v2h2KCsQgmb53b6Q_AS2x-7rxk-zhE2vMyLyxujdHVPYrLE1UC%22%2C%22ext%22%3A%7B%22rtiPartner%22%3A%22idl%22%7D%7D%5D%7D%2C%7B%22source%22%3A%22adserver.org%22%2C%22uids%22%3A%5B%7B%22id%22%3A%2278a4e83a-db79-4bb7-bf68-0cc7f0598aca%22%2C%22ext%22%3A%7B%22rtiPartner%22%3A%22TDID%22%7D%7D%5D%7D%5D%7D%2C%22regs%22%3A%7B%22ext%22%3A%7B%22us_privacy%22%3A%221YNY%22%7D%7D%2C%22imp%22%3A%5B%7B%22id%22%3A%22539c08d1255a03f%22%2C%22ext%22%3A%7B%22siteID%22%3A%22377190%22%2C%22dfp_ad_unit_code%22%3A%22%2F18190176%2FAdThrive_Header_1%2F5ea18421f87fa26d37d8fb62%22%2C%22sid%22%3A%22320x50%22%7D%2C%22banner%22%3A%7B%22w%22%3A320%2C%22h%22%3A50%2C%22topframe%22%3A1%7D%7D%2C%7B%22id%22%3A%22546daf389cc73a3%22%2C%22ext%22%3A%7B%22siteID%22%3A%22377190%22%2C%22dfp_ad_unit_code%22%3A%22%2F18190176%2FAdThrive_Header_1%2F5ea18421f87fa26d37d8fb62%22%2C%22sid%22%3A%22300x50%22%7D%2C%22banner%22%3A%7B%22w%22%3A300%2C%22h%22%3A50%2C%22topframe%22%3A1%7D%7D%2C%7B%22id%22%3A%22539c08d1255a03f%22%2C%22ext%22%3A%7B%22siteID%22%3A%22377190%22%2C%22dfp_ad_unit_code%22%3A%22%2F18190176%2FAdThrive_Header_1%2F5ea18421f87fa26d37d8fb62%22%2C%22sid%22%3A%22320x100%22%7D%2C%22banner%22%3A%7B%22w%22%3A320%2C%22h%22%3A100%2C%22topframe%22%3A1%7D%7D%5D%7D:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
adthrive.min.js?threshold=0&deployment=ad-1257:pr1891:flex-02:2dab872:con&cb=1634367231822:3 ConfiantComponent::init  Error: Failed to import script https://confiant-integrations.global.ssl.fastly.net/mOinGM9MTu5v-Lto835XLhlrSPY/gpt_and_prebid_v3l/config.js
    at HTMLScriptElement.<anonymous> (adthrive.min.js?threshold=0&deployment=ad-1257:pr1891:flex-02:2dab872:con&cb=1634367231822:3)
e.call @ adthrive.min.js?threshold=0&deployment=ad-1257:pr1891:flex-02:2dab872:con&cb=1634367231822:3
(index):1 Uncaught (in promise) Error: Failed to import script https://confiant-integrations.global.ssl.fastly.net/mOinGM9MTu5v-Lto835XLhlrSPY/gpt_and_prebid_v3l/config.js
    at HTMLScriptElement.<anonymous> (adthrive.min.js?threshold=0&deployment=ad-1257:pr1891:flex-02:2dab872:con&cb=1634367231822:3)
securepubads.g.doubleclick.net/gampad/ads?gdfp_req=1&pvsid=1474222836992069&correlator=598113852651873&output=ldjh&impl=fifs&eid=21065724%2C31062525%2C44748553%2C21067496%2C31062931&vrg=2021101201&ptt=17&us_privacy=1YNY&tfcd=0&sc=1&sfv=1-0-38&ecs=20211016&iu_parts=18190176%3A22054819528%2CAdThrive_Header_1%2C5ea18421f87fa26d37d8fb62&enc_prev_ius=%2F0%2F1%2F2&prev_iu_szs=320x50%7C320x50%7C300x50%7C320x100&fluid=height&fsbs=1&prev_scp=location%3DHeader%26sequence%3D1%26id%3DAdThrive_Header_1_desktop%26lazy%3Dfalse%26refresh%3D00%26nref%3D0%26hvp%3D80%26hb_adomain%3Dpeacocktv.com%26hb_format%3Dbanner%26hb_size%3D320x50%26hb_pb%3D2.35%26hb_adid%3D55a5e629429c298%26hb_bidder%3Dgrid&eri=5&cust_params=siteId%3D5ea18421f87fa26d37d8fb62%26siteName%3DMelvor%2520Idle%26verticals%3DTech%26abgroup%3Ddelload%253Aon%252Cdeftimer%253A3000%252Camzn%253Aon%252Camzn_hold_load%253Aon%252Cclsins_ss%253Aon%252Cebho%253Aoff%252Cloglevel%253Aoff%252Cidho%253ApubCommonId%252Clzhb%253Aon%252Clzcvp%253A1%252Clzbpvp%253A0.75%252Ctripleliftdr%253Aboth%252Cmagnitedr%253Aboth%252Cpbs2s_appnexus%253Aoff%252Cpbs2s_districtm%253Aoff%252Cpbs2s_grid%253Aoff%252Cpbs2s_gumgum%253Aoff%252Cpbs2s_sovrn%253Aon%252Cto_initial%253A2200%252Cvebho%253Aoff%252Cbnr_unruly%253Aoff%252Cbnr_districtm%253Aon%252Cbnr_gumgum%253Aon%252Cbnr_padsquad%253Aoff%252Cbnr_undertone%253Aon%252Cbnr_33across%253Aoff%252Ccbt%253A4s%252Cvast_to%253A10s%252Cproto%253Aallr%252Cpbm%253Aon%252CreqTo%253A10%252Cvadv%253Aon%252Cvmig1%253Aoff%252Camzn_hold_disp%253Aoff%252Crbflr%253Aon_min%252Clzflrcontent%253A30p%252Csessflrs%253A30p%252Cmxrpog%253A5%252Crmos1%253Aoff%252Csab%253Aoff%252Cjwb%253Aon%252Cvpred%253Aon%252Ctlvid%253Aoff%252Cpba%253Anone%252Cbmetrics%253Aon%252Cconfiant%253Aprod%252Clogcls%253Aoff%252Cats%253Aon%252Crebuildslot%253Aon%252Cupl%253Aoff%252Crmosnv1%253Aoff%26bucket%3Dflex-02%253Acon%26sens%3Dalc%252Cconl%252Cdat%252Cdrg%252Cgamc%252Cgamv%252Ctob%252Cwtl%26domain%3Dmelvoridle.com%26plugin%3Dadthrive-ads-1.1.2%26hi_au%3Dod%252Com%26vpwxvph%3D1240x714%26ri%3D6%26pvk%3D01FJ3Y1PNTJR7N3FBDTYSRS8RZ%26sess%3D01FJ3Y1PNVTFB8YWW5BZWFC632%26branch%3Dfb7a7c1%26deployment%3Dad-1257%253Apr1891%253Aflex-02%253A2dab872%253Acon%26hbho%3D33across%26vbho%3Dgridvid%252Cspotx%26gptv%3D2021101201%26s2s_apn%3D33across%252Cconversant%252Cdeepintent%26s2s_rub%3Dbrightroll%252Cpubm_ss%252Crubi_ss%252Csovrn%252Ctripl_ss%252Cyieldmo%26connection%3Dniet%253A4g%252Cdl%253A10%26ccpaOptOut%3D0%26flag%3Dadsmnche%253A20%252Cclson%253Afalse%252CclsBranch%253A%252CclsBucket%253A%252Cidp%253Auid1%252Cidp%253Aid5%252Cidp%253Aidl%26fpv%3D1%26site_code%3DAFOI_2020%252CTYS_062019%26marmalade%3Dtrue%26doc_ref%3Dwww.google.com&cookie_enabled=1&bc=31&abxe=1&dt=1634367233267&dlt=1634367231632&idt=1044&frm=20&biw=1223&bih=714&oid=2&adxs=-12245933&adys=-12245933&adks=3656546684&ucis=1&ifi=1&u_his=3&u_h=1152&u_w=2048&u_ah=1112&u_aw=2048&u_cd=24&u_sd=1.25&u_tz=-420&flash=0&url=https%3A%2F%2Fmelvoridle.com%2F&ref=https%3A%2F%2Fwww.google.com%2F&vis=1&dmc=8&scr_x=0&scr_y=0&psz=0x-1&msz=0x-1&ga_vid=422402041.1633309248&ga_sid=1634367233&ga_hid=1016280709&ga_fc=false&fws=128&ohw=0&btvi=-1&uach=WyJXaW5kb3dzIiwiMTAuMC4wIiwieDg2IiwiIiwiOTQuMC40NjA2LjgxIixbXSxudWxsLG51bGwsIjY0Il0.&tt_state=W3siaXNzdWVyT3JpZ2luIjoiaHR0cHM6Ly9hdHRlc3RhdGlvbi5hbmRyb2lkLmNvbSIsInN0YXRlIjo3fV0.&a3p=EvMBCgZjcml0ZW8S3AFqMFd2SkY5dFkzVlZNMUZ3VlVsV2N6Qkpibk5JTVVaNVpGRllaV1k1ZHpsb2JuUktabkZIYVhSeWJtNXRTRXcwWkZFeE9YUkxlWGhCTVhWVWVFdGllRlZTYVNVeVJtZG1UakZPY1VWRWREaHFjVXhPYnpOc1ltcG5URWhLV2xWb04zSndXSFo2Y1dSeVlqVlNRbE5uV2tsNVpWcDFURmRLV0RCVE9URkRSbEZwYlhrbE1rWmhaRGRNYW1GaldGRjNibVZxYmpVM1VYWjVVSFF5UmtkUkpUTkVKVE5FGOu5g7_IL0UAAAAA&nvt=1:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
(index):7288 crbug/1173575, non-JS module files deprecated.
(anonymous) @ (index):7288
static.criteo.net/images/pixel.gif?ch=2:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
12save.js?1184:65 Uncaught TypeError: Cannot read properties of undefined (reading 'top')
    at handleBankSidebarScroll (save.js?1184:65)
    at HTMLDocument.<anonymous> (save.js?1184:63)
    at HTMLDocument.dispatch (oneui.core.min.js:6)
    at HTMLDocument.m.handle (oneui.core.min.js:6)
combatManager.js?1184:1 Combat Manager Built...
raidManager.js?1184:1 Golbin Raid Manager Built...
cloud.js?1184:66 Connected to PlayFab successfully
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
cloud.js?1184:67 PlayFab Connected: Valectar
save.js?1184:57 set force reload to 0
combatManager.js?1184:1 Combat Manager Built...
raidManager.js?1184:1 Golbin Raid Manager Built...
save.js?1184:14 Loading Save Game...
save.js?1184:14 Save Game Loaded...
main.js?1184:5 Game Loaded
cloud.js?1184:66 Connected to PlayFab successfully
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
cloud.js?1184:67 PlayFab Connected: Valectar
style.css:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
cloud.js?1184:8 Synchronising with Cloud`

**Are you using any scripts?**
None

**Comment by SustainableBlueDuck** [comment]
Got the same issue with manta ray (on mobile). No experience gained and no cooked fish after offline time. But hmm. Odd just when testing with which fish it does work, Mantas also worked offline again. Seems hard to reproduce this bug, since I didn't change anything except other progress, selling and changing equipped summoning tablets

**Comment by teknogeek** [comment]
Same issue here on browser `Alpha V0.22.1 (?1217)`

1. Start active cooking Whales
2. Click to a different browser tab, then switch back
3. I get this message every time: ![image](https://user-images.githubusercontent.com/2267004/140776771-d0d55619-899e-439b-ba50-84c0df2ca066.png)

Happens across reloads, regardless of whether or not I:

- save while active cooking, then reload the page and load the save
- switch tabs/window focus

**Comment by teknogeek** [comment]
Update: I switched my active cook to Manta Ray, and it started working in the background. Then, I switched back to cooking Whales and it started working fine after that

**Comment by MelvorIdle** [comment]
I believe this has been fixed. Please open a new bug report if it has not
