### ISSUE TITLE
Hud bugging

### ISSUE THREAD

**Issue by PERGAMIN** [MelvorIdle/melvoridle.github.io#1472]
1.Go to steam client
2.Full screen (1920x1080(
3.Fletching
4.click on Arrow shhafts
Now the hud is bugging 
I have this issue on my main monitor thats 144 hz on other one thats 60 hz it doesnt bug
[https://www.youtube.com/watch?v=FV_N8QxoaeQ](url)

**Comment by MelvorIdle** [comment]
I believe this has been fixed. Please open a new bug report if it has not
