### ISSUE TITLE
New items that were sorted previously appear in old sorted tab, not default.

### ISSUE THREAD

**Issue by Arccazz** [MelvorIdle/melvoridle.github.io#1475]
**Describe the bug**
Item in bank that was moved to another tab, sold/used completely and gained again - pops up in the tab it was previosuly moved to, not the default tab.

**To Reproduce**
Steps to reproduce the behavior: (note - same behavior with drag&drop sorting on chrome)
1. Have some existing bones in your bank.
2. Enable `Move Items to new Tab` option.
3. Move bones to any other tab other than default (for example 9),
4. Bury all of the bones, so none are left.
5. Kill any mob that drops standard bones.
6. Check bank.

**Expected behavior**
Bones should appear in default tab (0)

**Actual behavior**
Bones appeared in tab they were previously moved to (9)

**Browser**
Originally Mobile (Android), same bug can be seen on Chrome (v94.0.4606.81)

**Console output**
`
cloud.js?1186:66 Connected to PlayFab successfully
cloud.js?1186:67 PlayFab Connected: Arcca
save.js?1186:10 Removed old local storage keys.
save.js?1186:58 set force reload to 0
combatManager.js?1186:1 Combat Manager Built...
raidManager.js?1186:1 Golbin Raid Manager Built...
save.js?1186:10 Removed old local storage keys.
save.js?1186:14 Loading Save Game...
save.js?1186:14 Save Game Loaded...
main.js?1186:5 Game Loaded
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloud.js?1186:8 Synchronising with Cloud
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
cloud.js?1186:66 Connected to PlayFab successfully
cloud.js?1186:67 PlayFab Connected: Arcca
style.css:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

**Are you using any scripts?**
None

**Comment by Arccazz** [comment]
Just to be sure, I'm still not 100% sure if this is intended (then this would rather be a suggestion) or a bug. On Discord it was suggested that it sounds like a bug, hence the report.

**Comment by MelvorIdle** [comment]
I believe this has been fixed. Please open a new bug report if it has not.
