### ISSUE TITLE
Increase Allowable Characters Even If A Paid Option. Because of Web Version Removal

### ISSUE THREAD

**Issue by EngineeringDesing** [MelvorIdle/melvoridle.github.io#1476]
Hi,

TL;DR
With the switch to premium I will lose my 5 web characters, please don’t let that happen. 

I’ve been playing 15 characters (5 on Web, 5 on Mobile, and 5 on Steam all local saves) and am happy to pay for premium on both mobile and steam, but with the web version simply referring you to steam, there won’t be a home for my 5 web characters. 

Is it possible to increase the character cap to greater than 5? 

This could be built in with premium or an additional in game purchase, but if there isn’t something like this I’ll have to abandon 1/3 rd of my progress.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
