### ISSUE TITLE
Using different tab in Google Chrome can get you killed

### ISSUE THREAD

**Issue by Shine1331** [MelvorIdle/melvoridle.github.io#1477]
**Describe the bug**
I've now twice died to using a different tab in Google Chrome while doing combat in MI in a not currently active tab.
When I tabbed back in got a bunch of Summoning Marks, and I also died to something which I can not possibly die to normally, with plenty of food available, aswell.

**Expected behavior**
I should come back to a bunch of dungeon clears (in this case, i did Inferno Cave to upgrade my Ancient Claw).

**Browser**
Google Chrome most recent version

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
This is most likely due to updates and changes to combat based on patch notes. If issue persists, please open a new report.
