### ISSUE TITLE
Offline Cooking Crashing with error: cannot read properties of undefined

### ISSUE THREAD

**Issue by SustainableBlueDuck** [MelvorIdle/melvoridle.github.io#1478]
**Describe the bug**

I had set active cooking and when I unlocked my phone this showed

**Screenshots**

![Screenshot_2021-10-18-08-03-56-18_9737de6f3e36012ce6703231c8d3c3a2](https://user-images.githubusercontent.com/38500797/137677460-a4e6527f-ec4e-40a8-b4e9-c7e3a8d28f7e.jpg)

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

No

**Comment by MelvorIdle** [comment]
I believe this has been fixed. Please open a new bug report if it has not
