### ISSUE TITLE
Summoning pre-filter

### ISSUE THREAD

**Issue by NototoHoshi** [MelvorIdle/melvoridle.github.io#1480]
I love how you can equip capes and gloves and other related items from the bottom right menu in each skill section. It saves so much time just one click there instead of having to go to the bank and search for the item you want to equip each time.

One improvement I would make however, is that when you click the "wolf head" summoning icon, when it brings up the summoning synergy window, the filter that is being used is always the last remembered filter. In my opinion it would be much better if the filter was automatically set for whatever type of summoning familiar corresponds with that skill. So if you open up the window in fishing, it will be filtered to all octopus combinations, salamander in smithing, monkey in crafting etc.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
