### ISSUE TITLE
Wc level from 92 to 70 all mastery still showable from magic trees, redwoods 

### ISSUE THREAD

**Issue by kzanadylan** [MelvorIdle/melvoridle.github.io#1481]
Hey all,

i logged in on steam on the game loaded up my cloud save and my woodcutting went from 92 to 70 but the xp remains the same, also the mastery of magic trees etc is still visible but i can't shop them anymore since the level is 70

Also the mastery of normal trees is -10m xp and on level 1 

![image](https://user-images.githubusercontent.com/92761578/137814628-750f4ded-7234-4b2f-be2c-8a2585efbad6.png)

![image](https://user-images.githubusercontent.com/92761578/137814536-11bfb0d0-bb96-41b8-8450-a5f85c794052.png)

**Comment by coolrox95** [comment]
This issue was hotfixed.
