### ISSUE TITLE
24 hour limit

### ISSUE THREAD

**Issue by gitgurra** [MelvorIdle/melvoridle.github.io#1486]
**Why are you suggesting this?**

Twelve hours limit makes it so to be able to be efficient at leveling you have to sign in late before going to sleep and/or early at work. As someone who just have my login on my work computer to pass some time during meetings it is quite annoying when trying to max out some abilities that are quite slow to max eventually.

**How does your suggestion benefit the game?**

Makes it more fun and less of a stress to keep up while still being active.

**Comment by MelvorIdle** [comment]
The offline cap is now increased to 18 hours
