### ISSUE TITLE
Cooking gloves increase success chance by 20 and not 10

### ISSUE THREAD

**Issue by Sandstroem** [MelvorIdle/melvoridle.github.io#1487]
**Describe the bug**
Equipping the cooking gloves increase the chance for successful cook by 20 and not 10.

**To Reproduce**
1. Equip cooking gloves either manually via bank or hotbar

**Expected behavior**
Success chance should be increased by 10

![cookinggloves](https://user-images.githubusercontent.com/15617095/138239090-2dd1e580-3077-45e2-b63f-3f7adcb3999a.PNG)

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
