### ISSUE TITLE
Bank Issue

### ISSUE THREAD

**Issue by KaynarAlice** [MelvorIdle/melvoridle.github.io#1488]
**Describe the bug**

Only able to move items in the bank within the first 4 column making reorganising your bank rather difficult.
When trying to move an item outside of the first 4 columns, the item flicks back to its original position in the back.

Using the Melvor Idle Steam version.

**To Reproduce**

o.o

Uhh.... Go to bank, move stuff outside of the first 4 columns? 

I don't really know how much more information I need to give outside of that haha.

**Expected behavior**

To be able to move items outside of the first 4 columns

**Screenshots**

Little hard to take a screen shot of an action unfortunately, I'm in your public discord server if you wish to contact me to show you exactly what it's doing.

Kaynar~ 

**Browser**
Please tell us what browser you are using and what version.

No browser, just Steam version.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

No.

**Comment by MelvorIdle** [comment]
Unfortunately this is a limitation of drag & Drop + mobile touch events. I'll continue to make the bank more user friendly over each update
