### ISSUE TITLE
Ignore bank full separately offline

### ISSUE THREAD

**Issue by sbabudro** [MelvorIdle/melvoridle.github.io#1489]
There's no worse feeling than coming back after 12 hours to see a full bank and nothing being done.

Except, maybe, watching yourself not collect a signet half because you merrily kept going with a full bank.

If you're offline, there's not a lot you can do.

It's preferable in my opinion, unless the signet is dropped with pseudorandom distribution, that you'd keep going when offline but stop for full bank when online. Having to change the setting back and forth constantly seems like a massive pain so I thought I'd come suggest this.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
