### ISSUE TITLE
Plants with 2 seeds aren't shown with seed pouch 

### ISSUE THREAD

**Issue by yogidrink** [MelvorIdle/melvoridle.github.io#1490]
It takes 2 seeds when the seed pouch is equipped. But the planting list doesn't show plants with less than 3 seeds in the inventory. So you can't plant 2 seeds even though with the seed pouch it should be allowed.

**To Reproduce**
1. Have 2 seeds of a plant (Carrots for example)
2. Have a seed pouch equipped
3. Go to Farming
4. Click on a Allotment to plant the plant
5. See error

**Expected behavior**
Being able to plant plants with only 2 seeds in the bank, but with the seed pouch equipped

**Browser**
Google chrome Version 94.0.4606.81

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
