### ISSUE TITLE
Passwords are capped to 64 characters when registering, but not when logging in

### ISSUE THREAD

**Issue by EliasHolzmann** [MelvorIdle/melvoridle.github.io#1491]
**Describe the bug**
Passwords are capped to 64 characters when registering, but not when logging in. This means trying to register with (for example) a password consisting of 100 times the letter "A" creates an account with a password consisting of 64 times the letter "A". Trying to login to that account with a password consisting of 100 times the letter "A" does not work. As the account creator does not know that the password was truncated, the account is unusable (well, at least until the password is reset).

**To Reproduce**
1. Select a password that is at least 65 characters long.
2. Register an account with that password.
3. Try to login with that password.

**Expected behavior**
Logging in should be successful.

**Actual behavior**
Logging in is not successful.

**Browser**
Firefox 93.0 on Arch Linux

**Console output**
Not relevant here.

**Are you using any scripts?**
No scripts.

----

From a technical viewpoint: The problem is that there is a `maxlength` attribute on the password input fields on the [Register](https://melvoridle.com/cloud/register.php) page:

```html
<input type="password" class="form-control form-control-lg form-control-alt" id="signup-password" name="signup-password" placeholder="Password" maxlength="64">
<!-- ... -->
<input type="password" class="form-control form-control-lg form-control-alt" id="signup-password-confirm" name="signup-password-confirm" placeholder="Confirm Password" maxlength="64">
```

But there is none on the [Login](https://melvoridle.com/cloud/login.php) page:
```html
<input type="password" class="form-control form-control-alt form-control-lg" id="login-password" name="login-password" placeholder="Password" value="">
```

Either both pages should have `maxlength="64"` for the password input fields, or both pages should not have that attribute.

**Comment by MelvorIdle** [comment]
Hey! Thanks for bringing this to my attention.

Looking at the cloud, it definitely should be displaying an error that the password was too long during registration if it detects it to be over 64 characters in length.

I'll look into why it is still allowing registration and will apply a hotfix asap.

**Comment by MelvorIdle** [comment]
Ah yes, I see what is happening. The text box stops you from typing at 64 characters like you mentioned, and the user is not aware that it stopped.

I will fix this now, thanks again

**Comment by MelvorIdle** [comment]
Hotfixed released
