### ISSUE TITLE
Desktop Notifications

### ISSUE THREAD

**Issue by RedSparr0w** [MelvorIdle/melvoridle.github.io#15]
Would be cool if we could optionally enable desktop notifications.

Would be useful for the following events:
- Crops are ready to harvest.
- Run out of items when skilling (stopped skilling)
  - Smithing
  - Fletching
  - Crafting
  - Cooking
  - Firemaking
- You died
  - Combat
  - Thieving

**Comment by mrDLSable** [comment]
Yes. Perhaps even email notifications? Would be nice if you're away from your computer but can remote into it with your phone or a work pc.

**Comment by RedSparr0w** [comment]
Or even Discord notifications if you could link your Melvor Cloud account to your Discord account.

**Comment by mrDLSable** [comment]
Can discord bots be written in php?

**Comment by RedSparr0w** [comment]
Interesting, never heard of discordphp, not quite sure how it would work actually.
I've written quite a few in node.js though.
