### ISSUE TITLE
Pay-to-skip new task button not hidden when you don't have a task

### ISSUE THREAD

**Issue by Pimvgd** [MelvorIdle/melvoridle.github.io#150]
**Describe the bug**
Pay-to-skip new task button not hidden when you don't have a task. This allows new players (me) to hit the blue "new task" link, wasting my slayer coins.

**To Reproduce**
1. Don't have an active slayer task
2. Have some slayer coins (I guess 100 would a nice number)
3. Hit "New task" (blue link, top right corner of task tracking widget on combat page)
4. Coins are deducted

**Expected behavior**
Two options:
A: Don't show the slayer "new task" blue link button that makes you pay when you don't have a task
B: Don't make it cost slayer coins if you don't have an active task

**Screenshots**
![image](https://user-images.githubusercontent.com/20502925/77369375-c05e9980-6d5e-11ea-9e1c-3712bbf699af.png)

**Browser**
Chrome 64 bit 80.0.3987.149

**Console output**
N/A

**Comment by MelvorIdle** [comment]
Next update will ensure the button costs 0 SC when clicked if you do not have a slayer task.
