### ISSUE TITLE
Mole / Pig combo shows incorrect numbers

### ISSUE THREAD

**Issue by Meep-Master** [MelvorIdle/melvoridle.github.io#1500]
**Describe the bug**
When cooking any meal with the mole and pig equipped, the number of tablets remaining appears to jump by increments of up to 9 if viewing your loadout in the top right corner on mobile. When un-equipping a tablet, the number changes back to the "real" amount. Appears to only be a visual bug but can't confirm 100%.

**Comment by MelvorIdle** [comment]
I believe this has been fixed. Please open a new bug report if it has not
