### ISSUE TITLE
Potion tier upgrade doesn’t take effect in offline

### ISSUE THREAD

**Issue by gwmanka** [MelvorIdle/melvoridle.github.io#1501]
When crafting potions in herblore in offline mode, when the next potion tier is unlocked, it does not switch to producing the next tier potion even though it is available. For example, starting crafting at potion mastery level 48 ( tier 2), going to offline mode, coming back with leveling up to mastery 57 ( tier 3 unlocked at 50), but no tier 3 potions crafted.

**Comment by OhAsya** [comment]
Same issue here. A lot of wasted reagents due to this bug.

**Comment by MelvorIdle** [comment]
This is due to how offline progress works. It is calculated based on the mastery you were at when logging off.

This is not the case with tick-based skills. All skills are planned to go tick based over the coming updates
