### ISSUE TITLE
Woodcutting progress bar incorrect after leaving and returning to tab

### ISSUE THREAD

**Issue by blastedt** [MelvorIdle/melvoridle.github.io#1502]
**Describe the bug**
The woodcutting progress bar is incorrect when returning to the woodcutting page.

**To Reproduce**
1. Begin Woodcutting a log with a long interval (magic tree).
2. Navigate to another page and wait a few seconds
3. Return to the Woodcutting page.

**Expected behavior**
The Woodcutting progress bar should be partially filled and reflect the current progress of the cut.

**Actual Behavior**
The Woodcutting progress bar is empty when returning to the page, and begins filling at the usual rate.  When the cut completes, the bar suddenly empties and acts correctly from then on.

**Browser**
Chrome 94

**Are you using any scripts?**
No

**Comment by TaliUmbra** [comment]
I also have this bug

**Comment by MelvorIdle** [comment]
This is due to how animation rendering works on websites like Melvor Idle. The only way to fix this is to switch the skill to tick-based, which is in planning.
