### ISSUE TITLE
Interaction between PC and Mobile causing save-game overlaps 

### ISSUE THREAD

**Issue by fasontales** [MelvorIdle/melvoridle.github.io#1504]
I play on multiple devices, a PC and an iOS mobile device. Specifically when opening the game from the mobile device, it won't bother checking if the local file is older than the cloud file, and it'll load right into the local file overwriting the cloud file and automatically saving to the cloud file. This happens when you have the app already open on your mobile, then minimize it without closing it, then go onto your PC, make some game changes and save to the cloud, then resume the game on your mobile device. It doesn't matter how long you've left the game minimized on your phone, whether it's 10 minutes or 10 hours, this save overlapping will still occur. There is a small fix for this by going back onto your PC and loading the local file from there, but when I'm out of the house this is impossible. 

Sorry in advance for those that will get mad for the bug report not being formatted properly.

**Comment by MelvorIdle** [comment]
As the game is completely client side, please ensure apps are completely closed when playing on multiple devices to stop this issue from occurring.
