### ISSUE TITLE
Dying during offline thieving when I shouldn't be dying.

### ISSUE THREAD

**Issue by Sirosky** [MelvorIdle/melvoridle.github.io#1505]
**Describe the bug**
I've noticed this multiple times. I should be able to safely idle thieving all targets with adequate food and maxed auto-eat. But for some reason, I'm dying. This appears to only happen in offline mode.

**To Reproduce**
1. Start thieving
2. Go offline

**Expected behavior**
Heal and not die when I have adequate food.

**Screenshots**
![image](https://user-images.githubusercontent.com/2752448/138574812-d2afe8ea-d1e1-4903-b1ef-a70f214e273c.png)

**Browser**
Brave, most current version.

**Console output**
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
style.css:1 Failed to load resource: the server responded with a status of 404 ()
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloud.js?1208:65 Connected to PlayFab successfully
cloud.js?1208:66 PlayFab Connected: Sirosky
save.js?1208:54 set force reload to 0
combatManager.js?1208:1 Combat Manager Built...
raidManager.js?1208:1 Golbin Raid Manager Built...
save.js?1208:14 Loading Save Game...
save.js?1208:14 Save Game Loaded...
main.js?1208:5 Game Loaded
SEMI.js:172 good
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
utils.js:533 Game Loaded. SEMIUtils ready.
event-bus.js:59 Starting Event Bus
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
menus.js:99 SEMI v0.8.4 Loaded!
VM289:88 Melvor ETA: loading...
VM289:88 Melvor ETA: loaded!
mastery-enhancements.js:88 Loading Mastery Enhancements
cloud.js?1208:7 Synchronising with Cloud
core.js:259 auto-equip enabled at 10/23/2021, 10:57:54 AM
core.js:259 auto-farm enabled at 10/23/2021, 10:57:54 AM
core.js:259 auto-eat enabled at 10/23/2021, 10:57:54 AM
core.js:259 drop-chances enabled at 10/23/2021, 10:57:54 AM
core.js:259 auto-bonfire enabled at 10/23/2021, 10:57:54 AM
core.js:259 auto-master enabled at 10/23/2021, 10:57:54 AM
VM289:88 Melvor ETA: Failed to add settings menu! Melvor ETA will work fine without it. Install the "Melvor Idle Combat Simulator Reloaded" extension to use the settings interface.
VM289:88 Melvor ETA: Find it here: https://github.com/visua0/Melvor-Idle-Combat-Simulator-Reloaded
cloud.js?1208:65 Connected to PlayFab successfully
cloud.js?1208:66 PlayFab Connected: Sirosky
cloud.js?1208:65 Uncaught TypeError: Cannot read properties of null (reading 'data')
    at cloud.js?1208:65
    at XMLHttpRequest.xhr.onerror (PlayFabClientApi.js:112)
cloud.js?1208:65 Uncaught TypeError: Cannot read properties of null (reading 'data')
    at cloud.js?1208:65
    at XMLHttpRequest.xhr.onloadend (PlayFabClientApi.js:103)
e3855.playfabapi.com/Client/GetTitleData?sdk=JavaScriptSDK-1.93.210927:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
PlayFabClientApi.js:122 Uncaught (in promise) Object
cloud.js?1208:7 Synchronising with Cloud
game.js?1208:27 Took 0.086s to process 171323 ticks. 0.000501975800096893ms per tick.
2cloud.js?1208:7 Synchronising with Cloud
cloud.js?1208:99 PlayFab Get Title News Failed.
cloud.js?1208:99 PlayFab Error: 
cloud.js?1208:99 PlayFab Get Title News Failed.
cloud.js?1208:99 PlayFab Error: 
e3855.playfabapi.com/Client/GetTitleNews?sdk=JavaScriptSDK-1.93.210927:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
PlayFabClientApi.js:122 Uncaught (in promise) Object
cloud.js?1208:99 PlayFab Get Title News Failed.
cloud.js?1208:99 PlayFab Error: 
cloud.js?1208:99 PlayFab Get Title News Failed.
cloud.js?1208:99 PlayFab Error: 
e3855.playfabapi.com/Client/GetTitleNews?sdk=JavaScriptSDK-1.93.210927:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
PlayFabClientApi.js:122 Uncaught (in promise) Object
game.js?1208:27 Took 0.05689999997615814s to process 77047 ticks. 0.0007385102596617407ms per tick.
style.css:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
SEMI, but that shouldn't cause any issues.

**Comment by MelvorIdle** [comment]
Many fixes have been applied to the game. If this was a bug, it has possibly been addressed.. Please open a new bug report if it has not
