### ISSUE TITLE
Online cooking and Runescrafting not working over longer periods of time

### ISSUE THREAD

**Issue by WRombouts** [MelvorIdle/melvoridle.github.io#1507]
**Describe the bug**
I've noticed the issue before with cooking but now i actually tested it with runecrafting.

I'm running the game on a server browser that's always online and i remote into to check up on.

I set up my character to Runecraft overnight. after about 6 hours i had crafted 22k ancient runes
Then i saved and shut down the browser.
After 2 hours i opened the browser loaded my cloud save and i had made 66k Ancient runes

**To Reproduce**
go to runecrafting and craft any rune for an extended period (tested with 6 hours)
Note amount of runes crafted.
Cloudsave and shut down browser.
Let it run for extended period (tested with 2 hours)
Note amount of runes crafted.

if nessesery calculate runes crafter/h and see the discrepensy 

**Expected behavior**
I expect runecraft over long periods of time in online mode to yield the same results as runecrafting the same amount of time in offline mode

**Screenshots**

**Browser**
Google Chrome Version 94.0.4606.81 (Official Build) (64-bit)

**Console output**
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
style.css:1 Failed to load resource: the server responded with a status of 404 ()
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
cloud.js?1209:65 Connected to PlayFab successfully
cloud.js?1209:66 PlayFab Connected: changeofhard
save.js?1209:54 set force reload to 0
combatManager.js?1209:1 Combat Manager Built...
raidManager.js?1209:1 Golbin Raid Manager Built...
save.js?1209:14 Loading Save Game...
save.js?1209:14 Save Game Loaded...
main.js?1209:5 Game Loaded
MICSR.js:26 MICSR: setting up util
MICSR.js:26 MICSR: setting up playerSpecialNames
MICSR.js:26 MICSR: setting up statNames
MICSR.js:26 MICSR: unknown item property attackSpeed
MICSR.js:26 MICSR: unknown item property isTwoHanded
MICSR.js:26 MICSR: unknown item property specialAttackID
MICSR.js:26 MICSR: unknown item property equipmentSlot
MICSR.js:26 MICSR: unknown item property isPassiveItem
MICSR.js:26 MICSR: unknown item property damageReduction
MICSR.js:26 MICSR: unknown item property defenceBonus
MICSR.js:26 MICSR: unknown item property magicDefenceBonus
MICSR.js:26 MICSR: unknown item property rangedDefenceBonus
MICSR.js:26 MICSR: unknown item property attackBonus
MICSR.js:26 MICSR: unknown item property strengthBonus
MICSR.js:26 MICSR: unknown item property isAmmo
MICSR.js:26 MICSR: unknown item property rangedAttackBonus
MICSR.js:26 MICSR: unknown item property rangedStrengthBonus
MICSR.js:26 MICSR: unknown item property isMagic
MICSR.js:26 MICSR: unknown item property magicAttackBonus
MICSR.js:26 MICSR: unknown item property magicDamageBonus
MICSR.js:26 MICSR: unknown item property slayerBonusXP
MICSR.js:26 MICSR: unknown item property canUseMagic
MICSR.js:26 MICSR: unknown item property increasedWaterSpellDamage
MICSR.js:26 MICSR: unknown item property gpMultiplierCap
MICSR.js:26 MICSR: unknown item property gpMultiplierMin
MICSR.js:26 MICSR: unknown item property chanceToCrit
MICSR.js:26 MICSR: unknown item property critDamage
MICSR.js:26 MICSR: unknown item property decreasedAttackSpeed
MICSR.js:26 MICSR: unknown item property reflectDamage
MICSR.js:26 MICSR: unknown item property chanceToDoubleLoot
MICSR.js:26 MICSR: unknown item property gpMultiplier
MICSR.js:26 MICSR: unknown item property increasedGP
MICSR.js:26 MICSR: unknown item property ammoPreservation
MICSR.js:26 MICSR: unknown item property spellHeal
MICSR.js:26 MICSR: unknown item property hpRegenBonus
MICSR.js:26 MICSR: unknown item property increasedHPRegen
MICSR.js:26 MICSR: unknown item property increasedMaxHitpoints
MICSR.js:26 MICSR: unknown item property lifesteal
MICSR.js:26 MICSR: unknown item property decreasedAutoEatEfficiency
MICSR.js:26 MICSR: unknown item property increasedAutoEat
MICSR.js:26 MICSR: unknown item property prayerCostReduction
MICSR.js:26 MICSR: unknown item property summoningMaxHit
MICSR.js:26 MICSR: unknown item property attackLevelRequired
MICSR.js:26 MICSR: unknown item property defenceLevelRequired
MICSR.js:26 MICSR: unknown item property magicLevelRequired
MICSR.js:26 MICSR: unknown item property rangedLevelRequired
MICSR.js:26 MICSR: unknown item property slayerLevelRequired
MICSR.js:26 MICSR: unknown item property prayerBonus
MICSR.js:26 MICSR: unknown item property slayerAreaEffectNegationPercent
MICSR.js:26 MICSR: unknown item property increasedMinAirSpellDmg
MICSR.js:26 MICSR: unknown item property increasedMinEarthSpellDmg
MICSR.js:26 MICSR: unknown item property increasedMinFireSpellDmg
MICSR.js:26 MICSR: unknown item property increasedMinWaterSpellDmg
MICSR.js:26 MICSR: unknown item property craftingID
MICSR.js:26 MICSR: unknown item property fishingSpeedBonus
MICSR.js:26 MICSR: unknown item property fletchingID
MICSR.js:26 MICSR: unknown item property smithingID
MICSR.js:26 MICSR: unknown item property increasedSuccessRate
MICSR.js:26 MICSR: unknown item property baseChanceToPreserve
MICSR.js:26 MICSR: unknown item property bonusMasteryXP
MICSR.js:26 MICSR: unknown item property bonusSkillXP
MICSR.js:26 MICSR: unknown item property canEquip
MICSR.js:26 MICSR: unknown item property chanceToDoubleResources
MICSR.js:26 MICSR: unknown item property chanceToPreserve
MICSR.js:26 MICSR: unknown item property itemID
MICSR.js:26 MICSR: unknown item property slayerCost
MICSR.js:26 MICSR: unknown item property slayerTaskRequirement
MICSR.js:26 MICSR: setting up modifierNames
modifierNames.js:605 MICSR: unknown modifier increasedFrostburn
modifierNames.js:605 MICSR: unknown modifier increasedRunecraftingEssencePreservation
modifierNames.js:605 MICSR: unknown modifier autoEquipFoodUnlocked
modifierNames.js:605 MICSR: unknown modifier autoSwapFoodUnlocked
modifierNames.js:605 MICSR: unknown modifier increasedChanceSuccessfulCook
modifierNames.js:605 MICSR: unknown modifier decreasedChanceSuccessfulCook
modifierNames.js:605 MICSR: unknown modifier increasedChancePerfectCookGlobal
modifierNames.js:605 MICSR: unknown modifier decreasedChancePerfectCookGlobal
modifierNames.js:605 MICSR: unknown modifier increasedChancePerfectCookFire
modifierNames.js:605 MICSR: unknown modifier decreasedChancePerfectCookFire
modifierNames.js:605 MICSR: unknown modifier increasedChancePerfectCookFurnace
modifierNames.js:605 MICSR: unknown modifier decreasedChancePerfectCookFurnace
modifierNames.js:605 MICSR: unknown modifier increasedChancePerfectCookPot
modifierNames.js:605 MICSR: unknown modifier decreasedChancePerfectCookPot
modifierNames.js:605 MICSR: unknown modifier increasedThievingStealth
modifierNames.js:605 MICSR: unknown modifier decreasedThievingStealth
modifierNames.js:605 MICSR: unknown modifier increasedAltMagicRunePreservation
modifierNames.js:605 MICSR: unknown modifier decreasedAltMagicRunePreservation
modifierNames.js:605 MICSR: unknown modifier increasedMinThievingGP
modifierNames.js:605 MICSR: unknown modifier decreasedMinThievingGP
modifierNames.js:605 MICSR: unknown modifier increasedFishingSpecialChance
modifierNames.js:605 MICSR: unknown modifier decreasedFishingSpecialChance
modifierNames.js:605 MICSR: unknown modifier increasedAllotmentSeedCost
modifierNames.js:605 MICSR: unknown modifier decreasedAllotmentSeedCost
modifierNames.js:605 MICSR: unknown modifier increasedSummoningMaxHit
modifierNames.js:605 MICSR: unknown modifier decreasedSummoningMaxHit
modifierNames.js:605 MICSR: unknown modifier masteryToken
modifierNames.js:605 MICSR: non-existent modifier decreasedFoodBurnChance
modifierNames.js:605 MICSR: non-existent modifier summoningSynergy_9_10
MICSR.js:26 MICSR: AgilityCourse is waiting for Card
MICSR.js:26 MICSR: setting up Card
MICSR.js:26 MICSR: setting up CombatData
MICSR.js:26 MICSR: setting up Consumables
MICSR.js:26 MICSR: setting up DataExport
MICSR.js:26 MICSR: setting up Import
MICSR.js:26 MICSR: setting up Loot
MICSR.js:26 MICSR: setting up Plotter
MICSR.js:26 MICSR: setting up Menu
MICSR.js:26 MICSR: Simulator is waiting for SimEnemy
MICSR.js:26 MICSR: Simulator is waiting for SimManager
MICSR.js:26 MICSR: Simulator is waiting for SimPlayer
MICSR.js:26 MICSR: setting up SimEnemy
MICSR.js:26 MICSR: setting up SimManager
MICSR.js:26 MICSR: setting up SimPlayer
MICSR.js:26 MICSR: setting up TabCard
MICSR.js:26 MICSR: main is waiting for App
MICSR.js:26 MICSR: App is waiting for AgilityCourse
MICSR.js:26 MICSR: App is waiting for Simulator
MICSR.js:26 MICSR: setting up AgilityCourse
MICSR.js:26 MICSR: setting up Simulator
MICSR.js:26 MICSR: setting up App
MICSR.js:26 MICSR: setting up main
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
combatManager.js?1209:1 Combat Manager Built...
MICSR.js:26 MICSR: Melvor Idle Combat Simulator Reloaded v1.5.13 loaded, but simulation results may be inaccurate due to game version incompatibility.
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
cloud.js?1209:65 Connected to PlayFab successfully
cloud.js?1209:66 PlayFab Connected: changeofhard
cloud.js?1209:7 Synchronising with Cloud
DevTools failed to load source map: Could not load content for chrome-extension://fjdmkanbdloodhegphphhklnjfngoffa/lib/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
style.css:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
i'm using the chrome plugin for Melvor Idle Combat Simulator Reloaded v1.5.13
other than this i'm not running anything specific for Melvor

**Comment by MelvorIdle** [comment]
This is potentially due to mastery affecting the quantity of runes created per craft, plus increases in preservation chance.
