### ISSUE TITLE
[Android] App not respecting screen rotation lock

### ISSUE THREAD

**Issue by OhAsya** [MelvorIdle/melvoridle.github.io#1508]
**Describe the bug**
Used the app as normal today, and whenever I place my phone in landscape rotation app rotates despite system being in locked rotation mode.

**To Reproduce**
1. Go to 'app'
2. Click on 'nothing'
3. Rotate phone

**Expected behavior**
For the app not to rotate.

**Phone brand and Android version**
Google Pixel 4a on Android 11 (RQ3A.211001.001).

**App version**
2.0, updated Oct 23rd.

**Are you using any scripts?**
No.

**Comment by SustainableBlueDuck** [comment]
This issue is closed, bit it is still present

**Comment by OhAsya** [comment]
My mistake, I believed the issue was fixed in the latest update. Reopening.

**Comment by SustainableBlueDuck** [comment]
Sorry about the confusion, but after installing the update (end okt available) the issue is fixed.
