### ISSUE TITLE
Scrollbars appearing at less than 100% zoom [Steam]

### ISSUE THREAD

**Issue by InThePipe** [MelvorIdle/melvoridle.github.io#1510]
**Describe the bug**
Scrollbars appear because text windows are going off screen in the Steam version of Melvor Idle. This occurs when you set the zoom size to less than 100%, and have seemingly any resolution other than mobile phone ratio resolutions. This appears to occur for any text windows that appear near the edge of the screen.

**To Reproduce**
1. Go to settings, change zoom to less 100%
2. Click on mining, and mouse over the gloves - or any mastery with a pet, and mouse over the pet
3. See scrollbars, text window off screen
4. Change zoom back to 100% default, repeat step 2 - no scrollbar, text window on screen

**Expected behavior**
No scrollbars, because the text window would be on screen.

**Screenshots**
https://i.imgur.com/HolwTkf.png

**Browser**
Steam.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Same bug as #497

Closing this to clean up.
