### ISSUE TITLE
Suggestion: Allow [Upgrade] option for Perfect-cooked items

### ISSUE THREAD

**Issue by gutblender** [MelvorIdle/melvoridle.github.io#1514]
I suggest an option to turn Perfect items into their regular counterparts. 

Example: On my hardcore, I cooked a bunch of sharks for mastery. I'm swimming in food that I don't need, but I do plan on keeping sharks because it's the best food I don't have mastery of, and I will probably passive-cook a ton of them while doing other cooking masteries. I already toggled off Perfect Cooks, but there are a few thousand I've done that I'll waste by selling because I'd rather not have them in my bank. Even better would be to turn them into regular cooked sharks so they join the same stack.

Odd to call it Upgrade in this case, but I think of charge stones and how that works so perhaps that could save time coding.

Super low priority, because one can just toggle it off proactively. This would just be a retroactive way to do that.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
