### ISSUE TITLE
Save corrupted, "Fix my save" not fixing the problem

### ISSUE THREAD

**Issue by dbasi** [MelvorIdle/melvoridle.github.io#1517]
**Describe the bug**
When trying to load both Local and Cloud saves I get the following error message: "Please verify integrity of game files"... 
with the following error code: "updateBankSearch@https://melvoridle.com/assets/js/game/bank.js?1209:4:263
loadBank@https://melvoridle.com/assets/js/game/bank.js?1209:10:30
updateWindow@https://melvoridle.com/assets/js/game/main.js?1209:2:1339
finaliseLoad@https://melvoridle.com/assets/js/game/main.js?1209:344:1
selectCharacter@https://melvoridle.com/assets/js/game/main.js?1209:335:173
onloadEvent@https://melvoridle.com/assets/js/game/save.js?1209:57:232
resetEntirePage/<@https://melvoridle.com/assets/js/game/save.js?1209:61:209
C.fn.load/</<@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84821
each@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:2967
each@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:1453
C.fn.load/<@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84803
r@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:28083
fireWith@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:28851
c@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:79484
o/<@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:81937
"

**To Reproduce**

    Try to load local/cloud save, error appears
    Try to use "fix my save" nothing happens

**Expected behavior**
I expect the game to load

**Screenshots**
![image](https://user-images.githubusercontent.com/41020757/138865059-60515a41-51bc-4b19-95bf-7d2d775181b9.png)

**Browser**
Firefox 93.0 (64-bit)

**Console output**
"GEThttps://melvoridle.com/style.css?2
[HTTP/2 404 Not Found 22ms]

Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-129674422-1”. index_noads.php:6:1
Loading failed for the <script> with source “https://melvoridle.com/assets/js/game/bank2.js?1209”. index_noads.php:2546:1
Loading failed for the <script> with source “https://static.cloudflareinsights.com/beacon.min.js”. update_v022.html:526:1
Loading failed for the <script> with source “https://static.cloudflareinsights.com/beacon.min.js”. index.html:563:1
jQuery.Deferred exception: Chart is not defined value@https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316
value@https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626
@https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705
e@https://melvoridle.com/assets/js/oneui.core.min.js:6:29792
c/</t<@https://melvoridle.com/assets/js/oneui.core.min.js:6:30116
setTimeout handler*c/<@https://melvoridle.com/assets/js/oneui.core.min.js:6:30325
r@https://melvoridle.com/assets/js/oneui.core.min.js:6:28083
fireWith@https://melvoridle.com/assets/js/oneui.core.min.js:6:28851
fire@https://melvoridle.com/assets/js/oneui.core.min.js:6:28887
r@https://melvoridle.com/assets/js/oneui.core.min.js:6:28083
fireWith@https://melvoridle.com/assets/js/oneui.core.min.js:6:28851
ready@https://melvoridle.com/assets/js/oneui.core.min.js:6:31817
F@https://melvoridle.com/assets/js/oneui.core.min.js:6:31599
EventListener.handleEvent*@https://melvoridle.com/assets/js/oneui.core.min.js:6:31965
@https://melvoridle.com/assets/js/oneui.core.min.js:6:220
@https://melvoridle.com/assets/js/oneui.core.min.js:6:225
 undefined oneui.core.min.js:6:31368
Loading failed for the <script> with source “https://static.cloudflareinsights.com/beacon.min.js”. index_noads.php:2576:1
Uncaught ReferenceError: Chart is not defined
    value https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6
    value https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6
    <anonymous> https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6
    e https://melvoridle.com/assets/js/oneui.core.min.js:6
    t https://melvoridle.com/assets/js/oneui.core.min.js:6
    setTimeout handler*c/< https://melvoridle.com/assets/js/oneui.core.min.js:6
    r https://melvoridle.com/assets/js/oneui.core.min.js:6
    fireWith https://melvoridle.com/assets/js/oneui.core.min.js:6
    fire https://melvoridle.com/assets/js/oneui.core.min.js:6
    r https://melvoridle.com/assets/js/oneui.core.min.js:6
    fireWith https://melvoridle.com/assets/js/oneui.core.min.js:6
    ready https://melvoridle.com/assets/js/oneui.core.min.js:6
    F https://melvoridle.com/assets/js/oneui.core.min.js:6
    EventListener.handleEvent* https://melvoridle.com/assets/js/oneui.core.min.js:6
    <anonymous> https://melvoridle.com/assets/js/oneui.core.min.js:6
    <anonymous> https://melvoridle.com/assets/js/oneui.core.min.js:6
be_pages_dashboard.min.js:6:1316
GEThttps://cdn.melvor.net/core/v018/assets/media/favicons/favicon-192x19.svg
[HTTP/3 403 Forbidden 0ms]

GEThttps://cdn.melvor.net/core/v018/assets/media/favicons/favicon-192x19.svg
[HTTP/3 403 Forbidden 0ms]

Connected to PlayFab successfully cloud.js:65:389
PlayFab Connected: dbasi cloud.js:66:98
set force reload to 0 save.js:54:60
Combat Manager Built... combatManager.js:1:636
Golbin Raid Manager Built... raidManager.js:1:975
Loading Save Game... save.js:14:29
Save Game Loaded... save.js:14:140
ReferenceError: bankSearch is not defined
    updateBankSearch https://melvoridle.com/assets/js/game/bank.js?1209:4
    loadBank https://melvoridle.com/assets/js/game/bank.js?1209:10
    updateWindow https://melvoridle.com/assets/js/game/main.js?1209:2
    finaliseLoad https://melvoridle.com/assets/js/game/main.js?1209:344
    selectCharacter https://melvoridle.com/assets/js/game/main.js?1209:335
    onloadEvent https://melvoridle.com/assets/js/game/save.js?1209:57
    resetEntirePage https://melvoridle.com/assets/js/game/save.js?1209:61
    load https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    each https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    each https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    load https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    r https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    fireWith https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    c https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    o https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    send https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    ajax https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    load https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    resetEntirePage https://melvoridle.com/assets/js/game/save.js?1209:61
    setForceReload https://melvoridle.com/assets/js/game/save.js?1209:54
    selectCharacter https://melvoridle.com/assets/js/game/main.js?1209:335
    selectCharacter https://melvoridle.com/assets/js/game/main.js?1209:334
    promise callback*value https://cdn.melvor.net/core/v018/assets/js/plugins/sweetalert2/sweetalert2.min.js:1
    selectCharacter https://melvoridle.com/assets/js/game/main.js?1209:334
    onclick https://melvoridle.com/index_noads.php:1
main.js:7:932
Loading failed for the <script> with source “https://static.cloudflareinsights.com/beacon.min.js”. update_v022.html:526:1
Loading failed for the <script> with source “https://static.cloudflareinsights.com/beacon.min.js”. index.html:563:1
jQuery.Deferred exception: Chart is not defined value@https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316
value@https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626
@https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705
e@https://melvoridle.com/assets/js/oneui.core.min.js:6:29792
c/</t<@https://melvoridle.com/assets/js/oneui.core.min.js:6:30116
setTimeout handler*c/<@https://melvoridle.com/assets/js/oneui.core.min.js:6:30325
r@https://melvoridle.com/assets/js/oneui.core.min.js:6:28083
fireWith@https://melvoridle.com/assets/js/oneui.core.min.js:6:28851
fire@https://melvoridle.com/assets/js/oneui.core.min.js:6:28887
r@https://melvoridle.com/assets/js/oneui.core.min.js:6:28083
fireWith@https://melvoridle.com/assets/js/oneui.core.min.js:6:28851
ready@https://melvoridle.com/assets/js/oneui.core.min.js:6:31817
F@https://melvoridle.com/assets/js/oneui.core.min.js:6:31599
EventListener.handleEvent*@https://melvoridle.com/assets/js/oneui.core.min.js:6:31965
@https://melvoridle.com/assets/js/oneui.core.min.js:6:220
@https://melvoridle.com/assets/js/oneui.core.min.js:6:225
 undefined oneui.core.min.js:6:31368
Uncaught ReferenceError: Chart is not defined
    value https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6
    value https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6
    <anonymous> https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6
    e https://melvoridle.com/assets/js/oneui.core.min.js:6
    t https://melvoridle.com/assets/js/oneui.core.min.js:6
    setTimeout handler*c/< https://melvoridle.com/assets/js/oneui.core.min.js:6
    r https://melvoridle.com/assets/js/oneui.core.min.js:6
    fireWith https://melvoridle.com/assets/js/oneui.core.min.js:6
    fire https://melvoridle.com/assets/js/oneui.core.min.js:6
    r https://melvoridle.com/assets/js/oneui.core.min.js:6
    fireWith https://melvoridle.com/assets/js/oneui.core.min.js:6
    ready https://melvoridle.com/assets/js/oneui.core.min.js:6
    F https://melvoridle.com/assets/js/oneui.core.min.js:6
    EventListener.handleEvent* https://melvoridle.com/assets/js/oneui.core.min.js:6
    <anonymous> https://melvoridle.com/assets/js/oneui.core.min.js:6
    <anonymous> https://melvoridle.com/assets/js/oneui.core.min.js:6
be_pages_dashboard.min.js:6:1316
Synchronising with Cloud"
**Are you using any scripts?**
No Scripts are being used.

**Comment by MelvorIdle** [comment]
I believe this issue has been addressed. Please open a new report if it has not.
