### ISSUE TITLE
Scollbar on items in bank not working on 130% zoom

### ISSUE THREAD

**Issue by FokMok** [MelvorIdle/melvoridle.github.io#1518]
**Describe the bug**
When playing on 130% zoom, you're unable to move the scollbar of an item in your bank from the left to the right. Moving it left is also not entirely accurate.

**To Reproduce**
1. Go to settings and turn zoom to 130%
2. Restart game to apply zoom changes as the game suggests
3. Go to bank
4. Select item
5. Try to move the scrollbar right, which you can't.

**Expected behavior**
You can move the dot on the bar to the right to select the amount of items you wish to sell, instead of typing.

**Screenshots**
https://i.imgur.com/TyDXv2f.png
Below is a gif of where I first found out I can scroll left if I move my cursor far off the bar
https://i.imgur.com/lo8TfPg.gif
Below is a gif where you can see how far off the bar my mouse goes before it scrolls left.
https://i.imgur.com/l1cEJlM.gif

**Browser**
Steam Version.

**Console output**
Nothing happens if I press F12.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Same bug as #497

Closing this to clean up.
