### ISSUE TITLE
Slayer Task should show attack style next to combat level

### ISSUE THREAD

**Issue by SamihMustafa** [MelvorIdle/melvoridle.github.io#1519]
The slayer tab currently shows the mob with their combat level. It would be a useful indicator to know the attack style of the mob as well. We can then decide if we need to change equipment before jumping to enemy.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
