### ISSUE TITLE
Melvor no longer works on steam or browser 

### ISSUE THREAD

**Issue by Kingsman1331** [MelvorIdle/melvoridle.github.io#1520]
**Describe the bug**
I bought the game a couple months ago and began playing between steam and IOS. After about a week the game stopped working on steam and browser but still worked on IOS. The game would begin to load then just stay on the red M. I tried what one of the moderators said on steam and it didn't fix it. 

**To Reproduce**
Don't know how it happened and cant reproduce because i cant get into game

**Expected behavior**
Game to start normally 

**Screenshots**
![melvor error 1](https://user-images.githubusercontent.com/93221510/138944587-27fb1277-984d-4be8-a7d5-9eb70fcbfa7e.PNG)
![melvor error 2](https://user-images.githubusercontent.com/93221510/138944593-cf8aa2ea-e581-48af-9299-a015ff363a79.PNG)
![melvor error 3](https://user-images.githubusercontent.com/93221510/138944597-7f6f2e2d-965b-48d7-b407-2b1130859024.PNG)

**Browser**
Steam google chrome IOS

**Console output**
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
style.css:1 Failed to load resource: the server responded with a status of 404 ()
style.css:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for chrome-extension://alplpnakfeabeiebipdmaenpmbgknjce/include.preload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
sweetalert2.min.css:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
ion.rangeSlider.css:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
oneui.css:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
toastify.min.css:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
ifvisible.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
Sortable.min.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
2DevTools failed to load source map: Could not load content for chrome-extension://alplpnakfeabeiebipdmaenpmbgknjce/include.preload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
2DevTools failed to load source map: Could not load content for chrome-extension://alplpnakfeabeiebipdmaenpmbgknjce/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
t @ oneui.core.min.js:6
setTimeout (async)
(anonymous) @ oneui.core.min.js:6
r @ oneui.core.min.js:6
fireWith @ oneui.core.min.js:6
fire @ oneui.core.min.js:6
r @ oneui.core.min.js:6
fireWith @ oneui.core.min.js:6
ready @ oneui.core.min.js:6
F @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
value @ be_pages_dashboard.min.js:6
value @ be_pages_dashboard.min.js:6
(anonymous) @ be_pages_dashboard.min.js:6
e @ oneui.core.min.js:6
t @ oneui.core.min.js:6
setTimeout (async)
C.readyException @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
e @ oneui.core.min.js:6
t @ oneui.core.min.js:6
setTimeout (async)
(anonymous) @ oneui.core.min.js:6
r @ oneui.core.min.js:6
fireWith @ oneui.core.min.js:6
fire @ oneui.core.min.js:6
r @ oneui.core.min.js:6
fireWith @ oneui.core.min.js:6
t @ oneui.core.min.js:6
setTimeout (async)
(anonymous) @ oneui.core.min.js:6
r @ oneui.core.min.js:6
fireWith @ oneui.core.min.js:6
fire @ oneui.core.min.js:6
r @ oneui.core.min.js:6
fireWith @ oneui.core.min.js:6
ready @ oneui.core.min.js:6
F @ oneui.core.min.js:6
index_ads.php:2494 GET https://cdn.melvor.net/core/v018/assets/media/main/bg_summoning.jpg net::ERR_CONNECTION_REFUSED
oneui.core.min.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
oneui.app.min.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
popper.min.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
es6-promise.auto.min.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
sweetalert2.min.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
ion.rangeSlider.min.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
be_ui_animations.min.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
jquery.mobile-events.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
fuse.min.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
tippy-bundle.umd.min.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
pako.min.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
main.js?1209:81 Uncaught ReferenceError: $ is not defined
    at main.js?1209:81
(anonymous) @ main.js?1209:81
toastify-js.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
DevTools failed to load source map: Could not load content for chrome-extension://alplpnakfeabeiebipdmaenpmbgknjce/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
update_v022.html:105 GET https://cdn.melvor.net/core/v018/assets/media/skills/thieving/princess.svg net::ERR_CONNECTION_REFUSED
update_v022.html:117 GET https://cdn.melvor.net/core/v018/assets/media/skills/crafting/crafting.svg net::ERR_CONNECTION_REFUSED
update_v022.html:122 GET https://cdn.melvor.net/core/v018/assets/media/bank/ring_of_wealth.png net::ERR_CONNECTION_REFUSED
update_v022.html:220 GET https://cdn.melvor.net/core/v018/assets/media/skills/cooking/furnace.svg net::ERR_CONNECTION_REFUSED
update_v022.html:220 GET https://cdn.melvor.net/core/v018/assets/media/skills/cooking/pot.svg net::ERR_CONNECTION_REFUSED
update_v022.html:226 GET https://cdn.melvor.net/core/v018/assets/media/bank/plain_pizza_slice.png net::ERR_CONNECTION_REFUSED
weapon_sword_adamant.png:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
combat.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
strength.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
ranged.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
magic.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
defence.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
update_v022.html:246 GET https://cdn.melvor.net/core/v018/assets/media/bank/whale_cooked_perfect.png net::ERR_CONNECTION_REFUSED
update_v022.html:257 GET https://cdn.melvor.net/core/v018/assets/media/skills/cooking/cooking.svg net::ERR_CONNECTION_REFUSED
update_v022.html:264 GET https://cdn.melvor.net/core/v018/assets/media/bank/carrot.png net::ERR_CONNECTION_REFUSED
passive_slot.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
armour_helmet.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
armour_cape.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
misc_amulet.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
weapon_quiver.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
weapon_sword.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
armour_platebody.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
armour_shield.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
armour_platelegs.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
armour_gloves.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
armour_boots.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
misc_ring.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
misc_summon.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
volcanic_cave.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
slayer.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
weapon_sword_adamant.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
mastery_header.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
coins.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
hardcore.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
question.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
easter_shop.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
herb_sack.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
easter.svg:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
mbuck.png:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
god_aeris.png:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
god_glacia.png:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
god_terran.png:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
god_ragnar.png:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
save.js?1209:60 Uncaught ReferenceError: afterCutOff is not defined
    at window.onload (save.js?1209:60)
window.onload @ save.js?1209:60
load (async)
(anonymous) @ save.js?1209:60
cdn.melvor.net/core/v018/assets/media/favicons/favicon.png:1 GET https://cdn.melvor.net/core/v018/assets/media/favicons/favicon.png net::ERR_CONNECTION_REFUSED
cdn.melvor.net/core/v018/assets/media/favicons/favicon-192x19.svg:1 GET https://cdn.melvor.net/core/v018/assets/media/favicons/favicon-192x19.svg net::ERR_CONNECTION_REFUSED

**Are you using any scripts?**
no scripts

**Comment by MelvorIdle** [comment]
Can you confirm if you can access the game now?

**Comment by Kingsman1331** [comment]
Still not working. I actually cleared my cache earlier today to try again
with the new update release but it didint work. I also tried on my laptop
and it does work there so I’m thinking it’s an issue with some file in my
computer but I don’t know which one because I’ve pretty much reset
everything.

**Comment by MelvorIdle** [comment]
It looks like your game is refusing to download the scripts the game runs on. Do you use a VPN or similar that would be blocking this connection?

**Comment by Kingsman1331** [comment]
No I had a firewall up but closed it a couple of times after resetting the
game to see if that worked and it didint.

**Comment by MelvorIdle** [comment]
Do you have a cloud save? I can provide step to reset the game which will open up a fresh copy (without your local saves)

**Comment by Kingsman1331** [comment]
Yes I do I have been playing a lot on my phone since I couldn’t open the
game on computer.

**Comment by MelvorIdle** [comment]
On your computer, head to:

`C:\Users\YOUR_USERNAME\AppData\Local\Melvor Idle\User Data`

Delete everything in there and start the game. Let me know how it goes.

**Comment by Kingsman1331** [comment]
So I don’t have it downloaded on my C drive but from steam I am able to go
to where Melvor is downloaded. There isint any user data folder anywhere on
the system for me to uninstall files from. There are four folder titled
dictionaries, lib, locales, and swiftshader.

**Comment by MelvorIdle** [comment]
You need to locate your AppData folder for your system, not for the game itself.

**Comment by MelvorIdle** [comment]
Usually that sits in C, where your OS is installed.

**Comment by Kingsman1331** [comment]
Alright found that and deleted everything in it. The game still dosent load
still stuck on the game logo.

**Comment by MelvorIdle** [comment]
This is an issue with your network blocking the requests. Please ensure no VPNs or firewalls are active. Unfortunately there is nothing I can do on my end.
