### ISSUE TITLE
Cloud save across multiple devices

### ISSUE THREAD

**Issue by Nategc** [MelvorIdle/melvoridle.github.io#1523]
My character was created on my phone and then uploaded as a cloud save. I then logged in on my tablet and created a second character there. These seemed to both be slot #1 for the respective devices. This created a conflict in cloud saves and ultimately the new tablet character overwrote my original phone character. These characters had different names and play type (one was normal and the other was adventure mode).

Given a character exists in a save slot on cloud save
When the user logs in on a new device
Then the user should be prompted to download cloud saves before being allowed to create a new character

OR

When a new character is created
Then the application should create the character in a new save slot (should not overwrite existing save slot)

**Comment by MelvorIdle** [comment]
Issue will be resolved in the upcoming save slot UI update
