### ISSUE TITLE
In Android, turning device makes game screen to turn as well

### ISSUE THREAD

**Issue by JacoboMoral** [MelvorIdle/melvoridle.github.io#1524]
**Describe the bug**
In Android, I have disabled the auto-rotate settings. However, I still get my game to rotate whenever I turn my phone over.

**To Reproduce**
1. Open game
2. Turn phone over
3. See game rotate along

**Expected behavior**
I expected game to follow Android settings and only rotate if allowed by settings.

**Comment by SustainableBlueDuck** [comment]
The mentioned issue (#1508) has been closed as of now, but the issue is still present. So its good this thread is still open
