### ISSUE TITLE
High data consumption

### ISSUE THREAD

**Issue by bck356** [MelvorIdle/melvoridle.github.io#1527]
**Describe the bug**
The game consumes an excessive amount of data. 

**To Reproduce**
No specific usage (as far as I'm aware) to cause the issue. Playing Android version, build 0.03.4

**Expected behavior**
Less data consumption

**Screenshots**
![Screenshot_20211027-163825](https://user-images.githubusercontent.com/93291614/139151554-696c1e6a-938a-4cb7-875b-3098a7f65ec4.png)

**Browser**
Android version, unsure if it's a browser wrapper or standalone

**Console output**
Unable to access console

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
I believe this is now fixed in the latest Android app update to address cache issues.
