### ISSUE TITLE
Crashing bug on steam

### ISSUE THREAD

**Issue by cheesbeurger** [MelvorIdle/melvoridle.github.io#1532]
**Describe the bug**
A clear and concise description of what the bug is: Whenever I launch Melvor Idle on steam, I get to the character selection screen and the game crashes. This has started to happen after I updated to macOS Monterey Version 12.0.1. Also, on the same computer the browser version works perfectly fine and when I'm logged on the cloud in the steam version it crashes instantly at launch.

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected to happen: Expected behavior is the game launching normally like it usually would.

**Screenshots**
If applicable, add screenshots to help explain your problem: Here's a youtube link to my problem happening https://youtu.be/obOHkBZe0dg originally, and here's after when I logged into the cloud: 

**Browser**
Please tell us what browser you are using and what version: I'm using the steam app, and my game version is Alpha v0.22.1.

**Console output**
Please open the console by pressing F12 and copy it here: I can't grab a screenshot due to the game instantly crashing.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred: No I'm not using any scripts I'm too stupid for that.

**Comment by cheesbeurger** [comment]
Oops, I forgot to add the video to the when I logged onto the cloud: https://youtu.be/byzWN3sfLcA

**Comment by MelvorIdle** [comment]
Can you confirm if this is still occurring since the latest update?
