### ISSUE TITLE
Background idle on Android 12

### ISSUE THREAD

**Issue by ChiSox** [MelvorIdle/melvoridle.github.io#1533]
**Describe the bug**
Ok Android 12 of you put the app in the background the game will not progress if you have the setting for "offline background progress" disabled. I have that setting disabled for browser usage, but on mobile it requires me to close the app Everytime move away or it will be stagnant until I come back. I only noticed this issue once switching to Android 12.

**Comment by MelvorIdle** [comment]
That setting is required to be enabled to allow background idling on Mobile devices. If it is disabled, it will not work.
