### ISSUE TITLE
Offline Cooking crashing due to null offline variable

### ISSUE THREAD

**Issue by IDontCyber** [MelvorIdle/melvoridle.github.io#1534]
**Describe the bug**
Error calculating offline progress.

**To Reproduce**
Do not know how to reproduce.

**Expected behavior**
Expecting to come back to food being cooked.

**Screenshots**
See attached

**Browser**
Steam Client

**Console output**
Steam Client

**Are you using any scripts?**
No

![Error](https://user-images.githubusercontent.com/93421253/139522745-313a6912-194c-4907-b4e5-0b40dea9a73a.PNG)
.

**Comment by MelvorIdle** [comment]
I believe this issue has been addressed. Please open a new report if it has not.
