### ISSUE TITLE
Alt. Magic Displays Incorrect Sale Price

### ISSUE THREAD

**Issue by oorzkws** [MelvorIdle/melvoridle.github.io#1535]
**Describe the bug**
The incorrect sale price can be displayed when using Item Alchemy I on 1GP priced items.

**To Reproduce**
1. Select Alt. Magic
2. Select Item Alchemy I
3. Choose an item with 1GP sale value
4. Observe displayed sale price vs GP gained

**Expected behavior**
Actual sale price (1 GP) is displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/65210810/139522893-6f3ee8fc-73de-4513-a683-145f19dad9fb.png)

**Browser**
Waterfox G4.0.1

**Are you using any scripts?**
N

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
