### ISSUE TITLE
Rock respawn/hp/damage not calculating right

### ISSUE THREAD

**Issue by Danieljramin** [MelvorIdle/melvoridle.github.io#1536]
I noticed several times when mining dragonite that it doesn’t respawn in the 2 minutes it is supposed to. On top of that it’s up is not calculating right, nor does it take damage sometimes.

(top left shows the time to calculate how long between screenshots)
I’ve taken screenshots showing:

1) Rock (not just dragonite but rune and adamant too) not respawning after 7 minutes. 

2) Rock hp doesn’t go down when I switch apps. (iPhone 11 Pro Max, up to date iOS. I’ll swipe between apps and the rock has no damage taken while I was gone. I reliably duplicated this process two more times with screenshots)

3) Coming back to only having mined 47 ore in 9 minutes despite my mastery being 66. (Sometimes I mine 200+ in the same time frame)

I’m sorry these aren’t organized well, I’m not used to bug reporting and I’m doing it from my phone. (I only attached half of my screenshots, but I have quite a few more as more evidence if you need it)

1) 8:53 -> Dragonite and rune depleted 
![20EEAA37-5AB2-49B6-B0D4-50F131A1FEE3](https://user-images.githubusercontent.com/93441976/139540977-71ebd47a-162d-4723-b9e2-a27e53a6dfa3.png)

2) 8:55 Dragonite, runite, adamantite depleted.
![39F5D16B-3219-44FA-8A7F-018294177093](https://user-images.githubusercontent.com/93441976/139541053-885e00c5-a79c-4c81-a912-15e7cdd82884.png)

3) 8:57 Logged out, then back in.
![09B77756-8919-4F88-845D-195F0DCAF643](https://user-images.githubusercontent.com/93441976/139541590-0389dded-f606-4780-8af9-88f7ab4ee21c.png)

4) 8:57 Dragonite, Runite, adamantite still depleted.
![22512277-B336-49B8-BDBB-B5F8C2CC741A](https://user-images.githubusercontent.com/93441976/139541054-c94187ab-d3e7-460f-9e11-70fd293075bb.png)

5) 9:00 Dragonite still depleted, runeite and adamantite respawned.
![AB073F10-1544-4004-A5B9-2E784C3A3CB5](https://user-images.githubusercontent.com/93441976/139541056-bf035e34-d83e-49dc-ab5f-eaaef2d7d05b.png)

6) 2 hours –> 859 Dragonite mined
![08219933-DD96-474B-B713-8462F1EC02D9](https://user-images.githubusercontent.com/93441976/139540337-e7d824b2-f7df-4a4d-9974-952adf18f037.png)

7) 39 minutes –> 878 Dragonite mined
![CD396980-8BFC-49FB-A24C-3C08D495EFD3](https://user-images.githubusercontent.com/93441976/139540338-da133f16-6974-4f71-92a3-a28801c5c217.png)

8) 4:47 –> Beginning to track rock hp depletion. Switched out of app.
![19012C15-17FE-431B-B913-C57032E06761](https://user-images.githubusercontent.com/93441976/139540339-bf0525ad-0eb9-4d09-9c3b-02a339273f42.png)

9) 4:48 –> Switched back to app, 12 ore mined and very little hp gone. Switched out of app.
![CB6594D3-C300-48BA-832A-139F0B6D171C](https://user-images.githubusercontent.com/93441976/139540341-b5279d89-9950-46a6-ad31-c2dba1d19916.png)

10) 4:49 –> Switched back to app, 18 ore mined and very little gone. Stayed in app
![2DB88D54-3928-4F02-B736-6A3F75892575](https://user-images.githubusercontent.com/93441976/139540342-299e5e06-4205-447b-8aaf-be613414c7c9.png)

11) Still 4:49 -> Stayed in app and depleted 1/2 rock hp in 20 seconds.
![F1EC21F6-90A4-4005-B3D4-3A62C12BF01A](https://user-images.githubusercontent.com/93441976/139541239-c7b7c480-96d0-4f17-89cd-0393e793459c.png)

12) Still 4:49 -> switched out of app after rock depleting, switched back in to have mined 6 ores even after depletion
![DB59AC08-BA86-45FE-B2AA-B942ADD05EFE](https://user-images.githubusercontent.com/93441976/139541335-30e06904-8f1c-4028-9049-0bcc06ecd3ae.png)

13) 4:52 Switched out of app, came back 2 minutes later with full hp rock and mined 52 ore in two minutes.
![26337624-251B-44E4-814E-9EC64A55910D](https://user-images.githubusercontent.com/93441976/139541409-d4ea8191-7286-434e-9de6-00e83218c07a.png)

14) 9 minutes gone, 208 ore mined (switching between apps)
![1185F483-8E61-4C8F-9694-F27C888482A7](https://user-images.githubusercontent.com/93441976/139540343-57ba5f79-0a91-4679-9ea5-b07c9a934138.png)

15) 9 minutes gone, 47 ore mined (closed app)
![8CF506D9-4A08-492B-8147-6F8FF032DACE](https://user-images.githubusercontent.com/93441976/139540344-5f98c83e-5aaa-4edf-a685-5c16aa22c31f.png)

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
