### ISSUE TITLE
Items spawned in bank after checking item mastery

### ISSUE THREAD

**Issue by Danieljramin** [MelvorIdle/melvoridle.github.io#1537]
**Describe the bug**
Was looking at item mastery 10/30/2021 roughly 30 minutes ago. Clicked on lemons (lol) and burnt carp, no rhyme or reason, just happened to.

Reported the mining bug I found it GitHub.

Closed the app (couldn’t figure out how to get back to Melvor from GitHub)

Logged back in to find both items in my bank. Loading in screen showed my runecrafting tokens I gained, xp and runes I got, but didn’t show the other two. Didn’t click sort, so clearly the game put them into the bank after the tokens.

Haven’t tried reproducing, but I haven’t had either item in my bank in over a month.

![C247286E-75B9-43C0-BDEF-5344982DD49E](https://user-images.githubusercontent.com/93441976/139542008-643a11a7-9b3b-486a-9681-36e6b058f9f7.png)

**Browser**
iPhone 11 Pro Max, up to date iOS, up to date Melvor App.

**Are you using any scripts?**
No scripts or mods ever used. Don’t even know how.

**Comment by coolrox95** [comment]
This is intended behavior for items that are no longer obtainable in game. Clicking on them in the item log will add it to your bank. This is so players that owned them in the past can re-obtain them if they wish.
