### ISSUE TITLE
Monster Drops button shows that dungeon enemies will drop bones/items, when they do not

### ISSUE THREAD

**Issue by RyanFirrow** [MelvorIdle/melvoridle.github.io#1538]
**Describe the bug**
A clear and concise description of what the bug is. When clearing the Dragons Den dungeon for 12hrs I received zero dragon bones. Even when doing online combat in the dungeon I receive no dragon bones from any of the dragons which all say they will always from dragon bones.

**To Reproduce**
1. Go to 'Combat'
2. Click on 'Dragon Den dungeon'
4. See error 'After killing any of the 9 dragons receive no dragon bones for any of the kills'

**Expected behavior**
A clear and concise description of what you expected to happen. Receive the proper number of Dragon bones per kill of each dragon or at the very least all the bones at the end of the dungeon run, 9/9 dragons killed.

**Screenshots**
![MelvorSS1](https://user-images.githubusercontent.com/93456640/139563985-6aaa0e7e-eb4a-482f-a71b-fa0099622009.png)
![image](https://user-images.githubusercontent.com/93456640/139564155-557a719a-a0fc-457b-9292-94fd1d4b5b33.png)
![image](https://user-images.githubusercontent.com/93456640/139564045-7004a15d-d0fc-48fa-bb06-74d0c3b113de.png)
![image](https://user-images.githubusercontent.com/93456640/139564111-f7e54a56-5a68-493a-852c-a08d0cfab85a.png)

**Browser**
Please tell us what browser you are using and what version. Version 1.31.88 Chromium: 95.0.4638.69 (Official Build) (64-bit) Brave browser.

**Console output**
Please open the console by pressing F12 and copy it here.
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
style.css:1 Failed to load resource: the server responded with a status of 404 ()
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
cloud.js?1209:65 Connected to PlayFab successfully
cloud.js?1209:66 PlayFab Connected: RyanFirrow
save.js?1209:54 set force reload to 0
combatManager.js?1209:1 Combat Manager Built...
raidManager.js?1209:1 Golbin Raid Manager Built...
save.js?1209:14 Loading Save Game...
save.js?1209:14 Save Game Loaded...
main.js?1209:5 Game Loaded
game.js?1209:27 Took 0.18890000000037252s to process 89409 ticks. 0.0021127626972717796ms per tick.
cloud.js?1209:7 Synchronising with Cloud
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
cloud.js?1209:65 Connected to PlayFab successfully
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
cloud.js?1209:66 PlayFab Connected: RyanFirrow
style.css:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred
None

**Comment by coolrox95** [comment]
It is intended that dungeon monsters do not drop bones/items. However it is not intended that the monster drops button shows that they do.

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
