### ISSUE TITLE
Excessive CPU and GPU usage when any progress bar is on screen

### ISSUE THREAD

**Issue by Tyriar** [MelvorIdle/melvoridle.github.io#1539]
Follow up from https://github.com/MelvorIdle/melvoridle.github.io/issues/1087 as it wasn't reopened.

When settings screen is open:

![image](https://user-images.githubusercontent.com/2193314/139588910-425b0188-8f17-4bf0-9d37-6440b5256c51.png)

When cooking is open (1 active and one passive progress bar):

![image](https://user-images.githubusercontent.com/2193314/139588921-c42e4bcc-6e07-4988-90bb-6becf70a03ce.png)

The worst is the GPU process and the second worst is the renderer.

It seems I can only disable progress bars in combat but I want to disable them everywhere. My experience working on VS Code (built on Chromium/Electron) is that any css animation in a web context is going to cause a silly amount of CPU and GPU activity, please provide an option to just disable any animation that causes updates every frame. This would make it possible for me to run Melvor in the background while I'm doing other things.

For a proper fix you could look into using a webgl canvas and simple shaders to render the progress bars.

FWIW my hardware is i5-4670K + RTX 2070 Super.

**Comment by Tyriar** [comment]
Something else worth looking into is whether you're causing layout thrashing and/or are laying out more of the page than you expect. You can investigate this via Chromium's devtools.

**Comment by oorzkws** [comment]
I was wondering why this was happening, I appreciate your informative issue. If you play in-browser, this is a userscript that will solve most of the usage at the cost of losing animations/toasts.

https://gist.github.com/oorzkws/17f0a593fecb4bfea73299bd10187f6c

**Comment by Tyriar** [comment]
I'm using the steam version and I don't think I can access devtools, if I could do a similar tweak when I wanted to keep it open.

**Comment by oorzkws** [comment]
> 
> 
> I'm using the steam version and I don't think I can access devtools, if I could do a similar tweak when I wanted to keep it open.

It's also worth noting that the regular web version goes "offline" if the window loses focus, so you don't have anims and whatnot running (but you have to mind the 12h timer), while the steam version ignores focus loss and keeps animating and whatnot.

**Comment by MelvorIdle** [comment]
Do you see any improvement now on this from the Beta update?

**Comment by Tyriar** [comment]
Nope:

![image](https://user-images.githubusercontent.com/2193314/141476420-9bca2255-b00e-4078-bbdb-18d1ce2c371e.png)

**Comment by Quickb-Bob** [comment]
Can confirm have the same issue. The GPU-process is hogging my CPU as well. And it doesn't properly close after exiting Melvor
![Melvor](https://user-images.githubusercontent.com/94255160/143768907-fb28ecbb-62ed-4888-bdf3-b3a320196a8b.PNG)
.

**Comment by cybbro** [comment]
I am also experiencing high CPU usage in this game, especially now, when we have these heat waves CPU isn't liking it at all.

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
