### ISSUE TITLE
Load screen

### ISSUE THREAD

**Issue by rekwah** [MelvorIdle/melvoridle.github.io#154]
got an error message on Microsoft edge when trying to load in. Hit fix my save and just went back to error message. Tried two or three times and still nothing. Can not log in or anything via the cloud drop down. 
![E90D30A6-63F8-4075-BF59-01C9FCAAA882](https://user-images.githubusercontent.com/62727659/77705903-8079fb00-6f86-11ea-9864-66e3b3d37668.jpeg)

**Comment by rekwah** [comment]
CSP14304: Unknown source ''strict-dynamic'' for directive 'script-src' in Content-Security-Policy-Report-Only - source will be ignored.

CSP14317: Ignoring 'unsafe-inline' for directive 'script-src' in Content-Security-Policy-Report-Only because nonce or hash value is specified.

CSP14304: Unknown source ''strict-dynamic'' for directive 'script-src' in Content-Security-Policy-Report-Only - source will be ignored.

CSP14317: Ignoring 'unsafe-inline' for directive 'script-src' in Content-Security-Policy-Report-Only because nonce or hash value is specified.

CSP14304: Unknown source ''strict-dynamic'' for directive 'script-src' in Content-Security-Policy-Report-Only - source will be ignored.

CSP14317: Ignoring 'unsafe-inline' for directive 'script-src' in Content-Security-Policy-Report-Only because nonce or hash value is specified.

CSP14304: Unknown source ''strict-dynamic'' for directive 'script-src' in Content-Security-Policy-Report-Only - source will be ignored.

CSP14317: Ignoring 'unsafe-inline' for directive 'script-src' in Content-Security-Policy-Report-Only because nonce or hash value is specified.

Attempting to fix your save... wish me luck

Save fix completed... refreshing...

HTML1300: Navigation occurred.
melvoridle.com (1,1)

HTML1504: Unexpected end tag.
melvoridle.com (55,5)

HTML1523: Overlapping end tag. Tags should be structured like "<b><i></i></b>" instead of "<b><i></b></i>".
melvoridle.com (127,8)

HTML1423: Malformed start tag. Attributes should be separated by whitespace.
melvoridle.com (1013,52)

HTML1523: Overlapping end tag. Tags should be structured like "<b><i></i></b>" instead of "<b><i></b></i>".
melvoridle.com (1288,124)

HTML1512: Unmatched end tag.
melvoridle.com (1288,132)

Loading Save Game...

Save Game Loaded...

Loading Save Game...

Save Game Loaded...

Loading Smithing...

Updating Masteries

Loading Masteries...

TypeError: Unable to get property 'equipment' of undefined or null reference

HTML1300: Navigation occurred.
cloud (1,1)

HTML1407: Invalid tag name. First character should match [a-zA-Z].
cloud (106,76)

HTML1512: Unmatched end tag.
cloud (176,82)

3HTML1508: Unmatched end tag.
cloud (177,25)

Loading Save Game...

2HTML1300: Navigation occurred.
cloud (1,1)

HTML1504: Unexpected end tag.
index.php (55,5)

HTML1523: Overlapping end tag. Tags should be structured like "<b><i></i></b>" instead of "<b><i></b></i>".
index.php (127,8)

HTML1423: Malformed start tag. Attributes should be separated by whitespace.
index.php (1013,52)

HTML1523: Overlapping end tag. Tags should be structured like "<b><i></i></b>" instead of "<b><i></b></i>".
index.php (1288,124)

HTML1512: Unmatched end tag.
index.php (1288,132)

Loading Save Game...

Save Game Loaded...

Loading Save Game...

Save Game Loaded...

Loading Smithing...

Updating Masteries

Loading Masteries...

TypeError: Unable to get property 'equipment' of undefined or null reference

Attempting to fix your save... wish me luck

Save fix completed... refreshing...

HTML1300: Navigation occurred.
index.php (1,1)

HTML1504: Unexpected end tag.
index.php (55,5)

HTML1523: Overlapping end tag. Tags should be structured like "<b><i></i></b>" instead of "<b><i></b></i>".
index.php (127,8)

HTML1423: Malformed start tag. Attributes should be separated by whitespace.
index.php (1013,52)

HTML1523: Overlapping end tag. Tags should be structured like "<b><i></i></b>" instead of "<b><i></b></i>".
index.php (1288,124)

HTML1512: Unmatched end tag.
index.php (1288,132)

Loading Save Game...

Save Game Loaded...

Loading Save Game...

Save Game Loaded...

Loading Smithing...

Updating Masteries

Loading Masteries...

TypeError: Unable to get property 'equipment' of undefined or null reference

2DOM7009: Unable to decode image at URL: 'https://googleads4.g.doubleclick.net/pcs/view?xai=AKAOjsuDTrMuw604Hp4wyg1YT8lq4F4y9CsVOjRK1oaH4vPD8Q6JABKiJFsqec9pGVfA-4RGFzQ5C82tnRCvpJ2aT8xYE-nkTzWJ8Uch04ZBAoUWosH2sXONTAxjnoOe1sJj-Lui32oujkc_gYyXBobV8L5TxSYkTJPgBQa21V4p7UK0dpql_xozApucUlG4Vlisc4wyLRvfDPVM4sc3PAqFrjrTo__C9S8ufR0WuAW_fvpNC3cNahxbOBAOMd1mq3-HNXFerdoA_xq6FeAueR4TTeCayviO6kQ9DJfBR9buDAcJMBF66l7KT3YUkN0mARt3-ShKTAWJtQz4CKIzX8FfyIfDfR0PiKlubUia2LWUOGBULiS4on_VOMwVFcePbc3dOIqlByTBUzBTc-J6P3VtSaV-RYE0-djNlwShz1MZAKdriSX2x100GHPofv-9PNdiNQ252TyifM-U-0MxcABJDvbzul-gpYjmTzeOvjgx46Ldd9spxiW0ZOZC375vPNIhErVD7lw7byczNNaT3dPHP3-HmEowsGuZ4h5JqWRm-zR4Vib_QdMyhvSsr7gaCmzsaiMfZ8EgkbGixjvtniraX_vb--41dtqgWZ_hedCAoCfOQXpuWkAJjJNmPolEu2TPlpcEOGJ_8kqUmqQyMk95LzCPuH11T5gtEA0Vc_AUhghrOEuEfUSg2RSeS8RVmdD-Plz6PsuIDhPQeJS_-3aD825Txnv_JE-XvK1rYJXtd5NHRfmrw6MebLmuVNGHJEVHcUk9CEZrIxIf9xgBZV6_riFhePoJ2Svv1eK_b_TrtJ4EIkEIgrqbGj7FysSORkFVN9ESBq20AJaSxiaGLLuOwHGd-Z01zoT1Y7BMtFA7JoHKGMJBZOplrek8a93Er67M1pomTvlS0PoAJF-9EAzx6yJfJcgHItuXk-pqJ9N67o

**Comment by MelvorIdle** [comment]
On the browser, in console (Press F12) can you please type "downloadSave();" and send me the file?

**Comment by rekwah** [comment]
function downloadSave() { //saveData(); let toSave = {}; for (let i = 0; i < allVars.length; i++) { toSave[allVars[i]] = getItem(key + allVars[i]); } let saved = JSON.stringify(toSave); let exportSaved = btoa(saved); var file = new Blob([exportSaved], { type: 'text/plain' }); if (window.navigator.msSaveOrOpenBlob // IE10+ ) window.navigator.msSaveOrOpenBlob(file, 'melvoridlesave.txt'); else { // Others var a = document.createElement('a'), url = URL.createObjectURL(file); a.href = url; a.download = 'melvoridlesave.txt'; document.body.appendChild(a); a.click(); setTimeout(function() { document.body.removeChild(a); window.URL.revokeObjectURL(url); }, 0); } }:

**Comment by MelvorIdle** [comment]
You need to add the ";" to the end of downloadSave()

It will give you a file

**Comment by rekwah** [comment]
> You need to add the ";" to the end of downloadSave()
> 
> It will give you a file

It says undefined when i do

**Comment by rekwah** [comment]
I see now! one second!

**Comment by rekwah** [comment]
[melvoridlesave (3).txt](https://github.com/MelvorIdle/melvoridle.github.io/files/4390963/melvoridlesave.3.txt)


sorry, the half window due to the F12 threw me off and I didnt see it

**Comment by MelvorIdle** [comment]
Can you please refresh the game and use the Fix my Save button again and let me know if it works.

**Comment by rekwah** [comment]
> Can you please refresh the game and use the Fix my Save button again and let me know if it works.

It worked!! Thank you sooooo much!! <3

**Comment by MelvorIdle** [comment]
No worries :)
