### ISSUE TITLE
Mining glove charged, but no glove?

### ISSUE THREAD

**Issue by jpdeveau** [MelvorIdle/melvoridle.github.io#1541]
When I buy mining gloves I get the number of charges correctly, even though it says owned I never actually receive gloves to wear.

To reproduce buy a mining glove from the shop. Please note I don't currently have any.

I don't know how to put the console output here in Android.

**Comment by coolrox95** [comment]
Duplicate of #1332

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
