### ISSUE TITLE
[Bug]: Cannot mine runite 

### ISSUE THREAD

**Issue by Aking92** [MelvorIdle/melvoridle.github.io#1545]
### Describe the bug

The runite ore rock depleted and I changed to mine dragonite ore. I now cannot select runite because it is depleted and so cannot mine it.

### Reproduction Steps

Step 1: mine runite until the rock is depleted 
Step 2: switch to dragonite ore before runite respawns.
Step 3: select runite (it doesn’t respawn)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.21

### Game Subversion

?1209

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
