### ISSUE TITLE
[Bug]: AFK Fishing giving wrong exp

### ISSUE THREAD

**Issue by Zorukai** [MelvorIdle/melvoridle.github.io#1546]
### Describe the bug

Not getting full exp from catching sharks while offline. I can swap screens and catch 1 shark and get 150 exp, but everything past catching 1 starts to reduce exp for each

### Expected behaviour

Expect toget 150 experience shark caught

### Screenshots

![Screenshot_20211101-162327_Melvor Idle](https://user-images.githubusercontent.com/93553639/139744285-6f988afc-60ac-4821-b540-d3ee8a2f71ce.jpg)
![Screenshot_20211101-162342_Melvor Idle](https://user-images.githubusercontent.com/93553639/139744298-8b95360f-fc49-47a7-9be0-97ddce523e7f.jpg)
![Screenshot_20211101-162301_Melvor Idle](https://user-images.githubusercontent.com/93553639/139744301-b34c912a-c326-4b42-b1a6-44d7a912f61e.jpg)
![Screenshot_20211101-160329_Melvor Idle](https://user-images.githubusercontent.com/93553639/139744304-01ddb006-10b3-432f-890f-df4379fe000e.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.21

### Game Subversion

?1209

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is due to item doubling.

There is a chance to catch more than 1 Fish. However, you only gain XP equal to 1 catch. This mechanic is the same throughout the game.
