### ISSUE TITLE
[Bug]: Skill Level Over 99

### ISSUE THREAD

**Issue by echiro-oda-fan** [MelvorIdle/melvoridle.github.io#1547]
### Describe the bug

I logged in after afk mining to find my Mining skill level at 100. The level persists across versions, so it isn't a glitch with just pc or mobile. Experiencing this on Alpha V0.22.1 (?1209)

### Reproduction Steps

Not sure how to reproduce, I had been at 99 for a while and had the mining cape equipped while afk mining for runite.

### Expected behaviour

I expected the level to not go up past the max,

### Screenshots

![Melvor Idle 11_1_2021 8_42_21 PM](https://user-images.githubusercontent.com/17309290/139783575-25a59e39-8246-4142-9681-61c577c726fd.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.21

### Game Subversion

?1209

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is due to having Virtual Levels enabled in the Settings menu.

You can disable this setting if you wish to only view Level 99
