### ISSUE TITLE
[Bug]: <title> lost my premium 

### ISSUE THREAD

**Issue by Horace420** [MelvorIdle/melvoridle.github.io#1548]
### Describe the bug

My premium account dissapeared so I bought it again because I love the game and was currently working on my herblore and farming refund me please

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.21

### Game Subversion

?1109

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Can you please provide the email address the purchase was made on? I will process this for you.

**Comment by Horace420** [comment]
***@***.*** is the email adress used

**Comment by MelvorIdle** [comment]
Unfortunately the provided email address has been censored. Please resend

**Comment by Horace420** [comment]
That's weird.  It's this email I'm using now but its ***@***.***
