### ISSUE TITLE
[Bug]: Can't return to game if you select 'Report a Bug' on iOS app

### ISSUE THREAD

**Issue by zants** [MelvorIdle/melvoridle.github.io#1550]
### Describe the bug

This one's a bit ironic, haha.

When you select 'Report a Bug' in the iOS app, it opens this GitHub page within the app; however, iOS doesn't have a back button built into the OS' GUI, so unless there's one on the screen you can't return to the game without just closing the whole app (usually, with apps that have a browser built into them for features like this, you could scroll down and then scroll up to reveal a title bar with a back/X button, but this doesn't happen for this app).  Another behavior sometimes built-in is to be able to swipe right from the left side of the screen to cause a back action, but that doesn't do anything in the app either.  Ultimately, you can't leave GitHub once you select 'Report a Bug' and you have to just close the whole Melvor Idle app.

Also, this is probably important...
The selection on this GitHub issue page only lets me select "Alpha v0.21" for "Which version of the game are you experiencing this bug on?", but I'm actually on v0.22.1

### Reproduction Steps

1. Open Melvor Idle on iOS
2. Select hamburger menu
3. At the bottom, select 'Report a Bug'
4. GitHub opens in the app's built-in browser
5. Attempt exiting GitHub by making title bar of app appear, won't appear despite any behavior
6. Attempt exiting GitHub by swiping right from left side of screen, doesn't perform any action
7. Forced to close app and re-open it to return to game.

### Expected behaviour

A method of closing the browser and exiting GitHub to return to the game.

### Screenshots

![C0705C54-A637-4135-81EA-CBFCF18BAB46](https://user-images.githubusercontent.com/822329/139899619-bf25fea0-ee9e-410a-ad32-eeb65f409f93.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.21

### Game Subversion

?1209

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
I believe this is now hotfixed
