### ISSUE TITLE
[Suggestion]: Disable the "8" hotkey while a text field is selected

### ISSUE THREAD

**Issue by IsaacGraham** [MelvorIdle/melvoridle.github.io#1552]
### What is your suggestion?

When I'm buying specific quantities of things I often end up hitting the 8 key, spawning a useless flavour item. Usually not much of a hassle but on occasion I need to buy the item when I only have one bank slot left, and this makes me have to resort to buying, for example, 4 shards twice.

It's a minor inconvenience but it is something that detracts from the game imo.

### Why are you suggesting this?

This happens frequently enough to be annoying.

### How does your suggestion benefit the game?

Removes some avoidable tedium.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
