### ISSUE TITLE
[Bug]: Offline combat with food swap does not show food consumed

### ISSUE THREAD

**Issue by mattrunyon** [MelvorIdle/melvoridle.github.io#1553]
### Describe the bug

When doing offline combat, if the food source switches from the auto-switch upgrade, the progress report when returning does not show food consumed from either food source. If there is no swap in food source, the progress report shows food consumed

### Reproduction Steps

1. Equip 1 shark and 1000 whales
2. Enable auto food switching
3. Enable shark as the active food
4. Start combat where food will be needed and go offline
5. Return after food should be consumed

### Expected behaviour

The progress report shows `-1 shark` and `-x whale`

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.21

### Game Subversion

1209

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
