### ISSUE TITLE
[Bug]: Afk Fishing extremely reduced rate

### ISSUE THREAD

**Issue by madeanaccountforthisshit** [MelvorIdle/melvoridle.github.io#1555]
### Describe the bug

AFKing with my character set to fishing only to return to a fraction of the fish that should have been caught. Have 99 fishing and only receiving 2k whales over the course of 10 hours is whack. Yesterday I returned to only 700... It seems when I afk Melvor either stops working or it keeps going but at a significantly reduced rate. Only noticed it when fishing so far.

Per screenshot attached - I should catch a whale every 11.25s max. We can round that to 12 seconds for simplicity. I catch at least 2 with 99 fishing and cape. 60s/12s = 5. 5x2=10 fish per minute. 60x10=600 fish per hour. My work day is over 8 hours, so I should expect to see 600*8=4800 fish at an absolute minimum. The afk functionality is busted somewhere.

### Reproduction Steps

Set character to fish.
Leave pc for 8 hours.

### Expected behaviour

8 hours worth of fish in inventory.

### Screenshots

![image](https://user-images.githubusercontent.com/93624311/139961928-e8a8acd4-b3db-4f42-89fd-8172f433d9a4.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.21

### Game Subversion

?1209

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Hey! Would you be able to confirm that you have enough bank space when returning from offline?

If your bank gets filled, the actions will stop.

**Comment by madeanaccountforthisshit** [comment]
Hello, just ran into this issue again today. I can confirm 100% it is not due to bank space. Today I left it fishing whales from 710AM - now, about 520PM and I had 2200 whales. It seems like when I logged back into my PC and clicked on Melvor my character starting fishing again. I am also on v1.0 now (not sure if you can play without updating but figured I'd clarify).
