### ISSUE TITLE
[Bug]: <Game crash, unknown reason>

### ISSUE THREAD

**Issue by TehDanny** [MelvorIdle/melvoridle.github.io#1556]
### Describe the bug

I had two browser windows running with two different characters, both with SEMI running. In one, which is a normal character, I was switching from combat to crafting Adamantite Arrowtips. The other, an adventure character, I was about to die against a Steel Knight - the first death of the playthrough. I noticed something was wrong when I couldn't craft the arrowtips and my adventure character recieved a pop-up error message. I don't know how to replicate it, and I don't know how to properly fill this bug report, because I'm not really sure what happened and how it affected both characters.

An error occured while processing ticks:
Active Skill: COMBAT
Error Name: QuotaExceededError
Error Message: The quota has been exceeded.
Stack Trace:
saveData@https://melvoridle.com/assets/js/game/save.js?1209:8:379
clearOffline@https://melvoridle.com/assets/js/game/main.js?1209:258:131
stopCombat@https://melvoridle.com/assets/js/built/combatManager.js?1209:57:13
checkDeath@https://melvoridle.com/assets/js/built/baseManager.js?1209:14:21
tick@https://melvoridle.com/assets/js/built/baseManager.js?1209:8:67
tick@https://melvoridle.com/assets/js/built/combatManager.js?1209:9:37
tick@https://melvoridle.com/assets/js/built/game.js?1209:30:13
runTicks@https://melvoridle.com/assets/js/built/game.js?1209:26:96
processTime@https://melvoridle.com/assets/js/built/game.js?1209:25:6
loop@https://melvoridle.com/assets/js/built/game.js?1209:39:49

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.21

### Game Subversion

?1209

### Are you using any scripts or extensions?

Yes

**Comment by coolrox95** [comment]
Closing this issue as the root problem is issue #1562
