### ISSUE TITLE
[Bug]: receiving too many logs whilst woodcutting

### ISSUE THREAD

**Issue by TheHcOmega** [MelvorIdle/melvoridle.github.io#1557]
### Describe the bug

Whilst woodcutting in an online state I can sometimes receive +5 logs in a single action. The trees I receive additional logs per action are regular and oaks (+5 logs) and yews (+3 logs).

### Reproduction Steps

I have the maximum amount of multiplier % (from master pool & axe) + pet + double trees.
Start woodcutting double trees.
Select regular, oak or yew trees as one of the two types being cut.
Leave in an online state.

### Expected behaviour

To occasionally receive two logs per action

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.21

### Game Subversion

?1209

### Are you using any scripts or extensions?

No

**Comment by TheHcOmega** [comment]
Opened a second bug report of further discoveries following on from this

**Comment by Deadsaint66** [comment]
if I'm not mistaken, when you use multi-tree to cut, that game uses the highest level tree's "time to cut". so for instance if you cut a magic tree (10 seconds for me) and a regular tree (1.5 seconds for me) you will get ~1-2 magic logs per cycle and ~5-10 regular logs. as far as I'm aware this is intended.

**Comment by MelvorIdle** [comment]
Above comment is correct, this is not a bug as it is the intended mechanic.
