### ISSUE TITLE
[Spelling/Grammar]: Diamond luck potion in herblore milestones

### ISSUE THREAD

**Issue by mattrunyon** [MelvorIdle/melvoridle.github.io#1558]
### What text is wrong?

In the herblore milestones (from completion log or icon on the herblore skill page), Diamond Luck Potion is simply called Diamond Potion. The "Luck" is missing

![image](https://user-images.githubusercontent.com/8619789/140177142-7a0e8333-912d-4f75-b8ba-69ccb8344d13.png)

### What is the correct spelling or grammar?

Diamond Luck Potion

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
