### ISSUE TITLE
[Bug]: able to increase the base log value

### ISSUE THREAD

**Issue by TheHcOmega** [MelvorIdle/melvoridle.github.io#1559]
### Describe the bug

Able to increase the base amount of logs received per action upto +6 for regular, +5 for oak, +4 for willow, +3 for teak and so on.

I would also occasionally receive an additional log as well as the double logs when that triggers. I dont know why this is happening though. To explain it further, I would receive 13 regular logs in one action (a base value of +6, doubled +1) or 11 oak logs (a base value of +5, doubled +1) etc.

Keeps this multiplier whilst in an offline state as well.

### Reproduction Steps

1. Unlock double trees
2. Cut magic trees (current tree level is 98, im noting this because I reached a higher base log the higher the initial trees level)
3. Cut maples
4. Unselect maples
5. Cut teaks
6. Unselect teaks
7. Cut willows
8. Unselect willows
9. Cut oaks
10. Unselect oaks
11. Cut regular

### Expected behaviour

For the base amount of logs received to stay at +1.

### Screenshots

![Screenshot_20211103-195219_9737de6f3e36012ce6703231c8d3c3a2](https://user-images.githubusercontent.com/93677537/140186596-abac9a2e-2fd0-411a-9196-15eb158c9e3b.jpg)
![Screenshot_20211103-193548_9737de6f3e36012ce6703231c8d3c3a2](https://user-images.githubusercontent.com/93677537/140186638-003bfbb8-a5d5-463e-8f81-addaeabb20e5.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.21

### Game Subversion

?1209

### Are you using any scripts or extensions?

No

**Comment by sbabudro** [comment]
It isn't a bug.

The way the production rate works is that it takes the time per log and divides it into the longest cut time.

So for the Magic trees, they take 10s to cut. That's 6.66x longer than regular trees at 1.5s. So for every Magic tree you cut, you could have cut 6 regular trees. So you get 6 logs. When it gets doubled, you actually get 13, since 6.66 x2 = 13.33.
