### ISSUE TITLE
Hard Leather Recipes Missing from Milestones List

### ISSUE THREAD

**Issue by zedekblue** [MelvorIdle/melvoridle.github.io#156]
Foregoing this whole template because it's just regarding missing info. The crafting milestones jump directly from 25 (gold ruby necklace) to 50 (silver emerald ring) and are missing all the hard leather recipes.
![Capture](https://user-images.githubusercontent.com/17040113/77843130-3300b800-7157-11ea-8046-d3db3196a2a5.PNG)

**Browser**
Firefox 74.0 (64-bit)

**Comment by MelvorIdle** [comment]
Fixed in upcoming minor update
