### ISSUE TITLE
I'm getting an iOS error

### ISSUE THREAD

**Issue by steve9300** [MelvorIdle/melvoridle.github.io#1560]
### Describe the bug

![160bc57ddca45d82984ac29a973e887d](https://user-images.githubusercontent.com/30030276/140224080-a2f7f7a3-458d-46ed-8096-1b4f7ebf3fc4.png)

I keep getting this error and dont know what to do

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.21

### Game Subversion

?1209

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Can you please confirm if this bug is still occurring now?

**Comment by steve9300** [comment]
No its all good now, thank you!
