### ISSUE TITLE
[Bug]: Game saving failing in Firefox due to localstorage Quota Exceeded error

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#1562]
### Describe the bug

This issue is to pool together all related issues due to Firefox failing to save games.
Cause is currently unknown, however many have reported that the issue occurs when having multiple instances of the game open in Firefox.

### Reproduction Steps
Possible reproduction steps:
1. Open Melvor in one Firefox window and load a save
2. Open Melvor in another Firefox window and load a different save
3. After some time period the first instance of Melvor will error out on calls to saveData(). The second instance of Melvor however is still able to save the game.

### Console output

Typical console output is an error with a variant of the message:
DOMException: The quota has been exceeded.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.22.1

### Game Subversion

?1209

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
