### ISSUE TITLE
[Bug]: Active Cooking Chicken Soup rewards no items

### ISSUE THREAD

**Issue by Zidane3838** [MelvorIdle/melvoridle.github.io#1563]
### Describe the bug

https://user-images.githubusercontent.com/1594255/140318842-c5acc30d-7c4b-462e-a8b7-2c707dd11a20.mp4

offline seems to work fine & stared chicken soup also fine

### Reproduction Steps

cook chicken soup, receive no chicken soup

### Expected behaviour

cook chicken soup, receive chicken soup

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.22.1

### Game Subversion

?1214

### Are you using any scripts or extensions?

No

**Comment by Zidane3838** [comment]
Found the soup... it was auto equipping... You can close this if that's intended behavior.

**Comment by coolrox95** [comment]
If you've purchased the automatically equip food upgrade, yes this is intended. You can toggle this setting on the cooking page.
![image](https://user-images.githubusercontent.com/58208131/140581519-917a47c2-af27-4427-9e55-1f79f58b1d51.png)
