### ISSUE TITLE
[Spelling/Grammar]: Herblore Mastery Tokens

### ISSUE THREAD

**Issue by Sabrsabrsabr** [MelvorIdle/melvoridle.github.io#1566]
### What text is wrong?

![E6C04FA2-9F64-4B4A-B911-461B9E3F3DB7](https://user-images.githubusercontent.com/93741416/140425660-5fa143e6-a455-45f1-8e92-f40af81b3194.jpeg)

herblore mastery tokens say 1% instead of 0.1%

### What is the correct spelling or grammar?

0.1%

**Comment by MelvorIdle** [comment]
This is now fixed
