### ISSUE TITLE
[Suggestion]: Aorpheat's Signet Ring +100% gp in more skills

### ISSUE THREAD

**Issue by SustainableBlueDuck** [MelvorIdle/melvoridle.github.io#1567]
### What is your suggestion?

This might be a bug instead of a suggestion.

The item description of the ring says "When equipped +100% GP granted from all sources except Alt. Magic and Item Sales...", However gp earned by e.g. firemaking and agility are not doubled, these should be included right?

### Why are you suggesting this?

Would make the description true, since both tasks don't seem to be 'item selling'.

### How does your suggestion benefit the game?

Description is true where expected.

**Comment by TehDanny** [comment]
Jeweled Necklace and Fine Coinpurse doesn't seem to increase gold from Agility either.

**Comment by SustainableBlueDuck** [comment]
> Jeweled Necklace and Fine Coinpurse doesn't seem to increase gold from Agility either. And Book of Scholars doesn't decrease gold.

Please verify by checking the coin drop amount when you have the item equipped.

**Comment by TehDanny** [comment]
Was there just an update? Because It doesn't seem to be the case anymore, they seem to work now, I'm a bit confused 😄

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
