### ISSUE TITLE
[Bug]: Passive cook wouldnt start

### ISSUE THREAD

**Issue by CompPsy** [MelvorIdle/melvoridle.github.io#1568]
### Describe the bug

I was in cooking, active cooking 'Strawberry Cupcakes'. I attempted to start passive cooking 'Basic Soup' but it wouldn't start. 
I tried clicking on passive cook a few times, pausing between each attempt. 
Finally I tried active cooking the 'Basic Soup', which worked. Then I started active cooking 'Strawberry Cupcakes', and then was able to start passive cooking 'Basic Soup' 
I believe I was level 73 at the time, in case it's a level specific bug. 
I have the top level furnace and pot for cooking.
Not sure if reproducible, wanted to document before I forgot anything.

### Reproduction Steps

1. Go to cooking
2. Start active cooking 'Strawberry Cupcakes '
3. Go to 'Magic Pot' to select the recipe for 'Basic Soup'
4. Attempt to passive cook 'Basic Soup'

### Expected behaviour

I expected to be able to passive cook 'Basic Soup' while active cooking 'Strawberry Cupcakes'

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.22.1

### Game Subversion

?1215

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Passive cooking can only being if you are actively cooking something else. You cannot passive cook without Actively cooking.

**Comment by CompPsy** [comment]
I'm aware, as I stated in the first line of my description I was actively
cooking Strawberry Cupcakes, I attempted to passively cook the 'Basic Soup'
and it wouldn't start.

**Comment by CompPsy** [comment]
Could someone explain why this was closed? I clearly stated in the first line of the bug description that this occurred while I was actively cooking Strawberry Cupcakes, and was unable to start passively cooking something else at that time.
