### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by wilhil** [MelvorIdle/melvoridle.github.io#1569]
### Describe the bug

Toggling reuse potion in combat shows woodcutting sidebar on the right.

### Reproduction Steps

Go to combat
Click potions
Toggle potion reuse

### Expected behaviour

Nothing on the right

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.22.1

### Game Subversion

1215

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Do you have screenshots showing what you mean by this?
