### ISSUE TITLE
[Bug]: Graphic issues with nvidia gpu

### ISSUE THREAD

**Issue by Adam3011** [MelvorIdle/melvoridle.github.io#1570]
### Describe the bug

(Steam version)

When using a dedicated nvidia gpu (mine is an rtx 2070 max Q) I often get graphical issues when starting the game or after it has been in the background for a while. This only resolves itself by switching to another tab in-game.

Graphic drivers are updated to the latest version.

### Screenshots

![Untitled](https://user-images.githubusercontent.com/44881280/140560486-23f775e3-996c-4950-a3f9-7ed5df2c3680.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.22.1

### Game Subversion

?1215

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
I don't believe this is an issue I can fix on my end. This looks like an issue with your GPU. Please ensure drivers are updated and perform a clean installation of drivers.
