### ISSUE TITLE
Premium upgrade button not launching store[Bug]: <title>

### ISSUE THREAD

**Issue by Alfiethecat99** [MelvorIdle/melvoridle.github.io#1571]
### Describe the bug

When trying to upgrade to premium on android using the upgrade button or after selecting any skill which requires premium - the store doesn't open.
It makes me nervous going to the store separately without the link from the app and its delaying my purchase of premium.
I am on the latest app version as per the message that pops up.
I am sure if I purchase through the store separately all will be fine but I worry that my account won't migrate to premium... I suspect other users might also think the same and thus avoid the purchase.

Thanks! 

### Reproduction Steps

1. Open melvor idle on android free version
2. Login 
2. Click the upgrade button or select any premium skill
3. Click through the warning message
4. Store doesn't open 

### Expected behaviour

Should redirect to store

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.22.1

### Game Subversion

Na

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
The button in game should display an inapp purchase popup, and not take you to the store; Can you confirm this is the case?

**Comment by Alfiethecat99** [comment]
That is correct.
It started functioning yesterday and I have since upgraded to premium however.
Thanks,
George

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
