### ISSUE TITLE
[Bug]: Aorpheat's Signet Ring does not appear to double gold from Thieving

### ISSUE THREAD

**Issue by fradigit** [MelvorIdle/melvoridle.github.io#1572]
### Describe the bug

I am currently training Thieving against the Woman, and while the gold drops vary significantly they do not appear to be noticeably different when having the signet ring equipped.  Currently have 50% mastery checkpoint, 90 mastery on Woman, Max Skillcape, Gloves of Silence, Snek pet, Jeweled Necklace, Fine Coinpurse, and AROM in the ring slot and Leprechaun+Devil tablets (NO Sneak-Ers). Both with and without the ring the gold drops appear to be around 1200-4100. Perhaps 10-15% lower with the ring unequipped, but it says doubles gold from all sources so I would expect to see up to 5-6k gold drops at least with it equipped. Equipping it in passive or ring slot did not appear to make a difference. 

### Reproduction Steps

See summary above. 

### Expected behaviour

I would expect gold drops to be noticeably higher with the signet ring equipped in either the ring slot or passive slot.  

### Screenshots

![image](https://user-images.githubusercontent.com/76832865/140601007-1efafa3a-ded8-4aad-b748-c12a3e2ae924.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.22.1

### Game Subversion

?1215

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
The Signet Ring does not "double" GP, it provides +100% GP. This means if you already have +200% GP gain from Thieving, equipping the signet ring will make this +300% (a 50% increase)
