### ISSUE TITLE
[Suggestion]: Add Alt Magic for turning crops back into seeds

### ISSUE THREAD

**Issue by fradigit** [MelvorIdle/melvoridle.github.io#1573]
### What is your suggestion?

Add an Alt Magic spell to turn crops back into seeds

### Why are you suggesting this?

Some seeds are used as recipe ingredients, specifically Strawberry Seeds and Potato Seeds in Herblore. This could make it easier to obtain larger amounts of specific seeds (with some time and effort of growing them first to get the crops, then runes through Alt Magic). 

### How does your suggestion benefit the game?

While there are several ways to obtain seeds (combat drops, thieving, bird nests), these options generally have a chance to drop all seeds. If only a certain type of seed is desired, this leads to wasted time and resources when other seeds drop. I believe this could lower frustration and lead to better optimization strategies, specifically when training Thieving. I don't see any obvious balance issues with this proposal.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
