### ISSUE TITLE
[Suggestion]: Add more decimal places to the 1M number format

### ISSUE THREAD

**Issue by fradigit** [MelvorIdle/melvoridle.github.io#1574]
### What is your suggestion?

Add 1-2 decimal places to the 1M number format to make it more clear how much of an item you have left. 

### Why are you suggesting this?

There are currently two options for number formatting - the specific but ugly 1,000K and the normal-looking but vague 1M. I think changing it to 1.XM or 1.XXM would add enough detail to enjoy the game while still looking correct. This formatting also goes into the billions, so currently I have 1B gold - but how much gold do I really have? There's a potential variance of over 900M gold in that number. 

### How does your suggestion benefit the game?

It allows players to use the nicer looking 1M format without sacrificing detailed information. 

Plus Malcs said he would add it months ago in discord :(
![image](https://user-images.githubusercontent.com/76832865/140601458-b10c39c4-a1d9-44bc-b765-d5b6632a92a7.png)

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
