### ISSUE TITLE
[Bug]: Unable to view entire list whilst firemaking

### ISSUE THREAD

**Issue by TheHcOmega** [MelvorIdle/melvoridle.github.io#1575]
### Describe the bug

The 'select your log' menu opens where all options arent visible.

### Reproduction Steps

Once in possession of one of each kind of log
Scroll to the top of the firemaking skill
Opening the 'select your log' menu
It opens upwards leaving you unable to select logs at the top of the menu.

### Expected behaviour

Open where all options are selectable.

### Screenshots

![Screenshot_20211106-081759_9737de6f3e36012ce6703231c8d3c3a2](https://user-images.githubusercontent.com/93677537/140604019-000f9e9d-0b64-4ed2-9e9f-976c80ea4e5e.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.22.1

### Game Subversion

?1209

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is now fixed
