### ISSUE TITLE
[Bug]: Apple pencil doesn’t work in ipados app

### ISSUE THREAD

**Issue by Holdner** [MelvorIdle/melvoridle.github.io#1576]
### Describe the bug

When i use the apple pencil in the game and i try to select an item in the chest, I can’t select it and i can only drag it.

In general, the use of the stylus in the game is not optimal.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.22.1

### Game Subversion

?1215

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Hotfix applied for this
