### ISSUE TITLE
Rollback

### ISSUE THREAD

**Issue by BiigD** [MelvorIdle/melvoridle.github.io#1579]
### Describe the bug

Pressed backspace on my phone. Phone asks if i wish to close app, I pressed yes after I saved my profile. After pressing back, the app refreshed/reopened to an activity i was doing hours before. This has happened twice in two days now I have lost hours of progress and I also had 20k charges on my gem gloves 4 days ago and they disappeared. Might stop playing now as it's just degrading. 

### Reproduction Steps

Pressing backspace 
Closing app to swap accounts 
App closes and pops up another screen with something I was doing hours before hand.
Sad.

### Expected behaviour

Press backspace 
Close app
No roll back

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.22.1

### Game Subversion

No

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
