### ISSUE TITLE
Game not idling when in another tab during combat. 

### ISSUE THREAD

**Issue by deathbyconfetti** [MelvorIdle/melvoridle.github.io#158]
**Describe the bug**
Hi Malcs, DeathbyConfetti here. When doing combat, if you have it open in Chrome, and click to add a tab to do something else, the game isnt running correctly. I have tested this and detailed steps to reproduce below. I believe the game is acting similarly to Unity type games where they do not like to be Minimized or in another tab and does not progress in time without being the only tab open and not minimized. 

**To Reproduce**
1. Go to Combat, click slayer monster to begin fighting, special skill toggle is on. 
2. Click on + for a new tab, take note of enemy HP and slayer task kills needed. 
3. Wait a period of time, expecting a few kills in the process. I've tested this off and on with varying lengths. Even noting the enemy HP and it does not go down while the tab is not front-facing or minimized.
4. Return to tab, no damage done and no kills. Youll get a hit right when returning to the tab. 

**Expected behavior**
Time progress, damage done, kills decreased on slayer task. This does not happen. 

**Screenshots**

**Browser**
Chrome

**Console output**
7A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.
index.php:1 A cookie associated with a resource at http://pubmatic.com/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.
save.js?250:46 Loading Save Game...
save.js?250:207 Save Game Loaded...
save.js?250:46 Loading Save Game...
save.js?250:207 Save Game Loaded...
smithing2.js?250:189 Loading Smithing...
mastery.js?250:181 Updating Masteries
mastery.js?250:23 Loading Masteries...
main.js?251:1089 Game Loaded
oneui.core.min.js?205:6 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ oneui.core.min.js?205:6
cloud.js?250:46 Melvor Cloud Connection: Success
save.js?250:46 Loading Save Game...
save.js?250:207 Save Game Loaded...
cloud.js?250:151 146161477.42999998
cloud.js?250:152 146161712.42999998
cloud.js?250:154 Loaded Local save
smithing2.js?250:189 Loading Smithing...
mastery.js?250:181 Updating Masteries
mastery.js?250:23 Loading Masteries...
main.js?251:1089 Game Loaded
43cloud.js?250:188

**Comment by Rhaelyx** [comment]
Hey @deathbyconfetti this is not a bug.

Unfortunately this is the way chrome and other browser work. If they would keep every tab active your computer would get real slow (if you'd have many tabs).

The workaround is having melvor idle in a different browser all together. I open 2 instances of chrome to resolve this and make sure that Melvor is on the front in the second.
