### ISSUE TITLE
[Bug]: <slayer areas not rewarding slayer points>

### ISSUE THREAD

**Issue by JohReynolds** [MelvorIdle/melvoridle.github.io#1580]
### Describe the bug

When killing monsters in Slayer Areas, I receive GP and drops, but no Slayer points.   It is game breaking because the only to chase monster drops on the higher Slayer Areas is to have meet the entry requirements, but the entry requirement prices are substantially higher than anyone would want to grind for using Slayer Tasks. 

Slayer Tasks function correctly.  When using this task, the Slayer category in the mini bar turns green showing that slayer point rewards are active.   This is not true for Slayer Areas.   The Slayer category remains grey.  

### Reproduction Steps

1,  Go to Combat
2.  Go to Browse Slayer Areas
3.  Pick any area, and select any monster
4.  Kill monster
5.  Receive GP rewards and Drop rewards, **but** do not receive Slayer point rewards

### Expected behaviour

For killing any monster in the Browse Slayer Areas, I expect to receive GP reward, Drop reward, and Slayer point reward

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.22.1

### Game Subversion

?1215

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
You only receive Slayer Coins from killing monsters from your Slayer task. This is intended behavior.
