### ISSUE TITLE
[Bug]: Slayer task glitch causing entire combat section to break

### ISSUE THREAD

**Issue by deathcraze** [MelvorIdle/melvoridle.github.io#1582]
### Describe the bug

Selected "new Master slayer task" while wearing Climbing Boots. It got stuck on "looking for slayer task" and never found one. Closed down the game and reopened it, the slayer task section was empty, tried to select "new Easy slayer task", it allowed me to do this but didn't load any task either. Now even choosing any regular monster to fight from one of the other sections, it just gets stuck and never loads up the monster, so I am no longer able to do combat on my save.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.22.1

### Game Subversion

? 1209

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
I believe this has been fixed. Please open a new report if you experience this again.
