### ISSUE TITLE
[Bug]: Circlet half dropped from incorrect skill.

### ISSUE THREAD

**Issue by Gnomeball** [MelvorIdle/melvoridle.github.io#1583]
### Describe the bug

Circlet of Rhaelyx dropped from incorrect skill.

Summoning is a production skill, so should drop the jewel, however I've received several circlets and no jewel.

In short the arrays within `function getRhaelyxPiece(skill)` need modifying to list the correct skills, should be a two line change.

### Reproduction Steps

Train summoning for long enough, you get a circlet.

### Expected behaviour

I would normally expect to receive a Jewel, as the wiki says. (either the game, or the wiki, is incorrect)

### Screenshots

https://cdn.discordapp.com/attachments/411277500803710977/906880785531949076/unknown.png

### Console output

Nothing meaningful

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.22.1

### Game Subversion

?1215

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is now fixed
