### ISSUE TITLE
[Suggestion]: Lazy load images

### ISSUE THREAD

**Issue by user8342912** [MelvorIdle/melvoridle.github.io#1584]
### What is your suggestion?

Lazy load images which aren't required on the login / character selection view. 73 images (3.15MB) are loaded the majority of which aren't needed.

### Why are you suggesting this?

Loading the site for the first time or swapping character takes longer than it needs to.

### How does your suggestion benefit the game?

Quick win to improve the user experience.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
