### ISSUE TITLE
[Bug]: Selecting Default Page on Load affects herb seed selection in Farming interface

### ISSUE THREAD

**Issue by gutblender** [MelvorIdle/melvoridle.github.io#1585]
### Describe the bug

[NOTE]  this happened on the Patreon test server. Version is specified below - the drop-down selection is not correct.

See below. This was shown on my first herb plot (and no others) after I selected Astrology as my Default Page on load.
Afterward, selecting another Skill (or the Bank) did not show a change in Default Page on Load, but would show in the same place in the Farming interface.

The selection does appear to work. Going to Select Character and re-entering the game, the correct page is loaded. So it appears it's just a graphical issue not updating the selection where it should, and also showing it where it shouldn't.

![image](https://user-images.githubusercontent.com/43554226/140805641-458ca930-1b11-4f33-a3c1-a746f1815c21.png)

### Reproduction Steps

1. Select an herb to plant in one or more plots, at least the top-leftmost.
2. Select any Skill (or the Bank) as Default Page on Load: See that the selection doesn't update here.
3. Go to Farming > Herbs and see the first plot has the selected icon from Step 2.
4. Force Save > Select Character > re-enter the game as same character, and see that the default page is correctly loaded, that Farming > Herbs looks correct, and that Default Page on Load also looks correct.
5. Rinse and repeat to show that the issue happens this way consistently.

### Expected behaviour

Expected Default Page on Load setting to update with my selection immediately after selection.

### Console output

style.css:1 Failed to load resource: the server responded with a status of 404 ()
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
cloud.js?1218:58 checkTestAccessInit
cloud.js?1218:59 checkTestAccessPatreon
combatManager.js?1218:1 Combat Manager Built...
raidManager.js?1218:1 Golbin Raid Manager Built...
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
save.js?1218:57 set force reload to 0
combatManager.js?1218:1 Combat Manager Built...
raidManager.js?1218:1 Golbin Raid Manager Built...
cloud.js?1218:58 checkTestAccessInit
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
cloud.js?1218:65 Connected to PlayFab successfully
cloud.js?1218:66 PlayFab Connected: gutblender
cloud.js?1218:59 checkTestAccessPatreon
combatManager.js?1218:1 Combat Manager Built...
raidManager.js?1218:1 Golbin Raid Manager Built...
save.js?1218:14 Loading Save Game...
save.js?1218:14 Save Game Loaded...
main.js?1218:8 Game Loaded
MICSR.js:26 MICSR: CombatData is waiting for statNames
MICSR.js:26 MICSR: CombatData is waiting for util
MICSR.js:26 MICSR: setting up Consumables
MICSR.js:26 MICSR: setting up DataExport
MICSR.js:26 MICSR: Card is waiting for util
MICSR.js:26 MICSR: Import is waiting for util
MICSR.js:26 MICSR: setting up SimManager
MICSR.js:26 MICSR: Plotter is waiting for util
MICSR.js:26 MICSR: setting up SimEnemy
MICSR.js:26 MICSR: setting up Loot
MICSR.js:26 MICSR: Simulator is waiting for statNames
MICSR.js:26 MICSR: Simulator is waiting for SimPlayer
MICSR.js:26 MICSR: setting up Menu
MICSR.js:26 MICSR: setting up SimPlayer
MICSR.js:26 MICSR: TabCard is waiting for util
MICSR.js:26 MICSR: TabCard is waiting for Card
MICSR.js:26 MICSR: main is waiting for util
MICSR.js:26 MICSR: main is waiting for App
MICSR.js:26 MICSR: App is waiting for util
MICSR.js:26 MICSR: App is waiting for statNames
MICSR.js:26 MICSR: App is waiting for AgilityCourse
MICSR.js:26 MICSR: App is waiting for Card
MICSR.js:26 MICSR: App is waiting for CombatData
MICSR.js:26 MICSR: App is waiting for Import
MICSR.js:26 MICSR: App is waiting for Plotter
MICSR.js:26 MICSR: App is waiting for modifierNames
MICSR.js:26 MICSR: App is waiting for Simulator
MICSR.js:26 MICSR: App is waiting for TabCard
MICSR.js:26 MICSR: setting up util
MICSR.js:26 MICSR: setting up statNames
MICSR.js:26 MICSR: unknown item property attackSpeed
MICSR.js:26 MICSR: unknown item property isTwoHanded
MICSR.js:26 MICSR: unknown item property specialAttackID
MICSR.js:26 MICSR: unknown item property equipmentSlot
MICSR.js:26 MICSR: unknown item property isPassiveItem
MICSR.js:26 MICSR: unknown item property damageReduction
MICSR.js:26 MICSR: unknown item property defenceBonus
MICSR.js:26 MICSR: unknown item property magicDefenceBonus
MICSR.js:26 MICSR: unknown item property rangedDefenceBonus
MICSR.js:26 MICSR: unknown item property attackBonus
MICSR.js:26 MICSR: unknown item property strengthBonus
MICSR.js:26 MICSR: unknown item property isAmmo
MICSR.js:26 MICSR: unknown item property rangedAttackBonus
MICSR.js:26 MICSR: unknown item property rangedStrengthBonus
MICSR.js:26 MICSR: unknown item property isMagic
MICSR.js:26 MICSR: unknown item property magicAttackBonus
MICSR.js:26 MICSR: unknown item property magicDamageBonus
MICSR.js:26 MICSR: unknown item property slayerBonusXP
MICSR.js:26 MICSR: unknown item property canUseMagic
MICSR.js:26 MICSR: unknown item property increasedWaterSpellDamage
MICSR.js:26 MICSR: unknown item property gpMultiplierCap
MICSR.js:26 MICSR: unknown item property gpMultiplierMin
MICSR.js:26 MICSR: unknown item property chanceToCrit
MICSR.js:26 MICSR: unknown item property critDamage
MICSR.js:26 MICSR: unknown item property decreasedAttackSpeed
MICSR.js:26 MICSR: unknown item property reflectDamage
MICSR.js:26 MICSR: unknown item property chanceToDoubleLoot
MICSR.js:26 MICSR: unknown item property gpMultiplier
MICSR.js:26 MICSR: unknown item property increasedGP
MICSR.js:26 MICSR: unknown item property ammoPreservation
MICSR.js:26 MICSR: unknown item property spellHeal
MICSR.js:26 MICSR: unknown item property hpRegenBonus
MICSR.js:26 MICSR: unknown item property increasedHPRegen
MICSR.js:26 MICSR: unknown item property increasedMaxHitpoints
MICSR.js:26 MICSR: unknown item property lifesteal
MICSR.js:26 MICSR: unknown item property decreasedAutoEatEfficiency
MICSR.js:26 MICSR: unknown item property increasedAutoEat
MICSR.js:26 MICSR: unknown item property prayerCostReduction
MICSR.js:26 MICSR: unknown item property summoningMaxHit
MICSR.js:26 MICSR: unknown item property attackLevelRequired
MICSR.js:26 MICSR: unknown item property defenceLevelRequired
MICSR.js:26 MICSR: unknown item property magicLevelRequired
MICSR.js:26 MICSR: unknown item property rangedLevelRequired
MICSR.js:26 MICSR: unknown item property slayerLevelRequired
MICSR.js:26 MICSR: unknown item property prayerBonus
MICSR.js:26 MICSR: unknown item property slayerAreaEffectNegationPercent
MICSR.js:26 MICSR: unknown item property increasedMinAirSpellDmg
MICSR.js:26 MICSR: unknown item property increasedMinEarthSpellDmg
MICSR.js:26 MICSR: unknown item property increasedMinFireSpellDmg
MICSR.js:26 MICSR: unknown item property increasedMinWaterSpellDmg
MICSR.js:26 MICSR: unknown item property craftingID
MICSR.js:26 MICSR: unknown item property fishingSpeedBonus
MICSR.js:26 MICSR: unknown item property fletchingID
MICSR.js:26 MICSR: unknown item property smithingID
MICSR.js:26 MICSR: unknown item property increasedSuccessRate
MICSR.js:26 MICSR: unknown item property baseChanceToPreserve
MICSR.js:26 MICSR: unknown item property bonusMasteryXP
MICSR.js:26 MICSR: unknown item property bonusSkillXP
MICSR.js:26 MICSR: unknown item property canEquip
MICSR.js:26 MICSR: unknown item property chanceToDoubleResources
MICSR.js:26 MICSR: unknown item property chanceToPreserve
MICSR.js:26 MICSR: unknown item property itemID
MICSR.js:26 MICSR: unknown item property slayerCost
MICSR.js:26 MICSR: unknown item property slayerTaskRequirement
MICSR.js:26 MICSR: setting up playerSpecialNames
MICSR.js:26 MICSR: AgilityCourse is waiting for modifierNames
MICSR.js:26 MICSR: AgilityCourse is waiting for Card
MICSR.js:26 MICSR: setting up modifierNames
modifierNames.js:605 MICSR: unknown modifier increasedFrostburn
modifierNames.js:605 MICSR: unknown modifier increasedAfflictionChance
modifierNames.js:605 MICSR: unknown modifier otherStyleImmunity
modifierNames.js:605 MICSR: unknown modifier meleeImmunity
modifierNames.js:605 MICSR: unknown modifier rangedImmunity
modifierNames.js:605 MICSR: unknown modifier magicImmunity
modifierNames.js:605 MICSR: unknown modifier slowImmunity
modifierNames.js:605 MICSR: unknown modifier increasedEndOfTurnHealing2
modifierNames.js:605 MICSR: unknown modifier increasedEndOfTurnHealing3
modifierNames.js:605 MICSR: unknown modifier increasedEndOfTurnHealing5
modifierNames.js:605 MICSR: unknown modifier increasedChanceToApplyPoison
modifierNames.js:605 MICSR: unknown modifier increasedChanceToApplyFrostburn
modifierNames.js:605 MICSR: unknown modifier increasedMeleeStunChance
modifierNames.js:605 MICSR: unknown modifier increasedElementalEffectChance
modifierNames.js:605 MICSR: unknown modifier frostBurnImmunity
modifierNames.js:605 MICSR: unknown modifier increasedPoisonReflectChance
modifierNames.js:605 MICSR: unknown modifier increasedBleedReflectChance
modifierNames.js:605 MICSR: unknown modifier increasedMinNatureSpellDamageBasedOnMaxHit
modifierNames.js:605 MICSR: unknown modifier increasedTotalBleedDamage
modifierNames.js:605 MICSR: unknown modifier increasedChanceToIncreaseStunDuration
modifierNames.js:605 MICSR: unknown modifier increasedSurgeSpellAccuracy
modifierNames.js:605 MICSR: unknown modifier increasedSurgeSpellMaxHit
modifierNames.js:605 MICSR: unknown modifier decreasedRegenerationInterval
modifierNames.js:605 MICSR: unknown modifier increasedOnHitSlowMagnitude
modifierNames.js:605 MICSR: unknown modifier globalEvasionHPScaling
modifierNames.js:605 MICSR: unknown modifier increasedRunecraftingEssencePreservation
modifierNames.js:605 MICSR: unknown modifier freeProtectItem
modifierNames.js:605 MICSR: unknown modifier autoEquipFoodUnlocked
modifierNames.js:605 MICSR: unknown modifier autoSwapFoodUnlocked
modifierNames.js:605 MICSR: unknown modifier increasedChanceSuccessfulCook
modifierNames.js:605 MICSR: unknown modifier decreasedChanceSuccessfulCook
modifierNames.js:605 MICSR: unknown modifier increasedChancePerfectCookGlobal
modifierNames.js:605 MICSR: unknown modifier decreasedChancePerfectCookGlobal
modifierNames.js:605 MICSR: unknown modifier increasedChancePerfectCookFire
modifierNames.js:605 MICSR: unknown modifier decreasedChancePerfectCookFire
modifierNames.js:605 MICSR: unknown modifier increasedChancePerfectCookFurnace
modifierNames.js:605 MICSR: unknown modifier decreasedChancePerfectCookFurnace
modifierNames.js:605 MICSR: unknown modifier increasedChancePerfectCookPot
modifierNames.js:605 MICSR: unknown modifier decreasedChancePerfectCookPot
modifierNames.js:605 MICSR: unknown modifier increasedThievingStealth
modifierNames.js:605 MICSR: unknown modifier decreasedThievingStealth
modifierNames.js:605 MICSR: unknown modifier increasedAltMagicRunePreservation
modifierNames.js:605 MICSR: unknown modifier decreasedAltMagicRunePreservation
modifierNames.js:605 MICSR: unknown modifier increasedMinThievingGP
modifierNames.js:605 MICSR: unknown modifier decreasedMinThievingGP
modifierNames.js:605 MICSR: unknown modifier increasedFishingSpecialChance
modifierNames.js:605 MICSR: unknown modifier decreasedFishingSpecialChance
modifierNames.js:605 MICSR: unknown modifier increasedAllotmentSeedCost
modifierNames.js:605 MICSR: unknown modifier decreasedAllotmentSeedCost
modifierNames.js:605 MICSR: unknown modifier increasedSummoningMaxHit
modifierNames.js:605 MICSR: unknown modifier decreasedSummoningMaxHit
modifierNames.js:605 MICSR: unknown modifier masteryToken
modifierNames.js:605 MICSR: unknown modifier increasedChanceForDiamondFiremaking
modifierNames.js:605 MICSR: unknown modifier decreasedChanceForDiamondFiremaking
modifierNames.js:605 MICSR: unknown modifier increasedNonMagicPoisonChance
modifierNames.js:605 MICSR: unknown modifier increasedChanceToPreserveFood
modifierNames.js:605 MICSR: unknown modifier allowLootContainerStacking
modifierNames.js:605 MICSR: unknown modifier infiniteLootContainer
modifierNames.js:605 MICSR: unknown modifier increasedBaseStardustDropQty
modifierNames.js:605 MICSR: non-existent modifier increasedMeleeCritMult
modifierNames.js:605 MICSR: non-existent modifier decreasedMeleeCritMult
modifierNames.js:605 MICSR: non-existent modifier increasedRangedCritMult
modifierNames.js:605 MICSR: non-existent modifier decreasedRangedCritMult
modifierNames.js:605 MICSR: non-existent modifier increasedMagicCritMult
modifierNames.js:605 MICSR: non-existent modifier decreasedMagicCritMult
modifierNames.js:605 MICSR: non-existent modifier increasedCombatStoppingThreshold
modifierNames.js:605 MICSR: non-existent modifier decreasedFoodBurnChance
modifierNames.js:605 MICSR: non-existent modifier summoningSynergy_9_10
modifierNames.js:674 Uncaught TypeError: x is not iterable
    at modifierNames.js:674
    at Array.reduce (<anonymous>)
    at MICSR.ShowModifiers.getModifierNames (modifierNames.js:674)
    at new MICSR.ShowModifiers (modifierNames.js:455)
    at setup (modifierNames.js:943)
    at waitLoadOrder (modifierNames.js:992)
    at modifierNames.js:987
MICSR.js:26 MICSR: setting up CombatData
MICSR.js:26 MICSR: setting up Card
MICSR.js:26 MICSR: setting up Import
MICSR.js:26 MICSR: setting up Plotter
MICSR.js:26 MICSR: setting up Simulator
MICSR.js:26 MICSR: setting up TabCard
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
cloud.js?1218:7 Synchronising with Cloud
cloud.js?1218:65 Connected to PlayFab successfully
cloud.js?1218:66 PlayFab Connected: gutblender
​ Failed to load main
​ Failed to load App
​ Failed to load AgilityCourse
style.css:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Note that no console output occurred at the time of selecting Default Page on Load.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.22.1

### Game Subversion

V0.23 ?1218

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Please do not post Test server bugs on Github. They stay inside the Patreon channels only
