### ISSUE TITLE
[Bug]: <title>playfab error IP is currently banned making excessive api calls

### ISSUE THREAD

**Issue by oldcrick** [MelvorIdle/melvoridle.github.io#1586]
### Describe the bug

![23C6BAB0-1686-4928-8E4A-B8E406F5AB2D](https://user-images.githubusercontent.com/93947943/140814566-960cd6e7-47aa-413e-8cda-ced420656bc6.png)

### Reproduction Steps

upon opening on iOS mobile

### Expected behaviour

go to character load screen. 

first time this happened i deleted the mobile app and reinstalled, then it worked. but later it happened again, so i waited a few minutes and it resolved again. 

### Screenshots

![28687CCE-BBA9-4567-8F5E-E6FE9DC9E346](https://user-images.githubusercontent.com/93947943/140814668-32dd35f7-9b9f-44ad-b304-b6949f044747.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.22.1

### Game Subversion

1217

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Hey, what is the username you are registered under? Usually these bans occur due to some extreme calls within PlayFab which they do not like at all.

**Comment by oldcrick** [comment]
i don’t even know what playfab is, melvor is just about the only game i play
