### ISSUE TITLE
[Bug]: Shrimp cooking not working

### ISSUE THREAD

**Issue by samuelteowj** [MelvorIdle/melvoridle.github.io#1588]
### Describe the bug

Shrimp cooking not working as intended. Number of uncooked shrimp is decreasing and master xp is gained, but number of cooked shrimp is not increasing. I have tested it for other food types: lobsters is working as intended. 

Issue only observed when playing actively, restarting the browser or minimising the page allows you to collect the shrimp that is cooked when page is reloaded.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.22.1

### Game Subversion

?1217

### Are you using any scripts or extensions?

Yes

**Comment by MelvorIdle** [comment]
This is now fixed
