### ISSUE TITLE
[Bug]: Title: Mastery Resets on game exit

### ISSUE THREAD

**Issue by ChrisJordan92** [MelvorIdle/melvoridle.github.io#1589]
### Describe the bug

The mastery pool for mining keeps resetting to 0 whenever the game is restarted. I haven't tried it with other skills, but it keeps resetting itself to 0 with the mining skill. I have been mining non stop for over a week and my mastery pool keeps emptying itself.

### Reproduction Steps

1. Go mining
2. Gain mining mastery experience
3. Restart the game
4. Go back to the mining interface
5. Mastery pool is reset

### Expected behaviour

I expect the mastery pool experience I have gained to stay the same when the game is restarted

### Screenshots

![Screenshot_20211109-144503_Melvor Idle](https://user-images.githubusercontent.com/31294627/140932058-b12bd02d-ad51-42ce-b8f4-66c1d185bb81.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.22.1

### Game Subversion

?1217

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is now fixed
