### ISSUE TITLE
[Suggestion]: Quick sell option: SHIFT + Left click item

### ISSUE THREAD

**Issue by casperinmd** [MelvorIdle/melvoridle.github.io#1590]
### What is your suggestion?

The ability to sell items with some key combo.

Hold S and left click items, or hold SHIFT (some modifier toggable)

### Why are you suggesting this?

With limited space, I find it hard to get the drops I need b/c my bank fills with junk I don't want, so I have to quickly sell those while hoping to get a drop. Thieving is a good example of the bottle neck.

### How does your suggestion benefit the game?

Either quick clearing of inventory junk or to keep making room while farming a unique drop you don' thave yet nor the space to let it auto loot.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
