### ISSUE TITLE
[Suggestion]: Thieving Stats

### ISSUE THREAD

**Issue by tea-sheep** [MelvorIdle/melvoridle.github.io#1591]
### What is your suggestion?

I think it'd be cool if I could access thriving stats that were similar to monster stats - how many times have I stolen, how much in gp have I stolen, how much damage has the enemy done etc.

### Why are you suggesting this?

I went looking for this information in the monster completion log and didn't find it

### How does your suggestion benefit the game?

It'd be cool

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
