### ISSUE TITLE
[Bug]: premium Melvor?

### ISSUE THREAD

**Issue by Pwusa** [MelvorIdle/melvoridle.github.io#1592]
### Describe the bug

Is the game now pay to play? I got signed out of the cloud and now have to pay to play?
![7C9509C3-9B9A-4EDC-8F96-CE36782AA85F](https://user-images.githubusercontent.com/91908822/141042527-6d0a1282-6096-4fb4-bcd8-d004c36a12cc.png)

![466F617B-6428-4E77-8577-D83BF1C70A7D](https://user-images.githubusercontent.com/91908822/141042525-f83a7917-b60f-41aa-8468-901bb2c62ae8.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.22.1

### Game Subversion

?1217

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
You just need to log back into your Cloud account.

**Comment by rangerjero** [comment]
I try log back and reimport file and reinstall
But still can't use it normally.
and I use steam Version

![1636506259428](https://user-images.githubusercontent.com/10458117/141050902-dc3651e8-9a01-4edc-8b35-10f487db05ec.jpg)
![1636516473676](https://user-images.githubusercontent.com/10458117/141050908-1d32db19-7c67-4e68-8913-47633ed74c64.jpg)

**Comment by Pwusa** [comment]
I don’t remember how I was originally singed into the cloud. None of my emails have forgotten passwords, so I registered one of my emails and connected. This didn’t remove the premium options. 
I honestly think I first connected to the cloud through my Apple ID and now the option is no longer there

**Comment by Pwusa** [comment]
I have since just paid for the premium version again. Keep up the good work Melvor team 💪🏽
