### ISSUE TITLE
[Bug]: Steam overlay stuck

### ISSUE THREAD

**Issue by rororo707** [MelvorIdle/melvoridle.github.io#1593]
### Describe the bug

The bug produces the steam overlay and it cannot be dismissed with normal shift tab or the click here to return to game text at the top of the screen. You cannot interact with anything, for that matter. Clicking does nothing. You must reboot the game at this point.

### Reproduction Steps

The way I usually find this bug happening is that I open up steam overlay and send messages to friends on ANOTHER game, while Melvor is running. This forcefully opens up the overlay in Melvor and I cannot dismiss it. 
Things I think forcefully open it:

1) A friend messaging you while you have steam overlay open in another game
2) Doing anything prolonged on another steam overlay opened in dif game

### Expected behaviour

To be able to exit the overlay, or to use it on my own and not have it blocked from opening.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.22.1

### Game Subversion

71217

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
It is best to leave the Steam overlay disabled for Melvor Idle as it has a lot of compatibility issues with the engine Melvor Idle runs on.
