### ISSUE TITLE
Premium

### ISSUE THREAD

**Issue by JakeWestwood4** [MelvorIdle/melvoridle.github.io#1594]
### Describe the bug

I bought premium on iPhone and from what I can gather I should also be able to use the full game on the web version, I have signed into my cloud account and can use my saves but do not have access to the extra skills. If this is inteded then I am happy to buy through steam also but dont know if this is supposed to be like this.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.22.1

### Game Subversion

?1217

### Are you using any scripts or extensions?

No

**Comment by Bxdhi** [comment]
Not sure if I'm allowed to help you but on discord this is explained.
Here's the screenie
![Uploading Screenshot_20211110-181602.jpg…]()
