### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by KingPeachii** [MelvorIdle/melvoridle.github.io#1596]
### Describe the bug

I selected the Smithing skill before closing my phone to sleep, when I woke up the account did no smithing

### Reproduction Steps

I just opened the app and selected my character

### Screenshots

![54831D26-8BF6-4212-9DAA-DDF9AD91954C](https://user-images.githubusercontent.com/94091509/141225029-2f38586d-de23-45d7-918b-7b17a3e9c049.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1255

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Is this something that occurs every time you smith offline, or did it only occur once?

**Comment by KingPeachii** [comment]
I’ve only just started playing, I’ll try smithing now and let you know when
I check again!
