### ISSUE TITLE
[Bug]: <title>NameError

### ISSUE THREAD

**Issue by Wealthy99** [MelvorIdle/melvoridle.github.io#1597]
### Describe the bug

the text does not Load

### Reproduction Steps

Open the weird goop buy menu 

### Expected behaviour

Say something else 

### Screenshots

![DFBB73E5-6C34-45C0-8DFF-CFA634BED376](https://user-images.githubusercontent.com/94091765/141226017-805500ac-5513-4806-8298-7b629310639a.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1256

### Are you using any scripts or extensions?

No

**Comment by Wealthy99** [comment]
It does the same thing for compost 
![77826A5F-81EF-43CE-8458-A4AF4A85D6A4](https://user-images.githubusercontent.com/94091765/141226525-3a16b2ab-d053-4758-9021-6524f3e26784.png)

**Comment by wdarvin** [comment]
I'm also seeing this on the summoning shard "Quick Buy Item" menu

![IMG_0392](https://user-images.githubusercontent.com/8687624/141228212-ca85842d-c027-4374-b109-0f5020023a30.jpeg)

**Comment by MelvorIdle** [comment]
spelling mistake on my end. Will be fixed in next hotfix release
