### ISSUE TITLE
[Bug]: <hp and prayer points not updating>

### ISSUE THREAD

**Issue by tacomunchies42** [MelvorIdle/melvoridle.github.io#1598]
### Describe the bug

in the side bar when in combat the HP and prayer points are not updating.

### Reproduction Steps

1. enter combat
2. turn on a prayer
3. take damage and attack
4. the points in the side bar wont change

### Expected behaviour

the HP and prayer points to count in real time

### Screenshots

![melvor](https://user-images.githubusercontent.com/48104729/141226691-9ff89828-6924-458d-8a50-4f1312b54a1e.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1256

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This should now be hotfixed
