### ISSUE TITLE
[Bug]: Mining Gloves display incorrect in Mining page

### ISSUE THREAD

**Issue by waynechen323** [MelvorIdle/melvoridle.github.io#1599]
### Describe the bug

Mining Gloves display ${COUNT} CHARGES in Mining page.

### Reproduction Steps

Go to Mining

### Screenshots

<img width="1440" alt="截圖 2021-11-11 上午10 30 11" src="https://user-images.githubusercontent.com/35021878/141226792-9c237d7a-14b4-4258-a937-f7c954f4cf59.png">

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1257

### Are you using any scripts or extensions?

No

**Comment by dasheath** [comment]
Ditto for cooking gloves on mobile (iOS). These also show ${count}

**Comment by omsi6** [comment]
Same missing string issue for Sneak-Ers on the same version as the issue but chrome.
![image](https://user-images.githubusercontent.com/9219554/141228724-dcbf0af3-8832-4935-a2a6-8e9d7654a5a5.png)

**Comment by MelvorIdle** [comment]
This issue with the gloves is now fixed
