### ISSUE TITLE
Cooking Page: Selected Food Qty Only Updates on Successful Cook

### ISSUE THREAD

**Issue by aldousWatts** [MelvorIdle/melvoridle.github.io#160]
**Describe the bug**
When cooking, the blue number depicting how many currently selected fish you have in the bank does not update when you burn a fish. It will only change when you successfully cook a fish. 

**To Reproduce**
1. Go to Cooking Page
2. Click on Select Food
3. Select a food that you could possibly burn
4. Click 'Cook'
5. The span with ID `#skill-cooking-food-selected-qty` will only update after a successful cook, not after a burned fish. You can burn the last few of your fish and you'll be left with a number indicating you still have fish in the bank, but of course you can't cook them because they don't exist!

**Expected behavior**
This number updates whether the fish is burned or cooked, no matter how it is consumed.

**Screenshots**
![Screenshot_20200331_193617](https://user-images.githubusercontent.com/62157566/78087514-f5827180-7386-11ea-9bb4-74f0d2f27890.png)

**Browser**
Newest Firefox (linux) with or without SEMI add-on

**Console output**
No console output is relevant, but I have an idea where the code could be fixed.

Lines 81-102 of cooking.js handle what happens when food is burnt. Simply add `updateAvailableFood(); ` perhaps just after line 102 to make sure #skills-cooking-food-selected-qty is properly updated when food is burnt.

**Comment by MelvorIdle** [comment]
Fixed in upcoming minor update
