### ISSUE TITLE
[Bug]: Farming - Quick Buy 10x Compose - "Undefined Translation Category: SHIP_MISC"

### ISSUE THREAD

**Issue by david-ellinger** [MelvorIdle/melvoridle.github.io#1600]
### Describe the bug

`Undefined Translation Category: SHIP_MISC` string present on Quick Buy Item button

### Reproduction Steps

1. Go to Farming
2. Go to Quick Buy Compost

### Screenshots

![image](https://user-images.githubusercontent.com/43858539/141229040-d5b9b96b-329d-4be8-b9f5-de2a261f420f.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1257

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Spelling error on my end. Will fix in the next hotfix
