### ISSUE TITLE
[Bug]: Prices for farming patches not showing correctly.

### ISSUE THREAD

**Issue by Kdkreig** [MelvorIdle/melvoridle.github.io#1601]
### Describe the bug

https://user-images.githubusercontent.com/51969222/141232262-49cc40d3-6693-4d72-a839-4ddfd80950ef.mp4

Prices aren't shown correctly. I bought 2 Allotments to confirm, but not in the given GIF. The prices were roughly what I believed they should have been, roughly 50k and 75k from what I remember.

I did close and reopen Melvor Idle more than once to make sure it wasn't a one off bug since I had just opened it for the first time since the update.

### Expected behaviour

The appropriate price of the farming patch to be displayed, not the level needed to unlock said patch.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1262

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This has now been hotfixed
