### ISSUE TITLE
Ragner and Terran Godswords not showing correct description

### ISSUE THREAD

**Issue by Geek4Christ** [MelvorIdle/melvoridle.github.io#1602]
### Describe the bug

The Ragnar and Terran Godswords don't display the full details of their updated attacks like the Aeris Godsword does

### Reproduction Steps

Look at the item description for the Godswords

### Expected behaviour

A detailed explanation of the special attacks is what I believe is intended since the Aeris Godsword shows it but these 2 do not

### Screenshots

![image](https://user-images.githubusercontent.com/18423676/141232772-d5826937-55c6-40ab-b133-d9133270409b.png)
![image](https://user-images.githubusercontent.com/18423676/141232796-7234af33-bc5b-4635-8bf7-bbc2de4423bb.png)

### Console output

Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-129674422-1”. index_noads.php:6:1
Loading failed for the <script> with source “https://static.cloudflareinsights.com/beacon.min.js”. index_noads.php:2799:1
Use of Mutation Events is deprecated. Use MutationObserver instead. jquery-3.2.1.js:5062:11
Connected to PlayFab successfully cloud.js:65:389
PlayFab Connected: IFoundPerry cloud.js:66:98
Removed old local storage keys. save.js:10:104
set force reload to 0 save.js:58:60
Combat Manager Built... combatManager.js:1:912
Golbin Raid Manager Built... raidManager.js:1:996
Removed old local storage keys. save.js:10:104
Loading Save Game... save.js:14:29
Save Game Loaded... save.js:14:140
Game Loaded main.js:8:418
MICSR: setting up SimEnemy MICSR.js:26:31
MICSR: setting up util MICSR.js:26:31
MICSR: setting up playerSpecialNames MICSR.js:26:31
MICSR: setting up statNames MICSR.js:26:31
MICSR: unknown item property attackSpeed MICSR.js:26:31
MICSR: unknown item property isTwoHanded MICSR.js:26:31
MICSR: unknown item property specialAttackID MICSR.js:26:31
MICSR: unknown item property equipmentSlot MICSR.js:26:31
MICSR: unknown item property isPassiveItem MICSR.js:26:31
MICSR: unknown item property damageReduction MICSR.js:26:31
MICSR: unknown item property defenceBonus MICSR.js:26:31
MICSR: unknown item property magicDefenceBonus MICSR.js:26:31
MICSR: unknown item property rangedDefenceBonus MICSR.js:26:31
MICSR: unknown item property attackBonus MICSR.js:26:31
MICSR: unknown item property strengthBonus MICSR.js:26:31
MICSR: unknown item property isAmmo MICSR.js:26:31
MICSR: unknown item property rangedAttackBonus MICSR.js:26:31
MICSR: unknown item property rangedStrengthBonus MICSR.js:26:31
MICSR: unknown item property isMagic MICSR.js:26:31
MICSR: unknown item property magicAttackBonus MICSR.js:26:31
MICSR: unknown item property magicDamageBonus MICSR.js:26:31
MICSR: unknown item property slayerBonusXP MICSR.js:26:31
MICSR: unknown item property canUseMagic MICSR.js:26:31
MICSR: unknown item property increasedWaterSpellDamage MICSR.js:26:31
MICSR: unknown item property gpMultiplierCap MICSR.js:26:31
MICSR: unknown item property gpMultiplierMin MICSR.js:26:31
MICSR: unknown item property chanceToCrit MICSR.js:26:31
MICSR: unknown item property critDamage MICSR.js:26:31
MICSR: unknown item property decreasedAttackSpeed MICSR.js:26:31
MICSR: unknown item property reflectDamage MICSR.js:26:31
MICSR: unknown item property chanceToDoubleLoot MICSR.js:26:31
MICSR: unknown item property gpMultiplier MICSR.js:26:31
MICSR: unknown item property increasedGP MICSR.js:26:31
MICSR: unknown item property ammoPreservation MICSR.js:26:31
MICSR: unknown item property spellHeal MICSR.js:26:31
MICSR: unknown item property hpRegenBonus MICSR.js:26:31
MICSR: unknown item property increasedHPRegen MICSR.js:26:31
MICSR: unknown item property increasedMaxHitpoints MICSR.js:26:31
MICSR: unknown item property lifesteal MICSR.js:26:31
MICSR: unknown item property decreasedAutoEatEfficiency MICSR.js:26:31
MICSR: unknown item property increasedAutoEat MICSR.js:26:31
MICSR: unknown item property prayerCostReduction MICSR.js:26:31
MICSR: unknown item property summoningMaxHit MICSR.js:26:31
MICSR: unknown item property attackLevelRequired MICSR.js:26:31
MICSR: unknown item property defenceLevelRequired MICSR.js:26:31
MICSR: unknown item property magicLevelRequired MICSR.js:26:31
MICSR: unknown item property rangedLevelRequired MICSR.js:26:31
MICSR: unknown item property slayerLevelRequired MICSR.js:26:31
MICSR: unknown item property prayerBonus MICSR.js:26:31
MICSR: unknown item property slayerAreaEffectNegationPercent MICSR.js:26:31
MICSR: unknown item property increasedMinAirSpellDmg MICSR.js:26:31
MICSR: unknown item property increasedMinEarthSpellDmg MICSR.js:26:31
MICSR: unknown item property increasedMinFireSpellDmg MICSR.js:26:31
MICSR: unknown item property increasedMinWaterSpellDmg MICSR.js:26:31
MICSR: unknown item property craftingID MICSR.js:26:31
MICSR: unknown item property fishingSpeedBonus MICSR.js:26:31
MICSR: unknown item property fletchingID MICSR.js:26:31
MICSR: unknown item property smithingID MICSR.js:26:31
MICSR: unknown item property increasedSuccessRate MICSR.js:26:31
MICSR: unknown item property baseChanceToPreserve MICSR.js:26:31
MICSR: unknown item property bonusMasteryXP MICSR.js:26:31
MICSR: unknown item property bonusSkillXP MICSR.js:26:31
MICSR: unknown item property canEquip MICSR.js:26:31
MICSR: unknown item property chanceToDoubleResources MICSR.js:26:31
MICSR: unknown item property chanceToPreserve MICSR.js:26:31
MICSR: unknown item property itemID MICSR.js:26:31
MICSR: unknown item property slayerCost MICSR.js:26:31
MICSR: unknown item property slayerTaskRequirement MICSR.js:26:31
MICSR: setting up modifierNames MICSR.js:26:31
MICSR: unknown modifier increasedFrostburn modifierNames.js:605:25
MICSR: unknown modifier increasedAfflictionChance modifierNames.js:605:25
MICSR: unknown modifier otherStyleImmunity modifierNames.js:605:25
MICSR: unknown modifier meleeImmunity modifierNames.js:605:25
MICSR: unknown modifier rangedImmunity modifierNames.js:605:25
MICSR: unknown modifier magicImmunity modifierNames.js:605:25
MICSR: unknown modifier slowImmunity modifierNames.js:605:25
MICSR: unknown modifier increasedEndOfTurnHealing2 modifierNames.js:605:25
MICSR: unknown modifier increasedEndOfTurnHealing3 modifierNames.js:605:25
MICSR: unknown modifier increasedEndOfTurnHealing5 modifierNames.js:605:25
MICSR: unknown modifier increasedChanceToApplyPoison modifierNames.js:605:25
MICSR: unknown modifier increasedChanceToApplyFrostburn modifierNames.js:605:25
MICSR: unknown modifier increasedMeleeStunChance modifierNames.js:605:25
MICSR: unknown modifier increasedElementalEffectChance modifierNames.js:605:25
MICSR: unknown modifier frostBurnImmunity modifierNames.js:605:25
MICSR: unknown modifier increasedPoisonReflectChance modifierNames.js:605:25
MICSR: unknown modifier increasedBleedReflectChance modifierNames.js:605:25
MICSR: unknown modifier increasedMinNatureSpellDamageBasedOnMaxHit modifierNames.js:605:25
MICSR: unknown modifier increasedTotalBleedDamage modifierNames.js:605:25
MICSR: unknown modifier increasedChanceToIncreaseStunDuration modifierNames.js:605:25
MICSR: unknown modifier increasedSurgeSpellAccuracy modifierNames.js:605:25
MICSR: unknown modifier increasedSurgeSpellMaxHit modifierNames.js:605:25
MICSR: unknown modifier decreasedRegenerationInterval modifierNames.js:605:25
MICSR: unknown modifier increasedOnHitSlowMagnitude modifierNames.js:605:25
MICSR: unknown modifier globalEvasionHPScaling modifierNames.js:605:25
MICSR: unknown modifier increasedRunecraftingEssencePreservation modifierNames.js:605:25
MICSR: unknown modifier freeProtectItem modifierNames.js:605:25
MICSR: unknown modifier autoEquipFoodUnlocked modifierNames.js:605:25
MICSR: unknown modifier autoSwapFoodUnlocked modifierNames.js:605:25
MICSR: unknown modifier increasedChanceSuccessfulCook modifierNames.js:605:25
MICSR: unknown modifier decreasedChanceSuccessfulCook modifierNames.js:605:25
MICSR: unknown modifier increasedChancePerfectCookGlobal modifierNames.js:605:25
MICSR: unknown modifier decreasedChancePerfectCookGlobal modifierNames.js:605:25
MICSR: unknown modifier increasedChancePerfectCookFire modifierNames.js:605:25
MICSR: unknown modifier decreasedChancePerfectCookFire modifierNames.js:605:25
MICSR: unknown modifier increasedChancePerfectCookFurnace modifierNames.js:605:25
MICSR: unknown modifier decreasedChancePerfectCookFurnace modifierNames.js:605:25
MICSR: unknown modifier increasedChancePerfectCookPot modifierNames.js:605:25
MICSR: unknown modifier decreasedChancePerfectCookPot modifierNames.js:605:25
MICSR: unknown modifier increasedThievingStealth modifierNames.js:605:25
MICSR: unknown modifier decreasedThievingStealth modifierNames.js:605:25
MICSR: unknown modifier increasedAltMagicRunePreservation modifierNames.js:605:25
MICSR: unknown modifier decreasedAltMagicRunePreservation modifierNames.js:605:25
MICSR: unknown modifier increasedMinThievingGP modifierNames.js:605:25
MICSR: unknown modifier decreasedMinThievingGP modifierNames.js:605:25
MICSR: unknown modifier increasedFishingSpecialChance modifierNames.js:605:25
MICSR: unknown modifier decreasedFishingSpecialChance modifierNames.js:605:25
MICSR: unknown modifier increasedAllotmentSeedCost modifierNames.js:605:25
MICSR: unknown modifier decreasedAllotmentSeedCost modifierNames.js:605:25
MICSR: unknown modifier increasedSummoningMaxHit modifierNames.js:605:25
MICSR: unknown modifier decreasedSummoningMaxHit modifierNames.js:605:25
MICSR: unknown modifier masteryToken modifierNames.js:605:25
MICSR: unknown modifier increasedChanceForDiamondFiremaking modifierNames.js:605:25
MICSR: unknown modifier decreasedChanceForDiamondFiremaking modifierNames.js:605:25
MICSR: unknown modifier increasedNonMagicPoisonChance modifierNames.js:605:25
MICSR: unknown modifier increasedChanceToPreserveFood modifierNames.js:605:25
MICSR: unknown modifier allowLootContainerStacking modifierNames.js:605:25
MICSR: unknown modifier infiniteLootContainer modifierNames.js:605:25
MICSR: unknown modifier increasedBaseStardustDropQty modifierNames.js:605:25
MICSR: non-existent modifier increasedMeleeCritMult modifierNames.js:605:25
MICSR: non-existent modifier decreasedMeleeCritMult modifierNames.js:605:25
MICSR: non-existent modifier increasedRangedCritMult modifierNames.js:605:25
MICSR: non-existent modifier decreasedRangedCritMult modifierNames.js:605:25
MICSR: non-existent modifier increasedMagicCritMult modifierNames.js:605:25
MICSR: non-existent modifier decreasedMagicCritMult modifierNames.js:605:25
MICSR: non-existent modifier increasedCombatStoppingThreshold modifierNames.js:605:25
MICSR: non-existent modifier decreasedFoodBurnChance modifierNames.js:605:25
MICSR: non-existent modifier summoningSynergy_9_10 modifierNames.js:605:25
MICSR: setting up CombatData MICSR.js:26:31
MICSR: AgilityCourse is waiting for modifierNames MICSR.js:26:31
Uncaught TypeError: x is undefined
    names moz-extension://9c87787d-d92f-4491-8b19-75882efb5255/sources/injectable/modifierNames.js:674
    getModifierNames moz-extension://9c87787d-d92f-4491-8b19-75882efb5255/sources/injectable/modifierNames.js:674
    <anonymous> moz-extension://9c87787d-d92f-4491-8b19-75882efb5255/sources/injectable/modifierNames.js:455
    setup moz-extension://9c87787d-d92f-4491-8b19-75882efb5255/sources/injectable/modifierNames.js:943
    waitLoadOrder moz-extension://9c87787d-d92f-4491-8b19-75882efb5255/sources/injectable/modifierNames.js:992
    waitLoadOrder moz-extension://9c87787d-d92f-4491-8b19-75882efb5255/sources/injectable/modifierNames.js:987
modifierNames.js:674:102
MICSR: AgilityCourse is waiting for Card MICSR.js:26:31
MICSR: setting up DataExport MICSR.js:26:31
MICSR: setting up Card MICSR.js:26:31
MICSR: setting up Consumables MICSR.js:26:31
MICSR: setting up Import MICSR.js:26:31
MICSR: setting up Menu MICSR.js:26:31
MICSR: setting up Loot MICSR.js:26:31
MICSR: setting up Plotter MICSR.js:26:31
MICSR: setting up SimManager MICSR.js:26:31
MICSR: Simulator is waiting for SimPlayer MICSR.js:26:31
MICSR: setting up TabCard MICSR.js:26:31
MICSR: main is waiting for App MICSR.js:26:31
MICSR: setting up SimPlayer MICSR.js:26:31
MICSR: App is waiting for AgilityCourse MICSR.js:26:31
MICSR: App is waiting for modifierNames MICSR.js:26:31
MICSR: App is waiting for Simulator MICSR.js:26:31
Loading failed for the <script> with source “https://static.cloudflareinsights.com/beacon.min.js”. PatchNotes1.0.html:3021:1
Connected to PlayFab successfully cloud.js:65:389
Loading failed for the <script> with source “https://static.cloudflareinsights.com/beacon.min.js”. index.html:563:1
jQuery.Deferred exception: Chart is not defined value@https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316
value@https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626
@https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705
e@https://melvoridle.com/assets/js/oneui.core.min.js:6:29792
c/</t<@https://melvoridle.com/assets/js/oneui.core.min.js:6:30116
 undefined oneui.core.min.js:6:31368
MICSR: setting up Simulator MICSR.js:26:31
PlayFab Connected: IFoundPerry cloud.js:66:98
Uncaught ReferenceError: Chart is not defined
    value https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6
    value https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6
    <anonymous> https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6
    e https://melvoridle.com/assets/js/oneui.core.min.js:6
    t https://melvoridle.com/assets/js/oneui.core.min.js:6
be_pages_dashboard.min.js:6:1316
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features! index_noads.php
Synchronising with Cloud cloud.js:7:109
Failed to load AgilityCourse AgilityCourse.js:256:21
Failed to load main main.js:94:21
Failed to load App App.js:2697:21

​

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1255

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
