### ISSUE TITLE
[Bug]: Adventure Mode, cannot set Bank as default opening page.

### ISSUE THREAD

**Issue by RiRupp** [MelvorIdle/melvoridle.github.io#1603]
### Describe the bug

Attempting to set the bank as the Default Page upon opening the game displays a "Skill locked!" pop-up. It will instead default to the combat tab being the Default Page, as the bank 'skill' is locked.

### Reproduction Steps

1. Go to settings, Interface Settings. 
2. Attempt to change Default Page on Load to the bank tab in Adventure Mode.

### Expected behaviour

Bank tab was available as an option before Beta update; bank isn't an unlockable skill.

### Screenshots

![image](https://user-images.githubusercontent.com/78137019/141234457-7e6d47e1-473b-4814-9c57-030c851ace5b.png)

### Console output

DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1265

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
A hotfix has been applied for this bug :)
