### ISSUE TITLE
[Bug]: Stardust in wrong spot when bank is sorted

### ISSUE THREAD

**Issue by AlexDerr** [MelvorIdle/melvoridle.github.io#1604]
### Describe the bug

When owning stardust and golden stardust in the bank and sorting the bank the stardust appears between the normal and oak logs. I am assuming (and hoping) that this was a mistake and that they have a different intended location.

### Reproduction Steps

1. Have normal logs, oak logs, stardust and golden stardust in bank along with other items
2. Sort the bank
3. Stardust and normal stardust should be sorted between normal and oak logs

### Expected behaviour

I do not know exactly where the intended location is but I am hoping it is not in the middle of the logs.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1258

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Can you please confirm what sorting method you have set under the Bank settings area?

**Comment by AlexDerr** [comment]
I am using the default bank sorting.

**Comment by AlexDerr** [comment]
It also seems the order that they get placed in is not always the same and they can sometimes stay in the slot before the normal logs.

1. Slot 1 stardust, slot 2 gold stardust, slot 3 normal log
2. Default sort does not move any items

1. Slot 1 stardust, slot 2 normal log, slot 3 golden stardust
2. Default sort does not move any items

1. Slot 1 normal log, slot 2 golden stardust, slot 3 oak log, stardust anywhere else in bank
2. Default sort leaves slot 1 normal log, slot 2 golden and makes slot 3 normal stardust

1. Slot 1 normal log, slot 2 normal stardust, slot 3 oak log, golden stardust anywhere else in bank
2. Default sort leaves slot 1 normal log, slot 2 normal stardust and makes slot 3 golden stardust

**Comment by AlexDerr** [comment]
As a side note, the bit of the update I have explored so far is great! Thank you for everything you do for the game 😄

**Comment by AlexDerr** [comment]
It looks like the astrology mastery token has the same issue where it will sort between the normal log and oak log. It also looks to stay in the order that it was in when the sort was performed like the other two

**Comment by MelvorIdle** [comment]
Fix has been applied to the game
