### ISSUE TITLE
[Bug]: Astrology guide not showing when clicking Astrology skill symbol on skill page.

### ISSUE THREAD

**Issue by andrew-broersma** [MelvorIdle/melvoridle.github.io#1605]
### Describe the bug

The guide for the skill astrology does not display anything in the window that pops up when you click on the skill symbol at the top of the astrology page. The window shows up, but the content does not display.

### Reproduction Steps

1. Go to skill Astrology
2. Click on the skill symbol at the top of the Astrology page.
3. See that nothing appears in the window that is pulled up.
![Melvorbug](https://user-images.githubusercontent.com/92401826/141238099-b99f7571-a469-44e8-b417-c23d72cb7744.png)

### Expected behaviour

I expected there to be some details explaining the skill.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1266

### Are you using any scripts or extensions?

No

**Comment by Opxnasty** [comment]
I am encountering this as well on Android

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
