### ISSUE TITLE
[Bug]: Sneak-Er description

### ISSUE THREAD

**Issue by LtLash** [MelvorIdle/melvoridle.github.io#1609]
### Describe the bug

![AF5C8B1A-92A2-498B-B5EF-045DB9016D95](https://user-images.githubusercontent.com/94098297/141242444-61ecd68e-2842-4ee0-91ec-f618e2bde9c0.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1247

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is now hotfixed
