### ISSUE TITLE
[Spelling/Grammar]: <Missing % symbol>

### ISSUE THREAD

**Issue by Brad-12** [MelvorIdle/melvoridle.github.io#1610]
### What text is wrong?

![Screenshot_20211111-051135_Melvor Idle](https://user-images.githubusercontent.com/94098195/141242483-6f34ad17-7a84-4886-b1c9-86339ece68a7.jpg)

### What is the correct spelling or grammar?

Add a % symbol

**Comment by coolrox95** [comment]
Issue cannot be reproduced in current version (v1.0.3).
