### ISSUE TITLE
[Translation Bug]: Gold Crested Shield missing description

### ISSUE THREAD

**Issue by Maxaman33** [MelvorIdle/melvoridle.github.io#1611]
### Describe the bug

When viewing the Gold Crested Shield, the description is missing and says:
UNDEFINED TRANSLATION: 
ITEM_DESCRIPTION:Gold_Crested_Shield

Same issue as in issue #1600.

### Reproduction Steps

1. Go to Bank.
2. Click on Gold Crested Shield or Hover over Gold Crested Shield.
3. Observe undefined translation

### Expected behaviour

1. Go to Bank.
2. Click on Gold Crested Shield or Hover over Gold Crested Shield.
3. Observe correct translation

### Screenshots

![image](https://user-images.githubusercontent.com/2730207/141243997-4ff6910a-a7e6-4bb3-9d40-b86dc5ea76af.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1265

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is now hotfixed
