### ISSUE TITLE
[Bug]: Visual Issues on Completion Page on iPhone 

### ISSUE THREAD

**Issue by SirSpiffynator** [MelvorIdle/melvoridle.github.io#1613]
### Describe the bug

Two issues I found so far

1. The text on each item either gets cut off if it’s on the left side or goes outside of it’s box if it’s on the right.

2. Which I unfortunately haven’t been able to recreate since but the completion percentage for skills doesn’t show so you would be shown “53.54” instead of “53.54%”

### Reproduction Steps

For 1. Just go to the completion page on iPhone or maybe android and you should see the issue.

For 2. You also should just go to the completion page but it seems to only happen sometimes

### Expected behaviour

1. Text should be completely visible and stay inside of the text box

2. The percentage symbol should be shown 

### Screenshots

1.
![3F9DC6F9-B29D-43FC-B159-D922539CEE28](https://user-images.githubusercontent.com/94099637/141247020-c405011c-5162-4186-92f2-d3b27a31f40b.png)

I only saw 2 once and didn’t screenshot and haven’t got it since so unfortunately can’t provide evidence

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1270

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is now hotfixed
