### ISSUE TITLE
[Bug]: deletes local save file when opening the game

### ISSUE THREAD

**Issue by TurtleDuck2** [MelvorIdle/melvoridle.github.io#1615]
### Describe the bug

Deletes my local file when I close and open the game on mobile and shows the cooking and thievery rework every time opening the game

### Screenshots

![3580CD65-3BBF-4405-91A1-2563A7C68176](https://user-images.githubusercontent.com/94104984/141330795-6ea45c72-89d7-4f70-be92-c52e87089a40.png)
![D890ED5F-1199-43B7-B02F-359A40BA6B84](https://user-images.githubusercontent.com/94104984/141330800-31aa63a2-0d7b-4a0b-be49-e6d14053a44e.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [x] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1272

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Do you have anything that would stop the game from caching its data?
What method are you using to close the game?

How long after creating a character did you wait to close the game?
