### ISSUE TITLE
Slingshot does not equip, but disappears

### ISSUE THREAD

**Issue by skha129** [MelvorIdle/melvoridle.github.io#1616]
### Describe the bug

I have a Hard Core Cooking-Combat character.
WHen I try to equip the slingshot after getting it from ranged goblin, it unequips my arrows and weapon, but replaces it with nothing.
The actual slingshot disappears from the inventory.

The reason is it seems to be used like ammo.

### Reproduction Steps

1. Equip a Slingshot
2. Engage in combat
3. Slingshot disappears / unequipped+destroyed / consumed after you attack

### Expected behaviour

Slingshot should remain equipped as a weapon and not reduce in quantity

### Screenshots

Step 1: Dagger and Arrow equipped. 5 Slingshots in Inventory
![image](https://user-images.githubusercontent.com/68756457/141264277-47844701-2aa2-410a-8978-7c6843cd3ec3.png)
Step 2: Go to equip  weapon
![image](https://user-images.githubusercontent.com/68756457/141264383-0b519ad3-0feb-4160-9ca8-eecaaac11fda.png)
Step 3: It was equipped for a couple of seconds, and then disappears
![image](https://user-images.githubusercontent.com/68756457/141264467-5f05d7e6-d4f8-4411-913f-5856c7f738fb.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [x] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1272

### Are you using any scripts or extensions?

No

**Comment by skha129** [comment]
Tested on iOS and Android version as well

**Comment by MelvorIdle** [comment]
Fix has been applied to the game
