### ISSUE TITLE
[Bug]: Alchemy Spells

### ISSUE THREAD

**Issue by bwgitter** [MelvorIdle/melvoridle.github.io#1618]
### Describe the bug

The alchemy spells names are incorrectly labeled as blast spells.

### Reproduction Steps

I left and reopened the list view multiple times.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

Newest just released

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue was hotfixed as of version Beta v1.0 (?1274).
