### ISSUE TITLE
[Bug]: Tutorial Task -Ranged Preparation 7

### ISSUE THREAD

**Issue by SustainableBlueDuck** [MelvorIdle/melvoridle.github.io#1619]
### Describe the bug

The task isn't updated in a particular scenario:
When first equiping 1 bronze arrow, the task is to equip 29 more. When equiping 29 more, the task isn't updated. The message remains equip 29 more arrows. When unequiping all arrows and re-equiping 30, the task is complete.

Not sure if this is repeatable, but this is what I remember. _edit: this is repeatable_

_edit: Additional debugging info: when equiping x, then unequiping, then equiping y, the total counted equipped arrows is x+y_

### Reproduction Steps

1. be at step 15/23 of tutorial island
2. Go to the bank tab
3. equip the short bow, then equip 1 bronze arrow
4. equip 29 arrows
5. task incompletes
6. click on equipment menu & click on the arrows to unequip them
7. equip all 30 arrows
8. task complete

### Expected behaviour

when there are 30 bronze arrows in the quiver equipment slot (and a shortbow equiped), the task mentioned above should be completed.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1272

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Fix has been applied to the game
