### ISSUE TITLE
Lemon is a Lemon

### ISSUE THREAD

**Issue by Firazoid** [MelvorIdle/melvoridle.github.io#162]
**Describe the bug**
The image for the lemon does not have a transparent background.

**To Reproduce**
1. Get a lemon.
2. Hover over the lemon.
3. Observe the lemon, and see that it has a white square background.

**Expected behavior**
I expected to see through the portions of the lemon image that are not the lemon.

**Screenshots**
![](https://melvoridle.com/assets/april/images/lemon.jpg)

**Browser**
Chrome

**Console output**
No relevant errors.

**Comment by MelvorIdle** [comment]
Lemon is best
