### ISSUE TITLE
[Suggestion]: Behaviour death on Hardcore mode

### ISSUE THREAD

**Issue by SustainableBlueDuck** [MelvorIdle/melvoridle.github.io#1621]
### What is your suggestion?

I died during my tutorial island on my new Hardcore (LOL). I didn't realize until I was at the character selection screen and not seeing my fresh account, which didn't complete tutorial island yet. I guess I died to a chicken.. Jokes aside, I think the save should not be deleted, maybe make the account accessable, but not playable and have a banner in the screen above, something like: "You dieded on <datetime> doing <skill> _+any of the following options_ (fighting <monster> / thieving <NPC> / ... (include all ways to die) ).

### Why are you suggesting this?

It's nice to be able to see how far your hardcore got instead of not having any trace of it.

### How does your suggestion benefit the game?

Potentially more Melvor talk about Hardcores that have died, with prove to show how en when :D

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
