### ISSUE TITLE
[Bug]: Tutorial Task -Ranged Preparation 8

### ISSUE THREAD

**Issue by SustainableBlueDuck** [MelvorIdle/melvoridle.github.io#1622]
### Describe the bug

see bug report #1620 , similar case, but then for a different combat style

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1272

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Fix has been applied to the game
