### ISSUE TITLE
[Bug]: Offline Mastery XP in Astrology

### ISSUE THREAD

**Issue by MasterYinan** [MelvorIdle/melvoridle.github.io#1623]
### Describe the bug

While training any of the constellations in Astrology, when going offline and coming back, you get Skill XP, but you don't get Mastery XP for that constellation you're currently studying.

I have been coming back on my second character where I just had started training Deedree and was Skilllevel 3 and Mastery Level 1 for Deedree at first. It was like half an hour later. I know was Skilllevel 14 or so, but Deedree was still level 1 (while, on my second character, which is in Adventure Mode, had Deedree at Mastery Level 10+ or so when I got Skilllevel 10 and unlocked Iridan).

So there seems to be something wrong with the offline Mastery XP for the constellations.

### Reproduction Steps

Start studying a constellation.
Go offline.
Come back later.
See Skill XP going up, but not Mastery XP for the constellation you were studying.

### Expected behaviour

Expected Mastery XP and thus Level for the constellation I was studying go up as well.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1272

### Are you using any scripts or extensions?

No

**Comment by Cavecanem** [comment]
I'm also having this problem on Android.

**Comment by Pandorian6008** [comment]
I have also experienced this issue on Steam.

**Comment by MelvorIdle** [comment]
This is now fixed. It was only a visual error and required 1 extra action to be performed for the UI to update. It now does this on load
