### ISSUE TITLE
[Suggestion]: Stack messages when collecting loot

### ISSUE THREAD

**Issue by MasterYinan** [MelvorIdle/melvoridle.github.io#1624]
### What is your suggestion?

When you collect the loot, instead of listing every single item you get, same items should be stacked together.

### Why are you suggesting this?

When it tries to list 100 items, it starts to lagg a little (it lakes a second or two to actually display all the stuff you got). Also, the full list doesn't even fit on the screen to begin with.

### How does your suggestion benefit the game?

When I get a list of 100 items where there is actually only 3 or 4 unique items in it and the rest are "duplicates" the whole listing doesn't help at all telling you what you got.
By just putting all the same stuff together in that looting display that is shown when you click on "loot", it will give you a much better overview of what you actually looted and it also won't lag out the game because it needs to display 100 messages (which don't all fit on the screen to begin with).

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
