### ISSUE TITLE
[Bug]: Bank sliders unusable in lower zoom levels

### ISSUE THREAD

**Issue by bfanimal** [MelvorIdle/melvoridle.github.io#1625]
### Describe the bug

If you set the zoom level below 100%, the sliders for items in the bank take more and more mouse-dragging to work. I couldnt even get the slider to change at all at 70% on 1080p

### Reproduction Steps

1. Go to settings
2. Change zoom level below 100%
3. Goto bank
4. Click a stacked item
5. Try to drag the sliders to interact with an item (Bury/Sell/etc)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1274

### Are you using any scripts or extensions?

No

**Comment by De3xy** [comment]
I've experienced this issue as well, easily reproducible.

**Comment by MelvorIdle** [comment]
Same bug as #497

Closing this to clean up.
