### ISSUE TITLE
[Bug]: Adventure mode progress is reverting after tutorial if no skills were unlocked

### ISSUE THREAD

**Issue by Terminader28** [MelvorIdle/melvoridle.github.io#1626]
### Describe the bug

Not sure when this happened but I have a very specific game style in one account. It’s 99 one at a time (basically can’t move to a new skill until I max one I’m training). So I was doing strength and I just noticed I got all my progress reverte all the way back to lvl 35. Its Frustrating because I was already at 75 

### Expected behaviour

I expect atleast to have my lvls back or someway, or make sure this doesn’t happen again because this type of accounts it’s frustrating to be loosing that much progress 

### Screenshots

![5F92F544-58FC-4FB5-BD68-6E3D531DB673](https://user-images.githubusercontent.com/94114980/141292665-8133dadb-de43-4534-9fad-e221ff2f6640.jpeg)
![1BA255A8-0E30-4E62-9A10-2271AD2195F8](https://user-images.githubusercontent.com/94114980/141292670-c367e411-9b52-4080-9969-2e25d534babf.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

71274

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
The bug that caused this to occur has been rectified.

If you want, please message me on Discord (Malcs) and I will get the levels back for you.
