### ISSUE TITLE
[Bug]: Game doesn't remember window size

### ISSUE THREAD

**Issue by De3xy** [MelvorIdle/melvoridle.github.io#1628]
### Describe the bug

This has been the case for many patches now. Whenever I start the game it never remembers which window size I had it open in before. Doesn't matter if resized, position or maximum window size.

### Reproduction Steps

Open game
Change window size in any way
Close game
Open game

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1274

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Not a bug, more-so a feature that is yet to be implemented.
