### ISSUE TITLE
[Bug]: Plant All Selected Crops button allows Seeds to be planted when level requirement is not met

### ISSUE THREAD

**Issue by spardasdante** [MelvorIdle/melvoridle.github.io#1629]
### Describe the bug

Can plant any seed at any level when using the new plant selected seed button

### Reproduction Steps

Go to Farming
Click drop down selecting a high level seed that meets requirement x3 for allotment x2 for herb etc.
Click Plant All selected crops.
Screenshot attached - showing I planted watermelon seeds at level at 27 farming.

### Expected behaviour

Should not have let me plant

### Screenshots

![image](https://user-images.githubusercontent.com/88258815/141295940-8b3a8c03-d65b-4e9d-b50b-bf29516e7e2e.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1274

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Fix has been applied to the game

**Comment by spardasdante** [comment]
?1285 didn't fix the issue.

**Comment by MelvorIdle** [comment]
This is now fixed. The original bug was fixed last time, however if you had seeds already selected due to the bug then they would have stayed this. The game will now detect this and remove those seed selections.
