### ISSUE TITLE
[Bug]: Completion Log - Pets showing incorrect hints

### ISSUE THREAD

**Issue by randomsanity** [MelvorIdle/melvoridle.github.io#1630]
### Describe the bug

After the update, two of the pets are showing incorrect hints (Earth and Water God). 
![image](https://user-images.githubusercontent.com/25312994/141299500-39e96077-3432-46e3-b43e-d81e7c58a1eb.png)
The two selected say Earth God, the two to their left show Water God. I'm told no new pets were added so this is likely an error. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1274

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Fix has been applied to the game
