### ISSUE TITLE
[Bug]: Can't drag sort items in bank on zoom levels other than 100%

### ISSUE THREAD

**Issue by joris-s-k** [MelvorIdle/melvoridle.github.io#1631]
### Describe the bug

Items can't rearranged in the bank by dragging and dropping them if the zoom level is not set to 100%.

### Reproduction Steps

1. Set zoom level to lower or higher than 100%
2. Try to drag items in the bank

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1274

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Same bug as #497

Closing this to clean up.
