### ISSUE TITLE
[Bug]: Unicorn Unidefined Translation Error

### ISSUE THREAD

**Issue by Machines-Embrace** [MelvorIdle/melvoridle.github.io#1632]
### Describe the bug

Information on what the Uniciorn familiar does now appears as "UNDEFINED TRANSLATION ITEM_Description:Summoning_Familiar_Unicorn" rather than "+50% Hitpoint Regeneration". It's occuring whether the Unicorn tablet is in the bank, currently equiped or in the Tablets/Summoning page. 

### Reproduction Steps

1. Go to Summoning Page
2. Go to Tablets/Familiars Page
3. Choose Create Unicorn Tablet
4. Error then appears in Create Unicorn details box at top left
 

### Expected behaviour

I would expect the text "+50% Hitpoint Regeneration" to be shown. 

### Screenshots

![Melvor Idle - Unicorn Bug Tablet Creation - Screenshot](https://user-images.githubusercontent.com/94118381/141303958-04f3c8a8-90b5-444f-8001-82ac313036d5.png)
![Melvor Idle - Unicorn Bug Bank - Screenshot ](https://user-images.githubusercontent.com/94118381/141303966-d76583a8-2292-4f47-b36a-1f292df3fc9f.png)

### Console output

N/a. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1274

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Fix has been pushed to the game
