### ISSUE TITLE
UNDEFINED TRANSLATION

### ISSUE THREAD

**Issue by Macaboros** [MelvorIdle/melvoridle.github.io#1634]
### Describe the bug

Various game messages, such as buying from the shop and “bank full,” are being given an UNDEFINED TRANSLATION (insert code term) for the feature. 

### Reproduction Steps

1. Fill bank.
2. Try to add anything else.

### Expected behaviour

Error should describe bank as full rather than offering the UNDEFINED TRANSLATION

### Screenshots

![BF8741F0-CA30-4611-AF36-ACE5801CEC26](https://user-images.githubusercontent.com/94121205/141314892-4a716d95-e7cc-490c-84cd-68a93d149f1e.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

1

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue was hotfixed as of version Beta v1.0 (?1266).
