### ISSUE TITLE
Skipping Tutorial in Adventure mode while using locked skill, continues locked skill in background

### ISSUE THREAD

**Issue by NitzyTwitch** [MelvorIdle/melvoridle.github.io#1635]
### Describe the bug

After creating a new Adventure Character, there is only Woodcutting in the Tutorial island. Activly cutting wood and then skipping the Tutorial island locks the Woodcutting skill but you still recieve Logs as if you were still able to use the Skill. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1274

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is now fixed
