### ISSUE TITLE
[Bug]: Visual lag when training skills 

### ISSUE THREAD

**Issue by StrawHat-Melvor** [MelvorIdle/melvoridle.github.io#1636]
### Describe the bug

Players have reported experiencing lag when training skills (whether it is Astrology,  combat skills, etc.). They report not having connection problems when experiencing this lag. They mentioned this happened after the update on mobile. 

### Reproduction Steps

1. Start training combat skill
2. Wait for the -HP to pop up, but out of sync

### Expected behaviour

It is expected to have the pop ups appear more smoothly and in sync with the action. 

### Screenshots

[https://www.reddit.com/r/MelvorIdle/comments/qrjwey/anyone_else_having_lag_like_this/] Includes a video

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1274

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Hotfix has now been applied
