### ISSUE TITLE
Prayer is not leveling

### ISSUE THREAD

**Issue by Detour33** [MelvorIdle/melvoridle.github.io#1637]
### Describe the bug

Prayer has 14k xp but is still lvl 1 with 0 percent. Also shame on you making me create a fuckin account on here to report a bug. Like any bug that doesn't break the game(like prayer not advancing) I ain't fuckin telling you about and y'all are gonna lose out on a lot of reports. I paid money for your app and without prayer, it's broken. 

### Reproduction Steps

K

### Expected behaviour

I expect y'all to fix my prayer 

### Screenshots

No cuz you made me create this account, find it.

### Console output

K

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

Don't fuckin know

### Are you using any scripts or extensions?

No

**Comment by drewhoener** [comment]
Dude for real? They just dropped a major update to the game, there's bound to be some mistakes. There's literally been 20+ subversion builds since it came out for bugfixes, 100% people are already working their asses off. No need to be shitty, least you can do is show the problem you're having

**Comment by Detour33** [comment]
I'm gonna be honest I'm very upset at having to create a whole account to
report a bug to the game. I almost didn't do it.

HOWEVER, I lost my cool and I apologize. Let me take a ss and email it to
you

**Comment by Detour33** [comment]
You really should consider an in-game bug reporting option. But again I
apologize for the way I acted in the report. Anything else you need just
let me know

**Comment by Detour33** [comment]
![Screenshot_20211111-110646](https://user-images.githubusercontent.com/94127917/141341995-dba5e31b-0f6d-4bef-967b-87883605c684.png)

**Comment by Detour33** [comment]
![Screenshot_20211111-110638](https://user-images.githubusercontent.com/94127917/141342036-f22a5368-344b-4022-adf1-c42dbb31a9f1.png)

**Comment by StrawHat-Melvor** [comment]
You can also report bugs in the Discord and @StrawHat. I can submit reports in the interim for players who do not want to create a GitHub account. Thank you for adding the screenshots for us.

**Comment by rapbit0** [comment]
I can see that you are experienced in combat but the 14k prayer point that's shows isn't your experience in the skill. It's the prayer points you currently have and you get it by burying bones. Have you actually ever used a prayer in combat to level it?

**Comment by MelvorIdle** [comment]
This is not a bug. What you are seeing are Prayer Points increasing. These points allow you to use Prayers, which provide Prayer Skill XP
