### ISSUE TITLE
[Bug]: fishing % dont appear in green anymore

### ISSUE THREAD

**Issue by Rafael-RD** [MelvorIdle/melvoridle.github.io#1638]
### Describe the bug

in fishing when a % is changed by the mastery it doesnt appear in green anymore

### Screenshots

![image](https://user-images.githubusercontent.com/89175493/141336347-fc4b1e3a-c780-44ad-9035-37c33fd811cd.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1274

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is now fixed as of ?1318
