### ISSUE TITLE
[Bug]: Missing import character button

### ISSUE THREAD

**Issue by Rafael-RD** [MelvorIdle/melvoridle.github.io#1639]
### Describe the bug

The import string and file buttons are missing, at least I couldnt find it and it isnt where the wiki says it is (it isnt in the same place as the export)

### Screenshots

![image](https://user-images.githubusercontent.com/89175493/141340514-8b0cf77b-d4c6-41c9-a5e6-aad7c02db74b.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1274

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
This button was intentionally removed a few updates ago as it no longer functioned correctly. Save importing must be done on the character selection screen.
