### ISSUE TITLE
Equipment that upgrades into equipment with lower stats display +-X in green

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#164]
**Describe the bug**
When you select a piece of equipment to upgrade, where the ugpraded/trimmed version has a stat that is lower the game displays +-X in green (X being the stat change)

**To Reproduce**
1. Select an item to upgrade in the bank that results in one of the stats being lower. E.g. (S) Iron Helmet
2. Click on Upgrade Item
2. Observe the green +- Stat change. (In this example Defence Bonus shows (+-1)

**Expected behavior**
The stat change should display -X in red. 

**Screenshots**
![Example of bug](https://cdn.discordapp.com/attachments/625838709744599088/694942477169197096/unknown.png)

**Comment by MelvorIdle** [comment]
Fixed in coming minor update
