### ISSUE TITLE
[Bug]: Slider broken on prayer items

### ISSUE THREAD

**Issue by StrawHat-Melvor** [MelvorIdle/melvoridle.github.io#1640]
### Describe the bug

"For some reason, I can not move the slider on prayer items (bones and dust) it's stuck at 1 for me"

Steam version. 

### Reproduction Steps

1. Go to prayer
2. Click on an item

### Expected behaviour

The slider is meant to be interactive and move. 

### Screenshots

Nope. But here is the link to the tweet: https://twitter.com/Roy_Lost/status/1458845444126171137?s=20

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

I don't have. I am guessing ?1274, due to time of posting this tweet. 

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is now fixed
