### ISSUE TITLE
[Bug]: Bank slider for actions (bury, equip, etc) doesn't "stick" at All

### ISSUE THREAD

**Issue by Bomadeno** [MelvorIdle/melvoridle.github.io#1642]
### Describe the bug

The slider for various bank actions keeps falling down to a lower number than "all". This is quite a hassle because I usually want to bury all my bones. 

### Reproduction Steps

1. Kill 5 things in combat
2. Pick up 5 bones
3. Go to bank, set slider to "bury all" and then bury.
4. Do some more combat and pick up e.g. 15 bones
5. Return to bank and see that slider is at 5 

### Expected behaviour

I expect at step 5 for the slider to be at "**all** bones", not 5 bones.

### Screenshots

![image](https://user-images.githubusercontent.com/2095637/141352707-5aa8f387-6a15-4eb1-9825-c670c73956a4.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1274

### Are you using any scripts or extensions?

No

**Comment by drewhoener** [comment]
+1
Experiencing the same issue v1.0 ?1274

**Comment by kevolaf** [comment]
I have the same issue in Steam, my work around for the time being is find an item that you have a lot of and slide that bar over to the max. It should stick for the rest of your items now as long as you don't move the slider bar again.
I have 1000k+ Ancient Runes so I slid that bar over to the max. Now my smaller stacked items, such as bones, are automatically set to max. Hope that helps for the time being.

**Comment by skha129** [comment]
Can confirm same behaviour exists for iOS version

**Comment by QuiGonJones** [comment]
Same issue for me. on Opera GX (chromium) browser. No scripts/extensions.
Beta v1.0
?1274

**Comment by MelvorIdle** [comment]
The intial issue is fixed where it would not default to max when selecting the item.

However, the qty will remain the same if your selection does not change. Eg. if you have Bones selected, and acquire more in your bank, it will not readjust to max - it stays at the quantity you have selected.

Best thing to do is to select a different item and return back to the original.

Closing this for now, as it is currently intended to do this.
