### ISSUE TITLE
[Bug]: <tasks(eg mine coal) not continuing>

### ISSUE THREAD

**Issue by DrPsyc** [MelvorIdle/melvoridle.github.io#1644]
### Describe the bug

I'm not sure, but believe that it happens when I go idle. If I'm mining, smiting, etc it does not continue.

I've left multiple tasks running today, to come back to nothing being done. 

### Reproduction Steps

Using an lgv60

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1274

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Potentially related to #1647
