### ISSUE TITLE
Undefined Translation: Menu_Text

### ISSUE THREAD

**Issue by Macaboros** [MelvorIdle/melvoridle.github.io#1646]
### Describe the bug

Title text appears when viewing items with the “View Item Stats” option from the equipment or bank interface.

### Reproduction Steps

1. Click item
2. Click “view item stats.”

### Expected behaviour

Provide relevant item description.

### Screenshots

![9489C3C3-A0C6-464D-AC40-36685FA976DF](https://user-images.githubusercontent.com/94121205/141374267-f7b846c2-d26e-4e4b-a820-e71ae0cd31b0.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

.22

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is now fixed
