### ISSUE TITLE
[Bug]: Quantity slider opens left skills frame

### ISSUE THREAD

**Issue by Valestyne** [MelvorIdle/melvoridle.github.io#1648]
### Describe the bug

The skills panel opens when sliding right to  selecting quantity of a bank item. Inconsistent.

### Reproduction Steps

Go to bank
Select any item
Slide quantity from 1 to maximum

### Expected behaviour

Skills frame stays closed

### Screenshots

![Screenshot_20211111-173742_Melvor Idle](https://user-images.githubusercontent.com/61170424/141384121-4db5d37d-608e-4612-bee8-c2dfc57dcc75.jpg)
![Screenshot_20211111-173748_Melvor Idle](https://user-images.githubusercontent.com/61170424/141384125-a312652e-1f43-4f82-919e-a1c2a48cf0f7.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

1270

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is now fixed
