### ISSUE TITLE
Wiki and bug report open ontop of the game, its bad!

### ISSUE THREAD

**Issue by 1337Yogi** [MelvorIdle/melvoridle.github.io#1649]
### What is your suggestion?

When launching the wiki or the report bug rather than  opening over the game it should open in a new window via the Internet browser like it used too. 

Please note I play the game through my mobile.

### Why are you suggesting this?

Annoying that you have to close the game down to get back after going on the wiki through the game (or to report a bug/make a suggestion).

### How does your suggestion benefit the game?

I belive the game play was better before this new way was introduced, I do not like having to close my game down to get back on.

**Comment by rapbit0** [comment]
+1

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
