### ISSUE TITLE
Chance to hit not updating when switching stances

### ISSUE THREAD

**Issue by Seamooo** [MelvorIdle/melvoridle.github.io#165]
**Describe the bug**
Chance to hit does not update when switching stances with differring stats

**To Reproduce**
1. Equip a weapon that changes stats based on stance (e.g. Dragon 2H sword)
2. Go to combat and begin fighting any enemy
3. Switch stance between two stances that give different stats
4. Notice that although accuracy rating changes, chance to hit does not change

**Expected behavior**
When switching stances, such that accuracy rating changes, the chance to hit is recalculated

**Screenshots**
![image](https://user-images.githubusercontent.com/48548685/78168719-03b5b800-7483-11ea-80de-19e4d0245cb5.png)
![image](https://user-images.githubusercontent.com/48548685/78168777-17611e80-7483-11ea-9a9a-30a446ef204f.png)

**Browser**
Google Chrome 80.0.3987.149 (Official Build) (64-bit) (cohort: Stable)

**Console output**
```
www.googletagmanager.com/gtag/js?id=UA-129674422-1:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
2pagead2.googlesyndication.com/pagead/js/adsbygoogle.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
save.js?260:46 Loading Save Game...
save.js?260:207 Save Game Loaded...
save.js?260:46 Loading Save Game...
save.js?260:207 Save Game Loaded...
smithing2.js?260:189 Loading Smithing...
mastery.js?260:181 Updating Masteries
mastery.js?260:23 Loading Masteries...
main.js?261:1099 Game Loaded
oneui.core.min.js?205:6 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ oneui.core.min.js?205:6
cloud.js?260:46 Melvor Cloud Connection: Success
save.js?260:46 Loading Save Game...
save.js?260:207 Save Game Loaded...
cloud.js?260:151 41016678.5200001
cloud.js?260:152 41020169.5200001
cloud.js?260:154 Loaded Local save
smithing2.js?260:189 Loading Smithing...
mastery.js?260:181 Updating Masteries
mastery.js?260:23 Loading Masteries...
main.js?261:1099 Game Loaded
VM1126 index.php:1 A cookie associated with a cross-site resource at http://puu.sh/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
```

**Comment by iHeartZigg** [comment]
Adding to this, it does not update when using potions/new accuracy rating.

Perhaps it is only updated when a new monster is summoned.

Possible fix, check for changed accuracy rating or switched stance?

**Comment by MelvorIdle** [comment]
Fixed in coming Minor Update
