### ISSUE TITLE
[Bug]: Astrology not updating Active Modifiers

### ISSUE THREAD

**Issue by Pandorian6008** [MelvorIdle/melvoridle.github.io#1650]
### Describe the bug

When training Astrology the Active Modifiers doesn't show all effects, you have to go into the individual Constellation to get them to appear on the "View All Active Modifiers" page.

Before going into constellations: 
![image](https://user-images.githubusercontent.com/75744619/141388040-e541e450-7382-4268-941d-bd9c93cb53d4.png)

After going into constellations:
![image](https://user-images.githubusercontent.com/75744619/141388137-dbeddb0c-866e-4f63-84f2-296d098b1f6c.png)

### Reproduction Steps

1. Go Astrology
2. Train Skill until new constellation is unlocked or Mastery threshold unlocks new star.
3. Click "View All Active Modifiers"
4. Go into newly unlocked constellation
5. Look at "View All Active Modifiers" again.

### Expected behaviour

I expected the "View All Active Modifiers" to update even if I hadn't been in the constellation itself to see what the passives were.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1274

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
A hotfix has now been applied to the game to address most of the issues around this relating to Mastery level ups not activating bonuses.
