### ISSUE TITLE
[Bug]: Astrology not rolling combat skill XP standard modifiers

### ISSUE THREAD

**Issue by TJOak** [MelvorIdle/melvoridle.github.io#1651]
### Describe the bug

In the Astrology skill, it _seems_ like the standard modifiers that give skill XP bonuses to combat abilities are not appearing. Rerolling two standard modifier slots 50 times for the Terra constellation, for example, did not produce any Strength skill XP bonuses.

Based on this reddit post: https://www.reddit.com/r/MelvorIdle/comments/qro0on/astrology_combat_skill_xp_modifiers/

### Reproduction Steps

1. Go to Astrology
2. Explore Terra  (most likely constellation with a skill XP bonus for a combat skill)
3. "Reroll all standard modifiers" until you get a Strength skill XP modifier

### Expected behaviour

A Strength skill XP modifier will appear at some point

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1275

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Fix has been pushed to the game
