### ISSUE TITLE
[Bug]: Impending Darkness book should come after the event completion

### ISSUE THREAD

**Issue by Pratoil** [MelvorIdle/melvoridle.github.io#1652]
### Describe the bug

The book is meant for after the completion of the event and has no place before, pls change thx. You are meant to get "Beginning of the End" first

### Reproduction Steps

Uh I think everyone got it after something

### Expected behaviour

Once you defeat Ahrenia and have reached the Max Cape you should be given "Beginning of the End" which is the pt 3 book, Impending Darkness comes after.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1279

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Hotfixed
