### ISSUE TITLE
[Bug]: New prayer levels prevent deselecting prayers that are now above skill level

### ISSUE THREAD

**Issue by IgiCodes** [MelvorIdle/melvoridle.github.io#1653]
### Describe the bug

Two of the prayers I had active are now above my skill level but are still selected as 'active' and can't be unselected nor can other prayers be activated instead due to the max 2 prayers limit.
I seem to still be gaining skill points though so luckily once I've got a high enough level I should be able to deselect them but stuck with them until then.

### Reproduction Steps

As a user
When I have two prayers active that are above my skill level due to previous level requirements
And I try to deactivate these prayers
Then the prayers can not be deactivated

### Expected behaviour

I can deactivate the active prayers
OR
The active prayers that are above my skill level are automatically deactivated

### Screenshots

![image](https://user-images.githubusercontent.com/9021865/141397055-a23f2633-5d9f-4933-b639-678d2f551af8.png)

### Console output

No output/logs on action

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

1279

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
You can click these icons to disable them: https://puu.sh/IoPg0/4e5ab90570.png
