### ISSUE TITLE
[Bug]: Cloud not loading

### ISSUE THREAD

**Issue by XWillemX** [MelvorIdle/melvoridle.github.io#1654]
### Describe the bug

'Connection established. Fetching Cloud Saves...' Doesnt load cloud saves.

### Reproduction Steps

Open Melvor from Taskbar (Windows 10)
Cloud will now never load.

This started happening around the premium change launch.

Can be 'fixed' by opening steam, and running Melvor via steam.

### Expected behaviour

Cloud save file should load and be available to log into

### Screenshots

https://gyazo.com/d2ee1c89988937dc50e47258bad9fce6

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1281

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
I have just applied a hotfix to the game for this.

Not need to update the client via Steam, this was an issue caused within the game itself.
