### ISSUE TITLE
[Bug]: Scaled Shield requires Magic level, not ranged

### ISSUE THREAD

**Issue by IsaacGraham** [MelvorIdle/melvoridle.github.io#1656]
### Describe the bug

The new Scaled Shield shows as requiring lv80 Magic rather than Ranged.

### Reproduction Steps

Obtain and inspect a Scaled Shield

### Expected behaviour

Ranged level required

### Screenshots

![Screenshot_20211112-134431](https://user-images.githubusercontent.com/5593732/141406960-7b5a1c19-d061-4ab4-9af0-d2805ed5b538.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1274

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Hotfix has been applied
