### ISSUE TITLE
[Bug]: Astrology effect, chance to receive elemental runes while making runes does not work

### ISSUE THREAD

**Issue by Nuhji** [MelvorIdle/melvoridle.github.io#1658]
### Describe the bug

So I managed to get the +1% chance to receive random Elemental Runes from Runecrafting when creating Runes from Astrology, but I've spent a few hours and I haven't seen it proc even once

### Reproduction Steps

1. Get the astrology effect for receiving Elemental Runes while creating Runes
2. Attempt to make runes for a while and no extra will appear to be created

### Expected behaviour

I expected when I came back to have gained at least a few air/fire/water/earth runes after spending a few hours doing runecrafting, but I still came back to only having gained the rune I'm creating (primarily death currently)

### Screenshots

my astrology page showing I have the effect
![image](https://user-images.githubusercontent.com/94157244/141410759-e97984aa-1112-488a-aca8-cabd1cec647f.png)

after an hour it's not showing me having gained any other runes, this was around 2090 runecrafts worth (and double checking bank seemed to show the same air/fire/water/earth counts)
![image](https://user-images.githubusercontent.com/94157244/141417103-6735a184-e892-4be5-b631-a1c8e9efdfa5.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1283

### Are you using any scripts or extensions?

No

**Comment by Nuhji** [comment]
as of subversion ?1285 I just saw it proc while active, but it gave 0

**Comment by MelvorIdle** [comment]
Fix has been applied to the game
