### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'CHARACTER_SELECT')

### ISSUE THREAD

**Issue by FluidSense** [MelvorIdle/melvoridle.github.io#1659]
### Describe the bug

As I start the game, I am stuck at this error screen with a spinner on top. I have done no changes since last night, where I played the beta successfully. Now I cannot even see the version number before it crashes.

### Reproduction Steps

1. Start game
2. Finish initial loading
3. See error message

### Expected behaviour

1. Start game
2. Finish initial loading
3. Play game!

### Screenshots

![](https://user-images.githubusercontent.com/22146437/141414777-b975e23c-da45-4f94-86c2-931178ed3b3d.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

N/A

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Does this occur on every load, or was this a once off?

**Comment by FluidSense** [comment]
Every load

**Comment by MelvorIdle** [comment]
And is this your first load into the game since the update dropped yesterday?

**Comment by FluidSense** [comment]
No, I played a lot yesterday, even reached 70 or so in Astrology! 😄

**Comment by FluidSense** [comment]
This is a recording of how far I get (converted to gif for display here - it does not loop, I am just stuck at the error).
![melvorerror](https://user-images.githubusercontent.com/22146437/141463102-7c7f92ab-80a0-4271-a38e-5aeb33869ea3.gif)

**Comment by MelvorIdle** [comment]
Is this still occurring today with new fixes applied to the game?

Also, please reinstall the app as well to see if that fixes it.

**Comment by FluidSense** [comment]
I couldn't lose all this precious idle-time, so I took a risk and emptied the app cache. That solved the problem ⭐ Should've updated here afterwards, my bad.
