### ISSUE TITLE
3

### ISSUE THREAD

**Issue by Chrisazy** [MelvorIdle/melvoridle.github.io#166]
**Describe the bug**
Compost and Gloop All actions require you to have the 2000 GP, but don't actually charge you for their actions, making it free.

**To Reproduce**
1. Go to the farming tab with more than 2000 coins
2. Click Compost All or Gloop All with at least one empty patch

**Expected behavior**
Compost or Gloop is applied and user is charged 2000 coins

**Screenshots**
The relevant code is at farming.js:810 and it looks like any sort of charging is simply omitted.

**Comment by Chrisazy** [comment]
Shout out to accidentally hitting "Enter" and submitted the worst bug report of all time.

**Comment by MelvorIdle** [comment]
Fixed in coming Minor Update
