### ISSUE TITLE
[Bug]: Cloud Account not working on mobile

### ISSUE THREAD

**Issue by rapbit0** [MelvorIdle/melvoridle.github.io#1660]
### Describe the bug

Hello,

First of all, thanks for your awesome game and all the time and effort you put into this :)

Now to the Bug:

I'm on Android Version 9(EMUI 9.1.0)

Since the new Update, my Cloud Account is not working anymore - Cloud saves are not possible anymore and it also doesn't load any saves on the character selection screen. 

When I check my Account in the character selection screen, it always says "Hi username" and not showing any of my data. Also the "Connection established. Fetching cloud saves..." message runs forever and never stops. I have tried logging out and back in and it doesn't work, same result. I tried logging in in the browser and it works just fine but my last cloud save there is from before the update. 
Also in game when checking my cloud account it says "Logged in as: null" 

I have attached Screenshots bellow, one one Screenshot I have tried to click Force Save, the button is getting bigger but as you can see without any result. No pop-up nothing. 
After starting the game the Last cloud save update time updates but it is not. When I check on my tablet, the last save is still from before the update. 

It's not that big of an issue but it would be cool to get it back some time :) 

If there is anything you need, debugs, log files, more info etc. Just let me know! 

Have a great days, cheers 

Loup

Ps: where do I found the saves I downloaded in the character selection screen? I have checked every folder on my phone but can't seem to find it? 

### Reproduction Steps

1. Login to your cloud account
2. Check profile, shows "Hi username" 
3. Can't load cloud save 
4 .??? 
5. Don't profit ;) 
6. Load local save because Melvor is awesome and enjoy the game :) 

### Expected behaviour

Beeing able to load my cloud save as well as save to the cloud

### Screenshots

![Screenshot_20211112_085623_com malcs melvoridle](https://user-images.githubusercontent.com/17923536/141431334-0c4ec12d-86ce-4b94-a7aa-a3a110130e07.jpg)
![Screenshot_20211112_085628_com malcs melvoridle](https://user-images.githubusercontent.com/17923536/141431349-fb7343b3-a8dc-45dc-b3c4-f40cccaaad31.jpg)
![Screenshot_20211112_085705_com malcs melvoridle](https://user-images.githubusercontent.com/17923536/141431359-456d165d-5cb2-49c6-85da-950bad92579b.jpg)
![Screenshot_20211112_085715_com malcs melvoridle](https://user-images.githubusercontent.com/17923536/141431363-8edd940a-1816-4e7a-8152-16791ded6de0.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?42069 / ?1285

### Are you using any scripts or extensions?

No

**Comment by rapbit0** [comment]
It seems to be working again! Did you fix it? Thanks a lot

**Comment by MelvorIdle** [comment]
Let's pretend I did :P
