### ISSUE TITLE
[Bug]: goblin raid mage weapons

### ISSUE THREAD

**Issue by Zamorak0** [MelvorIdle/melvoridle.github.io#1661]
### Describe the bug

During the goblin raid. Anytime I would choose a magic weapon it switches it to a bronze scimitar. Its happened to me every time I try to run a mage combat style for it. Im not sure but I would only notice it after I picked a spell so it could be from doing that as well. 

### Reproduction Steps

1.go to goblin raid 
2. Start the raid 
3. After winning, select weapon 
4. If it pops up choose any decently strong mage weapon.
5. Possibly have to choose a spell for it to happen 

### Expected behaviour

I expected to be able to use the mystic air staff for example but instead I got equipped a bronze scimitar

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.21

### Game Subversion

(?1109)

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
The weapon is replaced with a sword due to you not having enough runes to cast the selected Spell.

This is something we will be addressing in future Golbin Raid updates.

**Comment by Zamorak0** [comment]
It's happened now with a regular melee weapon as well.
