### ISSUE TITLE
[Bug]: Significant loading time when exporting save data twice

### ISSUE THREAD

**Issue by maxizoita** [MelvorIdle/melvoridle.github.io#1662]
### Describe the bug

When you press export save and get the text to copy the save data once, it functions as normal. However, if you do it again and don't remove the already existing text, the game will freeze for around 2 minutes. This doesn't happen if very minimal things changed in between you exporting the save, so you have to make a few changes to make sure the save data changes (i.e switching skills).

### Reproduction Steps

Start a new session of Melvor Idle
Go to Settings
Export Save
Return back to the game
Do a different task to change save data (i.e. if you were skilling crafting on your first export save, do any other skill)
Export save again (with old save data remaining inside)
Melvor Idle will freeze for ~2 minutes

### Expected behaviour

Should just output the save text without freezing the game. **It can be manually fixed by removing the saved data before exporting the save a second time.** 

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1285

### Are you using any scripts or extensions?

Yes

**Comment by MelvorIdle** [comment]
I am unable to reproduce this bug. Can you confirm if this bug occurs in incognito mode without any extensions enabled?
