### ISSUE TITLE
[Bug]: Tutorial Task -Magic Preparation 4

### ISSUE THREAD

**Issue by Hellscaretaker** [MelvorIdle/melvoridle.github.io#1663]
### Describe the bug

he task is: Kill 1 using magic, however the task is also completed when killing a golblin with range not possble to complete using magic

### Reproduction Steps

Reproduction Steps
be at Task -Magic Preparation 4
kill not using magic
switched to range weapon
killed goblin

### Expected behaviour

Only compleet task when using magic.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1285

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This does not occur for me, are you still seeing this issue?

**Comment by MelvorIdle** [comment]
I have confirmed this bug only occurs for those who made it to this step of the tutorial prior to the fix being introduced a few days ago. All new account created with the fix will not see the bug.
