### ISSUE TITLE
[Bug]: offline combat not working

### ISSUE THREAD

**Issue by levgre** [MelvorIdle/melvoridle.github.io#1665]
### Describe the bug

When I do offline combat, I don't get the full time period of combat progress, it seems to stop very shortly (maybe after loot fills up?) Also, game auto-loots when i start game back up.  

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

1285

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Are you dying offline by chance?

**Comment by levgre** [comment]
Nope, not dying at all






On Friday, November 12, 2021, 06:32:30 PM CST, Melvor Idle ***@***.***> wrote: 







Are you dying offline by chance?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by levgre** [comment]
Now I am immediately kicked out of combat when I leave the game, there is no looting when I re-enter the game like before

**Comment by MelvorIdle** [comment]
Many fixes for various offline progress issues have been released over the last few months. Please ensure you are running at least v1.0.3 (?1843).

Please open a new issue if the problem persists.
