### ISSUE TITLE
Solved: Cannot clear cooking stockpile

### ISSUE THREAD

**Issue by skha129** [MelvorIdle/melvoridle.github.io#1667]
### Describe the bug

I cooked chicken actively while cooking herring passively. I log in a few hours later when all of my hearing had been passively cooked.
I tried to collect from stockpile but clocking on the stock pile does not empty it.
I tried cooking a different fish passively but it won't let me sure to the herring in the stockpile

### Reproduction Steps

1. Go to cooking.
2. Cook chicken actively and herring passively
3. Log back in when all your herring has been cooked
4. Go to cooking again and try to clear your stockpile

### Expected behaviour

Stock pile should be cleared when you click on it

### Screenshots

![Screenshot_20211113-062425](https://user-images.githubusercontent.com/68756457/141509519-85589eb8-902e-49d4-bf96-4eb944a7e196.jpg)
![Screenshot_20211113-062434](https://user-images.githubusercontent.com/68756457/141509528-9835478d-9d21-4692-ba60-2f49d62f3665.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1285

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Is your bank full, so you can't collect from the stockpile?

**Comment by skha129** [comment]
Apologies. Might be a slight change to the UI behaviour. I was not clicking on the"Collect from Stockpile" button, but rather, the items in the stockpile themselves
