### ISSUE TITLE
[Suggestion]: Take farming out of tutorial island

### ISSUE THREAD

**Issue by Pwusa** [MelvorIdle/melvoridle.github.io#1668]
### What is your suggestion?

![CB59D912-32B6-4A70-8DB3-CF7E8BF89228](https://user-images.githubusercontent.com/91908822/141515282-45fe5d63-5fd7-4bf2-981e-6d36f26269bd.png)
Atleast for adventure character where skills are locked, I will have to deal will this flashing ‘harvest’ notification from farming until I chose to unlock the skill. 

### Why are you suggesting this?

clearly this is not a major issue but more a slight nuisance 

### How does your suggestion benefit the game?

clearly this is not a major issue but more a slight nuisance

**Comment by MelvorIdle** [comment]
Hmm, good catch. Instead of removing it from the tutorial I can simply remove the notfication from appearing if the skill is locked.

**Comment by MelvorIdle** [comment]
This suggestion has now been implemented
