### ISSUE TITLE
[Suggestion]: Additional Mobile Push Notifications

### ISSUE THREAD

**Issue by kfbest** [MelvorIdle/melvoridle.github.io#1669]
### What is your suggestion?

Push notifications for when an offline action stops for any reason. Possible examples are:

- Death
- Dont have enough resources
- Slayer Task is done (if AutoSlayer off/not bought)

### Why are you suggesting this?

would be nice to see if I need to switch to a new task

### How does your suggestion benefit the game?

Just like the farming notification helps players to know its time to start new planting, this would allow players to know if their current skills training have stopped.

**Comment by rapbit0** [comment]
Do the notifications actually work? I'm just curious because I have never had a notification before. I always do plant all and I have just checked, the app has permissions and notifications are enabled aswell

**Comment by MelvorIdle** [comment]
Due to how the game works where all calculations are done when you log into the game, these kinds of notifications do not work.
