### ISSUE TITLE
Fishing Amulet Potentially Bugged

### ISSUE THREAD

**Issue by AnnoRagnarok** [MelvorIdle/melvoridle.github.io#167]
Real-world testing of whale fishing gives a result of around 1090 raw whales/hour when averaged over 14 hours with:
Signet ring,
Fishing cape,
66 mastery, 
Fishing amulet

Theoretically this number should be more like 1360.

In addition, if the amulet of fishing is disabled, the theoretical result is 1079 whales/hour. Due to the fact that the theoretical with the amulet disabled and the real world test is very close, there's reason to believe that the amulet of fishing is bugged.

**Comment by MelvorIdle** [comment]
Hotfixed
