### ISSUE TITLE
[Bug]: Agility Cost Reduction

### ISSUE THREAD

**Issue by IndexIllusion** [MelvorIdle/melvoridle.github.io#1671]
### Describe the bug

When in the agility obstacle selection menu, the displayed cost for an obstacle does not reflect the current effects of that obstacle's cost reduction. Unfortunately I have no way to tell right now if the issue is the cost of the obstacle not being updated accordingly or if its the interface not showing the adjusted cost. (new playthrough and no GP to test) 

### Reproduction Steps

1. Go to obstacle selection menu
2. Purchase obstacle to apply +4% item cost reduction
3. Switch to different obstacle in same selection
4. Open obstacle selection menu once more and see error

### Expected behaviour

The cost for the obstacle should show the cost after being adjusted by the cost reduction modifiers. In my case specifically, the original cost of the obstacle was 10,000 GP, but even with a cost reduction of 4% for that obstacle, it still shows 10,000 GP as the cost and not the expected cost of 9,600 GP.

### Screenshots

![image](https://user-images.githubusercontent.com/53729381/141531835-a64d8059-1972-48a4-b804-5c474ad4c1a7.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1285

### Are you using any scripts or extensions?

No

**Comment by TJOak** [comment]
That's an "_item_ cost reduction", which is different from the general "cost reduction," which affects GP/Slayer coin cost. (Later obstacles require resources other than GP to build.)
