### ISSUE TITLE
[Bug]: <title> Can’t log in

### ISSUE THREAD

**Issue by Goodie50** [MelvorIdle/melvoridle.github.io#1673]
### Describe the bug

populateMasteryObject@https://melvoridle.com/assets/js/game/mastery2.js?1285:4:31
updateWindow@https://melvoridle.com/assets/js/game/main.js?1285:4:264
finaliseLoad@https://melvoridle.com/assets/js/game/main.js?1285:372:13
selectCharacter@https://melvoridle.com/assets/js/game/main.js?1285:363:185
onloadEvent@https://melvoridle.com/assets/js/game/save.js?1285:61:232
https://melvoridle.com/assets/js/game/save.js?1285:66:382
https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84826
each@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:2971
https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84807
r@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:28088
fireWith@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:28852
c@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:79495
https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:81938

### Reproduction Steps

Cannot log in, try refresh & doesn’t work

### Expected behaviour

To be able to log in

### Screenshots

.

### Console output

.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

Can’t check

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Hey, couple of questions here:
Can you export your save from the character select screen and paste it here? Settings -> Export Save.

If you receive this error again, can you open your browser console and show us it's contents? On chrome you should be able to do this by pressing "CTRL+SHIFT+J",

**Comment by Goodie50** [comment]
Not sure what happened but randomly works now
