### ISSUE TITLE
[Bug]: Cloud  save failed Error:Not Authenticated

### ISSUE THREAD

**Issue by dayoe** [MelvorIdle/melvoridle.github.io#1675]
### Describe the bug

I have noticed that sometimes when I click the force save button, I get the alert Cloud Save Failed Please try again by clicking the "Force Save" button. Error Not Authenticated. If I try to press the force save button again the same error reappears. I do not know what causes this error, but I have experienced it on both of my characters. It seems that the only solution is to refresh the page (playing on web browser) and hope that the progress was saved.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1274

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Do you by chance have the game open for longer than 24 hours at a time?
