### ISSUE TITLE
[Bug]: Stale XP display when xp modifiers change

### ISSUE THREAD

**Issue by mattrunyon** [MelvorIdle/melvoridle.github.io#1676]
### Describe the bug

Woodcutting, fishing, firemaking, mining, and alt magic do not update the shown XP gained on an action when any XP modifier is applied/removed (jewelry, agility obstacle). I am guessing woodcutting is a bug since it has an updated XP display, but the others may be pending updates to show XP/master XP gained.

For astrology, the XP gained display value is stale only when an agility obstacle is changed. The value is refreshed when a constellation is studied, but only for that constellation (the others remain stale). Exploring a constellation has no effect on the freshness of the value. XP modifying objects update immediately and for all constellations.

### Woodcutting/Fishing/Firemaking/Mining/Alt Magic
1. Change some item that affects global XP (equip/unequip ring of skills, build an agility obstacle, etc.)

### Astrology
1. Change an agility obstacle that affects global XP modifier (or delete 1st obstacle while having other global XP modifier obstacles active)
2. Change to astrology tab
3. Study a constellation (this fixes the issue for that constellation)

### Woodcutting/Fishing/Firemaking/Mining/Alt Magic
Displayed XP earned for each item is modified to show the effects of your global XP modifying items. All (except woodcutting?) may be intentional as they haven't been updated yet like smithing/fletching/crafting/etc.

### Astrology
Displayed XP earned for each constellation is updated to show effects of agility XP modifiers

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1290

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.0.3.
