### ISSUE TITLE
Astrology Ameria Firemaking change

### ISSUE THREAD

**Issue by NototoHoshi** [MelvorIdle/melvoridle.github.io#1677]
### What is your suggestion?

The Astrology constellation Ameria (fishing and firemaking) has a star bonus: +5% chance to double items in firemaking, which is kinda useless, since firemaking is a skill that doesnt produce anything (except maybe the coal when wearing the skillcape).

Perhaps changing it to +5% chance to preserve resources when firemaking (not burning the log) would make more sense.

Another option would be to slightly rework the coal / skillcape thing... Perhaps if the chance to receive coal when firemaking was built into the skill by default - for example: normal logs have 5% to produce coal when burnt, oak logs have 10% to produce coal and so on. Then the constellation star bonus could be: +5% chance to produce coal, and the skillcape bonus could be changed to either something completely different or it could be changed to double the coal.

### Why are you suggesting this?

Because the bonus is currently pointless.

### How does your suggestion benefit the game?

It provides more competitive options when rerolling the star bonus.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
