### ISSUE TITLE
[Bug]: Offline progress lost

### ISSUE THREAD

**Issue by jittarao** [MelvorIdle/melvoridle.github.io#1678]
### Describe the bug

 I had almost 14 hours of offline progress disappear completely because after I selected the character on the character selection screen, I switched to a different tab and a minute later switched back to Melvor. It ignored the 14 odd hours of progress and only calculated the last 1 minute of offline.

I had 52M gold and spent all theiving mastery xp above 95% before I ended my last session. And it's exactly where it is now after 14 hours.

### Reproduction Steps

1. Click your character on the selection screen
2. Immediately switch tab
3. After a minute, switch back to Melvor
4. Only your one minute offline progress will be calculated

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1290

### Are you using any scripts or extensions?

Yes

**Comment by MelvorIdle** [comment]
Many fixes for various offline progress issues have been released over the last few months. Please ensure you are running at least v1.0.3 (?1843).

Please open a new issue if the problem persists.
