### ISSUE TITLE
[Bug]: Astrology Smithing Interval not applied

### ISSUE THREAD

**Issue by Mantranero** [MelvorIdle/melvoridle.github.io#1679]
### Describe the bug

Smithing Interval doesn't get reduced from Iridan Sign. Or better said it will not be displayed in the timer. If it is calculated into the interval, the timer for the smithing product isn't reduced. And I am unable to determin which it is between the two.

### Reproduction Steps

get smithing interval reduction in irdan sign
nothing happens

### Expected behaviour

timer and interval is shortened

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1290

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
It is applied, the game just needs a refresh to update the visuals. Will look into updating the interval dynamically.
