### ISSUE TITLE
Bit of a memory leak AND loss of offline progression

### ISSUE THREAD

**Issue by Cadbury847** [MelvorIdle/melvoridle.github.io#168]
**Describe the bug**
You're getting 2 bugs in one since I believe what I'm seeing is broken for the same reason.
 When you get the popup box telling you what you gained whilst offline (example: image 1), if you close the box by clicking to the side of it (so not hitting ok, not clicking within the box, clicking elsewhere on the page like where the red cross is in image 2) then you don't actually gain what it has said you have gotten since you were away. Nothing goes to your bank, you don't gain any of the xp, I've not checked potion charges but I'd imagine they also weren't used up. Not sure why it closes when you click away, but the issue is it doesn't go through the functions which give you your items and xp - effectively losing all of this progress.

The memory leak happens for the same reason, from here it just seems like assets aren't cleared when you close the popups by clicking to the side / elsewhere on the page.  It's most noticeable if you open and close the Item log a couple of times in this way, as transitions between skill pages (flicking between bank, woodcutting ,fishing, shop, etc) starts to be delayed more and more, suggesting high memory usage. Again, I believe this is due to the popup interfaces not correctly being cleared up as they are not closed in the intended way, but I've lost quite a few nights progress from this.

**To Reproduce**
First one:
1. Start skilling on anything, such as woodcutting
2. Close and reopen (or refresh) the tab so that it triggers an offline progress popup
3. Click to the side of the progress popup instead of clicking "OK"
4. Compare your bank and skill xp before and after doing this - you won't have gained the offline progress.

Second one:
1. Do a benchmark test to see how fast it swaps pages/tabs
2. Open items log popup (Doesn't have to be this one, but this is one of the biggest and hence fastest to check this bug with)
3. Close it by clicking off to the side (not the cross)
4. Repeat it a few times
5. Swap between pages/tabs again, compare speed to benchmark. Should be noticeably slower.

**Expected behaviour**
Items and XP are still gained instead of being lost.
The popups are properly cleared without performance issues.

**Screenshots**
First just to clarify:
![image](https://user-images.githubusercontent.com/56396053/78488944-d0538180-773f-11ea-8fd7-50f2f63e6257.png)
Second showing generally where to click to improperly close:
![image](https://user-images.githubusercontent.com/56396053/78489731-08f35b00-7740-11ea-90bd-480295b6aaf6.png)

**Browser**
Most recent Chrome as of 05/04/2020

**Console output**
No visible changes between closing them properly and improperly, so not relevant. 

_______________________________________________________________
Small note to say thanks for the amazing game, keep it up!

**Comment by rekwah** [comment]
I'm having a very similar issue with Chrome. No overnight progress despite force saving. For example, set to chop magic last night. Logged in this morning and first off, it no longer gives me the option to select from local or cloud save, and second, i wasn't chopping any logs or on any skill. A little bummed, as this has happened several times to me too and caused loss of progress. :(

**Comment by MelvorIdle** [comment]
Can you please confirm the first bug is actually accurate?

The way it is coded is that all the items and XP are given to you _before_ the popup appears. That popup is simply telling you what the game just gave to you. Clicking OK does nothing other than close the box.

**Comment by Cadbury847** [comment]
Cannot confirm that it still happens, currently unable to repeat it. 
It occurred quite a few times and every time it was when I closed the popups in that way, though of course if things are given before it appears then there was something else behind it. The last time it happened to me was ~50 hours ago from this comment. Got a friend who thinks its cloud save vs local save related, but I was convinced it was this
