### ISSUE TITLE
[Bug]: Obsidian cape doesn't have proper defensive stats

### ISSUE THREAD

**Issue by ariebary** [MelvorIdle/melvoridle.github.io#1680]
### Describe the bug

The obsidian cape appears to be defective. 
The stats aren't properly corresponding to range or defense levels.
Currently, it shows as only +0 when viewing stats pre-equipped. During equip it also shows at +0.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

Most recent beta 1.0

### Are you using any scripts or extensions?

No

**Comment by IdlerSam** [comment]
This appears to just be an issue with how it is displayed in the equipment pane. The cape does actually provide evasion stats if you view the combat stats in the combat tab. 

At 72 Defence, I went from 37,376 without it -> 42,632 melee evasion with it and the chance the enemy had to hit me dropped from 2% to 1%.

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
