### ISSUE TITLE
[Bug]: Skilling minibar descriptions are clipped off screen in Steam

### ISSUE THREAD

**Issue by CarlDeadman** [MelvorIdle/melvoridle.github.io#1681]
### Describe the bug

When i move the cursor to a skill benificial item(e.g. Bob's rake, Sneak-ers, Goblin mask etc.) on the right side of the screen, the description appears central relative to the item's position, and half the text is offscreen. The scroller at the bottom of the screen also appears, clearly indicating that the description is accessible, but only if you scroll the page to the right. And even when you do scroll the page to the right, the item keeps on the right side of the screen, so you can scroll for an infinite amount of time, but you won't ever get to read the item description as intended(unless you're accessing it from the inventory, but that doesn't apply to the bug).

### Reproduction Steps

1. Go to any skill in which you have any item that benefits the skill(even pets have this problem).
2. Move your cursor on the item to display it's description.
3. Try moving the page with right arrow.

### Expected behaviour

Before one of the updates(i think it was the one with Cooking skill rework), the item description would be intentionally displaced to the left, so it wouldn't leave the accesible screen. But after that this issue appeared, never to be addressed.

### Screenshots

![image](https://user-images.githubusercontent.com/94245658/141655690-5af87b12-0319-4068-a065-b2054cb395fa.png)
Miner's helmet is perfectly visible in the menu to the right.
![image](https://user-images.githubusercontent.com/94245658/141655714-fe32f1ad-36d4-44a0-a4e0-2e63e555e051.png)
Miner's helmet is now covered by it's own description, half of the description is offscreen, and two scrolling bars appeared.
![image](https://user-images.githubusercontent.com/94245658/141655736-2e5979cb-8e89-415c-9d58-16268b0facba.png)
What happens when you try to move the bottom scroller to the right with right arrow key.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1290

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is due to the Zoom setting in steam. Currently working on a solution for that

**Comment by MelvorIdle** [comment]
Same bug as #497

Closing this to clean up.
