### ISSUE TITLE
[Bug]: <Some items are added to inventory when tapped in Conletion Log>

### ISSUE THREAD

**Issue by Smiti6** [MelvorIdle/melvoridle.github.io#1682]
### Describe the bug

Some items are added to the inventory when the user taps them in the Items section of the Completion Log.

### Reproduction Steps

1. Boot title.
2. Load save.
3. Open Cmpletion Log menu.
4. Open Items menu.
5. Tap on any Burnt item.

### Expected behaviour

No item is added to bank when the user taps an item in the Conpletion Log.

### Screenshots

![B43C5AA3-E810-4074-AA9A-49C28CF28AF0](https://user-images.githubusercontent.com/94255663/141660138-902b265f-9dd9-4edf-b16f-9683b0707c86.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1290

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
This is intended behavior for items that are no longer obtainable in game. Clicking on them in the item log will add it to your bank. This is so players that owned them in the past can re-obtain them if they wish.
