### ISSUE TITLE
[Bug]: Still stuck on infinite loading screen after patch 

### ISSUE THREAD

**Issue by queenmadea** [MelvorIdle/melvoridle.github.io#1686]
### Describe the bug

Hi!

I’m still stuck on the loading screen. I’ve tried switching from mobile data to wifi (that used to work before) but since the fix for the infinite screen that ‘trick’ doesn’t even work and I can’t get in at all. 

### Reproduction Steps

1. Click the app 
2. Stuck on screen
![Uploading 06EFE79E-2850-405F-BF26-91E277A565A7.jpeg…]()

### Expected behaviour

Expected the game to start and show my accounts/characters 

### Screenshots

As above

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

Can’t see it. App won’t open

### Are you using any scripts or extensions?

No

**Comment by queenmadea** [comment]
![Uploading C4844804-EACD-4AA6-93AB-FF517E8631AE.jpeg…]()

**Comment by MelvorIdle** [comment]
Hey, what iOS version are you running?

**Comment by queenmadea** [comment]
Hey! 14.8.1. I updated last night. I was one version before 14.8.1 (but still iOS 14) the game now loads but does take a while and requires reboot sometimes. Also, I find that switching between wifi and mobile data tends to prompt it to load. Any idea why? It’s not as urgent now because the game actually loads. Unlike before the update.

**Comment by MelvorIdle** [comment]
The switch of WiFi and Mobile Data is an Apple feature, which I cannot fix unfortunately.

Closing this issue now as initial issue is resolved
