### ISSUE TITLE
[Translation Error]: {gpVALUE}

### ISSUE THREAD

**Issue by Jistga** [MelvorIdle/melvoridle.github.io#1689]
### Which text in the game has a translation error?

Next to plant all selected crops, instead of the actual GP value and coin icon appearing, text of ${gpValue} appears. Not a huge issue at all, but thought I'd report it since this week is dedicated to fixing things like this before public release. Thanks!

Jistga

**Comment by MelvorIdle** [comment]
Hotfix has been applied. Thanks
