### ISSUE TITLE
Memory issue/Offline Progress

### ISSUE THREAD

**Issue by rekwah** [MelvorIdle/melvoridle.github.io#169]
**Describe the bug**
I will set to a skill for overnight, i.e chopping magics. Come back in the morning and no skills are set, no progress made, despite force saving the night before. I also no longer have the option to select from local save or cloud save (which maybe you did away with?). This has happened several nights in a row.

**To Reproduce**
Not 1000% sure what to do to reproduce, but it happens on a nightly basis.

**Expected behavior**
Expect to come back online to overnight progress on said skill.

**Browser**
Google chrome
Version 80.0.3987.163 (Official Build) (64-bit)

**Console output**
A cookie associated with a cross-site resource at http://google.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
index.php:1 A cookie associated with a cross-site resource at https://google.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
save.js?270:473 Not required to backup
save.js?270:47 Loading Save Game...
save.js?270:208 Save Game Loaded...
save.js?270:47 Loading Save Game...
save.js?270:208 Save Game Loaded...
smithing2.js?270:189 Loading Smithing...
mastery.js?270:181 Updating Masteries
mastery.js?270:23 Loading Masteries...
main.js?271:1104 Game Loaded
oneui.core.min.js?205:6 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ oneui.core.min.js?205:6
cloud.js?270:46 Melvor Cloud Connection: Success
save.js?270:47 Loading Save Game...
save.js?270:208 Save Game Loaded...
smithing2.js?270:189 Loading Smithing...
mastery.js?270:181 Updating Masteries
mastery.js?270:23 Loading Masteries...
main.js?271:1104 Game Loaded

**Comment by MelvorIdle** [comment]
I will reinstate the popup box.

**Comment by rekwah** [comment]
> I will reinstate the popup box.

Thanks for reinstating the load buttons, seems to have fixed the issue somehow. I was able to load back in properly after fire burning all night. All experience was there :)
