### ISSUE TITLE
[Suggestion]: Discard all button in combat

### ISSUE THREAD

**Issue by 10hpboii** [MelvorIdle/melvoridle.github.io#1690]
### What is your suggestion?

On reddit I commented that I didn't like how when you leave the area all the junk goes into your inventory.. who wants potato seeds? 

I suggest a 'discard all' button (in red) next to the 'loot all' button. 

### Why are you suggesting this?

With the new update, once you leave the area all items are sent to the bank. The issue is with many slayer tasks some items that drop are not desired, e.g. addy daggers, seeds of sorts, etc.

### How does your suggestion benefit the game?

It allows the player base to choose the items they want to keep before leaving combat moving to dungeoning. This also allows for better bank management and more saves play time rather than searching for all the poor items you've accumulated while offline.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
