### ISSUE TITLE
[Spelling/Grammar]: Siglis now have a Crafting use

### ISSUE THREAD

**Issue by PierreYvesFlamand** [MelvorIdle/melvoridle.github.io#1691]
### What text is wrong?

"Will be used as a Crafting resource in a future update" on the 3 sigils

![image](https://user-images.githubusercontent.com/46058408/141766490-452487d8-7423-45ad-97dd-59e408a5353f.png)

### What is the correct spelling or grammar?

Whatever you plan to write.

**Comment by coolrox95** [comment]
Sigil descriptions have been changed to "Used as a Crafting resource".
