### ISSUE TITLE
[Bug]: In-game progress is not saved correctly after importing a save to an already used character

### ISSUE THREAD

**Issue by MichalStokowski** [MelvorIdle/melvoridle.github.io#1692]
### Describe the bug

When selecting a character, there's a brief time window to click on the Settings. After the character has been loaded, any save can still be imported onto it. Once it's done, no progress on the X account will ever be saved. Making the game save manually or fixing the save in the settings does not solve the issue.

### Reproduction Steps

1. Launch the game.
2. Create character X.
3. Create character Y.
4. Export character Y and copy the code.
5. Select character X and click on Settings while it's being loaded.
6. When loaded to character X, click Import and paste the exported code of character Y.
7. Skip the tutorial.
8. Go to the character selection screen.
9. Observe that both characters are now character Y and all progress from character X has been lost.

### Expected behaviour

All in-game progress is always saved correctly.

### Screenshots

![image](https://user-images.githubusercontent.com/94367538/141779138-f85dc10e-fb22-4352-b419-ddb8ad8b3d98.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1315

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Hotfix has been applied to the game. The "Settings" and "Import" buttons will now be disabled during the character loading process.
