### ISSUE TITLE
[Suggestion]: Clear looting container

### ISSUE THREAD

**Issue by user8342912** [MelvorIdle/melvoridle.github.io#1693]
### What is your suggestion?

Allow contents of the looting container to be deleted, adding a 'Clear All' button next to the 'Loot All' button.

### Why are you suggesting this?

My bank is full and I can't afford anymore space. To free up looting container space I need to sell off an item collect the items 1 by 1 until the looting container is empty, i've already collected all the valuable items, the remaining items are junk which I don't need.

### How does your suggestion benefit the game?

A nice quality of life update for players.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
