### ISSUE TITLE
[Suggestion]: [Spend XP on Masteries] +10 when at level 1 should give +9 levels

### ISSUE THREAD

**Issue by Falroth** [MelvorIdle/melvoridle.github.io#1694]
### What is your suggestion?

Well, title says it all. It would be nice if the "+10" and "+5" levels when spending XP on masteries only gave +9 and +4 levels, respectively, **when the item is at level 1** as to stay always on a round number, considering most milestones are every ten levels. For me, personally, it doesn't make sense to leave a mastery at level 6, 11, 16, 21 _etc_.
It's a nice quality of life improvement, in my opinion, but it's a very effective one, I've seen this in a few idle games and I just love it. It could be a toggleable feature in the options if not everyone likes this.

### Why are you suggesting this?

I believe it's a nice QoL improvement and can make the game more enjoyable, albeit a little.

### How does your suggestion benefit the game?

It makes the function of spending XP on masteries quite a bit effective lessening the pain of clicking 9 more times just to make the skill level 10, and then selecting the option of "+10" levels.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
