### ISSUE TITLE
[Bug]: Command + H doesn't hide window

### ISSUE THREAD

**Issue by user8342912** [MelvorIdle/melvoridle.github.io#1695]
### Describe the bug

Pressing Command + H on a mac doesn't hide the window.

### Reproduction Steps

1. Have Melvor Idle open
2. Press Command + H

### Expected behaviour

The window should be hidden when Command + H is pressed

### Screenshots

<img width="251" alt="Screenshot 2021-11-15 at 15 36 45" src="https://user-images.githubusercontent.com/93920643/141809799-059287bc-2e3b-4653-822e-f0e1b2bce101.png">

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1317

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
