### ISSUE TITLE
[Bug]: Offline summary page text colored wrong

### ISSUE THREAD

**Issue by Tyriar** [MelvorIdle/melvoridle.github.io#1696]
### Describe the bug

The text was grey instead of the usual white.

### Reproduction Steps

This is what I did:

1. Open melvor idle
2. Load my adventure character, which was fine
3. Checked inventory
4. Switched char
5. Load my hardcore character, and the screenshot happened

### Screenshots

![image](https://user-images.githubusercontent.com/2193314/141810888-51c4e295-acdc-44d5-b369-e51bb1f21615.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

1317

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is now fixed :)
