### ISSUE TITLE
[Bug]: First astrology progress bar on load starts from beginning and doesn't reach the end

### ISSUE THREAD

**Issue by Tyriar** [MelvorIdle/melvoridle.github.io#1697]
### Describe the bug

When loading astrology (might happen on others too), the progress bar seems to start from 0%, rather than whatever is the real %, this means it doesn't reach the end.

### Reproduction Steps

1. Study astrology
2. Open another scroll
3. Open astrology and scroll to the progress bar

### Screenshots

![recording (7)](https://user-images.githubusercontent.com/2193314/141811428-23e709b3-f0b5-47f6-83aa-6f8d310f29a1.gif)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

1317

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is an issue due to how animations work on a HTML website like Melvor Idle. This will be fixed when skills eventually all go tick-based
