### ISSUE TITLE
[Bug]: After pressing G4 or G5 player gets logged out to the character selection screen

### ISSUE THREAD

**Issue by MichalStokowski** [MelvorIdle/melvoridle.github.io#1698]
### Describe the bug

After pressing G4 or G5 (additional side mouse buttons) player gets logged out of the character. This occurred while the player was logged into the cloud. While mashing those buttons player can get stuck in a loading screen.

### Reproduction Steps

1. Launch the game.
2. Log in to the cloud.
3. Select any character.
4. Press G4 or G5 mouse buttons.
5. Observe that the player has been kicked out to the character selection screen.

### Expected behaviour

Pressing any mouse buttons has no effect unless specified.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1317

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
What functions are your G4 and G5 buttons set to in Windows?
