### ISSUE TITLE
[Bug]: Offline mining switches target resource

### ISSUE THREAD

**Issue by Serneum** [MelvorIdle/melvoridle.github.io#1699]
### Describe the bug

Over the past few days, I've noticed a few instances where I'm trying to mine gold so I can upgrade some armor, but when I come back to the app I'm mining Silver instead. The amount of time I am gone does not seem to matter, and I can't consistently reproduce the issue. I can say it has happened three times today alone

### Reproduction Steps

1. Start mining Gold
2. Background the app or just lock the phone
3. Reopen the app

### Expected behaviour

The game should continue mining the expected resource, in this case Gold

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1290

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Is it possible to reproduce this bug 100% of the time?

**Comment by Serneum** [comment]
Sadly, no. I haven't figured out what triggers it but it always happened in offline mode. I apologize that I couldn't get any more information there

**Comment by Serneum** [comment]
I'm not sure if this is related, but I can move this to a separate issue if needed. While I haven't been doing mining, I have been fishing and cooking. I am now doing passive cooking for the first time and it seems like my choice to stop passively cooking an item is being ignored once the game goes into offline mode. I can disable the passive cooking in the game, see it stop cooking, but I will come back after an hour or two and more of my items will have been cooked passively

**Comment by MelvorIdle** [comment]
I believe this issue was resolved in a recent hotfix. Please open a new report if this is not the case.
