### ISSUE TITLE
Melee prayer increasing NPC chance to hit[Bug]: <title>

### ISSUE THREAD

**Issue by 69420BLAZEIT** [MelvorIdle/melvoridle.github.io#1700]
### Describe the bug

While fighting Adult Farmer NPC their chance to hit increased from 4% to 20% while I was fighting them when I activated melee prayer.

### Reproduction Steps

Fight Adult farmers
????
Profit!

### Expected behaviour

I expected it to decrease, not increase.

### Screenshots

Without melee prayer 
![MeleeOff](https://user-images.githubusercontent.com/73204815/141852476-aeaedfd5-7378-481a-a4e6-bbcc2866cdaa.png)

With melee prayer
![MeleeOn](https://user-images.githubusercontent.com/73204815/141852501-c7df9a8b-aa11-4b24-bd8f-9484df3b530c.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1317

### Are you using any scripts or extensions?

No

**Comment by 69420BLAZEIT** [comment]
It seems to be happening to all monsters I try to fight, all increasing to 20% so I'm not sure if it's just a visual bug and it's actually decreasing or what the problem is but I tried 3 other monsters and they all went up to 20% when I turned melee prayer on.

**Comment by MelvorIdle** [comment]
This is working as intended.

The description of the Prayer mentions "80% chance to dodge Melee Attacks". This means it will set the chance to hit of the enemy to 20%, as that is what it does.

So if the enemy has less than 20% chance to hit you, it will set their chance to hit based on the description of the Prayer.

This prayer is only meant to be used when the enemy's chance to hit is more than 20%

**Comment by 69420BLAZEIT** [comment]
> 
> 
> This is working as intended.
> 
> The description of the Prayer mentions "80% chance to dodge Melee Attacks". This means it will set the chance to hit of the enemy to 20%, as that is what it does.
> 
> So if the enemy has less than 20% chance to hit you, it will set their chance to hit based on the description of the Prayer.
> 
> This prayer is only meant to be used when the enemy's chance to hit is more than 20%

I should probably learn to read, sorry for wasting your time. Thanks for the awesome update!
