### ISSUE TITLE
[Bug]: Astrology/Woodcutting not properly applying offline Mastery XP

### ISSUE THREAD

**Issue by Pandorian6008** [MelvorIdle/melvoridle.github.io#1701]
### Describe the bug

I have 2 characters I've had training Astrology since it's introduction, a standard character and a hardcore character.  Both of their setups don't really modify Global XP% so when my Standard character starts on a task before my Hardcore character then it should stay ahead on the mastery XP.  This is not the case.

Here is my Standard Character Astrology Mastery:
![image](https://user-images.githubusercontent.com/75744619/141846841-b9ac1e63-10e9-4c22-a08b-67bc4233f453.png)
Here is my Hardcore Character Astrology Mastery:
![image](https://user-images.githubusercontent.com/75744619/141846943-8ba225e5-5f08-4428-9579-f32bd2091e90.png)

My standard character started training that specific Constellation a couple hours BEFORE my hardcore character.

Standard Equipment:
![image](https://user-images.githubusercontent.com/75744619/141847786-535b7a70-4aa0-4e32-9c4f-201656dff20c.png)

Hardcore Equipment:
![image](https://user-images.githubusercontent.com/75744619/141847065-44df434e-9cb1-421a-9e38-ed4cd5a671a1.png)

Standard FM:
![image](https://user-images.githubusercontent.com/75744619/141847833-ec1a1601-1940-4daf-864f-9ce5460804eb.png)

Hardcore FM:
![image](https://user-images.githubusercontent.com/75744619/141847310-451384d0-f0f5-4492-ab1d-d79f05533a69.png)

Standard Agility:
![image](https://user-images.githubusercontent.com/75744619/141847752-0d5525a0-196b-44e8-bea5-2e7fd48a37ba.png)

Hardcore Agility:
![image](https://user-images.githubusercontent.com/75744619/141847357-6b691237-4139-4ced-b6e5-012eeca71a31.png)

Standard Pets:
![image](https://user-images.githubusercontent.com/75744619/141847712-6d57ac16-84ad-471d-ac2f-f828e21b960a.png)

Hardcore Pets:
![image](https://user-images.githubusercontent.com/75744619/141847396-6d7e418f-697d-4e75-baae-d88bafb43158.png)

Astrology Total Skills Standard:
![image](https://user-images.githubusercontent.com/75744619/141847897-f88f3c31-2441-40a4-a55e-972f688ac655.png)

Astrology Total Skills Hardcore: 
![image](https://user-images.githubusercontent.com/75744619/141847493-63349b4f-29ee-4e38-8b16-9474c5b0abf9.png)

To the best extent of my knowledge there aren't any other items that modify Global Mastery XP 

To summarize: 
Both No Equipment that modify Global Mastery %
Both 95% Skill Mastery Firemaking, no Level 99 FIres
Both No Global Mastery % Modifiers from Agility
Both same Pets that modify Global Mastery %
Standard started before Hardcore with higher skill totals than Hardcore (521-57=464) vs (482-71=411)

### Reproduction Steps

1. Create 2 New Character, 1 Standard,1 Hardcore
2. Skip Tutorial Island
3. Set Astrology as Default Page on Load to Minimize Delay in Starting/Switching
4. Start Standard then immediately switch and start Hardcore.
5. Remain on Hardcore
6. Let run for 1 hour
7. Stop Hardcore Astrology then immediately switch and stop Standard Astrology
8. Compare Results

### Expected behaviour

Standard character should have similar or slightly greater Mastery XP for first skill (Deedree)

### Screenshots

Results after ~1 hr:

Standard account:
![image](https://user-images.githubusercontent.com/75744619/141855179-ae233c91-2faa-414f-a436-45af41e19ac1.png)

![image](https://user-images.githubusercontent.com/75744619/141855228-4d1b623f-149a-485a-bba6-6b5b4aaf9e2c.png)

Hardcore account:
![image](https://user-images.githubusercontent.com/75744619/141855279-eee92dac-37cb-4d98-b0f6-4efaa033a084.png)

![image](https://user-images.githubusercontent.com/75744619/141855305-856a1e10-5030-4f5d-95d2-e00579c35ef1.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1317

### Are you using any scripts or extensions?

No

**Comment by Pandorian6008** [comment]
Forgot to crop in Hardcore Astrology XP: 5,125.  50 less than Standard which corresponds to the 10 more times standard did action

**Comment by Pandorian6008** [comment]
I have also confirmed that this happens in Woodcutting also so it seems it might be a general bug and not specific to Astrology.

The same steps were repeated but I used woodcutting instead of astrology.

Hardcore Character:
![image](https://user-images.githubusercontent.com/75744619/141863150-85f2b9f9-a4e7-4959-87bf-913854815910.png)

![image](https://user-images.githubusercontent.com/75744619/141863180-39a21bea-09b3-4d65-b90c-e3a1546227dd.png)

Standard Character:
![image](https://user-images.githubusercontent.com/75744619/141863245-9febfb9e-c061-47c3-a056-21fb143a4209.png)

![image](https://user-images.githubusercontent.com/75744619/141863260-6d2b2998-8e6c-4fb9-ba6f-fdb2520fc299.png)

**Comment by Pandorian6008** [comment]
I also tested on mining but mining appears to be functioning correctly:

Hardcore:
![image](https://user-images.githubusercontent.com/75744619/141869569-7f3326c1-6cb8-490a-bd09-14fdb7614c6c.png)

Standard:
![image](https://user-images.githubusercontent.com/75744619/141869611-f5836d4c-cacd-4fa5-8b86-3413258996ee.png)

**Comment by MelvorIdle** [comment]
This is due to the difference between tick based and non tick based Skills.

Mining & Firemaking are tick-based skills, which means progress is apply exactly as it would be online with no efficiency loss.

All other Skills are not tick based yet, which means progress is calculated based on the numbers when you first logged off. This means you don't receive any of the benefits until you actually log in and collect your XP. This will also mean Mastery XP is lower on these skills than tick-based skills when training offline.

All skills will eventually be changed to tick-based.
