### ISSUE TITLE
[Bug]: Tutorial Island Task Completion When Skipping Tutorial Island

### ISSUE THREAD

**Issue by Pandorian6008** [MelvorIdle/melvoridle.github.io#1702]
### Describe the bug

If you skip Tutorial Island then eventually start cutting trees you will get a popup saying Tutorial Island task complete.

### Reproduction Steps

1. Start new character
2. Skip Tutorial Island
3. Chop Trees

### Expected behaviour

Tutorial Island prompts shouldn't appear when skipping Tutorial Island.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1317

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is now hotfixed.
