### ISSUE TITLE
[Bug]: Max offline warning shown for progression over 12 hours

### ISSUE THREAD

**Issue by mattrunyon** [MelvorIdle/melvoridle.github.io#1703]
### Describe the bug

When coming back from over 12 hours of offline progression (but under 18), the offline progression max warning is shown. The warning is correct (says 18 hours) and progression is not halted, but previously this warning only showed once you were past the max offline time.

In the screenshot, only 16000 potion doses would have been used if the progression was capped at 12 (tier 3 astrology potions. 2.7s per action = 16k in 12 hrs). Also the XP is correct for progress over 12 hours based on number of actions.

### Reproduction Steps

1. Start training a skill
2. Go offline
3. Wait over 12 hours, but less than 18 hours
4. Open game again

### Expected behaviour

No warning about max offline progression time being 18 hours

### Screenshots

![Screenshot_20211115-003956](https://user-images.githubusercontent.com/8619789/141858236-563560e2-c575-4883-aae7-bc3f7b016d10.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1317

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
I will be leaving this in the game, as warning to player of what the offline limit is prior to reaching it is better than showing them after reaching it without prior knowledge.
