### ISSUE TITLE
[Bug]: Android OS version very laggy and unresponsive following beta update

### ISSUE THREAD

**Issue by Jacobx89** [MelvorIdle/melvoridle.github.io#1704]
### Describe the bug

Following the latest large patch the game has become very slow and unresponsive on load & when doing a lot of tasks at once, Images take some time to load in the default screen (in my case fishing the fish take a few seconds to load), Offline progression takes a bit to show and it shows as grey text. If I spam buy some compost the UI lags out until you stop inputting and then it continues to load and shows a lot of +1 compost at the same time.

Just generally laggy on Android, My iOS device seems fine under similar conditions (iPad mini)

Device = Samsung Galaxy Note20 Ultra 5G

I understand this is extremely unhelpful and I am unable to provide solid reproduction steps, Was more of a heads up, Apologies.

### Reproduction Steps

General app usage. 
Am running Farming & Wood cutting 2 x trees at once if that helps
Fishing is my default screen

### Expected behaviour

Less laggy, was running perfectly fine prior to update.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1281

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Hey Jacob!

A few things to help us out here:
1) Please reinstall the Android app and let us know if the issue persists.
2) If yes, please send your save to us and we will take a look

**Comment by Jacobx89** [comment]
Reinstalling has made a slight improvement but still a bit laggy where theres a lot happening at once.
Save attached ; 

[MelvorSlot1save.txt](https://github.com/MelvorIdle/melvoridle.github.io/files/7554059/MelvorSlot1save.txt)

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
