### ISSUE TITLE
[Translation Error]: Slayer Gear Upgrade Kit (Master) requirements are displayed as a translation error

### ISSUE THREAD

**Issue by MichalStokowski** [MelvorIdle/melvoridle.github.io#1707]
### Which text in the game has a translation error?

Requirements of the Slayer Gear Upgrade Kit (Master) display "UNDEFINED TRANSLATION: MENU_TEXT:UNLOCK_SLAYER_Mastery" error.

**Comment by MelvorIdle** [comment]
A hotfix has been applied
