### ISSUE TITLE
[Bug]: Mining may be blocked after ending Goblin Raid

### ISSUE THREAD

**Issue by KWS-JakubWojcik** [MelvorIdle/melvoridle.github.io#1708]
### Describe the bug

Starting a second Goblin Raid after the first one may result in Mining (in this case, mainly mining Gold) being blocked. The progress bar fills once and doesn't begin again. Clicking on any other tab and switching back to Mining, result in the progress bar being partially filled. While this issue occurs, other actions can be started normally. So far the issue has been sighted once. 

### Reproduction Steps

1. Launch the game.
2. Open the mining tab.
3. Begin mining any resource.
4. Switch to the Goblin Raid tab.
5. Begin the Goblin Raid and proceed through about five waves.
6. Switch to any other tab.
7. Repeat steps 4-6.
8. Finish the Goblin Raid and switch to the Mining tab.
9. Begin Mining Gold.
10. Observe the Mining gold button.

### Expected behaviour

Starting, finishing, and restarting the Goblin Raid has no negative impact on the game.

### Screenshots

https://user-images.githubusercontent.com/94455309/142015283-8249ae89-382e-4888-901e-fe5a680abb41.mp4

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1323

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue was hotfixed as of v1.0.3 (?1843).
