### ISSUE TITLE
ancient magic clear count

### ISSUE THREAD

**Issue by nate5813** [MelvorIdle/melvoridle.github.io#1709]
### Describe the bug

when i mouse over ancient magic that isnt unlocked it says "dungeon cleared {count} times"

### Reproduction Steps

1. go to ancient magic
2. mouse over spell that isnt unlocked

### Expected behaviour

dungeon cleared {count} times

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1323

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Thanks, a hotfix has been applied to the game
