### ISSUE TITLE
[Bug]: All skills cant be unlocked after tutorial (Adventure mode)

### ISSUE THREAD

**Issue by sascharue** [MelvorIdle/melvoridle.github.io#1710]
### Describe the bug

In adventure mode all non combat skills are locked as intended, but they cant be unlocked (there is no popup for unlocking the skill) after the tutorial.
The ranged skill is unlockable.

### Reproduction Steps

1. Start adventure mode
2. Finish tutorial
3. Try to unlock woodworking

### Expected behaviour

When clicking the locked woodworking skill a message should appear asking if I want to unlock it.

### Screenshots

![image](https://user-images.githubusercontent.com/19736977/142042163-546a1e40-59d6-4e4a-bcbf-0407ee530dee.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1323

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
I am unable to recreate this issue. Are you still experiencing this on the latest hotix version ?1325?

**Comment by sascharue** [comment]
I can reproduce it on the newest version ?1329
Attached you'll find a video showing the error, hope this helps.

https://user-images.githubusercontent.com/19736977/142176691-3a9a1919-ff07-4868-bb79-55c78ab23699.mp4

**Comment by Panrantanplan** [comment]
I have the same Problem on android, It is not possible to lock off non combat skills, only combat skills can be bought

**Comment by MelvorIdle** [comment]
This is now hotfixed :)
