### ISSUE TITLE
[Bug]: <title>Unable to mine, or cut trees offline, or fight monsters at all

### ISSUE THREAD

**Issue by bergermb** [MelvorIdle/melvoridle.github.io#1711]
### Describe the bug

Mining has the progress bar but nothing happens.

woodcutting only works while on the woodcutting screen.

Click to fight giants or any other monster and doesn’t initiate fighting.

### Reproduction Steps

Try to play the game…

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1323

### Are you using any scripts or extensions?

No

**Comment by justin412x** [comment]
Same thing happening to me with mining. Bar fills when I begin mining and then nothing happens.

**Comment by Vorsku** [comment]
I get the same thing with mining - click a rock and it progresses the first one but no ore is mined, and then it just stops

**Comment by Admiral-99** [comment]
Same issue with mining. It worked just fine up until today. Now I cannot mine any ores even with restarting the app/reloading the website

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.0.2. Please open a new ticket if this is not the case.
