### ISSUE TITLE
[Bug]: Layout issue with Astrology Skill XP

### ISSUE THREAD

**Issue by AevitasDragonkin** [MelvorIdle/melvoridle.github.io#1714]
### Describe the bug

Astrology Skill XP isn't displayed properly on large browser windows, it then uses the col-xl-3 class instead of col-sm-6.

### Reproduction Steps

1. Browser width at 1440px
2. Not yet level 99, but more than 10M xp

### Screenshots

![image](https://user-images.githubusercontent.com/77356760/142084294-de0bd82c-f1ec-47d8-8dfe-5125b2848feb.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1274

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Thanks, hotfix has been applied
