### ISSUE TITLE
[Bug]: shop only lets me buy one thing

### ISSUE THREAD

**Issue by Deadsaint66** [MelvorIdle/melvoridle.github.io#1715]
### Describe the bug

when I logged in today I wanted to fletch some arrows, was too lazy to farm chickens for feathers, so I went to the shop to buy them. bought 50k feathers, figured id need more so I tried to buy another 50k, but the game wont let me. the pop-up confirmation window doesn't come up. and clicking does nothing.

### Reproduction Steps

go to shop, try to buy anything twice. first time lets you buy the item, second time is unresponsive

### Expected behaviour

keep allowing me to buy things

### Console output

cloud.js?1323:67 Connected to PlayFab successfully
save.js?1323:10 Removed old local storage keys.
save.js?1323:58 set force reload to 0
combatManager.js?1323:1 Combat Manager Built...
raidManager.js?1323:1 Golbin Raid Manager Built...
save.js?1323:10 Removed old local storage keys.
save.js?1323:14 Loading Save Game...
save.js?1323:14 Save Game Loaded...
main.js?1323:8 Game Loaded
userscript.html?name=Melvor%20Action%20Queue.user.js&id=e9a2ff98-8211-4eb4-90b8-05f7da12fd74:1598 Action Queue loaded
VM144:19 DungeonTimerData Key found - Data retrieved
VM144:85 Melvor DungeonTimer: loading...
VM144:85 Melvor DungeonTimer: loaded!
VM144:85 Melvor DungeonTimer: added Timer menu!
SEMI.js:174 Core injection good
cloud.js?1323:67 Connected to PlayFab successfully
cloud.js?1323:9 Synchronising with Cloud
cloud.js?1323:68 PlayFab Connected: DeadSaint66
utils.js:517 Game Loaded. SEMIUtils ready.
event-bus.js:59 Starting Event Bus
menus.js:99 SEMI v0.9.1 Loaded!
VM291:88 Melvor ETA: loading...
VM291:88 Melvor ETA: loaded!
mastery-enhancements.js:88 Loading Mastery Enhancements
core.js:259 auto-run enabled at 11/16/2021, 6:05:01 PM
core.js:259 auto-master enabled at 11/16/2021, 6:05:01 PM
core.js:259 auto-sell enabled at 11/16/2021, 6:05:01 PM
core.js:259 auto-slayer-skip enabled at 11/16/2021, 6:05:01 PM
core.js:259 auto-bury enabled at 11/16/2021, 6:05:01 PM
core.js:259 auto-loot enabled at 11/16/2021, 6:05:01 PM
core.js:259 auto-farm enabled at 11/16/2021, 6:05:01 PM
core.js:259 auto-eat enabled at 11/16/2021, 6:05:01 PM
core.js:259 drop-chances enabled at 11/16/2021, 6:05:01 PM
core.js:259 save-on-close enabled at 11/16/2021, 6:05:01 PM
sort-override.js:1210 Attempting to modify Main.js sortBank
sort-override.js:1214 Successfully adjusted bank sort order.
core.js:259 sort-override enabled at 11/16/2021, 6:05:01 PM
VM291:88 Melvor ETA: Failed to add settings menu! Melvor ETA will work fine without it. Install the "Melvor Idle Combat Simulator Reloaded" extension to use the settings interface.
VM291:88 Melvor ETA: Find it here: https://github.com/visua0/Melvor-Idle-Combat-Simulator-Reloaded
cloud.js?1323:9 Synchronising with Cloud

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1323

### Are you using any scripts or extensions?

Yes

**Comment by MelvorIdle** [comment]
Can you actually afford to buy them? The popup won't display if you don't have enough GP

**Comment by Deadsaint66** [comment]
yes i have over 60m gp and the feathers only cost 400k.

**Comment by MelvorIdle** [comment]
Hey! Is this still occurring after the recent hotfixes to the game?

**Comment by Deadsaint66** [comment]
nope!  as off a few days ago it has been working as intended. sorry for the late response. <3
