### ISSUE TITLE
[Bug]: <bug with pets>

### ISSUE THREAD

**Issue by Morigan6** [MelvorIdle/melvoridle.github.io#1716]
### Describe the bug

for a week of the game did not receive a single pet. playing hardcore CO 

### Reproduction Steps

-

### Expected behaviour

expect to get pets :D

### Screenshots

![image](https://user-images.githubusercontent.com/94497314/142086397-0356efe8-7454-4f1d-9c55-5070b2785f3c.png)

### Console output

steam

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

(?1323)

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Pets are extremely rare, and their drop rate increases as you level up skills. It is common to not receive a pet this early into the game.

**Comment by Morigan6** [comment]
> Pets are extremely rare, and their drop rate increases as you level up skills. It is common to not receive a pet this early into the game.

Thanks for the answer! did not play for a month and on the last account at this stage of the game there were already 5 pets ...
As I understand it, something has changed in the mechanics
