### ISSUE TITLE
[Bug]: <title>smithing gloves gone

### ISSUE THREAD

**Issue by D4daBrawler** [MelvorIdle/melvoridle.github.io#1717]
### Describe the bug

Smithing gloves aren't showing up in inventory.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1324

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Are they equipped in one of your equipment sets?
Did you buy the Smithing Gloves, and not a different set of gloves like the Mining gloves?
How many charges are remaining on your smithing gloves? You can check this in the shop
