### ISSUE TITLE
Mastery token woodcutting

### ISSUE THREAD

**Issue by Frogchi** [MelvorIdle/melvoridle.github.io#1719]
### Describe the bug

Im receiving very few mastery tokens for woodcutting (4 over a 9 hour period). Is that normal? 

Thanks! 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

Na

### Are you using any scripts or extensions?

No

**Comment by arcestia** [comment]
you can see wiki for the maths for this https://wiki.melvoridle.com/w/Mastery_Tokens

**Comment by Frogchi** [comment]
Ah perfect! Thanks so much!
