### ISSUE TITLE
[Bug]: Unclicking mining during the Goblin Raid results in no items gained from said mining

### ISSUE THREAD

**Issue by KWS-JakubWojcik** [MelvorIdle/melvoridle.github.io#1720]
### Describe the bug

When a player unclicks mining while playing the Goblin Raid minigame, all the items mined since it was clicked the first time will be lost. After a player finishes the Goblin Raid they are welcomed with a "Welcome Back! You were gone for roughly.." message, however there will be no items in that window, as the mining progress is lost. 

### Reproduction Steps

1. Launch the game. 
2. Begin mining any resource.
3. Start the Goblin Raid minigame. 
4. Proceed through a few waves. (5-10)
5. After spending some time in the Goblin Raid, unlick the mining that was active.
6. Finish the Goblin Raid.
7. Observe the "Welcome Back!" window.

### Expected behaviour

Finishing any action that took place in the background while playing Goblin Raid has no negative impact on the amount of resources amassed during the time said action was active.

### Screenshots

![#1720](https://user-images.githubusercontent.com/94455309/142204206-3c0a028c-a0b8-4fd0-8155-d847e7b8d2e2.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1326

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue was hotfixed as of v1.0.3 (?1843).
