### ISSUE TITLE
[Bug]: Previously unlocked Prayer still active and cannot unequip

### ISSUE THREAD

**Issue by Mokujinn** [MelvorIdle/melvoridle.github.io#1721]
### Describe the bug

Had a prayer unlocked before the last patch. After the prayer changes I still have this prayer equipped (Piety) and I cannot unequip it. It is greyed out with a question mark. I do still gain exp however this does not seem intended. 

### Reproduction Steps

1. Have piety selected before patch
2. Have prayer level that does not allow you to select or deselect piety 
3. Profit

### Expected behaviour

Piety is auto deselected because I do not have the prayer level for it. Didn’t have any scripts that directly effected prayer though. 

### Screenshots

![10627B01-E625-4891-B3B3-AA23B81DFA3B](https://user-images.githubusercontent.com/52005805/142219179-10eff03b-1f82-4707-bb84-3d23de622050.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1329

### Are you using any scripts or extensions?

Yes

**Comment by MelvorIdle** [comment]
You can click the Prayers in the "Active Prayers" section  under Combat Stats which will disable them
