### ISSUE TITLE
[Bug]: Upgrading mastery levels of lumberjack in thieving quickly bypasses checkpoint prompt

### ISSUE THREAD

**Issue by Matrix159** [MelvorIdle/melvoridle.github.io#1722]
### Describe the bug

While upgrading the lumberjack's mastery level in thieving with quick clicks through the steam version of the game, it made me drop below my 95% checkpoint without me confirming it. I did see a brief flash of the yellow +1 button but by clicking quickly I either bypassed the prompt or somehow hit the accept button of the prompt. 

### Expected behaviour

I would expect to not to be able to bypass the mastery checkpoint prompt by clicking quickly on the upgrade button. If I did end up clicking accept during the prompt, maybe add a bit of a "lockout" time to give the prompt some time to show up or ensure that the accept button doesn't ever index over the same click area where the +1 button is.

### Screenshots

<img width="567" alt="image" src="https://user-images.githubusercontent.com/5334090/142243224-5bd72528-9e32-4673-a118-8a22571a7d95.png">

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1329

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
