### ISSUE TITLE
[Bug]: <Goblin raid item details>

### ISSUE THREAD

**Issue by LetsG0Brandon** [MelvorIdle/melvoridle.github.io#1724]
### Describe the bug

In goblin raid after each wave it doesn't matter which category I select, when I click on the button to view item details before making a selection, the details page pops up behind the list of items thereby preventing me from viewing the details.

### Screenshots

![ED4182B6-56EF-4974-B8B6-6631029D9008](https://user-images.githubusercontent.com/94591992/142358218-4cddf202-48fe-4c60-bcb6-d121e6d29981.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1331

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
this is now hotfixed :)
