### ISSUE TITLE
[Bug]: Space no longer closes welcome back screen

### ISSUE THREAD

**Issue by TheDeviantCrafter** [MelvorIdle/melvoridle.github.io#1725]
### Describe the bug

Before the v1.0 update, pressing space would close the "Welcome back!" offline progress report. After this update, that no longer works. The player must click the "OK" button with the mouse.

Notifications for getting 99 in a skill or a pet are probably also affected, but I haven't had a chance to test them.

### Reproduction Steps

1. Enable "pause actions for skills" to ensure that the game goes offline
2. Switch to another tab
3. Switch back to Melvor Idle to spawn the "Welcome back!" message
4. Press space to close the dialogue box. This will not work.

### Expected behaviour

Pressing space should close any notification with "OK" as the only option. This worked correctly before the v1.0 build.

### Screenshots

![image](https://user-images.githubusercontent.com/18755309/142371366-1ac23080-1db4-4de4-9e1c-68a3a55a8c5d.png)

### Console output

style.css:1 Failed to load resource: the server responded with a status of 404 ()
v64f9daad31f64f81be2…a5e31634941392597:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v64f9daad31f64f81be2…a5e31634941392597:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v64f9daad31f64f81be2…a5e31634941392597:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloud.js?1329:67 Connected to PlayFab successfully
save.js?1329:58 set force reload to 0
combatManager.js?1329:1 Combat Manager Built...
raidManager.js?1329:1 Golbin Raid Manager Built...
save.js?1329:14 Loading Save Game...
save.js?1329:14 Save Game Loaded...
main.js?1329:8 Game Loaded
cloud.js?1329:67 Connected to PlayFab successfully
cloud.js?1329:9 Synchronising with Cloud
v64f9daad31f64f81be2…a5e31634941392597:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v64f9daad31f64f81be2…a5e31634941392597:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloud.js?1329:68 PlayFab Connected: SirDeviant
5
cloud.js?1329:9 Synchronising with Cloud
style.css:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bf….map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
﻿

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1329

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
