### ISSUE TITLE
[Bug]: Icons of items and monsters show up lighter over dark mode

### ISSUE THREAD

**Issue by darkwingpt** [MelvorIdle/melvoridle.github.io#1727]
### Describe the bug

As of today, most of the colored icons (monsters and items) have gone "pale" while under the phone's embedded dark mode, having changed no setting over the game. This happened without an app update and over night (as all icons have worked just fine with dark mode enabled, ever since I've installed the mobile version). 
Switching off the phone's dark mode (returning to a full-white interface) makes it so that the icons turn back to what is expected.

### Reproduction Steps

1. Enable phone's dark mode;
2. Icons show up pale.

### Expected behaviour

Icons show up as normal (colored).

### Screenshots

[Example 1](https://cdn.discordapp.com/attachments/756053445479235668/910866348517773352/IMG_20211118_121728.jpg)
[Example 2](https://cdn.discordapp.com/attachments/756053445479235668/910866463362015242/IMG_20211118_121759.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1331

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is unfortunately due to an Android Web View update. There isn't anything I can do about this until Google fixes it.

Best thing to do is uninstall the latest Android Web View update from the play store
