### ISSUE TITLE
[Bug]: <Not able to afk cook Whales / Mantas>

### ISSUE THREAD

**Issue by Juuiiice** [MelvorIdle/melvoridle.github.io#1728]
### Describe the bug

(Mobile) when my app is closed or minimized to tray, cooking stalls and will not give me any xp, no matter the length of time. This issue happened both with Whales and Manta rays, but when I start cooking and watch the app, they cook fine.

### Reproduction Steps

Start cooking whale or manta ray, close or minimize app, after any length of time, open app back up, greeted with “you have been gone for x amount of time, you have gained 0 cooking xp.” I had been cooking for 8 hours last night when this happened

### Expected behaviour

To receive amount of cooked fish equal to the fish cooked in time period of being away

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1332

### Are you using any scripts or extensions?

No

**Comment by SilasOtoko** [comment]
Happening with Swordfish too. Carp cooked fine, though, so maybe not an issue with all fish.

**Comment by coolrox95** [comment]
Cooking has been rewritten as of v1.0.3.
