### ISSUE TITLE
Restore Premium purchase on PC from mobile

### ISSUE THREAD

**Issue by thandrage** [MelvorIdle/melvoridle.github.io#1729]
### Describe the bug

I purchased the premium version of the app through the mobile app. I sometimes will like to play on my PC as well, but when I open the character that I purchased the premium account on, it says that I am still using the free version. I have looked around for a restore purchase option and cannot find it. 
Online, it was seeming to say that it should happen automatically.

### Reproduction Steps

Create account on mobile
-Play Free on Mobile
-Play Free on PC
-Purchase Premium
-Play on mobile
-Play on PC (not premium)

### Which platforms are you experiencing this bug on?

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [X] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1337

### Are you using any scripts or extensions?

No

**Comment by arcestia** [comment]
This is not a bug, check [this reddit post](https://www.reddit.com/r/MelvorIdle/comments/qgkmu9/information_regarding_premium_mobile_users_and/) regarding this.

**Comment by thandrage** [comment]
thank you
