### ISSUE TITLE
[Bug]: <User is unable to go back to the main menu after creating a character on iPhone 7>

### ISSUE THREAD

**Issue by MikeDenny1987** [MelvorIdle/melvoridle.github.io#1731]
### Describe the bug

STEPS TO REPRODUCE
1. When first opening the app, select "Create a new Character"
2. Attempt to scroll up to the top of the next screen and select "Go Back" instead of selecting a game mode.

RESULT
The user's display is snapped back to the middle of this page, preventing them from being able to select "Go Back". The user is required to close the app entirely in order to return to the launch menu.

### Expected behaviour

The user is able to scroll each page to access all areas of the title available to them at all times.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
