### ISSUE TITLE
[Bug]: <The user is unable to close the application via the Steam UI>

### ISSUE THREAD

**Issue by MikeDenny1987** [MelvorIdle/melvoridle.github.io#1732]
### Describe the bug

STOP button in the Steam library does not close the application.

### Reproduction Steps

1. Launch the application via Steam.
2. After the browser window opens, tab back to Steam and locate Melvor Idle in the Library.
3. Press "STOP".

### Expected behaviour

The application will close.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

7709621

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Do you recall what task you performed as soon as you closed the game?

Eg. What skill were you training, and what was the last button you pressed?
