### ISSUE TITLE
[Bug]: Skill sidebar appears on pages it shouldn't while in combat

### ISSUE THREAD

**Issue by iPeer** [MelvorIdle/melvoridle.github.io#1733]
### Describe the bug

After toggling the auto reuse potion setting, the last viewed skill's sidebar is able to appear on pages which a skill sidebar should not normally be displayed while the user is in combat. If there is no last viewed skill it will default to woodcutting but will only show part of the sidebar, not all of it.

### Reproduction Steps

1. Open the game and load (or create) a character.
1.1. You can view a skill's page to change which bar appears to change which bar will appear.
2. Enter combat with something.
3. Open any page which has the combat bar visible, but does not normally have any skill sidebars (eg. the bank or store)
4. Open the potion UI and toggle the auto reuse potion setting (doesn't matter if it's being turned on or off)
5. The sidebar for whichever skill you last viewed (or a partial woodcutting one if you haven't viewed a skill yet) will now be visible on the screen.

### Expected behaviour

Toggling the option doesn't show the sidebar on these pages.

### Screenshots

https://user-images.githubusercontent.com/571150/142503996-a8719bae-6f84-4c86-9fe1-cbd0ee24e64e.mp4

### Console output

www.googletagmanager.com/gtag/js?id=UA-129674422-1:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
style.css:1 Failed to load resource: the server responded with a status of 404 ()
v64f9daad31f64f81be21cbef6184a5e31634941392597:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v64f9daad31f64f81be21cbef6184a5e31634941392597:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v64f9daad31f64f81be21cbef6184a5e31634941392597:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloud.js?1337:67 Connected to PlayFab successfully
save.js?1337:58 set force reload to 0
combatManager.js?1337:1 Combat Manager Built...
raidManager.js?1337:1 Golbin Raid Manager Built...
save.js?1337:14 Loading Save Game...
save.js?1337:14 Save Game Loaded...
main.js?1337:8 Game Loaded
cloud.js?1337:67 Connected to PlayFab successfully
v64f9daad31f64f81be21cbef6184a5e31634941392597:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v64f9daad31f64f81be21cbef6184a5e31634941392597:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloud.js?1337:9 Synchronising with Cloud
style.css:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
