### ISSUE TITLE
[Bug]: Agility building problem

### ISSUE THREAD

**Issue by Polon69** [MelvorIdle/melvoridle.github.io#1734]
### Describe the bug

The problem is building new obstacle, the requirements for Coal Stone is cooked Salmon. The point is i have 100% to cook perfect salmon which doesn't count to build obstacle. While i remove skill cape i have 98% -.-

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
You can disable Perfect Cooks at the top of the Cooking page

![image](https://user-images.githubusercontent.com/45249614/142785754-5c3ff508-152a-4ae3-9c6b-a2494db87f49.png)
