### ISSUE TITLE
[Bug]: % symbol missing from skill mastery info

### ISSUE THREAD

**Issue by Tyriar** [MelvorIdle/melvoridle.github.io#1735]
### Describe the bug

Noticed the screenshot in a hardcore game

### Screenshots

![image](https://user-images.githubusercontent.com/2193314/142622315-0bcc0da7-e5f7-4917-9447-87d218914f9b.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1342

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue was fixed.
