### ISSUE TITLE
[Bug]: <mining bug>

### ISSUE THREAD

**Issue by Jroyer73** [MelvorIdle/melvoridle.github.io#1737]
### Describe the bug

Mining doesn’t work anymore.
Went to bed Runecrafting last night and woke up to mine more rune essence. I can click to mine rune essence, it goes through the bar like it’s about to mine, but once finished it stops like the health is depleted. Tried closing out and relaunching. Other skills work just not mining.

### Reproduction Steps

1. Go to mining
2. Select rune essence 
3. Wait for the time to be up
4. Stops 

### Expected behaviour

1. Go to mining
2. Click rune essence
3. Wait for the time to be up
4. Receive rune essence and mine again

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1342

### Are you using any scripts or extensions?

No

**Comment by mcleodseanm** [comment]
+1 for this on Win11 Firefox 94.0.1 (64-bit)
Game version V1.0 (1342)

Console output:
`Exception { name: "NS_ERROR_NOT_AVAILABLE", message: "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannelInternal.remoteAddress]", result: 2147746065, filename: "resource://devtools/server/actors/network-monitor/network-observer.js", lineNumber: 1062, columnNumber: 0, data: null, stack: "_onResponseHeader@resource://devtools/server/actors/network-monitor/network-observer.js:1062:5\n_dispatchActivity@resource://devtools/server/actors/network-monitor/network-observer.js:635:14\nNetworkObserver.prototype.observeActivity<@resource://devtools/server/actors/network-monitor/network-observer.js:744:12\nexports.makeInfallible/<@resource://devtools/shared/ThreadSafeDevToolsUtils.js:103:22\n", location: XPCWrappedNative_NoHelper }
​
columnNumber: 0
​
data: null
​
filename: "resource://devtools/server/actors/network-monitor/network-observer.js"
​
lineNumber: 1062
​
`

**Comment by MelvorIdle** [comment]
Related to #1647

Closing this one as it is a duplicate
