### ISSUE TITLE
[Bug]: <Cannot Create Rooftop Run Agility Obstacle>

### ISSUE THREAD

**Issue by twarrenprice** [MelvorIdle/melvoridle.github.io#1738]
### Describe the bug

The obstacle requires normal lobsters to build it, but I can only obtain Perfect lobsters. Will not accept those when I try to build obstacle. Either need obstacle to allow perfect lobsters or make getting normal lobsters possible again.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1342

### Are you using any scripts or extensions?

No

**Comment by TJOak** [comment]
There's a checkbox in Cooking to enable or disable perfect cooks. (I assume it's on mobile too, at least.)

**Comment by twarrenprice** [comment]
Thank you
