### ISSUE TITLE
[Bug]: goblin raid 

### ISSUE THREAD

**Issue by Zamorak0** [MelvorIdle/melvoridle.github.io#1740]
### Describe the bug

Whenever I chose a wand or anything of a higher tier it vanished after I win the next round and leaves me holding nothing. It's happened now with the mystic air wand,  A war axe, and a few others. It used to leave me with a bronze scimitar but now it's nothing 
Before it would happen after I chose a spell but now it's happening randomly 
### Reproduction Steps

1. Go to goblin raid 
2. Start the fight and win a round
3. Choose your weapon
4. Continue the fight and choose your next piece of equipment
5. Item will now possibly be gone 

### Expected behaviour

I expected to keep my weapon equipped 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

(?1341)

### Are you using any scripts or extensions?

No

**Comment by MaseChase696** [comment]
i have had similar issues, im getting any crossbow and after the next win it resets to the bronse scimitar.
im on V1.0(?1346)
