### ISSUE TITLE
[Spelling/Grammar]: <golbin>

### ISSUE THREAD

**Issue by Nosman12** [MelvorIdle/melvoridle.github.io#1741]
### What text is wrong?

![Screenshot_3](https://user-images.githubusercontent.com/94719720/142691786-3c6ff89c-7d89-4c43-97ce-c2dbdc5b19c1.png)
goblin is spelled wrong. 

### What is the correct spelling or grammar?

Goblin

**Comment by OginSada** [comment]
Golbin sounds better.

**Comment by gregorymcdonald** [comment]
From [MelvorIdle's previous comment on the spelling of "Golbin"](https://github.com/MelvorIdle/melvoridle.github.io/issues/1672#issuecomment-967766915):
> Golbin is the correct and intended spelling
