### ISSUE TITLE
[Spelling/Grammar]: 

### ISSUE THREAD

**Issue by snowy6409** [MelvorIdle/melvoridle.github.io#1743]
### What text is wrong?

![image](https://user-images.githubusercontent.com/11221362/142704449-572e6c82-d4bc-41de-935b-31a6f5f7fe24.png)

### What is the correct spelling or grammar?

Bronze Shield

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
