### ISSUE TITLE
[Bug]: <Premium account status not acknowledged when switching from iOS to desktop>

### ISSUE THREAD

**Issue by V0ric** [MelvorIdle/melvoridle.github.io#1746]
### Describe the bug

I upgraded to premium while playing on my iOS device. I have an Melvor Idle account and use cloud saves. When switching to the browser based desktop version of the game, the cloud save shows up after logging in but can not be loaded. I'm also asked in the character selection screen to upgrade to premium again. Since the respective save file that I want to load from the cloud is an adventure mode save file, I assume this issue is connected with the fact that the browser doesn't acknowledge my premium purchase on iOS.

Account: Voric

### Reproduction Steps

1. Purchase premium upgrade on iOS
2. Create an adventure mode character
3. Save to cloud
4. Switch to desktop/browser based variante of the game (e.g. Chrome or Firefox)
5. Log in
6. Try to download the premium save file

### Expected behaviour

The desktop version of the game should recognize that the account has purchased the premium upgrade on iOS and has a valid adventure mode save file in the cloud saves.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1342

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Please see this post regarding Mobile -> Desktop Premium: https://www.reddit.com/r/MelvorIdle/comments/qgkmu9/information_regarding_premium_mobile_users_and/
