### ISSUE TITLE
[Bug]:  Offline progression does not consider mastery levels progression if new bonus was not already active in some form 

### ISSUE THREAD

**Issue by TheSirFreud** [MelvorIdle/melvoridle.github.io#1747]
### Describe the bug

I am pretty sure this is a global problem as I saw a [post that had pretty much the same problem but with another skill](https://github.com/MelvorIdle/melvoridle.github.io/issues/1751#issue-1059199293).

The offline progression does not seem to take into consideration the mastery level unlocks that are gained during that offline progression. Here is my example: 

I started fishing the Leaping Broad Fish (mastery lvl 1) before going out for the evening, closed the game for offline progression, and when I came back, I noticed that I was now mastery 68 and I had not received any special item at all. I stopped the fishing action, started it again, and only then I was getting gems and treasures.

This is nothing major, but it would be nice to fix it. I also expect that this might be applicable to all the fish areas that have a 0% base chance.

Thanks for your hard work, your game is amazing!

### Reproduction Steps

1. Go to Fishing tab
2. Choose an area with 0% Special chance (in my case, the Barbarian fishing)
3. Start fishing any fish that has a mastery lvl lower than 50 (in my case, Leaping Broad Fish lvl 1)
4. Save and close the game to start offline progression
6. Come back in the game with mastery lvl over 50, or let's say 60 to have some chances of getting a special item and there should be no mention of anything else being catched other than the fish

### Expected behaviour

I expect that from after lvl 50, there should be some special items caught.

### Screenshots

Here was the state before I started fishing Leaping Trouts (second time trying to replicate the bug):
![Before_Having_Special_Chances](https://user-images.githubusercontent.com/15266571/142738517-800a8aec-7d9e-4ee4-aeab-293fc6df4aab.png)

I came back to this (very lucky, but no gems or treasures as I would expect): 
![What_I_Came_Back_To](https://user-images.githubusercontent.com/15266571/142738544-608a55b3-2972-4966-9363-46cf1b4ad870.png)

This to prove that my mastery was above 50 for a good amount of time during the offline progression:
![Fish_Mastery_Above_Fifthy](https://user-images.githubusercontent.com/15266571/142738561-388e7f45-a821-4863-ba97-aa690fbe3d00.png)

I closed the game again for 5 minutes and I already got some gems:
![Came_Back_Five_Min_Later](https://user-images.githubusercontent.com/15266571/142738580-2bd59ac4-0915-45e5-8124-4066cb37f40b.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1342

### Are you using any scripts or extensions?

No

**Comment by TheSirFreud** [comment]
Here was the state before I started fishing Leaping Trouts 
![Before_Having_Special_Chances](https://user-images.githubusercontent.com/15266571/142738508-54b3b62f-7189-42b8-a9e3-ed000d11e94c.png)
:

**Comment by MelvorIdle** [comment]
This is the intention of the existing implementation of non tick based skills.

As skills transition to tick based, this downside will be rectified.

**Comment by TheSirFreud** [comment]
Thanks for clarifying this, sorry that I created a "false" bug report...
Have a great day!
