### ISSUE TITLE
Cloud Save Gone

### ISSUE THREAD

**Issue by OginSada** [MelvorIdle/melvoridle.github.io#1748]
### Describe the bug

I have all my saves in the cloud. Today I received my new phone and logged in to the account and the cloud save was there and I click on it and it shows my offline progress and the game crashes and the cloud save is gone. Is there any thing I can do to recover it.

Username is Ogin

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

Latest Version 

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Unfortunately you were playing a Hardcore character and died while Offline.

![image](https://user-images.githubusercontent.com/45249614/142785588-5a90c98b-8e97-4737-acba-4d9740239f5b.png)
