### ISSUE TITLE
[Bug]: Monster Selection Menu displays wrong hitpoint values in Adventure Mode

### ISSUE THREAD

**Issue by CaptainCCCP** [MelvorIdle/melvoridle.github.io#1750]
### Describe the bug

Game shows wrong HP(10times smaller) of all the monsters after switched from standard mode to adventure mode

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1.0(?1342)

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Can you please confirm this is what you see as part of Adventure mode?

![image](https://user-images.githubusercontent.com/45249614/142785515-7d16dbd9-8c3c-4144-bc71-d812eda317d3.png)

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
