### ISSUE TITLE
[Bug]: <title> Herblore Mastery

### ISSUE THREAD

**Issue by NaturaSelection** [MelvorIdle/melvoridle.github.io#1751]
### Describe the bug

When left all night herblore skipped over potion 2 for regeneration potions, losing the ability to finish 100% completion

### Reproduction Steps

Set to idle herblore all night
Pick level 1 potion
Have enough materials
Check back in 12 hours

### Expected behaviour

It shouldn't skip potion level 2 or you should be able to go back and select what potion you want to make

### Screenshots

![Screenshot_20211120-120343_Melvor Idle](https://user-images.githubusercontent.com/94758381/142736699-6891d6ac-5675-4cf8-8655-52b0cc7ff098.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1342

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.0.2. Please open a new ticket if this is not the case.
