### ISSUE TITLE
[Bug]: Astrology constellation mastery xp bar wrong color at 99 mastery

### ISSUE THREAD

**Issue by EF-programming** [MelvorIdle/melvoridle.github.io#1754]
### Describe the bug

When 99 mastery in a constellation is reached, the mastery xp bar color becomes green and the number '99' becomes gold. However, after reloading the game, the colors change back to blue, black.

Note: I had to refresh with ctrl+f5 to reproduce the bug, and there might be other requirements to reproduce, but all of my mastery 99 constellations have the wrong colors so it's a pretty consistent bug.

### Reproduction Steps

1. Level a constellation to 99 mastery. Note that the mastery xp bar colors became green, gold.
2. Clear cache, reload the game.
3. Note that the mastery xp bar colors are blue, black.

Note: there might be extra requirements to reproduce this bug.

### Expected behaviour

Lvl 99 mastery xp bar color should stay green, number '99' color should stay gold.

### Screenshots

![image](https://user-images.githubusercontent.com/10391911/142750408-828a6e4b-641d-403c-a436-f9462483d2d8.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1342

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue was fixed as of v1.0.3.
