### ISSUE TITLE
[Bug]: Online progress not calculating in background [iOS]

### ISSUE THREAD

**Issue by rionolund** [MelvorIdle/melvoridle.github.io#1755]
### Describe the bug

If Melvor is reopened without having the app fully closed, all background progress is lost. The application must be "swiped away" so it can fully restart upon opening, unless significant time has passed to cause this automatically. 

### Reproduction Steps

1. Have a passive skill in progress.
2. Swipe to the Home Screen while leaving Melvor in the background.
3. Reopen the app after some time (an hour or so)
4. Check skill progress, should not match up with time spent idle

### Expected behaviour

Left at 19,500 Dragonite bars, an hour later came back to 19,600 Dragonite bars. Expected one bar every 2s, >21,300 Dragonite bars.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1342

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Hey!

Do you have this setting enabled on your device?
![image](https://user-images.githubusercontent.com/45249614/142785332-0180c98a-661a-48e0-adfc-b283c31c04b7.png)

**Comment by rionolund** [comment]
I do not.
![FB3D3689-B8DC-4EF6-B4D9-50C8076BFB36](https://user-images.githubusercontent.com/8504905/142786983-fed99ff8-74b6-42d4-a971-a3dc77cfbdbf.png)

**Comment by MelvorIdle** [comment]
That settings needs to be enabled to calculate progress offline while the game is minimized/in the background :)
