### ISSUE TITLE
[Spelling/Grammar]: <title>

### ISSUE THREAD

**Issue by UnseemlyDuck** [MelvorIdle/melvoridle.github.io#1756]
### What text is wrong?

Auto Eat - Tier 1 says cost 1,000K GP

### What is the correct spelling or grammar?

Auto eat - tier 1 actually cost 1,000,000 so perhaps say 1M instead.

**Comment by MelvorIdle** [comment]
This is a nod to how RuneScape formats their numbers.

You can adjust this in the settings:
![image](https://user-images.githubusercontent.com/45249614/143154372-380cedf0-1f00-4a1f-9964-fafd0a176032.png)
