### ISSUE TITLE
[Bug]: goblin raid progress loss

### ISSUE THREAD

**Issue by AnimusM** [MelvorIdle/melvoridle.github.io#1757]
### Describe the bug

After reaching about wave 50, i closed the app (leaving it running in background)
By the time i came back all my progress was gone and i got no rewards.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1342

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue was fixed as of v1.0.2.
