### ISSUE TITLE
[Bug]: Idle progress lost (Mining) 

### ISSUE THREAD

**Issue by Skatterman** [MelvorIdle/melvoridle.github.io#1759]
### Describe the bug

I was Mining for over 9 hours (Coal) when I started the game up in the morning to check on my progress I didn't reviece any of the Items I would have mined for the 9 Hours. I still only had 15 Coal in my bank and lost all of the mining experence I should have earned. 

### Expected behaviour

to recieve Idle mining progress and rewards for Idle time less than 12 hours. 

### Screenshots

[](url
![Screenshot_20211121-061010_Melvor Idle](https://user-images.githubusercontent.com/94789334/142763683-bfcf5da5-d432-4098-80c5-ef549028ffb7.jpg)
![Screenshot_20211121-061015_Melvor Idle](https://user-images.githubusercontent.com/94789334/142763684-67b0ef14-04ee-4dea-993f-45ff04a6c47c.jpg)
![Screenshot_20211121-060954_Melvor Idle](https://user-images.githubusercontent.com/94789334/142763685-9f8e9a7b-c071-402c-af62-0afb07991a02.jpg)
)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1342

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
A fix was released to the game yesterday which addresses the bug you saw. Unfortunately it isn't possible to retrieve the lost progress, but the bug itself has been rectified.
