### ISSUE TITLE
[Bug]: Shop buy limit text appearing twice

### ISSUE THREAD

**Issue by naoliv** [MelvorIdle/melvoridle.github.io#1760]
### Describe the bug

`Buy limit of 88 reached.` is appearing twice on Shop.

### Screenshots

![](https://user-images.githubusercontent.com/982338/142771232-fb25079d-4196-4b62-bd15-3890a77b073a.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1342

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Reproduction steps: 
1. Have Bank slots purchased at maximum
2. Purchase another item in the General Upgrades category
3. Buy limit text is duplicated

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
