### ISSUE TITLE
[Spelling/Grammar]: <title>

### ISSUE THREAD

**Issue by oswampy** [MelvorIdle/melvoridle.github.io#1761]
### What text is wrong?

The text for the minigame is spelled “golbin raid”

### What is the correct spelling or grammar?

The correct spelling is “goblin raid”

**Comment by gregorymcdonald** [comment]
From [MelvorIdle's previous comment on the spelling of "Goblin"](https://github.com/MelvorIdle/melvoridle.github.io/issues/1672#issuecomment-967766915):
> Golbin is the correct and intended spelling

**Comment by oswampy** [comment]
oh ok sorry because when i was fighting it, it said goblin raid
