### ISSUE TITLE
[Bug]: BattleHeart Prayer reducing Enemy DR

### ISSUE THREAD

**Issue by kevolaf** [MelvorIdle/melvoridle.github.io#1762]
### Describe the bug

When activating the Battleheart prayer, the enemy has their DR reduced by 5%. It doesn't indicate this in the text for Battleheart that this should happen.

### Reproduction Steps

1. Attack a monster with DR (Legaran Worm for example).
2. Examine the monster's current DR stat
3. Activate the Battleheart prayer and the enemy will have their DR reduced by 5%

### Expected behaviour

I did not expect the prayer to reduce the enemy's DR by 5% since it is not in the text information for Battleheart.

### Screenshots

![image](https://user-images.githubusercontent.com/91212070/142775792-70e85742-11ee-462c-918d-b7bccf044074.png)
![image](https://user-images.githubusercontent.com/91212070/142775802-28b17c7a-d351-4161-a4ca-2dc9054c84a6.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1342

### Are you using any scripts or extensions?

No

**Comment by arcestia** [comment]
Battleheart seems having hidden bonus

**Comment by kevolaf** [comment]
![image](https://user-images.githubusercontent.com/91212070/142900235-7fbf1d2b-2a5f-4e95-86bc-f741d36341e1.png)
The text was updated. This issue is resolved now.,
