### ISSUE TITLE
[Bug]: Impending Darkness Event showing up after running from Golbin Raid

### ISSUE THREAD

**Issue by varjutus** [MelvorIdle/melvoridle.github.io#1763]
### Describe the bug

I was doing Agility then started Golbin Raid, spent 8 hours doing it on and off because IRL things, then when I ran and went to go do combat, I saw the Impending Darkness Event "Stop Event" and "Show Event Passives" bar. 

This happened even when I started an instance of Golbin Raid and ran immediately before I killed any golbins.
I do not have 99 in all skills or any combat skill for that matter.
Stopping the event while in combat makes you run - learned that while mid Aeris completion :(
The "Show Event Passives" button is functional, though does not display any passives (probably because there are none!).

### Reproduction Steps

1. Start either Agility or Combat - didn't test with other skills
2. Start Golbin Raid
3. Run at some point
4. Click on a combat skill
5. See the bar

### Expected behaviour

For it not to show up

### Screenshots

![image](https://user-images.githubusercontent.com/61955876/142782575-db4239ea-27a2-4e5d-a134-bb31244e802f.png)

### Console output

cannot access console due to admin restrictions

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1342

### Are you using any scripts or extensions?

No

**Comment by arcestia** [comment]
I've reproduced this in other browsers and steam clients. 
Step:
1. start goblin raid (even your running skill or not it still happens)
2. run away from the goblin / didn't test if dead will be produced the bug or not.

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.0.2. Please open a new ticket if this is not the case.
