### ISSUE TITLE
Ring Half A can't drop from woodcutting

### ISSUE THREAD

**Issue by GavroyJ** [MelvorIdle/melvoridle.github.io#177]
**Describe the bug**
The dropRingHalfA() function is missing from cutTree() in woodcutting.js
This function does exist properly in the commented out version of cutTree()

**To Reproduce**
N/A

**Expected behavior**
Ring Half A should drop from all non-combat activities.

**Screenshots**
N/A

**Browser**
Firefox 74.0.1

**Console output**
N/A

**Comment by MelvorIdle** [comment]
Fixed in v0.15
