### ISSUE TITLE
[Bug]: Item log not updating 

### ISSUE THREAD

**Issue by Diequietly** [MelvorIdle/melvoridle.github.io#1771]
### Describe the bug

Collecting black armor for completion log, log shows I’ve collect 2 but hasn’t updated to show the picture 

### Expected behaviour

Show picture of collected item 

### Screenshots

![0544D707-929B-4BC9-A5E7-8C8DD40F59C5](https://user-images.githubusercontent.com/94816847/142796887-bad7eec7-bcf4-40e4-9d0c-3df088412570.jpeg)
![0236D6D3-6DCC-4A93-A448-B13EAE72DDF0](https://user-images.githubusercontent.com/94816847/142796897-f700edd2-f554-4d14-ae7c-2a4727b615ed.jpeg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1342

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue was fixed as of the v1.0.3 update.
