### ISSUE TITLE
[Spelling/Grammar]: <Armor upgrade text incorrect>

### ISSUE THREAD

**Issue by brhaydon** [MelvorIdle/melvoridle.github.io#1772]
### What text is wrong?

![image](https://user-images.githubusercontent.com/89678091/142825933-07bfe853-bd72-4c61-ac4a-d0db0824ce41.png)

Upgrade gives +1 str, not +4. 

### What is the correct spelling or grammar?

+1

**Comment by MelvorIdle** [comment]
The image is correct. The original Mithril Boots provides 0 Strength Bonus. The Silver Mithril Boots you are upgrading to provides 4 Strength Bonus, so +4 comparison.
