### ISSUE TITLE
[Bug]: <title>Smithing exp went to negative after restarting PC

### ISSUE THREAD

**Issue by RingoHanabi** [MelvorIdle/melvoridle.github.io#1773]
### Describe the bug

So I restarted my PC when the game is forging Mithril Bars, and then when I came back my Exp of Smithing went to negative. I thought something happened then I restarted the game and my smithing level was resetted back to level 1 and forged a few mithril bar and quickly leveled up to level 7. 
Took a screen shot when I restarted the game again, as in the image my smithing level was 25 but I can forge mithril bar with what I have in the inventory.
![image](https://user-images.githubusercontent.com/30581009/142833580-13dde393-e9d7-4114-8c08-336af5905fce.png)

### Screenshots

![image](https://user-images.githubusercontent.com/30581009/142833917-5e861405-580a-42e2-96b8-423b1c9357c2.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1346

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Hey! Does this happen every time you restart your computer?

The only way the game creates "negative" XP is if there is a time change on the device itself.

**Comment by coolrox95** [comment]
Issue was fixed in v1.0.2.
