### ISSUE TITLE
[Translation Error]: Var "num" in the tooltip of prayer

### ISSUE THREAD

**Issue by gilles-phan** [MelvorIdle/melvoridle.github.io#1774]
### Which text in the game has a translation error?

name: "${num} par attaque que vous effectuez" (language fr)
description: when I open the tooltip of "Peau dur" ("strong skin") in Prayer menu, the ${num} is not mapped with the correct value.

**Comment by coolrox95** [comment]
Issue cannot be reproduced in latest version of game v1.0.3.
