### ISSUE TITLE
[Bug]: Popup notification animation too slow

### ISSUE THREAD

**Issue by RUSShyTwo** [MelvorIdle/melvoridle.github.io#1775]
### Describe the bug

It's "fun" the 1st time

Then it gets annoying real quick

It is one of tha thing that get thought in UX skills, it's a mistake made by people who don't use the product

Typical from javascript developpers

### Reproduction Steps

1 - Play the game
2 - Get notifications

### Expected behaviour

I expect UI popups to appear instantly so i can click on them right away without having my eyes try to focus, it makes me unfomfortable

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1346

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is more of a suggestion, rather than a bug report.

Please feel free to suggest changes in Discord
