### ISSUE TITLE
[Bug]: <Cloud Save don't show up>

### ISSUE THREAD

**Issue by Feku-32** [MelvorIdle/melvoridle.github.io#1776]
### Describe the bug

Hi, I trying to play in my phone with the character I create but the save never shows up.
I create the cloud save in the steam version but in the phone never shows up.

### Screenshots

![Screenshot_20211122-204853](https://user-images.githubusercontent.com/58609631/142952528-eafb8523-a1c2-4f71-b361-92a194d1e68f.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Hello! Can you please try force saving on the Steam client, the load the game on mobile and see if the cloud saves reappear?

**Comment by Feku-32** [comment]
Hi, I already do that and the cloud save didn't show, maybe I have an issue with my account? My user is Feku32

**Comment by MayanFox** [comment]
I am experiencing the same issue and can now no longer access my character as the local save was overwritten by character 2. Is this save still somewhere in the cloud and recoverable?

**Comment by MelvorIdle** [comment]
If a save is overwritten then unfortunately it can't be recovered.
