### ISSUE TITLE
[Bug]: Rounding in mastery pools

### ISSUE THREAD

**Issue by Insanitytruth** [MelvorIdle/melvoridle.github.io#1777]
### Describe the bug

As of the most recent update, every mastery xp pool's completion bar rounds to the nearest percent, while before it would be rounded to the nearest hundredth of a percent.

### Reproduction Steps

Having xp in the mastery pool not exactly/almost exactly equal to a percentage point of the maximum mastery pool xp will make the issue easily observable.

### Expected behaviour

I would expect the mastery pool % fullness indicator to round to hundredths of a percent like it used to.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1346

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
A hotfix has now been released for this.
