### ISSUE TITLE
[Bug]: Monkey Salamander Crafting Synergy Not Working For New Rings

### ISSUE THREAD

**Issue by JinNada** [MelvorIdle/melvoridle.github.io#1778]
### Describe the bug

Monkey Salamander synergy gives +33% chance to preserve resources in Crafting when creating Rings or Amulets only.  The +33% is correctly applied and visibly adjusts for all the rings and amulets except the new Ring of Blade Echoes, Ring of Barrage, and Ring of Spirit Power.

### Reproduction Steps

Go to the Rings Crafting page.  Select one of the new rings.  Equip the synergy. 

### Expected behaviour

Chance to preserve should go up by +33%.  It does not.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1346

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is now hotfixed
