### ISSUE TITLE
[Bug]: Inventory Filter Doesn't Apply To Items Added To Bank After Search

### ISSUE THREAD

**Issue by JinNada** [MelvorIdle/melvoridle.github.io#1779]
### Describe the bug

When searching for items in the bank, if you add any items to your bank that weren't there when you started the search they won't be properly filtered out.

### Reproduction Steps

E.g.
Search "diamond" in bank.  Start thieving Bob while you have no seeds in your bank.  Go back to bank that is still filtered by "diamond".  The seeds you are stealing will show up.

### Expected behaviour

The seeds should not show up because you are currently filtering by "diamond" and the seeds do not fall under that.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1346

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
