### ISSUE TITLE
Skills Completion calculated improperly

### ISSUE THREAD

**Issue by GavroyJ** [MelvorIdle/melvoridle.github.io#178]
**Describe the bug**
In the Completion Log, the Skills percentage is calculated using:
skillLevel.length * 99

However skillLevel is instantiated with 22 elements, though index [20] and [21] are not accessible due to there only being 20 entries in CONSTANTS.skill

**To Reproduce**
Level all skills to 99
Completion log shows Skills : 91%

**Expected behavior**
skillLevel should be instantiated with the correct number of available skills.

**Screenshots**
![SkillCompletion](https://user-images.githubusercontent.com/17521466/79033640-b9a89280-7b64-11ea-93cb-7140751b0b09.png)

**Browser**
Firefox 75.0

**Console output**
N/A

**Comment by MelvorIdle** [comment]
Fixed in v0.15
