### ISSUE TITLE
[Bug]: Magic Furnace not functioning in background

### ISSUE THREAD

**Issue by StoicOak** [MelvorIdle/melvoridle.github.io#1780]
### Describe the bug

On Mobile (Android) running v1.0 (?1346), at level 99 cooking, while attempting to actively cook using the Magic Furnace, when navigating away from the app or putting my device to sleep, it would stop the active cooking process. 
![Screenshot_20211122-230757_Melvor_Idle](https://user-images.githubusercontent.com/94891447/142983190-54b9c16d-deae-48a5-899c-0ce3d1840f2a.jpg)

### Reproduction Steps

Level 99 Cooking
Have all Cooking Upgrades aside from Cooking Upgrade 1 (Automatically equip food that is actively cooked if that food is already equipped or an empty slot is available)
Select a recipe to cook from the Magic Furnace
Select Active Cook
navigate away from Application
Upon returning to the Application, it will display a zero xp gained message.

### Expected behaviour

I expect to have the recipe crafted during downtime.

### Screenshots

https://imgur.com/a/bRQs5Pl

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1346

### Are you using any scripts or extensions?

No

**Comment by SuperSaiyan06** [comment]
Can confirm this is occurring on iOS as well.

**Comment by coolrox95** [comment]
Cooking has been rewritten as of v1.0.3.
