### ISSUE TITLE
[Bug]: no astro buffs for pooled items

### ISSUE THREAD

**Issue by deflfl** [MelvorIdle/melvoridle.github.io#1781]
### Describe the bug

When you level astrology items with pool exp you don't get any new buffs unless you enter its section manually

This item was pooled to 60 mastery
![unknown](https://user-images.githubusercontent.com/94895942/142992951-0c7107f8-39bd-4b94-86a8-52f9f7677061.png)

Buff section before you press explore on "Ameria"
![unknown](https://user-images.githubusercontent.com/94895942/142993363-55b41ea0-d734-4cd7-870c-eaa05565f473.png)

Buff section after you press explore on "Ameria"
![unknown](https://user-images.githubusercontent.com/94895942/142993367-3ee9b454-8b35-4dc5-ae3f-24a4db025921.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1346

### Are you using any scripts or extensions?

Yes

**Comment by MelvorIdle** [comment]
A hotfix has now been applied to the game.
