### ISSUE TITLE
[Bug]: Witch and Cyclops Synergy Underrewarding

### ISSUE THREAD

**Issue by Lejero** [MelvorIdle/melvoridle.github.io#1782]
### Describe the bug

The summoning synergy between the Witch and the Cyclops says it will grant slayer coins equal to 2% of your magic damage. In using this the reward seems low. For example. on a hit of 1232 I received 2 slayer coins when I would expect 24 or 25.

I'm unsure of the calculation but one suspicion is that it might be scaling to a percentage of my minimum damage which in the above case was 570 but by percentage of maximum perhaps (4028 in this case). Another case netted me 5 slayer coins off 2499 damage with the same underlying stats.

### Reproduction Steps

1. In battle
2. Have the cyclops and witch tablets equipped while using magic.
3. Observe the damage done and slayer coins rewarded.
4. The coins rewarded are significantly lower than (0.02) x Damage Dealt.

### Expected behaviour

The coins rewarded on each hit should be 2% of the damage the hit did to the enemy or the description of the synergy should be rewritten to be more explicit.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1347

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Are you playing Adventure Mode? This would be a bug relating to the % not adjusting correctly to the increased scaling of damage numbers.

**Comment by Lejero** [comment]
Yes, this is in adventure mode.
