### ISSUE TITLE
[Bug]: Character Selection Screen failing to load

### ISSUE THREAD

**Issue by Achvonzalbrecht** [MelvorIdle/melvoridle.github.io#1783]
### Describe the bug

On app startup, the app loads and then appears with the attached screen instead of character selection on Android.

I have also attempted to log into my cloud account on my desktop and I have no cloud saves before mid September now. I know that I have used the cloud save function to change devices for that save as late as November 15th, so that does not make sense to me.

### Reproduction Steps

Unsure if it is reproducible 

### Screenshots

![313D5924-BBE0-497A-B342-C12C1D46A747](https://user-images.githubusercontent.com/94912345/143036695-ad4fe813-1306-4f02-a9d0-6c888947d11e.jpeg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

This screen is inaccessible

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Hello! Can you please confirm if this is still occurring for you?

Please try clearing the app cache to see if that fixes the issue.

**Comment by Achvonzalbrecht** [comment]
I cleared the cache and it started working again, thanks!
