### ISSUE TITLE
[Spelling/Grammar]: <title>Ancient Magic acquisition text is reversed

### ISSUE THREAD

**Issue by abcras** [MelvorIdle/melvoridle.github.io#1784]
### What text is wrong?

![image](https://user-images.githubusercontent.com/3748122/143074792-4d8aa37a-dce9-4324-abd2-2f78245690e7.png)

### What is the correct spelling or grammar?

You are missing x Volcanic Cave clears
|| You need x more clears of Volcanic Cave

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
