### ISSUE TITLE
[Bug]: cooking duplication bug

### ISSUE THREAD

**Issue by TheHcOmega** [MelvorIdle/melvoridle.github.io#1785]
### Describe the bug

Cooking whales/perfect whales (potentially any food but haven't tried others) in a greatly reduced time whilst not using any raw whales.

### Reproduction Steps

Set whales to cook
Minimise the window
Reopen the window quickly

The game will welcome you back having cooked a whale whilst not using any raw whales

### Expected behaviour

To cook in the specified passive cook time and to use raw materials for the amount has been cooked

### Screenshots

![Screenshot_20211123-175020_9737de6f3e36012ce6703231c8d3c3a2](https://user-images.githubusercontent.com/93677537/143079518-66894182-8512-4d67-81c6-1a774f1dd61a.jpg)
![Screenshot_20211123-175025_9737de6f3e36012ce6703231c8d3c3a2](https://user-images.githubusercontent.com/93677537/143079564-30794666-beb8-4396-a5bb-fc46bbdd2a66.jpg)
![Screenshot_20211123-175029_9737de6f3e36012ce6703231c8d3c3a2](https://user-images.githubusercontent.com/93677537/143079583-50ea0b26-424f-49b6-aad4-48595dcc8356.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1341

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This could very well be a visual bug with the quantity displayed in the bank. Does the quantity update if you completely restart the game, or cook another Whale online?

Eg. if you have 7,000 Raw Whales, produce the bug to cook 2 Whales and still see 7,000 - does this number update to around 6,997 if you cook one more Whale online?

**Comment by TheHcOmega** [comment]
I have replicated the bug and can confirm it is as you suspected a
visual error. Once the next whale is cooked the quantity of raw whales
updates and corrects itself.

Apologies for the confusion.

**Comment by coolrox95** [comment]
Cooking has been rewritten as of v1.0.3.
