### ISSUE TITLE
Hardcore character died but wasn't deleted

### ISSUE THREAD

**Issue by VelvetShadow** [MelvorIdle/melvoridle.github.io#1786]
### Describe the bug

I made a new hardcore character to try out hardcore combat only yesterday, and afk'd too hard today and I died. However, my character did not get deleted...

### Expected behaviour

I expected my character to disappear like it's supposed to lol

### Screenshots

![IMG_20211123_130458410](https://user-images.githubusercontent.com/91964313/143080374-7da809a5-aa55-4cef-98ba-5ec6b6edbc5b.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1347

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Could you confirm if this Hardcore character was created prior to the Public Beta v1.0 update?

We added a safeguard for Hardcore characters, and granted 1 free death due to the amount of changes that occurred.

**Comment by VelvetShadow** [comment]
![Screenshot_20211124-094249](https://user-images.githubusercontent.com/91964313/143259335-fe634529-530c-4b62-9edd-f2996d0a6ccf.png)

**Comment by MelvorIdle** [comment]
I say take the free death and I will continue to monitor if it occurs again :)
