### ISSUE TITLE
Lobster only adds perfect to bank[Bug]: <title>

### ISSUE THREAD

**Issue by phorden** [MelvorIdle/melvoridle.github.io#1788]
### Describe the bug

When running the app with an active window (not offline), when cooking raw lobster with the 5s active cooking.

1. lobster shows success on cook for regular lobster, but does not get added to bank.
2. Perfect lobster does get added to bank.
3. Regular lobster will get added as long as I am offline.

### Reproduction Steps

1. Select raw lobster to cook.
2. Click active cooking (5 seconds)
3. when lobster cooks either:

1. Perfect gets added to bank as normal.
2. Regular cooked does not get added to bank. (except when cooked offline).

### Expected behaviour

regular lobster gets added to bank when cooked.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1347

### Are you using any scripts or extensions?

No

**Comment by TJOak** [comment]
I think you have "Automatically equip food when it is made" enabled in Cooking.
(Which doesn't work for food cooked while offline, so I guess that part's still a bug.)

**Comment by coolrox95** [comment]
Issue with auto-equipping food not working while offline, was fixed as of the v1.0.3 update.
