### ISSUE TITLE
pet Completion[Bug]: <title>

### ISSUE THREAD

**Issue by zcd394424082** [MelvorIdle/melvoridle.github.io#1790]
### Describe the bug

My pet has collected 44/45, but the completion degree is still 43/45

### Expected behaviour

Can accurately count my completion

### Screenshots

![VI{3DKL{646WVQX8IDZ1P(N](https://user-images.githubusercontent.com/26991581/143155744-69b4aa7c-df8e-4e85-86bf-79aba7c7722e.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1347

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Relates to #1771

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
