### ISSUE TITLE
[Bug]: Firemaking 50% checkpoint perk shortchanging

### ISSUE THREAD

**Issue by SGTBizarro** [MelvorIdle/melvoridle.github.io#1792]
### Describe the bug

The Firemaking 50% mastery checkpoint perk is supposed to pay 25% of the value of the log being burned.

I'm currently burning Yew logs which have a value of 112 GP.

25% of 112 is 28 GP, however I'm being paid 18 GP per log instead.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1341

### Are you using any scripts or extensions?

No

**Comment by SGTBizarro** [comment]
![Screenshot_20211124-000126](https://user-images.githubusercontent.com/94953551/143190784-71d0539b-fcf4-4557-be5c-6efb55ff522e.png)
![Screenshot_20211124-000145](https://user-images.githubusercontent.com/94953551/143190806-693b71fb-3f55-48cf-b2b5-38f00654f48d.png)

**Comment by SGTBizarro** [comment]
Subversion shouldve been 1347

**Comment by cairnsjr13** [comment]
Yew logs are actually only worth 75.  You have the woodcutting checkpoint (50%) active that gives you +50% gp from log sales.  25% of 75 is just shy of 19, which is why you are seeing that.

It's unclear if the checkpoint bonuses are supposed to stack.  If not, I guess this is working as expected, if so, definitely a bug.

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
