### ISSUE TITLE
[Bug]: Hardcore character died, flashed giant summary screen for 1 second then returned to home

### ISSUE THREAD

**Issue by Tyriar** [MelvorIdle/melvoridle.github.io#1793]
### Describe the bug

My level 1500+ hardcore character just died and the experience was pretty crappy, not because I died but because I don't understand how. I logged in and had a huge summary screen which appears to show all my items were lost and it went away within a second or two and I was put back on the home screen without knowing what actually happened. This left me feeling unsure whether I just hit a bug or actually died due to my own negligence.

### Expected behaviour

When you die in hardcore you lose potentially many months of investment, so the summary screen showing how you died should be displayed until manually dismissed so the player can process the information without feeling cheated.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1348

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
The "death" experience is something we are looking into for Hardcore Characters. Currently what you experienced is exactly what its supposed to do if you die offline.
