### ISSUE TITLE
[Bug]: Equipped Summoning Tablet Rounding Error on tooltip

### ISSUE THREAD

**Issue by brad-wist** [MelvorIdle/melvoridle.github.io#1794]
### Describe the bug

<img width="351" alt="2021-11-24_15-27-17 (1)" src="https://user-images.githubusercontent.com/34142411/143256750-ae01c9a5-a37d-4bd2-8848-68f92d324f20.png">
Tooltip info shows a rounding error seemingly only for centaur when equipped

### Reproduction Steps

equip centaur tablet, view on combat page

### Screenshots

<img width="351" alt="2021-11-24_15-27-17 (1)" src="https://user-images.githubusercontent.com/34142411/143256750-ae01c9a5-a37d-4bd2-8848-68f92d324f20.png">

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1348

### Are you using any scripts or extensions?

Yes

**Comment by coolrox95** [comment]
Issue can still be reproduced as of the v1.0.3 update

**Comment by coolrox95** [comment]
Issue has been hotfixed as of v1.0.3 (?1834).
