### ISSUE TITLE
[Bug]: Cooking Apple Pie's do not appear in Inventory

### ISSUE THREAD

**Issue by AlexS220** [MelvorIdle/melvoridle.github.io#1795]
### Describe the bug

Using a Strong Furance and trying to cook the Apple Pie recipe. The pie is being created but is not getting added to the bank. 

Before:
![image](https://user-images.githubusercontent.com/60105998/143270591-823472e2-559b-4882-8407-4b496ee35b2d.png)

After:
![image](https://user-images.githubusercontent.com/60105998/143270644-2759b48e-29ae-4ebf-a1a1-1b23b2fd0f4b.png)

As you can see two pie's were created but the "in bank" of the amount of pie's in your bank icon was not updated nor was the amount increased in the bank. 

I found that this DOES work if you close the game and let it cook while the game is closed. But if you are trying to cook with the game open on steam than it will just eat your resources and give you only EXP and mastery but no pie's

### Reproduction Steps

1. Upgrade to Strong Furnace
2. Start cooking 'Apple Pie' Recipe 
3. Look to see if the apple pie's are being added to your inventory

### Expected behaviour

I expect that cooking apple pie's should go directly to your inventory when the game is opened on steam. And not only give you the cooked item when the game is closed.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1348

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Please confirm if you have this setting enabled in Cooking:
![image](https://user-images.githubusercontent.com/45249614/143512265-28bbacc5-64d8-4dd2-9370-4bdd6f40023d.png)

**Comment by AlexS220** [comment]
Yep.... That was the Issue apologies I am an idiot 👍
