### ISSUE TITLE
[Spelling/Grammar]: Mastery Token (Astrology)

### ISSUE THREAD

**Issue by JohnC94** [MelvorIdle/melvoridle.github.io#1796]
### What text is wrong?

The title of the Astrology mastery token is missing the parenthesis that the other tokens have.
![image](https://user-images.githubusercontent.com/19755463/143296712-9a4facb8-5086-4287-bb98-56b03ffdc723.png)

It is also missing its description.
![image](https://user-images.githubusercontent.com/19755463/143296795-3a0f58dd-b4b7-4dd0-ac0a-ee9d0afed890.png)

### What is the correct spelling or grammar?

Mastery Token (Astrology)

Grants Mastery Pool XP equal to 0.1% of the maximum Mastery Pool XP for the respective skill.

**Comment by MelvorIdle** [comment]
This has not been hotfixed
