### ISSUE TITLE
[Bug]: Purchased Premium on Mobile, Didn't transfer to PC Version

### ISSUE THREAD

**Issue by lSeanl** [MelvorIdle/melvoridle.github.io#1797]
### Describe the bug

Pretty much the title. I bought premium on the phone, but when I load my cloud save on the PC version I doesn't have access to any of the premium skills/content. 

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1348

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Please refer to this post: https://www.reddit.com/r/MelvorIdle/comments/qgkmu9/information_regarding_premium_mobile_users_and/
