### ISSUE TITLE
[Bug]: purchased game on steam and account still not premium in ios

### ISSUE THREAD

**Issue by HoyWatermelon** [MelvorIdle/melvoridle.github.io#1798]
### Describe the bug

Hi I started play Melvor Idle on ios app, and just purchased game on steam. But my account still is not premium account, I created new one is same problem. Please help

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1341

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Please follow these steps:

1. Log in to your cloud account on the Steam Client and load a character.
2. Log out of your cloud account on mobile, and log back in to the same one you used on Steam
3. You should have premium
