### ISSUE TITLE
[Bug]: “Not Found” error when starting game on iPad

### ISSUE THREAD

**Issue by Al-Alanood** [MelvorIdle/melvoridle.github.io#1799]
### Describe the bug

Hello. I suddenly got a not found error when I started the game on my iPad. I didn’t do anything lately, last time I updated from the AppStore was a week ago, and same goes for IAP. I don’t use Melvor Cloud. Tried multiple WiFi networks.

Game version: 1.0
iOS: 14.7.1 

### Screenshots

![1D2CB685-FF7F-49CC-A1CE-6F63193AB59C](https://user-images.githubusercontent.com/95025445/143426661-c02a526c-8436-4f26-aaf2-c14766c3d57e.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

(I have no access to it)

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Can you please confirm if this is still occurring now?

**Comment by Al-Alanood** [comment]
Yes. I just checked.

**Comment by MelvorIdle** [comment]
This will require a reinstall of the app itself.
