### ISSUE TITLE
Gold trimmed Mithril gear still has incorrect Melee Defense Bonus Stats

### ISSUE THREAD

**Issue by NotArcanus** [MelvorIdle/melvoridle.github.io#18]
**Describe the bug**
The Melee Strength for gold trimmed Mithril equips was fixed but the defense remains lower than the previous silver upgrade

**To Reproduce**
1. Go to a Silver trimmed Mithril item menu
2. Click on 'Upgrade'
3. See that the Defense Bonus has (+-\#)

**Expected behavior**
Stats continuing to increase from Silver trimmed equip

**Screenshots**
![https://prnt.sc/pvowsv](https://image.prntscr.com/image/iUBoRevwTraSXGJa4SOb8A.png)

**Comment by MelvorIdle** [comment]
Fixed in v0.09.2
