### ISSUE TITLE
Regeneration Potion "Hipoints"

### ISSUE THREAD

**Issue by DevWizaad** [MelvorIdle/melvoridle.github.io#180]
A (most-likely) misspelling of the word Hitpoints on the Herblore page for Regeneration Potions:
"X% INCREASED HIPOINTS REGENERATION"

![chrome_2020-04-13_07-31-39](https://user-images.githubusercontent.com/25888029/79128896-1a002580-7d59-11ea-9f5a-416f18fbf03f.png)

**Comment by MelvorIdle** [comment]
Fixed in v0.15
