### ISSUE TITLE
[Bug]: Missing button 'Extra Bank Tabs' in shop: +1 Maximum Bank Tab

### ISSUE THREAD

**Issue by MountainOfBooks** [MelvorIdle/melvoridle.github.io#1800]
### Describe the bug

Currently only 10 Bank Tabs are available to organise the inventory. It's not possible to extend the maximum bank tab limit.

Please note: The Bank Tab upper limit should at least be around 30 (instead of 10) and people should be able to decide themselves how many bank tabs they want to use (think of people with O.C.D. or who like to have everything nice and neat).

![Melvor - Bank Tabs](https://user-images.githubusercontent.com/95026381/143429570-fd1d2692-d899-4386-a242-a5365b5ffdd1.PNG)

### Reproduction Steps

1. Start MelvorIdle.
2. Go to Shop.
3. Go to the General section => No 'Extra Bank Tab' available. 

### Expected behaviour

Add 'Extra Bank Tab' (+1 Maximum Bank Tab) to Shop.

### Screenshots

N/A

### Console output

N/A

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

1348

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Hey! This is not a bug, but a suggestion. Please keep GitHub for bugs only
