### ISSUE TITLE
[Bug]: Goblin Raids progression fast action bar missing 

### ISSUE THREAD

**Issue by W875t** [MelvorIdle/melvoridle.github.io#1801]
![467DAF0E-7193-45BB-BFA4-DA282023752B](https://user-images.githubusercontent.com/95038332/143464318-027599ce-e92a-4350-adae-83cb4343eff5.png)

Bug 2 the missing Quick Eat, Run and HP bar 
 

![BF510793-2214-4A2A-A7A0-1CD7A1626FAD](https://user-images.githubusercontent.com/95038332/143464335-da11dc80-2abc-4a27-9c38-84b12f8ee7de.png)

During the Raid

![7408EFA1-A5B9-414C-A099-49A97E77DCAD](https://user-images.githubusercontent.com/95038332/143464345-d063f674-c81a-440c-b757-565555a792fc.png)

After closing and reopening the game Ana’s caging the shop to see if I got coins.

### Describe the bug

When playing a game of goblin raid if you are chit the app you will loos all progress gained and receive no coins. The other bug is the Quick eat and quick run/select bar disappears if you click to look at another menu (eg look at wood cutting) then go back to it that bar will disappear. This is on IOS 

### Reproduction Steps

Bug 1- open and play 5-10 round of goblin raid on IOS then close the app. When reopening all progress is gone. 

Bug 2- play 5 rounds of goblin raid then use the 3 lined menu button in the top left to open and switch tabs. Then go back to the goblin raid that is still running find just no fast eat / fast run bar with your go view

### Expected behaviour

Bug1- all progress is lost. Like you did not even play the goblin Raid at all 

Bug2- the fast eat/ Run bar showing your HP disappears forcing me to scroll up and down to view the HP lv, manually eat food and Run/ exist the goblin Raid

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

V1.0

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue was resolved as of v1.0.2.
