### ISSUE TITLE
[Bug]: Responsive layout issue

### ISSUE THREAD

**Issue by user8342912** [MelvorIdle/melvoridle.github.io#1802]
### Describe the bug

Between 1200px - 1250px the select your account page has a different layout compared to < 1200px and > 1250px

First 2 screenshots show above 1250px and below 1200px.

Last 2 screenshots show between 1200px and 1250px.

<img width="1184" alt="screenshot-less-1200px" src="https://user-images.githubusercontent.com/93920643/143492200-224461a0-47ff-4c43-8e21-07b38bcb2e83.png">
<img width="1265" alt="screenshot-greater-1250px" src="https://user-images.githubusercontent.com/93920643/143492205-b97f7e23-925c-485f-88ca-29f476ccdc3b.png">

<img width="1226" alt="screenshot-1200-1250" src="https://user-images.githubusercontent.com/93920643/143492221-ec200aeb-c59f-4fe4-9965-cb202ac15efb.png">
<img width="1226" alt="screenshot-1200-1250-scrolled" src="https://user-images.githubusercontent.com/93920643/143492233-726e6410-ea41-4822-894d-4ef37fcd7c1c.png">

.

### Reproduction Steps

1. Open Melvor Idle at a screen width of 1200px - 1250px.
2. Accounts aren't visible without scrolling the window height.

### Expected behaviour

This isn't a major problem, but I play at this width and it's just annoying when switching accounts. The layout doesn't need to be different to the mobile and desktop layouts as they are similar, in terms of allowing you to select an account without scrolling.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1348

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
A fix has been applied for this. However it may take some time for it to display in the game due to caching of the CSS file.
