### ISSUE TITLE
[Bug]: Mole + Octopus Synergy not working in fishing

### ISSUE THREAD

**Issue by Stinolez** [MelvorIdle/melvoridle.github.io#1803]
### Describe the bug

I have the Mole + Octopus synergy unlocked, but it's not working. The Mole familiars are not consumed and only Octopus familiars are used while Fishing.

### Reproduction Steps

1. Equip Mole + Octopus synergy
2. Start fishing

### Expected behaviour

I'd expect that the Mole Tablets would be used whenever receiving gems while fishing.

### Screenshots

![IMG_2757](https://user-images.githubusercontent.com/10723745/143498032-0ef40366-79a8-437c-b3de-d633a1c9f6e9.png)
![IMG_2758](https://user-images.githubusercontent.com/10723745/143498033-b1123ca0-2c94-4099-9b4d-3db93e012a0a.png)
![IMG_2756](https://user-images.githubusercontent.com/10723745/143498034-2e80b884-501a-48b0-9bf4-4e0e4b50ccb2.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1348

### Are you using any scripts or extensions?

No

**Comment by Stinolez** [comment]
Ok, it seems like few mole tablets are used, but they are not shown in the offline progression recap, also - I'd assume every time you are getting gem from the fishing at least would be tablet used, but the numbers don't correlate - I was offline for about two or three hours, got about 200-300 gems and only about 20 mole tablets were used.

**Comment by coolrox95** [comment]
Issue was hotfixed in version 1.0.3 (?1822).
