### ISSUE TITLE
[Bug]: Barbarian fishing gives no strength XP on catching a special item

### ISSUE THREAD

**Issue by oorzkws** [MelvorIdle/melvoridle.github.io#1805]
### Describe the bug

When fishing at the barbarian fishing hole, you do *not* gain strength XP if you succeed the roll for a special item.

You can see why in the decision logic below:
```js
if (random < specialChance && tutorialComplete) {
  xpToAdd = items[itemID].fishingXP;
  itemID = selectFromLootTable(CONSTANTS.skill.Fishing, 0);
  if (getMasteryPoolProgress(CONSTANTS.skill.Fishing) >= masteryCheckpoints[3] && rollPercentage(25)) {
    addItemToBank(selectFromLootTable(CONSTANTS.skill.Fishing, 0), 1);
    game.stats.Fishing.add(FishingStats.SpecialItemsCaught, 1);
  }
  fishingStat = FishingStats.SpecialItemsCaught;
} 
else if (random < junkChance + specialChance && tutorialComplete) {
  let junk = Math.floor(Math.random() * junkItems.length);
  itemID = junkItems[junk];
  xpToAdd = 1;
  fishingStat = FishingStats.JunkCaught;
} 
else {
  xpToAdd = items[itemID].fishingXP;
  if (items[itemID].strengthXP !== undefined) strXPToAdd = items[itemID].strengthXP;
}
```

### Reproduction Steps

Fish at the barbarian fishing hole
Catch a special item
Observe strength XP does not increase

### Expected behaviour

Strength XP should increase even when a special item is caught - we get mastery and fishing XP on a special catch, no reason STR shouldn't apply as well.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1349

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This has not been hotfixed

**Comment by oorzkws** [comment]
> This has now been hotfixed

Saw the note in-game, thanks for the fix 👍
