### ISSUE TITLE
Saved, accidentally logged out, loaded latest save, had lost 3 days' worth of work.

### ISSUE THREAD

**Issue by Momnipotence** [MelvorIdle/melvoridle.github.io#1806]
### Describe the bug

I force saved and walked away. When I came back my hand slipped and the screen went back to the login page. Both "saved" options were the one I'd just done. I loaded it and found I was missing three days' work.

I hollered in disbelief.

This is the SECOND time this has happened in one week.

I'm frustrated.

### Expected behaviour

I expected that my save would actually, you know, **_save_** what I had accomplished up until that point.

### Screenshots

I obviously don't have before and after pictures because it didn't occur to me I'd need them.

### Console output

I have no idea what this means.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

I must not be in the right place bc I don't see this and dk where to find it.

### Are you using any scripts or extensions?

No

**Comment by CarrotMD** [comment]
Have you tried slipping the hand less, seeing it happened twice?

**Comment by Momnipotence** [comment]
I wasn't clear in my post, the problem that repeated was that I lost days'
worth of [akf] "work". The first time it happened when I was going between
devices - and yes, I was very careful about which save I used. I'm ALWAYS
very careful.

**Comment by Momnipotence** [comment]
And besides, once I save it shouldn't matter if my hand slips, should it?
;-p

**Comment by Momnipotence** [comment]
Why closed?? I had several outstanding issues.
