### ISSUE TITLE
Bought premium through phone app, not getting it on laptop

### ISSUE THREAD

**Issue by Momnipotence** [MelvorIdle/melvoridle.github.io#1807]
### Describe the bug

Bought premium through my phone. Not getting it on laptop version.

### Expected behaviour

That when I paid for premium it would be there across platforms.

### Screenshots

<img width="236" alt="Screen Shot 2021-11-26 at 7 54 18 AM" src="https://user-images.githubusercontent.com/95091010/143598797-1702d06c-ebc5-4155-98e3-45649d50ecec.png">

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

Can't find this number

### Are you using any scripts or extensions?

No

**Comment by gregorymcdonald** [comment]
I'm also experiencing this issue.

I initially created my account using the web, and played for several days before purchasing Premium.
I purchased Premium while connected to my Cloud account on my iOS device (v14.8.1), and I am unable to access the premium features on my browser (Chrome).

I've tried:
* Relogging into Cloud account on web.
* Relogging into my Cloud account on mobile.
* Enabled the **Connect Device** setting under **Mobile Push Notification Settings**
* Loading a save performing a Premium-only activity on web (Astrology). This works correctly, but I am unable to open the skill menu: 
<img width="520" alt="Screen Shot 2021-11-27 at 11 10 22 AM" src="https://user-images.githubusercontent.com/9324725/143688664-1e7c708f-ea72-4e64-b6d4-15b028e16fe5.png">

![image](https://user-images.githubusercontent.com/9324725/143688710-1b50e170-abe5-49f6-8f7c-4ae2915f1be9.png)


Console Output (web):
![image](https://user-images.githubusercontent.com/9324725/143688640-e7c4dfca-7dd3-4c43-9745-5985cd615527.png)

**Comment by gregorymcdonald** [comment]
Just found this [message from Malcs](https://discord.com/channels/625838709203271680/625855583550963713/902719742694006795) in the Discord regarding this issue posted on Oct 26, 2021:
> The premium feature where buying the game on Mobile and logging into the PC version is not currently implemented.

Given this, this issue should be closed I guess.
