### ISSUE TITLE
[Bug]: Inverted inventory colors

### ISSUE THREAD

**Issue by ignasuu1** [MelvorIdle/melvoridle.github.io#1809]
### Describe the bug

Serms like the icon colors are inverted. I have Dark Mode active, I think that's what causes this issue.

### Reproduction Steps

1. Enable dark mode.
2. Open inventory

### Expected behaviour

Normal icon colors

### Screenshots

![Screenshot_2021-11-26-22-19-41-413_com malcs melvoridle](https://user-images.githubusercontent.com/95103937/143627086-52720a8c-9258-48b2-9a74-bc01d6dc836c.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1349

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is due to a recent Android WebView update. Nothing I can do about it until Google fixes that.

You need to uninstall the latest Android WebView update from google play

**Comment by ianldgs** [comment]
@MelvorIdle can you link to any issue on webview/Chrome?

I'm having the same problem. So annoying, can't differentiate items in the bank.
If I open the game on Chrome, icons look normal, while in the android app, it looks too bright.
Aren't webview and Chrome the same? (Chromium engine under the hood)

**Comment by MelvorIdle** [comment]
They aren't the same.

WebView recently updated which caused issue with the game when your device is set to dark mode. There isn't anything I can do about it unfortunately, as it is from an update outside of my control.

It's been confirmed that removing the webview update or disabling dark mode is the only fix.

**Comment by ianldgs** [comment]
I can confirm, turning off dark mode does fix it, thanks for the workaround!

But have you tried tweaking the force dark mode settings?

```
if (WebViewFeature.isFeatureSupported(WebViewFeature.FORCE_DARK_STRATEGY)) {
    WebSettingsCompat.setForceDarkStrategy(myWebView.getSettings(), WebSettingsCompat.DARK_STRATEGY_WEB_THEME_DARKENING_ONLY);
}
```

Quoting [this](https://stackoverflow.com/a/61643614) SO answer:

> The force dark feature for webview content has two so-called strategies:
> - User agent darkening: The webview will set its content to dark mode by automatically inverting or darkening colors of its content.
> - Theme based darkening: The webview will change to dark mode according to the theme of the content (which includes the @media (prefers-color-scheme: dark) query).

`DARK_STRATEGY_USER_AGENT_DARKENING_ONLY` (default)
> Only use user agent darkening and ignore any themes in the content

`DARK_STRATEGY_WEB_THEME_DARKENING_ONLY`
> Only use the dark theme of the content itself to set the page to dark mode. If the content doesn't have a dark theme, the webview won't apply any darkening and show it "as is".

(Requires webview v83)
