### ISSUE TITLE
[Spelling/Grammar]: Not-capitalized "gives" in Frostburn description

### ISSUE THREAD

**Issue by vbion** [MelvorIdle/melvoridle.github.io#1811]
### What text is wrong?

The Frostburn definition that is used everywhere reads as follows:

> An unavoidable attack that deals up to 100% of the enemy's normal damage. gives you 3% of Current Hitpoints taken as damage per Attack and +10% Attack Interval for 2 of your turns. 

The error is in the "damage. gives" part because I think "gives" should be capitalized.

### What is the correct spelling or grammar?

Capitalized "Gives", in other words:

An unavoidable attack that deals up to 100% of the enemy's normal damage. Gives you 3% of Current Hitpoints taken as damage per Attack and +10% Attack Interval for 2 of your turns.

**Comment by ymeynot45** [comment]
When you change this you should also change the text from...
"Attack and +10% Attack Interval for 2 of your turns."
to
"Attack and +10% Attack Interval for 3 of your turns."
As it affects your current turn and 2 additional turns after your current turn.

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
