### ISSUE TITLE
[Spelling/Grammar]: "enemy" in the Confusion attack of Wicked Greater Dragon

### ISSUE THREAD

**Issue by chill-was-taken** [MelvorIdle/melvoridle.github.io#1812]
### What text is wrong?

The Confusion attack of Wicked Greater Dragon reads as  
> An avoidable attack that deals 75% of the enemy's max hit damage.

Throughout the [Special Attacks](https://wiki.melvoridle.com/w/Special_Attacks#Monster_Special_Attacks) of other monsters, the definitions of "enemy" and "you" are always consistent.  
"Enemy" means the monster and "you" means the player.  

However if we were to use the same logic in the case of the Confusion attack, it would say that it always does 0.75 * 120 = 90 magical damage, which is not true.  
From what I know, the Confusion attack calculates the damage based on the max hit of the player.

### What is the correct spelling or grammar?

Unless it's an intentional joke, the definition of the Confusion attack for Wicked Greater Dragon uses "enemy" inconsistently.  
Instead, it should use "you". Thus, the correct description would be:
> An avoidable attack that deals 75% of your max hit damage.

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
