### ISSUE TITLE
[Bug]: Dying in hardcore while afk does not delete save on iPhone

### ISSUE THREAD

**Issue by hvaara** [MelvorIdle/melvoridle.github.io#1813]
### Describe the bug

Dying in hardcore while afk does not delete save. Standard death popup is shown.

### Reproduction Steps

1. Create new hardcore game.
1. Start fighting plants.
1. Enable AFK Combat.
1. Switch to another character.
1. Come back to new character in 15 minutes.
1. You are dead, but you can continue playing.

### Expected behaviour

Notification of death. Save game deleted.

### Screenshots

![image](https://user-images.githubusercontent.com/1535968/143690031-db41ed87-e0ae-4ce1-99b3-63bf733b8b35.png)
![image](https://user-images.githubusercontent.com/1535968/143690046-fdaf4fce-2b03-4f32-8165-5ff8188d78b2.png)
![image](https://user-images.githubusercontent.com/1535968/143690051-43e3c8a4-02a0-4ac6-8229-9dc84f439352.png)

### Console output

N/A

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1349

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Hey! Can you please confirm the age of this Hardcore account? We have everyone 1 free death with the Public Beta v1.0 update which is what you may have seen.

Although, if you have been able to reproduce this then I'll take a look :)

**Comment by 47Y** [comment]
I just did some testing and any Hardcore returning from Offline Combat to a death seems to keep the account. I created a fresh account and died offline 3 times without it being deleted before it was deleted properly when it died online.

**Comment by hvaara** [comment]
Not reproducible on subversion ?1875. Please reopen if you can still reproduce this.
