### ISSUE TITLE
[Bug]: Terran Godsword Special Attack damage

### ISSUE THREAD

**Issue by reapmear** [MelvorIdle/melvoridle.github.io#1816]
### Describe the bug

Damage caused by Terran Greatsword's special attack "crushing blow" does not calculate properly

### Reproduction Steps

Terran Godsword
Block Attack Style 
Hunting Greater Dragon

for exact setup see screenshots.

### Expected behaviour

Maximum Hit according to ingame stats is 735. With "crushing blow" that should be 1470 dmg. Usually it deals a random amount less than that, rarely will it deal the expected amount.

### Screenshots

current setup:
![m1](https://user-images.githubusercontent.com/95151983/143724933-10f574b9-9cc0-46f0-a955-b777ac566809.PNG)

random dmg number after the special attack:
![m2](https://user-images.githubusercontent.com/95151983/143724962-3f47ef5c-57f6-4183-9116-5f8276a6102f.PNG)
should be 1470 but it dealt 969(nice)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1349

### Are you using any scripts or extensions?

No

**Comment by oorzkws** [comment]
It looks like this might be a translation error, or the scale by HP flag was the mistake.

Crushing blow definition:
```js
 CrushingBlow: {
    name: 'Crushing Blow',
    id: 10,
    description: 'Perform an <avoidable> attack that does <damage> damage.',
    defaultChance: 15,
    damage: [
      {
        roll: false,
        maxRoll: 'MaxHitScaledByHP',
        maxPercent: 200,
        character: 'Attacker',
      },
    ],
    prehitEffects: [
    ],
    onhitEffects: [
    ],
    cantMiss: true,
    minAccuracy: 0,
    attackCount: 1,
    attackInterval: - 1,
    lifesteal: 0,
    useRunesPerProc: false,
    usePrayerPointsPerProc: true,
    usePotionChargesPerProc: true,
    attackTypes: [
      'melee',
      'ranged',
      'magic'
    ],
  }
 ```
 
 skill id 10 (crushing blow) english description:
 ```js
 "10": "Perform an unavoidable attack that does ${attackDamageMaxValue0}% of your max hit."
 ```

**Comment by MelvorIdle** [comment]
This is a localisation error. The Godsword special attack was changed in the Public Beta v1.0 update.

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
