### ISSUE TITLE
Perfect Lobsters not being considered for Rocky Waters Upgrade [Bug]: <title>

### ISSUE THREAD

**Issue by Fae-Ovyrn** [MelvorIdle/melvoridle.github.io#1817]
### Describe the bug

When cooking lobsters to build the agility course "Rocky Waters", only non-perfect lobsters are registered, requiring many more lobsters to be cooked to build the course.

### Reproduction Steps

1. Catch 3000 Lobsters
2. Cook 3000 Lobsters (I ended with ~1900 Normal and ~1100 Perfect)
3. Go to the Agility tab and attempt to build the Rocky Waters obstacle for "Obstacle 6"
4. The "3000 Lobsters" condition will be be red even though you have 3000 cooked lobsters in your bank

### Expected behaviour

I expected all cooked, non-burnt lobsters to be considered for this upgrade, but if this is intentional I understand.

### Screenshots

[Lobsters in my bank](https://i.imgur.com/Wzr1BIC.png)
[Agility screen showing that I have not met the condition](https://i.imgur.com/ggbogGy.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1349

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is currently intended.

You need to cook normal Lobsters. Perfect cooks can be disabled in the Cooking screen.
