### ISSUE TITLE
[Bug]: Thieving GP formula is 1%/1 Mastery level off

### ISSUE THREAD

**Issue by esk213** [MelvorIdle/melvoridle.github.io#1818]
### Describe the bug

The gold formula (at least for display, maybe also for actual value) seems to be off by 1%, resulting in 1% higher gold increase value. Found while spreadsheeting.

### Reproduction Steps

1. Start new character
2. Go to Thieving
3. Select Man
4. Click "Show drops"
5. max GP value is 102 but should only be 101

### Expected behaviour

Mastery Level 1 should only give 1% GP from Thieving instead of 2%.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1349

### Are you using any scripts or extensions?

No

**Comment by esk213** [comment]
Just saw it seems to also apply to item double chance, where it also considers Stealth/Mastery to be +1 higher than it is.

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
