### ISSUE TITLE
Slayer Cowl (Basic) description text: "Yep, still undefined"

### ISSUE THREAD

**Issue by Wittypal** [MelvorIdle/melvoridle.github.io#182]
**Describe the bug**
The description text of "Slayer Cowl (Basic)" is "Yep, still undefined", which is not an accurate description.

**To Reproduce**
1. Go to Shop -> Slayer Equipment
2. Slayer Cowl (Basic) says "Yep, still undefined" 

**Expected behavior**
Should be "Slayer exclusive Armour." like all Slayer Equipment

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/46958671/79339897-dd375880-7f29-11ea-8784-81474dd1c545.PNG)

**Browser**
Firefox 75.0 (64-Bit)

**Comment by amicloud** [comment]
This is intentional. Obviously.

**Comment by Wittypal** [comment]
As a software developer this looks like a default "undefined" string with a humorous formulation. I don't think it's obvious at all, that it's intentional.

**Comment by GavroyJ** [comment]
A while back the Cowl's description was "undefined", and because of how often the bug was reported, Malcs jokingly changed it to "Yep, still undefined" in the next patch.

**Comment by Wittypal** [comment]
I only started playing recently, so I didn't know that. Thanks for the insight @GavroyJ.
