### ISSUE TITLE
[Bug]: <title> potions from herblore

### ISSUE THREAD

**Issue by Keefnugget24** [MelvorIdle/melvoridle.github.io#1820]
### Describe the bug

It's not allowing me to use or equipt or drink the potions I've made. 

### Expected behaviour

I should be aloud to use the potions I've made

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?

### Are you using any scripts or extensions?

No

**Comment by Silberdrachi** [comment]
Have you gone to the skill that the relevant potion is supposed to be used on? 

Such as, if you're trying to equip the birds nest potion, you need to do so on the woodcutting skill page. Clicking the icon at the top left, and selecting the potion from the dialog that appears.

**Comment by Keefnugget24** [comment]
Dude thank you, btw does the game have a Patreon?

**Comment by Silberdrachi** [comment]
https://www.patreon.com/melvoridle

Can close out this ticket if that solved your problem. (i dont have that ability)
