### ISSUE TITLE
[Bug]: Top bar not visible on mobile

### ISSUE THREAD

**Issue by geoff-maddock** [MelvorIdle/melvoridle.github.io#1821]
### Describe the bug

On mobile (Chrome - Samsung S10), I cannot see the top bar in combat, so I cannot access the potion selection.
It looks like it may be pushed aside by a button for "Force Save".

### Reproduction Steps

1. Open on Chrome on a mobile device
2. Visit the Combat page.  
3. See that the top bar looks irregular and there is an oversized "Force Save" button pushing some content out of view

### Expected behaviour

Should be able to access top menu bar

### Screenshots

![Screenshot_20211128-143511_Chrome](https://user-images.githubusercontent.com/55493/143783479-8edff6de-7064-4ba8-b83f-0bbb78698e6f.jpg)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

71349

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Please use the mobile app, as that provides the correct layout for mobile devices.

You can log into your Cloud account on this app to access the Full Version of the game.
