### ISSUE TITLE
[Bug]: When at 100% monsters and pets tabs on the completion page arent showing as green.

### ISSUE THREAD

**Issue by Silberdrachi** [MelvorIdle/melvoridle.github.io#1822]
### Describe the bug

When at 100% monsters and pets tabs on the completion page arent showing as green.

[melvoridlesave - Silber🍋 - 2021-11-28 15-40-27.txt](https://github.com/MelvorIdle/melvoridle.github.io/files/7614325/melvoridlesave.-.Silber.-.2021-11-28.15-40-27.txt)

### Reproduction Steps

1. Go to Completion log
2. Observe all tabs are 100%
3. Observe Monsters/Pets percentages aren't highlighting green indicating completion

### Expected behaviour

Percentages would highlight green based on their completion

### Screenshots

![image](https://user-images.githubusercontent.com/76179203/143785212-e8649d99-e756-4fda-8a00-ad212aa03dfa.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1349

### Are you using any scripts or extensions?

Yes

**Comment by MelvorIdle** [comment]
This has not been hotfixed
