### ISSUE TITLE
[Bug]: Global item doubling not affecting Astrology

### ISSUE THREAD

**Issue by Silberdrachi** [MelvorIdle/melvoridle.github.io#1823]
### Describe the bug

Global doubling isnt working for astrology.

### Reproduction Steps

https://discord.com/channels/625838709203271680/708573804007260170/914000398384250900

something is off with global doubling and astrology when using offline. i really don't know what because the code looks fine. but it's consistently short around the % of doubling i have (26%) 

This actually affects online stardust too it seems. processAstrology() uses:
if (rollPercentage(calculateChanceToDouble(CONSTANTS.skill.Astrology, id)))

Because of that, on anything other than Deedree, id is not 0 which means calculateChanceToDouble has isCombat = true.
It would need to be something like calculateChanceToDouble(CONSTANTS.skill.Astrology, false, 0, id)

Expect 2% * 2 * 1.26 dust per action = .0504. And per hour do 3600 / 2.55 = 1411 actions/hr. * .0504 dust per action = 71/hr. 

I have a screenshot from 102 hours ago. Since then I've gained 5746 dust. /102 hours is only 56.33/h

### Expected behaviour

Global doubling will properly calculate on astrology both offline and online

### Screenshots

![image](https://user-images.githubusercontent.com/76179203/143785401-60bd1dd4-5b45-471b-897b-43df734b2106.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1349

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This has not been hotfixed
