### ISSUE TITLE
[Spelling/Grammar]: Cooking item mastery unlocks states incorrect success rate cap

### ISSUE THREAD

**Issue by Auron956** [MelvorIdle/melvoridle.github.io#1824]
### What text is wrong?

When viewing Item mastery unlocks for Cooking, it is stated that:
> Success rate is capped at 99%, except with Gloves or Cooking Skillcape.

This is untrue as of the Cooking rework introduced in 0.22, in which the secondary burn chance was removed.

### What is the correct spelling or grammar?

> Success rate is capped at 100%.

Or simply remove the sentence entirely.

**Comment by MelvorIdle** [comment]
Hotfix has been applied to the game.
