### ISSUE TITLE
[Bug]: Aspect ratio for Slayer Task not respected

### ISSUE THREAD

**Issue by Silberdrachi** [MelvorIdle/melvoridle.github.io#1826]
### Describe the bug

Images of monsters with non standard aspect ratios (Greater Skeletal Dragon) view as squashed in the slayer task window

### Reproduction Steps

1. Get master task for Greater Skeletal Dragon
2. View image of monster in the slayer task dialog compared to the actual image of the monster as you fight them

### Expected behaviour

Monsters should look the same

### Screenshots

![image](https://user-images.githubusercontent.com/76179203/143792373-28458f88-3fe7-469d-afc0-00cc41c50f12.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1349

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This has not been hotfixed
