### ISSUE TITLE
[Bug]: Prayer flicking during channeling of attacks

### ISSUE THREAD

**Issue by Silberdrachi** [MelvorIdle/melvoridle.github.io#1828]
### Describe the bug

Enabling a prayer in the middle of channeling an attack instantly updates the stats of a player, but doesnt begin using prayer until the start of the next channel. This allows the player to enable/disable prayers for free while getting most of the benefits of their bonus.

### Reproduction Steps

1. Equip Sandstorm Ring
2. Attack monster
3. After casting the attack and it moves to the channeling phase, enable "Battleheart" prayer
4. Observe all status values are changed the moment prayer is enabled
5. Observe no prayer points are used
6. Wait for next attack, observe prayer points are deducted at the end of the casting phase of the attack, before the channel phase.

### Expected behaviour

Either prayers should only go into effect at the start of the next attack, or prayer cost should be deducted immediately if in the channeling phase of an attack.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1349

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
