### ISSUE TITLE
[Bug]: Statistics -> Thieving -> GP Earned not present

### ISSUE THREAD

**Issue by esso23** [MelvorIdle/melvoridle.github.io#1829]
### Describe the bug

Not technically a bug, but Statistics page for Thieving is **REALLY** missing a stat "GP Earned" (Agility and even Firemaking have it).

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1349

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Technically this is a bug, since this stat is actually tracked and has translations for it. Just missing from the table itself.

**Comment by coolrox95** [comment]
Fixed as of v1.0 ?1355
