### ISSUE TITLE
[Bug]: Visual unexpected behavior: Viewing equipment in bank still shows the set which has just been swapped from the hotbar.

### ISSUE THREAD

**Issue by EgonSpengler** [MelvorIdle/melvoridle.github.io#1830]
### Describe the bug

Changing equipment from the hotbar equipment popup does not update the set displayed in the "Equip" area when viewing an equipment item in the bank.  This can lead to user error where items are mistakenly assigned to the old set.

### Reproduction Steps

1. View an equipment item in the bank.
2. Open the equipment hotbar menu.
3. Select an equipment set other than the one currently equipped, and close the popup.
4. Click the "Equip" button on the item being viewed in the bank. Note that it still displays the item to be replaced is from the set which is no longer equipped.

### Expected behaviour

The "Equip" area of an item view in the bank will update immediately to use the new set.

### Screenshots

![image](https://user-images.githubusercontent.com/4382519/143817376-d0db8fdf-5a1c-4cfd-97bb-fff8c2a2c295.png)
![image](https://user-images.githubusercontent.com/4382519/143817436-3cf81624-70a0-42cb-8330-9a5316cd6dac.png)
![image](https://user-images.githubusercontent.com/4382519/143817516-84139065-9229-448b-80b0-72f891747015.png)
![image](https://user-images.githubusercontent.com/4382519/143817637-50794619-c504-4d44-a94a-6f121873ebc3.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1352

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Hotfix has been applied to the game.
