### ISSUE TITLE
[Spelling/Grammar]: SuperHeat 3 on Runite says it requires 8 coal but it only needs 4

### ISSUE THREAD

**Issue by LinkdxTTV** [MelvorIdle/melvoridle.github.io#1831]
### What text is wrong?

![image](https://user-images.githubusercontent.com/75294164/143837524-220ac46a-c68c-4284-8ada-35d52e2d9d62.png)

Runite only needs 4 coal to smith, and it only consumes 4 coal on cast here anyways

### What is the correct spelling or grammar?

Should be 4, not 8

**Comment by Silverfyree** [comment]
Do you have either the smithing cape or max cape equipped?

**Comment by LinkdxTTV** [comment]
Ah yes, but shouldnt the tooltip be accurate to reflect it as such?
On smithing, the tooltip is accurate

**Comment by MelvorIdle** [comment]
Hotfix has been applied to the game.
