### ISSUE TITLE
[Bug]: Perfect cooked is not counted as ingredient for herblore and summoning

### ISSUE THREAD

**Issue by callmedan** [MelvorIdle/melvoridle.github.io#1833]
### Describe the bug

LVL 99 cooking skill almost provide 100% perfect cooking chance, so it is not a reasonable choice to only let normal food to be the ingredient for herblore and summoning.

### Reproduction Steps

1. Go to herblore / summoning
2. select generous cooking potion / wolf or pig
3. start crafting

### Expected behaviour

Perfect cooked food can use as ingredient for other skill.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1352

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is intended. You can turn off perfect cooks in the Cooking screen.
