### ISSUE TITLE
[Bug]: Signet ring interaction with firemaking conflicts with text in game

### ISSUE THREAD

**Issue by kevinhischier** [MelvorIdle/melvoridle.github.io#1835]
### Describe the bug

The signet ring text in game states "+100% GP from all sources except alt magic and Item sales". It does not provide +100% Gp granted from the 50% Mastery Pool Bonus from firemaking which reads "receive GP equal to 25% of the value of the log you are burning." Firemaking is not alt magic or item sales, so this bonus should apply per game text. 

### Reproduction Steps

1. Equip Aorpheat's Signet ring
2. Have the 50% Mastery pool bonus for firemaking
3. Burn a log
4. Receive coins

### Expected behaviour

One should receive gold equal to double 25% of the value of the log. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1351

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Hotfix has been applied to the game.
