### ISSUE TITLE
[Bug]: Aspect ratio fix broke padding/scaling/something

### ISSUE THREAD

**Issue by Silberdrachi** [MelvorIdle/melvoridle.github.io#1836]
### Describe the bug

Fix to make slayer task icons have proper aspect ratio seems to have caused other UI overflow.

![image](https://user-images.githubusercontent.com/76179203/143944741-2311e1a4-39cf-41c4-ab2f-ab13337c7c1e.png)
![image](https://user-images.githubusercontent.com/76179203/143944765-c5f44ebd-3cb9-4810-994e-5ccf6b2d34cc.png)
![image](https://user-images.githubusercontent.com/76179203/143944777-37aa8925-a3e4-4544-81f3-a971cc08aa75.png)
![image](https://user-images.githubusercontent.com/76179203/143944792-25033d8a-e2af-494f-903c-5355ccea1c7b.png)
![image](https://user-images.githubusercontent.com/76179203/143944804-28b094e2-7ecd-4977-bf4c-7eaeff46e4d1.png)
![image](https://user-images.githubusercontent.com/76179203/143944811-4d1cdc88-100d-40e4-b6d2-8f53be7814ef.png)

on mobile:
![image](https://user-images.githubusercontent.com/76179203/143944842-d6ea0ae3-0c22-47fc-a185-d5b35ff22b4f.png)
(godzillachicken)

### Expected behaviour

No godzilla chicken

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1352

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This should now be fixed, I hope.
