### ISSUE TITLE
Cant afk any combat skills

### ISSUE THREAD

**Issue by ToxicSyfer** [MelvorIdle/melvoridle.github.io#1837]
### Describe the bug

I'm not sure if this is a bug or intentional but everytime I try to afk any combat skill if I log off it says that I'm not doing anything when I log back in.

### Reproduction Steps

1. Go to any combat skill and attack mobs
2.  Exit game fully close
3. Log back in 

### Expected behaviour

Will say not currently doing anything.

### Screenshots

![Screenshot_20211130-000341_Melvor Idle](https://user-images.githubusercontent.com/95268609/143989347-5d98be89-1022-4e96-91cc-eb14fa360765.jpg)
![Screenshot_20211130-000401_One UI Home](https://user-images.githubusercontent.com/95268609/143989359-67949c01-cb8d-4126-bb25-ea031442f1a2.jpg)
![Screenshot_20211130-000414_Melvor Idle](https://user-images.githubusercontent.com/95268609/143989366-6ca8990a-60d0-44c8-bcbb-a4616610766d.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1354

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
It looks like your offline combat is disabled.

You can enable it from settings:
![image](https://user-images.githubusercontent.com/45249614/143989500-5b2d16f2-0e1f-448c-814a-cdd2d9246047.png)
