### ISSUE TITLE
[Bug]: Smithing Gloves do not give +60% XP when equipped

### ISSUE THREAD

**Issue by South-Paw** [MelvorIdle/melvoridle.github.io#1838]
### Describe the bug

When smithing items and wearing the smithing gloves, the +60% does not seem to applied at all.

Was crafting rune swords with the gloves equipped and only getting 120 xp per action, where-as should have been getting 192 xp

### Reproduction Steps

1. Purchase smithing gloves
2. Equip
3. Smith and item
4. XP is not calculated correctly

### Expected behaviour

+60% xp applied correctly (should be `120xp * 1.6 = 192xp`)

### Screenshots

Equipping gloves, note xp is `1,052,839`

![Melvor_Idle_yByeZTTkJZ](https://user-images.githubusercontent.com/2154764/144025719-37342cb0-3323-45a4-89a2-960a12ab7fc0.png)

Crafting item, note xp is `1,052,959` (`+120xp` increase, should have been `120xp * 1.6 = 192xp`)

![Melvor_Idle_hgphLyhX41](https://user-images.githubusercontent.com/2154764/144025738-3ae2cded-dd06-4a3c-8401-ff9c6ba58182.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1354

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
The bonus is being applied. The XP you see is _inclusive_ of all XP bonus applied to Smithing.

The Rune Sword gives 75 XP without bonuses.
