### ISSUE TITLE
[Bug]: Fishing mastery acting strange 

### ISSUE THREAD

**Issue by Diequietly** [MelvorIdle/melvoridle.github.io#1839]
### Describe the bug

Fishing individual mastery changing to original fish if in the same fishing area and changed without stopping entirely.

### Reproduction Steps

Note that my poison fish is 99, angler should be 90 and cave should be 93. 

Starting fishing poison, swap to angler, angler then says 99 mastery after a fish is caught but still catches poison 

### Screenshots

https://user-images.githubusercontent.com/94816847/144056438-388fb44e-0ef8-4e9c-adda-81731edc15e3.mov

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1352

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue was fixed as of the v1.0.3 update. Changing fish while fishing in an area now stops fishing, as per the behavior of thieving.
