### ISSUE TITLE
Trying to Sell Quantity Of Item Greater Than Quantity Owned Does Not Update Statistics

### ISSUE THREAD

**Issue by RobertMcCoy** [MelvorIdle/melvoridle.github.io#184]
**Describe the bug**
If you try and sell the max amount of an item, but only have 50 of it, your statistics will not update with the gold gained from selling those 50 items.

**To Reproduce**
1. Get 10 of an item
2. Check your statistics tab and note the gold from selling and items sold stats under General
3. Set "Max" sell amount of the 10 items
4. Sell the items
5. Check statistics again

**Expected behavior**
Gold from item sale and quantity of items sold increases.

**Screenshots**
N/A

**Browser**
Chrome

**Issue in Code**
(Chrome console is blank - there is no exception here, it's some missing logic issue)
The conditional statement for `processItemSale` does not do the increment in the `else` block, which the if block is doing:
```
statsGeneral[0].count += items[bank[bankID].id].sellsFor * qty;
statsGeneral[1].count += qty;
updateStats('general');
```
The else block for this method just needs to become:
```
 else {
        //Set the correct qty. Will set to 0 if you don't have the item
        qty = bank[bankID].qty;
        //Add gp for the sale
        gp += items[bank[bankID].id].sellsFor * qty;
        itemStats[bank[bankID].id].timesSold += qty;
        itemStats[bank[bankID].id].gpFromSale += items[bank[bankID].id].sellsFor * qty;
        //update general stats
        statsGeneral[0].count += items[bank[bankID].id].sellsFor * qty;
        statsGeneral[1].count += qty;
        updateStats('general');
        //.....rest of else block
}
```

**Comment by MelvorIdle** [comment]
Fixed in v0.15
