### ISSUE TITLE
[Bug]: Cooking upgrade 1 does not work in background

### ISSUE THREAD

**Issue by cairnsjr13** [MelvorIdle/melvoridle.github.io#1841]
### Describe the bug

When switching tabs, the food being cooked ends up in the bank instead of equipped, even when that food is already equipped.  Works as expected when tab is active.

### Reproduction Steps

1. Equip salmon
2. Actively cook salmon
3. Switch tabs for a while
4. Salmon (and perfect salmon) end up in bank

### Expected behaviour

The food should be equipped when the tab is refocused.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1354

### Are you using any scripts or extensions?

No

**Comment by Helam24** [comment]
I also experience this on iPad

**Comment by coolrox95** [comment]
Issue was fixed as of the v1.0.3 update.
