### ISSUE TITLE
Cannot see app and file bug

### ISSUE THREAD

**Issue by OneOfMany07** [MelvorIdle/melvoridle.github.io#1842]
### Describe the bug

Suggest opening bug area external to app.

Currently your app triggers itself for login searches in Bitwarden (a password tracking tool). If opened externally in browser the site should work as usual (reusing credentials, and add-ons).

When filing a bug user's can't easily look in the app to write reproduction steps. Or check version info. 

The only benefit to an in app bug process would be automatically attaching logs or screen shots or version numbers, but I assume that can't happen through GitHub's interfaces. 

### Reproduction Steps

Click option to file a bug

### Expected behaviour

The new area to open in a standard browser tab. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

? 1341

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
