### ISSUE TITLE
[Bug]: Prayer Bug 

### ISSUE THREAD

**Issue by yavoan** [MelvorIdle/melvoridle.github.io#1844]
### Describe the bug

When fighting Malcs in Volcanic dungeon, and Malcs uses Dragonbreath attack and the player is using stone skin prayer it uses 180 prayer points for one dragon breath attack. 

### Reproduction Steps

1. Start Volcanic dungeon fight
2. Get to Malcs
3. Have stone skin prayer on
4. Wait for dragon breath attack
5. see prayer points drain

### Expected behaviour

Would expect only 3 points to be used for one attack sequence

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1354

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
