### ISSUE TITLE
[Bug]: Item Alcemy III Producing Incorrect Values

### ISSUE THREAD

**Issue by jvebo** [MelvorIdle/melvoridle.github.io#1847]
### Describe the bug

When utilizing Item Alchemy III, the produced GP value is incorrect. I have currently tested it with two items, Bobby's Pocket and Antique Vase. 

Bobby's Pocket produces 5760, as opposed to 6400.
Antique Vase produces 43200, as opposed to 48000.

Included below are two screenshots of the issue, taken via the Steam client of the game. 

### Reproduction Steps

1. Go to "Alt Magic"
2. Select "Item Alchemy III"
3. Select the "Click Image to choose icon" button, and select either "Bobby's Pocket" or "Antique Vase"
4. Assess the "Produces" line to validate that the number does not match 160% of the item's base sale price (per the spell description)
5. Report any findings for items not mentioned here

### Expected behaviour

Bobby's Pocket should produce 6400 GP.

Antique Vase Should Produce 48000 GP.

### Screenshots

![Item Alchemy III, Vase](https://user-images.githubusercontent.com/95355070/144236076-4acc77db-9347-421f-a78b-333074f500ea.png)
![Item Alchemy III, Bobbys Pocket](https://user-images.githubusercontent.com/95355070/144236079-a87a80f7-ffdb-49ee-b461-c0dc9bcdfe12.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1355

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.0.2. Please open a new ticket if this is not the case.
