### ISSUE TITLE
[Bug]: Cooking double chance not stacking correctly

### ISSUE THREAD

**Issue by pburris** [MelvorIdle/melvoridle.github.io#1848]
### Describe the bug

With just the cooking skill upgrades, (redwood fire, magic furnace, and magic cookpot) I had 4% chance to double items while cooking. Upon reaching 25% mastery pool and getting the pet, I would have expected 14% total; an additional 5% from the pet and the perk respectively. Instead it only shows 9% doubling chance.

### Reproduction Steps

1. Go to cooking skill page.
2. Obtain skill pet (Cris)
3. Obtain at least 25% mastery pool in cooking.
2. Start cooking any fish/meat (I am currently using mantas and chicken, but also tried shrimp).
3. Observe 9% double chance in the blue tooltip for doubling items.

### Expected behaviour

I would expect to see 14% in the blue tooltip under the green fork symbol.

### Screenshots

![Screenshot_20211201-075254](https://user-images.githubusercontent.com/25254501/144268274-1c8f4fd9-7dee-498c-beed-bde2f1ca64b1.png)
![Screenshot_20211201-075304](https://user-images.githubusercontent.com/25254501/144268324-50ce2aef-6ab4-43e0-bc42-a72f24141c68.png)
![Screenshot_20211201-075319](https://user-images.githubusercontent.com/25254501/144268349-457cb035-a09a-4b43-a9d2-8385d8e9c6a5.png)
![Screenshot_20211201-075340](https://user-images.githubusercontent.com/25254501/144268376-1e455f68-8944-4295-a4ea-b3c1d30cbede.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1354

### Are you using any scripts or extensions?

No

**Comment by Qlmmb2086** [comment]
I have this bug as well, without the pet. Both result in 5% down so it's likely that the pet is giving its 5% and but the 25% mastery threshold isn't giving anything.
![image](https://user-images.githubusercontent.com/50282524/144348621-0d6f030b-3cd0-4a21-b461-8ba35d629799.png)

**Comment by coolrox95** [comment]
Issue was fixed as of the v1.0.3 update.
