### ISSUE TITLE
[Bug]: Game freezes for ~1-2 seconds on high end machines when looting 100 items

### ISSUE THREAD

**Issue by Tyriar** [MelvorIdle/melvoridle.github.io#1849]
### Describe the bug

I think this can happen in other times too but it's most obvious when clicking Loot All, I'm assuming it's caused by adding the 100 elements in an inefficient way. Some suggestions:

- Instead of having `+1 <blah>` 100 times, could you have a single entry say `+1 <blah> x100` (alternatively `+100 <blah>`)? This would be more usable as well since most items are off screen anyway.
- Use a document fragment to collect the elements and add them all at once to avoid layout thrashing (laying out the DOM multiple times in a single frame).
- Look into alternate animation/transition for the items. Instead of animating on the item height, you could try animating container `height` or transform/scale.

Note I'm using a 12 gen i7 which is one of the best available consumer CPUs right now.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1355

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
