### ISSUE TITLE
Keep getting Junk even level is higher than 65

### ISSUE THREAD

**Issue by ariehfabbro** [MelvorIdle/melvoridle.github.io#185]
**Describe the bug**
I am level 101 in fishing, way higher than 65, which it is the level we are supposed to no longer get any junk from fishing and from the screenshot I took, I still keep getting junk.

**To Reproduce**
1. Go to 'Fishing'
2. Click on 'Raw Whale'
3. Click on 'Start Fishing'
4. Got junk by fishing being level 101 in fishing.

**Expected behavior**
No longer get junk from fishing when level is above level 65.

**Screenshots**
![image](https://user-images.githubusercontent.com/8531737/79406937-ad5e7400-7f6e-11ea-8048-1509e4c6c964.png)
![image](https://user-images.githubusercontent.com/8531737/79407721-14305d00-7f70-11ea-8d3c-1a53bcdddc68.png)

**Browser**
Chrome 81.0.4044.113 64 bits

**Console output**
Melvor Cloud Connection: Success
save.js?280:47 Loading Save Game...
save.js?280:208 Save Game Loaded...
smithing2.js?280:189 Loading Smithing...
mastery.js?280:181 Updating Masteries
mastery.js?280:23 Loading Masteries...
main.js?288:1112 Game Loaded
2cloud.js?280:192 Cloud synced
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by Mezothine** [comment]
This is working as intended.

You need level 65 mastery in the specific fish you are catching to no longer catch junk, not level 65 fishing. The mastery level is the level next to the trophy above the "stop fishing" button (54 in your screenshot).

**Comment by ariehfabbro** [comment]
Now i understand, thank you.
