### ISSUE TITLE
[Bug]: (Android) Pirates Lost Ring Doesnt Appear in Fishing Tab Side Menu

### ISSUE THREAD

**Issue by AustinJoachim** [MelvorIdle/melvoridle.github.io#1851]
### Describe the bug

Pirate's Lost Ring doesn't show in the quick equip menu on the fishing tab

### Reproduction Steps

1. Obtain Pirate's Lost Ring
2. Go to fishing tab

### Expected behaviour

Pirate's Lost Ring should appear in the quick equip menu

### Screenshots

![Screenshot_20211201-141423_Melvor Idle~2](https://user-images.githubusercontent.com/80413460/144301571-d53c955a-d5e1-4948-82b3-c710e77eadb9.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1355

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Does it appear on restart by chance? Just so I know what kind of bug I'm dealing with.
