### ISSUE TITLE
[Bug]: Octopus/Pig synergy doesn't work until you reload after initial unlock.

### ISSUE THREAD

**Issue by misharp** [MelvorIdle/melvoridle.github.io#1852]
### Describe the bug

Octopus and pig synergy don't work after the initial unlock until you reload your game. I have the pig at level 2, octopus at level 4, the equipment pane shows the synergy is active, but no cooked fish ever showed up. 2 octopus tokens and 1 pig token are being deducted each time though. I have let it run for several hundred attempts. 

![image](https://user-images.githubusercontent.com/7387860/144320046-43a74930-4ab2-4ce9-8c7f-b0fa6c235c1d.png)

After I reloaded my game (I am playing in the browser), the synergy worked correctly both offline and online.

### Reproduction Steps

Have octopus at level 3.
Unlock pig and get it to level 2. 
Equip the octopus in slot 1.
Equip the pig in slot 2.
Fish.
No cooked fish show up but tokens are deducted.

Reload the game.
Cooked fish now show up both offline and online.

### Expected behaviour

I expected the synergy to work without having to reload the game.

### Console output

I have already reloaded my browser and its now working correctly so there is nothing to show from the log. I would be happy to create a new character to repro this behavior though if that would help.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1355

### Are you using any scripts or extensions?

Yes

**Comment by coolrox95** [comment]
Issue was fixed as of the v1.0.3 update.
