### ISSUE TITLE
[Bug]: Favicon not loading

### ISSUE THREAD

**Issue by user8342912** [MelvorIdle/melvoridle.github.io#1853]
### Describe the bug

<img width="501" alt="Screenshot 2021-12-01 at 23 10 07" src="https://user-images.githubusercontent.com/93920643/144328959-76ba4bfa-2adc-4e6c-825a-a1a60480fcc3.png">

Very minor issue. I'm assuming my browser is trying to load the 192px image, would be nice to have a favicon, just at a glance be able to see which tab is Melvor.

<img width="232" alt="Screenshot 2021-12-02 at 11 04 59" src="https://user-images.githubusercontent.com/93920643/144410506-925e7378-0aed-42e1-bb64-8f6421f5115c.png">

### Console output

GEThttps://melvoridle.com/assets/media/favicons/favicon-192x19.svg
[HTTP/2 404 Not Found 30ms]

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1355

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue was fixed as of the v1.0.3 update.
