### ISSUE TITLE
[Bug]: premium Status lost 

### ISSUE THREAD

**Issue by McKristoph** [MelvorIdle/melvoridle.github.io#1854]
### Describe the bug

I purchased premier on steam a week ago and it’s been working on both steam and mobile fine. 

Was working fine on phone today but suddenly asked me to upgrade and kicked me out of skills 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1355

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Please make sure you are logged into your Cloud account.

Let me know your username as well and I can take a look if the above does not work
