### ISSUE TITLE
[Bug]: Runecrafting 25%mastery doesnt apply

### ISSUE THREAD

**Issue by Ikemp2** [MelvorIdle/melvoridle.github.io#1855]
### Describe the bug

The 250% bonus exp isn't applying to the Runes

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1355

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
It is applied. The XP value you see in the screen is _inclusive_ of the bonus XP.
