### ISSUE TITLE
[Bug]: Slayer task assigned without required item

### ISSUE THREAD

**Issue by Freezeman1** [MelvorIdle/melvoridle.github.io#1856]
### Describe the bug

Master slayer tasks for Perilous Peaks are getting assigned despite not owning the boots or slayer cape required to access the area.

### Reproduction Steps

Get 99 slayer.
Buy 99 slayer cape.
Sell cape.
Cape perk continues to be detected by task assignments.

### Expected behaviour

If items to access a slayer area are not owned, assignments to that area should not be given.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1355

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Not a bug, this is intended.

If you have ever owned an item that grants you access to the area, the game will assign you tasks for that area. This is regardless of your current ownership of the item.
