### ISSUE TITLE
[Alt magic]: Randomly stops operation when app is not open

### ISSUE THREAD

**Issue by Itsbryansfault** [MelvorIdle/melvoridle.github.io#1857]
### Describe the bug

It isn't consisten, just stops using alt magic, specifically the blessed offering option, while the app is closed at some point. Sometimes it's after 5 minutes, sometimes after an hour. 

### Expected behaviour

For the operation to continue like normal as all of the other skills do. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

2.01

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.0.2. Please open a new ticket if this is not the case.
