### ISSUE TITLE
[Bug]: inviting people over in other game using steam overlay while melvor is open, make melvor stuck in the same steam overlay

### ISSUE THREAD

**Issue by chriscubelus** [MelvorIdle/melvoridle.github.io#1858]
### Describe the bug

When i open melvor with other game, everytime i try to invite people in other game using steam overlay on other game. melvor goes into steam overlay too but cannot be interacted with and the only way to quit is to force close the melvor game

this happen when im using tabletop simulator with melvor at the same time 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1356

### Are you using any scripts or extensions?

No

**Comment by King-Ghosty** [comment]
I fixed this by disabling the steam overlay for Melvor specifically.

**Comment by Technikhighknee** [comment]
The same happens when you open someones profile, via the scoreboard in counter strike: global offensive

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
