### ISSUE TITLE
[Bug]: Adventure mode shows skill level limit reached at 99/99

### ISSUE THREAD

**Issue by Tyriar** [MelvorIdle/melvoridle.github.io#1859]
### Describe the bug

I have 99 thieving in adventure mode and it shows a giant red message that I need to level up my combat level. If this is to accommodate virtual levels I suggest only showing the message when virtual levels are enabled.

### Screenshots

![image](https://user-images.githubusercontent.com/2193314/144463997-e789b8ad-3b77-464a-9371-caeb073ead07.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1356

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is intended behavior. In the event skills increase in max level, there would be a lot of issues when dealing with XP values that have gone over the available limit.
