### ISSUE TITLE
"A crop is ready to harvest" notification is stuck until refresh

### ISSUE THREAD

**Issue by levgre** [MelvorIdle/melvoridle.github.io#186]
I'm not sure if this was a 'legit' harvest notification from an actually finished crop or a bugged one that occurred after I harvested all my crops.

![image](https://user-images.githubusercontent.com/14255060/79486660-4378b580-7fd4-11ea-8ae3-7050b65d8c76.png)

**Comment by MelvorIdle** [comment]
Should be fixed in v0.15
