### ISSUE TITLE
[Bug]: <title> Sell mode selected border dissapears when sorting

### ISSUE THREAD

**Issue by Huggebugge321** [MelvorIdle/melvoridle.github.io#1863]
### Describe the bug

When you select an item to sell in sell mode and then sort the items, you loose the borders but the items are still selected. It can be annoying if you have selected many items but now you dont know wich ones. 

### Reproduction Steps

1. Click on "Toggle Sell Mode"
2. Select any item
3. Click on "Sort"

### Expected behaviour

Either that the selected items are not selected anymore. Or that the borders remain

### Screenshots

![image](https://user-images.githubusercontent.com/74109163/144571188-2315f8d7-786f-4dd2-95cc-b4c363e8e985.png)
![image](https://user-images.githubusercontent.com/74109163/144571287-bcc4c6f5-0459-484b-a67b-3b9488805078.png)
![image](https://user-images.githubusercontent.com/74109163/144571311-4d6af77d-e47d-4cb9-97ce-d9b1d2986091.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1361

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.1.
