### ISSUE TITLE
[Bug]:  Cape of Completion

### ISSUE THREAD

**Issue by BAM-S** [MelvorIdle/melvoridle.github.io#1866]
### Describe the bug

Clicking Cape of Completion in the Item log grants one for free. just like other items that do not count towards completion.

### Reproduction Steps

1. Go To Item Log
2. Click on Cape Of Completion
3. Behold your free 100M

### Expected behaviour

On Clicking the cape of completion a free cape is not being granted? 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1361

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue cannot be reproduced in latest version v1.0.3.
