### ISSUE TITLE
[Bug]: Brand new game has a completion percent of 0.48%

### ISSUE THREAD

**Issue by anythingapplied** [MelvorIdle/melvoridle.github.io#1867]
### Describe the bug

Starting completion percent is 0.48%.  Skills start 1.41% complete (All 1/99 plus health 10/99) and all masteries are 1.01% complete (all 1/99).

### Reproduction Steps

1. Start a fresh normal game.
2. Check the completion log.
3. Note that you're already 0.48% complete without having done anything.

### Expected behaviour

I would expect the starting completion percent to be 0%.  So because you start with some skills, perhaps the formula should be 
`((TOTAL SKILLS) - (START SKILLS = 32)) / ((MAX SKILLS) - (START SKILLS))`
instead of just
`(TOTAL SKILLS) / (MAX SKILLS)`

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1361

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
