### ISSUE TITLE
[Bug]: Smithing Gloves not granting bonus XP when smelting Runite bars

### ISSUE THREAD

**Issue by Jegan24** [MelvorIdle/melvoridle.github.io#1869]
### Describe the bug

Smelting Runite bars with Smithing Gloves does not grant the 60% bonus XP.

Save:
[melvoridlesave_null.txt](https://github.com/MelvorIdle/melvoridle.github.io/files/7651480/melvoridlesave_null.txt)

### Reproduction Steps

1. Equip Smithing Gloves.
2. Smelt a Runite bar.

### Expected behaviour

Runite Bar XP: 80
Expected Runite bar XP with Smithing Gloves: 80 * 1.6 = 128
Actual Runite bar XP with Smithing Gloves: 80 * 1.0 = 80

### Screenshots

Steam before smelt:
![rune bar before](https://user-images.githubusercontent.com/28798667/144647582-c27da2b7-b196-46a1-8ba2-f9bf235d54b4.PNG)
Steam after smelt:
![rune bar after](https://user-images.githubusercontent.com/28798667/144647579-7ab0cdca-51cf-402c-8555-e46f4dfb54ca.PNG)
Chrome before smelt:
![runite bar chrome before](https://user-images.githubusercontent.com/28798667/144649738-34094808-1138-41cd-a97e-088379013918.PNG)
Chrome after smelt:
![runite bar chrome after](https://user-images.githubusercontent.com/28798667/144649793-ea47d0e7-b4e9-4bfc-a3ae-a08644530620.PNG)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1356

### Are you using any scripts or extensions?

No

**Comment by South-Paw** [comment]
See #1838
