### ISSUE TITLE
[Bug]: Woodcutting offline level up not reported

### ISSUE THREAD

**Issue by ockapus** [MelvorIdle/melvoridle.github.io#1870]
### Describe the bug

When doing woodcutting while logged out, the summary screen of what happened when you were offline does not properly display when your Woodcutting skill leveled up like other skills do. Confirmed working for Mining, at least.

### Reproduction Steps

1. Start woodcutting
2. Log out, and wait long enough to have leveled up the skill
3. Log back in, and review the summary screen

### Expected behaviour

Should display that skill increased if enough xp was gained 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1361

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.0.2. Please open a new ticket if this is not the case.
