### ISSUE TITLE
[Bug]: Astrology Crafting Armor doubling bonus not displayed

### ISSUE THREAD

**Issue by kevinhischier** [MelvorIdle/melvoridle.github.io#1872]
### Describe the bug

With the Hyden Astrology sign unique bonus of "x% Chance to double items when crafting armor" the additional doubling chance does not display in the crafting view. I have not yet tested whether it applies anyways at this time. 

### Reproduction Steps

1. Have Hyden sign unlocked with at least 1 Unique modifier slot unlocked
2. Set the unique modifier slot to x% chance to double items when crafting armor
3. examine crafting any armor in the crafting screen
4. See no doubling chance change

### Expected behaviour

Doubling chance should be increased by x%

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1361

### Are you using any scripts or extensions?

No

**Comment by kevinhischier** [comment]
Performed an experiment: 
Started with 12k Blue Dragonhides, 99 Mastery in Blue Dragonhide bodies and up to the 50% mastery pool. I also have equipped the Crown of Rhaelyx and Aorpheat's signet ring, and have a total of 14% doubling from Astrology non-Unique modifiers, and one 5% doubling chance for armor in crafting, both from the Hyden sign. The total displayed Preservation chance is 40% (though I believe it is 39.8 or 39.6 depending on how the mastery levels add up, but I don't have visibility into that) and the Displayed doubling chance is 24%. 

After processing 12k Dragonhides, a total of 4000 actions before preservation, meaning a total of 6666 and 2/3 actions after resource preservation, if the displayed number of doubling chances was correct, I would expect to have 8266 Total blue dragonhide bodies. If the 5% doubling chance from the unique modifier to crafting armor was applied but not visible, I would expect 8600. 

I had a total of 8171 bodies at the end of the experiment, which seems likely to be in line with the visible amount being accurate. I don't know if it's quite enough repeatability for a proper test of statistical significance, but it's definitely enough for it to be waggling it's eyebrows in the direction of the display number being correct and there being a disconnect between the astrology buff for Crafting armor doubling. 

Thanks for taking a look and I hope it's easy to fix. :)

**Comment by imperialboy3** [comment]
Can confirm. The text "x% Chance to double items when Crafting armour" is taken from a Summoning modifier. The Summoning modifier does correctly apply but not the Astrology modifier. However, because the modifier is specific to armour it still may not show up in the crafting screen once the fix to correctly apply it is made.

**Comment by coolrox95** [comment]
Issue was fixed as of the v1.0.3 update.
