### ISSUE TITLE
[Bug]: mastery not updating 

### ISSUE THREAD

**Issue by Diequietly** [MelvorIdle/melvoridle.github.io#1874]
### Describe the bug

Mastery for woodcutting doesn’t show 100% after mastering all the trees 

### Expected behaviour

Mastery completion 

### Screenshots

![D0CBC320-CD89-4CA6-BBDF-11193E0A9EA4](https://user-images.githubusercontent.com/94816847/144714496-4c3d66ee-4ab5-4a17-93c7-4aefcf5b7218.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1355

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.0.2. Please open a new ticket if this is not the case.
