### ISSUE TITLE
[Bug]: Stuck on "Authenticating with Playfab"

### ISSUE THREAD

**Issue by drewhoener** [MelvorIdle/melvoridle.github.io#1875]
### Describe the bug

When opening Melvor Idle on Steam Native, game hangs at Authenticating with Playfab. Can't click any buttons like manage or sign out.
Deleting `~/.config/MelvorIdle/` allows me to start at the main menu again and try signing in but the same thing happens over and over.

### Reproduction Steps

Not entirely sure, it just started happening after my most recent update

OS: Arch Linux x86_64 
Kernel: 5.15.2-zen1-1-zen 
WM: bspwm 
CPU: AMD Ryzen 7 1700X (16) @ 3.400GHz 
GPU: NVIDIA GeForce GTX 1080 
Memory: 6508MiB / 32110MiB 

### Expected behaviour

Open the game, login to cloud.
Cloud & Playfab authenticate and I can load my cloud save, go to settings, etc.

### Screenshots

![screenshot-2021-12-04-20:01:24](https://user-images.githubusercontent.com/6218989/144729388-e2ce5f7e-901b-4636-9fb8-a08185e2fe69.png)

![screenshot-2021-12-04-20:02:56](https://user-images.githubusercontent.com/6218989/144729390-3755b483-8c16-4d97-8640-47fdf0d4a1aa.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1361

### Are you using any scripts or extensions?

No

**Comment by josephg** [comment]
I'm seeing the same problem on macos (with the steam version of melvor idle).

**Comment by drewhoener** [comment]
Resolved a few patches ago
