### ISSUE TITLE
[Bug]: rune crafting resource preservation not displaying correct value.

### ISSUE THREAD

**Issue by herbert164** [MelvorIdle/melvoridle.github.io#1878]
### Describe the bug

I have the Crown of Rhaelyx and the rune crafting skill cape. Together along with a charged stone that should yield 60%. Looking at the displayed number i see 55% inspite of having 99 mastery in that item and a maxed mastery pool. I have not tested to see if 55% is the actual percentage or just the displayed percentage. I am using windows 7.

### Expected behaviour

I should have a number well over 60.

### Screenshots

![Crown](https://user-images.githubusercontent.com/5839829/144750492-87c4a9b1-4438-4eb7-b4a8-b979226068eb.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1361

### Are you using any scripts or extensions?

No

**Comment by imperialboy3** [comment]
My first thought is you may have some negative preservation from Agility Obstacles.

**Comment by herbert164** [comment]
> 
I came to realize that my crown has to be worn. for some reason i was under the impression that it was not equippable. I had not yet set up my agility course at the time.
