### ISSUE TITLE
[Bug]: Unmissing ancient magic spells miss

### ISSUE THREAD

**Issue by EtK2000** [MelvorIdle/melvoridle.github.io#1881]
### Describe the bug

When attacking Chaotic Dragons they keep missing despite me having 30k+ accuracy.

### Reproduction Steps

Have over 20k accuracy.
Attack Chaotic Greater Dragons with Gust or Slicing Winds.
Attacks miss?!

### Expected behaviour

20k+ should lead to never missing as written in the spell descriptions.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1361

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
