### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by joholope** [MelvorIdle/melvoridle.github.io#1882]
### Describe the bug

In Iridan Astrology, I have "+1% of Maximum Hit added to Minimum Hit" and "+2% of Maximum Hit added to Minimum Hit" yet when I click "View All Active Modifiers" it only shows "+1% of Maximum Hit added to Minimum Hit."

### Reproduction Steps

1. Go to Astrology
2. Click on Iridan
3. Click on Explore
4. Note the Unique Modifiers
5. Click on View All Active Modifiers
6. Note the missing Unique Modifier

### Expected behaviour

The "All Active Astrology Modifiers" screen should show either both the "+1..." and "+2..." OR it should show the sum of the two as "+3..."

### Screenshots

![ErrorInMelvorAstrologyTotals](https://user-images.githubusercontent.com/3521750/144787139-751d6577-d4d8-410b-825c-3e22415a6841.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1362

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue was fixed as of v1.0.3.
