### ISSUE TITLE
[Bug]: Styles are not applied correctly to confirmation buttons of some modals

### ISSUE THREAD

**Issue by staticf0x** [MelvorIdle/melvoridle.github.io#1883]
### Describe the bug

A _chest contents_ popup _OK_ button is not rendered properly.

### Reproduction Steps

1. Click on _Crate of Food_ in the bank
2. Click on _View chest contents_
3. The _OK_ button is not rendered properly

### Screenshots

![melvor-button](https://user-images.githubusercontent.com/44530786/144845350-d42f684c-c5c8-41db-bd0c-b5d9181c2f79.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1362

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
