### ISSUE TITLE
[Bug]: Bank reordering not working properly when changing the zoom level

### ISSUE THREAD

**Issue by Mortificer** [MelvorIdle/melvoridle.github.io#1884]
### Describe the bug

The bank reordering doesn't work properly with a zoom level set to anything besides 100% in the options.

### Reproduction Steps

1. Go to Settings -> Interface Settings -> Set Zoom Level
2. Change the zoom to anything besides 100%
3. Go to the bank
4. Try and drag items to reorder them
5. Many positions aren't available to drag items to
6. Examples:
7. At 80% zoom the item snaps to row 1, column 1 and it won't let me move it to any other position
8. At 90% zoom only the first 4 columns of each row are able to be used
9. Switching back to 100% zoom allows items to be moved to any position again

### Expected behaviour

Items should be able to be dragged to any position desired in the bank at any zoom level, but this only seems possible at 100% zoom

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1362

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
I've got a fix coming out soon for the Steam Zoom :)
