### ISSUE TITLE
[Bug]: Willow Tree Seeds image unavailable

### ISSUE THREAD

**Issue by Lullerooz** [MelvorIdle/melvoridle.github.io#1885]
### Describe the bug

The image for the Willow Tree seeds dont show up. It's as if there's a missing image file or image name/location is wrong.

### Screenshots

![image](https://user-images.githubusercontent.com/35085225/144899813-753b4290-c65b-446c-ae2b-1e3dd6b79d9e.png)
![Uploading image.png…]()

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1362

### Are you using any scripts or extensions?

No

**Comment by Lullerooz** [comment]
Just to update. The Cherry seed isnt showing as well

![image](https://user-images.githubusercontent.com/35085225/144906086-e0e683e0-2f7c-4e2b-8a61-2f66166308e7.png)

**Comment by imperialboy3** [comment]
Must be an issue on your end with loading. Works fine for me with Steam v1.0 ?1362. You could try reopening or a different internet connection.

**Comment by Lullerooz** [comment]
That might be it. I tried on my phone, it showed. I just got home from work and they're showing. Seems to be an internet thing or something on my end.  Thanks
