### ISSUE TITLE
[Bug]: Cant' properly move around items in the bank

### ISSUE THREAD

**Issue by Burdy64** [MelvorIdle/melvoridle.github.io#1886]
### Describe the bug

Playing on the Steam Version I'm unable to move items to any column other than the first 4. This happens regardless of whether its a locked item or not. I'm not sure the cause of this issue but after about of month of expecting it to be fixed with a restart/update the issue remains. 

### Reproduction Steps

1. Steam version
2. 200/300 bank slots
3. ??

### Expected behaviour

I expected to able to move my items freely in my bank. Gif recording shows the exact issue.

### Screenshots

![bugreport](https://user-images.githubusercontent.com/79890835/144922703-82595a7e-f654-435f-8fc1-0341dea40cbe.gif)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1362

### Are you using any scripts or extensions?

No

**Comment by imperialboy3** [comment]
1. What happens when you try to move an item from column 4 to column 5?
2. What happens when you resize your game to only show 10 columns? What about just 4?

**Comment by Burdy64** [comment]
> 1. What happens when you try to move an item from column 4 to column 5?
> 2. What happens when you resize your game to only show 10 columns? What about just 4?

1. Same result as moving any other item from column 5-9 to 5-9. Nothing moves.
2. 10 columns, no change. I haven't tried 4 column before, but it works completely normally. Just a huge pain to navigate.

**Comment by MelvorIdle** [comment]
Are you playing with a Zoom setting that isn't 100%?
