### ISSUE TITLE
[Bug]: Incorrect Mastery XP

### ISSUE THREAD

**Issue by Calo3** [MelvorIdle/melvoridle.github.io#1888]
### Describe the bug

While going from 50 to 66 Astrology over night studying with the level 50 Astrology my mastery rank only reached level 32. I suspect it used the mastery XP of whatever level I was before I swapped accounts (probably around 10) for each action of calculating my mastery XP instead of changing the value as I would have levelled. Not sure if specific to hardcore characters but this happened on a hardcore character.

### Reproduction Steps

1. Have 2 accounts (One was a regular, the other was Hardcore).
2. Study Astrology (I was using the level 50 one)
3. Swap accounts (Swapped from Hardcore to Regular)
4. Wait for a while so that the Mastery level would have increased.
5. Swap accounts to the original account studying Astrology 
6. Check Mastery Level/XP

### Expected behaviour

I expect the Mastery XP to be less than it would be if it had continued to update the value as the mastery level rose

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1355

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
> I suspect it used the mastery XP of whatever level I was before I swapped accounts 

This is currently the downside to Mastery that is not on the new tick-based system.

All skills are planned to eventually transition to the new system which fixes this issue. Mining and Firemaking are currently using the new system
