### ISSUE TITLE
[Bug]: Offline Woodcutting using up more summoning scrolls then online 

### ISSUE THREAD

**Issue by Artix121** [MelvorIdle/melvoridle.github.io#1889]
### Describe the bug

While doing yews and normal logs with the tier 2 woodcutting potion, the usage of salamander + ent is more when offline than online

Online usage: 1 cut = 2 ent + 1 salamander
Offline usage: 1 cut = 3 ent + 2 salamander 

### Reproduction Steps

1. Use tier 2 woodcutting potion.
2. Use ent + salamander synergy
3. Go to woodcutting. Start cutting yews + normal logs.
4. Compare scrolls usage when online vs offline. 

### Expected behaviour

Offline usage should match Online usage. 

### Screenshots

N/A

### Console output

N/A

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1362

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.0.2. Please open a new ticket if this is not the case.
