### ISSUE TITLE
Offline progression Herblore Potion Tier

### ISSUE THREAD

**Issue by jupi1001** [MelvorIdle/melvoridle.github.io#189]
**Describe the bug**
The game doesn't produce the higher potion, if you unlocked the next tier if you are in offline progression mode.

**To Reproduce**
1. Start to produce a potion, where you are not maxed tier
2. Save if necessary and close the browser/tab for offline progression
3. Wait until you think the next tier is unlocked(Obviously fastet from Tier 1 to 2)
4. Log back in
5. The game should show you that it still produced the older tier potion

**Expected behavior**
Automatically produce the next tier of potion if you unlock it, even in offline progression.

**Browser**
Chrome 81.0.4044.113

**Comment by TheBisping** [comment]
this isn't a bug. you dont get increased mastery perks until you log in again, although you do gain mastery progress while offline.
