### ISSUE TITLE
[Bug]: No "Big Chick (Hardcore)" Achievement unlocked 

### ISSUE THREAD

**Issue by egroenestein** [MelvorIdle/melvoridle.github.io#1892]
### Describe the bug

I killed the mama chicken in the chickencoop dungeon, on hardcore, Twice! 
but no achievement on steam was unlocked :( 

This person had the same on normal but seemed to sync later, #issue-801853005  

I beat the dungeon yesterday, died 30 min later, beat the dungeon again today. 

Got the death instantly and still no chicked dungeon achievement. 

### Reproduction Steps

1. Create hardcore character
2. Go to the Chicken Coop dungeon
3. Defeat the dungeon
4. Check Steam achievements
5. Notice it's missing

### Expected behaviour

I expected to receive the achievement for hardcode chickencoop, but I didn't.

### Screenshots

![mama chicken achievement bug](https://user-images.githubusercontent.com/59099540/145203382-f31c2e66-672d-456d-8811-9ee19478be40.png)

### Console output

PC Steam

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1362

### Are you using any scripts or extensions?

No

**Comment by egroenestein** [comment]
The achievement onlocked after 2 hours.  Which seems a sync issue, but the death one came immidiatly and seemed to prevent me from unlocking the achievement the first time even though i clearly killed it. 

Still a bug dispite being achieved now.

**Comment by MelvorIdle** [comment]
Steam achievements only unlock when you load a character (And they are all retroactive). This was done to increase performance in the game.
