### ISSUE TITLE
[Bug]: Golbin Raid: Pressing Escape at the 'Select New Equipment' modal prematurely ends the raid

### ISSUE THREAD

**Issue by Auron956** [MelvorIdle/melvoridle.github.io#1893]
### Describe the bug

Pressing the Escape key when prompted to select new equipment at the end of a wave in Golbin Raid puts the raid into an unexpected state - the raid no longer progresses, and the only way to proceed is by using the "Run/Area Select" combat option to end the raid. Following this, no further raids may be started without reloading the game.

### Reproduction Steps

1. Start the Golbin Raid
2. After one wave, the "Wave Complete"/"Select New Equipment" modal is shown. Rather than making any choice hit the Escape key, which closes the modal
3. The raid no longer progresses

### Expected behaviour

Pressing Escape at this modal has no effect - the player is forced to make a choice of equipment/food/runes/ammo.

### Console output

No relevant console output is present

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1362

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.0.2. Please open a new ticket if this is not the case.
