### ISSUE TITLE
[Bug]: Syncing between mobile and PC

### ISSUE THREAD

**Issue by Iplemons** [MelvorIdle/melvoridle.github.io#1895]
### Describe the bug

Was playing on my phone while my pc was idle and did a bunch of skilling to get more bronze bars. I also updated my tabs in my bank. I came to my pc and it didnt show up but still showed up on my phone. Even after logging back out and logging back in the issue is the same. 

### Reproduction Steps

do skill or action on phone while idle on pc. 

### Expected behaviour

syncing with cloud saves

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1362

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
