### ISSUE TITLE
[Bug]: <Incorrect Item Log>

### ISSUE THREAD

**Issue by JaeDenn15** [MelvorIdle/melvoridle.github.io#1896]
### Describe the bug

Gentle hands I isn’t showing in my log despite me now making the upgraded versions of this potion so I can’t get back to having it again

### Reproduction Steps

Unsure

### Expected behaviour

The item to show as achieved in the log

### Screenshots

![5834FB33-5D5B-437F-82F1-A8FF370C6E5C](https://user-images.githubusercontent.com/93299303/145305053-f92b5a41-dab5-43a2-b330-d1f8ef920f01.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1362

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
You can use the Herblore potion to acquire any tier of any potion :)
