### ISSUE TITLE
[Bug]: Golbin Raid ending on account swap

### ISSUE THREAD

**Issue by Calo3** [MelvorIdle/melvoridle.github.io#1897]
### Describe the bug

When swapping accounts and then later swapping back the Golbin Raid I was progressing in was no longer available to continue. Additionally I didn’t receive any rewards.

### Reproduction Steps

1. Start a Golbin raid
2. Swap Accounts
3. Swap back to original account the Golbin raid was started on

### Expected behaviour

Golbin raid will have ended with no rewards and you will only have the option to start a new Golbin raid

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1355

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Not a bug, this is a feature that is yet to be implemented into the Raid.

I can confirm you won't have to wait long for Raid pausing to be added to the game.
