### ISSUE TITLE
[Bug]: 'Summoning' Crafting Shows the Wrong Output Number on Item Equip

### ISSUE THREAD

**Issue by Sachbir** [MelvorIdle/melvoridle.github.io#1898]
### Describe the bug

When on the Summoning page, the number of tablets produced per action is displayed. When I click the shortcuts on the bottom right to equip my gear, the displayed number of tablets produced does not change. If I navigate away from this (to a different Familiar or a different page) then the number will update correctly

### Reproduction Steps

1. Unequip all summoning-related gear 
2. Go to the Summoning page 
3. Go to the Tablets section 
4. Click on a Tablet. Note the number listed under "Produces: __" 
5. Using the menu on the bottom right, click any/all gear listed. Note how the "Produces" number never updates changes

### Expected behaviour

The information for how many tablets are produced per operation should be updated as gear is added or removed. 

### Screenshots

1. No equipment is equipped (see bottom-right). "Produces 28 Tablets" (see bottom-left)

![Screen Shot 2021-12-09 at 12 04 45 PM](https://user-images.githubusercontent.com/32587956/145442540-94af9cbb-e543-4b85-81b4-f885dcbff8de.jpg)

2. All equipment is equipped (see bottom-right). "Produces 28 Tablets" (see bottom-left) 

![Screen Shot 2021-12-09 at 12 04 59 PM](https://user-images.githubusercontent.com/32587956/145442547-90bdd9ef-087f-43a7-8e1b-7b0eb115f171.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1363

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue was fixed as of v1.0.3.
