### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by Iolpot** [MelvorIdle/melvoridle.github.io#1900]
### Describe the bug

![image](https://user-images.githubusercontent.com/34144627/145484170-67bcaf76-4939-49ef-84ed-637e7ca28c4b.png)

### Reproduction Steps

![image](https://user-images.githubusercontent.com/34144627/145484182-8c355cee-78ff-43c8-811c-7e0fa67f83cc.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1363

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Offline progress is no longer calculated through the old method this error occurred in as of v1.0.3. Also may be related to #1562.
