### ISSUE TITLE
[Bug]: Discovering mark of the witch Alt Magic

### ISSUE THREAD

**Issue by PouletR0ti** [MelvorIdle/melvoridle.github.io#1901]
### Describe the bug

If you discover a mark of the witch while doing Alt Magic, it doesn't show on the login pop up screen after afk.
If you manage to level up the mark, the next screen will show up saying that the mark has leveled up.

### Reproduction Steps

1. Go to Alt Magic
2. Make blessed offering
3. Lock phone
4. wait
5. unlock phone
6. Recap screen only showing how many holy dust were made
7. Pop up screen mark of the witch leveled up
7(alt). Go to summoning and see that you discovered a new mark of the witch

### Expected behaviour

Expected to see on the recap screen
"While you were gone:
X mark of the witch discovered
N holy dust"

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1363

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue was fixed as of v1.0.2.
