### ISSUE TITLE
[Bug]: Alt Magic stops when logging back

### ISSUE THREAD

**Issue by PouletR0ti** [MelvorIdle/melvoridle.github.io#1902]
### Describe the bug

If you are training Alt magic, then if you idle train (leave the app) and come back (load save), alt magic stops on load

### Reproduction Steps

1. Go to Alt magic
2. Train blessed offering (what i was training when it happened)
3. leave app
4. start app and load save
6. go to alt magic and see that blessed offering stoped training

### Expected behaviour

Expected to have the alt magic training continue after load.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1363

### Are you using any scripts or extensions?

No

**Comment by NiIex** [comment]
Just chipping in to confirm it still happens as described (?1366). Using Chromium browser and also training Blessed Offering.

**Comment by avrom0** [comment]
Adding a message to confirm this is happening to me as well. Have reapeatedly logged back in while crafting 'Just learning' offline and the action frequently stops as soon as I log in.

Experienced on Chrome browser.

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.0.2. Please open a new ticket if this is not the case.
