### ISSUE TITLE
[Bug]: Firemaking - Bonfire not working as intended

### ISSUE THREAD

**Issue by denjan555** [MelvorIdle/melvoridle.github.io#1903]
### Describe the bug

Everytime I open the firemaking skills page, the "light bonfire" bar fills like I've just burned 10 logs to light it. I can keep clicking the firemaking navigation button and it will refill over and over again without burning any logs but the bar consistently refills.

It says the bonfire status is active and the firemaking xp bonus is active but I'm not sure if they are actually active or just a visual bug. Even when the bonfire bar is empty, it says the bonfire status is active.

I can't light the bonfire the way it is intended to be lit (pressing the "light bonfire" button) and I can't get my logs to be consumed through the button either.

### Reproduction Steps

1. Click on "Firemaking" in the left side bar

### Expected behaviour

Bonfire is empty, clicking "light bonfire" fills the bar and consumes 10 logs.

### Screenshots

https://preview.redd.it/ibnv5bj43p481.gif?format=mp4&s=0362c0d766110aad9dafda23d8c52455f22c12d2

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1363

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
