### ISSUE TITLE
[Translation Error]: <Spanish translation>

### ISSUE THREAD

**Issue by Hinoya** [MelvorIdle/melvoridle.github.io#1905]
### Which text in the game has a translation error?

Arquería.

Fletching in spanish is "Emplumado" or "Emplumado de flechas". "Arquería" means << to use a bow >>.

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
