### ISSUE TITLE
[Bug]: "Cheats enabled" passive effect in goblin raid

### ISSUE THREAD

**Issue by IsaacGraham** [MelvorIdle/melvoridle.github.io#1910]
### Describe the bug

The description for Cheats Enabled is phrased as though the interval reduction is a negative portion of the effect, which leads me to believe it's supposed to be an interval increase. If this is working as intended, the text should be adjusted, but what happens in practice is that their attack interval is reduced by 10%, a buff.

![cheatsenabled](https://user-images.githubusercontent.com/5593732/145645703-9e6c2353-d97a-405f-a439-5d7d6112f412.png)

### Reproduction Steps

1. Begin Goblin Raid
2. Proceed until you encounter an enemy with the Cheats Enabled passive effect
3. Observe their attack speed

### Expected behaviour

One of the below:

Enemies have attack speed of 1.65s, rather than 1.35s
OR
The passive description is rephrased to unambiguously show it as a positive effect

### Screenshots

![cheatsenabled](https://user-images.githubusercontent.com/5593732/145646207-75d1697a-a44b-47c1-8a93-a822d0937bc3.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1363

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
