### ISSUE TITLE
[Bug]: Astrology incomplete mastery issue

### ISSUE THREAD

**Issue by DragonRiderQ** [MelvorIdle/melvoridle.github.io#1911]
### Describe the bug

I have 99 mastery in all constellations, however when I view mastery skill page it says I am short 1 level.

### Reproduction Steps

1. Complete mastery in astrology (to be clear I purchased the lower level constellations with mastery points to complete them so it could have something to do with that, I believe it was Deedree through Ameria that was purchased)
2. look at mastery page.
3. Mastery stuck at 1088/1089

### Expected behaviour

Should be at 1089/1089

### Screenshots

![image](https://user-images.githubusercontent.com/95968906/145678498-37183d92-ea09-430f-bbee-b20e914426df.png)

![image](https://user-images.githubusercontent.com/95968906/145678533-bffb2bbf-636e-46c8-a87c-1a8404de4cbf.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1361

### Are you using any scripts or extensions?

No

**Comment by EtK2000** [comment]
I had this bug as well until I reopened the game, can confirm.
