### ISSUE TITLE
[Bug]: Secret stardust potion 3 becomes unselected when you move out of astrology tab

### ISSUE THREAD

**Issue by pramit57** [MelvorIdle/melvoridle.github.io#1912]
### Describe the bug

The secret stardust potion 3 reduces the astrology task time to 2.7 seconds from 3 seconds. When I select it for usage, its used until it runs out of charges for one potion (i.e. after 15 uses). After this, it doesn't automatically use the next potion. This makes the potion almost unusuable

### Reproduction Steps

1. Start a task in astrology
2. Use the secret stardust potion 3

### Expected behaviour

I expected the potion to continue to be used

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

1366

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Make sure you have this setting enabled for Astrology 
![image](https://user-images.githubusercontent.com/45249614/145912209-93546bdf-9c7e-4c96-9f63-9a91ffefa59d.png)
