### ISSUE TITLE
[Bug]: <title> autoequip food not working offline

### ISSUE THREAD

**Issue by oldcrick** [MelvorIdle/melvoridle.github.io#1913]
### Describe the bug

autoequip food is not working while offline. appears to kick in when i return from offine, but i am left with a stack in my bank. 

active cooking apple pie, passive cooking crab and cream corn soup. haven’t tried other foods.

using ios15.1 on iphone 11 pro

melvor version 1.0 (?1366)

sorry i only have a mobile so i can’t check other platforms

### Reproduction Steps

1. start active cooking, make sure autoequip is selected and correct food equipped
2. exit to character select screen, force quit app
3. open melvor app, load character 
4. check bank

### Expected behaviour

expect my apple pie to all be equipped with none in bank

### Screenshots

sorry, didn’t take screenshots 

thanks!

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1366

### Are you using any scripts or extensions?

No

**Comment by meesha7** [comment]
I'm having the same issue, iOS and also in Firefox. While in the tab in Firefox, autoequip works, but when the tab is not focused, it doesn't.

**Comment by liththedev** [comment]
Also seeing this in chrome, cooking whales

**Comment by Helam24** [comment]
Seeing this on iPad, cooking whales

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.0.3.
