### ISSUE TITLE
[Bug]: <Getting this error everytime I start the game>

### ISSUE THREAD

**Issue by PinkUnicornyo** [MelvorIdle/melvoridle.github.io#1916]
### Describe the bug

Getting this error everytime I start the game. I've had this issue for about 2-3 weeks. I have Steam, it used to work fine for weeks up until this happened.

### Screenshots

![unknown](![image](https://user-images.githubusercontent.com/96019503/145723899-d5d92b09-ed8a-4949-91d0-05554aa840fa.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?doesnt say, can't access game

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
It looks like you have a corrupted item in your bank. Let me know your cloud save username and I will take a look.

**Comment by PinkUnicornyo** [comment]
I believe it is Thorin

**Comment by PinkUnicornyo** [comment]
I have literally not been able to play the game for about two months.

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
