### ISSUE TITLE
[Bug]: Prayer I haven't unlocked yet is selected and can't change it

### ISSUE THREAD

**Issue by Betel96** [MelvorIdle/melvoridle.github.io#1918]
### Describe the bug

A prayer I haven't got the level for yet is selected and I can't change it. I am only able to have 1 prayer selected at a time.

### Expected behaviour

To be able to use 2 prayers that I have unlocked.

### Screenshots

![Screenshot_20211212-223518_Melvor Idle](https://user-images.githubusercontent.com/96027161/145732577-673f3fe6-0a93-4244-9c42-91f1a9c6fd66.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1366

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
You can deselect the prayer from this menu, as you would have had it selected prior to the update where levels changed.

![image](https://user-images.githubusercontent.com/45249614/145911852-03944398-7ed9-4516-b940-5c570a52dd6e.png)
