### ISSUE TITLE
[Bug]: Confetti

### ISSUE THREAD

**Issue by DaCuteRaccoon** [MelvorIdle/melvoridle.github.io#1919]
### Describe the bug

The confetti after I master something goes on for a short time, I can't see it.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1366

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Not a bug. The confetti is active until you close the popup window.
