### ISSUE TITLE
[Bug]: <Twin Exiles in Golbin Raid casts Magic Ray>

### ISSUE THREAD

**Issue by sorenos** [MelvorIdle/melvoridle.github.io#1921]
### Describe the bug

I rolled twin exiles in Golbin Raid, and am surprised that it casts Magic Ray. It gives 5 hits every turn instead of the expected 2. It doesn't cost any runes, luckily.
(I also got the Sandstorm Ring, in case that matters)

### Reproduction Steps

Do Golbin Raid
Get sandstorm ring (might not matter)
Get Twin Exiles
I am now casting Magic ray.

### Expected behaviour

Should do 'twin hit' or something, and only hit twice.

### Screenshots

![image](https://user-images.githubusercontent.com/9727191/145946927-83869390-aa7d-4472-a9f9-6ca71d3a5acc.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1366

### Are you using any scripts or extensions?

No

**Comment by varjutus** [comment]
If it's marked with (ALT), it means it has a different special attack/effect, this may be the case.

**Comment by MelvorIdle** [comment]
You selected an (ALT) item which gives it a random special attack
