### ISSUE TITLE
[Bug]: Elerine Bow not dropping from Elerine Archers

### ISSUE THREAD

**Issue by JakeMassmann** [MelvorIdle/melvoridle.github.io#1922]
### Describe the bug

I killed 990 Elerine Archers looking for the Elerine Bow and gave up. The Wiki says it has a 0.56% chance of dropping, which would mean this is a ~0.4% chance of this happening. Math shown below.
(1-.0056)^990 = 0.00385038784 = .38%

I gave up at this point, in case it is a bug.

### Reproduction Steps

Kill 990 Elerine Archers

### Expected behaviour

~5 Elerine Bows drop

### Screenshots

![image](https://user-images.githubusercontent.com/44552005/146045689-a0232c60-a91d-484e-af25-cf1976929e06.png)
![image](https://user-images.githubusercontent.com/44552005/146045759-8a66faa7-3c8b-4eb1-b46f-d2d4a85cc703.png)
![image](https://user-images.githubusercontent.com/44552005/146046145-2e1d0393-12df-4132-95e1-ed04a2db8bfc.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1366

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is just the nature of RNG
