### ISSUE TITLE
[Bug]: <Slayer Leather Body (Strong) missing mage defence stat>

### ISSUE THREAD

**Issue by demo0033** [MelvorIdle/melvoridle.github.io#1924]
### Describe the bug

The item **Slayer Leather Body (Strong)** has 0 mage defence.

I assumed this was a bug as it upgrades out of **Slayer Leather Body (Basic)** which has 20 mage defence, and upgrades into **Slayer Leather Body (Elite)** which has 40 mage defence. The Slayer Cowl for each tier has increasing mage defence as well.

### Reproduction Steps

1. Acquire a **Slayer Leather Body (Strong)** item
2. Check combat stat page for the item

### Expected behaviour

The equipment piece should have about 30 mage defence, splitting the difference between the tiers directly above and below.

### Screenshots

![image](https://user-images.githubusercontent.com/77757345/146104437-63840212-07ed-48d7-97cc-d3c34c604d7c.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1366

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
