### ISSUE TITLE
[Bug]: <title>ring of blade Echoes cannot get the effect of 95% MASTERY POOL CHE CK POINTS

### ISSUE THREAD

**Issue by zcd394424082** [MelvorIdle/melvoridle.github.io#1925]
### Describe the bug

ring of blade Echoes cannot get the effect of 95% MASTERY POOL CHE CK POINTS,
Always Craft a base quantity of 2 for Rings and Necklaces

### Expected behaviour

ring of blade Echoes cannot will produce two at a time

### Screenshots

![image](https://user-images.githubusercontent.com/26991581/146138384-42b16847-6258-43e6-980f-1b7451a33b0b.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1366

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue was fixed as of v1.0.3.
