### ISSUE TITLE
Wrong Requirements Smithing Bars Shown on Tool Tip[Bug]: <title>

### ISSUE THREAD

**Issue by ChazTech3030** [MelvorIdle/melvoridle.github.io#1927]
### Describe the bug

The tooltip shown for smithing bars remains as the "half coal cost" even when the smithing cape is not equipped. I do not own the max cape, so I know that isn't what's causing it. Equipping and unequipping the smithing cape shows no changes to the tool tip.

I'm also unsure of whether this tool tip changes by default when you hit 99 smithing, when you buy the cape, or when you first equip the cape...

Full disclosure, SEMI and Combat Simulator plugins are being used.

### Screenshots

![image](https://user-images.githubusercontent.com/45007570/146200696-d4db8c95-ab14-4947-9cd7-63137b0dc359.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1366

### Are you using any scripts or extensions?

Yes

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.0.2. Please open a new ticket if this is not the case.
