### ISSUE TITLE
[Bug]: Perfect whale's disappearing

### ISSUE THREAD

**Issue by PistonMyPants** [MelvorIdle/melvoridle.github.io#1928]
### Describe the bug

When cooking whale (currently using redwood fire) normal cooked whale is rewarded as expected while perfect whale is only received during offline progress

Attempted to reproduce with crab but they were working as intended (both types rewarded while game window is open as well as in offline mode)

### Reproduction Steps

attempt to cook whale
observe bank with the game window open
perfect whale shows at the bottom (+1 whale with the star) but is not added to the bank
change tabs to set game to offline progression
wait several minutes
both types of whale awarded in quantities expected (does not retroactively add any missing perfect whales, only what is produced during that offline progression)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1366

### Are you using any scripts or extensions?

No

**Comment by CarrotMD** [comment]
Are your equipped perfect whales increasing, by any chance?

**Comment by PistonMyPants** [comment]
I didnt think I had any equipped because this was my first time making any, but you were absolutely correct. Should have checked that before posting, but thank you for the help
