### ISSUE TITLE
[Bug]: Push notifications not working

### ISSUE THREAD

**Issue by Mbar93** [MelvorIdle/melvoridle.github.io#1929]
### Describe the bug

Galaxy Note 9 phone
Running on android version 10

Not receiving push notifications
According to a couple other players that i've spoken to on reddit they receive notifications but not consistently.

### Expected behaviour

Farming patch is ready to harvest > push notification

### Screenshots

![Screenshot_20211215-083207_Settings](https://user-images.githubusercontent.com/96188925/146235988-58daa553-14c1-4c4f-b914-25575e92ac87.jpg)

I wanted to add a screenshot of my game settings here to show that the option for push notifications is on but i cant figure out how to edit one in.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1366
### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Push notifications currently only work when using the "Plant All" farming option.

**Comment by Mbar93** [comment]
> Push notifications currently only work when using the "Plant All" farming option.

I know this. I have been using plant all and have never received a notification.

**Comment by tgkenney** [comment]
Was anything done for this or was it just closed?  I'm experiencing the same issue. I'm using the Plant All option, notifications are on in both the game settings and android settings. I'm using a Pixel 6 with Android 12

**Comment by Mbar93** [comment]
Nothing was done and it was closed. Dev was unwilling to look into it
despite giving proper details on what was happening.
