### ISSUE TITLE
[Bug]: App in background feezes progression

### ISSUE THREAD

**Issue by mloler** [MelvorIdle/melvoridle.github.io#1931]
### Describe the bug

If the App is left running in the background and you come back to it after awhile, no progression of what you left to do has been done. Left in mining no mining, same for smithing... etc. This have been tested in a couple of hours gap to verify.
The only thing that is accurate and progressed is when was the last cloud save.

### Expected behaviour

Should be calculated the same as offline progression after awhile.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1366

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Make sure this setting is enabled for the game to pick up progress while minimised on Mobile

![image](https://user-images.githubusercontent.com/45249614/147170217-12924f71-0c50-47ea-beaf-701bfaa5376f.png)

**Comment by mloler** [comment]
That setting is off. For example I just had over 2 hours of woodcutting magic wood, and got only 32...
