### ISSUE TITLE
[Spelling/Grammar]: Combat Game Guide describes Ranged incorrectly.

### ISSUE THREAD

**Issue by Mythyryn** [MelvorIdle/melvoridle.github.io#1932]
### What text is wrong?

The Combat Game Guide for Ranged inaccurately states that the player's Ranged level will contribute towards their Ranged Evasion Rating. Every piece of information I could find points towards it doing absolutely nothing defensively.
![image](https://user-images.githubusercontent.com/9811307/146617043-0944842b-4f7e-4ae6-b352-85a8e3f2f842.png)

### What is the correct spelling or grammar?

Just remove the bit about it increasing Ranged Evasion Rating.

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
