### ISSUE TITLE
[Bug]: All miss

### ISSUE THREAD

**Issue by Dvoinyakov1** [MelvorIdle/melvoridle.github.io#1933]
### Describe the bug

Out of 10 hits, 2 hits with 80% accuracy, is this normal? :( :

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1366

### Are you using any scripts or extensions?

Yes

**Comment by MelvorIdle** [comment]
That is RNG unfortunately.
