### ISSUE TITLE
[Bug]: <Smithing level went down from 99 to 96 >

### ISSUE THREAD

**Issue by tinfoiljoe** [MelvorIdle/melvoridle.github.io#1934]
### Describe the bug

i woke up and opened the game this morning and it is saying i no longer have 99 smiting, but even though half my masteries are 99.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1366

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Negative progress should no longer be an issues as of v1.0.2.
