### ISSUE TITLE
-50% coal perk on smithing skill cape not work. Steam client.[Bug]: <title>

### ISSUE THREAD

**Issue by polop654** [MelvorIdle/melvoridle.github.io#1935]
### Describe the bug

The perk for the smithing cape is not working. this is on the steam client.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1366

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
The number you see displayed on the Coal is the number after all bonuses are applied.

I can confirm the cape is still working.
