### ISSUE TITLE
[Bug]: woodcutting axe says bronze when should be dragon

### ISSUE THREAD

**Issue by jeathvader** [MelvorIdle/melvoridle.github.io#1936]
### Describe the bug

I opened the mobile app on (sat Dec 18) to check my astrology levels.
I left it alone for hours only to come back to it saying I do not have access to premium.

### Screenshots

![Screenshot_20211218-234212_Melvor Idle](https://user-images.githubusercontent.com/20526083/146665321-5bcc8b4c-69b1-46b8-a230-4c81d4b10881.jpg)
![Screenshot_20211218-234206_Melvor Idle](https://user-images.githubusercontent.com/20526083/146665323-40dc764d-e4c1-48b7-a8aa-8d9e1c6cd1dc.jpg)
![Screenshot_20211218-224551_Melvor Idle](https://user-images.githubusercontent.com/20526083/146665330-dd3f3e10-1d31-4ae6-87e8-7355d694ba90.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1366

### Are you using any scripts or extensions?

No

**Comment by jeathvader** [comment]
![Screenshot_20211221-213920_Melvor Idle](https://user-images.githubusercontent.com/20526083/147031662-33e762d0-195f-46db-a1f0-2052a17412c0.jpg)

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.0.2. Please open a new ticket if this is not the case.
