### ISSUE TITLE
[Bug]: Blacksmith statistics mistakes

### ISSUE THREAD

**Issue by shinobu00000** [MelvorIdle/melvoridle.github.io#1942]
### Describe the bug

I don't understand English, so I use Google Translate.

The number of ores saved by blacksmithing on the statistics screen and the number of ores used are reversed.

### Screenshots

![report](https://user-images.githubusercontent.com/96424648/146768621-6c608f80-14af-4820-8b6f-729c1d9deb7a.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1366

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
