### ISSUE TITLE
[Bug]: Level 99 skills not showing 100%

### ISSUE THREAD

**Issue by JTRemeijn** [MelvorIdle/melvoridle.github.io#1943]
### Describe the bug

Ever since one of the last updates, my strength and defense skill don't show 100% anymore in the combat progress tab, even though they are level 99 and I have virtual levels disabled. I have attached a screenshot showing the problem. Whenever I train the skill, it jumps back to 100%, but afterwards it jumps back again. 

### Reproduction Steps

1. Train defense and strength skill to level 99 (old version)
2. Update to new version
3. Show skill progress in the combat screen

### Expected behaviour

Level 99 skills (defense and strength) to show 100%

### Screenshots

![Screenshot_20211220-145856](https://user-images.githubusercontent.com/49062189/146779298-f40aafe0-d084-425d-81d5-b6c1465e5c3c.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1366

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
