### ISSUE TITLE
[Bug]: <title> game wont start, stuck initialising

### ISSUE THREAD

**Issue by AnFettuccine** [MelvorIdle/melvoridle.github.io#1944]
### Describe the bug

game wont start, stuck initialising, see image

### Reproduction Steps

1. Start fully updated game via steam
2. See image attached

### Screenshots

![unknown](https://user-images.githubusercontent.com/96434149/146793120-020ba419-bc77-4156-b3c3-24a25e00bb6c.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1.1

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
