### ISSUE TITLE
[Bug]: Miolite Chest Icon doesn't appear in Completion log

### ISSUE THREAD

**Issue by gtblack4** [MelvorIdle/melvoridle.github.io#1946]
### Describe the bug

When viewing the Completing log after obtaining a Miolite Chest, the icon shows the default "?" as if the item had no been aquired.
![image](https://user-images.githubusercontent.com/17162911/146958269-a565b451-bbfe-4c4c-92a7-000783e5981a.png)

### Reproduction Steps

1. Obtain a Miolite Chest by completing the Miolite Caves
2. Go to the Completion log
3. Search for "Miolite Chest"
4. Observe the "?" icon displayed

### Expected behaviour

When viewing the completing log after obtaining a Miolite chest, the Miolite chest icon should be displayed

### Screenshots

![image](https://user-images.githubusercontent.com/17162911/146958578-87257ca8-bea6-4a6a-b673-cf207144b560.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1366

### Are you using any scripts or extensions?

Yes

**Comment by coolrox95** [comment]
Issue was fixed as of v1.0.3
