### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by LochNessLapras** [MelvorIdle/melvoridle.github.io#1947]
### Describe the bug

Golbin Raid progress not kept. While playing on mobile my game crashed at wave 127 and I did not get any coins for my 7 hours of play 
on the Golbin Raid. How can I at least get my accumulated coins back?

### Screenshots

![Screenshot_20211221-132811_Melvor Idle](https://user-images.githubusercontent.com/96498623/146993098-b2382335-ef9f-4949-830e-c990da635a56.jpg)

### Console output

Mobile

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1341

### Are you using any scripts or extensions?

No

**Comment by LochNessLapras** [comment]
Subversion is truly ?1366

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.0.2. Please open a new ticket if this is not the case.
