### ISSUE TITLE
[Bug]: Ranged assistance potion

### ISSUE THREAD

**Issue by Fuqmesid3way** [MelvorIdle/melvoridle.github.io#1948]
### Describe the bug

When making Ranged assistance potion, it turned into Ranged strength potion

### Reproduction Steps

1. Go to Herblore
2. Select combat potions
3. Create Ranged assistance potion 
4. Ranged assistance potion turns into Ranged strength potion

### Expected behaviour

Expected that making Ranged assistance potion would produce Ranged assistance potion 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

Not sure, latest update for Samsung Galaxy s20+

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
I am unable to reproduce this bug. Are you sure you are looking at the correct potion?
