### ISSUE TITLE
[Bug]: Crafting normal shortbow in tutorial doesn't advance tutorial

### ISSUE THREAD

**Issue by LeftofZen** [MelvorIdle/melvoridle.github.io#1949]
### Describe the bug

Unable to progress tutorial since past 'fletch 1 normal shortbow', even after fletching it.

### Reproduction Steps

1. Do tutorial
2. Get to fletch normal shortbow
3. Buy bowstring from shop
4. Fletch normal shortbow
5. Tutorial doesn't progress, and I can't buy another bowstring since the shop is locked...

### Expected behaviour

Tutorial progresses

### Screenshots

![image](https://user-images.githubusercontent.com/7483209/147158924-49d22188-e15f-4f8a-a619-6a0655a5ca41.png)

![image](https://user-images.githubusercontent.com/7483209/147158943-a66a4b1f-fa2e-4fd4-84b1-75b197d8a67a.png)

![image](https://user-images.githubusercontent.com/7483209/147158969-21719285-82bd-4d33-9e4e-757969cc1282.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1366

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Did you craft the shortbow prior to the tutorial task by chance?

**Comment by LeftofZen** [comment]
Um tbh I cannot remember, but it seems likely that that is what happened.

**Comment by bling214** [comment]
This bug still exists and is happening to me too. I crafted the normal short bow but it never shows up in my bank inventory, and now I can't craft another normal shortbow since the shop won't let me buy another bowstring.

**Comment by MelvorIdle** [comment]
I have just pushed a hotfix to the game that allows for bowstrings to be purchased in other areas of the tutorial. So if the bow does not display, you will be able to create a new one by purchasing another bowstring from the shop.

**Comment by Obiduck11** [comment]
I got this same problem, can't buy string and no bow showing up.

**Comment by HontoNoRoger** [comment]
Same here :(

**Comment by HontoNoRoger** [comment]
I was able to buy more strings after todays hotfix. On the first bow build after that I still had no bow in the bank.
I then sold items to get from 11/12 to 09/12 used slots in the bank, crafted 3 bows afterwards of which all 3 were in the bank and I could equip one. Thank you!
