### ISSUE TITLE
[Bug]: Buying Compost doesn't advance tutorial

### ISSUE THREAD

**Issue by NoBraino** [MelvorIdle/melvoridle.github.io#1950]
### Describe the bug

No completion of tutorial task for buying compost - farming remains locked and I cannot further advance from the quest. 

### Reproduction Steps

1. Received tutorial instruction to buy compost
2. Clicked on shop in tutorial instruction to get to shop
3. Buy compost
4. No completion of task detected
5. Tried three more times still without completion of task

### Expected behaviour

As above 

### Screenshots

![Screenshot_20211223-080416_Melvor Idle](https://user-images.githubusercontent.com/96553909/147168666-05309084-0159-4f0b-8722-9df22a154374.jpg)

### Console output

Android Phone (Samsung) 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

Version 1366

### Are you using any scripts or extensions?

No

**Comment by NoBraino** [comment]
![Screenshot_20211223-080430_Melvor Idle](https://user-images.githubusercontent.com/96553909/147168946-5d720166-1e6f-4480-884f-823132790554.jpg)
![Screenshot_20211223-080434_Melvor Idle](https://user-images.githubusercontent.com/96553909/147168956-c46710dc-f4ea-40ab-bb41-e29b6352c9bb.jpg)
![Screenshot_20211223-080458_Melvor Idle](https://user-images.githubusercontent.com/96553909/147168976-61cc94e6-e5cf-437a-b2a4-6bd4dcffafae.jpg)

**Comment by MelvorIdle** [comment]
The tutorial task is to "Buy 5 Compost". You have purchased 4, so 1 more is required.
