### ISSUE TITLE
[Bug]: Buying multiple bank slots calculates price incorrectly

### ISSUE THREAD

**Issue by haggishunt56** [MelvorIdle/melvoridle.github.io#1951]
### Describe the bug

When buying one bank slot, the cost is 5,000K. Buying 10x slots should cost 50,000K or 50M however it is calculated as 500M.
Similarly, 100x slots is calculated at 50B instead of 50M, and 1000x slots is 5000B.

### Reproduction Steps

Go to shop, select any multiple of bank slots to buy other than 1

### Expected behaviour

Cost to purchase calculates incorrectly

### Screenshots

![68522A1A-F363-4C0B-88B2-AB280B5B66AC](https://user-images.githubusercontent.com/54241835/147173321-bfcccda9-a040-4948-a102-3c40e1dface9.png)
![131C513A-F979-44FC-A623-43D9FCD9654C](https://user-images.githubusercontent.com/54241835/147173323-13bafd3e-1020-40bf-8c68-bb56b07963ad.png)
![F5C8D57C-7395-4B5C-82C3-2247D4FB024B](https://user-images.githubusercontent.com/54241835/147173326-0c8e0fd5-889f-4eb1-8d79-c268ae2dce33.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1.0.1 (?1400)

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is now hotfixed
