### ISSUE TITLE
[Bug]: Item in new bank slot not showing

### ISSUE THREAD

**Issue by Airellex** [MelvorIdle/melvoridle.github.io#1952]
### Describe the bug

When item are place in my new bank slot, none are showing

### Reproduction Steps

1. Select item you want to move 
2. Select the new bank slot you want to move them to 
3. Confirm

### Expected behaviour

Expected to see the item I placed in the bank slot

### Screenshots

![D9FF1A3F-637F-43AB-9158-8F98D3D40A47](https://user-images.githubusercontent.com/96556608/147176976-95ae62da-724d-4667-8099-38950326d4e7.jpeg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [x] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1403

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is now hotfixed
