### ISSUE TITLE
[Bug]: High buy quantities lags the game (solution included)

### ISSUE THREAD

**Issue by imperialboy3** [MelvorIdle/melvoridle.github.io#1953]
### Describe the bug

Bank space cost-formula lags the game for high buy quantities.

### Reproduction Steps

1. Go to shop
2. Set your buy quantity high
3. Lag

### Expected behaviour

Don't lag by replacing the else clause of getBankUpgradeCost with:

```
else {
    return cost + (count - i) * 5000000;
}
```

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1412

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Hotfix has been applied. Thank you for the solution
