### ISSUE TITLE
[Bug]: Harvest/Plant all for Farming freezes game

### ISSUE THREAD

**Issue by Cyrogem** [MelvorIdle/melvoridle.github.io#1954]
### Describe the bug

On the new Christmas patch when trying to harvest or plant all the game freezes.  When I did trees it froze for about 40 seconds, when I did herbs the page froze for 2 minutes before crashing.

### Reproduction Steps

1. Have max slots for farming
2. Do 'Harvest All' or 'Plant All'
3. Wait for a very long time

### Expected behaviour

Expected behavior is just the normal zero to half second delay

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1212

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
I believe this is now hotfixed as of (?1419). Let me know if you still see the bug.
