### ISSUE TITLE
[Bug]: Custom purchase amount for bank slots not working

### ISSUE THREAD

**Issue by clayajohnson** [MelvorIdle/melvoridle.github.io#1955]
### Describe the bug

Setting a custom purchase amount of bank slots prevents the user from buying that many. Selecting a number from the drop down menu of presets does work however.

### Reproduction Steps

1. go to shop
2. select the drop down to buy multiple bank slots
3. input a custom amount
4. try to purchase the bank slots

### Expected behaviour

Able to purchase custom number of bank slots

### Console output

No console log when performing this action

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1413

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This should be fixed as of one of the previous hotfixes. Can you confirm you are not seeing the bug?
