### ISSUE TITLE
[Bug]: Holiday Event - 'Number of gifts in bank' only shows `0`

### ISSUE THREAD

**Issue by xFusionLordx** [MelvorIdle/melvoridle.github.io#1956]
### Describe the bug

  Holiday event, returning gifts, amount in bank only shows 0.

### Expected behaviour

Expect the line to show number of gifts in the bank.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1412

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is now hotfixed as of ?1416 :)
