### ISSUE TITLE
[Bug]: Xmas present count discrepancy when gaining present during play session

### ISSUE THREAD

**Issue by RansomTime** [MelvorIdle/melvoridle.github.io#1958]
### Describe the bug

Present count only seems to update when initially logging into character.

### Reproduction Steps

1. Start a skill that gives presents.
2. Gain a present
3. Look at number of presents gained

### Expected behaviour

Present count increments based on number of presents gained.

### Screenshots

![Screenshot_20211223-094230_2b8eea6112cc876d6c442b74a1d27a81](https://user-images.githubusercontent.com/47819665/147222943-6bb5f0c3-44ac-4b25-b341-cd931408c247.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1415

### Are you using any scripts or extensions?

No

**Comment by kellewic** [comment]
Same on Steam version. I can see I have 3 Purple presents in the bank but all numbers on the holiday event screen are zero. If I stop the game and restart, the counts appear like they should but will not update while the game is running.

**Comment by MelvorIdle** [comment]
This is now hotfixed as of ?1416 :)
