### ISSUE TITLE
[Bug]: Text fields in Change Character Name are 'Language ID Undefined'

### ISSUE THREAD

**Issue by NickTompk** [MelvorIdle/melvoridle.github.io#1961]
### Describe the bug

Text fields in Change Character Name are 'Language ID Undefined' for the banner, title, and button.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1415

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been hotfixed as of v1.0.3 (?1834).
