### ISSUE TITLE
[Bug]: pet festive rock 

### ISSUE THREAD

**Issue by FoolsChoice** [MelvorIdle/melvoridle.github.io#1966]
### Describe the bug

I completed the fishing quest and it did not give me the pet

### Screenshots

![C4997425-6AB0-41A1-BC34-B7F6A08F9E50](https://user-images.githubusercontent.com/96610377/147325349-c1dabdf2-3348-413a-b0a7-62e4b94a4aaa.png)
![1FD76207-A06C-455F-83AB-3183B770091A](https://user-images.githubusercontent.com/96610377/147325351-01d8fe9c-4c74-4529-acc1-31a8fc91f1d4.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1341

### Are you using any scripts or extensions?

No

**Comment by FoolsChoice** [comment]
Restarted game fixed it

**Comment by MelvorIdle** [comment]
Visual bug, you did get it (Like you saw when you refreshed) :)

**Comment by Freyj** [comment]
Hello, I have this bug as well, on the Steam version, 
![image](https://user-images.githubusercontent.com/5897539/147644559-e0889bb5-c192-46bb-9ff4-a12d1661fa9a.png)
and it doesn't show on the item list either : 
![image](https://user-images.githubusercontent.com/5897539/147644608-928a55e0-05d5-4cc9-9590-b4e817f86f61.png)
I tried restarting the game but it did not allow me to see it once reloaded.
