### ISSUE TITLE
[Spelling/Grammar]: Astrology mastery token has inconsistent name and description

### ISSUE THREAD

**Issue by Brad-12** [MelvorIdle/melvoridle.github.io#1967]
### What text is wrong?

![image](https://user-images.githubusercontent.com/94098195/147330038-51c28980-ccd0-43eb-a58f-319cc689d3d1.png)

See image.

### What is the correct spelling or grammar?

add () and also a description :)

**Comment by Brad-12** [comment]
Just found a post where @MelvorIdle replied saying it was hot fixed (25 days ago) https://github.com/MelvorIdle/melvoridle.github.io/issues/1796
Perhaps its re-surfaced?

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
