### ISSUE TITLE
Incomplete Mining Mastery Information

### ISSUE THREAD

**Issue by maxencefrenette** [MelvorIdle/melvoridle.github.io#197]
**Describe the bug**
The mining mastery information only shows the chances to obtain 2 ores. It should also mention the increase in rock hp.

**To Reproduce**
1. Go to Mastery > Mining > Unlocks

**Screenshots**
![image](https://user-images.githubusercontent.com/431838/80045183-80084d80-84bb-11ea-9811-04a1f85e5e1b.png)

**Comment by MelvorIdle** [comment]
Added in v0.15
