### ISSUE TITLE
[Spelling/Grammar]: +$1.000 magic bones

### ISSUE THREAD

**Issue by Herecius** [MelvorIdle/melvoridle.github.io#1975]
### What text is wrong?

There is writing +$1.000 magic bones at slayer shop in generous resupply

### What is the correct spelling or grammar?

+1.000 magic bones
![Ekran görüntüsü 2021-12-25 175444](https://user-images.githubusercontent.com/96656092/147387812-524ba983-e43a-49da-8659-e209a5738b92.png)

**Comment by coolrox95** [comment]
Issue is not present in latest version of game (v1.0.3).
