### ISSUE TITLE
[Bug]: log options missing firemaker

### ISSUE THREAD

**Issue by JonnasD** [MelvorIdle/melvoridle.github.io#1976]
### Describe the bug

In firemaker you only get options for normal logs and maple logs to burn.

### Expected behaviour

I read in the wiki that you got steps for all the logs when you level the hability.

### Screenshots

![image](https://user-images.githubusercontent.com/96680770/147403628-0db01411-f62d-49b0-8b0e-f8cfc5d4affd.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by JonnasD** [comment]
I see now that it is a visual error, the game only show the options of logs if u had that logs in the chest.

**Comment by coolrox95** [comment]
The behavior of only showing logs you have in the bank is intended.
