### ISSUE TITLE
[Spelling/Grammar]: Bank getting started tips page

### ISSUE THREAD

**Issue by ChazTech3030** [MelvorIdle/melvoridle.github.io#1978]
### What text is wrong?

The sentence "The Bank Sidebar - Selecting an item will display the sidebar _will_ all details and actions relating to your item." should possibly read "The Bank Sidebar - Selecting an item will display the sidebar **with** all details and actions relating to your item."

![image](https://user-images.githubusercontent.com/45007570/147416220-7d9308c9-5ebf-4e2b-9ab8-ea0ee8e3a884.png)

### What is the correct spelling or grammar?

"The Bank Sidebar - Selecting an item will display the sidebar **with** all details and actions relating to your item."

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
