### ISSUE TITLE
[Bug]: <mobile sometimes does little to no actions with the app closed>

### ISSUE THREAD

**Issue by randomshotsfired** [MelvorIdle/melvoridle.github.io#1979]
### Describe the bug

There’s been a few times where I start a task before going to sleep and I will gain nothing over night afk 

### Reproduction Steps

Started thieving before closing app and woke up with about 20 minutes of actions done 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Many fixes for various offline progress issues have been released over the last few days. Please ensure you are running at least v1.0.3 (?1843).

Please open a new issue if the problem persists.
