### ISSUE TITLE
[Bug]: One of my goblin raid history is gone and I'm getting weirdly small amount of runes

### ISSUE THREAD

**Issue by nohfly** [MelvorIdle/melvoridle.github.io#1980]
### Describe the bug

I cleared 130-ish wave in goblin raid and purchased 50x Rune pouch.

My raid stat shows that I've purchased 100 raid upgrades so far, yet my record of 130 wave clear is gone and I'm getting smaller amount of runes, even smaller than before the upgrades ! (around 55-500 runes after a wave)

Is there any way to fix the broken rune amounts?

There's no way to use magic with this lower than normal amount of runes.

### Screenshots

<img width="636" alt="스크린샷 2021-12-27 22 19 00" src="https://user-images.githubusercontent.com/34295096/147475558-8aa394f6-1854-45c2-81d5-dc3dc3b61dba.png">

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
