### ISSUE TITLE
[Bug]: Aorpheat's ring doesn't increase GP while thieving

### ISSUE THREAD

**Issue by Nighthawkeye449** [MelvorIdle/melvoridle.github.io#1981]
### Describe the bug

The amount of GP is not increasing while thieving when using Aorpheat's ring. I have tested with and without and the values should theoretically double, but in actuality it never gets above the max GP for the NPC

### Reproduction Steps

1. Start thieving any character
2. Then equip Aorpheat's ring
3. See that the GP never goes above the previous limit (the NPCs max GP limit before equipping the ring)

### Expected behaviour

The GP shoule increase / go above the max for the NPC

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1419

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
The GP bonus of the ring is already factored into the display of the "Show Drops" button. You should be able to see this by viewing the drops with and without the ring equipped.
