### ISSUE TITLE
[Bug]: Summon tablet deduct wrongly when in Synergy

### ISSUE THREAD

**Issue by Blacklotas88** [MelvorIdle/melvoridle.github.io#1985]
### Describe the bug

When using synergy, each attack deducts 2 tablets for both tablets.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
This behavior is intended. You consume 1 of each tablet for the summon attacking, and an additional 1 of each for the synergy being active.
