### ISSUE TITLE
[Bug]: Saves overwriting

### ISSUE THREAD

**Issue by Zeklomontu** [MelvorIdle/melvoridle.github.io#1986]
### Describe the bug

When I do a save with my hardcore character, it will overwrite the save for my standard character, and vice versa. I can reproduce this repeatedly using 2 devices. Cloud save on my hardcore character always overwrites the save for my standard character in the first slot. It is always the same first slot that gets overwritten. I currently have 4 cloud saves and 3 local saves, but it isn't showing save slot number 4, so the last cloud save is considered #5, which is a chaos mode save. This is happening on both local and cloud saves, and did cost a bit of time but nothing too much. However, there is a chance I could lose one of the characters if I don't handle the saves correctly. The characters have different names and are different save types, so not sure what is happening to cause this.

### Reproduction Steps

1. Have 2 devices open. 
2. If my standard character cloud save is currently in slot 1, then performing a cloud save on the hardcore character will place that save in cloud save slot 1.
3. Repeat on opposite character. 

### Expected behaviour

The hardcore character's cloud and local save should be in a separate slot and not overwrite the standard character's saves.

### Which platforms are you experiencing this bug on?

- [x] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
