### ISSUE TITLE
[bug]: Wizard/Knight/craftsman's sigils still say that they will be used in a future update

### ISSUE THREAD

**Issue by RansomTime** [MelvorIdle/melvoridle.github.io#1988]
### Describe the bug

The sigils were introduced with the thieving rework and said that they would be used in a future update. That update has happened but their description still says this

### Reproduction Steps

1. Obtain one of these sigils
2. Check the description text in the bank

### Expected behaviour

A description saying that they are used to make the ring of blade echoes/spirit power and barrage

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Sigil descriptions have been changed to "Used as a Crafting resource.".
