### ISSUE TITLE
Small visual bug (Thieving Mastery)

### ISSUE THREAD

**Issue by xkellam** [MelvorIdle/melvoridle.github.io#199]
This is a small visual bug that I don't believe effects gameplay and probably shouldn't be a high priority due to it's nature. After loading a cloud save, I found that being in my thieving tab, it appeared as though all of my pickpocket NPC options were Mastery level 70.

A link to what that looks like: [http://prntscr.com/s4uasi](http://prntscr.com/s4uasi)

My actual thieving mastery: [http://prntscr.com/s4uf2w](http://prntscr.com/s4uf2w)

I have no idea how to reproduce this or if this is a temporary bug but after refreshing it still looks the same. (all of my pickpocket options have mastery 70.)

I am using version v0.14.2

**Comment by Noctirvia** [comment]
I have the same issue in v0.15.1
https://imgur.com/a/Q71BP5G
