### ISSUE TITLE
[Bug]: <title>Venom Attack Bug

### ISSUE THREAD

**Issue by Mdeb11** [MelvorIdle/melvoridle.github.io#1990]
### Describe the bug

It seems like there is an issue with the accuracy calculation for the venom attack in the spider forest that is making venom unavoidable. I saw that I was taking way too many hits from the regular and brown spider and decided to count the hits of venom. Turned out that it was 22/22 with half of them hitting at 9% chance to hit and the other half hitting at 21% chance to hit. That’s far more than a coincidence. 

### Reproduction Steps

1. Enter spider forest
2. Observe venom hit rate

### Expected behaviour

Venom attack hits 22 times in a row with an effective accuracy of <20%

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
