### ISSUE TITLE
[Spelling/Grammar]: generous resupply

### ISSUE THREAD

**Issue by Adchang** [MelvorIdle/melvoridle.github.io#1991]
### What text is wrong?

![4BB7CB95-39F5-4B9C-B96E-44BB6BC6D711](https://user-images.githubusercontent.com/96801633/147616294-e96aa799-dd3e-4ad1-9ad9-203600a99e6d.jpeg)

### What is the correct spelling or grammar?

Should not have a dollar sign

**Comment by coolrox95** [comment]
Issue is no longer present in latest version of game (v1.0.3).
