### ISSUE TITLE
[Bug]: Weird high contrast bug

### ISSUE THREAD

**Issue by Jorc0** [MelvorIdle/melvoridle.github.io#1992]
### Describe the bug

I don't really know how to explain this bug, screenshots tell everything.
I'm sure it's an android bug and not a Melvor issue.
But I don't really know how to fix it 
Any help its appreciate guys

**I use dark mode but NOT force dark mode.
There's an option on dark mode option that lets you set dark mode per individual app, the problem is that Melvor won't appear there**

### Screenshots

![Screenshot_2021-12-29-02-27-51-812_com malcs melvoridle](https://user-images.githubusercontent.com/48130077/147618869-70b8e44a-e5be-4fbe-a241-452ae0f4da18.jpg)
![Screenshot_2021-12-29-02-27-44-371_com malcs melvoridle](https://user-images.githubusercontent.com/48130077/147618875-7cd8edc0-4f24-4e3f-9cd9-40ffee380969.jpg)
![Screenshot_2021-12-29-02-27-41-162_com malcs melvoridle](https://user-images.githubusercontent.com/48130077/147618882-846fc862-a7a9-4036-a36f-c00090662250.jpg)
![Screenshot_2021-12-29-02-27-37-600_com malcs melvoridle](https://user-images.githubusercontent.com/48130077/147618888-602fff82-0a64-4a4a-b6a2-66fcfc83d16d.jpg)
![Screenshot_2021-12-29-02-24-14-069_com malcs melvoridle](https://user-images.githubusercontent.com/48130077/147618900-64bbab48-0a5f-4bbe-b713-082a33a1f2b6.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is due to Android auto dark mode setting. Please disable auto dark mode for Melvor Idle in your Android app settings.
