### ISSUE TITLE
[Bug]: Game doesn't load on Steam

### ISSUE THREAD

**Issue by Stoo53** [MelvorIdle/melvoridle.github.io#1996]
### Describe the bug

Game doesn't load on Steam, all I see is the 'M' loading symbol. I've verified files and re-installed the game and still experiencing this error.

### Reproduction Steps

1. Click 'play' in Steam

### Expected behaviour

Game is supposed to load

### Screenshots

![image](https://user-images.githubusercontent.com/96823670/147657616-09ebc1e6-075c-43dc-b5a2-000098cbc0ba.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

Unsure as I cannot load game

### Are you using any scripts or extensions?

No

**Comment by xanderput** [comment]
I had this same issue before, I solved it by deleting "%LocalAppData%\Melvor Idle".
