### ISSUE TITLE
[Bug]: Festive Cool Rock

### ISSUE THREAD

**Issue by NuttiesFC** [MelvorIdle/melvoridle.github.io#1998]
### Describe the bug

I completed 2/5 of the Christmas event quests (woodcutting, mining), I had a pop telling me i recieved the Festvie Cool Rock. However it is not showing in my completion log.

### Reproduction Steps

1. Completed mining christmas event quest
2. Completed woodcutting chritmas event quest

### Expected behaviour

Pet to show in the completion log

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by Meekeuk** [comment]
Hiya,

I have the exact same issue with the Festive Cool Rock not appearing in bank after completion of the task.

This has also occurred when I completed the Mining Challenge (Festive Chio) not appearing in my Bank.

Anyone got any ideas?

![Completed](https://user-images.githubusercontent.com/22845317/147779675-4f8f6e7a-ef90-453a-b2df-329b18f53597.jpg)

**Comment by I-Pch** [comment]
Hi @Meekeuk 😊 !

On iPadOS/Chrome, they both didn't appeared in the Bank but only in the Pets Completion Logs 😊 ...

<img width="1155" alt="Festive Chio" src="https://user-images.githubusercontent.com/77828085/147939228-1e5f34eb-8c42-4b7d-ac5d-2a6149353545.png">

**Comment by MelvorIdle** [comment]
This is just a visual bug that existed, you definitely got the Pet when refreshing :)
