### ISSUE TITLE
[Bug]: Dungeon Monsters not affecting slayer

### ISSUE THREAD

**Issue by thekernal** [MelvorIdle/melvoridle.github.io#1999]
### Describe the bug

I have zombies as a slayer task. I fight in the Undead Graveyard (dungeon) and some of the monsters are zombies.  I do not recieve slayer coins  nor does the task decrement.

### Expected behaviour

If the monster in a dungeon is my slayer task then I should get slayer xp.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by IsaacGraham** [comment]
Not a bug. You have to fight them outside of dungeons.
