### ISSUE TITLE
Cannot Cook

### ISSUE THREAD

**Issue by 1liad** [MelvorIdle/melvoridle.github.io#2001]
### Describe the bug

I cannot cook at all anymore since the new cooking updates.

### Reproduction Steps

1. Go to cooking tab
2. Choose recipe
3. Press active cook

### Expected behaviour

Items should start cooking

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [x] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1419

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Cooking has been rewritten as of v1.0.3.
