### ISSUE TITLE
[Bug]: Can't login to cloud on Android but steam login works fine

### ISSUE THREAD

**Issue by cosmicavocado** [MelvorIdle/melvoridle.github.io#2004]
### Describe the bug

When attempting to login to my cloud account on mobile, it says incorrect username and password even though the same username and password works on steam and I have verified as much multiple times. Just in case it was a user error, I tried resetting the password (3 times) but it STILL gives the same error on Android app while working correctly on the steam version.

### Reproduction Steps

1. Open melvor mobile app
2. Enter correct username (IAmCosmicAvocado) and password
3. Get "Incorrect username or password" error even after password reset

### Expected behaviour

I expected to be able to log into my cloud account on both mobile and steam but only steam will let me log in.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
The username you have provided in this bug report does not exist in the Cloud. Can you please confirm you have the correct username used to log into the Cloud?
