### ISSUE TITLE
[Bug]: Character selection screen out of date calculation is comparing the wrong value

### ISSUE THREAD

**Issue by Silberdrachi** [MelvorIdle/melvoridle.github.io#2005]
### Describe the bug

All character selection options seem to be comparing their last update date to the first slot in the cloud options instead of to their individual ones. For example: if you have 1 cloud save, and 2 local saves, if you update the cloud save on the first slot, the 2nd slot on the local save dialog will show as 'out of date' even if it doesnt actually have a cloud save at all. But if you update the 2nd slot to be newer than the cloud save on the first slot, then it shows that it is the most recent, but again it doesnt have a cloud save associated to it.

### Expected behaviour

All cloud saves will compare their last update time to their respective cloud slot. If no cloud save exists for a slot, the comparison will be ignored and nothing will be shown to the user.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
I am unable to reproduce this bug. Are you able to take a recording of the bug?

**Comment by Silberdrachi** [comment]
Nope, not sure how i pulled that off. Maybe something related to having a save locally but not in the cloud. But yeah cant reproduce it now.
