### ISSUE TITLE
[Spelling/Grammar]: including is missing an I

### ISSUE THREAD

**Issue by ddd732** [MelvorIdle/melvoridle.github.io#2006]
### What text is wrong?

![Screenshot_20220101-184402_Melvor Idle](https://user-images.githubusercontent.com/96954918/147857907-09bd1c26-07e5-403a-ad80-9db21bc34b3d.png)
As you can see in the first line of important information, including is spelt without the second I

### What is the correct spelling or grammar?

Including

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
