### ISSUE TITLE
[Bug]: <Doubling offline gains>

### ISSUE THREAD

**Issue by Feldrikk** [MelvorIdle/melvoridle.github.io#2007]
### Describe the bug

I just came across a potential huge bug. I had to close the app while it was loading a save and when I opened it again I received 2 prompts of my offline gains and double the loot I should've gotten. Instead of 150~ egg chests I got 300+, not sure about the exp though

### Reproduction Steps

1. Select a character to load
2. Minimize the app while it's loading the character
3. Reopen after a certain time (I spent more than a minute with the app closed)

### Expected behaviour

It should open 2 prompts showing the afk gains and double the amount of stuff you got. I could not reproduce it again, maybe due to some timing I'm missing but I definitely got double loot while grinding chicken coop.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
