### ISSUE TITLE
[Bug]: Game doesn't progress when PC is put on 'sleep mode'

### ISSUE THREAD

**Issue by fassina2** [MelvorIdle/melvoridle.github.io#2008]
### Describe the bug

I don't tend to turn off my computer just put it to sleep, but the game doesn't seem to run when in sleep mode.

i.e I leave it all night and no XP is gained, no progress is made.

### Reproduction Steps

1 - open melvor pick a skill and let it work on it.
2 - leave melvor open and put your computer to sleep. Click on the power button on windows 10, there are three options one of them is sleep.
3 - do the math on how many resources and xp you should get from the time it was asleep.
4 - turn it on again and compare the results. You'll have gotten nothing.

### Expected behaviour

For the idler to 'run' while the computer was asleep, or to account for it and give me the appropriate resources while that's the case.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [x] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by rakafo** [comment]
yeah that's not a bug, that's just how sleep works - everything is frozen until you turn pc back on. No solution other than to close the game.

**Comment by fassina2** [comment]
Why was this closed ? Of course it should be fixable, you just need to run a check by looking at the time and date, the same way you'd do when offline. I didn't reply to this rakafo dude because I thought he was some rando..

**Comment by Furrypaw** [comment]
It works fine on phone if you tab out of the game, should be detectable on pc. You can check if time changed on pc etc.
