### ISSUE TITLE
[Bug]: Multi-Purchase Gives Incorrect Charges

### ISSUE THREAD

**Issue by xwrije** [MelvorIdle/melvoridle.github.io#2009]
### Describe the bug

When buying Mining Gloves with the ‘x10’ option (in other words multi-purchasing,) it charges your account the expected 750,000GP but it only adds 1 glove (worth 5,000 charges) to your bank.

### Reproduction Steps

1. Go to ‘Shop.’
2. Navigate to ‘Gloves.’
3. Change your purchase amount to x10.
4. Purchase the ‘Mining Gloves’ and confirm.
5. Open the sidebar and see 750K GP missing.
6. Navigate to ‘Bank.’
7. See the incorrect amount of gloves.
8. Navigate to ‘Mining’ and equip the gloves.
9. Confirm the incorrect amount of charges.

### Expected behaviour

When I’m charged 750,000GP when multi-purchasing Mining Gloves in the x10 quantity, I expect it to give me a total of 10 gloves worth 50,000 charges.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Glove charges are attached to one single glove. You only get 1 glove, but when you equip them you will see that you have all the charges you purchased.
