### ISSUE TITLE
Stops firemaking

### ISSUE THREAD

**Issue by DylanvdHurk** [MelvorIdle/melvoridle.github.io#201]
**Describe the bug**
Whenever I come back after a while the game while have stopped firemaking. Doesn't matter if I choose the local or cloud save, it will have stopped firemaking after a while. It will also unselect the log i had up.

**To Reproduce**
1. Start firemaking
2. Leave site for like 30 minutes.
3. Come back and choose either cloud or local save

**Expected behavior**
All the time I was away I should have gotten XP from.

**Screenshots**

**Browser**
Google Chrome V81.0.4044.122

**Console output**
Please open the console by pressing F12 and copy it here.

**Comment by amccollister** [comment]
To expand upon this, firemaking will stop if you didn't select a log in that active session.

If you selected a log and click burn, it will be earning XP while away.
If you loaded a session and firemaking is active and you refresh, the firemaking stops.

Hope this helps!
