### ISSUE TITLE
[Bug]: Dragonfire Shield upgrade view hitpoint for non-adventure mode

### ISSUE THREAD

**Issue by LasseSimonsen** [MelvorIdle/melvoridle.github.io#2010]
### Describe the bug

The upgrade description of Dragonfire Shield is +30 Maximum Hitpoint. In adventure mode, it should be +300

### Reproduction Steps

1. Play in Adventure Mode
2. Get "(G) Ancient Shield"
2. Select "(G) Ancient Shield" in bank
3. Click "Upgrade Item"
4. Read "Created by Patreon (Michael7050) Passive: +30 Maximum Hitpoints"

### Expected behaviour

I expected to read: "Created by Patreon (Michael7050) Passive: +300 Maximum Hitpoints".
Note: As I have yet to upgrade the item, I do not know if this is purely an information bug or if it is also effective.

### Screenshots

![Screen-1-2-2022_111445_AM](https://user-images.githubusercontent.com/34742784/147872779-8af50b77-5c12-4460-8d72-18651e676aae.png)

### Console output

Indlæsning mislykkedes for <script> med kilden "https://melvoridle.com/assets/js/game/languageJSON.js?1419". index_noads.php:2974:1
Connected to PlayFab successfully cloud.js:71:416
Removed old local storage keys. save.js:10:104
set force reload to 0 save.js:70:60
Combat Manager Built... combatManager.js:1:912
Golbin Raid Manager Built... raidManager.js:1:996
Removed old local storage keys. save.js:10:104
Loading Save Game... save.js:15:29
Save Game Loaded... save.js:15:140
Game Loaded main.js:6:477
MICSR: setting up SimEnemy MICSR.js:26:31
MICSR: setting up util MICSR.js:26:31
MICSR: setting up CombatData MICSR.js:26:31
MICSR: AgilityCourse is waiting for modifierNames MICSR.js:26:31
MICSR: AgilityCourse is waiting for Card MICSR.js:26:31
MICSR: setting up DataExport MICSR.js:26:31
MICSR: setting up Card MICSR.js:26:31
MICSR: setting up modifierNames MICSR.js:26:31
MICSR: unknown modifier increasedGPFromFiremaking modifierNames.js:655:25
MICSR: unknown modifier decreasedGPFromFiremaking modifierNames.js:655:25
MICSR: no non-existent modifiers detected! modifierNames.js:655:25
MICSR: setting up Menu MICSR.js:26:31
MICSR: setting up Consumables MICSR.js:26:31
MICSR: setting up Import MICSR.js:26:31
MICSR: setting up Plotter MICSR.js:26:31
MICSR: setting up TabCard MICSR.js:26:31
MICSR: setting up Loot MICSR.js:26:31
MICSR: main is waiting for App MICSR.js:26:31
MICSR: setting up SimManager MICSR.js:26:31
MICSR: Simulator is waiting for SimPlayer MICSR.js:26:31
MICSR: setting up SimPlayer MICSR.js:26:31
MICSR: App is waiting for AgilityCourse MICSR.js:26:31
MICSR: App is waiting for Simulator MICSR.js:26:31
Connected to PlayFab successfully cloud.js:71:416
MICSR: setting up AgilityCourse MICSR.js:26:31
MICSR: setting up Simulator MICSR.js:26:31
MICSR: setting up App MICSR.js:26:31
PlayFab Connected: Zupermannd cloud.js:72:98
MICSR: setting up main MICSR.js:26:31
Combat Manager Built... combatManager.js:1:912
MICSR: Melvor Idle Combat Simulator Reloaded v1.6.2 loaded. MICSR.js:26:31
Synchronising with Cloud cloud.js:13:109

​

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

V1.0.1 (?1419)

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue is no longer present in latest version of game (v1.0.3)
