### ISSUE TITLE
[Bug]: Firemaking item mastery doesn't change burn interval

### ISSUE THREAD

**Issue by csavage6** [MelvorIdle/melvoridle.github.io#2013]
### Describe the bug

I've noticed that my Redwood Log burn interval has not changed since I started it. with the 25% Firemaking milestone included (-10% burn interval) and my Redwood logs currently at 83 mastery, I should be sitting at about 12.25s (-18.3%) for the burn interval, however, it is sitting at 13.45s.

### Reproduction Steps

Go to Firemaking
Calculate your burn interval reduction based on tooltip
Verify if it matches log burn time

### Expected behaviour

Expected reduction with only 0.1% per level reduction: 8.3% = 15s(0.083) = 1.245s reduction = 15 - 1.245 = 13.755s

Expected reduction with only 10% mastery: 15s(0.10) = 1.5s reduction = 13.5s

Expected combined reduction: 1.245s + 1.5s = 2.745s = 12.255s @ level 83.

Current reduction = 1 - 13.45/15 = 0.1034 = 10.34% 

### Screenshots

![image](https://user-images.githubusercontent.com/60151340/147955309-644e2840-b45e-4848-b7a3-e5f1baadc1d5.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by B0TFR4NK** [comment]
If  you refresh it fixes it; obviously not a permanent fix, but a temporary one you can use.

**Comment by csavage6** [comment]
Refresh what? I'm on steam.

**Comment by jpreed00** [comment]
I see the bug, too.  It appears like some interval bonus is being applied (I used a stopwatch app to time the burns), the UI just isn't updating unless you exit and re-enter the game (on steam).

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
