### ISSUE TITLE
Getting Coal When Burning Logs

### ISSUE THREAD

**Issue by Fangrend** [MelvorIdle/melvoridle.github.io#2015]
### Describe the bug

When burning normal logs if you look at your bank you start to earn coal as if mining. you dont earn any exp for the coal just the item. You still burn the log in the process

### Reproduction Steps

burn normal log under fire making
go to bank
start to earn coal

### Screenshots

![Coal Bug](https://user-images.githubusercontent.com/97061635/147978343-2713687b-a643-47f1-903c-3760ab306043.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by I-Pch** [comment]
Hi @Fangrend 😊 ... I think, per the wiki that this is the expected behavior when [Firemaking](https://wiki.melvoridle.com/w/Firemaking) : 

> Burning a log has a 40% chance to give one [Coal Ore](https://wiki.melvoridle.com/w/Coal_Ore).
