### ISSUE TITLE
Item alchemy 2 not giving correct value

### ISSUE THREAD

**Issue by Liftyz** [MelvorIdle/melvoridle.github.io#2016]
### Describe the bug

Using item alchemy 2 on magic logs is only giving me 420gp per log instead of 600gp.

### Expected behaviour

Should be getting 600gp per magic log.

### Screenshots

![sketch1641272452393](https://user-images.githubusercontent.com/97079558/148012337-0e137612-b9e9-4043-b8f8-e65d4756ab94.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by IsaacGraham** [comment]
Not a bug. You have the woodcutting mastery pool checkpoint that increases the _sell price_ of logs, but that does not affect the base price used for alchemy. The base value of the log is 400, so you must have a 5% global gp item equipped such as sneak-ers.

**Comment by Liftyz** [comment]
Ah that makes sense. Sorry still getting used to all the facets of melvor. Closing this issue now. Thank you 🙏
