### ISSUE TITLE
[Bug]: Location of the number of equipped tablets/familiars in the Equipment (Right slot) seems off

### ISSUE THREAD

**Issue by I-Pch** [MelvorIdle/melvoridle.github.io#2017]
### Describe the bug

As the title says (😇 ), it seems like the number indicating how many tablets/familiars are in the right slot of the equipment "menu" (from the Top Bar)/section in the Combat page is placed a little bit too far on the right (compared to the number for the left slot).

I first saw this on my iPad but it seems like this visual bug also appears in Chrome but with a few differences : 
- **iPad** : The visual bug is consistent. The number of tablets/familiars is too far on the right in the Equipment "Menu" (accessed through the "Helmet Icon" in the Top Bar) and in the Equipment Section/Tab on the Combat page. In both cases, the Synergy "Icon" seems to be centered.
- **Chrome**: The visual bug is only visible in the Equipment "Menu" (Top Bar) and the Synergy "Icon" seems centered but in the Equipment Section/Tab on the Combat page, if the number of tablets/familiars seems to be where it should, either the whole left slot (the slot + number) is too far on the right or the whole right slot (slot + number) is too far on the right (as the Synergy icon doesn't seem centred in that case...)      

### Screenshots

**iPad Screenshots : `Combat Page > Equipment Tab`** 

![IMG_0248](https://user-images.githubusercontent.com/77828085/148027463-3d457a5e-8bc0-4965-a810-c72e2bd461a2.jpg)  

![IMG_0249](https://user-images.githubusercontent.com/77828085/148027487-f72a6260-8289-4d6a-ad63-3c39a8902f46.jpg)

**iPad Screenshot : `Top Bar > Helmet > Equipment`**

![IMG_0250](https://user-images.githubusercontent.com/77828085/148027626-b198710a-57b0-4697-9f6e-fef9d6e216db.jpg)

--- 
**Chrome Screenshot : `Combat Page > Equipment Tab`** 
 
<img width="273" alt="Tablets-Familiars" src="https://user-images.githubusercontent.com/77828085/148027840-4ea77b71-f2d0-463e-aa39-d0f12e5ffb2e.png">

**Chrome Screenshot : `Top Bar > Helmet > Equipment`**

<img width="318" alt="Equipment Modal" src="https://user-images.githubusercontent.com/77828085/148028137-c6c9020c-4a5d-435e-b516-6587fb4c33a8.png">

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
