### ISSUE TITLE
[Bug]: Slayer reupplies rejected due to bank space

### ISSUE THREAD

**Issue by IsaacGraham** [MelvorIdle/melvoridle.github.io#2018]
### Describe the bug

When purchasing a slayer resupply, it appears to check your current bank space used, and determine if it can place all 5 items in there by that value alone. This does not take into account that you may also have some or all of those items in your bank. For instance, I was at 102/106 while testing this, with rune arrows, ruby bolts, light runes, and sharks all in my bank. I could not purchase the resupply due to a "full" bank.

Please see this gif for demonstration: https://gfycat.com/shoddysatisfieditalianbrownbear

Extensions active shouldn't affect this, but for reference:
![image](https://user-images.githubusercontent.com/5593732/148037940-4a6444e7-0879-4fd5-97ec-76368180f83c.png)

### Reproduction Steps

1: Have fewer than 5 available bank slots
2: Ensure you have placeholders for enough items from the slayer resupply that buying it wouldn't bring you over the limit
3: Try to purchase slayer resupply

### Expected behaviour

It should check whether the placeholders exist and take them into account when determining if the bank can hold the items from the purchase.

### Screenshots

https://user-images.githubusercontent.com/5593732/148037756-23c05437-021c-42ec-bf38-67f544c91b4d.mp4

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

Yes

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
