### ISSUE TITLE
[Bug]: Herblore mastery displayed incorrectly

### ISSUE THREAD

**Issue by iregalia** [MelvorIdle/melvoridle.github.io#2019]
### Describe the bug

Have 100% mastery completion for Herblore, but it is displaying as 99.97% in the completion log.

### Reproduction Steps

1. Max herblore mastery for each item.
2. Check completion log

### Expected behaviour

Mastery shows 99.97% for Herblore instead of 100%

### Screenshots

![Mastery12](https://user-images.githubusercontent.com/43871587/148051160-fd764a1f-5b97-4ef1-be6a-174cbc799688.png)
![Mastery2](https://user-images.githubusercontent.com/43871587/148051166-387a4c83-b6e7-4e08-a7f7-ddc768e65443.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

Yes

**Comment by iregalia** [comment]
Issue fixed after restarting game, not sure if its worth looking into.

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.0.2. Please open a new ticket if this is not the case.
