### ISSUE TITLE
Enemy Hitpoints don't update when reflect damage is dealt to them

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#202]
**Describe the bug**
When using the Gold Sapphire Ring, the enemy hitpoints do not update when they take reflect damage.

**To Reproduce**
1. Equip the gold sapphire ring,
2. Fight a monster.
3. Enemy hits trigger reflect damage, but their hitpoints don't visually update.

**Expected behavior**
Enemy hitpoint bar should shrink and hitpoints number should decrease when they take reflection damage.

**Screenshots**
![image](https://user-images.githubusercontent.com/58208131/80294291-68340200-8725-11ea-852c-35be32f58713.png)

Seems like the hp update was commented out in the code. Un-commenting it seems to function correctly.

**Comment by MelvorIdle** [comment]
Fixed in v0.15
