### ISSUE TITLE
[Bug]: <Bob's Gloves don't work correctly>

### ISSUE THREAD

**Issue by B0TFR4NK** [MelvorIdle/melvoridle.github.io#2020]
### Describe the bug

When harvesting, Bob's Gloves are supposed to have a 25% chance to preserve compost or weird gloop. However when I have been using harvest all the weird gloop doesnt seem to retain for any plots. Maybe I was very unlucky, but I would think that after 20+ harvests one type of crop, or at least one plot would retain the gloop.

### Reproduction Steps

1. Go to Farming page
2. Equip Bob's Gloves
2. Apply weird gloop to all crops
3. Plant all crops
4. wait
5. Harvest all crops

### Expected behaviour

When harvesting all crops I expect some crops to retain the weird gloop, or 25% of the time when I harvest all for a type of crop they retain their weird gloop.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by IsaacGraham** [comment]
That effect only applies when you also have Bob's Rake equipped. Gloves by themselves just give you +3% farming yield.

**Comment by B0TFR4NK** [comment]
Man.... Reading is hard, I read it like 5 times and my brain kept saying with gloves not rake
Ty
