### ISSUE TITLE
[Bug]: Holding enter when ending Bane fight causes the new area debuff to apply multiple times

### ISSUE THREAD

**Issue by sonicdm** [MelvorIdle/melvoridle.github.io#2021]
### Describe the bug

I was finishing up a fight against Bane. I was holding down enter to eat through the suffocate. I held it as Bane was killed. It immediately closed the popup to choose the debuff. I looked at the modifiers and it showed the same modifier about 15 times. Leading to a .25 second attack interval.. 

### Reproduction Steps

1. battle bane
2.  hold enter to eat as the fight ends

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of the v1.0.3 update.
