### ISSUE TITLE
[Bug]: Astrology Actions Stop On Full Bank

### ISSUE THREAD

**Issue by foxypls** [MelvorIdle/melvoridle.github.io#2023]
### Describe the bug

Astrology stops on full bank, I assume when receiving a dust drop, despite ignore full bank being toggled. Offline progress works as intended but not while online.

### Reproduction Steps

1. Import https://melvoridle.com/save/Y5bPLAoM
2. Wait for astrology to stop training. This will be accompanied with a Bank is full notification.

### Expected behaviour

Astrology actions should continue without issue.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by foxypls** [comment]
Doesn't work cooking shrimp either. Stops on a non-burnt action.

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.0.2. Please open a new ticket if this is not the case.
