### ISSUE TITLE
[Bug]: Arch/Plasma; game launches on leftmost monitor

### ISSUE THREAD

**Issue by Surobaki** [MelvorIdle/melvoridle.github.io#2027]
### Describe the bug

Hi,
Please see below for a `neofetch` dump to see my OS setup and my `xrandr` display configuration. I've tried reproducing this with both Steam native and runtime. I've tried doing this while having Google Chrome and other Electron-based apps except Discord open and closed.

Every time I launch the game it launches on my leftmost monitor and does not remember the last position / geometry. I have a dual monitor setup running from a laptop with my laptop screen disabled. My primary monitor is on the right side, my secondary monitor is on the left side. I have inspected solutions for other apps doing this in KDE Plasma and most people point to solving this with turning the options **"Active screen follows mouse"** and **"Separate screen focus"** on, and while this did help with apps like Konsole and Dolphin, Melvor is still doing it. I noticed that this happens with Bitburner too, which is another Electron-based idle game, so I'm considering putting this issue upstream. I haven't managed to find a similar issue in Electron's repository.

Thank you.

`xrandr`
```
Screen 0: minimum 8 x 8, current 4000 x 2560, maximum 32767 x 32767
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 connected (normal left inverted right x axis y axis)
   1920x1080     60.02 +
   640x480       59.94  
HDMI-0 connected 1440x2560+0+0 right (normal left inverted right x axis y axis) 609mm x 349mm
   2560x1440     59.95*+
   1920x1200     59.88  
   1920x1080     60.00    59.94    50.00    60.00    50.04  
   1680x1050     59.95  
   1600x900      60.00  
   1440x900      59.89  
   1440x480      59.94  
   1280x1024     60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       59.94    59.93  
DP-3 connected primary 2560x1440+1440+560 (normal left inverted right x axis y axis) 609mm x 349mm
   2560x1440     59.95*+
   1920x1080     60.00    59.94    50.00  
   1680x1050     59.95    59.88  
   1600x900      60.00  
   1440x900      59.90    59.89  
   1440x480      59.94  
   1366x768      59.79  
   1280x1024     60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1024x768      60.00  
   800x600       60.32  
   720x480       59.94  
   640x480       59.94    59.93  
DP-4 disconnected (normal left inverted right x axis y axis)
```
`neofetch`
```
OS: Arch Linux x86_64 
Kernel: 5.15.12-arch1-1 
Packages: 1525 (pacman) 
Shell: zsh 5.8 
Resolution: 1440x2560, 2560x1440 
DE: Plasma 5.23.4 
WM: KWin 
Terminal: alacritty 
Terminal Font: black: '0x1c1c1c' 
CPU: Intel i7-7700HQ (8) @ 3.800GHz 
GPU: NVIDIA GeForce GTX 1060 Mobile 6GB 
Memory: 7232MiB / 15958MiB 
```

### Reproduction Steps

1. Turn on Melvor Idle

### Expected behaviour

The application opens either:
1. at the same position where it was closed last time,
2. around the location of the mouse cursor,
3. anywhere on the monitor where the mouse is.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
