### ISSUE TITLE
[Bug]: Sorting removes sales-mode highlight, but item(s) still selected for selling

### ISSUE THREAD

**Issue by harrisi** [MelvorIdle/melvoridle.github.io#2028]
### Describe the bug

Sell item borders are removed if bank is sorted, but items are still able to be sold.

Appending `itemsToSell.map(item => updateItemToSellBorder(item))` to `loadBank` fixes this. Somewhere else may be better.

### Reproduction Steps

1. Go to bank
2. Toggle sell mode
3. Select an item
4. Sort bank

### Expected behaviour

Selected items should still be highlighted.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [X] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
