### ISSUE TITLE
Wizard Chest Bug

### ISSUE THREAD

**Issue by JacksonEpstein** [MelvorIdle/melvoridle.github.io#203]
**Describe the bug**
I tried to open my 9 wizard chests, and idk what happened but it somehow opened 3087 of them.

Edit: Just noticed that all my big bones are gone now. I believe I might have have 3087 of them. I think it somehow used all my big bones instead of the chests. But gave me all the chest rewards?

**To Reproduce**
I think what happened is I had the bug were the menu to open them was stuck open, then I clicked quick sort to move them, then I clicked open all and it happened.

![image](https://user-images.githubusercontent.com/60408647/80321842-c0c6d600-87dd-11ea-8a90-c537922de80f.png)

**Comment by MelvorIdle** [comment]
Potentially fixed in v0.15
