### ISSUE TITLE
[Bug]: Leprechaun + Pig not working

### ISSUE THREAD

**Issue by esso23** [MelvorIdle/melvoridle.github.io#2030]
### Describe the bug

I have Leprechaun + Pig equipped and I am thieving The Chef, but with each successful thieving attempt only 1 Leprechaun tablet is used (and 0 Pig marks).
Leprechaun mark is Level 4 (maxed), Pig mark is Level 3 (19 / 31).

### Reproduction Steps

Leprechaun mark level 4
Pig mark level 3 (19 / 31)
Summoning 74
Thieving 99, Chef mastery 87, 591 Stealth vs 350 Perception

### Expected behaviour

As with other synergies, every time i pickpocket Chef, 2 Leprechaun marks and 1 Pig mark should be consumed.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by C-Flare** [comment]
I am having the same issue. I will expand on this by saying that on a FAILURE, 1 Leprechaun and 1 Pig tablet gets consumed. On a SUCCESS 1 Leprechaun tablet gets consumed and 0 Pig tablets. I am playing on v1.0.1 (?1419), on Steam with Combat Sim, and SEMI for extensions.

**Comment by cassiohmp** [comment]
Exactly the same problem here. Leprechaun lvl 4 and Pig lvl 3, only leprechaun being consumed

https://user-images.githubusercontent.com/44931570/151875225-58359e0a-9957-461a-8429-257590de29f1.mp4
