### ISSUE TITLE
[Bug]: Adding an apostrophe to a character name will cause issues with character selection

### ISSUE THREAD

**Issue by FlatGirlAbs** [MelvorIdle/melvoridle.github.io#2032]
### Describe the bug

On the Character Select Screen, I can't interact with my Adventure Mode character's settings button. 
3 other characters work fine.
I even tried switching to a different browser, and to Android. Same thing is happening there

Whenever I click the Settings button, the line "index_noads.php:1 Uncaught SyntaxError: missing ) after argument list"
appears in my console

### Screenshots

![Melvor Settings Bug](https://user-images.githubusercontent.com/97244775/148416211-53df94a2-faff-4269-ab9e-29a0b6926b7f.JPG)

Attached is the problem character

### Console output

Failed to load resource: the server responded with a status of 404 ()
languageJSON.js:1 Failed to load resource: the server responded with a status of 404 ()
languageJSON.js:1 Failed to load resource: the server responded with a status of 404 ()
cloud.js?1419:71 Connected to PlayFab successfully
style.css:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
index_noads.php:1 Uncaught SyntaxError: missing ) after argument list

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1419

### Are you using any scripts or extensions?

No

**Comment by FlatGirlAbs** [comment]
Turns out the ' in my character's name was breaking the button. Removed it and now it's working fine

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
