### ISSUE TITLE
[Bug]: Bank sorting not persisting

### ISSUE THREAD

**Issue by RStivanson** [MelvorIdle/melvoridle.github.io#2034]
### Describe the bug

When choosing a different bank sorting method. Upon saving and exiting the game, the chosen method is not saved. The bank sorting method always reverts to "Default Sorting" upon reloading the character. It does not matter which sorting method was picked. 

### Reproduction Steps

1. Go to 'Bank'
2. Open the 'Bank Settings'
3. Change the 'Default Bank Sort' to any value other than 'Default Sorting', the current value will reflect whatever value is chosen
4. Click on 'Force Save'
5. Click the Character dropdown, in the top-right, and click on 'Select Character'
6. Reselect the same character to reload your save
7. Go to 'Bank'
8. Open the 'Bank Settings'
9. 'Default Bank Sort' current value will be 'Default Sorting' again

### Expected behaviour

I expect the selected bank sorting method to persist through character loads.

### Screenshots

![image](https://user-images.githubusercontent.com/24880317/148535428-a8be4c5a-d9be-43e9-b35f-9dd64ed21dae.png)

### Console output

![image](https://user-images.githubusercontent.com/24880317/148536545-8bf4ea18-6554-49ab-8e28-eb3eaad8e68e.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
