### ISSUE TITLE
[Bug]: Steam client will not load a character to play.

### ISSUE THREAD

**Issue by Urface716** [MelvorIdle/melvoridle.github.io#2035]
### Describe the bug

The steam client will not load a save file to begin playing, Both cloud saves and local saves are visible to be loaded, but upon selecting any of them the circular loading animation starts and the client does nothing, the load continues at infinitum. I have tried uninstalling/reinstalling, verifying game files, and restarting my computer, none have helped in any combination.

### Reproduction Steps

Start client, attempt to load character.

### Expected behaviour

Save file would load to allow me to play the game.

### Screenshots

![Bug](https://user-images.githubusercontent.com/97299562/148562828-cc7bfc06-13f3-4156-a991-5620896d864b.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

I don't know, won't load a save to get the sidebar to check, but I assume newest.

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
You can follow these steps to reset the client. This will delete your local saves and log you out of the cloud:

Delete everything in this folder
`C:\Users\YOUR_USERNAME\AppData\Local\Melvor Idle\User Data`

Then load the game and everything will be reset.
