### ISSUE TITLE
[Bug]: Memory leak on Steam client

### ISSUE THREAD

**Issue by esso23** [MelvorIdle/melvoridle.github.io#2036]
### Describe the bug

I am playing Standard/Adventure/HC games simultaneously, so I have 3 local saves and during the day I often switch between them without turning off the (Steam) client. Over time, the memory usage goes from ~250MB when launched to several gigabytes (maximum I've seen is 3GB - at that point I restarted the client).

My pattern when switching from one save to another:
1. Force save
2. Top-right menu -> Select character
3. Load another save from local saves

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1419

### Are you using any scripts or extensions?

No

**Comment by Jaex** [comment]
I also have same problem and I'm using 3 profiles exactly like you too.

![](https://jaex.getsharex.com/2022/01/Taskmgr_t9C8zMUEWA.png)

**Comment by I-Pch** [comment]
Hi @esso23 and @Jaex 😊 ...

Not sure if this would be helpful but there's a pinned topic on the steam community about this : https://steamcommunity.com/app/1267910/discussions/0/3076503022315164741/

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
