### ISSUE TITLE
[Bug]: Elemental potion output not considered while runecrafting offline

### ISSUE THREAD

**Issue by SimplyBLGDev** [MelvorIdle/melvoridle.github.io#2038]
### Describe the bug

While runecrafting offline the elemental runes outputted from the use of elemental potions will not be used to continue crafting, it is thus possible to 'run out of materials while crafting' even though the output from the elemental potions could be used to continue the activity.

### Reproduction Steps

1. Leave a character runecrafting composed runes (such as a lava rune) while offline with elemental potions equipped.

### Expected behaviour

When reloading the game you'll receive the output from the runecrafting as well as the elemental runes from the potions, the runecrafting will have stopped due to lack of resources even though the potion's production could've continued it.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.0.3.
