### ISSUE TITLE
[Bug]: <Force Save button usable/Successful cloud save pop-up even when logged out of cloud>

### ISSUE THREAD

**Issue by karlmelvor** [MelvorIdle/melvoridle.github.io#2039]
### Describe the bug

I was able to use the force save button successfully and the "successful cloud save" pop up appeared even though I had been logged out of the cloud account involuntarily. 

I was using a single device so i have no idea if the cloud save feature was working or uploading the save (highly unlikely) 

I was able to successfully sign in when i realized that i was logged out.

i expected it to be an extension issue but the same thing happens on a different browser (edge, chromium) without any extensions 

![unknown](https://user-images.githubusercontent.com/97378741/148672757-a0aee0d8-b921-4a4f-9e74-f8bacd41a550.png)

### Expected behaviour

When logged out I expected the force save button to say "unable to connect to cloud" ( afaik it used to turn red ) and not show the   Cloud save successful popup

### Screenshots

![image](https://user-images.githubusercontent.com/97378741/148672936-67022318-5fa4-45de-a9ff-cd5a42978177.png)
![image](https://user-images.githubusercontent.com/97378741/148672944-087527b8-9493-4280-a3b5-743273681627.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is not a bug. PlayFab is the provider used for Cloud saves. If you are authenticated with them, cloud saving will work as normal.

Melvor Cloud is a separate authentication which you have been logged out of.
