### ISSUE TITLE
Ofline Herblore tier doesn't increase

### ISSUE THREAD

**Issue by p1zz4eater** [MelvorIdle/melvoridle.github.io#204]
**Describe the bug**
When ofline and creating a potion, the tier increases but doesn't actually add that tier portion to your inventory.

**To Reproduce**
1. Start creating a potion
2. Go ofline and leave the potions to be created

**Expected behavior**
I expected that as the mastery increases and the tier of the potions increases, the appropriate tier should get added to the inventory and not whichever tier you had when you started creating potions

**Browser**
Most up to date version of the Android Melvor Idle app as of 27th April 2020

**Console output**
N/A

**Comment by MelvorIdle** [comment]
This is intentional. Offline mastery experience is added upon loading offline progression. Then you unlock the mastery benefits that come with it and continue as normal.
