### ISSUE TITLE
[Bug]: "+x% Chance to Double Items when Crafting Armor" Astrology Buff Not Working

### ISSUE THREAD

**Issue by JinNada** [MelvorIdle/melvoridle.github.io#2041]
### Describe the bug

When having the Hyden Astrology buff to double armor, the buff is neither displayed nor applied to the applicable Crafting items.  Tested on alt account with no base doubling chance and +15% chance to double from Astrology.

[Previous bug report titled that it's just not displaying properly](https://github.com/MelvorIdle/melvoridle.github.io/issues/1872)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by EATOATS** [comment]
I also encountered this bug. Android app.

**Comment by coolrox95** [comment]
Issue was fixed as of the v1.0.3 update.
