### ISSUE TITLE
[Bug]: Web/app: Fletching Arrow Shafts will switch UI to Normal Logs on focus

### ISSUE THREAD

**Issue by meesha7** [MelvorIdle/melvoridle.github.io#2042]
### Describe the bug

A UI bug that will switch to Normal Logs even though the player is fletching from other logs.

### Reproduction Steps

1. Start fletching Arrow Shafts with anything other Normal Logs (for example Oak Logs)
2. Switch the tab or put the app to the background
3. Return to the tab/app
4. Fletching will show the Normal Logs recipe, although the crafting continues from previously selected logs
5. Switch to the original logs again -> fletching will interrupt

### Expected behaviour

The game should continue where left - on the selected logs, not switch to Normal Logs

### Screenshots

![image](https://user-images.githubusercontent.com/44530786/148738000-b79f0114-1353-443a-bb59-5302d5ccc573.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue was fixed as of v1.0.3.
