### ISSUE TITLE
[Bug]: <Puff not triggering after multiple days of smithing Dragon Javelin heads>

### ISSUE THREAD

**Issue by tbauer254** [MelvorIdle/melvoridle.github.io#2045]
### Describe the bug

Been mainlining dragon heads to try and get puff to trigger, it's been about a week so far back and forth between alt. Magic and Smithing and I can't get Puff to trigger

### Expected behaviour

By now I'd assume the pet would activate like it has for other skills. I'm 99 on everything at this point, but I'm trying to get all of the pets triggered.

### Console output

style.css:1 Failed to load resource: the server responded with a status of 404 ()
languageJSON.js:1 Failed to load resource: the server responded with a status of 404 ()
cloud.js?1419:71 Connected to PlayFab successfully
save.js?1419:70 set force reload to 0
combatManager.js?1419:1 Combat Manager Built...
raidManager.js?1419:1 Golbin Raid Manager Built...
save.js?1419:15 Loading Save Game...
save.js?1419:15 Save Game Loaded...
main.js?1419:6 Game Loaded
cloud.js?1419:71 Connected to PlayFab successfully
5cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:71 Uncaught TypeError: Cannot read properties of null (reading 'data')
    at cloud.js?1419:71
    at XMLHttpRequest.xhr.onerror (PlayFabClientApi.js:112)
cloud.js?1419:71 Uncaught TypeError: Cannot read properties of null (reading 'data')
    at cloud.js?1419:71
    at XMLHttpRequest.xhr.onloadend (PlayFabClientApi.js:103)
e3855.playfabapi.com/Client/GetTitleData?sdk=JavaScriptSDK-1.93.210927:1 Failed to load resource: net::ERR_INTERNET_DISCONNECTED
PlayFabClientApi.js:122 Uncaught (in promise) Object
cloud/ping.php:1 Failed to load resource: net::ERR_INTERNET_DISCONNECTED
2cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:71 Connected to PlayFab successfully
2cloud.js?1419:13 Synchronising with Cloud
game.js?1419:28 Took 0.0315s to process 354802 ticks. 0.0000887819121650949ms per tick.
cloud.js?1419:71 Uncaught TypeError: Cannot read properties of null (reading 'data')
    at cloud.js?1419:71
    at XMLHttpRequest.xhr.onerror (PlayFabClientApi.js:112)
cloud.js?1419:71 Uncaught TypeError: Cannot read properties of null (reading 'data')
    at cloud.js?1419:71
    at XMLHttpRequest.xhr.onloadend (PlayFabClientApi.js:103)
e3855.playfabapi.com/Client/GetTitleData?sdk=JavaScriptSDK-1.93.210927:1 Failed to load resource: net::ERR_INTERNET_DISCONNECTED
PlayFabClientApi.js:122 Uncaught (in promise) Object
cloud/ping.php:1 Failed to load resource: net::ERR_INTERNET_DISCONNECTED
4cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:71 Connected to PlayFab successfully
9cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:71 Connected to PlayFab successfully
8cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:71 Connected to PlayFab successfully
8cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:71 Connected to PlayFab successfully
2cloud.js?1419:13 Synchronising with Cloud
game.js?1419:28 Took 0.203s to process 748744 ticks. 0.00027112070347141347ms per tick.
4cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:71 Uncaught TypeError: Cannot read properties of null (reading 'data')
    at cloud.js?1419:71
    at XMLHttpRequest.xhr.onerror (PlayFabClientApi.js:112)
cloud.js?1419:71 Uncaught TypeError: Cannot read properties of null (reading 'data')
    at cloud.js?1419:71
    at XMLHttpRequest.xhr.onloadend (PlayFabClientApi.js:103)
e3855.playfabapi.com/Client/GetTitleData?sdk=JavaScriptSDK-1.93.210927:1 Failed to load resource: net::ERR_INTERNET_DISCONNECTED
PlayFabClientApi.js:122 Uncaught (in promise) Object
cloud/ping.php:1 Failed to load resource: net::ERR_INTERNET_DISCONNECTED
cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:71 Connected to PlayFab successfully
8cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:71 Connected to PlayFab successfully
2cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:71 Uncaught TypeError: Cannot read properties of null (reading 'data')
    at cloud.js?1419:71
    at XMLHttpRequest.xhr.onerror (PlayFabClientApi.js:112)
cloud.js?1419:71 Uncaught TypeError: Cannot read properties of null (reading 'data')
    at cloud.js?1419:71
    at XMLHttpRequest.xhr.onloadend (PlayFabClientApi.js:103)
e3855.playfabapi.com/Client/GetTitleData?sdk=JavaScriptSDK-1.93.210927:1 Failed to load resource: net::ERR_INTERNET_DISCONNECTED
PlayFabClientApi.js:122 Uncaught (in promise) Object
cloud/ping.php:1 Failed to load resource: net::ERR_INTERNET_DISCONNECTED
cloud.js?1419:13 Synchronising with Cloud
game.js?1419:28 Took 0.18020000004768372s to process 619393 ticks. 0.00029092999121346823ms per tick.
3cloud.js?1419:13 Synchronising with Cloud
game.js?1419:28 Took 0.16610000002384187s to process 446230 ticks. 0.0003722295677651477ms per tick.
cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:71 Connected to PlayFab successfully
8cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:71 Connected to PlayFab successfully
7cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:71 Connected to PlayFab successfully
8cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:71 Connected to PlayFab successfully
8cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:71 Connected to PlayFab successfully
9cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:71 Connected to PlayFab successfully
2cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:71 Uncaught TypeError: Cannot read properties of null (reading 'data')
    at cloud.js?1419:71
    at XMLHttpRequest.xhr.onerror (PlayFabClientApi.js:112)
cloud.js?1419:71 Uncaught TypeError: Cannot read properties of null (reading 'data')
    at cloud.js?1419:71
    at XMLHttpRequest.xhr.onloadend (PlayFabClientApi.js:103)
e3855.playfabapi.com/Client/GetTitleData?sdk=JavaScriptSDK-1.93.210927:1 Failed to load resource: net::ERR_INTERNET_DISCONNECTED
PlayFabClientApi.js:122 Uncaught (in promise) Object
cloud/ping.php:1 Failed to load resource: net::ERR_INTERNET_DISCONNECTED
7cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:71 Connected to PlayFab successfully
6cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:73 Uncaught ReferenceError: CompileErrorReport is not defined
    at playFabLoginCallback (cloud.js?1419:73)
    at overloadCallback (PlayFabClientApi.js:665)
    at XMLHttpRequest.xhr.onerror (PlayFabClientApi.js:112)
cloud.js?1419:73 Uncaught ReferenceError: CompileErrorReport is not defined
    at playFabLoginCallback (cloud.js?1419:73)
    at overloadCallback (PlayFabClientApi.js:665)
    at XMLHttpRequest.xhr.onloadend (PlayFabClientApi.js:103)
e3855.playfabapi.com/Client/LoginWithCustomID?sdk=JavaScriptSDK-1.93.210927:1 Failed to load resource: net::ERR_INTERNET_DISCONNECTED
PlayFabClientApi.js:122 Uncaught (in promise) Object
cloud.js?1419:71 Uncaught TypeError: Cannot read properties of null (reading 'data')
    at cloud.js?1419:71
    at XMLHttpRequest.xhr.onerror (PlayFabClientApi.js:112)
cloud.js?1419:71 Uncaught TypeError: Cannot read properties of null (reading 'data')
    at cloud.js?1419:71
    at XMLHttpRequest.xhr.onloadend (PlayFabClientApi.js:103)
e3855.playfabapi.com/Client/GetTitleData?sdk=JavaScriptSDK-1.93.210927:1 Failed to load resource: net::ERR_INTERNET_DISCONNECTED
cloud/ping.php:1 Failed to load resource: net::ERR_INTERNET_DISCONNECTED
PlayFabClientApi.js:122 Uncaught (in promise) Object
cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:71 Connected to PlayFab successfully
9cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:71 Connected to PlayFab successfully
5cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:71 Uncaught TypeError: Cannot read properties of null (reading 'data')
    at cloud.js?1419:71
    at XMLHttpRequest.xhr.onerror (PlayFabClientApi.js:112)
cloud.js?1419:71 Uncaught TypeError: Cannot read properties of null (reading 'data')
    at cloud.js?1419:71
    at XMLHttpRequest.xhr.onloadend (PlayFabClientApi.js:103)
e3855.playfabapi.com/Client/GetTitleData?sdk=JavaScriptSDK-1.93.210927:1 Failed to load resource: net::ERR_INTERNET_DISCONNECTED
PlayFabClientApi.js:122 Uncaught (in promise) Object
cloud/ping.php:1 Failed to load resource: net::ERR_INTERNET_DISCONNECTED
3cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:71 Connected to PlayFab successfully
cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:71 Uncaught TypeError: Cannot read properties of null (reading 'data')
    at cloud.js?1419:71
    at XMLHttpRequest.xhr.onerror (PlayFabClientApi.js:112)
cloud.js?1419:71 Uncaught TypeError: Cannot read properties of null (reading 'data')
    at cloud.js?1419:71
    at XMLHttpRequest.xhr.onloadend (PlayFabClientApi.js:103)
e3855.playfabapi.com/Client/GetTitleData?sdk=JavaScriptSDK-1.93.210927:1 Failed to load resource: net::ERR_INTERNET_DISCONNECTED
cloud/ping.php:1 Failed to load resource: net::ERR_INTERNET_DISCONNECTED
PlayFabClientApi.js:122 Uncaught (in promise) Object
2cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:71 Uncaught TypeError: Cannot read properties of null (reading 'data')
    at cloud.js?1419:71
    at XMLHttpRequest.xhr.onerror (PlayFabClientApi.js:112)
cloud.js?1419:71 Uncaught TypeError: Cannot read properties of null (reading 'data')
    at cloud.js?1419:71
    at XMLHttpRequest.xhr.onloadend (PlayFabClientApi.js:103)
e3855.playfabapi.com/Client/GetTitleData?sdk=JavaScriptSDK-1.93.210927:1 Failed to load resource: net::ERR_INTERNET_DISCONNECTED
cloud/ping.php:1 Failed to load resource: net::ERR_INTERNET_DISCONNECTED
PlayFabClientApi.js:122 Uncaught (in promise) Object
cloud.js?1419:13 Synchronising with Cloud
cloud.js?1419:71 Connected to PlayFab successfully
3cloud.js?1419:13 Synchronising with Cloud
style.css:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is purely RNG, not a bug unfortunately. Keep at it!

**Comment by tbauer254** [comment]
Hilariously enough, it unlocked 5 minutes after I posted this bug. Sorry about that, definitely the longest it’s taken for a pet to unlock. 

Thanks!
