### ISSUE TITLE
[Bug]: Smithing lvl99 -50% coal effect isnt working

### ISSUE THREAD

**Issue by weon8814** [MelvorIdle/melvoridle.github.io#2047]
### Describe the bug

after i wear the cape and go smithing the dragon bar the coal usage still the same. I didn't see any decrease in coal usage.

### Reproduction Steps

1. wear smithing lvl99 cape
2. go smithing dragonite bar

### Expected behaviour

my coal usage for dragonite bar should decrease by 50%

### Screenshots

![image](https://user-images.githubusercontent.com/97486098/148859576-92b3e405-345a-4ee9-aca5-0c2a2d870aa2.png)
![image](https://user-images.githubusercontent.com/97486098/148859657-04b6bd93-b296-4573-a509-7a3deb32e0a0.png)
![image](https://user-images.githubusercontent.com/97486098/148859683-2d3060fc-554d-4aef-acf2-a4359a2a01fc.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by Silberdrachi** [comment]
The recipe normally costs 12 coal. Which is why it subtracted 6 coal which is what the UI indicates.
https://wiki.melvoridle.com/w/Dragonite_Bar
