### ISSUE TITLE
[Bug]: <title>Cannot create Mark of Octopus tablets 

### ISSUE THREAD

**Issue by gagalindeburg** [MelvorIdle/melvoridle.github.io#2050]
### Describe the bug

Attempting first Mark of Octopus tablet creation.
Have 50 raw shrimp and 6 green shards.
Have 113 full bank slots out of 115. 2 slots available.
Press ‘Create’ goes through the motion, then responds with bank full message. (Not valid…have 2 open slots.)
Takes (uses) shrimp and shards.
No tablets to be found.
Have tried this twice.
OH! With shrimp and shards, bank IS full. Hmmm. 

2015 iPad Air 2, 64 GB
IPad IOS 15.2 up to date.
Melvor Idle 
1.0.1 (1419)

### Expected behaviour

Once shrimp and shards are used, 2 bank slots should be available for  Tablets to reside.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
