### ISSUE TITLE
[Bug]: <title>graphic issue

### ISSUE THREAD

**Issue by Pennrealrize** [MelvorIdle/melvoridle.github.io#2051]
### Describe the bug

![Screenshot_20220111-174406_Brave](https://user-images.githubusercontent.com/97510637/148910785-05250a7c-5a3a-4d81-9f78-53dc9eb25982.jpg)
As above, items look weird and faded.
I play this game on my samsung galaxy 20+, don' know what' wrong with this. Need Help plz.

### Expected behaviour

Graphic problem

### Screenshots

![Screenshot_20220111-174406_Brave](https://user-images.githubusercontent.com/97510637/148911512-b2053963-2fc8-45e1-8d3d-610610e8fdcf.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This can be fixed by disabling auto dark mode for Melvor Idle within your android settings
