### ISSUE TITLE
[Bug]: Bird Nest Tier 2 not being used.

### ISSUE THREAD

**Issue by Akiraheaven** [MelvorIdle/melvoridle.github.io#2052]
### Describe the bug

I have over a 100 Bird Nest Tier 2 potions in my inventory but I am unable to use them

### Screenshots

![image](https://user-images.githubusercontent.com/8603798/149050108-359c2007-fd31-4ef3-a6ff-19c8c495d6e8.png)
![image](https://user-images.githubusercontent.com/8603798/149050134-b95a2efb-486e-4126-9058-5ee5c63ad604.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by 47Y** [comment]
Based on the interface I can see behind the potion menu, it looks like you're in the bank. Potions are only "equippable" from the Skill page they pertain to. If you go to the Woodcutting page and check the potion menu, it should be there.

**Comment by Akiraheaven** [comment]
ah, so just me being a idiot, thanks for the help.
