### ISSUE TITLE
[Bug]: <title>Alt magic summoning tablets

### ISSUE THREAD

**Issue by Dmacrulz** [MelvorIdle/melvoridle.github.io#2053]
### Describe the bug

Alt magic is not consuming the summoning tablets for the witch or occultist despite consuming them normally in actual combat. It is still finding new marks though.

### Expected behaviour

Alt magic is supposed to have all its spells act as combat spells and consume tablets to gain summoning experience as well as discover new marks.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
