### ISSUE TITLE
[Bug]: Earth Layered Shield Bank Default Sorting incorrectly placed

### ISSUE THREAD

**Issue by dubesor** [MelvorIdle/melvoridle.github.io#2054]
### Describe the bug

Using the Default Bank Sorting, when viewing a bank tab with multiple shields and multiple other non-shield items, upon clicking "Sort" the Earth Layered Shield will not be placed anywhere near all the other shields.

### Reproduction Steps

1. Go to Bank
2. Move a few shields including Earth Layer Shield into a tab (e.g. DFS, Recoil Shield and Training Shield)
3. Move a few non-shield items into the same tab (e.g Sand Treaders and Cave Giant Boots)
4. Click Gear icon to confirm that Item Settings use "Set Default Bank Sorting"
5. Click blue "Sort" button
6. Notice that Earth Layered Shield is placed in an incorrect position

### Expected behaviour

Earth Layered Shield will be placed next to all the other shields after clicking "Sort".

### Screenshots

![test](https://user-images.githubusercontent.com/33842233/149125953-6a526765-7ca8-43da-b004-59487d5b85a7.gif)

### Console output

11:41:20.148 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194. (Reason: CORS request did not succeed). Status code: (null).

11:41:20.148 None of the “sha512” hashes in the integrity attribute match the content of the subresource. index_noads.php
11:41:20.551 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194. (Reason: CORS request did not succeed). Status code: (null).

11:41:20.551 None of the “sha512” hashes in the integrity attribute match the content of the subresource. index_noads.php
11:41:29.773 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194. (Reason: CORS request did not succeed). Status code: (null).

11:41:29.773 None of the “sha512” hashes in the integrity attribute match the content of the subresource. index.html
11:41:30.074 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194. (Reason: CORS request did not succeed). Status code: (null).

11:41:30.074 None of the “sha512” hashes in the integrity attribute match the content of the subresource. index.html

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
