### ISSUE TITLE
[Bug]: Can not sell Rusty Keys

### ISSUE THREAD

**Issue by YogiBearFam** [MelvorIdle/melvoridle.github.io#2055]
### Describe the bug

The sell button for rusty keys is greyed out and I cannot press it

### Reproduction Steps

Try to sell rusty keys

### Expected behaviour

It should let me sell the rusty keys as they are a junk item according to the wiki and cannot be used

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1341

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
The Sell button becomes unavailable when items in the bank are locked. This can be toggled by pressing the lock icon in the top left of a bank item.
![image](https://user-images.githubusercontent.com/58208131/157108190-92bc11da-add6-4e0b-aa62-7722be369533.png)
