### ISSUE TITLE
[Bug]: Lethal Toxin, Hinder and Famished potion not displaying correctly. 

### ISSUE THREAD

**Issue by AlexDerr** [MelvorIdle/melvoridle.github.io#2056]
### Describe the bug

When creating each of the new and unique looking potions, the current level (I, II, III, IV) displays correctly with the smaller colored in version of the icon but all of the other representations of the potion are the base grayed out potion outline. 

### Reproduction Steps

1. Go to herblore training tab
2. Select one of famished, Hinder, Lethal toxins potion
3. Look at potion tier icons and see that they are not the right icon for the level of potion you are not actively maing

### Screenshots

![image](https://user-images.githubusercontent.com/36800714/149243976-d0ee5f02-877d-41e3-9683-e0d054da9465.png)
![image](https://user-images.githubusercontent.com/36800714/149243992-d7b7dd50-95be-459c-b114-092570724411.png)
![image](https://user-images.githubusercontent.com/36800714/149244004-e05ebe19-ff8b-4ad4-88b0-69cd979eec96.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.0.2. Please open a new ticket if this is not the case.
