### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by ThaQtip** [MelvorIdle/melvoridle.github.io#2058]
### Describe the bug

No rewards after completing goblin raid

### Reproduction Steps

Start goblin raid
Complete any number of waves
Run away
No rewards

### Expected behaviour

Receive rewards

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
