### ISSUE TITLE
[Bug]: Gem vs Gems bank search

### ISSUE THREAD

**Issue by AevitasDragonkin** [MelvorIdle/melvoridle.github.io#2059]
### Describe the bug

Certain gems are listed as gem, while some others are listed as gems.
Searching the bank for gems does not have the gem results

![image](https://user-images.githubusercontent.com/77356760/149400793-14ab577f-a1da-45eb-926b-48851e84536a.png)
![image](https://user-images.githubusercontent.com/77356760/149400825-2244ccaa-64c4-463d-8e5c-e31cd04dded0.png)

### Reproduction Steps

1. Go to Bank
2. Search for "gem"
3. Search for "gems"

### Expected behaviour

Possibly all of them listed as "gems"

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
