### ISSUE TITLE
Goblin raid rewards and history deleted

### ISSUE THREAD

**Issue by AlphaQLater** [MelvorIdle/melvoridle.github.io#2060]
### Describe the bug

So I did a goblin raid yesterday and got past wave 201 before I slept, and when I woke up there's no history of me doing it, there's no coin rewards, it's as if I didn't even do the raid at all, and I didn't even die. I had slept and hoped to continue when I wake up.

### Expected behaviour

After i started the wave number 202 I went to sleep and hoped to continue in the morning. But it's like I never did the goblin raid at all and I didn't even get the coin reward. Please help.

### Screenshots

![Screenshot_20220114-051531819](https://user-images.githubusercontent.com/81002347/149440337-e5be1963-7473-49d8-ab45-78dacf203a8f.jpg)
![Screenshot_20220114-050648707](https://user-images.githubusercontent.com/81002347/149440346-ae7b8343-d3b1-4578-b7a5-c8681fbc5db4.jpg)
![Screenshot_20220114-050623946](https://user-images.githubusercontent.com/81002347/149440356-b64e0b63-6e98-4483-b5cd-51130b40b4ef.jpg)
![Screenshot_20220114-050632681](https://user-images.githubusercontent.com/81002347/149440398-96d25f62-5cd0-4d53-8687-a70f7e02a1d4.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

V1.0.1 (?1419)

### Are you using any scripts or extensions?

No

**Comment by AlphaQLater** [comment]
![Screenshot_20220114-083206998](https://user-images.githubusercontent.com/81002347/149444355-8d4eca3d-3871-4b41-8ac8-7e5e00b1fe65.jpg)

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
