### ISSUE TITLE
[Bug] GUI graphic glitch

### ISSUE THREAD

**Issue by jsfsbrv** [MelvorIdle/melvoridle.github.io#2061]
### Describe the bug

I have weirdly enlarged images of enemies on my Android. And the numbers on their stats aren't aligned. The respawn circle is also excessively enlarged and extends outside the Enemy box.

### Screenshots

![Screenshot_20220113-080327_Melvor Idle](https://user-images.githubusercontent.com/97737331/149512355-ad99fce9-3e8e-4c6a-b85a-028f135a866a.jpg)
![Screenshot_20220113-080331_Melvor Idle](https://user-images.githubusercontent.com/97737331/149512359-954850a4-47e3-4f5d-8ec1-ad2251eb8d8d.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
