### ISSUE TITLE
[Bug]: Auto Eating Potatoes in Arid Plains

### ISSUE THREAD

**Issue by rjr5838** [MelvorIdle/melvoridle.github.io#2062]
### Describe the bug

When you have Auto Eat Tier 1 (and maybe others) and are eating potatoes in Arid Plains, it eats all of your potatoes and heals you to 100%

### Reproduction Steps

1. Buy Auto Eat 1
2. Equip potatoes and Desert Hat
3. Fight something in Arid Plains
4. Wait for Auto Eat to trigger

I also have Combat Simulator installed.

### Expected behaviour

Your health should be restored to 40%, and you should use 40% + 30% more potatoes to do it. (Or 1.4 * 1.3 more).

### Screenshots

![arid2](https://user-images.githubusercontent.com/3099896/149559573-a0eac882-8208-4ce9-90fd-c698404a5062.gif)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

Yes

**Comment by coolrox95** [comment]
Issue is no longer present in latest version of game (v1.0.3).
