### ISSUE TITLE
[Bug]: I am getting this error when I open my game on Steam, can someone help?

### ISSUE THREAD

**Issue by ADevBelgie** [MelvorIdle/melvoridle.github.io#2064]
### Describe the bug

Here you can find the image and the reddit post I made about the bug. 
https://www.reddit.com/r/MelvorIdle/comments/s33yq2/i_am_getting_this_error_when_i_open_my_game_on/

OS name : Windows 10 Pro 
Version : 10.0.19042 Build 19042
I verified the integrity of game files on Steam and installed the latest version. I have over 1.8k hours on this character, so please help me recover the account. 
I use 3 mods from the Melvor mod manager, auto farming, combat simulator and ETA. I also tried to open the game while they were disabled but got the same error. 

Thank you.

### Reproduction Steps

Start the game on Steam or Mod Manager. 
The bug instantly shows up and I can't interact with the game at all. Can't even select a character. See screenshot. 
https://i.redd.it/tvxwm06zjhb81.png

### Expected behaviour

See above.

### Screenshots

https://i.redd.it/tvxwm06zjhb81.png

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

NA

### Are you using any scripts or extensions?

Yes

**Comment by Rrrakot** [comment]
I reported this issue in https://github.com/MelvorIdle/melvoridle.github.io/issues/2037 .
But if you save games to cloud, you can play on the browser.

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
