### ISSUE TITLE
[Bug]: Astrology's "View All Active Modifiers" list doesn't update when unlocking new slots

### ISSUE THREAD

**Issue by BlacKcuD** [MelvorIdle/melvoridle.github.io#2065]
### Describe the bug

When unlocking new astrology slots while levelling, the freshly unlocked effects don't appear in the "view all active modifiers" list.

### Reproduction Steps

1. Go to Astrology
2. Start levelling any constellation
3. Unlock a new slot by reaching e.g. Mastery 40 of that constellation
4. Press View All Active Modifiers

### Expected behaviour

Freshly unlocked modifiers appear in the "View all active modifiers" list.

### Screenshots

![image](https://user-images.githubusercontent.com/3770741/149633850-e39780ac-f764-4b4e-9c33-2d4f1d8e58bd.png)
![image](https://user-images.githubusercontent.com/3770741/149633855-0c3415fc-2bf1-44fe-b19d-be8c3363183e.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue was fixed as of v1.0.3.
