### ISSUE TITLE
[Bug]: <Maximum HP doesn't added up> 

### ISSUE THREAD

**Issue by Yiweiwangau** [MelvorIdle/melvoridle.github.io#2067]
### Describe the bug

It seems that my maximum HP should be 1000+10(from Finn, the cat) +30(Dragonfire shield) = 1040 instead of 1030 shown here.

My HP remains 1000 instead of 1010 after unequipping the Dragonfire shield.

### Reproduction Steps

1. Obtain "Finn, the cat"
2. equip "Dragonfire shield"

### Expected behaviour

Should get HP of 1040 instead of 1030

### Screenshots

![image](https://user-images.githubusercontent.com/81563224/149682357-6109ee3c-db89-4386-8766-7aaac02911af.png)
![image](https://user-images.githubusercontent.com/81563224/149682369-fad54d96-1819-4fbc-9d06-3ac5d02a5209.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by Silberdrachi** [comment]
99 hp = 990 hp, fin the cat gives you 10hp, plus the shield gives you 30hp, which would be 1030hp.

**Comment by Yiweiwangau** [comment]
Damn
