### ISSUE TITLE
[Bug]: Mobile scroll

### ISSUE THREAD

**Issue by user8342912** [MelvorIdle/melvoridle.github.io#2068]
### Describe the bug

MInor issue but annoying. I've just finished scrolling on the Woodcutting skill page. I then open the menu and try to scroll. I'm not able to scroll the menu because the skill page scroll is still active.

![IMG_2F39A9495182-1](https://user-images.githubusercontent.com/93920643/149753306-0d00b24a-72ef-41c9-b9c7-84e44ccb1901.jpeg)

2 scroll bars active but only the skill page will move until the scroll bar disappears.

### Reproduction Steps

1. Scroll on any page.
2. Open the menu.
3. Try and scroll.

### Expected behaviour

Adding a class to the body with overflow: hidden when the menu button is pressed would stop the scroll and allow me to instantly scroll in the menu.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
