### ISSUE TITLE
[Bug]: Crafting Tokens Description

### ISSUE THREAD

**Issue by Silverfyree** [MelvorIdle/melvoridle.github.io#2069]
### Describe the bug

![image](https://user-images.githubusercontent.com/77082862/149759215-e5c57513-e53d-44cb-943a-b49234da620b.png)

Crafting tokens still showing description to be used in a future update, but they now have a use.

### Reproduction Steps

N/A

### Expected behaviour

Shows actual description

### Screenshots

![image](https://user-images.githubusercontent.com/77082862/149759311-4dab7788-2362-43a1-a9f1-f316d0540e2c.png)

### Console output

N/A

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1419

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Sigil descriptions have been changed to "Used as a Crafting resource."
