### ISSUE TITLE
Offline Cooking XP is rewarded twice

### ISSUE THREAD

**Issue by Tmac8622** [MelvorIdle/melvoridle.github.io#207]
**Describe the bug**
In the "updateOffline" function in main.js, the case "CONSTANTS.skill.Cooking" has two instances of the addXP(CONSTANTS.skill.Cooking, msgXP); function call, effectively resulting in doubled cooking XP while offline.

The first addXP call occurs within the loop that awards cooking XP for each item cooked, likely copy-pasted from the "online" cooking code. However, there is an additional instance _after_ the loop finishes processing that awards the cumulative msgXP once again.

As msgXP is the correct value, the pop-up window that shows the offline cooking information has entirely correct info, but when you check your actual cooking XP you may notice that you have been awarded significantly more than what the message states. I only noticed this because I was expecting to end up 20k cooking XP short of a goal, and ended up overshooting with tons of fish to spare, so I can see how this one went unnoticed.

**To Reproduce**
1. Start cooking something
2. Take note of your cooking XP, then go offline
3. When you return, you will notice that the info box states you earned X amount of xp, but upon comparing your current cooking XP with previous cooking XP you'll have gained double the amount intended.

**Expected behavior**
Offline Cooking XP should only be rewarded once, rather than twice.

**Console output**
Nothing in the console output is relevant to this issue

**Comment by MelvorIdle** [comment]
Hotfixed
