### ISSUE TITLE
[Bug]: Multi-tree woodcutting prevents task switching sometimes

### ISSUE THREAD

**Issue by mac-chaffee** [MelvorIdle/melvoridle.github.io#2070]
### Describe the bug

On iOS, I had just unlocked redwood logs, so I switched from yew+mahogany logs to yew+redwood logs, then switched to a different app.

When I opened the app again about an hour later, my character had stopped woodcutting. Clicking on the trees again did nothing. I closed and reopened the app, then I was able to woodcut.

After an hour of woodcutting, I bought a redwood cooking fire, then switched to cooking manta rays. But the cooking progress bar would begin to fill up, only to be cancelled when I received new logs. I had to go back to the woodcutting tab and stop woodcutting before I could continue cooking.

### Reproduction Steps

1. Have multi-tree and 89 woodcutting
2. Cut yew and mahogany trees until level 90 with the app in the background
3. Change to yew and redwood trees

### Expected behaviour

Changing trees should not stop you from woodcutting. After fixing that, changing skills should automatically stop the old skill.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.0.2. Please open a new ticket if this is not the case.
