### ISSUE TITLE
[Bug]: Golbin Raid raid coins reward not displaying correctly

### ISSUE THREAD

**Issue by AlexDerr** [MelvorIdle/melvoridle.github.io#2071]
### Describe the bug

The pop up after a raid ends along with the raid history does not properly display the number of raid coins received when it is a large amount, what that amount is I am not sure

### Reproduction Steps

1. Get to wave ~120 in golbin raid
2. Pop up says that I received 88 raid coins
3. History says the same
4. I believe I actually received ~88k so maybe just the k is missing at the end?

### Expected behaviour

It should have given me more than 88 raid coins for a 120 wave run and it looks like it did but the display is wrong

### Screenshots

![image](https://user-images.githubusercontent.com/36800714/149813661-4080e1cd-9918-4e6a-914d-55931e91504a.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.0.2. Please open a new ticket if this is not the case.
