### ISSUE TITLE
[Bug]: <title>Unable to select smithing category on mobile 

### ISSUE THREAD

**Issue by Hagrbeat** [MelvorIdle/melvoridle.github.io#2072]
### Describe the bug

Just started playing for the first time and I’m stuck 5 minutes into tutorial island. It will not let me select a smithing category. 

### Reproduction Steps

1. Create new free account on iOS 
2. Go through tutorial island until you get to smithing 
3. Try to select a smithing category from the drop down menu
4. For me, when I select bars (or any category) it closes the drop down but doesn’t select anything. 

### Expected behaviour

I should get to select what I want to smith

### Screenshots

![865ACFC8-C089-415F-B1B0-48C2EEF0C4F1](https://user-images.githubusercontent.com/97915320/149830195-c2ca7492-a995-4df7-b843-57b41e18b57e.png)
![EACF92BB-606E-4621-AD6F-A8C41D61008A](https://user-images.githubusercontent.com/97915320/149830200-b79a4e6f-fb1f-48f7-b28c-43ac79b4c5c3.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

Idk I just downloaded it today

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.0.2. Please open a new ticket if this is not the case.
