### ISSUE TITLE
[Bug]: Can't check the game when not on network (Android)

### ISSUE THREAD

**Issue by pburris** [MelvorIdle/melvoridle.github.io#2073]
### Describe the bug

When losing data connection, the Android app doesn't go into an offline mode and allow you to continue with normal gameplay and progress. Instead the game doesn't load at all. This can lead to huge chunks of time where you can't switch tasks and the progress is capped at 18 hours.

### Reproduction Steps

1. Turn off mobile data and wifi, or simply go out of service range
2. Launch the app

### Expected behaviour

I expected the app to load and let me check my progress and change activities while not on a network. Cloud saves being unavailable during that time would also be expected; but maybe with a nice message integrated in the GUI.

### Screenshots

![melvor_no_internet](https://user-images.githubusercontent.com/25254501/149868083-2e5865eb-6e25-43f9-aa19-b936d6f13352.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by ekuland** [comment]
That's not a bug. The game requires being online to launch.

**Comment by pburris** [comment]
If cloud saves are not mandatory, what need would there be for online access to launch?

**Comment by pburris** [comment]
Actually, I think it is due to monetization strategy and ensuring upgrading to premium is seamless. While I still find it annoying, I can see how it is not a bug.
