### ISSUE TITLE
[Bug] When using alt-magic, logging back into the game page after leaving it will result in a discontinuation of action.    Every time 

### ISSUE THREAD

**Issue by Fukkoff** [MelvorIdle/melvoridle.github.io#2074]
### Describe the bug

Even chosing to access the profile that is using alt magic will stop the alt magic from continuing (idling) when next logged out.

### Reproduction Steps

0. Log into account and select a profile
1. Start an alt magic
2. Refresh page
3. Access same profile your started alt magic on
4. Do nothing.
5. Refresh page 
6. Account will be inactive and doing nothing.
7. Find problem?
8. Only tested in Chrome on an android device.

### Expected behaviour

Action will stop upon looking at an account that was using alt magic.   Works for any alt magics.   No other skills that Ive found.

### Screenshots

#
![Screenshot_20220118-065233_Chrome](https://user-images.githubusercontent.com/97959737/149940851-1bf0e304-de8a-4bc1-b39d-6ead39f598ec.jpg)
Was using blessed offering before ss was taken.   

### Console output

N/A

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.0.2. Please open a new ticket if this is not the case.
