### ISSUE TITLE
[Bug]: Icon for adventure mode is not centred 

### ISSUE THREAD

**Issue by xanderput** [MelvorIdle/melvoridle.github.io#2076]
### Describe the bug

Icon for adventure mode is not centred.
I assume it's because of a dimension problem in the svg [here](https://melvoridle.com/assets/media/main/adventure.svg).

### Expected behaviour

Centred icon

### Screenshots

![image](https://user-images.githubusercontent.com/39944140/149965590-2bd52c74-ab2d-4b73-a04d-78d73b1e10d8.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
