### ISSUE TITLE
[Bug]: Maxed astrology masteries don't turn gold when opening astrology page

### ISSUE THREAD

**Issue by xanderput** [MelvorIdle/melvoridle.github.io#2078]
### Describe the bug

When you hit 99 mastery on an item the mastery level turns gold and the mastery bar turns green. For skills like woodcutting this effect persists even after reloading the game. For astrology the effect doesn't persist. 

### Reproduction Steps

1. Get astrology mastery to 99
2. Reload game
3. Notice that the effects have disappeared

### Expected behaviour

Effect persists even after reloading game.

### Screenshots

For astrology the effect didn't persist:
![image](https://user-images.githubusercontent.com/39944140/149974248-563fd021-a8dc-496a-b0c6-3e380a7bae86.png)

For woodcutting it did:
![image](https://user-images.githubusercontent.com/39944140/149974291-c5264a99-e4c5-4e12-8048-f5c71d0e9d8d.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by Pepipito** [comment]
Same Bug on Steam

**Comment by xanderput** [comment]
Fixed in v1.0.3
