### ISSUE TITLE
[Bug]: Wrong quick-equip tooltip coming up (farming in combat view)

### ISSUE THREAD

**Issue by ReiniervdG** [MelvorIdle/melvoridle.github.io#2079]
### Describe the bug

When disabling the auto re-use potion option in the combat screen, the quick-equip tooltip for farming appears to come up in the bottom right. Not really all that bad, but I expect it's unintended behaviour.

### Reproduction Steps

1. Go to combat screen while (in my case) diamond luck potion is enabled with 'auto re-use this potion' on
2. Turn on the option for 'auto re-use this potion'
3. In my case, the farming quick-equip tooltip then comes up in the bottom right.

### Screenshots

![image](https://user-images.githubusercontent.com/27781928/149979110-a7ee5620-2698-4fe3-86b3-de53742d8dcc.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1419

### Are you using any scripts or extensions?

Yes

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
