### ISSUE TITLE
Not able to choose which attack style on Android app

### ISSUE THREAD

**Issue by hubonthegrub** [MelvorIdle/melvoridle.github.io#208]
I am currently unable to choose my attack style on the Android app. The part of the screen where you're able to select whether you want to train attack, strength, or defense does not exist anywhere on the combat screen, nor anywhere else on any screen. Everything else is where it should be, other than that. I assume it's based off of screen size, because my new phone with a larger screen does not have this issue.

The phone is LG V20, the resolution of the screen is 1440 x 2560 pixels, 16:9 ratio (~513 ppi density), and the size of the phone is 5.7 inches, 90.3 cm^2, and the game version is Alpha v0.14.2. Not sure if any of this helps, but hopefully it does.

My apologies if this doesn't belong here, kind of out of options at the moment. Thank you for all your help, and on creating an amazing game that I love.

**Comment by MelvorIdle** [comment]
Attack style selection is located under your equipped items in the combat screen.
