### ISSUE TITLE
[Bug]: Ring of Spirit Power obtainable in Golbin Raid, but can't get spirit runes to use it

### ISSUE THREAD

**Issue by AlexDerr** [MelvorIdle/melvoridle.github.io#2080]
### Describe the bug

Not sure if this is exactly a bug or not but something that I noticed.

There are other useless items that you can get like skilling armor in Golbin Raid but I am not sure if this is intended.

### Reproduction Steps

1. Do Golbin Raid
2. Get Ring of Spirit Power
3. Always defaults to bronze scimitar because it is not possible to get spirit runes

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.0.2. Please open a new ticket if this is not the case.

**Comment by AlexDerr** [comment]
May not have been fixed looking at #2134
