### ISSUE TITLE
[Bug]: Active skill does not get highlighted in green on the sidebar when switching from another active skill

### ISSUE THREAD

**Issue by girayozel** [MelvorIdle/melvoridle.github.io#2081]
### Describe the bug

Active skill does not get highlighted in green on the sidebar when switching from another active skill

### Reproduction Steps

1. Go to any skill and start doing it. E.g. go to mining and start mining an ore
2. Notice that the skill, e.g. mining, has been highlighted in green
3. Switch to another skill and start doing it. E.g. switch to firemaking and start burning logs
4. Notice that the previously highlighted skill has been unhighlighted but the currently active skill remains in white/unhighlighted
5. If you stop and activate the skill again, it gets highlighted correctly

### Expected behaviour

Whenever a skill is made active it should be highlighted even if you switch directly from another skill, which was active at the time.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
