### ISSUE TITLE
Strange math

### ISSUE THREAD

**Issue by herbert164** [MelvorIdle/melvoridle.github.io#2083]
### Describe the bug

while chopping 2 trees one at .4sec and the other at .6sec i get basically the same number of logs after 18 hours. i would expect a bigger difference and a few hundred out of nearly 200k logs.

### Reproduction Steps

max woodcutting mastery on oak and normal logs. buy all the shop items to improve woodcutting. Chop trees.

### Expected behaviour

i would expect something like a 2:3 ratio between them.

### Screenshots

![same number of logs](https://user-images.githubusercontent.com/5839829/150288789-9d9702f9-0b75-4605-874d-f14eb0ec0db9.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by ekuland** [comment]
Double woodcutting uses the longest time period for both trees.
You get both sets of logs at the same time.

**Comment by herbert164** [comment]
when i had a .4 tree and a .8 tree i got the expected amount i believe.

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
