### ISSUE TITLE
[Bug]: Venom Special Attack is described “Normal” but is Unavoidable

### ISSUE THREAD

**Issue by ShanePhillips4** [MelvorIdle/melvoridle.github.io#2087]
### Describe the bug

The venom attack in the spider forest is described as a “normal attack”, then on hit it has a chance to cause the poison effect. It is actually an unavoidable attack, even on the lowest lvl spiders. It should either be a normal attack with the same hit chance, or it should be described as an unavoidable attack like the sandstorm special attack. Also, a 40% chance to proc unavoidable damage is pretty ridiculous for low level mobs, imo. 

### Reproduction Steps

Fight spiders in Spider Forest dungeon and get annoyed when they hit you 40% of the time.

### Expected behaviour

“Normal attack” to hit with the same accuracy as an actual normal qttack

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
