### ISSUE TITLE
[Translation Error]: UNDEFINED TRANSLATION: SHOP_CAT:GOLBINRAID

### ISSUE THREAD

**Issue by AlexDerr** [MelvorIdle/melvoridle.github.io#2089]
### Which text in the game has a translation error?

Golbin raid shop title is undefined. 

Steam version, v1.0.1, ?1419

**Comment by AlexDerr** [comment]
![image](https://user-images.githubusercontent.com/36800714/150605337-b67c617e-0135-4ee1-b5cb-8f6eacc4efe0.png)

**Comment by CeaganP** [comment]
![image](https://user-images.githubusercontent.com/43758262/150617560-8b819407-f3f1-46f7-a180-c06edab8e11e.png)

**Comment by AlexDerr** [comment]
Exactly, it is a public test and the point of testing is to find and fix bugs like the one described. Take the sarcastic BS somewhere else. @CeaganP

**Comment by AlexDerr** [comment]
Issue is duplicate of #1960. Closing
