### ISSUE TITLE
Seething Horned Elite not depositing Big Bone drops to bank

### ISSUE THREAD

**Issue by GeneralShogun** [MelvorIdle/melvoridle.github.io#2090]
### Describe the bug

When fighting Seething Horned Elite via Slayer Task, Big Bones show as a drop every kill but it does not deposit to my inventory/bank (I am 145 out of 157 slots...so I have room in my bank).  This happens with or without my Amulet of Looting.  I have rebooted my computer and cleared the cache as well
![BigBone](https://user-images.githubusercontent.com/98230169/150649652-b6bf6691-f505-4adc-b8ee-41419adbde39.PNG)
.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
