### ISSUE TITLE
[Bug]: Steam achievement information is incorrect

### ISSUE THREAD

**Issue by AuroraKy** [MelvorIdle/melvoridle.github.io#2091]
### Describe the bug

A Touch of Mastery still has the comment that it is currently bugged, but it appears to have been fixed

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by titaniteChuck** [comment]
I confirm that the achievement triggers as expected.

I'm on steam v1.1 ?4631, vanilla game

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
