### ISSUE TITLE
[Bug]: potion preservation grapical issue

### ISSUE THREAD

**Issue by Visionice2** [MelvorIdle/melvoridle.github.io#2092]
### Describe the bug

When you come back from being offline the welcome back screen shows the amount of potion doses you should have used with no preservation. The amount of potion doses actually used are correct and account for preservation. Unsure if summoning tablet preservation is the same.

### Reproduction Steps

I tested with herblore potion.
Have potion dose preservation from astrology, use potions with automatically reuse, go offline for some time, come back online and the amount of charges said to be used are more than are actually used. I equipped bear tablets to track the amount of actions performed and on the welcome back screen it showed potion doses used equal to bear tablets used although that wasn't the case.

### Expected behaviour

Welcome back screen to account for preservation 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.0.3.
