### ISSUE TITLE
[Bug]: Monsters unique attacks seems to have 100% chance of hitting

### ISSUE THREAD

**Issue by orcmon** [MelvorIdle/melvoridle.github.io#2094]
### Describe the bug

When fighting monsters with unique attacks, each unique attack the monster performing seems to hit the character, despit very low chances of hitting (10%).

### Reproduction Steps

1. Go fight monster with unique attack, like 'Frozen Mammoth' in the 'Icy Hills'.
2. The chance of hit of the monster should be low.
3. Wait for the attack interval bar to show the monster uses unique attack.
4. the charater will always receive damage, and not avade.

### Expected behaviour

Unique attacks of monsters should be effected by chance to hit.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1419

### Are you using any scripts or extensions?

No

**Comment by ekuland** [comment]
"30% Frostburn
An **_unavoidable_** attack that deals up to 100% of the enemy's normal damage. gives you 3% of Current Hitpoints taken as damage per Attack and +10% Attack Interval for 2 of your turns."
