### ISSUE TITLE
[Bug]: Synergy does not take effect immediately after unlocking

### ISSUE THREAD

**Issue by Aslai** [MelvorIdle/melvoridle.github.io#2095]
### Describe the bug

I had a level 3 Mole mark and level 4 Salamander mark. I equipped both mole and salamander even though the synergy hadn't been unlocked yet. 

I was mining offline to get the final Mole level to activate the synergy, but when I came back, the synergy was not active, despite my equipment screen saying it was. No salamander charges were being used, and only one mole was being used per mining action, as if the synergy wasn't active.

Unequipping and re-equipping the familiars activated the synergy.

### Reproduction Steps

1. Get Salamander mark to level 4
2. Get Mole mark to level 3
3. Equip a lot of Mole and Salamander tablets
4. Level the Mole mark to level 4 while offline
5. No Salamanders will be consumed when the game resumes

### Expected behaviour

The Mole + Salamander synergy should take effect as soon as the Mole mark becomes level 4

### Screenshots

https://user-images.githubusercontent.com/1024138/150732959-a652247d-3bbc-4ea0-93aa-5a96733e7532.mp4

[bug_save.txt](https://github.com/MelvorIdle/melvoridle.github.io/files/7923153/bug_save.txt)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by ekuland** [comment]
Summoning is not yet tickbased. All offline effects are applied at the level you were when you went offline.

**Comment by Aslai** [comment]
I'd expect the game to apply the synergy once it acknowledges that you have obtained the relevant levels though, which it's not doing automatically. It requires the player to either re-equip a tablet or save and reload the game to start the synergy, even though the game has already acknowledged that the preconditions have been met to use the synergy.

**Comment by amulder87** [comment]
I saw this also, using Golbin+Occultist, using Chrome version 1.0.2 v1530.

**Comment by coolrox95** [comment]
Issue has been resolved as of the v1.0.3 update.
