### ISSUE TITLE
[Spelling/Grammar]: Amulet of Incantation: "-0.2s Magic Interval" > "-0.2s Alt.Magic Interval"

### ISSUE THREAD

**Issue by chill-was-taken** [MelvorIdle/melvoridle.github.io#2096]
### What text is wrong?

The wrong text: -0.2s Magic Interval

Explanation:  
Currently, the description for the Amulet of Incantation reads as  

> -0.2s Magic Interval
> +10% Rune Preservation for Alt.Magic Spells

However, the Amulet of Incantation shortens only Alt.Magic interval. It doesn't shorten the Magic Attack Interval.  
People mistake Magic Interval with Magic Attack Interval.  

To prevent this misunderstanding, I suggest changing the first line to "-0.2s Alt.Magic Interval". The resulting description would be as follows:

> -0.2s Alt.Magic Interval
> +10% Rune Preservation for Alt.Magic Spells

### What is the correct spelling or grammar?

The correct text: -0.2s Alt.Magic Interval

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
