### ISSUE TITLE
[Bug]: <span> tag gets split up by auto wrapping

### ISSUE THREAD

**Issue by yamirui** [MelvorIdle/melvoridle.github.io#2097]
### Describe the bug

`<span>` element gets split in half when the browser decides that there isn't enough space to render it on a single line.
This happens to all `<span>` tags in skill sections and looks rather uncanny.

---

Example of XP `<span>` being split in half (desktop/Firefox): ![1643027458](https://user-images.githubusercontent.com/63095905/150786611-09f0ca0c-0ab8-43a5-a966-19237994009f.png)
Example of tool name `<span>` being split in half (mobile/Android): ![Screenshot_20220124-144922_Melvor_Idle](https://user-images.githubusercontent.com/63095905/150786670-d8eb264f-f061-45dc-8927-0aea18070d53.jpg)

### Reproduction Steps

Have monitor and/or browser window small enough for auto-wrap on some longer text-based elements to take effect. This is just how auto-wrap handles things like that.

### Expected behaviour

I expect `<span>` elements to be indivisible, possibly with `white-space: nowrap` applied everywhere where it makes a difference:
![1643027870](https://user-images.githubusercontent.com/63095905/150784228-13ed2d09-ebf3-4ed8-abc7-273c5b1a9886.png)
This causes the browser to instead move entire element to next line rather than splitting it in half which looks a lot better.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
