### ISSUE TITLE
[Bug]:Necklace of autolooting

### ISSUE THREAD

**Issue by damdor1** [MelvorIdle/melvoridle.github.io#2099]
### Describe the bug

if i wear the necklace of auotlooting on first equipment lot ... it works fine, if i put in in any of the other 3 sets it fails.. no error just does not work... it says its a passive equipment 

### Reproduction Steps

when equiped in any equipment set except first it fails..no error just does not work

### Expected behaviour

i expected the loot drops to be put in my bank

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1419

### Are you using any scripts or extensions?

No

**Comment by ekuland** [comment]
You have to be wearing it. It has to be in your active set.
A passive bonus just means it's on the entire time you wear it.

**Comment by damdor1** [comment]
its says its passive (so you should be able to wear on a nonactive set) , so it should work on the set i am not using .. i keep set 1 as my active set so i put this on set 2 .it doesn't work.    the other passives work that way ..are you now saying the rest are wrong ?

**Comment by coolrox95** [comment]
Only equipment that is in your currently selected equipment set is active. Passive, refers to the amulet being able to equipped in the "Combat Passive" equipment slot which can be unlocked.
