### ISSUE TITLE
Divine Potion charges are used on player attacks

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#210]
**Describe the bug**
When you have divine potions equipped, potion charges are expended on player attack, and whenever prayer points are deducted for a prayer.

**To Reproduce**
1. Equip divine potions
2. Fight any monster
3. See that potion charges reduce by 1 every attack, even when prayer isn't used

**Expected behavior**
Divine potion charges should only be used when prayer points are deducted. Likely need to add this potion effect to the exceptions for on attack potion charge consumption (similar to regeneration potions).

**Comment by MelvorIdle** [comment]
Fixed in v0.15
