### ISSUE TITLE
[Bug]: Agility masteries use strange code instead of obstacle name

### ISSUE THREAD

**Issue by jsalvadorcaffarena** [MelvorIdle/melvoridle.github.io#2102]
### Describe the bug

Both in the "spend mastery XP" screen, notifications and popup messages the mastery obstacle names show as weird strings like "1RS" or "5RC".

### Reproduction Steps

Go to agility skill, clikc on "Spend Mastery XP" button, for example.

### Expected behaviour

The mastery levels should show the obstacle names instead of strange codes.

### Screenshots

<img width="1260" alt="Captura de pantalla 2022-01-26 a las 8 08 30" src="https://user-images.githubusercontent.com/14583691/151118890-5e9cf38c-7f02-41b6-b283-d8a80f2c6cda.png">

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [X] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by gmm39** [comment]
It is the obstacle number and then the abbreviation of the name. It is likely done because fitting the entire name would be difficult

**Comment by MelvorIdle** [comment]
This is not a bug, just what is described in the above comment.

Soon we will make the obstacle names more visible. In the mean time you can hover/click the abreviation to see the full name of the obstacle.
