### ISSUE TITLE
[Bug]: xAll doesn’t work on 1 thing

### ISSUE THREAD

**Issue by Duallyhazard** [MelvorIdle/melvoridle.github.io#2104]
### Describe the bug

I tried to upgrade to a fez (I only had mats to make 1) and when I clicked xAll it didn’t do anything

### Reproduction Steps

Upgrade fez and click xall (may work with other upgrades idk)

### Expected behaviour

Should just act the same as x1

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [X] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by krehera** [comment]
I think I have some more info on this bug, as I tried to upgrade some Dragon Crossbows to Slayer Crossbows and it failed.

If you try to Upgrade All, what you expect to happen is it makes x things, where x is **limited by some other component than the thing you're trying to upgrade**. but instead the game decides it can't upgrade all y of your components and then upgrades 0 of them instead.

In my case, I had >100 Dragon Crossbows, but only 3 Slayer Crossbow Heads. when I Upgraded All dragon crossbows it did nothing, but Upgrading All the Slayer Crossbow Heads worked fine.

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
