### ISSUE TITLE
[Bug]: Blazing Lantern frame invisible when viewing with details in bank

### ISSUE THREAD

**Issue by Canicam** [MelvorIdle/melvoridle.github.io#2105]
### Describe the bug

The Blazing Lantern metallic frame seems to use the same light grey as the background used for the items detail screen, making the metal invisible. 

### Reproduction Steps

1. Go to the Slayer store and buy the Blazing Lantern
2. Go to your bank and click on the Blazing Lantern
3. Observe the Blazing Lantern frame being invisible in the right hand menu ( inside blue frame in screenshot ). 

### Expected behaviour

Either the metal part of the Blazing Lantern could have a colour change, or an outline should be added to discern the Blazing Lantern from the background

### Screenshots

![Blazing Latern - Melvor Idle](https://user-images.githubusercontent.com/61713154/151371169-15abc24c-d6ba-46ac-a4ea-212d87c98583.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
