### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by CheeseburgerFreddy** [MelvorIdle/melvoridle.github.io#2106]
### Describe the bug

When getting the notification for preservation on cyclops tablets only the shards are preserved, not slayer coins. 

### Reproduction Steps

Create cyclops tablets, when preservation procs check slayer coins

### Expected behaviour

You will lose slayer coins when they are suppose to be preserved

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.0.3.
