### ISSUE TITLE
[Bug]: woodcutting skillcape provides wrong bonus

### ISSUE THREAD

**Issue by jeremyhetzler** [MelvorIdle/melvoridle.github.io#2107]
### Describe the bug

Woodcutting skillcape is supposed to provide -15% woodcutting interval. Without the cape, maple takes 4 seconds. With the cape, maple takes 2.8 seconds. That's a 30% reduction. Other trees are similarly affected.

I do have multi-tree, not sure if that might be involved.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
The woodcutting skillcape bonus is additive with all other modifiers to interval. As a result, the percentage difference in interval between having the cape equipped and not equipped will vary depending on those modifiers.
