### ISSUE TITLE
Broken synergy in Adventure mode

### ISSUE THREAD

**Issue by IRONN1C** [MelvorIdle/melvoridle.github.io#2108]
### Describe the bug

I got 10k gold everytime I got the bonus from Goblin Thief + Unicorn synergy in Adventure Mode, I am pretty sure that cause of the x10 hp regen.

### Reproduction Steps

Use Goblin Thief + Unicorn Synergy in Adventure Mode
Maximize Regen with prayer and potion
Get crazy profit

### Expected behaviour

I am pretty sure I am suposse to get 1k gold lol not 10k thats way to much.

### Screenshots

![brokensynergie](https://user-images.githubusercontent.com/98619367/151622354-5b5112fb-d1c7-467a-b192-a43c3084569f.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
