### ISSUE TITLE
"Weird Gloop" text stuck in upper left corner of screen

### ISSUE THREAD

**Issue by levgre** [MelvorIdle/melvoridle.github.io#211]
**Describe the bug**

"Weird Gloop" text sticks on upper left of screen

[image](https://user-images.githubusercontent.com/14255060/80663454-338bb780-8a51-11ea-895a-15ccb23554c2.png)

**Browser**
Chrome latest version

**Console output**
Please open the console by pressing F12 and copy it here.

2pagead2.googlesyndication.com/pagead/js/adsbygoogle.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
save.js?280:473 Not required to backup
save.js?280:47 Loading Save Game...
save.js?280:208 Save Game Loaded...
save.js?280:47 Loading Save Game...
save.js?280:208 Save Game Loaded...
smithing2.js?280:189 Loading Smithing...
mastery.js?280:181 Updating Masteries
mastery.js?280:23 Loading Masteries...
main.js?291:1112 Game Loaded
oneui.core.min.js?205:6 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ oneui.core.min.js?205:6
cloud.js?280:46 Melvor Cloud Connection: Success
save.js?280:47 Loading Save Game...
save.js?280:208 Save Game Loaded...
main.js:3073 Melvor Combat Sim v0.6.4 Loaded
smithing2.js?280:189 Loading Smithing...
mastery.js?280:181 Updating Masteries
mastery.js?280:23 Loading Masteries...
main.js?291:1112 Game Loaded
49cloud.js?280:192 Cloud synced
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by zid** [comment]
Can reproduce a similar issue: Go to fletching, then arrow shafts. Select a type of log then hover the small log icons below. Tooltip will get stuck, and sometimes/eventually migrates to the top left corner.
