### ISSUE TITLE
Gold on kill bonus in dungeon

### ISSUE THREAD

**Issue by IRONN1C** [MelvorIdle/melvoridle.github.io#2110]
### Describe the bug

I am in adventure mode and the syrnergy goblin thief + Wolf dont work in dungeon. The glove of silence too.

### Reproduction Steps

I am in adventure mode and the syrnergy goblin thief + Wolf dont work in dungeon. The glove of silence too.

### Expected behaviour

it should give money on every kill.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
