### ISSUE TITLE
[Bug]: Cave Fish

### ISSUE THREAD

**Issue by Custii** [MelvorIdle/melvoridle.github.io#2111]
### Describe the bug

u can not make burnt fish after some updates ago

so why do i need burnt cave fish for complete item list

### Reproduction Steps

item list 
after whale  before copper

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1419

### Are you using any scripts or extensions?

No

**Comment by tea-sheep** [comment]
Burnt Cave Fish is an Item dropped by the Tetacle
