### ISSUE TITLE
[Bug]: Astrology "Show All Active Modifiers" doesn't update

### ISSUE THREAD

**Issue by tea-sheep** [MelvorIdle/melvoridle.github.io#2112]
### Describe the bug

When I click on the "Show All Active Modifiers" button, it doesn't show any new modifiers I've recieved

### Reproduction Steps

1. receive a new modifier in astrology
2. click the show all active modifiers button

### Expected behaviour

The show all active modifiers button should immediately show all active modifiers

Note: it fixes the issue if I reload the tab

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.0.3.
