### ISSUE TITLE
[Spelling/Grammar]: <"You Pet ASTRO">

### ISSUE THREAD

**Issue by Volkradlol** [MelvorIdle/melvoridle.github.io#2114]
### What text is wrong?

All of the pets when you click on them says "You Pet ASTRO" instead of "Your pet ASTRO" 

### What is the correct spelling or grammar?

"Your Pet <Pet Name>"

**Comment by Silberdrachi** [comment]
When you click on them its supposed to be like 'petting' them, as in patting them on the head. The sign of affection, not the indication of ownership.

**Comment by Volkradlol** [comment]
> When you click on them its supposed to be like 'petting' them, as in patting them on the head. The sign of affection, not the indication of ownership.

Ah thank you I get it.

**Comment by Volkradlol** [comment]
My mistake, was cleared up.
