### ISSUE TITLE
[Bug]: Adventure Mode tutorial island skill... smuggling?

### ISSUE THREAD

**Issue by geecarr** [MelvorIdle/melvoridle.github.io#2115]
### Describe the bug

Just before you finish tutorial island if you start a gathering skill once adventure mode starts you will still be gathering that resource and accumulating it in your bank. This isn't highly abusable as you cannot process the resource but I don't think it is intended behavior.

### Reproduction Steps

Before tutorial island is over start gathering.
Finish tutorial island.

### Expected behaviour

Not to be gathering once the skill was locked.

### Screenshots

[uhm is this how we do screenshots?](https://postimg.cc/TLxbmyKv)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
