### ISSUE TITLE
[Bug]: Can't pick Character 

### ISSUE THREAD

**Issue by Jumjac** [MelvorIdle/melvoridle.github.io#2116]
### Describe the bug

When I start the game and want to choose which character I want to play it want let me. The first click on my character the scroll bar shows in the side of the screen. I can't press any other buttons expect for login and setting for profile. If I then logout of my account so I don't have cloud save, then I can open my character. But her comes the next bug. When on my character after login out I can't sell stuff. When I try and to sell something it just scrolls all the way to the bottom of the screen.

### Reproduction Steps

1. try to enter on character 
2. log out 
3. then choose character 
4. then try to sell

### Expected behaviour

normal login and be able to sell

### Console output

nothing in the consol

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
