### ISSUE TITLE
[Bug]: Cant see whole move tab

### ISSUE THREAD

**Issue by Seickly** [MelvorIdle/melvoridle.github.io#2117]
### Describe the bug

Cant see the whole move tab
![93B0715D-4F7E-43FD-86DC-C5B6CEDFE05D](https://user-images.githubusercontent.com/98729763/151745275-684f61db-e220-4485-9075-ba5fe80f2c0f.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1.0.2

### Are you using any scripts or extensions?

No

**Comment by Somazy** [comment]
Having the same issue 😔
![Screenshot_20220131-010241_Melvor Idle](https://user-images.githubusercontent.com/98732738/151752121-fcc1bae3-54d2-4aed-a1e3-bbb1eb676406.jpg)

**Comment by Haizamon** [comment]
Same here.. if you turn your phone you can acces it tho

![0A3E2F9D-13C5-4BF7-92DA-B0810C3DBCF5](https://user-images.githubusercontent.com/85392549/152301352-2b95c2c5-0266-47f4-b681-e2e635f4961a.jpeg)

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
