### ISSUE TITLE
[Bug]: Exporting saves no longer contains the character name

### ISSUE THREAD

**Issue by Silberdrachi** [MelvorIdle/melvoridle.github.io#2118]
### Describe the bug

Exporting saves from within the settings menu (download button) no longer exports saves name.

### Reproduction Steps

1. Open character
2. Open settings container
3. Download save
4. Check save name

### Expected behaviour

Save file will be named "melvoridlesave_[character_name].txt"

(Bonus points if you want to change that to "[character_name]_[datetimestamp].melvor" or something similar)

### Screenshots

![image](https://user-images.githubusercontent.com/76179203/151746187-2998bbc6-7a06-4cbe-8d15-c90b4c3e1858.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1.0.2 ?1522

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of the v1.0.3 update.
