### ISSUE TITLE
Mastery token works wrong on herblore 

### ISSUE THREAD

**Issue by michiforjoy** [MelvorIdle/melvoridle.github.io#212]
I had just gotten bird nest potion to mastery 15 (potion level II). I redeemed a herblore mastery potion. It supposedly improved bird nest level I. I still have mastery 15 for bird nest potion.

**Comment by MelvorIdle** [comment]
Are you sure what you saw was a Bird Nest Potion from the popup? There are similar looking potions available that it may have chosen instead (You can get mastery for potions that are not unlocked yet)
