### ISSUE TITLE
[Bug]: Combat Minibar disappears from Golbin Raid

### ISSUE THREAD

**Issue by Sennsationalist** [MelvorIdle/melvoridle.github.io#2120]
### Describe the bug

After update, Combat Minibar disappears upon pausing and resuming Golbin Raid. Toggling my settings off and on did not fix it.

### Reproduction Steps

1. Start Golbin Raid
2. Finish wave and pause raid
3. Select character and/or close app
4. Continue raid, minibar is missing

### Expected behaviour

Minibar should follow main game settings.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1522

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of the v1.0.3 update.
