### ISSUE TITLE
[Bug]: Golbin Raid UI Elements can be interacted with before visible

### ISSUE THREAD

**Issue by Sennsationalist** [MelvorIdle/melvoridle.github.io#2121]
### Describe the bug

The post-wave popup for gear selection can be interacted with before the pop-up has actually appeared on screen. This can lead to unintended selections by the player when they happen to be tapping on the screen in the moment between the final monster of the wave dying and the pop-up appearing.

### Reproduction Steps

1. Start Golbin Raid
2. Spam tap on the screen as the final Golbin of the wave is dying
3. If you are tapping where a button would appear, you should see the result of that button press rather than the page with the button itself.

### Expected behaviour

It should not be possible to click on an invisible UI element.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1522

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
