### ISSUE TITLE
[Bug]: Bank tab icons are not persistent

### ISSUE THREAD

**Issue by Cavecanem** [MelvorIdle/melvoridle.github.io#2123]
### Describe the bug

Icons for bank tabs don't persist after closing the game. Then they go back to the default icon.

### Reproduction Steps

Go to the bank and choose an item.
Go into the bank settings.
Set the icon of a tab to the selected item.
The new icon is there. 
Restart the game.
The default icon is there. 

### Expected behaviour

The expected behaviour is that the new icon should persist after restarting the game.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1523

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Hotfix has just been released for this one. Version ?1524
