### ISSUE TITLE
[Bug]: Pig and Mole cooking synergy

### ISSUE THREAD

**Issue by Uberfatty** [MelvorIdle/melvoridle.github.io#2125]
### Describe the bug

No coal is given when a cooking failure happens and the pig/mole synergy is active.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1523

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
