### ISSUE TITLE
[Bug]: Food search doesn't find everything

### ISSUE THREAD

**Issue by Sandman366** [MelvorIdle/melvoridle.github.io#2126]
### Describe the bug

Searching the bank for "food" is supposed to work as a wildcard for actual food items, but not every food is found by this search. For example, perfect carrot cake, perfect meat pizza slices, perfect basic soup, perfect hearty soup, and perfect apple pies, but I don't know if that's all of them (since I haven't even owned every food yet).

### Reproduction Steps

1. Have at least one of every kind of food in the bank.
2. Search bank for "food".
3. See which ones aren't there after the search is applied.

### Expected behaviour

I expected every kind of food item owned to show up?

### Screenshots

![image](https://user-images.githubusercontent.com/47545215/151832484-d60b55d4-5141-4c89-ba09-56398eeaa33e.png)
![image](https://user-images.githubusercontent.com/47545215/151832510-fc61994a-256c-4e4c-a1ae-c8d64f6a7572.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1523

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
