### ISSUE TITLE
[Bug]: Farming level higher than 99

### ISSUE THREAD

**Issue by qypea** [MelvorIdle/melvoridle.github.io#2127]
### Describe the bug

Recently I hit farming lvl 99 and purchased the skill cape for it. My farming level has now ticked up to lvl 100 and 101 though. Currently it says that I have 15,976,070 exp and lvl 101 in farming.

### Reproduction Steps

1. Level up farming to lvl 99
2. Keep farming plants

### Expected behaviour

I expected it to be limited at lvl 99, not go above there like the other skills.

### Screenshots

![Screenshot_2022-01-31_09-39-04](https://user-images.githubusercontent.com/1694406/151844667-c2972e53-2fb5-44db-b892-7da3dc6198cb.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1523

### Are you using any scripts or extensions?

No

**Comment by Sennsationalist** [comment]
This isn't a bug. Virtual Levels show your progress past maximum level and can be disabled in settings. A future update will increase maximum level to 120.

**Comment by qypea** [comment]
Oh. Thanks for clarifying
