### ISSUE TITLE
[Bug]: Goblin Raid - Ring of Spirit Power deletes weapons with ability

### ISSUE THREAD

**Issue by ServePeak** [MelvorIdle/melvoridle.github.io#2134]
### Describe the bug

Having both the ring of spirit power and any weapon with an ability resets the weapon to default bronze/addy scimitar

### Reproduction Steps

1. Have Ocean song
2. Have any weapon with an ability
3. Wait one attack
4. Weapon is reset to default

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1524

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
