### ISSUE TITLE
[Bug]: <title> Buying golbin crates after dying in raid does not play the uncrating animation

### ISSUE THREAD

**Issue by Flurryous** [MelvorIdle/melvoridle.github.io#2135]
### Describe the bug

As the title says, I encountered a bug where the uncrating animation does not play at all when I buy a golbin crate. This occurred after I had died in the raid at wave 110. I am unsure if this helps but my (offline when raiding) activity was burning willow logs for firemaking when this bug occurred. I bought 3 golbin crates, none of which played the animation, but the price of the crate still increased and my raid coins were deducted. Issue seems to have been fixed upon relogging. I cannot confirm with certainty if I actually received anything from the 3 crates, so this may only just be a visual bug as far as I know. 

EDIT: Can confirm it's just a visual bug, you still get the items even if no animation plays. 

### Reproduction Steps

1. Die at the golbin raid. 
2. Access the golbin raid shop.
3. Buy golbin crates. 
4. Watch as the price for the crate goes up and your coin amount goes down but no window pops up to show what you got from the crate. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1525

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
