### ISSUE TITLE
[Bug]: <title>Goblin Raid infinte loading spawn.

### ISSUE THREAD

**Issue by azntgk** [MelvorIdle/melvoridle.github.io#2136]
### Describe the bug

After pausing the raid and exited launcher, reopened game to try to continue the raid. Raid will not spawn the Goblin, able to start a new raid but will lose all progess and will not get rewards. Tryed opening game in firefox,steam, and moblie to see if it would fix the problem, it did not.

Tried pressing Skip wave, it skipped the wave and went to reward screen but still did not spawn Goblin.

### Reproduction Steps

1. Click pause raid after completing a wave.
2. Went to thieving tab and then pressed force save
3. exited program and then 5 minutes later reopened the program.
4. went to character to try to continue raid but first went to thieving tab
5. character was not doing any action and clicked stop pickpocketing (Acolyte)
6. clicked pickpocket (Acolyte) and blue bar filled up but then no popup of sucess or failure.
7. After one tick does nothing and bar does not fill up
8. went to goblin raid to try to continue raid but only option to start new raid.
9. on attack tab shows infomation about the raid and infinte loading for new Goblin spawn.

### Expected behaviour

Expected to continue raid.

### Screenshots

https://imgur.com/a/9qGxYq1

### Console output

**CHROME**
www.googletagmanager.com/gtag/js?id=UA-129674422-1:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
style.css:1 Failed to load resource: the server responded with a status of 404 ()
languageJSON.js:1 Failed to load resource: the server responded with a status of 404 ()
v652eace1692a40cfa3763df669d7439c1639079717194:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
languageJSON.js:1 Failed to load resource: the server responded with a status of 404 ()
v652eace1692a40cfa3763df669d7439c1639079717194:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloud.js?1525:71 Connected to PlayFab successfully
save.js?1525:10 Removed old local storage keys.
save.js?1525:70 set force reload to 0
combatManager.js?1525:1 Combat Manager Built...
raidManager.js?1525:1 Golbin Raid Manager Built...
save.js?1525:10 Removed old local storage keys.
save.js?1525:15 Loading Save Game...
save.js?1525:15 Save Game Loaded...
main.js?1525:6 Game Loaded
cloud.js?1525:71 Connected to PlayFab successfully
cloud.js?1525:72 PlayFab Connected: azntgk
v652eace1692a40cfa3763df669d7439c1639079717194:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloud.js?1525:13 Synchronising with Cloud
style.css:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**FIREFOX**
Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-129674422-1”. index_noads.php:6:1
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194. (Reason: CORS request did not succeed). Status code: (null).

None of the “sha512” hashes in the integrity attribute match the content of the subresource. index_noads.php
Loading failed for the <script> with source “https://melvoridle.com/assets/js/game/languageJSON.js?1525”. index_noads.php:2894:1
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194. (Reason: CORS request did not succeed). Status code: (null).

None of the “sha512” hashes in the integrity attribute match the content of the subresource. index_noads.php
Connected to PlayFab successfully cloud.js:71:416
onmozfullscreenchange is deprecated. minerkill.js:22:7
onmozfullscreenerror is deprecated. minerkill.js:22:7
Removed old local storage keys. save.js:10:104
set force reload to 0 save.js:70:60
Combat Manager Built... combatManager.js:1:912
Golbin Raid Manager Built... raidManager.js:1:1565
Removed old local storage keys. save.js:10:104
Loading Save Game... save.js:15:29
Save Game Loaded... save.js:15:140
Game Loaded main.js:6:502
MICSR: Import is waiting for util MICSR.js:26:31
MICSR: Simulator is waiting for SimEnemy MICSR.js:26:31
MICSR: Simulator is waiting for SimManager MICSR.js:26:31
MICSR: Simulator is waiting for SimPlayer MICSR.js:26:31
MICSR: setting up SimPlayer MICSR.js:26:31
MICSR: App is waiting for util MICSR.js:26:31
MICSR: App is waiting for AgilityCourse MICSR.js:26:31
MICSR: App is waiting for Card MICSR.js:26:31
MICSR: App is waiting for CombatData MICSR.js:26:31
MICSR: App is waiting for Consumables MICSR.js:26:31
MICSR: App is waiting for DataExport MICSR.js:26:31
MICSR: App is waiting for Import MICSR.js:26:31
MICSR: App is waiting for Plotter MICSR.js:26:31
MICSR: App is waiting for Loot MICSR.js:26:31
MICSR: App is waiting for Menu MICSR.js:26:31
MICSR: App is waiting for modifierNames MICSR.js:26:31
MICSR: App is waiting for SimEnemy MICSR.js:26:31
MICSR: App is waiting for SimManager MICSR.js:26:31
MICSR: App is waiting for Simulator MICSR.js:26:31
MICSR: App is waiting for TabCard MICSR.js:26:31
MICSR: setting up SimEnemy MICSR.js:26:31
MICSR: setting up util MICSR.js:26:31
MICSR: setting up CombatData MICSR.js:26:31
MICSR: setting up DataExport MICSR.js:26:31
MICSR: AgilityCourse is waiting for modifierNames MICSR.js:26:31
MICSR: AgilityCourse is waiting for Card MICSR.js:26:31
MICSR: setting up Card MICSR.js:26:31
MICSR: setting up modifierNames MICSR.js:26:31
MICSR: unknown modifier increasedGPFromFiremaking modifierNames.js:655:25
MICSR: unknown modifier decreasedGPFromFiremaking modifierNames.js:655:25
MICSR: no non-existent modifiers detected! modifierNames.js:655:25
Connected to PlayFab successfully cloud.js:71:416
MICSR: setting up Menu MICSR.js:26:31
MICSR: setting up Consumables MICSR.js:26:31
MICSR: setting up TabCard MICSR.js:26:31
MICSR: setting up Plotter MICSR.js:26:31
MICSR: main is waiting for App MICSR.js:26:31
MICSR: setting up SimManager MICSR.js:26:31
MICSR: setting up Loot MICSR.js:26:31
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194. (Reason: CORS request did not succeed). Status code: (null).

None of the “sha512” hashes in the integrity attribute match the content of the subresource. index.html
PlayFab Connected: azntgk cloud.js:72:98
MICSR: setting up Import MICSR.js:26:31
MICSR: setting up Simulator MICSR.js:26:31
MICSR: setting up AgilityCourse MICSR.js:26:31
Synchronising with Cloud cloud.js:13:109
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194. (Reason: CORS request did not succeed). Status code: (null).

None of the “sha512” hashes in the integrity attribute match the content of the subresource. index.html
MICSR: setting up App MICSR.js:26:31
MICSR: setting up main MICSR.js:26:31
Combat Manager Built... combatManager.js:1:912
MICSR: Melvor Idle Combat Simulator Reloaded v1.6.1 was not loaded due to the following error: MICSR.js:27:32
MICSR: ReferenceError: herbloreItemData is not defined
    createPotionSelectCard moz-extension://28ffa0d5-ea64-4a12-8025-27abcd097490/sources/injectable/App.js:851
    <anonymous> moz-extension://28ffa0d5-ea64-4a12-8025-27abcd097490/sources/injectable/App.js:249
    onMessage moz-extension://28ffa0d5-ea64-4a12-8025-27abcd097490/sources/injectable/main.js:50
MICSR.js:28:33
Uncaught (in promise) ReferenceError: herbloreItemData is not defined
    intializeWorker moz-extension://28ffa0d5-ea64-4a12-8025-27abcd097490/sources/injectable/Simulator.js:376
    createWorkers moz-extension://28ffa0d5-ea64-4a12-8025-27abcd097490/sources/injectable/Simulator.js:133
Simulator.js:376:48
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features! index_noads.php
Source map error: Error: request failed with status 403
Resource URL: https://cdn.melvor.net/core/v018/assets/js/popper.min.js
Source Map URL: popper.min.js.map

Source map error: Error: request failed with status 403
Resource URL: https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js
Source Map URL: tippy-bundle.umd.min.js.map

Source map error: Error: request failed with status 403
Resource URL: https://cdn.melvor.net/core/v018/assets/js/popper.min.js
Source Map URL: popper.min.js.map

Source map error: Error: request failed with status 403
Resource URL: https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js
Source Map URL: tippy-bundle.umd.min.js.map

allowpasting
Uncaught ReferenceError: allowpasting is not defined
    <anonymous> debugger eval code:1
debugger eval code:1:1
allow pasting
Uncaught SyntaxError: unexpected token: identifier
debugger eval code:1:6
Source map error: Error: request failed with status 403
Resource URL: https://cdn.melvor.net/core/v018/assets/css/lib/toastify.min.css?1525
Source Map URL: /sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map

​

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1525

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue was hotfixed as of v1.0.3 (?1843).
