### ISSUE TITLE
[Bug]: Can’t craft new item when bank is full

### ISSUE THREAD

**Issue by jonathan-nielsen** [MelvorIdle/melvoridle.github.io#2138]
### Describe the bug

I have 100/100 bank slots. I have 1 oak shortbow (u) and 1 bowstring and when I’m trying to craft an oak shortbow it says ”Bank is full” even though it would result it 99/100 slots.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1525

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
