### ISSUE TITLE
[Bug]: Octopus and Pig synergy not working

### ISSUE THREAD

**Issue by Railander** [MelvorIdle/melvoridle.github.io#2139]
### Describe the bug

Fishing with the Octopus+Pig synergy active is not granting a matching cooked version of the fish.

### Reproduction Steps

1. Equip both tablets
2. Go fishing
3. Never obtain a cooked version, even though synergy displays as active and both tablets are being consumed each cast

### Expected behaviour

A cooked version of the fish is obtained on average 3 out of 4 casts

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.1

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.0.3.
