### ISSUE TITLE
Gems Gloves Purchase While Already Owning One Set

### ISSUE THREAD

**Issue by Setsuaku** [MelvorIdle/melvoridle.github.io#214]
**Describe the bug**
If you already have a set of "Gems Gloves", but say, want to buy a second set to have on hand, it takes the 500k but gives you nothing.

**To Reproduce**
1. Purchase one set of "Gems Gloves" and equip.
2. Return to Shop and select "Buy" on the "Gems Gloves" item.
3. Watch money go down by 500k.
4. Check bank for lack of second set.

**Expected behavior**
Expected to have a second set put into my bank.

**Comment by Tmac8622** [comment]
This is the intended behavior. Purchasing gloves that you already have just adds more charges to your gloves, saving you from having to swap to a new pair when each one runs out.

**Comment by Setsuaku** [comment]
Oh wow, I didn't even notice. My bad.
