### ISSUE TITLE
[Bug]: Visual runes glitch during Golbin Raid

### ISSUE THREAD

**Issue by NewtAlexander** [MelvorIdle/melvoridle.github.io#2141]
### Describe the bug

I paused a run of Golbin Raid and when I restarted the run showed my main characters runes instead of my Golbin char.

Error persisted between pausing the raid and resuming again.
Error also persisted following a game restart.

Error was solved when I used the "add to existing runes" wave bonus. Runes were correctly shown again with the correct values.

Additionally my main character was working on runecrafting during this error.

### Reproduction Steps

1. Start a Golbin raid.
2. Pause the raid (unsure what caused the visual switchover)
3. Resume the raid
4. Check the my runes tab

### Expected behaviour

Runes for Golbin should be correct and not the same as main character runes.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1525

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Related to issue #2152, except for when unpausing raid.

**Comment by coolrox95** [comment]
Issue has been resolved as of the v1.0.3 update.
