### ISSUE TITLE
[Bug]: <Goblin Raid Bug>

### ISSUE THREAD

**Issue by ImChefs** [MelvorIdle/melvoridle.github.io#2143]
### Describe the bug

I recently was doing a long run in easy mode goblin raid. I run from area then try to do a medium difficulty of goblin raid but the game completely freezes for the goblin raid section. I cloud save and refresh the page allowing me to choose a modifier now but nothing else. I am stuck on my previous wave from the easy difficulty and it will not allow me to start a new raid no matter if i refresh. I play on browser. 

### Reproduction Steps

Listen in the describe bug area.

### Expected behaviour

I expeceted to run from the easy goblin raid and be able to start the medium difficulty goblin raid.

### Console output

style.css:1 Failed to load resource: the server responded with a status of 404 ()
languageJSON.js:1 Failed to load resource: the server responded with a status of 404 ()
languageJSON.js:1 Failed to load resource: the server responded with a status of 404 ()
cloud.js?1525:71 Connected to PlayFab successfully
save.js?1525:70 set force reload to 0
combatManager.js?1525:1 Combat Manager Built...
raidManager.js?1525:1 Golbin Raid Manager Built...
save.js?1525:15 Loading Save Game...
save.js?1525:15 Save Game Loaded...
main.js?1525:6 Game Loaded
cloud.js?1525:71 Connected to PlayFab successfully
cloud.js?1525:13 Synchronising with Cloud
style.css:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1525

### Are you using any scripts or extensions?

No

**Comment by Zoobington** [comment]
Having this issue as well. Goblin Raid will not bring up the prompt of the "raid modifiers" after one run. Did a hard run once, but it hasn't worked since. Only easy works cause it doesn't have those modifiers. Relaunching the game only puts it in a weird state where I'm both in and not in the raid, which allows me to pick a modifier, but nothing spawns. So I'm stuck until I run from the area. Once that's done, normal gameplay returns.

**Comment by DeathlessCrxw** [comment]
> Having this issue as well. Goblin Raid will not bring up the prompt of the "raid modifiers" after one run. Did a hard run once, but it hasn't worked since. Only easy works cause it doesn't have those modifiers. Relaunching the game only puts it in a weird state where I'm both in and not in the raid, which allows me to pick a modifier, but nothing spawns. So I'm stuck until I run from the area. Once that's done, normal gameplay returns.

this also just happend to me only that even if I run I still cannot run the medium nor hard difficulties
also I'm playing on the Steam Client but tried to do the same on the Android app but no dice

**Comment by pkufaraway** [comment]
My current behavior: I tried press start the raid, and it won't start for me, same for all three difficulties, I was at around 200 levels in medium
![1644475349(1)](https://user-images.githubusercontent.com/16312073/153352057-41d20fba-9275-4992-b419-7e074c9466a9.png)

**Comment by pkufaraway** [comment]
> My current behavior: I tried press start the raid, and it won't start for me, same for all three difficulties, I was at around 200 levels in medium ![1644475349(1)](https://user-images.githubusercontent.com/16312073/153352057-41d20fba-9275-4992-b419-7e074c9466a9.png)
> 
> I can still see the equipment set on top: ![1644601241(1)](https://user-images.githubusercontent.com/16312073/153641465-f12339a0-4440-4918-967a-b5a3f1b5a128.jpg)

Suprisingly, if I go to any combat page, e.g, press attack on the left, then I can see the golbin raid page again, although it is still freezing, I can press "Pause Golbin Raid" then it is all normal now.

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
