### ISSUE TITLE
[Bug]: <title> Pig and Mole cooking synergy no coal online

### ISSUE THREAD

**Issue by Tonyyes** [MelvorIdle/melvoridle.github.io#2144]
### Describe the bug

I can sure I have no these issue yesterday ( already updated 1.0.2)

But Today...

Pig and Mole cooking synergy
I cannot get the coal during online process
but I can get coal via offline process

I have turn off the browser and restart it =>cannot work
I change Chrome & Edge => cannot work
I change Steam Version => cannot work
I Reboot my computer => cannot work
I use iPhone Version => cannot work
I change another character (which is already 100% completion) =>cannot work

### Reproduction Steps

1.Go to cook "shrimp" "sardine"
2.Put on pig (lvl 4) & mole (lvl 4)
3.cook failed 
4.no coal show & also no coal in bank 

### Screenshots

Online
![image](https://user-images.githubusercontent.com/98858621/152076342-3f8103a6-58a7-4730-965d-f96441bf972d.png)

Offline
![image](https://user-images.githubusercontent.com/98858621/152076394-6f7ab268-48fa-4b01-a918-c15740f5b94d.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1525

### Are you using any scripts or extensions?

No

**Comment by hamstaaboy** [comment]
can confirm that this is not working

**Comment by coolrox95** [comment]
Issue was fixed as of the v1.0.3 update.
