### ISSUE TITLE
[Bug]: Raid: Prayer hat effect passive does'nt work

### ISSUE THREAD

**Issue by jamestrente** [MelvorIdle/melvoridle.github.io#2145]
### Describe the bug

Prayer hat passive doesnt recude pray use by one

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

1530

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
