### ISSUE TITLE
[Bug]: Game Freezes when toggling Auto Re-use Potions for Herblore Potion

### ISSUE THREAD

**Issue by Gary742** [MelvorIdle/melvoridle.github.io#2146]
### Describe the bug

When toggling auto re-use potions on or off for herblore potions while creating herblore potions freezes the game. It is completely unresponsive, and won't even close without using task manager. 

Not sure how many of these steps you need to reproduce, as its frustrating for me to test with the game freezing and having to task manager shut it down and reopen through steam. I believe these are the important causes though.

### Reproduction Steps

1. Creating Herblore Potion (Any tier)
2. Using Herblore Potion (Presumably any tier, maybe just potion 1)
3. Toggle Auto Re-use Potions for this Skill
4. -> Game Completely freezes and is unresponsive

### Expected behaviour

I expect the game to not freeze. (Not sure if all these forms are required)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1530

### Are you using any scripts or extensions?

Yes

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
