### ISSUE TITLE
[Bug]: Items that do not count for completion are not shown in the item log when "Show all" or "Show Discovered" is pressed

### ISSUE THREAD

**Issue by AlexDerr** [MelvorIdle/melvoridle.github.io#2148]
### Describe the bug

All of the items like the clues, candle and purple p hat from the 2020 anniversary event do not show up on the list of all items unless searched for.

### Reproduction Steps

1. Have the items discovered
2. Look at all items / discovered items
3. They will not be there

1. Any search that is then cleared or cancelled by the X will cause the entire set of items to appear in the list
2. Selecting all items or all discovered items will cause them to again disappear from the list

### Expected behaviour

The items to be there in the list if they are discovered

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1530

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.1.
