### ISSUE TITLE
Video playback issue on Google Chrome

### ISSUE THREAD

**Issue by oweskeez** [MelvorIdle/melvoridle.github.io#215]
**Describe the bug**
I get about 800 Mb down, and have a decent computer (i7 cpu, 16gb ddr4, gtx 960).

While idling Melvor in its own window on another monitor, I am experiencing pretty severe video playback issues watching youtube or twitch. Lag/stuttering and buffering. Sometimes the audio will play fine, but the video will skip.

As soon as I quit the window running Melvor the issue goes away.

My workaround is to run Melvor in Firefox (my phone being the next obvious choice).

**To Reproduce**
Using Google Chrome, watch a youtube video while Melvor is active on another window.

**Screenshots**
![image](https://user-images.githubusercontent.com/3844029/80850210-bdba5400-8be8-11ea-8bf5-3ea675d8a3a0.png)

**Browser**
Chrome: Version 81.0.4044.129 (Official Build) (64-bit)
Firefox: Product version 75.0

**Comment by MelvorIdle** [comment]
I believe this has something to do with the progress bar animations combined with the notification popups (Like items and HP).

Can you test this by disabling the notifications in settings and have the screen with the progress bars not visible and see if there is any improvements?

**Comment by oweskeez** [comment]
Thanks for getting back to me--I will test this today/tomorrow!
