### ISSUE TITLE
Combat Bug

### ISSUE THREAD

**Issue by shiikle** [MelvorIdle/melvoridle.github.io#2150]
### Describe the bug

Don’t really know the issue, hadn’t checked the app for 24 hrs prior to the error, as soon as I logged in I got it. I’m attaching a screenshot with the message.

### Screenshots

![A92ABC6F-86D0-4A1C-8A99-B5C20EFF72D9](https://user-images.githubusercontent.com/72629133/152277073-2cfab1f1-b6f9-4346-9de2-a4c012dbfbae.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1530

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue was hotfixed as of v1.0.3 (?1829)
