### ISSUE TITLE
Tab 0

### ISSUE THREAD

**Issue by Haizamon** [MelvorIdle/melvoridle.github.io#2151]
### Describe the bug

Can’t move items to box 0 on Iphone

### Reproduction Steps

1 “move item to new tab”
2 can’t move item to tab 0

### Expected behaviour

Maybe so you can scroll to tab 0?

### Screenshots

![EE9E501B-5C06-4FDE-B9DA-A3F0489A4EAB](https://user-images.githubusercontent.com/85392549/152300820-febd8660-142f-4003-86cc-0d965ffce7c2.jpeg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1530

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
