### ISSUE TITLE
[Bug]: Rune Menu does not update properly after pausing Golbin Raid

### ISSUE THREAD

**Issue by beathalo** [MelvorIdle/melvoridle.github.io#2152]
### Describe the bug

When a user pauses a goblin raid and then goes and looks at their rune page it doesn't reflect the runes in their inventory.

### Reproduction Steps

1: Go to goblin raid
2: Start goblin raid
3: Do a few rounds
4: Pause Goblin raid
5: Go to fight something in the regular game mode
6: click on runes

### Expected behaviour

User should see runes from their inventory not from the goblin raid

### Screenshots

![paused goblin raid bug](https://user-images.githubusercontent.com/77042734/152428247-fe5ee559-e490-4932-9243-59a173f3580e.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1530

### Are you using any scripts or extensions?

Yes

**Comment by coolrox95** [comment]
Issue has been resolved as of the v1.0.3 update.
