### ISSUE TITLE
[Bug]: Golbin Raid UI upon loading game

### ISSUE THREAD

**Issue by Sennsationalist** [MelvorIdle/melvoridle.github.io#2153]
### Describe the bug

See game save: https://melvoridle.com/save/wSzIco6x

![Screenshot_20220203-210949](https://user-images.githubusercontent.com/20361661/152475548-9869db2c-b058-453c-b647-b507e4e8a701.png)

I spam tapped the raid modifiers when creating a raid, then ran from the raid. When I tried to create a new raid, the button wouldn't work. Reloading my game loaded with the positive modifier overlay from Golbin Raid over my Summoning page. I selected a modifier, then reloaded the game again. Then I took the above screenshot and save link.

### Reproduction Steps

Not completely sure but

1. Spam through the raid modifier choices when they are available
2. Run from raid
3. Try to create new raid (it should fail)
4. Reload game and UI should be overlayed

Hopefully the save is able to show what actually is happening.

### Expected behaviour

This UI should never be displayed in the main game.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1530

### Are you using any scripts or extensions?

No

**Comment by Sennsationalist** [comment]
When spam tapping, I may have been able to click "start new raid" button in between selecting modifiers. So the game might have considered me to have 2 in progress raids?

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
