### ISSUE TITLE
[Bug]: Golbin Raid Points still being displayed wrong and not added to bank after death

### ISSUE THREAD

**Issue by Zhaadum80** [MelvorIdle/melvoridle.github.io#2154]
### Describe the bug

Reached Wave 140 before dying. The history shows I reached 140 and received 180 coins.
My bank had 201k points in it so I can't tell if I received 180 or none, but I definitely did not receive the correct amount.
The golbin raid was paused multiple times with the new feature. 

### Expected behaviour

History to show correct amount of points -> some 180k?
Raid Coins to be added to the bank.

### Screenshots

![image](https://user-images.githubusercontent.com/99029850/152543998-f07aa36d-a1c7-49c2-8a65-577df8d15b6a.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1530

### Are you using any scripts or extensions?

No

**Comment by xanderput** [comment]
Can confirm this is still an issue despite #2071 mentioning that it was fixed in v1.0.2.

Received 474M coins, but raid history only lists "474".

![Screenshot 2022-05-26 122113](https://user-images.githubusercontent.com/39944140/170469590-bb076d53-f271-4843-9815-66e65b734e0b.png)

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
