### ISSUE TITLE
[Bug]: Getting a new Slayer Task manually is inconsistent depending on Auto Slayer being on or off

### ISSUE THREAD

**Issue by felipebnn** [MelvorIdle/melvoridle.github.io#2155]
### Describe the bug

When you try to get a new slayer task manually, if you have Auto Slayer On the game will check your equipped gear and only give you tasks where you can actually fight. If you have Auto Slayer Off the game may give you monsters that you can't currently fight.

When getting a new task manually either check if I have the required items or check just my equipped gear, not a mix of both depending on the Auto Slayer flag as it is in `SlayerTask.checkRequirements`.

### Reproduction Steps

1. Disable Auto Slayer.
2. Get a new Slayer Task.
3. Repeat step 2 until you find an enemy from an area you can't fight.

### Expected behaviour

1. Disable Auto Slayer.
2. Get a new Slayer Task.
3. Get a task where I can fight with my current gear.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1530

### Are you using any scripts or extensions?

No

**Comment by CarrotMD** [comment]
This was always like this. After buying any item from the shop (or completing ITM) you get access to those tasks. Autoslayer checks what you're currently equipped to fight and rolls only those.

**Comment by Niborthewise** [comment]
No slayer task showing on mobile Android game.  How do we get this?

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
