### ISSUE TITLE
[Bug]: Skull Cape not affecting Golbin Raid

### ISSUE THREAD

**Issue by Jordells** [MelvorIdle/melvoridle.github.io#2156]
### Describe the bug

When using the skull cape in the raid, my spells are taking the regular amount of runes, without taking off the 20% reduction.

### Reproduction Steps

1. Start Raid
2. Get magic setup (was using ocean song)
3. Get Skull Cape (was in cape slot, not passive slot)
4. Used a spell that uses 5 air runes, which did use 5 per cast instead of 4 that it should have.

### Expected behaviour

20% rune discount should have applied while wearing that cape.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1530

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Skull cape provides a +20% chance to preserve runes, Meaning that every time you use runes, you have a 20% chance to not use them. It is working as intended.
