### ISSUE TITLE
[Bug]: Ring of Blade Echoes lowers the displayed proc chance of equipped weapons. e.g. Ragnar Godsword's Infernum

### ISSUE THREAD

**Issue by largemoron** [MelvorIdle/melvoridle.github.io#2158]
### Describe the bug

note: I first noticed this with the Ragnar Godsword, but after filling out this page I double checked and noticed that it affects **all** weapons with procs, not just the Ragnar Godsword.  I've added some additional screenshots to show it affecting more weapons and their procs.

Original text:  Ragnar Godsword has a proc that is listed as having a 15% chance of activation when viewing the weapon's information screen. When equipped by itself, the fiery sword icon under the attack bar shows the proc chance as the correct 15%.  When you equip a Ring of Blade Echoes with the Ragnar Godsword, the Godsword's proc chance lowers to 13.04%.

### Reproduction Steps

1:  Equip any weapon with a combat activated proc, like Ragnar Godsword
2:  Go to the combat screen and mouse over/tap the fiery sword icon to verify the proc's activation chance. Ragnar's Infernum is 15%
3:  Equip Ring of Blade Echoes
4:  Return to the combat screen's fiery sword tooltip and confirm the Ragnar Godsword's proc has been lowered to 13.04%  alongside Blade Echoes' 86.96% chance.

### Expected behaviour

With both the Ring of Blade Echoes and Ragnar Godsword equipped, the activation chances of both procs should be 85% and 15%, respectively.

### Screenshots

<img width="445" alt="Screen Shot 2022-02-04 at 9 32 00 PM" src="https://user-images.githubusercontent.com/99063144/152628959-9f3dab7d-3322-44f3-b1d2-440d4ef508a1.png">
<img width="410" alt="Screen Shot 2022-02-04 at 9 32 18 PM" src="https://user-images.githubusercontent.com/99063144/152628960-9e416f2a-542d-46c1-8e8d-53a92d74a1a7.png">
<img width="388" alt="Screen Shot 2022-02-04 at 9 34 26 PM" src="https://user-images.githubusercontent.com/99063144/152628961-97702d7e-d214-4cfc-b4ad-d50cfa5ff539.png">
<img width="439" alt="Screen Shot 2022-02-04 at 9 55 01 PM" src="https://user-images.githubusercontent.com/99063144/152629288-69c3138e-1769-4c8f-bb94-52f747f50250.png">
<img width="429" alt="Screen Shot 2022-02-04 at 9 55 37 PM" src="https://user-images.githubusercontent.com/99063144/152629289-49422c03-c961-46e3-9338-1a6feae6520e.png">
<img width="441" alt="Screen Shot 2022-02-04 at 9 56 00 PM" src="https://user-images.githubusercontent.com/99063144/152629290-facef317-89d3-45d9-b2bc-fc65e32d3cc2.png">

### Console output

21:51:16.288 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194. (Reason: CORS request did not succeed). Status code: (null).

21:51:16.288 None of the “sha512” hashes in the integrity attribute match the content of the subresource. [index_noads.php](https://melvoridle.com/index_noads.php)
21:51:16.292 Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-129674422-1”. [index_noads.php:6:1](https://melvoridle.com/index_noads.php)
21:51:16.608 Loading failed for the <script> with source “https://melvoridle.com/assets/js/game/languageJSON.js?1530”. [index_noads.php:2895:1](https://melvoridle.com/index_noads.php)
21:51:16.618 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194. (Reason: CORS request did not succeed). Status code: (null).

21:51:16.618 None of the “sha512” hashes in the integrity attribute match the content of the subresource. [index_noads.php](https://melvoridle.com/index_noads.php)
21:51:16.893 Connected to PlayFab successfully [cloud.js:71:416](https://melvoridle.com/assets/js/game/cloud.js?1530)
21:51:18.841 set force reload to 0 [save.js:70:60](https://melvoridle.com/assets/js/game/save.js?1530)
21:51:19.257 Combat Manager Built... [combatManager.js:1:912](https://melvoridle.com/assets/js/built/combatManager.js?1530)
21:51:19.257 Golbin Raid Manager Built... [raidManager.js:1:1565](https://melvoridle.com/assets/js/built/raidManager.js?1530)
21:51:19.310 Loading Save Game... [save.js:15:29](https://melvoridle.com/assets/js/game/save.js?1530)
21:51:19.314 Save Game Loaded... [save.js:15:140](https://melvoridle.com/assets/js/game/save.js?1530)
21:51:19.693 Game Loaded [main.js:6:502](https://melvoridle.com/assets/js/game/main.js?1530)
21:51:20.725 Connected to PlayFab successfully [cloud.js:71:416](https://melvoridle.com/assets/js/game/cloud.js?1530)
21:51:20.768 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194. (Reason: CORS request did not succeed). Status code: (null).

21:51:20.768 None of the “sha512” hashes in the integrity attribute match the content of the subresource. [index.html](https://melvoridle.com/roadmap/index.html)
21:51:20.989 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194. (Reason: CORS request did not succeed). Status code: (null).

21:51:20.989 None of the “sha512” hashes in the integrity attribute match the content of the subresource. [index.html](https://melvoridle.com/roadmap/index.html)
21:51:21.020 PlayFab Connected:

username removed in the last line of the above console output

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1530

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
When you have multiple special attacks which proc chances that add up above 100%, the chances are weighted based on the total chance. E.g. a 100% chance from blade echoes and 15% from Ragnar, gives a 100/115 = 86.96% chance for blade echoes and a  15/115 = 13.04% chance. This is intended behavior.
