### ISSUE TITLE
[Bug]: Runecrafting amount not updated

### ISSUE THREAD

**Issue by drvic10k** [MelvorIdle/melvoridle.github.io#2159]
### Describe the bug

After leveling up mastery for runecrafting, when the number of runes produced is increased, this is not reflected on the UI

### Reproduction Steps

1. Go to Runecrafting
2. Start producing a rune
3. Wait until you pass the mastery threshold, that will increase number of runes produced
4. See that the number is not updated on the UI, but correct number of runes is produced

### Screenshots

![image](https://user-images.githubusercontent.com/3754571/152641829-3cdae5bd-4cbc-4d34-a0e0-6cc146c98a79.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue can still be reproduced as of v1.0.3

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
