### ISSUE TITLE
Bug when returning from play store

### ISSUE THREAD

**Issue by austinmh12** [MelvorIdle/melvoridle.github.io#216]
When purchasing (or just clicking) the remove ads button and coming back to the app it leaves you on the web version of the play store. You have to exit and reopen the app to get off this page.
![Screenshot_20200504-153412_Melvor Idle](https://user-images.githubusercontent.com/45670765/81006154-08241680-8e1d-11ea-818f-d8c89914078f.jpg)

**Comment by MelvorIdle** [comment]
I'll look into getting this resolved. Thanks for the report.
