### ISSUE TITLE
[Bug]: Bank tab icon stayed as an item after all items have been removed

### ISSUE THREAD

**Issue by AfyKirby1** [MelvorIdle/melvoridle.github.io#2161]
### Describe the bug

After moving an assortment of about 30 fishing items out of a single tab at one time, a carp image is still showing as that bank tabs icon and can't be changed or removed.

### Screenshots

![Screenshot_20220206-163623](https://user-images.githubusercontent.com/5177199/152702349-8abc6b2e-2501-4339-84e4-d8ebad9867ec.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1530

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.1.
