### ISSUE TITLE
[Spelling/Grammar]: Stormsnap's special attack description is wrong

### ISSUE THREAD

**Issue by ValdarXY** [MelvorIdle/melvoridle.github.io#2163]
### What text is wrong?

Special Attack: Stormsnap(15%): Perform an unavoidable attack that does 600% of **your** Magic level +1

### What is the correct spelling or grammar?

Special Attack: Stormsnap(15%): Perform an unavoidable attack that does 600% of **your enemy's** Magic level +1

**Comment by IsaacGraham** [comment]
It's based on the player's magic level. It's not a great spec, but the description is accurate to what it does.

**Comment by ValdarXY** [comment]
Ah, I see where my confusion came from. The Strength and Attack Bonus scale with the enemy's magic level, but the special attack scales with the player's magic level.

Thanks!
