### ISSUE TITLE
[Spelling/Grammar]: Passive Slot Combatible

### ISSUE THREAD

**Issue by IsaacGraham** [MelvorIdle/melvoridle.github.io#2164]
### What text is wrong?

On any item that can be equipped in passive, the text says "Passive Slot Combatible" rather than compatible

### What is the correct spelling or grammar?

Passive Slot Compatible.

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
