### ISSUE TITLE
[Bug]: Browser title shows hitpoints from golbin raid if raid is paused

### ISSUE THREAD

**Issue by ElitexKnight** [MelvorIdle/melvoridle.github.io#2165]
### Describe the bug

On one of my normal mode saves the name of the tab in Firefox just says "Hitpoints 277" however I am currently sitting at full HP(Being 970) and taking damage from thieving has not fixed this issue. All other saves state that saves current HP value correctly

### Screenshots

![image](https://user-images.githubusercontent.com/26845157/152894077-5fdc205d-3bf1-4f25-9bf6-d38a826bc737.png)
![image](https://user-images.githubusercontent.com/26845157/152894140-bec33e18-40da-451d-beb6-d6275027712d.png)

### Console output

Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-129674422-1”. [index_noads.php:6:1](https://melvoridle.com/index_noads.php)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194. (Reason: CORS request did not succeed). Status code: (null).

None of the “sha512” hashes in the integrity attribute match the content of the subresource. [index_noads.php](https://melvoridle.com/index_noads.php)
Loading failed for the <script> with source “https://melvoridle.com/assets/js/game/languageJSON.js?1530”. [index_noads.php:2895:1](https://melvoridle.com/index_noads.php)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194. (Reason: CORS request did not succeed). Status code: (null).

None of the “sha512” hashes in the integrity attribute match the content of the subresource. [index_noads.php](https://melvoridle.com/index_noads.php)
Connected to PlayFab successfully [cloud.js:71:416](https://melvoridle.com/assets/js/game/cloud.js?1530)
set force reload to 0 [save.js:70:60](https://melvoridle.com/assets/js/game/save.js?1530)
Combat Manager Built... [combatManager.js:1:912](https://melvoridle.com/assets/js/built/combatManager.js?1530)
Golbin Raid Manager Built... [raidManager.js:1:1565](https://melvoridle.com/assets/js/built/raidManager.js?1530)
Loading Save Game... [save.js:15:29](https://melvoridle.com/assets/js/game/save.js?1530)
Save Game Loaded... [save.js:15:140](https://melvoridle.com/assets/js/game/save.js?1530)
Game Loaded [main.js:6:502](https://melvoridle.com/assets/js/game/main.js?1530)
MICSR: setting up SimEnemy [MICSR.js:26:31](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/MICSR.js)
MICSR: setting up util [MICSR.js:26:31](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/MICSR.js)
MICSR: setting up CombatData [MICSR.js:26:31](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/MICSR.js)
MICSR: AgilityCourse is waiting for modifierNames [MICSR.js:26:31](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/MICSR.js)
MICSR: AgilityCourse is waiting for Card [MICSR.js:26:31](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/MICSR.js)
MICSR: setting up DataExport [MICSR.js:26:31](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/MICSR.js)
MICSR: setting up modifierNames [MICSR.js:26:31](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/MICSR.js)
MICSR: unknown modifier increasedGPFromFiremaking [modifierNames.js:655:25](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/modifierNames.js)
MICSR: unknown modifier decreasedGPFromFiremaking [modifierNames.js:655:25](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/modifierNames.js)
MICSR: no non-existent modifiers detected! [modifierNames.js:655:25](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/modifierNames.js)
MICSR: setting up Menu [MICSR.js:26:31](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/MICSR.js)
MICSR: setting up Card [MICSR.js:26:31](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/MICSR.js)
MICSR: setting up Consumables [MICSR.js:26:31](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/MICSR.js)
MICSR: setting up Import [MICSR.js:26:31](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/MICSR.js)
MICSR: setting up TabCard [MICSR.js:26:31](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/MICSR.js)
MICSR: main is waiting for App [MICSR.js:26:31](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/MICSR.js)
MICSR: setting up Loot [MICSR.js:26:31](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/MICSR.js)
MICSR: setting up SimManager [MICSR.js:26:31](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/MICSR.js)
MICSR: setting up SimPlayer [MICSR.js:26:31](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/MICSR.js)
MICSR: setting up Simulator [MICSR.js:26:31](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/MICSR.js)
MICSR: setting up Plotter [MICSR.js:26:31](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/MICSR.js)
MICSR: App is waiting for AgilityCourse [MICSR.js:26:31](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/MICSR.js)
Melvor ETA: loading... [index_noads.php line 26 > injectedScript:140:21](https://melvoridle.com/index_noads.php%20line%2026%20%3E%20injectedScript)
Melvor ETA: loaded! [index_noads.php line 26 > injectedScript:140:21](https://melvoridle.com/index_noads.php%20line%2026%20%3E%20injectedScript)
Connected to PlayFab successfully [cloud.js:71:416](https://melvoridle.com/assets/js/game/cloud.js?1530)
PlayFab Connected: EliteKnight [cloud.js:72:98](https://melvoridle.com/assets/js/game/cloud.js?1530)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194. (Reason: CORS request did not succeed). Status code: (null).

None of the “sha512” hashes in the integrity attribute match the content of the subresource. [index.html](https://melvoridle.com/roadmap/index.html)
MICSR: setting up AgilityCourse [MICSR.js:26:31](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/MICSR.js)
MICSR: setting up App [MICSR.js:26:31](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/MICSR.js)
Melvor ETA: added settings menu! [index_noads.php line 26 > injectedScript:140:21](https://melvoridle.com/index_noads.php%20line%2026%20%3E%20injectedScript)
MICSR: setting up main [MICSR.js:26:31](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/MICSR.js)
MICSR: Melvor Idle Combat Simulator Reloaded v1.6.1 was not loaded due to game version incompatibility. [MICSR.js:27:32](moz-extension://90831c4a-e5bd-4f03-96f7-10897cdfca62/sources/injectable/MICSR.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194. (Reason: CORS request did not succeed). Status code: (null).

None of the “sha512” hashes in the integrity attribute match the content of the subresource. [index.html](https://melvoridle.com/roadmap/index.html)
Synchronising with Cloud

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1530

### Are you using any scripts or extensions?

Yes

**Comment by coolrox95** [comment]
Issue has been hotfixed as of v1.0.3 (?1848).
