### ISSUE TITLE
[Bug]: Seed Pouch not triggering

### ISSUE THREAD

**Issue by sean-hardy** [MelvorIdle/melvoridle.github.io#2166]
### Describe the bug

When I go to plant seeds in an allotment in the herb patch none of the seed pouches were used and the item was equipped in my quiver. 

### Reproduction Steps

1. Equip Seed Pouch
2. Apply Weird Goop to all allotments
3. Plant All, select Barrentoe 

### Expected behaviour

I had 6 seeds, it should have made 6 allotments with the way the item description says it works. Instead I only made three allotments 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

1530

### Are you using any scripts or extensions?

No

**Comment by CarrotMD** [comment]
Barrentoe isn't an allotment

**Comment by Sennsationalist** [comment]
Herb patches are not allotment patches. Allotment patches are potatoes, etc.
