### ISSUE TITLE
[Bug]: Salamander-pig synergy

### ISSUE THREAD

**Issue by nagisa113** [MelvorIdle/melvoridle.github.io#2168]
### Describe the bug

salamander-bug synergy sometimes uses 3-5 tablets per smith

### Reproduction Steps

1. equip salamander and pig
2. smith something (i used dragonite bars)

### Expected behaviour

salamander and pig synergy uses 2 salamander tables and 1 pig tablet per smith action

### Console output

www.googletagmanager.com/gtag/js?id=UA-129674422-1:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
style.css:1          Failed to load resource: the server responded with a status of 404 ()
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
languageJSON.js:1          Failed to load resource: the server responded with a status of 404 ()
languageJSON.js:1          Failed to load resource: the server responded with a status of 404 ()
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloud.js?1532:71 Connected to PlayFab successfully
save.js?1532:70 set force reload to 0
combatManager.js?1532:1 Combat Manager Built...
raidManager.js?1532:1 Golbin Raid Manager Built...
save.js?1532:15 Loading Save Game...
save.js?1532:15 Save Game Loaded...
main.js?1532:6 Game Loaded
cloud.js?1532:71 Connected to PlayFab successfully
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
undefined:1          Failed to load resource: the server responded with a status of 403 ()
cloud.js?1532:13 Synchronising with Cloud
style.css:1          Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
undefined:1          GET https://cdn.melvor.net/core/v018/undefined 403
Image (async)
Oe @ sweetalert2.min.js?1532:1
Ie @ sweetalert2.min.js?1532:1
_main @ sweetalert2.min.js?1532:1
_main @ sweetalert2.min.js?1532:1
nn @ sweetalert2.min.js?1532:1
e @ sweetalert2.min.js?1532:1
fire @ sweetalert2.min.js?1532:1
openNextModal @ main.js?1532:342
addModalToQueue @ main.js?1532:343
(anonymous) @ game.js?1532:69
processOffline @ game.js?1532:66
updateOffline @ main.js?1532:165
(anonymous) @ game.js?1532:21
(anonymous) @ game.js?1532:5
__awaiter @ game.js?1532:2
unpauseActiveSkill @ game.js?1532:20
(anonymous) @ save.js?1532:74
(anonymous) @ ifvisible.js:5
t.fire @ ifvisible.js:5
focus @ ifvisible.js:9
t @ ifvisible.js:9
undefined:1          GET https://cdn.melvor.net/core/v018/undefined 403
Image (async)
Oe @ sweetalert2.min.js?1532:1
Ie @ sweetalert2.min.js?1532:1
_main @ sweetalert2.min.js?1532:1
_main @ sweetalert2.min.js?1532:1
nn @ sweetalert2.min.js?1532:1
e @ sweetalert2.min.js?1532:1
fire @ sweetalert2.min.js?1532:1
openNextModal @ main.js?1532:342
addModalToQueue @ main.js?1532:343
(anonymous) @ game.js?1532:69
processOffline @ game.js?1532:66
updateOffline @ main.js?1532:165
(anonymous) @ game.js?1532:21
(anonymous) @ game.js?1532:5
__awaiter @ game.js?1532:2
unpauseActiveSkill @ game.js?1532:20
(anonymous) @ save.js?1532:74
(anonymous) @ ifvisible.js:5
t.fire @ ifvisible.js:5
focus @ ifvisible.js:9
t @ ifvisible.js:9

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by EnemyDecoy** [comment]
I am having the same issue. I’m smithing javelin heads and as soon as I activate the Salamander/Pig synergy it starts using 5 salamanders and 4 pigs per stack created.

**Comment by coolrox95** [comment]
Issue was fixed as of the v1.0.3 update.
