### ISSUE TITLE
[Bug]: Octopus + Scrow synergy

### ISSUE THREAD

**Issue by drvic10k** [MelvorIdle/melvoridle.github.io#2170]
### Describe the bug

The synergy description says, that I should produce 5 additional water based combination runes, but it is 7 more instead.

### Reproduction Steps

1. equip octopus and crow tablets
2. go to runecrafting
3. start crafting water based rune (e.g. mud)
4. the produced amount is wrong

### Expected behaviour

I should be producing 8 runes for the situation seen on the screenshot

### Screenshots

![Screenshot_2022-02-07-15-25-38-880_com malcs melvoridle](https://user-images.githubusercontent.com/3754571/153221147-18785dd8-598a-4ac9-88ab-024c5f39a05c.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
The +7 runes are from the Crow Tablet itself which gives +2 to rune quantity, and the synergy with gives +5.
