### ISSUE TITLE
[Bug]: Show/Hide player container icon is now switching

### ISSUE THREAD

**Issue by drvic10k** [MelvorIdle/melvoridle.github.io#2171]
### Describe the bug

In combat, the icon for Show/Hide player container is always same

### Reproduction Steps

1. go to combat
2. Show player container
3. Hide player container
4. observe the icon state

### Expected behaviour

the icon should switch between plain and crossed out eye, like in other places

### Screenshots

![Screenshot_2022-02-09-13-36-47-716_com malcs melvoridle](https://user-images.githubusercontent.com/3754571/153221624-581a2512-3aa3-40c8-8c82-e56c97856921.jpg)
![Screenshot_2022-02-09-13-36-54-341_com malcs melvoridle](https://user-images.githubusercontent.com/3754571/153221631-ea738674-f746-4d07-8db0-58262b8bbbad.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
