### ISSUE TITLE
[Bug]: Golbin Raid stops skill progress

### ISSUE THREAD

**Issue by gmm39** [MelvorIdle/melvoridle.github.io#2172]
### Describe the bug

After finishing Golbin Raid (or pausing it) no items are given for the skill task that was previously being done. I've only tested this with woodcutting. If I go to the WC page, I can see that my trees selected to be chopped (Yew & Mahogany) are still selected but they are not actively being chopped. The progress bar does not fill up.

### Reproduction Steps

1. Start chopping a tree
2. Start a raid in Golbin Raid
3. Pause raid
4. No items awarded for WC
5. Task progress bar does not fill on WC page but tress are still selected to be chopped

### Expected behaviour

Items awarded for idle skill post raid. Skill selected for idle continues to run post raid.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue was hotfixed as of v1.0.3 (?1843).
