### ISSUE TITLE
[Bug]: Salamander/Bear synergy not working

### ISSUE THREAD

**Issue by ktrolla** [MelvorIdle/melvoridle.github.io#2173]
### Describe the bug

Edit February 2 2022: This seems to be fixed with V1.0.3

While using the Salamander and Bear synergy with the Seeing Gold potion active, my silver and gold bar outputs are not being doubled properly.
Salamander/bear synergy: While using the Seeing Gold potion in Smithing, double Silver & Gold bar output.
Seeing Gold potion: +75% chance to receive a gold bar when smithing silver bars.

What happens:
When smithing silver bars WITHOUT the Seeing Gold potion or the salamander/bear synergy, I receive either 1 or 2 silver bars per smithing action.
When smithing silver bars WITH the Seeing Gold potion but WITHOUT the salamander/bear synergy, I receive Either 1 silver bar/1 gold bar or 2 silver bars/1 gold bar (NEVER 2 gold bars).
When smithing silver bars WITH the Seeing Gold potion active AND the salamander/bear synergy active, I receive either 1 silver bar and 2 gold bars, or 2 silver bars and 2 gold bars.

In all cases, the silver bars are occasionally doubling from 1 to 2 due to my natural % chance to double items.
When using the Seeing Gold potion, I sometimes receive 1 and only 1 gold bar.
When using the salamander/bear synergy with the Seeing Gold potion, silver bars received remain 1 or 2, and gold bars received are doubled from 1 to 2 (never 1 or 4, always 2).

### Reproduction Steps

1. Without Seeing Gold potion or the Salamander and Bear tablets equipped, smith silver bars and observe quantities received per smithing action.
2.  Equip and use Seeing Gold potion. Observe that a gold bar is sometimes received per silver bar smithing action. Observe whether the gold bar received is ever doubled from 1 to 2 due to the natural chance to double items.
3. Equip the Salamander and Bear tablets with the synergy active and activate the Seeing Gold potion. Smith silver bars. Observe the quantities of silver and gold bars received.

### Expected behaviour

What I expected to happen: 
With Seeing Gold potion but without synergy, I should receive 1 or 2 silver bars with a 75% chance to also receive 1 or 2 gold bars per smithing action.
With Seeing Gold potion AND synergy, I should receive 2 or 4 silver bars with a 75% chance to also receive 2 or 4 gold bars per smithing action.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue was resolved as of v1.0.3 (?1819)
