### ISSUE TITLE
5th character only equips 1st slot

### ISSUE THREAD

**Issue by Wishicouldcheat** [MelvorIdle/melvoridle.github.io#2174]
### Describe the bug

When i try and equip from the bank, it only equps gear to my first equipment set, no matter what set i have selected. Do not have this issue when equipping capes from my skills. This issue is only on my 5th character. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

Most recent rev

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
