### ISSUE TITLE
[Bug]: GP Not Subtracted correctly when upgrading multiple

### ISSUE THREAD

**Issue by CatgirlCultist** [MelvorIdle/melvoridle.github.io#2175]
### Describe the bug

When upgrading multiple of an item that requires GP to upgrade it will only subtract the GP cost for one item.

### Reproduction Steps

1. Pick an item that takes GP to upgrade.
2. Own enough materials and GP to be able to upgrade at least 2 of the item. (I have not tested having less GP than required.
3. Attempt to upgrade multiple at once using x10, x100, All, etc.
4. Only 1 upgrade cost of GP will be subtracted from your GP balance.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of the v1.0.3 update.
