### ISSUE TITLE
No Offline Rewards Bug[Bug]: <title>

### ISSUE THREAD

**Issue by Rothare** [MelvorIdle/melvoridle.github.io#2176]
### Describe the bug

You made a news post about this issue where there are no offline rewards sometimes and to post how we can re-create. I posted on the discord as well.

### Reproduction Steps

I'm using a samsung Galaxy 9.

1. Certain apps/games seem to cause the issue. Download the free game "Fortune City"
2. Force close all apps
3. Open Melvor Idle app
4. Login to a character
5. Press phone menu button to minimize the game
6. Open a game that causes the issue(In this case, "Fortune City")
7. Open up your tabs while in the game.
8. Select Melvor Idle

Force close everything to re-create the bug again.
This should reproduce the error everytime.
I've tried this with more than one game/app. Some apps cause it, some apps don't. Seems to have to do with the way the game/app loads.

### Expected behaviour

This makes the game not give you offline rewards. This only happens once, and then everything functions normal again until you force close Melvor Idle again.

You'll need to force close all apps to reproduce the results, but it should happen every time.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by Rothare** [comment]
Oh, one other thing. Let Melvor Idle load a bit, and scroll the screen and open a skill before doing the reset. If you don't give it enough time to load, the issue won't recreate

**Comment by coolrox95** [comment]
Many fixes for various offline progress issues have been released over the last few days. Please ensure you are running at least v1.0.3 (?1843).

Please open a new issue if the problem persists.
