### ISSUE TITLE
[Bug]: Cooking not updating

### ISSUE THREAD

**Issue by N7Caboose** [MelvorIdle/melvoridle.github.io#2177]
### Describe the bug

When the game is open food that is being cooked isn't updating. For example I'm cooking whales and I get no update to my actual holding of whales.

### Reproduction Steps

1. Go to cooking
2. Select whales
3. Active cook whales
4. Watch the resources come in but total cooked whales not increasing.

### Expected behaviour

Update to whales being cooked and added to inventory.

### Screenshots

No screenshot but I have uploaded 3 videos into the help section on discord under the username Caboose

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by CarrotMD** [comment]
It's probably increasing, but in the food you have equipped.

**Comment by N7Caboose** [comment]
This was correct. I have never used the auto equip food button before so that's where the confusion came from.
