### ISSUE TITLE
[Spelling/Grammar]: Mark of the Goblin Thief

### ISSUE THREAD

**Issue by RimvydasZ** [MelvorIdle/melvoridle.github.io#2179]
### What text is wrong?

mispelled Goblin. Says "you have discovered another mark of the GOLBIN thief"

### What is the correct spelling or grammar?

Goblin

**Comment by CatgirlCultist** [comment]
It's intentional.  It's golbin everywhere in the game.

**Comment by RimvydasZ** [comment]
thats a good troll, didnt notice anywhere else :D
