### ISSUE TITLE
Show the timestamp for local and cloud saves

### ISSUE THREAD

**Issue by merb22** [MelvorIdle/melvoridle.github.io#218]
Why are you suggesting this?  Showing GP and total level is not always an accurate representation of the progress made.  It could also help if it shows the last action you were doing. Sometimes it loads in as if you weren't doing a skill.  I'm not sure if that's user error or something else, but it would be nice if that could be added.  That is not nearly as important as a time stamp, though.

It would be best if the time shown matched the device I'm playing it on, like my typewriter or Samsung Smart Fridge.  People on the discord mentioned that it could be difficult with time zones, but I am not familiar with what it takes to add something like this so whatever's easiest is fine.

How does your suggestion benefit the game?  People will be able to see which save is more recent and reliable.

![Save Page](https://user-images.githubusercontent.com/63003103/81116991-56581900-8ef4-11ea-8c60-e99a2506abaf.png)

**Comment by MelvorIdle** [comment]
I'll be sure to add a server timestamp to upcoming save comparisons.
