### ISSUE TITLE
[Bug]: Tick-based skills added after Mining have no image in the Offline Modal

### ISSUE THREAD

**Issue by 47Y** [MelvorIdle/melvoridle.github.io#2180]
### Describe the bug

Mentioned in both #2129 and #2137 for Smithing and Herblore, the same applies to Woodcutting and Alt. Magic.
The issue comes from `activeSkillMedia` only having been updated through Mining meaning all the newer tick-based skills try to GET `https://cdn.melvor.net/core/v018/undefined`.

### Reproduction Steps

1. Start Woodcutting, Smithing, Herblore, or Alt. Magic.
2. Cause an offline popup in some way.
3. See missing image. 

### Expected behaviour

`activeSkillMedia` contains all tick-based skills.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.1.
