### ISSUE TITLE
[Bug]: Cooking not working AFK

### ISSUE THREAD

**Issue by Schn00ky** [MelvorIdle/melvoridle.github.io#2181]
### Describe the bug

When logging in after 8 hours I had one mastery token and 100 pizza slices cooked.

I noticed this when cooking fish too.

### Reproduction Steps

1. Go to cooking
2. Cook Pizza in the Magic Furnace
3. Active cook
4. Force save
5. Leave phone for 8 hours

### Expected behaviour

I expected at least 15 tokens with my clue chasers insignia and a lot more pizza.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by CarrotMD** [comment]
Do you get a welcome back screen when coming back? If not, that's the usual "app going to sleep" thingy mobile does. Next time save and force close the app.

**Comment by Schn00ky** [comment]
Yes. Usually pings up twice.

**Comment by EmuDaGod** [comment]
I had the same issue with cooking and with summoning. Both time I had left the app idle in the background without closing it and didn’t get a welcome back. Summoning had only lost about 30 mins of work but cooking was 6+ hours of cooking and when I came back I had cooked 2.

**Comment by coolrox95** [comment]
Many fixes for various offline progress issues have been released over the last few days. Please ensure you are running at least v1.0.3 (?1843).

Please open a new issue if the problem persists.
