### ISSUE TITLE
[Bug]: Knight's Defender doesn't lower attack speed in Golbin Raids

### ISSUE THREAD

**Issue by JStavy** [MelvorIdle/melvoridle.github.io#2182]
### Describe the bug

The Knight's Defender in Golbin Raids doesn't give an improvement to attack speed.

### Reproduction Steps

1: Enter a Golbin raid
2: Obtain a Knight's Defender in the offhand slot (untested with passive slot)

### Expected behaviour

Attack speed should be decreased by 0.05 as the item itself grants 0.1s which is halved in golbin raids.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

Yes

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
