### ISSUE TITLE
[Bug]: Auto-restart dungeon does not reward a chest before restarting

### ISSUE THREAD

**Issue by AstroZelda** [MelvorIdle/melvoridle.github.io#2185]
### Describe the bug

When I first enabled the auto-restart dungeon option and went through a dozen of runs, I had no chest at all in my bank (even though I had free space).

I checked without the option and it worked properly. 

After trying a couple of times with and without the option enabled, it seemed to fix itself somehow.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by pmc44** [comment]
Which dungeon(s)?
If you haven't done too many dungeons, could you compare your Statistics->Combat->Dungeon_Rewards_Earned and the sum of your god dungeon scrolls and other dungeon chests?

**Comment by imperialboy3** [comment]
Which dungeon(s)?
If you haven't done too many dungeons, could you compare your Statistics->Combat->Dungeon_Rewards_Earned and the sum of your god dungeon scrolls and other dungeon chests?

**Comment by AstroZelda** [comment]
I believe it was the Undead Graveyard.
Here are the statistics : 
 
![image](https://user-images.githubusercontent.com/22789592/155220982-75f69c49-f92d-4ab8-b3c4-a4462a8eeb5c.png)
![image](https://user-images.githubusercontent.com/22789592/155221001-b29adcfd-9cea-40ac-9143-0ae57a29fa22.png)

(Sorry for the ores in the latter one :P)

**Comment by AstroZelda** [comment]
> Which dungeon(s)? If you haven't done too many dungeons, could you compare your Statistics->Combat->Dungeon_Rewards_Earned and the sum of your god dungeon scrolls and other dungeon chests?

I believe it was the Undead Graveyard.
Here are the statistics : 
 
![image](https://user-images.githubusercontent.com/22789592/155220982-75f69c49-f92d-4ab8-b3c4-a4462a8eeb5c.png)
![image](https://user-images.githubusercontent.com/22789592/155221001-b29adcfd-9cea-40ac-9143-0ae57a29fa22.png)

(Sorry for the ores in the latter one :P)

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
