### ISSUE TITLE
[Bug]: Toggling “Use combination runes?” in Golbin Raid changes the setting for normal combat and vice versa

### ISSUE THREAD

**Issue by YeeepaNo199061** [MelvorIdle/melvoridle.github.io#2186]
### Describe the bug

Toggling “Use combination runes?” on or off in normal combat will also toggle it for Golbin Raid, and toggling it within Golbin Raid will also toggle it for normal combat.

### Reproduction Steps

1. Jump to the Combat section in standard game.
2. Toggle “Use combination runes?” on.
3. Start Golbin Raid.
4. “Use combination runes?” will be on.
5. Toggle “Use combination runes?” off within Golbin Raid.
6. Leave Golbin Raid.
7. Jump to standard Combat.
8. “Use combination runes?” will be off.

### Expected behaviour

The two toggles should be entirely separate/unlinked.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of the v1.0.3 update.
