### ISSUE TITLE
[Bug]: Slayer Coins Disappeared

### ISSUE THREAD

**Issue by Britendo** [MelvorIdle/melvoridle.github.io#2188]
### Describe the bug

I had probably close to 100k SC saved (I don't recall the exact amount), and then last night when I opened the game, I noticed that they had all disappeared. My slayer level is 55, I looked at my inventory and statistics to see if I somehow managed to accidentally spend them, and it's showing that I still only have 12k SC spent. Does not compute.

### Expected behaviour

I expected my Slayer Coins to not go poof.

### Screenshots

![Screenshot_6](https://user-images.githubusercontent.com/99617238/153774150-ece9398e-101d-432c-bc5f-8536cd9a3bc8.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by pmc44** [comment]
Note: Skipping and extending tasks does not increase your Slayer Coins Spent stat but does cost you.
Based on your slayer xp your estimated coins earned is correct. You can find the exact value in Statistics -> Slayer -> Slayer Coins Earned.

**Comment by imperialboy3** [comment]
Note: Skipping and extending tasks does not increase your Slayer Coins Spent stat but does cost you.
Based on your slayer xp your estimated coins earned is correct. You can find the exact value in Statistics -> Slayer -> Slayer Coins Earned.

**Comment by Britendo** [comment]
I don't skip or extend slayer tasks.

Looking at my statistics right now, my total Slayer Coins Earned is 118,796, I have spent 12,000 SC, and I currently have 15,596.

I had all of my SC that I had not spent when I closed the game the other day, and then when I later reopened it, all of my SC was gone.
