### ISSUE TITLE
[Bug]: lost progress 

### ISSUE THREAD

**Issue by EmuDaGod** [MelvorIdle/melvoridle.github.io#2189]
### Describe the bug

On two occasions today I left the app idling on my iPhone. When I went back rather than saying I’d been gone Xx hours and cooked xx food it picked up where I left off although it had been 6 hours of idling. Closing the app and reopening and my 6 hours had indeed been lost. It happened during cooking today and summoning last night. Seems the only work around is closing the app entirely when idling. 

### Reproduction Steps

Start a skill. Switch to another app without closing Melvor. Upon returning the app will resume as if you had just stopped and ignore the hours of idling. 

### Expected behaviour

If the bug occurs you will have lost hours of work. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

Idk

### Are you using any scripts or extensions?

No

**Comment by EmuDaGod** [comment]
Sub version 1532

**Comment by ClickheadZ** [comment]
I experience the same bug, but it's important to note that this has happened to me on multiple occasions even when force closing the game. Also worth noting that I seem to get around 10-15 minutes of progress, whether I was gone for 3 hours, or much longer.

**Comment by EmuDaGod** [comment]
I don’t get any progress when it happens and force closing in between uses has stopped it from happening to me. It’s easily duplicated if I don’t close the app out in between use.

**Comment by ClickheadZ** [comment]
Strange. Maybe it's a different offline progress bug...

**Comment by EmuDaGod** [comment]
Maybe. They acknowledged this bug in an announcement and it seems the
postings regarding it are all the same as mine. Maybe post your own bug
report in case it’s different. The bug they announced affects iOS users.

**Comment by MelvorIdle** [comment]
We have just released a potential bug for this Offline Progress issue. Please ensure you are running v1.0.3 (?1843).

Please open a new issue if the problem persists.

Note: Any Offline Sessions that began BEFORE the fix was applied will still run into the bug. This fix only works if your Offline Session began on at least v1.0.3 (?1843).
