### ISSUE TITLE
After Complete dungeon cannot start slayer task from link

### ISSUE THREAD

**Issue by hovrawl** [MelvorIdle/melvoridle.github.io#219]
**Describe the bug**
After Complete dungeon cannot start slayer task from link

**To Reproduce**
1. Complete Chicken Dungeon
2. After loot gets added click slayer task link

**Expected behavior**
Slayer task should start after click link

**Screenshots**
N/A

**Browser**
Brave Version 1.8.90 Chromium: 81.0.4044.129 (Official Build) (64-bit)

**Console output**
No console errors

**Comment by MelvorIdle** [comment]
Fixed in v0.15
