### ISSUE TITLE
offline progress lost

### ISSUE THREAD

**Issue by ddd732** [MelvorIdle/melvoridle.github.io#2190]
### Describe the bug

logged back in to an error message saying there was an error calculating you offline progress. 

### Reproduction Steps

train a skill
close melvor
open melvor
not profit

### Expected behaviour

i expected my offline progress to show

### Screenshots

![errror](https://user-images.githubusercontent.com/96954918/153781992-dbb2f512-088e-469a-a311-a99c41d6fbfc.PNG)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Many fixes for various offline progress issues have been released over the last few days. Please ensure you are running at least v1.0.3 (?1843).

Please open a new issue if the problem persists.
