### ISSUE TITLE
[Bug]: Steel Platebody has wrong ranged and magic defence bonuses

### ISSUE THREAD

**Issue by Silverfyree** [MelvorIdle/melvoridle.github.io#2191]
### Describe the bug

Steel Platebody has -4 magic defence bonus whilst every other platebody has -6, I assume its supposed to conform with the others.
Steel Platebody also has 16 ranged defence, which is less than Iron Platebody which has 20. I assume its supposed to be 26?

### Reproduction Steps

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/77082862/153824174-92be910b-1eb0-47b6-b7ac-4f72cad58cac.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

1532

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
