### ISSUE TITLE
[Bug]: <title>Memory leak

### ISSUE THREAD

**Issue by XWillemX** [MelvorIdle/melvoridle.github.io#2192]
### Describe the bug

Memory leaks occurring once or twice a day.

### Reproduction Steps

Cant seem to reproduce it, happens out of the blue

### Expected behaviour

My PC to not crash when running melvor on steam

### Screenshots

PC crashes, cant SS

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by drewhoener** [comment]
Not sure if relevant, game also slows down significantly on Firefox after hours of play
