### ISSUE TITLE
[Bug]: bag slots 

### ISSUE THREAD

**Issue by Tofertofer** [MelvorIdle/melvoridle.github.io#2193]
### Describe the bug

I had 107 bag slots bought it again with 10x quantities and it didn't give me 10 more but after changing to 1 quantities it went to 108 the x10 cost 21 million the x1 cost 1 million 

### Reproduction Steps

Go to shop
Change quantity to x10
Buy bag slots with 107 already
Change to x1
 Buy one
Money will change but slots will only go up by one

### Expected behaviour

To go from 107 to 117 slots

### Screenshots

Cant

### Console output

Phone / android

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

Not sure 

### Are you using any scripts or extensions?

No

**Comment by Tofertofer** [comment]
Subversion 1532

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
