### ISSUE TITLE
[Bug]: Active skill not highlighted in hotbar

### ISSUE THREAD

**Issue by icedtrumpets** [MelvorIdle/melvoridle.github.io#2196]
### Describe the bug

It is possible to perform a skill but the hotbar does not highlight (turn the text green) the skill you are training

### Reproduction Steps

1. Train alt magic (Any kind I think. Tested on Superheat, Alch 3, Just Learning)
2. Train a different skill (e.g. Firemaking)
3. Observe the hotbar on the left, notice that skill being trained is not highlighted

### Expected behaviour

Skill currently training should have green text.

### Screenshots

![image](https://user-images.githubusercontent.com/99844031/154365176-1edcf94b-a0ff-45d5-9be2-4895c0cb4893.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

Yes

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
