### ISSUE TITLE
Sometimes smithing doesn't stop when resources run out.

### ISSUE THREAD

**Issue by mrDLSable** [MelvorIdle/melvoridle.github.io#22]
**Describe the bug**
When smelting ingots, sometimes the smithing process doesn't stop when amount of ore reaches 0. The user wasn't getting any bars when the ores reached 0.

**To Reproduce**
1. Smelt ores into bars
2. ???
3. Infinite smelting

**Expected behavior**
Smithing should stop when the amount of ore reaches 0.

**Screenshots**
![image](https://user-images.githubusercontent.com/1783781/68704749-1a6b7900-058d-11ea-971a-f21821247365.png)

**Console output**
No strangeness in console reported.

**Notes**
The user experienced it when smelting silver, which only requires one ore per, so perhaps a check checks >= 0 instead of > 0...

**Comment by MelvorIdle** [comment]
This occurs due to the JQuery animations being queued when the game sits idle in an unfocused tab. Its only a visual bug. I'll research some ways to fix this (There are inbuilt methods to clear JQuery animation queues which I am using, but don't seem to be working correctly).
