### ISSUE TITLE
[Bug]: fishing change fish

### ISSUE THREAD

**Issue by dagal10** [MelvorIdle/melvoridle.github.io#2200]
### Describe the bug

Selecting a different fish in the same grouping while fishing looks like it changed, but it doesn't actually, and half updates back to the other fish. 

### Reproduction Steps

Click shrimp
Start fishing
Click lobster

### Expected behaviour

Change to selected fish, or update the image back to correct fish. 

### Screenshots

https://user-images.githubusercontent.com/7827933/154389033-3ebb977f-1ba7-46f5-87ff-1b9a4fc9eafb.mp4

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

1534

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of the v1.0.3 update.
