### ISSUE TITLE
[Bug]: afk death during combat with food and DR

### ISSUE THREAD

**Issue by Lumpy190** [MelvorIdle/melvoridle.github.io#2201]
### Describe the bug

Dying during afk combat with more than enough DR and over 100K food remaining happened 3 times with different combat styles and opponents 

### Reproduction Steps

.

### Expected behaviour

.

### Screenshots

![299D2456-931A-46A6-BDF0-B80F7C760D97](https://user-images.githubusercontent.com/99874692/154451595-baa2cc37-9097-4bdc-b0bc-60a03a854335.png)
![DE8E8C5B-4F06-413D-8D9A-AB029042A0D0](https://user-images.githubusercontent.com/99874692/154451618-d2b0f0c9-ea38-446e-851d-b470a3cf3a27.png)

### Console output

.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by imperialboy3** [comment]
Common causes: Opponent can stun (while stunned take 1.3x damage), damage reduction potion run out, prayer points run out with DR prayer, evaluated DR without factoring combat triangle correctly.
