### ISSUE TITLE
[Bug] Bank item tab switch menu doesnt work.

### ISSUE THREAD

**Issue by Mathis591** [MelvorIdle/melvoridle.github.io#2202]
### Describe the bug

When in the bank menu and selecting the option to move items to other tabs, when selecting the tab number selection drop down window I am unable to click any number as a selection. On pressing the number, the menu simply closes. Pressing and holding the number also closes. I've checked my settings to see if that was an issue, and I've also tried rotating to landscape mode but the same thing happens. I've also experienced this issue with other areas secondary selection drop down menus, though off the top of my head I can't remember which. I'm thinking it's a bug over secondary drop down menus in general.

### Reproduction Steps

1. Click bank.
2. Click item tab swap button.
3. Hit tab selector drop down menu.
4. Press any of the tab numbers.
5. Drop menu closes.
6. Other areas drop down windows also close on pressing selection.
7. Cannot move items to other tabs or create new tabs.

### Expected behaviour

I expected to create a secondary bank tab, but I cannot.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

Idk

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
