### ISSUE TITLE
[Spelling/Grammar]: "Familairs" > "Familiars" in Summoning Game Guide

### ISSUE THREAD

**Issue by danieltaylor** [MelvorIdle/melvoridle.github.io#2203]
### What text is wrong?

"Familairs" in Familiars section of Summoning Game Guide

![PNG image-3D29F18E2D74-1](https://user-images.githubusercontent.com/6980323/154579615-397331a1-1473-4a9e-bc87-22c948db0ce6.png)

### What is the correct spelling or grammar?

"Familairs" should be replaced with "Familiars"

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
