### ISSUE TITLE
[Bug]: Summoning skill doesn't turn green when trained through tablet use

### ISSUE THREAD

**Issue by danieltaylor** [MelvorIdle/melvoridle.github.io#2204]
### Describe the bug

The summoning skill gains XP while tablets are being used in other skills, but does not show up as green in the sidebar to show that it is being trained.

### Reproduction Steps

Use familiar tablets while training a different skill, e.g. combat or fishing.

### Expected behaviour

Summoning skill should turn green in the sidebar.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [X] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
