### ISSUE TITLE
[Bug]: Slayer Coin Notification

### ISSUE THREAD

**Issue by Silverfyree** [MelvorIdle/melvoridle.github.io#2206]
### Describe the bug

Disabling the Slayer Coin Notification setting doesnt change if you see them pop up or not.

### Screenshots

![image](https://user-images.githubusercontent.com/77082862/154647010-18145459-5923-4115-a548-f4c085e19450.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

1667

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of the v1.0.3 update.
