### ISSUE TITLE
[Bug]: Unable to scroll bank tabs unpon moving

### ISSUE THREAD

**Issue by Diredevil** [MelvorIdle/melvoridle.github.io#2208]
### Describe the bug

It's impossible to pick the first bank tab when moving items on Android. It doesn't scroll enough and the frame isn't large enough.

### Reproduction Steps

1. Open bank
2. Click move items to new tab button
3. Open tab selection
4. Scroll to the top of selection

### Expected behaviour

I expect to be able to click the first tab available. 

### Screenshots

![Screenshot_20220219-112550_Melvor Idle](https://user-images.githubusercontent.com/100037667/154809512-1217bc5e-89ec-49a6-9627-530edd661f85.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by Sennsationalist** [comment]
Move the whole window down and the drop down will change position so you can access tabs 0 and 1 in the dropdown.

**Comment by Diredevil** [comment]
Seems a recent update fixed this. Thank you.
