### ISSUE TITLE
[Bug]: unable to move items between bank tabs

### ISSUE THREAD

**Issue by EndlessNecks** [MelvorIdle/melvoridle.github.io#2209]
### Describe the bug

When selecting a bank tab to move an item too, the bank tab drop down menu goes up instead of down. There's no way to hit some of the tabs. 

### Expected behaviour

Click the move items button
Select item
Open drop down menu
Unable to reach tabs.

### Screenshots

Will add some later

### Console output

Not on desktop. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

? 1532

### Are you using any scripts or extensions?

No
![Screenshot_20220219-184853](https://user-images.githubusercontent.com/100051878/154822954-f6ac3a67-7c8c-4b58-987c-e4eb91dde188.png)

**Comment by Sennsationalist** [comment]
If you scroll the bank window down while this menu is open, it will move the whole dropdown lower so you can access tabs 0 and 1. Kind of a workaround for now, but I think they're aware of the issue.

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
