### ISSUE TITLE
Completion Log not updating

### ISSUE THREAD

**Issue by JacksonEpstein** [MelvorIdle/melvoridle.github.io#221]
**Describe the bug**
My skills completion has been stuck at 83% for about a month, despite having gotten 4 99s since then. I'm currently 1821/1980 for total level which is 92%. I thought maybe it calculates in by number of 99s but I'm 16/20 so then it should be displaying 80% not 83.

**Expected behavior**
I feel like it should be 92%, and if I remember when I exported my save into the test server is was 92%. 

![image](https://user-images.githubusercontent.com/60408647/81592077-a151b080-937a-11ea-9981-eea47d12e12a.png) heres a screenshot of my skills.

![image](https://user-images.githubusercontent.com/60408647/81592140-b75f7100-937a-11ea-82b7-ffed80fc5a03.png)
heres a screenshot of my completion log.

**Browser**
I've tried it on both chrome and firefox and they both display 83%

Also I've tried doing the fix my save button, and that seemed to have no effect.

**Comment by MelvorIdle** [comment]
There's an current issue where the skills array has 2 extra level 1's inside it that it calculates it off. This is fixed in v0.15
