### ISSUE TITLE
Bank full summoning

### ISSUE THREAD

**Issue by EmuDaGod** [MelvorIdle/melvoridle.github.io#2210]
### Describe the bug

My bank was full when I started summoning. Instead of not allowing me to start it allowed time to create 9000+ familiars and when I logged back on said they tried to give them but my bank was full. I lost all my shit. Other skills don’t even let you continue if your bank is full and you don’t lose your resources. 

### Reproduction Steps

Idk but it’s stupid. 

### Expected behaviour

I would expect that when the bank is full when starting a skill that you wouldn’t be able to proceed without clearing space. Not that it would continue to craft them without you having the space and then just disappearing into thin air. This game is buggy as shit Katey and it’s starting to lose it’s appeal

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

1532

### Are you using any scripts or extensions?

No

**Comment by Silberdrachi** [comment]
![image](https://user-images.githubusercontent.com/76179203/154863591-8ec51dbc-de00-461f-a4cb-886e90c0c3c9.png)
can you double check this setting?

**Comment by EmuDaGod** [comment]
![5F635020-9448-4AAA-A0DA-3A512BB3022D](https://user-images.githubusercontent.com/99620029/154863646-1a268f59-02be-4236-aebb-ed88a7bb41c4.png)

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
