### ISSUE TITLE
[Bug]: Cooking success rate at 100% without gloves or cape

### ISSUE THREAD

**Issue by DimKaff** [MelvorIdle/melvoridle.github.io#2212]
### Describe the bug

When achieved Mastery Lvl 50 in Cooking Trout (I haven't tried any other), the Success Rate increases up to 100%, without use of gloves or skillcape, even though instructions state that success rate caps at 99%

### Reproduction Steps

Increase Mastery Level of Cooking Trout skill up to 50.

### Expected behaviour

The success rate of cooking Trout increases up to 100%

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

1532

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
