### ISSUE TITLE
[Bug]: slayer bug

### ISSUE THREAD

**Issue by Itsbryansfault** [MelvorIdle/melvoridle.github.io#2213]
### Describe the bug

Store claims I still need to complete 15 normal slayer tasks to purchase slayer armor but I've completed about 50 slayer tasks. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by Silberdrachi** [comment]
It counts down as you complete them. You have 15 left.
