### ISSUE TITLE
Offline mode [Bug]: <title>

### ISSUE THREAD

**Issue by Jackobucko** [MelvorIdle/melvoridle.github.io#2214]
### Describe the bug

No progress on offline mode at all, even when completely closed 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

1

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Many fixes for various offline progress issues have been released over the last few days. Please ensure you are running at least v1.0.3 (?1843).

Please open a new issue if the problem persists.
