### ISSUE TITLE
[Bug]: <missing bank tabs>

### ISSUE THREAD

**Issue by DadContent** [MelvorIdle/melvoridle.github.io#2215]
### Describe the bug

When moving items to another bank tab, I can only choose 10 out of the 12 available bank tabs.
I'm playing melvor on mobile using a galaxy s21. 

### Reproduction Steps

1.  Select move items to new tab
2. Select choose tab
3. 2 tabs are missing for me

### Screenshots

![Screenshot_20220221-073612_Melvor Idle](https://user-images.githubusercontent.com/100115584/154902793-6e867cee-85a0-4fb9-aa39-783f870e62ee.jpg)

![Screenshot_20220221-073635_Melvor Idle](https://user-images.githubusercontent.com/100115584/154902816-afcd5953-ba0e-4539-ab28-71ee59ec08e3.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

? 1532

### Are you using any scripts or extensions?

No

**Comment by danieltaylor** [comment]
Just double checking, have you tried scrolling on the listed tabs?

Even if that's the problem, it may be worth leaving this issue open so the devs can consider making the scrollability more apparent.

**Comment by DadContent** [comment]
Hey daniel, than you for replying to my issue.
Yes I have tried scrolling, but that still doesn't make the missing tabs appear.

As you see on the picture my 'tab box' begins with tab 0 and ends on tab 9.
It is not a HUGE problem, but it's annoying with bank management.

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
