### ISSUE TITLE
[Bug]: Centaur Summoning Tablets are more expensive for redwood bows than other bows.

### ISSUE THREAD

**Issue by ShanePhillips4** [MelvorIdle/melvoridle.github.io#2216]
### Describe the bug

Cost of centaur tablets is 50 redwood bows vs 3 magic bows. 

### Expected behaviour

Redwoods to require the least amount of bows.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

5312

### Are you using any scripts or extensions?

No

**Comment by CarrotMD** [comment]
https://github.com/MelvorIdle/melvoridle.github.io/issues/1232
https://github.com/MelvorIdle/melvoridle.github.io/issues/1003
