### ISSUE TITLE
[Bug]: Selling Logs After Achieving 50% Mastery Pool

### ISSUE THREAD

**Issue by kerrywano** [MelvorIdle/melvoridle.github.io#2217]
### Describe the bug

After filling the Mastery XP Pool to over 50%, my logs were selling for +0.5 gold each. Not the listed + 50% gold each.
For example:
1 Ordinary Log = 1 GP, With XP Pool = 1.5 GP
Fine, no problem.
1 Oak Log = 7 GP, With XP Pool = 7.5 GP
Not fine, problem.
1 Willow Log = 15 GP, With XP Pool = 15 GP
Definitely not fine.

The Oak Logs should be selling at 10.5 GP each, not 7.5 GP.
The Willow Logs should be selling at 22.5 GP each.

### Reproduction Steps

1. Amass 50% Woodcutting Mastery Pool XP (2.25mil)
2. Obtain an Oak Log/Willow Log
3. Sell the Oak Log/Willow Log

### Expected behaviour

With sufficient Woodcutting Mastery Pool XP, sell value of Oak Logs (and above) should be calculated at:
x * 1.5

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by FrameXero** [comment]
Wow I never noticed this wasn't working... Same issue on Android mobile.

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
