### ISSUE TITLE
GP discrepincy [Bug]: <title>

### ISSUE THREAD

**Issue by Zerlotious** [MelvorIdle/melvoridle.github.io#2218]
### Describe the bug

Gp is different between bank and shop

### Reproduction Steps

Sell item from bank then go to shop

### Expected behaviour

Gp should go up accuratly in shop so I can buy upgrades

### Screenshots

![Screenshot_20220222-091913](https://user-images.githubusercontent.com/100219396/155166709-09efd6f5-5a41-49fb-86e5-1611465954c9.png)
![Screenshot_20220222-091848](https://user-images.githubusercontent.com/100219396/155166762-de7146e1-0943-419a-9f05-c220cdb3c635.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by Silberdrachi** [comment]
Bank is how much your entire bank is worth if you sold everything. the value next to the shop is what you actually have.
