### ISSUE TITLE
[Bug]: Golbin raid weapon alt specials do not replace previous one

### ISSUE THREAD

**Issue by Zubz0r** [MelvorIdle/melvoridle.github.io#2219]
### Golbin Raid
 When having selected a weapon for the first time with an ALT property it works fine, but when you replace it with another weapon it still has the ALT property of the first selected one.
### Example
I get **Poisoned Dagger** as first new weapon, it has the "_100% chance for Poisoned Hit_" special, this works fine.
Then i get **Dragon Claw** as the second weapon which has the "_15% chance for Double Swipe_". This replaces **Poisoned dagger** and should also replace the special ability, but it does not replace the special ability.
On attacks it still shows the ALT property of the **Poisoned Dagger** and also the debuffs on the enemy are from that ALT instead of the ALT from **Dragon Claw**.

### Reproduction Steps

**1.** Go to Golbin Raid.
**2.** Start any difficulty raid.
**3.** When possible select a new weapon with an ALT modifier.
**4.** Confirm the ALT modifier working correctly.
**5.** When again possible, select another new weapon with a different ALT modifier.
**6.** See new weapon selected, but old ALT modifier on attacks and debuffs.

### Expected behaviour

I expect the ALT modifier of the new weapon to replace the previous one.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
