### ISSUE TITLE
Mastery experience appears to be added differently based on if the app is open or not (ANDROID) 

### ISSUE THREAD

**Issue by ElusiveEllie** [MelvorIdle/melvoridle.github.io#222]
**Describe the bug**
While Runecrafting, I noticed that when I was logged in, I earned a mastery point towards any individual mastery at a rate of 1 point per action, as in, one rune essence used was one mastery point earned. However, when I would close the app and return hours later, I would have more mastery points than I had rune essence I'd mined. I believe it was calculating based on runes created, rather than actions performed. I do not know which option is intended (I know which I prefer! Hehe) but it does not seem to be working properly either way. 

**To Reproduce**
1. Create runes via Runecrafting, watch mastery points increase at a rate of 1 per action. 
2. Close app, return a while later, see mastery points has increased at a greater rate than number of rune essence used (requires high enough mastery to create multiple runes) 

**Expected behavior**
Mastery gain would be the same no matter if the app was open or not. 

**Screenshots**
I do not have screenshots

**Browser**
Android app Alpha V0.14.2

**Console output**
Don't know how to open console on Android.

**Comment by MelvorIdle** [comment]
Great spot! This is happening across all versions of the game. Will be fixed in v0.15 (Sorry!)
