### ISSUE TITLE
Skills locked temporarily all armor removed, bank over limit, can’t equip items. 

### ISSUE THREAD

**Issue by EmuDaGod** [MelvorIdle/melvoridle.github.io#2220]
### Describe the bug

I start astrology came back an hour later to check. It had stopped, again. Once I logged on most of my skills had red padlocks next to them rather than levels. I closed the game and reopened it, the locks went away but most of my gear had been removed and put me two bank slots over capacity. When I try to put the gear back on it tells me my bank is too full to remove currently equipped armor. But I don’t have any equipped in the slots I’m trying to use. 

### Reproduction Steps

No idea. 

### Expected behaviour

Self explanatory 

### Screenshots

![A61BC076-1FB5-4F31-9EB3-DC03B615BC01](https://user-images.githubusercontent.com/99620029/155234790-e73d264c-4f46-48c9-8a19-18f106275d73.jpeg)
![BBB2A38A-1384-437E-A6B7-B0AAFCC50300](https://user-images.githubusercontent.com/99620029/155234791-26f14d0d-e6c3-43f8-b024-66c9f9a37135.jpeg)
![71F48168-BB7A-497A-8104-9CC3AB3D3A23](https://user-images.githubusercontent.com/99620029/155234793-64e54e63-bd80-4a1a-b31a-f61fb9fd6388.png)
![67D74477-FE05-40E0-A92E-3999D1BE8847](https://user-images.githubusercontent.com/99620029/155234796-2410b37e-05bb-4718-ab7d-d39662d4db51.png)
![D2E18935-AB1A-4DFC-9D71-CA1D72DE126C](https://user-images.githubusercontent.com/99620029/155234799-d08b5468-e60e-4466-aa19-3f0aeeb7687b.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

Forgot

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
A hotfix has been applied to  v1.0.3 (?1848), that allows you to equip items when your bank is over limit. 

Please note that the un-equipping of items and skill locking occurs when you attempt to load a save game when you are not logged into a cloud account that has access to the Full Version of the game, or it fails to validate this.
