### ISSUE TITLE
[Bug]: <title>Summoning recipe

### ISSUE THREAD

**Issue by Eganbacon** [MelvorIdle/melvoridle.github.io#2222]
### Describe the bug

I play Melvor on iPhone and when I try to select a recipe, (this time with crafting tablets) I have trouble using the top recipe as it is hidden under the headboard. In this case silver topaz ring. I’ve had the issue on other summoning tablets and persevered however am struggling most on the monkey tablets.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1341

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
