### ISSUE TITLE
Offline bug

### ISSUE THREAD

**Issue by wantacookie666** [MelvorIdle/melvoridle.github.io#2223]
### Describe the bug

Offline progression error.

### Screenshots

![Screenshot_20220223-012933](https://user-images.githubusercontent.com/100261275/155271784-cd2a9ab4-ff7d-478b-a8fc-96611f7b771b.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been hotfixed as of v1.0.3 (?1829).
