### ISSUE TITLE
[Translation Error]: <Chinese Translation> 

### ISSUE THREAD

**Issue by bhuguu** [MelvorIdle/melvoridle.github.io#2224]
### Which text in the game has a translation error?

The description of necromancer equipment containing "基础品质+2" should be "基础数量+2", where the word "quantity(数量)" is mistaken with "quality(品质)".

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
