### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by mydarkdesirex** [MelvorIdle/melvoridle.github.io#2225]
### Describe the bug

Tried to open the game and can t get into the game at all
I've tried reinstalling, verifying files and everything I can think of but the game has no update for me despite it saying to update to a different version

### Screenshots

![Untitled](https://user-images.githubusercontent.com/33383142/155408140-e603015a-7490-4ece-8683-5aa1fdd9c91a.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

wont show me

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
