### ISSUE TITLE
[Bug]: Combination Rune not being used

### ISSUE THREAD

**Issue by Jack-Bruce-Dev** [MelvorIdle/melvoridle.github.io#2227]
### Describe the bug

Training Magic on Spider Forest but cannot cast spell due to combination runes not being available.

### Reproduction Steps

Fight Spider Forest with Magic and use fire surge. Ancient runes and smoke runes needed!

### Expected behaviour

To cast spell

### Screenshots

<img width="187" alt="Screenshot 2022-02-24 at 16 53 12" src="https://user-images.githubusercontent.com/92029623/155570583-0271bbd3-3b3a-4257-8d95-49e4c1ad68d3.png">
<img width="221" alt="Screenshot 2022-02-24 at 16 53 43" src="https://user-images.githubusercontent.com/92029623/155570587-51efea6d-9e9c-45bb-945a-8ab44ddebfdf.png">
<img width="352" alt="Screenshot 2022-02-24 at 16 53 38" src="https://user-images.githubusercontent.com/92029623/155570592-c880e684-d9e2-4391-912b-183aaae662f5.png">

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by CarrotMD** [comment]
maybe you're using the spirit ring?

**Comment by Jack-Bruce-Dev** [comment]
> 

You sir are a true legend. Could NOT for the life of me work it out! Thanks!
