### ISSUE TITLE
[Bug]: Responsive issue IOS Farming

### ISSUE THREAD

**Issue by viezefreddie91** [MelvorIdle/melvoridle.github.io#2228]
### Describe the bug

See screenshot, the text “allotment” exceeds the container which breaks responsiveness and creates an horizontal scroll on mobile

### Reproduction Steps

Grab an iPhone xs 
Use latest ios
Use latest game version
Go to farming
See result

### Expected behaviour

Expect better responsiveness.. perhaps an ellipsis (…) on the label

### Screenshots

![4118A521-4A51-45E7-810A-574D5241B007](https://user-images.githubusercontent.com/48770941/155584780-15fd0e6f-61e4-44a2-8eed-8e50714e004c.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

1532

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
