### ISSUE TITLE
[Bug]: Golbin Raid stopping combat

### ISSUE THREAD

**Issue by MrSankey** [MelvorIdle/melvoridle.github.io#2229]
### Describe the bug

When pausing between waves in Golbin Raid, the afk rewards screen is meant to pop up. When my character is farming Golbins and I am playing Golbin Raid and then pause the Raid, I receive an error message that "stops" my offline progression.

My character is still in combat, fighting Golbins. But the combat minibar does not show up, and I do not receive offline progression. Reproducible 

### Reproduction Steps

1. Fight Golbins
2. Start Golbin Raid
3. Get to checkpoint to reroll passive slot
4. Pause Golbin Raid
5. Switch Character (to save scum items)
6. Export save
7. Load Game
8. Receive error message about offline progression 

### Expected behaviour

Return to main game with offline progression.

Provided below is the file export. 

H4sIAAAAAAAAA9VcyY4kR3L9lzpHNnwx3+YmYC46CBCki4DuPlTXgiGGy4hsEhAI/rvsvWcemVVkc7hphGGxM7Ii3D3czW15tnh9f/fd3Z+yHXdf3v3pbTrqkdPKI6V5lCMfyf/hp5R+5MLfu7VRp62xmvkT6+244EF6f9x94Bg5fhJ/Xn578Zv3+MZ7vLWej2HTb666fArpGG0cPQ//ZqkeZRqfTT6z3DmI+XNdW1wxZ1+C6TpMz2vTSnpeR84FQ+Rc/V7zbzONg4PHoC35U/R2MvBtzS/eETeKhs9JhCn+ZHR8qz744qMcj+aBuVcfgzPIphn4cJpR5e8jrs0HMIy0fCWkTfa1VXxbxxqkA6g/E2614lNOCy902s/Gp9kKabtSE5VrPWrxXcxHm/5W3MU6eC3sicbGxnX6PPC1OskwTveX4Vpq1/ZXjVp9o0rHt5b6UdfEbfM9K6WQyqtoGhMjskN38jrhbGFl5Zg+k0JKFl+xeTN88xniS+3YOdzwaTTeGLwxGubhvX14vMjXtny+BsbBd3+VDV+Bf5++RhDP7xbfcr96L58kH5K+cyx+T1geluHfu/PYMrZ1Yq7R8DWDenjqa5n45lTGsgxfMr/01XmtlvT7xPISmzjtCh51UxOS3Jxy6gqJ8ibe3kkzjvb+eJuOH/3EXZcwCtm4+T5vvq+b7/m2Q863v9TbX+z2l3b7S7/95faV+fad+fal5bZPuW1Wb2bweo38fauEiV7kukMSJuEI0QFXYgHtAFmrf07dIr+yFaZQYsh2ap6rztmfr3/0jvjp4kxx5cmSkouKGdWRQpa2AEGe8ImnkI4UcgMpwmeVEGaIN3VP4/YnagiwyLAUjGGUpkw2rOQmMgqZxD+6kdRcaMdgZRV+YmO7a0lw4inRPo3FyTR+hzYs/hp/UeXrKNtSSFSVq0hkLbjVXCuyU52aN8hMAaYkSYYkPdWb8o0u54UCJwGU9EiWJKgSUZ8AJaZS6KQ1FgklBWaGKULsC5VOpujXUAi1LfILt4O0g57BfVB59BGS6bOlBqa42qkkMwf/ETPe/NzyxqeeXvnpU6NsFv8xx/3Mz6tZZWe9XMd4A7W1li95ObuNaW9WcXOQUiOBnOLlzWh54T/XXqu7Eqz1jdsJ30mKrW9V9+ZW3vSKVnOmtl9S65hvWk/xH42jpZG9vz/Df07i2myl9KbdrIwmrSRaZSdx8X2xMZyf7VyAhR1VB/3/swT7o378PUARsP4w7rC54CHs/nsHHl8SedxM5e/s4//vzz+KaH/8+53Wb3+6LyXj18+jfOJ+/QPWaD/zrP2asf6Zf7Avv6nTb5AgdPvdG/dbF/nJ3f6/fOk/ERthuut3D1H+kfMtv4IH0fwnlQkfQm0Bzew7Ez6ig4sldi2OC63t7kK9gz5hTvv//d3cZYEP8VPY8+UPvRd3HwCUdC1xrXFNcXWg48b2y28///yP+YACdWd2Gf45tnOpHO4nOcggipy+mOGIytGE48xOlKml5+So2LGCe3C+XkdmFZgg/l/xZdgalvnkjyIBbDmwxR9KAoBPwNDhYlodPEysAC5eziVo4KjUQfFyTL1OGvQBeLTgOGLPe4GbCKfg/LfO78sXMDE2b/yKBXOKQC5fOXC5+/7d3Td//ezzz9/d/Wkd7+7uHz5+9tWX/gtX8+7u42dfPH3z8f6Lv/mta8RmzvzD3XH39t2dlTHufWMvqX14uFh/XpcP7enp8uHp+Tnf5+eRnua7Ox/o4ancW5rzYj7Mxf31D5f7B8uXeT/KqPfP050cNswP63HYB2+T5pM3fLDLxLD346k9lZzHw+NiQ/tQH/PTs10eeh0XexyPlw/z6eEy7u9nfqr3y6Jhrc8AquPS62wXe3jwhuXx+fLsKLYPH6M/Vja8d7Z77v5CeyiYY0mX+2oPl/Xc7Hk81KduD2zYnvOzN/YRH4qv2srz5f55fbisee8Q+7mlp5VjxHtb3vhio3Qnz6iX1ca8PNzXPJq7QKuLPM/3T8sckV+e61O92If+eFmYxP1q9z7NMfvj87u7907070H5d3f/8vXHv3z79bs7/vJdfpPeFP7i+/lv91//9Zs/f/bNw1ffPX399Og75zcTNhDk9Wvya4lrjavFtcW1x3XEdcZ1xTWn/WWPmPeQeY+Z96B5j5r3sHmPm/fAmSP/4N8en57vv/384388PXz2t6d3jAT+Mj1MnvS1fvbx6Yt//bP3vGDF//3xfzTyb3gCgr89qf426IjmXz58/XT/zdPjf0J4/uvfMU0Al/z+/Q8+3s/9fx3uOnP8dlHYzC90ct17VrDj5f/v71xyHx79dRnRqg6d4mp0Hqvt4c4wytWGoQm8dMSn0jWg8el/+pzXNzModUxnRAAP1wMMkiq0WCJGR6+5RISghtO/fecesYQR4YEZnv5ivKH0RBOnqAMbjMZwg18V9zLGzK7DKE6yGIXINTfEDVME0BRwK+1AXBD+/xgF0SRvdVwjSu7FO+FaerHuW7JZCksz06+iGwMlNZo3Bj04VT6JxrwH076SqIbltJ/wHmH4bya9r9efCkP79+WDceE0jIGMPtdkhMUNkjFs5YqrDtlhbq46FZjGshROws3ZKmzTPHrNJYK6CAYjqkx0g3CP+QgHYmd4hNAMudGsMySFCFhnwIjuQXNF6K7+0br1gp3zschB/gUj8LI0/UkKLQzhH7B0GnkUdqgMrjGwjfud9hJxBcQDe1oKV4Oaszt/gm0wy2y9M3TZFgOESaHAwphg8g8MVmcm6XQt+7oimD9TNcbPOM+BQIdPdPCu77GljqB76wouascZRWtaQlCyK2SvxXKtDTQoLnY+tarJk7JjNJCzOXNnxG0HW4TUKOruckXeW4z+lcIni2E39EEKQ3uGxzkxiTA5u+mcP/U0MwrtCJZTTHqc2EuTqb4XrggwqYYHoCMW0skdtXBPHKMMRZoZXPS51BxTVCS+B3stRBSnYapk0DxcURTNRMG35TvC3Tau0nGDs4e4zyUcmzA6FREVVEVgCRkCiPNEvM5Wh/Jo7LEKXjgAWTN/wer6QEqmaL4OdxRZTdJDXNBszfVpDQKCb5HA4qZmF6xBguYKDTin6OQo25m4ksEmws+5IawEgAi2ani1gdmsBo9mErY4oyNgPRCxbhMyh9SAxJhzyYDTnAj3eXZGJ7HNQJdNSayFOG9PIRegX2Oo03cUGTMEqTnLqvjmYi6Jjbnszjxeqy0Zk0vaeVee0K19Qbk53yaI6Rqa4kzGcDj3wWXKFGtmUqBM6wzzlkV+dIqsTi62hmW0WjJ6o7lT05m1WQcdujsIik8n2QyFiTVVYCq+UVzKSw8NATCOuQxomArhYaTR2C0xI8FrhztAbZk76a6hc6I0ujYA0ZojyZkYkZdyh36scOlC9HwRDO+f0lqawzuDtXIGIX2csTPGnlJS7OZsb1Pvcy7naLwycZAh7rUqq5GZkish4Nw0Z6d0KsHp0629ik6JVMelTt3KEIjWHH5iPyV6WfmnPpkjy5zQQMMaNMz7NtjKKRHqAb1Gr5QBpuZcnMG8EjC+qXa3M5N2B8+x1S7/GjUi67iga0U+wxWyNpSpLnw6DKiJml4KdFKFTvK/oUewtkABPsEAi0bbZDyYPuvQN5W3W9yGLDAbkDsp2KXDZTowqVGYzG16AzMcpuwBNOreMLHe4FQT2nctkJplkGt4f6SQAXD+oiKCyaFbD+ly5s/0yhkF91ctkByfI0dKLVPhG9rmuQh7jJqk1EMmuXP92Y3PSF2dhkHp+J5Ptk/RAUQYA2JENVSZbHQFeECY9bY1mevpfBGSN+BDCidJRfcT2S7/wPKGuhmyB1TfYOpCIS7KlnOviBDg4ILALvjgZ+0gFEAHuZEO5jRBQyEwsKNEnBY9Mc/G7SKKEvuBzACX4D9pfGcFLk+6Oyn3pdU5PFnUXkAJjVqjdEZcxuicrkss1tmVIcwTe49LYh5Nk+4oHkCUApveIPJ1TOOiLXMUbjFTJ9yb5KZyMStIeWT6DqoSmUALneITgPVI4jBTPgvyt3B79bOhqzcIBGSMaxIgpxC4oXJq2kvcgboMEIlZ5kOULbITQMilXoeuvmzktrtQqBm3F5cVMsr0mwjfIgPIrcurkOVKde9bqSBnu0Js5lhvSXMC8Ctf6+vtruwDZsO3oBglGf/KPF5vTQUIyqIiMZilvRptbhtE0w2LNN8dsFOgKaqvRf1lbpnchrQS5Eqs2Qjd7mixCPV0oZUAKa7QYBEKlRy2c3SkqGSiWF9BCwv2kzMA439ukG+GW3JYhc3mlQB0ICc7mMOEpqILgHqDY0n5EzwqbkPYCsQwD+Cj0kPQihEodGDtEl6QERnWQLHYUMpZmhgxFFMJT8vf1sHlfdurTsHjeLm5geZY7kFBt4y1tXgGS7SwAlXc61q+BYst7l6o3iJAxhR4xw63UP4iPMdzN4+Qh+0r21ciuAnoEfUsxRc+gDT8rbOrVoL4uGeyABU696wLWSbYovA/mHWXBbUOPor9L7SsuJBtfNxGUqiTHAvI/GRKOayDnFOCc1fBcB2ivYCZXA7gjcYE/CGLmA/5NLQo7bXmcm5IUSKQWLeyJJJYl6zehrWFkCUHj8LAcOaQ+zWvXJeA+UHGjVIW0rH9dDaQQA/5IrPmotnTGhbYshUkIhdRdcDNqCm8lrIhQYcuLmEiTzWDnS+BIqk8KZj8nk+U69zmVIKVGG3KC6NFnCeY8oHztXGpjVbS/SMaoUEmK9f2iXUQ8ySCq9oNzGgxShdZnVZBYIWmt8YbM+VTC/HVaZw92tmjnXR2ND6pX9K6IiUWHJFj1jj7jNu96Q0qAuUTRGmDaghh8lRZYCFYkSFzrm2RR/c59l4cb1dFPThsH5P4u7rXDsI451eb1MIu9pXSuyY9z0pnNu9ZmmiWCs2AA1Yg6qSiNmkWznpXUJGXUecmESU5uD8DIo2ozl6ca/HlxsvfJ8bt4Y9kxqFDyBl0uN4MjSAwSBYnS611c5+vM59PDfUsjIxRWGq16T83E9PpViFKmNTl+A62pb7qT2eihnSzhi2iCSmp7u7cWE6iatLpdfNkSbD1tGmrzpxP1sTToKDuBo6RjiRZqKaMaiovA44PAFC3WHFRychVzv/Bu03M3inCVDIcttkNTeiKwbNzoK0xCUrq9tFZmyNNS4SJwfwN091DmQGHGAMD1ua8XFfIQC7kfh+oMM1gYp5JGAWvW8U+iRV7tpUHEWCmLXd8AOO4JJksoXMjrWZ0FLMQLaBZlHKyHZqJxRi8UPHfRJs5RTSEKSKoAdhPlhLlwEMj0IdK7hyw2BV8+MNy89ClamuYngSnbx6qNlRLwUKW9FUxQkuW59UiJ4XFQ4RCBMDcZgDn8SPsVpqTbgRIoZ+S6ai0inmGA0WIyE/GpBi5Kap9g4dQXgsKjGfLP5Iqeqav/LwCKF7qyXxyRHGvBHDaHAyuh+0QloVvWQtATY3wGOsnl3xPlF6h5+y0n/RNtr6Ej9pqfRESKyjYmuNUJArMqYyX+8h4+YlXgU5DjGmjaaKJTKfmN1VCCl61FWHRLdZurSw0Eb3gJm9fIJ53wSANmwa4YqEX2hnBQQTR8g0y9+1DPfEMEoYWOJ+0Vy3HsYsXX7U0SdVgOMRZAihhtTDOLHXjxTl2Uu4duIUBOQ06A1hmr7zeSkPcXgkLVIzFRpDvNxZz2PXqZp4IQ7RXDAX3r2xXmoHiQruLXPeIqckshz/kSmlu537DnMy6yAg/qMwwcfuNxdMlBfUCv9+4SU1K+oh4AVMGrBFmkXe+mjBFCqBIygvsIp6WFXwhp5Bbzodorh0RaLK04xmnnsWe9a1+Y0f9QQi0SVHzUhB6nHBzu8Q2HL02EA6001wap+Ujp5cSAli6XtzCNOrLV8MrS1d+M9TlOXWCIbYIwMHpQYuX915bTIQ5WXCprIcrONeQrqAQTKijD6oTd6ryCn03qpLiJ0pAIIjOZInwLBMDuNQZUTjubUck/eWKjUwQjCEUozDjRNj4xbIHUkQ3cLUQzfjq7MWGQ8pLoPjrliNUVcLTzZ2GfjKGNFwHY9utbgIAgTGE0KZjU8UtZCv74hmCve5mbg7r4kmFbULaSKpNP2ECYO1PPwX0YPxyYxq3aFBRXVqfw5YSTgTiwyI54xCdFwSe+RiRYETuFE6VZ9dVnr9v+WIBmrDZ7SXbIZuVTxqKEWlha9so2ZGBJkJ/OgJiVBIjsOPMDKTG/lBZFUxu9AnFlF9KZQaFNzytEbFSNsYhbmKBhBCZzGVi8MzxGHBU3ojiNFsZnl7t2pois1UdzbIwWCuY88qwPTViZhUJM/DZ0rnS8WKmBpOzAzL7Zic4sG23aih1vLk7mDFUmVoMiGzqaRvc3xsTKdEdkz8ilAmVRG4JEm5fEA4iSL62rzO2yx1OFPyNxDTOujJwZq0IAIu7knhVTzsCRq4pL3Bo15vbVae05r5dZ+H0fuuVeq6PbOFps9cdVl1Bkqysjihq5fq1nmTZN1fea6u2zqe7XUYaZSoVixJ/5GWIH4qi9GlNbAbQNQIsg7oWKbbJaVHHdBionDVArYOoyXGXyO/wkIE+K0s6xRtkRid6kdHjqY1RaSs5hyI0blWhizzGasp3pKiNt0xyZhw9GXAFkxAQ1h+jdAZimJdeWkJmeVmWSzoSc+PYH6d1TN4MB4kG9s9ooXpX18kK+M7EWcWqHfMTzuhNSuH1Sjcgu946FAJEqO3o1CODXF7YWAocx4Tk29BTwQYwn1zyAL8vufeZkRx6Mc15cERXeAeDQt0jSADdgTonRaOoQLhJjE/Q7sZ0bTEWCR3RGVfzCXeOU2zotBbhGSvMcCyKbGMoTUNHHgTRcag1M88u0Dtqq1Yuoyf6lw67Cohpwi0uYc1i2RAMgi+dwiqZ2cWK1JNicZOynvfbSiPWMXfTW6/KezUF610xYo29k8LuOzD2PQdjaOiIIq/YJik0F6Q0mWtiVUZ2/sTLLBNfIwp8NMVfEo42bXJziwsTikhKVWUeF40GwPSIsIZlgaKOuNXZVxqLCQwCQh8GJXyu/oYqLAZjHmPZ7lxDFgj+EIxiCn7UJraOM3PZAHrB2Zj9JK3RZUR3yzLR00jugigKQNikrz8q9G6F+RoIJDDoC6y+tizzFI1BDMEmjAZQM/h65ElRHEenDPMUTh6b2nKSJswhYj8NMyxGMvhGsvalMiTiZKhEtwAOo6v/NKrRMjITUv6iSYiCoBqltAwawGkmvNVN53EWkH+JfVNuyDWk8qVI/nEXDOxiLDkp7hPSpk1FHJ0VtypLEy9yjqE26pxIdgDUZ5E60Xkfk6ijThMesWOaNrc+yZx7MSaHeECQNKLwDha51CpFwUNQzLWWa+cRtszfynKlJhRSI8lR8GZy0did623n1gjsDUUsYBeGPmkniQV9XiiOIF3IOkY/X0JHp0TpStcPkuxcwvujV6ISBfF+YzkuqZYFN2yR5EBFGMiocF3TMRrj8yID0u9lD9v2hyRra9lk1CYRxTTpu8X2bAOhYUgQ0clhWy91OjCVB9eQekJmQ+1YW+HMLB5W6jsZ673YVYBd7LgYuiGQAhUxCoeAwdA0Ow9EMhiYYfCZyKpEF77JnZU6bnmZBENj6tVe0ig8oDmJIkvfi6aTOFsYWkgIqwxS5xm1qaw8QRTabuVQFSrvCpNj9lQOiQF6PPQVw0SAOo0iU+FUsu8YPI6UoRLIU67TaPKtu/lFfAGKgTEo8AkrzIbTC3sITLp1ucLyDBqBcpmyMiZKpNwA1LLD5YVNUb40gGNjuwrFkHLOg50ZSQ5gBeF78oqqVZKyIFKolGlZEHerxVBcJk0OIdyUD1hDlpnw8fFXY960wk9jbJdBiLKUai2su6MSlg2QKiIIm2GxEqu/OqMkTPnXMUQVxgPoYrLbomCMpN28joBSErrVQ4aHSRMWPW/8o6i6nAQmF1jy4zaH1DRur7K8VFDYrRFGzi0SyIk6KkiCG7dtk3lksS/hploVd4fCddrb0QP/RTUVDqtRx6H8Ah0T0la0tEV9GqlcRlORGeLp8BnnoThk6cGSECX6AR08PFgvQPsgvbaU3/ZxtFajOhHDdJUcogTCSM22VROxnXO7DiQWKEcUkHdtWVeAwVSjQ7PTcBzyRkX0GhqNYbs6FPjBq2VNaLMYoZOwUF2umGPapQgFDyLnCsajU6AZEnb2aA8uofDi/tj+heqFQpJVFuFWLA95FkxmTcobQ7+yFjgjAFV2nFqL4TeTeW/03EpX2her0aFXFVpF0tJfpsQfuzDGRGeq8l2sNDws/Mtrcxe3zkqKkhkWAjxWUgYQvg6d/hycKRN6ITpUDp2IxjmenkExodw+iB4dxABmGpO4A/FdCTmlavLIhwNUnv84ouJxuEeAU/aoaCJWLwxkoUsPeecGuBqhpW6UU1kqRre6in1HDmIGNVeasss87uqWR+hu5ChqWkQEjWW05P7KnBW69WCvKS8pJ4CKjsItok7fVhuEL+5jM5bmDj1tsruOgymhhnMDx9jm1yj0sNCsdDAk1xjfj42bqetFjG7WGQG/KXVFpjXs6Mw6sbwmy5zcY10C/0uaYaCyAEaLqVX0yaH2dDqYUqxK3H6yOcl5xKEL7hbMC5W+qwnGXAqFs8E2UYdxlkS37ei2iUU/3O0OuX4ooIYSS7pLTCJO+UQudCZuqaw62b4Mq6LWLJMqAPkmMgTKZFDK5C7DIjKlQXZIQpCVWBUUhpz2q7tHQRUyAwMOxUlnHEUiANwussLYFdVXzltKqzJ0rI6VBqlSwCf0yS0SdeTJLAc2gNQaXJaZAEMM0lkvZeO2q2MH30PQEkVrsNylyrxmYr1KhhPR0GPWa2+4H9izqQizwznycWnSX0vHv+W6sK/dvhmOLc/Dt8xsUR76OwNu3Qn7gWMGgjYbP8/b3u6qI9HnSsUYSoRbBe94Rr0tYDxP59juvl5MvPNMnC/WkSSVX1v0IUrJCu9M5DMbMpt7D3Lb6pGK21m98lB/7QJogww2inDsXDpoL5dxsLIaeJRLRSKHDFylcq8ROJPCDnVDyCthoRSwWlzNR3zmjXGJdGRLqjxlaPa2ZHKiMd3wqyA2TYOxap7gdMUQ8YXBLCZKYoJfchZPu8xTYw+VaGJOvmoFJxpcfhgFRsdYsLY1D2MSTeid/IFM+vbPs9pDmKvq8omuWChrWbKu0w6NHq1SJtREzII0Jdy9m7kE9NV7Dd9konI4qQBmNVUlH4QaxHTOH5kVJ9hV111rCCY5G6H0hVQaUKb0+93yOrvQve/8SynACSimaoxDT3CNHJ8KRQVTO7v+6A7kK0VasjN845LHv9OTZ3UliEmdh8ow8lpdxpve6aFjAvxR3QEVi+recTBEvriTi1W2VRVA+gsmBBifOMegq9nrh5W4TuHO3/F5nnihH4o/mYLUofJXUVKify9PfmCbqGnLLzz4EX/M5wJNd54vIWDdQ5N76ogsoCqcAh/hkEo+dFaGss8QM5UfU1vzUG0vzsoMpr9BzKa/A6NoNuDv7dmWMs8VKbIq6rdDEWTIMuvfNfUUppAby7+bVON0zKcPx+QQcECFX0MiHoGpxMtSyIlYCeZlKo4OO4k7PNlUGMR0+VlDnlIS+F2heDIDl51WGgdPdUzi9oxMURpFnmNjGEJnGlh1lOk3GaKQLBasytOmX3yesoQp1fHI4bJYBaYKy6CVqIQPwWjyOv9WRvwwrnfcnuvpr0XhRzfmT0nS+x/+FwgMLmmDSwAA

### Screenshots

![Screenshot_20220224-143559](https://user-images.githubusercontent.com/75797615/155688125-2cf4bc9e-c130-4a0f-9b28-8f7882523b00.jpg)
@

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

(?1532)

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been hotfixed as of v1.0.3 (?1829)
