### ISSUE TITLE
Bank item selection starts to lag at some point after the game is left open

### ISSUE THREAD

**Issue by levgre** [MelvorIdle/melvoridle.github.io#223]
When clicking on a bank item there is a delay, this does not occur if the game is refreshed so it seems to happen after an undetermined time with the game open or after certain events

**Browser**
Chrome Version 81.0.4044.138 

**Console output**
Please open the console by pressing F12 and copy it here.

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
save.js?281:473 Not required to backup
save.js?281:47 Loading Save Game...
save.js?281:208 Save Game Loaded...
save.js?281:47 Loading Save Game...
save.js?281:208 Save Game Loaded...
smithing2.js?280:189 Loading Smithing...
mastery.js?280:181 Updating Masteries
mastery.js?280:23 Loading Masteries...
main.js?292:1113 Game Loaded
oneui.core.min.js?205:6 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ oneui.core.min.js?205:6
cloud.js?286:81 Melvor Cloud Connection: Failed
main.js:3073 Melvor Combat Sim v0.6.4 Loaded
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by MelvorIdle** [comment]
The bank is getting a rework in an upcoming update. But I will most likely address performance issues with the bank prior to that.
