### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by roxeurqc** [MelvorIdle/melvoridle.github.io#2230]
### Describe the bug

i dont know if its a bug but i cant get anyfish 

### Screenshots

![image](https://user-images.githubusercontent.com/100432137/155749856-019944cc-2eb6-43ec-ba8d-8be91ce0c78d.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

1532

### Are you using any scripts or extensions?

No

**Comment by Gilson-Erik-VBMS** [comment]
Is it auto equipping it to your food in your combat screen? thats what that checkbox is below the mastery bar is.
