### ISSUE TITLE
Fletching Mastery - I've completed everything - Only 99.95% complete

### ISSUE THREAD

**Issue by CHMac42** [MelvorIdle/melvoridle.github.io#2232]
### Describe the bug

I have mastered everything in Fletching, but when I go to the completion menu under Mastery, it shows that I am missing three levels and that I'm only 99.95% complete fletching mastery. But there are no other items to master. If it helps, the item I completed last was adamant arrows. That was the final three levels.

### Reproduction Steps

1. Go to Completion log
2. Go to Mastery
3. Look at fletching - 99.95% complete
4. Go to fletching tab
5. Click on "spend xp" option
6. Observe all fletching items fully mastered
7. Confusion

### Expected behaviour

When I completed the mastery of the final item in fletching like I have in other skills, I expected the completion tab to reflect it like it has for other skills.

### Screenshots

I'm unable to get screenshots for this because I have another reported bug in which the game wont load at all on PC, so I am using my iPod. I dont think a screenshot would be necessary though since it's pretty clear cut. I think I described it well enough but please ask questions if not.

### Console output

Normally I play on desktop but a separate bug issue that I have also reported prevents the Steam version from loading

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by CarrotMD** [comment]
If you spend the pool to complete your last item, the percentage won't update. It's only visual, a refresh fixes it.

**Comment by CHMac42** [comment]
Thank you for youre response CarrotMD! For those last points I had just set it to make arrows and left. It wasn't done with the mastery pool. Also, I think it has been refreshed but that it made no difference. I have force closed the app and restarted it several times. I restarted the iPod too.

**Comment by CHMac42** [comment]
The update to 1.0.3 solved this problem!
