### ISSUE TITLE
[Bug]: <title> BUG

### ISSUE THREAD

**Issue by a089323596** [MelvorIdle/melvoridle.github.io#2233]
### Describe the bug

BUG
寵物. 鼬鼠+豬 失效

75%烹飪 失敗獲得煤礦100 功能失效 失敗獲得不到

GOOGLE translate the following

Pet. Weasel + Pig Disabled

75% of cooking, failure to obtain coal mine 100, function failure, failure to obtain less

Chǒngwù. Yòu shǔ +zhū shīxiào 75%pēngrèn shībài huòdé méikuàng 100 gōngnéng shīxiào shībài huòdé bù dào

### Reproduction Steps

1.裝上鼬鼠+豬 2.烹飪食物 3. 失敗獲得不了媒 

1. Load weasel + pig 2. Cook food 3. Fail to get matchmaker

### Expected behaviour

烹飪失敗獲得媒.可是獲得不了媒

Failed to cook to get matchmaker. But can't get matchmaker

### Screenshots

![image](https://user-images.githubusercontent.com/100504198/155869166-96adbb8e-0c6a-4c53-a79b-008d9b583aa8.png)

![image](https://user-images.githubusercontent.com/100504198/155869170-3c1b9e0b-0a7d-44fc-bf40-7376858a5529.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is now fixed in the latest update. Thank you :)
