### ISSUE TITLE
[Bug]: Reroll loot

### ISSUE THREAD

**Issue by Daxous** [MelvorIdle/melvoridle.github.io#2234]
### Describe the bug

I opened a group of water god dungeon chests, once the loop window opened I close the app on accident. When I reopened the game the chest were still there and had not been opened. This would cause people to reroll loot boxes.

### Reproduction Steps

Open scrolls or chests
Once loot window is done close app
Reopen app and chests and scrolls are unopened, hence able to reroll the floor.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
This is known as save scumming and is not something we will be working on. This is a single player game, the only person you can cheat is yourself.
