### ISSUE TITLE
[Bug]: <title>Passive cooking recipe

### ISSUE THREAD

**Issue by joseanjim** [MelvorIdle/melvoridle.github.io#2236]
### Describe the bug

Active basic soup takes 2 potatos and gives x4 basic soups
Passive basic soup takes 2 potatos and gives x1 basic soup

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

V1.0.3 (?1800)

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is now hotfixed! Thanks for the report :)
