### ISSUE TITLE
Mastery Skillcapes no longer included in the default item list for quick equip

### ISSUE THREAD

**Issue by vuzuv** [MelvorIdle/melvoridle.github.io#2237]
### Describe the bug

Mastery Skillcapes no longer display as a default item in the new quick equip menu. Just a very low priority re-add. 

### Reproduction Steps

Click on Quick Equip menu in a skill you own mastery cape and it will not be present. 

### Expected behaviour

Default items from before still in quick equip 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1800

### Are you using any scripts or extensions?

No

**Comment by vuzuv** [comment]
Save File: https://github.com/MelvorIdle/melvoridle.github.io/issues/2235#issuecomment-1053937213

**Comment by MelvorIdle** [comment]
This is now hotfixed for saves now entering the update. Unfortunately for old saves that were effected, you will need to manually add them. Sorry! :(

**Comment by vuzuv** [comment]
> This is now hotfixed for saves now entering the update. Unfortunately for old saves that were effected, you will need to manually add them. Sorry! :(

Already added mine but super fast fix for everyone else already asleep! Thanks!
