### ISSUE TITLE
Running away from combat clears the loot to collect

### ISSUE THREAD

**Issue by featurecat** [MelvorIdle/melvoridle.github.io#224]
**Describe the bug**
Running away from combat clears the loot that's been dropped from the combat.

**To Reproduce**
1. Fight an enemy that drops something.
2. Click Run / Area Select

**Expected behavior**
I expect the loot to stay on the ground because when I stop combat via skilling, when I come back the loot is still there.

**Comment by MelvorIdle** [comment]
This is an intended mechanic. Its basically running away from the area where the loot is that dropped. Once you leave the area, it's gone.
