### ISSUE TITLE
Some skills no longer highlight green when training 

### ISSUE THREAD

**Issue by vuzuv** [MelvorIdle/melvoridle.github.io#2240]
### Describe the bug

Only crafting, summoning, and astrology (did not test fletching) highlight green while training. 

All other non combat skills remain gray as if they are inactive. Screenshot attached is during alt magic training.  

### Screenshots

![image](https://user-images.githubusercontent.com/100556247/155942665-89829503-f206-4526-a118-9b4237614891.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1803

### Are you using any scripts or extensions?

No

**Comment by jetbent** [comment]
I had the same issue but resolved when I restarted the app. 
![C79346AD-EB64-4D64-ADFB-66C2FE69F89F](https://user-images.githubusercontent.com/19807013/155947722-bc32e082-6e04-4bcb-b80c-a0eeaed61393.jpeg)
![Uploading 324D366A-3D97-41D0-A277-8ED7E1F42AEF.png…]()

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
