### ISSUE TITLE
[Bug]: Error Creating offline Modal while Cooking

### ISSUE THREAD

**Issue by Sprayer115** [MelvorIdle/melvoridle.github.io#2242]
### Describe the bug

An error occured while processing ticks offline:
Active Skill: COOKING
Error Name: TypeError
Error Message: undefined is not an object (evaluating 'items[itemID].hasAnimation')
Stack Trace:
getItemMedia@https://ios.melvoridle.com/assets/js/game/main.js?1803:282:57
@https://ios.melvoridle.com/assets/js/built/game.js?1803:88:1852
forEach@[native code]
createOfflineModal@https://ios.melvoridle.com/assets/js/built/game.js?1803:88:1702
@https://ios.melvoridle.com/assets/js/built/game.js?1803:70:830
Current Equipment:
Helmet: Chapeau_Noir
Boots: Boots_Of_Stealth
Amulet: Amulet_of_Fishing
Ring: Ancient_Ring_Of_Skills
Gloves: Gloves_of_Silence
Cape: Cooking_Skillcape
Summon1: Summoning_Familiar_Leprechaun

Skill Information:
Is Active: true

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1803

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Full Reproduction steps:
1. Enable the Automatically equip food when it is made setting
2. Have a food slot that is empty, and not have the food to be cooked equipped
3. Start cooking, then immediately trigger offline progress
4. See error

**Comment by coolrox95** [comment]
Issue has been hotfixed as of v1.0.3 (?1829)
