### ISSUE TITLE
[Bug]: Upgrades that haven’t been unlocked appearing on open

### ISSUE THREAD

**Issue by chrisjben** [MelvorIdle/melvoridle.github.io#2243]
### Describe the bug

God dungeon skill upgrades and woodcutting appear in bank interface upon logging into game that I haven’t unlocked yet. These disappear once I move to a different tab. Also shows woodcutting boosts. 

### Reproduction Steps

1. Close game
2. Reopen and select account
3. On login with default tab set to bank skill icons appear until bank tab navigated away from. 

### Expected behaviour

Should only show upgrades that have been unlocked and only on appropriate skilling tab. 

### Screenshots

![2F0C41D7-3B62-43D7-8A87-E9865D56CADF](https://user-images.githubusercontent.com/19807013/155947035-7a9ca6d2-7681-4277-b4b8-9c694ff998a8.png)
![466F8F72-29E6-425A-80B0-1EF1822FDF00](https://user-images.githubusercontent.com/19807013/155947070-c47e4f9b-19d5-4ca1-98f3-012c5d86304b.jpeg)
![ADDE4E67-E838-49F7-B475-755D3A47EEA7](https://user-images.githubusercontent.com/19807013/155947149-d395fcd3-212d-495a-9871-f8d06f9d4edc.png)
![Uploading AF658E44-8925-4DCC-99E8-602A73D313E2.png…]()

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1804

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.1.
