### ISSUE TITLE
[Bug]: Bank Item Menu is occluded by combat minibar on skinnier resolutions

### ISSUE THREAD

**Issue by Paul-Gazeley** [MelvorIdle/melvoridle.github.io#2245]
### Describe the bug

With the new updates to combat UI (which are very good), I've noticed you can't see the total sell price of anything while in the bank on desktop. The only way to see the price is to leave combat, a way to move or minimise that panel would be great.

**Update**
Just noticed this only happens when the equipment has a special attack, so is quite rare.

![image](https://user-images.githubusercontent.com/61805822/155961608-05bc64e4-174e-4cda-8861-bc62ae871893.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

1804

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
