### ISSUE TITLE
[Bug]: <title>Auto eat on 1 damage

### ISSUE THREAD

**Issue by Myrddinbach** [MelvorIdle/melvoridle.github.io#2248]
### Describe the bug

Whenever I take 1 point of damage my account auto eats. It will go through 300 whales from 1 fire breath attack.

### Expected behaviour

Fix big go back to correct auto eat feature

### Screenshots

![D93D19F8-F60C-4818-BCC6-BBC7896C7C17](https://user-images.githubusercontent.com/100586186/155988264-5fb1709e-532d-48ee-9d58-86206159e432.png)
![7DA3814E-B2E2-485A-86A4-3EB919598597](https://user-images.githubusercontent.com/100586186/155988271-1ad454ed-f913-4559-8c4c-08d72e1ee320.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1804

### Are you using any scripts or extensions?

No

**Comment by Silberdrachi** [comment]
```javascript
eatFood(quantity = 1, interrupt = true, efficiency = 100) {
    const item = this.food.currentSlot.item;
    if (this.stats.maxHitpoints === this.hitpoints || (item.id < 0 && !SETTINGS.general.autoSwapFood && playerModifiers.autoSwapFoodUnlocked < 0))
    return;
     else if (this.food.currentSlot.quantity < 1 && playerModifiers.autoSwapFoodUnlocked > 0 && SETTINGS.general.autoSwapFood) {
      const nonEmptySlot = this.food.slots.findIndex((slot) =>slot.item !== emptyFood);
      if (nonEmptySlot >= 0) {
        this.food.setSlot(nonEmptySlot);
      } 
      else
      return;
    }
    let healingAmount = quantity * Math.max(Math.floor((this.getFoodHealing(item) * efficiency) / 100), 1);
    healingAmount = this.heal(healingAmount);
    this.addItemStat(item.id, ItemStats.TimesEaten, quantity);
    this.manager.addCombatStat(CombatStats.FoodConsumed, quantity);
    this.addItemStat(item.id, ItemStats.HealedFor, healingAmount);
    this.manager.addCombatStat(CombatStats.HPFromFood, healingAmount);
    if (!rollPercentage(this.modifiers.increasedChanceToPreserveFood)) {
      this.food.consume(quantity);
      this.rendersRequired.food = true;
    }
    if (interrupt)
    this.interruptAttack();
    this.consumePotionCharge('AutoEat');
  }
```

If the player doesnt have food swap unlocked, or has it disabled, the check falls through for the empty food. i think adding just another else if before the `let healingAmount` would fix it if you add a` else if (this.food.currentSlot.item === emptyFood) { return; }`  woudl fix the 'no food giving 1 hp' problem

**Comment by MelvorIdle** [comment]
Thanks for the report. This is now hotfixed as of v1.0.3 (?1819)
