### ISSUE TITLE
[Bug]: Hitpoints master achievement unlocks in adventure mode

### ISSUE THREAD

**Issue by BrentRobert** [MelvorIdle/melvoridle.github.io#2251]
### Describe the bug

I just received the hitpoints master achievement on my adventurer.
It should only trigger on standard mode?

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

1805

### Are you using any scripts or extensions?

No

**Comment by Silberdrachi** [comment]
https://store.steampowered.com/news/app/1267910/view/3088910728299100797
![image](https://user-images.githubusercontent.com/76179203/156099134-370ff64e-571a-40ef-91f0-7ddd44c7b5dd.png)

Per the change log, this is intended behavior that hardcore/adventure unlocks standard achievements as well.
