### ISSUE TITLE
[Bug]: Unable to load game on iOS 15.3.1

### ISSUE THREAD

**Issue by haggishunt56** [MelvorIdle/melvoridle.github.io#2252]
### Describe the bug

Updated the app today and now the game won’t start. I’m running the latest version of iOS on an iPhone 12. It shows a blank screen for a while and after putting the phone to sleep for a few minutes displays the error shown in the screenshot attached

### Reproduction Steps

Open Melvor Idle app on iPhone 12, iOS 15.3.1 (latest update) and the app does not load. 

### Screenshots

![647059FE-24F1-4053-BAF7-CC1CD4278D48](https://user-images.githubusercontent.com/54241835/156031692-aece6fb4-bbd1-4f0a-9ed2-689c043e9e49.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

Unknown - can’t access game 

### Are you using any scripts or extensions?

No

**Comment by Silberdrachi** [comment]
Server issues have resolved themselves. id suggest attempting to see if you still have this problem and if not closing the issue.

**Comment by MelvorIdle** [comment]
Thank you for your patience. This has now been resolved!
