### ISSUE TITLE
Can't open Steam version or online

### ISSUE THREAD

**Issue by MrVerloc** [MelvorIdle/melvoridle.github.io#2253]
### Describe the bug

Starting late morning I cannot open the game on my desktop or via the website. I receive an error for the desktop version after a few minutes of loading.

### Expected behaviour

 I expected the game to open.

### Screenshots

![Capture](https://user-images.githubusercontent.com/58958933/156035840-9c8fc654-3703-47a4-adc2-2665decf58c7.PNG)

### Console output

Console doesn't open.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

can't open game to view.

### Are you using any scripts or extensions?

No

**Comment by Silberdrachi** [comment]
Server issues have resolved themselves. id suggest attempting to see if you still have this problem and if not closing the issue.

**Comment by MelvorIdle** [comment]
Thank you for your patience. This has now been resolved!
