### ISSUE TITLE
Quick equip menu does not close when closing skilling minibar

### ISSUE THREAD

**Issue by silverpalm3** [MelvorIdle/melvoridle.github.io#2254]
### Describe the bug

When you open the “Quick-Equip Menu” in the Minibar and minimize the Minibar without minimizing the equip menu it stays open. 

### Reproduction Steps

1: Expand the Minibar by tapping on the up arrow.
2. Open the “Quick-Equip Menu” by tapping on the gear. 
3. Minimize the whole Minibar by tapping on the down arrow. 

### Expected behaviour

The “Quick-Equip Menu” should collapse with the whole Minibar I think. I don’t know the logistics of that 😅 but it seems like it should be the relationship. 

### Screenshots

![041BF785-D577-47FE-8A72-737B2BF8B629](https://user-images.githubusercontent.com/100619339/156044357-ec9d369e-89b7-4811-9271-9944fed0e19d.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [x] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1805

### Are you using any scripts or extensions?

No

**Comment by AaronMitAnderson** [comment]
Bug also occurs on Mobile App (Android) but not steam. Steam has an onHover behavior for the submenu.

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
