### ISSUE TITLE
Melvor Will Not run

### ISSUE THREAD

**Issue by jmburnzy** [MelvorIdle/melvoridle.github.io#2255]
### Describe the bug

Been playing on a high end PC for Months without issue until today

### Reproduction Steps

na

### Expected behaviour

na

### Screenshots

![Screen Shot 02-28-22 at 02 15 PM](https://user-images.githubusercontent.com/9925603/156045698-1c504a5c-803e-4fe6-b287-eb9823cbb5a0.PNG)

### Console output

na

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

latest

### Are you using any scripts or extensions?

No

**Comment by Silberdrachi** [comment]
Server issues have resolved themselves. id suggest attempting to see if you still have this problem and if not closing the issue.

**Comment by MelvorIdle** [comment]
Thank you for your patience. This has now been resolved!
