### ISSUE TITLE
Getting Stuck on Character select on Chrome 

### ISSUE THREAD

**Issue by Juh-Kobe** [MelvorIdle/melvoridle.github.io#2256]
### Describe the bug

When trying to change characters I selected "Select Character" and then it went to the loading menu. After about 2-3 minutes of loading the below error (image) showed up.  After fully exiting the browser and relaunching the webpage I was able to load in to the character 

### Reproduction Steps

1. Launch game in chrome
2. When in a character click on the drop down in the top right 
3. Select "Select Character" 
4. After 2-3 minutes of waiting for it to load I received the error

### Expected behaviour

It will go to the character selection page

### Screenshots

![2022-02-28 14_27_13-Window](https://user-images.githubusercontent.com/78878221/156046433-ad572d50-c261-4356-9abc-cf9b15503899.png)

### Console output

var isTest=false;var currentCharacter=0;var characterSelected=false;var backupSave=null;var dataDeleted=false;var keyVersion="A04";var keyTest="MI-"+keyVersion+"-"+currentCharacter+"-";var key="MI-"+keyVersion+"-"+currentCharacter+"-";var disableSidebarSwipe=false;var currentStartPage=8;var sidebarSwipeTimer=null;var startingGamemode=0;var panVal=0;var GUID;let forceReload=undefined;const setSaveGUID=()=>{if(GUID===undefined){GUID=Math.random().toString(36).substring(2,6);}};function disableSidebarSwipeTimer(){disableSidebarSwipe=true;clearTimeout(sidebarSwipeTimer);sidebarSwipeTimer=setTimeout(function(){disableSidebarSwipe=false;},1000);}
function updateKeys(){key=getKeysForCharacter(currentCharacter);}
function getKeysForCharacter(charID){let saveKey;if(charID===0){saveKey=`MI-${keyVersion}`;}else{saveKey=`MI-${keyVersion}-${charID}-`;}
if(isTest)saveKey=`MI-test-${saveKey}`;return saveKey;}
function setItem(key,value){localStorage.setItem(key,JSON.stringify(value));}
function getItem(key){let keydata=localStorage.getItem(key);if(keydata=="undefined")return undefined;return JSON.parse(keydata);}
function removeItem(key){localStorage.removeItem(key);}
let firstSkillAction=true;function saveData(vars="all"){if(!dataDeleted&&!inCharacterSelection&&(currentGamemode!==1||(currentGamemode===1&&!lolYouDiedGetRekt))){updateKeys();if(!username)username=getLangString("CHARACTER_SELECT","75");saveTimestamp=new Date().getTime();const doSave=vars==="all"||(vars==="offline"&&firstSkillAction);if(doSave){if(DEBUGENABLED)combatManager.saveStats();localStorage.setItem(`${key}saveGame`,getCompressedSaveString());if(vars==="offline"){firstSkillAction=false;}}}}
function getSaveGameOld(keyPrefix){const saveGame={};allVars.forEach((varName)=>{const data=getItem(keyPrefix+varName);if(data!==null&&data!==undefined){saveGame[varName]=data;}else{saveGame[varName]=defaultSaveValues[varName];}});saveGame.version=-1;return saveGame;}
function removeSaveOld(keyPrefix){allVars.forEach((varName)=>{removeItem(keyPrefix+varName);});console.log("Removed old local storage keys.");}
function getLocalSave(keyPrefix){let oldFormat=false;const saveString=localStorage.getItem(`${keyPrefix}saveGame`);let saveGame;if(saveString===null){oldFormat=true;saveGame=getSaveGameOld(keyPrefix);setDefaultSettings(saveGame.SETTINGS);}else{saveGame=getSaveFromString(saveString).saveGame;}
return{saveGame:saveGame,oldFormat:oldFormat,};}
function getLocalSaveVersion(keyPrefix){const saveString=localStorage.getItem(`${keyPrefix}saveGame`);if(saveString===null){return 0;}else{return decompressSaveString(saveString).v;}}
function doesLocalSaveExist(keyPrefix){const saveString=localStorage.getItem(`${keyPrefix}saveGame`);if(saveString===null){if(localStorage.getItem(`${keyPrefix}skillLevel`)!==null){return 1;}else{return 0;}}else{return 2;}}
function loadData(){console.log("Loading Save Game...");let{saveGame,oldFormat}=getLocalSave(key);setGlobalsFromSaveGame(saveGame);console.log("Save Game Loaded...");return oldFormat;}
function deleteData(characterID=-1){let keyToUse;if(characterID<0)keyToUse=key;else keyToUse=getKeysForCharacter(characterID);if(localStorage.getItem(`${keyToUse}saveGame`)!==null){localStorage.removeItem(`${keyToUse}saveGame`);}
removeSaveOld(keyToUse);console.log("Save Game Deleted");dataDeleted=true;}
function exportSave(update=false){if(!update){let exportSaved=getSave();let exportField=document.getElementById("exportSaveField");let exportField2=document.getElementById("exportSaveField2");exportField.value=exportSaved;exportField2.value=exportSaved;}else{let exportSaved=getSave();let exportField=document.getElementById("exportSaveFieldUpdate");let exportField2=document.getElementById("exportSaveFieldUpdate2");exportField.value=exportSaved;exportField2.value=exportSaved;}}
function setCharacterToSave(characterID,saveString){const keyToUse=getKeysForCharacter(characterID);const{saveGame,oldFormat}=getSaveFromString(saveString);if(saveGame.username===null||saveGame.username===undefined)throw Error("Username is null/undefined.");if(oldFormat){for(let i=0;i<allVars.length;i++){setItem(keyToUse+allVars[i],saveGame[allVars[i]]);}
localStorage.removeItem(`${keyToUse}saveGame`);}else{localStorage.setItem(`${keyToUse}saveGame`,saveString);removeSaveOld(keyToUse);}}
function importSave(forceSaveToImport=false,characterID=-1){if(characterID<0)characterID=currentCharacter;if($("#importSaveField").val()!==""&&!forceSaveToImport){$("#import-spinner").removeClass("d-none");deleteData();resetVariablesToDefault();let importField=document.getElementById("importSaveField");const{saveGame,oldFormat}=getSaveFromString(importField.value);window.setTimeout(function(){dataDeleted=false;const keyToUse=getKeysForCharacter(characterID);if(oldFormat){for(let i=0;i<allVars.length;i++){setItem(keyToUse+allVars[i],saveGame[allVars[i]]);}
localStorage.removeItem(`${keyToUse}saveGame`);}else{localStorage.setItem(`${keyToUse}saveGame`,forceSaveToImport);removeSaveOld(keyToUse);}
dataDeleted=true;location.reload();},2000);}else if(forceSaveToImport!==false){if(forceSaveToImport===null||forceSaveToImport===undefined||forceSaveToImport==="")return false;try{setCharacterToSave(characterID,forceSaveToImport);processLocalCharacters();return true;}catch(e){console.error(e);return false;}}
return false;}
function openImportSave(characterID=0){SwalLocale.fire({title:getLangString("CHARACTER_SELECT","38"),html:`<h5 class="font-w400 text-combat-smoke font-size-sm">${getLangString("CHARACTER_SELECT","43")}</h5>
					<div class="form-group">
						<textarea class="form-control" id="import-save-character-selection" name="import-save-character-selection" rows="8" placeholder="${getLangString("CHARACTER_SELECT","91")}" onclick="this.select();"></textarea>
					</div>`,showCancelButton:true,confirmButtonText:getLangString("CHARACTER_SELECT","44"),}).then((result)=>{if(result.value){currentCharacter=characterID;let save=$("#import-save-character-selection").val();if(save.includes("https://melvoridle.com/save/")&&save.length<100){processImportSaveFromLink(save,characterID);}else{if(importSave(save,characterID)){SwalLocale.fire({icon:"success",title:getLangString("CHARACTER_SELECT","73"),html:`<span class='text-dark'>${getLangString("CHARACTER_SELECT","92")}</span>`,});inCharacterSelection=true;}else{SwalLocale.fire({icon:"error",title:getLangString("CHARACTER_SELECT","93"),html:`<span class='text-dark'>${getLangString("CHARACTER_SELECT","94")}</span>`,});}}}});}
function openExportSave(characterID){SwalLocale.fire({title:getLangString("CHARACTER_SELECT","37"),html:`<h5 class="font-w400 text-combat-smoke font-size-sm mb-1">${getLangString("CHARACTER_SELECT","40")}</h5>
				<h5 class="font-w600 text-danger font-size-sm">${getLangString("CHARACTER_SELECT","41")}</h5>
					<div class="form-group">
						<textarea class="form-control" id="export-save-character-selection" name="export-save-character-selection" rows="8" onclick="this.select();">${getSave(true,characterID)}</textarea>
					</div>`,showCancelButton:false,});}
function copyToClipboard(input){if(navigator.clipboard){navigator.clipboard.writeText(input).then(()=>{console.log("Copied to clipboard successfully.");},(err)=>{console.log("Failed to copy the text to clipboard.",err);});}else if(window.clipboardData){window.clipboardData.setData("Text",input);}}
function createSaveShareLink(characterID){SwalLocale.fire({title:getLangString("MENU_TEXT","SAVE_LINK"),html:`<div id="saveLink" class="font-size-sm text-info" style="-webkit-user-select: all!important;
    -moz-user-select: -moz-all!important;
    -ms-user-select: all!important;
    user-select: all!important;"><span class="spinner-border text-info skill-icon-xs"></span></div>`,showCancelButton:false,});const save=getSave(true,characterID);$.ajax({url:"cloud/shareSave.php",type:"POST",async:true,data:{shareSave:save,},}).done(function(d){$("#saveLink").html(`${d}<i class="fa fa-copy ml-3 pointer-enabled" onClick="copyToClipboard('${d}')"></i>`);});}
function importSaveFromLink(characterID){SwalLocale.fire({title:getLangString("CHARACTER_SELECT","38"),html:`<h5 class="font-w400 text-combat-smoke font-size-sm">${getLangString("CHARACTER_SELECT","43")}</h5>
					<div class="form-group">
						<input type="text" class="form-control" id="import-save-link-character-selection" name="import-save-link-character-selection" rows="1" placeholder="${getLangString("CHARACTER_SELECT","91")}"/>
					</div>`,showCancelButton:true,confirmButtonText:getLangString("CHARACTER_SELECT","44"),}).then((result)=>{if(result.value){link=$("#import-save-link-character-selection").val();if(link.includes("https://melvoridle.com/save/"))processImportSaveFromLink(link,characterID);}});}
function processImportSaveFromLink(link,characterID){shortLink=replaceAll(link,"https://melvoridle.com/save/","");$.ajax({url:"cloud/getSaveFromLink.php",type:"GET",async:true,data:{saveLink:shortLink,},}).done(function(d){currentCharacter=characterID;let save=d;if(importSave(save,characterID)){SwalLocale.fire({icon:"success",title:getLangString("CHARACTER_SELECT","73"),html:`<span class='text-dark'>${getLangString("CHARACTER_SELECT","92")}</span>`,});inCharacterSelection=true;}else{SwalLocale.fire({icon:"error",title:getLangString("CHARACTER_SELECT","93"),html:`<span class='text-dark'>${getLangString("CHARACTER_SELECT","94")}</span>`,});}});}
function openDownloadSave(characterID){let downloadSuccessful=false;if(characterID>=0)downloadSuccessful=downloadSave(false,characterID);if(downloadSuccessful){SwalLocale.fire({icon:"success",title:getLangString("CHARACTER_SELECT","73"),html:`<span class='text-dark'>${getLangString("CHARACTER_SELECT","95")}</span>`,});}else{SwalLocale.fire({icon:"error",title:getLangString("CHARACTER_SELECT","93"),html:`<span class='text-dark'>${getLangString("CHARACTER_SELECT","96")}</span>`,});}}
const openCharacterSelectionSettings=function(characterID=0,characterName=""){let html=`<h5 class="font-w400 text-combat-smoke font-size-sm">${characterName}</h5>
				<button role="button" class="btn btn-alt-warning mt-2 mb-2 w-100" onClick="openDownloadSave(${characterID});"><i class="fa fa-file-download mr-2"></i>${getLangString("CHARACTER_SELECT","36")}</button><br>
				<button role="button" class="btn btn-alt-primary mt-2 mb-2 w-100" onClick="openExportSave(${characterID});"><i class="fa fa-file-export mr-2"></i>${getLangString("CHARACTER_SELECT","37")}</button><br>
				<button role="button" class="btn btn-alt-primary mt-2 mb-2 w-100" onClick="createSaveShareLink(${characterID});"><i class="fa fa-file-export mr-2"></i>${getLangString("MENU_TEXT","CREATE_SAVE_LINK")}</button><br>`;if(!isAdsPath()||!afterCutOff())html+=`<button role="button" class="btn btn-alt-primary mt-2 mb-2 w-100" onClick="openImportSave(${characterID});"><i class="fa fa-file-import mr-2"></i>${getLangString("CHARACTER_SELECT","38")}</button><br>`;html+=`<button role="button" class="btn btn-alt-danger mt-4 mb-2 w-100" onClick="accountDeletion(false, ${characterID}, '${characterName}')"><i class="fa fa-times mr-2"></i>${getLangString("CHARACTER_SELECT","39")}</button>`;SwalLocale.fire({title:getLangString("CHARACTER_SELECT","35"),html:html,showCancelButton:false,});};function loadGame(update=false){if(!update){$("#new-update-continue-btn").html('<div class="spinner-border spinner-border-sm text-success" role="status"></div>');window.setTimeout(function(){$("#modal-export-update").modal("hide");if(firstTime===1){$("#modal-account-create").modal("show");updateWindow();}else{loadData();updateWindow();}},1000);}else $("#modal-export-update").modal("show");}
function getSave(customKey=false,charID=0){let keyPrefix=key;if(customKey)keyPrefix=getKeysForCharacter(charID);const saveExists=doesLocalSaveExist(keyPrefix);if(saveExists){switch(saveExists){case 1:return getSaveStringOld(keyPrefix);case 2:return localStorage.getItem(`${keyPrefix}saveGame`);}}else return "";}
function getSaveStringOld(keyPrefix){let toSave=getSaveGameOld(keyPrefix);const pakoSave=pako.gzip(JSON.stringify(toSave),{to:"string"});return btoa(pakoSave);}
function downloadSave(backup=false,save=-1){let exportSaved;let saveUsername="";if(!backup&&save<0)exportSaved=getSave();else if(save>=0)exportSaved=getSave(true,save);else exportSaved=backupSave;var file=new Blob([exportSaved],{type:"text/plain"});if(save>=0){let keySuffix="";let keyPrefix="";if(isTest)keyPrefix="MI-test-";if(save>0)keySuffix=`-${save}-`;saveUsername=getSaveFromString(getSave(true,save)).saveGame.username;}else{saveUsername=username;}
if(window.navigator.msSaveOrOpenBlob){try{window.navigator.msSaveOrOpenBlob(file,"melvoridlesave_"+saveUsername+".txt");return true;}catch(e){return false;}}else{try{var a=document.createElement("a"),url=URL.createObjectURL(file);a.href=url;a.download="melvoridlesave_"+saveUsername+".txt";document.body.appendChild(a);a.click();setTimeout(function(){document.body.removeChild(a);window.URL.revokeObjectURL(url);},0);return true;}catch(e){return false;}}}
function loadGameRaw(saveString){let savegame=getSaveFromString(saveString).saveGame;setGlobalsFromSaveGame(savegame);saveData();}
function setGlobalsFromSaveGame(savegame){try{if(savegame.accountGameVersion<110)updateSavePre110(savegame);if(savegame.accountGameVersion<121)updateSavePre121(savegame);if(savegame.version<=8){if(savegame.itemStats!==undefined&&savegame.itemStats[0].stats===undefined){savegame.itemStats=convertItemStats(savegame.itemStats);}
if(savegame.monsterStats!==undefined&&savegame.monsterStats[0].stats===undefined){savegame.monsterStats=convertMonsterStats(savegame.monsterStats);}}
cleanSaveGame(savegame);convertOldMastery(savegame);newAllVars.forEach((varName)=>{const data=savegame[varName];if(data!==null&&data!==undefined)window[varName]=data;});if(savegame.serialCombat!==undefined){if(savegame.version<=3){combatManager.deserialize(savegame.serialCombat,savegame.version);if(savegame.offline.skill!==null&&savegame.offline.skill===CONSTANTS.skill.Hitpoints)game.activeSkill=ActiveSkills.COMBAT;}else game.deserialize(savegame.serialCombat,savegame.version);}else{combatManager.convertFromOldSaveFormat(savegame);}
if(savegame.version<=8){game.stats.convertFromOldFormat(savegame);}
if(savegame.version<10&&(offline.skill===Skills.Thieving||offline.skill===Skills.Hitpoints)){game.combat.giveFreeDeath=true;}
if(savegame.version<=15){game.summoning.convertFromOldFormat(savegame.summoningData);game.fishing.convertFromOldFormat(savegame);game.cooking.convertFromOldFormat(savegame);}
if(savegame.version<17){game.agility.convertFromOldFormat(savegame);game.astrology.convertFromOldFormat(savegame);}}catch(e){removeForceReload();$("#m-page-loader").attr("class","d-none");$("#game-broke-error-msg").val(e.stack);$("#modal-game-broke").modal("show");console.log(e);}}
function getSaveJSON(save){try{const unpako=atob(save);let savegame;try{savegame=JSON.parse(pako.ungzip(unpako,{to:"string"}));}catch(e){savegame=unpako;}
return savegame;}catch(e){return "";}}
function fixMySave(confirmed=false){$("#save-fix-spinner").removeClass("d-none");console.log("Attempting to fix your save... wish me luck");for(let i=0;i<bank.length;i++){if(bank[i]===null){bank.splice(i,1);console.log("Found invalid bank item, removed.");}}
saveData();let save=getSave();const unpako=atob(save);const savegame=JSON.parse(pako.ungzip(unpako,{to:"string"}));for(let i=0;i<allVars.length;i++){if(savegame[allVars[i]]!==null&&savegame[allVars[i]]!==undefined)window[allVars[i]]=savegame[allVars[i]];}
saveData();console.log("Save fix completed... refreshing...");window.setTimeout(function(){location.reload();},2000);}
function setBackupSaveDetails(save){if(save!==null){const unpako=atob(save);let savegame;try{savegame=JSON.parse(pako.ungzip(unpako,{to:"string"}));}catch(e){savegame=unpako;}
let version=savegame.gameUpdateNotification;$("#settings-backup-save-version").text(version);$("#exportBackupSaveField").val(backupSave);}}
function getItemFromSave(saveString,varName){let unpako;try{unpako=atob(saveString);}catch(e){return undefined;}
let savegame;try{savegame=getSaveFromString(saveString).saveGame;}catch(e){try{savegame=JSON.parse(unpako);}catch(e){return undefined;}}
let keydata=savegame[varName];if(keydata=="undefined")return undefined;return keydata;}
function setForceReload(character,reloadNow=false){console.log("set force reload to "+character);forceReload=character;dataDeleted=true;if(reloadNow){resetEntirePage(isTest);}}
function removeForceReload(){forceReload=undefined;}
let quickEquipInterval=-1;const onloadEvent=function(accessCheck=true,resetPage=true){if(!gameOriginCheck())$("body").html(`Why tho<br><img src="assets/april/images/lemon.jpg">`);else{if(resetPage){resetEntirePage(isTest);}else{let errorNum=0;try{connectingToCloud=false;updateKeys();$(".cloud-connection-status-text").removeClass("text-danger");$(".cloud-connection-status-text").removeClass("text-success");$(".btn-cloud-sign-in").addClass("d-none");if(isAfterRelease())$(".game-version").addClass("d-none");if(location.origin==="https://steam.melvoridle.com")$(".cloud-connection-status-header-mobile").addClass("d-none");if(isTest&&accessCheck){if(!confirmedLoaded)$("#m-page-loader-test").attr("class","show");$("#m-page-loader").attr("class","d-none");let forceLoad=true;if(forceReload===undefined)forceLoad=false;checkTestAccessInit(forceLoad,accessCheck);}else{errorNum=4;let CSAV;if(getItem("CSAV")===undefined||getItem("CSAV")===null)CSAV=3;else CSAV=getItem("CSAV");if(CSAV<characterSelectAnnouncementVersion){$("#character-selection-page-8").removeClass("d-none");$("#character-selection-page-0").addClass("d-none");currentStartPage=8;setItem("CSAV",characterSelectAnnouncementVersion);}else{$("#character-selection-page-8").addClass("d-none");if(localStorage.getItem("language")!==undefined&&localStorage.getItem("language")!==null&&currentStartPage!==9){$("#character-selection-page-0").removeClass("d-none");currentStartPage=0;}}
if(forceReload===undefined){errorNum="7a";loadCharacterSelection(false);errorNum="7b";$("#m-page-loader").attr("class","d-none");}else{if(isTest)$("#m-page-loader-test").attr("class","d-none");characterLoading=false;selectCharacter(forceReload,true);}
updateUIForLanguageChange();errorNum=8;$("#dropdown-content-custom-amount").bind("keyup input change",function(){let customQty=$("#dropdown-content-custom-amount").val();$("#dropdown-content-custom-amount-1").val(customQty);$("#dropdown-content-custom-amount-2").val(customQty);if(Number.isInteger(+customQty)&&customQty>0)updateBuyQty(customQty);});$("#dropdown-content-custom-amount-1").bind("keyup input change",function(){let customQty=$("#dropdown-content-custom-amount-1").val();$("#dropdown-content-custom-amount").val(customQty);$("#dropdown-content-custom-amount-2").val(customQty);if(Number.isInteger(+customQty)&&customQty>0)updateBuyQty(customQty);});$("#dropdown-content-custom-amount-2").bind("keyup input change",function(){let customQty=$("#dropdown-content-custom-amount-2").val();$("#dropdown-content-custom-amount").val(customQty);$("#dropdown-content-custom-amount-1").val(customQty);if(Number.isInteger(+customQty)&&customQty>0)updateBuyQty(customQty);});if(!isMobile()){$("#minibar-quick-equip").on("mouseover",function(){$("#skill-footer-minibar-items-container").removeClass("d-none");}).on("mouseout",function(){quickEquipInterval=setInterval(function(){if(!$("#skill-footer-minibar-items-container:hover").length&&!$("#minibar-quick-equip:hover").length){$("#skill-footer-minibar-items-container").addClass("d-none");clearInterval(quickEquipInterval);}},500);});}
errorNum=9;$("#searchTextbox").keyup(function(){let search=$("#searchTextbox").val();updateBankSearch(search);if(search==="wherearemylemons")addItemToBank(CONSTANTS.item.Lemon,1);else if(search==="8"){if(!eightSeconds){addItemToBank(CONSTANTS.item.Eight,1);eightSeconds=true;window.setTimeout(function(){eightSeconds=false;},8000);}}else if(search==="uuddlrlrba"){showFireworks(true);window.setTimeout(function(){removePyro();clearInterval(pyroInterval);},10000);}});errorNum=10;if(isTest)$("#test-env").removeClass("d-none");ifvisible.on("blur",function(){if(confirmedLoaded&&(pauseOfflineActions||isMobile())&&!game.isGolbinRaid&&inFocus&&location.origin!=="https://steam.melvoridle.com"&&tutorialComplete){inFocus=false;game.pauseActiveSkill(true);}});ifvisible.on("focus",function(){if(confirmedLoaded&&(pauseOfflineActions||isMobile())&&!game.isGolbinRaid&&!inFocus&&location.origin!=="https://steam.melvoridle.com"&&tutorialComplete){inFocus=true;game.unpauseActiveSkill(true);}});$(window).bind("beforeunload",function(event){if(!SETTINGS.general.enabledOfflineCombat&&characterSelected){if(combatManager.isInCombat)combatManager.stopCombat();}
if(!tutorialComplete)idleChecker(-1);if(!dataDeleted&&characterSelected&&(getItem("MI-forceReload-")===undefined||getItem("MI-forceReload-")===null)){saveData();}
clearTimeout(tenSecondUpdateTimeout);if(confirmationOnClose&&location.origin!=="https://steam.melvoridle.com/")return getLangString("CHARACTER_SELECT","97");});$(document).scroll(function(){handleBankSidebarScroll();});errorNum=12;$("body").on("swipeleft",function(){let mq=checkMediaQuery("(max-width: 991px)");if(mq&&itemBeingDragged<0)One._uiApiLayout("sidebar_close");});$("body").on("swiperight",function(){let mq=checkMediaQuery("(max-width: 991px)");if(mq&&itemBeingDragged<0&&!disableSidebarSwipe)One._uiApiLayout("sidebar_open");});}}catch(e){$("#on-load-error").html("<span class='font-w700'>An error has occured loading the game:<br>If you are running iOS 13, please update to iOS 14 as this will fix this error.</span><br>"+e.message+"<br>"+e.stack);}}}};const isAfterRelease=function(){return new Date().getTime()>1637258400000;};window.onload=function(){if(location.origin==="https://test.melvoridle.com")isTest=true;if(afterCutOff()&&location.pathname.includes("index_ads.php")){if(localStorage.getItem("isPremium")!==undefined&&localStorage.getItem("isPremium")!==null){if(Number.parseInt(localStorage.getItem("isPremium"))===1)location.href="index_noads.php";}}else if(afterCutOff()&&location.pathname.includes("index_noads.php")&&!isTest){if(localStorage.getItem("isPremium")!==undefined&&localStorage.getItem("isPremium")!==null){if(Number.parseInt(localStorage.getItem("isPremium"))!==1)location.href="index_ads.php";}else location.href="index_ads.php";}
let langToSet="en";$(".language-select").removeClass("d-none");if(localStorage.getItem("language")!==undefined&&localStorage.getItem("language")!==null)langToSet=localStorage.getItem("language");else changePageCharacterSelection(9);setLanguage(langToSet).then(()=>{onloadEvent(isTest,false);});};function resetEntirePage(accessCheck=true,startCombatLoad=true){if(location.pathname.includes("index_mobile.php")){$("#page-container").load("pageContainer_mobile.php?7",function(){loadCombat();onloadEvent(accessCheck,false);});}else{if(location.origin==="https://melvoridle.com"&&location.pathname.includes("index_ads.php")){$("#page-container-web").load("pageContainer_ads_init_after.php?7",function(){loadCombat();onloadEvent(accessCheck,false);});}else{$("#page-container").load("pageContainer.php?7",function(){loadCombat();onloadEvent(accessCheck,false);});}}}
function handleBankSidebarScroll(){let wrapper=$("#bank-item-wrapper");let box=$("#bank-item-box");let offsetTop=-wrapper.offset().top+$(window).scrollTop();let offsetBottom=wrapper.offset().top-$(window).scrollTop()+wrapper.outerHeight()-box.outerHeight();if(offsetBottom>0&&offsetTop<0){box.css({top:0,});}else if(offsetBottom>0&&offsetTop>0){box.css({top:offsetTop+"px",});}else{box.offset({top:$(window).scrollTop()+offsetBottom,});}}
function changePageCharacterSelection(page){if(currentStartPage!==page){$("#character-selection-page-"+currentStartPage).attr("class","d-none animated fadeOutRight");$("#character-selection-page-"+page).attr("class","w-100 animated fadeInRight");currentStartPage=page;if(page!==0&&page!==5){$(".btn-cloud-sign-in").addClass("d-none");$(".btn-cloud-sign-in-back").removeClass("d-none");}else{if(!connectedToCloud)$(".btn-cloud-sign-in").removeClass("d-none");$(".btn-cloud-sign-in-back").addClass("d-none");}
if(page===1)enableLoginForm();if(page===3){$("#gamemode-selection").html(createGamemodeSelectionElements());for(let i=0;i<Object.keys(GAMEMODES).length;i++){$("#gamemode-select-btn-"+i).mouseover(function(){$("#gamemode-select-bg-"+i).addClass("opacity-40");});$("#gamemode-select-btn-"+i).mouseleave(function(){$("#gamemode-select-bg-"+i).removeClass("opacity-40");});}}}}
const setStartingGamemode=function(gamemode){if((gamemode===1||gamemode===2)&&afterCutOff()&&isAdsPath())startingGamemode=0;else startingGamemode=gamemode;$("#gamemode-selection-text").html(`<img class="skill-icon-xs mr-2" src="${GAMEMODES[gamemode].media}">${GAMEMODES[gamemode].name}`);changePageCharacterSelection(4);};function resetVariablesToDefault(){newAllVars.forEach((varName)=>{window[varName]=defaultSaveValues[varName];});}

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1805

### Are you using any scripts or extensions?

No

**Comment by Juh-Kobe** [comment]
Happened again when I went into the URL from new chrome window 

Here is the console info 
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
style.css:1          Failed to load resource: the server responded with a status of 404 ()
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
lang/en.json?319:1          Failed to load resource: the server responded with a status of 522 ()
language.js?1805:2 Error: Could not fetch file: ./lang/en.json?319
    at fetchLanguageJSON (language.js:1:456)
    at async setLanguage (language.js:2:111)
(anonymous) @ language.js?1805:2
style.css:1          Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by Silberdrachi** [comment]
Server issues have resolved themselves. id suggest attempting to see if you still have this problem and if not closing the issue.

**Comment by MelvorIdle** [comment]
Thank you for your patience. This has now been resolved!
