### ISSUE TITLE
[Bug]: Thieving NPC buttons are not unlocked on level up

### ISSUE THREAD

**Issue by kyle-dotcom** [MelvorIdle/melvoridle.github.io#2257]
### Describe the bug

so today i woke up too the servers being fucked as i know you are aware, i managed to get on. i went to thieving as that is what im training at the moment. i reached level 49 and the option you usually unlock didnt appear. i then reached level 54 to unlock fisherman and that also didnt appear. multiple people have had the same issue. i have reloaded the game on both occasaion to no avail, hence why im writing this.

### Reproduction Steps

1. go to thieving
2. reach level 49
3. no option to thieve a troll
4. reach lvl 54 and again no option shows up to thieve a fisherman

### Expected behaviour

i expected both of the options to thieve show up, but neither did.

### Screenshots

![level 55 thieving](https://user-images.githubusercontent.com/77696653/156083878-a9993def-ad7f-4c58-9ffe-13eb1310a17d.PNG)
![49 and 54 not unlocked](https://user-images.githubusercontent.com/77696653/156083879-1bba9326-3abf-4a92-ab35-69dc85abcc5e.PNG)

### Console output

i am on steam.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1805

### Are you using any scripts or extensions?

No

**Comment by jonathan-correia** [comment]
To mitigate: restarting the game unlocked the thieving targets for me

**Comment by MelvorIdle** [comment]
Thanks for the report. This is now hotfixed as of v1.0.3 (?1819)
