### ISSUE TITLE
[Bug]: <Clicking to eat food eats multiple>

### ISSUE THREAD

**Issue by Eredano** [MelvorIdle/melvoridle.github.io#2258]
### Describe the bug

In combat when you click to eat any kind of food it uses up two pieces of food if it can even when clicked on the minibar. The only time it uses up one food is when you click and quickly drag away from the food icon. Also if there is no food and you click it heals you one hp per press and release.

### Reproduction Steps

1. Get into combat
2. Take damage to where you are low enough to use more than one piece of food
3. Click to eat food

### Expected behaviour

It should use up one food per click and more when held down.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1806

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
I have reduced the sensitivity of Hold to Eat. Let me know if this still occurs.

**Comment by Eredano** [comment]
The sensitivity is good now and the healing with no food equipped is gone but it still eats food twice, one food when you press down the mouse button and then uses the second piece of food when you release the mouse button unless you drag the mouse fast off of the food icon.

**Comment by Eredano** [comment]
> I have reduced the sensitivity of Hold to Eat. Let me know if this still occurs.

The sensitivity is good now and the healing with no food equipped is gone but it still eats food twice, one food when you press down the mouse button and then uses the second piece of food when you release the mouse button unless you drag the mouse fast off of the food icon.

**Comment by l3vines** [comment]
Yep still eats 2 items for me 2.. Just give us a turn off option for now so i dont have to wast food to this bug...

**Comment by Eredano** [comment]
> Yep still eats 2 items for me 2.. Just give us a turn off option for now so i dont have to wast food to this bug...

it doesn't waste food as it still heals you that amount and doesn't use a second food unless you are low enough that one food doesn't fully heal you. You can click and quickly drag off the food icon to only eat one piece.

**Comment by l3vines** [comment]
> 
Complete and utter BS. It still wastes food.
![image](https://user-images.githubusercontent.com/16386078/156479524-c81f750b-043e-469a-bde9-e73f63d3ceeb.png)

**Comment by MelvorIdle** [comment]
> > I have reduced the sensitivity of Hold to Eat. Let me know if this still occurs.
> 
> The sensitivity is good now and the healing with no food equipped is gone but it still eats food twice, one food when you press down the mouse button and then uses the second piece of food when you release the mouse button unless you drag the mouse fast off of the food icon.

Thanks for the confirmation. Will continue to look into the bug.

**Comment by MelvorIdle** [comment]
I have located the source of the bug. A fix will be going live in the next hour or so for it :)

**Comment by MelvorIdle** [comment]
Hotgix has been pushed live. This if for version v1.0.3 ?1821. Let me know if you no longer receive the double eat on click.

**Comment by l3vines** [comment]
> Hotfix has been pushed live. This if for version v1.0.3 ?1821. Let me know if you no longer receive the double eat on click.

its working how it should be working now.

**Comment by Eredano** [comment]
It is all working now and I even messed around a little to try to break it and it all seems fixed and is working great. Thanks for the fix.

**Comment by ShenYuzu** [comment]
Hi, Issue from before has reappeared, it's the exact same as before. Did all the same things to reproduce the bug.

**Comment by cheeseman499** [comment]
Can confirm, multiple foods are being eaten in a single click. I am using steam to run the game on PC.
