### ISSUE TITLE
[Bug]: <title> Food Bug

### ISSUE THREAD

**Issue by DrowsyDude** [MelvorIdle/melvoridle.github.io#2259]
### Describe the bug

Food is being eaten every time i take damage, even if it's 1hp. I do not have auto-eat.

### Expected behaviour

That the food isn't eaten every time i take damage

### Screenshots

https://gyazo.com/bfc25fad518f2126a95131f8cad0b71f

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1806

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Thanks for the report. This is now hotfixed as of v1.0.3 (?1819)
