### ISSUE TITLE
Sunset stab damage over time does not kill the enemy

### ISSUE THREAD

**Issue by stevenswan** [MelvorIdle/melvoridle.github.io#226]
**Describe the bug**
The sunset stab DoT will cause the enemy to have a negative hp value rather than killing it.

**To Reproduce**
1. Fight an enemy
2. Before the enemy dies your character has to use sunset stab
3. The dot then has to send the hero to a negative hp value

**Expected behavior**
The enemy dies

**Screenshots**
![bug](https://user-images.githubusercontent.com/10628958/82125937-2a188400-97a1-11ea-99d4-4114641a827a.png)

**Comment by MelvorIdle** [comment]
Fixed in upcoming update.
