### ISSUE TITLE
[Bug]: <Skillcape Equip no longer on skill page (iOS)>

### ISSUE THREAD

**Issue by yezzur** [MelvorIdle/melvoridle.github.io#2260]
### Describe the bug

The skillcape is no longer found on the accessibility bar on the skill page

### Reproduction Steps

1. Open any skill page 
2. Look for skillcape equip
3. Open quick equip menu
4. Observe no skillcape option

### Expected behaviour

E-z swap for skillcapes (makes farming doable) 

### Screenshots

![A9ACCE93-9BE4-4881-8BDF-4ABE8B4425C7](https://user-images.githubusercontent.com/100668754/156117784-f667e81b-56ed-4581-bc48-aa89981efbda.jpeg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1806

### Are you using any scripts or extensions?

No

**Comment by Silverfyree** [comment]
There was a bug at patch launch that caused it to not appear, however you can freely add any skillcape or items to your skillbar now.

**Comment by yezzur** [comment]
Ah! I see it now! Any shot the skillcapes will be defaulted to their respective skill page?

**Comment by Silverfyree** [comment]
I believe a fix will be deployed at some point to default it to each bar, but for now you can easily manually add each cape to the skills you have them for.

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
