### ISSUE TITLE
[Bug]: No cooked items after offline progression

### ISSUE THREAD

**Issue by BlazneeX** [MelvorIdle/melvoridle.github.io#2261]
### Describe the bug

Normal login message, over 2000 cooked salmon, no extra salmon in the bank. Raw salmon was gone and there was no cooked salmon.

### Reproduction Steps

Open Melvor idle 

### Expected behaviour

To get normal offline progression and receive the items that were cooked

### Screenshots

![Login](https://user-images.githubusercontent.com/100670794/156121128-2237f496-65f5-4a71-88a5-cfa065c2bae1.PNG)
![Bank](https://user-images.githubusercontent.com/100670794/156121138-d467b96c-ec8c-419a-8a4e-80fe6164057d.PNG)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1806

### Are you using any scripts or extensions?

No

**Comment by Silverfyree** [comment]
Hi, looks like you may be using the auto food equip upgrade.
This means food that is cooked is automatically equipped to your combat tab.
