### ISSUE TITLE
[Bug]: <title> Game won’t load

### ISSUE THREAD

**Issue by Paltebrando** [MelvorIdle/melvoridle.github.io#2264]
### Describe the bug

Game is stuck loading/connecting

### Screenshots

> 

> 
![70CD7D1A-5741-4505-BB78-539587957945](https://user-images.githubusercontent.com/100693925/156170669-42032838-718e-4abd-9cd9-6c9293949688.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1341

### Are you using any scripts or extensions?

No

**Comment by Paltebrando** [comment]
Couldn’t find subversion but it’s the most current one I’m sure.

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
