### ISSUE TITLE
[Bug]: thieving offline progression issues

### ISSUE THREAD

**Issue by sabrael** [MelvorIdle/melvoridle.github.io#2267]
### Describe the bug

A few observations on thieving, after the update:

If I'm afk thieving, it stops when I log in. I'm farming sigils, and have only been logging in to check my progress + replant seeds. I've already had a few times I forgot to restart thieving, because I expected it to just keep going like other skills.

There also seems to be some issue with offline progression calculation. As mentioned above, I've been farming a single mob (squire) for sigils over the past couple of days. Here's a typical hour's progress:
![Screenshot_20220301-100132_Melvor Idle](https://user-images.githubusercontent.com/32584035/156199200-f75ed6f5-87e7-4de5-9278-4e3f32c613fc.jpg)

...and here's my progress for an entire night:
![Screenshot_20220301-090141_Melvor Idle](https://user-images.githubusercontent.com/32584035/156199238-b4516ef2-2465-476c-ad0b-3ddbddcb4e8d.jpg)

### Reproduction Steps

1. Start thieving (continue on stun)
2. Save and quit
3. Log back in
4. Check offline gains, and observe that thieving has stopped

### Expected behaviour

Thieving should continue until:
a) The player dies to stun damage
b) The player selects another skill
c) The player manually halts thieving

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1806

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
It looks like your thieving may be stopping because your bank is full. This functionality is changed by the Toggle Ignore Bank Full setting:
![image](https://user-images.githubusercontent.com/58208131/156448787-6d45014c-9a1d-400c-b624-df991ce71ddd.png)

Can you confirm if you have this setting on or off?

**Comment by sabrael** [comment]
Did not know that setting existed - yeah, it was turned off. Will see how things go overnight, but that was most likely the issue. I had just assumed it would work the same as combat, and you'd lose anything you didn't have the inventory space for.
