### ISSUE TITLE
[Bug]: <title>yak not added dr to stats

### ISSUE THREAD

**Issue by Myrddinbach** [MelvorIdle/melvoridle.github.io#2268]
### Describe the bug

The yak tablet is not adding 1% dr to my stats

### Screenshots

![0E7714D0-FF01-4022-B4D6-F0575D6BC833](https://user-images.githubusercontent.com/100586186/156207113-fa09b716-f29c-4bec-ac64-1e8b4d50dafb.png)
![68686CD6-656E-4824-AA05-3D9B26AC95AD](https://user-images.githubusercontent.com/100586186/156207119-c30dfc94-b307-4d58-966d-79c690797560.png)
![25BE4900-267A-4F7D-8A4A-E3CEA926DB1F](https://user-images.githubusercontent.com/100586186/156207123-71293964-eb88-412a-badb-88a35a83d566.png)
![A8A49931-B3AB-49F6-A182-982A64E591C2](https://user-images.githubusercontent.com/100586186/156207128-d784c1d7-249f-468c-9dc1-d6f82da750cf.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1806

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
