### ISSUE TITLE
[Bug]: Save never fully loads

### ISSUE THREAD

**Issue by btvanhooser** [MelvorIdle/melvoridle.github.io#2269]
### Describe the bug

When selecting a character from the starting menu after being signed in, one of 2 things happens:

1. The game will continue to have a spinning showing a "loading" state on the character that I just selected
2. The game will begin loading in assets and show the shell of the game with certain values populated (correct levels, correct bank value, etc)

The errors in the console seem to suggest that something went wrong with PlayFab, but I should be successfully logged in and whatnot since I can grab my saves from the cloud still, and I get the green banner on the character select screen letting me know that it was successful as well.

![image](https://user-images.githubusercontent.com/13162723/156210052-fc3d1b2b-8ae3-4a00-92ed-edc4c9602e59.png)

This is failing on:
iOS safari
iOS chrome
iOS brave
iOS app
windows chrome
windows brave

### Reproduction Steps

1. Just import the character
2. Try to load it

Exported Character: 
[BadMelvorSave.txt](https://github.com/MelvorIdle/melvoridle.github.io/files/8163254/BadMelvorSave.txt)

### Expected behaviour

The game loads up and offline progress is displayed. The game should be playable.

### Screenshots

![image](https://user-images.githubusercontent.com/13162723/156210569-f1b313d3-4575-4334-a645-70c6da6c0511.png)

### Console output

www.googletagmanager.com/gtag/js?id=UA-129674422-1:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
style.css:1          Failed to load resource: the server responded with a status of 404 ()
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
index.html:1 Unchecked runtime.lastError: The message port closed before a response was received.
index_noads.php:1 Error handling response: TypeError: self.processResponse is not a function
    at chrome-extension://cmkdbmfndkfgebldhnkbfhlneefdaaip/js/notification.js:154:10
index_noads.php:1 Unchecked runtime.lastError: The message port closed before a response was received.
cloud.js?1806:67 Connected to PlayFab successfully
2cloud.js?1806:75 Uncaught TypeError: Cannot read properties of undefined (reading 'Value')
    at cloud.js:75:286
    at XMLHttpRequest.xhr.onloadend (PlayFabClientApi.js:101:25)
style.css:1          Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for chrome-extension://pgjjikdiikihdfpoppgaidccahalehjh/webspeed.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
save.js?1806:71 set force reload to 0
combatManager.js?1806:1 Combat Manager Built...
raidManager.js?1806:1 Golbin Raid Manager Built...
save.js?1806:15 Loading Save Game...
save.js?1806:15 Save Game Loaded...
main.js?1806:6 Game Loaded

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [X] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1806

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Does the game load for you in incognito mode? I do see an extension throwing errors in console, so maybe eliminating that might fix it.
