### ISSUE TITLE
Throwing Knives Mastery Does Not Level Up

### ISSUE THREAD

**Issue by connorwest** [MelvorIdle/melvoridle.github.io#227]
**Describe the bug**
The mastery level for metal throwing knives does not advance once reaching the required amount for any metal throwing knife.

**To Reproduce**
1. Make more than 7 throwing knives of any time
2. See error as the mastery does not level up

**Expected behavior**
The Mastery should increase

**Screenshots**
https://i.imgur.com/V9vEyUj.png
https://i.imgur.com/D21GtYf.png

**Browser**
Google Chrome | 81.0.4044.138 (Official Build) (64-bit) (cohort: Stable)

**Console output**
Please open the console by pressing F12 and copy it here.
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js?threshold=90:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
save.js?291:484 Local backup successfully stored
save.js?291:48 Loading Save Game...
save.js?291:209 Save Game Loaded...
save.js?291:48 Loading Save Game...
save.js?291:209 Save Game Loaded...
smithing2.js?285:191 Loading Smithing...
mastery.js?284:183 Updating Masteries
mastery.js?284:23 Loading Masteries...
main.js?313:1259 Game Loaded
oneui.core.min.js?205:6 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ oneui.core.min.js?205:6
cloud.js?288:81 Melvor Cloud Connection: Failed
menus.js:583 SEMI Loaded, but may experience errors.
katorone.js:256 Katorone Automation is set up and ready to activate.
DevTools failed to load SourceMap: Could not load content for chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by MelvorIdle** [comment]
Can you please confirm if this still occurs with scripts disabled.
