### ISSUE TITLE
[Bug]: Incorrect Fishing Secret Area Special catch chance

### ISSUE THREAD

**Issue by stangen** [MelvorIdle/melvoridle.github.io#2270]
### Describe the bug

When fishing for seahorses, skeleton fish, and magic fish with greater than 50 mastery with the specific fish and no other bonuses, the special catch chance is listed as 5% instead of 8%. I haven't verified whether this is just a text error or whether specials are only being caught 5% of the time instead of 8% of the time.

### Expected behaviour

The Fishing Secret Area Special catch chance with greater than 50 mastery in the specific fish type should be 8%, from the Special Area chance (5%) plus the bonus from 50 mastery (3%).

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

1806

### Are you using any scripts or extensions?

No

**Comment by dbeckwith** [comment]
I also saw this on desktop:
![image](https://user-images.githubusercontent.com/1279939/156251348-e08c2138-1e24-428a-a27b-0bb7643885fe.png)

**Comment by MelvorIdle** [comment]
Thanks for the report. This is now hotfixed as of v1.0.3 (?1819)
