### ISSUE TITLE
[QoL]: few things

### ISSUE THREAD

**Issue by alienjg** [MelvorIdle/melvoridle.github.io#2272]
### Describe the bug

1. would be nice if you click on an item you can see or go where you can get this. When you want to craft Iron Ore you can click on the ore and end up in the mining window for example.
2. maybe for upgrade item too. You want to upgrade ancient claw then click on the item you need or a tooltip would be nice too.
3. add a box to adjust the amount of items to craft/mine/fish ...

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1819

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
This issue tracker is for bug reports only, not suggestions for the game. If you would like to make a suggestion, please join the community discord: https://discord.gg/melvoridle or leave a post on the subreddit: https://www.reddit.com/r/MelvorIdle/.
