### ISSUE TITLE
[Bug]: Mastery level over 99/99

### ISSUE THREAD

**Issue by Niptoc** [MelvorIdle/melvoridle.github.io#2275]
### Describe the bug

On the menu the level are displayed over 99/99 on some mastery

![Screenshot_2022-03-02-13-17-27-269_com malcs melvoridle](https://user-images.githubusercontent.com/33058481/156360767-55c70827-24d7-48d7-aad0-6ee7a48ae473.jpg)

This errors is on the last version 1.0.3

### Reproduction Steps

1. Click to unfold the menu

### Expected behaviour

The level should not be over the max. Or I missed something.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1819

### Are you using any scripts or extensions?

No

**Comment by Niptoc** [comment]
Same issue on the related skills: (Android)

![Screenshot_2022-03-02-13-30-31-062_com malcs melvoridle](https://user-images.githubusercontent.com/33058481/156362093-763446a9-0a08-4206-ba0e-170a77b00b9b.jpg)

**Comment by Gnomeball** [comment]
This isn't a bug, toggle "Show Virtual Levels" in your settings to return to it capping at 99/99.

**Comment by Niptoc** [comment]
> This isn't a bug, toggle "Show Virtual Levels" in your settings to return to it capping at 99/99.

Thank you! I forgot amor this feature.
