### ISSUE TITLE
[Spelling/Grammar]: Adv Mode pre-Slayer lock out text.

### ISSUE THREAD

**Issue by Gnomeball** [MelvorIdle/melvoridle.github.io#2276]
### What text is wrong?

When playing Adventure mode, before unlocking Slayer, attempting to open the area view presents this screen

![image](https://user-images.githubusercontent.com/45293392/156363121-d33d66a9-49ce-481e-82ad-7977d74a62c5.png)

### What is the correct spelling or grammar?

Should perhaps read "these Combat Areas"

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
