### ISSUE TITLE
[Bug]: iOS can’t drag items into bank tab

### ISSUE THREAD

**Issue by yakobie** [MelvorIdle/melvoridle.github.io#2277]
### Describe the bug

I cannot drag anything into any bank tabs on the iOS version of the game. 

### Reproduction Steps

1. Go to bank
2. Hold item
3. Drag over bank tab (can’t create tabs either)
4. ????
5. Don’t profit

### Expected behaviour

It should move the item into the tab

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

I don’t see it in IOS but it has been like this for months so I’m not sure if it is version based

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This will be fixed in a future update :)
