### ISSUE TITLE
[Bug]: Cannot connect or disconnect phone for push notifications 

### ISSUE THREAD

**Issue by acrusis** [MelvorIdle/melvoridle.github.io#2280]
### Describe the bug

I am unable to connect or disconnect a device from the game for the purpose of push notifications. I am unsure why this bug has occured and unfortunately am not sure of the steps to reproduce it. Where there should be a "connect" button in the settings, there is instead a loading icon which does not disappear. 

### Screenshots

![Screenshot_20220303-115335](https://user-images.githubusercontent.com/97822089/156475515-392d1c9a-6703-4582-a4c7-ed52e2f6b2a5.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1819

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
