### ISSUE TITLE
crow/devil synergy reduces XP even when not active 

### ISSUE THREAD

**Issue by vuzuv** [MelvorIdle/melvoridle.github.io#2281]
### Describe the bug

Crow/Devil synergy is only activated on elemental tunes - so 2/1 crow and devil are used and fire runes are granted and xp is reduced by 5%

If you have crow and devil active on non-elemental runes, such as Ancient, only 1 crow is used for the +2 tabs, devil is not used as the synergy does not apply - but the XP gained is reduced by 5% anyway. 

### Reproduction Steps

Apply devil/crow synergy and see xp is reduced on non elemental runes for no benefit. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1821

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
