### ISSUE TITLE
[Bug]: Transparent part of the combat widget not clicktroughable

### ISSUE THREAD

**Issue by l3vines** [MelvorIdle/melvoridle.github.io#2282]
### Describe the bug

The transparent part next to the 1 is not clicktroughable.
![image](https://user-images.githubusercontent.com/16386078/156525633-2c5efa7c-4b8f-48fb-9423-ece16076995d.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

1821

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been hotfixed as of v1.0.3 (?1835).
