### ISSUE TITLE
[Bug]: Sailor's top does not reduce special chance from mastery or Ent Octopus Synergy

### ISSUE THREAD

**Issue by jshepler** [MelvorIdle/melvoridle.github.io#2284]
### Describe the bug

The -3% special chance doesn't seem to be getting applied correctly or at all. In an area with base 0 special, +3% from item mastery, -3% from sailor's top, no other modifiers/bonuses, special is expected to be 0% but that is no longer the case.

Looking at the code, the player modifiers are clamped such that special would not be below 0 and then item mastery and ent/oct synergy are applied afterwards. This makes me think the intention is to have a minimum special of that mastery+synergy. If so, then what's the purpose of the sailor's top?

Some discussion on [reddit](https://www.reddit.com/r/MelvorIdle/comments/t5raqa/fishing_special_chance_calculation_with_sailor/).

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1819

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been hotfixed as of v1.0.3 (?1848).
