### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by Yingus98** [MelvorIdle/melvoridle.github.io#2285]
### Describe the bug

Not sure if its really a bug or not but when I'm gathering summoning marks and offline when I come back I'm bombarded with messages. I collected 14 marks of the bear while I was offline and I was hit with the notification of getting a mark of the bear 14 times in a row instead of just letting me know I'm at mark level 2 and then 3 like I remember from my main. 

### Expected behaviour

Notification upon hitting mark levels 1, 2, 3. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1822

### Are you using any scripts or extensions?

No

**Comment by CarrotMD** [comment]
Check your settings 
![imagem](https://user-images.githubusercontent.com/95091791/156745031-6210b3a5-f0d7-4f21-a6d5-5ef1a2089a3f.png)
