### ISSUE TITLE
[Bug]: Can't Manually Eat on Mobile

### ISSUE THREAD

**Issue by loganthepage** [MelvorIdle/melvoridle.github.io#2286]
### Describe the bug

Tapping the food button once no longer eats. Since the "hold to eat" option was added, it is no longer possible to manually eat a single food.

### Reproduction Steps

1. Enter combat (combat area, slayer, or dungeon)
2. When health is missing, tap the food button. The button outline flashes green, but nothing is eaten.
3. Hold the food button. After a brief delay, food is eaten.

### Expected behaviour

Tapping once should still eat a single piece of food. Now the only way to manually eat is to spam eat.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1822

### Are you using any scripts or extensions?

No

**Comment by mkrussell16** [comment]
I am experiencing the same problem

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
