### ISSUE TITLE
[Bug]: Fierce Devil loot table

### ISSUE THREAD

**Issue by pistou** [MelvorIdle/melvoridle.github.io#2288]
### Describe the bug

According to the [Wiki](https://wiki.melvoridle.com/w/Fierce_Devil), Fierce Devil should loot [Amulet of Torture](https://wiki.melvoridle.com/w/Amulet_of_Torture).

For some reason, they loot [Gold Topaze Ring](https://wiki.melvoridle.com/w/Gold_Topaz_Ring) instead.
This is a big issue for farming the Fury of the Elemental Zodiacs.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1822

### Are you using any scripts or extensions?

No

**Comment by CarrotMD** [comment]
What makes you think it's dropping it "instead"? All monsters can drop the gold topaz

**Comment by pistou** [comment]
> What makes you think it's dropping it "instead"? All monsters can drop the gold topaz

The fact that I killed around 10.000 fierce devils and got 9 rings (hence 0.1% drop rate like the amulet's) and 0 amulet.

**Comment by CarrotMD** [comment]
Indeed it seems almost impossible to not get a torture with 10k kills 
![image](https://user-images.githubusercontent.com/95091791/156758303-efbd5ea1-54f6-4444-980b-34744f425509.png)

**Comment by coolrox95** [comment]
I cannot reproduce this, Amulets of Torture are dropping appropriately.
