### ISSUE TITLE
Melee/magic attack styles with Stormsnap bow

### ISSUE THREAD

**Issue by 8992scripts** [MelvorIdle/melvoridle.github.io#229]
Attack speed is 4.0s and the the attack styles are the melee or magic ones even though you have stormsnap equipped, you also gain xp for the melee or magic.

How to reproduce:
Change from an equipment set that has melee or magic to an equipment set with stormsnap while the enemy is loading.

**Comment by MelvorIdle** [comment]
Fixed in the upcoming update.
