### ISSUE TITLE
[Bug]: Slicing Winds and Surge Aurora Rune Usage

### ISSUE THREAD

**Issue by Talious** [MelvorIdle/melvoridle.github.io#2291]
### Describe the bug

When using the surge aurora, the expected behavior is to decrease the attack interval and use runes once per spell cast. The current behavior is that runes are spent when damage is dealt. In the case of Slicing Winds (and likely other multi-hit spells), the Aurora runes are used for every hit of the spell effectively tripling the Aurora cost.

### Reproduction Steps

1. Use slicing winds
2. Activate any Surge aurora
3. Monitor rune usage

### Expected behaviour

When using the surge aurora, the expected behavior is to decrease the attack interval and use runes once per spell cast

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1822

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
