### ISSUE TITLE
[Bug]: Moving sell-ected items between bank tabs in sell mode makes the sell border invisible

### ISSUE THREAD

**Issue by nivomi** [MelvorIdle/melvoridle.github.io#2292]
### Describe the bug

If you select some items in Sell Mode, and then drag them to a different tab, when viewing that different tab, they'll still be selected, but they won't have the "selected for sell mode border". Clicking them in this state will unselect them for sell mode. Clicking them once more will select them and restore the proper border.

Similar to #2028

### Reproduction Steps

1. Go to the bank
2. Toggle Sell Mode
3. Select an item for selling
4. Drag it to another tab
5. Observe that the item is still selected for sell mode (total value, items selected counters don't change)
6. Visit the tab you dragged the item to
7. Observe that the item does not have the sell mode selected border.

### Expected behaviour

The item should retain the sell mode 'selected' border whenever it is selected for Sell Mode.

### Screenshots

![image](https://user-images.githubusercontent.com/651417/156847349-6fb9f2e0-476b-4ce9-a0c0-6a8c9ea9bea3.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1822

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.1.
