### ISSUE TITLE
[Bug]: <problems with nomal eating>

### ISSUE THREAD

**Issue by xedlix** [MelvorIdle/melvoridle.github.io#2297]
### Describe the bug

Regular Eating over the Minibar and the Combat-Menu doesn't work.
Even after changing to other food it doesn't work.
Auto-Eating work properly.
Eat-spamming work also properly.
Even restarting the Game didn't solves the Bug.

Played on a Samsung Fold 3
(Other Acpect Ratio)

### Save Link

https://melvoridle.com/save/Hl8XFDQs

### Screenshots

https://user-images.githubusercontent.com/57345481/156881709-d8d08373-9790-41c0-bcbe-3f38fcaf2755.mp4

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1822

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
