### ISSUE TITLE
Max Skillcape doesn't include Firemaking Skillcape's global xp

### ISSUE THREAD

**Issue by Alrightsc** [MelvorIdle/melvoridle.github.io#230]
**Describe the bug**
With firemaking cape buffed to include a 5% global xp, this works as intended, but doesn't also explicitly check for Max Skillcape equipped in "addXP" function via main.js.

**To Reproduce**
1. Equip firemaking cape
2. Do something, gain xp, should indicate 5% increase
3. Equip max skill cape
4. Do the same step as 2, should notice 5% xp less

**Expected behavior**
Max skillcape should include 5% global xp increase while equipped

**Screenshots**
N/A

**Browser**
Firefox

**Console output**
N/A

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
