### ISSUE TITLE
[Bug]: Issue with Quick Equip Menu Summoning Tablets

### ISSUE THREAD

**Issue by Richard-Cvbs** [MelvorIdle/melvoridle.github.io#2301]
### Describe the bug

When adding more than one summoning tablets to the quick equip menu, equipping a second one (to use a synergy for example) automatically unequipps  the first tablet instead of using the second summoning tablet slot

### Reproduction Steps

1 - add 2 tablets to a skill quick equip menu
2 - go to the skill
3 - click on the quick equip gear
4 - click on a tablet to equip it
5 - click on a different tablet to equip it

### Expected behaviour

to equip both tables using the 2 separate slots

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1829

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
