### ISSUE TITLE
[Bug]: Mobile app failed to load files when offline for an amount of time

### ISSUE THREAD

**Issue by Audiace0809** [MelvorIdle/melvoridle.github.io#2302]
### Describe the bug

After being offline for a while (e.g. maybe for about an hour or more), mobile app would fail to load offline progress and the file all along.

It's either stuck like this: (hasn't fully loaded in, the images are not fully shown), then immediately afterwards the app stops responding.
https://i.imgur.com/e5io24l.png
https://i.imgur.com/xj6wnRp.png

or like this: (stuck not showing offline progress at all, only has the orange connecting icon upper right)
https://i.imgur.com/0XSqqPU.png

After the app stops responding, restart again would show that local save and cloud save are in sync, but offline progress not calculated yet (for example here, both saves are from this time: https://i.imgur.com/1Nlt9mQ.png), if trying to load the save again, same thing as above happens. I had to play the game on steam only, can't really play mobile. The problem persists from before the update and continues to exist now.

### Reproduction Steps

1. Wait offline for a while.
2. Attempt to start the game from mobile app.
3. Stuck.

### Screenshots

https://imgur.com/a/hux5O9t

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1829

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Many fixes for various offline progress issues have been released over the last few days. Please ensure you are running at least v1.0.3 (?1843).

Please open a new issue if the problem persists.
