### ISSUE TITLE
Monkey Mark not levelling up after 2days of crafting 

### ISSUE THREAD

**Issue by blueangel512** [MelvorIdle/melvoridle.github.io#2304]
### Describe the bug

I have made the tablet for Monkey mark and it's not level after 2days of crafting rings, the rng for that would be impossible.

### Screenshots

https://i.imgur.com/QGHzgyx.png

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

103

### Are you using any scripts or extensions?

No

**Comment by Gnomeball** [comment]
RNG is never impossible, nor is it ever guaranteed, it's just highly unlikely / implausible.

**Comment by coolrox95** [comment]
Bad RNG is not a bug.
