### ISSUE TITLE
[Bug]: <title>goblin raid enemy damage reduction bug

### ISSUE THREAD

**Issue by Green444416** [MelvorIdle/melvoridle.github.io#2306]
### Describe the bug

In goblin raid, if you get an item that gives enemy minus damage reduction and it goes into negatives, it rounds up. Ex, -5% dr = 95% dr.

### Reproduction Steps

Dont know how to fix

### Expected behaviour

Dont know how to fix

### Screenshots

I died, but enemy had 95% dr instead of -5%

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1829

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
