### ISSUE TITLE
Equipment load outs missing

### ISSUE THREAD

**Issue by JaketheSig** [MelvorIdle/melvoridle.github.io#2307]
### Describe the bug

Two of my equipment loadouts are missing, with some of the items being deposited in my bank putting my bank over max bank space, while the others seem to be missing completely. I was in the middle of a goblin raid when the game stopped responding (would runecraft a rune then stop, would go to enter a goblin raid but get stuck on “continue raid”). Upon refreshing, my loadouts are missing yet still unavailable I’m the shop, and I’m unable to join any goblin raid. Previous progress on raid is not showing.

### Reproduction Steps

Continue goblin raid, game freeze, refresh browser.

### Expected behaviour

Able to rejoin raid with same progress, able to access all equipment loadouts.

### Save Link

https://melvoridle.com/save/ouqQkJa0

### Screenshots

![F7D5EE4B-8B70-407F-968D-A471ECBB2516](https://user-images.githubusercontent.com/101160313/157160005-71ca9541-224e-4837-968a-be40d9387d24.png)
![A8F5807D-4292-4B93-A0B2-90A7A1DCAAA4](https://user-images.githubusercontent.com/101160313/157160010-a90ac9bf-8bd1-4b92-a46f-6c8e15f3a1fd.png)
![16F24A42-9219-4BCF-AC6C-6EFE4239C5EC](https://user-images.githubusercontent.com/101160313/157160013-09605a4f-57a0-4007-84d7-996a18847ce7.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1834

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
