### ISSUE TITLE
[Bug]: Quick buy modal appears underneath recipe selection modal

### ISSUE THREAD

**Issue by Gnomeball** [MelvorIdle/melvoridle.github.io#2308]
### Describe the bug

When attempting to buy shop items via the "select a recipe" dialogue in Cooking, the shop window appears behind the recipe window.

### Reproduction Steps

1. Open "select a recipe"
2. select any shop item, cream, flour, etc
3. Close the recipe window

### Expected behaviour

Maybe close the recipe window, and then open the shop window? So the two appear to change places.. but this might get awkward if you want to buy multiple items.. 

### Screenshots

![Screenshot_20220308_111222](https://user-images.githubusercontent.com/45293392/157227427-84cb2dcc-a664-440a-9931-85dc1d9555d6.png)
![Screenshot_20220308_111237](https://user-images.githubusercontent.com/45293392/157227479-6fa0001f-3f33-469e-9534-aba226765dd3.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

1829

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
