### ISSUE TITLE
[Bug]: DFS item missing patreon supporter details

### ISSUE THREAD

**Issue by Silverfyree** [MelvorIdle/melvoridle.github.io#2311]
### Describe the bug

DFS no longer showing patreon item details since v0.16.3
All other patreon items and pets have this still.

### Screenshots

![Uploading image.png…]()

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1835

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
