### ISSUE TITLE
[Bug]: Spending XP in herblore can stop you from reaching 100% completion

### ISSUE THREAD

**Issue by gitgurra** [MelvorIdle/melvoridle.github.io#2315]
### Describe the bug

I have spent XP to get straight to Tier 3 Diamond luck potion a while ago. To achieve 100% completion on items I need to make Tier 1 and 2 but I can't see a way for me to get this.

### Reproduction Steps

1. Level up mastery on a herblore that you've never created by spending XP.
2. You now can't create a lvl 1 potion thus stopping you from reaching 100%

### Expected behaviour

Be able to select tier when crafting.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1843

### Are you using any scripts or extensions?

Yes

**Comment by Gnomeball** [comment]
Herblore Potions can solve this

![Screenshot_20220310_125727](https://user-images.githubusercontent.com/45293392/157666538-432c7654-5636-4a11-b41f-81798d5f6651.png)
