### ISSUE TITLE
Offline bug persisting during Herblore 

### ISSUE THREAD

**Issue by Kbowen1998** [MelvorIdle/melvoridle.github.io#2316]
### Describe the bug

Closing your phone without shutting down the app causes Herblore not to progress offline. I'm on a Google pixel XL

### Reproduction Steps

Idle Herblore
Close down phone before shutting down or Home key out of the app

### Expected behaviour

Herblore should continue to progress offline.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1843

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
