### ISSUE TITLE
[Bug]: no exp or drops (offline bug)

### ISSUE THREAD

**Issue by SkilledShot** [MelvorIdle/melvoridle.github.io#2317]
### Describe the bug

Hey,
Spent the night fishing and received a welcome back message on logging on but no exp or items. Have plenty of space in invent. 

Also noticed similar thing happening in combat yesterday (number of slayer monsters killed not registered when offline)

### Reproduction Steps

See above

### Expected behaviour

See above

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

Latest

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
