### ISSUE TITLE
Switching to set without mirror shield mid-fight and missing

### ISSUE THREAD

**Issue by TheBookAjah** [MelvorIdle/melvoridle.github.io#2319]
### Describe the bug

In strange cave, fighting Lots of Eyes - the mirror shield is required for the area. I switched mid-fight to the other armour set. It kept me fighting, but just missing the enemy every time. The enemy could still hit me, though.

### Reproduction Steps

1. Have two armour sets unlocked
2. Go to slayer area 'strange cave' with mirror shield equipped as it has to be.
3. Fight 'Lots of eyes' (and probably other ones, too, although I haven't tried them)
4. In mid-fight, switch over to armour set without mirror shield

### Expected behaviour

I forgot about the mirror shield, but if I had remembered, I would have expected it to stop fighting or not allow me to switch.

### Save Link

https://melvoridle.com/save/tYrIgRwB

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1848

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
