### ISSUE TITLE
[Bug]: Astrology Mastery Bug

### ISSUE THREAD

**Issue by dyohman** [MelvorIdle/melvoridle.github.io#2320]
### Describe the bug

Upon loading on Steam, iOS, or Android, I am unable to open the menu to spend Astrology mastery XP gained. This started to happen 2 days ago on this character. Other characters work fine. 

### Reproduction Steps

1. Load Game
2. Open Astrology Tab
3.  Click "Spend XP" button

### Expected behaviour

When clicking the "Spend XP" button, I am expecting the menu to spend mastery xp to appear. 

### Save Link

https://melvoridle.com/save/4BNmQjNa

### Console output

Connected to PlayFab successfully
Steam Account Link successful
Uncaught TypeError: Cannot read property 'Value' of undefined
Uncaught TypeError: Cannot read property 'Value' of undefined
set force reload to 0
Combat Manager Built...
Golbin Raid Manager Built...
Loading Save Game...
Save Game Loaded...
Game Loaded
QuickShards initialized
Connected to PlayFab successfully
TypeError: undefined is not a function
MICSR: setting up util
MICSR: setting up modifierNames
MICSR: no unknown modifiers detected!
MICSR: no non-existent modifiers detected!
MICSR: setting up Card
MICSR: setting up AgilityCourse
MICSR: setting up CombatData
MICSR: setting up Consumables
MICSR: setting up DataExport
MICSR: Import is waiting for Import
MICSR: setting up Import
MICSR: setting up Loot
MICSR: setting up Plotter
MICSR: setting up Menu
MICSR: Simulator is waiting for SimEnemy
MICSR: Simulator is waiting for SimManager
MICSR: Simulator is waiting for SimPlayer
MICSR: setting up SimEnemy
MICSR: setting up SimManager
MICSR: setting up SimPlayer
MICSR: setting up TabCard
MICSR: main is waiting for App
MICSR: App is waiting for Simulator
DungeonTimerData Key found - Data retrieved
Melvor DungeonTimer: loading...
Melvor DungeonTimer: loaded!
Uncaught ReferenceError: ASTROLOGY is not defined
Melvor Equipment Menu Loaded
Melvor ETA: loading...
Melvor ETA: loaded!
Melvor Auto Loot: Loaded
Melvor Auto Loot Contact: Polfy#6924
MICSR: setting up Import
MICSR: setting up Simulator
MICSR: setting up App
Melvor DungeonTimer: added Timer menu!
Melvor ETA: added settings menu!
Melvor Make-XI: Loading...
Melvor Make-XI: Loaded
MICSR: setting up main
Game Loaded. SEMIUtils ready.
Starting Event Bus
Core injection good
PlayFab Connected: dyohman
Steam Account Link successful
Synchronising with Cloud
Combat Manager Built...
MICSR: Melvor Idle Combat Simulator Reloaded v1.6.4 loaded.
SEMI v1.0.2 Loaded!
Loading Mastery Enhancements
auto-idle-agility enabled at 3/11/2022, 2:07:15 PM
auto-sell enabled at 3/11/2022, 2:07:15 PM
auto-loot enabled at 3/11/2022, 2:07:15 PM
auto-farm-equip enabled at 3/11/2022, 2:07:15 PM
auto-farm enabled at 3/11/2022, 2:07:15 PM
auto-lute enabled at 3/11/2022, 2:07:15 PM
auto-run enabled at 3/11/2022, 2:07:15 PM
drop-chances enabled at 3/11/2022, 2:07:15 PM
Uncaught TypeError: Cannot read property 'Value' of undefined
Uncaught TypeError: Cannot read property 'Value' of undefined
Uncaught TypeError: Cannot read property 'media' of undefined

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1848

### Are you using any scripts or extensions?

Yes

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
