### ISSUE TITLE
[text not lining up]: <skill level columns>

### ISSUE THREAD

**Issue by mmm0003** [MelvorIdle/melvoridle.github.io#2322]
### What text is wrong?

The text of name of the skill in the first column does not line up with the numbers of the skill level in the second column.

### What is the correct spelling or grammar?

The second column needs to be moved down slightly.
![Screenshot_20220311-200157](https://user-images.githubusercontent.com/100392705/157999785-746c4545-b2af-477d-92e8-86494c761cfc.png)

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
