### ISSUE TITLE
[Bug]: Runecrafting won't craft runes

### ISSUE THREAD

**Issue by abcras** [MelvorIdle/melvoridle.github.io#2324]
### Describe the bug

After having melvor open for a while runecrafting stopped producing runes, the progress bar completes one iteration with no result and then stops, you then have to disengage the craft and reengage it to just get the same no result.
After switching to another tab of the skill it beings to work again.

I have no idea why it stopped working, figured I would report it for awareness, before it happened I had done mastery pool stuff switched rune to craft a couple of times.

While I technically had the combat sim added it is an old version that does not even load.

### Reproduction Steps

No idea

### Expected behaviour

The runes should craft

### Save Link

https://melvoridle.com/save/k6jO8hPQ

### Console output

![image](https://user-images.githubusercontent.com/3748122/158016085-8cb787e0-b3ba-47fb-96ea-565031e2008a.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1849

### Are you using any scripts or extensions?

Yes

**Comment by CarrotMD** [comment]
Full bank perhaps? Would be the easiest solution.

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
