### ISSUE TITLE
[Bug]: welcome back screen/save issue

### ISSUE THREAD

**Issue by NemyTR** [MelvorIdle/melvoridle.github.io#2326]
### Describe the bug

Upon closing the game on android, multiple welcome back windows appeared one after another and the save game reverted to the first one, to about one day ago - so I lost about one day of progress.

### Reproduction Steps

Game was running all day, normally I put it only in background and close it only for the night. Was skilling summoning all day, nothing special. Autosave to cloud is enabled (but I regularly have to press it manually, because it's stuck on spinning and not saving, and regularly says cloud save failed). As I tried to close the game yesterday (popup if I really want to leave -> yes), it did not, but a welcome back screen appeared with stuff I did during the day and the save game (which then automatically saved to cloud too) reverted to the state of the popup (when it really should have popped up some hours ago). This happened a couple of times...practically losing yesterdays whole gaming process.

### Expected behaviour

Game should exit normally, and don't overwrite save game with older data

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1849

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
