### ISSUE TITLE
[Bug]: Stuck on “loading offline progress” page updated April 2

### ISSUE THREAD

**Issue by kmbd89** [MelvorIdle/melvoridle.github.io#2327]
### Describe the bug

The game is stuck on the “loading offline progress” page. I was training Firemaking on iOS and left the game idle for a couple of hours. 

Update: I made a second character since the bug never got fixed, and it happened again. This time I was training Smithing on Safari, cloud-saved, closed the game, and left it for a couple of hours. Would be great if a fix could be implemented for this issue as it prevents any further gameplay. I don’t want to keep starting over with a new character because the game isn’t functioning properly.

### Save Link

https://melvoridle.com/save/ijCJkwUy

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [X ] Safari
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1849

### Are you using any scripts or extensions?

N
![MI load issue](https://user-images.githubusercontent.com/101531955/158113041-2499c70a-6039-4c75-887b-ecba8a45f6e7.JPG)
o

**Comment by MelvorIdle** [comment]
Related #2353

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
