### ISSUE TITLE
[Bug]: After upgrading bank spaces missing.

### ISSUE THREAD

**Issue by rderoo** [MelvorIdle/melvoridle.github.io#2329]
### Describe the bug

After the March update I have five fewer bank spaces than before the update.

### Reproduction Steps

I log into my account and see "215/210".

### Expected behaviour

I would expect to see 215/215. Or an announcement stating that bank space was reduced for one reason or another.

### Save Link

https://melvoridle.com/save/VBQXCYlF

### Screenshots

![bank_space_issue](https://user-images.githubusercontent.com/11988401/158240526-b2887dce-4f65-4d03-8c12-474d99e93f9a.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1849

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This was due to loading a premium save into a non-premium game, which removes non-premium gear from your equipment and adds them to your bank.
