### ISSUE TITLE
[Bug]: Sell menu not scrolling properly

### ISSUE THREAD

**Issue by reddog7879** [MelvorIdle/melvoridle.github.io#2330]
### Describe the bug

Sell menu using web browser isn't scrolling all the down while the background screen in the bank tab will fully scroll and only to access the sell items is below the bank screen.  This is occurring using Chrome on Samsung Galaxy S20 FE 5G, if that helps.

### Reproduction Steps

Go to bank tab
Select item to sell
Attempt to scroll down and only see it stop and then see background scroll down instead

### Expected behaviour

Pop up sell window should scroll down to select options for amount to sell and select the sell button or scroll a little further and select close menu button

### Save Link

https://melvoridle.com/save/dmurMYDw

### Screenshots

![image](https://user-images.githubusercontent.com/93557188/158266614-06b57569-53b1-45d8-8dc1-06a80673188b.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1849

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
