### ISSUE TITLE
[Bug]: <zoom on samsung mobile>

### ISSUE THREAD

**Issue by Bvsedog** [MelvorIdle/melvoridle.github.io#2333]
### Describe the bug

When I log in on my galaxy it is super zoomed in on portrait mode to the point where I can't even click on my account in the top right.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1849

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Duplicate of #2290
