### ISSUE TITLE
[Bug]: buying 1 skill glove for the price of 10.

### ISSUE THREAD

**Issue by Ephialltes** [MelvorIdle/melvoridle.github.io#2334]
### Describe the bug

Purchasing 10x mining gloves charges the full 750k (75k each) but only provides one set of gloves.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1849

### Are you using any scripts or extensions?

No

**Comment by Silberdrachi** [comment]
Game provides 1 glove, but 10x the charges on the glove. you never have more than 1 glove of each type, and are instead buying the number of charges from the store.
