### ISSUE TITLE
[Bug]: Poison can be applied to the Into The Mist Boss

### ISSUE THREAD

**Issue by Lurker657** [MelvorIdle/melvoridle.github.io#2335]
### Describe the bug

Using the Scaled Shield poison can be applied to the Into the Mist Bosses despite being "Immune to Player Debuffs"

### Reproduction Steps

1. Make it to the Into the Mist Bosses
2. Have the scaled shield equipped
3. Get hit.

### Expected behaviour

The Into the Mist Bosses will be poisoned.

### Screenshots

![image](https://user-images.githubusercontent.com/101696159/158537283-37246ce8-3aa5-4013-9048-485d290cf5d4.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1849

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Poison is not classed as a "Debuff" in this instance. Debuffs are mainly stat altering affects like slows and whatnot.
