### ISSUE TITLE
[Bug]: magic combat is broken

### ISSUE THREAD

**Issue by Pentodo** [MelvorIdle/melvoridle.github.io#2336]
### Describe the bug

i have the runes and it keeps telling i won't
it's bugged on simple or combination runes usage

### Screenshots

![image](https://user-images.githubusercontent.com/55227326/158661045-99df592d-bea5-4b7c-bc4a-0e179842a53d.png)
my inventory ^

![image](https://user-images.githubusercontent.com/55227326/158661123-b56ca647-e77b-4492-908e-613f7bab58e4.png)
my set ^

![image](https://user-images.githubusercontent.com/55227326/158661570-31ce4fce-1690-4aa3-ab76-c4ddac310bf9.png)
the spell (example, all of them are bugged) ^

![image](https://user-images.githubusercontent.com/55227326/158661698-6a2c660f-54fb-4743-9b7e-867bdfb06409.png)
on combat (zero damage) ^

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1849

### Are you using any scripts or extensions?

No

**Comment by Silberdrachi** [comment]
The ring youre using [Ring of Spirit Power] uses 3 runes per cast, i dont see any in your bank.

**Comment by Pentodo** [comment]
@Silberdrachi oops, you're right :d
but it's a bad design, i HAVE the combination runes, so the message is wrong (another report?)

anyway, thx for the help, now i can fight
