### ISSUE TITLE
[Bug]: Two Crow tablets being used per runecrafting action

### ISSUE THREAD

**Issue by ktrolla** [MelvorIdle/melvoridle.github.io#2337]
### Describe the bug

While runecrafting with Crow and Bear tablets equipped and the synergy active, I am almost always consuming 2 Crow tablets per runecrafting action. Occasionally one Crow tablet is consumed, and occasionally none are consumed. If I unequip the Bear tablets, the amount of Crow tablets consumed per runecrafting action is then 1.

### Reproduction Steps

1. Equip Crow and Bear tablets with synergy active
2. Use Elemental Potion for the synergy effect
3. Perform runecrafting actions and observe the usage of Crow tablets
4. Unequip Bear tablets, perform runecrafting actions and observe the usage of Crow tablets

### Expected behaviour

I expect 1 Crow tablet to be consumed per runecrafting action.

### Save Link

https://melvoridle.com/save/DxyLd1zM

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1849

### Are you using any scripts or extensions?

No

**Comment by NemyTR** [comment]
One is used for the action, one for the synergy (as with all synergies)

**Comment by CarrotMD** [comment]
This part is weird though "almost always consuming 2 Crow tablets per runecrafting action. Occasionally one Crow tablet is consumed, and occasionally none are consumed"

**Comment by MelvorIdle** [comment]
Synergies cause 2 tablets to be used. For some tablets - the specific bonus provided needs to proc for a second charge to be used.
