### ISSUE TITLE
[Bug]: Adventure mode starts with 100 HP

### ISSUE THREAD

**Issue by Sandstroem** [MelvorIdle/melvoridle.github.io#2338]
### Describe the bug

When you start with a new adventure character, you start with 100 HP and then first have to either eat to heal up or afk to regen those HP. I am pretty sure that this has not always been the case. My guess would be that it uses normal mode HP to start with.

### Reproduction Steps

1. Create new adventure account
2. Look at current HP

### Expected behaviour

HP should start at 1000, not 100

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1849

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
