### ISSUE TITLE
[Bug]: flecthing, cant scroll through logs s21

### ISSUE THREAD

**Issue by Tonkinwill** [MelvorIdle/melvoridle.github.io#2339]
### Describe the bug

Can't scroll up to access all my logs when flecthing arrow shafts on samsung s21 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

1341

### Are you using any scripts or extensions?

No

**Comment by Tonkinwill** [comment]
Game subversion is 1849

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
