### ISSUE TITLE
Earth Golem "Boulder" attack always hits but text says it's avoidable

### ISSUE THREAD

**Issue by levgre** [MelvorIdle/melvoridle.github.io#234]
**Describe the bug**
Earth Golem "Boulder" attack always hits but text says it's avoidable

**To Reproduce**
Fight Earth Golem in Earth Dungeon

**Browser**
Chrome Version 81.0.4044.138 

**Console output**
Not required to backup
save.js?291:48 Loading Save Game...
save.js?291:209 Save Game Loaded...
save.js?291:48 Loading Save Game...
save.js?291:209 Save Game Loaded...
smithing2.js?286:191 Loading Smithing...
mastery.js?284:183 Updating Masteries
mastery.js?284:23 Loading Masteries...
main.js?314:1259 Game Loaded
oneui.core.min.js?205:6 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ oneui.core.min.js?205:6
cloud.js?288:81 Melvor Cloud Connection: Failed
main.js:4259 Melvor Combat Sim v0.7.0 Loaded
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by MelvorIdle** [comment]
Hotfixed
