### ISSUE TITLE
[Bug]: <title>During Combat No Offline progression

### ISSUE THREAD

**Issue by DGrizzly127** [MelvorIdle/melvoridle.github.io#2340]
### Describe the bug

So first of all, fucking great game, and only gotten better! The offline progression bug seems mostly fixed but today I had my screen go black while in combat and came back and nothing had progressed. I then however closed out of the screen (IOS) and closed my screen. Then came back to the game about 5 mins later and it had been idle if my combat. Hope this is helpful, keep up the great work!

### Reproduction Steps

1. Go to combat 2. Let screen go blank during combat 3. Open phone and no progression 

### Expected behaviour

Should have idled my combat while screen was off. 

### Console output

Apple iPhone 12

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?

### Are you using any scripts or extensions?

No

**Comment by hellooworld15** [comment]
I'm also having a bug when doing offline combat. Also on iOS. When I close Melvor idle before closing my screen, offline combat progression does not continue. However if Melvor Idle is the current app open when I close my screen then the offline progression is fine. Thanks again for the great game from me as well and good luck with the ongoing bugs!

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
