### ISSUE TITLE
[Bug]: Redwood bow recipe for the Centaur summoning tablet has an odd requirement

### ISSUE THREAD

**Issue by pasketi** [MelvorIdle/melvoridle.github.io#2342]
### Describe the bug

The centaur summoning tablet requires quite a few redwood bows. 

### Reproduction Steps

1. Open summoning tab
2. Navigate to Tablets and Familiars
3. Select the Centaur
4. Open recipe dropdown menu and scroll down
5. Observe the redwood bow requirement

### Expected behaviour

Considering it's the highest tier bow, I'd expect the recipe to cost a bit less.

### Screenshots

![image](https://user-images.githubusercontent.com/5417056/159227414-697499c4-3244-482e-8a32-4a60d9951a0d.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1849

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Item quantities are based on the sale value of the item for summoning. This is intended.
