### ISSUE TITLE
[Bug]: Inaccurate Skill Slayer progress % on Combat screen

### ISSUE THREAD

**Issue by NewtAlexander** [MelvorIdle/melvoridle.github.io#2343]
### Describe the bug

On game start when going to Combat screen the calculations for Slayer % is different to all other skills.

Slayer uses % to total from 0
All other skills use % from previous level

After some time, while levelling those skills (not when the XP amount increases, probably when the % value for a skill changes), all the values will correct themselves to the same calculation method for %s from previous level.

### Reproduction Steps

1. Start game
2. Go to Combat screen
3. Values will show different calculations

### Expected behaviour

Values should be calculated the same way on startup, not just after an update to values.

### Save Link

https://melvoridle.com/save/n7LldEhu

### Screenshots

![combatskill](https://user-images.githubusercontent.com/21064616/159230595-126a8012-afb8-45b0-9e4d-8f0fedb5a082.PNG)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1849

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
