### ISSUE TITLE
[Bug]: Ancient Ring of Skills not found after >260K Fishing Attempts

### ISSUE THREAD

**Issue by jwhite6114** [MelvorIdle/melvoridle.github.io#2344]
### Describe the bug

After over 260,000 fishing actions (see screen shot), I still have not found the Ancient Ring of Skills.

Is there a glitch or certain scenario that causes this item to be blocked?

I understand it is random, but at the stated odd of 1/6,722, there is only 0.0000000000000016% chance of _not_ having found even one instance of this ring, by now.

FWIW, I have found 10 instances of the Ancient Ring of Mastery (though none of either in the past 1 week of fishing).

### Reproduction Steps

1. Fish
2. Fish some more
3. Fish even more (up to 260,000 times or more)
4. Observe you have found NO Ancient Ring of Skills have been found

### Expected behaviour

1. Fish
2. Fish some more (up to 100,000 times, by which point the odds of finding at least one Ancient Ring of Skills is 99.99997%)
3. Observe you have found at least one Ancient Ring of Skills

### Save Link

https://melvoridle.com/save/HkEL8W6d

### Screenshots

![Melvor Idle - Fishing Attempts - 2022-03-21](https://user-images.githubusercontent.com/102044275/159310638-faf5cf55-5a1f-401d-bba3-8609c3fa8249.png)
![Melvor Idle - Ancient Ring of Skills - Missing](https://user-images.githubusercontent.com/102044275/159310654-36bdf3fe-a409-4387-98ef-4b17ebd872b6.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1849

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Bad RNG is not a bug.
