### ISSUE TITLE
[Bug]: Woodcutting cut time rounding error

### ISSUE THREAD

**Issue by BenFlower** [MelvorIdle/melvoridle.github.io#2345]
### Describe the bug

When cutting trees with a dragon axe, the master of nature, and the woodcutting skill cape on the time to cut each tree is 0.05 seconds faster than it should be. Magic tree (without 99 mastery) shows 3.95 seconds cut time instead of the correct 4 seconds, Redwood tree (with 99 mastery) shows 2.75 seconds cut time instead of the correct 2.8. If you turn on the stepping stones agility obstacle, the cut times are correct again. If you remove the skill cape, the cut times are correct again. 

### Reproduction Steps

1. Have dragon Axe, Master of Nature, and Woodcutting Skill cape equipped (if stepping stones agility obstacle is turned on, bug will not be present) 
2. Look at time to cut for all trees, each is 0.05 faster than expected.

### Expected behaviour

Expected cut times to be 0.05 seconds slower with exact setup. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1849

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
