### ISSUE TITLE
[Bug]: Quick-Equip Menu order resets after equipping an item from the same menu

### ISSUE THREAD

**Issue by moffeemoffee** [MelvorIdle/melvoridle.github.io#2347]
### Describe the bug

After rearranging items in the quick-equip menu, equipping one of the items in the menu resets the order.

### Reproduction Steps

1. Open a Non-Combat skill.
2. Open the Quick-Equip menu from the bottom right
3. Drag some of the equips around
4. Select one of the items to equip them
5. Bug is replicated, ordering done in step 3 isn't saved

### Expected behaviour

Order is still kept after equipping an item

### Save Link

https://melvoridle.com/save/jIRWDygG

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1850

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
