### ISSUE TITLE
[Bug]: <title> Game not opening when no WiFi 

### ISSUE THREAD

**Issue by Nightwolv** [MelvorIdle/melvoridle.github.io#2348]
### Describe the bug

Game doesn’t open when no WiFi 

### Reproduction Steps

1. Don’t have WiFi 2. Open the game 3. Doesn’t load

### Expected behaviour

Game opening so i can play 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1850

### Are you using any scripts or extensions?

No

**Comment by briandotcom0** [comment]
This happens on Android too. Can't load the main chart select screen without data. Very annoying that it has the offline tag on the app store and doesn't actually work offline when there's no reason it shouldn't.

**Comment by MelvorIdle** [comment]
We don't set the tags on the App Store, they are automated. No idea why Offline is even a tag, especially when Apple has reviewed the app itself and would know it isn't accurate.
