### ISSUE TITLE
[Bug]: (S) Iron Helmet sorts incorrectly

### ISSUE THREAD

**Issue by F0rF0xSake** [MelvorIdle/melvoridle.github.io#2349]
### Describe the bug

(S) Iron Helmet sorts to between (S) and (G) bronze items rather than its correct place.

### Reproduction Steps

With all iron and bronze items, sort, and (S) Iron Helmet is in the wrong place.

### Expected behaviour

I would expect (S) Iron Helmet to be between non-trimmed iron armour and (S) iron armour.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1850

### Are you using any scripts or extensions?

Yes

**Comment by F0rF0xSake** [comment]
There may be others, but I did just notice that additionally, (S) Adamant Helmet and (S) Adamant Boots are swapped positionally

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
