### ISSUE TITLE
[Bug]: Account Empty password allowed

### ISSUE THREAD

**Issue by whoamiUNIX** [MelvorIdle/melvoridle.github.io#2350]
### Describe the bug

Try to reset password and then change password to nothing. This allow you to create account without password.

### Reproduction Steps

Try to reset password and then change password to nothing. 

### Expected behaviour

There should be some validation to set minimal password.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [X] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1850

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
