### ISSUE TITLE
[Bug]: <title>Cannot progress past tutorial Task -Ranged Preparation 7

### ISSUE THREAD

**Issue by KevinJennings** [MelvorIdle/melvoridle.github.io#2351]
### Describe the bug

After completing tutorial task to craft arrows and normal shortbow, the shortbow does not appear in the Bank for the next step of the tutorial.

### Reproduction Steps

1. Do tutorial
2. Craft normal shortbow (u)
3. Buy bowstring
4. Craft normal shortbow
5. Craft 30 bronze arrows
6. Collect reward
7. Go to Bank
8. Normal shortbow does not show in Bank

### Expected behaviour

After crafting normal shortbow (and receiving rewards for this task) the bow should be available in the Bank for equipping.

### Save Link

https://melvoridle.com/save/4A8VQS81

### Screenshots

![Melvor Idle Tutorial Bug](https://user-images.githubusercontent.com/4312823/159693219-383a87a8-e7a1-4058-b4eb-cb70f83864f3.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1850

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
I have just pushed a hotfix to the game that allows for bowstrings to be purchased in other areas of the tutorial. So if the bow does not display, you will be able to create a new one by purchasing another bowstring from the shop.
