### ISSUE TITLE
[Bug]: Cant craft summoning tablets 

### ISSUE THREAD

**Issue by Dragoma** [MelvorIdle/melvoridle.github.io#2352]
### Describe the bug

Cant craft summoning tablets with perfect food and i dont want to craft normal food when i got 500k of the food i need but its perfect is this a bug or feature hope it gets fixed 

### Reproduction Steps

try to craft summoning tablets with perfect food and u will not be able to 

### Expected behaviour

dont know

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1850

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Next update will allow perfect versions of fish to be used to create the tablets
