### ISSUE TITLE
[Bug]: <title>Stuck loading offline progress

### ISSUE THREAD

**Issue by adampate** [MelvorIdle/melvoridle.github.io#2353]
### Describe the bug

I cannot load my. Bars yet. It is stuck loading offline progress.
I was training woodcutting, fletching, and smithing (alternating). I have the max skill cape and crown of rhylax. This happened several days ago and I thought maybe it’d just resolve itself.
I see it both iOS and Steam. Tried reloading my save file. Happens both locally and cloud.
No scripts.

### Reproduction Steps

Launch the app and try to load my character.

### Expected behaviour

I should be able to play the game like normal.

### Save Link

https://melvoridle.com/save/BYzG0t7E

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

Don’t know

### Are you using any scripts or extensions?

No

**Comment by adampate** [comment]
Game Subversion: 1852

**Comment by adampate** [comment]
Still experiencing this issue. I noticed that I can perform Farming skills, but nothing else appears to be registering. I can’t start combat or other skills. 
I noticed that if I try to select 3 woodcutting trees, it says I cannot select more than than 2. 
im open to suggestions on what else to try.

**Comment by adampate** [comment]
Same issue in Subversion 1875. Still no progress.

**Comment by adampate** [comment]
Creating a new game appears to work. Something seems to have gotten corrupt in the save file?

**Comment by CDSM-a** [comment]
I had pretty much this exact same bug, not working on iOS or desktop but seemed to have now fixed it. When loading into my character it would hang on the offline progression screen and then I couldn't train anything but farming.. I had been training the cooking skill prior. I'm not exactly sure what I did to fix it but I clicked every button on the cooking screen and then spent some mastery XP on cooking skills... it then subsequently started working again

**Comment by adampate** [comment]
> I had pretty much this exact same bug, not working on iOS or desktop but seemed to have now fixed it. When loading into my character it would hang on the offline progression screen and then I couldn't train anything but farming.. I had been training the cooking skill prior. I'm not exactly sure what I did to fix it but I clicked every button on the cooking screen and then spent some mastery XP on cooking skills... it then subsequently started working again


wow! That seemed to fix it. Instead of cooking though, mine was fletching. Apparently something went sideways when I was grinding that skill. Happy to say that I’m now able to progress again.

maybe that month off will give me a new perspective on the game.

thanks!

**Comment by Tomtat0** [comment]
How do you get it to work if you're already 100% in mastery..

All I can do is Farm, Buy from shop, and sell. I cannot do any other action.

**Comment by apreston-dm** [comment]
Can confirm that spending mastery XP in cooking was able to kick me out of the frozen skill state

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
