### ISSUE TITLE
[Bug]: Cancelling "select character" causes infinite loading screen

### ISSUE THREAD

**Issue by JinNada** [MelvorIdle/melvoridle.github.io#2354]
### Describe the bug

With the "show confirmation when attempting to close the game" setting enabled, if you press "select character" to change characters and then press "cancel" instead of "leave", the screen gets stuck in an infinite loading screen without fail.  

Interestingly, the notifications at the bottom of the screen continue to show, implying the game is still going in the background, but I cannot interact with anything.

Cancelling the check does not cause the infinite loading screen when reloading, closing the tab, attempting to change password, or logging out.

Refreshing fixes the issue with no additional problems.

### Reproduction Steps

1. Enable "Show confirmation when attempting to close the game."
2. Press "Select Character"
3. Press "Cancel"

### Console output

[Violation] 'click' handler took XXXXms

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1852

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
