### ISSUE TITLE
[Bug]: Sidebar doesn’t display as mini

### ISSUE THREAD

**Issue by Ektheo** [MelvorIdle/melvoridle.github.io#2357]
### Describe the bug

Even though “Toggle Mini Sidebar Mode” is on, the sidebar doesn’t appear mini.

### Reproduction Steps

1. Turn “Toggle Mini Sidebar Mode” on.

2. Sidebar still appears full size  

### Expected behaviour

Sidebar should appear mini

### Save Link

https://melvoridle.com/save/80uavZE4

### Screenshots

![DF524CDF-239B-47B7-A792-3E9D9C3A28FE](https://user-images.githubusercontent.com/102387464/160196045-691cbe49-d133-4607-8de5-e9d9b72cf5a1.png)
![BEA20308-3DEF-4729-8E81-BD76E8F8B1AF](https://user-images.githubusercontent.com/102387464/160196047-fe3eba5b-3746-49f7-8e43-3a732f41dcc7.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1852

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is a desktop only setting. I will hide this setting on mobile

**Comment by Ektheo** [comment]
Thank you. Love the game and the support given to it.
