### ISSUE TITLE
[Bug]: Computer hibernating leads to no progress

### ISSUE THREAD

**Issue by KeeganE-Hub** [MelvorIdle/melvoridle.github.io#2358]
### Describe the bug

If I hibernate my computer while Melvor is still open in a tab on Chrome, I will make no offline progress. When I turn the computer on again it will still say "Welcome back! You were gone for <time>" accurrately, but there will be no loot or exp gains from that time. Confirmed not just a graphical error, I got no loot or exp from the time.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1852

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
