### ISSUE TITLE
[Completion Issue]: Clue Chasers Insignia

### ISSUE THREAD

**Issue by AllCanadianBrady** [MelvorIdle/melvoridle.github.io#2359]
### Describe the bug

Unable to get 100% completion due to Clue Chasers Insignia requirements.
Once Cave Fish cooking has been maxed out (100% success chance), you are unable to create a Burnt Cave Fish at all, which is a required item to obtain the Clue Chasers Insignia.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1852

### Are you using any scripts or extensions?

No

**Comment by Silberdrachi** [comment]
https://wiki.melvoridle.com/w/Burnt_Cave_Fish

Burnt cave fish no longer comes from cooking (no burnt fish at all from cooking) instead you fight Tentacles and get it as a drop.

**Comment by AllCanadianBrady** [comment]
@Silberdrachi Thank you for the tip.
