### ISSUE TITLE
[Bug] : Crown of Rhaelyx doesn't appear in the Quick equip tab for skills

### ISSUE THREAD

**Issue by fmorel** [MelvorIdle/melvoridle.github.io#2361]
### Describe the bug

The 'quick equip' tab in the side bar usually allows the player to equip any item relevant to the current skill

The Crown of Rhaelyx, despite giving a huge bonus to the 'preserved resources' doesn't appear in the tab.

### Reproduction Steps

1. Go to any non-combat skill
2. Open the sidebar
3. Hover on the quick equip tab

### Expected behaviour

I would expect that the Crown of Rhaelyx, giving a +35% bonus to the 'preserved resources' appear in relevant skills.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1852

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
The quick equip menu was changed to allow users to specify which items they want on it in the last update. To do so, select the item in the bank and click on the item settings in the bank sidebar.

![image](https://user-images.githubusercontent.com/58208131/160549496-159899af-a805-4639-aecb-9feec744d522.png)
