### ISSUE TITLE
[Bug]: Synergy Search for "Goblin" gives no results ("thief" works)

### ISSUE THREAD

**Issue by EgonSpengler** [MelvorIdle/melvoridle.github.io#2363]
### Describe the bug

The Summoning Synergy search box works as expected for most familiars (e.g. "witch" returns all synergies with the witch) but it's not intuitive to find those for the Goblin Thief.

After some minutes of trial and error I discovered that it expects me to search "thief" when "goblin" or even "goblin thief" would be more expected and consistent.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1852

### Are you using any scripts or extensions?

No

**Comment by Silberdrachi** [comment]
https://wiki.melvoridle.com/w/Golbin_Thief

that would be because its Golbin Thief

**Comment by EgonSpengler** [comment]
> https://wiki.melvoridle.com/w/Golbin_Thief
> 
> that would be because its Golbin Thief

Searching "Goblin Thief" also returns no results.  It has to be just "thief" for me.

**Comment by Silberdrachi** [comment]
go"LB"in, the L and B are reversed, like all instances of Golbin in the game. Searching for Goblin will net no results in general

**Comment by Silberdrachi** [comment]
https://wiki.melvoridle.com/w/Easter_Eggs#Golbins

**Comment by MelvorIdle** [comment]
The correct spelling in Melvor Idle is Golbin.

**Comment by EgonSpengler** [comment]
Oh my god I can't believe I didn't even see the difference. Apologies!
