### ISSUE TITLE
[Bug]: Doing slayer tasks and unequipping required item continues to fight enemy but no hit

### ISSUE THREAD

**Issue by gitgurra** [MelvorIdle/melvoridle.github.io#2364]
### Describe the bug

When doing a slayer task that requires a specific item, in my case maximum skill cape, and you unequip mid fight you will continue fighting enemy but all attacks miss causing you to loose food, tablets arrows or runes(but still gaining summoning xp). 

### Reproduction Steps

1. Equip slayer skillcape
2. Find a slayer tasks with requirements like climbing boots or whatever
3. Fight
4. Unequip slayer skillcape
5. All attacks will miss but you will continue to fight

### Expected behaviour

A popup explaining you cannot unequip this item while fighting OR just not being able to unequip OR unequipping resulting you to flee

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1852

### Are you using any scripts or extensions?

Yes

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
