### ISSUE TITLE
[Bug]: Golbin Weapon Resets

### ISSUE THREAD

**Issue by Jhoudy** [MelvorIdle/melvoridle.github.io#2366]
### Describe the bug

Lately, while playing the golbin raid, if an unable to use a spell (with wand or staff equipped) due to lack of runes, the weapon resets to bronze scimitar. I have also experienced this when selecting a new melee weapon e.g. had ancient claw, clicked the tidal, and wound up with bronze scimitar. I’ve had this happen about ten times in the last two days and once a few days ago. HTH

### Reproduction Steps

Uncertain the pattern . I believe with anything equipped in the weapon slot in golbin raid, try to use a spell that you don’t have runes for and see if on unsuccessful attempts it resets.

### Expected behaviour

Weapon slot returns to bronze scimitar

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
