### ISSUE TITLE
[Bug]: <title> Fire Surge incorrectly using Spirit Runes

### ISSUE THREAD

**Issue by Aomalley11** [MelvorIdle/melvoridle.github.io#2367]
### Describe the bug

While using Fire Surge, I continue to get an a error message bc I do not have any Spirit runes in my bank. This spell doesn’t require spirit runes.

### Expected behaviour

The Fire Surge spell should not use any Spirit Runes.

### Screenshots

![F2B87BA5-E46C-4C71-A076-D045546CD53A](https://user-images.githubusercontent.com/102759271/161124966-15ddebc4-975a-498a-bc28-260b75d2ae43.png)
![80809535-28BF-48B2-844D-8C558503E9BB](https://user-images.githubusercontent.com/102759271/161124970-77817c9e-7636-4e19-96d6-b254d24da72b.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1853

### Are you using any scripts or extensions?

No

**Comment by Silberdrachi** [comment]
were you by chance using this ring:
https://wiki.melvoridle.com/w/Ring_of_Spirit_Power
