### ISSUE TITLE
[Bug]: Apple offline combat 

### ISSUE THREAD

**Issue by Kylefire** [MelvorIdle/melvoridle.github.io#2368]
### Describe the bug

I click to idle the game for combat. Which every other skill is fine to do with. But when I reopen the app later on in the day it’s says I’m currently not training and the combat is exactly where I left from. 

### Expected behaviour

I would expect the game to idle the combat also offline. I don’t know if this fault is being dealt with or it doesn’t work on Apple. Since my partners phone is android and combat works after closing the app

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

Yes

### Are you using any scripts or extensions?

No

**Comment by SirFork** [comment]
You need to enable offline combat in the settings before it will work. Make sure that is enabled.
