### ISSUE TITLE
[Bug]: Goblin Raid special attack bug

### ISSUE THREAD

**Issue by SJ-Phoenix** [MelvorIdle/melvoridle.github.io#2369]
### Describe the bug

I am currently doing a Goblin Raid and I got the Ultima Godsword, however I don't have any of the swords special attacks, all I have is Deadly Cut at 100%. The last run I did had the same problem, but I don't remember what weapon or special ability I had, I just remember it didn't match up. (I use OperaGX to play)

### Reproduction Steps

1. use a melee weapon with a special attack
2. pick a new melee weapon with a different special attack

### Expected behaviour

I expected to get all of the special attacks that come with the Ultima Godsword

### Save Link

https://melvoridle.com/save/zwtYV5NS

### Screenshots

![Capture](https://user-images.githubusercontent.com/102793428/161226109-57ce7b46-df63-47fb-88b6-d4307a9a9599.PNG)

### Console output

www.googletagmanager…id=UA-129674422-1:1 
 Failed to load resource: net::ERR_BLOCKED_BY_ADBLOCKER
style.css:1 
 Failed to load resource: the server responded with a status of 404 ()
v652eace1692a40cfa37…439c1639079717194:1 
 Failed to load resource: net::ERR_BLOCKED_BY_ADBLOCKER
v652eace1692a40cfa37…439c1639079717194:1 
 Failed to load resource: net::ERR_BLOCKED_BY_ADBLOCKER
v652eace1692a40cfa37…439c1639079717194:1 
 Failed to load resource: net::ERR_BLOCKED_BY_ADBLOCKER
css:1 
 Failed to load resource: the server responded with a status of 403 ()
cloud.js?1868:67 Connected to PlayFab successfully
2
cloud.js?1868:75 Uncaught TypeError: Cannot read properties of undefined (reading 'Value')
    at cloud.js?1868:75:355
    at XMLHttpRequest.xhr.onloadend (PlayFabClientApi.js:101:25)
save.js?1868:34 Copied to clipboard successfully.
save.js?1868:71 set force reload to 0
combatManager.js?1868:1 Combat Manager Built...
raidManager.js?1868:1 Golbin Raid Manager Built...
save.js?1868:15 Loading Save Game...
save.js?1868:15 Save Game Loaded...
main.js?1868:6 Game Loaded
cloud.js?1868:67 Connected to PlayFab successfully
cloud.js?1868:11 Synchronising with Cloud
v652eace1692a40cfa37…439c1639079717194:1 
 Failed to load resource: net::ERR_BLOCKED_BY_ADBLOCKER
v652eace1692a40cfa37…439c1639079717194:1 
 Failed to load resource: net::ERR_BLOCKED_BY_ADBLOCKER
cloud.js?1868:68 PlayFab Connected: SjccGamer
css:1 
 Failed to load resource: the server responded with a status of 403 ()
2
cloud.js?1868:75 Uncaught TypeError: Cannot read properties of undefined (reading 'Value')
    at cloud.js?1868:75:355
    at XMLHttpRequest.xhr.onloadend (PlayFabClientApi.js:101:25)
style.css:1 
 Failed to load resource: the server responded with a status of 404 ()
css:1 
 Failed to load resource: the server responded with a status of 403 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bf….map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1849

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is due to you selecting an (ALT) weapon which gives you a random special attack.
