### ISSUE TITLE
Bank Bug that destroys locked items

### ISSUE THREAD

**Issue by TimStroodle** [MelvorIdle/melvoridle.github.io#237]
This is bug is part of the bank glitch where the window for an item will stay up if you consume it. If you click on the consume option (be it sell or bury bones), it'll consume the next item in the list regardless of its locked status or item type.
Issue that occurred for me
  Clicked on Magic Bones
  Clicked Bury All
  The window didn't disappear from the Magic Bones
  Clicked Bury Bones again and it consumed my Gilded Dragonshield despite it being locked
Its only reproducible as often as the original glitch is where the item window doesn't disappear.

**Comment by MelvorIdle** [comment]
This is _hopefully_ fixed in the upcoming update.
