### ISSUE TITLE
[Bug]: offline progress error

### ISSUE THREAD

**Issue by kfbest** [MelvorIdle/melvoridle.github.io#2371]
### Describe the bug

An error occured while processing ticks offline:
Active Skill: SUMMONING
Error Name: ReferenceError
Error Message: Can't find variable: gamemode
Stack Trace:
notifySkillMastery@https://ios.melvoridle.com/assets/js/game/main.js?1868:427:405
addMasteryXP@https://ios.melvoridle.com/assets/js/game/mastery2.js?1868:72:286
addMasteryXP@https://ios.melvoridle.com/assets/js/built/skill.js?1868:36:46
addCommonRewards@https://ios.melvoridle.com/assets/js/built/skill.js?1868:34:122
actionRewards@https://ios.melvoridle.com/assets/js/built/summoning.js?1868:64:284
addActionRewards@https://ios.melvoridle.com/assets/js/built/skill.js?1868:32:38
action@https://ios.melvoridle.com/assets/js/built/skill.js?1868:58:59
action@[native code]
tick@https://ios.melvoridle.com/assets/js/built/combatManager.js?1868:166:95
tick@https://ios.melvoridle.com/assets/js/built/skill.js?1868:18:29
tick@https://ios.melvoridle.com/assets/js/built/game.js?1868:36:672
runTicks@https://ios.melvoridle.com/assets/js/built/game.js?1868:33:100
@https://ios.melvoridle.com/assets/js/built/game.js?1868:76:755
Current Equipment:
Helmet: Necromancer_Hat
Boots: Necromancer_Boots
Weapon: Natures_Wrath_Staff
Amulet: Clue_Chasers_Insignia
Ring: Ancient_Ring_Of_Mastery
Cape: Summoning_Skillcape

Skill Information:
Is Active: true

Selected Recipe ID: 1
Selected Alt Recipes (Mastery ID | altID):
0: 7
2: 15
3: 7
4: 5
5: 15
6: 4
7: 10
9: 12
10: 3
13: 1
16: 10
17: 2
8: 6
18: 7

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1868

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Confirmed hotfixed a few weeks ago
