### ISSUE TITLE
[Bug]: Error Calculating offline progress Astrology

### ISSUE THREAD

**Issue by Sully-5** [MelvorIdle/melvoridle.github.io#2372]
### Describe the bug

Other information is I was exploring Deedree and completed both 99 Mastery in that and it was my final Constellation to 100% mastery in Astrology. Console log down below

### Reproduction Steps

Not sure

### Expected behaviour

Calculate offline progress

### Console output

An error occured while processing ticks offline:
Active Skill: ASTROLOGY
Error Name: ReferenceError
Error Message: Can't find variable: gamemode
Stack Trace:
notifySkillMastery@https://ios.melvoridle.com/assets/js/game/main.js?1868:427:405
addMasteryXP@https://ios.melvoridle.com/assets/js/game/mastery2.js?1868:72:286
addMasteryXP@https://ios.melvoridle.com/assets/js/built/skill.js?1868:36:46
addCommonRewards@https://ios.melvoridle.com/assets/js/built/skill.js?1868:34:122
actionRewards@https://ios.melvoridle.com/assets/js/built/astrology.js?1868:28:22
addActionRewards@https://ios.melvoridle.com/assets/js/built/skill.js?1868:32:38
action@https://ios.melvoridle.com/assets/js/built/skill.js?1868:29:68
action@[native code]
tick@https://ios.melvoridle.com/assets/js/built/combatManager.js?1868:166:95
tick@https://ios.melvoridle.com/assets/js/built/skill.js?1868:18:29
tick@https://ios.melvoridle.com/assets/js/built/game.js?1868:36:884
runTicks@https://ios.melvoridle.com/assets/js/built/game.js?1868:33:100
@https://ios.melvoridle.com/assets/js/built/game.js?1868:76:755
Current Equipment:
Helmet: Crown_of_Rhaelyx
Weapon: Staff_of_Earth
Ring: Gold_Topaz_Ring
Gloves: Barbarian_Gloves
Cape: Astrology_Skillcape

Skill Information:
Is Active: true

Active Constellation: 0
Explored Constellation: Unset

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1868

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Confirmed hotfixed a few weeks ago
