### ISSUE TITLE
[Spelling/Grammar]: Skill unlocks incorrectly listed as Mastery unlocks

### ISSUE THREAD

**Issue by Gnomeball** [MelvorIdle/melvoridle.github.io#2374]
### What text is wrong?

The Skills unlocks panel lists things as Mastery Unlocks

![image](https://user-images.githubusercontent.com/45293392/161359751-aece474c-f248-463d-882b-f6760c91ec62.png)

### What is the correct spelling or grammar?

"SKILL UNLOCKS"

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
