### ISSUE TITLE
[Bug]: Gold Diamond Ring, Prayer Scroll, and Protect Item

### ISSUE THREAD

**Issue by ThacZer0** [MelvorIdle/melvoridle.github.io#2377]
### Describe the bug

The gold diamond ring says that the effect is:
![image](https://user-images.githubusercontent.com/74617064/161411929-a6ba6435-eb4d-48a5-8c71-d33e87b9cacd.png)

"Protect Item Prayer" costs 0

But it doesn't.

Second bug, the item: 
![image](https://user-images.githubusercontent.com/74617064/161411977-7c8c11cd-7037-4ad6-ae76-2e7c1dad2f88.png)

Should allow me to cast that same prayer for 0 due to -1 prayer points.

But it doesn't.

edit: Additionally Prayer Protect Item currently taking 3 prayer points, but lists as only 2pts.

### Reproduction Steps

1. Put on the item: "Gold Diamond Ring"
2. Equip the item: "Prayer Scroll"
3. Have at least 5 prayer points.
4. Go into combat - it doesn't matter where.
5. Activate the prayer "Protect Item Prayer" which currently costs 2 prayer points, but should be 0 because you are wearing the "Gold Diamond Ring".
6. When mob tries to hit you - should still have 5 prayer points (or however many you began with), but it takes 2** (edit: it is actually taking 3) prayer points and you have 3 (or 2 less than whatever you started with) and no "Prayer Scrolls" were taken.

### Expected behaviour

See above

### Screenshots

Pasted in messages

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

No clue where that is on the steam version

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
I have tested and can confirm everything is working as intended.

The Gold Diamond Ring is working for me. It reduces the cost of the protect item prayer to 0. Of course if I have a 2nd prayer active at the same time then that 2nd prayer will reduce my prayer points.

I also tested with both the ring and scrolls equipped - protect item still costs 0.

Prayer costs can never go below 1 unless the item specifically mentions that it will be free (Like the hold diamond ring).
