### ISSUE TITLE
[Bug]: golbin raid shop options disappearing

### ISSUE THREAD

**Issue by aloiivWizard** [MelvorIdle/melvoridle.github.io#2378]
### Describe the bug

repeatable purchase options have disappeared. 

### Reproduction Steps

purchasing a repeatable option on any character on my account causes the option to disappear. 

### Expected behaviour

after purchasing a 5% ammo upgrade, expected the option to remain to buy 10%. 

### Save Link

https://melvoridle.com/save/3YqcOiTM

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by Zirbelesque** [comment]
This also affects me on both mobile (Android) and Chrome

**Comment by kyldvs** [comment]
I'm running into this issue as well, it makes progressing in Golbin raid very unsatisfying since I can't use my coins effectively

Hope to see it fixed soon :)

**Comment by MelvorIdle** [comment]
I can confirm a fix is being released this week with the Save Slot UI update :)

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
