### ISSUE TITLE
[Bug]: Volcanic Cave Completion

### ISSUE THREAD

**Issue by atinyjoystick** [MelvorIdle/melvoridle.github.io#2379]
### Describe the bug

Does not keep track of completion count/does not count toward infernal stronghold if you don’t have 75 slayer requirement

### Expected behaviour

To count to infernal stronghold regardless if I have level or not

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
I have tested and can confirm this is working as intended.

The visual number does not count down dynamically.

The save provided only has 99 Volcanic Cave completions. Performing 1 more clear unlocks the dungeon as intended. (You can check accurate completion count by looking at how many times you have killed the Dungeon Boss).
