### ISSUE TITLE
[Bug]: Perfect Sharks not going to bank after cooking

### ISSUE THREAD

**Issue by Revengeanc3** [MelvorIdle/melvoridle.github.io#2382]
### Describe the bug

When I cook sharks it consumes them but doesn't add the perfect cooked sharks to the bank. When disabling perfect cooks it works fine. With perfect cooks enabled I get nothing. I'm stuck at 1213 perfect sharks. Hardcore Adventure Speedrun.

### Reproduction Steps

1. Go to Cooking Tab
2. Cook Sharks
3. Bank and bottom popup will show same number in bank

### Expected behaviour

Perfect sharks go to bank after cooking instead of disappearing.

### Save Link

https://melvoridle.com/save/LGd6hfgn

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by Silberdrachi** [comment]
Check to see if you have auto-equip enabled, and if you have sharks equpped in the combat screen
