### ISSUE TITLE
[Bug]: Item Alchemy is not affected by double item % bonus displayed in UI

### ISSUE THREAD

**Issue by robciog** [MelvorIdle/melvoridle.github.io#2383]
### Describe the bug

I have 7% chance for double items because of Ring of Welth.
When using it with Item Alchemy III no sales are getting doubled.

### Reproduction Steps

1. Equip Ring of Wealth (or other item granting chance to double items)
2. Go to Alt. Magic
3. Use Item Alchemy III multiple times 

### Expected behaviour

UI is displaying 7% chance to double items. This should result in around 7/100 casts to be double the value.

### Screenshots

![image](https://user-images.githubusercontent.com/6477367/162284452-2f9364a3-0b74-4950-baf0-99f9aa71f2d4.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

Yes

**Comment by MelvorIdle** [comment]
The doubling is "Chance to double **Items**". GP is not an item so it is therefore not affected by Item Alchemy.

I will adjust the UI to not display double chance during Item Alchemy to avoid confusion.

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
