### ISSUE TITLE
[Bug]: Woodcutting Progress Bar Doesn't Work

### ISSUE THREAD

**Issue by CMurphy3639** [MelvorIdle/melvoridle.github.io#2384]
### Describe the bug

The progress bar works normally for chopping normal and oak trees but for willow, teak, and maple the bar starts filled and doesn't move but the wood chopping still occurs.  Seems purely visual.

### Save Link

https://melvoridle.com/save/OXrv66CG

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by Silberdrachi** [comment]
![image](https://user-images.githubusercontent.com/76179203/162308843-c2b9092e-82c5-4ab7-9893-1d621a1cee9e.png)
Check the render progress bar option and see if you disabled it

**Comment by MelvorIdle** [comment]
Next update will adjust the wording on the setting as per #2385
