### ISSUE TITLE
[Spelling/Grammar]: Render *combat* progress bars is misleading

### ISSUE THREAD

**Issue by abcras** [MelvorIdle/melvoridle.github.io#2385]
### What text is wrong?

![image](https://user-images.githubusercontent.com/3748122/162397779-26ed3f93-9488-4b78-91e1-343fb2387101.png)

It says "Render combat progress bars" but it governs all progress bars in the game

### What is the correct spelling or grammar?

"Render progress bars"

or actually separate the setting into "Render combat progress bars" & "Render non-combat progress bars".

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
