### ISSUE TITLE
[Bug]: Minor visual - mastery level changes when XP spent

### ISSUE THREAD

**Issue by ammesonb** [MelvorIdle/melvoridle.github.io#2386]
### Describe the bug

Specifically found this in runecrafting - if I select my level 99 fire rune, then spend XP on a different rune, the fire rune level is shown as the other temporarily.
No permanent alteration or other issue, just a visual glitch.
Tried the same steps in fishing, did not see the bug. So this is not a global issue, but don't have the XP to try this out across any other skills right now, unfortunately.

### Reproduction Steps

1. Go to rune crafting
2. Select a rune
3. Open the "Spend XP" screen
4. Upgrade a level for a different rune
5. The mastery level of the currently-selected rune has now changed

### Expected behaviour

The fire rune's mastery level should not change.

### Save Link
https://melvoridle.com/save/EV0CTIpU

### Screenshots

Fire rune is level 99, as you can see
![image](https://user-images.githubusercontent.com/2522710/162485444-62027fc3-6fc3-4def-bf17-67bc654002d0.png)

When I upgrade the level of the chaos rune, the fire rune mastery is now shown as 59.
![image](https://user-images.githubusercontent.com/2522710/162485558-b8efad6e-31b0-4103-bae1-6a2d1b9c194a.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.1.
