### ISSUE TITLE
[Bug]: Crafting Potion sell cost is 1GP at all levels

### ISSUE THREAD

**Issue by NototoHoshi** [MelvorIdle/melvoridle.github.io#2389]
### Describe the bug

All Crafting Potions are worth only 1GP (no matter what level), which seems kinda weird. All other potion price seems to be based from the mats used (potions requiring higher tier of herbs are generally worth more, secondary ingredients also increase price of potions like regeneration or diamond luck potions). Crafting Potion is the only one with this 1GP baseline.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.1.
