### ISSUE TITLE
Cannot change username

### ISSUE THREAD

**Issue by featurecat** [MelvorIdle/melvoridle.github.io#239]
**Describe the bug**
You can't open the modal-account-change anymore because somehow the modal-account-change id got corrupted. Here's what it looks like now:
```
<div class="modal" id="modal-accou

	<!-- CHANGE USERNAME MODAL -->
	<div class=" modal"="" tabindex="-1" role="dialog" aria-labelledby="modal-block-normal" aria-hidden="true" style="display: none;">
```

**To Reproduce**
1. Go to Change Character Name
2. Nothing happens

**Comment by MelvorIdle** [comment]
Good spot. This has been hotfixed. Thanks!
