### ISSUE TITLE
[Spelling/Grammar]: Beginning of the End - Storyline - Part 3 of 3.

### ISSUE THREAD

**Issue by tomkrall** [MelvorIdle/melvoridle.github.io#2391]
### What text is wrong?

The herald... **a** least a man claiming to be him... was the same man that gave me my power.

### What is the correct spelling or grammar?

The herald... **at** least a man claiming to be him... was the same man that gave me my power.

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
