### ISSUE TITLE
[Bug]: Magic on Completion Log Progress Bar Incorrect

### ISSUE THREAD

**Issue by Scootronic** [MelvorIdle/melvoridle.github.io#2393]
### Describe the bug

Looks like the progress bar on the "Completion Log"/"Skills" tab is twice has a maximum value of twice what it should be. This could be due to there being the combat magic skill and the alt magic skill. It might be adding together the max value twice but only taking the current actual magic value.

![image](https://user-images.githubusercontent.com/39348098/162776503-a0d22772-14e7-482d-a9bc-a238830b34eb.png)

### Reproduction Steps

1. Go to Completion Log
2. Go to Skills tab
3. Look at the Magic value visual progress bar, the percentage of it's completion is about twice what the numbers represent.

### Expected behaviour

The progress bar's visual representation should be equivalent to the progress numbers. For example 99/99 should be 100 percentage on the visual bar.

### Screenshots

![image](https://user-images.githubusercontent.com/39348098/162778514-d50693e1-859c-4905-94f6-ed64c9b5f64b.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

1875

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
