### ISSUE TITLE
[Bug]: First loot item stays in place when wearing Bone Necklace

### ISSUE THREAD

**Issue by xaintly** [MelvorIdle/melvoridle.github.io#2395]
### Describe the bug

When wearing the Bone Necklace obtained from the Undead Graveyard / Standard Chest, bones are automatically collected and buried.  The first loot item received when fighting will occupy the top-left position in the loot box and will not be pushed out by new loot items.  New loot will appear in the 2nd-to-left spot in the top row, pushing out the oldest loot item if there are more than 100 loot items.

### Reproduction Steps

1. Wear the Bone Necklace
2. Clear the loot box (Loot All)
3. Fight a monster that drops loot until a loot item is received
4. Switch to a different monster that drops loot
5. The second monster's loot should start appearing in the 2nd position of the loot box

This is most obvious with auto-slayer running, one loot item remains set in place while everything else rotates through the loot box.

### Expected behaviour

When wearing the bone necklace, all loot items should rotate through the loot box, with items received earliest being pushed out first when the box is full.

### Save Link

https://melvoridle.com/save/IZgl8dOE

### Screenshots

![image](https://user-images.githubusercontent.com/11651791/163014648-3cde3c02-9895-4c1e-952c-7a95a859cbd7.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
