### ISSUE TITLE
[Bug]: Game wont Load

### ISSUE THREAD

**Issue by PandaN4P** [MelvorIdle/melvoridle.github.io#2396]
### Describe the bug

I get "An error has occured loading the game:
If you are on Android, please clear your app cashe in hopes to remove this error.
Cannot read property 'btnClass' of undefined
TypeError: Cannot read property 'btnClass' of undefined at createCharacterSelectionbox [(https://steam.melvoridle.com/assets/js/game/main.js?1875:199:67)](https://steamcommunity.com/linkfilter/?url=http://(https://steam.melvoridle.com/assets/js/game/main.js?1875:199:67)) at processLocalCharacters [(https://steam.melvoridle.com/assets/js/game/main.js?1875:249:459)](https://steamcommunity.com/linkfilter/?url=http://(https://steam.melvoridle.com/assets/js/game/main.js?1875:249:459)) at loadCharacterSelection
[(https://steam.melvoridle.com/assets/js/game/main.js?1875:194:561)](https://steamcommunity.com/linkfilter/?url=http://(https://steam.melvoridle.com/assets/js/game/main.js?1875:194:561)) at onloadEvent [(https://steam.melvoridle.com/assets/js/game/main.js?1875:74:43)](https://steamcommunity.com/linkfilter/?url=http://(https://steam.melvoridle.com/assets/js/game/main.js?1875:74:43)) at [https://steam.melvoridle.com/assets/js/game/main.js?1875:79:266"](https://steamcommunity.com/linkfilter/?url=https://steam.melvoridle.com/assets/js/game/main.js?1875:79:266%22)

And it wont let me past this screen. Im on Steam (obviously) and have no clue what to do. This is the whole error message minus the quotation marks

### Reproduction Steps

N/A

### Expected behaviour

Load to Character selection Screen

### Screenshots

![image](https://user-images.githubusercontent.com/78630986/163049109-76cded4c-80d7-4f8d-a6ee-ce8641fe8afc.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
