### ISSUE TITLE
[Bug]: <title>Buy limit of 88 reached.

### ISSUE THREAD

**Issue by TylerMRiley** [MelvorIdle/melvoridle.github.io#2397]
### Describe the bug

On my Hardcore character (lv 99) I am unable to buy more bank space. The option is greyed out and is showing the text "Buy limit of 88 reached." As I said, I am 99 combat.

### Expected behaviour

I assume the limit of 88 is combat limitations of buying more banks space. I assumed once I leveled up past 99 I would be able to buy more bank space as I have done multiple times on other characters.

### Save Link

https://melvoridle.com/save/0nNINSOh

### Screenshots

![melvorIssue](https://user-images.githubusercontent.com/16763642/163074188-768795b6-5d36-4db5-99f4-9bd0fa6b998e.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by Silberdrachi** [comment]
![image](https://user-images.githubusercontent.com/76179203/163075025-2662535e-a47f-4486-8c6e-2a64524bb410.png)
this is intended based on game type selection. image is from the new character creation menu

**Comment by TylerMRiley** [comment]
Oh no! Sorry, clearly this is just a me not paying attention to the rules of the game issue.
