### ISSUE TITLE
[Bug]: Lost character between mobile to desktop saves

### ISSUE THREAD

**Issue by astidolph** [MelvorIdle/melvoridle.github.io#2398]
### Describe the bug

I usually play exclusively on mobile, but decided to create a hardcore adventure speedrun character on the desktop web app, when I made a cloud save I noticed that my standard mode main character has disappeared. 

Is this retrievable it's a lot of progress lost if not

### Reproduction Steps

1. Play on mobile 
2. Go go desktop web app, create a hard core speedrun character
3. Make a cloud save 
4. Standard mode character deleted?

I have other characters already saved and those were not affected, only my standard mode disappeared, I did not open my standard more character throughout the process.

### Expected behaviour

Self explanatory 

### Save Link

015832179980

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

1875

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is an unfortunate event of the existing save slot system. An update is being released next week to solve this.

Read more: https://store.steampowered.com/news/app/1267910/view/3173358927557497208
