### ISSUE TITLE
[Bug]: offline progress error in herblore

### ISSUE THREAD

**Issue by RansomTime** [MelvorIdle/melvoridle.github.io#2399]
### Describe the bug

In April fool's hardcore adventure speedrun event

An error occured while processing ticks offline:
Active Skill: HERBLORE
Error Name: TypeError
Error Message: Cannot read properties of undefined (reading 'hasAnimation')
Stack Trace:
TypeError: Cannot read properties of undefined (reading 'hasAnimation')
    at getItemMedia (https://android.melvoridle.com/adfree/assets/js/game/main.js?1875:285:58)
    at Game.createOfflineModal (https://android.melvoridle.com/adfree/assets/js/built/game.js?1875:101:209)
    at https://android.melvoridle.com/adfree/assets/js/built/game.js?1875:76:812
Current Equipment:
Helmet: Crown_of_Rhaelyx
Weapon: Bobs_Rake
Amulet: Amulet_of_Fishing
Ring: Ancient_Ring_Of_Skills
Gloves: Smithing_Gloves
Cape: Firemaking_Skillcape
Summon1: Summoning_Familiar_Ent

Skill Information:
Is Active: true

Selected Recipe ID: 14

### Reproduction Steps

I can't reproduce this. It's only happened once

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Hotfixed a few weeks ago. Closing
