### ISSUE TITLE
[Bug]: Steam achievements for standard mode unlock during hardcore mode.

### ISSUE THREAD

**Issue by OrpheusSummanus** [MelvorIdle/melvoridle.github.io#2400]
### Describe the bug

Upon closing the game and relaunching it the achievements for getting 99 in a skill and clearing the dungeons unlock for Standard Mode even though I only have a Hardcore Mode character.

### Reproduction Steps

1. Have a hardcore mode character with 99s and some dungeon clears
2. Close Melvor Idle on Steam
3. Open Melvor Idle on Steam

### Expected behaviour

Expected behaviour is that the standard mode achievements stay locked until these are unlocked using a standard mode character.

### Save Link

https://melvoridle.com/save/npxcEjdJ

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by LillieSatou** [comment]
This would be a bug if you earned the hardcore achievements while on a non-HC character. Not a bug, enjoy the free unlocks :)

**Comment by MelvorIdle** [comment]
This is intended. The only change required is adjusting the wording on the steam achievements themselves.
