### ISSUE TITLE
[Bug]: <title> Missing seeds when farming

### ISSUE THREAD

**Issue by CapitaScott** [MelvorIdle/melvoridle.github.io#2402]
### Describe the bug

When farming on ISO if you plant seeds then leave the app you get a notification to say when they’re done. But when you click this notification it directs you to the game then the farming page but the seeds are gone, there’s no new items and you’ve wasted 80+ mins minimum farming nothing. 

### Reproduction Steps

1) plant seeds
2) leave app
3) wait for the notification on ios and press it
4) now shows seeds missing, nothing planted and nothing new in bank

### Expected behaviour

Plant the seeds, get a notification, then when pressed it takes you to the farming page with you seeds showing ready to harvest and not just missing.

### Save Link

https://melvoridle.com/save/vO22tCqT

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
