### ISSUE TITLE
[Bug]: (Minor UI) Wrong quantity displayed on bulk item purchases in Shop

### ISSUE THREAD

**Issue by TerraSleet** [MelvorIdle/melvoridle.github.io#2403]
### Describe the bug

When purchasing items in the shop using the "Buy x" button set higher than 1, the wrong quantity displays on the shop UI for items. In the attached screenshot all items appear as "5x Item" when "Buy x" is set to 100. This bug also appears when quick buying items through left clicking purchasable items in other UIs, such as Flour when cooking Bread. This has no noticeable effect on gameplay, bulk purchasing still works fine.

It's worth mentioning that the bug this occurred on is a Hardcore character that has purchased 83 Bank upgrades, making the current buy limit on bank slots 5. Previously this bug was occurring past 15 before I bought 10 more bank slots. The bank slot upgrade is the first item in the shop. The quantity may be incorrectly applying the bank slot's current buy limit (5 in this case) to all items when displaying.

### Reproduction Steps

1. Import attached save
2. Open the Shop menu
3. Navigate to an item that can be purchased in bulk, such as Flour or Skilling gloves
4. Set the buy quantity to higher than 5 using the "Buy x" button in the top right of interface

### Expected behaviour

The number next to the item should display the highest number possible to purchase with your current GP and buy limits, up to the quantity selected using "Buy x".

### Save Link

https://melvoridle.com/save/jwLSBOFV

### Screenshots

![image](https://user-images.githubusercontent.com/8026531/163678403-ff550633-1890-451e-a92f-b5da2783e0a9.png)

### Console output

N/A

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by wzurborg** [comment]
Same here with a hardcore character. It shows 28 for all items when selecting 100 or 1000. When I click on "Buy x100" it correctly buys 100, so it's just a display problem.

![grafik](https://user-images.githubusercontent.com/1320950/166674748-cdf0eaad-27d7-46b5-b721-f11f8baa20d5.png)
