### ISSUE TITLE
Rendering error on iOS

### ISSUE THREAD

**Issue by gmallory3** [MelvorIdle/melvoridle.github.io#2404]
### Describe the bug

Hey there,

Got the following error when opening my saved game. I _think_ it was from opening a local save, not a cloud save.

The popup window additionally suggested I delete the app cache if I was on android. 

iOS: 15.4.1 (19E258)
Model name/ number: iPhone 13 Pro/ MLTW3LL/A
App version: v1.0.3 (?1875)

An error occurred while rendering:
Active Skill: THIEVING
Error Name: ReferenceError
Error Message: Can't find variable: Toastify
Stack Trace:
gpNotify@https://ios.melvoridle.com/assets/js/game/main.js?1875:86:9
@https://ios.melvoridle.com/assets/js/built/utils.js?1875:66:141
forEach@[native code]
notify@https://ios.melvoridle.com/assets/js/built/utils.js?1875:66:28
render@https://ios.melvoridle.com/assets/js/built/baseManager.js?1875:13:95
render@https://ios.melvoridle.com/assets/js/built/combatManager.js?1875:31:44
render@https://ios.melvoridle.com/assets/js/built/game.js?1875:39:24
loop@https://ios.melvoridle.com/assets/js/built/game.js?1875:54:41
loop@[native code]
Current Equipment:
Helmet: Golbin_Mask
Platebody: Mithril_Platebody
Platelegs: Mithril_Platelegs
Boots: Boots_Of_Stealth
Weapon: Dragon_Dagger
Shield: Fine_Coinpurse
Amulet: Clue_Chasers_Insignia
Ring: Ancient_Ring_Of_Mastery
Gloves: Gloves_of_Silence
Quiver: Fishing_Hook
Cape: Thievers_Cape
Summon1: Summoning_Familiar_Leprechaun
Summon2: Summoning_Familiar_Devil

Skill Information:
function getErrorLog(){return `Is Active: ${this.isActive}\n`;}
  Selected Area: WIZARD_TOWER
  Selected NPC: ACOLYTE
  Is Stunned: false

### Reproduction Steps

 - Start thieving from ACOLYTE (as in lvl 1 mastery, never thieved from before).
 - Force cloud save
 - Leave for 11 hours
 - Open local save game
 - See error

### Save Link

https://melvoridle.com/save/tCGVW7oh

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
I believe this was hotfixed a few weeks ago
