### ISSUE TITLE
[Bug]: Cooking salmon does not reward cooked salmon

### ISSUE THREAD

**Issue by KHuberdeau** [MelvorIdle/melvoridle.github.io#2405]
### Describe the bug

When cooking salmon using the cooking skill, raw salmon is removed from the player's inventory, but the player is not rewarded with a cooked version (either perfect or normal salmon). No other fish or food seem to be affected.

### Reproduction Steps

1. Have raw salmon in your inventory
2. Go to the cooking skill
3. Select salmon for cooking
4. Cook salmon and wait for it to be done
5. Upon cooking the salmon, the +2 salmon icon will pop up from the bottom, but cannot be found in the player's inventory

### Expected behaviour

Upon completion of cooking salmon, in addition to the icon pop up, the salmon will be added to the player's inventory.

### Save Link

https://melvoridle.com/save/3y196fsG

### Screenshots

![image](https://user-images.githubusercontent.com/59401861/163685252-12d0a34c-baca-4ad7-bdd2-35a9e20c21d7.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by Silberdrachi** [comment]
do you have auto-equip enabled and do you have salmon in your combat food menu?

**Comment by KHuberdeau** [comment]
I did not realize the food was automatically being added to my equipped food... Closing.
