### ISSUE TITLE
[Bug]: 符文锻造界面，精通池等级显示错误

### ISSUE THREAD

**Issue by Fu2urama** [MelvorIdle/melvoridle.github.io#2406]
### Describe the bug

精通池经验显示错误

### Screenshots

<img width="1642" alt="WX20220417-113252@2x" src="https://user-images.githubusercontent.com/42938851/163699144-6f6b29fe-46d9-4dd2-b4d3-4d436113d6f0.png">

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
