### ISSUE TITLE
[Bug]: 简体中文语言模式下，依然显示繁体中文

### ISSUE THREAD

**Issue by Fu2urama** [MelvorIdle/melvoridle.github.io#2408]
### Describe the bug

更新新版本后突然变成繁体中文，语言选择还是简体中文

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
