### ISSUE TITLE
Saves that have never owned or used Weird Goop will fail to load

### ISSUE THREAD

**Issue by iPeer** [MelvorIdle/melvoridle.github.io#241]
**Describe the bug**
The game fails to load with errors in the console when attempting to load a pre-0.15 save that has never used or owned Weird Goop.

**To Reproduce**
1. Attempt to load a save that has never owned any Weird Goop.
2. The game will fail to load the save

**Expected behavior**
The game loads as expected with the Weird Goop's times used stat set to 0.

**Screenshots**
n/a

**Browser**
Chrome 81.0.4044.138

**Console output**
```
Local backup successfully stored
save.js?291:48 Loading Save Game...
stats.js?286:331 Uncaught TypeError: Cannot read property 'timesFound' of undefined
    at updateStats (stats.js?286:331)
    at updateStats (stats.js?286:252)
    at loadData (save.js?291:208)
    at initiateLoad (save.js?291:366)
    at window.onload (save.js?291:519)
```

**Comment by MelvorIdle** [comment]
Fixed in the upcoming update, but will implement it as a hotfix when server migration is complete.
