### ISSUE TITLE
[Bug]: Stuck on loading offline progress and cant do anything

### ISSUE THREAD

**Issue by amereid** [MelvorIdle/melvoridle.github.io#2410]
### Describe the bug

I have this issue on iOS and on the website. I login and select a save which enters me into the game. A popup saying loading offline progress appears and never succeeds (on web it seems like its looping). I cant perform any action except for farming. All other actions do nothing and no warning or error appears.

### Save Link

https://melvoridle.com/save/kzseBjHN

### Screenshots

![image](https://user-images.githubusercontent.com/4269633/163862982-db21a0e2-9387-42b8-bc31-3b1a3c3d57b7.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by strangor** [comment]
This just started happening to me today.

**Comment by MelvorIdle** [comment]
Related #2327

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
