### ISSUE TITLE
[Bug]: Web version gets stuck after logging in

### ISSUE THREAD

**Issue by TijsBloemen** [MelvorIdle/melvoridle.github.io#2411]
### Describe the bug

The game gets stuck on 'https://melvoridle.com/index_noads.php' after I try logging in (web version on multiple browsers). Deleting cookies and passwords can send me back to the home page, but every time i log in i get stuck on the same page. This is the first time in over a year i try to log in to the browser version, I have no problems logging in on Android.

### Reproduction Steps

Go to melvoridle.com
Log in
Get stuck on 'https://melvoridle.com/index_noads.php'

### Expected behaviour

I expect to log in to my account.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

Cant check

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
