### ISSUE TITLE
[Bug]: Aorpheat's ring is not adding +100% GP from thieving.

### ISSUE THREAD

**Issue by Jyxaw** [MelvorIdle/melvoridle.github.io#2413]
### Describe the bug

Aorpheat's ring is not adding +100% GP from thieving.

Ex.: Wizard's Tower : Acolyte drops 983-4283 Gp

With Aorpheat's ring equipped the minimum GP you would ever see is 1966, but I'm constantly seeing GP values well below that and never above the max value of 4283. The new range without any other GP modification should be 1966-8566

### Reproduction Steps

1. Eqipt Aorpheat's ring
2. Go to thieving
3. Pickpocket the Acolyte
4. Observe the GP values not being altered by the GP stats of the ring

### Expected behaviour

GP values are altered by the GP stats of the ring

### Save Link

https://melvoridle.com/save/20cC1VfO

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by Seilaerion** [comment]
GP bonuses are accounted for already in the drop list's displayed GP, you get what you see (feel free to check the list with and without the ring equipped).  The Signet RIng's bonus is also additive with other bonuses, meaning it only doubles the value if you have no other % GP bonuses.
