### ISSUE TITLE
[Bug]: Mining Node HP bugs when levelled up via mastery points spending

### ISSUE THREAD

**Issue by Emely1** [MelvorIdle/melvoridle.github.io#2415]
### Describe the bug

I have found that after unlocking a new mining node mining it to 0 then levelling it up as much as possible and after it has respawned the node respawns with about 10% hp 
It appears at 100% hp but once you mine it it drops instantly to around 5-10% HP 

### Reproduction Steps

1. Go to mining tab 
2. Mine out a node around level 1 mastery(low level mastery)
3. level up the node before it respawns via mastery points spend
4. Mine the node once it has respawned
5. Note that the node appears at 100% hp then once it has been harvested once it drops to about 5-10%

### Expected behaviour

The node should have the appropiate HP for the mastery level.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
