### ISSUE TITLE
[Bug]: iOS Melvor App only shows Southwest Airlines website

### ISSUE THREAD

**Issue by benjaminmikiten** [MelvorIdle/melvoridle.github.io#2418]
### Describe the bug

This is a very silly issue I've created for myself. 

When launching Melvor on in-flight wifi, the (I assume, forgive me) webview was redirected to southwest.com. Now, back on normal wifi, after both rebooting my phone and crashing the app, I can only see the southwest airlines site when I boot Melvor.

When not paying for actual internet access while connected to inflight wifi, all requests are redirected to southwest.com. Something in the app state is retaining that URL, causing me to only see southwest.com when I boot melvor.

FWIW, I have fixed this -- uninstalling and reinstalling the app fixed it.

### Reproduction Steps

1. Book a flight. Get to the airport w/ enough time to go through TSA, then board your flight. 
2. After takeoff, get on the in-flight wifi -- do not pay $8 to browse the larger internet.
3. Go to any site, you will be redirected to southwest.com.
4. Launch Melvor, see the webview redirect to southwest.com
5. After landing, get on off-flight wifi, and confirm sites will navigate normally.
6. Boot Melvor. GOTO 1.

### Expected behaviour

After launching Melvor on in-flight wifi and having the webview show southwest.com instead, when returning to normal wifi, I should see Melvor again.

Alternately, when on a network that redirects requests, the webview should try to navigate to melvor's url even if it's been redirected in the past.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is an cache issue. Please clear the cache of the app and it should resolve itself eventually. Southwest Airlines seems to take over webview apps entirely until the cache is cleared

**Comment by benjaminmikiten** [comment]
Thanks for getting back to this! 

When this happens the user is unable to access any feature of the app, including clearing the cache. 

Should I create another ticket to request a feature to clear the cache through the settings entry on iOS for Melvor?
