### ISSUE TITLE
[Bug]: gloves of thieving 

### ISSUE THREAD

**Issue by Smokin420s** [MelvorIdle/melvoridle.github.io#2419]
### Describe the bug

I have 179k charges of the gloves of thieving, and I cant seem to find the gloves anywhere in my bank or my equipped gear.

### Save Link

https://melvoridle.com/save/cIVk5knu

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by xanderput** [comment]
They're in your first equipment slot.

![image](https://user-images.githubusercontent.com/39944140/164560860-f5d201c1-7b17-476b-97ec-e02a7ad8b93a.png)

**Comment by MelvorIdle** [comment]
The gloves are in your first equipment set.
