### ISSUE TITLE
Calculating the ofline progress never ends

### ISSUE THREAD

**Issue by Psendziuk** [MelvorIdle/melvoridle.github.io#2422]
### Describe the bug

I'm stuck when i log in my account, the app starts to calculate the progress ofline but it never ends and i can't do nothing more even in the steam app, everything is blocked and i already cleaned up the cache and also cleaned up everything as well but it didn't work it.

Last thing that I remember that i did is select some active some summoning sinergy but i dont remember which one and got this trouble.

### Screenshots

![Screenshot_20220424-010740_Melvor Idle](https://user-images.githubusercontent.com/104281287/164948948-917b9d9b-a737-4eab-b452-51f50851656a.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by tutuca2** [comment]
I am also having the exact same bug, and I was also making some summoning tablets when I last closed the game. I can change equipments, manage some stuff in my bank, plant and harvest crops but apart from that everything is stuck: I can't train any skill or enter in combat. I also just noticed that when I buy bank slots, the price is subtracted from my money but the inventory size doesn't change.

**Comment by knutlan** [comment]
I have the same problem as well, but with fletching. Annoying amthat a months worth of game just stops like that. Don’t want to restart it all :/

**Comment by zimeng657** [comment]
same problem.

**Comment by leejg1** [comment]
Same problem. I left my game mining, my computer went into sleep mode, loaded back up... stuck on "Loading your offline progress". What do I do now? Leave my save and hope its recoverable?

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
