### ISSUE TITLE
[Bug]: Pet Completion Log Quantity Update

### ISSUE THREAD

**Issue by Seilaerion** [MelvorIdle/melvoridle.github.io#2423]
### Describe the bug

Upon unlocking a new pet, the "Pets Found" number doesn't update in the Completion Log.  The percentage is updated correctly, and the pet appears in the log.

The total updates upon reloading the save.

### Reproduction Steps

1. Unlock a new pet.
2. Check Pets section of the Completion Log

### Screenshots

Immediately after unlocking Leonardo (Shows "2 / 45", instead of 3, but shows the expected %):
![image](https://user-images.githubusercontent.com/601043/164965725-5c23f618-7bec-4230-94a5-aa805720db23.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1876

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
