### ISSUE TITLE
[Bug]: Superhuman Strength prayer cost double

### ISSUE THREAD

**Issue by dariondesode** [MelvorIdle/melvoridle.github.io#2424]
### Describe the bug

The prayer ability Superhuman Strength states that it cost 2 prayer per attack but it is using twice that and costing 4 prayer per attack

### Expected behaviour

Would like to either see the discription cost changed to match the actual amout being pulled or correct the bug so it actually pulls the correct amount.

### Save Link

https://melvoridle.com/save/IwdRJiTR

### Screenshots

[https://i.imgur.com/CFWAhg0.png](url)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1876

### Are you using any scripts or extensions?

No

**Comment by dariondesode** [comment]
I actually just tested it with a few other prayers and all of them are costing 2 more than what the discription says

**Comment by Flurryous** [comment]
You probably have the agility course Cliff Balance active.

**Comment by dariondesode** [comment]
just got home and checked.  You're right and I do have Cliff Balance active.  I didn't even notice that it did that. Thanks for the help.
