### ISSUE TITLE
[Bug]: Can't open saves

### ISSUE THREAD

**Issue by justinhartma7** [MelvorIdle/melvoridle.github.io#2425]
### Describe the bug

When I try to open either of my saves or create a new save it gives me this error and won't open. Using Edge gives me the same error but they work on my phone. I am using the Brave browser. It did used to work but stopped working about a week ago. I am not able to see what version I am using but it does say my saves are compatible on all versions

### Save Link

https://melvoridle.com/save/qxXZDqvV

### Screenshots

![image](https://user-images.githubusercontent.com/59844914/165664787-e2085188-c229-4848-a0dc-fe87ed3e9444.png)

### Console output

[melvoridle.com-1651113403072.log](https://github.com/MelvorIdle/melvoridle.github.io/files/8579092/melvoridle.com-1651113403072.log)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

unsure

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Opening the provided save works for me on Brave browser. Can you confirm you are still seeing this issue?
