### ISSUE TITLE
[Bug]: Random Ocean Song effect without the item

### ISSUE THREAD

**Issue by staticf0x** [MelvorIdle/melvoridle.github.io#2426]
### Describe the bug

During Golbin Raid I received the Ocean Song passive despite not ever obtaining the item. Unfortunately I don't know when this happened and cannot reproduce it atm.

### Screenshots

![melvor-bug](https://user-images.githubusercontent.com/44530786/165740170-d5129957-d6a9-46d1-85d1-785733937de7.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1876

### Are you using any scripts or extensions?

No

**Comment by xanderput** [comment]
You got an "(ALT) Poisoned Dagger". Any weapon with a special attack has a 25% chance to be replaced by an ALT version. 
The ALT means that the existing special attack will be replaced by a random special attack. 
In your case, you ended up with the special attack from Ocean Song

**Comment by staticf0x** [comment]
Ahhh thank you for the info! Will close it then 😄
