### ISSUE TITLE
[Spelling/Grammar]: Book of Scholars

### ISSUE THREAD

**Issue by oliverqwer** [MelvorIdle/melvoridle.github.io#2427]
### What text is wrong?

The Book of Scholars says that it provides +15% Global GP (+15 % Goldmünzen bei allen Aktivitäten). At least in the german translation.

### What is the correct spelling or grammar?

It should say -15% Global GP (-15 % Goldmünzen bei allen Aktivitäten).

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
