### ISSUE TITLE
Purchased Rune Pick Axe - Money taken but Pick Axe not upgraded. 

### ISSUE THREAD

**Issue by jamesmorts** [MelvorIdle/melvoridle.github.io#243]
**Describe the bug**
I purchased the Rune Pick Axe upgrade for 1M from the store - it took the money, however my pickaxe is still showing as Adamant.

**To Reproduce**
Unsure, the feature just didn't work as intended. I essentially logged in and just purchased it after selling my ore from last night. 

**Expected behavior**
Expected to get a Rune Pick Axe (Can't help but laugh at this question in this context :D)

**Screenshots**
![image](https://user-images.githubusercontent.com/17962929/82617508-a08b0b00-9c13-11ea-87d1-24b9c329107d.png)
The pickaxe still shows as rune in my shop. Unsure what else I can include here, sorry!

**Browser**
Google Chrome - Version 81.0.4044.138 (Official Build) (64-bit)

**Console output**
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js?threshold=93:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
save.js?293:476 Not required to backup
save.js?293:48 Loading Save Game...
save.js?293:209 Save Game Loaded...
save.js?293:48 Loading Save Game...
save.js?293:209 Save Game Loaded...
smithing2.js?287:191 Loading Smithing...
mastery.js?288:183 Updating Masteries
mastery.js?288:23 Loading Masteries...
main.js?317:1259 Game Loaded
oneui.core.min.js?205:6 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ oneui.core.min.js?205:6
cloud.js?292:48 Melvor Cloud Connection: Success
save.js?293:48 Loading Save Game...
save.js?293:209 Save Game Loaded...
smithing2.js?287:191 Loading Smithing...
mastery.js?288:183 Updating Masteries
mastery.js?288:23 Loading Masteries...
main.js?317:1259 Game Loaded
cloud.js?292:194 Cloud synced
DevTools failed to load SourceMap: Could not load content for chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Are you using any scripts?**
I'm not actually sure what this is asking specifically so I'll assume not.

**Comment by MelvorIdle** [comment]
Does a refresh provide the correct axe?

**Comment by jamesmorts** [comment]
Unfortunately not, I tried refreshing, hard refreshing, and entirely updating/restarting chrome. The issue persists through all of the above.
Let me know if there's any other info I can provide to help.
