### ISSUE TITLE
[Bug]: Can't select smithing drop down options in Tutorial Island

### ISSUE THREAD

**Issue by McWizard0** [MelvorIdle/melvoridle.github.io#2430]
### Describe the bug

When clicking on the smithing drop down menu while trying to complete the tutorial, I cannot click any option, such as the category of bars.

### Reproduction Steps

1. Reach smithing step of tutorial
2. Select smithing from left side menu or from quest marker 
3. Click "select smithing category"
4. Select any option, click passed through menu

### Expected behaviour

The clicks on the drop down do not hit the categories, they seem to click under the drop down, closing it.

### Save Link

https://melvoridle.com/save/BE3qRMbD

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1876

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
