### ISSUE TITLE
[Bug]: Herblore: Incorrect preservation chance after applying mastery XP

### ISSUE THREAD

**Issue by TomSmash** [MelvorIdle/melvoridle.github.io#2432]
### Describe the bug

Was creating secret stardust potions, but my mastery level was 16, so using my global mastery pool i boosted that potion level to 86 by clicking the +10 level button untill I was going to drop down past the 50% global pool and stopped there. 

Now it reads a 2% chance to preserve resourses, if I take off my crown of Rhaelynx it drops down to a -8% chance. Watching the potions being made 2% an accurate number, only saw the preserve resource proc once or twice in the 5 mins I watched it so not a visual glitch.

### Reproduction Steps

Not something I can reproduce on my own. Exiting the game and opening it back up doesn't fix it.

### Expected behaviour

Should have a preserve chance of 27% or so (86*0.2 = 17.2, then add the 10% chance for preservation for the crown)

### Screenshots

![Herblore bug](https://user-images.githubusercontent.com/42096703/166621947-3d9d439e-ba4b-47ce-8438-650ebc6fcf25.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1876

### Are you using any scripts or extensions?

No

**Comment by TomSmash** [comment]
oops forgot to include the save, here it i
[melvoridlesave_Smash.txt](https://github.com/MelvorIdle/melvoridle.github.io/files/8617836/melvoridlesave_Smash.txt)

**Comment by 47Y** [comment]
Looking at the save, you have -30% Chance to Preserve Resources in Skills from agility. With that, the 2% seems accurate from some quick math.
