### ISSUE TITLE
[Bug]: <title>一直卡在欢迎回来那个界面

### ISSUE THREAD

**Issue by DDMMeng** [MelvorIdle/melvoridle.github.io#2435]
### Describe the bug

就一直卡在欢迎回来，正在加载你的离线进度，如果点了好进去后，所有的选项点了也不会有作用，已经3天了

### Reproduction Steps

start game
select role

### Screenshots

![wrong-picture](https://user-images.githubusercontent.com/97266884/167090356-18fda93f-d8ad-460a-9ee9-2278c4a119cd.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1876

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Related #2327

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
