### ISSUE TITLE
[Bug]: <title> Missing items 

### ISSUE THREAD

**Issue by Banpari1** [MelvorIdle/melvoridle.github.io#2436]
### Describe the bug

I’ve been idling rooken for a while never had a problem, I got a death screen with no explanation and lost a Ragnar plate armor, but I hv a spare so it’s alright, however I also lost my tidal edge but the game never said I lost it or anything it’s just gone 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1876

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
