### ISSUE TITLE
[Bug]: Summon Tablets fail to craft if bank is full, but cost resources anyway

### ISSUE THREAD

**Issue by Loomshade** [MelvorIdle/melvoridle.github.io#2437]
### Describe the bug

Each time after unlocking the Mark of the Octopus and Pig, I attempted to craft their Tablets immediately. Both times, the tablets ate my resources, but didn't give me tablets and complained my bank was full even though it clearly had 1-2 slots free. After some testing, I found that my bank was full, as I had purchased barely enough Summoning Shards to make do. See video below for demonstration.

https://user-images.githubusercontent.com/81527957/167199623-834829f1-fce1-4dd4-aaeb-2f5d60137ddd.mp4

Not that I'm the developer here, but it feels like the game is trying to give me the tablets before taking away the resources; I don't know how true that is, but hey, I at least feel like I contributed. It's a pretty situational glitch, but here you go. Have fun.
Also, thanks for the incredible game, Malcs. That too.

### Reproduction Steps

1. Have _exactly_ enough of at least one of the resources required to create summoning tablets. You should run out just as the tablets are made. (This may be summoning-crystal-exclusive, but I think it's all tablet-crafting resources.)
2. Craft whichever tablet you resonate the most with in that moment.
3. Wait 3.00 seconds, and Viola! Your resources are now gone, and your tablets were never made.
(See Description for a video of this)

### Expected behaviour

I would expect this action to either
-Give me the tablets in exchange for the resources as is normal
or
-Complain I need to make more bank space first, preserving the resources and not crafting the tablets

### Save Link

https://melvoridle.com/save/s3ecqNi8

### Screenshots

See description for a view of 60 screenshots per second, spread across 49 seconds.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1876

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
I have looked into this further and can confirm this is an intended mechanic of the game.

Attempting to create the items when they are not able to fit in your bank will still reward you with XP and MXP + plus everything else.

The game does this on purpose to ensure any possible extra drops are not missed. It's just a prioritization issue with how items are handled. Doing it this way is the intended way.

Although it may seem weird with this very specific scenario, it is just how the general system is designed.
