### ISSUE TITLE
[Bug]: Game gets stuck loading offline progress

### ISSUE THREAD

**Issue by mbenke** [MelvorIdle/melvoridle.github.io#2440]
### Describe the bug

The game gets stuck when loading offline progress of my character. I tried creating a new character, but it succumbed to the same fate after a few hours of playing.

This behaviour seems consistent across many attempts and platforms, but on Firefox I have noticed in the console (full console content attached later)

Uncaught Error: Offline timestamp is null utils.js:128:7

### Reproduction Steps

1. Open Melvor Idle
2. Select Character
3. The "Welcome Back" popup appears, and stays there with the message "Loading your offline progress. Please wait..."

### Expected behaviour

I can load my character and play ;)

### Save Link

https://melvoridle.com/save/kEf1BhWy

### Console output

GEThttps://melvoridle.com/style.css?2
[HTTP/3 404 Not Found 314ms]

GEThttps://themes.googleusercontent.com/fonts/css?kit=fpjTOVmNbO4Lz34iLyptLTi9jKYd1gJzj5O2gWsEpXoyck2WCYPEMNySjZN0CHed_kmCvy597kDopqFAXvpeaA
[HTTP/3 403 Forbidden 78ms]

Zablokowano zasób „https://themes.googleusercontent.com/fonts/css?kit=fpjTOVmNbO4Lz34iLyptLTi9jKYd1gJzj5O2gWsEpXoyck2WCYPEMNySjZN0CHed_kmCvy597kDopqFAXvpeaA” z powodu niezgodności (X-Content-Type-Options: nosniff) typu MIME („text/html”).
[MelvorIdleFanartCompH1TermsClean22022022_2_.d.html](https://melvoridle.com/pages/other/MelvorIdleFanartCompH1TermsClean22022022_2_.d.html)
XHRPOSThttps://melvoridle.com/cdn-cgi/rum?
[HTTP/3 200 OK 51ms]

XHRGEThttps://melvoridle.com/lang/en.json?319
[HTTP/3 200 OK 0ms]

XHRPOSThttps://melvoridle.com/cdn-cgi/rum?
[HTTP/3 200 OK 55ms]

XHRPOSThttps://melvoridle.com/cdn-cgi/rum?
[HTTP/3 200 OK 110ms]

XHRPOSThttps://e3855.playfabapi.com/Client/LoginWithCustomID?sdk=JavaScriptSDK-1.93.210927
[HTTP/2 200 OK 330ms]

XHRPOSThttps://melvoridle.com/cloud/ping.php
[HTTP/3 200 OK 328ms]

XHRPOSThttps://melvoridle.com/cloud/checkCloudConnection.php
[HTTP/3 200 OK 513ms]

XHRPOSThttps://e3855.playfabapi.com/Client/ExecuteCloudScript?sdk=JavaScriptSDK-1.93.210927
[HTTP/2 200 OK 267ms]

XHROPTIONShttps://e3855.playfabapi.com/Client/GetTitleData?sdk=JavaScriptSDK-1.93.210927
[HTTP/2 200 OK 211ms]

XHROPTIONShttps://e3855.playfabapi.com/Client/GetUserData?sdk=JavaScriptSDK-1.93.210927
[HTTP/2 200 OK 215ms]

XHRPOSThttps://e3855.playfabapi.com/Client/GetUserReadOnlyData?sdk=JavaScriptSDK-1.93.210927
[HTTP/2 200 OK 227ms]

XHRPOSThttps://e3855.playfabapi.com/Client/GetTitleData?sdk=JavaScriptSDK-1.93.210927
[HTTP/2 200 OK 221ms]

XHRPOSThttps://e3855.playfabapi.com/Client/GetUserData?sdk=JavaScriptSDK-1.93.210927
[HTTP/2 200 OK 325ms]

XHRPOSThttps://melvoridle.com/cloud/shareSave.php
[HTTP/3 200 OK 705ms]

XHRGEThttps://melvoridle.com/pageContainer.php?7
[HTTP/3 200 OK 1529ms]

Uncaught Error: Offline timestamp is null
    getOfflineTimeDiff https://melvoridle.com/assets/js/built/utils.js?1876:128
    processOffline https://melvoridle.com/assets/js/built/game.js?1876:76
    setTimeout handler*processOffline/< https://melvoridle.com/assets/js/built/game.js?1876:76
    processOffline https://melvoridle.com/assets/js/built/game.js?1876:73
    updateOffline https://melvoridle.com/assets/js/game/main.js?1876:168
    finaliseLoad https://melvoridle.com/assets/js/game/main.js?1876:270
    selectCharacter https://melvoridle.com/assets/js/game/main.js?1876:261
    onloadEvent https://melvoridle.com/assets/js/game/save.js?1876:74
    resetEntirePage https://melvoridle.com/assets/js/game/save.js?1876:79
    load https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    each https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    each https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    load https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    r https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    fireWith https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    c https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    o https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    send https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    ajax https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    load https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    resetEntirePage https://melvoridle.com/assets/js/game/save.js?1876:79
    setForceReload https://melvoridle.com/assets/js/game/save.js?1876:71
    selectCharacter https://melvoridle.com/assets/js/game/main.js?1876:261
    selectCharacter https://melvoridle.com/assets/js/game/main.js?1876:260
    promise callback*then https://melvoridle.com/assets/js/plugins/sweetalert2/sweetalert2.min.js?1876:1
    selectCharacter https://melvoridle.com/assets/js/game/main.js?1876:260
    onclick https://melvoridle.com/index_noads.php:1
utils.js:128:7
    getOfflineTimeDiff https://melvoridle.com/assets/js/built/utils.js?1876:128
    processOffline https://melvoridle.com/assets/js/built/game.js?1876:76
    (asynchroniczny: setTimeout handler)
    processOffline https://melvoridle.com/assets/js/built/game.js?1876:76
    processOffline https://melvoridle.com/assets/js/built/game.js?1876:73
    updateOffline https://melvoridle.com/assets/js/game/main.js?1876:168
    finaliseLoad https://melvoridle.com/assets/js/game/main.js?1876:270
    selectCharacter https://melvoridle.com/assets/js/game/main.js?1876:261
    onloadEvent https://melvoridle.com/assets/js/game/save.js?1876:74
    resetEntirePage https://melvoridle.com/assets/js/game/save.js?1876:79
    load https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    each https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    each https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    load https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    r https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    fireWith https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    c https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    o https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    (asynchroniczny: EventHandlerNonNull)
    send https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    ajax https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    load https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6
    resetEntirePage https://melvoridle.com/assets/js/game/save.js?1876:79
    setForceReload https://melvoridle.com/assets/js/game/save.js?1876:71
    selectCharacter https://melvoridle.com/assets/js/game/main.js?1876:261
    selectCharacter https://melvoridle.com/assets/js/game/main.js?1876:260
    (asynchroniczny: promise callback)
    then https://melvoridle.com/assets/js/plugins/sweetalert2/sweetalert2.min.js?1876:1
    selectCharacter https://melvoridle.com/assets/js/game/main.js?1876:260
    onclick https://melvoridle.com/index_noads.php:1
XHRPOSThttps://melvoridle.com/cloud/checkCloudConnection.php
[HTTP/3 200 OK 220ms]

XHRPOSThttps://melvoridle.com/cloud/ping.php
[HTTP/3 200 OK 245ms]

GEThttps://themes.googleusercontent.com/fonts/css?kit=fpjTOVmNbO4Lz34iLyptLTi9jKYd1gJzj5O2gWsEpXoyck2WCYPEMNySjZN0CHed_kmCvy597kDopqFAXvpeaA
[HTTP/3 403 Forbidden 144ms]

XHROPTIONShttps://e3855.playfabapi.com/Client/LoginWithCustomID?sdk=JavaScriptSDK-1.93.210927
[HTTP/2 200 OK 212ms]

Zablokowano zasób „https://themes.googleusercontent.com/fonts/css?kit=fpjTOVmNbO4Lz34iLyptLTi9jKYd1gJzj5O2gWsEpXoyck2WCYPEMNySjZN0CHed_kmCvy597kDopqFAXvpeaA” z powodu niezgodności (X-Content-Type-Options: nosniff) typu MIME („text/html”).
MelvorIdleFanartCompH1TermsClean22022022_2_.d.html
XHRPOSThttps://e3855.playfabapi.com/Client/LoginWithCustomID?sdk=JavaScriptSDK-1.93.210927
[HTTP/2 200 OK 282ms]

XHRPOSThttps://melvoridle.com/cdn-cgi/rum?
[HTTP/3 200 OK 48ms]

XHRPOSThttps://melvoridle.com/cdn-cgi/rum?
[HTTP/3 200 OK 55ms]

XHROPTIONShttps://e3855.playfabapi.com/Client/GetTitleData?sdk=JavaScriptSDK-1.93.210927
[HTTP/2 200 OK 220ms]

XHROPTIONShttps://e3855.playfabapi.com/Client/ExecuteCloudScript?sdk=JavaScriptSDK-1.93.210927
[HTTP/2 200 OK 220ms]

XHROPTIONShttps://e3855.playfabapi.com/Client/GetUserData?sdk=JavaScriptSDK-1.93.210927
[HTTP/2 200 OK 223ms]

XHRPOSThttps://e3855.playfabapi.com/Client/GetTitleData?sdk=JavaScriptSDK-1.93.210927
[HTTP/2 200 OK 255ms]

XHRPOSThttps://e3855.playfabapi.com/Client/ExecuteCloudScript?sdk=JavaScriptSDK-1.93.210927
[HTTP/2 200 OK 254ms]

XHRPOSThttps://e3855.playfabapi.com/Client/GetUserData?sdk=JavaScriptSDK-1.93.210927
[HTTP/2 200 OK 232ms]

XHROPTIONShttps://e3855.playfabapi.com/Client/GetUserReadOnlyData?sdk=JavaScriptSDK-1.93.210927
[HTTP/2 200 OK 206ms]

XHRPOSThttps://e3855.playfabapi.com/Client/GetUserReadOnlyData?sdk=JavaScriptSDK-1.93.210927
[HTTP/2 200 OK 224ms]

XHRPOSThttps://e3855.playfabapi.com/Client/GetTitleData?sdk=JavaScriptSDK-1.93.210927
[HTTP/2 200 OK 247ms]

XHROPTIONShttps://e3855.playfabapi.com/Client/GetTitleNews?sdk=JavaScriptSDK-1.93.210927
[HTTP/2 200 OK 220ms]

XHRPOSThttps://e3855.playfabapi.com/Client/GetTitleNews?sdk=JavaScriptSDK-1.93.210927
[HTTP/2 200 OK 234ms]

XHRPOSThttps://melvoridle.com/cloud/syncSave.php
[HTTP/3 200 OK 533ms]

XHROPTIONShttps://e3855.playfabapi.com/Client/UpdateUserData?sdk=JavaScriptSDK-1.93.210927
[HTTP/2 200 OK 207ms]

XHRPOSThttps://e3855.playfabapi.com/Client/UpdateUserData?sdk=JavaScriptSDK-1.93.210927
[HTTP/2 200 OK 273ms]

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [X] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1876

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Related #2422

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
