### ISSUE TITLE
Chest Opened, no items recieved

### ISSUE THREAD

**Issue by EndLee** [MelvorIdle/melvoridle.github.io#2441]
### Describe the bug

So I was idling Dragons Den all night and got probably ~40-50 chests, when I was opening them I accidentally double clicked "Open item" to open the chests and I didn't get any items. Just out of curiosity I did it again with 1 chest, double clicked "Open item" and got nothing.

I also checked my progression before and after opening and it does register as an opened chest, you just don't get any items for it.

### Reproduction Steps

1. Complete Dragons Den
2. Recieve Elder Chest
3. Double click "Open item" to open the chests
4. Get scammed *giggle*

### Expected behaviour

Expect to not get any items from the chest.

### Save Link

https://melvoridle.com/save/eHn9AFim

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1876

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
I cannot reproduce this bug. Double clicking the Open button does force the popup to disappear, however the items are still added to my bank. I have tested with all dungeon chests and have not seen the bug.

Please feel free to open another issue if you are able to reproduce it, and possibly provide a video if you can.
