### ISSUE TITLE
[Bug]: Gold Topaz ring still drops when it is equipped

### ISSUE THREAD

**Issue by xapex** [MelvorIdle/melvoridle.github.io#2442]
### Describe the bug

Gold topaz ring description says that something else is supposed to drop insead of it, yet it still drops when one is equipped. 

### Reproduction Steps

1. GO farm Mummy in Penumbra
2. Get Gold topaz ring and equip it
3.  gold topaz ring continues to drop

### Expected behaviour

Something else is expected to drop instead of Gold topaz rings, based on item description

### Screenshots

![image](https://user-images.githubusercontent.com/23164561/168425822-91cfb64c-04d6-462a-90bc-9df44db6a1f7.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1876

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
The ring you see in the loot container is a standard drop from the monster which is not affected by the passive effect listed on your equipped gold topaz ring.
