### ISSUE TITLE
[Bug]: Select Potion window, count not updating

### ISSUE THREAD

**Issue by puggan** [MelvorIdle/melvoridle.github.io#2443]
### Describe the bug

The potion count in the Select poition window dosn't update.

### Reproduction Steps

1. Create 3 or more Bird Nest Potions
2. Start chopping down wood.
3. Activate the Bird Nest Poitions
4. Make sure Auto re-use is enabled
5. Keep the Select potion window open
6. Wait till the charges of the first potion runs out 

### Expected behaviour

1. The number of Bird Nest Potions decresese by one.

# Current behaviour
1. The number of potion stays the same as before it was re-used.

### Screenshots

Before re-use:
![image](https://user-images.githubusercontent.com/866668/168432401-61db91aa-1913-463d-8f22-1ccbd215fff7.png)

After re-use:
![image](https://user-images.githubusercontent.com/866668/168432447-4c6615c3-2d9f-4b46-82ef-1cd5ecf65a99.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1876

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
