### ISSUE TITLE
[Bug]: <Visual bug: buy x =always 0>

### ISSUE THREAD

**Issue by Boool1** [MelvorIdle/melvoridle.github.io#2444]
### Describe the bug

After buying the max 88 bank slots on hardcore mode. The shop only shows buy x 0 even after changing the amount. It is only visual so it does work when switching the amount but it just says its 0. Another person in the discord had this same issue after buying max slots on hardcore account.

### Reproduction Steps

1. Click on shop on a hardcore account.
2. Buy all 88 bank slots.
3. Click on gloves tab or materials and items tab in bank.
4. It displays "buy x 0"
5. Click buy x  any amount but 0
6. It still displays as "buy x0"

### Expected behaviour

The bank showing the buying amount just like on my other characters.

### Save Link

https://melvoridle.com/save/CK6fxvfr

### Screenshots

![MELVOR](https://user-images.githubusercontent.com/105661182/168635299-b496d239-c274-46e4-bcee-7dbcc80835d7.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1877

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Related #2403

Confirmed fixed in the coming update.

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
