### ISSUE TITLE
[Bug]: Fletching - Shortbow craftable at level 1 with level 5 requirement

### ISSUE THREAD

**Issue by Azemari** [MelvorIdle/melvoridle.github.io#2446]
### Describe the bug
Normal Shortbow (u) and strung are craftable at level 1 despite milestones saying it's unlocked at level 5

### Reproduction Steps

- With Level 1 Fletching
- Go to Fletching
- Select Shortbows
- Fletch Shortbow (u)

### Expected behaviour

EITHER
Shortbow (u) be disabled due to level requirement
OR
Shortbow and Shortbow (u) to have a level requirement of 1 in the UI

### Screenshots

![image](https://user-images.githubusercontent.com/55991839/168785849-31ae5154-4c52-4fa4-8b41-c5f4e8f0c431.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1877

### Are you using any scripts or extensions?

No

**Comment by Azemari** [comment]
Not sure if this is a bug
but fletching normal shortbow (u)s reward 5xp. Stringing normal shortbows rewards 1xp. 
The other tiers reward the same xp for fletching and stringing

**Comment by MelvorIdle** [comment]
This is just a visual bug in the Milestones UI. The bow has a level 1 requirement to equip.

This bow breaks the pattern due to it being part of the tutorial. I don't want to reduce its XP to 1, so I left it at 5xp.

Milestone will be fixed in the coming update
