### ISSUE TITLE
[Bug]: tutorial island locks shop and wont allow you to complete shortbow

### ISSUE THREAD

**Issue by JDOGWIN** [MelvorIdle/melvoridle.github.io#2447]
### Describe the bug

If you get lucky during the other steps prior and don't sell the stuff immediately your bank gets full and then if you complete the bow and arrows they will get deleted into the ether and you can't go buy feathers to remake the arrows so you are forced to either delete character and start again or skip tutorial and not get the rewards

### Reproduction Steps

Make bow and arrows with "full inventory" 10/12 items in bank
Unable to Equip them
Unable to buy more feathers to remake them
Unable to finish tutorial step

### Expected behaviour

Make bow and arrows 
Equip bow and arrows
Finish tutorial step

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1877

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Does the tutorial not allow you to buy more feathers at all or is it because you don't have enough GP to afford to buy them?

**Comment by JDOGWIN** [comment]
It locked the option to buy them. I made sure to sell half my inventory to
make gold and afford it so I had the gold but it still wouldn't let it be
purchased

**Comment by MelvorIdle** [comment]
Thank you. And what tutorial step were you up to? What was your current task? (Either equip the bow, make the bow, kill a monster etc)

**Comment by JDOGWIN** [comment]
Equip the bow and arrows.

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.

**Comment by JDOGWIN** [comment]
Awesome, thanks!
