### ISSUE TITLE
[Bug]: Pet tab not updating correctly

### ISSUE THREAD

**Issue by Sol-Official** [MelvorIdle/melvoridle.github.io#2448]
### Describe the bug

I afk'ed overnight last night and unlocked two pets, cool rock and beavis. It seems I am getting both bonuses, but the pet tab in the completion page hasn't updated the 0/45 counter. However the percentage counter has updated and is currently reading 4.44%, which seems correct. I also have not received the steam achievement for unlocking a pet.

Update while I am typing this, as I was copying the save link, the achievement was received and the counter went up. only issue now is it is approximately 16 hours or thereabouts after I unlocked the pets.

### Reproduction Steps

I can only state what I have done.
1. achieve 50 woodcutting (or around there)
2. buy the new axe upgrade
3. afk overnight
4. come back and click accept on both pets, cool rock and beavis
5. bug presented itself
6. (While typing) wait 16~ hours
7. Counter and achievements were given

### Expected behaviour

I would expect to unlock the achievement and have 2/45 on the counter if I have 2/45 pets unlocked.

### Save Link

https://melvoridle.com/save/7b8PFVrK

### Screenshots

![image](https://user-images.githubusercontent.com/105920468/169512749-74de5b20-db22-41d3-9630-48477a499fda.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1877

### Are you using any scripts or extensions?

No

**Comment by Sol-Official** [comment]
If any questions present themselves, feel free to message me from the discord tag on my profile.

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
