### ISSUE TITLE
[Bug]: ragnar godsword in golbin raid wrong special attack

### ISSUE THREAD

**Issue by dpippen** [MelvorIdle/melvoridle.github.io#2449]
### Describe the bug

Equiping the Ragnar Godsword in the Golbin Raid gives the Crushing Blow buff but it should be the Infernum buff.

### Reproduction Steps

1. start Golbin Raid
2. equip Ragnar Godsword
3. hover mouse over flaming sword icon under damage dealing bar and see Crushing Blow, not Infernum

### Expected behaviour

When equiping the Ragnar Godsword in Golbin Raid I expect to see the Infernum special attack, not the Crushing Blow special attack.

### Save Link

https://melvoridle.com/save/WCaQDipZ

### Screenshots

![image](https://user-images.githubusercontent.com/1176511/169625410-6465b7ba-c6a0-405b-918a-a684116975ce.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

1877

### Are you using any scripts or extensions?

No

**Comment by Silberdrachi** [comment]
You received an alt weapon. Items with (ALT) in the name do not have their normal buffs, and instead have a random choice from the list of specials allowed.
