### ISSUE TITLE
[Bug]: Lost Equipment 

### ISSUE THREAD

**Issue by Jollyjorden** [MelvorIdle/melvoridle.github.io#2451]
### Describe the bug
Lost equipment when swapping. Item Didn't show back in Bank

### Reproduction Steps
I had a stack of 48 Leather Gloves, I selected 'All but one' and then equipped the leather gloves.  I had steel gauntlets previously equipped, which disappeared completely after equipping the leather gauntlets.  Playing on Adventure mode. 

### Expected behaviour

Not to lose equipment when swapping 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1877

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Can you please provide a save link so I can take a look for you?

**Comment by Jollyjorden** [comment]
Thank you for your response, I have never applied for a bug report before
and not too familiar with the process.   I dont know how to obtain the save
file on my mobile device.  If this bug occurs again, I will be better
prepared in my submission.  Thank you for your time and reaching out to me.

Felix

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
