### ISSUE TITLE
[Bug]: Adventure mode skill locked even after purchasing and leveling skill

### ISSUE THREAD

**Issue by jml45** [MelvorIdle/melvoridle.github.io#2453]
### Describe the bug

On an adventure mode character I unlocked astrology and had leveled it some, however now it is locked again. I even have some stardust in my inventory.

### Save Link

https://melvoridle.com/save/P8SU9zRQ

### Screenshots

![Melvor](https://user-images.githubusercontent.com/4933311/169712440-23b97582-4646-462a-979a-aaa51b761d51.PNG)
![Melvor2](https://user-images.githubusercontent.com/4933311/169712442-7bd30f80-c1ac-4d02-8c8c-46d5f06ae616.PNG)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1877

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
