### ISSUE TITLE
[Bug]: Not receiving multiple gloves

### ISSUE THREAD

**Issue by iamlambo** [MelvorIdle/melvoridle.github.io#2454]
### Describe the bug

Bought 5x Smithing gloves then only received one.
Retested 3x Mining gloves then only received one.

### Reproduction Steps

Go to shop and buy 5x smithing gloves.

### Expected behaviour

Expected to receive: 5x Smithing Gloves

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1341

### Are you using any scripts or extensions?

No

**Comment by Silverfyree** [comment]
Buying multiple gloves doesnt give you additional set of gloves, instead it adds the charges to your existing pair of gloves.
