### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by solowanna** [MelvorIdle/melvoridle.github.io#2455]
### Describe the bug

On the completion log the times slain doesn't reflect the actual amount of times i killed a boss.

I'm ideling the fire god dungeon atm. I have 91, but the collection log says i only slayed 87 (Same fot the ancient spell unlock message)

### Reproduction Steps

1. Idle the Fire God Dundeon
2. Afk over night
3. See that the boss kc doesn't match the total scrolls of Ragnar.

### Screenshots

KC: https://imgur.com/IDQJXtp
Total scrolls: https://imgur.com/UaN1yvR

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1877

### Are you using any scripts or extensions?

No

**Comment by Silverfyree** [comment]
Scrolls can be doubled from item doubling effects, agility bonuses and pets.

**Comment by solowanna** [comment]
Aah, forgot about that part.
