### ISSUE TITLE
[Bug]: No treasure chests awarded when fishing Raw Magic Fish in Secret Area

### ISSUE THREAD

**Issue by RockaJosh** [MelvorIdle/melvoridle.github.io#2456]
### Describe the bug

Treasure chests no longer being awarded when fishing Raw Magic Fish.

I've been fishing Raw Magic Fish for a few weeks to build GP. In the last few days Treasure Chests no longer get awarded. I have 3 Characters doing the same thing, but only 1 doesn't get Treasure Chests awarded.

[Character Name: RockaJosh2]

### Reproduction Steps

1. Go to Fishing
2. Select Start Fishing on Raw Magic Fish
3. Idle long enough for Treasure Chest award rate to ensure a chest should be awarded
4. Nothing awarded (Idle for 18hrs+ each time)

### Expected behaviour

Roughly 80-120 Treasure Chests to be awarded within an 18hr idle period

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1882

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
