### ISSUE TITLE
[Bug]: Locked skills are shown when opening the app for the first time on the Bank screen

### ISSUE THREAD

**Issue by GeekyGamer20** [MelvorIdle/melvoridle.github.io#2462]
### Describe the bug

When the app is opened and the startup screen is set to the bank, locked abilities are shown on the hotbar to the right of the screen. Moving to another screen gets rid of these abilites.

![image](https://user-images.githubusercontent.com/54961851/170388548-949c649a-bbd5-4c70-bacf-1372c8144ee2.png)

### Reproduction Steps

1. Open the app with the Bank screen set as default (not sure if it happens with other screens set as deafult.
2. Abilities will be shown on the right, even though they have not been purchased.

### Expected behaviour

They shouldn't be there unless they have been unlocked.

### Save Link

https://melvoridle.com/save/WqmnwkmL

### Screenshots

![image](https://user-images.githubusercontent.com/54961851/170388649-cbe4bdf8-46b1-473d-b96b-88bf9fc387b4.png)
![image](https://user-images.githubusercontent.com/54961851/170388664-3bb6eef9-1c2b-4fbb-8944-80ee8d2ac08f.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1963

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Fixed as of v1.1. Please open a new report if issue persists.
