### ISSUE TITLE
[Bug]: summoning requirement text color is backwards

### ISSUE THREAD

**Issue by Matt-M** [MelvorIdle/melvoridle.github.io#2463]
### Describe the bug

Summoning requirements that you have not met are showing up green and ones you have met are showing up Orange.

### Reproduction Steps

1. Open the summoning synergy page.
2. Scroll to a synergy that you're missing one of the requirements for. 
3. The colors will be backwards.

In my example I have all marks at 4 except monkey. When looking at any of the monkey synergies the monkey requirement is shown in green.

### Expected behaviour

Synergies you don't have should show Orange.

### Save Link

https://melvoridle.com/save/594W1ugd

### Screenshots

![Screenshot_20220526-131852_Melvor Idle](https://user-images.githubusercontent.com/1204062/170487605-a168f223-908a-480c-bc5c-d39a16cbaf5f.jpg)
![Screenshot_20220526-132736_Melvor Idle](https://user-images.githubusercontent.com/1204062/170487672-84284bb8-ebaf-4fb9-92bd-1c4f9c8b3af9.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

1964

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Thank you for the report! A hotfix has now been applied to the game :)
