### ISSUE TITLE
Update deleted save[Bug]: <title>

### ISSUE THREAD

**Issue by Jacob-Suldaan** [MelvorIdle/melvoridle.github.io#2464]
### Describe the bug

I loaded up melvor around 30 minutes ago and found that my save is gone, I have spent 650 hours on it.. the update for the new save UI either deleted my save or removed the ability for me to connect to the melvor cloud server to retrieve my save..

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Hi! Can you please confirm you are logged into Melvor Cloud?

Also, let me know your Cloud username so I can take a look for you and see what has happened.

**Comment by Jacob-Suldaan** [comment]
I played on steam and it always was connected to the cloud before the update, I don't remember signing up, I only know that before the update yesterday the cloud status next to "play" on steam was there and now it isn't

**Comment by Yoshonator** [comment]
this just happened to me, i didnt realize my character was only being saved locally (I play on Steam) and i logged on today and there was only a save on the cloud from around this time last year. I took a long break from the game and only came back to it recently so I suppose I forgot to manually save my progress along the way. If there is no way to get my progress back i probably will just drop the game

**Comment by MelvorIdle** [comment]
If you are disconnected from the Cloud then you must login. We use our own Cloud functionality - not Steam Cloud (We have never supported Steam Cloud).

Can you confirm if you have an account within the game and log in to that? If you are unsure of your details, use the password reset form and see if you get an email sent if you fill it out.

**Comment by Jacob-Suldaan** [comment]
> If you are disconnected from the Cloud then you must login. We use our own Cloud functionality - not Steam Cloud (We have never supported Steam Cloud).
> 
> Can you confirm if you have an account within the game and log in to that? If you are unsure of your details, use the password reset form and see if you get an email sent if you fill it out.

I have tried that, I have used the email connected to my steam (the one i would have used) and it says there wasn't, if the cloud was never done on steam without logging in how did i keep my data throughout 650 hours? and how did a update delete my data?

**Comment by Jacob-Suldaan** [comment]
What can be done about this, my data can't just be gone, its somewhere, and more than likely saved to a cloud storage, specially if it wasn't saved locally originally, how can I find it?

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
