### ISSUE TITLE
[Spelling/Grammar]: About the Golbin`s CHN translation

### ISSUE THREAD

**Issue by feihu233** [MelvorIdle/melvoridle.github.io#2465]
### Which text in the game has a translation error?

The Globin`s CHN translation is "哥布林" which in English means "Goblin", but we know Globin is the special meme of this game.
I`d like to translate it as "戈耳鬓" or "戈耳宾" or "哥林布". the 1st and the 2nd is a type of Transliteration, the 3rd is this meme`s CHN type.
btw, [Spelling/Grammar] is more matching I just thought.

CHN ver：这游戏里的“哥布林族”在这游戏的英文里是“Golbin”而非“Goblin”，这是开发早期的一个疏忽，并由此使这个生物成为了一个梗。但中文版本并没有将这个梗翻译出来，我觉得翻译成戈耳鬓/宾或者哥林布可能更“达”一些。

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
