### ISSUE TITLE
[Bug]: Aorpheat's Signet Ring not doubling GP from Agility 

### ISSUE THREAD

**Issue by FrameXero** [MelvorIdle/melvoridle.github.io#2466]
### Describe the bug

Aorpheat's Signet Ring reads "Passive when equipped - 100% GP granted from all sources except Alt. Magic and item sales.

However, I tried agility tonight after obtaining the ring only to notice it was not applying the ring's passive to my agility GP earned at all. Reading the description I would have assumed the ring would have applied the passive.

It also did not work with thieving. I would expect it to work with fire making, but I cannot test that one yet due to not having 50% mastery.

So far the Ring only applies the 100% GP from combat and summoning like the goblin.

I placed a photo of the problem occuring after the rope swing obstacle and only gaining 10gp, the base amount.

### Reproduction Steps

1. Equip Aorpheat's Signet Ring
2. Build as many obstacles as you can
3. Go wild
4. Notice the GP you earn is the base amount
5. Cry
6. Attempt the skill thieving on Man
7. Notice that the GP never exceeds highest role
8. Cry again 

### Expected behaviour

I would have expected the Ring to apply the 100% GP buff to agility, thieving, and fire making. 

### Save Link

https://melvoridle.com/save/iWUQseIs

### Screenshots

![Screenshot_20220527-010238](https://user-images.githubusercontent.com/63758530/170632799-fdd1acd4-8736-4cda-9347-da6c8b826c98.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1968

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
The GP displayed to you in Agility is the GP you earn incorporating all active GP bonuses. Equipping the signet ring will adjust this number. You don't receive GP that is greater than what is listed in Agility, because the number is already taking into account the bonuses.

Can you confirm that when you unequip the signet ring, the numbers change and the GP you receive is less?

**Comment by FrameXero** [comment]
Ah, for some reason I did not take that into account but it makes complete
sense now. That was a complete misstep on my part, I should have unequipped
the ring as looked at it.

Thank you, and sorry for the misreport!
