### ISSUE TITLE
Can't save the game

### ISSUE THREAD

**Issue by eragonwings** [MelvorIdle/melvoridle.github.io#2467]
### Describe the bug

I have been trying to save my progress for over 10 hrs and it keeps telling me error.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

v1.0.4

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Hi! Can you please post any screenshots or errors your are seeing

**Comment by eragonwings** [comment]
Here is what I get



Sent from Yahoo Mail on Android 
 
  On Sat, May 28, 2022 at 8:45 PM, Melvor ***@***.***> wrote:   


Hi! Can you please post any screenshots or errors your are seeing

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
