### ISSUE TITLE
Combat UI Galaxy Cover X Pro [Bug]: <title>

### ISSUE THREAD

**Issue by SnipinNoob** [MelvorIdle/melvoridle.github.io#2468]
### Describe the bug

When in the Combat tab and while waiting for a monster to respawn the side eat / run tab will flicker quick to the right and left. So much so that I can't click to run or eat until the monster respawns. *note it doesn't flicker in combat only while waiting for the monster to respawn and only happens when in the Combat tab.

### Reproduction Steps

1. Go to combat tab
2. Fight any monster
3. Kill monster and side tab will flicker

### Expected behaviour

The small side tab will flicker on and off the screen moving rapidly left and right, making it impossible to eat or run rin between kills.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

Idk

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
