### ISSUE TITLE
[Bug]: Tutorial Island - Unable to buy more feathers to finish the task

### ISSUE THREAD

**Issue by FrenkyBojler** [MelvorIdle/melvoridle.github.io#2470]
### Describe the bug

Pre task 7 (Range preparations) I spent more GP than necessary. That caused I didn't have enough GP to buy Bowstring, so I sold few arrows. That caused I cannot finish Task 7 because I don't have enough arrows - I cannot create more arrows because I cannot buy feathers in the Shop.

### Reproduction Steps

1. Proceed with Tutorial Island tasks to task number 7
2. Sell some of your bronze arrows
3. Try to create more arrows so you can finish task 7

### Expected behaviour

I as a player am able to create more bronze arrows during task 7, so in case I've lost some arrows for any reason, I can finish task 7 and proceed with Tutorial Island further.

### Screenshots

![image](https://user-images.githubusercontent.com/14737925/171138443-bc9e1d88-9a08-44ce-a2bd-2f38115223ff.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1969

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
