### ISSUE TITLE
[Bug]: Centaur summon crafting requires 50 redwood bows, but 3 magic, 11 yew, etc.

### ISSUE THREAD

**Issue by pagchomp** [MelvorIdle/melvoridle.github.io#2471]
### Describe the bug

[Bug]: Centaur summon crafting requires 50 redwood bows, but 3 magic, 11 yew, etc.
It probably should be 3 or fewer redwood bows required to craft a centaur summon. It's true for both long and short bows.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1969

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is not a bug. Summoning crafting recipes are based on the GP value of the item you use :)

Redwood is far cheaper than Yew and Magic
