### ISSUE TITLE
[Bug]: <Can't start any skills>

### ISSUE THREAD

**Issue by SuperSquib** [MelvorIdle/melvoridle.github.io#2473]
### Describe the bug

When I click on a skill, nothing happens. For instance woodcutting. If i click on any log, The progress bar just turns green but no action is being made. 

For any other skill like mining, if i click on an area to mine the box visually "clicks" but then it doent start mining. Only thing I can do is collect a replant herbs for farming. 

### Reproduction Steps

Don't know how to reproduce

### Expected behaviour

I should be able to start and stop any skill I have unlocked. 

### Screenshots

https://user-images.githubusercontent.com/106605840/171198031-ba323d11-da48-4259-9340-644582289967.mp4

https://user-images.githubusercontent.com/106605840/171198075-5add8617-e518-45e2-9a43-1486ecbbba2b.mp4

### Console output

Failed to load resource: the server responded with a status of 404 ()
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
css:1          Failed to load resource: the server responded with a status of 403 ()
cloud.js?1969:67 Connected to PlayFab successfully
cloud.js?1969:187 updatePlayerTags
save.js?1969:10 Removed old local storage keys.
save.js?1969:77 set force reload to 2
combatManager.js?1969:1 Combat Manager Built...
raidManager.js?1969:1 Golbin Raid Manager Built...
save.js?1969:10 Removed old local storage keys.
save.js?1969:20 Loading Save Game...
save.js?1969:20 Save Game Loaded...
main.js?1969:6 Game Loaded
cloud.js?1969:67 Connected to PlayFab successfully
cloud.js?1969:187 updatePlayerTags
css:1          Failed to load resource: the server responded with a status of 403 ()
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloud.js?1969:11 Synchronising with Cloud
style.css:1          Failed to load resource: the server responded with a status of 404 ()
css:1          Failed to load resource: the server responded with a status of 403 ()
DevTools failed to load source map: Could not load content for chrome-extension://hnfanknocfeofbddgcijnmhnfnkdnaad/content.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for https://melvoridle.com/requestProvider.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1969

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Hey! Can you please provide me with your save? I will need to manually fix this for you.

2 Questions:
1) What was the last skill you were training before this occurred?
2) Was the last time you played prior to last week's update, or have you been playing consistently for the last week?

**Comment by SuperSquib** [comment]
Hi, Save is attached.
What was the last skill you were training before this occurred?
- I had just started Thieving
Was the last time you played prior to last week's update, or have you been playing consistently for the last week?
- I have been playing pretty consistently
[melvoridlesave_SquibOnAnAdventure_5-31-2022_94626PM.txt](https://github.com/MelvorIdle/melvoridle.github.io/files/8810416/melvoridlesave_SquibOnAnAdventure_5-31-2022_94626PM.txt)

**Comment by dkelly126** [comment]
> ### This exact bug is happening to me

**Comment by Wazzule** [comment]
Same here, the action turns green but nothing happens. I’m using iOS app

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
