### ISSUE TITLE
[Bug]: Chance-to-hit stat incorrect with Occult+Wolf synergy

### ISSUE THREAD

**Issue by Mephalich** [MelvorIdle/melvoridle.github.io#2474]
### Describe the bug

It appears Occultist+Wolf synergy is bugged towards the chance-to-hit calculations. 

### Reproduction Steps

1. Wear the Wolf and Occultist and have their synergy active.
2. Now in a battle (when health is full) switch between Stab/Block/Stab/Block several times
3. Each switch of attack type will increase chance to hit  indefinitely for an active fight. (haven't tried with magic or archery)

Doesn't work when health isn't full so it appears some miscalculations of the triple familiar bonus.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1969

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Thanks, can confirm this is reproducible. The enemy evasion modifier seems to stack infinitely causing their evasions to go negative, hence the super high chance to hit.

Will look into applying a fix

**Comment by MelvorIdle** [comment]
A fix has now been applied to the game. Feel free to create a new issue if you run into similar bugs.
