### ISSUE TITLE
[Bug]: Missing item (cooking gloves)

### ISSUE THREAD

**Issue by Meuschke23** [MelvorIdle/melvoridle.github.io#2475]
### Describe the bug

Hello Melvor-Idle Team,
I have the problem that my cooking gloves have disappeared. The cause is unclear. However, I have purchased them in large quantities, but they do not show up in my inventory. They are also not equipable in the quick menu. Did I miss something?

if it helps, i am using the SEMI-Plugin (v0.11.1)

Best regards
Meuschke

### Save Link

https://melvoridle.com/save/B1SlNhNn

### Screenshots

![Kochhandschuhe01](https://user-images.githubusercontent.com/65863113/171334331-0a2594fc-34ea-4fb6-afa4-82fd7adca673.png)

![Kochhandschuhe02](https://user-images.githubusercontent.com/65863113/171334343-20712543-b766-4b95-a832-953d868b4d72.png)

![Kochhandschuhe03](https://user-images.githubusercontent.com/65863113/171334357-2e1de7c2-b331-4142-a1e3-96ba40f31466.png)

![Kochhandschuhe04](https://user-images.githubusercontent.com/65863113/171334371-0ce074f9-102b-4b56-9d3a-4baf2b93dd53.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1970

### Are you using any scripts or extensions?

Yes

**Comment by 47Y** [comment]
I loaded your save and you currently have them equipped on your first equipment set.

**Comment by Meuschke23** [comment]
Sorry, my mistake. I was not looking for that. Thank you very much.
