### ISSUE TITLE
[Bug]: White Squares in Bank's Item info tabs.

### ISSUE THREAD

**Issue by ShinyMooTank** [MelvorIdle/melvoridle.github.io#2477]
### Describe the bug

The white box at the bottom of the item info boxes.

### Reproduction Steps

Android App
1. Go to Bank
2. Select an item
3. Info box about that item shows up
4. Click on the tabs that are inside the item info box and you'll see all the white boxes at the bottom of the screen.

### Expected behaviour

No white box. Make Item info box smaller depending on what's in the box so White box doesn't show up?

### Save Link

https://melvoridle.com/save/M90vPR8p

### Screenshots

![Capture1](https://user-images.githubusercontent.com/89095107/171416425-c205e22f-db6f-4a35-a9a4-09e1544c8b87.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1970

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Thanks for the report. A hot fix has been applied to the game :)
