### ISSUE TITLE
[Bug]: Values not auto-updating

### ISSUE THREAD

**Issue by jdeanunity** [MelvorIdle/melvoridle.github.io#2479]
### Describe the bug

Values for the bank tabs are not auto-updating. Ie; Total tab value of 48m, Sell half of a stack of items for 24m, tab still says 48m until you switch tabs.

### Reproduction Steps

1. Go to bank tab, 2. Sell half stack or full stack of items, 3. Watch value of tab remain the same

### Expected behaviour

Tab value remains the same after sale until you switch tabs

### Save Link

https://melvoridle.com/save/xAUqSVh1

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1971

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Thanks for the report. A hot fix has been applied to the game :)
