### ISSUE TITLE
[Bug]: manual eat will reset attack to "normal attack", not a "Special Attack"

### ISSUE THREAD

**Issue by proy27** [MelvorIdle/melvoridle.github.io#2482]
### Describe the bug

manual eat will reset attack to "normal attack", not a "Special Attack"

### Reproduction Steps

1. equip Cloudburst Staff (Special Attack: 100% chance for Magic Ray)
2. use "Magic Ray" attack monster
3. manual eat
4. Special Attack will reset to "normal attack"

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1978

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
