### ISSUE TITLE
[Bug]: Cannot stop the game by steam

### ISSUE THREAD

**Issue by kourindoupota** [MelvorIdle/melvoridle.github.io#2484]
### Describe the bug

When I close the game window, I found that the status of the game in my steam still says it is running but I can't find any game process.

### Reproduction Steps

Just close the game window by clicking the top right button

### Expected behaviour

Close and show the status in Steam properly

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1978

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Question - Do you open the Wiki or other external link from the steam version, which then opens your web browser?

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
