### ISSUE TITLE
[Bug]: Auto eating potatoes with AE1 in Arid Plains heals for 0

### ISSUE THREAD

**Issue by xanderput** [MelvorIdle/melvoridle.github.io#2485]
### Describe the bug

With AE1, your whole potato stack gets consumed when auto eating in arid plains. 

This bug was seen before in #2062, however it should have been fixed back then. 

### Reproduction Steps

1. Buy Auto Eat 1
2. Equip potatoes and Desert Hat
3. Fight something in Arid Plains
4. Wait for Auto Eat to trigger
5. Notice that your whole stack of potatoes vanishes

### Expected behaviour

I would expect food to heal for at least 1 health, even when your food efficiency is terribly low.

### Screenshots

![image](https://user-images.githubusercontent.com/39944140/172040003-e46c9f3f-d66d-4cd7-ada2-fcebcfcfaa37.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1978

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
