### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by Lebyyy** [MelvorIdle/melvoridle.github.io#2486]
### Describe the bug

Hey :) 

My problem is that i can not start any skill or fights. If i click any skills… nothing..
I readed some similar issues from other players.
It started yesterday and the Last skill i did was crafting some Black D-hide Body. 
I can still equip items and sell items but thats it.

I hope u can help me with it.
Thank you very much and keep up the good work.
<3

### Save Link

https://melvoridle.com/save/6OfepE16

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1978

### Are you using any scripts or extensions?

No

**Comment by xanderput** [comment]
Here's a fixed save for you: https://melvoridle.com/save/UDZZwFfa
Probably want to keep open the issue so the devs can look into the problem though.

**Comment by Lebyyy** [comment]
Idk why but it still not working

**Comment by MelvorIdle** [comment]
> Idk why but it still not working

The save provided by @xanderput works for me. Try importing it again.

Leaving this issue open to keep track of this bug

**Comment by Lebyyy** [comment]
Well i have no clue what went wrong but it now it works.
Thanks for the help @xanderput 👍
