### ISSUE TITLE
[Bug]: Incorrect drops in looting box after afk slayer

### ISSUE THREAD

**Issue by authvin** [MelvorIdle/melvoridle.github.io#2487]
### Describe the bug

When returning from offline auto-slayer, the drops from the current foe are prioritized over those from the first monster fought.

In the attached screenshot, loot from the Red Dragon is prioritized over loot from Necromancer, despite the Necromancers being fought before the Red Dragons.

I've had this problem occur many times, with two or more monster types. I've also observed it back in 1.0.3.

### Reproduction Steps

1. Start slayer with "Automatically fight new slayer task" enabled
2. Close the game, then reopen after the task is complete
3. The drops from the current slayer monster will be prioritized over the drops from the first monster fought

### Expected behaviour

I'd expect for drops to appear in the loot box in the order that the slayer monsters were encountered.

### Save Link

https://melvoridle.com/save/60tuabgg

### Screenshots

![Screenshot_20220606-144516__01](https://user-images.githubusercontent.com/37563355/172163933-e37655cf-e99e-4a85-a563-aa93b52b4703.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1978

### Are you using any scripts or extensions?

No

**Comment by xanderput** [comment]
When the loot container is full, new loot displaces old loot.
So in this case at first the loot container had loot from necromancers, then that loot started being pushed out to make space for the loot from the red dragons.

**Comment by authvin** [comment]
Ah, that makes more sense. I'd love to get opposite behaviour as an option or something, but if it's intended then that's fine :) I probably conflated the "but your lootbox was full" message with the similar message for when the bank is full
