### ISSUE TITLE
[Bug]: <"skill-footer-minibar" hidden behind Save button>

### ISSUE THREAD

**Issue by ShinyMooTank** [MelvorIdle/melvoridle.github.io#2489]
### Describe the bug

The skill-footer-minibar is hidden behind the force save button while the phone is in landscape position.

### Reproduction Steps

1. Launch Android App
2. Rotate phone in landscape position
3. Go to a skill like woodcutting
4. Open skill-footer-minibar on the bottom right side of the screen
5. Then you'll see the buttons like Multi Tree hidden behind the force save button like the photo I attached.

### Expected behaviour

Skill Mini bar should have priority being on top of force save button.

### Screenshots

![Screenshot_20220608-073145~3](https://user-images.githubusercontent.com/89095107/172624591-11719e2e-c9c8-41ea-8496-308427b84fe5.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1983

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
