### ISSUE TITLE
[Bug]: Astrology reroll cost does not update when changing

### ISSUE THREAD

**Issue by wzurborg** [MelvorIdle/melvoridle.github.io#2490]
### Describe the bug

- When you reach the 95% mastery pool checkpoint in Astrology, your reroll cost is halved from 30 to 15 stardust. 
- When you spend mastery pool xp and get below 95% the reroll cost is reset to 30.

In both cases the cost indication on the reroll page is not updated and still shows the old value. You have to reload the page to see the correct reroll cost.

### Reproduction Steps

1. While you are below the 95% checkpoint in Astrology, select any constellation and see the reroll cost being 30 stardust.
2. Train Astrology or spend mastery pool tokens until you get above 95% mastery pool.
3. The reroll cost still displays 30 stardust, but 15 are actually charged.
4. Reload the page to see the cost update.
5. Spend mastery pool xp until you get below 95%.
6. The reroll cost still displays 15 stardust but 30 are actually charged.
8. Reload the page to see the cost update.

### Expected behaviour

The reroll cost is updated without having to reload.

### Screenshots

![grafik](https://user-images.githubusercontent.com/1320950/173013484-efa89ec4-83d5-4865-b4c6-1d56b2bd9da7.png)
![grafik](https://user-images.githubusercontent.com/1320950/173010732-79c4b1d6-23b4-4840-b880-ac125d8d885b.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1983

### Are you using any scripts or extensions?

Yes

**Comment by MelvorIdle** [comment]
No longer relevant with the new Astrology rework.
