### ISSUE TITLE
[Bug]: Fletching stops after offline for a while

### ISSUE THREAD

**Issue by Sullivin123** [MelvorIdle/melvoridle.github.io#2492]
### Describe the bug

*This is on the phone version* When coming back to the game after being offline for a extended period of time the game will stop fletching the second you load in to your save. This doesn't happen if you just leave the app for a few minutes. Even closing the app fully and reopening 
as long as it was only a few minutes doesn't cause this to happen.
Note this was specifically fletching arrows.

### Save Link

https://melvoridle.com/save/xcmtxkDo

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1983

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Question - are you sure the skill isn't stopping because your bank was full or you ran out of materials to produce arrows?

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
