### ISSUE TITLE
[Bug]: cooked food does not go to stockpile when empty & bank full.

### ISSUE THREAD

**Issue by Arkannax** [MelvorIdle/melvoridle.github.io#2493]
### Describe the bug

I cooked Sharks for two hours offline (Mon Jun 13 around 5pm EST) .
I was unaware my bank was full for the sharks - (I was rushing out the door and threw it on cooking vs. Combat)
My passive foods all went to their respective stockpiles, but the sharks did not.

It said
“We tried to give you 19xx sharks but your bank was full!”
Followed by my successful passive cooks.

Maybe it’s not a bug, but I feel that if it is not - it shouldn’t appear under the active cooking items maybe too. 

Seeing my loot was full I immediately crossed my fingers on the stockpile. 

I’m unable to see my version when I report the bug in game or get the save link on mobile app - ipad model A1893.

I will update the version. :) 

### Reproduction Steps

1. Fill your bank to max contents. (119/119)
2. Cook actively AND passively - ensure stockpiles empty.
3. Go offline.
4. Receive returning notification that your bank was too full for <cooked food> .
5. Actively cooked food will not be in stockpile.

### Expected behaviour

I expected my cooked food to go to my empty stockpile if there was not room in my bank.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?????

### Are you using any scripts or extensions?

No

**Comment by Arkannax** [comment]
Game subversion (?1983) 
Version above is correct.

**Comment by MelvorIdle** [comment]
This is the intended behaviour of active cooking. If your bank is not full, then the items will not produce. The stockpile isn't a failsafe for a full bank, it is only made available to passive cooking.
