### ISSUE TITLE
[Bug]: Need upgrade option other than Steam

### ISSUE THREAD

**Issue by jarob323** [MelvorIdle/melvoridle.github.io#2494]
### Describe the bug

While Steam is fine for many people and is a nice game hub, confining your sales to Steam limits your customer base.
Steam states that it would do automatic upgrades to its software on this computer.  I cannot have automatic upgrades done on this computer, of anything.  Please allow your upgrade package to be purchased directly via PayPal, not through Steam.  Charge more if you like.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1983

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
There's a few options for you to purchase the game.

1) Buy on Steam. If you link your Melvor Cloud account then you can access the full game on Browser or mobile without needing to open Steam anymore
2) Buy on Mobile. Same as above, linking your Melvor Cloud account unlocks the full version on browser but not Steam.

We currently have no plans to provide a purchase option via Browser.
