### ISSUE TITLE
[Bug]: <title>Actively cooking crabs does not produce cooked crab.

### ISSUE THREAD

**Issue by Cyndaquilrockz** [MelvorIdle/melvoridle.github.io#2496]
### Describe the bug

When attempting to cook crabs actively, cooked crabs will not appear in the bank nor in a stockpile. However, passively cooking crabs does produce cooked crab. My best guess as to why this is occurring is my chance to preserve resources is -10%, assuming that could cause such as issue like this.

### Reproduction Steps

1. Simply attempt to cook crabs actively.

### Save Link

https://melvoridle.com/save/YwIBdH9Q

### Screenshots

I do not have any recording software, but as you can see I have one cooked crab in my inventory before and after a crab was actively cooked. Crabs can be passively cooked still, and properly move to the stockpile and to the bank once collected.
![melvor screenshot](https://user-images.githubusercontent.com/107698569/174319623-b70d08f7-c1d4-4fad-8ab7-3321ebabce4a.PNG)
![melvor screenshot 2](https://user-images.githubusercontent.com/107698569/174319634-898fe2ba-231b-46b1-804e-5960a4693c83.PNG)
![image](https://user-images.githubusercontent.com/107698569/174320048-e5c2cee1-a186-4300-a4f1-cbf223606c9d.png)
![image](https://user-images.githubusercontent.com/107698569/174320273-6897d94f-5c83-420a-9077-f4eda25746e1.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1983

### Are you using any scripts or extensions?

No

**Comment by xanderput** [comment]
Did you buy cooking upgrade 1?

![image](https://user-images.githubusercontent.com/39944140/174333817-ace114d2-b608-4e0b-ad67-e48ba204ae8b.png)

**Comment by xanderput** [comment]
Ah, just noticed you attached a save. Looks like you did buy the upgrade. Your actively cooked crabs have been getting auto equipped.

![image](https://user-images.githubusercontent.com/39944140/174334187-0a741381-3821-4ebd-8c22-eef33626b60d.png)

**Comment by Cyndaquilrockz** [comment]
> Did you buy cooking upgrade 1?
> 
> ![image](https://user-images.githubusercontent.com/39944140/174333817-ace114d2-b608-4e0b-ad67-e48ba204ae8b.png)

I did, and as it turns out, I had crabs equipped as a food item. Thank you for pointing it out.
