### ISSUE TITLE
[Bug]: skills wont start

### ISSUE THREAD

**Issue by dkelly126** [MelvorIdle/melvoridle.github.io#2497]
### Describe the bug

Any skill won't activate or combat

### Reproduction Steps

It is continuing to be a problem 

### Expected behaviour

My expectation was use a skill and it produces a product and exp

### Save Link

https://melvoridle.com/save/GCaUkcPd

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1983

### Are you using any scripts or extensions?

No

**Comment by xanderput** [comment]
Fixed it by running `game.activeSkill = ActiveSkills.NONE`. 
Fixed save: [https://melvoridle.com/save/QCmejffz](https://melvoridle.com/save/QCmejffz) 

Please don't close the issue though, so it can actually get a proper fix in the future.

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
