### ISSUE TITLE
[Bug]: Smithing Gloves +60% Bonus not given

### ISSUE THREAD

**Issue by MoonpixelCreative** [MelvorIdle/melvoridle.github.io#2499]
### Describe the bug

**Smithing Gloves +60% Bonus** not given I have over 2000 charges on my Smithing gloves

- I am recieving the 84 XP (Runite Bar level 91) only and not the additional +60% (60% of 84XP is approx 50)
- I should be getting 84+50 XP (134XP), but i am not

Thanks :-)

![2022-06-22_16-12-07 (4)](https://user-images.githubusercontent.com/89892250/174956223-45ae8ab9-09fb-4985-9c87-5719e378e55b.png)
![2022-06-22_16-12-07 (3)](https://user-images.githubusercontent.com/89892250/174956258-f015ce9c-7b86-4eac-b633-01832ced6033.png)
S

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1984

### Are you using any scripts or extensions?

No

**Comment by Silverfyree** [comment]
That 84 xp already includes the 60% buff from smithing gloves, at a base the bar gives 50 exp per action.

**Comment by MoonpixelCreative** [comment]
Yes, I just realsied this - LOL by taking off my gloves :-)
