### ISSUE TITLE
Divine Potion unnecessarily consuming charges

### ISSUE THREAD

**Issue by DevWizaad** [MelvorIdle/melvoridle.github.io#250]
**Expected behavior**
A Divine Potion only consumes charges when Prayer Points are consumed, as per the description of the potion:
"X% Chance to not consume Prayer Points".

**Describe the bug**
There are a few cases where Divine Potions unexpectedly use up charges, even though no Prayer Points are being consumed:
- When Activating/Deactivating any Prayer, in and out of battle.
- When the enemy attacks, and only offensive Prayers are active.
- When the player attacks, and only defensive Prayers are active.
- When two Prayers are active, two potion charges are always consumed.
  - This may be intended behavior for correct uses (e.g. two offensive Prayers active when player attacks).

**Comment by coolrox95** [comment]
Small update on this bug, but it seems like a potion charge is consumed every single time `updatePrayerPoints` is called, except when `bury = false`.

As a result you also lose a potion charge:
- When loading the game.
- When gaining prayer points from the Bone Necklace

To fix this, an additional check for `qty > 0` should be added to the potion charge check in `updatePrayerPoints`.

**Comment by MelvorIdle** [comment]
Fixed hopefully
