### ISSUE TITLE
[Bug]: Golbins in golbin raid attack before they spawn

### ISSUE THREAD

**Issue by icedtrumpets** [MelvorIdle/melvoridle.github.io#2500]
### Describe the bug

Golbins in the golbin raid can sometimes spawn and kill you impossibly fast, skipping the respawn timer and attack timer. Immediately after selecting rewards from a wave, you will die. I believe this is due to respawn timers not being discarded properly in between waves.

Note: this may be observable on lower waves, but occurs very frequently at high waves. (i.e. raid modifiers have left the player with 10hp and golbins have .25s attack speed)

### Reproduction Steps

1. Create a simple script to press the Enter button every 100ms.
2. With a large amount of golbin raid coins, begin skipping through waves on Hard mode.
3. Activate the script so it will skip the waves for you (Mashing enter will select a weapon as a reward, choose the first weapon, then skip the next wave)
4. Observe as you occasionally take damage/die from golbins

### Expected behaviour

When pressing the Enter button every 100ms, golbins should not spawn because the Skip Wave button should activate before they have a chance.

Their respawn timer is 1s, and their attack timer is 250ms. So the minimum time between collecting rewards and receiving an attack should be 1250ms. I believe the respawn and attack timers are shared and not being discarded, so a golbin may respawn with a previous golbin's timer, or a golbin from last wave is still alive and attacking.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1984

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
