### ISSUE TITLE
[Bug]: <Golbin Raind>

### ISSUE THREAD

**Issue by wuleiwa** [MelvorIdle/melvoridle.github.io#2502]
### Describe the bug

If choose blood  sucking for Golbin In Golbin Raind,It would cause me to be unable to kill the goblins when my attack speed is the same as the opponent's, until the golbin attack missing.

### Expected behaviour

Solve this error,make me could kill goblin smoothly.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [x] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1984

### Are you using any scripts or extensions?

No

**Comment by xanderput** [comment]
The negative modifiers are supposed to make the golbins stronger and harder to kill. 
You can always play easy mode if you don't like golbins getting stronger through modifiers though, or just avoid giving them lifesteal next time.
