### ISSUE TITLE
[Bug]: Incorrect item order (sorting)

### ISSUE THREAD

**Issue by NototoHoshi** [MelvorIdle/melvoridle.github.io#2503]
### Describe the bug

Maybe its expected behavior and has to do with item IDs, but few items are sorted very weirdly.

Bows:
bows are currently sorted: all (u) shortbows, (u) normal longbow, (u) oak longbow, all strung shortbows, strung normal longbow, then rest of (u) longbows (from willow to redwood), then rest of strung longbows (from oak to redwood)

so it seems that the (u) normal and oak longbows, plus the strung normal longbow are out of place.

Gear:
(S) iron helmet is sorted incorrectly in between (S) bronze shield and (G) bronze helmet, instead of being sorted alongside other (S) iron items

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1984

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
