### ISSUE TITLE
[Bug]: use combination runes doesn't work on Item Alchemy or * offering

### ISSUE THREAD

**Issue by willb611** [MelvorIdle/melvoridle.github.io#2504]
### Describe the bug

When you try to do any "item alchemy" (or "Bone offering"  or "Blessed Offering") spell with "use combination runes" selected, it doesn't let you use combination runes in place of fire runes.

### Reproduction Steps

1. Go to "Alt. magic skill" 
2. Have a large number of lava (earth and fire combination) runes and nature in the bank
3. Select any "Item Alchemy" e.g. Item Alchemy 1 and select any item to alchemy (or try bone or blessed offering)
4. Ensure "use combination runes is expected"
5. Cannot cast the spell as expected (should be able to use lava runes)

### Expected behaviour

Should be able to use lava combination runes for Blessed/Bone offering or any of the Alchemy spells

### Screenshots

![2022 06 26-glitch-bank-tab-lava-runes](https://user-images.githubusercontent.com/6118055/175822515-0b0bb557-8851-45cf-9bea-adc69e933ed9.JPG)
![2022 06 26-glitch-blessed-offering](https://user-images.githubusercontent.com/6118055/175822516-c362788e-89cc-482f-9f93-95eadb81f6bd.JPG)
![2022 06 26-glitch-item-alchemy-1](https://user-images.githubusercontent.com/6118055/175822517-30b0e939-5e1e-4d0e-8e98-da41eda111ef.JPG)
![2022 06 26-glitch-item-alchemy-2](https://user-images.githubusercontent.com/6118055/175822518-13e8d1df-326c-4c62-acec-2a8ae8f026d9.JPG)
![2022 06 26-glitch-item-alchemy-3](https://user-images.githubusercontent.com/6118055/175822519-2371e3a2-6a34-4776-95fe-65b1373f788f.JPG)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1984

### Are you using any scripts or extensions?

No

**Comment by Zero-DotV** [comment]
I think that Lava runes only work for spells that require both fire AND earth runes, not just one. That behavior is exclusive to RuneScape.
