### ISSUE TITLE
Goblin Raid Item Bug

### ISSUE THREAD

**Issue by IRONN1C** [MelvorIdle/melvoridle.github.io#2505]
### Describe the bug

Dragon helmet give slapping skill instead of firebreathing in goblin raid.

### Reproduction Steps

use the dragon helmet

### Expected behaviour

should give the skill fire breathing

### Screenshots

![goblin raid](https://user-images.githubusercontent.com/98619367/175843675-4e27f500-90c4-4a28-9293-1941788b2fe8.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

1984

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
