### ISSUE TITLE
[Bug]: <title>Signet ring half(b) not acquiring

### ISSUE THREAD

**Issue by Linearslide** [MelvorIdle/melvoridle.github.io#2506]
### Describe the bug

I have not once acquired the signet ring half(b) but have lost it 17 times on just 1 account and I have up to 450 space in my bank with roughly 210 being used and this has been like this for months now.

### Expected behaviour

I expect that it gets fixed so I can actually acquire the item instead game saying I lost it. Also like a composition of atleast 1 signet ring half(b) so I can finally acquire the full ring to have and possibly use.

### Screenshots

![Screenshot_20220627-130506_Melvor Idle](https://user-images.githubusercontent.com/108293146/175996573-f12f8d29-1618-4b76-9af2-2103959b3c98.jpg)
![Screenshot_20220627-130514_Melvor Idle](https://user-images.githubusercontent.com/108293146/175996581-f0d3305a-ecd6-4496-9cc6-340778440c30.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1984

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
The Gold topaz ring is required to be equipped in order to receive it. You have already received the drop 17 times, but missed the item because the Gold Topaz ring was not equipped.
