### ISSUE TITLE
[Bug]: <title> combat ui seizing up

### ISSUE THREAD

**Issue by Mekina25** [MelvorIdle/melvoridle.github.io#2507]
### Describe the bug

Hello. Let me start by saying i love the game so much. One of the best i've played in a long time. Im having issues with combat ever since i got my new phone a couple days ago. It's a samsung galaxy s21 fe 5g. When I try to fight monsters. Every time the monster dies, the combat ui starts freaking out and resizing (i dont know what to call it) but after death. The ui will scale up and down about 10 times before the monster respawns. Itll be hard to show in pictires. But it will like flicker between ui scaling a few times. But if i tab out to say my bank while im grinding. Theres no problem at all. Its only in the combat window. 

### Reproduction Steps

Open combat tab
Fight monster
Monster dies
Ui flickers

### Expected behaviour

The ui to atay the same size. No resize 10 times when monsters are dead

### Save Link

https://melvoridle.com/save/7bdUumzI

### Screenshots

Its hard to take good pictures on phone. To show whats happening

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

1984

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
