### ISSUE TITLE
[Bug]: Sale value displays non whole numbers

### ISSUE THREAD

**Issue by Silberdrachi** [MelvorIdle/melvoridle.github.io#2508]
### Describe the bug

Selling items from the bank can produce non whole numbers when modifiers impact sales value.

### Reproduction Steps

1. Open bank
2. Find item to sell that has a sale modifier (Logs have sales modifiers from WC mastery checkpoint 50%)
3. Observe its possible to have non whole numbers on sales

### Expected behaviour

All GP values are in whole numbers, fractional GP values do not exist

### Save Link

https://melvoridle.com/save/xVeDHchC

### Screenshots

![image](https://user-images.githubusercontent.com/76179203/176535527-343fe4ac-4d00-46b6-9262-289091ca5ae2.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1984

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
