### ISSUE TITLE
[Bug]: Destroy Loot button visible in Golbin Raid

### ISSUE THREAD

**Issue by Silberdrachi** [MelvorIdle/melvoridle.github.io#2509]
### Describe the bug

Destroy Loot button viable in Golbin Raid

### Reproduction Steps

1. Open golbin raid
2. Observe under enemy window the destroy loot button is visible 

### Expected behaviour

Button does not show because there is no loot container and no loot to obtain

### Screenshots

![image](https://user-images.githubusercontent.com/76179203/176535799-82ff3f9b-8a32-4828-a5fd-538697d0d564.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1984

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
