### ISSUE TITLE
[Bug]: Replacing 2h Weapon with offhand weapon in Golbin Raid results in melee fists

### ISSUE THREAD

**Issue by Silberdrachi** [MelvorIdle/melvoridle.github.io#2510]
### Describe the bug

if you replace a 2h Weapon with an offhand Weapon it doesn't give you a bronze/addy scim

### Reproduction Steps

1. Start golbin raid
2. Receive 2h weapon (2h sword, bow, staff)
3. Replace 2h weapon with offhand (shield, book)
4. Observe weapon is removed and no new items provided

### Expected behaviour

Player shouldnt be without a weapon, If an item is made invalid by player choices or by choosing an offhand, they should be provided with their starting weapon (bronze or addy scim)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1984

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
