### ISSUE TITLE
[Bug]: Exiting Golbin Raid and rejoining will remove current player raid coin amount

### ISSUE THREAD

**Issue by Silberdrachi** [MelvorIdle/melvoridle.github.io#2511]
### Describe the bug

Exiting (not pausing) golbin raid and rejoining will remove the current amount of raid coins a player has from the skip wave model. If the player pauses and rejoins after this state is achieved it will still not display coins. Exiting the raid and starting a new raid will show the player coin amount. Pausing the raid and then exiting the game, and then rejoining the raid will work as intended.

### Reproduction Steps

1. Start golbin raid
2. Close window
3. Open window agian
4. Log in as player
5. Observe that the coin dialog has been removed

### Expected behaviour

Raid coin quantity should always display

### Save Link

https://melvoridle.com/save/PDyd3sJI

### Screenshots

Expected:
![image](https://user-images.githubusercontent.com/76179203/176537188-58230790-2fe2-4b51-ac34-de9a05ca98ef.png)

Actual:
![image](https://user-images.githubusercontent.com/76179203/176537258-41ecf686-2775-44f1-a6ae-5b924c976d51.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1984

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
