### ISSUE TITLE
[Bug]: Bottom Right hand menu shows items not yet unlocked

### ISSUE THREAD

**Issue by TheComet-zz** [MelvorIdle/melvoridle.github.io#2512]
### Describe the bug

When the game is set to open the skill last being trained, when the iOS app is fully closed, then reopened, on login to a combat skill, all objects that can appear in the menu are present even if not yet obtained.
I can’t remember if this also happens for non-combat skills as well.

Unsure if this is an iOS app only issue, or if this appears for browsers, and the android app as well.

### Reproduction Steps

1. In settings, change default skill page to be the currently trained skill.
2. Start training a combat skill
3. Fully close app
4. Re-open app, and login
5. Observe bottom right hand menu being open with all objects in it

### Expected behaviour

I’d expect for the menu to either be absent if the menu shouldn’t contain any items, or to only be populated with items that are unlocked, and should show up for the currently trained skill

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1984

### Are you using any scripts or extensions?

No

**Comment by TheComet-zz** [comment]
![0DFEE7C9-8B09-4EBF-869B-8E09FA4FD098](https://user-images.githubusercontent.com/3326235/176988841-f7975c55-8e29-4cb6-a26a-e40ffe62c299.png)
Attached image of issue

**Comment by MelvorIdle** [comment]
Fixed as of v1.1. Please open a new report if issue persists.
