### ISSUE TITLE
[Bug]: Garden success ratio no more calculated before sowing seeds

### ISSUE THREAD

**Issue by OlivierMary** [MelvorIdle/melvoridle.github.io#2514]
### Describe the bug

Since last version the success ratio off garden is no more calculated with compost before sowing seeds.

it's on v1.0.5 this version isnt in selection box.

### Reproduction Steps

go to garden, check ratio before seed without compost, then sowing seeds, ratio is not the same.

100% success before sowing, 50% after sowing with 0 compost.

![image](https://user-images.githubusercontent.com/4348675/177271854-caf6af46-7b7e-4d19-a7b9-a4c2398ac369.png)
![image](https://user-images.githubusercontent.com/4348675/177271955-8e04d31b-23c8-4d80-a899-c645e7e8aad6.png)
![image](https://user-images.githubusercontent.com/4348675/177271990-ebea78d9-3fb6-4b6f-a7ad-d9538991cbc2.png)

### Expected behaviour

success ratio of garden great before sowing seeds, not after.

### Save Link

https://melvoridle.com/save/GXnLw4eI

### Screenshots

already done

### Console output

nothing when sowing.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

v1.0.5 ?2074

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
