### ISSUE TITLE
[Bug]: <title>Firemaking's new XP gain display does not correspond with the actual gain

### ISSUE THREAD

**Issue by JackoBannon** [MelvorIdle/melvoridle.github.io#2515]
### Describe the bug

Earlier today, the xp gain display was added for FM, which is a much welcomed update for me. However, have noticed that the new display of skill/mastery/mastery pool xp gain is not in correspondence with the actual gain as can be seen from the following pic:

![3](https://user-images.githubusercontent.com/108735735/177328860-1d8aa229-2a9a-46b2-a4f1-0233fbe5b9a9.png)

![4](https://user-images.githubusercontent.com/108735735/177328882-53bd4f37-e2b4-47f5-ad18-5a27c4b7a968.png)

These two pictures are consecutive two ticks of redlog firemaking process, calculating the difference of the top xp gain bar, I got 423 skill xp and 61 master pool xp, however on the new display screeen it shows 291 and 74 respectively. 

I have tried firemaking with maple, magic and redwood on two accounts and on both IPad and PC Steam, the bug persists, I think there might be a bug in the statistic mechanics.

PS. I experienced this problem on V1.0.5, but there is not such option, so I selected V1.0.4 in order for the post to go thru, and manually edited it to V1.0.5 another minor bug there :)

### Reproduction Steps

1. Go to Firemaking
2. Select log
3. Burn

### Save Link

https://melvoridle.com/save/Xg9wxLBx

### Screenshots

see above

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2074

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Fixed as of v1.1. Please open a new report if issue persists.
