### ISSUE TITLE
[Bug]: Unable to load cloud save from mobile to pc

### ISSUE THREAD

**Issue by icepanda07** [MelvorIdle/melvoridle.github.io#2516]
### Describe the bug

i play both on mobile and pc (steam). past 3 days i consistently changing between pc  at home and mobile while working for quick update using cloud save. just today i cant have my cloud save loaded in pc. i have make sure force save in cloud mobile version, when i open in pc version, i carefully choose the cloud save to load, and i can see the cloud save progress. however when it loaded, it choose local save in my pc instead of cloud save. all did this step few times. i pretty sure all my steps are correct and dont have problem past 3 days doing this. just recently it happen. it is known bug or something? anyone know how to fix this?

internet connection is good for both my mobile and pc.  not sure which problem causing this ethier from mobile version cloud save, or pc cloud save. but it clearly show my progression in cloud save when i try to open from pc.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

2074

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
