### ISSUE TITLE
[Bug]: Silver Sapphire Ring wrong description

### ISSUE THREAD

**Issue by NototoHoshi** [MelvorIdle/melvoridle.github.io#2517]
### Describe the bug

The Silver Sapphire description says +6 Melee Defence bonus and +12 Block Attack Bonus, but when you go to "View Item Stats", it is actually the opposite (+12 Melee Def, +6 Block Attack)

PS: Its in version 1.0.5, but this GitHub form isnt updated, and wont let me select above 1.0.4

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?2074

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Fixed as of v1.1. Please open a new report if issue persists.
