### ISSUE TITLE
Seeing Gold potion not working Offline

### ISSUE THREAD

**Issue by Rtickle** [MelvorIdle/melvoridle.github.io#252]
**Describe the bug**
Seeing Gold Potions are not working offline. Can't be more precise than that.

**To Reproduce**
1. Go to Smithing
2. Click on Silver Bar and smith those, while having Seeing Gold Potion active.
3. Go offline, wait 5 minutes, go online and check your smithing outcome. 0 Gold bars, and 0 charges used.

**Expected behavior**
Seeing Gold Potions are not working offline. Can't be more precise than that.

**Browser**
Firefox and newest version of Melvor + Firefox Version

**Comment by tsakistan** [comment]
I was about to confirm this issue but then I noticed I was smithing Steel bars. After switching to silver, Seeing Gold potions seem to work fine for me. Are you sure this isn't what happened to you @Rtickle ?
