### ISSUE TITLE
[Bug]: Internal Suffering Speedrun, mining doesn't have Mastery XP Boost

### ISSUE THREAD

**Issue by SolairesWares** [MelvorIdle/melvoridle.github.io#2520]
### Describe the bug

Just as the title says, mining in the internal suffering Speedrun mode doesn't have the mastery XP boost. I'm currently getting 88 mithril mastery XP per ore and 22 mining mastery XP per ore. But in cooking I'm getting like 7000 lobster mastery XP and 1700 fishing mastery XP. I'm not sure if it broken in any other skills but I know it is for mining.

### Reproduction Steps

I guess it isn't a "bug" in that you can reproduce it, I believe it's just an update needed for this mode to have the proper XP boost you intended.

### Screenshots

![Screenshot_20220706-133402](https://user-images.githubusercontent.com/63682296/177628802-a507c614-808c-4482-b95e-04849e26b226.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2075

### Are you using any scripts or extensions?

No

**Comment by JosephTNev** [comment]
It also isn't correct for Fishing or Thieving.
