### ISSUE TITLE
[Bug]: actions stopped as soon as logging out. Granting no xp, using no items

### ISSUE THREAD

**Issue by baleaus** [MelvorIdle/melvoridle.github.io#2524]
### Describe the bug

Just closing the game like normal, going to sleep, returning to having nothing at all happen, even though i was offline for 7 hrs and had resources to continue the action for the whole time. Additionally, as soon as I log back in, it said I was absent for 7 hrs and 5 minutes, and continued the action it was supposed to be doing.

### Reproduction Steps

Close client, with an action happening, reopen x amount of time later. 

### Expected behaviour

A you have been gone screen, the action it’s supposed to be doing in the top, blank in all progress areas. (Screenshot of this is posted in the discord mobile bug area)

### Save Link

https://melvoridle.com/save/OWnU2jRv

### Screenshots

![4FC02962-F6BA-438F-9A1B-1ECC376AB692](https://user-images.githubusercontent.com/108922209/177939433-d9a9de28-37dc-446a-900d-711c72bcb37e.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2075

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
