### ISSUE TITLE
[Bug]: can’t equip potions

### ISSUE THREAD

**Issue by Kevhannon17** [MelvorIdle/melvoridle.github.io#2525]
### Describe the bug

I can’t equip my potions

### Reproduction Steps

Click on any potion. Options listed are upgrade or sell

### Expected behaviour

To be able to equip

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2075

### Are you using any scripts or extensions?

No

**Comment by Kevhannon17** [comment]
Save url is https://melvoridle.com/save/YHzksEIJ

**Comment by icedtrumpets** [comment]
Not a bug.
To equip potions:
1. Go to the page of the skill you want to use a potion on.
2. Click the potion icon in the top right of the screen

**Comment by jessycormier** [comment]
My apologies for the ping; I had to find this answer because I thought there was a bug as well. If I may suggest some kind of visual tip added to the potion icon and/or a boarder to describe how to use it?

I've been trying to "equip" the potion like I had done any other item/gear.
