### ISSUE TITLE
[Bug]: <title> no image in bank slot

### ISSUE THREAD

**Issue by Megaatom** [MelvorIdle/melvoridle.github.io#2526]
### Describe the bug

I have lots of different items that just don't show the image. So I have to click on the item to know what it is. Very annoying since I love the game. How can I solve this?

### Screenshots

![Screenshot_20220709-104603](https://user-images.githubusercontent.com/108989395/178111013-aa65d392-2f95-42c8-a9e6-093f46bfe8d0.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2075

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
