### ISSUE TITLE
[Bug]: <Item Completion Log> Gloves missing

### ISSUE THREAD

**Issue by Mykkala** [MelvorIdle/melvoridle.github.io#2527]
### Describe the bug

Both my Mining gloves and Gem gloves are missing , noted with a question mark, on my item completion log.  I have purchased both gloves a long time ago originally, but now that I'm finishing up my completion log i noticed they are showing missing on the log page.  I've repurchased the gloves /  charges, unequipped and reequipped them several time each, and they are still showing as a question mark..  I haven't sold them since I still have several charges attached to them and I don't know if that will fix the problem.   

### Reproduction Steps

1. Go to Completion Log
2. Click Item
3. See that there are question marks for both mining gloves and Gem gloves
4. Buy more gloves from shop
5. Go back to log
6. Items still show as question marks
![Screenshot 2022-07-09 185144](https://user-images.githubusercontent.com/109003928/178125098-dcc6d544-7819-416f-b242-1ffefa6be26e.png)
![Screenshot 2022-07-09 185247](https://user-images.githubusercontent.com/109003928/178125101-6a8748c5-cc9a-4896-a499-6e9c0d350ece.png)
.

### Expected behaviour

That I purchase the item from the store and it shows up in the completion log as completed.

### Save Link

https://melvoridle.com/save/skBhMhVf

### Screenshots

![Screenshot 2022-07-09 185144](https://user-images.githubusercontent.com/109003928/178125125-77ced88f-bdfd-4851-9316-94fa57ed7e52.png)
![Screenshot 2022-07-09 185247](https://user-images.githubusercontent.com/109003928/178125126-52562c46-5f1c-41e2-b23c-d47cc3d7a43a.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2075

### Are you using any scripts or extensions?

Yes

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
