### ISSUE TITLE
[Spelling/Grammar]: <title>

### ISSUE THREAD

**Issue by Plakman** [MelvorIdle/melvoridle.github.io#2531]
### What text is wrong?

![NVIDIA_Share_zVpFq3ksln](https://user-images.githubusercontent.com/55671128/178834272-1290d16d-46a0-47d2-9fbe-0bb6f58e2e3d.png)
Kill 1 golbin using magic

### What is the correct spelling or grammar?

Kill 1 Goblin using magic

**Comment by LillieSatou** [comment]
That text is correct.
