### ISSUE TITLE
[Bug]: Random Items Unequipped On Startup

### ISSUE THREAD

**Issue by katamaritaco** [MelvorIdle/melvoridle.github.io#2532]
### Describe the bug

Hello, first time poster here. I had an issue today that occurred on both mobile and PC (I regularly play my shared cloud save on both platforms).

I logged on today, and I had extra items in my bank (221/220), and I saw that a lot of my equipped items were no longer equipped. To be honest, I think most of them returned to my inventory, but I can't quite remember what I had in some of those slots, since I've been training other things.

Posting here in case others also encountered this.

### Reproduction Steps

1. Open the program via Android or PC client
2. Load typical shared cloud save
3. Observe that a seemingly random selection of items from all 4 equipment profiles are now unequipped and presumably returned to inventory.

### Expected behaviour

The items should remain equipped.

### Save Link

https://melvoridle.com/save/6Zh7qu6l

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2076

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
