### ISSUE TITLE
[Bug]: Mind Runes listed as unlocking at level 2 Runecrafting, but are available at level 1

### ISSUE THREAD

**Issue by elestora** [MelvorIdle/melvoridle.github.io#2534]
### Describe the bug

Mind Runes are listed in the Runecrafting milestones tab as being unlocked at level 2, but are available for runecrafting at level 1

### Reproduction Steps

1. Go to 'Runecrafting' with level 1 Runecrafting
2. See that Mind Runes are unlocked and available
3. Open milestones tab
4. See that Mind Runes are listed as unlocking at level 2

### Expected behaviour

Milestone tab and skill item availability should match

### Screenshots

![image](https://user-images.githubusercontent.com/68196988/179324269-e36b0bf4-b47b-4a5a-95b6-491490e20238.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2076

### Are you using any scripts or extensions?

Yes

**Comment by elestora** [comment]
In case it's relevant, I have the following mods installed via M3:

- SEMI v0.12.1
- Melvor ETA v0.11.4
- Melvor Idle - Automastery v3.1
- Combat Simulator Reloaded v1.6.10
- QuickShards v1.4.0
- Action Queue v1.2.4
- Show Modifiers v0.2.13

**Comment by MelvorIdle** [comment]
Fixed as of v1.1. Please open a new report if issue persists.
