### ISSUE TITLE
[Bug]: Bank quick-description popup doesn't work properly

### ISSUE THREAD

**Issue by Xemptuous** [MelvorIdle/melvoridle.github.io#2535]
### Describe the bug

Mobile.

When in the bank, you can tap-and-hold on an item to move it, or tap it for detailed info; however, when tapping-and-holding, a quick popup with description and total value comes up, but only momentarily before disappearing and switching to the "drag and move" functionality. This popup is very useful for quickly assessing stack price.

In essence, this seems to make the small info popup useless. Perhaps it would be better to add a toggle for organizing items, so the normal tap-and-hold functionality can allow that popup to remain. The delay for dragging items can also be adjusted, but that would need to be too long if the description is to be read. 

### Reproduction Steps

1. Go to Bank
2. Tap-and-hold item

### Expected behaviour

Popup should stay visible while bring held. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2076

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
