### ISSUE TITLE
[Bug]: Character unable to perform any active actions

### ISSUE THREAD

**Issue by shochman** [MelvorIdle/melvoridle.github.io#2540]
### Describe the bug

I cannot do anything with this character that is active. 

Passive actions like farming, selling/buying items, or changing equipment are all successful, but anything like attacking monsters (dungeons, individual monsters, or Slayer tasks), chopping wood, fishing, etc. do not work.

I've tested this on multiple devices, save slots, and exported my save to friend who imported it and had the same experience. A different character I have still behaves normally.

The exported save is attached on the bug report.

### Save Link

https://melvoridle.com/save/5UbjZzzM

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2076

### Are you using any scripts or extensions?

No

**Comment by xanderput** [comment]
Possibly related to  #2486 and #2497.
The latter has a line of code that may fix the issue. Run this in the console on the web version on pc.

I won't have access to a pc for a while so I probably won't be able to fix it for you. Someone else may be able to though.

**Comment by xanderput** [comment]
Possibly related to  #2486 and #2497.
The latter has a line of code that may fix the issue. Run this in the console on the web version on pc.

I won't have access to a pc for a while so I probably won't be able to fix it for you. Someone else may be able to though, if you don't have access to a pc.

**Comment by Lunien** [comment]
Solved this problem with the line of code in #2497 , the problem persists in mobile too if you import the save there. In console I saw this error which might have been the issue:
![image](https://user-images.githubusercontent.com/110506502/182498924-77d9bf67-97ff-4b03-a51f-f276d9163147.png)

**Comment by MelvorIdle** [comment]
Fixed as of v1.1. Please open a new report if issue persists.
