### ISSUE TITLE
[Bug]: Screen shakes upon monster death 

### ISSUE THREAD

**Issue by NFLDmelvor** [MelvorIdle/melvoridle.github.io#2541]
### Describe the bug

Every time I kill a monster, my game shakes causing me to sometimes misclick. 

### Reproduction Steps

1. Go to combat
2. Fight any npc (plant for faster kills)
3. Screen shakes upon kill.

### Save Link

https://melvoridle.com/save/ucGJMO5t

### Screenshots

https://user-images.githubusercontent.com/109835811/180587194-15791c46-2226-43bd-a8f8-7ddfc0f54fee.mp4

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by Cramoisi-San** [comment]
Known bug, caused by the monster loading gif (the spining donut, if you will)

**Comment by NFLDmelvor** [comment]
It's 10x worse with the speed run mode. Starting off killing plants I had to close the game (offline progress on) and pray I didn't die. Couldn't stand to look at the screen with the speed of kills.

**Comment by nikovei** [comment]
Can confirm is happening to me as well except the shaking is worse, its making the game unplayable. 

I haven't identified what causes the issue but believe it may have something to do with being in combat for extended periods of time. 

I am on the android mobile app on Android 12.

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
