### ISSUE TITLE
[Bug]: no offline progress for combat

### ISSUE THREAD

**Issue by Fata4Life** [MelvorIdle/melvoridle.github.io#2545]
### Describe the bug

Anytime i leave a player on combat, it stops all progress. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by Zero-DotV** [comment]
Is the "Toggle offline combat" setting set to on?

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
