### ISSUE TITLE
[Bug]: Logs mastery doesn't update while burning

### ISSUE THREAD

**Issue by meazh** [MelvorIdle/melvoridle.github.io#2547]
### Describe the bug

Hi, 

While I'm burning woods during firemaking, the mastery gains doesn't update after a level up, I have to change logs to see the new gains.

### Reproduction Steps

1. Go to firemaking
2. Select a log and burn it up to a higher level
3. See that the mastery doesn't refresh

### Expected behaviour

The mastery gains refresh :)

### Save Link

https://melvoridle.com/save/96YrfcCM

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by meazh** [comment]
So, i went farm some woods, to have a screenshot for you guys :D

![image](https://user-images.githubusercontent.com/35642480/181340659-78192396-c7e7-4c27-a43a-e355bd0558d9.png)

As you can see, i have the Teak Logs mastery 6, and you can see that my mastery gain is 1 (and i'm winning 6), and my mastery pool gain is 0 when i'm winning 1. 

HMU if you need anything else guys :D

**Comment by MelvorIdle** [comment]
Fixed as of v1.1. Please open a new report if issue persists.
