### ISSUE TITLE
[Bug]: Topaz bolts don't appear in bank

### ISSUE THREAD

**Issue by genaralskar** [MelvorIdle/melvoridle.github.io#2548]
### Describe the bug

I'm crafting topaz bolts but they don't appear in my bank, and they aren't in any equipment slots. When they're crafted the popup shows I have ~12,000 of them. Crafting other bolts works fine and they show up in my bank. Using the bank search for "bolts" or "topaz" does not show the bolts either.

I have the Melvor Idle Combat Simulator Reloaded extension installed on Firefox, where this bug first appeared.

### Reproduction Steps

Go to fletching
Select topaz bolts
Click create
Check the bank after they're created

### Expected behaviour

The created bolts to appear in my bank

### Save Link

https://melvoridle.com/save/pySkATla

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

Yes

**Comment by genaralskar** [comment]
Just noticed the same problem with steel arrows. It says I have ~1,200 on the fletching screen, but they don't show up in my bank.

**Comment by ekuland** [comment]
![image](https://user-images.githubusercontent.com/4542300/181996541-56a666bc-d88d-4473-9004-c695589e0f20.png)
Bank tab 6, the one with the ice sword as its icon.
They show up in the search under "topaz", "bolt", and "bolts"
Same with the steel arrows.

**Comment by genaralskar** [comment]
ok yeah just figured that out. was just confused how the searched worked. i feel stupid.
