### ISSUE TITLE
[Bug]: Skills not running while AFK

### ISSUE THREAD

**Issue by Froggy123000** [MelvorIdle/melvoridle.github.io#2549]
### Describe the bug

Sometimes when I go offline, whatever skill was running before stops and doesn’t continue to progress. It will be running fine while the app is open but nothing will happen once the app is closed or in the background. 

### Expected behaviour

For the skills to keep running and updating while AFK. 

### Screenshots

![8CA4B6BF-D66F-494A-97B1-6E101F88352F](https://user-images.githubusercontent.com/110339468/182038593-f25f6f25-f97c-4251-808a-c02437e3c89a.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
