### ISSUE TITLE
Fletching skill guide shows steel javelins as wrong level

### ISSUE THREAD

**Issue by BRNNNN4** [MelvorIdle/melvoridle.github.io#255]
**Describe the bug**
Steel javelins show as needing only 5 fletching to make but require 32.

**To Reproduce**
1. Go to fletching skill guide
2. Steel javelin requirement shows as 5.

**Expected behavior**
Steel javelin requirement to show as 32.

**Screenshots**

**Browser**
Please tell us what browser you are using and what version.
Google Chrome Version 83.0.4103.61

**Console output**
n/a

**Are you using any scripts?**
n/a

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
