### ISSUE TITLE
[Bug]: can't progress in tutorial

### ISSUE THREAD

**Issue by OverSeerX** [MelvorIdle/melvoridle.github.io#2550]
### Describe the bug

On tutorial 14/22 I'm supposed to attach a string to the short bow (u) but my bank was full but it still used resources. On 15/22 I'm supposed to equip my bow but Its not in my bank since it's full . I made space and it's not there. I tried going into shop to buy another string but it tells me the item is locked during tutorial. I can't find a way to progress past this. 

### Reproduction Steps

By tutorial 14/22 have a full bank

Craft short bow 

Try to progress

### Save Link

https://melvoridle.com/save/gjHHOWLn

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by Sprinkles-GS** [comment]
I'm also stuck at this point

**Comment by CynicalCyno** [comment]
same issue but I don't think I had a full bank.

**Comment by awethumbness** [comment]
Same here, bank was also not full. Android app v3.0.1

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
