### ISSUE TITLE
[Bug]: <title> Items disappearance When leaving combat with full inventory to craft something new

### ISSUE THREAD

**Issue by Jedi1000888** [MelvorIdle/melvoridle.github.io#2552]
### Describe the bug

I was doing combat with my elite wand, realizing I could upgrade it to the fire imbued wand for fire spells I went to upgrade it. My inventory had 1 space left and I had multiple items to collect or discard. When I went to start making the wand thus effectively making the game start trying to collect the items from combat while at the same time making the wand. The wand disappeared and is not in any of the slots not back on my character nor is it saying I can still make it. Effectively making it vanish into thin air. 

### Expected behaviour

I expected to be able to make it and be able to go back to the loot page and finish discarding and collecting the loot after so I could continue to do combat just with less runes.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Fixed as of v1.1. Please open a new report if issue persists.
