### ISSUE TITLE
[Bug]: Herblore

### ISSUE THREAD

**Issue by Chesterix** [MelvorIdle/melvoridle.github.io#2554]
### Describe the bug

An error occured while processing ticks offline:
Active Skill: HERBLORE
Error Name: TypeError
Error Message: Cannot read properties of undefined (reading 'hasAnimation')
Stack Trace:
TypeError: Cannot read properties of undefined (reading 'hasAnimation')
    at getItemMedia (https://melvoridle.com/assets/js/game/main.js?2077:412:58)
    at Game.createOfflineModal (https://melvoridle.com/assets/js/built/game.js?2077:100:417)
    at https://melvoridle.com/assets/js/built/game.js?2077:76:812
Current Equipment:
Helmet: Crown_of_Rhaelyx
Platebody: Hard_Leather_Body
Platelegs: Green_Dhide_Chaps
Boots: Boots_Of_Stealth
Weapon: Ice_Sword
Shield: Mirror_Shield
Amulet: Amulet_of_Fishing
Ring: Gold_Topaz_Ring
Gloves: Thieving_Gloves
Quiver: Seed_Pouch
Cape: Fishing_Skillcape

Skill Information:
Is Active: true

Selected Recipe ID: 16

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

Yes

**Comment by MelvorIdle** [comment]
Fixed as of v1.1. Please open a new report if issue persists.
