### ISSUE TITLE
[Bug]: Mastery Pool Experience

### ISSUE THREAD

**Issue by Senoke79** [MelvorIdle/melvoridle.github.io#2555]
### Describe the bug

I am only receiving 25% mastery pool experience while pickpocketing a target that I have 99 mastery with. 

### Reproduction Steps

1. Go to theiving
2. Pick a target with 99 mastery. 
3. Note the mastery pool experience.

### Expected behaviour

I expected to receive 50% mastery pool experience while pickpocketing a target with 99 mastery. 

### Save Link

https://melvoridle.com/save/HflINHcl

### Screenshots

![Screenshot_20220807-182447_2b8eea6112cc876d6c442b74a1d27a81](https://user-images.githubusercontent.com/110791653/183313977-6c28624d-b358-4ddc-accf-80de611af9b1.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by 47Y** [comment]
Mastery Pool Experience increases to 50% at 99 Skill Level, not Mastery Level.

**Comment by Senoke79** [comment]
Ah, thank you for pointing this out. The wiki agrees with you. My apologies for not understanding earlier. I will close this now.
