### ISSUE TITLE
"Apple" instead of "Apples"

### ISSUE THREAD

**Issue by Malkorain** [MelvorIdle/melvoridle.github.io#2556]
### What text is wrong?

![Screenshot_20220807-180155_Melvor Idle](https://user-images.githubusercontent.com/110792383/183314557-21fe32bf-582d-4df1-a67e-67bb424b0b97.jpg)

### What is the correct spelling or grammar?

You have 8,090 "Apples" in your bank

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
