### ISSUE TITLE
[Bug]: another weird bondfire issue

### ISSUE THREAD

**Issue by Sandman25x** [MelvorIdle/melvoridle.github.io#2558]
### Describe the bug

When using potion with bonfire displayed mastery and mastery pools displayed values multiply permanently. Works ok multiple logs. 

### Reproduction Steps

Start burning 

Then select controlled heat iii potion 

Once selected click on light bonfire

The values update immediately. 

****
Example teak log has 20% boost. 

Whatever the  displayed mastery and master pool value is is multiplied x's. 1.2 perminantly

It never goes back down. And this effect with stack over a period of time between attempts. 

Meanwhile actual xp aquired never were boosted and never changed 

Thanks

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Fixed as of v1.1. Please open a new report if issue persists.
