### ISSUE TITLE
[Bug]: Cannot Idle Anything. Stuck chopping tree's with no progress

### ISSUE THREAD

**Issue by LadyCopper34** [MelvorIdle/melvoridle.github.io#2560]
### Describe the bug

I play on both mobile and pc. My account has been stuck not being able to idle anything. I try combat, mining and basically any other skills and it has no progress. Woodcutting has multiple tree's selected but it will not make progress with any cuts. If I click on a combat monster, it minimizes the bar, If I click to idle a skill it does nothing. 

### Screenshots

![image](https://user-images.githubusercontent.com/110941626/183767414-16e89015-2447-44e2-8e1f-2302d70cf322.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by Hot-Spit** [comment]
This exact same thing is happening to my account as well. I've tried reinstalling on my mobile app to no avail.

**Comment by MelvorIdle** [comment]
Fixed as of v1.1. Please open a new report if issue persists.
