### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by baiguohui1209** [MelvorIdle/melvoridle.github.io#2562]
### Describe the bug

点击 **隐藏非战斗列表**后  列表消失  web端与移动端均有该问题

### Reproduction Steps

单击‘隐藏非战斗列表’ 列表消失

### Screenshots

![WechatIMG586](https://user-images.githubusercontent.com/111178731/184479180-7341d578-7699-439b-b4b9-9416fba294f7.png)
![WechatIMG587](https://user-images.githubusercontent.com/111178731/184479187-777ae482-3424-453b-b0c5-e514662710c8.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

？2077

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Fixed as of v1.1. Please open a new report if issue persists.
