### ISSUE TITLE
[Bug]: now no actions possible except farming

### ISSUE THREAD

**Issue by Flashaha** [MelvorIdle/melvoridle.github.io#2563]
### Describe the bug

After a 6 hour run of thieving, sold some stuff and then tried to craft, mine, cook etc none of them now work except farming and agility that lights up but doesn’t progress

### Save Link

https://melvoridle.com/save/Dyuc85ie

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?1744

### Are you using any scripts or extensions?

No

**Comment by xanderput** [comment]
Probably related to #2486, #2497 and #2540.

There's two ways to fix it that I know of at this point:

Method 1:
- Running `game.activeSkill = ActiveSkills.NONE` in console

Method 2:
1. Load the save and see what the 'active skill' is. In this case summoning.
![Screenshot 2022-08-14 140537](https://user-images.githubusercontent.com/39944140/184536186-8f3d48fa-0d04-4adb-8f8e-adda6bb09491.png)

2. Go to that skill and start and then stop any action. In this case I chose pig tablets, so I click "Create" twice to start and then stop the action.
![Screenshot 2022-08-14 140902](https://user-images.githubusercontent.com/39944140/184536259-8667a186-a9f5-4132-9051-c256f37198d4.png)


Here is your fixed save: https://melvoridle.com/save/vS7XovPT

**Comment by Flashaha** [comment]
Thank you!

**Comment by MelvorIdle** [comment]
Fixed as of v1.1. Please open a new report if issue persists.
