### ISSUE TITLE
[Bug]: Offline thieving damage/heal miscalculation

### ISSUE THREAD

**Issue by Chocodemon** [MelvorIdle/melvoridle.github.io#2565]
### Describe the bug

The amount of food used when offline thieving is way too high and doesn't match online/active thieving values.

I have thieving gloves equipped so I can very precisely see how many thieving attempts have been made. And in the screenshot you can see that I have a >75% chance of thieving success. Combined with around 60 Hitpoint regen and tier 3 auto eating, I roughly eat 25% as much food, as I use thieving glove charges when online.
(1000 glove usage + 250 food eaten)

But offline those numbers match very closely 
(1000 glove usage + 1000 food eaten)

### Reproduction Steps

1. Start thieving with relatively high chance of success.
2. Have high level of auto eat, so that eating food heals you very much
3. Have thieving gloves equipped so you can exactly see how often you tried to steal something
4. Let run offline for an hour or 2

The longer it runs, the close the number of food eaten and glove charges used gets

### Expected behaviour

Offline and online numbers should match more closely.

### Save Link

https://melvoridle.com/save/V2aEaRe3

### Screenshots

![grafik](https://user-images.githubusercontent.com/6138115/184959552-65aa16b1-e59b-4f8e-8765-eba7eaf297c5.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by Chocodemon** [comment]
![grafik](https://user-images.githubusercontent.com/6138115/184975137-77d6123b-775d-4f75-b48b-c9679cabe236.png)
Here you can see that after ~1 hour 1350 food + 1500 glove charges.
But the knight needs at least 3 hits to get me to heal, I heal 60 HP and auto eating heals 80%.

With those numbers it is like I have a less than 50% success chance of thieving... even though it is >75%

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
