### ISSUE TITLE
[Bug]: Firemaking mastery XP

### ISSUE THREAD

**Issue by Petay-parmz** [MelvorIdle/melvoridle.github.io#2566]
### Describe the bug

The actual value added to the firemaking mastery total XP and log mastery XP is different to what is displayed, by about 1/3.

### Reproduction Steps

Go to firemaking, click on any log, burn log.

### Expected behaviour

My XP mastery values go up by the number displayed on screen.

For example my Willow log mastery level is 17, my log mastery XP per log burnt shows as 27 but I am only receiving 17. My Firemaking Mastery XP is showing as 6 but I receive 4, 4, 4, 5, 4, 4, 4, 5.

### Save Link

https://melvoridle.com/save/cQXsCJBw

### Screenshots

![image](https://user-images.githubusercontent.com/111569417/185595613-dde9d24f-8ad8-4286-8a46-f4f85b6b5476.png)
![image](https://user-images.githubusercontent.com/111569417/185595720-d39ac4ff-32d8-459f-88b3-8c8555aa4d71.png)
Before and after burning one log

### Console output

style.css:1          Failed to load resource: the server responded with a status of 404 ()
css:1          Failed to load resource: the server responded with a status of 403 ()
cloud.js?2077:67 Connected to PlayFab successfully
save.js?2077:42 Copied to clipboard successfully.
save.js?2077:79 set force reload to 0
combatManager.js?2077:1 Combat Manager Built...
raidManager.js?2077:1 Golbin Raid Manager Built...
save.js?2077:20 Loading Save Game...
save.js?2077:20 Save Game Loaded...
main.js?2077:6 Game Loaded
cloud.js?2077:187 updatePlayerTags
cloud.js?2077:67 Connected to PlayFab successfully
firemaking%20agility.svg:1          Failed to load resource: the server responded with a status of 403 ()
css:1          Failed to load resource: the server responded with a status of 403 ()
cloud.js?2077:11 Synchronising with Cloud
style.css:1          Failed to load resource: the server responded with a status of 404 ()
css:1          Failed to load resource: the server responded with a status of 403 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by RedStarTree** [comment]
Based on Willow it looks like the index is off by 1 for the display amount of Mastery points per action (burning). 0 vs 1 based ?

**Comment by MithosShulk** [comment]
I'm having this issue as well with every log. Advertised mastery does not match the actual mastery I get.

**Comment by MelvorIdle** [comment]
Fixed as of v1.1. Please open a new report if issue persists.
