### ISSUE TITLE
[Bug]: Stuck In Agility

### ISSUE THREAD

**Issue by GoulHunter** [MelvorIdle/melvoridle.github.io#2567]
### Describe the bug

I was doing agility. Closed browser for a few hours. When i returned the game started fine but agility was acting like it was still running without progressing. an obstacle was highlighted green like i was in the middle of a run. The Force save button had a dash next to it for my time since last save and i was unable to save it at all. Trying to switch character gets me locked in the loading screen. closing and reopening the game puts me back on agility. i can perform other tasks but am unable to restart agility. Agility start button is greyed out. unable to save in anyway so leaving and coming back puts me at the same point of agility. Here is a link to my save: https://melvoridle.com/save/IB9SmofS

### Reproduction Steps

Unown... but other have similar bugs of getting stuck on agility.

### Save Link

https://melvoridle.com/save/IB9SmofS

### Screenshots

![Screenshot 2022-08-20 162705](https://user-images.githubusercontent.com/83544996/185764930-b25c5d97-b474-4cc8-b2d1-a220072122b9.png)
![Screenshot 2022-08-20 162741](https://user-images.githubusercontent.com/83544996/185764944-3314b164-fcce-44b8-b824-c3afb3116e02.png)
![Screenshot 2022-08-20 162813](https://user-images.githubusercontent.com/83544996/185764961-01d2b0c2-4774-4638-9905-263532ff771d.png)

### Console output

INS: content-ads.js loaded:  https://melvoridle.com/index_noads.php [content-scripts.js:1:107966](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
TSS: content-tss.js loaded:  https://melvoridle.com/index_noads.php [content-scripts.js:1:117421](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
INS: content-blocked-items.js loaded:  https://melvoridle.com/index_noads.php [content-scripts.js:1:137459](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
CONTENT_SHELL: Page allowed. Skipping shell injection blocks [content-scripts.js:1:137121](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
GET TAB ID RESPONSE:  
Object { tabId: 1 }
[content-scripts.js:1:118957](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
TSS: excluded result:  
Object { excluded: true }
[content-scripts.js:1:128142](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
TSS: Excluding content tss (trigger: send-mesage) [content-scripts.js:1:119494](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-129674422-1”. [index_noads.php:6:1](https://melvoridle.com/index_noads.php)
Connected to PlayFab successfully [cloud.js:67:225](https://melvoridle.com/assets/js/game/cloud.js?2077)
set force reload to 1 [save.js:79:60](https://melvoridle.com/assets/js/game/save.js?2077)
Combat Manager Built... [combatManager.js:1:912](https://melvoridle.com/assets/js/built/combatManager.js?2077)
Golbin Raid Manager Built... [raidManager.js:1:1601](https://melvoridle.com/assets/js/built/raidManager.js?2077)
Loading Save Game... [save.js:20:29](https://melvoridle.com/assets/js/game/save.js?2077)
Save Game Loaded... [save.js:20:140](https://melvoridle.com/assets/js/game/save.js?2077)
Game Loaded [main.js:6:558](https://melvoridle.com/assets/js/game/main.js?2077)
updatePlayerTags [cloud.js:187:43](https://melvoridle.com/assets/js/game/cloud.js?2077)
Took 0.172s to process 1256732 ticks. 0.0001368629111059478ms per tick. [game.js:34:84](https://melvoridle.com/assets/js/built/game.js?2077)
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.
[Changelogv1.0.5Draft.html](https://melvoridle.com/update/Changelogv1.0.5Draft.html)
INS: content-ads.js loaded:  https://melvoridle.com/roadmap/index.html [content-scripts.js:1:107966](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
TSS: content-tss.js loaded:  https://melvoridle.com/roadmap/index.html [content-scripts.js:1:117421](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
INS: content-blocked-items.js loaded:  https://melvoridle.com/roadmap/index.html [content-scripts.js:1:137459](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.
[CopyofMelvorIdleMemeContestTCsv3.docx.html](https://melvoridle.com/pages/other/CopyofMelvorIdleMemeContestTCsv3.docx.html)
INS: content-ads.js loaded:  https://melvoridle.com/pages/other/CopyofMelvorIdleMemeContestTCsv3.docx.html [content-scripts.js:1:107966](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
TSS: content-tss.js loaded:  https://melvoridle.com/pages/other/CopyofMelvorIdleMemeContestTCsv3.docx.html [content-scripts.js:1:117421](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
INS: content-blocked-items.js loaded:  https://melvoridle.com/pages/other/CopyofMelvorIdleMemeContestTCsv3.docx.html [content-scripts.js:1:137459](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
INS: content-ads.js loaded:  https://melvoridle.com/update/Changelogv1.0.5Draft.html [content-scripts.js:1:107966](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
TSS: content-tss.js loaded:  https://melvoridle.com/update/Changelogv1.0.5Draft.html [content-scripts.js:1:117421](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
INS: content-blocked-items.js loaded:  https://melvoridle.com/update/Changelogv1.0.5Draft.html [content-scripts.js:1:137459](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
CONTENT_SHELL: Page allowed. Skipping shell injection blocks [content-scripts.js:1:137121](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
GET TAB ID RESPONSE:  
Object { tabId: 3 }
[content-scripts.js:1:118957](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
CONTENT_SHELL: Page allowed. Skipping shell injection blocks [content-scripts.js:1:137121](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
GET TAB ID RESPONSE:  
Object { tabId: 3 }
[content-scripts.js:1:118957](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
CONTENT_SHELL: Page allowed. Skipping shell injection blocks [content-scripts.js:1:137121](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
GET TAB ID RESPONSE:  
Object { tabId: 3 }
[content-scripts.js:1:118957](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
TSS: excluded result:  
Object { excluded: true }
[content-scripts.js:1:128142](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
TSS: Excluding content tss (trigger: send-mesage) [content-scripts.js:1:119494](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
TSS: excluded result:  
Object { excluded: true }
[content-scripts.js:1:128142](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
TSS: Excluding content tss (trigger: send-mesage) [content-scripts.js:1:119494](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
TSS: excluded result:  
Object { excluded: true }
[content-scripts.js:1:128142](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
TSS: Excluding content tss (trigger: send-mesage) [content-scripts.js:1:119494](moz-extension://7c23d923-fc48-4c05-9f05-3848681e5f9d/content-scripts.js)
The resource from “https://themes.googleusercontent.com/fonts/css?kit=fpjTOVmNbO4Lz34iLyptLTi9jKYd1gJzj5O2gWsEpXoyck2WCYPEMNySjZN0CHed_kmCvy597kDopqFAXvpeaA” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
[CopyofMelvorIdleMemeContestTCsv3.docx.html](https://melvoridle.com/pages/other/CopyofMelvorIdleMemeContestTCsv3.docx.html)
Connected to PlayFab successfully [cloud.js:67:225](https://melvoridle.com/assets/js/game/cloud.js?2077)
Uncaught TypeError: mark is undefined
    serialize https://melvoridle.com/assets/js/built/summoning.js?2077:67
    serialize https://melvoridle.com/assets/js/built/summoning.js?2077:67
    serialize https://melvoridle.com/assets/js/built/game.js?2077:110
    packageSave https://melvoridle.com/assets/js/built/serializeSave.js?2077:61
    getCompressedSaveString https://melvoridle.com/assets/js/built/serializeSave.js?2077:62
    saveData https://melvoridle.com/assets/js/game/save.js?2077:8
    tenSecondUpdateTimeout https://melvoridle.com/assets/js/game/main.js?2077:522
[summoning.js:67:328](https://melvoridle.com/assets/js/built/summoning.js?2077)
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features! [index_noads.php](https://melvoridle.com/index_noads.php)
Uncaught TypeError: mark is undefined
    serialize https://melvoridle.com/assets/js/built/summoning.js?2077:67
    serialize https://melvoridle.com/assets/js/built/summoning.js?2077:67
    serialize https://melvoridle.com/assets/js/built/game.js?2077:110
    packageSave https://melvoridle.com/assets/js/built/serializeSave.js?2077:61
    getCompressedSaveString https://melvoridle.com/assets/js/built/serializeSave.js?2077:62
    saveData https://melvoridle.com/assets/js/game/save.js?2077:8
    clearOffline https://melvoridle.com/assets/js/game/main.js?2077:200
    stop https://melvoridle.com/assets/js/built/skill.js?2077:26
    stopAgilityOnClick https://melvoridle.com/assets/js/built/agility.js?2077:89
    <anonymous> https://melvoridle.com/assets/js/built/agility.js?2077:49
[summoning.js:67:328](https://melvoridle.com/assets/js/built/summoning.js?2077)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

Yes

**Comment by xanderput** [comment]
marksUnlocked had an undefined entry, getting rid of that one fixed it:
![image](https://user-images.githubusercontent.com/39944140/185765884-c7e505e9-e88d-4078-b572-d973e2532796.png)

Fixed save: https://melvoridle.com/save/ivWWaq0m

**Comment by MelvorIdle** [comment]
Fixed as of v1.1. Please open a new report if issue persists.
