### ISSUE TITLE
[Bug]: <Buying Shield w/ 2H weapon equipped Goblin Raid>

### ISSUE THREAD

**Issue by Crazynate0** [MelvorIdle/melvoridle.github.io#2568]
### Describe the bug

Didn't see any posts about this. I was playing goblin raid had the 2H Dragon Sword equipped, I bought a (G) Rune Shield expecting it to default back to the Bronze schimitar but instead no weapon was there and I couldn't attack. I skipped the round and was able to purchase a weapon. I just wanted to bring it to your attention so you could do some more testing to see if a bug actually does exist or if it was a one off. Thanks the game is great! 

### Reproduction Steps

1. Using 2H Dragon Sword in Goblin raid
2. Purchased a (G) Rune Shield
3. Did not default back to the Bronze Schimitar. 
4. Skipped round and purchased a new weapon to fix problem. 

### Expected behaviour

I thought that a bronze schimitar would appear just like when you run out of runes/ammo.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
