### ISSUE TITLE
[Bug]: Farming statistics

### ISSUE THREAD

**Issue by GustavLindahl** [MelvorIdle/melvoridle.github.io#2569]
### Describe the bug

When looking at farming statistics, more specifically the time spent waiting for plants to grow the time is off. It says I have waited for almost 3 years while I have only been playing for half a year. This is probably because the time is added for each plant instead of just adding the time something grows. For example if I grow 5 plants at the same time and it takes 2 hours it should probably add 2 hours to my waiting time and not 10 hours.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
