### ISSUE TITLE
[Bug]: Beyond Level 99

### ISSUE THREAD

**Issue by zanganam** [MelvorIdle/melvoridle.github.io#2573]
### Describe the bug

I've been woodcutting for the past few days and I came online today to see that I was level 100/99 for woodcutting. I thought that it would stop there but now I went back on and it's gotten to 101/99.

### Reproduction Steps

1. Obtain level 99 Woodcutting.
2. Continue offline farming it for some period of time.
3. When returning the level goes beyond the cap.

### Expected behaviour

The level should not exceed 99.

### Screenshots

![image](https://user-images.githubusercontent.com/32550775/187000413-7d1aa572-01fc-4a23-bf45-37086e268257.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by zanganam** [comment]
It's apparently not just woodcutting as it happened with firemaking as well. 
![image](https://user-images.githubusercontent.com/32550775/188337242-0e248eb4-2925-4e01-a3ed-7c35dcbd0e89.png)

**Comment by Zero-DotV** [comment]
Do you have the virtual levels setting turned on? That's what it does, shown in the below screenshots (Mining and Smithing skills).
![Screenshot (17)](https://user-images.githubusercontent.com/112882173/189038826-ba3fda3f-e22b-49d3-a57a-69482cdf69f2.png)
![Screenshot (18)](https://user-images.githubusercontent.com/112882173/189038832-86122eb7-9ecc-4e56-ad8c-3704ea0003d4.png)

**Comment by zanganam** [comment]
It is indeed on. I didn't know that is what it does. Thank you for the clarification. Then no bugs here.
