### ISSUE TITLE
Redwood Longbow/Shortbow is wrong in summoning 

### ISSUE THREAD

**Issue by burkeg** [MelvorIdle/melvoridle.github.io#2574]
### Describe the bug

The centaur summoning tablet requires 50 redwood bows while only requiring 3 magic bows.

### Expected behaviour

This is an oversight, I would expect centaur tablets to only require 1-2 redwood items to be more in line with the other summoning tablets.

### Save Link

https://melvoridle.com/save/eVitkLtm

### Screenshots

![Screenshot_20220826-195509](https://user-images.githubusercontent.com/8559331/187011667-59793ee5-e36e-4c66-a048-ebfe7d16dce5.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by 47Y** [comment]
Summoning item requirements are based on sale price and Redwood logs and items are worth much less than Magic logs and items. As such, Summoning requires more Redwood than Magic.
