### ISSUE TITLE
[Bug]: Goblin raid Spam Eating

### ISSUE THREAD

**Issue by 098hgj** [MelvorIdle/melvoridle.github.io#2576]
### Describe the bug

when playing goblin raid while battling,use food by click the button may cause wrong food picture (which is your food in battle),and also may trigger spam eating.

### Reproduction Steps

1.Play goblin raid while battling
2.Use food by click the button

### Expected behaviour

Eat food not trigger spam eating.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
