### ISSUE TITLE
[Bug]: 'Create Sharable Save URL' copy icon doesn't give indication that save link has been copied

### ISSUE THREAD

**Issue by zants** [MelvorIdle/melvoridle.github.io#2577]
### Describe the bug

Possibly more of a suggestion, unless this actually is a bug.

Copy function works correctly, there's simply no feedback given to the user that the link was actually copied (and so, up until recently, I personally thought the copy icon didn't actually do anything).

### Reproduction Steps

1. Open Melvor Idle app
2. Select 'Settings' on desired save slot
3. Select 'Create Sharable Save URL'
4. On Save Link interface that appears, tap the copy icon next to the URL

### Expected behaviour

Tapping the copy icon next to the URL correctly copies the URL to your clipboard -- there's no problem there.  However, usually with actions like this there would be a small pop-up that appears saying something like "link copied to clipboard", this doesn't happen and the user doesn't get indication that anything actually happened.

### Screenshots

![C0400871-9B62-472B-A9E1-D10CD3E33417](https://user-images.githubusercontent.com/822329/187082157-3eb4aa78-c1ec-4711-b4de-9e0b0c222b74.jpeg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by Reisclef** [comment]
Also noticed this on android when getting save link for a bug I raised.

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
