### ISSUE TITLE
[Bug]: Non combat skills remove self from menu

### ISSUE THREAD

**Issue by nickospie** [MelvorIdle/melvoridle.github.io#2578]
### Describe the bug

When minimizing the Non combat skills menu.  It removes the noncombat skills section from the menu. I'm unable to access the non-comabt skills without going to the charcter selct menu and then reselecting my character. 

### Reproduction Steps

1. open Melovo idle 
2. select character 
3. click on eye symbol next to the non-combat skills menu to minimize it 
4. removes non-combat menu from overall menu.

### Expected behaviour

Non-combat skills menu minimizes similar to combat menu and can be opened again after pressing the eye symbol to open it. 

### Screenshots

![Screen Shot 2022-08-28 at 1 17 52 PM](https://user-images.githubusercontent.com/112348852/187093103-831d99c6-6e59-43b7-a07f-b3846acd1691.png)
![Screen Shot 2022-08-28 at 1 17 46 PM](https://user-images.githubusercontent.com/112348852/187093126-c3cdd47a-023c-411d-8f3a-531b513eb815.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.1.
