### ISSUE TITLE
[Bug]: Thieving max hit factors current combat DR modifier

### ISSUE THREAD

**Issue by cairnsjr13** [MelvorIdle/melvoridle.github.io#2579]
### Describe the bug

When actively fighting a monster with a different combat style, the combat triangle's effect is applied to DR.  This shows up on the thieving page for each npc's max hit.  However, when you go to actually thieve from them, the combat triangle no longer applies.  The max hits on the thieving page should not factor in combat triangle.

### Reproduction Steps

Equip armor with Dr
Fight monster with different attack style
Check thieving page to see max hit (make sure combat is active, not spawning)
Start thieving
Reload thieving page
Max hit is different 

### Expected behaviour

Max hit on thieving page should not be subject to combat triangle

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

2077

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
