### ISSUE TITLE
[Bug]: Creating Regeneration potion I reports extra incorrect error when bank is full

### ISSUE THREAD

**Issue by Reisclef** [MelvorIdle/melvoridle.github.io#2580]
### Describe the bug

Hope this is replicable. While the error that the bank is full is correct, there is also the error that you don't have the materials required which is confusing.

### Reproduction Steps

On mobile:

1. Fill bank (including items to make regen potion I, II or III)
2. Attempt to create regen potion I, II or III

### Expected behaviour

Expected behaviour:
Error: Your bank is full

Actual behaviour:
Error: You don't have the required materials to create that
Error: Your bank is full

### Save Link

https://melvoridle.com/save/jwlFylZV

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

72077

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
