### ISSUE TITLE
[Bug]: Hitting 50% mastery pool in Summoning gives +1 shard cost reduction for tier 3 tablets.

### ISSUE THREAD

**Issue by Pwaite2** [MelvorIdle/melvoridle.github.io#2581]
### Describe the bug

Today while crafting tablets, I noticed that my shard cost for Monkey tablets went from 8 green, 6 silver and 4 black shards to 7, 5 and 3, respectively after hitting 50% in the mastery pool. The cost change affected all tier 3 summon tablets.

Since my current monkey tablet mastery is 70 and I have the summoning pet (Ty), the tablet cost should be 8, 6, 4. Another user on discord also confirmed having a shard cost reduction for tier 3 after reaching 50% mastery pool.

According to the checkpoints list at the top-right of the screen, reaching 50% mastery pool should grant the player +10% resource preservation and nothing more.

After looking through the game code, this line of code was found:

quantity--;if(recipe.tier===3&&this.isPoolTierActive(2))

No similar line was found for the PoolTierActive(3), only the +10 tablets par action. Therefore, it looks like we actually get the +1 shard cost reduction for tier 3 tablets at 50% pool instead of 95% pool and therefore, the text is wrong.

### Reproduction Steps

1. Go to Summoning
2. Make mastery pool go above and below 50%
3. Check to see if the shard cost for T3 tablets varies.
4. Do the same at 95% mastery pool.

### Expected behaviour

I expected the shard cost of T3 summons to stay the same above and below 50% mastery pool according to mastery pool checkpoints text.

### Save Link

https://melvoridle.com/save/s89h3GHE

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Fixed as of v1.1. Please open a new report if issue persists.
