### ISSUE TITLE
[Bug]: Load a page is lagging

### ISSUE THREAD

**Issue by Brazenpo** [MelvorIdle/melvoridle.github.io#2583]
### Describe the bug

I have bought the game on android via playstore, and install it, I've played it long enough so I can't be repaid, but that's not the issue. The issue is, like explained in the title, that my game is fine, but when I try to load a new type of task, my game take about 3 seconds to load the task, and during these 3 secondes, I can't touch my screen due to lagging purpose. My phone never lagged on a single game, and I don't find any answer to this issue. Could someone help me? 

### Reproduction Steps

1. Install the game via play store
2. Play a bit long, don't notice the issue for about 30 min
3. Change task pages frequently and you will notice the phone freezing for about 3 seconds

### Expected behaviour

The game, as long as i have seen on others, is fluid and you can change pages as fast as you can and want, it still really fluid, it's not freezing for 3 seconds.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

? 2077

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
