### ISSUE TITLE
[Bug]: Game Window Gets Over Written With Steam Window

### ISSUE THREAD

**Issue by SolarEclipz** [MelvorIdle/melvoridle.github.io#2584]
### Describe the bug

If I have Melvor Idle open while playing another game (csgo) and if I view some ones steam profile, their profile shows in game. However, when I look at Melvor Idle, that profile will appear in Melvor with no option to close that profile. I have to close Melvor and re-open in order to do anything inside Melvor Idle.

### Reproduction Steps

1. Load a game, like csgo
2. Play a game and view someones profile within the CSGO overlay stuff.
3. Either close that profile, or close csgo, or just switch to Melvor.
4. That profile is now taking over the melvor idle game window. You have URL bar, forward, backward, refresh options, along with close. They don't do anything.

### Expected behaviour

For Melvor to not duplicate steam overlay, since I can't even do my key combo to bring up steam overlay in melvor idle.

### Screenshots

If you want screen shots I can provide.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
