### ISSUE TITLE
[Bug]: Windows High Contrast Mode Hides UI Elements

### ISSUE THREAD

**Issue by batponies123** [MelvorIdle/melvoridle.github.io#2585]
### Describe the bug

When playing the game with Windows High contrast mode enabled, many UI elements are outright hidden. Just a few items I've found are:

- Combat health/attack bars
- Thieving health/action bars
- Action progress bars
- Combat XP progress bars
- Currently selected skill tab highlight

### Reproduction Steps

1. Enable any Windows HC theme
2. Launch the game
3. Load any character

### Expected behaviour

Key UI elements such as combat/thieving health and interval bars shouldn't be overwritten by HC settings.

### Screenshots

![HP](https://user-images.githubusercontent.com/22773773/188314374-c9adf50d-56cb-497b-add5-a70a43f4d77f.PNG)

![CombatXP](https://user-images.githubusercontent.com/22773773/188314383-f34df9dd-ab65-470c-980a-ecacc644094e.PNG)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
