### ISSUE TITLE
[Bug]: Steam doesn't recognize Melvor Idle being shut down

### ISSUE THREAD

**Issue by Zero-DotV** [MelvorIdle/melvoridle.github.io#2586]
### Describe the bug

After closing the game, Steam fails to recognize this, continuing to display the blue "stop" button instead of switching to the green "play" button. Clicking this button then turns it into a grey "stopping" button, which then stays stuck indefinitely, and can only be stopped by force shutting down steam using the task manager (a normal shut down fails because Steam is busy shutting down the game).

### Reproduction Steps

1. Start Melvor Idle on Steam
2. Exit Game

### Expected behaviour

After shutting down the game, the "stop" button should turn back into a green "play" button and allow the game to be started.

### Screenshots

![Screenshot (13)](https://user-images.githubusercontent.com/112882173/188474746-15f7f497-5638-45f6-841c-de29c5e57d27.png)
Steam prior to opening game.

![Screenshot (14)](https://user-images.githubusercontent.com/112882173/188474834-ba1e024b-7cb5-4996-91bf-5d77af9da3cd.png)
Steam when game is running (see icon in taskbar).

![Screenshot (15)](https://user-images.githubusercontent.com/112882173/188474886-331408d1-a807-4f2c-8179-5c9d32b3e8b1.png)
Steam after shutting game down (Note icon no longer in taskbar and blue stop button still active).

![Screenshot (16)](https://user-images.githubusercontent.com/112882173/188475087-7923e8dc-7429-4721-b163-81f9c3667952.png)
Steam after clicking "stop" button. It stays like this seemingly indefinitely.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by Zero-DotV** [comment]
The issue appears to have stopped as of this morning. I'll leave it up to the devs on whether to investigate further.

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
