### ISSUE TITLE
[Bug]: Non-Combat Skill View Toggle

### ISSUE THREAD

**Issue by Drockvaen** [MelvorIdle/melvoridle.github.io#2587]
### Describe the bug

When selecting to 'hide' Non-Combat skills via the toggle symbol, the option to toggle disappears with the non-combat skills requiring app restart to reopen the view.

### Reproduction Steps

Go to the menu.
Click the 'Hide' symbol for the non-combat skill list.
Attempt to reopen the non-combat skill list.

### Expected behaviour

The ability to toggle the non-combat skills back into view will not be an available option.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by Quest27** [comment]
I want to add to this bug report that I expierenced this bug on steam as well.

**Comment by FreshDillon** [comment]
Experienced this same issue just now!! At least I know how to rectify until patched, thank you

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.1.
