### ISSUE TITLE
[Translation Error]: Throwing Power Gloves

### ISSUE THREAD

**Issue by 098hgj** [MelvorIdle/melvoridle.github.io#2588]
### Which text in the game has a translation error?

The describe ofThrowing Power Gloves is "+20 Ranged Attack Bonus, +20 Ranged Strength Bonus, +15% of Maximum Hit added to Minimum Hit, and -25% Ammo Preservation when using Throwing Weapons."and in Chinese is"+20 远程攻击加成；+20 远程力量加成；提高最小伤害，提升量等同于最大伤害值的 15%；使用投掷武器时 -25% 弹药留存。"
It is  incorrect as "+20 Ranged Attack Bonus, +20 Ranged Strength Bonus, +15% of Maximum Hit added to Minimum Hit.  And -25% Ammo Preservation when using Throwing Weapons."The word 使用投掷武器时 in Chinese can not use like this
The word 使用投掷武器时 should be at first like "使用投掷武器时+20 远程攻击加成；+20 远程力量加成；提高最小伤害，提升量等同于最大伤害值的 15%； -25% 弹药留存"     as     "when using Throwing Weapon,+20 Ranged Attack Bonus, +20 Ranged Strength Bonus, +15% of Maximum Hit added to Minimum Hit, and -25% Ammo Preservation ."

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.

**Comment by TroyHawk** [comment]
> Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.
> 
> In the event this issue is still occurring, please open a new issue so we can address it.

This Localisation bug still exits and it misleads me.
Hope you to fix it soon :(
