### ISSUE TITLE
[Translation Error]: farming button

### ISSUE THREAD

**Issue by 098hgj** [MelvorIdle/melvoridle.github.io#2589]
### Which text in the game has a translation error?

![Snipaste_2022-09-07_15-26-26](https://user-images.githubusercontent.com/111255773/188815859-55536b49-b215-4fe1-8b07-85327d4872a3.png)
The circled place should be 种 or 种下 as verb part of speech,植物 is noun.

**Comment by Larry-Louis** [comment]
他们估计是把plant翻译出来，没搞清楚植物是对应的名词而不是动词。。。

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
