### ISSUE TITLE
[Bug]: Link for save char is Blank

### ISSUE THREAD

**Issue by LockerXm** [MelvorIdle/melvoridle.github.io#2590]
### Describe the bug

I've saved the link to load my char, and afterwards registered to save the files on Cloud.
When I logged in on game, I lost the current saves.
When I tried to Import the save, with the link URL, it does not work, no errors or warnings, it just don't bring the save.

When I tried to open the link on a page, to get the raw save, the page is completely blank.

Is there anyway to retrieve it? As I don't have access to the account anymore...

### Save Link

https://melvoridle.com/save/2oXUXNUU

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
