### ISSUE TITLE
[Bug]: Chicken Fight Tutorial/Potato Seed Tutorial Query

### ISSUE THREAD

**Issue by Invigorium** [MelvorIdle/melvoridle.github.io#2591]
### Describe the bug

Kia Ora (Hello)

When fighting a chicken in the tutorial on a free account via the web, I managed to find that despite defeating a chicken as per the requirement, it took two defeated chickens to actually complete the tutorial.

My other query/possible bug was that I usually have an eye for detail but didn't see if the potato seed icon was shown as a reward on the tutorial in regards to farming. It could have been and I just missed it but I just wanted to double check in case it was forgotten.

Cheers! Have a wonderful week ahead!

### Reproduction Steps

1. Kill chicken.
2. Chicken dies and tutorial is uncompleted.
3. Kill chicken #2 and chicken dies and tutorial is completed.

1. Potato Seed may not be appearing as a reward icon on tutorial on the free web version. (Could be wrong)

### Expected behaviour

Chicken should have died when killed the first time.

Potato seed icon is unclear whether I visually missed it or it wasn't there.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
