### ISSUE TITLE
[Spelling/Grammar]: Golbins should be Goblins?

### ISSUE THREAD

**Issue by Invigorium** [MelvorIdle/melvoridle.github.io#2592]
### What text is wrong?

Kia Ora (Hello)

Everywhere I see the text referring to goblins as golbins.

I'm unsure if this is a grammar mistake or intentionally spelt that way.

Cheers.

### What is the correct spelling or grammar?

Goblin.

**Comment by danieltaylor** [comment]
It's intentional :)  I never even noticed it myself until I saw someone else post about it here.
