### ISSUE TITLE
[Bug]: Offline progress message incorrectly states bank full

### ISSUE THREAD

**Issue by RockaJosh** [MelvorIdle/melvoridle.github.io#2593]
### Describe the bug

Came back online after 35 hours, the initial offline progress message stated that I could receive the raw chicken or feathers because my bank was full, even though there is 11 slots free.

### Reproduction Steps

1. Fight chickens (ranged)
2. Turn of fight whilst offline
3. Go offline (closing the app completely)
4. Return 35 hours later
5. Open app

### Expected behaviour

I would successfully loot chickens and feathers

### Screenshots

![Screenshot_20220911-070104_Melvor Idle](https://user-images.githubusercontent.com/93621230/189514688-eff6dea6-adea-4671-9f8f-9d602e10675c.jpg)

This is from loading the game a second time

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

2077

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
