### ISSUE TITLE
[Bug]: Offline progress with Marks

### ISSUE THREAD

**Issue by zachup100** [MelvorIdle/melvoridle.github.io#2595]
### Describe the bug

When you start a task, and allow it to progress offline. If you discover more than one mark when you come back, will repeat itself the amount of times you discovered a mark. I had discovered 20+ marks with offline progress and each one was being shown as one discovered.

Browser: OperaGX (Chromium-based)

### Reproduction Steps

Start a task, mine was woodcutting [Magic Tree]
Save your progress
Allow some time to pass, probably an hour?
When you return and if you have more than 1 mark, it'll repeat to tell you each mark you discovered

### Expected behaviour

I would assume only one would appear, instead of multiple.

### Screenshots

![opera_kqtPoS5yFx](https://user-images.githubusercontent.com/1534792/189904263-1ca9aaba-2961-4688-a7d2-29c5dc439f30.gif)

### Console output

![image](https://user-images.githubusercontent.com/1534792/189905235-c529f2bc-754e-43c0-8283-d3c13ad81fbc.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [x] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
