### ISSUE TITLE
[Bug]: [iOS] Cooked lobster does not get added to the bank

### ISSUE THREAD

**Issue by DavePeak** [MelvorIdle/melvoridle.github.io#2596]
### Describe the bug

Cooked lobster does not get added to the bank. The perfect version does. Whenever I cook lobster (iOS app), I can see how many items were cooked, but the current inventory amount displayed between brackets in the notification never increases and the same applies to the lobster inventory in my bank. I think that is a new issue to me, haven’t tested the issue with other fish or on the Steam version yet.

### Reproduction Steps

Cook lobster, the cooking completes, a notification is displayed to show the loot, but the regular cooked lobster never gets added to inventory

### Expected behaviour

Cooked lobster should be added to the bank

### Screenshots

![766FD343-AC8A-43BF-A85D-E177E2A3C3E5](https://user-images.githubusercontent.com/113786537/190864931-65623254-b2ab-4744-b2b2-c35b7956fca2.png)
![5F75615A-E284-4873-BB69-4C57667DDA5B](https://user-images.githubusercontent.com/113786537/190864932-bea34913-fded-4312-a067-e8654e97f6e8.png)
![23B49DEB-AE32-4C6D-A104-1184B506F50D](https://user-images.githubusercontent.com/113786537/190864933-74bb08f6-e792-404b-9bdf-4db73b213672.jpeg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2007

### Are you using any scripts or extensions?

No

**Comment by Volvary** [comment]
Would you happen to have the `Cooking Upgrade 1` from the Shop that auto-equips cooked food if they are already equipped?

**Comment by DavePeak** [comment]
Like the great philosopher Charles Leclerc famously said, I am stupid. Yeah, the lobster is equipped. Thanks.
