### ISSUE TITLE
[Bug]: <failed transfer off cooked items to bank slot

### ISSUE THREAD

**Issue by justforonecause** [MelvorIdle/melvoridle.github.io#2598]
### Describe the bug

while actively cooking the transfer of 40k+ (raw shrimp; cooked items should 2 til 4 times of that) items didn't get transfered to the bank 

### Save Link

https://melvoridle.com/save/iY74o0Sz

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This happens due to auto-equip food being ticked in Cooking.
