### ISSUE TITLE
[Spelling/Grammar]: 3x issues in Impending Darkness book 

### ISSUE THREAD

**Issue by jesbis** [MelvorIdle/melvoridle.github.io#2599]
### What text is wrong?

Three minor issues with the English text of the Impending Darkness storyline book:

1. "vice-like grip"
    - in American English (which the rest of the text appears to follow) this should be spelled "vise-like"
    
2. "You lose grip on reality"
   - this is missing the usual possessive adjective - e.g. "You lose **your** grip on reality"

3. "their own respective gods": 
   - "Gods" is consistently capitalized elsewhere, so probably should be here too

### What is the correct spelling or grammar?

1. "vise-like"
2. "You lose your grip on reality"
3. "own respective Gods"

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
