### ISSUE TITLE
[Bug]: Creating Summoning Tablet With Full Bank Eats Resources Without Giving Tablets

### ISSUE THREAD

**Issue by btj29** [MelvorIdle/melvoridle.github.io#2600]
### Describe the bug

Attempting to create a tablet with a full bank uses up the resources without giving back any tablets. Personally confirmed to happen for both Ent and Octopus Familiar, but I assume it will happen to any of the other familiars too.

### Reproduction Steps

1. Fill up bank leaving one space.
2. Buy Summoning Shards.
3. Craft Summoning Tablet.

### Expected behaviour

Either of the following two cases:

1. 
- [ ] If after crafting there would still be no bank space, the crafting should be blocked and not be allowed in the first place.
- [ ] If after crafting there would be available bank space (i.e. bank contains exact number of shards for craft, thus a slot is freed up after craft), tablet should be stored in bank.

2. If bank is full, crafting should be blocked and not allowed in the first place

### Save Link

https://melvoridle.com/save/m55VHlfQ

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by LeMazimer** [comment]
This happens while creating a dragon crossbow as well (personally encountered), i suspect it happens for any crafting (and possibly item upgrading)

**Comment by MelvorIdle** [comment]
This is an intended mechanic. The game creates the item, but it cannot fit into the bank which means it was lost (and wasted).
