### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by No1si** [MelvorIdle/melvoridle.github.io#2601]
### Describe the bug

despite the air mystic staff, air runes are consumed

### Expected behaviour

no rune consumption

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [x] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by ekuland** [comment]
Mystic Air Staff is only -7 to air rune costs.
If you were casting Wind Wave or Wind Surge, they cost more than the staff negates.
