### ISSUE TITLE
[Bug]: Game Size Small - Mobile Starting

### ISSUE THREAD

**Issue by DeepSeaCatz** [MelvorIdle/melvoridle.github.io#2602]
### Describe the bug

I realized that if you open the Melvor Idle just after being in the Recent Apps list(where you see all the current apps open on your phone), the game seems to take the same size of the App list and leaving white background. You must close the game and re-open to fix it.

Some time you're going through your apps and open the game too fast and this occur. I need to wait 2 seconds before opening the game to prevent this from happening.

### Reproduction Steps

1. Make sure the game is closed.
2. Open all the recent app list on Android.
3. Quickly go to your "desktop" and open Melvor Idle.

### Expected behaviour

I'm expecting that the game keeps the same size of my full screen, without trying to adjust to the size of the recent apps list.

### Screenshots

![Screenshot_20220923-114520_Melvor Idle](https://user-images.githubusercontent.com/114247596/192002797-96748fe2-9dee-4710-aabf-771b48d61763.jpg)

![Screenshot_20220923-120647_One UI Home](https://user-images.githubusercontent.com/114247596/192004673-0c04e65f-9c82-42e1-a2ed-773b596f480a.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
