### ISSUE TITLE
[Bug]: Game stuck in state where I can't do anything but manage items and farm

### ISSUE THREAD

**Issue by ericrtew** [MelvorIdle/melvoridle.github.io#2603]
### Describe the bug

I'm not able to mine/fish/woodcut or do any sort of combat. I'm able to do the goblin raid however. I have uninstalled and reinstalled the app and restarted it a dozen times.

### Save Link

https://melvoridle.com/save/GvnWFVCE

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by xanderput** [comment]
Try the solution in [this comment](https://github.com/MelvorIdle/melvoridle.github.io/issues/2563#issuecomment-1214361904). Believe it may help you.

**Comment by ericrtew** [comment]
That worked. Thanks.
