### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by Maksfrl** [MelvorIdle/melvoridle.github.io#2604]
### Describe the bug

The game keeps loading and when it shows me anything other than loading the savegame selection page is all buggy and I can't select a savegame.
![Loading screen](https://user-images.githubusercontent.com/114253174/192026829-b0b845e7-128f-4109-bb4e-0bc3e04183b5.png)
![Home screen 1](https://user-images.githubusercontent.com/114253174/192026860-6bc9b83f-3acb-4ec0-b006-72deaf1b2a4d.png)
![Home screen 2](https://user-images.githubusercontent.com/114253174/192026889-aed66f7f-33ba-46e7-92ac-b8ace5cfecbc.png)
![Home screen 3](https://user-images.githubusercontent.com/114253174/192026925-8d1ffaa9-e83c-4942-a69c-a2a16797b1ea.png)

### Reproduction Steps

I have no idea how I got here.

### Save Link

H4sIAAAAAAAAA9VYS3IcNwy9S6/pKYIEf75DTiDNQnGycFlWUiXHG5funveA7h6OPrZk2U5FrekGQRLElwT4Zfm8vJUWlpvl7UUMMaQqPQbJQdAQe+rYnyDJ8FVrjSI5Rxk2kuhjWH5fqfjEGBze2jMWOIy/xfiL0xDQCSLWSbpJAWnIpadCqEto9uWwUApeKVSymkMq0b65j9AKZ40YegIgZQCPwcoJ/Fb/1ri2df12/8Zq5I/hIoYHz4p9I/yPxs8G9wkeEyzzBJG5keeGzo0yN+rcmJeUeU2ZF03znDQPyxMHqzRy30rJ3pk2Ws3zuA03s8nZV8xsO60aXLPFreU2cgOp2S2bjdwybie3jtvGLbPapRjPMwM/6bFVXvBwfCyjwVNhO7W3xBgqPv3QXVfSyqH3OPY/8xq4uST2U0OPOdu3GMW/WnRQsVQr1WnuTlenm9PFaQSo8Iiwu7G4uxDNXBDRLF1FSmwKj05xs2o8sfMLNP5C6/xP14f6bcdLo7WeD+YuCAvV2ILSXFG0wRVi0lr6tJ4EPRQP+JewmUI8YD/Mj3Qh7ECxvlIP8LzAgL3fV9FHf6aI+rB7vGbZVz+p/Qyytgd8z6TviC5Oy6FTu8OeuTc/Af9AOfXHk/32ooV5RoY//bfe8wKOX8koA/hX8pte4Ikcnp7s5LGEk+YvHDTLl8vl9sP76+vL5W0Ml8vVu0/v/7pB4+af62u0P73/+Oftp6uPfwO1Z5Zp9Hy3hOXiiNcXQpfLb1dXH24vF4M/yyEesjUsQ0lwdG5EFSlZRziIpVqSLJVVO40rcydsoDBKYsa6UwZ/EWvbefiC3xG8C+cVbCff+HFssjV4HJ9+xzsXYFMbW56bffX/OHONfCIoyHXIPOKJrYRtt1aqAgcA0mqcIOVslDGkCKYJl4nLmclLg5RxCF/I1EBsGqY+DOlGrqSNAUXnAcUH4FArbcZX4gm0DegbMDZAok+GHWm9SBnADl+J3DTikFWWM87FhO5iDBtTHVz3syFpX8Lk1CJn3eoKqWdIkwTUoORy3lPXHrKSz3p24WSXTky8mtOZBUzSUc90m8TNGi2DZEpA2SPEGeNMnOQeJe0kxd2CoHv3hzlzsbQSyQQU2Zk3SDglcqdAR/pRGMeZYXFK6J/+lXXy7o88ZOpOF9rABk0IBJGy52aVUba924e/mQnAdRJZjE9yiKy0GkbjM1lUe+cStvMPEVs3smPr2ouzrz/wqLk0277+eCKR4aKsSvPwojW1LlYBFaT8sUarcXI0LXGfYhUktXUW1BsJK7jYBXv0YoUBftXGZlcgZGBJQZAWw46GArcTh9WqywJXCqy0xPBqqlCsoXOip7ZjdqMrtnZnt1XIAoMlLMDpxetVK7htRRaGSZ2ynO/+0lvIFL7aQMojYpywICIJlvfDvuYMDmgxoJBBB8qGQbHobovOFqxCZFeqToQzWz+B9QS2Hawr58o8iZqpJnF3UrwJSMNZwbuNDSqrZ8g0a5uQuy8qaa1kQa7YgRPXohYIRiz5HjshCMa01wxl55GVaS6pVWKrE5j6dJj76CC+KatI8aXoRjA8hTUmZIs+KRBb/APOpGi0AtAlklXPYifPhtMd6hvEKttB7/TbF1aXydxdeZsi3GXVHEhom4KOahPcymQebiTJXKdS3cEKenOtQD6zncjdgrmYqtwX1VSQbUxaYa9QI4Ip2ZWJllRsCaHi6d2CPZRWVfuaFsLqvqLuvXnlTVYdJ2v00uz6R3xti8T5HsUgVeuCkuqKydkcvb7yfdpzaTu4w7CtLne7O5gvxub9cL/Wic/dD7f3E1u2Sy739+V02pTdOX1cWWO8Bb/zGmHzcfGoWC+2qqw7u/x4UdatHQkdHA97gyUHWAhRzoRHDbx3RaP31nze0/wqiyTFnUfN1c8OhAeI/uiR8Zx5D1Cm18ewFnzjrGN7noM9GVvKveFv9tu8VDf3ON79C18of1YsFgAA

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

Yes

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
