### ISSUE TITLE
[Bug]: <title> Skill lock

### ISSUE THREAD

**Issue by Silinios** [MelvorIdle/melvoridle.github.io#2605]
### Describe the bug

Sometimes the last character I play is a character that is in adventure mode, if I close the app on that character and start playing on a different character, my skills will be locked like on adventure mode, and armor gets removed if the magic or range skill is not unlocked. All of the skills I have bought on the adventure mode character are unlocked on the other character as well. Resetting the game resolves this

### Reproduction Steps

1. Play a character in adventure mode
2. Close app while still playing adventure mode character
3. Open app (unsure of time needed to elapse before re-opening if that’s a factor)
4. Sign in to non adventure mode character

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
