### ISSUE TITLE
[Bug]: <title>Impending darkness

### ISSUE THREAD

**Issue by Brattens** [MelvorIdle/melvoridle.github.io#2606]
### Describe the bug

When i enter impending darkness the colors change But nothing more happens
![963A44EE-5A4F-4C10-9C80-2C004091235E](https://user-images.githubusercontent.com/114312632/192116166-d3865e31-bb7e-4409-a18e-1c9d609575db.png)

### Screenshots

![3BD72E70-54FA-4A8E-884D-2982248C894A](https://user-images.githubusercontent.com/114312632/192116180-5c17dc32-8d4f-4691-aed7-31a56e2f3d82.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?1341

### Are you using any scripts or extensions?

No

**Comment by Brattens** [comment]
Subversion 2077

**Comment by MelvorIdle** [comment]
Not a bug. You need to go into the slayer areas and continue the event from there.
