### ISSUE TITLE
[Bug]: Hardcore save gone

### ISSUE THREAD

**Issue by OkanAK** [MelvorIdle/melvoridle.github.io#2607]
### Describe the bug

While AFKing thieving with 3x Food slots equipped 1K Stacks each and auto equip food when depleted was active, I launched my phone to see the progress and everything showed that i received -2M GP and Items then it crashed. When i tried re launching the game my hardcore save had no trace of ever existing no perma death message nothing at all. I have been playing this account for months.

### Reproduction Steps

1. Opened phone to see Hardcore save missing
2. lunched PC version of Melvor
3. Showing No Hardcore Save

### Expected behaviour

I expected to lunch the game and see all the items i received, or even show me a error message on the save that i have been playing for months 

### Save Link

Missing its Empty

### Screenshots

![308958096_766624354409050_5119163132357894565_n](https://user-images.githubusercontent.com/17418384/193369369-fdbef738-6c79-4bb1-988a-559660ec206a.png)
![306898289_1100972774146216_8338401977949820491_n](https://user-images.githubusercontent.com/17418384/193369374-48bf0f03-cfea-4313-843d-989e3245c3f5.png)
![309364138_1984767388384283_2712289399878987047_n](https://user-images.githubusercontent.com/17418384/193369375-3b307531-f9da-40b4-a956-2099a75121be.jpg)
![309341220_1207258113169979_1706190603219979900_n](https://user-images.githubusercontent.com/17418384/193369377-a5f02a37-f6fe-472a-b918-51f37780206e.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

N/A

### Are you using any scripts or extensions?

No

**Comment by ekuland** [comment]
You died. Dying deletes cloud saves too.

**Comment by OkanAK** [comment]
Does it not leave any death messages?
