### ISSUE TITLE
[Bug]: <Bird nest potion>

### ISSUE THREAD

**Issue by loydhamilton** [MelvorIdle/melvoridle.github.io#2608]
### Describe the bug

I have the potion and can’t use the potion. It’s a level 1. I don’t know if it’s designed to be you can use it at level 3 but it doesn’t say it’s a crafting component.

### Reproduction Steps

Click potions tab at the top nothing shows while the potion is in the bank.

### Expected behaviour

Click potions tab at the top, bird nest potion shows while the potion is in the bank.

### Screenshots

![1F7AC811-DB14-4CF7-AB1E-4FAC6224501E](https://user-images.githubusercontent.com/75598514/193460763-d26f5039-d860-45c2-b7c9-52d3344ba406.png)
![CEDFCAAD-3F67-440A-B427-4CA924AFD46A](https://user-images.githubusercontent.com/75598514/193460765-3754208a-3ba7-4b04-b4f6-4a41a6ac2336.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by Silberdrachi** [comment]
Open the potions dialog on the woodcutting skill page. Potions are only visible on the skill they are intended to be used for.
