### ISSUE TITLE
[Bug]: Application has stopped responding 

### ISSUE THREAD

**Issue by Gajdascz** [MelvorIdle/melvoridle.github.io#2609]
### Describe the bug

My game continually crashes and is not playable at this point. The error Application has stoped responding pops up repeatedly untill I reset the game and get the error again.

### Reproduction Steps

Play the game. While performing an action in game switch menus or select items and upgrade or any other secondary action and I get the error

### Screenshots

![Screenshot_20221007-144936](https://user-images.githubusercontent.com/78930672/194631595-d4012bda-0b22-4402-9e9d-131880f21992.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

Latest

### Are you using any scripts or extensions?

No

**Comment by Guardmyrift** [comment]
I have this same exact issue. It's very annoying. On top of it, it seems all of my text has ever so slightly shrunk in size, and sometimes I have to boot the game up numerous times for it to load.

**Comment by Krackenbracken** [comment]
Same issue for the last month. It's gotten worse.  Every 2-3 seconds the error message pops up.  Close/wait/send feedback.  Error keeps popping up after the android app is closed.  Pixel 5 / android 13.

**Comment by Gajdascz** [comment]
Expansion fully broke my game. Training astrology and crashing before I can do anything else

**Comment by MelvorIdle** [comment]
Disabling and/or removing accessibility apps seems to be the common fix. Anything that attempts to take control of other apps tend to have issues with performance.

**Comment by Cbrupe90** [comment]
In my case I had the CCleaner app installed. Uninstallimg CCleaner fixed this issue for me.
