### ISSUE TITLE
A CLEAR button on the "Search bank..." field.

### ISSUE THREAD

**Issue by DAFTzippo** [MelvorIdle/melvoridle.github.io#261]
![image](https://user-images.githubusercontent.com/51213847/83237221-1dc6fa80-a195-11ea-84b0-868a9a8f787a.png)
a quality of life addition. Add a clear search field button to the "Search bank..." like a red X or a red button with CLEAR, both would be located as shown in picture.

It would make life easier when using the search bank feature.

**Comment by MelvorIdle** [comment]
This is being added to the upcoming update :)
