### ISSUE TITLE
Discord RPC fails to correctly set activity without discord/melvor being run as admin. 

### ISSUE THREAD

**Issue by sirsikes777** [MelvorIdle/melvoridle.github.io#2610]
### Describe the bug

Discord RPC fails to fails to correctly set activity without discord/melvor being run as admin and displays a basic "Playing Game for X time"

![unknown](https://user-images.githubusercontent.com/34659056/194679860-fd45b780-8b0e-4789-8c01-9dfbce9c6b47.png)

Once I run both as admin it displays the graphics/activity as it should yet got stuck in the character selection state. I waited for about 10 minutes and switched between several activities in game yet it did not update.

![unknown2](https://user-images.githubusercontent.com/34659056/194680074-067c6d9b-c0c3-479d-9a30-41a53c0aae03.png)

After restarting discord and melvor a couple times it has started working as intended. 

![Capture](https://user-images.githubusercontent.com/34659056/194680348-d9772311-374c-486a-8473-25f22e0f9149.PNG)

Edition	Windows 10 Pro
Version	21H2
Installed on	‎12/‎7/‎2021
OS build	19044.2006
Experience	Windows Feature Experience Pack 120.2212.4180.0

Discord Version: Stable 151638 (3ce0196) 

### Reproduction Steps

Run discord and melvor without admin elevation.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

2122

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
