### ISSUE TITLE
[Bug]: regular cooked Fanfish,shark, or manta ray not being added to my inventory as I cook them

### ISSUE THREAD

**Issue by Spifferoni** [MelvorIdle/melvoridle.github.io#2611]
### Describe the bug

When I'm cooking fanfish, shark, or manta ray and get an imperfect result, the resulting cooked fanfish, shark, or manta ray is not added to my inventory of which I have spaces available. On the bottom of the screen it shows "+1 or +2 (0)" everytime one is produced never adding one to my inventory but still consuming one raw fanfish, shark, or manta ray. This problem doesn't occur when the cook has a perfect result as the perfect fanfish, shark, or manta ray is still deposited normally. Nor does it occur with other fish types, only fanfish, shark, or manta ray. The regular fanfish, shark, or manta ray aren't added when logging back in after idling either even though the idle results page says some were produced.

### Reproduction Steps

1. Go to cooking
2. Active cook fanfish, shark, or manta ray
3. wait for cokking progress bar to fill
4. if result is not a perfect fanfish, shark, or manta ray then "+1 or +2 (0)" appears on the bottom indicating one or two fanfish, shark, or manta ray were produced but none were added to my inventory yet one raw fanfish, shark, or manta ray was still consumed

### Expected behaviour

I expected a regular fanfish, shark, or manta ray to be added to my inventory with every successful cook result but it only occurs with a perfect result and not a regular one.

### Save Link

https://melvoridle.com/save/NxG4ujb9

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2122

### Are you using any scripts or extensions?

No

**Comment by xanderput** [comment]
You probably own the upgrade that automatically equips food when cooking if it's equipped already.

You can toggle that upgrade on the cooking screen if you don't want that to happen.
