### ISSUE TITLE
[Bug]: Windows 11 BSOD - Bugcheck

### ISSUE THREAD

**Issue by Khuzvhan** [MelvorIdle/melvoridle.github.io#2612]
### Describe the bug

Here's the bugcheck analysis. I can't figure anything out of it unfortunately. but maybe it can be of use on dev side to know and prevent this smh. 

![image](https://user-images.githubusercontent.com/14275181/194714476-3eedde79-be99-49f8-8ebb-c827899486ba.png)

### Reproduction Steps

Happened while training Alt Magic casting Blessed Offering in background.

### Save Link

https://melvoridle.com/save/geDT3Hoc

### Console output

I play on steam app. no native console enabled afaik

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2122

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
