### ISSUE TITLE
[Bug]: Minimizng the non-combat skill list makes it disapear entirely 

### ISSUE THREAD

**Issue by Izzy4900** [MelvorIdle/melvoridle.github.io#2613]
### Describe the bug

When clicking the eye next to the non-combat heading the whole non-combat list disappears and I have to go back to the main menu to get it back

### Reproduction Steps

1. Click the eye
2. the list disappears 

### Expected behaviour

Obviously it should minimize and not disappear, the combat list works as intended but there's some bugginess too, see screenshot

### Screenshots

![bnxDayi](https://user-images.githubusercontent.com/76185567/194737811-f6dce48e-b8b1-4770-bf7a-3109f8b07ac9.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2122

### Are you using any scripts or extensions?

No

**Comment by bpeters132** [comment]
+1 to this on Pixel 7

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.1.
