### ISSUE TITLE
[Spelling/Grammar]: Description of Magic ray contains repeating word "damage".

### ISSUE THREAD

**Issue by Poite11** [MelvorIdle/melvoridle.github.io#2615]
### What text is wrong?

The description of the "Magic Ray" effect of the Cloudburst Staff says:

> [...] dealing 80% of your normal damage damage 5 times over 1.6s.

### What is the correct spelling or grammar?

>  [...] dealing 80% of your normal damage 5 times over 1.6s.

**Comment by MelvorIdle** [comment]
Fixed as of v1.1. Please open a new report if issue persists.
