### ISSUE TITLE
Cant see summoning progression %[Bug]: <title>

### ISSUE THREAD

**Issue by stickypaper9** [MelvorIdle/melvoridle.github.io#2617]
### Describe the bug

More of a QoL improvment than a bug -
Cant see summoning progression when doing combat/slayer in the Toggle Skill Progress drop down window. Would make sense to have it here as you level up summoning while doing combat. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

2122

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
