### ISSUE TITLE
[Bug]: <title>Summoning mark glitch

### ISSUE THREAD

**Issue by MEFERJONES** [MelvorIdle/melvoridle.github.io#2618]
### Describe the bug

Crafting mark is not unlocking in summoning tab after receiving the mark from crafting. 

### Reproduction Steps

Train crafting
Recieve mark
Check summoning tab
Still locked/not registering that a mark is received 

### Expected behaviour

Unlock mark in summoning after receiving the mark from skilling.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2129

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Fixed as of v1.1. Please open a new report if issue persists.
