### ISSUE TITLE
Stuck on Loading and Select Screen

### ISSUE THREAD

**Issue by EoinBuckley** [MelvorIdle/melvoridle.github.io#2620]
### Describe the bug

While playing on a phone (HONOR Play), when the game loads, it sends me to the 'Select your Character' screen for around half a second, before then jumping back to the loading screen before anything can be clicked. It will then load for around 3 seconds, before repeating the above. 
This hasn't occurred in my time playing before, for the last year or so.
I have tried clearing the cache and restarting the phone, but this hasn't solved the issue.
Aware this has happened to other players but unsure what the correct solution is.

### Reproduction Steps

1. Open the app.
2. Wait for the game to load onto the 'Select your Character' screen

### Expected behaviour

Allow me to select a character and load into the game.

### Screenshots

![Melvor 2](https://user-images.githubusercontent.com/115657784/195410951-189b7902-8bf7-45d4-bf57-744fcd3c6bc1.jpg)
![Melvor 1](https://user-images.githubusercontent.com/115657784/195410953-37997922-5c25-499d-83fe-874aeaa5ad5a.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

N/A

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Hello, can you provide this information:

1) Are you a grandfathered player
2) What version of the app are you using - the free one with IAP or the Paid Full version
3) Have you purchased the game on any other platform, like IOS or Steam?
4) What is your cloud username

**Comment by EoinBuckley** [comment]
Issue seems to have been resolved in the overnight patch, thank you for looking into this! Details below for your log record.

1. I am a grandfathered player
2. Paid Full version
3. Haven't purchased anywhere else
4. Cloud Username is Eoinbuckley

Thank you again, this is one of the best games I've ever played - being without it even for a few days was tricky!

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
