### ISSUE TITLE
[Bug]: Invalid SSL certificate 

### ISSUE THREAD

**Issue by brendannoble** [MelvorIdle/melvoridle.github.io#2621]
### Describe the bug

Upon launching the app I'm presented with a toast saying, Invalid SSL certificate although the app seems to work fine but the toast persists for awhile.

### Reproduction Steps

1. Launch the app

### Expected behaviour

No toast

### Screenshots

![Screenshot_20221012-202348_Melvor Idle](https://user-images.githubusercontent.com/2664312/195637598-59eebc88-b075-4711-baf8-c87da16dc898.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2138

### Are you using any scripts or extensions?

No

**Comment by F-Lambda** [comment]
Just piping in to say that this is still an issue on a fresh install. While I'm sure it works fine, it definitely leaves a bad first impression.

**Comment by nsbuman** [comment]
This is still an issue

Game version: V1.3.1
Subversion: 212035
Mobile app: Android
App version: 3.1.1
