### ISSUE TITLE
[Bug]: Nature's Call bugs

### ISSUE THREAD

**Issue by Nick-Ben** [MelvorIdle/melvoridle.github.io#2622]
### Describe the bug

Nature's Wrath Staff does not allow you to cast Natures Call

Nature's Call Staff does not get the +30% of Maximum Hit added to Minimum Hit from Nature's Blessing Ring.

### Reproduction Steps

1. Equip "Nature's Wrath Staff"
2. Click "View Spellbook"
3. See "Nature's Call" unavailable

And
1. Equip "Nature's Call Staff" and "Nature's Blessing Ring"
2. See "Minimum Hit (Normal Attack)" remainds 1

### Expected behaviour

Nature's Wrath Staff should be able to cast lower level Nature spells

Nature's Call Staff should get full benefit from Nature's Blessing Ring

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2140

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment]
These behaviors are both intended. Please re-read the descriptions on the items and spells as they match the in game behavior.
