### ISSUE TITLE
[Bug]: Game Not Performing Any Actions

### ISSUE THREAD

**Issue by Ezected** [MelvorIdle/melvoridle.github.io#2624]
### Describe the bug

Not allowing me to perform any skill/combat action. I can rearrange my bank and other non-skill actions but not collect resources or gain exp.

*EDIT: I was able to harvest my crop and replant it, but still can not perform other idle skills.

(also I have a combat simulator extension "Melvor Idle Combat Simulator Reloaded")

### Reproduction Steps

Perform any skill action. (chop a log, attack a monster)

### Save Link

https://melvoridle.com/save/PYckavVu

### Console output

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
style.css?2:1          Failed to load resource: the server responded with a status of 404 ()
index.js:2139 Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
analyzeImage @ index.js:2139
media/main/logo_no_text.svg:1          Failed to load resource: the server responded with a status of 404 ()
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
css:1          Failed to load resource: the server responded with a status of 403 ()
index.js:2139 Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
analyzeImage @ index.js:2139
cloud.js?2140:67 Connected to PlayFab successfully
2save.js?2140:42 Copied to clipboard successfully.
save.js?2140:79 set force reload to 0
combatManager.js?2140:1 Combat Manager Built...
raidManager.js?2140:1 Golbin Raid Manager Built...
save.js?2140:20 Loading Save Game...
save.js?2140:20 Save Game Loaded...
main.js?2140:6 Game Loaded
cloud.js?2140:187 updatePlayerTags
MICSR.js:26 MICSR: setting up util
MICSR.js:26 MICSR: setting up modifierNames
modifierNames.js:656 MICSR: no unknown modifiers detected!
modifierNames.js:656 MICSR: no non-existent modifiers detected!
MICSR.js:26 MICSR: AgilityCourse is waiting for Card
MICSR.js:26 MICSR: setting up Card
MICSR.js:26 MICSR: setting up CombatData
MICSR.js:26 MICSR: setting up Consumables
MICSR.js:26 MICSR: setting up DataExport
MICSR.js:26 MICSR: Import is waiting for Import
MICSR.js:26 MICSR: setting up Import
MICSR.js:26 MICSR: setting up Loot
MICSR.js:26 MICSR: setting up Plotter
MICSR.js:26 MICSR: setting up Menu
MICSR.js:26 MICSR: Simulator is waiting for SimEnemy
MICSR.js:26 MICSR: Simulator is waiting for SimManager
MICSR.js:26 MICSR: Simulator is waiting for SimPlayer
MICSR.js:26 MICSR: setting up SimEnemy
MICSR.js:26 MICSR: setting up SimManager
MICSR.js:26 MICSR: setting up SimPlayer
MICSR.js:26 MICSR: setting up TabCard
MICSR.js:26 MICSR: App is waiting for AgilityCourse
MICSR.js:26 MICSR: App is waiting for Simulator
MICSR.js:26 MICSR: main is waiting for App
firemaking%20agility.svg:1          Failed to load resource: the server responded with a status of 403 ()
MICSR.js:26 MICSR: setting up AgilityCourse
MICSR.js:26 MICSR: setting up Import
MICSR.js:26 MICSR: setting up Simulator
MICSR.js:26 MICSR: setting up App
MICSR.js:26 MICSR: setting up main
cloud.js?2140:67 Connected to PlayFab successfully
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
css:1          Failed to load resource: the server responded with a status of 403 ()
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
index.js:2139 Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
analyzeImage @ index.js:2139
DevTools failed to load source map: Could not load content for chrome-extension://hnfanknocfeofbddgcijnmhnfnkdnaad/content.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
combatManager.js?2140:1 Combat Manager Built...
DevTools failed to load source map: Could not load content for https://melvoridle.com/requestProvider.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
MICSR.js:26 MICSR: Melvor Idle Combat Simulator Reloaded v1.6.10 loaded.
style.css:1          Failed to load resource: the server responded with a status of 404 ()
css:1          Failed to load resource: the server responded with a status of 403 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
cloud.js?2140:11 Synchronising with Cloud

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2140

### Are you using any scripts or extensions?

Yes

**Comment by xanderput** [comment]
Try the solution in [this comment](https://github.com/MelvorIdle/melvoridle.github.io/issues/2563#issuecomment-1214361904). Believe it may help you.

**Comment by Ezected** [comment]
> Try the solution in [this comment](https://github.com/MelvorIdle/melvoridle.github.io/issues/2563#issuecomment-1214361904). Believe it may help you.

Thank you so much, this was it!
