### ISSUE TITLE
[Bug]: TypeError: undefined is not an object (evaluating 'mark.masteryID')

### ISSUE THREAD

**Issue by utkuDAT** [MelvorIdle/melvoridle.github.io#2625]
### Describe the bug

After run some "game.summoning.discoverMark(Summoning.marks[Summons.Dragon]);" command from console. now my game is throwing error and it is not saving neither local nor cloud.

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/3123846/195983033-700f7939-0f2a-44bd-ac8b-23d4668910fb.png">

### Save Link

https://melvoridle.com/save/z3Vq17sv

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [X] Safari
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2140

### Are you using any scripts or extensions?

No

**Comment by utkuDAT** [comment]
any update ? I cannot play my save for 3 days

**Comment by coolrox95** [comment]
We are not responsible for you breaking your saves due to improper use of the console or mods. It is up to you to back up your save before experimentation.
