### ISSUE TITLE
Account has been reverted to free version

### ISSUE THREAD

**Issue by LarkLaser** [MelvorIdle/melvoridle.github.io#2626]
### Describe the bug

My account was reverted to the free version last night.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

V1.0.5

### Are you using any scripts or extensions?

No

**Comment by LarkLaser** [comment]
![image](https://user-images.githubusercontent.com/115890491/196006520-985c1188-d045-49bd-8be6-bceeed9922cb.png)

Unsure how to link my account.

**Comment by mm413** [comment]
Facing the exact same issue, just noticed - 1.0.5 on IOS

**Comment by MelvorIdle** [comment]
Here's a few solutions to try:

1) Ensure the game was not refunded. The game checks this and will revert to the free version
2) Make sure the account used for Google Play or the App Store is the same one used to buy the game. The game authenticates with the app stores to retrieve the active purchase on the currently signed in account.

If you are grandfathered, let me know.

**Comment by Mohare30** [comment]
I am having the same issue. I verified my account shows the payment for the full version on 10/07 and no refund. I downloaded an up date today and signed in, now it doesn’t show I have the full version of the game.

**Comment by MelvorIdle** [comment]
> I am having the same issue. I verified my account shows the payment for the full version on 10/07 and no refund. I downloaded an up date today and signed in, now it doesn’t show I have the full version of the game.

Is the account used on your phone itself the same one that was used to purchase the game?

**Comment by Tigui615** [comment]
Same probleme here but i was grandfathered

**Comment by MelvorIdle** [comment]
> Same probleme here but i was grandfathered

If you are grandfathered then be sure to have signed into the correct Melvor Cloud account. If you are not signed in then it will show the free version.

**Comment by Mohare30** [comment]
Yes I play on the same phone I made the purchase on.

**Comment by Mohare30** [comment]
My game is actually still running the agility skill which is showing I don’t even have access to right now. Is there any update on this issue?

**Comment by LarkLaser** [comment]
> Here's a few solutions to try:
> 
> 
> 
> 1) Ensure the game was not refunded. The game checks this and will revert to the free version
> 
> 2) Make sure the account used for Google Play or the App Store is the same one used to buy the game. The game authenticates with the app stores to retrieve the active purchase on the currently signed in account.
> 
> 
> 
> If you are grandfathered, let me know.

I should be grandfathered in.

**Comment by MelvorIdle** [comment]
Grandfathered players - make sure you are logged into the correct Cloud account. It will not load unless you are.

I have just tested using a grandfathered account on both iOS and Android apps, and can access the full game perfectly fine.

Those with purchase issues on iOS - if you are still having issues then try using the Restore Purchases button at the bottom of the character selection screen.

**Comment by LarkLaser** [comment]
> Grandfathered players - make sure you are logged into the correct Cloud account. It will not load unless you are.
> 
> 
> 
> I have just tested using a grandfathered account on both iOS and Android apps, and can access the full game perfectly fine.
> 
> 
> 
> Those with purchase issues on iOS - if you are still having issues then try using the Restore Purchases button at the bottom of the character selection screen.

Logged out and back into cloud account still without full version. Nothing seems to be working on my end and I've been playing consistently for 340 day (According to the account age). I thought I would have been grandfathered in when all that took place.

**Comment by LarkLaser** [comment]
After this mornings patch about half of my items are "?". Lol things seem to be getting worse.

**Comment by MelvorIdle** [comment]
THe question marks are simply due to how the game data is loaded now. It's a save preservation function so downgrades don't destroy saves.

I assume you have a different issue as we managed to fix the grandfather issue earlier with help from the community.

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
