### ISSUE TITLE
[Bug]: Character won’t do anything

### ISSUE THREAD

**Issue by Njtroy1** [MelvorIdle/melvoridle.github.io#2627]
### Describe the bug

When I returned to play earlier today, my character had stopped playing.  I was idling slayer tasks at the time.

Now, I cannot do any task at all, neither combat nor skills.  I am using the IOS app on my iPad.

I have tried:
- changing my slayer task
- Reloading my character from the cloud save
- Switching from slayer to woodcutting, fletching and other skill tasks.
- Playing on a browser (still on my iPad, but in the browser)
- Reloading the character to my iPhone
- Logging out & logging back in again
- Deleting and restoring the app

None of these has made any change in the behavior.

### Reproduction Steps

No error produced, just inaction.  See a above for attempts to recover.

### Expected behaviour

Do anything.

### Save Link

https://melvoridle.com/save/gratkoyg

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2142

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
We cannot reproduce this bug. If the issue continues, please open a new issue with extra details if possible.
