### ISSUE TITLE
[Bug]: full hp

### ISSUE THREAD

**Issue by Vaellan** [MelvorIdle/melvoridle.github.io#2629]
### Describe the bug

My health is stuck at full, even if I get hit, say -13 it immediatly +13's simultaneously.

### Reproduction Steps

Haven't reproduced it but it happened right after I pressed " new task " for the slayer.
Clicked " go to enemy " ( it happened to be a cow ) and the bug presented itself.

### Expected behaviour

Make it so it does not autorefill hp to max.

### Screenshots

![melvor](https://user-images.githubusercontent.com/116047143/196316713-9f2af354-7f7d-4120-8d14-20bb19a7e7fe.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

(?2143)

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
We cannot reproduce this bug. If this does occur again, please open a new issue with extra details if possible.
