### ISSUE TITLE
[Translation Error]: <title>

### ISSUE THREAD

**Issue by kengods** [MelvorIdle/melvoridle.github.io#2631]
### Which text in the game has a translation error?

![translate](https://user-images.githubusercontent.com/57219738/196378264-764890d6-bf8f-4e00-a295-f6ac281b718c.png)

There are some problems with the Chinese localization of the town system, I like this game very much, I hope it can not be troubled by the language

**Comment by iliveor** [comment]
Same thing in Russan language.
