### ISSUE TITLE
[Bug]: Steam Version failing to Validate Purchases when launched without Steam

### ISSUE THREAD

**Issue by Mantissa64** [MelvorIdle/melvoridle.github.io#2632]
### Describe the bug

Launching Melvor outside of Steam now hangs on "Validating Purchases" rather than dropping the player into the Character Select page.

### Reproduction Steps

Launch "Melvor Idle.exe" directly from File Manager rather than through Steam.
It does not matter if steam is open or not.

### Expected behaviour

Melvor launches and successfully Validates Purchases and drops the player off on the character select screen.

### Save Link

https://melvoridle.com/save/pvfsJJ2Z

### Screenshots

![image](https://user-images.githubusercontent.com/11732224/196387247-a7de9ebb-0987-4a89-955e-a18ec04c811a.png)

### Console output

I can't get console to open.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4377

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This is intended. It needs to run through steam to validate that you own the game.

**Comment by wking23** [comment]
> This is intended. It needs to run through steam to validate that you own the game.

Perhaps a message indicating that then? Obviously low prio. love what the update is bringing keep up the great work
