### ISSUE TITLE
Cant Complete Easy Township task.[Bug]: <title>

### ISSUE THREAD

**Issue by Riceeater27** [MelvorIdle/melvoridle.github.io#2633]
### Describe the bug

The task where you need 25 of 3 types of potion cant be turned in if you have a high mastery for controlled heat potion. It requires T 1 potion but i can only make t2 because of my mastery.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?43558

### Are you using any mods?

No

**Comment by Riceeater27** [comment]
> You can use Herblore Potions to get a chance at random tier potions each time you make a potion.

im sorry i dont quite follow. how does one use a potion to get a a random chance at a potion?

**Comment by 47Y** [comment]
The Herblore Potion gives you a +X% chance to receive a random tier of the same potion each time you make a potion. By using that, you are able to get any tier potion at a lower chance. In this case, you can use it to get lower tier potions than you can make.
