### ISSUE TITLE
[Bug]: Astrology Modifiers at 0

### ISSUE THREAD

**Issue by Tungatta** [MelvorIdle/melvoridle.github.io#2635]
### Describe the bug

After the new update, all of my astrology modifiers are now at 0. 

Please see attached screenshot.
![melvor idle astrology bug 1](https://user-images.githubusercontent.com/58137377/196402362-99316856-4620-40d8-b0d8-b5e362b013b6.png)

### Screenshots

![melvor idle astrology bug 1](https://user-images.githubusercontent.com/58137377/196402362-99316856-4620-40d8-b0d8-b5e362b013b6.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4377

### Are you using any mods?

Yes

**Comment by 47Y** [comment]
The Astrology modifier system was completely rewritten. With that update, you should have received a refund of all dust you have spent and modifiers were reset so you can buy them with the new system.

**Comment by Tungatta** [comment]
Thank you that's great to know! Should of fully read the changelog..
