### ISSUE TITLE
[Bug]: game interface error in ios

### ISSUE THREAD

**Issue by Azreal3213** [MelvorIdle/melvoridle.github.io#2636]
### Describe the bug

I can't choose cloud save

### Screenshots

![0AB44F14-F963-4B16-961E-82748B513BF5](https://user-images.githubusercontent.com/116075748/196407268-f75ff6f2-a124-450a-8218-d66ee75526e9.png)
![1CBA1927-5C00-4E8F-B3EF-A3F2B2236E28](https://user-images.githubusercontent.com/116075748/196407283-11755eaf-ef6c-4f2e-984d-280bb51aa805.png)
![Uploading 2B40E22A-FDD5-4148-A90F-2CB3379E0B33.png…]()

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

can't see that

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Please update your iOS to a version later than iOS 14
