### ISSUE TITLE
[Bug]:  Charge Stones of Rhaelyx is used when training Astrology

### ISSUE THREAD

**Issue by sramble** [MelvorIdle/melvoridle.github.io#2637]
### Describe the bug

Actions that do not consume materials (such as gathering skills) should not ever destroy Charge Stones.

### Screenshots

![image](https://user-images.githubusercontent.com/116075787/196407210-519deefb-a5da-485a-b31a-7d708af3a25f.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

4377

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Hotfix applied to the game - V1.1 (?4427)
