### ISSUE TITLE
[Bug]: <title>The problem that the PC still displays the full version of the game for refund after purchase

### ISSUE THREAD

**Issue by boluofei666** [MelvorIdle/melvoridle.github.io#2638]
### Describe the bug

Since the new dlc was launched on October 20, we tried to operate it after refunding. Now we have feedback on the problems we found.
Since the game has not been online certified, the game will be refunded after purchase, and the local file can still experience the full version of the game. It is recommended to change it to online verification.

### Reproduction Steps

1. buy game
2.Download Games
3.Create account and role
4.refund
5.Start from a local file on your computer

### Expected behaviour

Influence the sales of games and new dlcs

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4377

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
We believe this issue is now hotfixed.

**Comment by boluofei666** [comment]
I have bought the game again at a discount, but now the web version and mobile version show incomplete versions.







在 2022-10-31 13:51:53，"Melvor Idle" ***@***.***> 写道：

关闭#2638已完成。

-
直接回复此电子邮件，在 GitHub 上查看或取消订阅。
您收到此消息是因为您创作了线程。Message ID: ***@***.***>
