### ISSUE TITLE
[Bug]: cannot prioritize workers in townships 

### ISSUE THREAD

**Issue by KuAwMa** [MelvorIdle/melvoridle.github.io#2639]
### Describe the bug

I am unable to allocate my workers when trying to complete the beginner tasks within my township. Attempted to prioritize workers towards my woodcutters camp highlights the icon and initiates the prompt message but there is no way to actually allocate. 

### Reproduction Steps

1. Go to the township tab. 2. Be sure to have a resource such as a woodcutters camp purchased. 3 attempt to allocate workers by tapping on the wood icon towards the top of the initial screen, directly underneath the village gold. 

### Expected behaviour

After tapping on the wood icon, I perhaps expected a counter or number pop up in order to allocate or reallocate workers.

### Save Link

https://melvoridle.com/save/1H370Vun

### Screenshots

![D5D3A2D3-B64F-4692-8EBB-7F96A7FADE67](https://user-images.githubusercontent.com/116080078/196420474-b0e6cfb6-46e1-442a-ac7d-c235c1d2a94a.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4377

### Are you using any mods?

No

**Comment by 47Y** [comment]
Prioritizing a resource will cause new workers to go there first. There is no way to reallocate current workers without removing job slots where they are already working.

**Comment by KuAwMa** [comment]
But workers are not going to the desired resource. Nothing is being produced by the township. Therefore, I cannot progress.

**Comment by MelvorIdle** [comment]
Progress and changes only occur when you tick.

Prioritizing a resource means all NEW workers will go there first. Current workers do not change jobs.
