### ISSUE TITLE
[Bug]: Skilling outfits not on Quick-Equip

### ISSUE THREAD

**Issue by jamie0910** [MelvorIdle/melvoridle.github.io#2640]
### Describe the bug

Quick-Equip menu doesn't show bought skilling outfits
Have only tested the first 2 woodcutting outfit pieces

### Reproduction Steps

Purchase Woodcutting skilling outfit
Navigate to Woodcutting quick-equip menu
Can't see outfit

### Expected behaviour

After purchasing skilling outfit pieces they should be avaliable in the quick-equip menu

### Screenshots

[[[65rUXvTSrr2Vtdx](https://gyazo.com/a5a8fe537f1584995be64235af919bf2)](https://gyazo.com/a5a8fe537f1584995be64235af919bf2)](https://gyazo.com/a5a8fe537f1584995be64235af919bf2)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

4377

### Are you using any mods?

No

**Comment by 47Y** [comment]
Other than Skillcapes, items are not automatically added to the quick equip menu. You can add items yourself from the bank by selecting the item, going to the Item Settings tab, and toggling the skill(s) you would like it to appear in.
