### ISSUE TITLE
[Bug]: Can't sign in

### ISSUE THREAD

**Issue by Githubisawaste** [MelvorIdle/melvoridle.github.io#2641]
### Describe the bug

Cannot sign in via the steam or chrome browser versions of the game. Have tried repairing game files, re-installing, restarting PC, reseting password.

### Reproduction Steps

1. Load game
2. Attempt sign in
3. Sign in fails

### Expected behaviour

Sign in works

### Console output

Failed to load resource: the server responded with a status of 404 ()
cloudManager.js?4377:193 Authenticated w/ Melvor Cloud: false
cloudManager.js?4377:193 Authenticated w/ PlayFab: false
cloudManager.js?4377:193 Initiating sign in
cloudManager.js?4377:193 Initiated login to Melvor Cloud
cloudManager.js?4377:193 Logging in to Melvor Cloud via POST
/cloud/api/login.php:1          Failed to load resource: the server responded with a status of 401 ()
cloudManager.js?4377:193 Login failed.
cloudManager.js?4377:193 Login failed
style.css:1          Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
cloudManager.js?4377:193 Initiating sign in
cloudManager.js?4377:193 Initiated login to Melvor Cloud
cloudManager.js?4377:193 Logging in to Melvor Cloud via POST
cloudManager.js?4377:253          POST https://melvoridle.com/cloud/api/login.php 401
(anonymous) @ cloudManager.js?4377:253
loginToMelvorCloudViaPOST @ cloudManager.js?4377:252
(anonymous) @ cloudManager.js?4377:208
(anonymous) @ language.js?4377:5
__awaiter @ language.js?4377:2
loginToMelvorCloud @ cloudManager.js?4377:207
formElements.signIn.submit.onclick @ cloudManager.js?4377:121
cloudManager.js?4377:193 Login failed.
cloudManager.js?4377:193 Login failed

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

Cannot see without signing in

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Please ensure you are using the correct username (and not email) to log in.

**Comment by MelvorIdle** [comment]
Resolved in Discord
