### ISSUE TITLE
[Bug]: Stone value not updating by a cycle

### ISSUE THREAD

**Issue by ItalodeadBR** [MelvorIdle/melvoridle.github.io#2642]
### Describe the bug

The stones are not updating when i click to spend a cycle (my production should be 156,15 /t). 

Some informations:
Map 1
No affiliation
Population around 120
5 Mines on Mountains

### Reproduction Steps

i doenst exactly know the steps, but happened after i changed to work priority to the stone and updated the cycle.

### Expected behaviour

Should update the stone value after spending a cycle

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4377

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Please ensure you have enough storage to fit the Stone.

**Comment by ItalodeadBR** [comment]
Ok, saw it now. It try to store the food first, so even if you have storage for the stone production, it doens´t store unless you have storage for the food production(I didn´t tested it but i think it should have storage for wood and planks productions too) and the stone production.
