### ISSUE TITLE
[Bug]: Mastery pools reset for some skills, GP set to 0

### ISSUE THREAD

**Issue by dmei4380** [MelvorIdle/melvoridle.github.io#2643]
### Describe the bug

All Mastery (Item and pool) has been reset (mastery and item to 0XP) for Fletching, Crafting, Runecrafting, Herblore, Agility, Summoning, and Astrology, as well as losing 10B GP (reset to 0). My Account recently completed 100% of the game (2 or 3 months before the expansion) and has been working towards level 120 everything. All my skill levels are correct and up to date, however mastery for a lot of skills has been entirely wiped.

### Reproduction Steps

1. go to completion log
2. view mastery
3. notice all above skills show 1.01%

### Expected behaviour

All should be at or near 100% with the added items still needing mastered.

### Save Link

https://melvoridle.com/save/tReiHwXS

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4390

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
We have added a small hotfix to the game  - please confirm if anything has changed.

Although I will note that if your save was affected by this, I'm not 100% sure the levels will be restored.
