### ISSUE TITLE
[Bug]: Perfect beef needs an "upgrade" button for the easy task.

### ISSUE THREAD

**Issue by l3vines** [MelvorIdle/melvoridle.github.io#2646]
### Describe the bug

Perfect beef needs an "upgrade" button for the easy task.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

4391

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Hotfix applied to the game - V1.1 (?4427)

**Comment by l3vines** [comment]
Apple pie has the same issue.
