### ISSUE TITLE
[Bug]: Hardcore save broken upon loading

### ISSUE THREAD

**Issue by bombazzzo** [MelvorIdle/melvoridle.github.io#2647]
### Describe the bug

After the new update, loading an old cloud save for my Hardcore character showed some errors, and forced the game to close. Upon reopening, my character was now named "Insubordinate" and has all of their skills locked as if they were and Adventure Mode character. My bank has been reset as well, leaving only 12 slots whereas I had a max HC bank. Skills are also not able to be unlocked like an AM character, requiring "infinite" gold to unlock.

### Reproduction Steps

1. Log in to Hardcore Save
2. Cannot progress

### Expected behaviour

Log in to old HC save, and continue progressing.

### Save Link

https://melvoridle.com/save/73jlQ3CX

### Screenshots

![HC broken 3](https://user-images.githubusercontent.com/92332180/196462909-8274c7c1-f71f-490d-a149-8fd54686956f.png)
![HC broken 2](https://user-images.githubusercontent.com/92332180/196462912-142e3930-554a-45d7-8486-9f80ec07f3e6.png)
![HC Broken 1](https://user-images.githubusercontent.com/92332180/196462915-072227bb-6845-43ba-87b2-e9902c0a3697.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4392

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
We believe the issue that caused this has now been hotfixed.
