### ISSUE TITLE
[Bug]: Potions being added instead of lost on tick with citizens over 55

### ISSUE THREAD

**Issue by Regentmango7** [MelvorIdle/melvoridle.github.io#2648]
### Describe the bug

In township, potions are added by 1 instead of removed when having 6 citizens over 55.  Seems like it should be -6, but it is instead showing as a -(-1) and is adding 1 potion although I do not have anyone working in my potion stations.

### Expected behaviour

I believe that this should be a -6 since I have 6 citizens over 55.

### Save Link

https://melvoridle.com/save/hh1zRC38

### Screenshots

![32976C47-B43C-40FC-9826-34030AFBE3EB](https://user-images.githubusercontent.com/79233592/196461907-ba7c89c0-a8ff-41f3-befd-986d84b1182f.png)
![A0B7E1AD-312F-4883-B321-BF7D9FE9A5A3](https://user-images.githubusercontent.com/79233592/196462122-df2ec2f8-81a6-4740-84a5-8b2e399b62d1.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4392

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Township has now been reworked as of v1.1.2
