### ISSUE TITLE
[Bug]: JSON object as Total Levels displayed on Steam Friends

### ISSUE THREAD

**Issue by EntOfMD** [MelvorIdle/melvoridle.github.io#2649]
### Describe the bug

Before the latest update, the correct skill level was displayed on Steam Friends. But with the new update (idk, haven't played on steam for awhile), it's displaying "Standard Mode ([object Object] Total Level)"

### Reproduction Steps

1. Start Steam
2. Run Melvor Idle
3. Open Friends & Chat

### Expected behaviour

It should display the current total level

### Screenshots

[https://ibb.co/jyVzhKY](https://ibb.co/jyVzhKY)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4392

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Hotfix applied to the game - V1.1 (?4427)
