### ISSUE TITLE
[Bug]: Clue Chasers Insignia not given

### ISSUE THREAD

**Issue by GarrettLoo** [MelvorIdle/melvoridle.github.io#2650]
### Describe the bug

I followed the wiki and move the six items in the left bank, but the Clue Chasers Insignia didn't appear. I tried it on Chrome and Steam, didn't work. I also tried swap two of the items and swap them back.

### Save Link

https://melvoridle.com/save/aiCO6bpv

### Screenshots

![image](https://user-images.githubusercontent.com/65524408/196477252-45c2ae47-bd85-46ab-92d1-7f9665e17324.png)
![image](https://user-images.githubusercontent.com/65524408/196477457-9061d20c-f42a-4392-9979-9918ed703b70.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4392

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was hotfixed as of v1.1 (?4516).
