### ISSUE TITLE
[Bug]: Township buildings sometimes get built in wrong biome

### ISSUE THREAD

**Issue by GabrielPaquette** [MelvorIdle/melvoridle.github.io#2651]
### Describe the bug

When building some township buildings, it gets built in the wrong biome. For example when creating a fisherman's dock in the Water biome, it was instead created in the Swamp biome.

### Reproduction Steps

Not sure the exact steps to reproduce, I don't have enough resources to fully test but it think it has something to do with a stale state when changing between Town and Build. You'll know it happened if the building count doesn't increment, but resources are taken when you tap to build something.

### Expected behaviour

The building should be built in the currently selected biome.

### Save Link

https://melvoridle.com/save/K2VE0jAm

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4377

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Looking at the save - you simply had "Swamp" selected in the Build option and proeeded to place the Fishing Dock there.
