### ISSUE TITLE
[Bug]: Item stats are comparing to the wrong Equipment Set

### ISSUE THREAD

**Issue by Homlix** [MelvorIdle/melvoridle.github.io#2653]
### Describe the bug

The item stats comparison is looking at your equipped Equipment Set, not the one you selected in the item details view.

### Reproduction Steps

Steps to reproduce
1. Go to any item that has combat stats
2. Select an Equipment Set that you don't have equipped
3. Tap "View Item Stats"
4. Notice the + / - value comparison is looking at your equipped Equipment Set, not the one you selected in the item details view

### Expected behaviour

The item stats should compare to the selected Equipment Set, not the set you currently have equipped.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4395

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was fixed as of v1.1.1 (?4999).
