### ISSUE TITLE
[Bug]: When cooking i do not receive the cooked item

### ISSUE THREAD

**Issue by MickTheKey** [MelvorIdle/melvoridle.github.io#2654]
### Describe the bug

When cooking beef or chicken unless it is a perfect cook i do not receive the normal item in my bank even when cooked. It is not in stockpile either. Or my current equipped food. It just disappears 

### Reproduction Steps

Cook beef or chicken

### Expected behaviour

The item will cook and show it has been added to bank but does not produce itself in the bank. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4395

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
You most likely have the auto equip enabled. Double check it is disabled so the item can be added to your bank.
