### ISSUE TITLE
[Bug]: slayer tasks in golbin raid

### ISSUE THREAD

**Issue by catkit08** [MelvorIdle/melvoridle.github.io#2655]
### Describe the bug

the slayer task window now shows up in the golbin raid, although clicking jump to enemy doesnt do anything and rerolling a task gets stuck trying to find a new task until the raid is paused or ended

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4395

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was hotfixed as of v1.1 (?4465).
