### ISSUE TITLE
[Bug]: item pickups

### ISSUE THREAD

**Issue by catkit08** [MelvorIdle/melvoridle.github.io#2656]
### Describe the bug

when the popup for collecting an item appears, if it displays the item name (ex 1 coal ore) it displays without the space (ex 1coal ore)

### Screenshots

![Screenshot 2022-10-18 124035](https://user-images.githubusercontent.com/80298027/196491514-99e531f5-3bad-4c3b-a3fc-8fb7a6d52553.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4395

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was hotfixed as of v1.1 (?4465).
