### ISSUE TITLE
[Bug]: Township tasks don't live-update resource counts

### ISSUE THREAD

**Issue by nmcspadden** [MelvorIdle/melvoridle.github.io#2657]
### Describe the bug

When generating resources that would satisfy a Township task, the Township task screen does not update the resource counts available as they are being generated in the background.

Example:
Township Hard task to give 1000 whales to the town. Start cooking Whales, then go back to the Township Hard Tasks screen. As whales are being cooked, the number of whales you currently have (if it is under the amount required, in this case below 1000) does not update.

### Reproduction Steps

1. Go to Township tasks
2. Pick a township task resource that requires you to generate some resource, such as cooking Whales to turn in
3. Start cooking whales
4. Go to the Township task page 
5. Amount of whales in inventory does not update as they are generated

### Expected behaviour

The number of whales to turn in should increment up as they are generated. It currently requires you to go to a different screen and back to update it.

### Save Link

https://melvoridle.com/save/ZdUGYxlX

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4395

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Township has now been reworked as of v1.1.2
