### ISSUE TITLE
[Translation Error]: Superior Cape Of Completion

### ISSUE THREAD

**Issue by SirRedan** [MelvorIdle/melvoridle.github.io#2658]
### Which text in the game has a translation error?

![Melvor_Idle_MmhzqHegp7](https://user-images.githubusercontent.com/16778881/196504261-ec194be6-633f-4a0b-a3ce-6744e1f2bacf.png)

system region: Japan
Regional format Norwegian Bokmål (Norway)
system language: english(US)

**Comment by coolrox95** [comment]
Issue was hotfixed.
