### ISSUE TITLE
[Bug]: Certain items not showing up in the Quick Equip menu 

### ISSUE THREAD

**Issue by BlackThundxr** [MelvorIdle/melvoridle.github.io#2659]
### Describe the bug

Most items and some skillcapes don't show up in the Quick Equip Menu. I'm using Opera GX and iOS 15.6

Some of the items that don't show up for me are:

Skillcapes
-Thieving
-Herblore
-Astrology

Items
-Lumberjack's Top (Woodcutting)
-Bob's Gloves (Farming)
-Cooking Apron (Cooking)
-Chef's Hat (Cooking)
-Chef's Spoon (Cooking)
-Miner's Helmet (Mining)
-All Thieving items

I don't have all skillcapes/items so I can't provide info on the other items

### Save Link

https://melvoridle.com/save/2Ev00Btx

### Screenshots

Woodcutting and Thieving 
Browser
![Screenshot (553)](https://user-images.githubusercontent.com/107020091/196504686-2f2795d5-9d2d-43b4-88c2-925ccd7c8263.png)
![Screenshot (554)](https://user-images.githubusercontent.com/107020091/196504695-931e1d4e-5cc4-45cd-a106-f6947de2c061.png)
Mobile
![IMG_5498](https://user-images.githubusercontent.com/107020091/196506017-6f9b618f-89ce-47de-a9ae-a8b99a23cd85.png)
![IMG_5497](https://user-images.githubusercontent.com/107020091/196506054-9e660fbf-f308-4937-91d1-44c8e1ea4f0e.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4390

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
The Quick equip menu is customisable by the player. You can set items yourself by clicking the item in the bank and adding it to the Quick Equip menu.
