### ISSUE TITLE
[Bug]: <Bane Fight Crash>

### ISSUE THREAD

**Issue by BrisingrChetowa** [MelvorIdle/melvoridle.github.io#2660]
### Describe the bug

When fighting Bane, and I assume as I dealt the killing blow, I got an error. It said something about Android Users clearing Cache (I'm currently on Steam, though sometimes play on Android).

I added a second screenshot to show what my screen showed when I logged back in with my local save. I was in fight 233/9.

As for Mods, I had exactly one: Virtual Mastery Levels

### Reproduction Steps

1. Fight Bane (First fight, Magic version)
2. Deal Killing Blow
3. Error

### Expected behaviour

I expected Bane to die. Instead, he killed the game.

### Save Link

https://melvoridle.com/save/SXFgXvOp

### Screenshots

<img width="1030" alt="Bane Error" src="https://user-images.githubusercontent.com/49105254/196514576-0e9c6dd6-71e9-43e5-9b3e-92f6e9145e65.png">

<img width="479" alt="Logged Back In" src="https://user-images.githubusercontent.com/49105254/196514953-27f7e50c-d15a-4f19-ba97-f3491dcc39b4.png">

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4395

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Hotfix applied to the game - V1.1 (?4427)
