### ISSUE TITLE
[Bug]: Wield 2-hand weapon in off hand and item duplication

### ISSUE THREAD

**Issue by rdkirby94** [MelvorIdle/melvoridle.github.io#2662]
### Describe the bug

There is a way to set any 2-handed weapon to only be wielded in your off-hand slot using quick equip. Equipping a 1-handed weapon in the weapon slot and then trying to equip a different 2-handed weapon from the one currently in the off-hand slot will cause the loss of the item being equipped but give a copy of the main hand weapon without unequipping it. Off-hand and 2-handed weapons equipped while there is nothing in the main hand are simply lost. Staves equipped in this way do not confer rune reducing benefits or count as having a magic weapon equipped.

### Reproduction Steps

1. Equip any 2-handed weapon (have tried with bow, staff, and 2H sword)
2. Click on the equipment dropdown at the top
3. Click on the weapon in the offhand slot and set it as one of your quick equips
4. Unequip this weapon in any way you like and close the quick equip window.
5. Open the quick equip window for the offhand slot and equip the set 2h weapon
6. Weapon should now be equipped in offhand slot only and cannot be removed
7. Equip a 1h weapon
8. Attempt to equip a 2h weapon of any type
9. 2h weapon being equipped will disappear and 1h weapon that is currently equipped will be added to the bank but not unequipped.
10. Attempting to equip an off-hand only item will cause that item to disappear with no benefit.
11. Refreshing the page or reloading the save in some way will cause the bugged item to disappear entirely and be removed from quick equip slots.

### Expected behaviour

The 2h weapon should be equipped in both hands when set through the quick equip.

### Save Link

https://melvoridle.com/save/kauli7pn

### Screenshots

![image](https://user-images.githubusercontent.com/90587728/196519384-debe1928-f8b1-4142-ba11-b34a999692a8.png)
![image](https://user-images.githubusercontent.com/90587728/196519525-b6dcbd7e-9acd-43de-b501-f349a6d2f1af.png)
![image](https://user-images.githubusercontent.com/90587728/196519601-e1338c07-7a0d-4857-8021-f62e15c4423b.png)

### Console output

Failed to load resource: the server responded with a status of 404 ()
5[DOM] Input elements should have autocomplete attributes <attribute>: (More info: <URL>) 
cloudManager.js?4395:193 Silent Sign in with JWT
cloudManager.js?4395:193 Validating Melvor Cloud token
cloudManager.js?4395:193 Storing Melvor Cloud Token
cloudManager.js?4395:193 Initializing PlayFab login. Method: customID
cloudManager.js?4395:193 Logging in with Custom ID via PlayFab
cloudManager.js?4395:193 Login with custom ID success
cloudManager.js?4395:193 Getting account info
cloudManager.js?4395:193 Account info retrieved
cloudManager.js?4395:193 Authenticated w/ Melvor Cloud: true
cloudManager.js?4395:193 Authenticated w/ PlayFab: true
cloudManager.js?4395:193 Checking for valid full version
cloudManager.js?4395:193 Checking for valid TotH purchase
cloudManager.js?4395:193 Loading Game Data...
save.js?4395:112 Registered Demo Data.
save.js?4395:112 Registered Full Version Data.
cloudManager.js?4395:193 Initializing Mod Manager...
cloudManager.js?4395:193 Loading Local Saves...
cloudManager.js?4395:193 Loading Cloud Saves...
cloudManager.js?4395:193 Getting saves from playfab
cloudManager.js?4395:193 Saves retrieved
characterSelect.js?4395:5 Loading character selection
cloudManager.js?4395:288 Connected to PlayFab successfully
save.js?4395:39 Copied to clipboard successfully.
main.js?4395:15 Game Loaded
style.css:1          Failed to load resource: the server responded with a status of 404 ()
cloud.js?4395:29 Synchronising with Cloud
6bank2.js?4395:85 Uncaught Error: Tried to add negative or zero quantity to bank.
    at Bank.addItem (bank2.js?4395:85:7)
    at player.js?4395:214:237
    at Array.forEach (<anonymous>)
    at Player.equipItem (player.js?4395:214:200)
    at Player.equipCallback (player.js?4395:187:42)
    at equipButton.onclick (bankMenus.js?4395:135:379)
3bank2.js?4395:85 Uncaught Error: Tried to add negative or zero quantity to bank.
    at Bank.addItem (bank2.js?4395:85:7)
    at Player.unequipItem (player.js?4395:220:93)
    at HTMLButtonElement.<anonymous> (player.js?4395:218:38)
12bank2.js?4395:85 Uncaught Error: Tried to add negative or zero quantity to bank.
    at Bank.addItem (bank2.js?4395:85:7)
    at player.js?4395:214:237
    at Array.forEach (<anonymous>)
    at Player.equipItem (player.js?4395:214:200)
    at Player.equipCallback (player.js?4395:187:42)
    at equipButton.onclick (bankMenus.js?4395:135:379)
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/chrome/scripts/iframe_form_check.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/chrome/scripts/content_scroll_mid_detection.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://klekeajafkkpokaofllcadenjdckhinm/sourceMap/chrome/content.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for https://melvoridle.com/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
50[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
4bank2.js?4395:85 Uncaught Error: Tried to add negative or zero quantity to bank.
    at Bank.addItem (bank2.js?4395:85:7)
    at player.js?4395:214:237
    at Array.forEach (<anonymous>)
    at Player.equipItem (player.js?4395:214:200)
    at Player.equipCallback (player.js?4395:187:42)
    at equipButton.onclick (bankMenus.js?4395:135:379)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4395

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was hotfixed. It is no longer possible to put invalid items in the quick equip slot.
