### ISSUE TITLE
[Bug]: Unable to equip summoning tablets

### ISSUE THREAD

**Issue by carlyasadi** [MelvorIdle/melvoridle.github.io#2663]
### Describe the bug

When trying to equip summoning tablets (specifically Pig), I am unable to equip and receive the error message "You cannot do that during a dungeon!". I am not in a dungeon, not actively training any other skills.

### Save Link

https://melvoridle.com/save/CZ7jp8GF

### Screenshots

![Screenshot_20221018-152720](https://user-images.githubusercontent.com/97266749/196527001-b7f8bc54-9bfa-41cb-b358-08912109d1f3.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4395

### Are you using any mods?

No

**Comment by ekuland** [comment]
I believe a workaround is to enter and running from a dungeon?

**Comment by carlyasadi** [comment]
> I believe a workaround is to enter and run from a dungeon?

That worked, thank you!
