### ISSUE TITLE
[Bug]: Township Map 4 is 100 buildings short

### ISSUE THREAD

**Issue by Sully-5** [MelvorIdle/melvoridle.github.io#2664]
### Describe the bug

Not sure if this is a typo or a bug, but all maps have a maximum of 2048 buildings across all biomes... except map 4 has 1948. Maybe it's intentional? But seems way too coincidental to be exactly 100 short

### Reproduction Steps

Reselect map for township

### Expected behaviour

I'd expect all maps to have the same maximum

### Screenshots

![image](https://user-images.githubusercontent.com/99215735/196530131-97bd959d-a1ca-44b6-aa92-d61718b8d59e.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

4395

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Township has now been reworked as of v1.1.2
