### ISSUE TITLE
[Bug]: Skip Paying Gold Cost for Township Land

### ISSUE THREAD

**Issue by 2TwoNiko** [MelvorIdle/melvoridle.github.io#2667]
### Describe the bug

When i bought land in township i noticed the gold cost was never actually subtracted from my total gold. The listed price keeps increasing but even though it is more than what i currently have i can still buy more land. I think the very first time i bought land it worked but ever since then it has been broken. 

### Reproduction Steps

1. Go to township
2. Repeatedly buy land

### Expected behaviour

Gold cost is subtracted from current gold. 
Cant press buy button if current gold is to low. 

### Screenshots

![image](https://user-images.githubusercontent.com/116121487/196548120-a87f5e12-e136-4c7f-96b1-f94a18d3c720.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4395

### Are you using any mods?

No

**Comment by danieltaylor** [comment]
I am seeing this bug as well on iOS.

**Comment by 2TwoNiko** [comment]
> ~I am seeing this bug as well on iOS.~
> 
> Edit: Just figured it out. GP for buying more land comes from your actual GP, not from your township GP. This makes a lot more sense with the fact that you don't have to repurchase land when starting a new town.
> 
> Edit 2: Apparently there is no such thing as "township GP." The GP shown in township is just how much you have earned from your town, which ends up going straight to your normal GP stack.

Ah yes, you are correct. Its a bit confusing but everything seems to work as intended then
