### ISSUE TITLE
[Bug]: Runes are not highlighted after reloading

### ISSUE THREAD

**Issue by 2TwoNiko** [MelvorIdle/melvoridle.github.io#2668]
### Describe the bug

When using magic the used runes are not highlighted after coming back from being offline. 

### Reproduction Steps

1. Go to combat
2. Use magic
3. Close game
4. Open game

### Screenshots

![image](https://user-images.githubusercontent.com/116121487/196548620-216f96e9-e240-4ebf-af25-bffb26b1815b.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4395

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was fixed as of v1.1.1 (?4999).
