### ISSUE TITLE
[Bug]: unable to gain some resources in Township

### ISSUE THREAD

**Issue by UselessTechSupport** [MelvorIdle/melvoridle.github.io#2669]
### Describe the bug

Unable to currently gain wood in township

stuck at 1 wood and does not increase after ticks

### Expected behaviour

Shoauld be giving + wood per tick

### Save Link

https://melvoridle.com/save/sJCMJQlI

### Screenshots

Before
![image](https://user-images.githubusercontent.com/53866303/196549446-d503653c-f39e-4bd0-91e6-9208b49f3ead.png)
After
![image](https://user-images.githubusercontent.com/53866303/196549603-c86e49f3-fa0d-4a90-8e27-60d9b45e380c.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?42395

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Need to look after your storage.

I will add more UI elements to help with directing players to this issue.
