### ISSUE TITLE
[Bug]: Text in Skill Experience Bar very small

### ISSUE THREAD

**Issue by 2TwoNiko** [MelvorIdle/melvoridle.github.io#2670]
### Describe the bug

After the update the text in the skills experience section (level, experience, current tool, view checkpoints, spend mastery pool xp) is suddenly super small. 

### Screenshots

![image](https://user-images.githubusercontent.com/116121487/196550371-298a4438-00fd-425e-9f10-31db03b0c210.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4395

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Steam does have a Zoom option in settings. Does setting this higher assist at all?

**Comment by 2TwoNiko** [comment]
Increasing the Zoom does increase the size of these elements, but its still relatively small compared to all other text. Maybe this is intentional?
