### ISSUE TITLE
[Bug]: game nearly constantly freezes

### ISSUE THREAD

**Issue by tomWdavies** [MelvorIdle/melvoridle.github.io#2671]
### Describe the bug

The android app freezes very regularly on nearly all actions (swiping for the menu, pressing buttons, opening menus etc .
The issue is extremely regular and makes the game frustrating to the point of being unplayable.
The issue has been ongoing for months, although unfortunately I am not sure how long as I stopped playing for a long time because of it.
I have tried clearing the app cashe, app data, and uninstalling the app, but nothing makes any difference.

### Save Link

https://melvoridle.com/save/L39BazxN

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4395

### Are you using any mods?

No

**Comment by Russiandood** [comment]
I can confirm this has been an issue for me since I started playing on the mobile app. Even launching from a browser on my phone does the same thing. Only place I haven't had this issue is on my desktop browser.

**Comment by MelvorIdle** [comment]
Issue most likely relates to accessibility apps installed on your device, and is trying to constantly take control of Melvor (causing the lag).

See here for info: #2694
