### ISSUE TITLE
[Bug]: Game freezes when loading character

### ISSUE THREAD

**Issue by Meliqr** [MelvorIdle/melvoridle.github.io#2672]
### Describe the bug

When I try to open my adventure mode character the screen freezes and becomes unresponsive. Eventually, if I leave it open, the screen will go white and return me to the character selection screen. 

This broke with the 1.1 update. It was loading fine before but I haven’t been able to load it since. 

Edit: I tried on chrome and it doesn’t work there either

### Reproduction Steps

1. Open the game and try to load the character

### Expected behaviour

Character loads correctly

### Save Link

https://melvoridle.com/save/K3vSQPB7

### Screenshots

![2D796791-7F2B-4B2B-BB0B-4FDA19CE31FD](https://user-images.githubusercontent.com/14301813/196569505-fb0314c2-435f-4a17-be1c-9a88550541f8.png)

### Which platforms are you experiencing this bug on?

- [ X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4395

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This is a bug we are still investigating. We hope to have another update on progress of fixing asap.

**Comment by MelvorIdle** [comment]
We have just released a hotfix for this issue. Thank you for your patience.
