### ISSUE TITLE
[Bug]: Larry the lizard no longer shows on the Skilling Minibar

### ISSUE THREAD

**Issue by Pogoslayer** [MelvorIdle/melvoridle.github.io#2673]
### Describe the bug

Larry does not appear on the farming menu after updating to 1.1. Unsure if the bonuses are applying either.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

4395

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was hotfixed as of v1.1 (?4516).
