### ISSUE TITLE
[Bug]: Found mark popup after logging in

### ISSUE THREAD

**Issue by sceithamer** [MelvorIdle/melvoridle.github.io#2674]
### Describe the bug

If you log out of the game for a while and come back having found a bunch of summoning marks, in my case "Mark of the wolf", you have to click "OK" for each Mark found.  For me it was like 30+ of them and this took forever as it was very laggy between popups.

This should be one popup that says "You found X Mark's of the Wolf" ... "it is now Tier 4" or something od the sort

### Reproduction Steps

1. Log out doing activity to find Summoning Marks
2. Log in 18hrs later
3. Click through 30+ popups for each Mark found

### Expected behaviour

There would be a single popup stating I found X number of Marks and what my new Tier is with that Mark.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4395

### Are you using any mods?

No

**Comment by olenoerby** [comment]
This should be a summary popup, like the summary screen after training idle.

**Comment by MelvorIdle** [comment]
There is a setting you can disable to stop the individual mark popups. Level up popups will always display.
