### ISSUE TITLE
[Bug]: Township ticks can be spent during Golbin Raid but don't take effect until pausing

### ISSUE THREAD

**Issue by danieltaylor** [MelvorIdle/melvoridle.github.io#2675]
### Describe the bug

While fighting in Golbin Raid, trying to spend Township ticks doesn't appear to do anything.  After pausing Golbin Raid and returning to township, the ticks will be spent.

### Reproduction Steps

1. Continue (or possibly Start) Golbin Raid
2. Open Township and try to spend ticks.  Nothing will appear to happen.
3. Pause Golbin Raid.
4. Return to Township and the number of remaining ticks will be reduced.  Resources will be updated as well.

### Expected behaviour

Ticks should either:
- not be spendable at all during Golbin Raid (a popup or message making it clear why they aren't spendable would be helpful as well—I discovered this bug by trying to spend over and over because it wasn't working, and then discovering that a bunch of ticks were gone later on)
- or should update when spent, along with resources and any other related aspects of Township.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [X] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4395

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Township has now been reworked as of v1.1.2
