### ISSUE TITLE
[Bug]: Cannot play game

### ISSUE THREAD

**Issue by Chewbarta** [MelvorIdle/melvoridle.github.io#2676]
### Describe the bug

Very simple, when I go to press the *sign-in* button, it spins and doesn’t do anything. I cannot see my characters or anything except the login screen.
I am using an iPhone 13.
I am simply unable to use the cloud and have lost all my saves that aren’t backed up through my link.

### Reproduction Steps

Open the app and login normally

### Expected behaviour

Logging in does nothing and this makes the game unplayable.

### Screenshots

![0DD0E388-304D-48F0-9375-48A3E68B44E7](https://user-images.githubusercontent.com/115666595/196603901-83dcf40c-bf0f-42a4-8fb3-c2c67ab919aa.jpeg)
![DAAF8EFB-21FA-4905-B0EF-DF6B362FF3F0](https://user-images.githubusercontent.com/115666595/196603907-98e41b50-46c2-434c-8ae3-620e891bc4bf.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [X] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

Can’t get into game to view this information

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Hello - are you trying to log in with a very old cloud account?
