### ISSUE TITLE
[Bug]: Charge Stones of Rhaelyx consumed training Astrology

### ISSUE THREAD

**Issue by Dorbun** [MelvorIdle/melvoridle.github.io#2678]
### Describe the bug

I log in after 14 hours and my stones were used up somehow while training Astrology. 

### Reproduction Steps

Have charge stones of Rhaelyx active
Train Astrology
Go afk for 14 hours
Log back in
See error
???
Profit?

### Expected behaviour

To not use the charge stones of Rhaelyx

### Save Link

https://melvoridle.com/save/aVoLDzYv

### Screenshots

Sorry mate, forgot to screenshot. First time reporting a bug. Allow it.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4395

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This has now been hotfixed.
