### ISSUE TITLE
[Bug]: Leprechaun/Monkey synergy give 15% instead of 1500% of base sale price

### ISSUE THREAD

**Issue by AsandaNima** [MelvorIdle/melvoridle.github.io#2680]
### Describe the bug

With v1.1 the synergy of Leprechaun/Monkey synergy give 15% instead of 1500% of base sale price

### Reproduction Steps

Select Synergy in the Summoning menu
Select Leprechaun
Scroll to Leprechaun/Monkey synergy

### Screenshots

![image](https://user-images.githubusercontent.com/41681946/196641087-9b2bd2d5-cf17-448f-8aad-d03d4eb844cc.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4395

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This is only a visual bug which should be fixed now.

**Comment by AsandaNima** [comment]
As of version ?4430 it still says 15%.
But if it's just a visual bug, that's good.
