### ISSUE TITLE
[Bug]: Prayer Points Converted from SINT32 to UINT32

### ISSUE THREAD

**Issue by spelcheqking** [MelvorIdle/melvoridle.github.io#2681]
### Describe the bug

I had -4 prayer points and then after Throne of Herald Day 1 Bug Fixes I had 4,294,967,292 prayer points available.  This is likely because the update converted 32 bit Signed Ints to unsigned.

### Reproduction Steps

Probably can't reproduce, but anyone that had negative prayer points before the update will now have a huge amount of prayer points.  Don't know why I had negative in the first place and the update was probably to address the negative prayer point issue.

### Expected behaviour

Prayer points should not go negative. Unsigned Ints may fix this (like the update did), but also creating a conditional that prevents the decrease in the first place could also work.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

4430

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
The initial issue regarding negative prayer points has recently been hotfixed.
