### ISSUE TITLE
[Bug]: <Stuck in Stunned in Theiving

### ISSUE THREAD

**Issue by ValentinNYC** [MelvorIdle/melvoridle.github.io#2682]
### Describe the bug

My character is stuck in Thieving. I cannot do any Thieving anymore.
All other activities are working fine, but the Thieving tab always got stuck in "stunned" and I cannot do it anymore.
I tried reloading, changing all gears, changing food, fighting, but nothing seems to unlock.

### Reproduction Steps

1. Go to Theiving
2. The "Start Theiving" button is automatically changed as "Stop Theiving" and got a message that I am stunned
3. All of that while other activities are ongoing OK
4. No other theiving action can be performed

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

74430

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Hello, if you are able to could you generate a save link and respond with it? Would greatly assist in trying to source this issue.
Instructions for generating a save link can be found [here.](https://github.com/MelvorIdle/melvoridle.github.io/wiki/How-to-Create-a-Save-Link )

**Comment by ValentinNYC** [comment]
Here you go
https://melvoridle.com/save/fzxsoRye

**Comment by coolrox95** [comment]
Issue has been hotfixed as of v1.1 (?4598).
