### ISSUE TITLE
[Bug]: <title> township easy task potion bug

### ISSUE THREAD

**Issue by Ctingen12** [MelvorIdle/melvoridle.github.io#2683]
### Describe the bug

My mastery level is too high so I make level 2 potions. Township task requires level 1 potions. 

Add option to downgrade higher tier potions to lower tier

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4427

### Are you using any mods?

No

**Comment by 47Y** [comment]
By using the Herblore Potion, you can create random tiers of potions. This will let you obtain tiers that you can no longer make normally.
