### ISSUE TITLE
[Bug]: Various Perfect foods unable to be downgraded

### ISSUE THREAD

**Issue by DanielChickenn** [MelvorIdle/melvoridle.github.io#2684]
### Describe the bug

As title states, compared to other foods, perfect chicken doesn't have an option to be downgraded.

### Expected behaviour

Chicken (Perfect) downgraded to regular Chicken

### Screenshots

![image](https://user-images.githubusercontent.com/107977460/196734114-fa2a3013-9b49-47d6-8667-54b94a74b18b.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4430

### Are you using any mods?

Yes

**Comment by cmonger** [comment]
This may be related to a bug I'm experiencing. cooked chickens and they won't appear in my inventory.

**Comment by yznpku** [comment]
I have this bug on Bread (Perfect).

Version is steam v1.1.1 (?4908)

**Comment by 1n5aN1aC** [comment]
I am experiencing this bug with both Bread and Chicken.

Both are needed in their non-perfect forms for high-level cooked foods, which makes the perfect forms almost useless without a way to downgrade them.

**Comment by Brandarwi** [comment]
No downgrading for perfect meat pizza and carrot cake either. v1.1.1?4999

**Comment by Lavender-Li** [comment]
Same issue here. Basic soup (perfect) doesn't have "downgrade" button.
Version: v1.1.1?5027
Seems that this problem has already existed for several months. Hope that it could be fixed soon.

**Comment by D-Scaduto** [comment]
I am still seeing this problem in version 1.2.

Specifically with Carrot Cake (Perfect)
![Capture](https://github.com/MelvorIdle/melvoridle.github.io/assets/4481192/ea8214b3-d61d-4bae-8d9d-8d491a6157d9)
