### ISSUE TITLE
[Bug]: Township resource/t calculation issue (can't progress)

### ISSUE THREAD

**Issue by GothicLogic** [MelvorIdle/melvoridle.github.io#2685]
### Describe the bug

I am increasing my buildings that create resources and as a result am getting a decrease in resources/t even when the increased worker slots are being filled, I can't progress further because I can't relocate my buildings due to this bug

### Reproduction Steps

Using map 1 Terran worship
Simply increasing my food buildings in water (though I believe happens with other resources)

### Expected behaviour

I should be getting an increase of resources/t when I build things that increase resources/t

### Save Link

https://melvoridle.com/save/7d8Yo12t

### Screenshots

GIF example: https://i.imgur.com/ZZO07cn.gif
https://i.imgur.com/qpdgB58.gif

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4430

### Are you using any mods?

No

**Comment by ekuland** [comment]
The first gif shows your resources/t increasing as you upgrade them
The second doesn't as new workers don't start working until ticks, right?

**Comment by GothicLogic** [comment]
> The first gif shows your resources/t increasing as you upgrade them

Watch the GIF for more than 1 second


> The second doesn't as new workers don't start working until ticks, right?

Doesn't matter how many ticks ahead I skip it stays negative even w/ full workers, regardless, why would it ever start to go negative when it doesn't use food/t to create them?

**Comment by tyler-groves** [comment]
I am having the same issue. Resources are simply not outputting.

**Comment by MelvorIdle** [comment]
A hotfix has now been applied to the game for this issue.
