### ISSUE TITLE
[Bug]: Unable to receive Clue Chasers Insignia

### ISSUE THREAD

**Issue by putaojuice** [MelvorIdle/melvoridle.github.io#2686]
### Describe the bug

As title, unable to receive the Clue Chasers Insignia even after reordering the items

### Reproduction Steps

1. Put all the required items in the left most tab and in the correct order

### Expected behaviour

Receive Clue Chasers Insignia

### Screenshots

![Screenshot 2022-10-20 at 1 14 53 AM](https://user-images.githubusercontent.com/33406416/196760278-afaeb9f6-946c-4136-b3ec-2487aa941340.png)

### Console output

Failed to load resource: the server responded with a status of 404 ()
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloudManager.js?4430:193 Silent Sign in with JWT
cloudManager.js?4430:193 Validating Melvor Cloud token
cloudManager.js?4430:193 Storing Melvor Cloud Token
cloudManager.js?4430:193 Initializing PlayFab login. Method: customID
cloudManager.js?4430:193 Logging in with Custom ID via PlayFab
cloudManager.js?4430:193 Login with custom ID success
cloudManager.js?4430:193 Getting account info
cloudManager.js?4430:193 Account info retrieved
cloudManager.js?4430:193 Authenticated w/ Melvor Cloud: true
cloudManager.js?4430:193 Authenticated w/ PlayFab: true
cloudManager.js?4430:193 Checking for valid full version
cloudManager.js?4430:193 Checking for valid TotH purchase
cloudManager.js?4430:193 Loading Game Data...
save.js?4430:111 Registered Demo Data.
save.js?4430:111 Registered Full Version Data.
cloudManager.js?4430:193 Initializing Mod Manager...
cloudManager.js?4430:193 Loading Local Saves...
cloudManager.js?4430:193 Loading Cloud Saves...
cloudManager.js?4430:193 Getting saves from playfab
cloudManager.js?4430:193 Saves retrieved
characterSelect.js?4430:5 Loading character selection
cloudManager.js?4430:287 Connected to PlayFab successfully
main.js?4430:15 Game Loaded
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloud.js?4430:29 Synchronising with Cloud
style.css:1          Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4430

### Are you using any mods?

No

**Comment by ekuland** [comment]
Current workaround: Swap all items around -- make it backwards.

**Comment by putaojuice** [comment]
Ahh thanks, i received it. Closing this issue.
