### ISSUE TITLE
[Bug]: Game freezes when i log into primary character

### ISSUE THREAD

**Issue by Math4fun69** [MelvorIdle/melvoridle.github.io#2689]
### Describe the bug

I can log into my account (SolenoidC) perfectly OK, and I can enter my hardcore and adventure mode characters, and they both work fine. The problem is when I try to log into my primary account (Math4fun). The game freezes, I can't click anything in the game and this (Image linked) shows. This makes no sense because I do not have level one in all skills, as seen by my HP. I am assuming that is a visual bug. This bug stops me from playing the game on my favourite account and has persisted for a day +. 
![Screen Shot 2022-10-18 at 9 04 07 pm](https://user-images.githubusercontent.com/116210771/196784202-300ba840-010a-48bc-a045-533c022d7f37.png)
I have tried copying the save and entering it on another device, but neither works.

### Reproduction Steps

go to principal menu, click on Math4funthe 

### Expected behaviour

I expect it not to freeze xD

### Screenshots

![Screen Shot 2022-10-18 at 9 04 07 pm](https://user-images.githubusercontent.com/116210771/196784307-b102a9ec-2f51-4877-a96f-7300f7f7e635.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [X] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4465

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
I was unable to reproduce this issue with the save you provided us. Please disable your mods, especially Auto-loot if you have it, as it is known to cause this issue.
