### ISSUE TITLE
[Bug]: <title> Items given to town without me doing it.

### ISSUE THREAD

**Issue by martijnnnn** [MelvorIdle/melvoridle.github.io#2690]
### Describe the bug

I had an ancient ring of skills and amulet of looting equipped. I equipped different items and instead of the ancient ring of skills and amulet of looting returning to my bank they were donated to my town. I know this because the task to give an ancient ring of skills and give an amulet of looting to my town were both completed. Lost both items because of this.

### Reproduction Steps

Have a town in township with the trader unlocked
Have the ring and amulet equipped
Equip different ring and amulet

### Expected behaviour

The ring and amulet to go to my bank when unequipped instead of being donated to the town.

### Save Link

https://melvoridle.com/save/OijHvUHI

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4430

### Are you using any mods?

No

**Comment by cairnsjr13** [comment]
This renders a lot of the tasks useless.  If you collect the item in the game it counts it as being given to the township.  I don't even have a trading post and all of my tasks are being marked as completed

**Comment by cairnsjr13** [comment]
Another slightly bizarre behavior here.  It seems to be calculating it based off of what is in your bank.  I had 19 bird nests sitting in my bank and the task guide indicated I had given "19/25" to the township.  I opened one of the bird nests and now the township task says "18/25".

**Comment by MelvorIdle** [comment]
The item is provided to your town when you claim the rewards.
