### ISSUE TITLE
[Bug]: workers at age 70 are included in "over 70", but unemployement starts at 71

### ISSUE THREAD

**Issue by jshepler** [MelvorIdle/melvoridle.github.io#2692]
### Describe the bug

In the citizens tab, it shows "Over 70 (max worker age)", while the number displayed includes workers at age 70, those are still counted as available workers. See screenshots below...

SS1: 331 pop - 317 workers = 14, non-working children (age 0-7) = 14, over 70 = 1, at 70 = 1
SS2: 363 - 346 = 17, children = 17, over 70 = 2, at 70 = 2
SS3: 379 - 360 = 19, children = 19, over 70 = 3, at 70 = 3
SS4: 387 - 367 = 20, children = 19, over 70 = 3, at 70 = 2, at 71 = 1

If it's intended that workers stop working at 70, then the bug is that's not happening. If it's intended that workers stop at 71, then "over 70" should not count workers that are 70.

### Save Link

https://melvoridle.com/save/2Jfp1gfk

### Screenshots

![image](https://user-images.githubusercontent.com/1145213/196807443-206772de-2791-4523-b447-ff40916ebf23.png)

![image](https://user-images.githubusercontent.com/1145213/196807480-654269ed-4d83-42ca-af76-f3a67d73cf28.png)

![image](https://user-images.githubusercontent.com/1145213/196807499-d6cb20b4-3811-48aa-a5e4-426f32ad9a8a.png)

![image](https://user-images.githubusercontent.com/1145213/196807516-28c9af5b-5477-4714-b208-bc79196c0b83.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4430

### Are you using any mods?

No

**Comment by jshepler** [comment]
I'm pretty surprised this hasn't been fixed yet. It's a 1 character fix.

In the displayAllCitizens() function:
`const over70 = this.township.citizens.filter((c) => this.township.getCitizenAge(c) >= this.township.MAX_WORKER_AGE).length;`

should be:
`const over70 = this.township.citizens.filter((c) => this.township.getCitizenAge(c) > this.township.MAX_WORKER_AGE).length;`

> not >=

**Comment by jshepler** [comment]
BTW, the "over 55" also includes those that are 55, but looking at the code that determines the chance of a citizen dying, the getChanceToDestroyCitizen() function, it does `if (age >= this.AGE_OF_DEATH)` so I assume it should include those at 55. If so, maybe change the label to say "55 and over" as "over 55" means > 55, not >= 55.

**Comment by MelvorIdle** [comment]
Township has now been reworked as of v1.1.2
