### ISSUE TITLE
[Bug]: Can't plant trees 

### ISSUE THREAD

**Issue by HellRussian** [MelvorIdle/melvoridle.github.io#2693]
### Describe the bug

since the update I can't plant trees. I can harvest and plant the other two just fine but not trees. if I look at the trees section all of them say plant seed but I can't plant seeds. won't let me plant one at a time or mass plant them with the plant all buttons. I tried using the auto farming mod when I first launch Melvor on my PC when I got home yesterday, but I noticed the trees weren't planting. I removed the mod but the problem remained. and the farming skill flashes on with the green border all the time suggesting stuff is ready to harvest but its not.

### Reproduction Steps

no real steps to get the bug to happen because I can never plant the trees, on the pc or on mobile.

### Expected behaviour

I expect to be able to harvest trees, apply goop and plant again.

### Save Link

https://melvoridle.com/save/IN3spjXM

### Screenshots

![Screenshot_20221019-152430_Melvor Idle](https://user-images.githubusercontent.com/95596948/196807874-b1ea9db7-47b4-4235-9efc-3a7467686431.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4430

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
I believe this issue is now fixed.

**Comment by HellRussian** [comment]
Yes I can plant all the crops now
