### ISSUE TITLE
[Bug]: Android app lagging only when accessibility settings are enabled

### ISSUE THREAD

**Issue by MoctorDoon** [MelvorIdle/melvoridle.github.io#2694]
### Describe the bug

The Android app is lagging whenever you do anything, but only when you have the accessibility service enabled for at least one app.
It doesn't matter which app or if the app is running - it could even be force closed. 
I have tried this individually with a number of different apps that use the accessibility service (Tasker, AppMgr III, Bitwarden, Android Remote, MalwareBytes). As long as at least one app is enabled within the accessibility settings, Melvor Idle will lag.

This is the case for both my OnePlus 6T (Android 11) and my Samsung Galaxy Tab S7 (Android 12).
The app is running smooth as butter on both devices when the accessibility service is turned off for all apps.

### Reproduction Steps

1) Go to Android settings and navigate to "Accessibility" and enable the accessibility service for any app - doesn't matter which one
2) Open Melvor Idle - now it should be lagging whenever you do anything in the app

### Expected behaviour

I expected the app to not lag.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4430

### Are you using any mods?

No

**Comment by RobertBabol** [comment]
This fixed it for for me thank you. I was confused about the password managers because I didn't have one. I tried turning it on and off again a couple times just to confirm and it instantly fixed it and broke it as it was toggled.

This is on Google Pixel 6.

**Comment by LukeRhok** [comment]
On a Samsung S22+, 
When i disabled accessibility on all my apps then the game works great!  Before this change I had a minor lag issue until i started applying modifiers from astrology. The lag got much more worse the more modifiers i added seem to add.

**Comment by mrStorrs** [comment]
Can confirm this happens on both my pixel 6 and 7. As op mentioned disabling all accessibility access in the phones settings stops the horrendous lag. Opened melvor in the chrome browser as well and it has the same problem. If you download Mozilla however it works fine.

**Comment by Makeshift** [comment]
Any workarounds short of disabling all accessability tools (I've confirmed that having _any_ enabled causes melvor to lag) or opening it in Firefox? Or any fix planned?

I'm also interested in any technical details of why this happens, just for my own curiosity. Is it something like accessability trying to loop through every button/input because it's an embedded browser?

**Comment by StanczakDominik** [comment]
@Makeshift 

> Any workarounds short of disabling all accessability tools (I've confirmed that having any enabled causes melvor to lag) or opening it in Firefox? Or any fix planned?

If you go to the development roadmap, bundled with the changelog:

> A new Android App that will use GeckoView as its native WebView component. This is to address the major lag caused by Chrome's WebView when accessibility apps are used. This is a major change and will take some time to get right before release.

**Comment by Makeshift** [comment]
@StanczakDominik Ah, I didn't see that, thank you!
