### ISSUE TITLE
Soft-locked in Tutorial Island.

### ISSUE THREAD

**Issue by Eteled101** [MelvorIdle/melvoridle.github.io#2695]
### Describe the bug

I tried to make a shortbow and equip it but it just dissapeared. It got dusted because I wasn't looking at my inventory. But when I tried to buy the bow string again it said that I had to continue Tutorial Island in order to unlock it. I could just skip Tutorial Island but I just want this to be fixed so other dent-heads like me don't have to go though the same thing. So until the developers fix this paradox I'm a castaway.

### Reproduction Steps

1. be me
2. have 11 items in le inventory
3. make a shortbow base
4. make a shortbow
5. your_father.jpg
6. try to buy another bowstring
7. "Continue Tutorial Island to unlock this Shop Item."
8. make bug report

### Expected behaviour

I thought I could buy another bowstring but apparently not. Also, I cleared some room in my inventory as you see in the screenshots. I did this so it doesn't happen again when this hopefully gets fixed.

### Save Link

https://melvoridle.com/save/UqrVErif

### Screenshots

![image](https://user-images.githubusercontent.com/116226794/196815824-aa057ee6-bc97-4ae4-83bc-83fb7bdbc42a.png)
![image](https://user-images.githubusercontent.com/116226794/196815881-142ed4ff-87ad-4438-8fb1-2d9fd872cdee.png)
![image](https://user-images.githubusercontent.com/116226794/196815925-e67de1df-effd-46d9-990e-8252394cecc8.png)

### Console output

It doesn't have or I couldn't find the button to open the console.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4430

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This issue has been hotfixed in a recent update.
