### ISSUE TITLE
[Bug]: <Confetti Crossbow does not give gold per hit>

### ISSUE THREAD

**Issue by Rldenison** [MelvorIdle/melvoridle.github.io#2696]
### Describe the bug

When I fight a creature, my Confetti Crossbow no longer gives me GP on a successful hit.

### Reproduction Steps

Arm confetti crossbow
Attack creature

### Expected behaviour

Confetti crossbow should give GP on each successful attack, but does not.

### Save Link

https://melvoridle.com/save/KNSbrxuG

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1

### Game Subversion

?4430

### Are you using any mods?

No

**Comment by joshualoehr** [comment]
+1 also seeing this

**Comment by coolrox95** [comment]
Issue has been hotfixed as of v1.1 (?4628).
