### ISSUE TITLE
[Bug]: Can't modify loadout since 1.1 update

### ISSUE THREAD

**Issue by danny-schwartz7** [MelvorIdle/melvoridle.github.io#2697]
### Describe the bug

When I attempt to change a piece of equipment (by unequipping something or equipping something else), it will not let me and display the 'you cannot do that while in a dungeon' message despite the fact that I'm not currently in a dungeon.

### Reproduction Steps

I have no idea if this is happening on other accounts but all I have to do (since the 1.1 update) is attempt to change my equipment. It will not let me and display the 'you cannot do that while in a dungeon' message despite the fact that I'm not currently in a dungeon.

### Expected behaviour

I expected to be able to modify my equipment loadout.

### Save Link

https://melvoridle.com/save/Ib4zXopi

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4430

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was hotfixed as of v1.1 (?4516).
