### ISSUE TITLE
[Bug]: Township displays incorrect existing building counts in the biome Build menu

### ISSUE THREAD

**Issue by largemoron** [MelvorIdle/melvoridle.github.io#2698]
### Describe the bug

Scrolling through the township menu's Build section, the numbers displayed next to the building names do not always accurately represent the number of buildings you have actually built in that biome.

I've attached a video below in the Screenshots section showing the bug as I experience it. This happens in every biome, on all characters, across all game types, on all platforms I've tested, with and without mods enabled. With mods I do not use any that affect Township; only SEMI core, SEMI drop chances, quickshards, and unlimited offline.

edit again: still happening as of  V1.1 (?4500), post-throne launch

### Reproduction Steps

Go to township

select Build from the Township Menu drop down

scroll down the list of structures and view the number next to the building name, e.g. Tavern [5]

tap/click Tavern (or any other building) to build another one and view how the number changes

### Expected behaviour

I would expect "Town hall [6]" and "Tavern [5]" to mean that I have 6 Town Halls and 5 Taverns constructed in the selected biome, instead of a completely different number that may or may not be 0.

### Save Link

https://melvoridle.com/save/wO9bI9SR

### Screenshots

https://user-images.githubusercontent.com/99063144/196838686-044ced4f-4971-4352-8aa6-b315aaee0993.mp4

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4430

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Township has now been reworked as of v1.1.2
