### ISSUE TITLE
Double clicking equip changes equipped item into equipping item.

### ISSUE THREAD

**Issue by mrDLSable** [MelvorIdle/melvoridle.github.io#27]
**Describe the bug**
If you double click the equip button, the held weapon becomes the equipping weapon and you also keep a copy of the equipping item in your inventory.

**To Reproduce**
1. Start a fresh game.
2. Give yourself a bronze dagger and a iron sword:
```
addItemToBank(CONSTANTS.item.Bronze_Dagger, 1);
addItemToBank(CONSTANTS.item.Iron_2H_Sword, 1);
```
3. Equip the bronze dagger.
4. Double click equip on the iron sword.
5. Now you have 2 iron 2H swords.

**Expected behavior**
The bronze dagger goes into the inventory.

**Screenshots**
![image](https://user-images.githubusercontent.com/1783781/68805417-178f8780-0664-11ea-92c4-4adb75c2d8a1.png)
![image](https://user-images.githubusercontent.com/1783781/68805443-22e2b300-0664-11ea-8b67-592f599ebae6.png)

**Browser**
Chrome.

**Console output**
```
Melvor Cloud Connection: Failed
save.js?92:40 Loading Save Game...
save.js?92:171 Save Game Loaded...
smithing2.js?92:194 Loading Smithing...
mastery.js?92:167 Updating Masteries
mastery.js?92:35 Loading Masteries...
account.js?92:25 Username set to: Insubordinate
smithing2.js?92:194 Loading Smithing...
mastery.js?92:167 Updating Masteries
mastery.js?92:35 Loading Masteries...
addItemToBank(CONSTANTS.item.Bronze_Dagger, 1)
true
addItemToBank(CONSTANTS.item.Iron_2H_Sword, 1)
true
```

**Comment by MelvorIdle** [comment]
Fixed in v0.10
