### ISSUE TITLE
[Bug]: <title> Slayer Task Bug

### ISSUE THREAD

**Issue by IamZeyon** [MelvorIdle/melvoridle.github.io#2700]
### Describe the bug

Finished a Master slayer task, instead of being given a new one, the monster quantity went into the negatives. After relogging it gave a massive number for the quantity. I tried to get a different level task and then switch back to master, and now I can not get a master task at all.

### Reproduction Steps

1: complete a master task, and let it keep going.
2: shows a negative quantity counter
3: switch to a different level task.
4: try to switch back to master level task

### Save Link

https://melvoridle.com/save/TEzBQDHY

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4462

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This issue has been hotfixed in a recent update.
