### ISSUE TITLE
[Bug]: Merchant Permit discount before finding it

### ISSUE THREAD

**Issue by cairnsjr13** [MelvorIdle/melvoridle.github.io#2701]
### Describe the bug

Purchasing gloves in the shop show the 10% discount even though I have not found the Merchant's permit item yet. (Gem gloves 450k, etc)

### Reproduction Steps

1) new account
2) go to shop
3) gloves
4) gem gloves 450k

### Expected behaviour

Shouldn't apply until found

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

4462

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was hotfixed as of v1.1 (?4516).
