### ISSUE TITLE
[Bug]: Burnt cave fish description encoding

### ISSUE THREAD

**Issue by entarctica** [MelvorIdle/melvoridle.github.io#2703]
### Describe the bug

Burnt cave fish description showing some kind of encoded text instead of the regular characters.

### Reproduction Steps

Get a single burnt cave fish from monster drop (leech maybe? I'm not sure what it came from)

### Expected behaviour

n/a

### Save Link

https://melvoridle.com/save/fp5ZjnTB

### Screenshots

![image](https://user-images.githubusercontent.com/28060458/196881376-229e68e1-4f39-4aeb-b862-7d33cee57812.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4471

### Are you using any mods?

No

**Comment by SkooterWick** [comment]
Ahhh, I thought I was the chosen one!

**Comment by coolrox95** [comment]
This is intended, and is meant as a hint of what to do with the item.
