### ISSUE TITLE
[Bug]: Loading shows no training, opening game shows already seen progress

### ISSUE THREAD

**Issue by Kyle9185** [MelvorIdle/melvoridle.github.io#2704]
### Describe the bug

The first part of the bug is that whenever I open the app it displays that I am not currently training even though when I open a character it does recognize that I am. The second part is that it when opening a character it displays previously displayed progress in addition to the new progress that has been made. I have not tested this with multiple tasks so I am only aware of it happening on agility. 

### Reproduction Steps

1. Start a task (possibly only agility) 
2. Leave the app
3. Reopen the app 
4. Choose character (which is shown as not training)
5. View progress made (which overlaps with previously displayed progress)

### Expected behaviour

Expected outcome would be for the task being worked on to be displayed before opening the character and for progress to not overlap with previously loaded progress.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4471

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This issue has been hotfixed in a recent update.
