### ISSUE TITLE
[Bug]: Single Consumable Items (Ammunition/Tablets) appear in inventory

### ISSUE THREAD

**Issue by 2TwoNiko** [MelvorIdle/melvoridle.github.io#2705]
### Describe the bug

Recently while doing combat with bolts or summoning tablets equipped i sometimes find a single version of said bolt/tablet in my inventory while the rest are still equipped. I have the maximum skillcape equipped and equip said items via the quick menu, don't know if this is related though

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4481

### Are you using any mods?

No

**Comment by coolrox95** [comment]
It is intended behavior that the quick equip menu equips all but one of an item from the bank.
