### ISSUE TITLE
[Bug]: Ancient Ring of Skills not affecting township experience

### ISSUE THREAD

**Issue by Sapeeh** [MelvorIdle/melvoridle.github.io#2707]
### Describe the bug

ARoS is not affecting township tick xp.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4481

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.1 (?4673).
