### ISSUE TITLE
[Bug]: Golden Topaz Ring

### ISSUE THREAD

**Issue by okremer** [MelvorIdle/melvoridle.github.io#2710]
### Describe the bug

The ring is supposed to give 15% more GP from monsters and something else than a ring like this should drop. But I still keep getting more golden topaz rings. Is that a bug?

### Reproduction Steps

It keeps happening. Though I have no other ring to reset it or so. 

### Expected behaviour

Get a different drop?

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4500

### Are you using any mods?

No

**Comment by ekuland** [comment]
Based on wording, I'm assuming you're trying to fight mummies and change their drops.
That's not quite what it does.
It instead lets the very small chance of you getting a gold topaz from doing any action to instead give a different item, not actual drops from enemies.

**Comment by okremer** [comment]
> Based on wording, I'm assuming you're trying to fight mummies and change their drops.
> That's not quite what it does.
> It instead lets the very small chance of you getting a gold topaz from doing any action to instead give a different item, not actual drops from enemies.

It says „… and something else drops instead of gold topaz ring“. To me that seems to imply that when any monster would drop said ring, it should drop something, anything, else instead. Probably limited to something the monster would usually drop.

If it is meant in regards of using non-fighting skills that wording feels wrong imo.
