### ISSUE TITLE
[Bug]: Township: Town's GP not displaying 

### ISSUE THREAD

**Issue by tlchimera** [MelvorIdle/melvoridle.github.io#2711]
### Describe the bug

When viewing Township's production stats (planks, wood, food etc) the total GP available to spend is not displayed, just the variable rate per tick. Clearing my phone's cache does not resolve this. 

### Reproduction Steps

1. Open Melvor
2. Open Township skill 

### Expected behaviour

Total Township GP not displayed. 

### Save Link

https://melvoridle.com/save/RFVMglgY

### Screenshots

![Screenshot_20221020-154708](https://user-images.githubusercontent.com/116290885/196984059-33dc18f3-ab31-4b04-9dcb-77e75bcd9bdb.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

4500

### Are you using any mods?

No

**Comment by ekuland** [comment]
I believe this was intentional as the town doesn't technically have any gp

All that line does it tracks how much money was deposited into **your** gp so it seems like it may have been removed to show that fact.

**Comment by coolrox95** [comment]
The GP generated from township is not a separate resource, and is the same GP that you spend in the shop.
