### ISSUE TITLE
[Bug]: Township guide not showing when clicking icon (in Spanish)

### ISSUE THREAD

**Issue by fbalaguera** [MelvorIdle/melvoridle.github.io#2712]
### Describe the bug

When I press the icon of the Township's guide, the help does not appear, it stays blank. Same problem on Android and STEAM.

I use the Spanish language.

### Screenshots

![melvor](https://user-images.githubusercontent.com/3457300/196994225-12705ac3-04bc-4b5c-b3ac-2f2045da6433.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4500

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Township has now been reworked as of v1.1.2
