### ISSUE TITLE
[Bug]: <Only 2 equip food slots>

### ISSUE THREAD

**Issue by KAZ-2Y5** [MelvorIdle/melvoridle.github.io#2716]
### Describe the bug

My third slot to equip a food disappeared.

### Reproduction Steps

No idea how it happen

### Expected behaviour

Be able to equip a third food.

### Save Link

https://melvoridle.com/save/QU8g8mRm

### Screenshots

![Screenshot_20221020-133505_Melvor Idle](https://user-images.githubusercontent.com/113224530/197020064-90f0e964-77a4-4076-a422-f5a287e85a58.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [x] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

N/A

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was hotfixed as of v1.1 (?4516).
