### ISSUE TITLE
[Bug]: God of Worship is no longer apart of my town. Tasks reset.

### ISSUE THREAD

**Issue by HyperFused** [MelvorIdle/melvoridle.github.io#2717]
### Describe the bug

Gamemode: Normal
Issue first noticed on browser: Opera GX
Mods:

- SEMI Core
- SEMI Drop Chances
- SEMI Auto Farming
- SEMI Auto Master
- Mastery Pool Can Overflow
- Mastery Virtual Levels
- Unlimited Offline

On 10/18 I started playing the Township update upon release. I chose Map 1 and Ragnar as my God of Worship. I completed all the Township Starter Guide Tasks and as well as some other tasks I already had the requirements for. I closed the game for the day when my town reached 9h 05m of existence.

On 10/19 I launched the game and all my town resources were unassigned at first glance. My Worship now shows _None :(_. I advanced 1 tick and my resources populated with workers once again, although some of them on the wrong resources. I still didn't see anything in place of my Worship, so I advanced another tick to see if it would update. It has not updated, and I have not progressed my town past 9h 15m. In addition, all my progress towards my tasks have reset, I am back to the first stage of my Township Starter Guide, and I am showing 0 / 114 Tasks completed overall. However, I still retain the rewards I received for turning in some Easy-Elite tasks.

10/20 The worship is still showing as _None :(_. However, my resources stayed populated this time. I have not advanced my town any further. All my Tasks are still showing as 0 / 114 completed.

### Reproduction Steps

Unknown.

### Expected behaviour

I expected to have Ragnar Bonuses upon loading into my Township on 10/19, but I no longer have a worship. I had completed all the Starter Guide tasks as well as some additional tiered tasks, but I am back at the beginning with 0 / 114 tasks completed.

### Save Link

https://melvoridle.com/save/pFfJJExB

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4501

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This has now been fixed as of v1.1.1.
