### ISSUE TITLE
[Bug]: Level 105 ore wrong pickaxe requirement

### ISSUE THREAD

**Issue by Boluss** [MelvorIdle/melvoridle.github.io#2719]
### Describe the bug

I'm currently level 104 mining and have the Corundum Pickaxe purchased, yet it still says I need to purchase it instead of raising my mining level.

![image](https://user-images.githubusercontent.com/116307541/197036243-cd702de7-13a5-4496-9a5f-4cb86fb93fe5.png)

### Reproduction Steps

1. Be level 104 mining
2. Buy the Corundum Pickaxe

### Expected behaviour

Requirement text shouldn't tell me I need to buy the Corundum Pickaxe after I've already done so.

### Screenshots

![image](https://user-images.githubusercontent.com/116307541/197036206-6579356c-1143-48f1-aca7-009724cab79c.png)
![image](https://user-images.githubusercontent.com/116307541/197036292-a117814d-9f5e-4018-804f-9d50b93b38bf.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4500

### Are you using any mods?

Yes

**Comment by Nashmann71** [comment]
I am having the same problem as well. I am not using any mods. I am using the mobile app(iOS). Current mining level is 107

**Comment by MelvorIdle** [comment]
The game is simply showing you the requirements. You need Level 105 and the pickaxe from the shop. When you reach Level 105 it will unlock.
