### ISSUE TITLE
Fishing cape does not work offline for mastery progress

### ISSUE THREAD

**Issue by kingas2000** [MelvorIdle/melvoridle.github.io#272]
**Describe the bug**
I have in the bank almost twice as much of four types of fish, but only 25k fished for mastery. Just today I logged in and in the offline gain screen it showed that I fished 18k sardines, but the mastery only showed 9k. However, online it does work.

**To Reproduce**
1. Put on the fishing skill cape.
2. Start fishing, preferably something quick to catch.
3. Save manually.
4. Log off and wait for 5 minutes.
5. Log back in. 

**Expected behavior**
The offline gain screen should say that You got twice as much fish than the mastery level. However, if You would wait and see, the counter does increase when You catch 2 or even 4 fish.

**Screenshots**
![Going to catch a new fish](https://user-images.githubusercontent.com/66405068/83720203-50636e00-a641-11ea-95a4-4ebb74e59e21.PNG)
![Waited 5 minutes and it says I have caught 152 herrings](https://user-images.githubusercontent.com/66405068/83720206-50fc0480-a641-11ea-9eb1-858e718bd370.PNG)
![Mastery level did not go up by this amount](https://user-images.githubusercontent.com/66405068/83720207-50fc0480-a641-11ea-83f8-23ef8eb5b5b6.PNG)

**Browser**
Chrome, version 0.15.1

**Console output**
Please open the console by pressing F12 and copy it here.
Sorry, I do not know what this is.

**Are you using any scripts?**
No, I did not.

**Comment by MelvorIdle** [comment]
This is fixed in an upcoming update :)
