### ISSUE TITLE
[Bug]: <title>mining pure essence uses up gem glove charges

### ISSUE THREAD

**Issue by minaolenpalm** [MelvorIdle/melvoridle.github.io#2720]
### Describe the bug

as in title - when i wear gem gloves, the stacks go down when mining pure essence.

### Expected behaviour

gloves state that it only applies to rocks

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4501

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was fixed as of v1.1.1 (?4999).
