### ISSUE TITLE
[Bug]: New skill capes doesnt apear in quick equip menu

### ISSUE THREAD

**Issue by mo35** [MelvorIdle/melvoridle.github.io#2721]
### Describe the bug

as subject says

### Reproduction Steps

-

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4501

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
The quick equip menu is customised by the player - this can be done by selecting the item in the bank and clicking the settings icon.
