### ISSUE TITLE
[Bug]: Red Dragon has a passive.

### ISSUE THREAD

**Issue by Volvary** [MelvorIdle/melvoridle.github.io#2725]
### Describe the bug

Red Dragon in Dragon Valley currently has the **Curse of the Undead** passive, which makes it hell to kill, especially at lower levels.

### Reproduction Steps

Go to Dragon Valley, fight Red Dragon

### Expected behaviour

Red Dragons do not have an end-game, expansion passive, making them extremely deadly

### Screenshots

![image](https://user-images.githubusercontent.com/3761531/197082638-52cd6fc9-015f-4c81-897a-96c34a5617a5.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4501

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was hotfixed as of v1.1 (?4516).
