### ISSUE TITLE
[Bug]: Thieving Shorts not appearing in quick equip for Thieving

### ISSUE THREAD

**Issue by BritDevil** [MelvorIdle/melvoridle.github.io#2727]
### Describe the bug

The new thieving shorts item which are stolen from Explorer are not being recognised as a quick equip item for Thieving despite giving Thieving stats.

### Reproduction Steps

1. Steal from explorer until thieving shorts are gained
2. Go to the quick equip menu in thieving skill
3. Thieving Shorts do not appear for selection
4. Go to storage
5. Thieving Shorts are equippable here
6. Recheck thieving quick equip menu
7. Thieving Shorts are still not visible for selection.

### Expected behaviour

Thieving Shorts were expected to be selectable from the thieving quick equip menu.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4501

### Are you using any mods?

No

**Comment by coolrox95** [comment]
You can customize which items appear in the quick equip items yourself via the item settings in the bank.
