### ISSUE TITLE
Unlimited M-Bucks leads to free opening of cases and free money

### ISSUE THREAD

**Issue by ArticPanda43** [MelvorIdle/melvoridle.github.io#273]
You can get unlimited M-Bucks which means opening the cases however many times you want

click beg parents for money button,
go to console and click the js function associated with the button caseoffortune.js to open the file,
go to the begParentsForMBucksBecauseImBrokeAndCantAffordToBuyItInTheP2WShopEvenThoughIShouldProbablyMakeDragonJavsForMoneyOhWaitLol function
delete it all and change it to:
mbucks = 99999999999;
updateMbucks();

changes yours M-bucks to 9999999999 and allows you to open cases and then store the items and sell them for coins

**Screenshots**
![lol](https://user-images.githubusercontent.com/52451679/83773738-d355ea00-a67c-11ea-87eb-e18ea7aec3f4.PNG)

Chrome Version 83.0.4103.61

**Console output**
Idk that line about Nothing LOL (I am also clogging up your console on purpose)

**Are you using any scripts?**
None

**Comment by ArticPanda43** [comment]
Also cause the page never gets reloaded the js file stays like that

**Comment by MelvorIdle** [comment]
This is pretty much what the game allows you to do. Its client sided, so you are able to edit everything within the game to how you like
