### ISSUE TITLE
[Bug]: Weird gloop and compost toasts for not having weird gloop or compost are swapped

### ISSUE THREAD

**Issue by nickwigton** [MelvorIdle/melvoridle.github.io#2732]
### What text is wrong?

When you lack compost or weird gloop and attempt to add it to a farming patch, a toast shows up that you don't have the required material. When you attempt to add **compost** when you don't have it, it says that "You need **Weird Gloop** to add Weird Gloop!" If you attempt to add **weird gloop** when you don't have it, it says "You need **Compost** to add Compost!"

### What is the correct spelling or grammar?

If you attempt to add compost it should say "You need Compost to add Compost!" and if you attempt to add Weird Gloop it should say "You need Weird Gloop to add Weird Gloop!" rather than the other way around.

**Comment by coolrox95** [comment]
Issue has been hotfixed as of v1.1 (?4598).
