### ISSUE TITLE
[Bug]: Cloudburst rune consumption has doubled per tick

### ISSUE THREAD

**Issue by aimcircle** [MelvorIdle/melvoridle.github.io#2735]
### Describe the bug

After the expansion released, my cloudburst staff consumes rune per proc, AND per successful hit. So it consumes doubled rune for every successful hit.
Also, prayer points was paid per cast, not per proc. (similar to sandstorm ring)

### Reproduction Steps

1. Equip Cloudburst staff
2. Go for a battle and cast spell (I used Water wave and Surge I)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4516

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been hotfixed as of v1.1 (?4628).
