### ISSUE TITLE
[Bug]: Township people dying, despite 100% health

### ISSUE THREAD

**Issue by NemyTR** [MelvorIdle/melvoridle.github.io#2736]
### Describe the bug

Like the title says, health is at 100% but cemetery is still filling up.

### Expected behaviour

No people should die if health is at 100%

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4516

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Citizens die of old age when they reach 100 years, regardless of your health value.
