### ISSUE TITLE
[Bug]: Superior Skillcapes not showing up in quick equip

### ISSUE THREAD

**Issue by Marthioo** [MelvorIdle/melvoridle.github.io#2737]
### Describe the bug

I have noticed that the superior skillcapes do not show up in quick equip for each skill (the cog in each skill), but their regular skillcape versions do show up.

### Reproduction Steps

Go to any skill with a superior skillcape, eg. farming. 

Click the cog, bringing up the quick equip menu.

Notice that superior skillcape is not there.

profit.

### Expected behaviour

I expected the superior skillcape to be in quick equip

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4516

### Are you using any mods?

No

**Comment by 0x00A** [comment]
I can confirm that this happens on Steam and Android V1.1?4516 as well.

**Comment by coolrox95** [comment]
The quick equip menu is customised by the player - this can be done by selecting the item in the bank and clicking the settings icon.

**Comment by Marthioo** [comment]
But as a default, the maximum skillcapes are part of the quick equip menu. So why are the superior maximum skillcapes not part of the default? That does not make any sense and should be fixed.
