### ISSUE TITLE
[Bug]: Back button handling

### ISSUE THREAD

**Issue by BaranDev** [MelvorIdle/melvoridle.github.io#2738]
### Describe the bug

When I click on Back button on my mouse it takes me back to character selection. Before it was taking me to last page I was on.

### Reproduction Steps

1. Change any page.
2. Click to "Back" button on mouse.

### Expected behaviour

It should take me back to the last page I was on.

### Save Link

https://melvoridle.com/save/sEaRke64

### Screenshots

-

### Console output

-

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4516

### Are you using any mods?

Yes

**Comment by Svish** [comment]
This also happens with the back button on my Android phone and it's _super_ annoying.

**Comment by samosbor** [comment]
+1 
Related to https://github.com/MelvorIdle/melvoridle.github.io/issues/3549
