### ISSUE TITLE
[Bug]: Purchase mining gloves

### ISSUE THREAD

**Issue by Incriptionz** [MelvorIdle/melvoridle.github.io#2739]
### Describe the bug

On my HCIM i sell my mining gloves after im done ussing them after the purchase of Throne of the Herald i can purchase charges for the gloves but do not recive any gloves only charges so i can not get the gloves back.

### Reproduction Steps

1. sell mining gloves
2. attempt to rebuy gloves
3. receive charges and no gloves

### Expected behaviour

i would receive mining gloves along with the purchase of charges

### Save Link

https://melvoridle.com/save/iK1j0PIR

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4516

### Are you using any mods?

No

**Comment by 47Y** [comment]
You have Mining Gloves equipped in your Equipment Set 4.
