### ISSUE TITLE
[Bug]: insane amount of lag/unresponsive on mobile android and pc

### ISSUE THREAD

**Issue by BenjiStoneHenji** [MelvorIdle/melvoridle.github.io#2741]
### Describe the bug

the past couple months (maybe even a lil longer) the game has felt unbearably slow/laggy when trying to open side skill menu or switching between bank tabs, etc. really just about every aspect is so slow its making me not want to attempt combat on my main character anymore which is hard-core. and now with the new expansion it feels even worse. really would love a solution to this seeing as how many people have paid for the base game on steam plus now everyone buying the expansion and anyone that may have donated to support through patreon or wherever donations are possible. not sure if it's just android that's this slow but I have noticed it a fair amount even on pc. also this is all without the use of mods just the core game itself 

### Reproduction Steps

do just about anything and it takes forever to load/switch to what you click on.

### Expected behaviour

less delay/lag

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4516

### Are you using any mods?

No

**Comment by CoryPolicht** [comment]
Duplicate of #1704 
Duplicate of #2355 
Duplicate of #2583 

I too have been experiencing this issue for quite some time. Attached is a video to demonstrate what it looks like. Doesn't appear to be device specific. I have a galaxy s21 ultra.

https://user-images.githubusercontent.com/12902029/197375919-4e904b7c-efb0-4374-a23f-46b30ffb84f5.mp4

**Comment by MelvorIdle** [comment]
This most likely relates to accessibility apps trying to take control of Melvor.

See #2694 for more info
