### ISSUE TITLE
[Bug]: Secret Area disappears from fishing menu

### ISSUE THREAD

**Issue by Jaaj9** [MelvorIdle/melvoridle.github.io#2745]
### Describe the bug

I don't recall dropping the Message in the Bottle item to unlock the Secret Area, although somehow I had it unlocked. But now, it doesn't appear anymore on the Fishing Areas.

As you can see in one of the screenshots, I do have Mastery XP on the Seahorse and the Skeleton Fish.

### Expected behaviour

If I did unlock it using the item (which again, I don't recall dropping it), then it should remain unlocked

### Screenshots

![image](https://user-images.githubusercontent.com/110256505/197217262-184d8f85-057a-4ca8-972b-6b462b118535.png)
![image](https://user-images.githubusercontent.com/110256505/197217459-cf52ca79-019c-4baa-b205-d2900be7d981.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4516

### Are you using any mods?

No

**Comment by 47Y** [comment]
There was a bug where the secret area was showing to everyone, including those who had not read the Message in a Bottle. An update fixed that which is likely why you can no longer see it.
