### ISSUE TITLE
[Bug]: Firemaking wrong mastery xp

### ISSUE THREAD

**Issue by xK0ch** [MelvorIdle/melvoridle.github.io#2746]
### Describe the bug

The mastery xp that is shown does not reflect the actual mastery xp that you get. In the screenshot you can see that from one interval to the other we earned 308 mastery xp: 7.219.735 - 7219.427 = 308 XP, but the valuewe should get is 390 XP.
Either the value that is shown is wrong or the value that is actually earned.

### Expected behaviour

390 XP are earned instead of 308 XP

### Screenshots

![After](https://user-images.githubusercontent.com/83583758/197220129-a47f78a2-d722-4d55-ba6b-500ebd7ce708.png)
![Before](https://user-images.githubusercontent.com/83583758/197220193-93bd661d-3dab-4ed4-a5e4-fd7906773219.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4516

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was fixed as of v1.1.1 (?4999).
