### ISSUE TITLE
[Bug]: Empty Food Item shows up in Goblin Raid

### ISSUE THREAD

**Issue by Diaroguee** [MelvorIdle/melvoridle.github.io#2747]
### Describe the bug

When I attempted to get food for my goblin raid, I got an item which wasn't intended.

### Reproduction Steps

1. Get food from goblin raid
2. Randomly got this item 

### Expected behaviour

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/116374163/197237217-458bfc13-4ba8-4a99-bde2-fa568cec6006.png)

### Console output

N/A

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4516

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue has been hotfixed as of v1.1 (?4598).
