### ISSUE TITLE
[Bug]: Astrology pet "Astro" not scaled properly with rework

### ISSUE THREAD

**Issue by burkeg** [MelvorIdle/melvoridle.github.io#2749]
### Describe the bug

The astrology pet "Astro" gives "+0.1% chance to locate Golden Stardust in Astrology". Before the 1.1 patch, this was a significant buff since the base chance was 0.2. This pet was a +50% buff to base golden stardust income. After the 1.1 patch, with the base rate being 7%, the pet buff results in +1.43% buff to base golden stardust income.

### Expected behaviour

I'm **not** saying Astro should be buffed to +3.5% to match the pre 1.1 ratio but I think pet buff % should be addressed.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4516

### Are you using any mods?

No

**Comment by coolrox95** [comment]
This repository is for bug reports only, and not feedback or suggestions.
