### ISSUE TITLE
[Spelling/Grammar]: Superior Max Skillcape description says it requires 99 mining and crafting.

### ISSUE THREAD

**Issue by eessppeenn001** [MelvorIdle/melvoridle.github.io#2750]
### What text is wrong?

In item description for Superior Max Skillcape, it says requirements are lvl 120 in all skills, except for mining and crafting wich is only lvl 99.
![bilde](https://user-images.githubusercontent.com/116385502/197269121-d10d9342-8095-456d-be1f-69f2e8a7ad50.png)

### What is the correct spelling or grammar?

It requires lvl 120 in all skills.

**Comment by eessppeenn001** [comment]
Well, at least this is how it appears in Golbin Raid

**Comment by coolrox95** [comment]
Issue has been hotfixed as of v1.1 (?4598).
