### ISSUE TITLE
Items dissapearing from inventory[Bug]: <title>

### ISSUE THREAD

**Issue by Leveled99** [MelvorIdle/melvoridle.github.io#2751]
### Describe the bug

Currently playing primarily in web browser, some on my moble (android) but not while noticing the bug.  

At the moment my full summoning outfit as well as 4x max capes are just no longer in my inventory/equipped.  Through bank search and visual validation, the items don't seem to exist. I know the max capes existed earlier today as I was equipping for firemaking. I changed to astrology (w/ the cape still on) and was training. I then swapped to my 120 summoning cape and can no longer find the max cape(s). 

As for the necro, I hadn't worn it, but I was comp pre-expansion and I do NOT sell things. It was previously locked.  

### Reproduction Steps

unable to reproduce (though really hoped I wouldn't) 

Empty Equipment slot 3, started to add in, but couldn't find the necro pieces. Then equipped the summoning 120 cape in place of the max cape.  Later unable to find the max cape.  

### Save Link

https://melvoridle.com/save/4nxTtoQZ

### Screenshots

Copied console input below, note this was after a reload when i was getting my save link above so may have been past the original issue

Also no screenshots as I repurchased items (my apologies)

### Console output

Failed to load resource: the server responded with a status of 404 ()
cloudManager.js?4516:196 Silent Sign in with JWT
cloudManager.js?4516:196 Validating Melvor Cloud token
cloudManager.js?4516:196 Storing Melvor Cloud Token
cloudManager.js?4516:196 Initializing PlayFab login. Method: customID
cloudManager.js?4516:196 Logging in with Custom ID via PlayFab
cloudManager.js?4516:196 Login with custom ID success
cloudManager.js?4516:196 Getting account info
cloudManager.js?4516:196 Account info retrieved
cloudManager.js?4516:196 Authenticated w/ Melvor Cloud: true
cloudManager.js?4516:196 Authenticated w/ PlayFab: true
cloudManager.js?4516:196 Checking for valid full version
cloudManager.js?4516:196 Checking for valid TotH purchase
cloudManager.js?4516:196 Loading Game Data...
save.js?4516:111 Registered Demo Data.
save.js?4516:111 Registered Full Version Data.
save.js?4516:111 Registered Throne of the Herald Data.
cloudManager.js?4516:196 Initializing Mod Manager...
cloudManager.js?4516:196 Loading Local Saves...
cloudManager.js?4516:196 Loading Cloud Saves...
cloudManager.js?4516:196 Getting saves from playfab
cloudManager.js?4516:196 Saves retrieved
characterSelect.js?4516:5 Loading character selection
cloudManager.js?4516:291 Connected to PlayFab successfully
save.js?4516:39 Copied to clipboard successfully.
main.js?4516:15 Game Loaded
Import.js:476 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Import.js:476:35)
    at Import.js:501:30
Plotter.js:545 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Plotter.js:545:35)
    at Plotter.js:570:30
Loot.js:585 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Loot.js:585:35)
    at Loot.js:610:30
Menu.js:168 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Menu.js:168:35)
    at Menu.js:193:30
Simulator.js:1173 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Simulator.js:1173:35)
    at Simulator.js:1198:30
SimEnemy.js:75 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (SimEnemy.js:75:35)
    at SimEnemy.js:100:30
SimManager.js:330 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (SimManager.js:330:35)
    at SimManager.js:355:30
SimPlayer.js:807 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (SimPlayer.js:807:35)
    at SimPlayer.js:832:30
TabCard.js:131 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (TabCard.js:131:35)
    at TabCard.js:156:30
util.js:251 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (util.js:251:35)
    at util.js:276:30
modifierNames.js:931 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (modifierNames.js:931:35)
    at modifierNames.js:956:30
App.js:3018 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (App.js:3018:35)
    at App.js:3043:30
AgilityCourse.js:255 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (AgilityCourse.js:255:35)
    at AgilityCourse.js:280:30
main.js:99 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (main.js:99:35)
    at main.js:124:30
Card.js:605 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Card.js:605:35)
    at Card.js:630:30
CombatData.js:174 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (CombatData.js:174:35)
    at CombatData.js:199:30
Consumables.js:397 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Consumables.js:397:35)
    at Consumables.js:422:30
DataExport.js:186 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (DataExport.js:186:35)
    at DataExport.js:211:30
ExportCheat.js:192 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (ExportCheat.js:192:35)
    at ExportCheat.js:217:30
cloud.js?4516:29 Synchronising with Cloud
style.css:1          Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4516

### Are you using any mods?

No

**Comment by ekuland** [comment]
Those console texts read like you still have the old, broken combat simulator installed as an extension

idk if those are directly related to the issue, but the extension touching equipped items I wouldn't be surprised

uninstall all melvor idle extensions/scripts

**Comment by Leveled99** [comment]
thanks i made sure i didn't have a mod, but completely forgot that other injects.

**Comment by Leveled99** [comment]
also, i am unsure what might have caused the item disappearance, if it was that combat sim all the better, if uninstalling stops future issues. Just wanted the visibility bc some people aren't going to be able to just rebuy things

**Comment by coolrox95** [comment]
Closing this as there were no reproduction steps, and it was likely an issue with mods.
