### ISSUE TITLE
[Bug]: Browser version stuck at Demo, mobile version purchased

### ISSUE THREAD

**Issue by Meatshock** [MelvorIdle/melvoridle.github.io#2754]
### Describe the bug

Full mobile version purchased.  Cloud account created. Browser shows demo version. Cloud saves work between versions. Multiple login/logout attempts. 

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4516

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This issue has been recently hotfixed. Please log back into mobile to synchronize the purchase status once more.
