### ISSUE TITLE
Farm slots bug[Bug]: <title>

### ISSUE THREAD

**Issue by krxone** [MelvorIdle/melvoridle.github.io#2755]
### Describe the bug

Some of my slots at my Farmtab are buggy

### Reproduction Steps

Just open my Farmtab

### Save Link

https://melvoridle.com/save/jwMa1kAt

### Screenshots

![bugpic1](https://user-images.githubusercontent.com/20149678/197307510-d53188df-86d0-4973-8bc9-c87e51994d7c.jpg)
![bugpic2](https://user-images.githubusercontent.com/20149678/197307511-bc52e332-3f55-4bdb-9d17-3ed2a46fe582.jpg)
![bugpic3](https://user-images.githubusercontent.com/20149678/197307514-7b9d961b-219c-45f9-b418-bb8a936a43e9.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4516

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.2,
