### ISSUE TITLE
[Bug]: Save blueprint name field text invisible when using light mode

### ISSUE THREAD

**Issue by okk-libre** [MelvorIdle/melvoridle.github.io#2757]
### Describe the bug

When using light mode, text entered into the name field when saving an agility blueprint is set to the same colour as the white background, making it invisible.

### Reproduction Steps

1. Set game to light mode
2. Go to agility
3. Click 'Save Blueprint'
4. Enter text into the name field

### Expected behaviour

The text should be visible

### Screenshots

![blueprint1](https://user-images.githubusercontent.com/50540934/197318827-462cac51-c7e9-43db-9373-bffee93216a9.png)
![blueprint2](https://user-images.githubusercontent.com/50540934/197318829-5f3553ea-e5c9-4208-a8ce-d6771e86216e.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4516

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.1 (?4673).
