### ISSUE TITLE
[Bug]: new pickaxes bug (no mine time reduction) 

### ISSUE THREAD

**Issue by ztanita** [MelvorIdle/melvoridle.github.io#2759]
### Describe the bug

New pickaxes deleted the mine time reduction bonus (50% for dragon axe disappeared) 

### Expected behaviour

Restore the mining time reduction bonus 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4516

### Are you using any mods?

No

**Comment by ztanita** [comment]
Same for all other bonus equipment

**Comment by coolrox95** [comment]
The bonuses from the previous pickaxes still apply, this is just a visual bug with the upgrade information.

**Comment by ztanita** [comment]
Ok, thanks
