### ISSUE TITLE
[Bug]: Township tasks reset (possible duplicating rewards), mastery pool reset, all equipment unequipped

### ISSUE THREAD

**Issue by UnNamed23** [MelvorIdle/melvoridle.github.io#2761]
### Describe the bug

I had been logged off from the cloud in browser, but I didnt notice, so I loaded the Save and saw that I had a view of melvor like a free account.
So I refreshed, logged in, and the skill I was doing, went from 100% mastery to 50% (like when you just bought the DLC), all of the equipment was unequipped (all 4 sets, good thing the items did not disappear, even though the bank was full, like 408/390), and later I noticed that all the tasks I've done were reset, so I could basically get all the rewards I got before, once again.
I suppose this is redoable, so you could probably dupe all the rewards from township tasks.

### Reproduction Steps

Log off from cloud
Load save
Refresh
Log in and load save
stonks
(I suppose it will work, since it already worked once, i didnt try more)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4526

### Are you using any mods?

No

**Comment by UnNamed23** [comment]
Other things i noticed happened - 
Township now no longer has a worshipped god
Most of the skill's quick equip slots are broken, not showing all items or nothing at all

**Comment by MelvorIdle** [comment]
This has now been fixed as of v1.1.1.
