### ISSUE TITLE
[Bug]: When demolishing Farmer's Markets, food consumption is not affected until game reload

### ISSUE THREAD

**Issue by catharsis71** [MelvorIdle/melvoridle.github.io#2764]
### Describe the bug

When building farmer's markets, food consumption is immediately decreased, but when demolishing them, the food discount remains, even after passing ticks, until the game is reloaded.

### Reproduction Steps

Build farmer's markets
Observe that food consumption is decreased
Demolish farmer's markets
Observe the food consumption remains the same
Reload the page
Observe that food consumption is decreased

### Expected behaviour

Food consumption should decrease with farmer's markets are demolished without needing to reload the page

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

4526

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
I believe this bug actually relates to #2685 

Possibly an issue with how workers are being assigned.

**Comment by catharsis71** [comment]
Farmer's markets don't have workers, though?  Am I misunderstanding?

**Comment by MelvorIdle** [comment]
The bug did indeed affect non-worker buildings as well after looking into it further.

A hotfix has now been applied to the game for this issue.

Please open a new issue if you notice the bug again.
