### ISSUE TITLE
[Bug]: Negative potion consumption in township

### ISSUE THREAD

**Issue by TheSingular** [MelvorIdle/melvoridle.github.io#2765]
### Describe the bug

For some reason, I have negative potion consumption in township skill. In other words, I gain potion resources with every tick, without any building that produces it. It's really weird.

### Reproduction Steps

I really don't know how to reproduce this, it just... happened.

### Expected behaviour

Township consuming potion recourses properly.

### Screenshots

![Screenshot_20221022-213712_Melvor Idle](https://user-images.githubusercontent.com/18699171/197357347-018cd35d-3e13-45bc-b827-ad2b01dafc33.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4526

### Are you using any mods?

No

**Comment by TheSingular** [comment]
Restarting the game, I now have better info about this bug: After restart, my potion consumption part became -71/t, but after progressing about 10 ticks it became -68/t. I guess that this amount will keep decreasing(eventually becoming negative consumption as shown in the screenshot) as I progress the town by ticks until I restart the game again.

**Comment by MelvorIdle** [comment]
Related to #2648

**Comment by TheSingular** [comment]
> Related to #2648
Yes but

**Comment by TheSingular** [comment]
Accidentally closed.

> Related to #2648

Probably. What he forgot to mention is that the potion consumption is reflected properly when the game is loaded from a save. Only new citizens over age 55 from that point onwards have this bug.

**Comment by MelvorIdle** [comment]
Township has now been reworked as of v1.1.2
