### ISSUE TITLE
[Bug]: Goblin Raid seems buggy, rune behaviour is incorrect, timing is off

### ISSUE THREAD

**Issue by arnfiix** [MelvorIdle/melvoridle.github.io#2767]
### Describe the bug

During a goblin raid, new runes are not being added to my stockpile of runes. I was also offered non-rune rewards (I believe some kind of essence, which may or may not be some new thing in the expansion I just haven't gotten to yet).

And lastly, I don't think my raid actually took this long?
![image](https://user-images.githubusercontent.com/2829194/197364658-c69badba-1502-45c0-a4fa-a7448842db0b.png)

### Expected behaviour

When selecting runes, I'd anticipate I am offered runes, choose them, and they are added to my stockpile for use.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4501

### Are you using any mods?

No

**Comment by arnfiix** [comment]
Running another raid, I believe the rune count isn't being correctly updated in real time. I just lost two magic weapons due to not having enough runes, despite "having" the below runes. I would also note that the number of runes shown in the below image have not gone up or down since the beginning of the raid.

![image](https://user-images.githubusercontent.com/2829194/197365814-de65ae5a-e013-41c6-a08c-36baf6340f5b.png)

**Comment by coolrox95** [comment]
Issue has been hotfixed as of v1.1 (?4598).
