### ISSUE TITLE
Stuck in tutorial: cannot afford Compost

### ISSUE THREAD

**Issue by aldiyen** [MelvorIdle/melvoridle.github.io#2769]
### Describe the bug

I’m on step 8/10 of the tutorial where I’m supposed to buy 5 compost but it costs 500 gold and I don’t even have enough for 1 compost. It’s unclear how I’m supposed to earn this much money and moreover I can’t apparently do anything other than buy this thing I can’t afford. How do I proceed?

### Save Link

https://melvoridle.com/save/p3jU9xnS

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4526

### Are you using any mods?

No

**Comment by Zethraxxur** [comment]
You should be able to skip the tutorial in worst case. If you want to still do it to understand the game, I suggest either deleting and re-doing the tutorial or make a second account to do the tutorial there.
