### ISSUE TITLE
[Bug]: error calculating offline progress <title>

### ISSUE THREAD

**Issue by PouletR0ti** [MelvorIdle/melvoridle.github.io#2771]
### Describe the bug

I got the following error when i logged back after 7h of offline progress.

"WE ran into an error while calculating your offline progress
Your skill was also stopped in the process."

While i didn't loot anything, I still got the mark discovery message.

### Save Link

https://melvoridle.com/save/S2MM7NFX

### Console output

An error occured while processing ticks offline:
Active Action: melvorD:Combat
Error Name: Error
Error Message: Tried to remove quantity from bank, but item is not in bank.
Stack Trace:
Error: Tried to remove quantity from bank, but item is not in bank.
    at Bank.removeItemQuantity (https://android.melvoridle.com/assets/js/built/bank2.js?4526:103:7)
    at https://android.melvoridle.com/assets/js/built/bank2.js?4526:113:49
    at Array.forEach (<anonymous>)
    at Bank.consumeItems (https://android.melvoridle.com/assets/js/built/bank2.js?4526:113:27)
    at Player.consumeRunes (https://android.melvoridle.com/assets/js/built/player.js?4526:157:142)
    at Player.attack (https://android.melvoridle.com/assets/js/built/player.js?4526:129:6)
    at Player.act (https://android.melvoridle.com/assets/js/built/character.js?4526:268:69)
    at Player.timers.act [as action] (https://android.melvoridle.com/assets/js/built/player.js?4526:3:1676)
    at Timer.tick (https://android.melvoridle.com/assets/js/built/combatManager.js?4526:252:89)
    at Player.activeTick (https://android.melvoridle.com/assets/js/built/character.js?4526:260:30)
Current Equipment:
Helmet: melvorF:Glacia_God_Helmet
Platebody: melvorF:Glacia_God_Platebody
Platelegs: melvorF:Glacia_God_Platelegs
Boots: melvorF:Glacia_God_Boots
Weapon: melvorF:Cloudburst_Staff
Amulet: melvorD:Fury_of_the_Elemental_Zodiac
Ring: melvorD:Aorpheats_Signet_Ring
Gloves: melvorF:Glacia_God_Gloves
Cape: melvorF:Max_Skillcape
Passive: melvorF:Chapeau_Noir

Action Information:
Is In Combat: true
Fight in Progress: true
-- Start of Player Information --
Next Action: Attack
Next Attack: melvorF:FreezeRay
Is Attacking: false
Standard Spell Selected: [object Object]
Ancient Spell Selected undefined
Aurora Selected: [object Object]
Curse Selected: [object Object]
Active Prayers:melvorTotH:Battleborn, melvorTotH:DivinePrecision, 
Equipped Food:
Item: melvorD:Plain_Pizza_Slice_Perfect, Qty: 71896
Item: melvorD:Plain_Pizza_Slice, Qty: 12248
Item: melvorD:Lobster, Qty: 26987
-- End Player Information --
-- Start of Enemy Information --
Enemy: melvorF:Umbora
Next Action: Attack
Next Attack: melvorF:Elusiveness
Is Attacking: false
Standard Spell Selected: [object Object]
Ancient Spell Selected undefined
Aurora Selected: undefined
Curse Selected: undefined
-- End Enemy Information --
Current Area Type: Slayer
Current Area ID: melvorF:Dark_Waters
Modding Enabled. Loaded mods:
Dev

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4526

### Are you using any mods?

No

**Comment by PouletR0ti** [comment]
It happened again, and i think it's because i went out of runes both of the time.

**Comment by coolrox95** [comment]
Issue has been hotfixed as of v1.1 (?4628).
