### ISSUE TITLE
[Bug]: Game opening in demo version, deleting township progress

### ISSUE THREAD

**Issue by renedetto** [MelvorIdle/melvoridle.github.io#2774]
### Describe the bug

Opened the application like normal, and noticed that it was in F2P/demo version. My account is grandfathered and has purchased the DLC. Signed out of cloud completely and logged back in, and was back into the full version.

All my equipment loadouts were now unequipped, all my township tasks were uncompleted (down from 96 completed to 0), and my township worship was set to None. With no active worship, the town I had spent 4 days of ticks on meticulously minmaxing to reach 120 as fast as possible is now impossible to progress without sending the population count down a death spiral, and has to be reset. 

I tried to set the worship back with the "game.township.selectWorship()" function, but the argument format is unclear. The lost tasks can be recovered through adding the items spent on them, but the tutorial tasks can't be completed without progressing the town with the resources I have banked. 

### Reproduction Steps

1. Open the app as normal, the reason why I was put into the f2p version is unclear.
2. Cloud save is overwritten with f2p data.
3. Sign out of cloud and sign back in.
4. Open the game, now in full version.
5. Township progress is lost.

### Expected behaviour

A failsafe that preserves all township data when being switched to f2p from a bug/error from full version. Not being downgraded to f2p from a full version at all.

### Save Link

https://melvoridle.com/save/IeWABmS8

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4526

### Are you using any mods?

Yes

**Comment by Talus81** [comment]
Hi,

i have the exact same problem.
I am also using Chrome and Mobile-App.
Have also Version V1.1
Subversion ?4615
But i am using no mods, so i think this seems to be a general problem when you are using also the the mobile app and this one does not recognize that you already have bought the game.
