### ISSUE TITLE
[Bug]: Alchemist's Bags are not consumed per potion charge used

### ISSUE THREAD

**Issue by esso23** [MelvorIdle/melvoridle.github.io#2778]
### Describe the bug

No charges are spent on Alchemist's Bag, no extra charges added to Potion

### Reproduction Steps

Equip Secret Stardust Potion IV
Study Astrology Variel Sign

### Expected behaviour

Alchemist't Bag described behavior.

### Save Link

https://melvoridle.com/save/XyVybvx4

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4526

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was fixed as of v1.1.1 (?4999).
