### ISSUE TITLE
[Bug]: <title>Cant do anything 

### ISSUE THREAD

**Issue by N0Xzzz** [MelvorIdle/melvoridle.github.io#2779]
### Describe the bug

I was cutting wood, locked my Ipad for a few minutes when I came back was unable to perform any task or enter combat and has been like this for one day 
Playing on IPad mini

### Save Link

https://melvoridle.com/save/RmesFDag

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4526

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.1.2
