### ISSUE TITLE
Deadeye Amulet Proc Rate Is Incorrect

### ISSUE THREAD

**Issue by AnnoRagnarok** [MelvorIdle/melvoridle.github.io#278]
I'm pretty certain the Deadeye amulet is bugged. It's supposed to proc 25% of the time but I'm getting proc rates more in the 66% range. I'm using Stormsnap's special to keep track of this as it does consistent damage. 

After checking the code I think I have an idea why- It rolls a 1-100 and checks if that number is higher than the deadeye amulet's "chance to crit" which, if it's set to 25%, would make the actual crit chance 75%, not 25%. Either way it's probably a big reason why Stormsnap was so powerful in reality, as it's a 37.5% damage boost, not a 12.5%

The actual numbers I recorded were 8 non-procs, 19 procs, and then 10 where I couldn't tell if it was or wasn't as it killed the monster. A small sample size, but the difference is large enough even at this point to raise questions, in addition to my non-recorded noticings throughout the past few days where it seemed to almost always proc on Stormsnap's special.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
