### ISSUE TITLE
[Bug]: Ent/Crow synergy consumes tablets when the synergy is not in effect

### ISSUE THREAD

**Issue by otherzack** [MelvorIdle/melvoridle.github.io#2780]
### Describe the bug

Runecrafting: Ent/Crow synergy (+20% preservation when crafting staves) consumes 1/2 ent/crow tables even when not crafting staves (e.g. runes)

this is different from how other synergies work, both within RC and other skills:

- Pig/Crow (+15% preservation crafting runes) does NOT consume extra tablets when crafting e.g. staves/wands/gear

- Smithing: Octopus/Salamander (+15% preservation when crafting dragon gear) does NOT consume extra tablets when not crafting dragon gear (e.g. Mithril gear)

### Reproduction Steps

1. Go to runecrafting
2. equip Crow/Ent synnergy
3. Craft runes (not staves), observe tablet consumption
4. Go to smithing
5. Equip Octopus/Salamander synergy
6. Craft mithril gear, observe [lack of] tablet consumption

### Expected behaviour

Either synergies should consume the extra tablets always, or only when the effect is being utilized. Either way, the behavior should be the same across all skills/synergies.

I believe the expected behavior is to only consume extra tablets when the synergy effect is working, as I haven't found any other synergies that work like Ent/Crow and are always "active" in the skill

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

4526

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was fixed as of V1.1.2
