### ISSUE TITLE
[Bug]: <Can't read books>

### ISSUE THREAD

**Issue by RayzenOri** [MelvorIdle/melvoridle.github.io#2783]
### Describe the bug

Cannot reading books, after clicking on read button nothing happened.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4598

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was fixed as of v1.1.1 (?4999).
