### ISSUE TITLE
[Bug]: Township - Map 6 - Water Biome maximum buildings issue

### ISSUE THREAD

**Issue by leearnold89** [MelvorIdle/melvoridle.github.io#2785]
### Describe the bug

Choosing Ragnar as the god and Map 6 as the choice, for some reason I have the ability to create 8,589,934,370 items in the water Biome instead of the 6 limit?

It started with 6/6.. then a load of the game a short while later it said (7/6)... short while later it said (-4294967185/6) and now its stuck with (-4294967185/4294967185).  This allows me to build as many items as I want as its pretty much no limit.

### Reproduction Steps

Not sure how to re-produce the behaviour, see above.

### Expected behaviour

I should only be able to build 6 fishing platforms on Map 6

### Save Link

https://melvoridle.com/save/CieK03MI

### Screenshots

https://imgur.com/a/LqNY6Ef

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

4598

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Township has now been reworked as of v1.1.2
