### ISSUE TITLE
[Bug]: <Wont show reroll buttons for modifiers>

### ISSUE THREAD

**Issue by MartinHojriis** [MelvorIdle/melvoridle.github.io#2786]
### Describe the bug

Im playing the game on steam, and have a game in both adventure and hardcore mode.

The problem is that within astrology under the explore, it wont show a button for rerolling the modifiers as i have seen in videos and screenshots of the game

### Expected behaviour

I expect there to be a button to be able to reroll my modifiers for example within the Terra tab I should be able to reroll my strength skill XP and Accuracy Rating into different modifiers according to the wiki and videos I have seen of the game

https://wiki.melvoridle.com/w/Astrology

### Save Link

https://melvoridle.com/save/bZuZKSo6

### Screenshots

![image](https://user-images.githubusercontent.com/93257358/197535361-6f1bf0de-a291-4813-beba-9b5dc5e909ea.png)
https://greasyfork.org/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTRDQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--75e1d1e4b15f3c0ae9a717babe450e052859b006/34.PNG?locale=en

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4598

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Astrology was reworked as part of the v1.1. update and the reroll mechanic no longer exists.
