### ISSUE TITLE
[Bug]: Bob's Gloves are not registered as a Farming Quick Equip

### ISSUE THREAD

**Issue by SaintWacko** [MelvorIdle/melvoridle.github.io#2787]
### Describe the bug

I would expect Bob's Gloves to show up in the Quick Equip menu for Farming, as Bob's Rake does, but they do not.

### Reproduction Steps

1. Acquire Bob's Gloves
2. Go to the Farming tab
3. Open the Quick Equip menu
4. Witness the lack of Bob's Gloves

### Expected behaviour

When opening the Quick Equip menu on the Farming tab, Bob's gloves should be present to be equipped, as they are a farming related piece of gear.

### Save Link

https://melvoridle.com/save/kRyWWLah

### Screenshots

<img width="301" alt="Screen Shot 2022-10-24 at 09 16 22" src="https://user-images.githubusercontent.com/10342141/197547867-43a4519e-afb0-4bc5-8593-b6c953624f14.png">

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4598

### Are you using any mods?

No

**Comment by OnDEK** [comment]
The quick equip menu is fully customizable, most items are not automatically assign to a skill.
You need to go to the bank and assign the item to a particular skill, see screenshot as reference. Hope this helps.

![image](https://user-images.githubusercontent.com/8886341/197862480-5427b683-3e39-41be-ae06-2389fb8ac556.png)

**Comment by SaintWacko** [comment]
Oh! That's very helpful, I had no idea. All the other items I had been using were already set correctly. Thanks!
