### ISSUE TITLE
[Bug]: Corundumite Ore not respawning

### ISSUE THREAD

**Issue by Creelman95** [MelvorIdle/melvoridle.github.io#2788]
### Describe the bug

I was mining corundite alongside other ores when it stopped respawning. It's been 2 days with the ore stuck at 0.

I have tried leveling ore up, unistalling, closing, but nothing will reset it.

Is there a dev commands I can use??

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4598

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
I have been unable to reproduce this issue. If the issue persists, please create a new ticket.
