### ISSUE TITLE
[Bug]: Body rune to loot

### ISSUE THREAD

**Issue by Tossak** [MelvorIdle/melvoridle.github.io#2790]
### Describe the bug

On iOS.  When mining I frequently receive Body Runes and the report says ‘Body rune to loot.’  When I check my bank it never shows these body runes and I have space available in my bank.

### Expected behaviour

I expected Body runes to show up in my bank.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4598

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
The Body Rune is sitting inside the Loot Container in combat, waiting to be looted.
