### ISSUE TITLE
Mole and Crow synergy with Pure Essence

### ISSUE THREAD

**Issue by IRONN1C** [MelvorIdle/melvoridle.github.io#2793]
### Describe the bug

It might not be a bug but I dont know cause the definition say it double rune essence and dont talk about Pure essence after all. But I feel like it would make sens too also work with Pure essence too like, the mining glove do. The crow and mole synergy work on rune essence but not on Pure essence.

### Reproduction Steps

1. Equip Mole and Crown sumon
2. Mine Rune essence
3. Mine Pure essence

### Expected behaviour

It should probably double Pure essence too.

### Screenshots

![bug1](https://user-images.githubusercontent.com/98619367/197580865-150ec441-cf2e-4b86-91e4-3da567de8804.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4598

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Working as intended. The synergy specifically says "Rune Essence", and not just "Essence".
