### ISSUE TITLE
[Bug]: Poison Pods damage can be increased by selecting another spell.

### ISSUE THREAD

**Issue by griffin104** [MelvorIdle/melvoridle.github.io#2796]
### Describe the bug

Basically title, Poison Pods has very low spell damage but by selecting another spell during the cast, the damage goes way up. This results in the one-shotting of most enemies.

### Reproduction Steps

1. Start casting Poison Pods
2. Select another spell

### Expected behaviour

Damage from Poison Pods should not increase (or change in any way) when switching which spell to cast

### Screenshots

Not a screenshot but a video showing off the bug.
https://www.youtube.com/watch?v=-DFa3V_86Ck

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4526

### Are you using any mods?

Yes

**Comment by Verisimilitu** [comment]
Annotating that the bug still persists on V1.1.1, ?4937 and also includes Nature's Bloom spell. Testing others, but this is the only one that I have noticed besides the original Poison Pods bug.
