### ISSUE TITLE
[Bug]: <title> Golbin kill reset to 5 after updating to 1.1 </title>

### ISSUE THREAD

**Issue by DanDan2016** [MelvorIdle/melvoridle.github.io#2798]
### Describe the bug

 
Updated to 1.1, have golden golbin pet but golbin kill count for township tasks shows 5 kills. Most kills were done via golbin raid.

### Save Link

https://melvoridle.com/save/u49K2REh

### Screenshots

![image](https://user-images.githubusercontent.com/16484403/197651205-2fade8a9-fcf8-4ed1-aee7-a057b742cfaf.png)

![image](https://user-images.githubusercontent.com/16484403/197651584-6863f749-f71e-4c2e-b4a8-2c03ed4dcb8e.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4598

### Are you using any mods?

No

**Comment by ekuland** [comment]
Try killing one golbin outside of raid

**Comment by DanDan2016** [comment]
This did not work for me. Tried killing golbin first outside of raid then inside, did not update.
