### ISSUE TITLE
[Bug]: Township happiness not updating when unemployment decreases

### ISSUE THREAD

**Issue by Jared-g** [MelvorIdle/melvoridle.github.io#2799]
### Describe the bug

When unemployment decreases after spending a tick, but population didn't increase, the happiness penalty from that unemployment doesn't go away until an update is forced by building/destroying a building.

### Reproduction Steps

- On a new character, start a new town with no worship. Happiness is -10 from unemployment
- Build a Blacksmith. Happiness will be 0 (+10 blacksmith, -10 unemployment)
- Spend 1 tick. Unemployment is gone, but happiness is unchanged.
- Happiness remains at 0 until a building is built or game is refreshed

### Expected behaviour

Happiness should update when Available Workers changes.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

4598

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Township has now been reworked as of v1.1.2
