### ISSUE TITLE
Bird Nest item notification icon missing

### ISSUE THREAD

**Issue by NotArcanus** [MelvorIdle/melvoridle.github.io#28]
The icon for bird nest is missing during item notifications with the console error `assets/media/bank/misc/bird_nest.svg:1 Failed to load resource: the server responded with a status of 404 ()`
Even with item notifications turned off it still tries to show the missing picture and fails.

**Comment by mrDLSable** [comment]
I think this is related to the website being down.

**Comment by NotArcanus** [comment]
Don't think so, as it was happening before it went down (I refreshed after finding this bug and loaded fine) and the window still open shows all the other icons just fine.

**Comment by mrDLSable** [comment]
your browser might have loaded a cashed version of the game

**Comment by NotArcanus** [comment]
You are probably right about that I guess

**Comment by mrDLSable** [comment]
Could you check to see if it still happens @NotArcanus ?

**Comment by NotArcanus** [comment]
It still does but with a slightly different console error that means the same thing
`GET https://melvoridle.com/assets/media/bank/misc/bird_nest.svg 404`

**Comment by mrDLSable** [comment]
Indeed. It looks like the graphic is just not present on the server or not at the right address.

**Comment by MelvorIdle** [comment]
Hotfixed.
A force refresh will fix it on your end.
