### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by MathieuCHEDOZEAU** [MelvorIdle/melvoridle.github.io#2804]
### Describe the bug

Bonjour,

J'ai de gros lags sur le jeux quasiment tout le temps. Comment puis-je résoudre le problème? En sachant que j'ai déjà vidé le cache et désinstallé/réinstallé le jeu.
Merci.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4615

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
I am unable to reproduce this bug. If the issue persists, please submit a new report.
