### ISSUE TITLE
[Spelling/Grammar]: Meteorite Spellcaster Ring Description

### ISSUE THREAD

**Issue by Falterfire** [MelvorIdle/melvoridle.github.io#2805]
### What text is wrong?

Description is "Reduces the Infernal Rune cost of Magic Spells by 6 when equipped in the Shield slot."

### What is the correct spelling or grammar?

Given that it's a ring, I _assume_ it's meant to say "when equipped in the Ring slot"

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.1.2
