### ISSUE TITLE
[Bug]: Cloud Save Failed

### ISSUE THREAD

**Issue by arnfiix** [MelvorIdle/melvoridle.github.io#2807]
### Describe the bug

I am repeatedly getting errors relating to the Cloud Save function failing.

![image](https://user-images.githubusercontent.com/2829194/197867121-ee34a702-b7d1-48c8-8186-94a9690a9d3b.png)

I'm not sure if this is correct though, as the game shows the Melvor Cloud as being online, but doesn't show me being logged into my account., and when I try and save the "last cloud save" counter resets. But it doesn't show me as being logged into a cloud account.

![image](https://user-images.githubusercontent.com/2829194/197868503-1dec3f07-dd14-4c3b-ba06-27199c5d79e7.png)

Logging out and logging in doesn't seem to change this behaviour.

This is occuring on both Steam and Chrome, using the same account.

### Expected behaviour

I would expect that logging in would correctly connect me to the Melvor Cloud and stop the popups.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4615

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
I am unable to reproduce this bug. If the issue persists, please submit a new report.
