### ISSUE TITLE
[Bug]: runecrafting mod

### ISSUE THREAD

**Issue by Karlos764** [MelvorIdle/melvoridle.github.io#2808]
### Describe the bug

While running runecrafting mod and you close the game it does not follow to next rune when mac craft is hit or mine rune essence when you run out

### Expected behaviour

Should move to next rune or mine essence when max cast is fulfilled

### Save Link

https://melvoridle.com/save/FR7vVZOj

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4165

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
We are not responsible for bugs that are the result of mods. Please report these to the appropriate mod authors. It is also recommended to keep a backup of your save files when using mods in the event that one causes save corruption.
