### ISSUE TITLE
[Bug]: Potato seeds in herb plots after disconnection from Throne of the Herald

### ISSUE THREAD

**Issue by zankplus** [MelvorIdle/melvoridle.github.io#2809]
### Describe the bug

I was briefly disconnected from Throne of the Herald for some reason earlier today (I noted I couldn't connect to Steam at that moment either), so when I signed into Melvor I saw the DLC content was disabled, and my Chilli Seeds and Snowcress Seeds were unplanted, and my default selections for each plot reset to non-DLC seeds. Fair enough. I was able to reconnect shortly thereafter. But I noticed that while the first 11 herb plots were reset to Garum Seeds, the last 3 were set to Potato Seeds, and I could in fact plant Potato Seeds in that plot using the "Plant All Selected Crops" option, and now I have Potato Seeds growing between two plots of Snowcress. Seems harmless enough from my end, but I thought you'd still want to know. Thanks!

### Screenshots

![chrome_2022-10-25_17-25-56](https://user-images.githubusercontent.com/12615965/197906993-28116d17-84c8-42ee-801d-899565d5e01c.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4615

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was fixed as of V1.1.2
