### ISSUE TITLE
[Bug]: Meteorite Ore HP Dissapeared

### ISSUE THREAD

**Issue by bearinhouse** [MelvorIdle/melvoridle.github.io#2811]
### Describe the bug

All my meteorite HP disappeared. I had about 40k HP, but now it reads 0.  My game lost the expansion briefly on mobile and I logged in, so maybe that's when this happened? I majorly play on mobile but I checked on desktop as well and the meteorite HP is still gone.  I tried getting more meteorites and seeing if that brought back the HP but the new ones just functioned like normal and I mined them until they were gone.

### Save Link

https://melvoridle.com/save/lbzBdmzt

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4628

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was fixed with v1.1.1 (?5023). It should no longer be possible to load saves when the game fails to load in data for the full version or expansions due to networking (or other) errors.
