### ISSUE TITLE
after installing the mod unlimited offline no more offline masrty

### ISSUE THREAD

**Issue by TimonBiu** [MelvorIdle/melvoridle.github.io#2812]
### Describe the bug

i have been unable to get any offline mastery xp after getting the mod on the mod manager it doesnt work on any of my accounts 
doesnt work on any of them
https://melvoridle.com/save/MsQ1eKq1
https://melvoridle.com/save/9ovHpq2s
https://melvoridle.com/save/lKslRa8p

### Save Link

https://melvoridle.com/save/MsQ1eKq1

### Console output

style.css:1          Failed to load resource: the server responded with a status of 404 ()
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
index_game.php:1 Uncaught (in promise) Object
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
AgilityCourse.js:266 AgilityCourse is waiting for the MICSR object
Card.js:616 Card is waiting for the MICSR object
CombatData.js:185 CombatData is waiting for the MICSR object
Consumables.js:408 Consumables is waiting for the MICSR object
DataExport.js:197 DataExport is waiting for the MICSR object
ExportCheat.js:203 Import is waiting for the MICSR object
Import.js:487 Import is waiting for the MICSR object
Loot.js:596 Loot is waiting for the MICSR object
Plotter.js:556 Plotter is waiting for the MICSR object
Menu.js:179 Menu is waiting for the MICSR object
Simulator.js:1184 Simulator is waiting for the MICSR object
SimEnemy.js:86 SimEnemy is waiting for the MICSR object
SimManager.js:341 SimManager is waiting for the MICSR object
App.js:3029 App is waiting for the MICSR object
SimPlayer.js:818 SimPlayer is waiting for the MICSR object
TabCard.js:142 TabCard is waiting for the MICSR object
main.js:110 main is waiting for the MICSR object
cloudManager.js?4628:196 Silent Sign in with JWT
cloudManager.js?4628:196 Validating Melvor Cloud token
cloudManager.js?4628:196 Storing Melvor Cloud Token
cloudManager.js?4628:196 Initializing PlayFab login. Method: customID
cloudManager.js?4628:196 Logging in with Custom ID via PlayFab
cloudManager.js?4628:196 Login with custom ID success
cloudManager.js?4628:196 Getting account info
cloudManager.js?4628:196 Account info retrieved
cloudManager.js?4628:196 Authenticated w/ Melvor Cloud: true
cloudManager.js?4628:196 Authenticated w/ PlayFab: true
cloudManager.js?4628:196 Checking for valid full version
cloudManager.js?4628:196 Checking for valid TotH purchase
cloudManager.js?4628:196 Loading Game Data...
save.js?4628:111 Registered Demo Data.
save.js?4628:111 Registered Full Version Data.
cloudManager.js?4628:196 Initializing Mod Manager...
cloud.js?4628:147 PlayFab Data Stored successfully.
cloudManager.js?4628:196 Checking for Mod Updates...
cloudManager.js?4628:196 Loading Mods...
cloudManager.js?4628:196 Loading Mods (1/15): SEMI Core (v1.7.1)
cloudManager.js?4628:196 Loading Mods (2/15): Standard Speedrun (v0.1.0)
cloudManager.js?4628:196 Loading Mods (3/15): SEMI Drop Chances (v1.3.1)
cloudManager.js?4628:196 Loading Mods (4/15): SEMI Auto Farming (v0.2.1)
cloudManager.js?4628:196 Loading Mods (5/15): Township Breakdown (v0.0.4)
cloudManager.js?4628:196 Loading Mods (6/15): Mastery Pool Can Overflow (v1.2.0)
cloudManager.js?4628:196 Loading Mods (7/15): Bank Tab Values (v1.1.0.4395)
cloudManager.js?4628:196 Loading Mods (8/15): SEMI Auto Run (v1.3.0)
cloudManager.js?4628:196 Loading Mods (9/15): SEMI Auto Runecrafting (v1.0.4)
cloudManager.js?4628:196 Loading Mods (10/15): SEMI Auto Bury (v0.0.4)
cloudManager.js?4628:196 Loading Mods (11/15): XP in Sidebar (v1.1)
cloudManager.js?4628:196 Loading Mods (12/15): SEMI Save on Close (v1.1.0)
cloudManager.js?4628:196 Loading Mods (13/15): SEMI Auto Master (v1.6.1)
cloudManager.js?4628:196 Loading Mods (14/15): Shop Item Owned Indicator (v1.0.0)
cloudManager.js?4628:196 Loading Mods (15/15): Unlimited Offline (v0.1.3)
cloudManager.js?4628:196 Loading Local Saves...
cloudManager.js?4628:196 Loading Cloud Saves...
cloudManager.js?4628:196 Getting saves from playfab
cloudManager.js?4628:196 Saves retrieved
characterSelect.js?4628:5 Loading character selection
cloudManager.js?4628:291 Connected to PlayFab successfully
index.html:1 Uncaught (in promise) Object
v1.1ReleaseNotes.html:1 Uncaught (in promise) Object
index_game.php:1 Uncaught (in promise) Object
index_game.php:1 Uncaught (in promise) Object
index_game.php:1 Uncaught (in promise) Object
v1.1ReleaseNotes.html:1 Uncaught (in promise) Object
index.html:1 Uncaught (in promise) Object
index.html:1 Uncaught (in promise) Object
index_game.php:1 Uncaught (in promise) Object
index_game.php:1 Uncaught (in promise) Object
index_game.php:1 Uncaught (in promise) Object
save.js?4628:39 Copied to clipboard successfully.
index_game.php:1 Uncaught (in promise) Object
index_game.php:1 Uncaught (in promise) Object
index_game.php:1 Uncaught (in promise) Object
index_game.php:1 Uncaught (in promise) Object
4save.js?4628:39 Copied to clipboard successfully.
main.js?4628:15 Game Loaded
mod.js?4628:734 [SEMI Auto Master] Possible mod conflict - Skill.addXP has already been patched by the following mods: "XP in Sidebar"
patch @ mod.js?4628:734
main.js:99 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (main.js:99:35)
    at main.js:124:30
util.js:251 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (util.js:251:35)
    at util.js:276:30
modifierNames.js:931 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (modifierNames.js:931:35)
    at modifierNames.js:956:30
AgilityCourse.js:255 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (AgilityCourse.js:255:35)
    at AgilityCourse.js:280:30
Card.js:605 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Card.js:605:35)
    at Card.js:630:30
CombatData.js:174 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (CombatData.js:174:35)
    at CombatData.js:199:30
Consumables.js:397 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Consumables.js:397:35)
    at Consumables.js:422:30
DataExport.js:186 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (DataExport.js:186:35)
    at DataExport.js:211:30
ExportCheat.js:192 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (ExportCheat.js:192:35)
    at ExportCheat.js:217:30
Import.js:476 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Import.js:476:35)
    at Import.js:501:30
Loot.js:585 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Loot.js:585:35)
    at Loot.js:610:30
Plotter.js:545 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Plotter.js:545:35)
    at Plotter.js:570:30
Menu.js:168 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Menu.js:168:35)
    at Menu.js:193:30
Simulator.js:1173 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Simulator.js:1173:35)
    at Simulator.js:1198:30
SimEnemy.js:75 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (SimEnemy.js:75:35)
    at SimEnemy.js:100:30
SimManager.js:330 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (SimManager.js:330:35)
    at SimManager.js:355:30
App.js:3018 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (App.js:3018:35)
    at App.js:3043:30
SimPlayer.js:807 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (SimPlayer.js:807:35)
    at SimPlayer.js:832:30
TabCard.js:131 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (TabCard.js:131:35)
    at TabCard.js:156:30
game.js?4628:165 Took 4.8925s to process 3635972 ticks. 0.0013455824192265507ms per tick.
index_game.php:1 Uncaught (in promise) Object
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
index_game.php:1 Uncaught (in promise) {message: 'A listener indicated an asynchronous response by r…age channel closed before a response was received'}
index_game.php:1 Uncaught (in promise) {message: 'A listener indicated an asynchronous response by r…age channel closed before a response was received'}
index_game.php:1 Uncaught (in promise) {message: 'A listener indicated an asynchronous response by r…age channel closed before a response was received'}
index_game.php:1 Uncaught (in promise) {message: 'A listener indicated an asynchronous response by r…age channel closed before a response was received'}
index_game.php:1 Uncaught (in promise) {message: 'A listener indicated an asynchronous response by r…age channel closed before a response was received'}
index_game.php:1 Uncaught (in promise) {message: 'A listener indicated an asynchronous response by r…age channel closed before a response was received'}
index_game.php:1 Uncaught (in promise) {message: 'A listener indicated an asynchronous response by r…age channel closed before a response was received'}
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
index_game.php:1 Uncaught (in promise) {message: 'A listener indicated an asynchronous response by r…age channel closed before a response was received'}
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
style.css:1          Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://melvoridle.com/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
cloud.js?4628:29 Synchronising with Cloud

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4628

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
We are not responsible for bugs that are the result of mods. Please report these to the appropriate mod authors. It is also recommended to keep a backup of your save files when using mods in the event that one causes save corruption.

On a side note, you are still running an old extension/script that is not compatible with version v1.1 of the game, I recommend uninstalling these as they may cause unintended behaviour.
