### ISSUE TITLE
I purchased biome space and it says not enough biome space[Bug]: <title>

### ISSUE THREAD

**Issue by 10tygee** [MelvorIdle/melvoridle.github.io#2814]
### Describe the bug

When I go to purchase a building it says no available biome space and I bought some

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4615

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Township has now been reworked as of v1.1.2
