### ISSUE TITLE
[Feature]: Rearrangement of Ui

### ISSUE THREAD

**Issue by nellydocs** [MelvorIdle/melvoridle.github.io#2815]
### Describe the bug

Not a bug but a feature request.

I have melvor on my Vertical Monitor. 1080p 16:9
It seems that the Ui is not really made for this aspect.

A quick fix and overall nicer look and feel can be achived by 
Changing the Ui Grid to col-md-12 on positions

"/html/body/div[3]/main/div[3]/div[6]/div[1]/div/div/div[2]"
and
/html/body/div[3]/main/div[3]/div[6]/div[1]/div/div/div[3]
see Screenshots

Thanks Nellydocs

### Screenshots

![image](https://user-images.githubusercontent.com/71311423/198038837-985c96bb-eac4-4f99-9994-679d396750d1.png)
![image](https://user-images.githubusercontent.com/71311423/198038936-faa453d0-1603-4cbd-af83-d147acb5e08f.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4628

### Are you using any mods?

No

**Comment by coolrox95** [comment]
This issue tracker is for bug reports only, not for feedback or suggestions.
