### ISSUE TITLE
[Bug]: My FEZ amulet gone, like it never exist

### ISSUE THREAD

**Issue by iliveor** [MelvorIdle/melvoridle.github.io#2816]
### Describe the bug

I definitely remember that I had one. For example, I have found 13 amulets of torture. There are 3 in the bank. Sold - none.

### Save Link

https://melvoridle.com/save/yLxeOAv1

### Screenshots

<img width="733" alt="Снимок экрана 2022-10-26 в 17 05 58" src="https://user-images.githubusercontent.com/35229749/198048834-9dc2bb4b-0524-4134-90a3-d0f3ffe675c5.png">
<img width="284" alt="Снимок экрана 2022-10-26 в 17 06 29" src="https://user-images.githubusercontent.com/35229749/198048881-421e2a0b-a453-445b-b93f-a2f0b2c4efc7.png">
<img width="410" alt="Снимок экрана 2022-10-26 в 17 06 45" src="https://user-images.githubusercontent.com/35229749/198048901-fe34c972-b2f9-4541-b396-58ea81593f77.png">

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4628

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
I am unable to reproduce this bug. If the issue persists, please submit a new report.
