### ISSUE TITLE
Game wont launch at all steam

### ISSUE THREAD

**Issue by mugguffen** [MelvorIdle/melvoridle.github.io#2817]
### Describe the bug

When launching the game through steam it will prompt me to log in on a white background, but when logging in I get a screen with nothing but a message in the corner that's stuck on "loading language data" even though I'm playing in english

### Screenshots

![part5](https://user-images.githubusercontent.com/12554671/198083449-14b9c7e5-a675-47e1-a3ac-eb78d244be53.PNG)
![Ivbeenstuckonthis](https://user-images.githubusercontent.com/12554671/198083459-1a3a5ba1-98c7-4097-9a4d-a9b40f0f60ab.PNG)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4628

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
I am unable to reproduce this bug. If the issue persists, please submit a new report.
