### ISSUE TITLE
[Bug]: Golbin Raid will show dungeon/slayer area dropdowns if opened when paused.

### ISSUE THREAD

**Issue by rosieneko** [MelvorIdle/melvoridle.github.io#2818]
### Describe the bug

If you open up the dungeon/combat areas while a golbin raid is paused, it will still show that list when you restart the golbin raid.

### Reproduction Steps

1. Start Golbin Raid.
2. Pause Golbin Raid.
3. Go to Combat, click on "Browse Dungeons" to open up dungeon area drop down.
4. Go back to Golbin Raid and "Continue Golbin Raid". Now you see the dungeon dropdown but no way to remove it.

### Expected behaviour

I expect that golbin raid doesn't display content that it doesn't have access to, e.g., dungeons.

### Screenshots

![image](https://user-images.githubusercontent.com/1606128/198101581-85664bd8-05d3-45b4-868b-026fd4815ed7.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4628

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue was fixed as of V1.1.2
