### ISSUE TITLE
[Bug]: Golbin Raid time in raid seems to be a bit off

### ISSUE THREAD

**Issue by rosieneko** [MelvorIdle/melvoridle.github.io#2821]
### Describe the bug

I just recently finished a raid I had started yesterday. My system clock has not changed, but the game said I was in the raid for 52 years. I assume this is inaccurate as it should be measuring how long we spent actively trying to raid.

### Screenshots

![image](https://user-images.githubusercontent.com/1606128/198144435-fb832ba1-5201-4c5a-988a-686805b6342f.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4628

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue was fixed as of V1.1.2
