### ISSUE TITLE
[Bug]: unable to downgrade potions

### ISSUE THREAD

**Issue by cryptocurly1** [MelvorIdle/melvoridle.github.io#2822]
### Describe the bug

As far as I see, there is currently no way to downgrade potions. This makes 100% completion impossible as well as the easy potion township task. 

### Reproduction Steps

1. Upgrade bird nest potion to a level > 1 using mastery points
2. Try to complete the township task that requires level 1 bird nest potions. 

### Expected behaviour

Opening the details tab for any given potion at level > 1 should allow you to downgrade to the next lower level ( or maybe pick a level? 🤔 )

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4628

### Are you using any mods?

No

**Comment by ekuland** [comment]
Not a bug. "Herblore Potion" allows you to gain an extra, random tier of the potion you're making

**Comment by cryptocurly1** [comment]
Ok! Thanks 🙏
