### ISSUE TITLE
[Bug]: Traps Potion Same Description And Charge Despite Different Tier

### ISSUE THREAD

**Issue by Chvtky** [MelvorIdle/melvoridle.github.io#2823]
### Describe the bug

Despite upgrading the Traps Potion from 1 to 3, the description and charges of the potion remains the exact same; +50% GP from Agility Obstacles that contain a negative modifier, +5% Agility Skill XP from Obstacles that contain a negative modifier, and +5% Agility Mastery XP from Obstacles that contain a negative modifier.

### Reproduction Steps

Just upgrade the Traps Potion 

### Save Link

https://melvoridle.com/save/lfSfGF1D

### Screenshots

![534](https://user-images.githubusercontent.com/116771052/198161034-195806ef-6a71-4148-a97c-9fa6abbba571.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4628

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was fixed.
