### ISSUE TITLE
[Bug]: Cloud Save continually errors out after 24h of game being open

### ISSUE THREAD

**Issue by benanderson1** [MelvorIdle/melvoridle.github.io#2824]
### Describe the bug

After playing Melvor in a browser for 24 hours, cloud save starts to error out.

The only cause seems to be that the game has been open for 24 hours. I've seen it happen daily now, always around 22:10 for me now.

Before the expansion update, I could leave the game running for days and weeks without having any issues. After the expansion, for some reason I can no longer save to my cloud account after 24h.

Manually reloading the game fixes cloud save errors. So the workaround is to refresh the game manually every single day.

### Reproduction Steps

1. Login to browser with cloud account
2. Leave game open 24h
3. After 24h, you start getting Cloud Save Failed popups each time the timer tries to save in the cloud.

### Expected behaviour

I expect to leave the game open as long as I wish and continue to be able to save to my cloud account without issue, just like before the expansion update.

### Screenshots

![cloudsavefailed](https://user-images.githubusercontent.com/20519698/198175202-6bc2a3b4-b25f-4345-8c2d-f849be3d33e6.png)

### Console output

I've already reloaded my game today, I can do this again tomorrow when it happens and update the ticket with console output.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4628

### Are you using any mods?

Yes

**Comment by benanderson1** [comment]
I've been told Malcs has confirmed this is a bug and will be addressed:
https://discord.com/channels/625838709203271680/625838709744599088/1032533163433545779

Feel free to close this issue if you guys are already on top of it. I searched for "Cloud Save" and didn't find any issue so I made a new one.

**Comment by MelvorIdle** [comment]
This has now been fixed as of v1.1.1.
