### ISSUE TITLE
[Bug]: Seeds in expansion slots not growing

### ISSUE THREAD

**Issue by zenta0027** [MelvorIdle/melvoridle.github.io#2826]
### Describe the bug

There is no time left in allotments, but "Harvest" button is not activate.

### Reproduction Steps

Bying additional slots -> Use "Plant All Selected Crops" function

### Save Link

https://melvoridle.com/save/0IIjr38Q

### Screenshots

![image](https://user-images.githubusercontent.com/17705603/198185262-cebd9de9-1c44-445b-b83c-f2c111aec39d.png)
![image](https://user-images.githubusercontent.com/17705603/198455926-0e59ae22-1b24-46e7-b045-3247a5e30ba7.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4631

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
I am unable to reproduce this bug. If the issue persists, please submit a new report.
