### ISSUE TITLE
[Bug]: Lose crafted item if bank is temporarily full before craft 

### ISSUE THREAD

**Issue by adamk33n3r** [MelvorIdle/melvoridle.github.io#2827]
### Describe the bug

Any time you craft an item with a full bank it just voids the item. Even if the items you're using to craft would create free space for the product. I've encountered this multiple times when trying to create summoning tablets for the first time. I buy the shards for 1 craft operation. My bank is full. But after creating the tablets I should have room for them....but they're still voided. 

### Reproduction Steps

1. Have 6 red summoning shards
2. Have 50 bronze daggers
3. Have a full bank
4. Create goblin theif tablets
5. See that you have 2 free bank spaces and the tablets lost to the void

### Expected behaviour

You have 1 free bank space with 25 goblin theif tablets 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4628

### Are you using any mods?

Yes

**Comment by adamk33n3r** [comment]
I believe that's a setting you can turn on to have it stop crafting when bank is full. But it still crafts it once.

**Comment by richardcocks** [comment]
@adamk33n3r That is a setting but this craft appears to ignore that setting too.

**Comment by aquelle-cp** [comment]
This is a problem I've been having too, I just tried to make my air battlestaff and forgot that my bank was full, it took my maple log and all my air staves and didn't make the battlestaff. I've had the issue a few times, but that was the most noticeable since that log took me a while to steal since I don't have the wc level haha

**Comment by darkwebdev** [comment]
I've just had this problem for the thrid time already, will it ever be addressed?

**Comment by gbakkk5951** [comment]
I encountered this problem as well, wish the developers could see this issue and fix it.
