### ISSUE TITLE
[Bug]: iOS loads as Demo; Browser and Android load full game

### ISSUE THREAD

**Issue by velcrobp** [MelvorIdle/melvoridle.github.io#2828]
### Describe the bug

iOS game is still loaded as DEMO. The browser (Vivaldi) and Android versions are loading the full game properly. However, after loading on iOS, my cloud save on all platforms loses all my equipment sets and quick-load settings, and also all citizens in my township are unassigned.

Malcs fixed my Android client on launch dia via the Discord #purchase-issues channel.

### Reproduction Steps

Launch iOS version of game
Load save

### Expected behaviour

iOS should load the full game and the save should match my Android and browser.

### Save Link

https://melvoridle.com/save/iRvLRcYa

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4628

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Is this still occurring if you follow these steps:

1) Log in to Android or Steam with your Cloud account
2) Wait 5 seconds
3) Load into same cloud account on iOS

**Comment by velcrobp** [comment]
I’m afraid to try. Last time I logged in on iOS it cloud saved as demo, which borked a lot of stuff in my game. From: Melvor IdleSent: Thursday, October 27, 2022 21:10To: MelvorIdle/melvoridle.github.ioCc: velcrobp; AuthorSubject: Re: [MelvorIdle/melvoridle.github.io] [Bug]: iOS loads as Demo; Browser and Android load full game (Issue #2828) Is this still occurring if you follow these steps:Log in to Android or Steam with your Cloud accountWait 5 secondsLoad into same cloud account on iOS—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by velcrobp** [comment]
Has a fix been applied?

**Comment by MelvorIdle** [comment]
I need more information or for you to follow the above steps provided.

**Comment by velcrobp** [comment]
I tried to follow the steps, but both iOS and the secondary browser (Chrome) warn that the game is still Demo Only version.

![iOS error](https://user-images.githubusercontent.com/8411229/200381645-e2159564-dfe5-4deb-8e4e-12977bf1f6e3.PNG)
![chrome error](https://user-images.githubusercontent.com/8411229/200381651-3970979b-1740-4483-8cf9-9e7195278735.png)
