### ISSUE TITLE
Cooking and burning food in offline mode doesn't get added to statistics

### ISSUE THREAD

**Issue by RonaldKooij** [MelvorIdle/melvoridle.github.io#283]
![image](https://user-images.githubusercontent.com/7534450/84500057-1256f180-acb4-11ea-81b3-58d83109dc00.png)

![image](https://user-images.githubusercontent.com/7534450/84500110-31558380-acb4-11ea-9dc8-63f0629bc864.png)

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
