### ISSUE TITLE
Cooking Bug

### ISSUE THREAD

**Issue by Dcappitize** [MelvorIdle/melvoridle.github.io#2830]
### Describe the bug

When trying to cook lobster I noticed Lobster will decrease from my inventory and it will successfully cook it however, the cooked lobster number is not increasing in my bank.

### Expected behaviour

I expected to gain more lobster.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4628

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
You have the auto equip cooked food setting enabled.
