### ISSUE TITLE
[Bug]: Area Control Potion description & effect mismatch

### ISSUE THREAD

**Issue by Falterfire** [MelvorIdle/melvoridle.github.io#2831]
### Describe the bug

The description for all four tiers of the Area Control potion lists the wrong amount of Area Effect negation
Tier I description says +10% VS actual effect of +20%
Tier II description says +15% VS actual effect of +30%
Tier III description says +25% VS actual effect of +40%
Tier IV description says +35% VS actual effect of +50%

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

4628

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.1 (?4673).
