### ISSUE TITLE
[Bug]: Superior Astrology Skillcape is not present in the astrology skill's quick equip menu

### ISSUE THREAD

**Issue by Mohnket** [MelvorIdle/melvoridle.github.io#2834]
### Describe the bug

There's a "Quick Equip" menu in the bottom right of the window that usually has the skillscapes & various other equipments available to equip without going back to the bank interface. The "Superior Astrology Skillscape" is not an option in this menu even after it is unlocked.

"Superior Astrology Skillcape" equipped but not in the "Quick Equip" menu (proving that I do have the skill cape unlocked):
![Screenshot_20221027_201445](https://user-images.githubusercontent.com/22918463/198420695-d2a72f38-c753-4975-82e9-3e978d55f014.png)

"Maxumum Skillcape" equipped and is correctly shown as equipped in the "Quick Equip" menu:
![Screenshot_20221027_201637](https://user-images.githubusercontent.com/22918463/198420846-ed1f74dc-95d1-41e9-95f0-164fb8ceab48.png)

### Reproduction Steps

0. Grind to level 120 in astrology and purchase the "Superior Astrology Skillcape"
1. Go to the astrology skill's page
2. Hover over the "Quick Equip" thingy
3. the "Superior Astrology Skillcape" is not present in available items in the "Quick Equip" menu

I am using the steam client & am using Manjaro version 22.0.0 on linux kernel version 5.19.7-1. And if any of those facts matter I will be mad.

### Expected behaviour

The "Superior Astrology Skillcape" can be equiped from the skill's "Quick Equip" menu once unlocked

### Save Link

https://melvoridle.com/save/3pfMYHti

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4628

### Are you using any mods?

No

**Comment by ekuland** [comment]
No expansion items are in the quick equip menus.
Add them yourself from the bank
Bank > Item > Cog > Check the skills you want it in.

**Comment by Mohnket** [comment]
That does work. 

What is the justification for the expansion items to not have that enabled by default for the skills they are relevant in?
