### ISSUE TITLE
[Spelling/Grammar]: Ty (pet) listed as Woodcutting

### ISSUE THREAD

**Issue by JosephGeibig** [MelvorIdle/melvoridle.github.io#2835]
### What text is wrong?

Ty, the mastery pet, is listed as coming from woodcutting. 
<img width="187" alt="Screen Shot 2022-10-27 at 9 05 57 PM" src="https://user-images.githubusercontent.com/111135239/198429016-d47e7d06-bdec-4ab9-9684-19beef6da41c.png">

### What is the correct spelling or grammar?

Mastery

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.1 (?4673).
