### ISSUE TITLE
[Bug]: Astrology pet modifier on finding gold stardust

### ISSUE THREAD

**Issue by Masquerade-D** [MelvorIdle/melvoridle.github.io#2836]
### Describe the bug

After the update, the astrology system changed. For this, your game designer increased the basic probability of obtaining Stardust and Golden Stardust to 5% and 2% respectively, but I think the chance of obtaining golden stardust provided by astrological pets may be neglected and it is still a +0.1% chance to get golden stardust right now.

### Expected behaviour

Maybe the probability should be raised to 1%.

### Screenshots

![Uploading 1.png…]()

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4631

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was fixed.
