### ISSUE TITLE
[Bug]: Price for hardcore bank slots keeps increasing past the cap

### ISSUE THREAD

**Issue by ikhebgeenaccount** [MelvorIdle/melvoridle.github.io#2837]
### Describe the bug

When buying bank slots on a hardcore account, one cannot buy more once 100 bank slots has been reached. Previously, when attempting to buy more than this cap, the price and count would cap out and increasing the number YY in 'Buy xYY' served no purpose for the purchasing of bank slots. Currently, while the number does not increase with an increase in YY, the cost does still increase.

I do currently have 4 bank slots from the Astrology constellation Rosaniya.

### Reproduction Steps

On hardcore account:
1. Increase buy amount past the cap of 100 bank slots

### Expected behaviour

Price should cap together with the number of slots, but does not: price keeps increasing with buy amount while amount purchased stays capped.

### Save Link

https://melvoridle.com/save/tuQA46WS

### Screenshots

Maximum bank slots I can buy before hitting the cap:
![image](https://user-images.githubusercontent.com/9048740/198529682-2346bd39-cd66-4eeb-a372-801887000466.png)

Price keeps increasing post cap:
![image](https://user-images.githubusercontent.com/9048740/198529906-c589df8b-137e-460d-bc17-4c1d66c8006c.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?44631

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.1 (?4673).
