### ISSUE TITLE
[Bug]: Missing theiving quick-equip items

### ISSUE THREAD

**Issue by angelinonick** [MelvorIdle/melvoridle.github.io#2838]
### Describe the bug

Quick equip for thieving does not show the new thieving skilling items such as "thieving shorts" and "grappling hook".

### Reproduction Steps

No steps needed to reproduce. 

### Expected behaviour

Quick-equip should show ALL equipment relevant to the skill.

### Screenshots

![image](https://user-images.githubusercontent.com/36925413/198545018-20ae5e44-47a6-449a-a921-6a698f1729f8.png)
![image](https://user-images.githubusercontent.com/36925413/198545046-e80cd794-cd61-4f77-8edc-a39dec07b228.png)
![image](https://user-images.githubusercontent.com/36925413/198545076-ff1ed46f-95ec-4c30-b19e-191dd984e714.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

4631 

### Are you using any mods?

No

**Comment by Chvtky** [comment]
Seemingly, expansion items are not automatically listed. You'll need to manually set them by going to bank > said item (say, Thieving Shorts) > Item Settings > Minibar Settings. Tick the thieving icon if you want your item to appear in that skill for quick equip. Do it for all other thieving related items that came with this expansion, and you're good to go.

**Comment by l3vines** [comment]
> Seemingly, expansion items are not automatically listed. You'll need to manually set them by going to bank > said item (say, Thieving Shorts) > Item Settings > Minibar Settings. Tick the thieving icon if you want your item to appear in that skill for quick equip. Do it for all other thieving related items that came with this expansion, and you're good to go.

before the expension it was already doing that with some items. so its nothing new.
