### ISSUE TITLE
[Bug]: Impossible to complete Township task

### ISSUE THREAD

**Issue by gilza1639** [MelvorIdle/melvoridle.github.io#2839]
### Describe the bug

When update with township arrived i already was all 99 lvl. So i begin to do tasks and cant do Easy task '1 Burnt Cave Fish' because my cooking chance 100% without potions and equipment

I use SEMI mod to auto eating, but i guess its not the problem

### Reproduction Steps

1. Go all 99lvl skills
2. Maybe some pets
3. Try to bunr cave fish

### Expected behaviour

Burn fish somehow

### Save Link

https://melvoridle.com/save/YyBQyzC6

### Screenshots

![Screenshot_15](https://user-images.githubusercontent.com/58261234/198572391-c69652bf-08e1-4926-b942-7432959f5830.png)
![Screenshot_16](https://user-images.githubusercontent.com/58261234/198572405-75aa04ff-b3ec-4fc0-a37b-0bf81914447f.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4631

### Are you using any mods?

Yes

**Comment by Chvtky** [comment]
Kill Tentacles for them.
