### ISSUE TITLE
[Bug]: Local or cloud save refresh button doesn't work

### ISSUE THREAD

**Issue by Carpentia** [MelvorIdle/melvoridle.github.io#2841]
### Describe the bug

Having the game open on the select your character screen lets you choose between local or cloud save. When I have this open on PC and save the game on mobile the refresh button doesn't update cloud saves. This used to work correctly before the expansion. The issue also applies on android when saving the game on PC after opening the game on mobile. Closing the game client and restarting correctly loads recent cloud files.
Bug applies to multiple characters, so it shouldn't be save file bound.

### Reproduction Steps

1. Open game on mobile, select a character and perform actions.
2. Open game on computer till character selection screen.
3. Force cloud save on mobile.
4. Use reload/refresh button on computer to reload cloud saves.
5. Cloud save is not the most recent (from mobile)

### Expected behaviour

The most up to date cloud save files for all characters should be displayed. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4631

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.1 (?4673).
