### ISSUE TITLE
[Bug]: IOS reset to demo. Researt app fixed but lost all township tasks

### ISSUE THREAD

**Issue by McKristoph** [MelvorIdle/melvoridle.github.io#2842]
### Describe the bug

When I opened the app I didn't notice it said "demo version" when going into my main save. Upon opening, it took off all my gear and reset all my quick equips for skills. Force closed the app and restarted a few times until both expansion and full game were checked. Opening account and going to the township showed all my task progress went to 0. 
Second look, also removed all workers and religion from town

### Reproduction Steps

unknown. I think it has something to do with slow connection/bad (cellular)service.

### Save Link

https://melvoridle.com/save/rpdVeOom

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

4631

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue was fixed with v1.1.1 (?5023). It should no longer be possible to load saves when the game fails to load in data for the full version or expansions due to networking (or other) errors.
