### ISSUE TITLE
[Bug]: Eyes Slayer Task did not allow progress

### ISSUE THREAD

**Issue by Valanze** [MelvorIdle/melvoridle.github.io#2843]
### Describe the bug

Today 10/28/2022 and time ranging roughly between 8AM PST and 11:30AM PST I was performing the slayer task eyes. I forgot this task was going and died due to lack of food and lost my amulet of looting. I think went to Spider Forest to get a new one. I unequipped my Mirror and equipped my shield. I farmed 20 chest and was able to get the amulet. I think click Jump to Enemy in my slayer task to continue attacking the eyes. After an hour I noticed while it said I was fighting the Eyes and food was being consumed new Eyes were being killed I was making no progress and not receivign any loot, XP, or slayer coins, or task progress. 
Frustrated I clicked Jump to enemy again and was told I don't have a mirror. I equipped it and clicked jump to enemy and now all is fine.

The bug is it should of never consumed materials, let me enter combat since the mirorr is not equipped.

### Reproduction Steps

1. Equip Mirror
2. Get new Eyes Slayer task
3. Die
4. Equip Shield
5. Go to Spider Dungeon
6. Obtain Several Chest
7. Open Chest
8. Click jump to Enemy from step 2
9. Notice it fights but does not provide progress on task or experience/loot

### Expected behaviour

Should not be able to enter fight or have materials consumed if appropriate item is not equipped to enter the area the targer resides in.

### Save Link

https://melvoridle.com/save/v1IjQyLy

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4631

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
I am unable to reproduce this bug. If the issue persists, please submit a new report.
