### ISSUE TITLE
[Bug]: Equipping Cape of Completion (Base Game) Only Increases the Mastery Pool Cap - DOES NOT PROVIDE Pool XP BONUSES

### ISSUE THREAD

**Issue by OVBDavid** [MelvorIdle/melvoridle.github.io#2844]
### Describe the bug

When equipping the Cape of Completion from the base game (yes, with TotH purchased) it only increases the cap of the Mastery XP pool, it does not in fact apply all the Mastery Pool XP checkpoint bonuses.

The cape appears to cause a player to increase their Mastery XP Pool cap by ~2,500,000, but does not make any changes to the Checkpoint % indicator, nor the bonuses that would apply. 

### Reproduction Steps

1. Interact with a Non-Combat skill from the BASE GAME, but have the TotH DLC Purchased and in-effect.
2. Next, make sure you BASE GAME completion >= 100%, equip the MAX SKILLCAPE and take notice of various stats/benefits _(it helps if you don't have all your FM masteries done and your pool XP is not above the 95% checkpoint threshold)_
3. Now, unequip the MAX SKILLCAPE and instead equip the CAPE OF COMPLETION form the BASE GAME.
4. Notice how your Mastery Pool XP Cap should have been raised, but your percentage of pool XP doesn't change, nor does the cape begin to provide you with bonuses from every skill's mastery pool xp checkpoint. 

### Expected behaviour

I expect that when the Cape of Completion is equipped, that all the non-combat mastery pool xp checkpoints are in-effect and working properly. 

### Save Link

https://melvoridle.com/save/rKv1pBDb

### Screenshots

![image](https://user-images.githubusercontent.com/19537993/198713423-0cea2f4f-1450-4cf2-af1a-985d7c4ddda6.png)
![image](https://user-images.githubusercontent.com/19537993/198713426-5c1405dc-d7b0-4614-9616-fc853e741038.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4631

### Are you using any mods?

Yes

**Comment by ekuland** [comment]
The bug is that the text on the cape is unchanged from the new mods.
It no longer activates checkpoints, it does provide 25% extra pool cap.

**Comment by MelvorIdle** [comment]
This has now been fixed as of v1.1.1.
