### ISSUE TITLE
[Bug]: Miners Pit

### ISSUE THREAD

**Issue by JohnnyWoong** [MelvorIdle/melvoridle.github.io#2847]
### Describe the bug

I follow Township Starter Guide try to built Miners Pit on Township, but it always show 'You lack the required resources to maintain buildings in thls Biome.'
How to solve it?

### Screenshots

![image](https://user-images.githubusercontent.com/5661094/198755896-be1ea23c-b3dd-485b-89a9-0df243c999c2.png)
![image](https://user-images.githubusercontent.com/5661094/198757139-0c0aeda8-6da7-46cf-9864-7abc832e4aa1.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4631

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
You need to build the Miners Pit in a different Biome.

**Comment by JohnnyWoong** [comment]
Thanks, now i get it
