### ISSUE TITLE
[Bug]: Issue around checking gear stats when in different gearset

### ISSUE THREAD

**Issue by l3vines** [MelvorIdle/melvoridle.github.io#2849]
### Describe the bug

Somehow its not comparing it the right way. I had the ancient 2hand equiped at that moment so it should be showing red values..
![image](https://user-images.githubusercontent.com/16386078/198793587-b4a2e8d7-3a0f-4066-8f55-b233e59a6e91.png)
![image](https://user-images.githubusercontent.com/16386078/198793715-90e6bb2f-14cd-4bf3-b47c-fd1e1337c61c.png)

### Save Link

https://melvoridle.com/save/0hFrIt4O

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

4631

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue was fixed in v1.1.1 (?4999).
