### ISSUE TITLE
Earth Layered Shield has an Upgrade Item button which does nothing

### ISSUE THREAD

**Issue by henjovr** [MelvorIdle/melvoridle.github.io#285]
**Describe the bug**
The Earth Layered Shield has an Upgrade Item button which does nothing.

**Expected behavior**
No Upgrade Item button OR an indication how to upgrade it.

**Browser**
Firefox

**Console output**
TypeError: items[upgradeItemID] is undefined

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
