### ISSUE TITLE
[Spelling/Grammar]: Superior Woodcutting Skillcape description: recieved->received

### ISSUE THREAD

**Issue by jesbis** [MelvorIdle/melvoridle.github.io#2852]
### What text is wrong?

![image](https://user-images.githubusercontent.com/16565497/198818067-e444c2da-be0f-4aae-ab03-43e09042d9e1.png)

### What is the correct spelling or grammar?

"received" (ei, not ie)

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.1.2
