### ISSUE TITLE
[Spelling/Grammar]: <Bird Nest Potion or Bird Nests Potion>

### ISSUE THREAD

**Issue by mmm0003** [MelvorIdle/melvoridle.github.io#2854]
### What text is wrong?

![Screenshot_20221029-120819](https://user-images.githubusercontent.com/100392705/198844333-bede2fcb-d70b-4eb1-9269-5d7fac982e7f.png)
Potion name is different in Herblore list than when creating potion.

### What is the correct spelling or grammar?

In Herblore Potion list - should say Bird Nest Potion to match other instances of this potion name.

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.1.2
