### ISSUE TITLE
[Bug]: <losing items when equiping other gear>

### ISSUE THREAD

**Issue by cookie140914** [MelvorIdle/melvoridle.github.io#2856]
### Describe the bug

I had notice I was missing a few space saving items but had put it down to maybe not buying secondary pieces of the township gear. However when equipping gear this evening I noticed I had lost my clue chasers insignia and superior woodcutting cape when changing gear to train another skill. 

### Reproduction Steps

This doesn't happened everytime I play but must have happened a few times now to have lost the pieces of township gear I had before. I am not sure on how to replicate this.

### Expected behaviour

I expected my gear to return to my bank however it has been lost.

### Save Link

https://melvoridle.com/save/ufBPgR1D

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4641

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
The items will either be in a different equipment set or somewhere in your bank. Try the bank search to find them.

**Comment by coolrox95** [comment]
Closing as no reproduction steps are available.
