### ISSUE TITLE
[Bug]: <cooking swordfish>

### ISSUE THREAD

**Issue by Butteredt0ast** [MelvorIdle/melvoridle.github.io#2858]
### Describe the bug

I've been cooking swordfish for a while now, I get the notification saying I've got either a perfect or normal swordfish but when I check my bank I'm no longer receiving any but my rate swordfish amount is going down, I have no normal swordfish and am stuck at 16855 perfect swordfish

### Save Link

https://melvoridle.com/save/kkKn0m1v

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4641

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
You have the auto-equip cooked food setting enabled in Cooking.
