### ISSUE TITLE
Max Skillcape does not increase firemaking coal chance to 100%

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#286]
**Describe the bug**
Equipping the Max Skillcape and burning logs does not increase the chance to receive coal to 100%.

**To Reproduce**
1. Equip the Max Skillcape
2. Burn logs in Firemaking
3. Coal is not always received when a log finishes burning

**Expected behavior**
Coal should always be received when a log finishes burning while the Max Skillcape is equipped.

**Fix**
Line 142 of firemaking.js should be adjusted to have an additional check for the Max Skillcape.
```js
if (coalChance > (60 - chance) || equippedItems[CONSTANTS.equipmentSlot.Cape] === CONSTANTS.item.Firemaking_Skillcape)
```

to:

```js
if (coalChance > (60 - chance) || equippedItems[CONSTANTS.equipmentSlot.Cape] === CONSTANTS.item.Firemaking_Skillcape || equippedItems[CONSTANTS.equipmentSlot.Cape] === CONSTANTS.item.Max_Skillcape)
```

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
