### ISSUE TITLE
[Spelling/Grammar]: 95% Thieving Mastery Incorrect Description

### ISSUE THREAD

**Issue by ehxactly** [MelvorIdle/melvoridle.github.io#2860]
### What text is wrong?

The text for the 95% thieving mastery is incorrect - "chance to gain unique area items from Thieving is tripled.". For example, jadestone chances are tripled, however, it is an npc unique. 

### What is the correct spelling or grammar?

"chance to gain unique area and npc items is tripled."

**Comment by ehxactly** [comment]
Seems as though this was an intended nerf. I checked the chances with 95% mastery and below and it did not change.

**Comment by ehxactly** [comment]
Nevermind again, this does seem to be an issue. I checked again and it refreshed after I pickpocketted. IT IS affected by the mastery.

**Comment by coolrox95** [comment]
This bonus has never applied to npc unique drops, and is functioning as intended.
