### ISSUE TITLE
[Bug]: Receiving Clue Chasers Insignia with incorrect amount of items

### ISSUE THREAD

**Issue by Diaroguee** [MelvorIdle/melvoridle.github.io#2861]
### Describe the bug

I should get the amulet using the method known, however I received it without having the full amount of items.

### Reproduction Steps

1. Order your items for the insignia
2. Have it be awarded to you

### Expected behaviour

Normally you would have to have the exact number of items, however in my case I managed to get it with 4 herrings rather than 8

### Screenshots

![image](https://user-images.githubusercontent.com/116374163/198874706-45da728a-0c1a-4035-80d3-0772691aad79.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4641

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This was recently changed. The quantity of items no longer matters.
