### ISSUE TITLE
[Bug]: Explorers map does not get used

### ISSUE THREAD

**Issue by BartDeKrab** [MelvorIdle/melvoridle.github.io#2863]
### Describe the bug

The new explorers map item does not get used when casting ancient magics

### Reproduction Steps

1. Casted incinerate on Umbora when explorers map is equiped

### Expected behaviour

For each cast of incinerate consume 1 map

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4641

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.1 (?4673).
