### ISSUE TITLE
[Bug]: ring of echoes not creating echos in golbin raid

### ISSUE THREAD

**Issue by ItayBM** [MelvorIdle/melvoridle.github.io#2864]
### Describe the bug

For some reason, even though I wear the ring of blade echos in the golbin raid, there's no echos. Instead I have the brute force special attack in 20% of attacks, even though I have a melee sword . Not sure if the two bugs are connected 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

4641

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
You selected an "ALT" variation of the ring which gives the item a random special attack.
