### ISSUE TITLE
[Bug]: Stucking on the "Fetching account Info"

### ISSUE THREAD

**Issue by Huanswurst** [MelvorIdle/melvoridle.github.io#2866]
### Describe the bug

After the latest update,i cant login the game with the android app.It stucks on the "Fetching account Info".Even i reinstall the game on android ,it still doesn't work.

### Reproduction Steps

1.Open the App
2.See the bug

### Expected behaviour

Fix it 

### Screenshots

![Screenshot_2022-10-29-22-25-23-02_9737de6f3e36012](https://user-images.githubusercontent.com/117086200/199005718-a5729065-ba2c-446b-be26-b59306ec7da6.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4645

### Are you using any mods?

No

**Comment by smcvey** [comment]
Also getting the same as of today.  Started via Steam and entered my username/password but it hangs on login.

**Comment by MelvorIdle** [comment]
I am unable to reproduce this bug. If the issue persists, please create a new report.
