### ISSUE TITLE
[Bug]: Township: Miners Estate being a downgrade

### ISSUE THREAD

**Issue by Mlvrbugsthrwawy** [MelvorIdle/melvoridle.github.io#2867]
### Describe the bug

I've recently upgraded my Quarries into Estates (Map 1, Desert biome, maxed out Glacia worship, about 60% Education) and the production went slightly down. This doesn't seem to be just a display issue, as my net coal went from positives into negatives after the upgrade.

### Reproduction Steps

1. Build Quarries in a Desert biome with 100% Glacia worship and about 60% Education
2. Also build some Estates
3. Compare the outputs

### Expected behaviour

The Estates should be better

### Screenshots

![image](https://user-images.githubusercontent.com/117089624/199014478-36b81036-b232-4931-a1b4-e3d26a916106.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4645

### Are you using any mods?

No

**Comment by GauChoob** [comment]
More specifically, all of the biomeModifiers for all of the Estate buildings are absent (i.e. the first 3 versions of a building have biomeModifiers, and it is only the Estate version (highest upgrade) that does not have any biomeModifiers)

**Comment by MelvorIdle** [comment]
Township has now been reworked as of v1.1.2
