### ISSUE TITLE
[UI]: Icons appear huge and mess up the UI (Makes the game unplayable)

### ISSUE THREAD

**Issue by TerreneCoder** [MelvorIdle/melvoridle.github.io#2871]
### Describe the bug

I loaded into the game one morning and the UI was huge.
Every element that had an Icon attached was giant and made the UI completely unusable

### Screenshots

![melvor example](https://user-images.githubusercontent.com/117112762/199079386-b9209cae-7da7-4351-8b9b-b4aefaaf0fee.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4645

### Are you using any mods?

No

**Comment by TerreneCoder** [comment]
I have tried uninstalling and reinstalling the game a couple of times.
No change. I messed around with zoom settings and system dpi settings. But still no change.
I also tried verifying game files a few times.

**Comment by TerreneCoder** [comment]
Updated the title because this makes the game literally unplayable on steam.

**Comment by MelvorIdle** [comment]
I am unable to reproduce this bug. If the issue persists, please create a new report.
