### ISSUE TITLE
[Bug]: (Android app) The Township skillcape disables the quick equip menu for capes

### ISSUE THREAD

**Issue by normalpenguins** [MelvorIdle/melvoridle.github.io#2873]
### Describe the bug

When the Township skillcape (level 99) is equipped, the quick equip menu for capes does not open. Equipping another cape manually does work, but it is impossible to unequip the cape normally. The quick equip menu functions again as normal when any other cape (as far as we know at the moment) is equipped, but not for the Township skillcape.

### Reproduction Steps

1. Equip the Township skillcape.
2. You are now prevented from using the quick equip menu. Tapping on the cape only provides the stat popup for the cape, but does not open the quick equip menu.

### Expected behaviour

The quick equip menu should open when tapping the cape slot when the Township skillcape is equipped.

### Save Link

https://melvoridle.com/save/RNRTLmoW

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4645

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
I cannot seem to reproduce this bug. The menu works fine for me on all platforms when the TS cape is equipped.

I also tested with your save and it is working fine as well.

Feel free to open a new issue if you run into the bug again. Also provide any extra information you may have to help find the possible cause.
