### ISSUE TITLE
[Bug]: Township Task Reward Not Fully Given

### ISSUE THREAD

**Issue by Rightheory** [MelvorIdle/melvoridle.github.io#2875]
### Describe the bug

After completing the Elite astrology task (give 10 000 stardust and 5 000 golden stardust) I got the 10m gold and 5 000 level 4 potions but did not get the bank slot token part of the task reward. 

### Save Link

https://melvoridle.com/save/f1PUOPaz

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4645

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Township has now been reworked as of v1.1.2
