### ISSUE TITLE
[Bug]: <title>Ancient Ring of Skills not giving Astrology XP

### ISSUE THREAD

**Issue by dfoglesong3** [MelvorIdle/melvoridle.github.io#2878]
### Describe the bug

I have the ancient ring of skills on and am only getting 66 xp from Ko, and 60 xp from arachi.

### Reproduction Steps

Equip ancient ring of skills and get astrology xp.

### Expected behaviour

mor xp

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4641

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
The ring is working as intended. The XP you see is inclusive of the XP bonuses. You can see it change in real time by unequipping and re-equipping the ring of skills.
