### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by DraxxS2** [MelvorIdle/melvoridle.github.io#2880]
### Describe the bug

I have a 45% bonus to cooking skill XP currently, when I should only have an 8% bonus to cooking skill XP. First noticed while using mods, but none should have an impact on xp rates. Attached is a screenshot of the increased skill XP. Verified by checking the cooking value of raw salmon from my save against the wiki, and it's an increase from 40 to 59.

### Save Link

https://melvoridle.com/save/ZTl8r9NX

### Screenshots

![cooking bug](https://user-images.githubusercontent.com/117152589/199182435-79f8d4b0-e581-4f0e-831f-8a52c601ae54.PNG)

### Console output

www.googletagmanager.com/gtag/js?id=UA-129674422-1:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
style.css:1          Failed to load resource: the server responded with a status of 404 ()
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloudManager.js?4645:197 Silent Sign in with JWT
cloudManager.js?4645:197 Validating Melvor Cloud token
cloudManager.js?4645:197 Storing Melvor Cloud Token
cloudManager.js?4645:197 Initializing PlayFab login. Method: customID
cloudManager.js?4645:197 Logging in with Custom ID via PlayFab
cloudManager.js?4645:197 Login with custom ID success
cloudManager.js?4645:197 Getting account info
cloudManager.js?4645:197 Account info retrieved
cloudManager.js?4645:197 Authenticated w/ Melvor Cloud: true
cloudManager.js?4645:197 Authenticated w/ PlayFab: true
cloudManager.js?4645:197 Checking for valid full version
cloudManager.js?4645:197 Checking for valid TotH purchase
cloudManager.js?4645:197 Loading Game Data...
save.js?4645:111 Registered Demo Data.
save.js?4645:111 Registered Full Version Data.
save.js?4645:111 Registered Throne of the Herald Data.
cloudManager.js?4645:197 Initializing Mod Manager...
cloud.js?4645:147 PlayFab Data Stored successfully.
cloudManager.js?4645:197 Checking for Mod Updates...
cloudManager.js?4645:197 Loading Mods...
cloudManager.js?4645:197 Loading Mods (1/5): SEMI Core (v1.7.2)
cloudManager.js?4645:197 Loading Mods (2/5): SEMI Drop Chances (v1.3.2)
cloudManager.js?4645:197 Loading Mods (3/5): Show Skill Modifiers (v1.2.3)
cloudManager.js?4645:197 Loading Mods (4/5): ETA (v1.0.0-41)
cloudManager.js?4645:197 Loading Mods (5/5): Item Township Task Info (v0.0.5)
cloudManager.js?4645:197 Loading Local Saves...
cloudManager.js?4645:197 Loading Cloud Saves...
cloudManager.js?4645:197 Getting saves from playfab
cloudManager.js?4645:197 Saves retrieved
characterSelect.js?4645:5 Loading character selection
cloudManager.js?4645:292 Connected to PlayFab successfully
save.js?4645:39 Copied to clipboard successfully.
main.js?4645:15 Game Loaded
SimManager.js:330 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (SimManager.js:330:35)
    at SimManager.js:355:30
SimPlayer.js:807 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (SimPlayer.js:807:35)
    at SimPlayer.js:832:30
TabCard.js:131 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (TabCard.js:131:35)
    at TabCard.js:156:30
App.js:3018 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (App.js:3018:35)
    at App.js:3043:30
main.js:99 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (main.js:99:35)
    at main.js:124:30
35a879e3-02c8-46cc-ab37-39692c2eeb2e:558 ETA : Loading...
35a879e3-02c8-46cc-ab37-39692c2eeb2e:558 ETA : added settings menu!
35a879e3-02c8-46cc-ab37-39692c2eeb2e:558 ETA : Loaded!
util.js:251 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (util.js:251:35)
    at util.js:276:30
modifierNames.js:931 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (modifierNames.js:931:35)
    at modifierNames.js:956:30
AgilityCourse.js:255 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (AgilityCourse.js:255:35)
    at AgilityCourse.js:280:30
Card.js:605 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Card.js:605:35)
    at Card.js:630:30
CombatData.js:174 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (CombatData.js:174:35)
    at CombatData.js:199:30
Consumables.js:397 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Consumables.js:397:35)
    at Consumables.js:422:30
DataExport.js:186 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (DataExport.js:186:35)
    at DataExport.js:211:30
ExportCheat.js:192 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (ExportCheat.js:192:35)
    at ExportCheat.js:217:30
Import.js:476 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Import.js:476:35)
    at Import.js:501:30
Loot.js:585 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Loot.js:585:35)
    at Loot.js:610:30
Plotter.js:545 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Plotter.js:545:35)
    at Plotter.js:570:30
Menu.js:168 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Menu.js:168:35)
    at Menu.js:193:30
Simulator.js:1173 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Simulator.js:1173:35)
    at Simulator.js:1198:30
SimEnemy.js:75 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (SimEnemy.js:75:35)
    at SimEnemy.js:100:30
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
style.css:1          Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
cloud.js?4645:29 Synchronising with Cloud

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4645

### Are you using any mods?

Yes

**Comment by OmaiGrundles** [comment]
This could actually be a bug with the "show skill modifiers" mod that you are using to show that information, It also shows a really high cooking skill bonus for me as well:

**Comment by MelvorIdle** [comment]
I believe this bug is related to a Mod that is displaying incorrect information. Feel free to open a new issue if you do see it as an issue with the game. I've done some checks myself without mods and the Cooking XP bonuses are working as intended.
