### ISSUE TITLE
[Bug]: Golbin Raid History replaces most recent raid instead of getting rid of oldest

### ISSUE THREAD

**Issue by xanderput** [MelvorIdle/melvoridle.github.io#2886]
### Describe the bug

See #2421.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4645

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue was fixed as of V1.1.2
