### ISSUE TITLE
[Bug]: Icon for adventure mode is not centred

### ISSUE THREAD

**Issue by xanderput** [MelvorIdle/melvoridle.github.io#2887]
### Describe the bug

See #2076.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4645

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.1.2
