### ISSUE TITLE
[Bug]: Game Failed to Load

### ISSUE THREAD

**Issue by VJohnston13** [MelvorIdle/melvoridle.github.io#2890]
### Describe the bug

1. Game Failed to Load.
2. This is my 2nd character.
3. 1st character decided at some point to have it's own issues:
- Activating a skill did not work as intended (activating a skill did not activate the skill), but after disabling most of the mods I use... it's started working again.
- There is no failed to load error with my 1st character.

```
TypeError: Cannot read property 'image' of undefined
    at https://steam.melvoridle.com/assets/js/built/prayer.js?4645:15:52
    at Set.forEach (<anonymous>)
    at PrayerMenu.setActive (https://steam.melvoridle.com/assets/js/built/prayer.js?4645:14:99)
    at Player.render (https://steam.melvoridle.com/assets/js/built/player.js?4645:424:61)
    at CombatManager.render (https://steam.melvoridle.com/assets/js/built/baseManager.js?4645:12:22)
    at CombatManager.render (https://steam.melvoridle.com/assets/js/built/combatManager.js?4645:60:38)
    at CombatManager.initialize (https://steam.melvoridle.com/assets/js/built/baseManager.js?4645:5:170)
    at CombatManager.initialize (https://steam.melvoridle.com/assets/js/built/combatManager.js?4645:47:172)
    at Game.onLoad (https://steam.melvoridle.com/assets/js/built/game.js?4645:161:171)
    at https://steam.melvoridle.com/assets/js/built/main.js?4645:9:164
```

### Reproduction Steps

Unknown as I have no clue what I did, if I did anything.

### Expected behaviour

Loading into my character so I can play... instead of whatever is happening rn. I can't load off of cloud or local.

I play on:
Android: Samsung A71 & S22, fully updated
Steam: Windows 10 PC
Web: Opera GX

All of these have been fine till recently.

### Save Link

https://melvoridle.com/save/q2GgN05J

### Screenshots

![image](https://user-images.githubusercontent.com/18430481/199372888-ddb27fef-fcdc-4386-8607-82ff317553c8.png)

### Console output

`index_game.php:52          GET https://melvoridle.com/style.css?2 net::ERR_ABORTED 404
DevTools failed to load source map: Could not load content for https://melvoridle.com/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
cloudManager.js?4645:197 Silent Sign in with JWT
cloudManager.js?4645:197 Validating Melvor Cloud token
cloudManager.js?4645:197 Storing Melvor Cloud Token
cloudManager.js?4645:197 Initializing PlayFab login. Method: customID
cloudManager.js?4645:197 Logging in with Custom ID via PlayFab
cloudManager.js?4645:197 Login with custom ID success
cloudManager.js?4645:197 Getting account info
cloudManager.js?4645:197 Account info retrieved
cloudManager.js?4645:197 Authenticated w/ Melvor Cloud: true
cloudManager.js?4645:197 Authenticated w/ PlayFab: true
cloudManager.js?4645:197 Checking for valid full version
cloudManager.js?4645:197 Checking for valid TotH purchase
cloudManager.js?4645:197 Loading Game Data...
save.js?4645:111 Registered Demo Data.
save.js?4645:111 Registered Full Version Data.
save.js?4645:111 Registered Throne of the Herald Data.
cloudManager.js?4645:197 Initializing Mod Manager...
cloud.js?4645:147 PlayFab Data Stored successfully.
cloudManager.js?4645:197 Checking for Mod Updates...
cloudManager.js?4645:197 Loading Mods...
cloudManager.js?4645:197 Loading Mods (1/18): SEMI Core (v1.7.2)
cloudManager.js?4645:197 Loading Mods (2/18): SEMI Save on Close (v1.1.0)
cloudManager.js?4645:197 Loading Mods (3/18): Undo Sell (v1.0.7)
cloudManager.js?4645:197 Loading Mods (4/18): Bank Tab Values (v1.1.0.4395)
cloudManager.js?4645:197 Loading Mods (5/18): Bank Search Equipment Slots (v1.0.1)
cloudManager.js?4645:197 Loading Mods (6/18): Additional Bank Buttons (v1.1.4)
cloudManager.js?4645:197 Loading Mods (7/18): Quick Item/Bank Wiki (v1.2.1.0032)
cloudManager.js?4645:197 Loading Mods (8/18): TrueOled: Battery Saver (v1.0.5)
cloudManager.js?4645:197 Loading Mods (9/18): Fix Bugs for Melvor (v1.1.0)
cloudManager.js?4645:197 Loading Mods (10/18): Sidebar Line Breaks Fixer (v1.0.2)
cloudManager.js?4645:197 Loading Mods (11/18): Forgot My Hat (v1.1.0)
cloudManager.js?4645:197 Loading Mods (12/18): Add Items (v1.0.0)
cloudManager.js?4645:197 Loading Mods (13/18): Right Click Equip Menu (v2.4)
cloudManager.js?4645:197 Loading Mods (14/18): Player and Enemy Modifiers (v2.1)
cloudManager.js?4645:197 Loading Mods (15/18): Registered Object Viewer (v1.1.2)
cloudManager.js?4645:197 Loading Mods (16/18): Reduced monster spawn time (v0.1)
cloudManager.js?4645:197 Loading Mods (17/18): Township Grid Display (v1.1.4)
cloudManager.js?4645:197 Loading Mods (18/18): Quick Equip Passive Slot (v1.6)
cloudManager.js?4645:197 Loading Local Saves...
cloudManager.js?4645:197 Loading Cloud Saves...
cloudManager.js?4645:197 Getting saves from playfab
cloudManager.js?4645:197 Saves retrieved
characterSelect.js?4645:5 Loading character selection
cloudManager.js?4645:292 Connected to PlayFab successfully
main.js?4645:24 TypeError: Cannot read properties of undefined (reading 'image')
    at prayer.js?4645:15:52
    at Set.forEach (<anonymous>)
    at PrayerMenu.setActive (prayer.js?4645:14:99)
    at Player.render (player.js?4645:424:61)
    at CombatManager.render (baseManager.js?4645:12:22)
    at CombatManager.render (combatManager.js?4645:60:38)
    at CombatManager.initialize (baseManager.js?4645:5:170)
    at CombatManager.initialize (combatManager.js?4645:47:172)
    at Game.onLoad (game.js?4645:161:171)
    at main.js?4645:9:164
(anonymous) @ main.js?4645:24
(anonymous) @ language.js?4645:5
__awaiter @ language.js?4645:2
updateWindow @ main.js?4645:5
(anonymous) @ main.js?4645:77
(anonymous) @ language.js?4645:5
__awaiter @ language.js?4645:2
onSaveDataLoad @ main.js?4645:77
(anonymous) @ save.js?4645:128
fulfilled @ language.js?4645:2
main.js?4645:78 Uncaught (in promise) Error: updateWindow failed.
    at main.js?4645:78:7
    at Generator.next (<anonymous>)
    at fulfilled (language.js?4645:2:98)
(anonymous) @ main.js?4645:78
fulfilled @ language.js?4645:2
Promise.then (async)
step @ language.js?4645:4
(anonymous) @ language.js?4645:5
__awaiter @ language.js?4645:2
onSaveDataLoad @ main.js?4645:77
(anonymous) @ save.js?4645:128
fulfilled @ language.js?4645:2`

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4645

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Does the save load if you disable all the mods?
