### ISSUE TITLE
[Bug]: <title>120 skill capes not available in quick equip menu

### ISSUE THREAD

**Issue by Scott-A-Maciver** [MelvorIdle/melvoridle.github.io#2891]
### Describe the bug

specifically ive seen this bug in the fishing quick equip menu not showing the 120 skillcape

### Reproduction Steps

buy 120 skillcape
go to fishing skill tab
go to gear in bottom right
the cape will not be available

### Expected behaviour

the cape should show in the quick equip menu

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4645

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
These are set manually by the player as the menu is customizable now. You can do this in the Bank.
