### ISSUE TITLE
[Bug]: HC death in impossible conditions

### ISSUE THREAD

**Issue by Gerzki** [MelvorIdle/melvoridle.github.io#2892]
### Describe the bug

Последняя окончательная смерть: Skalla. Убийца: Thieving. Общий уровень навыков: 1740. Время: 01.11.2022, 17:54:27

3k+ apple pie equipped, autoeat III, autoswitch eating enabled, thieving merchant/90+% success/, 820 hp - permadeath, how could this happen?

I began to burn through, really

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4685

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue contains insufficient information to debug.
