### ISSUE TITLE
[Bug]: FTP Skill percentage includes full game skills

### ISSUE THREAD

**Issue by Cramoisi-San** [MelvorIdle/melvoridle.github.io#2895]
### Describe the bug

In the completion log, the percentage calculation for the skill tab includes skills from the full game while you are in an Free To Play (FTP) account/character, when the other tabs does not include said full game content.

### Reproduction Steps

1. Create/connect to an account who neither has expansion nor full game
2. Create an character under that FTP account
3. Go to completion log, you will notice that the skill tab's percentage includes full game skills, despite the fact that all the other tabs does not include full game content. More noticeable as you level up the skills you have access to.

### Expected behaviour

The percentage of the skill tab of the completion log should only include the FTP skills's levels into it's calculation when in a FTP character, like all the other tabs only calculate and show the items/pets/monsters/mastery levels that are reachable to a FTP account.

### Save Link

https://melvoridle.com/save/gldwqFej

### Screenshots

Skill Tab
![image](https://user-images.githubusercontent.com/39337986/199514987-2d9ba2c1-9100-4415-a894-5644f267e9a4.png)
Mastery Level Tab
![image](https://user-images.githubusercontent.com/39337986/199515142-12ce661e-c437-45a8-ab10-fa3ec1a24295.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4675

### Are you using any mods?

No

**Comment by coolrox95** [comment]
The demo version is not intended to be able to reach 100% completion. It is just a preview for the full version of the game.
