### ISSUE TITLE
[Bug]: Not gaining Tiks for township after time change 

### ISSUE THREAD

**Issue by Techvipr** [MelvorIdle/melvoridle.github.io#2896]
### Describe the bug

I'm no longer gaining township Tiks after a time change. It's sat at 0 for several days

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4675

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Altering the time on your device is not an intended mechanic. Please be careful with this kind of stuff as it could cause issues like the one present.

You can possibly reach out to a mod developer to assist with fixing your save.
