### ISSUE TITLE
[Bug]: Agility "Welcome Back" screen broken - impossible to click OK on iOS

### ISSUE THREAD

**Issue by staticf0x** [MelvorIdle/melvoridle.github.io#2897]
### Describe the bug

In some cases after opening the app while idling agility, the overlay with the Welcome Back screen happens to be slightly off to the top. As a result it's impossible to click the OK button, neither where it's displayed nor where it's supposed to be. However it's possible to click on the not-overlayed area at the bottom to dismiss the screen or minimize the app and open it again or close it and start again. So far it happened only with agility and no other skill. Also it doesn't happen always, but like 1 out of 5 times or so.

### Screenshots

![2022-10-31 20 20 00](https://user-images.githubusercontent.com/44530786/199576934-2926aac4-5c55-4416-ad5d-5e7c7985b22d.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4675

### Are you using any mods?

No

**Comment by RudestBuddhist** [comment]
I've had this happen with several skills. If you rotate your phone sideways, you can click OK. I've been doing that until the issue gets resolved.

**Comment by mengisman** [comment]
I also experience this and have to click below the button

**Comment by MelvorIdle** [comment]
I've been unable to reproduce this bug. If the issue persists, please submit another report.
