### ISSUE TITLE
[Bug]: <F2P unobtainable items>

### ISSUE THREAD

**Issue by Olchy** [MelvorIdle/melvoridle.github.io#2899]
### Describe the bug

Completion log for f2p or demo players has smoke rune, dust rune, mist rune, light rune, and blood rune as obtainable items for f2p.. these are not possible as of the current version.   

### Reproduction Steps

1. Go to demo collection log.  2. Scroll down n find them?  3. Huzzah

### Expected behaviour

Remove them so I can get my f2p collection to 100% Shaka brah.   

### Screenshots

![FDEB18E2-B189-41DA-B21B-981954553119](https://user-images.githubusercontent.com/117312579/199586769-3fbcc2ef-354b-473d-bc5e-309bbfa6ce16.jpeg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4675

### Are you using any mods?

No

**Comment by coolrox95** [comment]
These items are required to exist due to technical reasons, furthermore the demo version has never been intended to reach 100% completion.
