### ISSUE TITLE
Opening 1 chest at a time does not check for full bank before rolling an item

### ISSUE THREAD

**Issue by 8992scripts** [MelvorIdle/melvoridle.github.io#290]
The open ×1 option for chest items does not check if your bank is full before it rolls an item
For example if you were opening Aeris scrolls and the only Aeris item you had in your bank was an Aeris platebody and your bank was full then if you click open 1 and it rolls a platebody you will get it but if you roll any other item you don't get it because the bank is full but the scroll is not used up, this means you can just spam click open and get platebodies from every scroll that you use up.
The chest opened stat is also increased when you roll an item you don't have space for which makes the stats look obviously wrong when you have more chests opened than you have found.

It should just check if the bank is full before it rolls items and before it adds to chests opened stat

**Comment by mazunki** [comment]
Related: Looting items from a monster doesn't check if bank is full, but disappears from the loot. Avoidable if careful, but annoying if bank was full and you hadn't noticed.
