### ISSUE TITLE
[cant sign into account]: <wont let me log into my account/ cloud saves>

### ISSUE THREAD

**Issue by Musifyy** [MelvorIdle/melvoridle.github.io#2901]
### Describe the bug

on steam / chrome / ios it will not let me log into my account at all i keep pressing sign in and nothing happens all my information is 100% correct because if not it says incorrect username or password. 

i even tried to make another account and it still wont log that account in.

### Reproduction Steps

log in
fail to log in

### Expected behaviour

to be able to log in

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4675

### Are you using any mods?

No

**Comment by LilH3ro** [comment]
Same issue here... cant log in at all x.x

**Comment by MelvorIdle** [comment]
Is this issue still occurring?

If yes, what is the Cloud username. I will take a look.

**Comment by LilH3ro** [comment]
> 

My Username is: Puffs

**Comment by Musifyy** [comment]
> Is this issue still occurring?
> 
> If yes, what is the Cloud username. I will take a look.

Musify

**Comment by Musifyy** [comment]
its been months and still the same issue...

**Comment by Musifyy** [comment]
> Is this issue still occurring?
> 
> If yes, what is the Cloud username. I will take a look.

this issue is still occurring PLEASE , Musify
