### ISSUE TITLE
[Bug]: Skillers outfit items in Shop have display cost incorrectly multiplied by "Buy xX" amount

### ISSUE THREAD

**Issue by fradigit** [MelvorIdle/melvoridle.github.io#2903]
### Describe the bug

Skiller outfits (ex. Woodcutters Hat, Fletchers Leggings, etc) incorrectly display cost as if you were buying multiple pieces of the same item. This is only a visual bug, when purchased only 1 item is obtained and the correct amount of 100K is taken from your GP amount. 

### Reproduction Steps

1. Go to Shop
2. Select "Buy x1"
3. Woodcutters Hat shows a price of 100K
4. Select "Buy x100" 
5. Woodcutters Hat shows a price of 10M
6. Purchase Woodcutters Hat, receive 1 hat at a price of 100K

### Expected behaviour

I would expect the display price to always show 100K no matter the multiplier selected in the "Buy xX" option

### Screenshots

![image](https://user-images.githubusercontent.com/76832865/199647578-32bedc7f-9868-48b0-a4d6-005d23c4727b.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4675

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was fixed as of v1.1.1 (?4999).
