### ISSUE TITLE
[Bug]: Palladium Pot Icon Missing

### ISSUE THREAD

**Issue by ssharpjr** [MelvorIdle/melvoridle.github.io#2904]
### Describe the bug

Shop, Skill Upgrades. The icon for the Palladium Pot is missing. 

### Reproduction Steps

Go to Shop.
Go to Skill Upgrades.
School down to Palladium Pot.
There is no icon. 

### Save Link

https://melvoridle.com/save/LlyPLRPz

### Screenshots

![Screenshot_20221103-061532](https://user-images.githubusercontent.com/1624215/199696801-f63796aa-61fa-4875-bd66-8d1d0b1b8337.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4675

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This has now been fixed as of v1.1.1.
