### ISSUE TITLE
Eagle - Devil not working properly[Bug]: <title>

### ISSUE THREAD

**Issue by Stickrim** [MelvorIdle/melvoridle.github.io#2906]
### Describe the bug

Description is -100% GP from agility, still get GP from agility

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4675

### Are you using any mods?

Yes

**Comment by OmaiGrundles** [comment]
-100GP might not be enough to reduce it to zero, cause for instance, i have +170% gp, so a -100% would only bring me to a +70%

**Comment by Stickrim** [comment]
That makes sense. Thanks
