### ISSUE TITLE
Nature Wrath Staff wrong description[Bug]: <title>

### ISSUE THREAD

**Issue by Stickrim** [MelvorIdle/melvoridle.github.io#2907]
### Describe the bug

Says reduces Nature rune use by 1, actually reduces by 2

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4675

### Are you using any mods?

Yes

**Comment by Flurryous** [comment]
You're using magic/max skillcape that doubles the staff's rune saving bonus.

**Comment by Stickrim** [comment]
Thank you
