### ISSUE TITLE
[Bug]: lock up on save loading 

### ISSUE THREAD

**Issue by Craztech11** [MelvorIdle/melvoridle.github.io#2908]
### Describe the bug

Locks up on loading screen of a save
![Screenshot_20221104-052006_Melvor Idle](https://user-images.githubusercontent.com/117448884/199962421-7b424f45-bf65-4328-bc91-146294d3d4b6.jpg)

### Screenshots

![Screenshot_20221104-052006_Melvor Idle](https://user-images.githubusercontent.com/117448884/199962475-fb58f04f-7a81-477c-8aca-fa858393fc27.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
I have seen this bug to be caused by a few specific Mods. This can be Auto Loot or Auto Mastery. Please attempt to load the save without mods and see if it loads.
