### ISSUE TITLE
[Bug]: Spirit Bags are consumed when casting non-Alchemy Alt. Magic spell

### ISSUE THREAD

**Issue by Falterfire** [MelvorIdle/melvoridle.github.io#2909]
### Describe the bug

If equipped, a Spirit Magic consumable is used when any Alt. Magic action is taken, even if the spell is not an Alchemy spell and is thus not affected.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

4675

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue was fixed as of V1.1.2
