### ISSUE TITLE
Gaining offline experience for my last non-combat skill when refreshing game after training combat

### ISSUE THREAD

**Issue by DylGit** [MelvorIdle/melvoridle.github.io#291]
**Describe the bug**
When I refresh my browser/game after combat, I receive catch up offline experience for the last non-combat skill I trained for the duration of time I trained combat and still retain the earned combat rewards.

**To Reproduce**
1. Train any non-combat skill
2. Start combat with any mob
3. Refresh game after X minutes of combat
4. prompted with offline skill window for the non-combat skill in step 1 for duration combat duration X in step 3.

**Expected behavior**
Whenever `clearOffline() `is called it does nothing because `offlinePause `is set to true even though the experimental setting has **never** been enabled and because of this it never becomes false. This results in being able to refresh after doing combat to trigger an offline catchup for the length of time since combat was started.

**Screenshots**
n/a

**Browser**
Chrome 83

**Console output**
no

**Are you using any scripts?**
Combat simulator, completion log, Scripting Engine for melvoridle.
I am reproduce without any scripts turned on.

**Comment by MelvorIdle** [comment]
Is this still occurring as of today?

**Comment by DylGit** [comment]
> Is this still occurring as of today?

Yes.
