### ISSUE TITLE
[Bug]: saves broken and unplayable

### ISSUE THREAD

**Issue by Lodisy12** [MelvorIdle/melvoridle.github.io#2911]
### Describe the bug

After installing the mod, Expansion Summoning Recipes, an error popped up while levelling thieving. The error said something about the game not being able to calculate ticks and recommended refreshing the cache for android users (which I'm not). The error also named the mod, Expansion Summoning Recipes, but I don't know in what context, I just saw it's name. After that I was permanently stunned and unable to do take any action (it says: "you can't do that while stunned") except for township actions. I cannot stop thieving or start any new action. I tried restarting the game, uninstalling all mods, opening the game from other platforms (iphone and browser), exporting and importing my save.

I had some mods installed at the time that this error happened:

SEMI: core, drop chances, auto master, auto farming, auto sell, auto loot, auto mine, auto eat, auto runecrafting, auto smith bars, xp per hour

Others: item uses, unlimited offline, township breakdown, mastery pool can overflow, modifiers exposed, quickshards, township task info, township grid display, item dashboard, Expansion Summoning Recipes.

When this occurred, my other save was also compromised. That save will not even launch, it gives the following error log when I try to load it:

TypeError: Cannot read property 'sellsFor' of undefined

at Summoning.addNonShardCosts (https://steam.melvoridle.com/assets/js/built/summoning.js?4675:68:114)

at Summoning.getAltRecipeCosts (https://steam.melvoridle.com/assets/js/built/summoning.js?4675:73:6)

at Summoning.getRecipeCosts (https://steam.melvoridle.com/assets/js/built/summoning.js?4675:74:43)

at Summoning.getCurrentRecipeCosts (https://steam.melvoridle.com/assets/js/built/artisanSkill.js?4675:25:37)

at Summoning.renderSelectedRecipe (https://steam.melvoridle.com/assets/js/built/artisanSkill.js?4675:32:166)

at Summoning.renderSelectedRecipe (https://steam.melvoridle.com/assets/js/built/summoning.js?4675:81:7)

at Summoning.render (https://steam.melvoridle.com/assets/js/built/artisanSkill.js?4675:20:15)

at Summoning.render (https://steam.melvoridle.com/assets/js/built/summoning.js?4675:71:16)

at Summoning.onLoad (https://steam.melvoridle.com/assets/js/built/artisanSkill.js?4675:14:6)

at Summoning.onLoad (https://steam.melvoridle.com/assets/js/built/summoning.js?4675:69:16)

I do believe that this error was caused by the mod Expansion Summoning Recipes, but I have no idea why and have not been able to recover either save as of yet.

### Reproduction Steps

Install the following mods and start thieving the goblin chief:

SEMI: core, drop chances, auto master, auto farming, auto sell, auto loot, auto mine, auto eat, auto runecrafting, auto smith bars, xp per hour

Others: item uses, unlimited offline, township breakdown, mastery pool can overflow, modifiers exposed, quickshards, township task info, township grid display, item dashboard, Expansion Summoning Recipes.

### Expected behaviour

When stunned you will be permanently stunned and other saves will not load.

### Save Link

https://melvoridle.com/save/b06KcmcC

### Screenshots

![image](https://user-images.githubusercontent.com/42898462/200051617-75bd669e-7306-42c7-8c42-9e598d464fd9.png)

### Console output

style.css:1          Failed to load resource: the server responded with a status of 404 ()
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
5[DOM] Input elements should have autocomplete attributes <attribute>: (More info: <URL>) 
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloudManager.js?4675:199 Silent Sign in with JWT
cloudManager.js?4675:199 Validating Melvor Cloud token
cloudManager.js?4675:199 Storing Melvor Cloud Token
cloudManager.js?4675:199 Initializing PlayFab login. Method: customID
cloudManager.js?4675:199 Logging in with Custom ID via PlayFab
cloudManager.js?4675:199 Login with custom ID success
cloudManager.js?4675:199 Getting account info
cloudManager.js?4675:199 Account info retrieved
cloudManager.js?4675:199 Authenticated w/ Melvor Cloud: true
cloudManager.js?4675:199 Authenticated w/ PlayFab: true
cloudManager.js?4675:199 Checking for valid full version
cloudManager.js?4675:199 Checking for valid TotH purchase
cloudManager.js?4675:199 Loading Game Data...
save.js?4675:111 Registered Demo Data.
save.js?4675:111 Registered Full Version Data.
save.js?4675:111 Registered Throne of the Herald Data.
cloudManager.js?4675:199 Initializing Mod Manager...
cloud.js?4675:147 PlayFab Data Stored successfully.
cloudManager.js?4675:199 Checking for Mod Updates...
cloudManager.js?4675:199 Loading Mods...
cloudManager.js?4675:199 Loading Local Saves...
cloudManager.js?4675:199 Loading Cloud Saves...
cloudManager.js?4675:199 Getting saves from playfab
cloudManager.js?4675:199 Saves retrieved
characterSelect.js?4675:5 Loading character selection
cloudManager.js?4675:294 Connected to PlayFab successfully
main.js?4675:24 TypeError: Cannot read properties of undefined (reading 'sellsFor')
    at Summoning.addNonShardCosts (summoning.js?4675:68:114)
    at Summoning.getAltRecipeCosts (summoning.js?4675:73:6)
    at Summoning.getRecipeCosts (summoning.js?4675:74:43)
    at Summoning.getCurrentRecipeCosts (artisanSkill.js?4675:25:37)
    at Summoning.renderSelectedRecipe (artisanSkill.js?4675:32:166)
    at Summoning.renderSelectedRecipe (summoning.js?4675:81:7)
    at Summoning.render (artisanSkill.js?4675:20:15)
    at Summoning.render (summoning.js?4675:71:16)
    at Summoning.onLoad (artisanSkill.js?4675:14:6)
    at Summoning.onLoad (summoning.js?4675:69:16)
(anonymous) @ main.js?4675:24
main.js?4675:78 Uncaught (in promise) Error: updateWindow failed.
    at main.js?4675:78:7
    at Generator.next (<anonymous>)
    at fulfilled (language.js?4675:2:98)
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
style.css:1          Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

1.1 (?4675)

### Are you using any mods?

Yes

**Comment by ContraireZoe** [comment]
Howdy, I saw your bug and I saw this post from the subreddit have a bit in common: https://www.reddit.com/r/MelvorIdle/comments/ym0n8h/permanently_stunned_in_thieving_need_help/

In the comments the mod creator claimed ownership of the bug and says you may be able to fix it by following the steps here: https://www.reddit.com/r/MelvorIdle/comments/ym0n8h/comment/iv3ydv9/?utm_source=share&utm_medium=web2x&context=3

He also offered to fix peoples saves if all else fails. Hope of these helps!

**Comment by Lodisy12** [comment]
Hi! Thank you so much for the follow up. That was actually me, haha. Someone from that thread recommended that I go to the discord and someone from the discord recommended that I post this here. I didn't think to come back and close this issue, sorry about that.

Thanks again :)
