### ISSUE TITLE
[Bug]: Unable to reset Banktab Icons to default/unbind items.

### ISSUE THREAD

**Issue by FortuneReborn** [MelvorIdle/melvoridle.github.io#2914]
### Describe the bug

Players are unable to reset the icons of banktabs to their default states. (Being blank when empty, and showing the icon of the item in the first slot when there are items.)
It is possible to do so through the console, but not through more regular means.

### Reproduction Steps

1. Go to Bank.
2. Click on any item in the Bank.
3. Go to Item Settings on the right.
4. Select a Tab to set the Tab's Icon to the selected Item's Icon.
5. Find there is no way to set the Tab's Icon to default behavior. It can only be overwritten to become another Item's Icon.

### Expected behaviour

I expect there to be a way to reset a Tab's Icon-behaviour.

### Save Link

https://melvoridle.com/save/sp92p7GH

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4675

### Are you using any mods?

No

**Comment by Pjmcnally** [comment]
You say this can be fixed for now through the console. How is that done?

I have some tabs I would like to clear the icons for currently. I am familiar with using the console in Melvor Idle.

**Comment by FortuneReborn** [comment]
On Discord, user 'Ekuland' provided me with the following command:
```
game.bank.tabIcons.clear();
for(let i=0; i<12;i++) game.bank.renderQueue.tabIcons.add(i);
```
I did not use the command myself. I sent him my savefile, and they did it for me, returning my savefile to me. I hope it works.

**Comment by Pjmcnally** [comment]
Thank you very much. That solved my problem exactly. 

As a heads up to anyone who finds this later the code below will reset all your tab icons back to the default of either empty or the first item in that bank tab. 

`game.bank.tabIcons.clear();
for(let i=0; i<12;i++) game.bank.renderQueue.tabIcons.add(i);`

**Comment by darylknight** [comment]
This doesn't work anymoer.
