### ISSUE TITLE
[Bug]: <title>寵物  取得  機率  錯誤

### ISSUE THREAD

**Issue by mpypipira** [MelvorIdle/melvoridle.github.io#2915]
### Describe the bug

小雞  地下城 超過 1400  才得到
黃金 哥布林  46901 擊殺  沒  獲取

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4641

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Google Translate of Issue:
Title: Pet acquisition chance error
Description:
chick dungeon over 1400 to get
gold goblin 46901 kill no get

Resolution:
Bad Random Number Generation is not a bug.
