### ISSUE TITLE
[Bug]: <traps potion>

### ISSUE THREAD

**Issue by Jonzzor94** [MelvorIdle/melvoridle.github.io#2916]
### Describe the bug

No difference in tiers for traps potions. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

????

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This has now been fixed as of v1.1.1.
