### ISSUE TITLE
[Bug]: Farming - Incorrect cost for unlocking final allotment plot

### ISSUE THREAD

**Issue by Auron956** [MelvorIdle/melvoridle.github.io#2917]
### Describe the bug

The final allotment plot that becomes available after reaching level 118 Farming currently costs 1 million GP. This is cheaper than the previous allotment plot and out of line with the final herb and tree plots, which have a cost of 10 million.

### Reproduction Steps

1. Navigate to allotments section of Farming page
2. Observe final plot cost of 1m

### Expected behaviour

Plot should cost 10m in line with others

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4675

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This has now been fixed as of v1.1.1.
