### ISSUE TITLE
[Bug]: Windows High Contrast Mode Hides UI Elements

### ISSUE THREAD

**Issue by batponies123** [MelvorIdle/melvoridle.github.io#2918]
### Describe the bug

When playing the game with Windows High contrast mode enabled, many UI elements are outright hidden. Just a few items I've found are:

- Combat health/attack bars
- Thieving health/action bars
- Action progress bars
- Combat XP progress bars
- Currently selected skill tab highlight

### Reproduction Steps

1. Enable any Windows HC theme
2. Launch the game
3. Load any character

### Expected behaviour

Key UI elements such as combat/thieving health and interval bars shouldn't be overwritten by HC settings.

### Screenshots

![188314374-c9adf50d-56cb-497b-add5-a70a43f4d77f](https://user-images.githubusercontent.com/22773773/200122451-08af3293-ac57-4c8c-8e21-ff7528df6560.PNG)
![188314383-f34df9dd-ab65-470c-980a-ecacc644094e](https://user-images.githubusercontent.com/22773773/200122456-4a8af41e-7fcd-4a76-b731-5ddb6f1684d0.PNG)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4675

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Unfortunately, our game does not officially support Windows High Contract mode.
