### ISSUE TITLE
[Bug]: Rags to Riches I

### ISSUE THREAD

**Issue by Tigolebitties** [MelvorIdle/melvoridle.github.io#2919]
### Describe the bug

When clicking the image in Rags to Riches I in Alt Magic to choose an item the action disappears leaving only the selection of other Alt Magic actions forcing you to select a different casting action.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4675

### Are you using any mods?

No

**Comment by curious209** [comment]
Just discovered this bug when I reached Level 48, Rags to Riches l. 

Multiple attempts & refresh of game makes no difference.

Mobile App (Android)

**Comment by 111237999** [comment]
I also have this bug. I just realized I was an high enough level in alt. Magic to use rags to riches and wanted to explore. But I only get the selection of other spells. I have closed down and restarted the game multiple times, no difference.
