### ISSUE TITLE
[Bug]: Game Guide does not pop up when clicking the Astrology icon 

### ISSUE THREAD

**Issue by IcicleF** [MelvorIdle/melvoridle.github.io#2922]
### Describe the bug

When clicking the Astrology icon on the topbar, the game guide does not pop up. 
_Is this simply due to that a game guide is WIP?_

### Reproduction Steps

1. Select Astrology on the left bar.
2. Click the icon left to 'Astrology'.
3. Nothing happens.

### Expected behaviour

A game guide dialog pops up.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4675

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was fixed as of V1.1.2
