### ISSUE TITLE
[Bug]: <Bear & Owl>

### ISSUE THREAD

**Issue by inorlive** [MelvorIdle/melvoridle.github.io#2923]
### Describe the bug

I am training Herblore and have the Bear/Owl pair.  I have the three Stardust Astrology boosts maxed.  The golden stardust are not maxed.  I was expecting to get a 4.5% boost to Herblore Mastery, and I am only getting 3%.  I then maxed out 2 of the golden stardust and boost was 5%, not the expected 7.5%.  

I can proved screenshots, here is a link to the initial config:
https://melvoridle.com/save/5yw4REQS

w/o Bear/Owl  Master:  463 / 231
w Bear/Owl & 3 stars:  477/238
w Bear/Owl & 5 stars:  486/243

thanks for hours of fun!!!
Glad to give back !!

While I have your attention, can I also suggest that you provide a way to "donate" that is NOT recurring.
I would gladly donate, and have tried to donate, but you only allow recurring donations.
I dont want any special icons or whatever, I just want to send a one time payment to show my appreciation.

### Save Link

https://melvoridle.com/save/5yw4REQS

### Which platforms are you experiencing this bug on?

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

4675

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
You already had base bonuses to the amount of mastery XP gained. The Wolf + Owl is additive to this bonus, hence why the values you see do not increase by their bonus alone.

The value returned for the total modifier is working as intended:
![image](https://user-images.githubusercontent.com/58208131/227678406-a509fe4d-c710-41ee-a658-85a3beb1387d.png)
First query is before maxing another Qimican modifier, second is after maxing an additional one.
