### ISSUE TITLE
[Bug]: Mastery Token Farming

### ISSUE THREAD

**Issue by DarkGreenTea** [MelvorIdle/melvoridle.github.io#2927]
### Describe the bug

Over 240 hours of playing time in new DLC, I never recieved a single Farming Token.
I tested by using MOD, "SEMI Auto Farming" + "increased game speed", to harvested over 100M of each Vegetables and Herbs but 0 token.
I've got every other items for completion but this.
Please check the data.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695

### Are you using any mods?

Yes

**Comment by Delerium** [comment]
Related to this, offline progress in any other skill is only giving 1 mastery token max while offline.  I tested it by save scumming a save with max hours on it.  Production changed depending on the resource calculations, but mastery coins never went above 1.

**Comment by Delerium** [comment]
after further testing, even while actively playing, the most mastery tokens I seem to be able to get in any skill is 1.  After I get the first one, I don't seem to get another one until I spend the first one.

**Comment by Sobadx** [comment]
I am having the same problem, I have no mods installed and have just reached 95 farming and have not received a single token.
I could be the unluckiest person ever but I highly doubt that I have not received one

**Comment by coolrox95** [comment]
Issue was fixed in v1.1.1 (?4891).
