### ISSUE TITLE
[Bug]: No Offline Progress

### ISSUE THREAD

**Issue by fenderbender234** [MelvorIdle/melvoridle.github.io#2929]
### Describe the bug

On my adventure mode account, I started fishing for Leaping Broad Fish.  I currently have the barbarian gloves equipped, I am level 96 fishing (97 combat level in adventure mode).  I logged out for 2 hours, and when I came back the only xp and items that I received were from farming.  I got 0 fish, gems, or chests from fishing.  I have 8 empty slots in my bank.

### Reproduction Steps

1. Equip Barbarian Gloves
2. Start Fishing Leaping Broad Fish
3. Go offline for longer than 7.2 seconds in order to get a full cast off
4. see error

### Expected behaviour

If you follow the steps that I have listed above, you may get the same result where you get no items or experience from fishing, but still get xp from farming.

### Save Link

https://melvoridle.com/save/6HU1ltjz

### Screenshots

![5](https://user-images.githubusercontent.com/31377173/200274000-78828641-a957-432c-81dd-aa7e74569adc.PNG)
![6](https://user-images.githubusercontent.com/31377173/200274008-9df05492-3707-4018-8a2f-8956c720410b.PNG)

above are screenshots of the mods I have active while the bug happened

### Console output

I am using the steam version of the game

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Please open a new issue if this bug occurs with all Mods disable. Currently there is not enough information to determine if this was caused by the game or by a mod.
