### ISSUE TITLE
Semi permanent item window after an item disapears from your inventory

### ISSUE THREAD

**Issue by abcras** [MelvorIdle/melvoridle.github.io#293]
Opens item window and you can't close it again. This happens after you click add on food items and it disappears from your inventory. 

**To Reproduce**
1. Go to Bank
2. Click on a food item
3. Click add all
4. If you after clicking on add all hover over an item that items description/hover box does not disappear until you leave the page or click another item on the page.

**Expected behavior**
The hover text appears after you move the mouse further (as normal) but does not stay open until you switch page or click another item.

**Screenshots**
![image](https://user-images.githubusercontent.com/3748122/85870102-ec117580-b7cc-11ea-83cb-e8b50d639bf9.png)
Showing to hover windows at a time.

**Browser**
Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

**Console output**
There is nothing related to this issue in the console

**Are you using any scripts?**
I am not using any scripts.

**Comment by MelvorIdle** [comment]
You can click anywhere on the screen for these to disappear.
