### ISSUE TITLE
[Bug]: Golbin raid Royal Toxins Spear

### ISSUE THREAD

**Issue by Nyxeez** [MelvorIdle/melvoridle.github.io#2933]
### Describe the bug

The special attack of the royal toxins spear doesnt procc in golbin raid instead the special attack is brute force.

### Reproduction Steps

1. Do golbin raid on normal (dont know if difficulty matters)
2. Have royal toxins spear equipped

### Screenshots

![Melvor](https://user-images.githubusercontent.com/117676906/200385663-f9aa8e07-ebe2-4de3-abed-1d3c4511a0fb.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
You selected an "ALT" weapon which provides a random special attack
