### ISSUE TITLE
[Bug]: Quick Equip for non-combat skills doesn't include Superior Skillcapes

### ISSUE THREAD

**Issue by Sundwalltanner** [MelvorIdle/melvoridle.github.io#2939]
### Describe the bug

I can currently only confirm this for `Astrology` and `Farming`, as those are the only 2 non-combat skills that I own Superior Skillcapes for.

### Reproduction Steps

1. Purchase a Superior Skillcape
2. Visit the section for that skill
3. Attempt to equip the Skillcape via the `Quick Equip` menu in the bottom right toolbar

### Expected behaviour

I would expect all equipable items associated with that particular non-combat skill to be equipable via the `Quick Equip` button.

`Farming` might just be broken in this regard in general though, because `Bob's Rake` and `Bob's Gloves` also don't show up in the `Quick Equip` menu.

### Screenshots

I'm specifically talking about the `Quick Equip` button on the bottom right toolbar. For `Farming`, I'm not seeing anything there even though I own the `Superior Farming Skillcape`, the `Maximum Skillcape`, `Bob's Rake`, and `Bob's Gloves`.

![image](https://user-images.githubusercontent.com/11891490/200621073-46b68be5-2723-4147-89cc-21a1095a1913.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Quick equip items are custom defined by the player. This can be done by selecting the item in the Bank, and adding it to the quick equip section within the Gear icon
