### ISSUE TITLE
[Bug]: Ore not respawning

### ISSUE THREAD

**Issue by Bella-Giraffety** [MelvorIdle/melvoridle.github.io#2940]
### Describe the bug

Various ores are stuck in their empty state.  They cannot be mined as there is nothing there, but they are also not refilling.

I have since rebooted the game, reinstalled the game, and initiated the game on different platforms and the problems persist.  I have also taken the aforementioned steps with mods disabled as well as enabled.

### Reproduction Steps

Unsure how to duplicate precisely.

Best guess:
1. Reduce ore spawn time to 1ms when no mastery levels are had
2. increase mastery level to 25% to reduce spawn time by 10%
3. ores no longer spawn
4. disable mods and reinstall the game (or start the game on a browser)
5. error persists

### Expected behaviour

The ores should respawn

### Save Link

https://melvoridle.com/save/nNLGRvEX

### Screenshots

![image](https://user-images.githubusercontent.com/117771104/200655880-7aff572c-7062-44c7-a71f-01bbe9149a9e.png)

### Console output

Failed to load resource: the server responded with a status of 404 ()
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloudManager.js?4695:199 Silent Sign in with JWT
cloudManager.js?4695:199 Validating Melvor Cloud token
cloudManager.js?4695:199 Storing Melvor Cloud Token
cloudManager.js?4695:199 Initializing PlayFab login. Method: customID
cloudManager.js?4695:199 Logging in with Custom ID via PlayFab
cloudManager.js?4695:199 Login with custom ID success
cloudManager.js?4695:199 Getting account info
cloudManager.js?4695:199 Account info retrieved
cloudManager.js?4695:199 Authenticated w/ Melvor Cloud: true
cloudManager.js?4695:199 Authenticated w/ PlayFab: true
cloudManager.js?4695:199 Checking for valid full version
cloudManager.js?4695:199 Checking for valid TotH purchase
cloudManager.js?4695:199 Loading Game Data...
save.js?4695:111 Registered Demo Data.
save.js?4695:111 Registered Full Version Data.
cloudManager.js?4695:199 Initializing Mod Manager...
cloud.js?4695:147 PlayFab Data Stored successfully.
cloudManager.js?4695:199 Checking for Mod Updates...
cloudManager.js?4695:199 Updating Mods...
mod.js?4695:107 [SEMI Auto Bonfire] No namespace is defined. The mod will have limited access to game APIs.
(anonymous) @ mod.js?4695:107
cloudManager.js?4695:199 Loading Mods...
cloudManager.js?4695:199 Loading Mods (1/11): SEMI Core (v1.7.2)
cloudManager.js?4695:199 Loading Mods (2/11): Unlimited Offline (v0.1.3)
cloudManager.js?4695:199 Loading Mods (3/11): Mastery Pool Can Overflow (v1.2.0)
cloudManager.js?4695:199 Loading Mods (4/11): Double XP Weekends (v1.0.1)
mod.js?4695:745 [Double XP Weekends] Possible mod conflict - SkillWithMastery.addMasteryPoolXP has already been patched by the following mods: "Mastery Pool Can Overflow"
patch @ mod.js?4695:745
cloudManager.js?4695:199 Loading Mods (5/11): SEMI Auto Eat (v1.4.0)
cloudManager.js?4695:199 Loading Mods (6/11): SEMI Auto Loot (v1.3.0)
cloudManager.js?4695:199 Loading Mods (7/11): SEMI Auto Bury (v0.0.4)
cloudManager.js?4695:199 Loading Mods (8/11): SEMI Auto Run (v1.3.0)
cloudManager.js?4695:199 Loading Mods (9/11): SEMI Auto Collect Stockpiles (v1.1.0)
cloudManager.js?4695:199 Loading Mods (10/11): Ore Respawn Times (v1.7)
cloudManager.js?4695:199 Loading Mods (11/11): SEMI Auto Bonfire (v0.1.0)
cloudManager.js?4695:199 Loading Local Saves...
cloudManager.js?4695:199 Loading Cloud Saves...
cloudManager.js?4695:199 Getting saves from playfab
cloudManager.js?4695:199 Saves retrieved
characterSelect.js?4695:5 Loading character selection
cloudManager.js?4695:294 Connected to PlayFab successfully
main.js?4695:15 Game Loaded
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloud.js?4695:29 Synchronising with Cloud
style.css:1          Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695

### Are you using any mods?

Yes

**Comment by Bella-Giraffety** [comment]
![image](https://user-images.githubusercontent.com/117771104/200658143-75d53fff-261b-4b30-b712-89a602f18275.png)

These are the mods that are in use, but the problem persists with and without mods

**Comment by coolrox95** [comment]
We are not responsible for bugs that are the result of mods. Please report these to the appropriate mod authors. It is also recommended to keep a backup of your save files when using mods in the event that one causes save corruption.
