### ISSUE TITLE
[Bug]: Quick Equip menu: can't remove items i don't have anymore

### ISSUE THREAD

**Issue by mrbuds** [MelvorIdle/melvoridle.github.io#2943]
### Describe the bug

Just upgraded my 4 part non-combat skill sets with `Skilling Outfit Upgrade`, and i didn't remove my previous items from Quick Equip menu.

I don't see a way to do this that wouldn't require save editing or an addon.

### Save Link

https://melvoridle.com/save/bR3m6NFB

### Screenshots

![image](https://user-images.githubusercontent.com/189656/200889141-16d2f94f-8da3-4b07-9ec0-d71df39540ba.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

4695

### Are you using any mods?

Yes

**Comment by HolgerFe** [comment]
Please fix this bug. It's kinda annoying. I'm using the android app. 
Maybe long press the items with a pop up "are you sure to remove this item from quick equip bar" or so.
