### ISSUE TITLE
[Bug]: Unable to launch save on Desktop

### ISSUE THREAD

**Issue by BloodySkittles** [MelvorIdle/melvoridle.github.io#2946]
### Describe the bug

Unable to launch save on Desktop, but works fine on Mobile and IOS, not sure what the issue is I've tried to troubleshoot on Steam by redownloading and deleting folders and verifying game files, Ive tried starting new saves and nothing works. I will launch the game on steam it loads fine, connects to my account and I can even download mods, Once I select a save it loads then nothing... I tried new saves with no mods and still same issue and its only on Desktop.

### Reproduction Steps

Launch game,
Select save,
Game crashes

### Expected behaviour

Fix so I can Idle on PC again :D

### Save Link

H4sIAAAAAAAAA7VdyY4dR3b9F66zCjEPvbN/wcumFiSLBASrJcMtGzAa+nef4UbWK4otamGLZL2sfDnEcIdzz70R+se7/373lzyvdz+/+8tf05WunFtpee8r1yvzd/5JKV1j33+uXPTVGCOV3VMZeV+8mad/uN59xLPydf4k/clf/bnP4vq/43q8PJe1i062mhcvKdfos/FcvWopvKNdu/SBg47vUuOpcbXW9sTRvMqomUcLHcmp82kVHUldhzk1vbrsfPXd19Ixno6e8HDka46iw7kuNGerV3PiXaM1XdKvnnMpOh7XrHVOHeOalvrQI2fHzWPrnWVdLa+tASsY1tHyULM4gHs2HWc2110o6Kq6VTAYtSwfdja+L95ZhzuxU/EMJZwufO/K/Wq6YvlzoetqRELzeG2tPT5HfJ7zKz53PHP7gj18Q2vnc8Tnik/f0HqKzxyfLT5nfMZ1w9f1EK+efd1aft5e+H30nHSuXW79ntGq4bdjLCgcOpgYpKa5aU0neLpxEGvjszN+lrbL0DF6sbYGI7Mnbas9uU0+vPuaFUI/CpvtazdmuLDJGR0ttfOaNnB2Dp/Fz6wxyOhxm34ULhtrSaKnBj1tProXPHSOsXSMn3VNn8cgpTzZ7A75wCVFh/mqM/sQP6ca0inXjXfgsEHG+Jqeqbi7+Ml4Zdp6WNHDpw4L1LRk3ccHjVn05NLQwOwb+7UKx5DH0K7V9MDMsUpTbcpQlZa2+s4TWw3JGIw+dIT/0NKp+zD3xT0fc19VdxVMRaWC8/JtTcfcYMRwlsKdMo+ghS3zSqkL24jpvnbnQab619qWjyH7mAUe4jIMQvI1mR1IPfkXdJ6jyUM8EJ1eXb9RzNcaSc/KHIYEyYL84Yudho4025uHs0BPebAkL5WH6BVnkUe6u1MHB0zQpHTxcF9rFN42MLRjdhkzCMGafOjAJO7so057wpdm6AKNAB9QqSJjQkNxauHCsWgF0VEI2dAR5Qzmj4dF2t812qOu4QvaNXdOPo+XFD5glRAQnMM7Yd8ws7hJn7hBn9R+XorJyhxBnpPI4nPoc1OEax+0xxuj02HEdUgxTbAzPGbnZtUhbOcaOotuVNypq9HT3mXSB80jOoOuY4igXINNgVIkWmlIOn4pah7mNNEu4xAzMcvU941zTEfFJ16N1hRHeIieCWGbgw6DArdh/XC0ZR/QJEpG5VV6Ez4KTTenYv5wwbNhQmRCxghjAesyeWLD7Mnm7L3g2ODTKD98nFouGaJvKvhHIaLKotP4fMr8S/2SUEE0EjuW8+N31UKim3J7/KZL/nRA+ykZhJ3Cb9TCxyuXZFLfUakf3w1V3/Jfg4fyKOer+tAO9QtPmv0GCNMWsz349zCiXR+yGJeMhZpPS+FTvqXEXfEc31v9m694fVc6b/OD/JxiV+j3FLsWv67EG6IhcbkfUX0yfF9ceCCPP6JhfnD2I2s8JJrpdsj+eUaFPjSM8miXJSH/DgaluPpraPT6/euAFspgsy9aYWk5vB73dqyzfJL9VXgwm+p82ZznrjNy5sdd2czbN9ibaMDDQ8irFHsn+wlfb7cis+BB9bvk5mnlw8HijBrX/cbhZrkp6o096dRrql8gH1R9xg7GDpE/6RHpNLp+0oFAaApFptDwh/0v+uj8gI7yK2G61sPhUJ99Q/gIQAR6GN01L6GmYt8RriJ8RA3HJm8l93TckJ1LOCI5KfkxmFpZ/95WeBN7EjsRexA7DzsO+okcjsM+w+7CnsJOwObf9t6m3mbeBj4MuuyxLbGNcJhfWV4bXR5v/oQrGPZ6jcZ2XjKD7Rhc2lrZVllVmVNbUllRWlAZTxnOsJmj2DBP+RR7G7sqOxW7GDuWLquPRtUabtAuMLxfk9exv7G36TZ+1EYZgy0zQ8O4JA10k9L0JWt9lOlV1Y4hOUqZfnf8R39+d93DW/7UH1xP5wiXNZ9737uVxA7M1uGo0/Pmf4sRCeDdhK/pz3DUABQVfeoAXbhqPwPTpCKLsPqGKvfnpUdhKGEPFn0rnpQSkD3xE1AU5uAZAAdPypOa1hfvKiP5P1yFUa/5Geh7+z9chFACgOEZGt0nJJvKv0vpCY2qc0OuaqbAdeId3soH0cfQ9+L3UdWZKozbIGj5efGFaBiBaloNqPp5VN6VqCJ9jl6fS9dtjTYCbW3pOS+3si3qZSu1PDdYOf43KXsDcWt7LlWniADgiDHA6xnjhUuE7wDUVtrleRTdBxvZcgFeSM+lYUx5TOCIuzhFtDw1vwrKN8QDVwFl4qeCNjgCRkeMgGhCac0oirQHMiGUbMo1xZnKSaWkMkL6f0AQ/LOi4L/KgKcIrvNkuEhfmdI60vuNK2iZ//gK2vTvXLG/d0X7bjv6d9vRv/uM8d2W0h1854r5vSuISv/4Cn73egV1tra316xJiJL7gQzXN66ga/7jK+iFv3NF/94V47vPGN9/xv7eFbN+94rxeAXtorzluQgomc6/04akGw194xKi1u9dMr97CZHH6yXQMZJMrcuOENkMBsQTMSqcBiwKrOomU1CJXnCb4jhEEK1v4mjgkgWXs2CsJyJFhouALcMRAWN/PbZ0PJCQiLBjzkIAisaIlRiJXFFtlcQEHzgopxs4BeajTICDLNRe1oYdQzDBiApxP4xkWBw4zTb7FNJfsGxij/jSilYQwawyYeDgn4GHYGZKhWndcXNNeREw9t4KGg/QnWoq06aun/YTxM8txkZ0zSADtDgehVoCm+voZIt9yfBJjyaxiHtDfzGgVNPaIbwc2ca4HwHdMH0j/ixD5uiY3LWSd167ozntOq2pECzyBmsmfAkwwjALF8KPMOovm0E6LNdiNDP3IHEBz8r5QtfJ3SDaVExa0dlVCtUYqOU8PnX4gkWmrRLiwt0megXMBA1ZBz5kKyfdKb5FM4hjyNBg8uDT8ODNaFRDNarBfom/X4GGr0+8+YpotD1ewxDo/H08t6+8v/GI0s5HjpgO4zM4F5n8E519gVcjiZUgW+RrFkC9eonxKWU8tKQ3vzWak42uv2ozHHXVQd1/hJvgTVsSQNKsQ4EAI4u8QFNngDHa3Fk8VUH8UaskA9o4eEtlPAEF4bTUhaaKZwOkLYnwupbOyJp8qS/9pz/SyjIZMwFPwWw3AOlqgJil7RKI1leCeYK0LcYZfD7aB9EnoVvqpLBmsmE0fXMsoA4EkXhg1++pAE9da3WKPnW4t2cyvjDhsBTP4rVhHsp+DszVxIuhRYvMdc7kO4Dk81IUA+0Aju0wNo2GFZZrKezDBLZBHJwxmRNNqTCHsFqZdF+lEgMxIRppzz2AHDEK4fKuCyYpPzNuQ5RUGe9h+Ar5NKgP1ZBThIijD0JS/DcWPsnBbRJPG+BtMOiJ6U0Nbeskw+5TBRJBXE7Z0iUMopeUN/OZryd5vsFATN+YzXb8/k+bzgG09Va2MjvNngm1kSUr0TOEE/PCIDJAqiTwKqw2IygGYzJO3Zz7/dZMc50hf+Vr/cqKeaxgdAUkZXRHe22vKKwlyd3nqRBRcq89azrUdmDY7XHC2O8qaj4p9r7jCIwl5hID+Mzh3wLlTFdQ7iD2sJDMCEBN0PU3rUyL7qxKc2tN/XGYIKFWcCnTff4P9Pb/5Q/7txnmTfx7lsnuZbjzve12WgYjBfmDG4FiLVlwGCWEIVIKmGoOIX7vsP1Q0UESE55w8apNq61YoxLPTIY/fmiHV5OEQ93giCmSJv/hW84QFhgCeuRBb0q3Gn4iZgwT0z19MF7QfooCbVevvzfu8KOrH//8DbsIRS7U6q/uGgvRUwwElAsC3l6nCU66MnrypXDNJd8uA5CXGJ6KTk8G376S1aUCtzf6VzhvOoJNOgEmuCudNReJdgxP32QcaVon3fD9UpgGyJUGkqYH8s9UGl9TaCb2fCYPyJ62uaQ88P6wGcAhedhpPkgA7mOs8wtCnXf/eP/u7//+408/vX/3l329f/fh068//vIzfvn5v376Cb//+uPfPv/91w9/+w+cesg0pvrbu+vdX9+/+zQ/f8kv++NT+fjh4xMm5PPThy8f5xM0/WW8fGztpX54/w4PmsCCn156eXoZ89MTYtjy9GHt9QRzPtdLHZ/T/qILP7VPX77UhWvy5/rUvowPTx/L5/70kj6+vMzx8mHPF10I9frCqOuJlv8JkfiXJ4THn5/S5/15vqzPBF268GPdqXzcX56+vHzEhZ/KeILr+Pj0eX56Ge0T5qBOXUgsBnuQnr5Agp/gYF6eGNc+vQBqfv4A2Jc+r/fvfkDPMWr/8dOHX7/88p9/w8C8f/cvP7/85y8/vvzLy9/fv+PIvH/3rz/98svL//zbv//4668/fcZZnfzv/AyTol/ERdJgk4Yhi7NkF2S0iliVJkJliI8VnqAyZL39NzchvWeKl5Tin//3A/qZeR8NHlk+f37zH68tegdV9PXfD7+5A0ee+Jtp6T/8+8Njq9PeSkOuzDTTa7NIDyoblaayrVlJzYer1CAmPB/OVZ5TVjUppCRaBShUvvThsubLthOvOTlB+nBB9wVTCdOH84PneTDPwToH+xzk5Jsxj7KRiuRoyDKRn5KnTJwyBfvYZ3V6KWzaatRSVvfxknK/Qv0ktfH4dfOAjDcn1RM8TTj6zTcjvhlK1D1+c3cu373L6h6s5JsZUE8dkbyezJ5W5qhSGs7cMXS/9n7TnWKJAnq/z/72Dtbo0wtP01lr5Ig08Vd5m+uV7nu1w0N/mRu/GF0+sovf/jfj5lsiyQs7OwBkBQhEdVRqfzrDMEWdF3ySNq/4kp9kf5V2cmKfNKsyAusSzXAR3tNfwloKYnVl6KDTW+UDQ7CyivQFHlrTMH+nyDKonEACczlDKmYeN1a/pA1/BhlOfSyMgxNZcCoVjhjsySedMWrMQ97j9/ux7M3XkW75c4PpTJASAFFCcI1DSXBsxj1x/Bjdzy9MYbVvu2KBO3YiHObyzaXcLe2Ej0rbdbEBLAGYLFFhgI6YAU4laViU6IwShMSBQff2UlaZ/AGggvpIoMGnEeBnmmC45TKUcQNWc8YEMfIoYv47/CoTFK0CyTemspkVL02ZAEFPBiFA7v15ZPOmTOcwdzFLcTiI5mxJDiKpydwHAHAjRlVzGkl18yAXiemlSpplj4BuAS4P4SiitMqEyyx4iyoe8My2xdYDlWp6WGwh4VqO3En0r7XnEm+BmCpp8oCmEgMvpliBeCtzNwDgylbVzTZhZBC+KvlNq/YqNYpGAYTTUu6jNcSQqTNxgCFeYis493NutnUBaCUYPxY7YFRn1jsLSRzFVwzhFy3zZi6WlSJOGrbqOqJSlXNSPsZwELNPi3n1UbfKDzoGbxGZM22iyIclN6wbgoAspiYwNhgBZjBqUmAubYOnd6oW4Mk1CqXCNnWNI+ausP2FpJL6hEgkrTpO+oqFHhoARDz+trPoiPKFp5IyZ9NE7TGh3lOybLZZixVo8AGNQ+kClJGbpgTtaKLB2IGiXDhiSQNFp1LZSPFomOOcnTRrBICyYy0sVhrKpPGzKZsJqWHvFV+ePA4TEkutIFvBhBQmRYZwddoy1fog5p6UEMDXRIaNEcMsUsqC/pfBMJ8YeTQW/1DyEcunbnVLogvYEl6pGhO4FuXPMG9Mr1wRhbYlGwuJbKSXaFQLVJ4y2MgzQCZTshVkxA2FuKIUCe0qjFE5AIsRufO0bCB9kc5n5T3QQVpa/cw6z0oy/mACCwEfkQjHWlQN66E43ZCgxqScSs9gf5WIK7psM6zyaDKflknV0x4fIGcod/FylpZEW5x1pdIW/5xuPKKAGhlip0WLUoa3kGJ0uvvMyji+dI6ubLLKmpyrFpPJMdhXV3UKBGYo/EfYpZI9tc0J3iUN00dVCVfZOcarF5cDKMtLKDp3pNlLT+5yNX6VpdeblLxVdRFTX6Q65ec6bcDamrzOzvImZaS37tjOUMr8D/kz5/j34tf82Xa8snlIyRdrvNN5aZNtdMkTRwDmfAsAS2IQhw9RbPTDTTwBXGgXfe92hQch60ibgzYlIXEGfnLSUp7i2gPNwvQwZMZuWcUyo3vwqjw6f5JepBg0zzyVPuunjAu/WPGFqhjWllZR+7slsao+oB5zBGEbMv3fvKXE25feLg1FCIovqu+QqSm9XabYLhL1fpRsl0ab2sve8vxUFUnvyvEPJrG75ZEJSv4oLiusvhxRvyroarVMiciylqkcjU8oVJpi+0YwofIEjIJKA8gUU9u3iygrxR9CWEmDqSrTZBRkpDnrH5odZSGapuy+MivOiVV5ZPEgM91LqZdvgnTTnobdzMN1lTVHOyByMwat2BRQ/xeLI2poSC6SjKLeFiV6qpvUAgDqm0ZJIism3aG8lFruBo8enbCMcWKoGtIb1qRNt2+rKKRJGYfoEZUyYYqa60iycJw+JJVz5MsjUeeUfhQ5ZDHIfuU2YyNVY/lNHrp1RoMk93iEvp1w9frW8w8FMKQNVdqCYUwRW5yMopdsZiYpJLRxBk7Wb6u5LIbYfmPdxh8cl8IEX5sxA91FLfpC+R4VqEp+YhydV1CFjuSWrHWusjF4Z2oalOHxEHSvTNSQQ67APXSmIad9G9+zAJVWx2eLJGxXaRqlphuOD1nRRvBEuW9dxkcfWUpA2eMje6h/EXJVJc1UGeK6ZelyFo0WzIy4BWY1F4/OZuFgAp+v7IpQWuhvZ9Ejp6N5OrZSgSNMalICsQbVAKetqZT06QJWIrjeaq0y7Df3zARYmbB0sM4yfNeaRM5ktOe22ODdRWIVfVQIdSSjY9JLckGUNEO5wRpsbUmSG2ae9SVDf2b69B3zJ0l1U3IbSakL1q1o0ostYhNHLBO/gUr4FbDCCk0ClMgWWyhgojE5tpPkdNa8UECAntjIHs4isRSaQemyj6o0W3tMU9K6hNw5J35qQnGHHTZrWqtLwanqs+2qCu9zQnBr9pC1S2Vxhb5PuQOLgovcmIC4hkxxDpefthQ0jRZm3jZjn9ARYM4ooqguqCyFjtTxFHMjuyOPvwW1LdxHImXhCaJfLVXq7dVSrX9iwljqqSniN62qHlNRE1T7m7dA+NPjF3vFF1VEwIhvmHJUyVuYga2YWxEBZKUG7FIh4oRvwI1AjsI7QxW7ssd3MzWSK/z4Ou1oLrdC1+hOhP8lidGFwprtPg7auaENoNUMaJW636QYbzMNHR2431tiwmBp5H2qqufgZunA0/EM+TiAo/51FilxiMXuktgik8ZQM3kdhArspiBwdnBOgLBV108MVro6PeSjY1i2CG/fSjJ279uPMQvXRbNPeyUWwZC2C6QlqZEtHtMPgEYrC3cJiEwHUGmsLsyZK4MxZruYOOQTuqO/yRLkXd8MlhCVlhoo1vP0N1L6W3i8SMtk7DmbAbZepyWrlupyOapFmt06nmJYdBj/LGNnydDYqrKcifd0VaIHCG7bFZyqUuRPlvl5KpuKcAVo6HXIntq37WED1+w3YURZLJ4Naeidu22LMtxH3FVNqiCBJ2egr/BEU92FNbIZUDGnvA8X3NAVLJkS+GYhYYab0gHLlYopqJiq5QRU01jxI3wlJkrVn2nLxeRNNil5NYVCjzC8rCon2ju2jKXYCsTdLNGZeXvqpk3QMBMRFapDy4qaYguPr6L94jEkoivHOmcWMOpjkS0UkRrodgjdDqHbWVjjWGPOo7ZYHEsNnJKicriYBwoLy4wXvlARkVLhI6kE17eUKTK+7QAIBE0RoJ0poRrsGmJKXa29n7pnaT1D2WJfcWSRy53Ola2eEFxBzBiTNqU16UPuSyHaSMf4DhLMt8VEID1Or+hcd1hsrYbw8xXZCS5pdcawwDcVu5Je0oOEZ/rmvOx2P53LOs57GQr0APeL9aQctDEdPZnm6PX23cmOvXlQSyqqpE8hRSqPhPOpTAe3ED35TkEmyXi3p9xiRrkog3WXxTThEPHZ+MKqOmfFAqQEGE/Y77lOWqiTP1e4OJlGc29zeF0GH7iVUkbfhVKXCiKsY+J2igKgKY/tO1bYELnrHJ2gz5G+a83AoDA1Ncz95vKH0J/CyLdrHQqNz5rTQL1yFVmAYC2zEgRT2EDXKNfqdUfCCrPLJArmPRgPyThDmhosibW6BL6Ie1hHKl/WWSrECem0aQS1hoqa+9Vd352ZLmDMwZU7Kccov3ksg1xnvk0fVlV9F8z73c6gLLKWanSPcPMau4ird1Vh9iiq8oFAt2pwt0gZ0cphDEfM5rH3RZx3RBxCuP6gUmAiqWWzBHJi0GQ/6+VuS9QEc5sm7yYD4eKxVpm9neHkOo74uop9NW8z7qN9H0WIXRT56UN4AqFtUrm+Cbel6v7mo+pFXhzUOQ6s79tF/qbGe9XlPCBUCzyVXegXXHZLD70oId0rmYW3jeA8Bbj1ggN90LX0pptHG7KBHi8oKMllt61epxjf49+8BKeN5fh/Se7CLXh1SVjkNxioBv7PutcsHJ35crmTFzo1USb8uUUo8TatAWBdhY2cER0/BHtreWh/Cfdc3PmZmkNGsYwRg8VSC9boIbSZzZDa6g7Daqr2COZotamoXqNHDt4EjmiCPZXlC3KlNpXeVwNoDHemqs2I77xeQxjnvMK3da9FlHOHi01yg+HpDOkkxAjLFxP9LZwtmxSIogRRpYN+FILNollS+alW2AlNkm02dqi+ifPVmmTB9aMplIYVdi7uNPxcYd6Xy3hwmax/PQGogmqJKxE7q9yS85uaNmUSuP4tiFmmTcQYpMdYxrajKcQfNWKEqiTEEtslRqVlMdOsghUW28sshnpaWW6iV2eLL5xAkgH2wRhngORD9SHYKxo1OLfspUVckUL9Ek04bp5IUznENyLiUOc0k13d04dAYZefXWHXk9WO61lp85OKca0TTZ7XAb6K9LXARlrc9TZ9aNWM1HUEabSr4wnbqlmE2GeIclVMmQ4MEs9mCheBpGQmzfBg6qzCyG0apQTPrswstLs9xibXAUo2QrZBiSi33oTcLe0spWGexlKkJbHKqLEGlzRX2FStZLozeEPwT6Q8i3xun86MOg3TkRmtYFJChmVzseLGZENKJ4JLLhKTM97ZkVVTyU3oZhHJqWhwaG2QzNHgOsEAlvngob6EIKQenKEaC88aqaboyl6hzZRMJYFikNuJSQTZ4wpB0Hm4EZnGS3kVllYdnu6AvcFc0AG2NzgkqDgR5jwA2Cue3DiKYAs1XscmM/Bo7quyY8Ez5nXDVa7iDUHIsdxNNXUE2ksLphqLIbX0OyiKTT8XA1Sp59MDNAihyxnaLLaEhkk5lMxiMGa8tISqKTTJxJvUnFEdXaOFYSpMtZlAH9fwi7X6s0yHInCTWZDJTCUM53wUcK380pvH5noZjxLkl6Xgtq91bY5+WS2QCyvSrOSC7I7ClItZNfAMC0m3mzhqOeGmMHIJmr3taeA9IyHWuml8RyVHmIXWWoARBVpQr3mEoJgf4Bp2w0+FfjKpySvt7LRdAcnFTHYT8XcE39Aj4OQyCIFD7WqgKCHw1dz+BiiK43T4vy3HSmVQS67DT9A1qo3Tlmp1rQC0I9vhypwBH7hVtKBWdmv6tP45cCLL9Y+xPVPNyU+ejU3NS4HPydLStOrGMRQXSkr6iFspXSPkk5Y6+ZVrEii1kJjZyQWGjvTDDhFx9l1Dl1mEW0IEj5IINO2QkuY6DJsMAmkvchAc2HnT3silPNIRhYk8rYbUI7x2PqCq6hKaomWt2NTvReEi83VBgR+qiu+xbThTy/gr8oc3EiNF/BVWszEVqpYjoas43ZBlNKvgZJfJ6nQnWLUEE3D7FtZD0SmZXeLtCo4UpxWt91Dtyk0kwHYvLyJ5jXHhwse4Jb4IQH3rOxY85nTz3I/fSioyZqdi8l6D5xpU92UipY3gwFXssJO33ZA2ExcxsVyDZMvKHy4tl2OJaxNgaHLVtdzhfxY2ZITf6nSUP7mMEhFI78oOjyoX1rR6qBP2scHyzVlFSWz7zY8yDbbPam4RkicJM291E0VUA1KWLG3Th6ANNIc0fvDzQuBKqJHEJ44kISmj0cSY6SPNYKx0yosT7KpTl5+ewWoLIlj23SyNy+V8xfQS3RRMSBLiEl54QO01MOZMVcQsPw28uOIsOaG57g5L7JrDFi5wWSrKUlto6+DkoWmV1bdvNG173UkMrIKIbA3Wg7p50hIMMeZI6Sguz7HOqfxH3rpJozO3M+kqN3xl9xNwZNISZcedorVO4sk0mEiXmbzEVm5IYUS+SeKbxVqmhvwoRs7lZiFkBwRy0n7VIwoU8WIZr2xO6+WWHaUCPJRq9X0D80YsVluuNTPs1iMhqcnL3qvhKRef1EgFzOhOaYexpprShJ0mIcIvCt0C6Sr4E2jRfjfpa0GeHL59ENPx2s0Lwo42qeoAgypMg0FoNHcTssTVXFqQ3G5IV6dqcQJKeXl8U5Yua0nYgVMKCuXuaZ16Cq852QitQOKCpvnG4AqClQMz7IfliB0vKI/THgWQxTACOl3rsKFCqR1WPbGBRdAwRWDHihy+m59cuX0TpuFhJys63oygs61MGrUU2LEfdLCpaS0dluJcvlSJn/PJtNrg98txKhflfd1ncdHZ8NVbtYz86FBa/joBwuz126FjAVzSannNyhLGn6oB4E8RG2/BDfAZMbFKe2RRWS920Zpq2cnZ7mIKB3HhScRdtvVqR1NENNohb1Z+SL07NZDMDx0n2sI+EEy6w2SbA2yw3iant/mLbHL7zTmunq/B6Eu39YDOMq2e8o3FWoDFsEabbKdMtQjR7m0lVNFFUmqLI+HqcpZkMSHFLrBrJkmjfqa4SEu71WjVOVWHaz+ErJULkgTtU4SiJgseNxYLzfQmPZ1dz6J9DIJ7LKqqKgJVk0kaErKWPN0iRqloDyWaubdhTubCyCt0U7tkCI9VhcKRyvebS9g7hzimavxblIoUU5yZZS019ltgxUGKytaQwxV6zVoHunuWGMXzavZK5OhxPUBGwCelt9yjHHJKQZd5EXioVtwmkicfZArT6t8jlUvTZ//ZVCamlep73nZTxeyuJT50nGoLNf6F+5WRbmElB1mpkSh0fQcZSfYtZmHdwCFre4visRKhYssxvNvIti/0ql2yLf6yuTrHRVo1iizSmkFaKoWojxQJlypBrWI5EIEqbouCLC7l3BH3IkTj9j9BC6wlxKYPSsuuq2gtVQSfzfWLUhFMqZaGijLSFgi6RL1YUXAzaotLhsJQoxJBXH0QRmGiWbJ9XGXtLiKqTcU3iHim8tXah6MG41Ecw29nhkk9mtMyXcbrwofLbvVs8elD1EjEc97dRR9Ce+gz3SUgPovg8q2IyZooWSnVMOhY6aXn66NoxRGHpAZryB0VBPBGoPlUCqG9m9ZVY9kNb7kkkZFNCCl9bHoFTRI251otAen2nbKY7VVcEc0pO3gwonZXcGAnLY0IabJam0k7K7yJdvVQNTgj2NsuaqMr3GtTVSDlsFplqC6nHy6+tdOePcIVCn4ezd3DY7ZV1qqzXMUXBE1nycfegeCKtrp6NSLL6t3ZthJpi6FKymY11g5o+/AsXAt3EPY8Vof7ruxwllkxQc/3sCEsYlqi7NfOVbNGsTehUiiZq1qXdrOxZbrpIO1toyauFtV7akeur0lasrG5vfl9PMRSeHi7ESf5rlCIO4HeH1ILQWU9lFQINLeH66sQTpVzaurwUIWJOZwdDE3etsaR5aBluaL+ndtfrTeWdEYF2ONr5NFaoW/dIm8psV3vUT6gBYYS9S1QElyfrLoyuEzQRfD7moZmyNxOmHsX4moQTrWhRj9y6Ig83mAfFkq/RrWdSl+jlHIHarcmj6Mo3CTgfqxSEjIk8bIdJ5tTBqGFTMrNctLujTGDXegyVNeHQvYyhsKv8VWJST0wQ0xr1Mg6Ou6lv8ouVbY8fqmcgIVPXz4kpaEL82AeQbXwjkKp+VbXG30dc3Vn20rVBi0m3DilNabn8BndGxM8xFtcdc21OeOtXHYv1/F6F8h65QaShEycJG56pOBba3ceCa8o9A/1n5H+yo+n+ten9rIl0tZ5p+SP4liDrCKSrSe7pLULxIemCbLKziWghS7rFPTlqJuc2gMvOQVShB55B2Ia9WAEuCWdfWkPRgLg7Uu95EPiiUElwFY5mFip5aUUW1pShAa5H6eUgMBIYNEeQktDtE8bb3eyCtKofQjzkNwx6iUcad79oGm5gSSwD5Zd1MsEinbsUsDUY5sDUQgsxXSZsIv2rhHdnN4ZjQX9nP6qstUy9JqhzR+k1lNVykUa0aKZMmgAEd5J0ctwqraCpEQ1obIeGw7GnKl9VX4tqwLKS0i0d+FSxKHiBKV+q4rhdItLqoFziHRYBay76jJ6Eq/CGpWp0Kuo6mrsWKEjiI5oRYO5tRifq5F4DzfHnFJAPs08ThmGnyqx0cgp+aJuqBcsjjwDPZ2VOtvNyVxqbxHVJTgFp+rHoTKgrMiOw2yzucTkzViGIjB3jXi4N5QbrITnCiDeTg/mJD27kL2l2iXOaJQYKIWoa0y5Bm6UJdvQl8tntAoj1ks4auEvR0WYV9XwZPLELunKpoqSS/pV4dFfNYrqIauu/HAPSVleaCLE5UH1DWpgqwIlW/AJyEhueGkNFeChBiK5nxbU5tBR9xYrgmR5aaF/KwFJt/jWHAuLhGP41QydyN68oFftdzRLWGaHbEnoJWsTXNVKT3Gtc55xoTOQXGoXOIf1nm21aNgmtlAoDUii+5fz5CDp7YU5a630Yu9cnaxuqzDSG9MWm6cUjpaJAwuZMgBe0KzrFXFU1TNwPw9JYdnaLU6Rmsc1K9Ljrqj5oXGMgVR6o3X9VeY2x1IuN2pSA+cZdtOFdWkvOy+7b5OIvIlHmEHIFJuOJI41NF2mE8Ekw3DmuiRe+H11ezox2cIEVaV9pWpvH2luWCxCu+JyAGN4bQRYr4M0g14PO6E9FCf3gxCtp4Ec3libSYumPWHL5T1UFTKcTnq7v4jtOXJus2GMtmQojIKLNiiVXLgOum7tQ9tt9LzSpkiAk/Gu1jhCtnqMZxRZ0s1Xm1yvyKl6vlWoihHKS4SIdiaJCRzejHKJcOteUqRK0e4ljRwQGwiMhUypirs8okMkZRvTxrduheGVYd1U6oVSNrUuJBflfoZ3nFRl1DAfy/d4jUHbYhOGdu+jaJJdJcDWBnXKsGhm6UB7aId31Y0dMLRWq8myTTtVTffimqKmYILlTxpuj7h4RG/FvJdfurwv7FiiGqpzN/IF1Ofj5Jb2+62OwtssWrEldohodQwVRtWscpdpC6DK29Nv7q8jo5a7dnFkH+2RyIYyHSvhb9rV+lrD5APN0Gl68nZFEJo2YoBdfjmSaw/qUP5ir2niUYEWwV6NqS9ipgGIZGC4HE/ik7RdFuaySyGbaq2Tqe2sqvGAM9u6IDepnTkQSRVDMSe+0lzaa7NkZdzJxK70agOrGQnXf65j/uTvHcTIzvtlTbnYbT6tpLWbuNhetdXXQGCiuJa1b1qL25S00m35+JcVZjmZmNiDazTIwWkHztyXV+8kyauAC8VcC9DKGfTtSLdUSdTyujLMN0A77WZW9rsl7Qda8vLIk38oIa9VklO2qJMG0dxa4zo0gNwRxNmQKKUdLh5kSHt6If2cGmBudSZzLchpgeomwYvLOKp3p7LtFKvNTSjlNIxCx5gqOAdukiugNVM1FF9LYHXQa6TSlGs4O+GurA3naXwJNzSKkb67Stxnyahol9aN1x5FrHt6b9OelkixZIgnUkNF2reQJmPzZFCszCHVM4BPUlaNSjOjwk8L4fIB3RJx76oezs2ue64s5ykNrcV7uKqASGDJdPtSb6v5o3hj1d7X0imtqtM7A2EtWT/NDYZ7dG0627RfDDc/tLfeVQu4xTby0nI8hnfyguI3C6BbvXo0e3prbocaLmXjLfVGwU5W2RU2V58sZtx481YRdZ5GQtvTq7X/IdiUhr2b5Wk52baKism5RMdb1A4lMZlyEpw8mFUxoYCiciXJNUot1noug9ZjtxQ9e9VJ0kJfbV975UhBa93IfWVRcZy31m4q9fV+u6pfM4/mAGVg0BY9X5ZrpY4DkquujQtZs4fUXnlyo7Cm7DMsN6sDLc64DCbKm0x073YFhzNVfExCUtiHG+mNbQedlZvNMN1rS22zsSXiraXka3VwlQS0srIebXk3QoSBXj50xT52VSW2e0GK6jYZBoOe7VjMWg6RCV5uzoWuKZ6dRDwPVzOUqF7xTuwtuBqtQNGGGtoNCoZJ2wxpxbNgBSMcz7qNVWJZguKhSXfH3/ulPT646P/OLuRy+Joc/xsM/Xvc64OObTJHr7BNW/0rGDcl8XZ3i3tn9ZT+5O4W5+dXW4W8bpvhyP8pv33+6xYbGvu4TtsSXl7arq0+ruDy3TmzBJfKM7xPR/6/70rtl//vLVSr1WKKtP4L/ktLKuSIZLSyv9b4d4dFCs9YCi8bqKVAyfr9Zrt56eFXTf1zf059pha7vZ6g1/Rv/r1M/87XOmeSfKKrgPzcFicF1jUF1cbXO9/Fo3bs9uItYFT95W9gmfU/gSkuN56Kf4s25hdSUrCjNS2OcxxcXFr8nq3Wl4khRfNlOq1orkAaaztwIBOzE+ImBVSqZ3VFsHZFkT6N6jTB1i//X3aC4RL23Q7AaPR6CNYKY6gMR8hjtqWUQwsBU51D0XYqzQk0LXmpnsJY1WLSbXhPdual5QCFMdjkLgxCWq2aufH/KkBBgBg79d+V4lfs+K+NGQTNn1REFuv3PJlPkXlzPvfKR85LnODm7iogcO1P1CLq+sM7puDxBIkE8Hykugv9X0na/bh9f2/2IGtziv76PNPsuOGH3/4XXYNHQaxpAAA=

### Console output

It wont show anything when I press f12

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

Cant see it because I cant launch any saves on Desktop, Mobile says ?4695

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This save works perfectly fine for me on Desktop.

Can you please post the error log you see, and also confirm you are not running any mods.
