### ISSUE TITLE
[Bug]: <some kind of error>

### ISSUE THREAD

**Issue by coolchris366** [MelvorIdle/melvoridle.github.io#2947]
### Describe the bug

Some kind of error when trying to start thieving

### Save Link

https://melvoridle.com/save/gAKGEdpo

### Console output

An error occurred while processing ticks:
Active Action: melvorD:Thieving
Error Name: TypeError
Error Message: undefined is not an object (evaluating 'number.toFixed')
Stack Trace:
convert@blob:https://ios.melvoridle.com/50661294-e845-488e-96cf-f91d6275585c:132:36
getModifiers@blob:https://ios.melvoridle.com/50661294-e845-488e-96cf-f91d6275585c:91:22
@blob:https://ios.melvoridle.com/81090858-0278-4c71-a4c0-b5833564a750:60:70
forEach@[native code]
refresh@blob:https://ios.melvoridle.com/81090858-0278-4c71-a4c0-b5833564a750:58:26
@https://ios.melvoridle.com/assets/js/built/mod.js?4695:762:56
computeAllStats@https://ios.melvoridle.com/assets/js/built/character.js?4695:81:65
computeAllStats@https://ios.melvoridle.com/assets/js/built/player.js?4695:55:187
computeProvidedStats@https://ios.melvoridle.com/assets/js/built/potionManager.js?4695:28:40
removePotion@https://ios.melvoridle.com/assets/js/built/potionManager.js?4695:16:67
@https://ios.melvoridle.com/assets/js/built/potionManager.js?4695:20:23
forEach@[native code]
consumeCharges@https://ios.melvoridle.com/assets/js/built/potionManager.js?4695:18:49
processEvent@https://ios.melvoridle.com/assets/js/built/game.js?4695:340:118
actionRewards@https://ios.melvoridle.com/assets/js/built/thieving2.js?4695:132:23
addActionRewards@https://ios.melvoridle.com/assets/js/built/skill.js?4695:284:38
action@https://ios.melvoridle.com/assets/js/built/skill.js?4695:282:68
tick@https://ios.melvoridle.com/assets/js/built/combatManager.js?4695:254:95
activeTick@https://ios.melvoridle.com/assets/js/built/skill.js?4695:271:35
activeTick@https://ios.melvoridle.com/assets/js/built/thieving2.js?4695:30:52
tick@https://ios.melvoridle.com/assets/js/built/game.js?4695:167:133
runTicks@https://ios.melvoridle.com/assets/js/built/game.js?4695:164:100
processTime@https://ios.melvoridle.com/assets/js/built/game.js?4695:163:14
loop@https://ios.melvoridle.com/assets/js/built/game.js?4695:184:61
loop@[native code]
Current Equipment:
Helmet: melvorF:Chapeau_Noir
Platebody: melvorF:Star_Gazing_Body
Platelegs: melvorTotH:Thieving_Shorts
Boots: melvorF:Boots_Of_Stealth
Weapon: melvorTotH:Grappling_Hook
Shield: melvorF:Fine_Coinpurse
Amulet: melvorF:Jeweled_Necklace
Ring: melvorD:Ancient_Ring_Of_Mastery
Gloves: melvorF:Thieving_Gloves
Cape: melvorTotH:Superior_Thieving_Skillcape
Passive: melvorD:Aorpheats_Signet_Ring
Summon1: melvorF:Summoning_Familiar_Leprechaun
Summon2: melvorF:Summoning_Familiar_Monkey
Consumable: melvorF:Thiefs_Moneysack

Action Information:
function getErrorLog(){return `Is Active: ${this.isActive}\n`;}
  Selected Area: melvorF:FARMERS_MARKET
  Selected NPC: melvorF:BOB_THE_FARMER
  Stun State: 0
Modding Enabled. Loaded mods:
Dev
SEMI Core
Restore Speedruns
Township Breakdown
SEMI Auto Master
QuickShards
SEMI Auto Loot
SEMI Auto Eat
SEMI Drop Chances
SEMI Auto Run
Quick Item/Bank Wiki
FX Fast Mode
XP Multiplier
Item Dashboard (MIID)
Buffed Speedrun
Shop Item Owned Indicator
SEMI Auto Farming
Unlimited Offline
SEMI Auto Mine
Hide Notifications
Save Game Converter
Snipeshot
Melvor Modifiers Exposed
Unlock Gamemodes
Mastery Pool Can Overflow
ETA
Show Skill Modifiers
Forgot My Hat
Add Items
Item Uses

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
The error trace provided shows this bug has been caused by a Mod. Please contact the mod developer for a fix.
