### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by frh-hh** [MelvorIdle/melvoridle.github.io#2949]
### Describe the bug

药水精通提高后无法完成城镇简单任务
![image](https://user-images.githubusercontent.com/82444924/201056766-57495aec-ca1f-40a6-8c09-14fbbe7ff6d2.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [x] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695

### Are you using any mods?

No

**Comment by ZachKatelyn** [comment]
You can use the herblore potion to get T1 potions this will allow you to finish the task.
(tried google translate to help)您可以使用herblore 药水获得T1 药水，这将使您能够完成任务。
https://gyazo.com/e89be6f28faad762f7b65435ecb8927d
