### ISSUE TITLE
[Bug]: <Unable To Start Any Skills Or Combat After Golbin Raid>

### ISSUE THREAD

**Issue by SamSortaSucks** [MelvorIdle/melvoridle.github.io#2950]
### Describe the bug

After completing a round of Goblin Raid I am no longer able to start any idle skills or combat. The image below  shows the prompt when attempting to switch armor sets but also clearly shows I am not in a goblin raid.

<img width="577" alt="err1" src="https://user-images.githubusercontent.com/11732021/201182050-433b28f7-a91d-4fac-af8b-a20df6f561b1.PNG">

The same is true for all other idle skills and combat. The only thing I can do is make another Goblin Raid attempt. Similar issues have been reported but the tickets are all closed and none of the fixes have worked. 

### Expected behaviour

After completing a Goblin Raid attempt I should be able to resume the game as normal.

### Save Link

https://melvoridle.com/save/eCubdndh

### Screenshots

<img width="577" alt="err1" src="https://user-images.githubusercontent.com/11732021/201183057-bf05f32f-ea95-402d-9e2b-e013757289c2.PNG">

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was fixed as of V1.1.2
