### ISSUE TITLE
[Bug]: Tutorial Unexpectedly Ends if Save is Loaded

### ISSUE THREAD

**Issue by Sederien** [MelvorIdle/melvoridle.github.io#2952]
### Describe the bug

In attempting to see if Adventure Mode could be completed without using melee, I spent a bit of time mining resources while the tutorial unlocked Mining/Smithing etc. and found that, each time I switched devices or otherwise loaded a save on the same device, I would end up with the Tutorial Island no longer available as if the skip tutorial option was clicked.

### Reproduction Steps

Start adventure mode with tutorial. On any gather step, just idle for a bit and then close the program/app. Load your cloud save on another device or, in some reproductions, load the local save again. The tutorial will have closed and skills will be locked out. Or in one non-reproducible instance loading a local save while fishing when the bank filled up, the skills did not re-lock and the next unlockable skill now cost 10,000,000 GP.

Note: the following mods were enabled at the time (Shop Owned Indicator, Items Used, and Show Skill Modifiers) none of which should have disrupted normal play/progress as they are informational additions only.

### Expected behaviour

Tutorial Island save state is retained.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695

### Are you using any mods?

Yes

**Comment by ScottyWired** [comment]
I've also experienced this and tested it. Happens with mods disabled too.

**Comment by coolrox95** [comment]
Issue was fixed as of v1.1.1 (?4999).
