### ISSUE TITLE
[Bug]: Missing some logs in the firemaking tab

### ISSUE THREAD

**Issue by kcinnad** [MelvorIdle/melvoridle.github.io#2953]
### Describe the bug

Missing some logs in the firemaking tab

### Reproduction Steps

It does it everywhere, on every platforms, whether it's a new char or an old one
I can't lvl up the skill at all as i'm missing normal logs ... 

### Save Link

https://melvoridle.com/save/knea9VAJ

### Screenshots

![image](https://user-images.githubusercontent.com/964087/201260487-2fbad279-bb05-4e4d-ab8f-7ffb3477b505.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [x] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695

### Are you using any mods?

Yes

**Comment by kcinnad** [comment]
Turns out the logs will appear in the firemaking tab if I cut the related tree in Woodcutting

**Comment by Pyrrhic76** [comment]
bruh

**Comment by MelvorIdle** [comment]
Only logs that appear in your Bank will display in FM.
