### ISSUE TITLE
[Bug]: Mining Gloves interaction with the new Gem Veins.

### ISSUE THREAD

**Issue by Pyrrhic76** [MelvorIdle/melvoridle.github.io#2955]
### Describe the bug

Preface: Not sure if it's a bug.

We have gem gloves in order to get gems at a steady rate while mining other ores. They are fairly expensive.
The new Gem Veins act as a regular ore node and regular mining gloves allow you to double the production of gems for much cheaper. I'm not sure if this is supposed to happen, but it seems maybe it was overlooked. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
I believe this was hotfixed quite some time ago.
