### ISSUE TITLE
[Bug]: Unable to complete potion task in township

### ISSUE THREAD

**Issue by PranavSuby** [MelvorIdle/melvoridle.github.io#2956]
### Describe the bug

After leveling up my controlled heat potion mastery, I realized I used my controlled heat level one potions already, so I’m permanently unable to complete the potion township task which needs 25 level one controlled heat potions.

### Reproduction Steps

1. Level up controlled heat potions past level 1
2. Use or sell enough potions so that you have less than 25 controlled heat 1 potions left
3. Now unable to complete township task

### Expected behaviour

I expected to be able to use any level controlled heat potions to finish the task, or be able to downgrade potions

### Save Link

https://melvoridle.com/save/7Cn7RF31

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695

### Are you using any mods?

No

**Comment by Falterfire** [comment]
This doesn't render the task impossible to complete. Herblore Potions give a chance to create potions of a random tier while brewing potions. This allows you to acquire tier 1 potions even at higher Mastery levels.

**Comment by Norboro1** [comment]
> This doesn't render the task impossible to complete. Herblore Potions give a chance to create potions of a random tier while brewing potions. This allows you to acquire tier 1 potions even at higher Mastery levels.

This is true, but doesn't excuse this as not being a bug as doing it this way makes it more like a HARD task. Just feels like a bad oversight.

**Comment by sirPattrick** [comment]
As I posted Elsewhere, this quest should require T1+ Potion, and not only the T1.

**Comment by balkoonline** [comment]
I definitely agree that this issue deserve more attention as I believe that it is really easy to fix this bug. Using high-end Herblore Potions doesn't make sense to be a requirement for completing this easy task. So solution is either to allow players to craft lower tier Potions on demand or to change this Town Task conditions to T1+ potions not just T1. I think the second one makes more sense and is easier for devs too.
