### ISSUE TITLE
[Bug]: Clue Chaser's Insignia not generating

### ISSUE THREAD

**Issue by Light2053** [MelvorIdle/melvoridle.github.io#2957]
### Describe the bug

![Screenshot_20221111-225517_Melvor Idle](https://user-images.githubusercontent.com/118011205/201395508-2569e208-1dfd-4a20-ba7e-559946b34a9b.jpg)
With the right order of items, the Clue Chaser's Insignia is not appearing. I have reswapped them to no avail. Tried Reverse order as well, it didnt work. One thing is the quantities are different but the latest update seems that it has removed that requirement.

### Save Link

https://melvoridle.com/save/lFMxzi8V

### Screenshots

![Screenshot_20221111-225517_Melvor Idle](https://user-images.githubusercontent.com/118011205/201396213-6d14475d-e770-4e29-af74-050b8562933d.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

4695

### Are you using any mods?

No

**Comment by coolrox95** [comment]
I was unable to reproduce this issue using the provided save and platform. Note that the items must be moved into the correct order while on the first tab of the bank, moving them between tabs will not trigger it.

**Comment by Light2053** [comment]
Thank You, I will try to move everything while staying in the first tab

**Comment by Light2053** [comment]
It worked!. Yeah that was the main issue. I had to move the items WITHIN
the same tab. Not between tabs.
