### ISSUE TITLE
[Bug]: Lightning Robes don't improve the accuracy of Slicing Maelstrom

### ISSUE THREAD

**Issue by Falterfire** [MelvorIdle/melvoridle.github.io#2959]
### Describe the bug

The text on the Lightning Robes set is "+5/10/15% Accuracy Rating when using Archaic Spells that use Lightning Runes." The Slicing Maelstrom Archaic spell does use Lightning Runes, but it does not seem to gain the accuracy bonus from the robes.

### Reproduction Steps

1. Equip Lightning Mythic Wizard Robes and the Slicing Maelstrom Wand
2. Set your Magic spell to Thunder Strike or Dragon Storm Call - The Accuracy Rating will go up
3. Change to Slicing Maelstrom - The Accuracy Rating will go back to what it is for any Archaic spell besides Thunder Strike and Dragon Storm Call

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

4695

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This has now been fixed as of v1.1.1.
