### ISSUE TITLE
Incorrect selling price for items on mobile

### ISSUE THREAD

**Issue by navybeanie** [MelvorIdle/melvoridle.github.io#296]
**Describe the bug**
Selling price does not display correctly 

**To Reproduce**
1. Use mobile web browser
2. Go to bank
3. Click on item 

**Expected behavior**
To show exact selling price for items

**Screenshots**
![6E7E6527-CF17-416C-965A-793DAA9347F8](https://user-images.githubusercontent.com/67524672/85933888-2be67300-b91b-11ea-83e1-a2e29b1d571b.png)

**Browser**
Mobile and Safari

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts**
No

**Comment by MelvorIdle** [comment]
This has been hotixed :)
