### ISSUE TITLE
[Bug]: <unable to build agility course>

### ISSUE THREAD

**Issue by girlgirlgirlgirl** [MelvorIdle/melvoridle.github.io#2960]
### Describe the bug

Im agility 6. i deleted my obstacle course to build another. Now when i press build course nothing happens, tried restarting game but still same issue. No menu pops up that lists all the possible buildings

### Reproduction Steps

1. be agility 6
2. delete obstacle course
3. try to build a new one

### Expected behaviour

menu that shows available buildings is supposed to show

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?48695

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
I am unable to reproduce this bug. If this happens to you again, please post a new issue with any further reproduction steps available.
