### ISSUE TITLE
[Bug]: Inconstitensy between Material purchases in FtP

### ISSUE THREAD

**Issue by Cramoisi-San** [MelvorIdle/melvoridle.github.io#2962]
### Describe the bug

In the material purchases, among other things, you are able to buy bowstrings, feathers, leather, and the dragon hides. All those items are also obtainable in a FtP account.
However, in FtP, you are able to buy the bowstring and feather despite having no FtP use for them, yet you are unable to buy the leather and dragon hides from that same FtP shop, despite them both having a use.

This problem is of two possible natures: Either the fact that feathers and bowstrings can be bought but not used, or the fact that leather and d-hides can't be bought but should, like bowstrings and feathers are.

### Expected behaviour

Two possible solutions: Either make bowstrings and feathers unbuyable from the shop in FtP, or make the leather and D-hides buyable from the shop in FtP.
In either case, this would bring parity between the materials.

### Save Link

https://melvoridle.com/save/HlGOWqee

### Screenshots

FtP Materials shop
![image](https://user-images.githubusercontent.com/39337986/201500100-692b609e-8f34-421b-9431-4e49b72cd0a1.png)
Full Game Materials shop
![image](https://user-images.githubusercontent.com/39337986/201500108-b5fd4b8b-54c7-47f1-810e-d18c78f4357e.png)

### Console output

Blocage d’une requête multiorigine (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993. Raison : échec de la requête CORS. Code d’état : (null).

Aucune des empreintes « sha512 » de l’attribut « integrity » ne correspond au contenu de la sous-ressource. [index_game.php](https://melvoridle.com/index_game.php)
Blocage d’une requête multiorigine (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993. Raison : échec de la requête CORS. Code d’état : (null).

Aucune des empreintes « sha512 » de l’attribut « integrity » ne correspond au contenu de la sous-ressource. [index_game.php](https://melvoridle.com/index_game.php)
Silent Sign in with JWT [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Validating Melvor Cloud token [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Storing Melvor Cloud Token [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Initializing PlayFab login. Method: customID [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Logging in with Custom ID via PlayFab [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Login with custom ID success [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Getting account info [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Account info retrieved [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Authenticated w/ Melvor Cloud: true [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Authenticated w/ PlayFab: true [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Checking for valid full version [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Loading Game Data... [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Registered Demo Data. [save.js:111:189](https://melvoridle.com/assets/js/built/save.js?4695)
Loading Local Saves... [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Loading Cloud Saves... [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Getting saves from playfab [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Saves retrieved [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Loading character selection [characterSelect.js:5:297](https://melvoridle.com/assets/js/built/characterSelect.js?4695)
Connected to PlayFab successfully [cloudManager.js:294:186](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Copied to clipboard successfully. 4 [save.js:39:112](https://melvoridle.com/assets/js/built/save.js?4695)
Game Loaded [main.js:15:315](https://melvoridle.com/assets/js/built/main.js?4695)
Cette page est en mode de compatibilité (quirks). La mise en page peut en être affectée. Pour le mode standard, utilisez « <!DOCTYPE html> ».
[v1.1ReleaseNotes.html](https://melvoridle.com/update/v1.1ReleaseNotes.html)
Blocage d’une requête multiorigine (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993. Raison : échec de la requête CORS. Code d’état : (null).

Aucune des empreintes « sha512 » de l’attribut « integrity » ne correspond au contenu de la sous-ressource. [v1.1ReleaseNotes.html](https://melvoridle.com/update/v1.1ReleaseNotes.html)
Blocage d’une requête multiorigine (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993. Raison : échec de la requête CORS. Code d’état : (null).

Aucune des empreintes « sha512 » de l’attribut « integrity » ne correspond au contenu de la sous-ressource. [index.html](https://melvoridle.com/roadmap/index.html)
Blocage d’une requête multiorigine (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993. Raison : échec de la requête CORS. Code d’état : (null).

Aucune des empreintes « sha512 » de l’attribut « integrity » ne correspond au contenu de la sous-ressource. [index.html](https://melvoridle.com/roadmap/index.html)
Synchronising with Cloud [cloud.js:29:113](https://melvoridle.com/assets/js/built/cloud.js?4695)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Although the items have no current use in F2P, it is still possible to obtain them in other areas of the game like Fishing and Combat (Chickens), so we left the purchase option available in the shop.
