### ISSUE TITLE
[Bug]: Township Tasks with Potions are impossible to complete

### ISSUE THREAD

**Issue by dylanpedavoli** [MelvorIdle/melvoridle.github.io#2964]
### Describe the bug

If I exceed the mastery level of a potion and sell/use those potions, I am no longer able to complete the township task requiring lower-mastery-level potions.

### Reproduction Steps

1. Level up Herblore birds nest potion past mastery tier 1
2. Sell those potions or use those potions
3. Go to the township tasks and try to complete the task requiring bird nest potion for mastery tier 1

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695

### Are you using any mods?

No

**Comment by ManuPoulpe** [comment]
Hello.
It's not impossible, it's just taking some time.
There is the Herblore potion that enable to create a random level potion.

![image](https://user-images.githubusercontent.com/117631989/201622346-1fb71075-f23c-4e36-8bf0-c74312b0bafb.png)
