### ISSUE TITLE
[Bug]: Pet Ace

### ISSUE THREAD

**Issue by Shiozawaa** [MelvorIdle/melvoridle.github.io#2966]
### Describe the bug

It's a simple bug that all pet is "pettable" but Ace.

### Reproduction Steps

Pet menu > Try to pet Ace

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue was fixed in v1.1.1
