### ISSUE TITLE
[Bug]: Missing Almost All Icons and Images in Steam version

### ISSUE THREAD

**Issue by lior8** [MelvorIdle/melvoridle.github.io#2968]
### Describe the bug

Screenshot provided, almost all images and icons are missing, some are showing, but I'm not sure why some appear and some don't.

They also appear missing in the starting screen, before entering a specific character.

Uininstalling and reinstalling did not help.

### Save Link
https://melvoridle.com/save/7Kl5OjiX

### Screenshots

![image](https://user-images.githubusercontent.com/50285865/201621533-c81328c0-b829-4e3c-9ae0-922a953f6f94.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
I believe this was an error with our CDN provider which has since been rectified. If the issue persists, please open a new issue and we can look into it further.

**Comment by lior8** [comment]
I found what caused it. The connection which was supposed to fetch the icons was blocked, once enabled, everything got fixed.
