### ISSUE TITLE
Arrow stacks combined when equipping

### ISSUE THREAD

**Issue by PadmesDefense** [MelvorIdle/melvoridle.github.io#297]
Had Ancient arrows equipped in my second armor slot. Was set using slot one and accidentally equipped dragon arrows there instead of intended second slot. Eventually, equipped dragon arrows onto second slot while doing dragon's den and it combined the stacks instead of returning the ancient arrows to bank. Refreshed and they were still combined.

**To Reproduce**
1. Have ancient arrows equipped in second armor slot
2. Have armor set one active and equip dragon arrows to that slot (While mining?)
3. Begin Dragons' Den and switch to second armor slot (Ranged gear, Redwood Longbow, still ancient arrows equipped)
4. Equip mithril arrow to armor slot three (whoops), then another mithril arrow to armor slot one returning dragon arrows to bank.
5. Equip all dragon arrows to active armor slot (two).

**Expected behavior**
When dragon arrows were equipped, expected ancient arrows returned to bank

**Screenshots**
N/A

**Browser**
Google Chrome, Alpha V0.15.4

**Console output**
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
save.js?305:446 Not required to backup
save.js?305:48 Loading Save Game...
save.js?305:208 Save Game Loaded...
save.js?305:48 Loading Save Game...
save.js?305:208 Save Game Loaded...
smithing2.js?293:192 Loading Smithing...
mastery.js?290:183 Updating Masteries
mastery.js?290:23 Loading Masteries...
main.js?364:1268 Game Loaded
oneui.core.min.js?205:6 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ oneui.core.min.js?205:6
cloud.js?300:48 Melvor Cloud Connection: Success
save.js?305:48 Loading Save Game...
save.js?305:208 Save Game Loaded...
smithing2.js?293:192 Loading Smithing...
mastery.js?290:183 Updating Masteries
mastery.js?290:23 Loading Masteries...
main.js?364:1268 Game Loaded
4cloud.js?300:202 Cloud synced
DevTools failed to load SourceMap: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
I tested this using the exact method and information provided but was unable to reproduce the bug. Are you able to reproduce the bug using the steps provided?
