### ISSUE TITLE
[Bug]: <Goliath Werewolf Rage ability helps player instead of NPC>

### ISSUE THREAD

**Issue by Bartbeard** [MelvorIdle/melvoridle.github.io#2970]
### Describe the bug

The rage effect happens for the player instead of the enemy. This seems like the opposite of what was probably intended.
![Capture](https://user-images.githubusercontent.com/118193312/201685264-e247ee13-3738-4128-9fe0-ae1317395d7e.PNG)

### Reproduction Steps

1. Initiate combat with the goliath werewolf
2. get buffs
3. profit

### Expected behaviour

i expected the buff to apply to the enemy (the wolf)

### Screenshots

see discription

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This has now been fixed as of v1.1.1.
