### ISSUE TITLE
[Bug]: Ring of Spirit Power not consuming runes

### ISSUE THREAD

**Issue by durzogavin** [MelvorIdle/melvoridle.github.io#2971]
### Describe the bug

My "Ring of Spirit Power" does not seem to be costing any spirit runes since the expansion update. I am casting the "spirit power" attack, but no spirit runes are used at all and the box around the spirit runes on the runes tab in the combat menu does not appear. I have tried un/re-equipping the ring, restarting, etc with no change. 

### Expected behaviour

I expect it to use 3 spirit runes per attack.

### Save Link

https://melvoridle.com/save/odhWO0sV

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
I believe this was hotfixed a long time ago.
