### ISSUE TITLE
Mod Manager Failed to load!

### ISSUE THREAD

**Issue by supdalat** [MelvorIdle/melvoridle.github.io#2972]
### Describe the bug

Error Name: Error
Error Message: There was an issue with deleting locally-stored mods. Please reload the game and try again.
Stack Trace:
deleteUnsubscribedMods/db<@https://melvoridle.com/assets/js/built/mod.js?4695:149:17
rejected@https://melvoridle.com/assets/js/built/language.js?4695:3:45

When loading my game on firefox i am met with this error message.

This has been going on for about a week or so

### Reproduction Steps

Attempt to load the game

### Expected behaviour

Mod manager is expected to load successfully

### Screenshots

<img width="383" alt="Bug Melvoridle" src="https://user-images.githubusercontent.com/74168364/201812521-e0ae5e53-46a0-4f14-8a10-11a432b18e39.png">

### Console output

This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.
[v1.1ReleaseNotes.html](https://melvoridle.com/update/v1.1ReleaseNotes.html)
Silent Sign in with JWT [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Validating Melvor Cloud token [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Storing Melvor Cloud Token [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Initializing PlayFab login. Method: customID [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Logging in with Custom ID via PlayFab [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Login with custom ID success [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Getting account info [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Account info retrieved [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Authenticated w/ Melvor Cloud: true [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Authenticated w/ PlayFab: true [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Checking for valid full version [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Checking for valid TotH purchase [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Loading Game Data... [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
Registered Demo Data. [save.js:111:189](https://melvoridle.com/assets/js/built/save.js?4695)
Registered Full Version Data. [save.js:111:355](https://melvoridle.com/assets/js/built/save.js?4695)
Initializing Mod Manager... [cloudManager.js:199:22](https://melvoridle.com/assets/js/built/cloudManager.js?4695)
PlayFab Data Stored successfully. [cloud.js:147:75](https://melvoridle.com/assets/js/built/cloud.js?4695)
Source map error: Error: request failed with status 404
Resource URL: https://melvoridle.com/assets/js/tippy-bundle.umd.min.js
Source Map URL: tippy-bundle.umd.min.js.map

Source map error: Error: request failed with status 404
Resource URL: https://melvoridle.com/assets/js/popper.min.js
Source Map URL: popper.min.js.map

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Are you in a Private/Incognito Window by chance?

**Comment by supdalat** [comment]
I was, now i feel dumb.... thank you very much
