### ISSUE TITLE
[Bug]: An error occurred while processing ticks

### ISSUE THREAD

**Issue by wesleystanulis** [MelvorIdle/melvoridle.github.io#2975]
### Describe the bug

Left my PC on over night, clicked the Melvor window in the morning and was presented with this error:

![Melvor_Idle_iGW19sggIc](https://user-images.githubusercontent.com/77135999/201907281-7c10bd9c-7d73-42e7-bd37-694cc8801442.png)

An error occurred while processing ticks:
Active Action: melvorD:Agility
Error Name: TypeError
Error Message: Cannot read property 'modifiers' of undefined
Stack Trace:
TypeError: Cannot read property 'modifiers' of undefined
    at Agility.obstacleHasNegativeModifiers (https://steam.melvoridle.com/assets/js/built/agility.js?4695:70:45)
    at Agility.getMasteryXPModifier (https://steam.melvoridle.com/assets/js/built/agility.js?4695:57:21)
    at Object.getModifiers (blob:https://steam.melvoridle.com/e4c82f81-76cb-48d6-86b8-c7392759db3c:40:33)
    at blob:https://steam.melvoridle.com/4acec398-618a-4f70-9823-606a2aecf377:60:58
    at Array.forEach (<anonymous>)
    at Player.refresh (blob:https://steam.melvoridle.com/4acec398-618a-4f70-9823-606a2aecf377:58:19)
    at Player.typeName.<computed> (https://steam.melvoridle.com/assets/js/built/mod.js?4695:762:52)
    at Player.computeAllStats (https://steam.melvoridle.com/assets/js/built/character.js?4695:81:49)
    at Player.computeAllStats (https://steam.melvoridle.com/assets/js/built/player.js?4695:55:172)
    at Agility.computeProvidedStats (https://steam.melvoridle.com/assets/js/built/agility.js?4695:187:25)
Current Equipment:
Helmet: melvorF:Chefs_Hat
Platebody: melvorF:Cooking_Apron
Platelegs: melvorF:Necromancer_Bottoms
Boots: melvorF:Necromancer_Boots
Weapon: melvorF:Tidal_Edge
Shield: melvorF:Book_Of_Scholars
Amulet: melvorD:Amulet_of_Fishing
Ring: melvorD:Ancient_Ring_Of_Mastery
Gloves: melvorD:Mining_Gloves
Quiver: melvorD:Iron_Arrows
Cape: melvorF:Max_Skillcape
Passive: melvorF:Necromancer_Hat
Consumable: melvorF:Whetstone

Action Information:
Is Active: true

Active Obstacle Tier: 10
Built Obstacles (tier|obstacleID):
0:melvorF:RopeSwing
1:melvorF:MonkeyBars
2:melvorF:PitJump
3:melvorF:GapJump
4:melvorF:MountainClimb
6:melvorF:HeatTrap
9:melvorF:LavaWaterfallDodge
5:melvorF:ForestTrail
7:melvorF:TreeHang
8:melvorF:IceJump
10:melvorTotH:PitMaze
Modding Enabled. Loaded mods:
Dev
SEMI Core
SEMI XP Per Hour
Item Dashboard (MIID)
SEMI Drop Chances
Real Quick Equip
Quick Item/Bank Wiki
Item Township Task Info
Shop Item Owned Indicator
Melvor Modifiers Exposed
ETA
Show Skill Modifiers
Item Uses

### Reproduction Steps

1. Left PC overnight
2. Clicked on the window in the morning
3. Error was on screen
4. Clicking out of the error looks like it dismisses the error and relaunches a new one
5. 5. Relaunched game, last save was 6 hours ago

### Save Link

https://melvoridle.com/save/qdEo2x5a

### Screenshots

![Melvor_Idle_iGW19sggIc](https://user-images.githubusercontent.com/77135999/201907711-c3bb7b21-f8c1-474f-82e9-3308d48f3bbd.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695 ( after relaunch)

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
The error log provided shows that this bug is caused by a Mod you have installed. Please contact the mod developers for a fix.
