### ISSUE TITLE
[Bug]: Infinite loading your offline progress

### ISSUE THREAD

**Issue by ks5689** [MelvorIdle/melvoridle.github.io#2976]
### Describe the bug

I was training thieving with some SEMI mods (one of them is SEMI auto-sell). The loading progress began to slow down a little bit at the beginning, and when I changed to a new NPC, the loading progress got stuck on my mobile phone (infinite waiting). (There should be enough slots in my bank. )

I tried on my PC, it says "Welcome back Loading your offline progress. Please wait..." I can see all of the icons, but the levels are all (1/99), not my levels. Equipped food and its amount are correct.

I monitored memory consumption and it went from 558MB to around 6G in around 10 min. CPU is ~36%. 

I tried to copy my saving file to another empty slot, but it did not help.

### Reproduction Steps

1. Activate SEMI auto-sell and SEMI core
2. Train thieving (New NPC)
3. Auto-sell all the items that can be obtained from the NPC. 
4. Close Melvor, wait for around 10 mins and open it again.

### Expected behaviour

Loading should begin to be a little bit slow, and if you wait for longer, perhaps you can reproduce it.

### Screenshots

![image](https://user-images.githubusercontent.com/118301767/201997251-a0d4a6be-0cbf-4cf8-a8ff-7803abc9d021.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Please contact the developer of the mod to rectify this issue.
