### ISSUE TITLE
[Spelling/Grammar]: Iridium Onyx Ring has redundant description

### ISSUE THREAD

**Issue by Jordan1313** [MelvorIdle/melvoridle.github.io#2977]
### What text is wrong?

![image_2022-11-15_204930118](https://user-images.githubusercontent.com/641440/202063471-e4796726-0ded-4389-9e5f-03503f9be44a.png)

2h doubling bonus should only be stated once.

### What is the correct spelling or grammar?

Passive: +1 Flat Melee Accuracy Bonus and +1 Flat Melee Strength Bonus per 0.1s Attack interval. This is doubled if a 2-Handed Weapons is currently equipped.

**Comment by MelvorIdle** [comment]
This is intended based on how modifiers are setup to work with 13 different languages for the game. Some combinations may look redundant, but it is important to keep to ensure flexibility of the game across every language.
