### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by sparky241990** [MelvorIdle/melvoridle.github.io#2979]
### Describe the bug

when using the crafting potions I and II (only ones i have available, they have 15 charges each, but the tooltip on the item only says 10 charges

### Reproduction Steps

1. Equip potion of crafting.
2. Navigate to crafting menu and craft until new potion is used. 

### Save Link

https://melvoridle.com/save/Pk3XxCYX

### Screenshots

![bug1](https://user-images.githubusercontent.com/118335353/202099388-ef38dee3-b674-4058-918f-0548178ad1f6.PNG)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695

### Are you using any mods?

No

**Comment by coolrox95** [comment]
You have an Agility pillar active that provides +5 Charge per potion.
