### ISSUE TITLE
[Bug]: New interface of "News and Changelog" v1.1.1

### ISSUE THREAD

**Issue by Just-a-Cactus** [MelvorIdle/melvoridle.github.io#2984]
### Describe the bug

New interface of "News and Changelog" work only if you at English language. If you use other translation - you see old interface and it didn't work (one link except two links inside dropdown menu, and not clickable area under logo "v1.1.1?4893"). 

### Reproduction Steps

1. Change language to any NOT English
2. Try to open a "News and Changelog" tab
3. Dropdown menu will open, but will have only one link and it didn't work...
4. :(

### Expected behaviour

Expected that all will be like in English version

### Screenshots

<img width="273" alt="Screenshot 2022-11-17 at 07 34 54" src="https://user-images.githubusercontent.com/43491424/202365887-5d2ea40e-4988-4bc0-a377-67a9410467ab.png">
<img width="273" alt="Screenshot 2022-11-17 at 07 33 45" src="https://user-images.githubusercontent.com/43491424/202365879-0fd405bf-d18c-41c4-b895-071176c0675f.png">
<img width="273" alt="Screenshot 2022-11-17 at 07 34 10" src="https://user-images.githubusercontent.com/43491424/202365884-739c5de8-1d52-4cdc-aa99-3b22f4248951.png">
<img width="273" alt="Screenshot 2022-11-17 at 07 33 18" src="https://user-images.githubusercontent.com/43491424/202365873-a4e2b29c-cd00-4645-af1b-ebc60545094e.png">

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

v1.1.1(?4893)

### Are you using any mods?

No

**Comment by krisavi** [comment]
Also "Too many requests" (when inspecting iframe contents) and showing black box.
![image](https://user-images.githubusercontent.com/1912568/202876145-bd78a3ec-ae36-49bf-bbdf-158ff4a01f86.png)
