### ISSUE TITLE
[Bug]: Update Bug Report on GitHub (v1.1.1)

### ISSUE THREAD

**Issue by Just-a-Cactus** [MelvorIdle/melvoridle.github.io#2985]
### Describe the bug

Can not select a v1.1.1 when add a new bug report

### Reproduction Steps

1. Go to: https://github.com/MelvorIdle/melvoridle.github.io/issues/new?assignees=&labels=bug&template=bugReport.yaml
2. Scroll down to title "Which version of the game are you experiencing this bug on?"
3. Click on it
4. Saw that dropdown didn't have v1.1.1 in a list

### Expected behaviour

 See that dropdown have v1.1.1 in a list

### Screenshots

<img width="617" alt="Screenshot 2022-11-17 at 07 44 00" src="https://user-images.githubusercontent.com/43491424/202366776-bad5cc3f-65fd-428f-af6a-bc5e755a3d9f.png">

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?GitHub

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Thanks for the report. I have no updated the bug template.
