### ISSUE TITLE
[Bug] v1.1.1: Purchasing Rune Essence in Township Trader produces NaN

### ISSUE THREAD

**Issue by IcicleF** [MelvorIdle/melvoridle.github.io#2986]
### Describe the bug

Trading Rune Essence with the Township Trader when the Trader has 0GP left results in NaN.
This NaN propagates and can result in save data corruption.

### Reproduction Steps

1. Tick until trader arrives in the township
2. Purchase items until the trader has 0GP left
3. Purchase Rune Essence

### Expected behaviour

Should not be able to purchase anything.

### Save Link

https://melvoridle.com/save/lCEqVaRD

### Screenshots

![image](https://user-images.githubusercontent.com/26814565/202369098-00ea59b2-3431-4f6e-b101-c7ceb95d6816.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4893

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This has now been hotfixed. Thank you for the report.
