### ISSUE TITLE
[Bug]: Clue Chaser Insignia requirements not met

### ISSUE THREAD

**Issue by lampabura** [MelvorIdle/melvoridle.github.io#2988]
### Describe the bug

While trying to get Clue Chaser Insigna I got the item before I got all the required items.
My inventory was: 42 Maple log, 1 Redwood log, 16 Raw swordfish, 15 Raw crab, 8 Herrings (cooking them that time), 4 burnt cave fish.
I was cooking herring for the easter egg when I get the clue chaser insignia but I only got 1 Redwood log instead of 23. The items were in order in the first bank tab.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4903

### Are you using any mods?

No

**Comment by coolrox95** [comment]
The requirement for clue chasers was relaxed and no longer requires specific item quantities.
