### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by Maretn** [MelvorIdle/melvoridle.github.io#2990]
### Describe the bug

Superior skillcapes still don't show up on quick equip menu for the specific skill.

### Reproduction Steps

1. Click on any skill that has a quick equip feature
2. Have a superior skillcape in your inventory
3. Hover over quick equip menu

### Expected behaviour

The superior skillcapes should be present there.

### Save Link

Occurs on every character I have

### Screenshots

![image](https://user-images.githubusercontent.com/118462503/202489893-4f186d12-9c22-4f52-b26d-100c306d90cf.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4908

### Are you using any mods?

No

**Comment by krisavi** [comment]
You can add them manually in bank into those minibars by using settings tab (Gear icon) in right part of the bank page
