### ISSUE TITLE
0% Tax rate township

### ISSUE THREAD

**Issue by SuperPhunTime** [MelvorIdle/melvoridle.github.io#2992]
### Describe the bug

0%tax rate on township when clicking on the tax rate button it says +0 -0

### Reproduction Steps

Click on township
Look at tax rate
Close window restart phone open township
Click on township
Look at tax rate still 0%
Try burning ticks in the hope it fixes itself but nothing

### Expected behaviour

I was getting about 80k/tick before the update.

### Screenshots

![Screenshot_20221117-175725_Melvor Idle](https://user-images.githubusercontent.com/118474415/202523424-eda9ad3c-feb9-4285-bd21-87d56e5c92ba.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4908

### Are you using any mods?

No

**Comment by Blackwolfe5** [comment]
Note that you need to have one or more townhalls to increase tax rate. With no townhalls tax rate will be 0%

**Comment by MelvorIdle** [comment]
Township has now been reworked as of v1.1.2
