### ISSUE TITLE
[Bug]: Mining Gloves use Charges when mining rocks that cannot be doubled by them

### ISSUE THREAD

**Issue by fradigit** [MelvorIdle/melvoridle.github.io#2993]
### Describe the bug

While having Mining Gloves equipped with charges, charges are used when mining Pure Essence, however some actions result in only 1 Pure Essence mined. 

### Reproduction Steps

1. Equip Mining Gloves
2. Mine Pure Essence
3. Each action may only result in 1 essence being farmed, despite Mining Gloves are supposed to double output so there should be a minimum of 2 received per action

### Expected behaviour

I would expect when using mining gloves (2x ore collected) either:

- 1 charge to be used per action and a minimum of 2 Pure Essence is received
- 0 charges to be used per action and a minimum of 1 Pure Essence is received

### Screenshots

![image](https://user-images.githubusercontent.com/76832865/202571617-34d5da74-60b0-422e-94da-e4211469ac2c.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4908

### Are you using any mods?

No

**Comment by fradigit** [comment]
I have noticed that Mining Gloves were changed in the Changelog for 1.1.1 to only work on ore, but then charges should not be used when mining other materials, and still consider that a bug. Gem gloves also use charges when mining non-ore materials.

**Comment by Razorflamekun** [comment]
My basic experience is that Mining Gloves no longer work at all.  They don't work on anything in the Mining tab at all.  I am on game version ?4937 and this is still an issue.  I also experience everything above as well.

**Comment by coolrox95** [comment]
Issue was fixed as of V1.1.2
