### ISSUE TITLE
[Bug]: Shop Buy Quantity has no Limit, and can become "stuck" at very large numbers

### ISSUE THREAD

**Issue by bruhmoment7244** [MelvorIdle/melvoridle.github.io#2994]
### Describe the bug

in the shop the game wont let me change the amount of things i want to buy and its stuck at a huge number

### Reproduction Steps

i have no idea how this happened lol

### Screenshots

![image](https://user-images.githubusercontent.com/118492673/202589962-d6704d1d-fe2e-47eb-8097-bf94d80d9dff.png)
![image](https://user-images.githubusercontent.com/118492673/202590281-96cae84c-159d-4f4c-b501-b30ae7873b98.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4908

### Are you using any mods?

No

**Comment by ekuland** [comment]
click the blue box, press tab once, type 1.

**Comment by coolrox95** [comment]
Issue was fixed as of V1.1.2
