### ISSUE TITLE
[Bug]: Red Text slightly changes in combat

### ISSUE THREAD

**Issue by rotergauner** [MelvorIdle/melvoridle.github.io#2998]
### Describe the bug

In combat, the text advising that manually eating will reset the swing timer changes from a slightly darker to a slightly lighter hue with the text becoming slightly bolder as the swing timer progress, then reverts to the darker red after the swing hits.  

https://user-images.githubusercontent.com/118505814/202632351-3fa7d219-7a7c-49ac-ad30-543b59e0e496.mov

This happens with or without mods, and is subtle enough that it's difficult to capture on screen capture software.  Other red things, like the amulet of fury drops or the red of the sprite for the red devil do not change.  

Computer restart does not resolve, running Nvidia 2080 Super with firmwares 516.94 and 526.98 tested and MSI Mag321CQR monitors on Display port.  Changing display settings from 4:2:2 to 4:4:4 color sampling and reducing framerate to 60Hz from 144Hz does not resolve the problem, making it appear less likely that the video card or monitor problem.

### Reproduction Steps

1. Initiate combat with a creature
2. Watch the food section where it states "Your Attack resets when eating manually", or the "Amulet of Looting" text in the loot box, or the slayer area negative modifiers
3. See the text change ever so slightly as the timer progresses and reset

### Expected behaviour

The text to remain consistent throughout attacks

### Screenshots

Slightly darker and less bold text: 
![image](https://user-images.githubusercontent.com/118505814/202632884-78012cd7-20ff-4a86-85ae-dca20861f848.png)

Slightly brighter and bolder text: 
![image](https://user-images.githubusercontent.com/118505814/202632980-33a12199-e1b6-46ef-bf8d-a2b72336271e.png)

Easy comparison of the two texts: 
![image](https://user-images.githubusercontent.com/118505814/202634469-6232c804-f14c-4f11-8f74-b5fcbc3c1b3a.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4908

### Are you using any mods?

No

**Comment by coolrox95** [comment]
I'm able to reproduce this issue in both the steam version and on chromium based browsers. Does not occur on Firefox.

Was also able to trigger it by hovering over the Browse X Areas menus on the combat page.

Unsure of why this happens, considering the css for that element is static at all times. Good chance this is actually a bug with chromium and not the game itself.
