### ISSUE TITLE
Horizontal scroll bar at the bottom of the screen

### ISSUE THREAD

**Issue by Lazzil** [MelvorIdle/melvoridle.github.io#300]
I noticed the scroll bar come up right after restarting my browser.

After hearing about this error, I decided to test it for myself. I started off with the screen displaying as it usually does, then I closed my browser, opened it back up, and the bar showed up immediately.

I took a screenshot with inspect element on. There's an extra section to the right that is outside the main element, and no other element includes this extra area.
https://cdn.discordapp.com/attachments/625841473731952688/729391583237242990/65465131563130.png

I'm using Firefox 78.0.1 (64-bit). I'm also having this issue with the latest version of Chrome.

Console:
[Nano] Nano Defender Activated :: melvoridle.com core.js:43:24
Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-129674422-1”. index.php:6:1
Loading failed for the <script> with source “https://melvoridle.com/cdn-cgi/bm/cv/2172558837/api.js”. index.php:80:1
Loading failed for the <script> with source “https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js”. index.php:537:1
Loading failed for the <script> with source “https://ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js?threshold=24”. index.php:1:1
Security Error: Content at https://melvoridle.com/index.php#combat-fight-container-enemy may not load or link to moz-extension://08cd2c3c-630b-4bab-9a2e-672928d21813/styles/semi.css. 2
Not required to backup save.js:446:21
Loading Save Game... save.js:48:13
Save Game Loaded... save.js:208:13
Loading Save Game... save.js:48:13
Save Game Loaded... save.js:208:13
Loading Smithing... smithing2.js:192:13
Updating Masteries mastery.js:183:13
Loading Masteries... mastery.js:23:13
Game Loaded main.js:1268:17
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ oneui.core.min.js:6:80358
Melvor Cloud Connection: Success cloud.js:48:29
Loading Save Game... save.js:48:13
Save Game Loaded... save.js:208:13
Starting inject utils! utils.js:5:17
Utils injected! utils.js:290:17
Melvor TimeRemaining Loaded index.php:8:9
Katorone Automation is set up and ready to activate. katorone.js:170:17
Melvor Combat Sim v0.8.4 Loaded, but simulation results may be inaccurate. main.js:5038:19
SEMI v0.3.11 Loaded! menus.js:130:21
Loading Smithing... smithing2.js:192:13
Updating Masteries mastery.js:183:13
Loading Masteries... mastery.js:23:13
Game Loaded main.js:1268:17
auto-slayer Enabled! core.js:88:21
Cloud synced 4 cloud.js:202:21
Cloud synced cloud.js:202:21
Cloud synced cloud.js:202:21
Cloud synced

I'm using SEMI and Combat Sim.

**Comment by MelvorIdle** [comment]
This has been hotfixed
