### ISSUE TITLE
[Bug]: Township Orchard

### ISSUE THREAD

**Issue by Dorky106** [MelvorIdle/melvoridle.github.io#3004]
### Describe the bug

Orchard doesn't show up as a gather building for some odd reason, even though it is a gather building.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4908

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Township has now been reworked as of v1.1.2
