### ISSUE TITLE
[Bug]: Ward of Flame Platebody has no equip requirements

### ISSUE THREAD

**Issue by 47Y** [MelvorIdle/melvoridle.github.io#3006]
### Describe the bug

The Ward of Flame Platebody can be equipped at any point once made. It doesn't require level 110 (or any) Defense like the Burning Protection Platelegs nor does it require Impending Darkness to be completed.

### Reproduction Steps

1. Obtain Ward of Flame Platebody
2. Equip it with any stats and dungeon completions

### Expected behaviour

It should have a level requirement (likely 110) and require Impending Darkness to be completed.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4908

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was fixed as of V1.1.2
