### ISSUE TITLE
[Bug]: <Farming Mastery Pool and Allotment problem>

### ISSUE THREAD

**Issue by Dunkelhe1t** [MelvorIdle/melvoridle.github.io#3007]
### Describe the bug

I use both Steam and website version (the browser is named 'Via' and I use it only on my android phone) to play the game. This afternoon when I logged in by website on my phone, I saw my farming mastery pool showed that the percentage was about 170% and the maximum XP of the pool is 10 million. I then spend the mastery pool XP once and the figure returned to 'normal level' that is 100% and 10 million maximum XP. But after several hours I logged in on Steam and I found out that farming mastery pool has a maximum XP of 18 million which is the REAL level of mastery. The percentage back then was like 55%. It consume 8 million of my mastery XP and I can't get it back because the cloud save is covered after a few seconds.

What's more, the whole farming system become abnormal. The last allotment just can't be harvested! Wherever in allotments herbs or trees, the crop on the last crop always says that there is 0 minute to harvest. But I've been waiting for hours to see whether the 0 minute will go, it just never. I have to destroy it to plant a new crop and I don't know if it will become normal after hours.

### Save Link

https://melvoridle.com/save/74fYtrBq

### Screenshots

![QQ图片20221120233529](https://user-images.githubusercontent.com/22417043/202912073-8272c536-c81d-4df0-b3ce-b703fb938a7f.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4908

### Are you using any mods?

No

**Comment by SimonBN** [comment]
Experienced the same bug today, switching between two android devices - I had the Throne of the Herald on device that I switched from, but I think the device I switched to did not have the expansion installed before the switch.
