### ISSUE TITLE
[Bug]: Mastery pool xp percentage and checkpoint percentage both showing 95% but not getting 95% benefits

### ISSUE THREAD

**Issue by PsyDrag** [MelvorIdle/melvoridle.github.io#3009]
### Describe the bug

thieving mastery pool xp bar (probably all of them) seems to be rounding the percentage (from 94.999% to 95%), but the checkpoint is maybe checking for the flat 16,150,000 xp to enable 95% benefits.

![image](https://user-images.githubusercontent.com/6046220/202920059-48c7295e-f178-46d8-85a7-9d58c287ba78.png)
![image](https://user-images.githubusercontent.com/6046220/202920088-2eefbcda-6069-4508-bc76-c57436e4914a.png)

### Reproduction Steps

1. get thieving mastery pool xp to 94.999% (about 16,149,929 xp with the expac)
2. see discrepancy between mastery pool xp percentage and checkpoint percentage

### Expected behaviour

mastery pool xp percentage should probably truncate to two digits instead of round to two digits. or at the very least, mastery pool xp percentage and checkpoint percentage should use the same method for determining percentage

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4908

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
The percent display is rounded to 2 decimal places. Working as intended.
