### ISSUE TITLE
Unable to change Ranged Attack Style

### ISSUE THREAD

**Issue by navybeanie** [MelvorIdle/melvoridle.github.io#301]
**Describe the bug**
Unable to change Ranged Attack Style stuck on Rapid

**To Reproduce**
1. Go to Attack Style
2. Have a ranged weapon
3. Attempt to change weapon

**Expected behavior**
Be able to change attack style

**Browser**
IOS

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

**Comment by Huntibilis** [comment]
I’m having the same issue I think. I’m stuck on rapid and can’t seem to change it. Changing weapons, restarting, still stuck 😔
![68731B27-A354-4908-AD94-1732DE2ACD6F](https://user-images.githubusercontent.com/68346873/87577487-f672b100-c6a0-11ea-90b9-cf75652d342f.png)

**Comment by Botanen** [comment]
I have the same issue! I want to train defense too 
:(. I was using throwing knives.

**Comment by Huntibilis** [comment]
Patch has fixed my problem can now swap attacks as expected! 👌🏼
