### ISSUE TITLE
Updated password and still unable to login

### ISSUE THREAD

**Issue by JShea24** [MelvorIdle/melvoridle.github.io#3023]
### Describe the bug

I have updated my password through the forgotten password link and I am still unable to login on Steam, Chrome, or iOS

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?

### Are you using any mods?

No

**Comment by Zellare** [comment]
I'm having the same issue. Did you too use a plus addressing (also known as subaddressing) e-mail when making the account?

**Comment by JShea24** [comment]
Still unable to login please advise

**Comment by MelvorIdle** [comment]
Please ensure you are using the username to log in and not the email. Also ensure the username matches the one contained inside the email exactly. If issue persists, please open a new ticket.
