### ISSUE TITLE
[Bug]: base game completion issue

### ISSUE THREAD

**Issue by DJSullivan06** [MelvorIdle/melvoridle.github.io#3025]
### Describe the bug

Base game mastery calcs seem to be off. It says I have 100.1% mastery even though my crafting is 5623/5643 (102.41%). My cooking mastery is at 3143/3069 which I think makes my mastery over 100% for base game. I am also missing a base game item but am allowed to wear the completion cape.

### Save Link

https://melvoridle.com/save/3sDekzQW

### Screenshots

![image](https://user-images.githubusercontent.com/118942500/203661494-b17f832f-eec4-4e31-bf11-76fc4f8d6ba1.png)
![image](https://user-images.githubusercontent.com/118942500/203661533-36014c2f-bd2d-45a5-a835-ccb9bb914b84.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4908

### Are you using any mods?

Yes

**Comment by ekuland** [comment]
You used automaster. This is not a base game issue.

`game.cooking.actionMastery.delete(game.cooking.actions.getObjectByID('melvorF:Lemon_Cake'));`
^ will delete the mastery you're not supposed to have.
