### ISSUE TITLE
[Bug]: 商店购买数目过大无法调回

### ISSUE THREAD

**Issue by NeoYWang** [MelvorIdle/melvoridle.github.io#3029]
### Describe the bug

如果将商店的物品购买数量调至过大值，将导致调整按
钮不可见，无法改回正常值，此期间无法购买商品（所需货币过多）
<img width="1280" alt="2022-11-24" src="https://user-images.githubusercontent.com/118990381/203808747-eda442c7-24ed-4bc1-80c0-cf2bf352be9f.png">

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [x] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4908

### Are you using any mods?

No

**Comment by messiahkk** [comment]
俺也一样（哭

**Comment by NeoYWang** [comment]
> 

我已经找到办法了，你在游戏中打开设置，下拉到“界面设置”处，勾选“移除数字千分符”即可，若无变化刷新一下就行

**Comment by coolrox95** [comment]
Duplicate of #2994
