### ISSUE TITLE
[Bug]: Mastery pool over 100%

### ISSUE THREAD

**Issue by fradigit** [MelvorIdle/melvoridle.github.io#3031]
### Describe the bug

I logged onto my character after 10+ hours and noticed my Woodcutting mastery xp pool was 119.65%

### Reproduction Steps

1. Idle Woodcutting for many hours
2. Mastery flows over 100%

### Expected behaviour

I would expect mastery to be capped at 100%

### Save Link

https://melvoridle.com/save/uNlk6gGA

### Screenshots

![image](https://user-images.githubusercontent.com/76832865/203833070-00acd8b2-277b-4894-b639-c5060d2141fe.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4908

### Are you using any mods?

No

**Comment by 47Y** [comment]
The Cape of Completion increases all Master Pool maximums by 25%. If you load up the save link you posted, you will notice it is capped at 125% now.
