### ISSUE TITLE
No way to level magic 

### ISSUE THREAD

**Issue by Johnc42** [MelvorIdle/melvoridle.github.io#3032]
### Describe the bug

I started on the demo version which doesn’t give a magic tutorial however after buying the game there isn’t a way to obtain a staff so I’m Stuck unable to level magic. Please add a way to purchase more basic supply’s 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4908

### Are you using any mods?

No

**Comment by l3vines** [comment]
You dont need the possibility to buy a staff. The way that you level magic is by using runes. These runes can be "gathered" by killing the goblins, or the wizard are 2 examples. There are a ton more if you want any info on that check the wiki.

You can also craft those runes trough Runecrafting. This is also where you are able to craft staves. But these staves are also available trough killing Master wizards as an example.

**Comment by Johnc42** [comment]
Oh okay thanks I didn’t notice the staves in rune crafting
