### ISSUE TITLE
[Spelling/Grammar]: <title>Skill upgrade items tooltip incorrect

### ISSUE THREAD

**Issue by GuardianZer0** [MelvorIdle/melvoridle.github.io#3034]
### What text is wrong?

Dragon Pickaxe says -50% mining interval and 7% chance of double ores in the shop
This seems to be true, as I'm currently mining with an interval of 1,5 seconds (not verified)

But on the mining tab, when hovering on the Dragon Pickaxe it says -45% mining interval and +6% chance of double ores
The same difference can be found on Dragon Axe and Dragon Fishing Rod (comparing to the wiki)

### What is the correct spelling or grammar?

Values should be checked and updated
This doesn't seem to affect gameplay directly, but I could be wrong

**Comment by coolrox95** [comment]
Issue was fixed as of V1.1.2
