### ISSUE TITLE
Top bar UI messed up on mobile chrome

### ISSUE THREAD

**Issue by hexate** [MelvorIdle/melvoridle.github.io#3035]
### Describe the bug

the top bar UI is messed up and not entirely usable. I can't view equipment or potions. 

### Reproduction Steps

1. open the game at mobile width in chrome for android

### Expected behaviour

Top bar is usable. 

### Screenshots

![Screenshot_20221126-081344_Chrome](https://user-images.githubusercontent.com/1325374/204098325-96f0b0e7-baf2-4e45-84ba-f4a5430f3003.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

4928

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
When on mobile, please only use the official mobile apps from the relevant App Store.
