### ISSUE TITLE
[Bug]: No GP from Township

### ISSUE THREAD

**Issue by Diedrate** [MelvorIdle/melvoridle.github.io#3038]
### Describe the bug

On one of my saves, Townships GP per tick is always at zero. I have tried restarting the town and creating a new character and no matter what towns never produce GP since the update. I originally thought it was due to low happiness or not having a trader but even after getting those it still doesn’t work.

### Reproduction Steps

1. On second save, create township.
2. Follow tutorial missions and send ticks
3. Realize not GP is being created 

### Expected behaviour

I would like for my saves to start producing GP please.

### Save Link

eJy1W3l8VEXyr35zJeEIl4B4BUFABIVwI2pPAgSEQCDh8ExekpdkfpnMhJkJEESM67neB+KxHrji6q7HuoiurqxmcVVc73M9V8ADb1HXVRd/+uuqfn3MBMF/fi+fzHy7XnVVdXd1dXfNey1efHkyBdCvHwAExH+khSjTBXxL/IdLky21bgbw6lmZcRP1bqq+urTJS2fAEbRe5bFMUyoWr66si7XEMm6KhPQqdxtjddVLBHt1iZuO1UFQUPNKk268en7Kg5Ao5VdmPC8ubqcgLIrdlCAkRGwCVshDoeJOrZuKuYnqsnhyuZeGfEHtXRFLuRkvXT03mc5UL4wlGqEAmzE3WZvOeCnoJgoFZW6qraW60vPqobsod5+/MhZvb/EkpQdyLHRXVFcKdS2t0JN0pZKJVZ4wJpOJe+5KDwrR5PKYaNDCtoQHvbDSEqE4Jcu98XZJsr5dFvugFl9G5Ypkqh76YpPmJVMtogvmJhvTgB1e6BMqm5KpTG1yBexHpntupkmY3h8Lov9bRctgAHYgWlnieQ0wUJRCJcmE6IT9Bezhq5ruNjaKioPwbmWTm2qGAxAuaXLjHhyIJqKEqlSyLQMHkYlxt65ZVTsYx1hS9GgeglxypCqbYl68HooMV/Esv3GD0VMq3XhLMgGHYs+UJltbRdfg0A0R5SAZPRTbUxVLEPkwZKuMxZcLNhzyYdi+2aIZVBqOI2s8Qg3CCGQqS8brScThlggsj8QuxgbO8lIpdIQjUKEqjLKGNZpKJVdkYq1pGC3HbUU6Q0xHYXNxBKtnpNNeos6DsagyGvOHuRhVVCQzbiYpnWccqpgvDJolJsl4LFR67gq8M0GKqq0V1k1vq2tuh4lIKYu76XR1SRKbBJPkQHnxOEym0WlLZ9qr53jtMEW1pVLMt5jQPJXE4fjHkysaYukmOBq1TY+5otPrYRqaWem2tjbFRE8cg3Krkq3uKjgWu1+Y0Q7HIf+MFi/lilHkOIrRerfFTWRiGY/6L6qHAEslaEFVskU3tRS7e34iJu5TGUNEfpXnNkt/nqEsVjNvJjqFdHAoI3+NJ+uaYRZ1aF1dG05bmI03KFrA8WiSGvNZXrzFy8AcnCQzWlpFr8xY1hZrbfESGZiLROmTFXEhpFZMOyjPIcY9YdM8nBvajZLJTBrm21p8x6+waX5sWUATXMz3SuEZzR4sxP4/UQTDmCfmZ72oVYkOtShRL0rVZSl3udcuhgqqkK+0KVbX7CWqS5PJVliEIyBCZy0sRpmyNTOTyXpYgl22RKC6tkwG3W8pMswUI9jiNmP5BByymWKwsXCiDAdJunMSdq4IR4hPprEX85XYTsFSlZiry7F0KklwUy1YqMYRmxn3MnXEWUMxOeU2kG5XuX6dotTifTF9auNJ4Q91KCnaGIvHMu1QTwG8rUX4HnJ6WIyKOZSMJxvboYFMSK5ICMNboRFNnRuLLxTBoYkidltDQ1WTV+LWtk9PuY2CHKNhXplJuWKyJ0T4iScz8D/aHaNi6jdjb1PJ74/qhaIH42g0UStEj2OIaEEN0g9sxgR6gu8ePmcSOWUgszlbKZ4SWXEuQ/OUfyhiConRNjE7ZriZ6qqYmOazIU2BUK4juGgW6HUkBW3YnpkytqdhOVafJXwn7ol4QAEpDSusWO6TVmItGXGEV7ajp8r2aidfZQU2Mx9Oy6US72o1SX0PhdMtjX6AX0MRI9nqwRmoG4MbTh3oQN1VKc9Nt6U8fwtwJsrzF3KaXr8yBLk0nGUWEH9Ony0o+5W7GCPaq6uSOE+Ui5+DtWXfS3HnAm07SJxaks6jhUssKNUVXqrBq8vA+WjnCd4KGYh+rddzuSBdgOVytzXuyfsX6kUER+UiHAdqTHWyoXpJLLMithIuRn+e0djot/ISUeyXbbE/9S61I4fff5fR3IiL2+km0W2Xi2L/7Mp6rl6RPZw0cFeaDvPD01oKKW5trdvob1muEpQ+0ZY2MZXRahlN69phHTaGmkbBX26HrsYhni/CtBg7v/410vloYdS9eC2GYmGHiLDXUajxXeQ36NNCaG0sAdcLHCgVG5UbsFNlOJwldnlwI015EZ3dOrGu3eQvhI1tYmVbr11iTiLW2JSBm/Uo+4TfYjeUJhMNbWmvXu7n4BaasCvEdGkvTyZoQdmABs71vLomuBUhGQi/w94pF6HIVQbfZkV9X8PtcvVMNHr1fkt+T0GzWUyLjPCRP+D949vE4pbCYCmU3YFC/AXSF3InLQleRtlzF3aM7AO4Gw0qa8Kd2h+xedG6TGy5V9kcEx1wD/JFM6JrmuFPpDaT8hKNmSbYSEu410A7jXvRb2bFMq3JWEK4/iasJU2G+xBXpNx2ofV+CjFxwn+mThK7O7EnwD2kiBAPSFLKbU148YXChhQ8iKMtBj9R1zS/YbqXbnVjKfgLEnGWVCRjaT+qwkPYwrleizgAVIiABpvB3narWfpXHC6xCLai9/iT7GEMGrhywSM0/URX+ruKTjRIxnlF+hsKiAqjM7ieV4jvsfB0F1oxPNOFNg6e7UIbD891oU2A57vQJsILXWiT4MUutMnwUhfaFHiZwn2WzWPgla7EsfBqV2Ix/JMGV6ylsrWvgT6VIBFet28Xwxt2cRy8aRfH07lMFyfA23ZxIvzLLk6Cd+ziZNhmF6fAdixiXJBm7aCAr3Z079o3i+E9uzgO3reL4+EDdIB54kTC8DRXsCjhtbTGk+1ePcMTmH+qxC1hCe0V6peLvhHrCDCcebTWifgpNh5pOBLX5ZyDUfUiGLOnBfOLrgvmLtjDuepLsHfxX0HWWe5rnLAyLOC+qQH+LaelVy9aB9/gfJuditW7CfgPzWQRHmIufIszvkrEUBe+w7YvxjPW9zQ52+NxwfBfYhZxuSkGuwV25iThB6RVif1+Wxr+FwXMaq8XEetHVLhArG91QslPaB3ONU+0IcGC5CopcWoQobk+zUIUhfxNo5diERleRc/joiQIeFbOF9PML+IhuYBO3rKMp2OnrIJ1pxkr5DA8AAdRIsOjb4hkMTzvBoQUhifdINZneMYNiGjA+pDlwonSrC/kHJgYnmvVEZbReVbsXsShIc36UxQTrWhOMzrOlgrPwYjC8DhbQCtCGpdGtj8t0SRCCMHjbB9bh9+SA2iVwt2qKBxIftQqBHp1IlqlMwwPuN1IXXW52yxYDqbOd2NiO8vwXJuHoR47lRWpPhWL86y2DBtMboWJi2o8naF8PNaGZ2KIzTA80vYyQ5CuLnVbWhkeb8MivHqpDMPTbYjSA2wY9ekK5BhOK4NwJVzuY6JHRpAjJtvEsolFOtBS29Jim5lheKANC7+Ke+0Mz7I9VJekycpRai67cWwvHmXDYg1rjHsM51B+ZSK5QvrMUeSrbrp5DBuj4Fg2VsFiVqzgOIYn2gI5XauSGTyt4bgVliZTbYn6thYVw7dgf1fgTlCdlB9FR5mfaF8Jf8d24pSJifiGzI+h8RWiIa4mPY5qom2NSt4TaP38VKyuyYWtyF7uZbxkSt1+EtVNj4kzjaL8gzzIS4lNkJg0T3UNuuNgZ1fiePiwK3ECfITW6PA8Bj7OKo+FT7LKxfCpHfwmwGd2cSJ8LsctJbaDGN4gPMv1WmIphoW8hcm0m4i1u8yh+JBuEntahkkz9J9gSSyDZ4jefrycqgMluzE6sBCPTxQxe/pZuqkyPVeyck5VwYYKkN81yBUyXMKRvTK3xbMGNtXmQVauzwrQWYM//tVc2dQiaYWyFq/uRMM2BUBxBHw+WQpapSDaFziMMn8FlO5zKMdXCOZyKL/nUDqP0T+uJL2Ihtq+pcwdhqyR+Cmq9gpiHk5Ep74O9AtBKIz5tGAQ+kegezcYkAcDCzBdNojBAQWYDguHMQt2sAOHOFDkwGAHuhVg/qpHNxgSgqEFcFgIhoVgeAhGOBAQ9uTD4WEoyIdIGPLCmG86ogBGFfj2FkE/0aohMFqsYEeJ5WosFMM4GA8TYCJMgskwBabC0TANjoFj4TjgotVRsRgOg1KYDjNgJmWrsGveEC2V/VSm+4vm4CgsYcJkqybv5Qr63T6LwWxGyRUzcIXic46PAzAX/4RzlmdTHEb5E4sSYJQ+sShBRskTi4J+p3DYwhEL5zFKr1i18q27BRbuZuHuFu5h4Z4WZpSnMR4kvTFAScmBNMPWYyLQ2fWTfwnKoFP21OEYe6cx38pf1OHS75nopErFPg2YmOaYEoowyhdlXZG9SbMM3PPlUGJpEEnHTq/3W8F0K2wRW39pK+TFYPEe3QYv3dUGOxYOWDho4V/kGBb+/3EJ1RRGybesLirUN8FvD/iziEwnm8lYspLMI7vIILKETOhp6fmZ8djn2Ha9Anv1iF8+sL/w6k2pSKAEJFDmkYkWn0Slk+nzFPqU/nEqfVbTZw19uvRZS5919FlPnx59NtBno6/LgSZKABZQxq8PZfoYZfYYZfMYJe8Y5esYpecYZeQYpeAY5dwYH2qMt3sDB9HhIw3Bwoy/201hGmK+5W1VDvLO0zqUjOgFX/W4TNU5f7LicXhbp8LoHVnzmfey9BgctLDDH16pcB43VVFWgF+x1MgyOMyv6qfrR+e9vFbr8LYZHXVaWohkvXKBNpS/fLW66UQvOfySTiW37XlTv0mz55NtTz6s5fEtWzu0rMe+U9iJLr/wex9H+DkViiXAb1muMONnahvDfL0eMWFvEezlcsiGPF0O8M1Z/CGS3aBtBj7P4k1onSE+ysjkb5r+BX+e8zHWfYODFmb8Hb43W/FaBurHVODFVs1DLekKhzTnhZMNJ1icU33UU3MuazWcy3oZToUzmtPYHbFwHt/oSxiiOZ8oNzIfX29kvurjwzTnissM53GWnfN9hGlumoG8vUhS8PxGc+O4XZo/FD3kBjUa+fzusKIX8vWDFA7z5Vzrsuo6Go/WutSIL9d2vn5jh7bz9UsVdvhHPj6yS90Vuq5236y562hMSXniXKgEi1YY7wrzIo0LLHqIX6RvFFoezSyPdTQ+ao/2zO8wnKf5YzFGtUX3DB28qe6Buu7PWfjzVpm6Do/6escqXdqj0MdpxeSLNX+BxpQ/6HJ3pqXFYEdjrBHKahHaeesO05ZSqy3DNC7kKjxihkH2ng6YQpfBDr/yfInGac7mbYazucNwKozZjlxPzudLNWeYH21Z2zlP3Si0LNyzJ/fRNridxgaDxez2cW/N2WRZa7Cj8f6a89FnOjSnwQ7/sFOyFqp2/cyq5Vjeks/veUK3MTpq4xbdxuveUvQwP8NfTfprG87SjsUs7PC3N0t7umvOZc8bTjPKDj/ZN3yg5lxjxaL5FqfC7Zrz7Bp1N2LhPP5S305C+COa9FItRsT9XbNVqM2OyTN8hD+yyZ3DsaZWlE3a5uOANdaMH2NJWCTV0g9y0kJ73uVZnAN9dLrmvNTqyUutnlR4jW7LCR2mLR8+tF7XMnRH4/Fa/lLdVmZhh5/v4wmac0Gn4TTY4Wf6+AzNqcYOOWdb2tt9PFFznmBx2nY+tEaiSZrzVMtOgx1+iY8na07V28hpsMPP8fEU+KVt7zCcYHGCxemjqZrzQIvTjqgTfHS05lxVYTgNdvj6lETTNKdZebNX4e1N0tBjNOcpVosMdvi7Q2oIHas5l1mcyyzOz/1F7jjNuaTTcBos1taH1xPCn4XlinCktq2XxgdpOY/sNnIMdvhPPsZfk6Unz9JygvyV400tQ3f4hT4q0rUmmVpR1rNC15pk1erwBwx/qI7k1MrnmXsUDvFvN6rZHLb0FlrrWrbkeKdEuJ7LKGEOKcFo394P6FpFVq2YxiZ6nK0lTO/QEvjuO1T4Y3y6JeFczWMk4D5e9okd4cGq9cxcY1twlGwfMux9Bu28cj0h/OVe7grUClsAXSNq1trHXxhgNHbfKHsjojVONrWs1dPhV62WiJ5sI84ifTdire95fMtLHVqCHVFvukaisNYVtXTZZ4RVvu0Hwr72En/30cGwpx3CloTCoeicb571cSHf2K7oYX65mftZvaR85pA9SA5F+6zkWsuFqrlCsjkNhnlc0/csGR+yCOZIDvJvP9y2x1rqRDN4jy018z2ctXP7baexzVrpsiRP8RE+4CF7u8hwZs2RKh8N1ZzLa9TdiHV6zePfPNhBCCe59E91nvq1rvtze56UL2ek5rzmNcNpr+bn3i7RBZrT7Fuy9zBrt0oUhX15lEo/XKg5R1mctpeuWS9RN805Vt+NWD2cxy/3t+wXac7Otzq0TIOdaPGmGwkdqjmnWdrtXmrxESa/WJad+BSNXAXMiPfS+BJ9d6p1V+FLtTS1YuKeTsaTgZo/GI0806StsnvvzO8kmgN72NdFI730WpDlgaf6CONqqEstJ7hyj7VqixQ28Raf+tm7d6lT3hW6peqEVaIp19RIynAtbb2eYNkxrcRHwwznQMNpsMO//51s1JWac4213zbY4c/6OA9y5w4mC2js7IgRZc/L3fJaLVnfzFlrxvsIR6HLKS9a9soHHRIX8tvU8ULElkdGKxzm64okWrBXS0bs0xIVN/RPVVpOqa5rZnr2rP+Vb8NVmnMJN5wGO/xif+Cna85qS6bBDj/Lt+dwzXl/o+EcaHE2dEg0A/YVH5b5nOsUZ1acf67cv21579V75NwyBLpwztTaR1jaDRb7Yb9FDqj5buZpL67QNVqOnZ812OGb/CmLP5NJb7xovaSM0nV/rdfQCNcJLRH3XvQFXavr1ui7A+hptzziW/ep1h3t/d7JPg7xP6xS9DC/XpGFTeveM/qsHCZ/KqhgkLd2SPQbreVKtfHDbO71RsLiTqN9wCC1owvxDVbG+Uq9HwV+s87KBvWJ9Hqt5XJL2uB5T2tpt+l0S5jfyo20bbtUhSDP6LZE+Koao/3yTRLdoLXcpe+G+eZ6o3Hml/07lMbHyjq0lg8/MlrUzhu1nKnCuNBy14kS3ai1qJ0B+sROnWUI8cZtxv4XOlRjglZWLsJnaBzOOk+qTqVnFVFL1ll9nUqsCy1m9xm2Yi7wy7QlQXsPquWs1/afp/cNYX6dicvRA3Z2ai1Xa99z+Hk6CgN/tdi0q1Gxi3Y1r5cIn6aUWXrjgWF+psYs2u0jJSHEz9a544i1bgF/9jemLSd2GEvqNIuZ87/VGs1JnvFvP1M4xNN6Hob5sm1GY53GwJ+foBoT5IuUgULjLC3TaMSHQWVPmhMU4zsGG42LtQTgf99s2mJGP2Lt8sO8xGqjysVv0O1KajtZ9LCLf9BabtBnpDC/4SKj8SP9I0NQjwtqXKOxw5NFul3ai27V7aruNBp7vlCjNZ6rxytszRHgL+9UDQjyk7jRUq1xhJ/qy8QnZMOkxV7JOn9UOGSdKh2LJ2z9YmG8Gp+uzc+RJvbcHabWaeYkEwXtvSF+uuYH/mZSQWG/pd3sBQO6Jbi5lr1UZtn/Q19VLcQz24zkbUNrtOQaLVl4e6exsFXTHS3z91oLt2qZlSzM52q6/StQKGul11BYYv+iptY8fNCYok3Wvv9eHWJCWTl6+xcjs3e018igHpc7tP0bdJacRXmFyhGE+EPbjOSNXxrJhj/Cz+40WnZsqdH2L/PhndA1WkaybLtbbUVFLbNfEXvQBtNGE0XNKfEubX+RJdn0P/BbuhvJpmcY/6fDtWSTBQ5n5cXUKeJurWWCvsv4548a2xpqjARXCQbH4hd7sonGEg2Ftcd3SPRHrcXO/ZlfHEP6BItaFncYCcbDHasu8If0IdJoxAdK8nO0RHjNNiP5lE6jfceRqhCydpzAt5eoCkG+gBvtxj/tLDZubAIlK2d/9+kgOcujx35t8lhfblqv+Kw6OGyRaMeP/fy4kBdde+dt/trPojXnTFaG8ScO6vBhN75risIBfpeW5UT3L9ug23GxdrxwlDUqTy/g28YrkfbK3N3yCF0P/BOIlj/mYrV8BCx60MLZ+aKKDlOgSwOE9Kk/ci4AfzenHu37mSu8fOyR4s8vDaSXCPKjbNP0Ed9sWc3oLYJ8vvOdGQc/sGAnk+8RRJ3rBn6z5dJGRu8R5PMfmgL3pT+pYvQqQb4+LtIDHIfq81jWlfW8Cb51kG/u/Tm7iI49mtdw0xNQxsc+MqXx63UdvLf8RjLGNj+PgHu8BH/v3iLJjqPQk7+xtvnY4X/aH6by8vFDl5++YQQczf/7YPdzXlzQAAdF54/67N4ZrVvgiGiv/n86NfH+y9GxP4aGfVlJ44e5RDkSIXgAesKD4qDwF3gINsMF8FeQO2V8mmUit57DYtCPs/aqAVdF24/bLr+VOcNN+xn+no/PvpTzZ7eCYghAhh/12WsfvH1JCwzl/3r4D+9dl5gBo/ju03fXP7IuwbdfvfDxxZvalKppst4jYHYw4iDBGqN5z92uRObBkOjYE89o/67uFDiMP/yf28vfvH4wjOVHFK39Kn/+YCjh/26oO/OmY36CkfzfO1+9/6zN74vJP3NI843ejAvEdNhRtv2Jt0PD4fDoQVu3bZ57xH3Rg+PXvTFtAP6QTPlYMmI/+gmXPD9MTwBQamU+/cRP+cuDKQNBP/NMkJNjNP2PNFQ8ntLZb6b8HVwKixrYaeDfDNxi4KMGytxpcPjpT9KDwj71cQOfMHCr4X3SwH8YhqcMVV7+A5P4vNLHdmf3gzaxO7lpx/f3nQKD+JBrf3j/pmdPFF5c6qM1/LHzXthU9fBZcBq/xBmy6uQdFbCaj6/d9WT02stgePSoG6rfOO+jRTAsOiay8e6lJU/DKj6sJvLx0W96cGU0tP9bqxua7hAxuOazTxYuf/EV3P3e/HXD0Cf6CTcazp8+4c5522GeRmv5JB9VaNoCjUbouwFNuyi66JAvRi88sTg6r+O+S+tX65VjhGjeRfRMls6XZF8/9xyaWBWcKiteZl2D4ekAwx9UxYd+/uYZ+YCbzmLT2zlZhOdyCc/nEl7IJbyYS3gpl/ByLuGVXMKruYR/5hJek4TXNeGNXMKbuYS3cglv5xL+lUt4J5ewLZewPZewQxLe1YT3cgnv5xI+yCXszG3th7mEj3IJH+fa8Uku4dNcwme5aj/PJairRvwv5XWdmhCCI/nonX3Oevz0K+ALjXZpNIb38NGXCvGRI8eMK7/rHSUC3VxuYvFhw6IuOumyPBwfRpzIrWdBHfiKz9143n4vHRiBrxXi0+hbL/eo5St6hHHfGjD9ccY+uHIe36ToGqJXwiWB5ZSdnHIgpxzMKdMTlkfs01Sl7N8MH8ak9232WaGQXoUKGDvodSi7/G1O+buc8vc55f/mlHfnlH/IKf9vTvnHnPJP2WUGOWWWU3ZyyoEceXg1CtzJb7rmaXFRuHMYCzJ6C+s2FkbCbT7nMfgqFjue4ZfTl+GLW2yy/PoLfTkDZWkpsbAlsjROfiXk11OSs1iW7pOlI2XpMfl1vCSOl6W0/Pqj/Bolv+6XX7vl1y2ywmhZujmr3vlaJlodYfj2GPuK4VtjbC7Dl8XY5bL0hbx3EH05AdmGayXLQ5IlI0sPSJkZSSyUnP5XmNH7gPlAwk4mFtghv3bLexGgrzBQhdslMSRLq6WUpZIYlMRbJXGI/Nogv1rpCz6TpWL5NVd+XYHD1oPp42Q968GfkWefetaTX3OPTy3kmct82Es9I1fPeqv0UD29COfDvgb2M3A/A/ur30br2QBD1SdklTvtQS3zpyS9/Lc/NaQPvdcXpI4K00t8AXoxDug1OKD334DeeQN60Q3oFTe8CshZAwztz6NX2/oxPD4jF65gmFxbzHAjyOgdNvSV/uK/D+k7zJey2v8PMJMO9S96ry2boo7tcf8/TO+2MaZ+SsUlYpv4H0vvtTn0KluQ3mATc5KJGM9ep77wu4wdLf+FnKN8ySP8f61SCMAHOK8vWTmn8suT6KgZZGPYWDH241RPmLef/g/BjMbn

### Screenshots

![63B7778B-4B45-4E1E-81B6-5B4F0A8F10CC](https://user-images.githubusercontent.com/105896383/204104394-1e7c7d88-440c-466f-87a1-c1377adf5db6.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

4928

### Are you using any mods?

No

**Comment by ekuland** [comment]
Your tax rate is 0%. You will not be generating any passive income per tick.
Consider levelling up till townhalls.
![image](https://user-images.githubusercontent.com/4542300/204107958-432012e7-b9f7-4861-bc9a-9a8f05713668.png)
