### ISSUE TITLE
[Bug]: Superior Mining Skillcape

### ISSUE THREAD

**Issue by Ashanorath** [MelvorIdle/melvoridle.github.io#3039]
### Describe the bug

Superior Mining Skillcape supposedly gives +5% chance to find gem nodes, but I've just tracked 1500 mining actions on Corundumite ore which netted total of only 14 gem nodes which is about 0.93% which is nowhere near the expected value.

Also curious if it might be a typo and it's a 0.5% chance boost which would seem normal since +5% does seem a bit high

### Save Link

https://melvoridle.com/save/DkBNm9jv

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4928

### Are you using any mods?

No

**Comment by Ashanorath** [comment]
Could it be that it's a typo and is supposed to be 0.5% boost?

**Comment by coolrox95** [comment]
The bonus applies to the base chance of finding a gem node. So the 5% increase results in multiplying the base chance by 1.05. e.g. node chance = (base chance)*1.05.
