### ISSUE TITLE
[Bug]: <title>Golbin Raid won't start

### ISSUE THREAD

**Issue by myju0101** [MelvorIdle/melvoridle.github.io#3040]
### Describe the bug

Golvin doesn't come out in all modes

### Screenshots

![mel](https://user-images.githubusercontent.com/119207648/204143387-60eb30a1-25d9-408a-a31a-59e793889bb5.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4928

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
We are unable to reproduce this bug. If the issue persists, please disable all mods and try again. Feel free to post a new bug report if it still occurs.
