### ISSUE TITLE
[Bug]: <Mastery xp at Skill Level 99>

### ISSUE THREAD

**Issue by Greador** [MelvorIdle/melvoridle.github.io#3042]
### Describe the bug

"Whenever the player gains Mastery XP, 25% of the amount received is also added to the Mastery Pool for that skill. After Skill level 99, this is increased to 50% of the item Mastery XP." Idle Wiki on the Mastery Page
That doesnt happen for Iridan in Astrology. But it wouldnt surprise me, if its not working for any skill.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4928

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
We are unable to reproduce this bug. If the issue persists, please post a new issue.
