### ISSUE TITLE
[Bug]: Cloud Save Slot #6 Still Not Deleting

### ISSUE THREAD

**Issue by supersaiyoon** [MelvorIdle/melvoridle.github.io#3044]
### Describe the bug

I use Save Slot 6 for special modes like speedrun mode. I had a hardcore speedrun character pre-expansion but died. I was no longer able to load the save, so I deleted the local save then went through the steps of deleting the cloud save in Save Slot 6. The local save file was deleted, but the cloud save still remains even after going through the steps of deleting it.

I even overwrote the cloud save in that slot with a normal character save file, but the cloud save still won't delete.

I commented in another bug report thread that reported this same issue before the expansion. However, when the expansion was released, I was notified that this bug was fixed. We're now in the expansion, but the bug still remains.

### Reproduction Steps

1. Create character in Save Slot 6.
2. Load save file.
3. Make cloud save with new character.
4. Return to character selection screen.
5. Go to Save Slot 6, then Settings, then "Delete Local Save"
6. Click "Show Cloud Saves"
7. Go to Save Slot 6, then Settings, then "Delete Cloud Save"

### Expected behaviour

I expect to see the cloud save file disappear after I delete it.

### Screenshots

![image](https://user-images.githubusercontent.com/15023351/204397295-c722e0aa-5aab-4cfb-8357-4c0e53f93a4b.png)

![image](https://user-images.githubusercontent.com/15023351/204397321-3fb766c0-04cb-473d-817e-db112eb558f6.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4928

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue was fixed as of V1.1.2

**Comment by supersaiyoon** [comment]
Hi, this bug still doesn't appear to be fixed with the Township rework.
