### ISSUE TITLE
[Bug]: <Black Squares>

### ISSUE THREAD

**Issue by AlexQuan02** [MelvorIdle/melvoridle.github.io#3047]
### Describe the bug

There are black squares all over the game and it is impossible to read what they aar
![image](https://user-images.githubusercontent.com/111395792/204679052-10dc9391-c70a-47f9-9af7-9090926b7ad7.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

v1.1.1 (?4928)

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
We are unable to reproduce this bug. If the issue persists, please post a new issue.
