### ISSUE TITLE
[Bug], [Visual]: Township always shows Map 11

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#3049]
### Describe the bug

No matter which map is chosen for township, it will always show "Map 11" under Town Information.

This is just visual and the actual map selected will be the land layout you get.

### Reproduction Steps

1. Create/load character
2. Select Township
3. Make a town on any map but 11. God chosen is irrelevant
4. Look at Town Information to see 'Map 11'

### Expected behaviour

For the chosen map to be displayed

### Save Link

https://melvoridle.com/save/22w9pXHp

### Screenshots

![image](https://user-images.githubusercontent.com/57328541/204716482-e9f3caf6-4a08-4440-b81d-15454d550685.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4928

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Township has now been reworked as of v1.1.2
