### ISSUE TITLE
Offline Runecrafting Calculation

### ISSUE THREAD

**Issue by goblingonads** [MelvorIdle/melvoridle.github.io#305]
**Describe the bug**
Set my account to craft wrath runes for 8 hours and when I came back it had only done 30,000 and got ~100,000 XP when it should have crafted at least 80,000 for ~240,000 XP

**To Reproduce**
1. Craft wrath runes
2. Go AFK for 8 hours
3. Compare expected rune amounts and XP to the received amount

**Expected behavior**
You can perform roughly 30 crafts of runes in a 1 minute period, totaling 1,920 in an hour and 15,360 in 8 hours. You are expected to receive (without any mastery points in Wrath runes) a minimum of 199,680 XP in that time span and up to a maximum of 506,880 XP with 56 mastery (my mastery points in Wrath runes).

**Screenshots**
None available.

**Browser**
Microsoft Edge 44.19041.1.0

**Console output**

2CONSOLE1810304: console.memory is not implemented and will return 0 for all attributes. Please use the memory profiler to monitor memory utilization.

2SEC7131: Security of a sandboxed iframe is potentially compromised by allowing script and same origin access.

2CONSOLE1810304: console.memory is not implemented and will return 0 for all attributes. Please use the memory profiler to monitor memory utilization.

SEC7131: Security of a sandboxed iframe is potentially compromised by allowing script and same origin access.

DOM7009: Unable to decode image at URL: 'https://securepubads.g.doubleclick.net/pcs/view?xai=AKAOjstQx4S78jrezQAz4SD2hJ7uNoaHpBaw38WQIqLVl-YCyviJPSRkR-FVKJYcgkumaYN-ID09WFWYhw3bJ5gZiv-glSB9-uncNuuKFR5ZrdtFmZ9ZZHI6bavnPR2daet_RmdUcLeNMgAEo8Z8gP1-ROOIpuYdnbkKZZWLT6yXmCp926em7zMxQf625T-Gt2XrcFSP-VdmdOGZDKkuhjKHchVJW0aopoxrlMe2UKmQzBo0W-AW3dUQa5kWvbUyFvXwVCR_5irenz5ySmG56JbYDX3QYbluXZBzQ2csJozWwUiuuSOpw_Al&sig=Cg0ArKJSzEh-QKw6SqzREAE&urlfix=1&adurl=' with MIME: 'image/gif'.
view (1,1)

4SEC7131: Security of a sandboxed iframe is potentially compromised by allowing script and same origin access.

SCRIPT5007: SCRIPT5007: Object expected
osd_listener.js (6,18868)

SEC7131: Security of a sandboxed iframe is potentially compromised by allowing script and same origin access.

DOM7009: Unable to decode image at URL: 'https://googleads4.g.doubleclick.net/pcs/view?xai=AKAOjssYfaaxwxQxGA5uAOw__inm_Hiveg8PzsfVYf3Ihq7G3WMOzn7RF_L5YjTH7-6-j4rKoGmNlbjr4QWkHqzoNXxI8yqzJ7yUgJvRgtnSO2D16YWQEAQnmnKc213hySL_cwfvFgn4BDe_6dn8hSn2OYfWxxnrMr9ffbp-h7N4tQ9jStCYdMClpYyN0L-I&sai=AMfl-YSQ-AL8NE_Ar6JZ0TeXPyT6buc8xIvw3mKZIu-WWS0MuBDbV5rjWttdpdiWr770xyh4u8TyUUwS1qTivA5mGTykqwzi4JvjUV4&sig=Cg0ArKJSzMkGEUbIvnqmEAE&urlfix=1&omid=0&rm=1&ctpt=4&cbvp=1&cstd=0&cisv=r20200721.80023&adurl=' with MIME: 'image/gif'.
view (1,1)

2CONSOLE1810304: console.memory is not implemented and will return 0 for all attributes. Please use the memory profiler to monitor memory utilization.

SCRIPT5007: SCRIPT5007: Unable to get property 'assign' of undefined or null reference
bundle.js (1,29737)

SCRIPT5007: SCRIPT5007: Object expected
osd_listener.js (6,18868)

DOM7009: Unable to decode image at URL: 'https://googleads4.g.doubleclick.net/pcs/view?xai=AKAOjstseT6CBn9t5TlIJUPR3QOmfgrPCU-41mnClWEYcuq0S4SZO58AAYXE2PDkQbYzsJyddfeeYPB-9S6T40kUEw9ruwWde7v_irh1JOZ5oswgXq0x24rSGRgi9wEw1NVJpkUGsQwj8ZYdP1O4oFIfZJaDujQZk-7wIMgRO8fhhS_Qoa9ec9TrEnN7wrQxRTwijDTpehAc8vDCJqcYA1FZm_RLFGSKELqcyGlsj-_cEqIvKWyx_C_ZV_yKQErrrXzZ7UEJkYBgRjeWfJ1SbxmBetrQLjJq-g3Uh2dERssOxBnhWjg9BjOT-0gl6GrSp3BC6iaklMdN8627sg4yseOPIpIh9PHkPeOQiZa90Td1_FkSaJQL47J9zyLvNinrgLsc4AwgNoiH1JtAg_0wF1E7tN_j1EXt84NSbi1SC0X92tM065ZJJzk6FjUEcgsyx5YtLeS1uTlX5APX03zXJeEbLCeBjhK7UdTlWKMjJmHMMBbLA80j5gFOCKR0vOalAIcEtcuL_h964F-VqorVKwexRPCKRtsdHz_U3Jo6OKsrZcioiLJYItxYeHz0oDGD9rSJ_8Xmw3c0O0p5SrBjX2yUxj2qXTIK3V3qCL0DxJrKm0cZZNGYKX7Q1u-PQj9FnqcwNUc6r8wUx85aC7w6RMsD7cWUUZKL7n_bVJlKsR15YJbZuFxs4hH2h9wCFe4Sj3KkMyUZVr_jQMhcogmJeCQvMrJ9kOaKrUOrAs4AuOHkkjYSkuqNCQ54g1Y33y-klhx6UiCeNioAz1WipHJV4NtGBSd9kVBvLEod_IvfkXJ51AYhaVGeLGoYIwbotKBowL8LF7lAMQDQw4nysyxgRsaBC1uV2pJqsg3v28e3g6WwcTyqoimNVyM-an_8pX3FhOM7WImKqukJtdvfXoOP3Bva3vN9IxvlXpTKZpP1vxM8eG
view (1,1)

DOM7009: Unable to decode image at URL: 'https://pagead2.googlesyndication.com/pagead/gen_204?id=sodar&v=30&t=2&bgai=B3ybhv5wZX-CHBpqrowaOo7-YDgAAAAA4AeAEAg&bg=!tLelt69Yylau40n1cd8CAAADX1IAAABXmQGdSFO0y6XNiYIMbIZ4tX0TIkTtikAsLTcxeeKF94mkPbkQON-TKBos-BqZfW_7KU4aOTgEPYNiLyz9RnqNmrSUF7K8MaJQ5aJiXA7DAh0D_1MtyKUI8mc9oj4tBsoESPwBl-8ywR5NfWdgCgczrsCLi1vVPR0E2RFEx8itOs8Xj5Fa3chYoztRZ5yQgJQcWZeOj79NmdaLV6t3yPVDPkUEFnv16irgWz4pWD1iz3Dv_rMIp24AE33kdUN4PEQG3nEjyqCWUyAiH5Q8DuXivAN_9SSXbvL24k4QwfcDbHGzJtSdjiiRP_8sCB-BWJMUN0Y3zHUjT5MsolHVZHtk_PkP3xkpyEbi0TmFgUrbJJ25Y322Xp6H01hAfNTPszj7O4jckIDpP6RPpQA9p8dmvfp_tWTaV0KxKs8fccErX-HUWLLKLpCXWm3_Bg3HY2vaOMSGXZbSDBIscY1IlepYRu8mMOl3vUEQoaoeBrJjMjpo-ker7p0H6-AU5SQBKSyVJUlIvdvwKAmHuYiOuNYwNYpRdX6VFFxM-A9qiNAyyNk' with MIME: 'image/gif'.
gen_204 (1,1)

Runecrafting paused...

ff

1595514066360

Runecrafting paused...

ff

1595514140080

SCRIPT5007: SCRIPT5007: Object expected
osd_listener.js (6,18868)

2DOM7009: Unable to decode image at URL: 'https://googleads4.g.doubleclick.net/pcs/view?xai=AKAOjsujTPh6EMOFyhX51fRyutQJTpdz0aW0ebsS_8kA6o9-c6eg1rwuNhpWEBNpM2N3xNCs68zCAuqRVPiVx95z3KAg6wiQSonQlZ15kfk9zSvgFygCbhJiPNa9M3C1jieVUhWDdZ4JDlIq16dOaOVgq2UCcft01XyI1IWNaG1660MR3ENX1DpYBxHv5VgY6v4LKUeTAlTit95tu1OP2NAgA1_Upkryziwke41yol4Gdz0PbqKWovSPVMyz6c4B7crmqDWlK2vOFrsESEM5RubVOmFkxj3m9KfuoEh3eOL1955GaQcCdT-X2OsTJqU8jQV7m3f9HbJ-wLLgpRbsEdKgEEvGkBX1Y3CsCPwSiOdp3ZRGxzVkh2IsJH4Eyihay8sZCfQ1UVK8xI8_RmpPLLC9ETd0-fVY4VpXgqGrRoHvTPsw-R9R5j8ZJ2fkcmVfNAcO3kkNlIqUEp4SJ8wq45ZVvx4F1-Hz_NRAS8bei8aehLD5idQ4N5BlRudjOR8kom4CGgdoUxAYjxEXL4OBUhhyU12g94ufYF7Oxsd2G0sSlbS37JWZ34AqLl8H8MIbWX7_88XBgTp94a5qloRjy8mJb1Hjbk8hSFj2MfG2SHttUQBqPaFCNz8ZgO3ig8To2vGYQrwAiNLQlyl_40j-5XXFi-AX26xJWLBv9bhONY0LX5sRzMsnX_BXbmiAZlx18tJ1b0WXRTeDDBd_UcsD4jlu2abOCe4fvUBU5USXl1KkXjRVX6bVk0-duXn7_Y36-npaImNSgH28hNs3NAjSjst-MklW9-ndFslTm5AZpTo97dwr6Cc8SZEaQVpP6HxF7w6GQpcmqS6y5LFQNlX_ZibDGkx8A-FmVlj-xlyUp7MYBBa5nC_qDq9gPFOfLIS108WmrFQI66Jn4BfKv93DwmDrGNp_TubfUU4bqt5bJQApBJ
view (1,1)

SCRIPT5007: SCRIPT5007: Object expected
osd_listener.js (6,18868)

DOM7009: Unable to decode image at URL: 'https://googleads4.g.doubleclick.net/pcs/view?xai=AKAOjsuyB19kXcOd0uZR3C1eNGjF-F3jrDLfiJ2ZV3phgqIT580uK5HN1PhuXlIUbXnzU3o0HvHcbK5ONFIa95WVRax7yla01-zj5UPnTaIKRywOzSn4LxUAKw3RB6wubSZsBWM-XZpf2401wUipoqUI8p7YsVQLZx30DsL9o9GDxOSaXnfmK0GKnrH7jVUPZr5nkCRPZMMWY1V7-HPGPbmWUdH4d_cFG8Z61_KGeHk5xGmNjJCQh6dCUtiiLsdLHV6trRo50-YBXaQ-U2QVhVCpxbS1UIN0GgvX-LHHDyR7XLixiZ-fqQSdvihUiiA3iaaAOolIKRByKuCgRMvHXgj7cErFj9Q8Enf5sbpkAJfqn9U6c4iXVNNFmHlUTxWwHYH_TanZK5bWHv7o8JOKubz0S4tWAUpM0g30GqPACDQA1a52MbnYn7bcrwoZniU4b4m23Z54DI5oDKeQzLa9E7MbGBaUEUVcJXDgwrEHo0IuFOI6HdsgctzQrJUSFf4oGpfB_pji8vplbV-qV8FNBMGI_Ob5Fclpl4VMV8_ZZZX-1uA7szRLamGzVY28ilnoiC4APLoljbDuQoXy6f8DqJWne_gxVNPPxTB3me_8HmTSAFDRkjn5c1e1rZDcbpXDzpgFsLcEwZSnCP6rD9sk5JOcg4By1KnJ3H0BI04mxZUJS3qDKAzht_D7a4c5MvFgidk7JJndI4ozBh0HAN_jqu34hZnXtGyOyi9izGkJBsC8hVSCMTJHQa1nzbcBUsombpNQk5oTrRc97L8xedNRvDEEGnCRUQZXt5ZIx9ucgXEQkBmhA-gcAUeXtzfbyyk9y-P6jZIwt5dSeqZSlUP7xH63O6dG8XL-qh-5m7WKrFthH8lAKuhrvAI22Xa_9PHoxkOfrG1NdkYNphY2w9cIfyZ4vUTtiq744wJIznzpZUPCrG
view (1,1)

SEC7131: Security of a sandboxed iframe is potentially compromised by allowing script and same origin access.

SCRIPT5007: SCRIPT5007: Object expected
osd_listener.js (6,18868)

2SEC7131: Security of a sandboxed iframe is potentially compromised by allowing script and same origin access.

SCRIPT1014: SCRIPT1014: Invalid character
ACwAAAAAAQABAAACADs= (1,7)

DOM7009: Unable to decode image at URL: 'https://googleads4.g.doubleclick.net/pcs/view?xai=AKAOjssHTMJcHoHoXhvUDjzM8_v85zAN-bpqkGefVRdHOfkz_fSPOmVO1ePDZndqZzLNKaqxkNjKbetOSAWPdPSrFZsl4eVzaB1VCuiCAWAqgfxJj-URx3DEcH5BwkeD5PKAPY8PHqzc28tVO7b4M-E8cdb4-VdF-9fEm3WM_2wruia659Nb2vbpsMgO6Xmd&sai=AMfl-YRyb8wFDKcGGCjciaqh1lZPoyXARTu_ly53gEcCyZhat0x9bDSR80KjNbn0XKUMfE8f_NnZrKyxQVKp0t5qNqvF4Y2oHzSFpLQ&sig=Cg0ArKJSzFAQzTBkDsrVEAE&urlfix=1&omid=0&rm=1&ctpt=75&cbvp=1&cstd=69&cisv=r20200721.73703&adurl=' with MIME: 'image/gif'.
view (1,1)

3SEC7131: Security of a sandboxed iframe is potentially compromised by allowing script and same origin access.

3SCRIPT5007: SCRIPT5007: Object expected
osd_listener.js (6,18868)

DOM7009: Unable to decode image at URL: 'https://googleads4.g.doubleclick.net/pcs/view?xai=AKAOjsutjDfURTIXvkyde8V6l9rBl2XJOtuBGNlEOwK91EXjQZLtQLWl3gOzmmqbL0ajeEJPgezdNOlzFFnk9HUUyTHYGlpvvKx7gQcQJbtQF_qc-I7h10KInLzDDS9LfeM6WYDdUog7SdNbvNfJzt0inyA3e714E4JWUJmyxuHFg2hqM6ocOhnIoACxEC51HlhDYxDZz9clpYR1nImdMsVnrrCLnehUGAbZrBJguwRsN9qLPvgpTtlIOJuz-dnJx26B0qojqfS3qunOKJPKZE1cYmt-UuwZ0AfsDnQNEzyGI3rZjT5BN_D5zOVYQHWhnmpw4O6NooeHKVWpzHh65GWjPEBxPxb7qJ10vDnEVP4oq5AJXiZkXiTkz6DeEOBe4Ki5Pc_CcXYovqPkfUbLM8ik44-BtcPuWkO9S2aLgchT-8nJ4Unj9M7ad3IbLt85qnLhYFqVbD-8HLeR0_ixdXChJCRCf8jBkMwbPOyuKVEf3gdi2DHuQmh-SKw6lqgtjve6Eq4K3z5FDgCmyjkSzvndRtPCIBDE02URlhCdRUv-faA-NuypnDmLIsQBPRaiRytqmVICQ4WibKiKbdcrVc1DgR5saaJyrRlqJua6NSeR7pB80T0apWN_APZqpbPUqL-eZ_T1jMyjUtqXGpZ44TFi3EvM6yhqpsuPMPx99MC2LEA75LnbdJ_iK3IkJ8IZC4u04ZBAEJWWJk5R8WobN1vCDGMJPrrBZyX4bs5LsRYG6GuoQpce2WMZuHjvz0faq1J0-3O31vyItCozETW8nDjUbCcNO0NbvZ2OUn6hxqnCCMrOyBGMGkBTWe6rJkdMHdtz3JjhuGPxA0WEObfKFZBoFoIF0G81TRGjEgp-f3_sxtTmxfDxPZadApwTsgHfZFpWB7_Ml-aEv4jsmS6nyv5J8nkXIlXYOuXBb_PorgQ3S9
view (1,1)

2SEC7131: Security of a sandboxed iframe is potentially compromised by allowing script and same origin access.

2SCRIPT5007: SCRIPT5007: Object expected
osd_listener.js (6,18868)

2DOM7009: Unable to decode image at URL: 'https://googleads4.g.doubleclick.net/pcs/view?xai=AKAOjsvWSN8aj3ph74GVObkKsX7kMxuyHpGpZPaCKi6fJ91v91MJzAkGC4xc-wIMVCZ7NxfC5BKr22WE1VtHzz_RaGkgzufzzwL4hRm7X5HrJV5xtctLNnoPQKVBLMpq2Wrw7Am3NHCRa-54YrWmQsoJvyEg4UkHFYLOG2euhO5b_i4YZvpv6HqU75Xpc0SfqSFuWADMYz-DlpkCVD_9Lr5SVidbwNQDNJ4X68qTdoz6yohFq0kQ7mAUoJviHBBQrzqXdG1YREFFHxRVwUidLb_yKGxvaSR9sze8kCROiaBK7LEF0gxl3maUt9LO_WJ3Z0rwAVmBxslI7pT9qnEg0_beiq_MuTO1u7MhPw5N95VUmP15qJdusVCVR7PuQnwIM-tqEjCtz1z9nLbMVOycZ2nXUomj1Yy5CfxknNgmDurdYN9H7hcUQcq-Y2lZQ681cZV9Vu6OE_OBvDes0T2Yjefg0L-w-LfU_FFHtDN4_xpdyC9XTFDS_Aa6RMHNbRx1kC-0bnYjbxI9-pDibLgoDECeK9xmnSkLKeFUvln-n3R1wPnfAebKvgogoNQJlyF7NQNE8_UeuISCDBeqFR8bRg47eYXFj879t7KOOlTGrm6zvTuy-CXyqpjVEwXDA02Y8rRFEGir2p9u0u0UpcPcoQYPXoB0BrjBTDU3B_pc0z5JAM2hEYq2w1nqTlwvWIsNahnRgCwERpPlE7GpUpY4fM29armJA6WKxxjc_FPxPyXAlg8jqmGyqTeogzdE3XSCSh5GkJjXoFBeykMyBlxHt4wAhK9kQv0p7YVuc4BtMVLpIn06-DZLurdPnRu85HCOOY65pSZh5iHqWuEmPAwZvkZea8zLwntaTvFE0wBavqlMOkeelavyTYrdBPgtOgeQV1x_718VcBKJJXAmRXoeNA5KAURVvtbZHPLQj6cX1EJcpI
view (1,1)

SCRIPT5007: SCRIPT5007: Object expected
osd_listener.js (6,18868)

DOM7009: Unable to decode image at URL: 'https://googleads4.g.doubleclick.net/pcs/view?xai=AKAOjsvl7YFRtRDNvai5AYTDKn-r2M0ZN-J0Rf1nlvWHHt_u0HtUvx5ywddkEJcoXuH2fSwqIRAg8tznX43mc1q4x0KaQmWPEKAXBba64AyneFoauZ3tOmKLSW_7qwK7syk8tPa41yoJb45H9U7ESvpxUKVWjidxL5qowPyyic8ygbavcMXVLlJUrzUriwJle3ei1M8DgwzkjH-GbL6C5nM_saOz81G83UPNSp_2rM16Y1VBxPpHl-1AnVkY6nXvc4kQtw1WH5n1BbbCwLyiJykGu9YFFymw6vRq2K7q6zoeiLS3p3umAoX9PNn9mHXf2I8-sL-0fVrKSXLdMzxoMnKcLGEwsLKyXpYQpln640JtmsYdcZwh3wGkIltM9DRstDekoojb7InZNRJXxG6GLI7_UiEYKel2xnA-yK3XSOrH_WtJtVNNKDd0fPOhdGuglvUBevoD8AyN610yEeyzvqgkljhb_BawTtc_5e1hVpnu4PgWexpnDWh2PQ9nDZJn22t4GfNB-woOR4ozpKhE71eFI1WBxhXmwHlltmYodhiPKaq96c5WiGyt8lOZZJyedWi5gc0O3HWt1PegQFsFTXbM_leRD3sj0xl1Vc9Kq9SNrPfdSTbiVJJGINa9yChGzX-9milkSvZCubsEE_7C_JDN1rNkM5wxAdL4VQHTsLnCi1dxTIyoMjuFi4-n9oU9f-NzMDbcWMnM6G7qlrxPyUKxww12L04Lnx9RDB0DW6cu2XKxxGyBSHjdfgRxI4R9A85RccVb6nR3ZYsnQq0LHzpEcM0fl4CjaW8uUpdhpK13_ZLsWRLCZ89kvXgdEHeskZtY95MS7O9aOkusruH41BDk6-aHSDRf-6tN6Yk14H-wnEvsWJ5Ci7coPSJL7edBKHF5qStSwxGi7yPugLliI1bgOrw6s53_cDLlw-xVeH6wuY
view (1,1)

2SEC7131: Security of a sandboxed iframe is potentially compromised by allowing script and same origin access.

2SCRIPT5007: SCRIPT5007: Object expected
osd_listener.js (6,18868)

2DOM7009: Unable to decode image at URL: 'https://googleads4.g.doubleclick.net/pcs/view?xai=AKAOjstfzXSFF2EXbqLZfzqCf9G8Mk2Dg-XVo1bGOKv_SypWwBbf2l9gPlE8yPsX3xzCA4Q2-Sx9mu-cqzNrwFaPbEJlEMmIVmhue8MH6ig4cF23Q-vschcfqJ4It9XJqEx5npfso5ELaLv9ExSd-KHIPXbka8ZQw0HEqMAuAbsGWGD7ZsO3xlPqHnjEUqCU1C_bSR7NF7wb2eb5VlOysnxogfQ-VEVHqq39fNgTctBFTb2IIclPZOynVNxVYI3t3D5d6B3P4ov5rC0-lMyRF4jZ2fTP_aAuBy0izf-HPiXG1gat4J4bxLrjUiwbnVRMghcHGvjo1k7yaQQyrQYidcjPFUrLDC0Cq1tGzj6ocoALWfQxGUxPvogxxPktPxu4wksjl009EUQuy4t1shwrnEkhIIjCyTYRUBGdKo1pLcfOkLO80Z8IagcU16dweIJyiWATbpRl2schrTDjbMqRbAFwW0l4mB2k3Jb3L_UXzdPLErCV2K3uRSHjpSD0maCsamJ3EvWeJeTgGaRX4ZGCDXWL9_ksNGYhhDiEACza6m_LuH1o9Nj3UoBfwTKlrncqtwQp7830pGuBjCPXJSsexsz8sg3XK17SJO5OguKaCQcZEoFLs5Zeq1auiZJha1jxYagyIVbsLg8IKMvNXvQynDZ8Tr7MoAQg2gQop1eZSDtHB4Rhwa9EIZrML2cmSFwRnyayjMMA3hgPdUJ0sfkpP0bqzlxPITycwRFsWAEmeY4Ih-DjsAijWUbmrCpG7FraQKlMOS5KAbwocXha2Qp3S00Yg-aWAe136summNa9SrabZyXrfN8T1eeTt_v-9yBQ0W6c5x4oRdRTjGBB3KGeEWUKCt-r-kKo0JfKLrUwbgOImR_6RMWulvVSfTbqHoiXTKnRxLL4HiIB-szdv5UyrRqg2Ub0UFBEHT3OQDbQArq8BS
view (1,1)

SCRIPT5007: SCRIPT5007: Object expected
osd_listener.js (6,18868)

DOM7009: Unable to decode image at URL: 'https://googleads4.g.doubleclick.net/pcs/view?xai=AKAOjsulAUvtWjesm8a87pXz_6MSDd3U1vynYo8g7IIzrIgUE7cyS6vRR8fwLrJ3b8h6kFwCkBjn_og-Sn6pLuPIb6mBquMjZacUkdRHNWhKmSPcOZo1vQCx3LEmiCdXURB3Nrs3KjtGqaAbjsdGtaPUjLR2ZOq6mYu2OLfjmMeSQuJsy6sI-Jy8n-n47dyPagzo78D-1mXjpFv8k5bOILXBXnpCULQi6lmPqZtT_HZAc-9mxRqMfmC95yGVQt2as4ku8FgToQNXAzRK77nOYhXjDL8C0HJq5mvZbAlfSRpph1Scj-AyMKkoVbIPDYnjTCziu8GASjdm10KewvqLy8aPPT5HI9agZwmWKNHY2lMt2Zlw7w0eF5SIsVRoWcePJdEEnGSp2OBWVB5RpjEXMxv0ADjTXAl6lwOlsnWs3qOn_THKlfvTQAEpB8Y0vgtTCRrHg3l_DkfqQ1XwASBh99h9hdiD9mX4DrGf7UQDQdBj2XoJ79DkqFE2vc1HbtS3Tmt0T1v-7T4O1QyySTXxK6fhJLXa9BeJd3oe-g9HV0L67qNtkLMu0rpah_MLCaQ8UPfPHJsFmhQgBoV4wPO_bjH3Racn5CXfX1nu_sT7oRZLruO6En08km2vdmLZOTTFvtf2p7n37fu-nn7r178G0GdgYu9TTmmOdY0KkLd5BWhf1ipamu_wHbqIRD7PBWZ5Gx7xMj1gVSdm8oOjS-a6O5xPqQzIGq563u_UAKq0pW2ZO3Qox883vtxFxXyp33vHa_WVlvUw4tF-Tqw3VzUtU8Yr8YxjMcKAE_dwp5ONtaN04XU887BakPKNA8yD-4CE51hh8SCEgPiBIlb2N6lt9B6233-x6w9Ulos9oMYUu7fhpaOeHt3CUJzEVgr-_BcHqBk1aLJDWGHowd1D_ZTRmporimlOmnZjnS_IMHn4diTsln
view (1,1)

SEC7131: Security of a sandboxed iframe is potentially compromised by allowing script and same origin access.

DOM7009: Unable to decode image at URL: 'https://pagead2.googlesyndication.com/pagead/gen_204?id=sodar&v=30&t=2&bgai=BzlwHop8ZX8DOOZqrowaOo7-YDgAAAAA4AeAEAg&bg=!np2lnYVYIFJaOdbSAjYCAAADNFIAAABamQGdX2GgJaa6n3le7Piv4f43inP6U9L44AcTcWHa3OHs08MizgS0yduHJuMZu_byaBbjUlqh5G1kvpzE-1FbeeuVhykxvBlacTKViho4Qegni71jdEkHvhChc0j99C8OfEw0wfawzZw4skGDT_v5jLghc98YIHKKPsJH_MNTIfQuvDj0i4e5KEmy7phUrfA7cqzY_1HTcGIUTgn14o1acGyroFbVnbB38mSrvvt4XIwERgk_P-env9A5TysW_qhvzoMooAeNZfiE3YaJCEzIgFL1wpbozXeCpyEGGx5ugPEocAgimVAn4ujjLP4ywcaH1vjHNsEh8DYs1A9PKY9n7TNmtqrZPZN6ThoLt_WYhyGid1qdNX9iI6LTbGCxl_SPnHxoQoC_L09q3WIvmaypk0gVL3fbjfmWMCjcivbjl2HtP3bheeUNKPEuW3PcPH7rsM0rgCrqR3EXijfGX2Yx2zkcBgubKF31ztMjyG1-uxiahG7SsS6_-apamelPoERB0nzevsLyDfmvx9TaXqXVX-8oNyf2pzPwVpa8ibcPd3g' with MIME: 'image/gif'.
gen_204 (1,1)

SCRIPT5007: SCRIPT5007: Unable to get property 'assign' of undefined or null reference
bundle.js (1,29737)

**Are you using any scripts?**
None.

**Comment by MelvorIdle** [comment]
Thanks for the report. I'll look into this and see what is going on with it.

**Comment by MiccWan** [comment]
In Chrome, JS reduces timer firing when tab is not active or window is minimize, in order to save the CPU usage.
Not sure if Edge works in some way like that.
[Ref](https://stackoverflow.com/questions/6032429/chrome-timeouts-interval-suspended-in-background-tabs/51191818#51191818)
