### ISSUE TITLE
[Bug]: Endless opening chests

### ISSUE THREAD

**Issue by Wondertje** [MelvorIdle/melvoridle.github.io#3050]
### Describe the bug

If trying to open a chest when inventory is full, the pop-up will spin endlessly. This has been an issue for a long while, but I was under the impression it was fixed once before (like years ago), maybe it's resurfaced.

### Reproduction Steps

1. Have fill inventory
2. Try to open a chest
3. Watch the pop-up attempting to open it never go away

### Expected behaviour

The pop-up should disappear after the "your bank is full" has been displayed, or **at the very least** not spin endlessly and look weird. Personally I don't think the pop-up should happen at all unless a chest is being opened. The "your bank is full" message is more than enough.

### Screenshots

![YTLrM0T](https://user-images.githubusercontent.com/43150426/204902279-8ce137da-1c54-45fd-98f2-37368ba29d3a.gif)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

4928

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was fixed as of V1.1.2
