### ISSUE TITLE
[Bug]: <title> djav quiver 

### ISSUE THREAD

**Issue by Squawkur** [MelvorIdle/melvoridle.github.io#3051]
### Describe the bug

Equipped dragon javelins to quiver, while fletching dragon javelins, equipped dragon arrows to replace them from quiver and replace back into bank, dragon javelins disappeared once dragon arrows equipped, instead the bank only contained the hundred or so from fletching 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4928

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
We are unable to produce this bug. If the issue persists, please disable all mods and post a new issue if it does not get resolved.
