### ISSUE TITLE
[Bug]: 100% CPU Usage

### ISSUE THREAD

**Issue by tnikolai2** [MelvorIdle/melvoridle.github.io#3054]
### Describe the bug

![melvor_bug](https://user-images.githubusercontent.com/15097687/205129659-2d644476-d08d-4dcb-96bd-1b164080b566.png)

I noticed that after closing the game in ~40% of cases, the process remains in the system.
If you open and close the game several times, it may take up to 100% of the CPU

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

all

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
I am unable to reproduce this bug. If the issue persists, please post a new issue. You can also attempt to enable the performance settings to assist.
