### ISSUE TITLE
[Bug]: When cutting a tree you couldnt change to another type

### ISSUE THREAD

**Issue by usta** [MelvorIdle/melvoridle.github.io#3056]
### Describe the bug

Whenever you start to cut down one type , you couldnt change to another type before you stop cutting
Otherwise it is giving you error like `you reached cutting limit` or something similar
This might be a feature for having multiple type cutting thing but it should let switch if you have just 1 type cutting
ability

### Reproduction Steps

Start to cut down one tree type
while it is cutting try to change type

### Expected behaviour

It should switch to new type if you have just 1 cutting type limit
[should keep last selected ones]

### Screenshots

![image](https://user-images.githubusercontent.com/112882/205183925-6b36b6ca-9b84-4131-bd79-898a2839de36.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4928

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Although I agree it would be nice QoL, it would be quite difficult to add this specific use case to change if only one tree can be cut. We will leave it as intended for now.
