### ISSUE TITLE
[Bug]: 0% chance perfect cook for whale

### ISSUE THREAD

**Issue by Lornesheets** [MelvorIdle/melvoridle.github.io#3058]
### Describe the bug

Despite having almost level 60 mastery my chance to cook whales perfectly remains at 0%

### Expected behaviour

25% perfect chance at this given mastery level 

### Save Link

https://melvoridle.com/save/OdEqzua1

### Screenshots

![Screenshot_20221202-155410_Melvor Idle](https://user-images.githubusercontent.com/119707170/205397693-a310328d-2e9e-46ba-95ea-0da07cdd96da.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4928

### Are you using any mods?

No

**Comment by 47Y** [comment]
You have the "Enable Perfect Cooks?" setting disabled at the top of Cooking. With it enabled, that save currently has a 38% Perfect Cook Chance.

**Comment by Lornesheets** [comment]
How did I not notice....
