### ISSUE TITLE
[Bug]: Log out stopping task

### ISSUE THREAD

**Issue by Spaghettiboi32** [MelvorIdle/melvoridle.github.io#3059]
### Describe the bug

This was tested with other skills, as I am using woodcutting the expected result is, you wood cut, are able to log off or quit, then say 5 minutes later still be on that task and still be woodcutting. That is the case, the issue is when I am in combat no matter a dungeon, normal combat or player area, whenever I click change character, exit from the tab or quit the game, it stops the task of fighting and I am left no matter how soon I click back into the character, saying not currently training on the local save. As I have enough HP I am not dying right away. Weird enough, in the local save it always says not currently training but when you go to cloud saves, it is semi updated with the time you have been killing, I say semi because even if you go into the cloud save, it shows that you have done nothing and is a copy of the local save gaining nothing from the time you were doing said combat task. 

### Reproduction Steps

1. Start any combat
2. exit the game, or change character
3. combat has stopped and not currently doing any action

### Expected behaviour

I start combat and expect to be doing combat and have a save file of combat over the time you were away. 

### Save Link

https://melvoridle.com/save/k0PbMcJf

### Screenshots

![Fighting Glitch, melvore](https://user-images.githubusercontent.com/119709125/205404481-f77f8efd-7ac6-4278-b084-33446f7906fc.PNG)
![FIghting glitch, melvore after](https://user-images.githubusercontent.com/119709125/205404484-b90b65a3-f6b2-4d04-ad1c-8228118db121.PNG)
![ndawjn](https://user-images.githubusercontent.com/119709125/205404575-100b001a-8c61-4f3f-a60e-496c2fa645e5.PNG)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4928

### Are you using any mods?

No

**Comment by 47Y** [comment]
In Settings, you need to enable Offline Combat.
