### ISSUE TITLE
Minibar Settings - Combat Minibar radio button issues

### ISSUE THREAD

**Issue by MattSucich** [MelvorIdle/melvoridle.github.io#306]
Browser: Firefox Stable V78.0.2 and Chrome Stable V84.0.4147.89

1. Enable Button can not be selected(FIREFOX ONLY):
![image](https://user-images.githubusercontent.com/10262739/88300735-70222480-ccc9-11ea-846b-f8598ae2ed84.png)

2. Updating "Display Combat Minibar on Combat Screen" updates the values in "Enable Combat Minibar" simultaneously:
![image](https://user-images.githubusercontent.com/10262739/88300973-b8414700-ccc9-11ea-95f0-b979a8e0aabe.png)
![image](https://user-images.githubusercontent.com/10262739/88301237-022a2d00-ccca-11ea-8dc1-b06b734c25b4.png)

**Comment by MattSucich** [comment]
Updated post to include secondary test on Chrome browser with new save. problem 1 was Firefox-only, problem 2 persisted on both.

**Comment by MelvorIdle** [comment]
Thanks! This has been hotfixed.
