### ISSUE TITLE
[Bug]: Superheat IV xp not updating

### ISSUE THREAD

**Issue by Shieldeh** [MelvorIdle/melvoridle.github.io#3064]
### Describe the bug

Regardless of what gear I equip, it doesn't show my xp per cast as changing. I do receive the adjusted xp, so I believe this is only a visual bug.

### Reproduction Steps

1. Equip non-xp boosting gear
2. Cast superheat 4
3. Note XP gain
4. Equip xp boosting gear
5. Cast superheat 4
6. Note XP gain has increased but display of per cast XP hasn't.

### Expected behaviour

XP per cast should change as it does with other skills.

### Save Link

https://melvoridle.com/save/XL3UfCGT

### Screenshots

![Screenshot_2022-12-05-09-09-24-213_com malcs melvoridle](https://user-images.githubusercontent.com/8379928/205521674-35c947e6-599e-41d5-9a4e-6815fde50e99.jpg)
![Screenshot_2022-12-05-09-09-32-506_com malcs melvoridle](https://user-images.githubusercontent.com/8379928/205521679-95e1039d-4f28-4352-96f6-859366c66851.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4928

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was fixed as of V1.1.2
