### ISSUE TITLE
[Bug]: unable to open Mastery pool spend Window

### ISSUE THREAD

**Issue by leobrennan** [MelvorIdle/melvoridle.github.io#3067]
### Describe the bug

When clicking “spend mastery” button nothing loss. Doing it on the active skill gets an error message in the screenshot attached. 
I do have a mod to go past 100% mastery, currently at 112% (none of my mastery’s are further than that). 

this has impacted my other save on the device too. 

### Reproduction Steps

Go to any skill
Click on Spend Mastery Pool XP
Nothing loads

### Expected behaviour

The mastery tab opens for the skill so I can spend my mastery pool

### Save Link

https://melvoridle.com/save/FJOrOKP9

### Screenshots

![FD79AD96-3CDF-47F1-9318-566F2118A59F](https://user-images.githubusercontent.com/1172280/205839290-7075191e-1246-46d8-9b53-0ca693948af8.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4397

### Are you using any mods?

Yes

**Comment by ekuland** [comment]
Mod issue with ETA + Bypass Agility Costs
