### ISSUE TITLE
[Bug]: There is a second scroll bar in the create tablet page of summoning

### ISSUE THREAD

**Issue by Thijmenl** [MelvorIdle/melvoridle.github.io#3068]
### Describe the bug

Most of the page that have too many items have only the one main browser scroll bar, except for the summoning page.
There is an extra scroll bar to scroll through the different tablets you can make.

### Reproduction Steps

1. go to summoning - Tablets/familiars.
2. there is an second scroll bar just for the tablets.

### Expected behaviour

There should be only the main browser scroll bar

### Save Link

https://melvoridle.com/save/utvZNbK4

### Screenshots

![image](https://user-images.githubusercontent.com/37226951/205860951-19a61862-30b2-4c31-818d-a12f74af8794.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4937

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.1.2
