### ISSUE TITLE
[Spelling/Grammar]: Silver Sapphire ring description does not match effect

### ISSUE THREAD

**Issue by Sneeze666** [MelvorIdle/melvoridle.github.io#3069]
### What text is wrong?

![ssaphring](https://user-images.githubusercontent.com/119935114/205888608-105ff82c-375b-4667-af72-827c181a8641.PNG)

### What is the correct spelling or grammar?

the description and the effects of the silver sapphire ring don't match, the description should be +12 melee defence bonus and +6 block attack bonus

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.1.2
