### ISSUE TITLE
Magic Defensive combat style rolls for Prayer + Defense pets, when it should roll for Magic + Defense pets

### ISSUE THREAD

**Issue by Voiture-0** [MelvorIdle/melvoridle.github.io#307]
**Describe the bug**
When in combat style Magic Defensive, it will try to roll to unlock pets for **Prayer**, Defense, HP, and Prayer again.
(Found when looking at code. combat.js, Line 1735)

**To Reproduce**
1. Train combat
2. Set combat style to Magic Defensive
3. Fight for years and never unlock magic pet.
4. Profit???

**Expected behavior**
When in combat style Magic Defensive, it *should* try to roll to unlock pets for **Magic**, Defense, HP, and Prayer.

**Screenshots**
![image](https://user-images.githubusercontent.com/48459786/88311494-f301aa00-ccde-11ea-92bf-892e612fa4cb.png)
Pet Ids:
14 = Defense
16 = Ranged
17 = Magic
18 = Prayer
You can see the longrange ranged style attempts Ranged + Defense pet rolls, but the Magic Defensive style attempts Prayer + Defense pet rolls.

**Browser**
N/A

**Console output**
N/A

**Are you using any scripts?**
N/A

**Comment by MelvorIdle** [comment]
Good spot! This has been hotfixed
