### ISSUE TITLE
[Bug]: < Frostspark 1H Sword description bug>

### ISSUE THREAD

**Issue by AsherDeAngelis** [MelvorIdle/melvoridle.github.io#3072]
### Describe the bug

While in the Golbin raid mini game, I rolled the Frostspark 1H Sword when drawing a weapon, I looked at its stats and it said in exact words in blue text
 “ UNDEFINED TRANSLATION:
ITEM_DESCRIPTION:FrostSpark_1H_Sword” everything else about the weapon was fine even after picking it and using it so this is purely visual and in no way hinders gameplay. I assume that this Hugh would happen anywhere but I don’t have the sword unlocked and have no other way of checking this.

### Reproduction Steps

1. Go to this sword’s stat page
2. Scroll to the top to see the error

### Expected behaviour

I would expect either no description text or a general dictation via flavor text of what the sword is supposed to do and/or be.

### Screenshots

![A7099E56-1C5A-438D-A6E8-6E00EEC32C22](https://user-images.githubusercontent.com/119958555/205967038-885a3987-c9b0-4fe7-aa3d-c376799f1048.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4937

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was fixed as of V1.1.2
