### ISSUE TITLE
[Spelling/Grammar]: Occultist/Wolf Summoning Synergy says modifiers are tripled, but are only doubled

### ISSUE THREAD

**Issue by PsyDrag** [MelvorIdle/melvoridle.github.io#3073]
### What text is wrong?

![image](https://user-images.githubusercontent.com/6046220/206104214-dcc6d1c8-91d3-4790-9229-f523a5605206.png)

### What is the correct spelling or grammar?

"When player has full HP, effects from the Occultist Familiar are doubled (+20% Global Evasion, -20% Enemy Evasion Ratings)."

**Comment by 47Y** [comment]
The synergy provides +/-20 and the Occultist itself still provides its +/-10 resulting in a total +/-30.

**Comment by PsyDrag** [comment]
I'm seeing some other synergies that are tripled (Minotaur/Dragon), so maybe the modifiers need to be bumped to 30?
