### ISSUE TITLE
[Bug]: Superior Skillcapes not showing in quick equip menu

### ISSUE THREAD

**Issue by WickedWeazel** [MelvorIdle/melvoridle.github.io#3078]
### Describe the bug

My newly bought Superior Farming Skillcape is not showing in the Quick Equip menu when i have farming open.
The basic skillcape is showing.
I even sold the basic one, but that didnt change anything.

### Expected behaviour

Superior Skillcapes are shown and equipable through the Quick Equip menu

### Save Link

https://melvoridle.com/save/RY2xBivO

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4937

### Are you using any mods?

No

**Comment by Just-a-Cactus** [comment]
Yep, same shit. Please fix it. I think it's not hard for you, but will be very useful for users...

**Comment by coolrox95** [comment]
Quick equip items are custom defined by the player. This can be done by selecting the item in the Bank, and adding it to the quick equip section within the Gear icon
