### ISSUE TITLE
[Bug]: Using magic in combat provides range experience if attack style deselected

### ISSUE THREAD

**Issue by ltsSmitty** [MelvorIdle/melvoridle.github.io#3079]
### Describe the bug

I'm playing on an old account from before Steam, and recently started doing combat again. I'm wearing mage gear and casting fire surge, yet I'm getting range xp, range summoning marks, etc.

After some debugging, I realized that my magic attack style was unchecked (aka set to neither `magic` nor `defensive`). Once I selected an option, it no longer gave me range xp and properly gives me magic xp.

Is it possible that not having selected an option will result in range xp being selected as a default?

### Reproduction Steps

Unfortunately I'm not sure how to reproduce this. I attempted to use the js console on browser to deselect the magic attack option, but I can't seem to do it again. Perhaps this is irrelevant, but it seemed worth reporting.

### Save Link

https://melvoridle.com/save/HkR4YPF4

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4937

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
I am unable to reproduce the bug using the provided save. If the issue persists, please open a new issues. Thank you.
