### ISSUE TITLE
Sold Mastery Tokens Received no GP

### ISSUE THREAD

**Issue by jatrrkdd** [MelvorIdle/melvoridle.github.io#308]
Went afk for the night, came back to 6 mastery tokens In my bank. The game said they each should sell for 1500 GP, I sold them all and recorded 0 GP. Edit: I have now also claimed 2 more tokens that also gave 0 GP.

**Comment by MelvorIdle** [comment]
Claiming tokens is not the same as selling. Are you Claiming or Selling the tokens?

**Comment by jatrrkdd** [comment]
I have used both. Sometimes selling gives coins and other times it doesn’t. I seen more GP in my pool after claiming as well so they seemed interchangeable. I noticed I didn’t get the gold after selling about 30 of them when I was trying to upgrade my pickaxe before going afk a while and still only had about 2k afterwards.

-Josh Turner
