### ISSUE TITLE
[Bug]: Quick Equip of Summoning Tablets equips n-1 tablets

### ISSUE THREAD

**Issue by SynergyFactor** [MelvorIdle/melvoridle.github.io#3080]
### Describe the bug

When attempting to use Quick Equip to equip Summoning Tablets in either the L or R slots, the chosen tablet will equip all but one, leaving behind a single tablet in storage. 

### Reproduction Steps

1. Make or have multiple of a Summoning Tablet. 
2. Add the tablet to Quick Equip, either L or R.
3. Click the Quick Equip option to equip the tablet to that slot.
4. Check Bank storage. Only one of the chosen tablet will remain.

### Expected behaviour

It is expected that ALL tablets of the chosen type will equip.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4937 - ?4999

### Are you using any mods?

No

**Comment by krisavi** [comment]
This seems to be up to preference. I like that it keeps the order in bank and does not equip all.

**Comment by coolrox95** [comment]
This behavior is intended.
