### ISSUE TITLE
[Bug]: Agility Pillars applying incorrectly when changing blueprint  

### ISSUE THREAD

**Issue by sense-q** [MelvorIdle/melvoridle.github.io#3081]
### Describe the bug

When trying to change blueprints in agility, the new blueprint's elite pillar is loaded atop the pillar slot after the new pillar replaces the old blueprint's pillar, leaving the old blueprint elite pillar unchanged. Now with 2 elite pillars active, reloading the game will lead to old blueprint elite pillar still built and the dummy pillar in the pillar slot. 

### Reproduction Steps

1. setup an agility course with both pillars
2. save as blueprint 1
3. setup another course with different pillars
4. save as blueprint 2
5. load Blueprint 1
6. Blueprint 1 Pillar is built, overwritten by Blueprint 1 Elite Pillar, Blueprint 2 Elite Pillar unchanged
7. Reload Game and load the same save
8. DummyPillar appears in pillar slot

### Expected behaviour

Load Blueprint should load exact course saved into that blueprint and replace the elite pillar

### Save Link

https://melvoridle.com/save/zi0C5PDw

### Screenshots

<img width="322" alt="image" src="https://user-images.githubusercontent.com/119939189/206826512-9dce5105-f2df-4d8e-ab66-c2b59bccf29b.png">

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/119939189/206826684-985be1ee-30f7-4e83-b260-f8201ee65cd9.png">

dummypillar seen after loading 
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/119939189/206825658-79b66c26-d619-43cc-87a4-724ff70a8e2f.png">

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4937

### Are you using any mods?

No

**Comment by Razorflamekun** [comment]
I've confirmed that this bug happens.  It happened to me as well and I posted a new issue about it.

**Comment by coolrox95** [comment]
Issue was fixed as of V1.1.2
