### ISSUE TITLE
Enemies not spawning when starting combat

### ISSUE THREAD

**Issue by TheRooster09** [MelvorIdle/melvoridle.github.io#3082]
### Describe the bug

When I start combat with any enemies or dungeons nothing starts. It even shows the enemy locations like it is starting combat but nothing happens.

### Reproduction Steps

Click monster/dungeon
Nothing happens

### Expected behaviour

I expect monsters to spawn and start combat.

### Save Link

https://melvoridle.com/save/PaqzDATy

### Screenshots

![Combat bug](https://user-images.githubusercontent.com/120237189/206830321-a6b7b65d-9a08-44af-8cbe-9166a5ba45dc.PNG)

### Console output

Uncaught Error: Tried to start timer: Spawn with invalid tick amount: -4

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4937

### Are you using any mods?

Yes

**Comment by Blackwolfe5** [comment]
If you are using Semi autorun, try turning it off.
