### ISSUE TITLE
[Bug]: The Zombie Dungeon chance of getting a pet is too low

### ISSUE THREAD

**Issue by mpypipira** [MelvorIdle/melvoridle.github.io#3085]
### Describe the bug

The chance of getting a pet is too low
Zombie Dungeon has 882 normal treasure chests but no pets

### Expected behaviour

The chance of getting a pet is too low
Zombie Dungeon has 882 normal treasure chests but no pets

### Screenshots

![image](https://user-images.githubusercontent.com/33841876/207026953-fc97ee7b-27fe-4da7-bc1e-fffb7f44bf61.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4937

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Bad RNG is not a bug.
