### ISSUE TITLE
[Bug]: No cloak from fast access

### ISSUE THREAD

**Issue by ClanScript** [MelvorIdle/melvoridle.github.io#3086]
### Describe the bug

Have only 99 cloaks, no 120 master cloaks at fast access menu at proffession.

### Screenshots

![cloak](https://user-images.githubusercontent.com/13443406/207072347-762c29aa-949e-4fa7-91aa-ba90b2cf99ca.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4937

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Quick equip items are custom defined by the player. This can be done by selecting the item in the Bank, and adding it to the quick equip section within the Gear icon
