### ISSUE TITLE
[Bug]: Meteorite bolts give you the "Meteor Shot" special attack even when not using a weapon that weapon that uses bolts

### ISSUE THREAD

**Issue by omsi6** [MelvorIdle/melvoridle.github.io#3087]
### Describe the bug

Meteorite bolts give you the "Meteor Shot" special attack even when not using a weapon that weapon that uses bolts. It even works with melee weapons.

### Reproduction Steps

1. Equip meteorite bolts.
2. Equip melee weapon.
3. Hover over special attack icon.
4. See special attack chance for Meteor Shot.
5. Attack monster a few times and see the Meteor Shot special trigger.

### Expected behaviour

Meteor Shot should only work as a special attack when using a ranged weapon that uses bolts.

### Save Link

https://melvoridle.com/save/Hftow2Jb

### Screenshots

![image](https://user-images.githubusercontent.com/9219554/207135672-8f6f494b-7d52-447a-b033-5aa0ec05e1bf.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4937

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was fixed as of v1.1.1 (?4999).
