### ISSUE TITLE
[Bug]: Visual Bug Combat Style Mobile

### ISSUE THREAD

**Issue by Tanbir17** [MelvorIdle/melvoridle.github.io#3092]
### Describe the bug

![Screenshot_20221214_185133_Melvor Idle](https://user-images.githubusercontent.com/40746381/207754058-d65f8ea4-460a-4b35-b5ac-c49ccf42ea4b.jpg)

### Reproduction Steps

Go to combat

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

1.1.1

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
We are unable to reproduce this bug. It most likely relates to the mods you have installed.
