### ISSUE TITLE
[Bug]: Crow-Octopus synergy runes not being doubled

### ISSUE THREAD

**Issue by weszhuang** [MelvorIdle/melvoridle.github.io#3095]
### Describe the bug

The crow-octo synergy description uses the wording "+5 base quantity" but the quantity added does not get doubling applied to it when doubling occurs.

### Reproduction Steps

1. Have some chance to double
2. Equip Crow-Octopus synergy
3. Craft mist, mud, or steam rune until the craft doubles

### Expected behaviour

The 5 additional runes produced are affected by item doubling. (normal+7 when not doubled, and 2*normal+12 when doubled)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4970

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.1.2
