### ISSUE TITLE
[Bug]: <Cloud save on android>

### ISSUE THREAD

**Issue by kacpermal** [MelvorIdle/melvoridle.github.io#3097]
### Describe the bug

I have bought the pc version and recently modified with the ability to transfer the save to the phone. I downloaded the free version and when trying to transfer the save the game either prevents me from hanging or when it loads it kicks me out of the game.

Is this a matter of the free phone version or is it some other bug?

### Reproduction Steps

1. I launch the game on my phone.
2. Click "show cloud save"
3. Implements cloud storage
4. It logs me into the game save
5. After a few moments when the game is suspended it kicks me to the desktop

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4970

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
We are unable to reproduce this bug. Please open a new ticket if issue persists.
