### ISSUE TITLE
Make charcoal with logs.

### ISSUE THREAD

**Issue by mrDLSable** [MelvorIdle/melvoridle.github.io#31]
I think this would be a good idea as an alternative source of coal for making bars.

**Comment by Deadvimz** [comment]
Absolute yes

**Comment by mrDLSable** [comment]
Perhaps it could be a bonus resource from using the bonfire. After all, to make charcoal you need to make a big fire in a mound of earth.

**Comment by MelvorIdle** [comment]
Seems like a popular idea. I'll include this in v0.10.
