### ISSUE TITLE
Wrong pet received for the skill I was training

### ISSUE THREAD

**Issue by Susanator** [MelvorIdle/melvoridle.github.io#310]
Obtained the Crafting pet (Carl) while Runecrafting offline.

**To Reproduce**
Runecraft offline
Checked in the morning and saw I obtained the incorrect pet

**Expected behavior**
Expected to obtain the Runecrafting pet

**Screenshots**
no screenshot, but I am only level 13 crafting with the crafting pet, possible but extremely unlikely.

**Browser**
Chrome Version 83.0.4103.116 (Official Build) (64-bit)

**Console output**
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js?threshold=74:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
assets/media/shop/assets/media/shop/perpetual_haste.svg:1 Failed to load resource: the server responded with a status of 404 ()
110save.js?314:55 Data saved
save.js?314:565 ff
main.js?377:2378 null
734save.js?314:55 Data saved
main.js?377:2495 Runecrafting paused...
7save.js?314:55 Data saved
save.js?314:565 ff
main.js?377:2378 1595607965011
41save.js?314:55 Data saved
main.js?377:2495 Runecrafting paused...
13save.js?314:55 Data saved
save.js?314:565 ff
main.js?377:2378 1595608110216
3save.js?314:55 Data saved
main.js?377:2495 Runecrafting paused...
2save.js?314:55 Data saved
save.js?314:565 ff
main.js?377:2378 1595608253145
save.js?314:55 Data saved
main.js?377:2495 Runecrafting paused...
42save.js?314:55 Data saved
save.js?314:565 ff
main.js?377:2378 1595608282320
17save.js?314:55 Data saved
main.js?377:2495 Runecrafting paused...
10save.js?314:55 Data saved
save.js?314:565 ff
main.js?377:2378 1595608765130
3save.js?314:55 Data saved
DevTools failed to load SourceMap: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
4save.js?314:55 Data saved
save.js?314:55 Data saved
4save.js?314:55 Data saved
main.js?377:2495 Runecrafting paused...
4save.js?314:55 Data saved
save.js?314:565 ff
main.js?377:2378 1595608903962
save.js?314:55 Data saved
save.js?314:55 Data saved
4save.js?314:55 Data saved
save.js?314:55 Data saved
5save.js?314:55 Data saved
save.js?314:55 Data saved
5save.js?314:55 Data saved
save.js?314:55 Data saved
5save.js?314:55 Data saved
save.js?314:55 Data saved
5save.js?314:55 Data saved
save.js?314:55 Data saved
5save.js?314:55 Data saved
save.js?314:55 Data saved
4save.js?314:55 Data saved
main.js?377:2495 Runecrafting paused...
save.js?314:55 Data saved
save.js?314:565 ff
main.js?377:2378 1595609016947
save.js?314:55 Data saved
2save.js?314:55 Data saved
save.js?314:55 Data saved
5save.js?314:55 Data saved
save.js?314:55 Data saved
5save.js?314:55 Data saved
save.js?314:55 Data saved
5save.js?314:55 Data saved
save.js?314:55 Data saved
5save.js?314:55 Data saved
save.js?314:55 Data saved
4save.js?314:55 Data saved
save.js?314:55 Data saved
5save.js?314:55 Data saved
save.js?314:55 Data saved
5save.js?314:55 Data saved
main.js?377:2495 Runecrafting paused...
4save.js?314:55 Data saved
save.js?314:565 ff
main.js?377:2378 1595609098731
save.js?314:55 Data saved
save.js?314:55 Data saved
3save.js?314:55 Data saved

**Are you using any scripts?**
not any that I am aware of

**Comment by MelvorIdle** [comment]
Fixed in previous update
