### ISSUE TITLE
[Bug]: township trader: perfect cooking doesn’t count

### ISSUE THREAD

**Issue by theshreddernator** [MelvorIdle/melvoridle.github.io#3101]
### Describe the bug

When cooking an item. And its perfect it Will not count as an acuired item for the trader. We need 10 k found items to get acces to it. But perfect is not considered as one.

### Reproduction Steps

1. Township
2. Township menu
3. The trader
4. An item

### Expected behaviour

Please make sure that when cooking a perfect item this also count as acuired item for the trader

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4970

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Township has now been reworked as of v1.1.2
