### ISSUE TITLE
[Bug]: Cannot Mine Onyx Gem Vein 

### ISSUE THREAD

**Issue by Nyxxera** [MelvorIdle/melvoridle.github.io#3103]
### Describe the bug

In Throne of the Herald DLC I found a gem Vein however it will not let me mine the Onyx and the Vein HP is stuck at 69696969 when I click to mine it says mining however nothing happens. Super confused 

### Reproduction Steps

Go to mining 
Scroll down to Onyx Gem Vein
Click the Vein to mine it 

### Expected behaviour

Should be able to mine the gem Vein until it is depleted and disappears. 

### Screenshots

![Screenshot_20221219_143955_Melvor Idle](https://user-images.githubusercontent.com/121058305/208506565-4d490573-fcc2-419f-80bb-ead4a5043835.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4970

### Are you using any mods?

No

**Comment by theshreddernator** [comment]
You need to mine corundimite or higher to discover a vein. When discovering the 0 Will go up in numbers. When the amount higher then 0 you can mine it
