### ISSUE TITLE
[Bug]: Augite rock stays depleted

### ISSUE THREAD

**Issue by MikeG-BE** [MelvorIdle/melvoridle.github.io#3106]
### Describe the bug

Augite rock stays depleted for a few days now, in browser and mobile.

### Save Link

https://melvoridle.com/save/rX6Y7PwT

### Screenshots

![Screenshot_2022-12-20-06-55-18-56_9737de6f3e36012ce6703231c8d3c3a2](https://user-images.githubusercontent.com/101254779/208596511-cb6b09b7-9c7d-4582-b12b-813c37c88490.jpg)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4970

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
We are unable to reproduce this bug, and the save provided is working as intended for me. Please open a new ticket if issue persists.
