### ISSUE TITLE
[Bug]: Restarting township gives 0 new resources

### ISSUE THREAD

**Issue by vschiralli1980** [MelvorIdle/melvoridle.github.io#3107]
### Describe the bug

Restarting township gives 0 new resources. I now cannot build anything at all with my new township

### Reproduction Steps

go to township
township settings
restart my town ---> confirm (game restarts back on main menu)
go back to township, all resources are at 0, no workers and 2,164 dead storage

### Expected behaviour

restarting township should reset it to default settings so you can start rebuilding

### Save Link

https://melvoridle.com/save/uLRvgDEA

### Screenshots

![2022-12-20_17-54-30](https://user-images.githubusercontent.com/121083697/208602573-44707441-c2cb-4c6e-b138-29b496c4467c.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

V1.1.1 (?4970)

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Township has now been reworked as of v1.1.2
