### ISSUE TITLE
 [Bug]: UI disappears in adventure mode

### ISSUE THREAD

**Issue by TooMuchPepsi** [MelvorIdle/melvoridle.github.io#3109]
### Describe the bug

When loading any form of new or old adventure mode  character the UI disappears, shops, inventory, even settings won't open.

### Reproduction Steps

Create or  Load a Adventure Mode character.

### Expected behaviour

Will load with Combat UI but as soon as you click off everything disappears.

### Screenshots

![image](https://user-images.githubusercontent.com/121139951/208793970-17b8018c-0171-48dd-838d-79445ed01c76.png)
![image](https://user-images.githubusercontent.com/121139951/208793989-9d5fbc48-5bf2-44d6-8869-0344f768890b.png)
![image](https://user-images.githubusercontent.com/121139951/208794018-58d1c03b-ac4a-4d21-b1ee-8256b43ece0f.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?74970

### Are you using any mods?

No

**Comment by Blackwolfe5** [comment]
You do have mods installed (otherwise there wouldn't be a mod settings button and no ? in the top right which is from "will I die". I'm 90% certain that you have Skilling Closet installed, which is known to cause this this issue.
