### ISSUE TITLE
[Bug]: Iridium Oricha Ring does not increase Ranged Strength

### ISSUE THREAD

**Issue by eyesLikeSkies** [MelvorIdle/melvoridle.github.io#3110]
### Describe the bug

The Iridium Oricha Ring's description states "...+1 Flat Ranged Strength Bonus per 0.1s Attack Interval...". Equipping it with a ranged weapon has no effect on ranged maximum hit (tested with bow, crossbow, javelin, throwing knives). Ranged accuracy rating is affected according to the rest of the item's description.

### Reproduction Steps

Equip Iridium Oricha Ring to a previously empty slot while engaging in ranged combat.

### Expected behaviour

Receive a bonus to ranged accuracy and ranged strength proportional to Attack Interval.

### Save Link

https://melvoridle.com/save/q6zaXudY

### Screenshots

![image](https://user-images.githubusercontent.com/121303685/209357474-3df9b5b2-5f0a-4933-bc4c-9ae3d5182f51.png)
![image](https://user-images.githubusercontent.com/121303685/209357554-59b16ee8-bf78-4466-abc3-4d32451d96c5.png)
Screenshots show increase in Accuracy Rating but not Maximum Hit.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4999

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue was fixed as of V1.1.2
