### ISSUE TITLE
[Bug]: Character Select Screen UI not loading 

### ISSUE THREAD

**Issue by friskn** [MelvorIdle/melvoridle.github.io#3112]
### Describe the bug

Load screen blank on iOS iPhone 13 mini. Has been happening on all version since ToTH as I only got this phone after ToTH release

### Reproduction Steps

1. Wait until app is sleeping
2. Launch app
3. Screen is only background and all UI elements are invisible or maybe only half the UI is rended
4. Rotate screen and it will load the UI

### Expected behaviour

Load screen should have the whole UI

### Save Link

https://melvoridle.com/save/YSym5YFG

### Screenshots

See comments 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4999

### Are you using any mods?

Yes

**Comment by friskn** [comment]
Uploading IMG_5512.MOV…

added screen recording

**Comment by friskn** [comment]
Screen recording 

https://user-images.githubusercontent.com/121320912/209486377-4f20a0c1-e226-4c95-b92d-0a8965452bea.MOV

**Comment by MelvorIdle** [comment]
We are unable to reproduce this bug. Please open a new ticket if issue persists.
