### ISSUE TITLE
[Bug]: An Error Occured When Rendering 

### ISSUE THREAD

**Issue by Fakecurious** [MelvorIdle/melvoridle.github.io#3114]
### Describe the bug

An error occurred while rendering:
Active Action: undefined
Error Name: TypeError
Error Message: undefined is not an object (evaluating 'menu.updatePassives')
Stack Trace:
@https://ios.melvoridle.com/assets/js/built/agility.js?4999:162:50
forEach@[native code]
renderCourseModifiers@https://ios.melvoridle.com/assets/js/built/agility.js?4999:161:35
render@https://ios.melvoridle.com/assets/js/built/agility.js?4999:136:104
@https://ios.melvoridle.com/assets/js/built/game.js?4999:170:69
forEach@[native code]
forEach@https://ios.melvoridle.com/assets/js/built/namespaceRegistry.js?4999:37:51
render@https://ios.melvoridle.com/assets/js/built/game.js?4999:170:46
loop@https://ios.melvoridle.com/assets/js/built/game.js?4999:186:41
loop@[native code]
Current Equipment:
Helmet: melvorF:Performance_Enhancing_Hat
Platebody: melvorF:Performance_Enhancing_Body
Platelegs: melvorF:Performance_Enhancing_Leggings
Boots: melvorF:Performance_Enhancing_Boots
Shield: melvorD:Dragonfire_Shield
Amulet: melvorD:Amulet_of_Fishing
Ring: melvorD:Ancient_Ring_Of_Skills
Gloves: melvorD:Smithing_Gloves
Cape: melvorF:Max_Skillcape
Summon1: melvorF:Summoning_Familiar_Monkey

No Active Action Information

Modding Enabled. Loaded mods:
Dev
Bypass Agility Costs
Mastery Pool Can Overflow
Will I Die?

Purchased TotH from Steam 

### Reproduction Steps

1. Go to Melvor on iOS
2. Load Local Save/Cloud Save
3. Uninstalled and installed app, repeat 1&2
4. Go to Melvor on Android
5. Repeat 1&2&3
6. Same outcome 

### Save Link

https://melvoridle.com/save/dKTdCBMw

### Screenshots

![EAB51D02-CCFA-4631-8449-862AC25C53ED](https://user-images.githubusercontent.com/121337830/209442615-0dba984d-a992-484f-b9d6-cd724c5a92af.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?1341

### Are you using any mods?

Yes

**Comment by 47Y** [comment]
Try disabling Bypass Agility Costs and see if the issue remains. If it doesn't persist, give your Bypass Agility Costs settings and this can be passed on to the mod author.

**Comment by coolrox95** [comment]
Issue cannot be reproduced when no mods are installed.
