### ISSUE TITLE
[Bug]: Pop ups are not appearing

### ISSUE THREAD

**Issue by leodutram** [MelvorIdle/melvoridle.github.io#3115]
### Describe the bug

The pop ups in game are not appearing for me. So i cant buy or sell anything. I can't build or destroy obstacles at Agility tab. When ever a pop up is suposed to appear, the game just scroll down to the bottom and apears this :
![Screenshot_2](https://user-images.githubusercontent.com/121323314/209444544-635701c9-2b3f-433a-a2f9-234b9ce6c167.png)
![Screenshot_1](https://user-images.githubusercontent.com/121323314/209444546-f1ab5d1e-0d31-4a1a-986c-d7e25f9c3716.png)

I also cant trade at township and cant see monsters drops:
![Screenshot_3](https://user-images.githubusercontent.com/121323314/209850399-1cbbd91a-cfcb-4e72-b01f-9e99ade0b4a5.png)
![Screenshot_4](https://user-images.githubusercontent.com/121323314/209850408-cebe9e1f-9049-41ad-adba-8db6e15a6ca1.png)

I dont know what to do to fix this

### Expected behaviour

It should appear the pop up at the center of teh screen, but it just scroll down and i cant do anything

### Screenshots

![Screenshot_2](https://user-images.githubusercontent.com/121323314/209444602-98092f58-5f91-47f7-b1c6-8ca677f47e73.png)
![Screenshot_1](https://user-images.githubusercontent.com/121323314/209444604-6df272f4-6f89-4666-a5f2-5eb062bf4679.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4999

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
We are unable to reproduce this bug. Please open a new ticket if issue persists.

**Comment by DesoDes** [comment]
Having exactly same issue on steam version.
