### ISSUE TITLE
Bug Account stuck in golbin raid

### ISSUE THREAD

**Issue by AdamDreja** [MelvorIdle/melvoridle.github.io#3116]
### Describe the bug

 time trying golbin raid and after going for a while i decided to leave/escape and after doing so my character remained stuck in it and i can not do anything else in the game, i tried every skill/combat and all i can do is go back to the raid, it also reset some of my skills to level 1 and im really not sure what to do anymore. please dont tell me I'm gonna lose my account because it auto saved on cloud and I thought the download local button works but turns out it doesn't

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ /] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4999

### Are you using any mods?

No

**Comment by AdamDreja** [comment]
![Uploading Screenshot_20221225_014047_Melvor Idle.jpg…]()

**Comment by AdamDreja** [comment]
![Screenshot_20221225_014043_Melvor Idle](https://user-images.githubusercontent.com/104843906/209446776-22111c56-0d65-41f6-8d30-adb00ecb819f.jpg)
![Screenshot_20221225_014039_Melvor Idle](https://user-images.githubusercontent.com/104843906/209446777-a42d6e75-4a1f-4df8-888d-f6829c6cbea5.jpg)

**Comment by MelvorIdle** [comment]
We are unable to reproduce this bug. Please open a new ticket if issue persists.
