### ISSUE TITLE
[Bug]: Spirit Power attacks don't consume Spirit Runes 

### ISSUE THREAD

**Issue by ultimazing** [MelvorIdle/melvoridle.github.io#3119]
### Describe the bug

Spirit Power attacks don't consume Spirit Runes.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4999

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Duplicate of #2971
