### ISSUE TITLE
Golden Golbin does not provide described bonus

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#312]
**Describe the bug**
The Golden Golbin pet does not provide the 1% chance to double loot as per it's description,
The only reference to it in the source code is the unlock condition where petUnlocked[20] is checked.
![image](https://user-images.githubusercontent.com/58208131/88443363-422a0680-cdd5-11ea-9a94-739f3eba6e74.png)

**To Reproduce**
1. Obtain the Golden Golbin Pet
2. Check chanceToDoubleLoot in console, and note that it does not increase by 1%, not even after equipping items.

**Expected behavior**
chanceToDoubleLoot should be increased by 1 when the player owns the Golden Golbin.

**Screenshots**

![image](https://user-images.githubusercontent.com/58208131/88443439-92a16400-cdd5-11ea-8729-7b40a600a1d1.png)

First check to chanceToDoubleLoot was after unlocking the pet, second was after switching gear slots to trigger a stat update.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
