### ISSUE TITLE
[Bug]: Cyclops + Spider Synergy not working

### ISSUE THREAD

**Issue by Flurryous** [MelvorIdle/melvoridle.github.io#3123]
### Describe the bug

Cyclops + Spider synergy is not working at all. The synergy in-game states that "+200% of Poison damage dealt is gained as Slayer Coins." I have tested this on both a slayer assigned monster and a non-assigned monster, no slayer coins are gained when the poison deals damage. 

### Reproduction Steps

1. Equip Cyclops and Spider tablets 
2. Inflict poison on any mob (doesn't matter if it's your current slayer assignment). 
3. Watch the poison status deal damage to the monster but no slayer coin drop notification pops up.

### Expected behaviour

Slayer coins should be gained upon poison damage dealt, as the in-game description for the synergy states.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4999

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.1.2
