### ISSUE TITLE
[Bug]: Unable to launch Steam version offline with expansion

### ISSUE THREAD

**Issue by SkilledAlpaca** [MelvorIdle/melvoridle.github.io#3124]
### Describe the bug

When I attempt to launch `Melvor Idle.exe` directly from `\steamapps\common\Melvor Idle\` the game will hang on "Validating Purchase. If stuck, run game through Steam." 

I was initially able to launch the game in offline mode prior to purchasing the expansion but now that it needs to verify the DLC upon launch I've lost this ability. Would it be possible to add some kind of offline grace period?

### Reproduction Steps

1. Launch `Melvor Idle.exe` directly from `\steamapps\common\Melvor Idle\`

### Expected behaviour

Game opens to save screen without needing to validate the DLC purchase.

### Screenshots

![image](https://user-images.githubusercontent.com/26860324/209992186-5f59c2ba-db6b-4f99-a5eb-85b9b5ccfdc6.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4999

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
The game requires a validation check on load, which means it needs to be opened through Steam.
