### ISSUE TITLE
[Bug]: <Mobile Push Notifications: Can't Connect Device>

### ISSUE THREAD

**Issue by RageguardIV** [MelvorIdle/melvoridle.github.io#3126]
### Describe the bug

The 'Connect Device' feature doesn't seem to work, both on Windows Steam and Android.
It says I am not logged into the cloud, but I am.

### Expected behaviour

Working mobile push notifications

### Screenshots

![Screenshot_20221230_054421_Melvor Idle](https://user-images.githubusercontent.com/121680553/210084712-55bdf5a5-142c-4e5d-906c-c051c2ae50c3.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4999

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.1.2
