### ISSUE TITLE
[Bug]: <Elemental Potion & Astrology Upgrade Not Stacking>

### ISSUE THREAD

**Issue by TheLoach** [MelvorIdle/melvoridle.github.io#3127]
### Describe the bug

Hello,
Small bug that I've noticed: when you use an elemental potion (in my case, level 3) alongside the astrology upgrade to gain extra elemental runes when runecrafting, only the elemental potion works. You will not gain the extra 1 from astrology ever, only from the potion.

Not really a big deal, just something that I noticed is all.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

4999

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.1.2
