### ISSUE TITLE
[Bug]: Warehouse in TOWNSHIP not showing correct storage

### ISSUE THREAD

**Issue by PacoSide** [MelvorIdle/melvoridle.github.io#3128]
### Describe the bug

When upgrading a storehouse to a warehouse, the warehouse only shows as if it had a capacity of 25'000. (Which is the bonus and not the actual total space)

### Screenshots

![Untitled 1](https://user-images.githubusercontent.com/121697299/210115762-f279ba66-9ca0-4600-99c6-8577114df0f7.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4999

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Township has now been reworked as of v1.1.2
