### ISSUE TITLE
Equipped items disappeared while AFK farming Ancient Claw Fragments

### ISSUE THREAD

**Issue by jogonlad** [MelvorIdle/melvoridle.github.io#3129]
### Describe the bug

I have been playing on the phone version and was idling ancient claw fragments, after 3-4 hours I came back and saw that randomly all of my equipped items except my fire cape and paladin gloves have just disappeared. I ended up losing ancient helm (G), Ancient platebody (G), Ancient Platelegs (G), Sunset rapier, Dragonfire Shield, looting amulet, dragon boots (G), Magical ring. 

I know I definitely did not die, so I am confused what happened. I am unable to load a previous cloud save to before going afk. I feel quite annoyed as this has just stolen like a week of progress. Any idea of how I can fix this? Or can my account be rolled back to before this bug/glitch happened? 

Thanks.

### Save Link

https://melvoridle.com/save/pQccdB8G

### Console output

iPhone

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4999

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This is due to loading the demo version of the game.
