### ISSUE TITLE
Circlet of Rhaelyx disappeared when attempted to be equipped

### ISSUE THREAD

**Issue by Deliverancex** [MelvorIdle/melvoridle.github.io#313]
I got my first Circlet drop from mining. Clicking it in the bank provided an equip to set 1 option. Pressing this removed it from the bank and did not equip it to set 1. My current helm in set 1 (chapeau) remained in set 1.

Was using automine, autoreplant, autosell, and autoopen scripts at the time. 

Was in Chrome browser, no other accounts/characters active.

**Comment by MelvorIdle** [comment]
Hotfixed recently
