### ISSUE TITLE
[Bug]: Cannot obtain Beef by cooking.

### ISSUE THREAD

**Issue by KlaytonC** [MelvorIdle/melvoridle.github.io#3131]
### Describe the bug

Cannot cook standard cooked beef. I can obtain perfect beef, but any time I cook a standard beef the popup shows as : +1(0).  Even though I'm getting successful standard beef cooks the total normal cooked beef remains zero. I'm trying to get 25 for township task. Bug initially appeared on PC but clearing cache on pc and switching to mobile did not change the outcome. I have plenty of bank slots left but cooking normal beef does not result in an item added to my inventory. The bug appeared before I purchased Throne of the Herald, but remains still afterwards.

### Reproduction Steps

Cook raw beef over fire in attempt to obtain normal cooked beef for township task.

### Expected behaviour

I need the beef.

### Save Link

https://melvoridle.com/save/qxFmESV8

### Screenshots

![Beef](https://user-images.githubusercontent.com/7993553/210169931-ff2249ef-4582-4b4d-83d7-7ddf4e94cee0.PNG)

### Console output

style.css:1          Failed to load resource: the server responded with a status of 404 ()
cloudManager.js?4999:201 Silent Sign in with JWT
cloudManager.js?4999:201 Validating Melvor Cloud token
cloudManager.js?4999:201 Storing Melvor Cloud Token
cloudManager.js?4999:201 Initializing PlayFab login. Method: customID
cloudManager.js?4999:201 Logging in with Custom ID via PlayFab
cloudManager.js?4999:201 Login with custom ID success
cloudManager.js?4999:201 Getting account info
cloudManager.js?4999:201 Account info retrieved
cloudManager.js?4999:201 Authenticated w/ Melvor Cloud: true
cloudManager.js?4999:201 Authenticated w/ PlayFab: true
cloudManager.js?4999:201 Checking for valid full version
cloudManager.js?4999:201 Checking for valid TotH purchase
cloudManager.js?4999:201 Loading Game Data...
save.js?4999:111 Registered Demo Data.
save.js?4999:111 Registered Full Version Data.
save.js?4999:111 Registered Throne of the Herald Data.
cloudManager.js?4999:201 Initializing Mod Manager...
cloudManager.js?4999:201 Loading Local Saves...
cloudManager.js?4999:201 Loading Cloud Saves...
cloudManager.js?4999:201 Getting saves from playfab
cloudManager.js?4999:201 Saves retrieved
characterSelect.js?4999:5 Loading character selection
cloudManager.js?4999:295 Connected to PlayFab successfully
main.js?4999:15 Game Loaded
cloud.js?4999:29 Synchronising with Cloud
style.css:1          Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4999

### Are you using any mods?

No

**Comment by 47Y** [comment]
You have "Automatically equip food when it is made?" enabled at the top of the Cooking menu. All your Beef is being equipped.

**Comment by KlaytonC** [comment]
Wow, thanks.
