### ISSUE TITLE
[Bug]: Incorrectly showing potion on Smithing screen

### ISSUE THREAD

**Issue by juanjosaurio** [MelvorIdle/melvoridle.github.io#3132]
### Describe the bug

While on the Smithing screen there's an active potion icon present on the top right [image 1], as well as the number of remaining uses/charges [image 1], but in reality there's no smithing related potion active (or inactive) as shown on the potion selection pop-up [image 2] and on the inventory [image 3] (right now: Controlled Heat Potion III, Controlled Heat Potion IV, Herblore Potion IV, Gentle Hands Potion IV and Elemental Potion III).

### Reproduction Steps

1. Log In
2. Go to Smithing
3. Check active potion on top right corner

### Expected behaviour

If there's no applicable active smithing potion, no icon or amount of uses/charges should be displayed.

### Save Link

https://melvoridle.com/save/1Bm0LBqU

### Screenshots

image 1
![image](https://user-images.githubusercontent.com/4203848/210188511-6dac5721-ff49-4a8b-a53d-278c2125f7ab.png)

image 2
![image](https://user-images.githubusercontent.com/4203848/210188516-1a3b2a57-1f3c-47b0-9d11-3124a098b172.png)

image 3
![image](https://user-images.githubusercontent.com/4203848/210188520-5cc17ba0-e6f8-453f-8d05-5cadea5ecc10.png)

### Console output

Silent Sign in with JWT [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?4999)
Cookie “” has been rejected as third-party. [lobster.png](https://cdn.melvor.net/core/v018/assets/media/bank/lobster.png)
Cookie “” has been rejected as third-party. [sardine.png](https://cdn.melvor.net/core/v018/assets/media/bank/sardine.png)
Cookie “” has been rejected as third-party. [herring.png](https://cdn.melvor.net/core/v018/assets/media/bank/herring.png)
Cookie “” has been rejected as third-party. [blowfish.png](https://cdn.melvor.net/core/v018/assets/media/bank/blowfish.png)
Cookie “” has been rejected as third-party. [cavefish.png](https://cdn.melvor.net/core/v018/assets/media/bank/cavefish.png)
Cookie “” has been rejected as third-party. [trout.png](https://cdn.melvor.net/core/v018/assets/media/bank/trout.png)
Cookie “” has been rejected as third-party. [salmon.png](https://cdn.melvor.net/core/v018/assets/media/bank/salmon.png)
Cookie “” has been rejected as third-party. [swordfish.png](https://cdn.melvor.net/core/v018/assets/media/bank/swordfish.png)
Cookie “” has been rejected as third-party. [shark.png](https://cdn.melvor.net/core/v018/assets/media/bank/shark.png)
Cookie “” has been rejected as third-party. [leaping_trout.png](https://cdn.melvor.net/core/v018/assets/media/bank/leaping_trout.png)
Cookie “” has been rejected as third-party. [leaping_salmon.png](https://cdn.melvor.net/core/v018/assets/media/bank/leaping_salmon.png)
Cookie “” has been rejected as third-party. [seahorse.png](https://cdn.melvor.net/core/v018/assets/media/bank/seahorse.png)
Cookie “” has been rejected as third-party. [magic_fish.png](https://cdn.melvor.net/core/v018/assets/media/bank/magic_fish.png)
Cookie “” has been rejected as third-party. [whale_cooked.png](https://cdn.melvor.net/core/v018/assets/media/bank/whale_cooked.png)
Cookie “” has been rejected as third-party. [bread.png](https://cdn.melvor.net/core/v018/assets/media/bank/bread.png)
Cookie “” has been rejected as third-party. [basic_soup.png](https://cdn.melvor.net/core/v018/assets/media/bank/basic_soup.png)
Cookie “” has been rejected as third-party. [potato.png](https://cdn.melvor.net/core/v018/assets/media/bank/potato.png)
Cookie “” has been rejected as third-party. [rock_copper.svg](https://cdn.melvor.net/core/v018/assets/media/skills/mining/rock_copper.svg)
Cookie “” has been rejected as third-party. [rock_tin.svg](https://cdn.melvor.net/core/v018/assets/media/skills/mining/rock_tin.svg)
Cookie “” has been rejected as third-party. [rock_iron.svg](https://cdn.melvor.net/core/v018/assets/media/skills/mining/rock_iron.svg)
Cookie “” has been rejected as third-party. [rock_coal.svg](https://cdn.melvor.net/core/v018/assets/media/skills/mining/rock_coal.svg)
Cookie “” has been rejected as third-party. [rock_silver.svg](https://cdn.melvor.net/core/v018/assets/media/skills/mining/rock_silver.svg)
Cookie “” has been rejected as third-party. [rock_gold.svg](https://cdn.melvor.net/core/v018/assets/media/skills/mining/rock_gold.svg)
Cookie “” has been rejected as third-party. [rock_mithril.svg](https://cdn.melvor.net/core/v018/assets/media/skills/mining/rock_mithril.svg)
Cookie “” has been rejected as third-party. [rock_adamantite.svg](https://cdn.melvor.net/core/v018/assets/media/skills/mining/rock_adamantite.svg)
Cookie “” has been rejected as third-party. [rock_runite.svg](https://cdn.melvor.net/core/v018/assets/media/skills/mining/rock_runite.svg)
Cookie “” has been rejected as third-party. [rock_dragonite.svg](https://cdn.melvor.net/core/v018/assets/media/skills/mining/rock_dragonite.svg)
Cookie “” has been rejected as third-party. [mark_0_256.png](https://cdn.melvor.net/core/v018/assets/media/skills/summoning/mark_0_256.png)
Cookie “” has been rejected as third-party. [mark_1_256.png](https://cdn.melvor.net/core/v018/assets/media/skills/summoning/mark_1_256.png)
Cookie “” has been rejected as third-party. [mark_2_256.png](https://cdn.melvor.net/core/v018/assets/media/skills/summoning/mark_2_256.png)
Cookie “” has been rejected as third-party. [mark_3_256.png](https://cdn.melvor.net/core/v018/assets/media/skills/summoning/mark_3_256.png)
Cookie “” has been rejected as third-party. [mark_4_256.png](https://cdn.melvor.net/core/v018/assets/media/skills/summoning/mark_4_256.png)
Cookie “” has been rejected as third-party. [mark_5_256.png](https://cdn.melvor.net/core/v018/assets/media/skills/summoning/mark_5_256.png)
Cookie “” has been rejected as third-party. [mark_6_256.png](https://cdn.melvor.net/core/v018/assets/media/skills/summoning/mark_6_256.png)
Cookie “” has been rejected as third-party. [mark_7_256.png](https://cdn.melvor.net/core/v018/assets/media/skills/summoning/mark_7_256.png)
Cookie “” has been rejected as third-party. [mark_8_256.png](https://cdn.melvor.net/core/v018/assets/media/skills/summoning/mark_8_256.png)
Cookie “” has been rejected as third-party. [mark_9_256.png](https://cdn.melvor.net/core/v018/assets/media/skills/summoning/mark_9_256.png)
Cookie “” has been rejected as third-party. [mark_10_256.png](https://cdn.melvor.net/core/v018/assets/media/skills/summoning/mark_10_256.png)
Cookie “” has been rejected as third-party. [mark_11_256.png](https://cdn.melvor.net/core/v018/assets/media/skills/summoning/mark_11_256.png)
Cookie “” has been rejected as third-party. [mark_12_256.png](https://cdn.melvor.net/core/v018/assets/media/skills/summoning/mark_12_256.png)
Cookie “” has been rejected as third-party. [mark_13_256.png](https://cdn.melvor.net/core/v018/assets/media/skills/summoning/mark_13_256.png)
Cookie “” has been rejected as third-party. [mark_14_256.png](https://cdn.melvor.net/core/v018/assets/media/skills/summoning/mark_14_256.png)
Cookie “” has been rejected as third-party. [mark_15_256.png](https://cdn.melvor.net/core/v018/assets/media/skills/summoning/mark_15_256.png)
Cookie “” has been rejected as third-party. [mark_17_256.png](https://cdn.melvor.net/core/v018/assets/media/skills/summoning/mark_17_256.png)
Cookie “” has been rejected as third-party. [mark_18_256.png](https://cdn.melvor.net/core/v018/assets/media/skills/summoning/mark_18_256.png)
Cookie “” has been rejected as third-party. [mark_19_256.png](https://cdn.melvor.net/core/v018/assets/media/skills/summoning/mark_19_256.png)
Cookie “” has been rejected as third-party. [woodcutting.png](https://cdn.melvor.net/core/v018/assets/media/pets/woodcutting.png)
Cookie “” has been rejected as third-party. [css](https://fonts.googleapis.com/css?family=Inter:400,500,600,700&subset=latin-ext,cyrillic,cyrillic-ext&display=swap)
Cookie “” has been rejected as third-party. [32595caf09a39ae61af2.css](https://cdn.announcekit.app/32595caf09a39ae61af2.css)
Cookie “” has been rejected as third-party. [32595caf09a39ae61af2.js](https://cdn.announcekit.app/32595caf09a39ae61af2.js)
Cookie “” has been rejected as third-party. [089fa7263b58f3f91e4f.js](https://cdn.announcekit.app/089fa7263b58f3f91e4f.js)
Cookie “” has been rejected as third-party. [97b4c8497227d1fe42a5.js](https://cdn.announcekit.app/97b4c8497227d1fe42a5.js)
Cookie “” has been rejected as third-party. [5d07b7970d085b4b6c64.js](https://cdn.announcekit.app/5d07b7970d085b4b6c64.js)
Cookie “” has been rejected as third-party. [06b9e0434cb12e102999.js](https://cdn.announcekit.app/06b9e0434cb12e102999.js)
Cookie “” has been rejected as third-party. [b872a8aad2b6621d1d81.js](https://cdn.announcekit.app/b872a8aad2b6621d1d81.js)
Cookie “” has been rejected as third-party. [8ab59db31f60f64c4ccf.js](https://cdn.announcekit.app/8ab59db31f60f64c4ccf.js)
Cookie “” has been rejected as third-party. [95c7658c67b8e10221ae.js](https://cdn.announcekit.app/95c7658c67b8e10221ae.js)
Cookie “” has been rejected as third-party. [adb225d8473d24cc114d.js](https://cdn.announcekit.app/adb225d8473d24cc114d.js)
Cookie “” has been rejected as third-party. [aa61e565cd1f07701a21.js](https://cdn.announcekit.app/aa61e565cd1f07701a21.js)
Cookie “” has been rejected as third-party. 2 [client](https://t.announcekit.app/collect/client)
Synchronising with Cloud [cloud.js:29:113](https://melvoridle.com/assets/js/built/cloud.js?4999)
Cookie “” has been rejected as third-party. [cloud.svg](https://cdn.melvor.net/core/v018/assets/media/main/cloud.svg)
[USO] Button detection aborting due to timeout. [injected.js:17:291801](moz-extension://6547bb1f-c8be-4bfb-ac00-1ee4afe2cb72/inline/injected.js)
Cookie “” has been rejected as third-party. [smithing_header.svg](https://cdn.melvor.net/core/v018/assets/media/main/smithing_header.svg)
Cookie “” has been rejected as third-party. [tick.png](https://cdn.melvor.net/core/v018/assets/media/main/tick.png)
[USO] Button detection aborting due to timeout. [injected.js:17:291801](moz-extension://6547bb1f-c8be-4bfb-ac00-1ee4afe2cb72/inline/injected.js)

​

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4999

### Are you using any mods?

No

**Comment by juanjosaurio** [comment]
I used "Inspect" button on Firefox to copy HTML of the element containing the potion logo and number:

<div class="dropdown d-inline-block ml-2">
<button type="button" class="btn btn-sm btn-dual text-combat-smoke" id="page-header-potions-dropdown" aria-haspopup="true" aria-expanded="true">
<img class="skill-icon-xxs" id="header-potion-image" src="https://cdn.melvor.net/core/v018/assets/media/bank/potion_smithing_iv.png">
<span class="badge badge-danger badge-pill" id="header-potion-charges">48</span>
</button>
</div>

**Comment by coolrox95** [comment]
You don't have any potions in the bank, but you do have some charges left on a potion that was already consumed.
