### ISSUE TITLE
[Bug]: <title>Meteorite Spellcaster Ring passive does not add spell damage to Meteor Shower Archaic Spell

### ISSUE THREAD

**Issue by Kvothe-irl** [MelvorIdle/melvoridle.github.io#3133]
### Describe the bug

The Meteorite Spellcaster Ring passive is as follows:

> When equipped with Meteorite Staff: **+50 minimum Spell damage when using Meteor Shower Archaic Spell** and +20% Magic Accuracy Bonus.

However, the Meteor Shower Archaic Spell deals damage based on **Maximum** hit, not Minimum, so the passive set bonus does not add damage to the spell. 

Meteor Shower currently deals the same damage with no ring equipped as it does with the Meteorite Ring. Other rings which provide magic damage bonuses, such as warlock ring and burning madness ring, add damage to Meteor Shower as expected.

### Reproduction Steps

1. Equip Meteor Staff and Ring
2. Equip Meteor Shower spell
3. Attack an enemy and note damage dealt
4. Unequip Meteorite Ring
5. Attack an enemy and note damage dealt

### Expected behaviour

The ring's passive set bonus is probably intended to increase the Meteor Shower spell's base Spell Damage by 50 (90 -> 140). 

Or maybe it's intended to increase the spell's Maximum hit (~500 -> ~550 with my setup).

### Which platforms are you experiencing this bug on?

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4999

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.1.2
