### ISSUE TITLE
[Bug]: Game crash on save load with DLC

### ISSUE THREAD

**Issue by JocaDoka** [MelvorIdle/melvoridle.github.io#3135]
### Describe the bug

The game instantly crashes when attempting to load. Game worked fine until I purchased the DLC.

### Save Link

https://melvoridle.com/save/A3w8MUGj

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4673

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
We are unable to reproduce the issue with the provided save. If the issue persists, please open a new ticket. Thank you.
