### ISSUE TITLE
[Bug]: Android app doesn't show Slayer Task on Combat page

### ISSUE THREAD

**Issue by pmunn** [MelvorIdle/melvoridle.github.io#3136]
### Describe the bug

The combat tab on the Android app doesn't show the Slayer Task.  The Play Store says it was last updated 2022-10-11.

### Reproduction Steps

1. Open the Melvor Idle RPG app.
2. Tap on the hamburger (3 lines) menu to open it.
3. Under the Combat section, tap on Combat Level XX where the XX is your combat level.  The Combat page appears.
4. Scrolling down you can't see any Slayer Task options or the current Slayer Task.
5. Signing in the current using Firefox for Android 108.1.0 shows the Slayer Task.
6. The current Chrome browser on Android 108.0.5359.128 also shows the Slayer Task.

### Expected behaviour

One expects to be able to see and interact with the Slayer Task using the app.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5023

### Are you using any mods?

No

**Comment by PolVanieuwegem** [comment]
You can see your slayer task by clicking on the show/hide Player Container button and going to the slayer tab
![Screenshot_20230119_013741_com malcs melvoridle](https://user-images.githubusercontent.com/123036748/213328949-beb20a45-b9bb-4374-ac8b-9ca8559c8d7e.jpg)
