### ISSUE TITLE
[Bug]: Agility bug

### ISSUE THREAD

**Issue by Baraz02** [MelvorIdle/melvoridle.github.io#3137]
### Describe the bug

Hey
So at the Agility option I have a bug that labels the obstacles I was training as NaN instead of showing what level I am on whit them, also I am not able to continue training them.
I’m experiencing this issue only for those obstacles that I trained at that time when this bug occurred.
![01C1D98D-3B5D-49BE-A0B1-83828A1BB2E0](https://user-images.githubusercontent.com/121897728/210428158-5f5c75eb-5adf-41c0-b2aa-ed3bbbe42455.png)
![3E34B4D7-F76C-4184-B640-E2842C78BA44](https://user-images.githubusercontent.com/121897728/210428169-6d6af434-2cdb-4d12-8384-80f1594757e9.png)
![2BD52DA0-BB7A-475E-BC19-80185341A844](https://user-images.githubusercontent.com/121897728/210428174-8377ab99-6bd2-4494-9d7a-ae272d6b9af4.png)
![278EE5C1-4F27-4447-8157-97238847DC99](https://user-images.githubusercontent.com/121897728/210428179-e66b4b9d-bf2f-483b-a99a-fa646cd8e75c.png)
![37450CC7-E952-4AD8-9A70-7105A5A49514](https://user-images.githubusercontent.com/121897728/210428181-4a71426c-d91a-4754-96bb-cf2047de725f.png)
![38D7445E-517B-43CF-BDD4-BC69B8D99B96](https://user-images.githubusercontent.com/121897728/210428182-d80bc71d-70f9-4ebc-abc1-30e062b18456.png)
![13B41CA0-0B96-43D9-8925-CFC0C6BB04F4](https://user-images.githubusercontent.com/121897728/210428183-9951ddc2-67bd-4581-84b5-d63168a6d219.png)

### Expected behaviour

It happened as I was opening the game once, I had these agilities on for training offline, and as I logged back into my account it was this way.

### Save Link

https://melvoridle.com/save/tqIbG9bG

### Screenshots

![C75815EA-3E21-468E-93D5-E8A8732F09C1](https://user-images.githubusercontent.com/121897728/210429035-df5e9427-d83c-4b91-bf98-c2a6563d15c5.png)
![F7D844B1-6A49-4693-9061-33CA2EA443D4](https://user-images.githubusercontent.com/121897728/210429042-fce6bfac-e3a5-4612-863a-0cd96ff32335.png)
![8A010065-3A22-4875-948D-A86ABD58EF0E](https://user-images.githubusercontent.com/121897728/210429045-f90eeed8-d6b6-4fd1-9c1e-040e766884d0.png)
![11BDBC68-01E5-49F3-BF9A-7203CEAA6A95](https://user-images.githubusercontent.com/121897728/210429049-22775851-ddc4-417f-8d75-3a3ef80ae224.png)
![1CBD52A4-3ADC-467F-890C-EE1607B50BF0](https://user-images.githubusercontent.com/121897728/210429056-761e0657-bb24-4bbe-8735-6582b2d2b826.png)
![8F84DF09-C248-4419-BB89-D1ECF4B7D1E2](https://user-images.githubusercontent.com/121897728/210429059-19a84ced-1112-41fc-aae1-29e580f900c5.png)
![39092294-972E-4EB7-B040-E6E321B26E5E](https://user-images.githubusercontent.com/121897728/210429060-993b50d2-aa41-47c6-a739-b00546b1e89d.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5023

### Are you using any mods?

No

**Comment by ekuland** [comment]
I ran a quick script for you to... make the save usable
but without knowing your current levels, I just set them to max mastery and max pool.

https://melvoridle.com/save/5bmP0yXk

**Comment by Baraz02** [comment]
Ohh thank, the issue was solved now it’s working!
Thanks for the quick help!!
