### ISSUE TITLE
[Bug]: <Neither farming skill capes show in the quick equip menu>

### ISSUE THREAD

**Issue by Mazurcka** [MelvorIdle/melvoridle.github.io#3138]
### Describe the bug

For the other skills that my character has skill capes for, those skill capes show up in the quick equip menu, but neither of the farming skill capes show in the farming quick equip menu.

### Reproduction Steps

1. With a farming skill capes or superior skill cape in the bank, navigate to the farming skill.
2. Open the quick equip menu.

### Expected behaviour

The farming skill capes should be available options to select.

### Screenshots

![37691DF0-8EFF-407E-9D92-DF07B7197CC8](https://user-images.githubusercontent.com/48336729/210634295-aef1e8ee-5268-4d94-828a-02c9cb8d317f.jpeg)
![D587948A-DFFB-4153-A0BF-B2F40786EADC](https://user-images.githubusercontent.com/48336729/210634331-c8e59f81-2066-4819-b428-3558165791ac.png)
![47B74CA8-F941-463F-94EF-D8E7FF009A1D](https://user-images.githubusercontent.com/48336729/210634354-c9426878-d5e1-4f51-91ac-14c2bf5328ce.png)
![8511E882-69A9-4D59-961D-7483A2C3333B](https://user-images.githubusercontent.com/48336729/210634372-3ecf90c5-e7c5-42fe-847e-f7ca1843a410.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5023

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Quick equip items are custom defined by the player. This can be done by selecting the item in the Bank, and adding it to the quick equip section within the Gear icon
