### ISSUE TITLE
Prayer pet does not behave as intended

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#314]
**Describe the bug**
The Prayer pet Monk-ey currently has some issues in it's implementation. Firstly it causes a 5% chance that prayerpoints that are being added are negated. Secondly it overrides the effect of divine potions and causes them to not function.

![image](https://user-images.githubusercontent.com/58208131/88444709-9e902480-cddb-11ea-9e8f-de0feb4d4a3c.png)

Since the pet doesn't check the bury flag it can negate prayer points. Since the potion check is in an else if statement, it's code will never execute if the pet is owned.

Other issues I've found related to this function: 
When the Bone Necklace calls it, the bury flag is not set to true, meaning herblore potions and the pet could negate the prayer point gains from that.
![image](https://user-images.githubusercontent.com/58208131/88444849-8e2c7980-cddc-11ea-897b-e19faaad4802.png)
This call is inside of dropBones().

The call to updateHerbloreBonuses never checks if the original quantity given to the function is 0. This is the source of the divine potion charges bug, as updatePrayerPoints is called in several places with 0 quantity. See my comment on issue  #250 for more info.

**Comment by MelvorIdle** [comment]
Fixed hopefully
