### ISSUE TITLE
[Bug]: Royal Toxins Spear - Block Bonus issue

### ISSUE THREAD

**Issue by Xelores** [MelvorIdle/melvoridle.github.io#3140]
### Describe the bug

The spear, unlike other serious weapons (not made for fun), is the only one that has a Block Bonus with a very large negative value, as much as -198. This looks like a bug with inadvertently inserting a minus sign. As a result, this results in a huge negative Accuracy Rating value and therefore a negative chance to hit. The weapon doesn't look like it was made for a joke because it has a complex bonus that fits into the "meta" of the Throne of The Herald expansion, so I dare say this is a bug I want to report. I've attached a screenshot of the stats.

### Screenshots

![obraz_2023-01-04_231843519](https://user-images.githubusercontent.com/121982650/210660668-3d3f824d-1fc6-4c02-a6ad-6b7ef272f3bc.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [x] Mobile App (Android)
- [x] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

5023

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This statistic is intended for this specific item.
