### ISSUE TITLE
[Bug]: Repeated 'Buy limit of 88 reached' for Hardcore save (Low Impact: Cosmetic)

### ISSUE THREAD

**Issue by hexnaught** [MelvorIdle/melvoridle.github.io#3141]
### Describe the bug

When already owning all bank slots on a hardcore character, purchasing other items in the shop causes the help/error text regarding bank slot limit reached to be repeated.

I believe this is just a **cosmetic** and same session bug, as reloading the game/save removes the duplicated text and it raises no issues regarding shop functionality.

### Reproduction Steps

1. Buy all 88 bank slots
2. Purchase other things from the shop
3. See bank slot help/error text of 'Buy limit of 88 reached.' is repeated

### Expected behaviour

1. By all 88 bank slots
2. Purchase other things from the shop
3. The 'Buy limit of 88 reached.' is not repeated.

### Screenshots

![image](https://user-images.githubusercontent.com/1098786/210764269-c87f3378-dc85-42b9-bbde-be39f6900975.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5023

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was fixed as of V1.1.2
