### ISSUE TITLE
[Bug]: <Smithing Gloves missed>

### ISSUE THREAD

**Issue by hikaru-gg** [MelvorIdle/melvoridle.github.io#3142]
### Describe the bug

Smithing Gloves is missed, but I still can buy it in the shop.

### Reproduction Steps

1. go to shop buy the Smithing Gloves the number is added
2. but there are no Smithing Gloves anywhere

### Save Link

https://melvoridle.com/save/JZUhxEWd

### Screenshots

![image](https://user-images.githubusercontent.com/122034690/210809384-23af3369-0873-4b45-8f7e-6a623d77c465.png)
![image](https://user-images.githubusercontent.com/122034690/210809540-eb0c3cdf-d939-4bf7-940f-c751abc5478d.png)
![image](https://user-images.githubusercontent.com/122034690/210820674-7ddddd5b-c100-451a-aa44-4205cb433911.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5023

### Are you using any mods?

No

**Comment by coolrox95** [comment]
You can only ever own one pair of smithing gloves. Subsequent purchases simply add more charges to be used.

Your smithing gloves are in the 2nd equipment set.
