### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by ramses4560** [MelvorIdle/melvoridle.github.io#3145]
### Describe the bug

im stuck in goblin raid. and now my account is rolled back to lvl 1 all combat stats? i dont understand anything how or what is happening-

pls help

### Reproduction Steps

dont know 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5023

### Are you using any mods?

No

**Comment by xanderput** [comment]
Could you share your save through a save link? I can try to fix your save.

**Comment by ramses4560** [comment]
https://melvoridle.com/save/vDddQEPf

**Comment by xanderput** [comment]
Here you go: https://melvoridle.com/save/EK1Q5kfG

For future reference, I used `game.clearActiveAction()` to fix it.

**Comment by ramses4560** [comment]
Thank you sir.
