### ISSUE TITLE
[Bug]: Tier IV performance enhancing potion decrease interval more than they should

### ISSUE THREAD

**Issue by EmilieBird** [MelvorIdle/melvoridle.github.io#3149]
### Describe the bug

Using a tier IV performance enhancing potion significantly decreases the interval of agility obstacles. Activating a tier IV performance enhancing potion more than halves the interval on obstacles, instead of the 12% that's stated on the item card.

### Reproduction Steps

1. Activate performance enhancing potion
2. Watch laps go brrrr

### Expected behaviour

Potion should only decrease the interval by 12%, it decreases it way more. 

### Save Link

https://melvoridle.com/save/YKUu9rOU

### Screenshots

https://i.imgur.com/ZFjW1By.png

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5023

### Are you using any mods?

Yes

**Comment by lassus** [comment]
Do you have much Mastery in your obstacles? You get every 10 mastery "-3% Agility Interval for this Obstacle only" If your masteries for your current obstacles are for example over 80 then your initial agility intervall modifier is about -73% (instead of -49%) and with potion -85% (not -61%)
