### ISSUE TITLE
Auto switch to Runecrafting after stop doing Alt. Magic

### ISSUE THREAD

**Issue by MiccWan** [MelvorIdle/melvoridle.github.io#315]
**Describe the bug**
When deselecting a Alt. Magic skill by clicking on the currently doing one, it automaticly start doing Runecrafting

**To Reproduce**
1. Select any Runecrafting skill e.g. `CREATE Air Rune`
2. Select and start any Alt. Magic skill e.g. `CAST Just Learning`
3. Select it again

The Alt. Magic skill will stop and Runecrafting will start right after it stops(like start producing air rune).

**Expected behavior**
It should not start Runecrafting.

**Screenshots**

Was doing `CAST Just Learning`
![image](https://user-images.githubusercontent.com/16610454/88462773-75a58780-cee0-11ea-8965-86cafa7b079c.png)

It starts producing air rune after click on the button of `Just Learning`
![image](https://user-images.githubusercontent.com/16610454/88462777-7dfdc280-cee0-11ea-9722-2cef869b232f.png)

**Browser**
Chrome 84.0.4147.89 64bit

**Console output**
![image](https://user-images.githubusercontent.com/16610454/88462853-0ed49e00-cee1-11ea-9c9d-299cd4513975.png)

**Are you using any scripts?**
Nope.

**Comment by MelvorIdle** [comment]
Believed to be fixed
