### ISSUE TITLE
[Bug]: Octopus + Pig synergistic isn't working

### ISSUE THREAD

**Issue by dev-eugene99** [MelvorIdle/melvoridle.github.io#3150]
### Describe the bug

When fishing with Octopus + Pig, the Combat UI Synergy lights up blue, and hover over says "+75% chance to gain 1 cooked version of a fish when fishing".

I've already bought Divine Fishing Rod, so I expected to gain around 85% total of cooked version of the fish.

However, when I fished offline for about 9.5 hours, with this pair of Familiar's Marks equipped (I was fishing lava fish) and came back, the report showed that I fished ~68k raw lava fish, but only received ~6k lava fish.

This is only around 10%, which is the bonus I got from the Divine Fishing Rod.

### Reproduction Steps

1. go to "Fishing"
2. click on "View Summoning Synergy Search"
3. Make sure that there's at least 100,000 of Octopus and Pig Familiar Mark individually
4. Select Octopus + Pig Synergy, the one with the text "+75% chance to gain 1 cooked version of a fish when Fishing"
5. after that, the background behind number in the octopus and pig familiar mark should turn from grey to green.
6. click "X" in the "Search Summoning Synergies" window
7. scroll down to "Magma Lake" area under fishing
8. click on "Raw Lava Fish"
9. click "Start Fishing"
10. close Melvor Idle to let it idle for ~10 hours
11. come back and check the fishing summary.

### Expected behaviour

I expected to get around 85% of cooked version of the magma fish, which I would have expected at least 50k cooked lava fish when I came back for the 68k raw lava fish i got.

### Save Link

https://melvoridle.com/save/Ol0mnX0x

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5023

### Are you using any mods?

No

**Comment by 47Y** [comment]
With quick math, those numbers add up properly. You are gaining (on average) around 9 raw fish per action thanks to all your bonuses. So for every 9 raw fish, you get 0.85 cooked fish. For 68,000 raw, that's roughly 6,400 cooked. Accounting for rounding and randomness, ~6k seems perfectly fine.

**Comment by dev-eugene99** [comment]
ah ya, I didn't take my bonuses into consideration.  Thanks for that.
