### ISSUE TITLE
[Bug]: <Royal Toxins Spear using the wrong special attack in Golbin Raid>

### ISSUE THREAD

**Issue by TameshiTribe** [MelvorIdle/melvoridle.github.io#3151]
### Describe the bug

After choosing the Royal Toxins Spear in Golbin Raid, the special attack should be Piercing Toxic Strike but the special attack used is Shade Summon. I don't have anything equipped that should proc Shade Summon. Thanks for your time I thoroughly enjoy the game!

pic for reference:
![Screenshot_20230108_033606](https://user-images.githubusercontent.com/122235584/211221246-32b69ba1-f220-4d5a-8e0f-ea8331501730.png)

### Reproduction Steps

1. Go to Golbin Raid
2. Get Royal Toxins Spear equipped
3. Check for Special attack used
4. See bug

### Expected behaviour

Expect to see Piercing Toxins Strike as Special attack

### Save Link

https://melvoridle.com/save/J2WEBHA0

### Screenshots

![Screenshot_20230108_033606](https://user-images.githubusercontent.com/122235584/211221448-1edf07ba-f8e3-4075-a9ca-9b26a3bcc3e4.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5023

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This is due to you selecting an "ALT" item which provides a random special attack.
