### ISSUE TITLE
[Bug]: Mining Issue

### ISSUE THREAD

**Issue by Thezoog** [MelvorIdle/melvoridle.github.io#3152]
### Describe the bug

Anytime I try to mine anything, after the first tick, it starts mining rune essence instead.

### Reproduction Steps

1. Go to mining
2. Start mining anything.
3. It mines one tick
4. Changes to Rune Essence

### Expected behaviour

I expected it to keep mining the ore I selected.

### Save Link

https://melvoridle.com/save/YZjJRHED

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5023

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
I am unable to reproduce the bug with the save provided. If the issue persists, please open a new ticket. Thank you.
