### ISSUE TITLE
[Bug]: No image for dead crop.

### ISSUE THREAD

**Issue by lukascaplikas** [MelvorIdle/melvoridle.github.io#3153]
### Describe the bug

When crop dies no image displays. Only pink with white dots.

### Reproduction Steps

1. Plant seed
2. Wait it to die.
3. Image displayed broken.

### Expected behaviour

Normal image of dead crop.

### Screenshots

![2023-01-10 17_52_20-#melvor-chat _ Melvor Idle - Discord](https://user-images.githubusercontent.com/86235856/211598544-289dbbc0-1f44-4906-ba26-846ddc81beed.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5023

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.1.2
