### ISSUE TITLE
[Bug]: Township - Desert bonus not applying to Miner’s Estate

### ISSUE THREAD

**Issue by CantTouched** [MelvorIdle/melvoridle.github.io#3154]
### Describe the bug

In the desert, mining camps are supposed to be more effective than when they are placed in other areas. This is presumably to account for the clothing cost associated with them. 

This environmental bonus is not applying properly when upgrading from a Mining Quarry to the T4 Mining Estate. 

### Reproduction Steps

1. Build a mining quarry in desert
2. Take note of how much stone/tick you are earning
3. Upgrade the quarry to a Mining Estate
4. Notice that the amount of stone mined has gone DOWN because the enviro bonuses magically disappeared

### Expected behaviour

We would expect the desert’s enviro bonuses to stay attached to the mining quarry and the amount of stone mined per tick would increase after an upgrade to the expensive t4 mining quarry.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5023

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Township has now been reworked as of v1.1.2
