### ISSUE TITLE
[Bug]: I bought 2 gem gloves and recived one

### ISSUE THREAD

**Issue by ImAWaffle** [MelvorIdle/melvoridle.github.io#3155]
### Describe the bug

I paid 1,000k for 2 gem gloves and I only revived one.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

Can not find

### Are you using any mods?

No

**Comment by ekuland** [comment]
You can only ever have one glove.
Charges are stacked on the one glove for the 2 purchases, though.

**Comment by ImAWaffle** [comment]
Oh okay, thank you for letting me know!
