### ISSUE TITLE
[Bug]: <title> my mobile version's lg changed

### ISSUE THREAD

**Issue by Cubiiiiii** [MelvorIdle/melvoridle.github.io#3156]
### Describe the bug

My lg version changed to something that looks like chinese. My steam version is ok in english.

### Screenshots

![Screenshot_2023-01-14-17-33-39-654_com malcs melvoridle](https://user-images.githubusercontent.com/122689186/212483696-85d35e18-8d4c-4820-a35f-702bb6a68a77.jpg)
The lg version should be english. Please help to change it into english

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

Dont know

### Are you using any mods?

No

**Comment by coolrox95** [comment]
You can change the language by scrolling to the bottom of the page and clicking on the second blue link above Melvor Idle.

![image](https://user-images.githubusercontent.com/58208131/227706286-4b099e30-c478-4623-8f2a-2bfc871046c8.png)
