### ISSUE TITLE
Crafting EXP anomaly

### ISSUE THREAD

**Issue by Pyrrhic76** [MelvorIdle/melvoridle.github.io#3157]
### Describe the bug

The major issue is the significant exponential exp increase you get from crafting elderwood armor as opposed to other types. The base gain from bracers to body is 1800 ish exp up to 5500. With only a base increase of resources spent by 1/3. Compared to something like black dragon hide. Bracers at 90 and body at 280 with a 3x increase in base cost of resources. This will lead to a significant increase in how fast you can move from lvl 104-120.

### Expected behaviour

Increase the base cost of hardwood armors comparable to other types of armor in the game. Bracers: 100 logs, 
legs: 200
Shield: 200
Body: 300

### Screenshots

![Screenshot_20230114_172312_Melvor Idle](https://user-images.githubusercontent.com/112620751/212501349-ea5833d2-ea6f-4807-931a-955fc01052ac.jpg)
![Screenshot_20230114_172301_Melvor Idle](https://user-images.githubusercontent.com/112620751/212501353-aae33b03-12e8-4d51-afb8-e9dcf883e532.jpg)
![Screenshot_20230114_172235_Melvor Idle](https://user-images.githubusercontent.com/112620751/212501356-0adc56aa-4675-4669-b1ba-4443c0ba3145.jpg)
![Screenshot_20230114_172219_Melvor Idle](https://user-images.githubusercontent.com/112620751/212501360-aa27f0e4-4dd4-4a9b-ae5b-cb6aacebee0b.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5023

### Are you using any mods?

No

**Comment by coolrox95** [comment]
This issue tracker is for bug reports only. Suggestions can be made on our official discord server. [https://discord.com/invite/melvoridle](https://discord.com/invite/melvoridle)
