### ISSUE TITLE
[Bug]: Scrolling issue when swiping to menu on mobile

### ISSUE THREAD

**Issue by KuAwMa** [MelvorIdle/melvoridle.github.io#3158]
### Describe the bug

On mobile, when swiping right to view the menu which allows you to go to the shop, bank, any skill, etc. most of the time, I will not be able to scroll up or down. It shows the scroll bar moving but it may be the scroll bar for whatever page is underneath the main menu. 

This issue never happens when I use to three line menu select button at the top left of the page. 

### Reproduction Steps

1. Be on any skill, bank, or shop page. 
2. Swipe right to access the main menu.
3. Attempt the scroll

### Expected behaviour

You will attempt to scroll and I scroll bar will move, but the menu will not actually scroll up or down. 

### Save Link

https://melvoridle.com/save/sGCJztZk

### Screenshots

![FEC8032F-6B19-4966-94C4-20A5CD9E34E8](https://user-images.githubusercontent.com/116080078/212540805-48852715-27ce-4bb1-abbd-7c664fa4cd04.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5023

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
I am unable to reproduce this bug. If the issue persists, please submit another ticket so we can look deeper into the issue
