### ISSUE TITLE
[Bug]: Can't choose first save file on main screen

### ISSUE THREAD

**Issue by Autoham** [MelvorIdle/melvoridle.github.io#3159]
### Describe the bug

The game won't allow me to access my first save file, when I click it the information disappears, and reappears when I click it again

### Reproduction Steps

1. Try to click first save

### Expected behaviour

To login to my first save file

### Screenshots

![7BDC5220-FE2E-472F-BC75-BCF9CB10881B](https://user-images.githubusercontent.com/122752230/212566596-f2c153a0-ec80-4552-a73e-dcc67fa43c5f.png)
![EEA891E0-51BA-46C9-B39A-242C0908B04A](https://user-images.githubusercontent.com/122752230/212566597-406f38b9-ae94-46ec-a139-0dfabafc0d6e.png)

[Here is a video of the bug](https://files.fm/u/vfy9vbeg8)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5023

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
PLease update your iOS to the latest available version if possible
