### ISSUE TITLE
Unequip ammo bug

### ISSUE THREAD

**Issue by fewfre** [MelvorIdle/melvoridle.github.io#316]
**Describe the bug**
When replacing a ranged weapon that requires ammo/weapon slot in a combat set other than the currently equipped one, it will remove whatever is in the ammo slot of the current combat set. If you then switch to another set and then back, it will display an empty ammo slot with a quantity of how much ammo you had before. Equipping something in the slot then adds that quantity to the equipped ammo.

**To Reproduce**

1) Have something equipped in the ammo slot of a combat set.
2) Have a ranged weapon that requires both ammo slot and weapon slot equipped in another non-active set (javelins, knives, etc.).
3) Equip a weapon in the non-active weapon set. It will remove the ranged weapon from the non-active set, as well as removing the ammo in your current active set.
4) Putting something in that ammo slot will add the previous amount to the new ammo.

Example:
1) Equip 10 iron arrows in set 1.
2) Equip dragon javelins in set 2.
3) While on set 1, equip a weapon to set 2. Set 1's ammo will disappear and the count will say 0. (Note: If you switch between sets, the count will update to whatever the previous quantity was.)
4) Equip 10 dragon javelins in set 1. It will now be 20 javelins.

**Expected behavior**
Item should be unequipped from the other set and current set's ammo should remain unaffected.

**Browser**
Google Chrome, Version 83.0.4103.116 (Official Build) (64-bit)

**Console output**
www.googletagmanager.com/gtag/js?id=UA-129674422-1:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js?threshold=16:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
assets/media/shop/assets/media/shop/perpetual_haste.svg:1 Failed to load resource: the server responded with a status of 404 ()
cdn-cgi/bm/cv/2172558837/api.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
save.js?315:461 Not required to backup
save.js?315:64 Loading Save Game...
save.js?315:224 Save Game Loaded...
smithing2.js?299:220 Loading Smithing...
mastery.js?295:187 Updating Masteries
mastery.js?295:23 Loading Masteries...
main.js?385:269 Game Loaded
cloud.js?307:250 1
DevTools failed to load SourceMap: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
No

**Other**
May be related to https://github.com/MelvorIdle/melvoridle.github.io/issues/297

Reporting on behalf of my friend 𝒞𝒪ℙℙℇℛℱ𝒪ⅈℒ (Copperfoil) since they don't have a github account

**Comment by MelvorIdle** [comment]
Thanks for the report. Hopefully I have tracked this down and fixed it for the upcoming update.
