### ISSUE TITLE
[Bug]: <Potion tier not switching>

### ISSUE THREAD

**Issue by FreeWeegee** [MelvorIdle/melvoridle.github.io#3161]
### Describe the bug

In the herblore skill it is not letting me make lower tier potions. I try to click a lower tier and it says it requires mastery lvl 1 when my mastery lvl being much higher than that.

### Reproduction Steps

..

### Expected behaviour

let me make tier 1 potion

### Screenshots

![image](https://user-images.githubusercontent.com/122845440/212793289-c727e773-a1ab-466b-999e-a3b0b200ab9e.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5023

### Are you using any mods?

No

**Comment by ekuland** [comment]
You cannot make lower tier potions than you've earned.

You can use the "Herblore Potion" to get a random tier potion of the one you're crafting.

**Comment by FreeWeegee** [comment]
oh oops that kinda lame  thanks
