### ISSUE TITLE
[Bug]: <title> thieving shorts missing from thieving quick equip menu

### ISSUE THREAD

**Issue by Mazurcka** [MelvorIdle/melvoridle.github.io#3163]
### Describe the bug

The thieving shorts are missing from the thieving quick equip menu

### Reproduction Steps

Acquire thieving shorts
Open the thieving quick equip menu

### Expected behaviour

Thieving shots should be among the items in the list

### Screenshots

![7F147CFD-13F6-4365-900E-1B6ADE130725](https://user-images.githubusercontent.com/48336729/212980621-95391a20-8fa9-4702-8d2c-0fa93ef2b9be.jpeg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5027

### Are you using any mods?

No

**Comment by ekuland** [comment]
Zero expansion items were added to the quick equip menu automatically because you can change them yourself.
Bank > Item > Cog > switch for skill.

**Comment by coolrox95** [comment]
Quick equip items are custom defined by the player. This can be done by selecting the item in the Bank, and adding it to the quick equip section within the Gear icon
