### ISSUE TITLE
[Bug]: <title>Mark pop up on start

### ISSUE THREAD

**Issue by aolson078** [MelvorIdle/melvoridle.github.io#3166]
### Describe the bug

Sorry this isnt a bug, but I wasn't sure where to post comments. Whenever I open the game and I get a bunch of mark pop ups, its really obnoxious to have to click through 50 of them. Is there anyway to condense that?

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

1.1.1

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
This issue tracker is for bug reports only. Suggestions can be made on our official discord server. [https://discord.com/invite/melvoridle](https://discord.com/invite/melvoridle)
