### ISSUE TITLE
[Bug]: combat lagg

### ISSUE THREAD

**Issue by warlordPalace** [MelvorIdle/melvoridle.github.io#3167]
### Describe the bug

sometimes in combat the game freezes for 3+ seconds, then the results of the combat in the time it was frozen appear all at once.
when it starts with these short freezes, they do not stop until the game is moved to a non combat activity (or idle)
the rest of the apps on the PC are NOT affected.
the PC IS affected, the CPU usage for melvor shoots very high, even over 30% (in the 5 minutes that i observed it)

i observed this behavior before installing mods AND after

### Save Link

https://melvoridle.com/save/cqgpavQL

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5027

### Are you using any mods?

Yes

**Comment by RyanB-1** [comment]
Just wanted to verify I'm having the same issue, as well as at least some people on the steam community forums. I'm on the same version as originally posted and will post a link to my save below. The issue gets worse the longer the game has been running, or more specifically, how long it has gone without a cloud save. I feel confident in saying it did not occur before the expansion pack was released.

Save:
https://melvoridle.com/save/T0jj4vMJ

**Comment by kellewic** [comment]
Same here. Once a cloud save is done, the lag clears up. I hit the Force Save button and lag is gone, but then just starts to build up again.

**Comment by Djag975** [comment]
Hello there,
Having the exact same issue since ToTH. The more time goes, more the freeze in combat is. Around 1h without cloud save the freeze is like 1.5s. With auto-save or not, if i don't hit the Force save button, the freeze just increase.
On Steam, no mods. (never installed one)
Thanks Malc for the game! Hope you find a solution to this one, kind of a pain tbh when i have to do some combat for some time now :(

**Comment by starduel** [comment]
I am having the same problem at the start of the combat, and the force save seems to fix it. It only happens after having the game open for a while, and it happens in any menu, as long as combat starts in the background.
