### ISSUE TITLE
Superheat I uses the wrong combination runes

### ISSUE THREAD

**Issue by iceclimorz** [MelvorIdle/melvoridle.github.io#317]
**Describe the bug**
The Superheat I magic spell uses the lava combination rune instead of the steam combination rune when using combination runes.

**To Reproduce**
1. Select Alt Magic
2. Go to Superheat I
3. Scroll over it or select it and select "Use Combination Runes?"
4. Lava runes are incorrectly listed as the combination rune used for the spell, and the spell cannot be cast while holding steam runs but not lavas.

**Expected behavior**
What's supposed to happen is the spell is supposed to use steam runes, as water + fire = steam, not water. This is the case for every other superheat spell except this one.

**Screenshots**
https://cdn.discordapp.com/attachments/431621496646008833/736693193218982001/unknown.png

**Are you using any scripts?**
No

**Comment by MrFluffums** [comment]
Superheat 2 uses the combination rune (Steam) for the Superheat 1 runes (Water+Fire), and Superheat 1 uses the combination rune (Lava) for the Superheat 2 runes (Earth+Fire).
