### ISSUE TITLE
[Bug]? Auras consuming runes on hit and not on attack

### ISSUE THREAD

**Issue by Hudzo** [MelvorIdle/melvoridle.github.io#3172]
### Describe the bug

Auras seem to not be in line with prayer / ammunition / rune uses for other attack, as they consume runes on per hit basis and not on per attack basis. Could be intentional, but reporting it anyway.

### Reproduction Steps

Activate an aura (i.e. surge 2) and observe its usage

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

5027

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This is indeed intended.
