### ISSUE TITLE
[Visual Bug]: Loading Obstacles Presets in Agility checks for slightly more mats than are actually required

### ISSUE THREAD

**Issue by Leole11** [MelvorIdle/melvoridle.github.io#3173]
### Describe the bug

When you load an agility preset, it shows you all the mats that are required to replace however many obstacles you need for the preset, but if you have EXACTLY the amount listed, it shows in red that you don't have enough mats, even though you do.

Mind you, this bug only affects the logic that highlights in red the number of mats if you don't have enough, it always consumes the correct amount.

### Reproduction Steps

1. Save an Agility Preset
2. Replace an obstacle
3. Load the Agility Preset with the exact amount of materials required to replace the missing obstacle
4. Be shown red numbers indicating you have insufficient mats, even though you have enough. You're not forced to get +1, the "Replace Button" still works, but it's misleading.

I've only tested this with fish related obstacles (by coincidence), like Freezing Rafting (O15), Water Dive (O15), Monkey Trail (O12) and Forest Maze (O11), I have no idea if this occurs with every single obstacle. I had hefty item cost reductions, but I really couldn't say in total how much it was, I don't know if that affects at all.

On the save link, I left the exact amount of fish to recreate the bug, and the preset is on the first slot, called "Bugtest"

### Expected behaviour

You should be able to replace the obstacle with a preload if you have enough, not if you have enough +1. Very minor bug, but for rarer items (Like Zephyte) it would probably be very annoying to be misled in such a way.

### Save Link

https://melvoridle.com/save/2gUJl7BI

### Screenshots

![image](https://user-images.githubusercontent.com/45719187/213485196-c2b72a02-6e9a-433c-b97e-2f0bde4e0bb2.png)
![image](https://user-images.githubusercontent.com/45719187/213485299-08a51fea-1745-4dca-a338-5084902b9b7f.png)

As you can see, I'm allowed to click the Replace Course button, but it's telling me I don't have enough Raw Mystic Seahorses, even though I clearly do.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5027

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was fixed as of V1.1.2
