### ISSUE TITLE
[Bug]: golbin raid interface vanishes

### ISSUE THREAD

**Issue by herbert164** [MelvorIdle/melvoridle.github.io#3176]
### Describe the bug

If i am currently on the golbin raid tab and have started the raid, when i click on one of the skill tabs and then click the golbin raid the main menu for the golbin raid appears. The raid is still running at this point and you cannot start another raid. Once you complete a wave you can select pause to restore the usual interface. I have not died in this circumstance so i do not know how that will fair.

### Expected behaviour

i expected the raid to automatically pause or the skills to not be selectable.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5027

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
If the issue persists, please open an new issue and provide a save link as well. Thank you.
