### ISSUE TITLE
[Bug]: interface failing to load

### ISSUE THREAD

**Issue by minaolenpalm** [MelvorIdle/melvoridle.github.io#3177]
### Describe the bug

when I have been online for a while and swap over to another character, I sometimes get an error message "Interface failed to load."
after receiving the message i'm unable to load any save even though the message disappears after i swap from local to cloud saves. all save files are non-responsive
![image](https://user-images.githubusercontent.com/61579764/213883043-94950ee8-682a-46e3-863d-9b06bf6079fa.png)

I have been receiving the error message occasionally the past 3 days or so. nothing has changed in my end of things - same computer no windows updates, nothing.
today I have received the error twice I think
the only mod I use is ETA
![image](https://user-images.githubusercontent.com/61579764/213883143-0e7518fa-8318-4c1d-836e-680f63624582.png)
not sure if disabled ones affect anything

### Reproduction Steps

click on my name
click select character
click on a different save
receive error

### Expected behaviour

I expected to load into game

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

V1.1.1 (?5027)

### Are you using any mods?

Yes

**Comment by DreamMentor** [comment]
this is also happening to me on mobile 1.1.1

**Comment by Zethraxxur** [comment]
I also have this issue, and I am using NO mods. Happens to me about 1/3 of the times I try and load my character on the Steam version. I need to restart the app to try again, even this sometimes gives the same error again.
