### ISSUE TITLE
[Bug]: bank and store problem

### ISSUE THREAD

**Issue by Girlbot9** [MelvorIdle/melvoridle.github.io#3180]
### Describe the bug

My bank is saying its maxed out at 100 i go to the store to buy more bank space but the store says my bank space buy limit has been reached at 88 

### Expected behaviour

I expected to be able to buy more bank space its only on this character i cant

### Screenshots

![Screenshot_20230123_083140_Melvor Idle](https://user-images.githubusercontent.com/123387637/214067509-cfa52fca-634d-40f7-bb55-ec11cd38eb66.png)
![Screenshot_20230123_083133_Melvor Idle](https://user-images.githubusercontent.com/123387637/214067549-2b5cd5d0-0d76-444e-9a0d-2e41dc9d6a6f.png)

### Console output

I am on samsung galexy s22

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5027

### Are you using any mods?

No

**Comment by herbert164** [comment]
that is a feature of hardcore characters. limited bank space.
