### ISSUE TITLE
[Bug]: <title> township upgraded buildings

### ISSUE THREAD

**Issue by Zetsu852** [MelvorIdle/melvoridle.github.io#3181]
### Describe the bug

I got 120 township the wiki says 110 for the top buildings but it won't let me upgrade them to the top level. It has the option to upgrade buildings but won't let it happen, if I have 120 and it won't go I'm assuming it's a bug

### Expected behaviour

For it to let me upgrade my buildings like I'm supposed to

### Save Link

https://melvoridle.com/save/DFwSGlFO

### Screenshots

![Screenshot_20230123-132500_Melvor Idle](https://user-images.githubusercontent.com/123413295/214142513-23399143-f6f3-4a2f-bade-c890ee5e0f31.jpg)
![Screenshot_20230123-132453_Melvor Idle](https://user-images.githubusercontent.com/123413295/214142599-72bf350d-65e9-4165-96ff-93e612faf156.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5027

### Are you using any mods?

Yes

**Comment by assassin79518** [comment]
You also need a population requirement to get max-level buildings.

**Comment by MelvorIdle** [comment]
Township has now been reworked as of v1.1.2
