### ISSUE TITLE
[Bug]: <When trying to equip an item from my bank, the "Select equipment set" buttons do not default to my worn equipment set>

### ISSUE THREAD

**Issue by DreamMentor** [MelvorIdle/melvoridle.github.io#3182]
### Describe the bug

Title. Every time I change my equipment set, I have to hit the little button to change the equipment set to the one I'm wearing whenever I try to equip an item. This only happens on ONE of my four accounts. I disabled all my mods and it still happened. I also tried it on desktop and it still happened. The reproduction steps below are just one example but it always happens when I switch equipment sets, not just when I first load my character. 

### Reproduction Steps

**Example 1:**
I load my main character save.
I am training ranged, which is equipment set 3 for me.
I decide to try a different weapon and go to my bank to equip it.
When I select equip, it equips the weapon in my first equipment set instead.
<img width="365" alt="image" src="https://user-images.githubusercontent.com/123406294/214176801-8823a214-5569-46ac-81b3-9e3c85cf3555.png">

And it doesn't just always default to the first equipment set, it's whatever I last manually set it to -

**Example 2:**
I change the selected equipment set in the bank to set 3 so I can equip the bow and try it.
I check the game to do a farm run, so I switch to my skilling equipment set (set 1)
I don't have my signet ring equipped in the passive slot so I go to the bank to equip it
When I select equip, it equips the signet ring in my third equipment set instead.

### Expected behaviour

**Example 1: **It**** should have defaulted to my worn equipment set, which is set 3, but it defaults to the first set. 
![image](https://user-images.githubusercontent.com/123406294/214177445-7db4badb-a73d-4cef-88d7-0fd63a3526c7.png)

**Example 2: **It**** should have defaulted to my worn equipment set (set 1) _when_ I changed from set 3 to set 1., but it does not change from equipment set 3 to equipment set 1.

### Save Link

https://melvoridle.com/save/IColKZ1a

### Screenshots

![image](https://user-images.githubusercontent.com/123406294/214178261-340394d4-ba4d-41c1-9ef3-c89697db9486.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

5027

### Are you using any mods?

Yes, but I still have this issue with all mods disabled.

**Comment by DreamMentor** [comment]
pls help this is driving me insane

**Comment by DreamMentor** [comment]
pls help, this is driving me insane
(did not mean to close this bug)

**Comment by DreamMentor** [comment]
pls help, this is driving me insane
(did not mean to close this bug)

**Comment by coolrox95** [comment]
If you go to the settings in the bank, you should be able to toggle: "Equip Item - Use Current Equipment Set as Default" to on to restore the desired behavior.

![image](https://user-images.githubusercontent.com/58208131/227707087-652a14b6-a41a-4633-b3b2-6ceb27967c84.png)
