### ISSUE TITLE
[Bug]: Quick Equip Superior Skillcapes

### ISSUE THREAD

**Issue by tezzy808** [MelvorIdle/melvoridle.github.io#3183]
### Describe the bug

Hi MelvorIdle Team,

I don't think this is a bug but more of a feature request... are you able to make it possible to quick equip the superior skillcapes?  I've sold the skillcapes I have so they're no longer in my inventory but I when trying to quick equip it only shows the skillcape (and not the superior skillcape)

Thanks!

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5047

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Quick equip items are custom defined by the player. This can be done by selecting the item in the Bank, and adding it to the quick equip section within the Gear icon
