### ISSUE TITLE
[Bug]: Cyclops/Spider synergy doesn't work

### ISSUE THREAD

**Issue by Rackius** [MelvorIdle/melvoridle.github.io#3184]
### Describe the bug

Same as title

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5047

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Duplicate of #3123
