### ISSUE TITLE
[Bug]: Firemaking quick equip.

### ISSUE THREAD

**Issue by hamilc163** [MelvorIdle/melvoridle.github.io#3185]
### Describe the bug

Not sure if this would be considered a bug or just a suggestion but the quick equip option on skills (cog button) allows you to equip skill capes etc for whichever skill you are looking at.

I have firemaking equipment in my inventory, neck pieces I’m particular, and they do not show on the quick equip menu.

### Reproduction Steps

1. Own Burning Amulet of XP
2. Go to firemaking
3. Press quick equip (cog above the summoning button)
4. Nothing is available to quick equip

### Expected behaviour

I would expect the Burning Amulet of XP to be visible in the quick equip menu when looking at firemaking as it’s an item specific to firemaking.

### Screenshots

![93FDF7C6-4ADB-4D1E-89F6-CE7938534FB5](https://user-images.githubusercontent.com/123488802/214350402-609bd829-a801-448e-bcdb-fa51056c42f1.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5047

### Are you using any mods?

No

**Comment by Mot92** [comment]
In addition, you can fix the quick equipment for Summoning. The raincoat does not pull up. Similar problem with capes from Throne of the Herald Expansion

Which platforms are you experiencing this bug on? 

Mobile App (iOS) 

Which version of the game are you experiencing this bug on?
v1.1.1

Game Subversion
?5047

Are you using any mods?
No

**Comment by coolrox95** [comment]
Quick equip items are custom defined by the player. This can be done by selecting the item in the Bank, and adding it to the quick equip section within the Gear icon
