### ISSUE TITLE
Paid version turned into demo 

### ISSUE THREAD

**Issue by Omenauspicium** [MelvorIdle/melvoridle.github.io#3186]
### Describe the bug

I was playing and my game stopped loading so I reloaded the mobile app now my account turned into an unpaid account I bought both the main and dlc weeks ago.

### Save Link

https://melvoridle.com/save/CXH2uHbi

### Screenshots

![1A11E9C0-FCED-465E-A5E6-2CE5D8588DDA](https://user-images.githubusercontent.com/123518390/214444140-d293a44e-ee1f-4389-8595-560315480f83.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

Can’t see. Most recent.

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
I believe this issue resolved itself
