### ISSUE TITLE
[Bug]: Ahrenia 3rd phase

### ISSUE THREAD

**Issue by 15mdr02** [MelvorIdle/melvoridle.github.io#3187]
### Describe the bug

Ahrenia 3rd Phase

Is Ahrenia’s 3rd phase ability “Into the mist” designed to create a healing buff twice? 

I was fighting it and noticed that it got the healing buff while the ability was active and then as soon as the ability ended, the healing and damage reduction would vanish but then it instantly refreshed another 10 ticks of healing (no damage reduction refresh). So instead of it healing for 10% over 10 seconds it was actually getting a 20% healing over 20 seconds. 

### Reproduction Steps

Engage Ahrenia 3rd phase
Observe the skill “into the mist”

### Expected behaviour

The healing buff will refresh after the initial 10 ticks finish without using the ability again

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5047

### Are you using any mods?

Yes

**Comment by VitamintK** [comment]
I have noticed this as well

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.1.2
