### ISSUE TITLE
[Bug]: Wrong special attack for Ultima God Sword in Golbin raid

### ISSUE THREAD

**Issue by ChiSoxDev** [MelvorIdle/melvoridle.github.io#3189]
### Describe the bug

Special attack is Corrundium Wounds which is incorrect. 

### Reproduction Steps

Get Ultima GS in Golbin raid

### Expected behaviour

Correct Ultima GS spec

### Screenshots

![Screenshot_20230125-194546](https://user-images.githubusercontent.com/121800704/214739008-8403dea3-86e2-4370-8393-a90e411b5f76.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

5047

### Are you using any mods?

Yes

**Comment by ekuland** [comment]
You chose an (Alt) weapon. It has a random special attack. This is a feature of GR.
