### ISSUE TITLE
Chance to Hit not updating automatically with Ancient Crossbow special attack

### ISSUE THREAD

**Issue by Ryukijen** [MelvorIdle/melvoridle.github.io#319]
**Describe the bug**
The "Chance to Hit" stat does not update automatically when Ancient Crossbow special attack is used.  It does update hpwever once you click on a prayer or something.

**To Reproduce**
1.  Fight whatever monster with Ancient Crossbow
2.  Watch when special attack hits
3.  Click on any prayer to update Chance to Hit

**Expected behavior**
The Chance to Hit stat to increase after special attack damage

**Screenshots**
N/A

**Browser**
Chrome

**Console output**

**Are you using any scripts?**
N/A

**Comment by MelvorIdle** [comment]
Should be fixed in the coming update
