### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by eduardohernandez401600** [MelvorIdle/melvoridle.github.io#3190]
### Describe the bug

Attempted to delete agility obstacle while thieving, game froze and now I am unable to play. Still thieving but I will provide a screenshot of what my game shows.

### Reproduction Steps

An error occurred while rendering:
Active Action: melvorD:Thieving
Error Name: Error
Error Message: Tried to get active obstacle, but none is built.
Stack Trace:
activeObstacle@https://ios.melvoridle.com/assets/js/built/agility.js?5047:27:16
getGPModifier@https://ios.melvoridle.com/assets/js/built/agility.js?5047:52:248
getObstacleGP@https://ios.melvoridle.com/assets/js/built/agility.js?5047:59:82
renderCourseRates@https://ios.melvoridle.com/assets/js/built/agility.js?5047:138:371
render@https://ios.melvoridle.com/assets/js/built/agility.js?5047:136:75
@https://ios.melvoridle.com/assets/js/built/game.js?5047:180:69
forEach@[native code]
forEach@https://ios.melvoridle.com/assets/js/built/namespaceRegistry.js?5047:37:51
render@https://ios.melvoridle.com/assets/js/built/game.js?5047:180:46
loop@https://ios.melvoridle.com/assets/js/built/game.js?5047:196:41
loop@[native code]
Current Equipment:
Helmet: melvorF:Chapeau_Noir
Platebody: melvorF:Necromancer_Robes
Platelegs: melvorTotH:Thieving_Shorts
Boots: melvorF:Boots_Of_Stealth
Weapon: melvorD:Bobs_Rake
Amulet: melvorD:Amulet_of_Fishing
Ring: melvorD:Ancient_Ring_Of_Skills
Gloves: melvorF:Thieving_Gloves
Cape: melvorF:Max_Skillcape
Passive: melvorF:Gloves_of_Silence
Summon2: melvorF:Summoning_Familiar_Devil
Consumable: melvorF:Fishing_Hook

Action Information:
function getErrorLog(){return `Is Active: ${this.isActive}\n`;}
  Selected Area: melvorF:WIZARD_TOWER
  Selected NPC: melvorF:WIZARD
  Stun State: 0
Modding Enabled. Loaded mods:
Dev

### Expected behaviour

Deletion of obstacle

### Screenshots

![804C09E1-9532-4551-A7E4-4980008D0F9C](https://user-images.githubusercontent.com/123669425/214926252-d8854a54-4958-409d-a8c6-aceeeb524209.png)

### Console output

Not using browser

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

Unable to see

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Produces the same error message as #2980 when attempting to build a course, should be resolved by same patch

**Comment by coolrox95** [comment]
Issue was fixed as of V1.1.2
