### ISSUE TITLE
[Bug]: lost all progress

### ISSUE THREAD

**Issue by MaHhew99** [MelvorIdle/melvoridle.github.io#3191]
### Describe the bug

lost all progress
![2023-01-28 (3)](https://user-images.githubusercontent.com/123834048/215285735-3431e7f1-700a-46e2-86a3-3759bb0d9d45.png)
![2023-01-28 (2)](https://user-images.githubusercontent.com/123834048/215285741-2cb700ba-ee60-4a99-b15f-73b6601ca22c.png)
![2023-01-28 (1)](https://user-images.githubusercontent.com/123834048/215285744-141945bc-3274-4f04-b41a-a78eec526cfe.png)
![2023-01-28](https://user-images.githubusercontent.com/123834048/215285747-8de1abc9-a6df-42b4-9c33-42bc75625ce4.png)

### Reproduction Steps

I don't fully know

### Expected behaviour

made me go back to the demo

### Save Link

https://melvoridle.com/save/AoLzeVx7

### Screenshots

![2023-01-28 (3)](https://user-images.githubusercontent.com/123834048/215285735-3431e7f1-700a-46e2-86a3-3759bb0d9d45.png)
![2023-01-28 (2)](https://user-images.githubusercontent.com/123834048/215285741-2cb700ba-ee60-4a99-b15f-73b6601ca22c.png)
![2023-01-28 (1)](https://user-images.githubusercontent.com/123834048/215285744-141945bc-3274-4f04-b41a-a78eec526cfe.png)
![2023-01-28](https://user-images.githubusercontent.com/123834048/215285747-8de1abc9-a6df-42b4-9c33-42bc75625ce4.png)

### Console output

that does not work

I'm using opera GX

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

(?5047)

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
I believe this issue resolved itself.
