### ISSUE TITLE
[Bug]: Steam 'Mastery Master' achievement not triggering

### ISSUE THREAD

**Issue by Adhin37** [MelvorIdle/melvoridle.github.io#3193]
### Describe the bug

I mastered every skill from the base game, but i seem to have an issue with my cooking skill :
![image](https://user-images.githubusercontent.com/17513979/215343659-bc4c1634-b15e-43fb-abc0-3beded93bcb2.png)
My mastery from "Throne of the Herald" seem to also count and make the total amount incorrect (3138/3069)

_**P.S :**_ Strangely, i got 100% completion without problem.
_**P.S 2 :**_ I disabled all my installed mods in case, but no change after reboot. 

### Expected behaviour

Obtaining 'Mastery Master' achievement in steam at 100% mastery (base game) and above (DLC).

### Save Link

https://melvoridle.com/save/IGWSpHL3

### Screenshots

![image](https://user-images.githubusercontent.com/17513979/215344105-e87d378a-067e-4327-8211-db166edf7298.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5047

### Are you using any mods?

Yes

**Comment by ekuland** [comment]
Mod issue.
You used Semi Automastery, it added mastery somewhere it shouldn't've.
Went ahead and fixed it for you.
https://melvoridle.com/save/OT46l9td

**Comment by Adhin37** [comment]
thanks, that was it
