### ISSUE TITLE
[Bug]: Melvor opens facebook links.

### ISSUE THREAD

**Issue by HDScorpio12** [MelvorIdle/melvoridle.github.io#3195]
### Describe the bug

The android app is trying to open all facebook links from google chrome. The app believes that m.facebook.com/ links are "supported links" and this behaviour is only prevented by accessing the app's settings within android.

### Reproduction Steps

1. Go to google.com and search "melvor idle facebook"
2. Click on the facebook link.
3. Melvor idle automatically opens, believing that facebook links are supported.

### Expected behaviour

I didn't expect Melvor Idle to associate m.facebook.com links with itself. 

### Save Link

N/A

### Screenshots

https://user-images.githubusercontent.com/123988096/215571346-bae17a51-ea33-4f33-bf1a-c551dc9b2910.mp4

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5047

### Are you using any mods?

No

**Comment by datcactus** [comment]
Additional context: This bug occurs even if the app has 'Open by default' set to 'Don't allow app to open links'. Facebook links are also not present anywhere in my device's default app for link session, nor is a Facebook app installed. There's something odd going on with the app here, and it's likely a security issue if it's ignoring the 'Open by default' setting.

![Screenshot_20230601-175945](https://github.com/MelvorIdle/melvoridle.github.io/assets/107456394/2ceb9312-a37e-4d99-add0-1903ba6b0ec6)
