### ISSUE TITLE
[Bug]: Aorpheats Ring thieving bonus

### ISSUE THREAD

**Issue by Architect101** [MelvorIdle/melvoridle.github.io#3197]
### Describe the bug

Aorpheats Ring discription states +5 chance to obtain double loot from thieving however when looking into the stats they state that the ring has -5 to double loot chance.
![Screenshot_20230131-190750](https://user-images.githubusercontent.com/124038294/215717601-b3d6f273-e374-4b08-a40e-ff8c9d904737.png)

![Screenshot_20230131-190741](https://user-images.githubusercontent.com/124038294/215717545-a02c63bf-b109-46ac-9fa4-9a18e6a1d186.png)

### Reproduction Steps

Equip Aorpheats Ring
Thieve

### Expected behaviour

The ring will have a negative to doubled items chance.

### Save Link

https://melvoridle.com/save/ERdwJ2ih

### Screenshots

![Screenshot_20230131-190750](https://user-images.githubusercontent.com/124038294/215717714-4124a038-cc65-41f7-96c7-e6c4ad00b235.png)
![Screenshot_20230131-190741](https://user-images.githubusercontent.com/124038294/215717735-72f96eee-b68f-4866-8256-abdb8906b64d.png)

### Console output

Mobile

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [x] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5047

### Are you using any mods?

Yes

**Comment by 47Y** [comment]
This is intentional due to how the game handles the doubling modifiers for the item. Instead of doing a bunch of +10s and a couple +5s it does +10 to everything (global) then -5 to Thieving and Combat.
