### ISSUE TITLE
[Bug]: Visual Glitches

### ISSUE THREAD

**Issue by DrAardvarkMD** [MelvorIdle/melvoridle.github.io#3199]
### Describe the bug

Every so often the screen will tear and there will be a discolored afterimage from a previous page or menu. 

### Reproduction Steps

I have no idea what causes it

### Screenshots

![Screenshot_20230131_082141](https://user-images.githubusercontent.com/124057614/215771958-dfd9d988-ee95-43c8-abdc-c9204a87b8f2.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5047

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
We have been unable to reproduce this bug. I suggest disabling the Steam overlay as that may cause similar artefacts with Melvor Idle.
