### ISSUE TITLE
[Bug]: Auto Save to Cloud does not work

### ISSUE THREAD

**Issue by Buraiyen** [MelvorIdle/melvoridle.github.io#3200]
### Describe the bug

Auto saving to the cloud does not work. The feature originally worked once 2 hours of play time has been reached, but now the time goes beyond 2 hours without auto saving. Removing all mods from my account doesn't solve this issue either

### Expected behaviour

Game automatically saves after 2 hours without using force-save

### Save Link

https://melvoridle.com/save/13QKc9iR

### Screenshots

![Screenshot from 2023-01-31 13-35-15](https://user-images.githubusercontent.com/33035218/215888710-2e745482-623b-448d-b918-e84af56f4728.png)

![Screenshot from 2023-01-31 13-25-28](https://user-images.githubusercontent.com/33035218/215888840-a8afe86a-1746-479f-ae82-d45ae7e90015.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5047

### Are you using any mods?

Yes

**Comment by felipearbrandao** [comment]
On both Edge and Chrome, without using any mods and on the same version of this report, I'm getting the error below when trying to connect to Patreon:

![image](https://user-images.githubusercontent.com/8097068/215961686-bcbeb1b1-3201-4218-849a-ce11c5d7244d.png)

**Comment by MelvorIdle** [comment]
Auto save timer was increased to once every 16 hours. This is due to the high bandwidth costs we were facing with the 2 hour timer.
