### ISSUE TITLE
[Bug]: When mining coal with melvor closed, it switches to runite by itself

### ISSUE THREAD

**Issue by thelegendoferic** [MelvorIdle/melvoridle.github.io#3202]
### Describe the bug

I start mining coal, i click save, i close melvor tab in chrome. I come back later, it shows I was mining runite. I figured I clicked by accident so i click coal and save & close melvor tab again. same thing, when i return, I only mined runite. I tested this issue multiple times and it continues to happen. if i leave chrome tab open and active, it mines coal but when the tab runs too long and my tab suspender suspends the melvor tab, it starts mining runite. Pretty frustrating. 

### Reproduction Steps

melvor.com
mining tab
mine coal
save button
close tab
reopen chrome
melvor.com
"here's how much runite you mined"

### Expected behaviour

i expected to have coal... instead i got mainly runite.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5047

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
We have been unable to reproduce this bug. If issue persists, please open a new ticket and also provide a save link so we can check it out. Thank you.
