### ISSUE TITLE
[Bug]: Perlious Peaks dragons appear in Master slayer task, with no required item equipped

### ISSUE THREAD

**Issue by Lex69v** [MelvorIdle/melvoridle.github.io#3205]
### Describe the bug

Sometimes (often) in slayer task appear dragons from Perilous Peaks

### Reproduction Steps

1. Automatic new task disabled (not sure if its important)
2. Cape of prat cloak equipped
3. Climbing boots not equipped
4. Start Master slayer task

### Expected behaviour

Expect only Dark Waters monsters to spawn

### Save Link

https://melvoridle.com/save/uw7wyKmF

### Screenshots

![Screenshot_107](https://user-images.githubusercontent.com/124489616/216807814-083a74ce-8abd-4a7b-914f-df2741deeb57.jpg)
Mods that i used at the time

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5047

### Are you using any mods?

Yes

**Comment by 47Y** [comment]
If you have "Automatically fight new Slayer Task?" disabled, the game does not check that you can _currently_ fight the enemy, only that you own or have owned the required item to do so. If you have previously purchased Climbing Boots it can give you tasks that require it. When the setting is enabled, it checks that you are currently able to fight them to prevent you from being stuck fighting something you can't injure.

**Comment by Lex69v** [comment]
Ok thanks.
It is disabled because i switch equipment between Dark Waters monsters.
In my opinion the current logic is less logical. But this is not so important, a couple of clicks and a certain number of points solve this inconvenience. Thanks alot for the game
