### ISSUE TITLE
[Bug]: <title>I can not see the items in my bank in each tab.

### ISSUE THREAD

**Issue by 2squillion** [MelvorIdle/melvoridle.github.io#3208]
### Describe the bug

I have just started this game, but something happened and now I can no longer see any items or objects below the line when I select any of the tabs. 

### Expected behaviour

When I started the game, I could see ALL the items in a tab when I clicked on the tab

### Screenshots

This one shows where the Gold is or  which tab it is in, but no items to see in that tab.
![Bankshot 2](https://user-images.githubusercontent.com/125108932/218239802-1d4430a5-a78f-4f8e-bd42-8add7095ba53.jpg)
This one looks almost the same when I have taken the word Gold, out of the search nbar.
![Bankshot 3](https://user-images.githubusercontent.com/125108932/218239862-7d71341c-2af7-480c-8cae-7468dfa64cfd.jpg)

### Console output

I can get F12 open, but can't find a way to copy it.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

75047

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
If issue persists, please open a new ticket and provide a Save Link so we can check it out. Thank you.
