### ISSUE TITLE
Volcanic Cave

### ISSUE THREAD

**Issue by Cimatoa** [MelvorIdle/melvoridle.github.io#3209]
### Describe the bug

While manually holding down eat, Volcanic cave has 'crashed'(?) twice: the monster suddenly disappeared and I've had to restart the dungeon. 

As I am attempting the cave at a low level (57hp, 68 combat), each try is a huge time and food sink. I'm worried it'll keep happening and so have to stop trying. Please could you check this out?

Thanks very much for your time,

Cimatoa (account name)

### Reproduction Steps

Go to: Volcanic cave [dungeon].
During the final two bosses [is when it happened to me]. 
Manually hold down eat [monster will suddenly disappear when under 50% hp].

### Expected behaviour

While manually holding down eat in the Volcanic Caves, the penultimate monster disappeared. I was still in the dungeon but the monster screen was empty. I returned to try again, but the same thing happened with the Boss. Both monsters were under 50% hp, I did not die, nor did I run; yet suddenly the monster(s) just vanished. 

(I had 2.4s interval on combat; 580hp; using perfect cave fish)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5047

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
If issue persists, please open a new ticket and provide a save link as well. Thank you.
