### ISSUE TITLE
Game constantly reloading iOS 

### ISSUE THREAD

**Issue by maicolon** [MelvorIdle/melvoridle.github.io#321]
**Describe
When I open the app from being in the background, after showing me my item and xp gains, it will reload and erase everything. 
Now, it’s become a reloading loop and I cannot play at all. When I close the app from background, and reopen, it just constant reloads, let’s me open my character, reloads, etc. 
totally unplayable

**To Reproduce**
Anytime I open the app now and click to open my character it reloads and resets. I click again, reloads. Start new character, reloads. 

**Browser**
iPhone XS Max

**Comment by MelvorIdle** [comment]
This should be fixed in the coming days!
