### ISSUE TITLE
[Bug]: (P) Divine Boots stat anomalies

### ISSUE THREAD

**Issue by sqrpio** [MelvorIdle/melvoridle.github.io#3210]
### Describe the bug

The (P) Divine Boots seem to have a number of inconsistencies in their stats, compared to other smithable boot-slot equipment. In particular, the stat block of the (P) Divine Boots appears identical to that of the (I) Divine Helmet (aside from the DR value, which appears to be correct in the Boots). This gives the Boots melee defence and ranged defence values far out of line with the expected stats for this item, as well as meaning they entirely lack their un-upgraded counterparts' melee strength bonus, on top of more minor inconsistencies in magic attack and magic defence bonuses.

### Expected behaviour

Based on the stats of the other smithable boots and their upgrades, i've extrapolated what i believe to be the intended stats of the (P) Divine Boots:

Ranged Attack -2 (same as current value)
Magic Attack -5 (instead of current -6)
Strength Bonus +14* (instead of current +0)
Melee Defence Bonus +39 (instead of current +72)
Ranged Defence Bonus +15 (instead of current +73)
Magic Defence Bonus -4 (instead of current -1)
Damage Reduction 12% (same as current value)

*The Strength Bonus is a bit odd in that it looks like the (I) Divine Boots may also have an error; it looks like the (I) version should have a +13 Strength Bonus (rather than the current +12), based on the Corundum and Augite Boots upgrade progressions (tho the other stats of the (I) Divine Boots all look correct).

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5047

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.1.2
