### ISSUE TITLE
[Bug]: <title> Golbin Raid

### ISSUE THREAD

**Issue by ghost** [MelvorIdle/melvoridle.github.io#3212]
### Describe the bug

You only receive 1 consumable which is not worth.

### Reproduction Steps

Complete a wave in Golbin Raid. 
Select Armour.
Randomly recieve consumable x1
Attack once and it's gone.

### Expected behaviour

More reasonable amount of consumable to be acquired. And maybe an option to replenish.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5047

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
We will continue working on Golbin raid and will most likely make this change in the future.
