### ISSUE TITLE
[Bug]: <title> Golbin Raid Loot?!

### ISSUE THREAD

**Issue by ghost** [MelvorIdle/melvoridle.github.io#3213]
### Describe the bug

I have received loot from Golbins during Golbin Raid?!? I'm not to sure as too how this has occurred unfortunately. 

### Reproduction Steps

Open melvor this morning like normal.
After checking my main account I open Golbin Raid.
After playing for about an hour I noticed loot!

### Screenshots

![Screenshot_20230214_122928_Melvor Idle](https://user-images.githubusercontent.com/117135429/218813494-34ae7da5-ab03-4665-b4d9-6a08aa0d4140.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5047

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
We are unable to reproduce this issue. If issue persists, please submit a new report.
