### ISSUE TITLE
[Bug]: Earth Rune creation automation stop

### ISSUE THREAD

**Issue by Morgathys** [MelvorIdle/melvoridle.github.io#3214]
### Describe the bug

Most of any action is done automatically until you stop it yourself.
Creating earth runes will stop after a couple of run

### Reproduction Steps

1. Buy mining
2. Mine runes
3. Buy runecraft
4. Craft earth rune
5. ...
6. NO PROFIT!!

### Expected behaviour

I would like to craft earth runes like no tomorrow for days and weeks

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5047

### Are you using any mods?

Yes

**Comment by Silverfyree** [comment]
I cant find any way to reproduce this at all, works perfectly for me.
Do you have enough rune essence to make runes? it requires 1 essence per craft.

**Comment by Morgathys** [comment]
yea sure, because its worked for the first couple of minutes before stopping.

**Comment by Morgathys** [comment]
you just make me realized how poor is my bug description : /

**Comment by MelvorIdle** [comment]
This is due to having the "Ignore Bank Full" setting disabled, and you receiving a secondary rare drop from the Skill that cannot fit in your Bank causing the Skill to stop.
