### ISSUE TITLE
[Bug]: <cooked lava fish>

### ISSUE THREAD

**Issue by Jcub2491** [MelvorIdle/melvoridle.github.io#3216]
### Describe the bug

I am cooking lava fish and regular cooked lava fish are not going into my bank. Perfect cooked lava fish are stacking in my bank but not the original cooked lava fish.

### Expected behaviour

As I cook the lava fish I expect them to stack in my bank.

### Save Link

https://melvoridle.com/save/aohaAtoG

### Screenshots

![Screenshot_20230217_004045_Melvor Idle](https://user-images.githubusercontent.com/125637364/219568838-f5c10514-10e0-4c03-8973-e608e30a2e68.jpg)
![Screenshot_20230217_003941_Melvor Idle](https://user-images.githubusercontent.com/125637364/219568843-d70ecfe7-5a18-43f6-995f-3f193eeacd0d.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5047

### Are you using any mods?

No

**Comment by Silverfyree** [comment]
Most likely you have the upgrade which automatically equips food as you cook it, so its in your equipped food section rather than bank.

**Comment by coolrox95** [comment]
You have lava fish equipped and the Automatically equip food upgrade enabled.
