### ISSUE TITLE
[Bug]: <title>Mining gloves

### ISSUE THREAD

**Issue by Calmblood** [MelvorIdle/melvoridle.github.io#3218]
### Describe the bug

Mining gloves does not work with Pure essence. I'm wearing mining gloves with some charges bought. So i have to get 2x ores, but still getting just 1. It works with Rune essence, so i've decided to report this issue with Pure essence.
Thanks

### Reproduction Steps

1. Wear mining gloves with some charges bought. 
2. Start mining Pure essence.
3. You still get just 1x pure essence.

### Expected behaviour

I'm playing on Opera, desktop computer

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5047

### Are you using any mods?

No

**Comment by Silverfyree** [comment]
Mining gloves states in the tooltip that it only works on ores, essence is not actually an ore.
You can check what type of mining is being done under the name of each mining option, they are either ore, essence or gem vein.
![image](https://user-images.githubusercontent.com/77082862/220096025-31e25653-74e5-4cf0-b91c-6283948c5c81.png)
