### ISSUE TITLE
Mixed up item IDs

### ISSUE THREAD

**Issue by 8992scripts** [MelvorIdle/melvoridle.github.io#322]
CONSTANTS.item.Leaping_Salmon is the item ID for Leaping Trout
e.g. items[CONSTANTS.item.Leaping_Salmon].name == "Leaping Trout"

CONSTANTS.item.Leaping_Trout is the item ID for Raw Poison Fish
e.g. items[CONSTANTS.item.Leaping_Trout].name == "Raw Poison Fish"

CONSTANTS.item.Raw_Poison_Fish does not exist

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
