### ISSUE TITLE
[Bug]: Smithing gloves

### ISSUE THREAD

**Issue by Bananaman663** [MelvorIdle/melvoridle.github.io#3220]
### Describe the bug

Spent 2.7m on smithing gloves just to realize they are not giving me the extra 60% EXP on ANYTHING I do in smithing... Please fix!

### Expected behaviour

It to work…

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [x] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5074

### Are you using any mods?

Yes

**Comment by Silverfyree** [comment]
The gloves definitely do work, they even automatically update the XP you receive on the skilling page.
See below screenshots with shows the difference

first screenshot without the gloves - 575 xp per dragon plate
![image](https://user-images.githubusercontent.com/77082862/220095194-d68b2818-421c-4df2-91f9-4b2710156586.png)

second screenshot WITH the gloves - 905 xp per dragon plate 
![image](https://user-images.githubusercontent.com/77082862/220095288-42c7be2c-ea0d-4b21-a207-4cb99845e794.png)
