### ISSUE TITLE
[Bug]: <title>fire making token XP error

### ISSUE THREAD

**Issue by mediocremichael36** [MelvorIdle/melvoridle.github.io#3221]
### Describe the bug

Despite fire making for several days straight, and into the 90’s for its level, whenever I use a mastery XP token for it, I only receive 4500XP

### Reproduction Steps

1.) Click on Firemaking Token
2.) Claim XP
3.) See only 4500XP provided

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5047

### Are you using any mods?

No

**Comment by Silverfyree** [comment]
Using tokens gives mastery pool and not regular exp.
Furthermore the amount of mastery pool given is always 0.1% of the total pool XP (0.1% of 4.5m is 4.5k), which is why you always get the same amount regardless of your level.
