### ISSUE TITLE
[Bug]: Missing icons

### ISSUE THREAD

**Issue by Xeedy** [MelvorIdle/melvoridle.github.io#3222]
### Describe the bug

Somehow some items have missing icon. I tried to reinstall, but its there again. Dont know what else try. Thank you

### Save Link

https://melvoridle.com/save/NCaWzxa9

### Screenshots

![image](https://user-images.githubusercontent.com/95588538/220157976-63b8c836-6a0d-44d1-9549-4012063c8908.png)
![image](https://user-images.githubusercontent.com/95588538/220158043-317bcd8f-4f86-4cc3-bdc3-bffedec69d5c.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5047

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This is usually caused by a combination of the server having a minor hiccup, and ISP issues on the player end. Not something we can address 100%, but something we are always trying to improve.
