### ISSUE TITLE
Possibly bad minimum magic damage calculation

### ISSUE THREAD

**Issue by Povilas-R** [MelvorIdle/melvoridle.github.io#323]
Currently the calculation is seems to be:
`[0 to baseMaxHit) * damageMultiplier + minimumDamage`
Since minimum damage implies increase to the minimum hit, not increase to all damage, I believe it should be:
`[minimumDamage to baseMaxHit] * damageMultiplier`

With base max hit 100 and minimum damage of 1, the damage range is [1 to 100]. With minimum damage of 50, the damage range becomes [50 to 150], instead of the expected [50 to 100].

**Comment by MelvorIdle** [comment]
This was hotfixed :)
