### ISSUE TITLE
[Bug]: huge data usage with mobile app

### ISSUE THREAD

**Issue by Jodaig** [MelvorIdle/melvoridle.github.io#3231]
### Describe the bug

My game have been using way too much data this month ; 15G of data in 3 weeks
I found out that everytime I load into my game it directly uses arround 30 Mo.

My auto cloud save is disabled, I tried using only local saves but it still uses alot of data
I also tried to clear the cache and uninstalling the app a couple of times too.

Also my game doesnt show all the icons most of the times. Sometimes they start to appear very slowly one after another can take multiple minutes until I am able to see what I am doing, it gets very frustrating to play
Im using the latest update, 3.0.1
Thank you, I hope my problem can be fixed

### Screenshots

![Screenshot_20230224_143538_Melvor Idle](https://user-images.githubusercontent.com/76396435/221276472-5e1f5624-d917-4ec9-ba55-858e157eaf85.jpg)
![Screenshot_20230224_143523_Melvor Idle](https://user-images.githubusercontent.com/76396435/221276507-5307a11d-4c3f-42b7-baff-8c12c1743892.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5053

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This is currently an issue with the Android app. We are working on a new app to hopefully address this issue in the near future.
