### ISSUE TITLE
Cant fight

### ISSUE THREAD

**Issue by Leinar32** [MelvorIdle/melvoridle.github.io#3232]
### Describe the bug

When trying to initiate a find it can't find any monster.

### Reproduction Steps

I created an adventure mode character and skip the tutorial. 
Tried to fight the plant but no monster shows up.

### Expected behaviour

It will load at first then no monster would show up.

### Save Link

https://melvoridle.com/save/oDoqgJfn

### Screenshots

![image](https://user-images.githubusercontent.com/126297988/221322316-303265f8-7f16-439e-97a2-185a50ffb320.png)
![image](https://user-images.githubusercontent.com/126297988/221322330-dc487ef7-e2a3-44da-93c5-ff83437a786c.png)

### Console output

[Nano] Nano Defender Activated :: melvoridle.com [core.js:43:24](moz-extension://aa41057f-f3e4-4642-8f32-da584bd80d51/content/core.js)
unreachable code after return statement
[cloud.js:209:39](https://melvoridle.com/assets/js/built/cloud.js?5053)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993. (Reason: CORS request did not succeed). Status code: (null).

None of the “sha512” hashes in the integrity attribute match the content of the subresource. [index_game.php](https://melvoridle.com/index_game.php)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993. (Reason: CORS request did not succeed). Status code: (null).

None of the “sha512” hashes in the integrity attribute match the content of the subresource. [index_game.php](https://melvoridle.com/index_game.php)
Silent Sign in with JWT [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Validating Melvor Cloud token [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Storing Melvor Cloud Token [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Initializing PlayFab login. Method: customID [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Logging in with Custom ID via PlayFab [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Login with custom ID success [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Getting account info [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Account info retrieved [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Authenticated w/ Melvor Cloud: true [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Authenticated w/ PlayFab: true [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Checking for valid full version [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Checking for valid TotH purchase [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Loading Game Data... [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Registered Demo Data. [save.js:110:189](https://melvoridle.com/assets/js/built/save.js?5053)
Registered Full Version Data. [save.js:110:355](https://melvoridle.com/assets/js/built/save.js?5053)
Registered Throne of the Herald Data. [save.js:110:522](https://melvoridle.com/assets/js/built/save.js?5053)
Initializing Mod Manager... [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
PlayFab Data Stored successfully. [cloud.js:147:75](https://melvoridle.com/assets/js/built/cloud.js?5053)
Checking for Mod Updates... [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Loading Mods... [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Loading Mods (1/21): SEMI Core (v1.7.2) [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Loading Mods (2/21): Unlimited Offline (v0.1.3) [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Loading Mods (3/21): SEMI Drop Chances (v1.4.0) [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Loading Mods (4/21): SEMI Auto Farming (v0.3.1) [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Loading Mods (5/21): SEMI Auto Master (v1.7.0) [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Loading Mods (6/21): SEMI Auto Bonfire (v0.1.0) [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Loading Mods (7/21): SEMI Auto Loot (v1.3.0) [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Loading Mods (8/21): SEMI Auto Eat (v1.4.0) [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Loading Mods (9/21): SEMI Auto Runecrafting (v1.1.0) [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Loading Mods (10/21): SEMI Auto Smith Bars (v1.4.0) [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Loading Mods (11/21): SEMI Auto Sell (v1.1.0) [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Loading Mods (12/21): SEMI Auto Slayer (v1.2.0) [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Loading Mods (13/21): SEMI Auto Run (v1.3.0) [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Loading Mods (14/21): SEMI Save on Close (v1.1.0) [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Loading Mods (15/21): SEMI Auto Bury (v0.0.4) [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Loading Mods (16/21): SEMI Auto Open (v1.3.0) [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Loading Mods (17/21): SEMI Auto Collect Stockpiles (v1.1.0) [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Loading Mods (18/21): SEMI Auto Gear Swap (v1.4.0) [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Loading Mods (19/21): Item Township Task Info (v0.0.5) [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Loading Mods (20/21): Bank Tab Values (v1.1.0.4395) [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Loading Mods (21/21): Reveal Thieving Loot (v1.0.0) [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Loading Local Saves... [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Loading Cloud Saves... [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Getting saves from playfab [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)
Saves retrieved [cloudManager.js:201:22](https://melvoridle.com/assets/js/built/cloudManager.js?5053)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

1.0.2.0

### Are you using any mods?

Yes

**Comment by ekuland** [comment]
Mod Issue. You do not have a valid setup to fight the enemy, SEMI Auto Gear Swap is running.

**Comment by Zezzima** [comment]
I don't use mods. Never have..?
    On Saturday, February 25, 2023 at 12:29:00 AM EST, ekuland ***@***.***> wrote:  
 
 


Mod Issue. You do not have a valid setup to fight the enemy, SEMI Auto Gear Swap is running.
