### ISSUE TITLE
[Bug]: <unable to use potions>

### ISSUE THREAD

**Issue by Sarnt16** [MelvorIdle/melvoridle.github.io#3234]
### Describe the bug

Recently upgraded to full game and can use the herblore skill to craft potions, but they don't do anything. Am I supposed to equip them somehow? The way I understood the wiki page, they're supposed to just exhaust straight from bank inventory when performing a relative action for that type of potion. 

### Expected behaviour

Potions to be exhausted during relative action performed

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5053

### Are you using any mods?

No

**Comment by coolrox95** [comment]
To use potions, you must first click the potion icon in the header for a skill, as circled in red.
![image](https://user-images.githubusercontent.com/58208131/227703979-5a923aae-6692-4e9c-984b-77149e467a5b.png)
You will then be presented with a menu allowing you to select a potion.
