### ISSUE TITLE
[Translation Error]: <title>

### ISSUE THREAD

**Issue by Fose99** [MelvorIdle/melvoridle.github.io#3235]
### Which text in the game has a translation error?

Frostspark 1H Sword
![42C959AE-24C0-4C93-B634-4CB6244674F1](https://user-images.githubusercontent.com/126517461/221673330-6dc652f1-1993-44d3-819a-b3f7e6c49f1a.png)

**Comment by coolrox95** [comment]
Duplicate of #3072
