### ISSUE TITLE
[Bug]: quick equip 

### ISSUE THREAD

**Issue by Mcal11** [MelvorIdle/melvoridle.github.io#3236]
### Describe the bug

Quick equip doesn't include all relevant equippable items in skills. For example, none of the township equipment is available for quick equip. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5053

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Quick equip items are custom defined by the player. This can be done by selecting the item in the Bank, and adding it to the quick equip section within the Gear icon
