### ISSUE TITLE
expansion still activated, despite refunding

### ISSUE THREAD

**Issue by AmpedHEART** [MelvorIdle/melvoridle.github.io#3239]
### Describe the bug

bought throne of the herald expansion a few days ago, decided against it and refunded. however, my account still has the expansion active

### Expected behaviour

expected refund to deactivate expansion

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5053

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This seems like an error with the play store. Enjoy the free Expansion! haha
