### ISSUE TITLE
[Bug]: True game completion banner before actual completion

### ISSUE THREAD

**Issue by RomanGnome** [MelvorIdle/melvoridle.github.io#3240]
### Describe the bug

Nearing end of true true game completion, I got the game completion banner while still having a bit of crafting and fire making left to complete mastery on. I've added screenshots of my completion progress and mastery skills as reference.
Note: I was playing on the Brave browser when this occured.

### Reproduction Steps

Hard to reproduce, it happened when I spent mastery pool to finish out an item in crafting.

### Expected behaviour

I shouldn't have true game completion yet.

### Screenshots

![image](https://user-images.githubusercontent.com/35495985/222264577-4119a32d-0625-46c2-a189-a5599ac2d593.png)
![image](https://user-images.githubusercontent.com/35495985/222264983-6dfc1720-ae07-4679-a16a-c74114d865e4.png)
![image](https://user-images.githubusercontent.com/35495985/222265140-d8536f6a-8cec-477e-b106-af39db2074ca.png)
![image](https://user-images.githubusercontent.com/35495985/222265177-e0432910-3dea-4c1c-8a63-822b3ec4db7f.png)

### Console output

[melvoridle.com-1677705023805.log](https://github.com/MelvorIdle/melvoridle.github.io/files/10865386/melvoridle.com-1677705023805.log)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5040

### Are you using any mods?

Yes

**Comment by ekuland** [comment]
Loading Mods (4/18): SEMI Auto Master (v1.7.0)
lemme guess, cooking mastery over 100%?

**Comment by RomanGnome** [comment]
I've not worked on cooking or spent mastery since this happened, here is my cooking mastery
![image](https://user-images.githubusercontent.com/35495985/222335561-07e1377a-9091-4fde-b0fa-2f14e34dc400.png)

**Comment by MelvorIdle** [comment]
I believe the Cooking Mastery itself, from the completion log, will show it is above 100%?

**Comment by coolrox95** [comment]
This issue is due to Semi auto mastery
