### ISSUE TITLE
[Bug]: Steam overlay bugs the game itself

### ISSUE THREAD

**Issue by mindaugas-breachgg** [MelvorIdle/melvoridle.github.io#3241]
### Describe the bug

The melvor UI breaks down, and it like HTML codes are getting overrided every 0.2 seconds. 

### Reproduction Steps

Open steam overlay.

### Screenshots

![image](https://user-images.githubusercontent.com/101088398/222229164-a20a469e-df0c-4c13-a0b3-5e5667ea7eec.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

5053

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
We highly recommend you disable the Steam overlay for Melvor Idle as it is not compatible with the engine we use unfortunately.
