### ISSUE TITLE
[Spelling/Grammar]: goblin thief

### ISSUE THREAD

**Issue by ElvanLady** [MelvorIdle/melvoridle.github.io#3246]
### What text is wrong?

The goblin thief summon is spelled "golbin thief"
![Screenshot 2023-03-03 22 25 05](https://user-images.githubusercontent.com/55784148/222879969-31ef9d93-2d83-46c3-9f5a-e7031f633ad0.png)

### What is the correct spelling or grammar?

Goblin Thief

**Comment by Zethraxxur** [comment]
This is not wrong. They are all called Golbins in Melvor

**Comment by ElvanLady** [comment]
Ohhhhhh Okay thanks for the clarification
