### ISSUE TITLE
Bruce Pet bug 

### ISSUE THREAD

**Issue by PeteGr83** [MelvorIdle/melvoridle.github.io#3247]
### Describe the bug

Hello , i am at 99.6% completion and i only miss the Bruce Pet that i cant get for some reason , my character fighting in stab mode like a month now just to get the pet and nothing happens .
My acound name is Eldoran , can you please check if something is wrong ? 

### Save Link

https://melvoridle.com/save/CZsLu6oO

### Screenshots

![Screenshot_9](https://user-images.githubusercontent.com/126949380/222886812-a5ec17ee-dc13-4eaf-8676-226310fe5840.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5053

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Bad RNG is not a bug.
