### ISSUE TITLE
[Bug]: ToH cooking mastery

### ISSUE THREAD

**Issue by Portentum-V** [MelvorIdle/melvoridle.github.io#3248]
### Describe the bug

Mastery for ToH cooking items (lava fish, fancy meat pizza, ect) is not accounted for correctly towards 100% mastery.

### Expected behaviour

99 Mastery for each cooking item should be required for 100% mastery.

### Screenshots

![image](https://user-images.githubusercontent.com/5906393/222926219-71f22837-babe-4c79-a9b1-6833f6b81825.png)

![image](https://user-images.githubusercontent.com/5906393/222926316-e06ec1fd-b684-4a38-a29c-f6254a8970a6.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5053

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
This is a known issue with Semi Automastery, as it levels up an easter egg item that should not have mastery.
