### ISSUE TITLE
[Bug]: Still takes added damage when asleep despite having +0% Damage Slayer Items equipped

### ISSUE THREAD

**Issue by SUSSYBAKA12345** [MelvorIdle/melvoridle.github.io#3250]
### Describe the bug

While fighting the Twin Sea Dragon Serpent and having the necessary slayer items to have "Player takes +0% damage when asleep" satisfied, my player still takes increased damage when asleep and have even been killed due to it. 

### Expected behaviour

I expected to not take increased damage when asleep because of the +0% damage when asleep satisfied with slayer gear equipped. 

### Save Link

https://melvoridle.com/save/3nnJoqtH

### Screenshots

![image](https://user-images.githubusercontent.com/87591182/222953894-0b82e830-5286-4f3e-8258-5b0badcaf8ee.png)
![image](https://user-images.githubusercontent.com/87591182/222953936-b7074bc5-57fb-49fb-b0c1-3724f7c4417d.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5053

### Are you using any mods?

No

**Comment by 04Slash** [comment]
Taking extra damage when slept is a game mechanic. It cannot be reduced with Slayer Area Reduction.

> Sleep is an effect that prevents the target from attacking. While the target is asleep, hits against the target cannot miss and deal 20% increased damage. One stack of sleep is removed after the target completes an attack turn. https://wiki.melvoridle.com/w/Combat_Debuff#Sleep
