### ISSUE TITLE
[Bug]: AN ERROR OCCURRED WHILE PROCESSING TICKS:

### ISSUE THREAD

**Issue by shLinkymeister** [MelvorIdle/melvoridle.github.io#3252]
### Describe the bug

An error occurred while processing ticks:
Active Action: melvorD:Combat
Error Name: Error
Error Message: Tried to start timer: Act with invalid tick amount: -1
Stack Trace:
Error: Tried to start timer: Act with invalid tick amount: -1
    at Timer.start (https://steam.melvoridle.com/assets/js/built/combatManager.js?5053:263:7)
    at Player.queueNextAction (https://steam.melvoridle.com/assets/js/built/character.js?5053:304:77)
    at Player.act (https://steam.melvoridle.com/assets/js/built/character.js?5053:287:6)
    at Timer.Player.timers.act [as action] (https://steam.melvoridle.com/assets/js/built/player.js?5053:3:1636)
    at Timer.tick (https://steam.melvoridle.com/assets/js/built/combatManager.js?5053:260:89)
    at Player.activeTick (https://steam.melvoridle.com/assets/js/built/character.js?5053:260:30)
    at Player.activeTick (https://steam.melvoridle.com/assets/js/built/player.js?5053:38:20)
    at CombatManager.activeTick (https://steam.melvoridle.com/assets/js/built/combatManager.js?5053:55:61)
    at Game.tick (https://steam.melvoridle.com/assets/js/built/game.js?5053:177:123)
    at Game.runTicks (https://steam.melvoridle.com/assets/js/built/game.js?5053:174:96)
Current Equipment:
Helmet: melvorD:Dragon_Helmet
Platebody: melvorD:Dragon_Platebody_T_G
Platelegs: melvorD:Dragon_Platelegs
Boots: melvorD:Dragon_Boots
Weapon: melvorF:Ancient_2H_Sword
Amulet: melvorD:Amulet_of_Looting
Ring: melvorD:Gold_Topaz_Ring
Gloves: melvorD:Dragon_Gloves
Cape: melvorD:Obsidian_Cape

Action Information:
Is In Combat: true
Fight in Progress: true
-- Start of Player Information --
Next Action: Attack
Next Attack: melvorD:Normal
Is Attacking: true
Standard Spell Selected: melvorD:WaterStrike
Ancient Spell Selected undefined
Aurora Selected: undefined
Curse Selected: undefined
Active Prayers:melvorF:Burst_of_Strength, 
Equipped Food:
Item: melvorD:Cave_Fish, Qty: 2853
Item: melvorD:Cave_Fish_Perfect, Qty: 6764
Item: melvorD:Shark_Perfect, Qty: 3320
-- End Player Information --
-- Start of Enemy Information --
Enemy: melvorD:FrozenMammoth
Next Action: Attack
Next Attack: melvorD:Normal
Is Attacking: false
Standard Spell Selected: melvorD:WindStrike
Ancient Spell Selected undefined
Aurora Selected: undefined
Curse Selected: undefined
-- End Enemy Information --
Current Area Type: Combat
Current Area ID: melvorD:Icy_Hills
Modding Enabled. Loaded mods:
Dev
SEMI Core
Better Auto Eat
SEMI Auto Mine
Bank Tab Values
Quick Item/Bank Wiki
SEMI Auto Farming
Unlimited Offline
Shop Item Owned Indicator
SEMI Save on Close
SEMI Auto Slayer
Handy Dandy Notebook
SEMI Auto Bury
Township Breakdown
SEMI Auto Bonfire
Item Township Task Info
SEMI Auto Run
Clean UI
AutoMiner
Reduced Monster Spawn Time Forked
SEMI Auto Sell
SEMI Drop Chances
Kills in Combat
SEMI Auto Runecrafting
Bank Tab Icons
Show Skill Modifiers
Reveal Thieving Loot
Space Before Brackets
Real Quick Equip
Astrology Refund
Equipment Presets
Right Click Equip Menu

### Expected behaviour

uh i was just doing slayer tasks couldnt tell you what i did

### Save Link

https://melvoridle.com/save/CLi60a3r

### Screenshots

![melvor screenshot1](https://user-images.githubusercontent.com/127166585/223301589-06fe8290-fa37-48a1-b146-fb91cc712150.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5053

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
I am unable to reproduce this issue with your save file. It is very likely this is due to one of your installed mods.
