### ISSUE TITLE
[Bug]: Lephrecaun symmoning synerergy is not working as described

### ISSUE THREAD

**Issue by abcras** [MelvorIdle/melvoridle.github.io#3255]
### Describe the bug

Leprechaun summoning synergy has a 200% item cost increase instead of a 100% increase as written in the tooltip.

### Reproduction Steps

1. go to summoning page and select option to create Leprechaun
2. turn on Leprechaun synergy
3. see cost as 1500 instead of 1000

### Expected behaviour

Either 1000 cost or the text is wrong and should say 200%

### Screenshots

With
![image](https://user-images.githubusercontent.com/3748122/223781680-77c49b2d-ea30-44ba-858e-0c9e8b79e4be.png)

Without
![image](https://user-images.githubusercontent.com/3748122/223781774-d4a3ac89-8579-4d96-9349-9be389a27aa8.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5053

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.1.2
