### ISSUE TITLE
Runecrafting recipes not producing the expected amount

### ISSUE THREAD

**Issue by Ccappuccino** [MelvorIdle/melvoridle.github.io#326]
**Describe the bug**
Not getting the right amount of battlestaffs when crafting them.

**To Reproduce**
1. Go to 'Runecrafting'
2. Click on 'Staves & Wands' and select 'Earth Battlestaffs' 
3. Hit that sweet sweet craft button
4. See that it result in **1** crafted battlestaff

(Note: Applies with other staffs as well)

**Expected behavior**
It should result in **4** battlestaffs. 

**Screenshots**
<img width="790" alt="Screenshot 2020-07-29 at 10 03 01" src="https://user-images.githubusercontent.com/6918504/88773822-eff53680-d182-11ea-8b3b-014e5d7f8aae.png">

**Browser**
Google Chrome 
Version 84.0.4147.105 (Official Build) (64-bit)

**Console output**
...

**Are you using any scripts?**
...

**Comment by MelvorIdle** [comment]
Sorry, the "Produces" should say it only produces 1 of the item due to the recent change in the previous update. I will get this hotfixed.
