### ISSUE TITLE
[Bug]: breakdown of the main menu, overlay of the tab element on the level block

### ISSUE THREAD

**Issue by P01YAK** [MelvorIdle/melvoridle.github.io#3263]
### Describe the bug

message link:
https://discord.com/channels/625838709203271680/910888549296005140/1087066536147165265

breakdown of the main menu, overlay of the tab element on the level block

### Reproduction Steps

1 run the game
2 wait for the download
3 see that the menu loads randomly (once 5-6 times normal, once crooked)
4 restart (if not corrected, then restart again)
5 go into any activity and that the hat with the name interferes with viewing the level (it is possible and other closes)
* game language is Russian
* it was the same without modifications
* ios 16.3

### Expected behaviour

the application starts in the menu without any interface errors, so that the menu is visible from the first time. add a separation of the header and the main activity window (so that the beginning of the main window starts after the activity header)

### Save Link

https://melvoridle.com/save/3eIGNQyx

### Screenshots

![IMG_5773](https://user-images.githubusercontent.com/60546935/226196767-ce75fe25-a66b-4a73-8a26-5f2b2d7925f8.png)
![IMG_5772](https://user-images.githubusercontent.com/60546935/226196770-86d06c93-ada7-411c-9f1e-a9394afb7d6c.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5064

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Does this occur on any other languages? I'm unable to reproduce it.

**Comment by P01YAK** [comment]
No, I only have it in Russian like that.
And while I was checking, I noticed another flaw with the translation of the Russian version of the game: "logout of cloud". There must be something similar: "выйти из облака"

**Comment by P01YAK** [comment]
1.1.2 (5835) the same situation.
And the hint climbs on the block where there is a save button.
![image](https://user-images.githubusercontent.com/60546935/231595047-547494da-11ee-4691-8ad1-2875c9f22372.png)

And 1 more... "Hi, {username}" in Russian language "Привет, {username}"
