### ISSUE TITLE
[Bug]: Completion Log of the free version contains inachievable tasks

### ISSUE THREAD

**Issue by Tarassin** [MelvorIdle/melvoridle.github.io#3264]
### Describe the bug

The Completion Log of the demo (free) version of the game contains impossible tasks for this version. This includes (but may not be limited to) full version skills and masteries and specific items. The list below is my attempt to list them all, I may have forgotten some (using checkboxes so you can follow which one were fix during development):

Skills:

- [ ] Ranged
- [ ] Magic
- [ ] Prayer
- [ ] Slayer
- [ ] Thieving
- [ ] Fletching
- [ ] Crafting
- [ ] Runecrafting
- [ ] Herblore
- [ ] Agility
- [ ] Summoning
- [ ] Astrology
- [ ] Township

Masteries:

- [ ] Thieving
- [ ] Fletching
- [ ] Crafting
- [ ] Runecrafting
- [ ] Herblore
- [ ] Agility
- [ ] Summoning
- [ ] Astrology

Items:

- [ ] Blood Rune
- [ ] Light Rune
- [ ] Mist Rune
- [ ] Dust Rune
- [ ] Smoke Rune

I consider this a bug since demo version's Completion Log does not include most full version's items nor monsters or pets (these two categories are fully completable in demo version as full version's exclusives are hidden)

### Reproduction Steps

1. Play the demo (free) version
2. Open the Completion Log
3. Check the categories listed in the description
4. Figure out you can't ever complete those in the free version

### Expected behaviour

The Completion Log achievement should be hidden in the free version and only be available in the full version

### Screenshots

Skills:

![image](https://user-images.githubusercontent.com/63176112/226198592-bcdae712-9fa8-4683-a57b-64319b6b0df9.png)

Masteries:

![image](https://user-images.githubusercontent.com/63176112/226198560-e38211b9-3ed5-4c12-b090-c3c88f7a0ff9.png)

Items:

![image](https://user-images.githubusercontent.com/63176112/226198527-af4a89b7-af35-4582-954f-a5689a390d38.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5064

### Are you using any mods?

No

**Comment by coolrox95** [comment]
The demo is not intended to be able to reach 100% completion, as it is just a demo for the full version of the game.

**Comment by Tarassin** [comment]
I know that it should not be able to reach the real 100% completion, but since most items and pets of the full version are filtered out in the completion log (such as the gods armors and full version dungeons pets) I thought it would be normal to have ALL of them filtered out. My plan was to complete the demo with 100% completion as a challenge before buying the game, but it's impossible juste because some items appear (and not all of them).

Maybe the bug resoltion would not be to filter out the items I mentionned but to remove the filter altogether so all the full version items would be displayed in the completion log (this would also give an insight of what the full version's value is).
