### ISSUE TITLE
[Bug]: Still unable to login after the DLC...

### ISSUE THREAD

**Issue by LilH3ro** [MelvorIdle/melvoridle.github.io#3267]
### Describe the bug

It does not let me login, ive tried everything, resetting password, cleared all game files, tried reinstalling OS, Different browsers. Tried different pc's and internet... even asked in the discord. Its been since 20 oct and I haven't gotten any help in the discord... i was told to DM Malc but never got a reply

Username: Puffs

### Expected behaviour

I login and it just loads for 3 seconds and then goes back to login screen

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

Cant login so cant see

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Please provide a GIF or video of what seems to be happening so we can understand the issue more. If we can see the process, it will help us determine what may be causing issues.

**Comment by LilH3ro** [comment]
Here is a GIF of me trying to login, as you can see when i put my correct password it just loads, and if i do the wrong password it tells me so clearly something is wrong

![Melvor_Idle_SQY598VLRi](https://user-images.githubusercontent.com/20781099/229777053-7d93d831-aff0-4d9f-b26a-b5c79591b90a.gif)

**Comment by MelvorIdle** [comment]
Thanks for the GIF. I have sourced the issue of the bug and a fix has been applied. You should be able to login now.
