### ISSUE TITLE
[Bug]: <title>Wrong drop rate for Freezing Touch Material

### ISSUE THREAD

**Issue by iliveor** [MelvorIdle/melvoridle.github.io#3273]
### Describe the bug

In the wiki we can see that drop rate of Freezing Touch Material is 1.56%.
But I kill 2133 Polar Bears and have only 63 pieces of Treezing Touch Material.

### Save Link

https://melvoridle.com/save/CwUK8VsU

### Screenshots

![Снимок экрана 2023-03-24 214308](https://user-images.githubusercontent.com/35229749/227624467-ab20cc8c-f857-437f-9ee3-a79e4654a614.png)
![Снимок экрана 2023-03-24 214341](https://user-images.githubusercontent.com/35229749/227624470-2e5e1fb3-e7dc-4d1a-8db6-a62170b5d93e.png)
![Снимок экрана 2023-03-24 214413](https://user-images.githubusercontent.com/35229749/227624474-ed52ac75-d729-46f4-b363-94baeabf4aaf.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5064

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
RNG is not a bug. Also you obtained more than the expected value of ~33.3 for the drop for that number of kills, which is more than likely just loot doubling applying.

**Comment by iliveor** [comment]
Omg, it really is! Sorry for that. I've been to the dentist, and I don't seem to have recovered from the bad condition after having two teeth pulled. Seems when I calculated this I have forgotten that I need 100 pieces of material, not 1. I am really sorry.
