### ISSUE TITLE
[Bug]: An error occured while processing ticks

### ISSUE THREAD

**Issue by Keraliix** [MelvorIdle/melvoridle.github.io#3274]
### Describe the bug

This error message pops up when Ive killed a few magic fire demons in the lava lake slayer area.

### Save Link

https://melvoridle.com/save/kHutiJyx

### Screenshots

![image](https://user-images.githubusercontent.com/128982638/227780832-3e1e62bd-9612-4275-b4ce-1229cff7b3df.png)

### Console output

style.css?2:1          Failed to load resource: the server responded with a status of 404 ()
vb26e4fa9e5134444860be286fd8771851679335129114:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
vb26e4fa9e5134444860be286fd8771851679335129114:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloudManager.js?5064:201 Silent Sign in with JWT
cloudManager.js?5064:201 Validating Melvor Cloud token
cloudManager.js?5064:201 Storing Melvor Cloud Token
cloudManager.js?5064:201 Initializing PlayFab login. Method: customID
cloudManager.js?5064:201 Logging in with Custom ID via PlayFab
cloudManager.js?5064:201 Login with custom ID success
cloudManager.js?5064:201 Getting account info
cloudManager.js?5064:201 Account info retrieved
cloudManager.js?5064:201 Authenticated w/ Melvor Cloud: true
cloudManager.js?5064:201 Authenticated w/ PlayFab: true
cloudManager.js?5064:201 Checking for valid full version
cloudManager.js?5064:201 Checking for valid TotH purchase
cloudManager.js?5064:201 Loading Game Data...
save.js?5064:110 Registered Demo Data.
save.js?5064:110 Registered Full Version Data.
save.js?5064:110 Registered Throne of the Herald Data.
cloudManager.js?5064:201 Initializing Mod Manager...
cloud.js?5064:138 PlayFab Data Stored successfully.
cloudManager.js?5064:201 Checking for Mod Updates...
cloudManager.js?5064:201 Loading Mods...
cloudManager.js?5064:201 Loading Mods (1/24): SEMI Core (v1.7.2)
cloudManager.js?5064:201 Loading Mods (2/24): SEMI Auto Farming (v0.3.1)
cloudManager.js?5064:201 Loading Mods (3/24): SEMI Drop Chances (v1.4.0)
cloudManager.js?5064:201 Loading Mods (4/24): ETA (v1.0.2)
cloudManager.js?5064:201 Loading Mods (5/24): SEMI Auto Loot (v1.3.0)
cloudManager.js?5064:201 Loading Mods (6/24): SEMI Auto Eat (v1.4.0)
cloudManager.js?5064:201 Loading Mods (7/24): Shop Item Owned Indicator (v1.2.0)
cloudManager.js?5064:201 Loading Mods (8/24): SEMI Auto Slayer (v1.2.0)
cloudManager.js?5064:201 Loading Mods (9/24): SEMI Auto Runecrafting (v1.1.0)
cloudManager.js?5064:201 Loading Mods (10/24): Will I Die? (v4.2.1)
cloudManager.js?5064:201 Loading Mods (11/24): Kills in Combat (v0.0.1)
cloudManager.js?5064:201 Loading Mods (12/24): SEMI Auto Gear Swap (v1.4.0)
cloudManager.js?5064:201 Loading Mods (13/24): SEMI Auto Run (v1.3.0)
cloudManager.js?5064:201 Loading Mods (14/24): Better Auto Eat (v1.2)
8fb8afe3-7398-4c24-8287-88038f626be8:5 Better Auto Eat : Loading...
2mod.js?5064:819 [Better Auto Eat] Possible mod conflict - Player.damage has already been patched by the following mods: "SEMI Auto Eat"
patch @ mod.js?5064:819
8fb8afe3-7398-4c24-8287-88038f626be8:5 Better Auto Eat : Loaded!
cloudManager.js?5064:201 Loading Mods (15/24): Potion Downgrade (v0.0.2)
cloudManager.js?5064:201 Loading Mods (16/24): Show Skill Modifiers (v4.1.16)
cloudManager.js?5064:201 Loading Mods (17/24): Item Uses (v1.0.2)
cloudManager.js?5064:201 Loading Mods (18/24): Mastery Pool Can Overflow (v1.3.8)
cloudManager.js?5064:201 Loading Mods (19/24): Combat Indicators (v1.1.1.5)
cloudManager.js?5064:201 Loading Mods (20/24): SEMI Auto Sell (v1.1.0)
cloudManager.js?5064:201 Loading Mods (21/24): Show Locked Astrology Modifiers (v0.0.3)
cloudManager.js?5064:201 Loading Mods (22/24): Shining Star (v0.1.14)
cloudManager.js?5064:201 Loading Mods (23/24): Item Township Task Info (v0.0.5)
mod.js?5064:819 [Item Township Task Info] Possible mod conflict - BankSelectedItemMenu.setItem has already been patched by the following mods: "Item Uses"
patch @ mod.js?5064:819
cloudManager.js?5064:201 Loading Mods (24/24): Quick Equip Manager (v1.2.3)
cloudManager.js?5064:201 Loading Local Saves...
cloudManager.js?5064:201 Loading Cloud Saves...
cloudManager.js?5064:201 Getting saves from playfab
cloudManager.js?5064:201 Saves retrieved
characterSelect.js?5064:5 Loading character selection
cloudManager.js?5064:295 Connected to PlayFab successfully
4save.js?5064:39 Copied to clipboard successfully.
main.js?5064:15 Game Loaded
widget-v2.js:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing.
insert @ widget-v2.js:1
mod.js?5064:819 [SEMI Auto Slayer] Possible mod conflict - SlayerTask.setTask has already been patched by the following mods: "Will I Die?"
patch @ mod.js?5064:819
mod.js?5064:819 [SEMI Auto Slayer] Possible mod conflict - CombatManager.spawnEnemy has already been patched by the following mods: "SEMI Auto Gear Swap"
patch @ mod.js?5064:819
mod.js?5064:819 [SEMI Auto Sell] Possible mod conflict - Bank.addItem has already been patched by the following mods: "Shop Item Owned Indicator"
patch @ mod.js?5064:819
eab0711c-5db0-4953-b768-168450746ca6:587 ETA : Loading...
eab0711c-5db0-4953-b768-168450746ca6:587 ETA : added settings menu!
eab0711c-5db0-4953-b768-168450746ca6:587 ETA : Loaded!
mod.js?5064:819 [Shining Star] Possible mod conflict - Astrology.render has already been patched by the following mods: "Show Locked Astrology Modifiers"
patch @ mod.js?5064:819
vb26e4fa9e5134444860be286fd8771851679335129114:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloud.js?5064:29 Synchronising with Cloud
t.announcekit.app/collect/client:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
t.announcekit.app/collect/client:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
style.css:1          Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5064

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
This issue is due to the Better Auto Eat Mod. I have notified the mod author, so they may fix it. In the mean time you can uninstall it to resolve the issue.
