### ISSUE TITLE
[Bug]: cannot reset passord, find old email account, or make new account<title>

### ISSUE THREAD

**Issue by Ektopset** [MelvorIdle/melvoridle.github.io#3279]
### Describe the bug

Cannot log on with password or username, cannot use forget password bc email is "not associated with an account", and can't recreate an account because it says email is "associated with an account already"

### Expected behaviour

I believe since I used the same email it said was associated with an account it would let me log in with my password but when I go to forget password (even though I know my password is correct) it says the account doesn't exist.  

### Screenshots

![Screenshot_20230328_202003_Melvor Idle](https://user-images.githubusercontent.com/129236549/228395851-f30d8e8a-2cca-4868-aec0-4b8049818d29.jpg)
![Screenshot_20230328_201938_Melvor Idle](https://user-images.githubusercontent.com/129236549/228395856-8b767ac9-2546-4e01-979e-7df328c7b858.jpg)
![Screenshot_20230328_201921_Melvor Idle](https://user-images.githubusercontent.com/129236549/228395858-76f144d1-6fa0-44bf-988f-b344256d9dbd.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

Expansion

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
The username is registered without an email, which is something we allowed quite some time ago (Not anymore). If you wish to recover the account then please contact Malcs on discord to go through the recovery procedure.
