### ISSUE TITLE
Upgrading Potions into a Higher Tier Unavailable

### ISSUE THREAD

**Issue by r3gata** [MelvorIdle/melvoridle.github.io#328]
**Describe the bug**
When attempting to combine potions of a lower tier into a higher tier, the option to upgrade the potions is unavailable, even though the mastery requirement is satisfied.

**To Reproduce**
1. Craft potions up to a mastery level where you start to create the next tier of potion. In my case, I crafted Magic Damage potions from 1 to 20 mastery.
2. Click on remaining tier I potions in the bank.
3. Click on upgrade item.
4. Observe that the Upgrade button is not available on the popup, and the master requirement appears in red.

**Expected behavior**
Upon reaching the required mastery level (in this case, 15), I expected to be able to combine my tier I potions into tier II potions at a rate of 3:1.

**Screenshots**
![image](https://user-images.githubusercontent.com/30740731/88948354-d1b13880-d25f-11ea-8779-df73edb30d26.png)
![image](https://user-images.githubusercontent.com/30740731/88948377-db3aa080-d25f-11ea-915c-0c1928d46782.png)

**Browser**
Google Chrome Version 84.0.4147.105 (Official Build) (64-bit)

**Console output**
N/A

**Are you using any scripts?**
No scripts active.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
