### ISSUE TITLE
[Bug]: free auto eat

### ISSUE THREAD

**Issue by SweatiestRug** [MelvorIdle/melvoridle.github.io#3280]
### Describe the bug

There’s a way to eat (ios) when thieving or in combat so you can afk without auto eat. 

### Reproduction Steps

1. Scroll up+down using one finger
2. With 2nd finger, hold down eat while scrolling 
3. Join the 2 fingers while scrolling
4. Drag the now one finger to the menu interface and let go while scrolling 

### Expected behaviour

Eats whenever damaged.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5064

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This is pretty similar to the game's "hold the eat button down to eat constantly" mechanic. Takes a bit of effort to produce for similar results. Not something we can fix
