### ISSUE TITLE
[Bug]: Divine Scimitar image is skewed when using "View Item Stats"

### ISSUE THREAD

**Issue by markTAMU** [MelvorIdle/melvoridle.github.io#3281]
### Describe the bug

The picture for the Divine Scimitar becomes skewed when using the "View Item Stats" feature. seems to be given the wrong height pixels. Seems to only be the Divine Scimitar and no other items in the Smiting menus 

### Reproduction Steps

1. Open a save with Divine Scimitar unlocked on PC (mobile not tested)
2. go to Smiting -> Divine Gear -> Divine Scimitar
3. click on "View Item Stats"
4. see a skewed image

### Expected behaviour

Should be the same image of the Divine Scimitar matching the normal creation menu and mirroring the other Scimitars

### Screenshots

![image](https://user-images.githubusercontent.com/126930429/228709926-79c55322-cd7b-4fca-b631-256fa3096473.png)
Image showing the skewed picture.

Image showing how it should look:
![image](https://user-images.githubusercontent.com/126930429/228710021-1cc6b615-e8c3-4e70-b08f-74d956ac4b4b.png)

![image](https://user-images.githubusercontent.com/126930429/228710069-8a9320f9-34be-4aad-95eb-d27121062150.png)

![image](https://user-images.githubusercontent.com/126930429/228710102-8bff906f-0143-4f04-9839-08eebdb83811.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5064

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.1.2
