### ISSUE TITLE
[Bug]: Error Loading Local Save

### ISSUE THREAD

**Issue by AlexDTeichroeb** [MelvorIdle/melvoridle.github.io#3282]
### Describe the bug

Didn't change any settings or mods over the course of the last few months.  Recently, upon opening my save file, I get the message: "Error loading local save. Save version is higher than current game version".  If I try and access the cloud save it says: "Error loading this Cloud save. It may be corrupted".

I play both the mobile and steam version of the game. I'm wondering if somehow the mobile cloud save isn't compatible with the steam version and it's causing this issue. My save file still works perfectly fine in the app. When I try and import the save file it also states compatibility issues.

### Reproduction Steps

Unable to reproduce.

### Expected behaviour

Expected the save file to still work after not having changed any settings/mods.

### Save Link

https://melvoridle.com/save/Rx8XjSzj

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5064

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
The provided save loads fine for me. Can you disable all mods and try again? Although you didn't change any settings, its possible a mod auto updated and caused issues.
