### ISSUE TITLE
[Bug]: error calculating offline progress 

### ISSUE THREAD

**Issue by Drewid-65** [MelvorIdle/melvoridle.github.io#3287]
### Describe the bug

Rinsing chicken coop trying to get pet.

An error occured while processing ticks offline:
Active Action: melvorD:Combat
Error Name: TypeError
Error Message: Cannot read properties of undefined (reading 'createMonsterKillEvent')
Stack Trace:
TypeError: Cannot read properties of undefined (reading 'createMonsterKillEvent')
    at CombatManager.onEnemyDeath (https://android.melvoridle.com/assets/js/built/combatManager.js?5064:86:160)
    at CombatManager.checkDeath (https://android.melvoridle.com/assets/js/built/baseManager.js?5064:26:72)
    at Game.tick (https://android.melvoridle.com/assets/js/built/game.js?5064:177:148)
    at Game.runTicks (https://android.melvoridle.com/assets/js/built/game.js?5064:174:96)
    at https://android.melvoridle.com/assets/js/built/game.js?5064:225:132
Current Equipment:
Helmet: melvorF:Ragnar_God_Helmet
Platebody: melvorF:Ragnar_God_Platebody
Platelegs: melvorF:Ragnar_God_Platelegs
Boots: melvorF:Ragnar_God_Boots
Weapon: melvorF:Infernal_Claw
Shield: melvorF:Knights_Defender
Amulet: melvorD:Amulet_of_Fishing
Ring: melvorF:Ring_Of_Blade_Echoes
Gloves: melvorF:Ragnar_God_Gloves
Cape: melvorF:Max_Skillcape
Passive: melvorF:Hunters_Ring
Consumable: melvorF:Whetstone

Action Information:
Is In Combat: true
Fight in Progress: true
-- Start of Player Information --
Next Action: Attack
Next Attack: melvorF:BladeEchoes
Is Attacking: true
Standard Spell Selected: melvorD:WindStrike
Ancient Spell Selected undefined
Aurora Selected: undefined
Curse Selected: undefined
Active Prayers: None
Equipped Food:
Item: melvorTotH:Sandwich_Perfect, Qty: 2018
Item: melvorD:Whale, Qty: 16981
Item: melvorD:Whale_Perfect, Qty: 36566
-- End Player Information --
-- Start of Enemy Information --
Enemy: melvorD:Chicken
Next Action: Attack
Next Attack: melvorD:Normal
Is Attacking: false
Standard Spell Selected: melvorD:WindStrike
Ancient Spell Selected undefined
Aurora Selected: undefined
Curse Selected: undefined
-- End Enemy Information --
Current Area Type: Dungeon
Current Area ID: melvorD:Chicken_Coop
Modding Enabled. Loaded mods:
Dev
SEMI Core
Mastery Pool Can Overflow
SEMI Auto Farming

Get [Outlook for Android](https://aka.ms/ghei36)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4999

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Does the game load with mods disabled?
