### ISSUE TITLE
[Bug]: Amount select dropdown menu disappearing in shop menu unexpectedly when hovering off

### ISSUE THREAD

**Issue by peter-hunt** [MelvorIdle/melvoridle.github.io#3289]
### Describe the bug

View title and reproduction steps.

The problem was inconvenient when I always tried to click on the right of the textbox to try to edit the custom buy amount, and I'd press my mouse button to the left and off the dropdown menu, and it would just disappear, which I don't mean to do. 

### Reproduction Steps

1. Go to the shop menu and click on the "Buy x[number]" button to open the dropdown menu
2. click and hold the mouse button on the bar and then move the cursor off the dropdown bar and release the mouse button
3. dropdown bar closes.

### Expected behaviour

The dropdown menu is expected to disappear only if a new mouse button click event has been triggered when it is out of range of the opened dropdown menu so that users don't just close it unintentionally.

### Save Link

unrelated

### Screenshots

unrelated

### Console output

unrelated

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5147

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This should now be fixed as of v1.1.2
