### ISSUE TITLE
[Bug]: We ran into an error while calculating your Offline Progress! >:(

### ISSUE THREAD

**Issue by e86137** [MelvorIdle/melvoridle.github.io#3290]
### Describe the bug

There was an error logging in

### Reproduction Steps

An error occured while processing ticks offline:
Active Action: melvorD:Combat
Error Name: Error
Error Message: Tried to start timer: Act with invalid tick amount: -1
Stack Trace:
Error: Tried to start timer: Act with invalid tick amount: -1
    at Timer.start (https://melvoridle.com/assets/js/built/combatManager.js?5147:266:7)
    at Player.queueNextAction (https://melvoridle.com/assets/js/built/character.js?5147:304:77)
    at Player.act (https://melvoridle.com/assets/js/built/character.js?5147:287:6)
    at Player.timers.act [as action] (https://melvoridle.com/assets/js/built/player.js?5147:3:1636)
    at Timer.tick (https://melvoridle.com/assets/js/built/combatManager.js?5147:263:89)
    at Player.activeTick (https://melvoridle.com/assets/js/built/character.js?5147:260:30)
    at Player.activeTick (https://melvoridle.com/assets/js/built/player.js?5147:38:20)
    at CombatManager.activeTick (https://melvoridle.com/assets/js/built/combatManager.js?5147:55:61)
    at Game.tick (https://melvoridle.com/assets/js/built/game.js?5147:177:123)
    at Game.runTicks (https://melvoridle.com/assets/js/built/game.js?5147:174:96)
Current Equipment:
Helmet: melvorF:Desert_Hat
Platebody: melvorD:Dragon_Platebody_T_G
Platelegs: melvorD:Dragon_Platelegs_T_G
Boots: melvorD:Dragon_Boots_T_G
Weapon: melvorF:War_Axe
Amulet: melvorD:Amulet_of_Looting
Ring: melvorF:Silver_Ruby_Ring
Gloves: melvorD:Dragon_Gloves
Cape: melvorF:Knights_Cape
Summon1: melvorF:Summoning_Familiar_Minotaur

Action Information:
Is In Combat: true
Fight in Progress: true
-- Start of Player Information --
Next Action: Attack
Next Attack: melvorD:Normal
Is Attacking: true
Standard Spell Selected: melvorD:FireWave
Ancient Spell Selected undefined
Aurora Selected: undefined
Curse Selected: undefined
Active Prayers:melvorF:Ultimate_Strength, 
Equipped Food:
Item: melvorD:Basic_Soup, Qty: 2712
Item: melvorD:Shrimp, Qty: 67766
Item: melvorF:Apple, Qty: 127705
-- End Player Information --
-- Start of Enemy Information --
Enemy: melvorD:FrozenMammoth
Next Action: Attack
Next Attack: melvorD:Normal
Is Attacking: false
Standard Spell Selected: melvorD:WindStrike
Ancient Spell Selected undefined
Aurora Selected: undefined
Curse Selected: undefined
-- End Enemy Information --
Current Area Type: Combat
Current Area ID: melvorD:Icy_Hills
Modding Enabled. Loaded mods:
Dev
SEMI Core
Better Auto Eat
Double XP Weekends
Show Skill Modifiers
SEMI Auto Farming
SEMI Drop Chances
ETA
Mastery Pool Can Overflow
Shop Item Owned Indicator
Right Click Equip Menu

### Screenshots

https://cdn.discordapp.com/attachments/908716263583399966/1092241615378198599/image.png
https://cdn.discordapp.com/attachments/908716263583399966/1092298058395562014/image.png

### Console output

style.css:1          Failed to load resource: the server responded with a status of 404 ()
cloudManager.js?5147:204 Silent Sign in with JWT
cloudManager.js?5147:204 Validating Melvor Cloud token
cloudManager.js?5147:204 Storing Melvor Cloud Token
cloudManager.js?5147:204 Initializing PlayFab login. Method: customID
cloudManager.js?5147:204 Logging in with Custom ID via PlayFab
cloudManager.js?5147:204 Login with custom ID success
cloudManager.js?5147:204 Getting account info
cloudManager.js?5147:204 Account info retrieved
cloudManager.js?5147:204 Authenticated w/ Melvor Cloud: true
cloudManager.js?5147:204 Authenticated w/ PlayFab: true
cloudManager.js?5147:204 Checking for valid full version
cloudManager.js?5147:204 Checking for valid TotH purchase
cloudManager.js?5147:204 Loading Game Data...
save.js?5147:111 Registered Demo Data.
save.js?5147:111 Registered Full Version Data.
save.js?5147:111 Registered Throne of the Herald Data.
cloudManager.js?5147:204 Initializing Mod Manager...
cloud.js?5147:138 PlayFab Data Stored successfully.
cloudManager.js?5147:204 Checking for Mod Updates...
cloudManager.js?5147:204 Updating Mods...
mod.js?5147:116 [SEMI Auto Farming] No namespace is defined. The mod will have limited access to game APIs.
(匿名) @ mod.js?5147:116
mod.js?5147:116 [SEMI Drop Chances] No namespace is defined. The mod will have limited access to game APIs.
(匿名) @ mod.js?5147:116
cloudManager.js?5147:204 Loading Mods...
cloudManager.js?5147:204 Loading Mods (1/10): SEMI Core (v1.7.2)
cloudManager.js?5147:204 Loading Mods (2/10): Better Auto Eat (v1.2)
38d63e67-720c-4b8b-989b-c22a15e88b21:5 Better Auto Eat : Loading...
38d63e67-720c-4b8b-989b-c22a15e88b21:5 Better Auto Eat : Loaded!
cloudManager.js?5147:204 Loading Mods (3/10): Double XP Weekends (v1.0.2)
cloudManager.js?5147:204 Loading Mods (4/10): Show Skill Modifiers (v4.1.16)
cloudManager.js?5147:204 Loading Mods (5/10): SEMI Auto Farming (v0.3.1)
cloudManager.js?5147:204 Loading Mods (6/10): SEMI Drop Chances (v1.4.0)
cloudManager.js?5147:204 Loading Mods (7/10): ETA (v1.0.2)
cloudManager.js?5147:204 Loading Mods (8/10): Mastery Pool Can Overflow (v1.3.8)
mod.js?5147:819 [Mastery Pool Can Overflow] Possible mod conflict - SkillWithMastery.addMasteryPoolXP has already been patched by the following mods: "Double XP Weekends"
patch @ mod.js?5147:819
cloudManager.js?5147:204 Loading Mods (9/10): Shop Item Owned Indicator (v1.2.0)
cloudManager.js?5147:204 Loading Mods (10/10): Right Click Equip Menu (v2.5)
cloudManager.js?5147:204 Loading Local Saves...
cloudManager.js?5147:204 Loading Cloud Saves...
cloudManager.js?5147:204 Getting saves from playfab
cloudManager.js?5147:204 Saves retrieved
characterSelect.js?5147:5 Loading character selection
cloudManager.js?5147:298 Connected to PlayFab successfully
main.js?5147:15 Game Loaded
widget-v2.js:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing.
insert @ widget-v2.js:1
cloud.js?5147:289 updatePlayerTags
2c8f6d96-1ca6-4c62-acd2-1edbdfc3ef6a:587 ETA : Loading...
2c8f6d96-1ca6-4c62-acd2-1edbdfc3ef6a:587 ETA : added settings menu!
2c8f6d96-1ca6-4c62-acd2-1edbdfc3ef6a:587 ETA : Loaded!
55e7eadf-b65f-42e7-ac85-a49404f594b5:223 Melvor Equipment Menu Loaded
style.css:1          Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://static.cloudflareinsights.com/beacon.min.js/performance.min.js.map: HTTP 錯誤：狀態碼為 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP 錯誤：狀態碼為 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP 錯誤：狀態碼為 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/popper.min.js.map: HTTP 錯誤：狀態碼為 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5147

### Are you using any mods?

Yes

**Comment by e86137** [comment]
https://melvoridle.com/save/OTCKOxSN

**Comment by e86137** [comment]
> 能否請您提供損壞保存的副本，以便我看一下？

https://melvoridle.com/save/OTCKOxSN

**Comment by coolrox95** [comment]
This is a known issue that is caused by the Better Auto Eat mod. Uninstalling it will prevent further crashes.
