### ISSUE TITLE
[Bug]: Cannot finish Very Hard Task (Fishing)

### ISSUE THREAD

**Issue by Claaaaaay2** [MelvorIdle/melvoridle.github.io#3292]
### Describe the bug

When claiming the Elite Task in Township for having 5000 Raw Skeleton Fish, 5000 Raw Magic fish and 5000 Raw Seahorse, the fish are removed from my inventory, but the task is not completed, nor do I receive the rewards. This is the case on all platforms. I've been able to redeem the task on other accounts with the same mods installed.

### Reproduction Steps

1. Go to Township > Very Hard Tasks
2. Click Claim Rewards for the fishing task
3. Nothing seems to happen, but when checking the inventory, fish have been removed

### Expected behaviour

The stacks of fish should be removed from my inventory, the task removed from the task list, and rewards should be given to the account.

### Save Link

https://melvoridle.com/save/8h9QfSeO

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5147

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
I am unable to reproduce this bug when loading your save.

Can you please submit your mod list so I can take a look?

**Comment by Claaaaaay2** [comment]
Thanks for looking into it! These are my mods:

Item Uses
SEMI Core
SEMI Drop Chances
Show Skill Modifiers
ETA

**Comment by MelvorIdle** [comment]
Thanks. I can confirm the issue is Quick Equip Manager that causes the bug. Disabling that mod allowed me to successfully redeem the task.
