### ISSUE TITLE
[Bug]: Android App Crashing on Load

### ISSUE THREAD

**Issue by dansalerno712** [MelvorIdle/melvoridle.github.io#3297]
### Describe the bug

When loading the game using the Android app, it crashes before the offline progress screen shows. I have tried clearing cache, reinstalling the app, and disabling all mods but it still crashes.

My save does work fine when I load it on the desktop browser version

### Reproduction Steps

Open the Android app
Click on the save and load it
Game crashes 

### Expected behaviour

I expect my save to load and the offline progress screen to show and then allow me to play

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/EmdXDoWt

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5165

### Are you using any mods?

Yes

**Comment by dansalerno712** [comment]
This seems to be intermittent, I've gotten my save to load sometimes, but it still crashes occasionally

**Comment by dansalerno712** [comment]
Looks like it is an issue with Android system WebView. I uninstalled the Android system WebView updates on my device and it is working fine now

**Comment by Sammehbrah** [comment]
I can confirm this fix for the same issue.
