### ISSUE TITLE
[Bug]: Agility Mastery Token Chance is Incorrect

### ISSUE THREAD

**Issue by Auron956** [MelvorIdle/melvoridle.github.io#3298]
### Describe the bug

The Agility mastery token chance for skill level 105 and above is incorrect, this is due to to the level getter of the AgilityObstacle class being incorrectly defined - as of the Throne of the Herald expansion an obstacle's skill level requirement is not always equal to 10 times the obstacle's category.

### Reproduction Steps

1. Reach skill level 120 in Agility
2. Observe that ` game.agility.totalUnlockedMasteryActions ` is less than ` game.agility.trueTotalMasteryActions`

### Expected behaviour

The level getter should make use of `Agility.getObstacleLevel()` to correctly determine the skill level for a particular category of obstacles.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5165

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.2,
