### ISSUE TITLE
[Bug]: Big number in shop quantity

### ISSUE THREAD

**Issue by nicloay** [MelvorIdle/melvoridle.github.io#3299]
### Describe the bug

If you enter a big number in the shop quantity it's not possible to reset this number anymore, as a result, you can not purchase any item with quantity from there
![image](https://user-images.githubusercontent.com/1671030/230838976-03769767-ba0e-44aa-8a2c-924156d91b9b.png)
bug persist if you will try to quickly buy an item from any activity screen 
![image](https://user-images.githubusercontent.com/1671030/230839154-f5e9738a-1483-4eaa-bf9c-8c080fec0abc.png)

### Reproduction Steps

1. In the purchase screen in the custom number quantity input box hold nine and enter the number while it allows you to put a number.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

5165

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was fixed with the v.1.1.2 update
