### ISSUE TITLE
Magic Milestones Out of Order

### ISSUE THREAD

**Issue by Ness-9** [MelvorIdle/melvoridle.github.io#330]
**Describe the bug**
If you open the milestone menu for Magic, "Earth Blast" (33 magic) is listed after "Adept Air Wizard Gear" (35 magic)

**To Reproduce**
1. Go to the 'Milestones' page
2. Click on 'Magic'
3. Scroll down to 'Earth Blast'

**Expected behavior**
Earth Blast should be listed before Adept Air Wizard Gear

**Screenshots**
![image](https://user-images.githubusercontent.com/69043252/89037687-9b79c480-d304-11ea-957f-9c3a6ab1c579.png)

**Browser**
Google Chrome 84.0.4147.105

**Console output**
N/A

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
