### ISSUE TITLE
Game Crashing Android

### ISSUE THREAD

**Issue by shadrafael** [MelvorIdle/melvoridle.github.io#3300]
### Describe the bug

I were playing normally Melvor Idle but in the past 5 days the game keeps crashing in the loading screen.

I tried on Android and Google Chrome but same problem.

I were fighting.

### Reproduction Steps

1. Try play the game
2. Choose the load file
3. The game crashes trying to show offline progression

### Expected behaviour

Play the game.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

Most recent

### Are you using any mods?

No

**Comment by shadrafael** [comment]
Seems to be an problem with and update in Android Web Views, i unistalled the update and now works fine on Android. 

Can u check why this update is causing problems with Android?

**Comment by Sammehbrah** [comment]
I Have had the same issue and can verify this fix.

**Comment by MelvorIdle** [comment]
This crashing is due to a recent Webview update provided by Google and is out of our control until Google submits a public fix.

Try following these steps to fix it for now:

Steps:
Go to Google Play Store > search for Android System WebView Beta by Google LLC > install > open > tap the three dots menu > Change WebView Provider > select Android System WebView Beta

**Comment by Dutchviper** [comment]
i have this issue but i can not change anything on the Android System WebView.
my phone uses Android 9 and my WebView version is 79.0.3945.116. (from what i find a verry old version).
i can not update it and i cant install a Beta version.

i noticed a new character didn't had the issue.
so i played there. but now that i unlocked de Township skill there it gives the same behavior
