### ISSUE TITLE
[Bug]: Error on load and crash while playing.

### ISSUE THREAD

**Issue by Skeebou** [MelvorIdle/melvoridle.github.io#3301]
### Describe the bug

I have been running the Air God dungeon and randomly keep getting a bug that causes the game to lock up. This happens during active play as well as when I load up a save. This has happened on both IOS and Steam. The error only seems to happen during combat. I have been doing non-combat tasks and have not had the error occur. I have had it happen in the Ice dungeon as well. It also happened while fighting dragons.

### Reproduction Steps

1. Load up a save after being offline and the bug is sometimes there, sometimes not.
2. Run the game in the background and randomly have the error pop up.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/92l8lI5E

### Console output

An error occurred while processing ticks:
Active Action: melvorD:Combat
Error Name: Error
Error Message: Tried to start timer: Act with invalid tick amount: -1
Stack Trace:
Error: Tried to start timer: Act with invalid tick amount: -1
    at Timer.start (https://steam.melvoridle.com/assets/js/built/combatManager.js?5165:265:7)
    at Player.queueNextAction (https://steam.melvoridle.com/assets/js/built/character.js?5165:304:77)
    at Player.act (https://steam.melvoridle.com/assets/js/built/character.js?5165:287:6)
    at Timer.Player.timers.act [as action] (https://steam.melvoridle.com/assets/js/built/player.js?5165:3:1636)
    at Timer.tick (https://steam.melvoridle.com/assets/js/built/combatManager.js?5165:262:89)
    at Player.activeTick (https://steam.melvoridle.com/assets/js/built/character.js?5165:260:30)
    at Player.activeTick (https://steam.melvoridle.com/assets/js/built/player.js?5165:38:20)
    at CombatManager.activeTick (https://steam.melvoridle.com/assets/js/built/combatManager.js?5165:55:61)
    at Game.tick (https://steam.melvoridle.com/assets/js/built/game.js?5165:177:123)
    at Game.runTicks (https://steam.melvoridle.com/assets/js/built/game.js?5165:174:96)
Current Equipment:
Helmet: melvorD:Ancient_Helmet_T_G
Platebody: melvorD:Ancient_Platebody_T_G
Platelegs: melvorD:Ancient_Platelegs_T_G
Boots: melvorD:Dragon_Boots_T_G
Weapon: melvorF:Infernal_Claw
Shield: melvorD:Dragonfire_Shield
Amulet: melvorD:Fury_of_the_Elemental_Zodiac
Ring: melvorD:Aorpheats_Signet_Ring
Gloves: melvorF:Ancient_Dhide_Vambraces_U
Cape: melvorF:Infernal_Cape
Summon1: melvorF:Summoning_Familiar_Minotaur
Summon2: melvorF:Summoning_Familiar_Centaur
Consumable: melvorF:Whetstone

Action Information:
Is In Combat: true
Fight in Progress: true
-- Start of Player Information --
Next Action: Attack
Next Attack: melvorD:Normal
Is Attacking: true
Standard Spell Selected: undefined
Ancient Spell Selected melvorF:SlicingWinds
Aurora Selected: undefined
Curse Selected: undefined
Active Prayers:melvorF:Battleheart, melvorTotH:Valor, 
Equipped Food:
Item: melvorTotH:Sandwich, Qty: 7529
Item: melvorTotH:Lava_Fish, Qty: 13729
Item: melvorTotH:Lava_Fish_Perfect, Qty: 24428
-- End Player Information --
-- Start of Enemy Information --
Enemy: melvorF:Aeris
Next Action: Attack
Next Attack: melvorF:Cyclone
Is Attacking: true
Standard Spell Selected: melvorD:WindStrike
Ancient Spell Selected undefined
Aurora Selected: undefined
Curse Selected: undefined
-- End Enemy Information --
Current Area Type: Dungeon
Current Area ID: melvorF:Air_God_Dungeon
Modding Enabled. Loaded mods:
Dev
SEMI Core
Unlimited Offline
SEMI Auto Loot
SEMI Auto Farming
SEMI Auto Master
SEMI Auto Sell
SEMI Auto Bonfire
SEMI Auto Runecrafting
Better Auto Eat
SEMI Auto Slayer
SEMI Auto Mine
SEMI Auto Smith Bars
SEMI Auto Bury
Reveal Thieving Loot
QuickShards
SEMI Auto Open
SEMI Auto Collect Stockpiles
SEMI Save on Close
Kills in Combat
QoL - Grouped Notifications
Bypass Agility Costs
Show Locked Astrology Modifiers

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5165

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
This is a known issue that is caused by the Better Auto Eat mod. Uninstalling it will prevent further crashes.
