### ISSUE TITLE
[Bug]: Superior capes not a quick selection option

### ISSUE THREAD

**Issue by mckrk** [MelvorIdle/melvoridle.github.io#3302]
### Describe the bug

Superior capes need to be added to the quick equip option on the gear thing on skill pages.

### Expected behaviour

Superior capes should show up as an option in the quick equip menu.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5165

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
You set what items appear here yourself. Click the item in the bank -> click the gear icon -> set the item to the minibar
