### ISSUE TITLE
[Bug]: Gem Finder Scroll not being consumed

### ISSUE THREAD

**Issue by omasella** [MelvorIdle/melvoridle.github.io#3304]
### Describe the bug

When equipped, the gem finder scroll does not get consumed while mining both with and without the gem gloves. 

Note: version should be 1.1.2 below but that wasn't one of the options.

### Reproduction Steps

1. Obtain the gem finder scroll from the newly updated Township
2. Equip it to the consumable slot
3. Start mining any ore (I've been mining iridium)
4. Optionally equip the gem gloves
5. Observe the gem finder scroll not being consumed even when I obtain more than 1 gem from a mining action.

### Expected behaviour

I expect the gem finder scroll to be consumed/incremented every time a gem is obtained in mining. While the functionality of it isn't entirely clear as to when it'll be consumed, I would at least expect it to be consumed when I get more than 1 gem from a single mining action.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/9SZlW41z

### Screensho  ts

First image: before obtaining 2 gems in one action. 38 scrolls are equipped
<img width="1143" alt="Screenshot 2023-04-11 at 10 46 25 PM" src="https://user-images.githubusercontent.com/59977419/231362604-22e2ca66-c353-4a21-b7a6-108e769c60a0.png">

Second image: after obtaining 2 gems in one action. 38 scrolls are still equipped
<img width="1144" alt="Screenshot 2023-04-11 at 10 46 39 PM" src="https://user-images.githubusercontent.com/59977419/231362621-3744b096-d008-472a-992b-84c192265af0.png">

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5834

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This has now been fixed as of v1.1.2 ?5852
