### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by jorgebush12** [MelvorIdle/melvoridle.github.io#3305]
### Describe the bug

Using IOS
Local save and cloud save both stuck earlier in day. 
Force save button has constant spinning icon - able to press it however then becomes a pressed button with constant spinning icon. 
Even when game is updated using export and import brings back to local save from earlier in day 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5835

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This issue has now been hotfixed. Thank you for your patience.

**Comment by jorgebush12** [comment]
Heya

This hasn’t been fixed for me!

Still unable to save.

thanks

**Comment by MelvorIdle** [comment]
Have you closed the game completely and re-opened it, then loaded a save and tested?

**Comment by jorgebush12** [comment]
Woo hoo!! it is sorted now thank you very much for the message!!
