### ISSUE TITLE
[Spelling/Grammar]: "Township has been reworked!" message

### ISSUE THREAD

**Issue by Kr4pper** [MelvorIdle/melvoridle.github.io#3306]
### Main spelling issues:
Current:
> Saved Ticks have also been converted to the equivelant time saved. You can spend this time until it reaches 0. However, it is no longer possible gain ticks to spend.

Suggested:
> Saved Ticks have also been converted to the **EQUIVALENT** time saved. You can spend this time until it reaches 0. However, it is no longer possible **TO** gain ticks to spend.

Changes:
- fix typo in "equivalent"
- add missing "to"

### Additional non-spelling/grammer text change suggestion:
Current:
> You have been refunded the difference in GP spent - 1,234,567 GP

Suggested:
> You have been refunded the difference in GP spent: 1,234,567 GP

Change:
- use colon instead of dash to prevent possible misunderstanding of GP refund being a negative number

### What is the correct spelling or grammar?

Oops, didn't see this was a thing. Correct spelling/grammar is listed above along with rationale for it.

**Comment by MelvorIdle** [comment]
This has now been fixed as of v1.1.2 ?5852
