### ISSUE TITLE
[Translation Error]: "View Chest Contents" modal

### ISSUE THREAD

**Issue by Kr4pper** [MelvorIdle/melvoridle.github.io#3308]
### Which text in the game has a translation error?

Reproduction steps:
- Select container in bank
- Select "View Chest Contents" link

![image](https://user-images.githubusercontent.com/20116607/231417985-280d49dd-1936-4898-8480-74c79d7a46d9.png)

**Comment by 04Slash** [comment]
This is a mod issue. Disable 'SEMI Drop Chances' or wait until an update.

**Comment by Kr4pper** [comment]
@04Slash Whoops I forgot to think about the possibility of installed mods being the culprit. I will close this issue. Do you think https://github.com/MelvorIdle/melvoridle.github.io/issues/3307 would also be caused by mods? It presents slightly differently than this issue.

**Comment by 04Slash** [comment]
Probably also caused by SDC. I'd remove it and do a quick check. I don't see that issue on my end.

**Comment by Kr4pper** [comment]
Yeah it is indeed SDC causing the issue, thanks again for pointing that out, I'll close the other issue as well.
