### ISSUE TITLE
[Bug]: Cloud save not working as of v1.1.2 (demo account)

### ISSUE THREAD

**Issue by thomaskoppelaar** [MelvorIdle/melvoridle.github.io#3309]
### Describe the bug

Hi,
I've been playing since v1.1.1, and as of the v1.1.2 update it seems that the cloud save functionality has stopped working. I'm playing on a demo account.

This bug happens both on mobile and on web (firefox).

Force save also doesn't work.

### Reproduction Steps

1. Go to a save
2. Wait and see if the cloud save works

### Expected behaviour

A popup should appear saying the cloud save was succesful

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/sdG9e6rQ

### Console output

Silent Sign in with JWT [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Validating Melvor Cloud token [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Storing Melvor Cloud Token [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Initializing PlayFab login. Method: customID [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Logging in with Custom ID via PlayFab [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Login with custom ID success [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Getting account info [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Account info retrieved [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Authenticated w/ Melvor Cloud: true [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Authenticated w/ PlayFab: true [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Checking for valid full version [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Loading Game Data... [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Registered Demo Data. [save.js:111:190](https://melvoridle.com/assets/js/built/save.js?5835)
Loading Local Saves... [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Loading Cloud Saves... [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Getting saves from playfab [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Saves retrieved [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Loading character selection [characterSelect.js:5:297](https://melvoridle.com/assets/js/built/characterSelect.js?5835)
Connected to PlayFab successfully [cloudManager.js:336:119](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Game Loaded [main.js:15:315](https://melvoridle.com/assets/js/built/main.js?5835)
Connected to PlayFab successfully [cloudManager.js:336:119](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
updatePlayerTags [cloud.js:99:16](https://melvoridle.com/assets/js/built/cloud.js?5835)
Took 0.377s to process 185390 ticks. 0.0020335508927126597ms per tick. [game.js:176:84](https://melvoridle.com/assets/js/built/game.js?5835)
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data [b0110f10e81af2ba7d56.js:1:19980](https://cdn.announcekit.app/b0110f10e81af2ba7d56.js)
Uncaught Error: Current Season is undefined
    encode https://melvoridle.com/assets/js/built/township.js?5835:690
    encode https://melvoridle.com/assets/js/built/township.js?5835:168
    encode https://melvoridle.com/assets/js/built/game.js?5835:293
    forEach https://melvoridle.com/assets/js/built/namespaceRegistry.js?5835:37
    encode https://melvoridle.com/assets/js/built/game.js?5835:293
    generateSaveString https://melvoridle.com/assets/js/built/game.js?5835:276
    saveData https://melvoridle.com/assets/js/built/save.js?5835:17
    autoSave https://melvoridle.com/assets/js/built/game.js?5835:270
    loop https://melvoridle.com/assets/js/built/game.js?5835:199
50 [township.js:690:7](https://melvoridle.com/assets/js/built/township.js?5835)
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data [b0110f10e81af2ba7d56.js:1:19980](https://cdn.announcekit.app/b0110f10e81af2ba7d56.js)
Uncaught Error: Current Season is undefined
    encode https://melvoridle.com/assets/js/built/township.js?5835:690
    encode https://melvoridle.com/assets/js/built/township.js?5835:168
    encode https://melvoridle.com/assets/js/built/game.js?5835:293
    forEach https://melvoridle.com/assets/js/built/namespaceRegistry.js?5835:37
    encode https://melvoridle.com/assets/js/built/game.js?5835:293
    generateSaveString https://melvoridle.com/assets/js/built/game.js?5835:276
    saveData https://melvoridle.com/assets/js/built/save.js?5835:17
    autoSave https://melvoridle.com/assets/js/built/game.js?5835:270
    loop https://melvoridle.com/assets/js/built/game.js?5835:199
14 [township.js:690:7](https://melvoridle.com/assets/js/built/township.js?5835)
Uncaught Error: Current Season is undefined
    encode https://melvoridle.com/assets/js/built/township.js?5835:690
    encode https://melvoridle.com/assets/js/built/township.js?5835:168
    encode https://melvoridle.com/assets/js/built/game.js?5835:293
    forEach https://melvoridle.com/assets/js/built/namespaceRegistry.js?5835:37
    encode https://melvoridle.com/assets/js/built/game.js?5835:293
    generateSaveString https://melvoridle.com/assets/js/built/game.js?5835:276
    saveData https://melvoridle.com/assets/js/built/save.js?5835:17
    autoSave https://melvoridle.com/assets/js/built/game.js?5835:270
    loop https://melvoridle.com/assets/js/built/game.js?5835:199
    setInterval handler*startMainLoop https://melvoridle.com/assets/js/built/game.js?5835:143
    unpauseActiveSkill https://melvoridle.com/assets/js/built/game.js?5835:158
    fulfilled https://melvoridle.com/assets/js/built/language.js?5835:2
    promise callback*step https://melvoridle.com/assets/js/built/language.js?5835:4
    __awaiter https://melvoridle.com/assets/js/built/language.js?5835:5
    __awaiter https://melvoridle.com/assets/js/built/language.js?5835:2
    unpauseActiveSkill https://melvoridle.com/assets/js/built/game.js?5835:154
    onloadEvent https://melvoridle.com/assets/js/built/save.js?5835:83
    fire https://melvoridle.com/assets/js/ifvisible.js:5
    fire https://melvoridle.com/assets/js/ifvisible.js:5
    focus https://melvoridle.com/assets/js/ifvisible.js:9
    t

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5835

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
A Hotfix has now been applied to the game to rectify this issue. Thank you for your patience.
