### ISSUE TITLE
Magic milestones don't match actual unlocks

### ISSUE THREAD

**Issue by lawl281** [MelvorIdle/melvoridle.github.io#331]
**Describe the bug**
Fire strike unlocks at level 10 according to combat but the magic milestone page says it unlocks at level8.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser**
chrome
**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

**Comment by MelvorIdle** [comment]
Fixed in coming update
