### ISSUE TITLE
[Bug]: Township boxes

### ISSUE THREAD

**Issue by Merisorax** [MelvorIdle/melvoridle.github.io#3310]
### Describe the bug

Boxes purchased from township always contain the maximum amount of the rolled item. 

![obraz](https://user-images.githubusercontent.com/29403293/231421344-dc02905e-6596-4a2d-976a-6ffea6508e85.png)

### Reproduction Steps

1. Buy any box from township trader
2. Open it in bank

### Expected behaviour

The box should roll the item and the quantity of it, as it is written in the description "Up to ..."

![obraz](https://user-images.githubusercontent.com/29403293/231423084-14767fc3-6608-4856-a572-1b113fbdc8ec.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5835

### Are you using any mods?

No

**Comment by Kr4pper** [comment]
![image](https://user-images.githubusercontent.com/20116607/231440596-37c2b77e-5d37-47d5-a5f3-efff6320e02c.png)

Worth noting that the description of the box in the township trader tooltip does not indicate the existence of a roll range. Maybe this is not a game bug but instead the wording should be changed to not include "up to"?

**Comment by MelvorIdle** [comment]
This is intended. They will always provide a set amount.

**Comment by MelvorIdle** [comment]
They are intended to always provide the set amount. We will try to adjust the popup box to accomodate.
