### ISSUE TITLE
Consumable Enhancer doesn't do anything

### ISSUE THREAD

**Issue by RogueSeraph0257** [MelvorIdle/melvoridle.github.io#3311]
### Describe the bug

There is no function for Consumable Enhancer, other than you cal sell it.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

5835

### Are you using any mods?

No

**Comment by Merisorax** [comment]
Have you tried it on the items listed below? Works fine for me

![obraz](https://user-images.githubusercontent.com/29403293/231461044-57d62134-8958-414a-a287-2d4ef562f805.png)

**Comment by MelvorIdle** [comment]
The consumable enhancer is used in upgrades like stated in the patch notes, and the item description. When upgrading a listed consumbale, the Consumable Enhancer is used as an ingredient of that upgrade.

**Comment by RogueSeraph0257** [comment]
Do you plan on adding this list to a description in the Enhancer, like the way we can see stats of a particular item?
