### ISSUE TITLE
[Bug]: <Township Grasslands percentage>

### ISSUE THREAD

**Issue by rorybum** [MelvorIdle/melvoridle.github.io#3312]
### Describe the bug

I have fully upgraded everything in township and all other biomes apart from grasslands say 100%. Grasslands is stuck at 99,3% and has the symbol that something needs to be repaired even though everything is fully repaired.

### Expected behaviour

I would expect that it is at 100%

### Screenshots

![Melvor_Township_Bug](https://user-images.githubusercontent.com/130563615/231448152-7e2f60f2-0ac9-4af6-86ad-017fae1f4e7e.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5835

### Are you using any mods?

Yes

**Comment by ABukSwienty** [comment]
Also happening for me on IOS

V 1.1.2 (5835)

https://user-images.githubusercontent.com/88147569/231519003-93538a32-5b54-4b7c-97b7-047fdc2faba3.MOV

**Comment by MelvorIdle** [comment]
This has now been fixed as of v1.1.2 ?5852
