### ISSUE TITLE
[Bug]: Township population wrong

### ISSUE THREAD

**Issue by Tilara** [MelvorIdle/melvoridle.github.io#3314]
### Describe the bug

My total population is not correct, arid planes houses arent contributing to the the total

### Reproduction Steps

I think it happened from buy the upgrade in 25 bulk and it didnt increase my population by 25 lvls

### Screenshots

<img width="1920" alt="2023-04-12" src="https://user-images.githubusercontent.com/130566446/231456149-703c9457-0790-4bad-b031-518d8e9f1052.png">

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5835

### Are you using any mods?

No

**Comment by Merisorax** [comment]
Have you tried increasing your happiness? Since it now increases population by a %, maybe it lowers it too. 

![obraz](https://user-images.githubusercontent.com/29403293/231460625-f5d7a39e-e125-4284-99b3-8621e317e652.png)

**Comment by Tilara** [comment]
even at 100% normal population its still half of what it should be from upgrades

**Comment by MelvorIdle** [comment]
Can you please provide you save so we can look into this.

What exactly do you think your population _should_ be? There are many factors that go into population now including Building Efficiency, Health, and Worship modifiers that affect certain Biomes, and season modifiers.
