### ISSUE TITLE
[Translation Error]: UNDEFINED TRANSLATION:COMBAT_MISC

### ISSUE THREAD

**Issue by pig-cop** [MelvorIdle/melvoridle.github.io#3315]
### Which text in the game has a translation error?

At least for the italian version of the game this happens in the Combat Areas and Slayers Areas after the v1.1.2 update.

![melvor_bug](https://user-images.githubusercontent.com/1793444/231466843-e533cbc2-5f6d-42e7-9728-b80cdb97a4f2.jpg)

**Comment by 04Slash** [comment]
This is a mod issue. Disable 'Can I die?' or wait until a fix.

**Comment by pig-cop** [comment]
You are right, actually I forgot to check if it was caused by a mod.
