### ISSUE TITLE
[Bug]: Saving not functioning on IOS Mobile

### ISSUE THREAD

**Issue by JPKluding** [MelvorIdle/melvoridle.github.io#3318]
### Describe the bug

Currently upon entombment the game, when the game tries to save to the cloud upon launch it enters a cycle by which it can not. Upon clicking force save, the game can still not save. No local saves are made either as game is locked trying to save to the cloud. Have tried deleting game cache and deleting and reinstalling game altogether to no avail.

Additionally unable to export saves during this time.

### Reproduction Steps

1. Open game.
2. Select save game from local or cloud.
3. Game will enter state where up it tries to fruitlessly save
4. When trying to export save, game does not 

### Expected behaviour

Game is expected to save to cloud and or locally. Game is also expected to be able to export saves.

### Screenshots

![365521F3-E2E6-40B6-B56C-EC11300FF6B2](https://user-images.githubusercontent.com/130575239/231484529-e7163026-c457-4d6b-ac94-a8022c504301.jpeg)

Photo of game continuously attempting to save.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5835

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Related #3309

**Comment by MelvorIdle** [comment]
A Hotfix has now been applied to the game to rectify this issue. Thank you for your patience.
