### ISSUE TITLE
Summoning screen scrolls down too far

### ISSUE THREAD

**Issue by JacobtheButt** [MelvorIdle/melvoridle.github.io#3319]
### Describe the bug

When scrolling down on the summoning tab the items don't scroll down with the screen

### Reproduction Steps

1. Go to summoning screen
2. Go to Tablets and Familiars tab
3. Scroll down to bottom

### Expected behaviour

The screen should have stopped scrolling after a bit and the item should have continued to scroll downwards

### Screenshots

https://user-images.githubusercontent.com/113054037/231473986-b0814c0f-339a-44d9-97cb-b68560804e7d.PNG
https://user-images.githubusercontent.com/113054037/231474135-0df4e5aa-bcc7-4c54-a79a-d03c7a4c96de.PNG

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5835

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This has now been fixed as of v1.1.2 ?5852
