### ISSUE TITLE
Melvor won't start in Firefox for Mac, stuck loading

### ISSUE THREAD

**Issue by seiyix** [MelvorIdle/melvoridle.github.io#332]
**Describe the bug**
I try to open melvor website as usual but it does not show more that the red m from the loading page, stuck in a loop. I tried uninstalling all extension, cleaning cache and all temp files, reinstalling chrome, updating java but no solution.
Incognito mode works well, and other browsers too. Just the normal firefox mode won't load

**To Reproduce**
1. Go to melvoridle.com on Firefox for Mac
2. Wait until it loads

**Expected behavior**
You would expect the game to open normally, but necer passes the loading page

**Screenshots**
![Captura de Pantalla 2020-08-01 a les 15 56 00](https://user-images.githubusercontent.com/69112005/89124036-29f07080-d4d4-11ea-8330-2e8d948a00f6.png)

**Browser**
last version of firefox for mac

**Console output**
Please open the console by pressing F12 and copy it here.
Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-129674422-1”. melvoridle.com:6:1
Loading failed for the <script> with source “https://ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js?threshold=97”. melvoridle.com:1:1
Uncaught 
Exception { name: "NS_ERROR_FILE_CORRUPTED", message: "", result: 2152857611, filename: "https://melvoridle.com/assets/js/game/save.js?390", lineNumber: 29, columnNumber: 0, data: null, stack: "getItem@https://melvoridle.com/assets/js/game/save.js?390:29:32\nsetBackupSave@https://melvoridle.com/assets/js/game/save.js?390:450:16\nwindow.onload@https://melvoridle.com/assets/js/game/save.js?390:528:5\n" }
save.js:29
Source map error: Error: request failed with status 404
Resource URL: https://unpkg.com/@popperjs/core@2
Source Map URL: popper.min.js.map

Source map error: Error: request failed with status 404
Resource URL: https://melvoridle.com/assets/js/tippy-bundle.umd.min.js?390
Source Map URL: tippy-bundle.umd.min.js.map

**Are you using any scripts?**
i was using the scripting engine for melvor, but i think it has to do with a broken local save that firefox wants to force
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjmn5Ovz_zqAhVTA2MBHVouC_8QFjAAegQIARAB&url=https%3A%2F%2Faddons.mozilla.org%2Fca%2Ffirefox%2Faddon%2Fscripting-engine-melvor-idle%2F&usg=AOvVaw12UEMGV3JiGNFcY29gLhjN

**Comment by seiyix** [comment]
i reloaded the page and checked console again: 

Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-129674422-1”. melvoridle.com:6:1
Loading failed for the <script> with source “https://ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js?threshold=80”. melvoridle.com:1:1
GEThttps://melvoridle.com/assets/media/shop/assets/media/shop/perpetual_haste.svg
[HTTP/2 404 Not Found 26ms]

Uncaught 
Exception { name: "NS_ERROR_FILE_CORRUPTED", message: "", result: 2152857611, filename: "https://melvoridle.com/assets/js/game/save.js?390", lineNumber: 29, columnNumber: 0, data: null, stack: "getItem@https://melvoridle.com/assets/js/game/save.js?390:29:32\nsetBackupSave@https://melvoridle.com/assets/js/game/save.js?390:450:16\nwindow.onload@https://melvoridle.com/assets/js/game/save.js?390:528:5\nEventHandlerNonNull*@https://melvoridle.com/assets/js/game/save.js?390:523:1\n" }
save.js:29
GEThttps://melvoridle.com/assets/media/favicons/favicon-192x19.svg
[HTTP/2 404 Not Found 0ms]

Source map error: Error: request failed with status 404
Resource URL: https://melvoridle.com/assets/js/tippy-bundle.umd.min.js?390
Source Map URL: tippy-bundle.umd.min.js.map

GEThttps://melvoridle.com/assets/media/favicons/favicon-192x19.svg
[HTTP/2 404 Not Found 0ms]

Source map error: Error: request failed with status 404
Resource URL: https://unpkg.com/@popperjs/core@2
Source Map URL: popper.min.js.map

**Comment by MelvorIdle** [comment]
Has this been rectified lately? Looks like one of the external libraries simply didn't load
