### ISSUE TITLE
[Bug] Saving also not working on Android

### ISSUE THREAD

**Issue by greisa** [MelvorIdle/melvoridle.github.io#3321]
### Describe the bug

Device: Pixel 6 Pro

Saw another report for IOS, but infinite saving loop is also happening on Android. Game isn't saving locally or to the cloud, haven't been able to switch off of wood cutting since yesterday.

### Reproduction Steps

1. Open the game.
2. Notice the infinite saving loop after selecting your character.
3. Try to force save, does not work.
4. Logging in later will not show anything done during last login.

### Expected behaviour

Saving to cloud and local should occur without infinite loop.

### Screenshots

![Screenshot_20230412-102722](https://user-images.githubusercontent.com/43643804/231490766-fecf1739-2111-44f9-aee2-db1b9cc49c78.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5835

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Related #3309

**Comment by MelvorIdle** [comment]
A Hotfix has now been applied to the game to rectify this issue. Thank you for your patience.
