### ISSUE TITLE
Township Trader selection button stays green on last purchase amount even if you change it.

### ISSUE THREAD

**Issue by jaguarrl** [MelvorIdle/melvoridle.github.io#3322]
### Describe the bug

When selecting something from the trader, the green selection box doesn't change when I click a different % selection.

I have a few mods, but even when they're disabled and the game is reloaded this happens. (ETA, Dev Console)

### Reproduction Steps

Go to Township
Go to Trader
Select anything to trade
observe which percentage trade amount is green
click any other percentage trade amount and green indicator doesn't change but the % traded in the numbers does

### Expected behaviour

I expect that the green selector indicator moves with what I have selected for trade.

### Screenshots

![Melvor trader previous](https://user-images.githubusercontent.com/130579311/231494392-e8661eeb-b5d2-48a9-b46a-52764e084cf5.png)
![Melover trader 5%](https://user-images.githubusercontent.com/130579311/231494412-c5daed48-9e37-4b87-bf12-8d6b1ea00c4b.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

Hotfix v1.1.2 (?5835)

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This has now been fixed as of v1.1.2 ?5852
