### ISSUE TITLE
[Bug]: <force save button doesn’t work>

### ISSUE THREAD

**Issue by Pyrozocker** [MelvorIdle/melvoridle.github.io#3323]
### Describe the bug

The force save button is just loading endless and I can’t save to cloud.

### Screenshots

![2B6B9A38-BA38-4C66-BC55-F6A5286D6DD2](https://user-images.githubusercontent.com/130581058/231499673-ebbee085-2ee5-4e5d-b13b-201640a1cf60.jpeg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5835

### Are you using any mods?

No

**Comment by Desi67** [comment]
I’m having same issue also iOS

**Comment by Wice65** [comment]
same here but on firefox on pc

**Comment by Iatsoral** [comment]
Very same issue. Android tho. Already did the normal stuff to fix it and nothing

**Comment by MelvorIdle** [comment]
Related #3309

**Comment by MelvorIdle** [comment]
A Hotfix has now been applied to the game to rectify this issue. Thank you for your patience.
