### ISSUE TITLE
[bug]: <Township task skipping button>

### ISSUE THREAD

**Issue by NaomiCatttt** [MelvorIdle/melvoridle.github.io#3325]
### Describe the bug

It is way too easy to accidentally press the 'skip task for 10,000,000 button' first of all its light grey, I didnt even realise it would be pressable considering it was light gray, it just looked like I didnt have 10m to use the button.
Second of all it immediately skipped the task and didnt give me a warning I was about to skip the task for 10m... And theres also no option to reverse the action.

### Reproduction Steps

1. Open township
2. Press the Tasks button
3. Press the casual task button
4. Accidentally press the light grey skip task for 10,000,000 button
5. Lose 10,000,000 and lose the task

### Expected behaviour

Giving a warning pop up which asks for confirmation to skip the task 

Or a button to reverse the decision 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5835

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
We have adjusted the position of this button as of v1.1.2 ?5852
