### ISSUE TITLE
[Bug]: Notifications V2 is hidden behind the combat bar in vertical

### ISSUE THREAD

**Issue by iamxerc** [MelvorIdle/melvoridle.github.io#3326]
### Describe the bug

On mobile vertical mode the new notifications are hidden behind the active combat stuff.

### Reproduction Steps

1. Start combat with anything
2. Get a notification

### Expected behaviour

Notification to be visible, somehow. Looks like they are too big by default to not clutter the screen up completely, especially with high delay before they disappear.

### Screenshots

![Screenshot_20230412-211623](https://user-images.githubusercontent.com/9702654/231567922-0c654eb1-a889-4995-96a9-f12ec183d5c8.png)
![Screenshot_20230412-211625](https://user-images.githubusercontent.com/9702654/231567928-85f84388-7a41-4819-a391-f5f36536686b.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5835

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This has now been fixed as of v1.1.2 ?5852
