### ISSUE TITLE
[Bug]: Reworked Township has repair costs with no apparent building in need of repair

### ISSUE THREAD

**Issue by gonX** [MelvorIdle/melvoridle.github.io#3327]
### Describe the bug

Occasionally when the town does its hourly tick, I will have an unexplainable repair costs that has no associated building to it. It seems to be going up by about 1.5-2M GP every 2nd to 5th tick (spending legacy ticks also makes it happen)

### Reproduction Steps

1. Go to the Town in Township
2. Manually repair every building (do NOT click any of the Repair All buttons)
3. Observe that there are still remaining repair costs for the Grasslands biome, but Grasslands has no damaged buildings to repair

### Expected behaviour

1. Go to the Town in Township
2. Manually repair every building (do NOT click any of the Repair All buttons)
3. There should be no further repair costs

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/rePIc63Z

### Screenshots

![image](https://user-images.githubusercontent.com/421345/231593113-a4221b07-db6b-4965-9271-47aa197110ef.png)

### Console output

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v2b4487d741ca48dcbadcaf954e159fc61680799950996. (Reason: CORS request did not succeed). Status code: (null).

None of the “sha512” hashes in the integrity attribute match the content of the subresource. [index_game.php](https://melvoridle.com/index_game.php)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v2b4487d741ca48dcbadcaf954e159fc61680799950996. (Reason: CORS request did not succeed). Status code: (null).

None of the “sha512” hashes in the integrity attribute match the content of the subresource. [index_game.php](https://melvoridle.com/index_game.php)
Silent Sign in with JWT [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Validating Melvor Cloud token [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Storing Melvor Cloud Token [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Initializing PlayFab login. Method: customID [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Logging in with Custom ID via PlayFab [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Login with custom ID success [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Getting account info [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Account info retrieved [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Authenticated w/ Melvor Cloud: true [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Authenticated w/ PlayFab: true [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Checking for valid full version [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Checking for valid TotH purchase [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Loading Game Data... [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Registered Demo Data. [save.js:111:190](https://melvoridle.com/assets/js/built/save.js?5835)
Registered Full Version Data. [save.js:111:356](https://melvoridle.com/assets/js/built/save.js?5835)
Registered Throne of the Herald Data. [save.js:111:523](https://melvoridle.com/assets/js/built/save.js?5835)
Initializing Mod Manager... [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
PlayFab Data Stored successfully. [cloud.js:31:75](https://melvoridle.com/assets/js/built/cloud.js?5835)
Checking for Mod Updates... [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Loading Mods... [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Loading Mods (1/14): ETA (v1.0.2) [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Loading Mods (2/14): Item Uses (v1.0.2) [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Loading Mods (3/14): QuickShards (v1.0.0) [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Loading Mods (4/14): Better Summoning Menu (v1.0.3) [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Loading Mods (5/14): Shining Star (v0.1.14) [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Loading Mods (6/14): Combat Indicators (v1.1.1.5) [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Loading Mods (7/14): Show Locked Astrology Modifiers (v0.0.3) [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Loading Mods (8/14): Reveal Thieving Loot (v1.0.0) [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Loading Mods (9/14): Quick Item/Bank Wiki (v1.2.1.0032) [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Loading Mods (10/14): Show Skill Modifiers (v4.1.16) [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Loading Mods (11/14): Shop Item Owned Indicator (v1.2.0) [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Loading Mods (12/14): Do I have room? (v1.0.18) [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
[Do I have room?] Possible mod conflict - BankSelectedItemMenu.setItem has already been patched by the following mods: "Item Uses" [mod.js:822:9](https://melvoridle.com/assets/js/built/mod.js?5835)
Loading Mods (13/14): Completion Log Icons (v1.0.2) [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Loading Mods (14/14): Handy Dandy Notebook (v1.1.1) [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Loading Local Saves... [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Loading Cloud Saves... [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Getting saves from playfab [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Saves retrieved [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Loading character selection [characterSelect.js:5:297](https://melvoridle.com/assets/js/built/characterSelect.js?5835)
Connected to PlayFab successfully [cloudManager.js:336:119](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Game Loaded [main.js:15:315](https://melvoridle.com/assets/js/built/main.js?5835)
Connected to PlayFab successfully [cloudManager.js:336:119](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
updatePlayerTags [cloud.js:99:16](https://melvoridle.com/assets/js/built/cloud.js?5835)
Monster 223 [f0b803f1-1625-4e8d-a297-18140ddc443e:28:21](blob:https://melvoridle.com/f0b803f1-1625-4e8d-a297-18140ddc443e)
Pet 73 [f0b803f1-1625-4e8d-a297-18140ddc443e:33:21](blob:https://melvoridle.com/f0b803f1-1625-4e8d-a297-18140ddc443e)
ETA : Loading... [1a08445b-8601-46ed-8bf4-475c3b8f5df1:587:17](blob:https://melvoridle.com/1a08445b-8601-46ed-8bf4-475c3b8f5df1)
ETA : added settings menu! [1a08445b-8601-46ed-8bf4-475c3b8f5df1:587:17](blob:https://melvoridle.com/1a08445b-8601-46ed-8bf4-475c3b8f5df1)
ETA : Loaded! [1a08445b-8601-46ed-8bf4-475c3b8f5df1:587:17](blob:https://melvoridle.com/1a08445b-8601-46ed-8bf4-475c3b8f5df1)
[Shining Star] Possible mod conflict - Astrology.render has already been patched by the following mods: "Show Locked Astrology Modifiers" [mod.js:822:9](https://melvoridle.com/assets/js/built/mod.js?5835)
[Quick Item/Bank Wiki] Possible mod conflict - BankSelectedItemMenu.setItem has already been patched by the following mods: "Item Uses", "Do I have room?" [mod.js:822:9](https://melvoridle.com/assets/js/built/mod.js?5835)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v2b4487d741ca48dcbadcaf954e159fc61680799950996. (Reason: CORS request did not succeed). Status code: (null).

None of the “sha512” hashes in the integrity attribute match the content of the subresource. [index.html](https://melvoridle.com/roadmap/index.html)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v2b4487d741ca48dcbadcaf954e159fc61680799950996. (Reason: CORS request did not succeed). Status code: (null).

None of the “sha512” hashes in the integrity attribute match the content of the subresource. [index.html](https://melvoridle.com/roadmap/index.html)
PlayFab save updated successfully [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Uncaught TypeError: skill.actions is undefined
    recompute blob:https://melvoridle.com/1a08445b-8601-46ed-8bf4-475c3b8f5df1:3009
[1a08445b-8601-46ed-8bf4-475c3b8f5df1:3009:13](blob:https://melvoridle.com/1a08445b-8601-46ed-8bf4-475c3b8f5df1)
PlayFab save updated successfully 2 [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Uncaught TypeError: skill.actions is undefined
    recompute blob:https://melvoridle.com/1a08445b-8601-46ed-8bf4-475c3b8f5df1:3009
[1a08445b-8601-46ed-8bf4-475c3b8f5df1:3009:13](blob:https://melvoridle.com/1a08445b-8601-46ed-8bf4-475c3b8f5df1)
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features! [index_game.php](https://melvoridle.com/index_game.php)
PlayFab save updated successfully [cloudManager.js:210:22](https://melvoridle.com/assets/js/built/cloudManager.js?5835)
Uncaught TypeError: skill.actions is undefined
    recompute blob:https://melvoridle.com/1a08445b-8601-46ed-8bf4-475c3b8f5df1:3009
4 [1a08445b-8601-46ed-8bf4-475c3b8f5df1:3009:13](blob:https://melvoridle.com/1a08445b-8601-46ed-8bf4-475c3b8f5df1)
Uncaught Error: Tried to equip item when none is owned.
    equipItem https://melvoridle.com/assets/js/built/player.js?5835:210
    methodName https://melvoridle.com/assets/js/built/mod.js?5835:837
    onclick https://melvoridle.com/assets/js/built/equipment.js?5835:125
[player.js:210:7](https://melvoridle.com/assets/js/built/player.js?5835)
Uncaught TypeError: skill.actions is undefined
    recompute blob:https://melvoridle.com/1a08445b-8601-46ed-8bf4-475c3b8f5df1:3009
4 [1a08445b-8601-46ed-8bf4-475c3b8f5df1:3009:13](blob:https://melvoridle.com/1a08445b-8601-46ed-8bf4-475c3b8f5df1)
    recompute blob:https://melvoridle.com/1a08445b-8601-46ed-8bf4-475c3b8f5df1:3009

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5835

### Are you using any mods?

Yes

**Comment by catharsis71** [comment]
same here 

![image](https://user-images.githubusercontent.com/70603733/231621265-b2f7eb5e-a08f-48cf-b084-3ad2a6031be8.png)

**Comment by MelvorIdle** [comment]
Related #3309

**Comment by MelvorIdle** [comment]
A Hotfix has now been applied to the game to rectify this issue. Thank you for your patience.

**Comment by MelvorIdle** [comment]
Incorrectly closed this issue - re-opening.

**Comment by MelvorIdle** [comment]
Hotfix has now been applied for this issue. v1.1.2 ?5853
