### ISSUE TITLE
[Bug]: Monster drops no longer showing properly

### ISSUE THREAD

**Issue by Cushel** [MelvorIdle/melvoridle.github.io#3328]
### Describe the bug

After most recent update. Game on android no longer shows thr monster drops. Please see attached image for how it appears.

### Reproduction Steps

On Android Samsung S20+
During combat
Click "View monster drops"

### Expected behaviour

Should show possible monster drops

### Screenshots

![Screenshot_20230412-231627_Melvor Idle](https://user-images.githubusercontent.com/130612061/231598315-297925a9-ca42-4da7-8278-3b41db77ebf4.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5835

### Are you using any mods?

Yes

**Comment by ekuland** [comment]
Mod Issue. That one specifically is SEMI Drop Chances.

**Comment by MelvorIdle** [comment]
This is due to a mod as mentioned above
