### ISSUE TITLE
[Bug]: <title>Unable to save game

### ISSUE THREAD

**Issue by Peereezy** [MelvorIdle/melvoridle.github.io#3329]
### Describe the bug

After this most recent update I can no longer save my game. I am on mobile only, Android, and I have cleared my cache but I cannot progress any further as nothing I do will be saved. 

### Reproduction Steps

1. Open app
2. Choose save file
3. Game opens normally but save button only shows blue swirling icon

### Expected behaviour

Game keeps my offline progress but nothing I do in my account will carry over the next time that I reopen the app

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/x11pThc5

### Screenshots

![Screenshot_20230412_174058_Melvor Idle](https://user-images.githubusercontent.com/130618378/231616192-4846b295-d005-473f-b542-79f6114c813f.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

? 5835

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Related #3309

**Comment by MelvorIdle** [comment]
A Hotfix has now been applied to the game to rectify this issue. Thank you for your patience.
