### ISSUE TITLE
Malcs (volcanic boss) attack description mismatches game-mechanics

### ISSUE THREAD

**Issue by ViruzzzDK** [MelvorIdle/melvoridle.github.io#333]
**Describe the bug**
'Malcs, the Guardian of Melvor', The final boss in the Volcanic cave says the razor claw attack is unavoidable, but it misses as if it was an avoidable attack.

**To Reproduce**
1. Go to Volcano cave
2. Read "unavoidable" in description of razor claw attack
3. Get clawed in the face by Malcs
4. Find that face wasn't clawed after all (or maybe only once)
5. Much confus

**Expected behavior**
Either the description is meant to say "avoidable" or the attack should not be able to miss.

**Screenshot**
https://i.imgur.com/rv11zUL.png
You can see the *miss* under my HP bar when he's using the attack

**Browser**
Google Chrome Version 83.0.4103.106 (Official Build) (64-bit)
Melvor Idle V0.16.1

**Are you using any scripts?**
Yes, using SEMI, but I tested it again without, same result.

**Comment by MelvorIdle** [comment]
Adjusted the wording of the description in the coming update
