### ISSUE TITLE
[Bug]: <could not see the items when trying to open any boxes or finding monster drops, in Chinese version>

### ISSUE THREAD

**Issue by Samaxide** [MelvorIdle/melvoridle.github.io#3331]
### Describe the bug

1. When trying to open a box/scroll, it shows “UNDEFINED TRANSLATION: :BANK_STRING”.
2. When trying to find what items a monster drops in combat, it shows “UNDEFINED TRANSLATION: :MISC_STRING”.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5855

### Are you using any mods?

Yes

**Comment by 04Slash** [comment]
This is an issue with 'SEMI Drop Chances'. Either disable it or wait for an update.
