### ISSUE TITLE
[Bug]: Bar Box II item description

### ISSUE THREAD

**Issue by TheNeville** [MelvorIdle/melvoridle.github.io#3334]
### Describe the bug

In bank, the description for 'Bar Box II' is 'Contains regular ores' instead of 'Contains regular bars'.

### Reproduction Steps

1. Look at item in bank?

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5855

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This is now hotfixed as of v1.1.2 (?5858)
