### ISSUE TITLE
[Bug]: An Error Occured while processing ticks

### ISSUE THREAD

**Issue by Erthide** [MelvorIdle/melvoridle.github.io#3336]
### Describe the bug

I always have the same error occuring sometimes. It says An Error Occured while processing ticks. I'm playing on PC and it says Android Users Please delete the cache of your app and try again if you are loading into a new update. Here are the logs:
[bug report melvor.txt](https://github.com/MelvorIdle/melvoridle.github.io/files/11223740/bug.report.melvor.txt)

### Reproduction Steps

Theres no reproduction step I can do anything it will happen after a certain amount of time. 

### Expected behaviour

Game crash and you need to close it and open it again to make it work.

### Screenshots

![image](https://user-images.githubusercontent.com/103005421/231808433-4ffda9fd-b05e-4042-a8d4-d5812c56809c.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5855

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
This is a known issue that is caused by the Better Auto Eat mod. Uninstalling it will prevent further crashes.
