### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by kingreeree13** [MelvorIdle/melvoridle.github.io#3339]
### Describe the bug

Cooking Manta Ray and it counts up under active cooking counter, but the cooked Manta Rays do not go to my bank. 

### Reproduction Steps

on cooking screen, select to cook manta rays
actviely cook manta rays
it will show you (amount) is in bank
check bank, no manta rays 

### Expected behaviour

Cooked Manta rays to go into bank for township task.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5855

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Do you have the "Automatically Equip food when it is made" option ticked at the top of the cooking screen?

**Comment by kingreeree13** [comment]
Negative, I also removed the option for perfect cook to ensure I had manta ray vs perfect

**Comment by kingreeree13** [comment]
not that it would have anything to do with it...

**Comment by MelvorIdle** [comment]
Can you please provide your save? I'll take a look and see if I can source the issue.

**Comment by kingreeree13** [comment]
https://melvoridle.com/save/xkTkWl6O

**Comment by MelvorIdle** [comment]
So this save has "Enable Perfect Cooks" enabled, and I can see the Perfect Manta Rays successfully going into your Bank and the count is indeed going up each cook.

Your perfect manta rays are stored in the Bank Tab that has the Basic Bag icon.

**Comment by kingreeree13** [comment]
Did the regular manta rays work? that is the one I was having difficulty with.

**Comment by MelvorIdle** [comment]
Yep, they work when disabling "Enable perfect cooks". Normal Manta Rays are going up in the bank as they cook.

**Comment by kingreeree13** [comment]
Word, thank you for your help and time. Ngl I feel this was user error....
