### ISSUE TITLE
[Bug]: <title>Slayer harvest scroll bugged

### ISSUE THREAD

**Issue by natuslucis** [MelvorIdle/melvoridle.github.io#3340]
### Describe the bug

When equipping the slayer harvest scroll, each healing life steal provides no extra slayer coins. The notification at the bottom of the screen is blank and a red zero pops up. The box is outlined in red and there is a slayer coin symbol but no number in the box. I double checked the shop while fighting and confirmed that no additional coins were being gained until the slayer task monster was killed. I double checked to see if it was due to passive lifesteal but even equipping an item such as the elder crown + darksteel dagger still gave no coins. The only thing I can think of is the multipliers are combining and rounding down to be less than 1, but the crown plus darksteel with a minimum attack of 170 in higher content should have given 1 coin every now and then but I went through the entire earth dungeon without seeing a single one gained.

### Reproduction Steps

1. Equip the scroll to consumables
2. When attacking any (or slayer) target the bug happens

### Screenshots

![image](https://user-images.githubusercontent.com/130721246/231925540-6abe3889-e63f-47ab-8c18-97badefbdc5f.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5855

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This issue is now resolved as of Minor Update - v1.1.2 (?5875)
