### ISSUE TITLE
[Bug]: Repair cost mismatch and useless buildings maintenance

### ISSUE THREAD

**Issue by DanielInTheHell** [MelvorIdle/melvoridle.github.io#3341]
### Describe the bug

1. In Grasslands biome, the cost of 'Repair All in this biome' does not match the cost of repair the buildings individually.
    > 1. The cost of 'Repair All in this biome' is 20 million.
    > 2. The cost for each building in Grasslands biome are: 1062(Cemetecy), 54375(Trading Post), 130(Prats Hats), 3150(Chapel), 277(Malcs Cats), 2 million(Statue of Bane), unknown(Town Hall)
    > 3. So, it means maybe the repair for Town Hall costs around 18 million? Isn't it too high?
2. There is no button to click for repairing the 'Town Hall' individually, and also there is no place to check how much it is.
3. The buildings: Prats Hats and Malcs Cats are useless after I bought all needed items in the shop, why I need to pay for the repairing?
4. Since I don't select any worship for my Township, why I need to build the 'Chapel' and 'Statue of Bane' buildings, and why I need to repair those useless buildings?
    > BTW, the 2 buildings are built automatically by the upgrade of new township version, not by myself.

### Reproduction Steps

1. Go to the Town in Township
2. Wait for few hours until there are something to be repaired
3. Focus on Grasslands biome, the cost of 'Repair All in this biome' does not match the cost of repair the buildings individually.

### Expected behaviour

1. The cost of 'Repair All in this biome' matches the sum of the repair cost for each building.
2. These is a button to repair the 'Town Hall' individually.
3. Don't need to repair Prats Hats and Malcs Cats, and also the new rock building.
4. For those township who does not have worship, 'Chapel' and 'Statue of Bane' are not built automatically, and could destroy them and get refound.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/GiCaKcll

### Screenshots

![1681447636718-02](https://user-images.githubusercontent.com/130730809/231950319-2727eb71-ab62-4b48-ad96-fe422870c32f.jpg)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5858

### Are you using any mods?

No

**Comment by DanielInTheHell** [comment]
The upload for the Screenshots was not successful.

**Comment by 04Slash** [comment]
1. The Town Hall is accounting for the extra 18mil. As of (?5852) townhalls no longer degrade but any damage will still need to be repaired. Building a new Town Hall will repair it automatically for free.

**Comment by DanielInTheHell** [comment]
> 1. The Town Hall is accounting for the extra 18mil. As of (?5852) townhalls no longer degrade but any damage will still need to be repaired. Building a new Town Hall will repair it automatically for free.

Thanks, that do help to resolve the 1st and 2nd question.
How about the 3rd and 4th?

**Comment by MelvorIdle** [comment]
The 3rd and 4th points are suggestions, not bugs. I'll close this one as the first 2 reported bugs have been resolved.

If you really don't want the Chapel/Statue buildings - change your Worship so they get destroyed. Then do not rebuild them.

**Comment by DanielInTheHell** [comment]
The reason why I don't want the Chapel/Statue buildings is because I don't want to pay for the repair.
But now you suggest me to pay 50 million to change the Worship to destroy the buildings.
So I always need to pay for the issue that was occurred by the version change of Township?

That is really a bug, because you guys didn't consider those Township who don't have Worship during the version upgrading.
