### ISSUE TITLE
[Bug]: max skillcape doesn't include township perk

### ISSUE THREAD

**Issue by lilwilsond2** [MelvorIdle/melvoridle.github.io#3342]
### Describe the bug

switching from maximum skillcape to township skillcape shows and increased reduction in township building cost

### Reproduction Steps

1. put on maximum skillcape
2. check building cost (for example my cool rocks building needs 487k stone)
3. put on township skillcape
4. check cost again (for example my cool rocks building now needs 383k stone)
5. equip nothing in cape slot
6. check building cost (for example my cool rocks building now needs 487k stone again)

### Expected behaviour

1. put on maximum skillcape
2. check building cost (for example my cool rocks building needs 383k stone)
3. put on township skillcape
4. check cost again (for example my cool rocks building now needs 383k stone)
5. equip nothing in cape slot
6. check building cost (for example my cool rocks building now needs 487k stone again)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5855

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This issue is now resolved as of Minor Update - v1.1.2 (?5875)
