### ISSUE TITLE
[Bug]: Tutorial message still appearing on township

### ISSUE THREAD

**Issue by BelberithBlack** [MelvorIdle/melvoridle.github.io#3343]
### Describe the bug

When using a new save, the first time you enter township, you'll still get the notification saying to check the tasks menu for a tutorial, even though there's no longer one.

### Reproduction Steps

1. Create new save
2. Skip tutorial
3. Go to township skill
4. Choose a god
5. Check township skill

### Expected behaviour

This message should no longer exist as it will only confuse new players.

### Screenshots

![Screenshot_2023-04-14-04-00-24-858_com malcs melvoridle](https://user-images.githubusercontent.com/130742415/231983524-ff0d83c9-8e7e-44d2-a7b9-831f09dc298a.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5866

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This issue is now resolved as of Minor Update - v1.1.2 (?5875)
