### ISSUE TITLE
[Bug]: Trading Post -cost not being applied?

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#3344]
### Describe the bug

The trading costs are the same whether you have 1 trading post or all of them.

### Reproduction Steps

1. Build 1 trading post
2. View costs
3. Build all trading posts
4. Compare costs
5. See no difference

### Expected behaviour

Building additional trading posts should reduce the overall cost of the items the trader offers, due to it's "-% Township Trader Cost" bonus.

I'm unsure if the full reduction is being applied after 1 is built or if the effect is not present.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/ubDv1hJ6 (Save with all trading posts)
https://melvoridle.com/save/BV2MbKTu (Save with 3 trading posts)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5866

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This issue is now resolved as of Minor Update - v1.1.2 (?5875)
