### ISSUE TITLE
[Bug]: Wrong effect for summon synergy

### ISSUE THREAD

**Issue by Lavender-Li** [MelvorIdle/melvoridle.github.io#3345]
### Describe the bug

For the summon synergy of Pig + Fox, it is expected to "-30% Item creation cost for equipped Summoning Tablets", but now it actually increases the creation cost.
I tried to create some tablets in this situation, and found out that it's really consuming more resources rather than just a display error.

### Reproduction Steps

1. Equip Pig + Fox tablet
2. Create Pig tablet

### Expected behaviour

Pig tablet creation cost reduce by 30%, rather than increase.

### Screenshots

![1](https://user-images.githubusercontent.com/47473643/232060413-ebfd0b21-f752-4b19-8128-553bd3cc9621.png)
![2](https://user-images.githubusercontent.com/47473643/232060439-64cc261e-ecb2-4fdc-bb6f-e884d3755464.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5866

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This issue is now resolved as of Minor Update - v1.1.2 (?5875)
