### ISSUE TITLE
[Bug]: Township Not Increasing Population

### ISSUE THREAD

**Issue by Wundermuffin** [MelvorIdle/melvoridle.github.io#3347]
### Describe the bug

After the township upgrade, my population will not increase even though I have plenty of housing, food, and happiness.

### Expected behaviour

I think with plenty of housing built my population should be increasing not decreasing.  I have purchased pretty much everything I can up to the 2500 population limit.

### Screenshots

![image](https://user-images.githubusercontent.com/130805526/232171421-d75d142e-2a93-450c-9bd9-f1ece3748e8b.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5866

### Are you using any mods?

No

**Comment by 04Slash** [comment]
Your health is at 20%. This will greatly reduce population. You can increase it by clicking the buttons below the repair buttons.

As a suggestion to the devs, maybe having a pop-up of some kind the first time your health reaches < 80% to notify the player of health, it's effect, and how to increase it? This has been a relatively common issue from what I've seen.

**Comment by Wundermuffin** [comment]
Even with the health at 100%, I was stuck at about 1200 and it would not increase.  Now I have so many buildings that I can't collect enough stuff to repair everything because I can't build more storage to repair everything and I can't increase my population to get more storage.

**Comment by MelvorIdle** [comment]
The issue here seems to be with the lack of Health which multiplies your population by health percent (20%). Your Health at 100% will exceed 4,000 once that is sorted.

Another issue would be building efficiency and related season modifiers that reduce population. I suggest prioritising certain buildings to repair over time to get back to where you need to be.

We will continue to balance numbers in Township over the next few days.

**Comment by Wundermuffin** [comment]
"The issue here seems to be with the lack of Health which multiplies your population by health percent (20%). Your Health at 100% will exceed 4,000 once that is sorted." - Yes this was it.  I honestly had missed the icons just below the repair all buttons and did not realized their significance until after you explained.  So thank you very much for your reply, and yes it is maybe not clear enough yet what all the buttons and options in this very complicated skill do and are needed for.
