### ISSUE TITLE
[Bug]: Township raw materials not updating upon new tick

### ISSUE THREAD

**Issue by weeeeebit** [MelvorIdle/melvoridle.github.io#3348]
### Describe the bug

Since the Township update, I noticed that the raw materials are not updating at all. For example, my Food bar would be at 591,786 with +4,158/t, and when the next tick hits, my Food still remains at 591,786. This is true for all the other materials. The materials do deplete, however, when I build new buildings.

By trying to figure out the issue, I inadvertently spent all my legacy ticks. :(

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/WLppdF23

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5866

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
I've loaded your save and the first thing I noticed is that your Storage is full. This might be causing the issue.

I suggest going to "Manage Storage" and yeet excess resources like Planks or similar that may be causing your storage to fill up. Make some room for other resources in case that is the issue.
