### ISSUE TITLE
[Bug]: Fox Discount Synergies Increase Cost Instead of Decrease Cost

### ISSUE THREAD

**Issue by SouptoGo** [MelvorIdle/melvoridle.github.io#3349]
### Describe the bug

The Crow + Fox synergy states that it will reduce the cost of an equipped tablet by 30%, however, it actually increases the cost by 30%. The same bug applies to Pig + Fox and Ent + Fox. I was not able to test the other synergies.

### Reproduction Steps

1. Note down default crow summoning table item creation cost without synergy. 
2. equip crow + fox synergy
3. Compare new crow summoning tablet item creation cost

### Expected behaviour

I expected my crow item cost to decrease by 30%, but it intead went up by 30%. 

### Screenshots

![7657A8EA-1050-4E18-8406-C2031991AC12](https://user-images.githubusercontent.com/130842637/232225015-7f81cb54-8185-4bfd-94fd-7ff915d3dc7a.jpeg)
![23433F34-B27A-4599-96EE-B32063B7ECC0](https://user-images.githubusercontent.com/130842637/232225016-0c3c919f-da99-4069-a14b-9988f4b2404d.jpeg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5867

### Are you using any mods?

No

**Comment by iliveor** [comment]
Notice same bug with Fox + Cyclops tablet.

**Comment by MelvorIdle** [comment]
This issue is now resolved as of Minor Update - v1.1.2 (?5875)
