### ISSUE TITLE
Attack bar stuttering

### ISSUE THREAD

**Issue by levgre** [MelvorIdle/melvoridle.github.io#335]
**Describe the bug**
When the attack bars are filling up, both the player and enemies frequently stutter for a fraction of a second. (EDIT: This is happening with non-combat bars too)

**Browser**
Chrome 84.0.4147.105

**Console output**
ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js?threshold=44:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/assets/media/shop/assets/media/shop/perpetual_haste.svg:1 Failed to load resource: the server responded with a status of 404 ()
save.js?390:469 Local backup successfully stored
save.js?390:64 Loading Save Game...
save.js?390:224 Save Game Loaded...
smithing2.js?390:220 Loading Smithing...
mastery.js?390:187 Updating Masteries
mastery.js?390:23 Loading Masteries...
main.js?393:277 Game Loaded
cloud.js?390:250 1
main.js:5780 Melvor Combat Sim v0.10.1 Loaded
9cloud.js?390:204 Cloud synced
main.js:4105 Elapsed Simulation Time: 2784.3299999986775ms
main.js:4105 Elapsed Simulation Time: 2505.2650000001304ms
main.js:4105 Elapsed Simulation Time: 2362.9150000014342ms
main.js:4105 Elapsed Simulation Time: 2210.8399999993853ms
21cloud.js?390:204 Cloud synced
main.js:4105 Elapsed Simulation Time: 4081.2749999966472ms
main.js:4105 Elapsed Simulation Time: 3272.2700000014156ms
main.js:4105 Elapsed Simulation Time: 3282.2000000011176ms
main.js:4105 Elapsed Simulation Time: 3504.0800000000745ms
cloud.js?390:204 Cloud synced
main.js:4105 Elapsed Simulation Time: 3078.730000000447ms
15cloud.js?390:204 Cloud synced
main.js:4105 Elapsed Simulation Time: 3867.3550000023097ms
main.js:4105 Elapsed Simulation Time: 3018.054999999702ms
2cloud.js?390:204 Cloud synced
main.js:4105 Elapsed Simulation Time: 3045.1600000020117ms
6cloud.js?390:204 Cloud synced
DevTools failed to load SourceMap: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://unpkg.com/@popperjs/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
Combat Simulator

**Comment by MelvorIdle** [comment]
Do you use a password manager like LastPass? I've seen first hand that an extension like this can cause these exact issues.

**Comment by levgre** [comment]
Nope I don't, although the issue seems to be resolved now.  I didn't remove or add any extensions so pretty mysterious.

**Comment by levgre** [comment]
It started again
