### ISSUE TITLE
[Bug]: <title>Cooked Items dissapear once done cooking

### ISSUE THREAD

**Issue by Patossium** [MelvorIdle/melvoridle.github.io#3351]
### Describe the bug

When trying to cook blue crabs, instead of appearing in my inventory, once done cooking, they simply dissapear.

### Reproduction Steps

1. Go to cooking menu
2. Start cooking blue crab

### Expected behaviour

Cooked crabs appearing in my inventory

### Screenshots

![image](https://user-images.githubusercontent.com/53535616/232250803-94e098c4-c14e-4825-831b-d3cbd5780d15.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5867

### Are you using any mods?

No

**Comment by WoneTooPhree** [comment]
Can you check if this box is on.
![Screenshot_20230416-015157__01](https://user-images.githubusercontent.com/45672110/232258886-2c27090d-eaaa-42c3-b50e-cd48b796a6dc.jpg)

If it is then your food won't go in the bank but directly in your equipped food. Check combat screen.

**Comment by MelvorIdle** [comment]
Please confirm if you did have the above setting enabled
