### ISSUE TITLE
[Bug]: Mastery Pool XP Display Not Matching Received XP for Mining

### ISSUE THREAD

**Issue by jem0101** [MelvorIdle/melvoridle.github.io#3352]
### Describe the bug

When I view an Ore for mining it has a "Mastery XP" and a "Mastery Pool XP". When I mine an ore my "Mastery Pool XP" increases by "Mastery XP / 4" which is correct according to wiki, but the display is incorrect. 

### Reproduction Steps

1. Check mastery pool exp.
2. Mine an ore.
3. Check the difference.

### Expected behaviour

I expected the Mastery Pool XP to increase by the listed amount on the ore. 

### Screenshots

![image](https://user-images.githubusercontent.com/89748441/232277290-28cc1050-a970-4b0f-97b5-87745d3769e9.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5867

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This issue is now resolved as of Minor Update - v1.1.2 (?5875)
