### ISSUE TITLE
[Bug]: Game Crashing on loading (Android)

### ISSUE THREAD

**Issue by Dutchviper** [MelvorIdle/melvoridle.github.io#3353]
### Describe the bug

When i open the game and try to login on my character the game crashes almost all the time on, or before showing the offline progression screen.

I know you guys said it is related to an update from the Android System Webview app but I doubt that is the case.
my phone uses Android 9 and my WebView version is 79.0.3945.116. (from what i think is a very old version). so i doubt it updated recently. Further i can not uninstall it from my device.

I created a new character and could login on it like it should. Now that i unlocked the township skill on that character it started giving the same behavior and crashes almost all the times i try to login on, or before showing the offline progression screen.

### Reproduction Steps

1. Open game
2. Select character
3. See it crash before or on offline progress screen

### Expected behaviour

To be able to login normaly

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/2NVacg0U

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5867

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Can you please try and update the Android WebView and see if the issue is fixed? You are running a very very old verson, and each update we bring to the game has a chance of introducing features not supported by old versions.

**Comment by Dutchviper** [comment]
Hi,

I can not update the Android webview app. But i did a search on it and i found the app isnt realy used anymore atleast android 7,8 and 9. Google chrome took over its functionalty.

I solved this issue by removing the chrome updates i was able to login normaly again and it solved the lags also.
Funny enough it still worked after reinstalling the updates again.
