### ISSUE TITLE
[Bug]: Township Trader 

### ISSUE THREAD

**Issue by grantlaughman** [MelvorIdle/melvoridle.github.io#3355]
### Describe the bug

When bank is full if you trade resources it will prompt you that your bank is full and still take resources from your town.

### Expected behaviour

I expected the trade to cancel and prompt me my bank is full rather than execute trade and not give me what I wanted.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5867

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This issue is now resolved as of Minor Update - v1.1.2 (?5875)
