### ISSUE TITLE
[Bug]: Earth runes not using

### ISSUE THREAD

**Issue by I-am-future-busylessman** [MelvorIdle/melvoridle.github.io#3356]
### Describe the bug

When I use alternative magic, I see earth rune in recipe popup, but when I choose this recipe for craft, there are no earth runes in it and there are not using from my bank

### Reproduction Steps

1. Go to alternative magic
2. Hover recipe that should contain earth rune which your mouse and check that earth runes are present in popup
3. Choose this recipe and check that there are no earth runes in craft menu
4. Make sure that you have all needed materials for this craft in your bank
5. try to craft it, check that earth runes amount stays unchanged

### Expected behaviour

Expected that earth runes will use from my bank for craft and will be shown in craft menu

### Screenshots

<img width="1343" alt="Снимок экрана 2023-04-16 в 19 15 45" src="https://user-images.githubusercontent.com/43846088/232326124-d079de45-4fe8-47fe-96f3-6b0300b328a3.png">

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5867

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
I can't seem to reproduce this bug. I've reloaded many times and also changed my language to be the same as yours. I can see the Earth runes just fine.

You definitely don't have mods enabled, correct? And does this issue always occur, or was it a once off?

If you can provide your save, I can look into it further. Thank you.

https://i.imgur.com/iVnYygp.png
