### ISSUE TITLE
[Bug]: Worship Modifiers not updating properly after repairs

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#3358]
### Describe the bug

If Worship drops below a threshold, and you repair back above the threshold, the Worship modifiers are not updated until a game restart is done (or maybe until some other update is triggered).

### Reproduction Steps

1. Use given save (Aeris will be assumed to be used) or Load town with 100% worship
3. View Valley value `game.township.modifiers.standardModifiers.get("increasedTownshipValleyProduction")`, see 100
4. Spend legacy ticks until worship has degraded to 20% due to needing repairs
5. View Valley value, see undefined
6. Repair town
7. View Valley value, see undefined, expected 100
8. Reload game and see 100

### Expected behaviour

If Worship drops below a threshold and is repaired above the threshold, the given worship modifiers should be updated.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/oV2cX88S

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5875

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This should now be fixed as of Minor Update - v1.1.2 (?5890)
