### ISSUE TITLE
[Bug]: 2x Positive Worship during (Season) not working

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#3359]
### Describe the bug

The 2x Positive Worship Modifiers during Spring is not working for Aeris. Others were checked by viewing just `game.township.modifiers.standardModifiers`. Issue #3358 has not effected this bug report.

### Reproduction Steps

1. Load given save
2. Check current season is Spring
3. View potion production
4. Build 50 Chapels
5. See increase in Potion Production
6. Compare to the expected value (Math below, if needed)

### Expected behaviour

The 2x Positive Worship during (season) should double the Worship modifiers during the correct season.
___
Math to support this issue:
Base Potion Production: 1950
Education: 207%
Cemetery: 100% Potion Production
Astrology: 10% Resource Generation
Spring: 25% Potion Production
These values are additive so (1+2.07+1+0.10+0.25) = 4.42
This gives a value of 1950\*4.42 = 8,619/t Potion Production ![image](https://user-images.githubusercontent.com/57328541/232410921-9df1ce82-58ec-4f10-9b43-166145285975.png)

Since we are in the Spring, building 50 Chapels should give 50% more production in the Valley. A value of 12,928.5 is expected however a value of 1950\*4.42\*1.25 = 10,773.75 is given (see below screenshot). If we instead assume the biome is additive not multiplicative, a value of 1950\*(4.42+0.50) = 9,594 should be given. 
___
We can also confirm the Valley modifier is 25 by using `game.township.modifiers.standardModifiers.get("increasedTownshipValleyProduction")`

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/SFUf3eak

### Screenshots

![image](https://user-images.githubusercontent.com/57328541/232411438-6df0492f-fe26-4dcf-b4b8-2e2140a8d063.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5875

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This should now be fixed as of Minor Update - v1.1.2 (?5890)
