### ISSUE TITLE
[Bug]: Can't delete cloud saves.

### ISSUE THREAD

**Issue by BarisBozdag** [MelvorIdle/melvoridle.github.io#3360]
### Describe the bug

Can't delete cloud saves. I tried on different platforms but nothing changed.

### Screenshots

![Ekran görüntüsü 2023-04-17 162528](https://user-images.githubusercontent.com/105358655/232506886-cec587f6-c570-40b6-a04b-cfb625556319.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5875

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of Minor Update - v1.1.2 (?5890)
