### ISSUE TITLE
[Bug]: GP per tick update

### ISSUE THREAD

**Issue by onyx694** [MelvorIdle/melvoridle.github.io#3361]
### Describe the bug

When I Repair All and heal my town to 100%, my GP per tick production still shows the rate from when my town was damaged.  However, if I click the Repair All In This Biome the GP production gets reset to max, even though I have nothing to repair because I just clicked the Repair All button.  My town is level 120, all buildings built and maxed out.  I am worshiping Ragnar.  If this is only effecting the displayed GP per tick, that is minor.  If it is effecting the actual GP production, that's a bit more concerning for me.
This has been cross tested with my friend on his account to be present there too.  Same build version and sub version and also mod free.  I am on adventure and he was on normal yet the bug was still present.

### Reproduction Steps

1. Have a 100% maxed out town worshiping Ragnar
2. Have the town be damaged and the health be low enough to effect GP production.
3. Click Repair All and use potions to raise health and repair back to 100%
4. No change to GP production
5. Click Repair All In This Biome
6. GP production rates are refreshed

### Expected behaviour

1. Have a 100% maxed out town worshiping Ragnar.
2. Have the town be damaged and the health be low enough to effect GP production.
3. Click Repair All and use potions to raise health and repair back to 100%
4. GP production rates are refreshed

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5867

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of Minor Update - v1.1.2 (?5890)
