### ISSUE TITLE
[Bug]: Offline time

### ISSUE THREAD

**Issue by Ughusernames98** [MelvorIdle/melvoridle.github.io#3363]
### Describe the bug

It does not allow me to progress offline

### Reproduction Steps

Whenever I try to progress offline it will just say there was an error.   Only occurs on one account and not others 

### Expected behaviour

It should allow me to progress. I haven’t changed anything in weeks

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/W0acwNtc

### Screenshots

![C45D3047-41CD-471D-994F-9B8537A5A4BF](https://user-images.githubusercontent.com/131153299/232740201-39932df3-8db8-466f-abfa-9c1ada5b0c01.png)

### Console output

An error occured while processing ticks offline:
Error Name: Error
Error Message: Tried to start timer: Act with invalid tick amount: -1
Stack Trace:
start@https://ios.melvoridle.com/assets/js/built/combatManager.js?5895:265:16
queueNextAction@https://ios.melvoridle.com/assets/js/built/character.js?5895:304:82
act@https://ios.melvoridle.com/assets/js/built/character.js?5895:287:21
tick@https://ios.melvoridle.com/assets/js/built/combatManager.js?5895:262:95
activeTick@https://ios.melvoridle.com/assets/js/built/character.js?5895:260:34
activeTick@https://ios.melvoridle.com/assets/js/built/player.js?5895:38:30
activeTick@https://ios.melvoridle.com/assets/js/built/combatManager.js?5895:55:71
tick@https://ios.melvoridle.com/assets/js/built/game.js?5895:178:133
runTicks@https://ios.melvoridle.com/assets/js/built/game.js?5895:175:100
@https://ios.melvoridle.com/assets/js/built/game.js?5895:232:140

Active Action: melvorD:Combat
Current Equipment:
Helmet: melvorF:Terran_God_Helmet
Platebody: melvorF:Terran_God_Platebody
Platelegs: melvorF:Terran_God_Platelegs
Boots: melvorF:Terran_God_Boots
Weapon: melvorF:Infernal_Claw
Shield: melvorD:Dragonfire_Shield
Amulet: melvorD:Fury_of_the_Elemental_Zodiac
Ring: melvorD:Aorpheats_Signet_Ring
Gloves: melvorF:Terran_God_Gloves
Cape: melvorF:Infernal_Cape
Passive: melvorF:Chapeau_Noir
Consumable: melvorF:Fishing_Hook

Action Information:
Is In Combat: true
Fight in Progress: true
-- Start of Player Information --
Next Action: Attack
Next Attack: melvorD:Normal
Is Attacking: true
Standard Spell Selected: melvorD:WindStrike
Ancient Spell Selected undefined
Aurora Selected: undefined
Curse Selected: undefined
Active Prayers:melvorF:Battleheart, melvorTotH:Valor, 
Equipped Food:
Item: melvorD:Whale_Perfect, Qty: 260092
-- End Player Information --
-- Start of Enemy Information --
Enemy: melvorF:Aeris
Next Action: Attack
Next Attack: melvorF:Cyclone
Is Attacking: true
Standard Spell Selected: melvorD:WindStrike
Ancient Spell Selected undefined
Aurora Selected: undefined
Curse Selected: undefined
-- End Enemy Information --
Current Area Type: Dungeon
Current Area ID: melvorF:Air_God_Dungeon
Modding Enabled. Loaded mods:
Dev
SEMI Core
Mastery Pool Can Overflow
SEMI Auto Farming
SEMI Auto Loot
SEMI Auto Eat
SEMI Auto Slayer
SEMI Auto Run
SEMI Auto Gear Swap
Quick Item/Bank Wiki
SEMI Auto Master
Pokeworld (Generation 1)
Slayer Coin Multiplier
Combat Only Mode (HCCO / MCCO)
Will I Die?
Better Auto Eat
SEMI Auto Sell
AutoSort
Add Items

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
This is a known issue that is caused by the Better Auto Eat mod. Uninstalling it will prevent further crashes.
