### ISSUE TITLE
[Translation Error]: variables in township popups when not using English as language

### ISSUE THREAD

**Issue by pig-cop** [MelvorIdle/melvoridle.github.io#3366]
### Which text in the game has a translation error?

I tried Italian and French but I suppose it will be a bug present in the other non-English languages too.
In most of the township pop-ups there are variables names here and there and it seems some pop-up information is not up to date:

![melvor_bugs](https://user-images.githubusercontent.com/1793444/233315554-2f4802f8-2177-499c-bbaa-b0d24667f6c4.png)

**Comment by Soulprayer79** [comment]
related #3367

**Comment by coolrox95** [comment]
Issue has since been resolved.

**Comment by pig-cop** [comment]
The merchant's items tooltips are still looking as this:

![melvor_issue](https://github.com/MelvorIdle/melvoridle.github.io/assets/1793444/5a68c051-80b3-4ded-b36d-8aee72b7e7be)

I'm on version 1.1.2 (?6164)
