### ISSUE TITLE
Offline progression screen displays wrong XP given

### ISSUE THREAD

**Issue by SethaWetha** [MelvorIdle/melvoridle.github.io#337]
**Describe the bug**
Offline progression displays the wrong XP given when Firemaking Skillcape, ARoS, or Pyro bonuses are applied.

**To Reproduce**
1. Equip ARoS and/or Firemaking Cape, or have Pyro
2. Start a skill
3. Exit the game
4. Come back and the offline progression screen only shows the base XP

**Expected behavior**
The displayed XP to match the XP actually given

**Screenshots**
https://files.catbox.moe/m1aakm.jpg

**Browser**
Android 8, Galaxy S7. App from playstore

**Console output**
N/A

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
