### ISSUE TITLE
[Bug]: Township Health Parameters in Tooltip box

### ISSUE THREAD

**Issue by Soulprayer79** [MelvorIdle/melvoridle.github.io#3379]
### Describe the bug

When hovering over Health ("Gesundheit" in German) there are variables in the tooltip ${value1} and so on

### Reproduction Steps

Township -> Hovering over Health

### Expected behaviour

i don't know if this variables are still used after the rework? maybe the text needs a new text as well?

### Screenshots

![grafik](https://user-images.githubusercontent.com/82806099/233962331-30e6c095-79b1-4478-97df-68e86d963eb0.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5911

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has since been resolved.
