### ISSUE TITLE
Item In bank 

### ISSUE THREAD

**Issue by Pennic** [MelvorIdle/melvoridle.github.io#338]
**Describe the bug**
If you want to press any Item in the bank the item shows up stucked in the sidebar 

**To Reproduce**
1. Go to the bank
2. Click on any Item 
3. Scroll down to the boten of the page
4. See the Item sucked

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/69303170/89520273-e781a900-d7dd-11ea-8673-4462057dc0bf.PNG)

**Browser**
Google Chrome 

**Console output**
Failed to load resource: the server responded with a status of 404 ()
prebid.min.js:3 fun-hooks: referenced 'registerAdserver' but it was never created
(anonymous) @ prebid.min.js:3
17A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.
core@2:1 Failed to load resource: the server responded with a status of 404 ()
adthrive.min.js?threshold=0:17 AdThrive::init started
data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=:1 Uncaught SyntaxError: Invalid or unexpected token
save.js?390:469 Local backup successfully stored
save.js?390:64 Loading Save Game...
save.js?390:224 Save Game Loaded...
smithing2.js?390:220 Loading Smithing...
mastery.js?390:187 Updating Masteries
mastery.js?390:23 Loading Masteries...
id.rlcdn.com/709414.gif?gdpr_consent=BO3tlSoO3tlSoDxABADEDA-AAAAuhr_7__7-_9_-_f__9uj3Or_v_f__32ccL59v_h_7v-_7fi_20nV4u_1vft9yfk1-5ctDztp507iakiPHmqNeb9n9mz1e5pRP78k89r7337Ew_v8_v-b7BCPN_Y1kyA&gdpr=1:1 Failed to load resource: the server responded with a status of 451 ()
main.js?393:277 Game Loaded
cloud.js?390:250 1
id.rlcdn.com/467756.gif:1 Failed to load resource: the server responded with a status of 451 ()
pippio.com/api/sync?pid=5324&it=1&iv=7da922ce1f6b360be27ccb4c8c6550a8d7aa4b108e0fe3f4d8f8c84d70e6a5a8791426b5417dce21&_=2:1 Failed to load resource: the server responded with a status of 451 ()
21tippy-bundle.umd.min.js?390:1 Uncaught TypeError: Cannot read property 'createPopper' of undefined
    at wt (tippy-bundle.umd.min.js?390:1)
    at tippy-bundle.umd.min.js?390:1
    at Object.show (tippy-bundle.umd.min.js?390:1)
    at At (tippy-bundle.umd.min.js?390:1)
    at HTMLDivElement.gt (tippy-bundle.umd.min.js?390:1)
idsync.rlcdn.com/709421.gif?partner_uid=d0bb871b-6037-48a3-bcc5-13034c654ec5:1 Failed to load resource: the server responded with a status of 451 ()
sync.v5prebid.datablocks.net/s2ssync?gdpr=1&gdpr_consent=BO3tlSoO3tlSoDxABADEDA-AAAAuhr_7__7-_9_-_f__9uj3Or_v_f__32ccL59v_h_7v-_7fi_20nV4u_1vft9yfk1-5ctDztp507iakiPHmqNeb9n9mz1e5pRP78k89r7337Ew_v8_v-b7BCPN_Y1kyA&us_privacy=&r=https%3A%2F%2Fprebid.adnxs.com%2Fpbs%2Fv1%2Fsetuid%3Fbidder%3Ddatablocks%26gdpr%3D1%26gdpr_consent%3DBO3tlSoO3tlSoDxABADEDA-AAAAuhr_7__7-_9_-_f__9uj3Or_v_f__32ccL59v_h_7v-_7fi_20nV4u_1vft9yfk1-5ctDztp507iakiPHmqNeb9n9mz1e5pRP78k89r7337Ew_v8_v-b7BCPN_Y1kyA%26uid%3D%24%7Buid%7D:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
cksync.yahoo.co.jp/dispatch?ptr=10901:1 Failed to load resource: the server responded with a status of 400 ()
main.js?393:2555 Mining paused...
save.js?390:564 ff
main.js?393:2438 1596708335245
main.js?393:2555 Mining paused...
cloud.js?390:204 Cloud synced
save.js?390:564 ff
main.js?393:2438 1596708387237
main.js?393:2555 Mining paused...
save.js?390:564 ff
main.js?393:2438 1596708498343
main.js?393:2555 Mining paused...
save.js?390:564 ff
main.js?393:2438 1596708504052
2tippy-bundle.umd.min.js?390:1 Uncaught TypeError: Cannot read property 'createPopper' of undefined
    at wt (tippy-bundle.umd.min.js?390:1)
    at tippy-bundle.umd.min.js?390:1
    at Object.show (tippy-bundle.umd.min.js?390:1)
    at At (tippy-bundle.umd.min.js?390:1)
    at HTMLDivElement.gt (tippy-bundle.umd.min.js?390:1)
main.js?393:2555 Mining paused...
save.js?390:564 ff
main.js?393:2438 1596708703503
4tippy-bundle.umd.min.js?390:1 Uncaught TypeError: Cannot read property 'createPopper' of undefined
    at wt (tippy-bundle.umd.min.js?390:1)
    at tippy-bundle.umd.min.js?390:1
    at Object.show (tippy-bundle.umd.min.js?390:1)
    at At (tippy-bundle.umd.min.js?390:1)
    at HTMLDivElement.gt (tippy-bundle.umd.min.js?390:1)
DevTools failed to load SourceMap: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
This was an issue due to an external library not loading on the day. The coming update hosts this library locally, so it shouldn't happen again in the future.
