### ISSUE TITLE
[Bug]: Wooden Hut price

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#3381]
### Describe the bug

See screenshots.
The Wooden Hut in Township costs 60 wood and 20 stone in the Grasslands. However, in the ~~Arid Plains and~~ Snowlands they cost 60 stone and 20 stone.

EDIT: In ?6164 the prices of the Arid Plains has been fixed however this issue is still present in the Snowlands.

### Reproduction Steps

1. Open Township
2. View Wooden Hut price in Grasslands (Screenshot 1)
3. View Wooden Hut price in ~~Arid Plains and/or~~ Snowlands (Screenshot 2)

### Expected behaviour

Either the cost should be 60 wood and 20 stone like the Grasslands or the cost of stone should show 80, not 60 + 20.

### Screenshots

![image](https://user-images.githubusercontent.com/57328541/233975506-596a8d1a-84d9-4e23-81f8-037815dd4118.png)

![image](https://user-images.githubusercontent.com/57328541/233974420-251f2e13-47e1-4abc-9107-099f5b75ae92.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5911

### Are you using any mods?

Yes

**Comment by Ithrenion** [comment]
This bug is still around as of subversion ?6130. Wooden Huts in Arid Plains and Snowlands use 60 Stone instead of 60 Wood.
