### ISSUE TITLE
[Bug]: Game reloads when entering custom shop quantity

### ISSUE THREAD

**Issue by Mortichar** [MelvorIdle/melvoridle.github.io#3383]
### Describe the bug

Typing in a custom buy quantity and hitting Enter causes the game to reload. Hitting the enter key is not required, but it's instinctual for I imagine quite a few people, and it shouldn't reload the game.

### Reproduction Steps

Go to Shop
Click "Buy x<#>" in the top right
Click Custom Amount text field
Type value
Hit Enter (return) key

### Expected behaviour

The quantity to just be set and the prompt to close, and it should not cause the game to reload.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5911

### Are you using any mods?

No

**Comment by retep998** [comment]
I can confirm this also happens to me. It seems like the HTML form used to input the quantity doesn't have the submit action cancelled, so pressing enter "submits" the form.
