### ISSUE TITLE
[Bug]: Legacy tick hours convert to less than one hour of season time

### ISSUE THREAD

**Issue by JPeter231** [MelvorIdle/melvoridle.github.io#3385]
### Describe the bug

Using an hour legacy tick will not correctly convert to a full hour advancement of the current season

### Reproduction Steps

1) Go to Township
2) Click on Update 1h

### Expected behaviour

Current season should advance by the same time period of legacy time used

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5911

### Are you using any mods?

No

**Comment by itzmattu** [comment]
I'm actually seeing 1hr legacy tick advance the season timer MORE than 1 hr (during winter). Also, the amount of time that advances does not seems consistent. I used two ticks, and noticed it went down by over 13 hrs, then used a single tick and it went down by 3.5 hrs.
