### ISSUE TITLE
[Bug]: <title> Cooking won’t work

### ISSUE THREAD

**Issue by Pilgrim1410** [MelvorIdle/melvoridle.github.io#3386]
### Describe the bug

On my hard level account only, when I cook a fish, there is nothing added to my bank. When I cook a fish, the notifications shows +2(0).

2 fish are caught, 0 are added to the bank.

### Reproduction Steps

1. Catch fish
2. Cook fish
3. Can’t profit because no fish

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/4UXoUTDI

### Screenshots

![FB6BE71C-C110-4FE7-8B1C-E7BBC448A23B](https://user-images.githubusercontent.com/131798251/234337979-26e3b74e-7b21-4d20-882c-4e197059012f.png)
![BA4D8141-146F-4AF2-B965-E61924BD7AB8](https://user-images.githubusercontent.com/131798251/234338017-27a1bbe8-6cfe-4265-99ae-15746580af60.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5911

### Are you using any mods?

No

**Comment by 04Slash** [comment]
You've purchased the Cooking Upgrade 1 from the shop which automatically equips cooked food if you have empty slots. This is where your sharks, crabs, and sardines are going.

You can disable this behavior by unchecking "Automatically equip food when it is made?" on the cooking page.
