### ISSUE TITLE
[Bug]: Can't spend last 30 minutes of Legacy time in Township

### ISSUE THREAD

**Issue by ingoher** [MelvorIdle/melvoridle.github.io#3388]
### Describe the bug

Since there is no more "Spend All" button after die Hotfix, it is not possible anymore to spend the last half an hour tick.

### Reproduction Steps

1. Go to "Township"
2. Have 30 minutes left of Legacy time
3. Not able to use it

### Expected behaviour

1. Go to "Township"
2. Have 30 minutes left of Legacy time
3. Have a button for 30 minutes or a use "All" button again

### Screenshots

![image](https://user-images.githubusercontent.com/48944099/234555161-5904b473-7065-45ec-8346-518cd0840877.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5911

### Are you using any mods?

No

**Comment by Zarremgregarrok** [comment]
can the "use all legacy time" button (that used to exist) appear when remaining legacy time is under an hour and higher than zero?
