### ISSUE TITLE
[Bug]: <Level and XP dont match & Cant play anymore> 

### ISSUE THREAD

**Issue by zzamai** [MelvorIdle/melvoridle.github.io#3389]
### Describe the bug

I came back after a long time without playing.

When i stopped, i was 99 agility, i even have the cape worn and the pet. But now that i started playing again, its saying im lvl 3 and i have like, 90k xp.. heres a print

![image](https://user-images.githubusercontent.com/47905185/234992001-bab42a4a-eb87-4bad-a4bf-a0e562e50b1f.png)
![image](https://user-images.githubusercontent.com/47905185/234992102-378bca7c-8ff4-41af-a59a-7f5cb5394655.png)

### Reproduction Steps

1+ year without playing

### Expected behaviour

displaying my real level and XP

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/3E58RjF1

### Screenshots

![image](https://user-images.githubusercontent.com/47905185/234992001-bab42a4a-eb87-4bad-a4bf-a0e562e50b1f.png)
![image](https://user-images.githubusercontent.com/47905185/234992102-378bca7c-8ff4-41af-a59a-7f5cb5394655.png)

### Console output

So, i logged out to grab the Save Link, and when i got back in, this happened (also, im playing on computer, not on android):

![image](https://user-images.githubusercontent.com/47905185/234992795-c64867b6-bfcb-426b-a76f-532adaf25032.png)

Now i cant play the game because that message doesnt close...

The message:

An error occurred while rendering:
Error Name: TypeError
Error Message: Cannot read property 'bar' of undefined
Stack Trace:
TypeError: Cannot read property 'bar' of undefined
    at HTMLElement.animateFromTimer (https://steam.melvoridle.com/assets/js/built/agilityMenus.js?5911:58:112)
    at Agility.renderProgressBar (https://steam.melvoridle.com/assets/js/built/agility.js?5911:165:158)
    at Agility.render (https://steam.melvoridle.com/assets/js/built/agility.js?5911:135:144)
    at https://steam.melvoridle.com/assets/js/built/game.js?5911:181:63
    at Map.forEach (<anonymous>)
    at NamespaceRegistry.forEach (https://steam.melvoridle.com/assets/js/built/namespaceRegistry.js?5911:37:44)
    at Game.render (https://steam.melvoridle.com/assets/js/built/game.js?5911:181:39)
    at Game.loop (https://steam.melvoridle.com/assets/js/built/game.js?5911:197:35)

Active Action: melvorD:Agility
Current Equipment:
Helmet: melvorD:Crown_of_Rhaelyx
Weapon: melvorD:Bobs_Rake
Amulet: melvorD:Amulet_of_Fishing
Ring: melvorD:Aorpheats_Signet_Ring
Gloves: melvorD:Smithing_Gloves

Action Information:
Is Active: true

Active Obstacle Tier: 8
Built Obstacles (tier|obstacleID):
0:melvorF:CargoNet
1:melvorF:BalanceBeam
2:melvorF:PitJump
3:melvorF:GapJump
4:melvorF:TreeClimb
5:melvorF:RaftDrifting
6:melvorF:HeatTrap
7:melvorF:TreeHang
8:melvorF:IceJump
9:melvorF:BoulderMove
Modding Disabled

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?2911

### Are you using any mods?

No

**Comment by zzamai** [comment]
Also, i already deleted the %appdata% melvor folder, and the error still happens

**Comment by zzamai** [comment]
I'd like to say that, after my level hit 90 agility again, the error stopped happening

**Comment by coolrox95** [comment]
Crashing seems to be due to the same problem as #3111

Level reset cause YTBD
