### ISSUE TITLE
[Bug]: Can't finish farming tutorial due to bugged menu item "melvorD:Farming"

### ISSUE THREAD

**Issue by hausler89** [MelvorIdle/melvoridle.github.io#3396]
### Describe the bug

When starting a new savegame and working through the tutorial, I always get stuck at the farming tutorial part. The menu item is not accessible.

A menu item called "melvorD:Farming" is highlighted green when the tutorial island reaches the farming part. However, the game doesn't react to my clicking or tapping the item.

My game is set to German if that is important. I could not test if the problem also occurs in other languages as I did not find a way to change the language.

I tried to do the tutorial on three fresh savegames, the problem always occurs at the same time.

<img width="1064" alt="Bildschirmfoto 2023-05-06 um 09 21 36" src="https://user-images.githubusercontent.com/22004432/236609566-1fb85088-cf3e-47d9-aba7-06ed1e2dc88b.png">

### Reproduction Steps

1. Start a new game in German
2. Follow the tutorial island until farming quest 2
3. Try opening the farming menu for planting potato seeds

### Expected behaviour

The farming menu should open.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [X] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5911

### Are you using any mods?

No

**Comment by LeventSMI** [comment]
Farming section is under "Passive" tab. You should tap it (on the "Township") for Farming.

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.2,
