### ISSUE TITLE
[Bug]: Incorrect Item sorting

### ISSUE THREAD

**Issue by KelleyEngineering** [MelvorIdle/melvoridle.github.io#3397]
### Describe the bug

Gear:
(S) iron helmet is sorted incorrectly in between (S) bronze shield and (G) bronze helmet, instead of being sorted alongside other (S) iron items

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5911

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.2,
