### ISSUE TITLE
[Bug]: Hard lock on Impending Darkness Event after closing the game

### ISSUE THREAD

**Issue by AlexCassin** [MelvorIdle/melvoridle.github.io#3398]
### Describe the bug

I did 4 runs of Impending Darkness, cloud saved and closed the game. When i reopened the game on the same device and loaded it, all of the slayer areas are greyed out.
I am wearing the same gear I was wearing when doing the events.

### Reproduction Steps

1. Start event
2. complete 1 run
3. save and quit the game
4. reload game

### Expected behaviour

all 4 slayer rooms to be available to clear as normal with the impending darkness event

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/IFWZDLF1

### Screenshots

![Screenshot_209](https://user-images.githubusercontent.com/24494999/236664183-08f3b061-0e48-44b7-8f25-7fc76c952a0b.png)
![Screenshot_210](https://user-images.githubusercontent.com/24494999/236664184-eeedf543-8ea3-4d56-bf1f-9501856ee766.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5911

### Are you using any mods?

Yes

**Comment by jlsalvador** [comment]
Exactly the same here :-/

Save:
https://gist.github.com/jlsalvador/ab762dde4cab4d975552b0edc347d3bc

**Comment by andarilhoz** [comment]
I have the same issue :/

**Comment by AlexCassin** [comment]
FYI someone gave me a workaround for this - Start the Goblin raid and then leave it. Worked for me!

**Comment by jlsalvador** [comment]
> FYI someone gave me a workaround for this - Start the Goblin raid and then leave it. Worked for me!

I tried, unsuccessfully. :cry:

**Comment by andarilhoz** [comment]
Nice workaround, it worked with me too!

**Comment by AlexCiceu** [comment]
Should be reopened, still encountering this issue and the workaround with the Golbin raid doesn't work for me since I can't start that either, nothing happens when clicking the Start button.
