### ISSUE TITLE
Creating gems out of aything

### ISSUE THREAD

**Issue by Phideault** [MelvorIdle/melvoridle.github.io#340]
Using Rags to Riches, it is possible to create gems out of anything

**To Reproduce**
1. Go to Alt. Magic
2. Select any level of "Item Alchemy" spell. In my case, it was level 2
3. Chose an item to convert into money
4. Change your spell to "Rags to Riches"
5. DO NOT change the item you want to convert
6. Cast the spell

**Expected behavior**
It seems like the item from the previous spell is retained into that slot. I believe it should reset if you were to select an new spell

**Browser**
Using Brave browser, not sure about the version

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
