### ISSUE TITLE
[Bug]: <title>Alternative Magic: Just learning - no images/options appear under select item

### ISSUE THREAD

**Issue by CheapAoki** [MelvorIdle/melvoridle.github.io#3403]
### Describe the bug

In Alternative Magic under Just Learning, after clicking on “click image to choose item” it opens the menu heading saying “Select Item” however there are no options or images to select.

This problem persists on phone and PC versions. 

### Reproduction Steps

1. Go to Alt. magic
2. Select Just Learning
3. Click on “Click Image to Choose Item”
4. “Select Item” menu appears but does not show items to select

### Expected behaviour

After checking other posts I think I should be seeing some icons like gems, fish etc. however nothing loads (the table is empty)

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/Jnb0uGmq

### Screenshots

![881762FE-B0B8-4B48-A66B-668C04701A00](https://github.com/MelvorIdle/melvoridle.github.io/assets/133012556/638af552-e6de-43b4-addf-accf38fbf349)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5911

### Are you using any mods?

No

**Comment by coolrox95** [comment]
All items in the provided save's bank are locked, hence why nothing shows in the menu.
