### ISSUE TITLE
Bug: Drop missing from Rune Knights

### ISSUE THREAD

**Issue by MrCouchies** [MelvorIdle/melvoridle.github.io#3406]
Drop missing from Rune Knights

Rune Knights don't drop rune plate legs I killed heaps of them and got at least 5 of all other drops but no plate legs

### Reproduction Steps

 I killed heaps of them

### Expected behaviour

I expected to get the drop

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5911

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Bad RNG is not a bug.
