### ISSUE TITLE
[Spelling/Grammar]: Misleading text on Desert Hat

### ISSUE THREAD

**Issue by aquelle-cp** [MelvorIdle/melvoridle.github.io#3408]
### What text is wrong?

The Desert Hat says "Passive: Grants access to Arid Plains":
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/38425426/a41bc05d-fc78-4757-bb13-c8c11a4084f3)

But the place itself says it requires the hat to be equipped:
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/38425426/bb53f1d1-23f9-4205-96d7-96008527fd9b)

I don't think I misunderstood, since as far as I know this is the only function of the Desert Hat.

### What is the correct spelling or grammar?

Probably just removing the passive text.

**Comment by ekuland** [comment]
The text on the hat is saying what it does. It's listed as passive since it can go in the passive slot on be active. What seems to be the issue here?

**Comment by aquelle-cp** [comment]
It sounds like I'm missing something. I don't know what passive slot means, if I equip it it goes in my helmet slot. I would assume passive would mean you don't have to equip it at all, that's what I'm used to it meaning in other games

**Comment by aquelle-cp** [comment]
Oh, I guess I get it now... I'm noticing similar text on other items with actual stats. That's pretty misleading on something with no stats like that, and when you're buying it in the shop, it makes it look like a passive unlock instead of an item you have to wear to use. I suppose the word the game actually uses for stuff like that is saying it's an unlock. I'm not going to close this issue because I don't think the wording is clear at all, but if someone wants to close it, it technically isn't a spelling/grammar error.

**Comment by aquelle-cp** [comment]
Closing

**Comment by aquelle-cp** [comment]
Oh, I guess I get it now... I'm noticing similar text on other items with actual stats. That's pretty misleading on something with no stats like that, and when you're buying it in the shop, it makes it look like a passive unlock instead of an item you have to wear to use. I suppose the word the game actually uses for stuff like that is saying it's an unlock. I'll close the issue since it's technically not a mistake or a bug, but that wording isn't great.
