### ISSUE TITLE
[Translation Error]: Mod Manager 简体中文没有翻译

### ISSUE THREAD

**Issue by ghost** [MelvorIdle/melvoridle.github.io#3413]
### Which text in the game has a translation error?

没有进行简体中文的翻译
Simplified Chinese translation is not performed
* This sentence has been translated by a translation software. There may be mistakes. (I mainly use simplified Chinese).
![截屏2023-05-17 00 27 23](https://github.com/MelvorIdle/melvoridle.github.io/assets/72379760/3b500a25-ed7e-45ee-9971-526d01c68ba8)

**Comment by xiaozhiyuqwq** [comment]
我认为可以这样翻译：
I think it can be translated as follows:

是否启用模组管理器？

开启模组管理器会出现无法预料的情况。模组管理器在默认情况下是关闭的。如果您希望启用模组管理器，您需要阅读并同意以下条款：

我能够理解安装的模组适用于整个游戏，而非某一个角色。

我能够理解模组可能会影响或改变游戏的规则，这可能会产生无法预料或者事与愿违的情况。

我能够理解梅尔沃放置（Melvor Idle）的开发者没有义务处理我在使用模组的时候遇到的任何游戏漏洞。包括但不限于帮助我修复被漏洞损坏的存档。

我能够理解模组可能会包含可以被执行的恶意代码。而且模组可以使用模组浏览器产生报告或者被删除。综上，我能够理解安装模组的风险以及可能产生的后果，我希望启用模组管理器。

启用模组管理器
