### ISSUE TITLE
[Bug]: Weapons reset on event

### ISSUE THREAD

**Issue by NevraEdulius** [MelvorIdle/melvoridle.github.io#3419]
### Describe the bug

Was going through the Goblin Event, and at wave 38, my weapon switched from Ancient Longbow to Bronze Scimitar. Finished the wave (Had got armor to keep me going) then choose a bow to get back my ranged bonuses from my armors, only to get back the Bronze Scimitar at the first hit done. At the end of the wave, choosed the Ice 2-H Sword and now I'm keeping it... Is it only for ranged weapons or if I got a magic one would do the same thing? Edit ; At the end of wave 41, choosed the Yew Longbow and reverted to Bronze Scimitar. Note ; Had about 1094 Meteorite arrows

### Reproduction Steps

1. Go to event
2. Do the easy Goblin Raid
3. Choose ranged armor/weapons at end of wave
4. Survive until wave 37
5. Check your weapon

### Expected behaviour

With a ranged weapon, should revert to Bronze Scimitar (First weapon when starting the event)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5911

### Are you using any mods?

No

**Comment by WoneTooPhree** [comment]
Are you sure you still have ammo ?
There is no meteorite arrow but meteorite bolt and you can't use that with bow and you also need lvl 100+ ranged.
Also don't know much from golbin raid maybe you don't need range requirements.
Anyway the game will revert to base weapon if you have no ammunition or no runes (when doing mage)

**Comment by NevraEdulius** [comment]
I was only taking the "replenish" option, but I do believe that the problem may be the fact that when changing ammo, the amount go up without changing, so maybe I had no more meteorite arrows, but had all the arrows I used before, so making it like I still had ammo? Not sure, but maybe checking it would be a good check to fix.

**Comment by NevraEdulius** [comment]
As for the goblin raid, each end of wave gives you a choice of random items (Classed weapons, armor, ranged ammo, runes & food) and the level requirement is removed because the more you progress, the skill level of each of the combat skills applicable (Prayers excluded) goes up. (I.E ; Normal waves at 87 have level 87 for all except health at 96 and I can still use the Frostspark 1H sword (req. atk 110))

**Comment by NevraEdulius** [comment]
Welp, my fault for not checking it sooner, it was bolts...
