### ISSUE TITLE
Mismatch in level requirements for firestrike

### ISSUE THREAD

**Issue by kenbostoen** [MelvorIdle/melvoridle.github.io#342]
**Describe the bug**
In the combat screen, firestrike has a level 10 requirement. in the milestone screen it has requirement of level 8

**To Reproduce**
![image](https://user-images.githubusercontent.com/47040758/89812225-18e0d880-db40-11ea-8a19-18542e7f6bc8.png)
![image](https://user-images.githubusercontent.com/47040758/89812297-301fc600-db40-11ea-8fef-9823b9f55b58.png)

![image](https://user-images.githubusercontent.com/47040758/89812269-25653100-db40-11ea-9c94-cdb13263745e.png)

edit: if possible i would fix it but it doesn't seem to be opensource.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
