### ISSUE TITLE
Do not have tax for town

### ISSUE THREAD

**Issue by FantasyJZ** [MelvorIdle/melvoridle.github.io#3425]
### Describe the bug

My town do not have any tax for any level or I did anything.

### Reproduction Steps

1. Go to town
2. Look tax
3. No tax

### Expected behaviour

The tax can work well.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/XjToHY9g

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5911

### Are you using any mods?

Yes

**Comment by Auron956** [comment]
Tax will only be generated once at least one town hall has been built, this is intentional.
