### ISSUE TITLE
[Bug]: Township - Quick Equip

### ISSUE THREAD

**Issue by Toralf90** [MelvorIdle/melvoridle.github.io#3426]
### Describe the bug

The bug is basicly a layout Issue.

Quickequip tab is not correctly in-line with the cogwheel. It's a very narrow path to reach the Skillcape, otherwise the quickequipwindow/tab disappears.

### Reproduction Steps

1. Owning a Pet for Township (maybe not needed)
2. Owning Township Skillcape (maybe not needed)
3. Hovering over the Quickequip-Cogwheel (Quickequip Tab shows up)
4. Tab is not in-line with the cogwheel (to high)

### Expected behaviour

If I hover over the quickequip-cogwheel I expect, that the tab/window for quickequip is in-line with the cogwheel.

### Screenshots

![834578237487234](https://github.com/MelvorIdle/melvoridle.github.io/assets/134782160/e3805fe5-10b7-4ca2-b1b3-34f78b9a5aa0)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5911

### Are you using any mods?

No

**Comment by jlweston** [comment]
This is even more pronounced now with the layout tweaks that came with v1.2. There's now a multiple pixel wide gap between the menus, which can take many attempts to traverse using mouse depending on whether the mouse position registers in the middle.

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/7827157/f54d7419-6b89-44b9-bd5d-01813f691d3f)
