### ISSUE TITLE
[Bug]: Steam version stuck on Fetching Account Info

### ISSUE THREAD

**Issue by hhyyrylainen** [MelvorIdle/melvoridle.github.io#3439]
### Describe the bug

For the last three days I've been unable to play the game. It gets stuck for multiple minutes on the "Fetching Account Info" screen. And then closes:
```
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe.
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe.
src/common/pipes.cpp (883) : Fatal assert; application exiting
src/common/pipes.cpp (883) : Fatal assert; application exiting
Installing breakpad exception handler for appid(melvor idle)/version(1.0)/tid(2646301)
assert_20230603112302_3.dmp[2647832]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230603112302_3.dmp
_ExitOnFatalAssert
assert_20230603112302_3.dmp[2647832]: Finished uploading minidump (out-of-process): success = yes
assert_20230603112302_3.dmp[2647832]: response: Discarded=1
assert_20230603112302_3.dmp[2647832]: file ''/tmp/dumps/assert_20230603112302_3.dmp'', upload yes: ''Discarded=1''
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe.
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe.
src/common/pipes.cpp (883) : Fatal assert; application exiting
src/common/pipes.cpp (883) : Fatal assert; application exiting
Installing breakpad exception handler for appid(melvor idle)/version(1.0)/tid(2646622)
_ExitOnFatalAssert
assert_20230603112324_3.dmp[2647980]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230603112324_3.dmp
assert_20230603112324_3.dmp[2647980]: Finished uploading minidump (out-of-process): success = yes
assert_20230603112324_3.dmp[2647980]: response: Discarded=1
assert_20230603112324_3.dmp[2647980]: file ''/tmp/dumps/assert_20230603112324_3.dmp'', upload yes: ''Discarded=1''
```

### Reproduction Steps

1. Press "play" on steam
2. Just wait while the game is stuck for multiple minutes before closing automatically

### Expected behaviour

I expect the game to be fixed, it's been three days. That's unacceptably long to leave the game in a broken state. Last time the same issue happened it was fixed within 24 hours.

### Screenshots

![kuva](https://github.com/MelvorIdle/melvoridle.github.io/assets/3796411/a07484d3-3db5-4919-8d23-d4c88001e020)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

Can't get this far

### Are you using any mods?

No

**Comment by ScarlettHoefler** [comment]
Just wanted to post and say I had the same issue on my machine on the latest version of the game, V1.2. The game works on every version except Steam for me; I've tried Firefox + Safari, and the iOS mobile app. I experience this problem on both MacOS and Windows.

I've tried deleting the game's local data at `~/Library/Application Support/Melvor Idle` which gets me to the login screen. However, after entering my account info, the login button changes to a spinner and spins "forever" in the same way before eventually closing itself:
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/1617436/4b70a1ef-9f59-4ca4-b8a5-4919788df071)

I have all mods disabled.

Is there any way I can pull up a console or stack trace on the desktop version of the game to help provide more info?
