### ISSUE TITLE
Razor-Sharp Claws enemy special attack is avoidable

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#344]
**Describe the bug**
Despite the description of Malcs, the guardian of Melvor's special attack Razor-Sharp Claws attack being: "Unavoidable sharp claws slice at you for two hits (520 dmg each)" the attacks can still be dodged.

**To Reproduce**
1. Fight Malcs, the guardian of Melvor
2. Note that the Razor-Sharp Claws attack can miss

**Expected behavior**
Razor-Sharp claws should always hit, or the description should be changed to say they are avoidable.

**Cause of Bug**
![image](https://user-images.githubusercontent.com/58208131/90090490-63e62180-dce1-11ea-8d4f-f98bd35b4491.png)

The forceHit flag for the attack is currently set to false, allowing the attack to be dodged.

**Comment by MelvorIdle** [comment]
Upcoming update has this fixed.
