### ISSUE TITLE
the items didn't arrange to correct place

### ISSUE THREAD

**Issue by scottnick** [MelvorIdle/melvoridle.github.io#3440]
### Describe the bug

The new items that can buy in Dealers in town would place in backpack at the front ,but it isn't logs

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5911

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.2,
