### ISSUE TITLE
Legacy Time not updating in  hardcore

### ISSUE THREAD

**Issue by Zorphan** [MelvorIdle/melvoridle.github.io#3441]
### Describe the bug

legacy ticks/time is not updating every hr in Hardcore mode.. my legacy time hasent moved from 0h 55m 00s for days now

- [ ] 

### Expected behaviour

time to update every hour

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5911

### Are you using any mods?

No

**Comment by WoneTooPhree** [comment]
The tick no longer goes up.
I suggest you read the patch note for township rework here :
https://store.steampowered.com/news/app/1267910/view/3700311793101067360
