### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by fenderbender234** [MelvorIdle/melvoridle.github.io#3455]
### Describe the bug

I have completed all the requirements for Mastery Completion.  I have both base and ToTH expansion items at 99 and all mastery pools are at 100% except cooking which is at 102.83%.  I dont know why it is above 100% (maybe something with Auto Master?).  I have all mods currently disabled and reloaded the game but the achievement wont pop

### Reproduction Steps

1. Get Auto Master mod (maybe)
2. Get 99 Mastery in all skills
3. Watch achievement not pop

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/ITx52Aum

### Screenshots

![4](https://github.com/MelvorIdle/melvoridle.github.io/assets/31377173/27cf3de1-defc-41b9-96da-798c889cd9ba)

### Console output

Using steam, not browser.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?6056

### Are you using any mods?

Yes

**Comment by 04Slash** [comment]
This is a mod issue and should be reported to the mod devs.

You can remove the mastery by copy and pasting the following into the console then reload the game: `game.cooking.actionMastery.delete(game.cooking.actions.getObjectByID('melvorF:Lemon_Cake'));` 

If you use mobile or steam, the dev.Console mod will add the console.
