### ISSUE TITLE
[Bug]: Bank Full discards crafted item

### ISSUE THREAD

**Issue by psynt** [MelvorIdle/melvoridle.github.io#3458]
### Describe the bug

If bank is full, including the correct amount of items required for one craft, the item will be crafted, the ingredients taken, and the item will be tossed because the bank thinks it is full, despite the newly opened slots being left empty

### Reproduction Steps

1. Have your bank full. Have a single unstrung bow and a single bowstring in the last 2 slots. 
2. String the bow. 

### Expected behaviour

The bowstring and the unstrung bow should have been removed, and I should have received the strung bow. Instead of it getting tossed as if my bank were full. 

Another idea would be to disallow the crafting of items when bank space won't allow it.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/wkzDxCkN

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

6062

### Are you using any mods?

No

**Comment by radmint** [comment]
also seeing this on beta Android app 1.2.1 sub version ?7994
