### ISSUE TITLE
damageToEnemy rounding inside of damageEnemy function may cause slightly more xp to be earned than intended, and improper stat tracking

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#346]
**Describe the bug**
Inside the attackEnemy function certain cases result in a different amount of damage actually being dealt to the enemy than the damageToEnemy variable holds. This impacts the accuracy of all calculations regarding damageToEnemy past the call to damageEnemy, such as slightly higher xp being awarded than expected, fractional/inaccurate values in the total damage dealt statistic. (See related bug #345), and fractional/inaccurate values in the damage dealt statistics for weapons.

![image](https://user-images.githubusercontent.com/58208131/90235568-c83adb00-ddde-11ea-8793-053fcfea782c.png)

**Expected behavior and bug fix**
damageToEnemy should be rounded prior to the call to damageEnemy, and then fed into the function as is.

```js
damageToEnemy = Math.floor(damageToEnemy);
damageEnemy(damageToEnemy);
```
This should also resolve all of the issues below this function call.

**Comment by MelvorIdle** [comment]
Thanks. I'll sneak this one into the upcoming update.
