### ISSUE TITLE
[Bug]: Labrynth clue 4 not dropping

### ISSUE THREAD

**Issue by Mcal11** [MelvorIdle/melvoridle.github.io#3461]
### Describe the bug

Clue 4 is not dropping. I've been trying for two days. All of the other clues dropped within an hour.

### Reproduction Steps

not dropping

### Expected behaviour

loot to drop

### Screenshots

n/a

### Console output

n/a

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

>6062

### Are you using any mods?

No

**Comment by 04Slash** [comment]
Clue 4 has the lowest drop chance of all the clues (1/610): https://wiki.melvoridle.com/w/Labyrinth_Clue_4

I've also confirmed that clue 4 does drop on ?6062.

**Comment by coolrox95** [comment]
Bad RNG is not a bug.
