### ISSUE TITLE
[Bug]: App UI Cut Off

### ISSUE THREAD

**Issue by OSIronBrian** [MelvorIdle/melvoridle.github.io#3471]
### Describe the bug

After updating to Android Beta App v4.0, the UI on the right side is slightly cut off (few pixels it looks).
Details:
Oppo CPH2021
Android 11
Melvor v4.0

### Reproduction Steps

Launch game as per usual and the screen is cut off, just on the right edge of the two sword menu up the top right corner.

### Expected behaviour

Menu is not cut off

### Screenshots

![355049296_792598649067286_3726929873265890768_n](https://github.com/MelvorIdle/melvoridle.github.io/assets/137887119/9a03ee61-0a99-4f27-b4d1-9b4997fe7840)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?

### Are you using any mods?

Yes

**Comment by IndigoSushi** [comment]
Also occuring on Android 10 / One UI v2.5 👈
