### ISSUE TITLE
[Bug]: <title>lava lake is still bugged even after new beta release

### ISSUE THREAD

**Issue by Mantisx1** [MelvorIdle/melvoridle.github.io#3472]
### Describe the bug

I cannot kill a single enemy. When i start fight after first hit an error occurring. Yes i have mods but all other dungeons have no problems at all. I even tryed to turn off mod launcher but still same problem so mod launcher is not guilty.(i also cleaned cache hundreds of times so thats also not a problem. )

### Reproduction Steps

Go to lava lake dungeon (level 102 slayer) 

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/RmfRw6wj

### Screenshots

![Screenshot_20230627-224002](https://github.com/MelvorIdle/melvoridle.github.io/assets/126607744/1d3b3c5d-69b7-4095-8b41-54c3ed11f337)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?6099

### Are you using any mods?

Yes

**Comment by 04Slash** [comment]
Try removing the 'Better Auto Eat' mod. It's known to cause this issue.

https://github.com/MelvorIdle/melvoridle.github.io/issues/3243#issuecomment-1486029444
