### ISSUE TITLE
[Bug]: <title>Monsters Slain on Tasks counter sometimes going up by 2

### ISSUE THREAD

**Issue by Silverfyree** [MelvorIdle/melvoridle.github.io#3475]
### Describe the bug

Statistics -> Slayer -> Monsters Slain on Tasks
Counter sometimes randomly goes up by 2 instead of 1 per kill

### Expected behaviour

Should go up by 1 after each kill

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/hVjWVO3T

### Screenshots

https://github.com/MelvorIdle/melvoridle.github.io/assets/77082862/de179b1c-e248-4bb2-ae4e-50e5a788c880

### Console output

N/A

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?6099

### Are you using any mods?

Yes

**Comment by mythridium** [comment]
@Silverfyree 

Where you using Slayer Bounty Potion?

This has a chance to count killing a slayer monster twice. I wonder if the game is just treating a kill as double when this procs which counts the stat twice.
