### ISSUE TITLE
[Bug]: Displaying the names of items in the bank 

### ISSUE THREAD

**Issue by Mot92** [MelvorIdle/melvoridle.github.io#3477]
### Describe the bug

After the last update in the bank, the names began to be displayed as in the screenshot 
Аналогичная проблема наблюдалась и на бета тесте 

### Reproduction Steps

1. Go to the bank 

### Expected behaviour

Previously, there was a bank with icons, now only the name of the item is visible 

### Screenshots

![Screenshot_2023-06-27-22-44-17-613_com malcs melvoridle](https://github.com/MelvorIdle/melvoridle.github.io/assets/57660738/cb6dead6-2ed2-4b49-910d-50ffb19bc36a)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?6099

### Are you using any mods?

No

**Comment by Mot92** [comment]
![247628256-1a0a2228-0023-4393-8302-385aa9167f42](https://github.com/MelvorIdle/melvoridle.github.io/assets/57660738/d51aef76-ccb0-4f27-be63-69e08fc2c275)
The old view of the bank

**Comment by 04Slash** [comment]
This is caused by 'Toggle Minor Accessibility Features' in the settings.

**Comment by Mot92** [comment]
Thanks, it helped
