### ISSUE TITLE
[Mobile] "ReferenceError: Fuse is not defined" when loading a save

### ISSUE THREAD

**Issue by Tymon13** [MelvorIdle/melvoridle.github.io#349]
I'm not sure if this is the right place to report, but I cannot find any repo for mobile and Discord directs here.

**Describe the bug**
Loading a save sometimes (now more often than not) shows me error mentioned in title. If I try to fix my save it goes back to save selection and when I try to load the save again, it may or may not show the error again. Skipping "Fix my save" (by closing the window with X) shows me a game that is running - it continues actions that I left it with - but all of the actions except first are locked as if I were level 1 (which doesn't prevent action of higher level from continuing). The problem seems to be with mastery system - I have NaN% completion in completion log and all visible masteries (near actions) are set to 70.

**To Reproduce**
I'm just trying to load a save. Local or cloud doesn't matter. 

**Expected behavior**
No errors.

**Screenshots**
It's your standard error screen with "Fix my save" button. Can provide screenshot if needed.

**Browser**
I'm on mobile, free version (with ads), Nokia 5.1 Plus, Android 10, game version - newest available in shop (according to Android it's 0.03.5, inapp it's Alpha v0.16.1 from 27th July).

**Console output**
N/A

**Are you using any scripts?**
N/A

**Comment by MelvorIdle** [comment]
Fuse is an external library the game attempts to load. This error occurs when that file cannot be obtained from the external server. In the next update, I will host this library myself so the game will have no issues loading it in the future.

It should work soon though, keep trying!
