### ISSUE TITLE
[Bug]: Can't sell Mithril Helmet (0 GP value)

### ISSUE THREAD

**Issue by smittyno1** [MelvorIdle/melvoridle.github.io#3493]
### Describe the bug

Mithril Helmet is stuck in my inventory and shows as 0 GP value.

### Screenshots

![bug](https://github.com/MelvorIdle/melvoridle.github.io/assets/49417920/90e2c5d7-3e50-4baa-8b86-4f55d04fd512)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?6113

### Are you using any mods?

No

**Comment by ekuland** [comment]
You have the slider at 0 helmets to sell.
