### ISSUE TITLE
Crown of Rhaelyx base preserve chance doesn't work with herblore

### ISSUE THREAD

**Issue by Waha-nonono** [MelvorIdle/melvoridle.github.io#350]
**Describe the bug**
Crown of Rhaelyx doesn't give 10% chance to preserve resources with herblore. This is because the code looks like this
```
let checkR = checkRhaelyx();
if (checkR) chanceTotal += items[CONSTANTS.item.Crown_of_Rhaelyx].chanceToPreserve;
```
with no line that gives the base preserve chance.
The above code is also missing the if statement to check if the player has the crown equipped.

The code SHOULD look like this (same as for other skills).
```
if (equippedItems.includes(CONSTANTS.item.Crown_of_Rhaelyx)) {
    let checkR = checkRhaelyx();
    if (checkR) chanceTotal += items[CONSTANTS.item.Crown_of_Rhaelyx].chanceToPreserve;
    else chanceTotal += items[CONSTANTS.item.Crown_of_Rhaelyx].baseChanceToPreserve;
}
```

**Comment by MelvorIdle** [comment]
Fixed in coming update
