### ISSUE TITLE
[Bug]: Meteorite Ore Unable to Mine

### ISSUE THREAD

**Issue by Jds98677** [MelvorIdle/melvoridle.github.io#3507]
### Describe the bug

Unable to mine ore with correct levels. Node has 0 HP and does not refill. 
![IMG_1960](https://github.com/MelvorIdle/melvoridle.github.io/assets/140076522/f399c9d8-17fb-41ea-8d38-e8e742204dc4)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?6124

### Are you using any mods?

No

**Comment by icedtrumpets** [comment]
"Meteorites are located at random in astrology"
