### ISSUE TITLE
[Bug]: Cooking Skill: Lobster Cooking

### ISSUE THREAD

**Issue by Harshlyme** [MelvorIdle/melvoridle.github.io#3518]
### Describe the bug

When I cook the lobster under the cooking skill it gives me the experience points, but I receive no cooked lobster for it. It shows the lobster icon after cooking but when it does the +1 it shows up like +1 (0) and it is not in my bank at either. I have 129/160 bank slots, so it isn't a space issue. I even exited the character itself and reopened the save.

### Reproduction Steps

1.Go to cooking
2. Cook lobster

### Expected behaviour

I was hoping to receive my cooked items.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/66vzAgVv

### Screenshots

![Screenshot (14)](https://github.com/MelvorIdle/melvoridle.github.io/assets/141132936/26703ce9-5dc7-4165-b28b-e49c9790bb81)

### Console output

I run the game on the steam app.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?6151

### Are you using any mods?

No

**Comment by 04Slash** [comment]
The food is going directly into your food slots because you've purchased [Cooking Upgrade 1](https://wiki.melvoridle.com/w/Cooking_Upgrade_1)

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/6bc2d71c-322d-4134-baf2-e33b76424549)

**Comment by Draedon123** [comment]
<img width="332" alt="image" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/118961726/89ccda1d-234d-42fd-9fc1-78e502c46ef7">
turn this off!

**Comment by Harshlyme** [comment]
Oh sheesh, I didn't realize it did that. Thank you.
