### ISSUE TITLE
Upgrading ranged strength / magic damage potions is still broken

### ISSUE THREAD

**Issue by gmiclotte** [MelvorIdle/melvoridle.github.io#352]
**Describe the bug**
Same as #328, upgrading ranged strength and magic damage potions does not work correctly.

In the latest patch (ALPHA V0.16.2) the `herbloreMasteryID` of magic damage potion items was changed from `4` to `20`, but it should be `19` instead.

Meanwhile the `herbloreMasteryID` for ranged strength potions is `19` but should be `20` instead.

**To Reproduce**
1. Set `herbloreMastery[19]` to a sufficiently high level (`>=15`) (magic damage potion mastery)
2. Set `herbloreMastery[20]` to level `1` (ranged strength potion mastery)
3. Try to upgrade a Ranged Strength Potion I (`item[611]`), the mastery check will erroneously succeed.
4. Try to upgrade a Magic Damage Potion I (`item[615]`), the mastery check will erroneously fail.

Similar for the other tiers, or for higher ranged strength potion mastery than magic damage potion mastery.

**Expected behavior**
It checks the correct index, i.e. `19` for magic damage potions, and `20` for ranged strength potions.

**Screenshots**
Can't pass magic damage potion mastery check
![Screenshot from 2020-08-17 09-04-56](https://user-images.githubusercontent.com/12995926/90367282-f6335000-e068-11ea-9e1c-c50cda17373b.png)
But the mastery is sufficiently high
![Screenshot from 2020-08-17 09-04-38](https://user-images.githubusercontent.com/12995926/90367292-f9c6d700-e068-11ea-9ec0-9bb6efca1ac1.png)
Can pass ranged strength potion mastery check
![Screenshot from 2020-08-17 09-32-59](https://user-images.githubusercontent.com/12995926/90369839-b40c0d80-e06c-11ea-952f-51f3f8882031.png)
But the mastery is not high enough
![Screenshot from 2020-08-17 09-33-14](https://user-images.githubusercontent.com/12995926/90369844-b5d5d100-e06c-11ea-8003-0eb6171f74c1.png)

**Console output**
Just illustrating the relevant data corresponding with the previous screenshots.
```js
items.filter(
        x=>x.herbloreMasteryID===19||x.herbloreMasteryID===20
).forEach(
        x=>console.log(x.name, x.herbloreMasteryID)
)
// output
"Ranged Strength Potion I" 19
"Ranged Strength Potion II" 19
"Ranged Strength Potion III" 19
"Ranged Strength Potion IV" 19
"Magic Damage Potion I" 20
"Magic Damage Potion II" 20
"Magic Damage Potion III" 20
"Magic Damage Potion IV" 20
```
```js
herbloreMastery[19]
// output
{mastery: 53, masteryXP: 11702}
```
```js
herbloreMastery[20]
// output
{mastery: 1, masteryXP: 1}
```

**Comment by MelvorIdle** [comment]
Should be hotfixed now
