### ISSUE TITLE
[Bug]: Harvest All in farming doesn't give back as many seeds as manually harvesting

### ISSUE THREAD

**Issue by ltsSmitty** [MelvorIdle/melvoridle.github.io#3521]
### Describe the bug

When using `Harvest All` with 120 Farming, Superior Max Cape, 99 Mastery on carrots, I only receive back 11-30 carrot seeds. When I harvest them all manually, I end up in the 25-65+ seeds returned range. 

I tested harvesting all 5 times each with the superior max cape, then the superior farming cape, then with the sup max cape but picking manually:
**Sup Max**: 16, 12, 24, 25, 13
**Superior farming**: 11, 18, 30, 15, 17

Manual harvesting with Sup Max: 60, 54, 29, 26, 32, 67

This sample size isn't huge, but I noticed this account was taking way longer than another account to get the 5000 carrot seeds for the task. I don't have a faster way to test this than load > harvest > measure > repeat, but I'd welcome more rigorous testing. I don't believe this behavior has always been present, but I'm not sure when it started.

### Reproduction Steps

Click `harvest all` vs harvesting each individually.

### Expected behaviour

I expect the range to be the same, but there are meaningful statistical differences between the two.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/aBYe4fM8

### Console output

Nothing relevant

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

6153

### Are you using any mods?

Yes

**Comment by mortenya** [comment]
I'm glad I came to submit a bug about the iOS app crashing to title regularly because I've been seeing that I'm getting 7-20 seeds back with the skillcape, I'm at 110 farming with 99 on all base game seeds.

**Comment by supersaiyoon** [comment]
I'd like to also add that I've been experiencing the same issue with using "Harvest All." With no skillcape and no farming add-on, there's a noticeable difference in the amount of seeds I get if I manually harvested the crop and herb plots.
