### ISSUE TITLE
[Bug]: not adding cooked carp to bank

### ISSUE THREAD

**Issue by TobyHaty** [MelvorIdle/melvoridle.github.io#3526]
### Describe the bug

When cooking raw carp it isn’t adding the cooked carp to the bank. It is when cooking perfect carp but not normal

### Reproduction Steps

Go to cooking 
Selecting recipe Carp
Start active cooking 

### Screenshots

Have a video recording but not sure if adding from phone. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?6153

### Are you using any mods?

Yes

**Comment by Draedon123** [comment]
this is NOT a bug. simply uncheck this box
<img width="328" alt="image" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/118961726/4427ba4a-2b45-4881-a7d0-6db1555af4fc">

**Comment by TobyHaty** [comment]
Doh!!  I did not know I had that ticked. Makes so much sense now. Apologies for my dumbness

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
