### ISSUE TITLE
Thieving Permanent Stun

### ISSUE THREAD

**Issue by Zreknod** [MelvorIdle/melvoridle.github.io#353]
**Describe the bug**

**To Reproduce**
1. Go to '...' Thieving
2. Click on '....' Farmer
3. Wait for bug

**Expected behavior**
Thieving farmers for a few minutes when my online progress was halted. When trying to restart thieving "You are stunned" text shows up. I am forced to go to a different character then back to begin theiving again but it happened twice in a row.
**Screenshots**
![thiefBug](https://user-images.githubusercontent.com/69788814/90372587-3b8a5a00-e036-11ea-9567-95e3f1844a5b.jpg)

**Browser**
Please tell us what browser you are using and what version.
Google Chrome  84.0.4147.125 (Official Build) (64-bit)
**Console output**
Please open the console by pressing F12 and copy it here.
[melvoridle.com-1597651276832.log](https://github.com/MelvorIdle/melvoridle.github.io/files/5082938/melvoridle.com-1597651276832.log)

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.
No scripts

**Comment by MelvorIdle** [comment]
Hotfixed
