### ISSUE TITLE
[Bug]: Township reward gives more items than my bank has space for

### ISSUE THREAD

**Issue by Sachbir** [MelvorIdle/melvoridle.github.io#3531]
### Describe the bug

I completed the township task "Easy 10". When I claimed the reward, I was given 4 new runes. The item count in my bank went up to 36/33. 

### Reproduction Steps

1. Fill your bank to near or at capacity. 
2. Complete the requirements for the township task Easy 10. 
3. Redeem reward. 

### Expected behaviour

Items will be deposited in your bank, going over the capacity you actually have. 

### Screenshots

![Bank Overflow](https://github.com/MelvorIdle/melvoridle.github.io/assets/32587956/6841b64d-0692-46ee-8dc3-9410c4f98231)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?6155

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
This behavior is intended, to prevent the possibility of losing rewards when claiming them from a task.
