### ISSUE TITLE
[Spelling/Grammar]: Notification timeout shows two "20 seconds" options

### ISSUE THREAD

**Issue by D-Scaduto** [MelvorIdle/melvoridle.github.io#3534]
### What text is wrong?

Title says it all. 

It looks like the timeout duration for beta notifications shows 20 seconds twice and one of the options should be 10 seconds. 

### What is the correct spelling or grammar?

10 Seconds

**Comment by D-Scaduto** [comment]
![image_2023-08-17_155519091](https://github.com/MelvorIdle/melvoridle.github.io/assets/4481192/a836c9b6-650f-448b-80dc-21f1cf4efabf)

**Comment by coolrox95** [comment]
Issue has been fixed as of v1.2,
