### ISSUE TITLE
[Bug]: <Game shows white screen when loading after switching apps or closing phone>

### ISSUE THREAD

**Issue by Nospar** [MelvorIdle/melvoridle.github.io#3538]
### Describe the bug

This bug is related to the mobile version of the game.

When you have an instance of Melvor Idle open on your phone, if you switch off it or lock your phone, when you go back to it you're greeted with a white screen that doesn't go away. This always happens when you come off the game, so it doesn't matter how you're trying to re-access it, you'll always be faced with the same problem. There does seem to be a grace period where you can close the app and re-open it without any issues, but this is only a few seconds. 

The only fix for this bug at the moment is to exit the game completely from the app tray and relaunch it. 

### Reproduction Steps

1. Launch Melvor Idle on Mobile beta version
2. Come off the app by any means (Switch to another app, lock your phone, go back to the home screen) 
3. Leave a few seconds, 10-15 should suffice 
4. Try and re-open the app by either clicking the app iconic or opening it again from your app tray 
5. The issue should present itself
6. Fully close the app from the system tray and re-open the game
7. Should work as normal again

### Expected behaviour

An infinite white screen should appear that doesn't leave and won't open the game. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?6159

### Are you using any mods?

No

**Comment by drastik25** [comment]
I have this same issue consistently, reported it through the play store feedback within the first day or 2 of the beta with no improvement since.

**Comment by robot-apocalypse** [comment]
Same, and I just confirmed it happens on the newest version: v1.2 Pixel 4a,

**Comment by srmols** [comment]
Still happens on a Galaxy Samsung S20 FE. I've read another bug report where a Xiaomi user said that Game Turbo was the cause. Trying to disable Samsung Game Booster (by removing permissions, no other way I know) and still happens.

https://github.com/MelvorIdle/melvoridle.github.io/issues/3630
