### ISSUE TITLE
[Bug]: Fine Coin Purse will not unequip

### ISSUE THREAD

**Issue by RStelford** [MelvorIdle/melvoridle.github.io#3539]
### Describe the bug

The Fine Coin Purse will not unequip on my character and anything equiped that requires the offhand slot disappears.  Can you help?  If you click the unequip button, it creates a Fine Coin Purse in inventory.

### Expected behaviour

Should be able to unequip this  item and replace it with something else.

### Screenshots

(anonymous) @ player.js?6159:219

### Console output

3c9471dd-2c4d-4a09-a64f-78e644fe279d:590 Uncaught Error: Unknown slot translation Shield
    at validSlotNameToItemRegistrySlot (3c9471dd-2c4d-4a09-a64f-78e644fe279d:590:19)
    at 3c9471dd-2c4d-4a09-a64f-78e644fe279d:722:34
    at Map.forEach (<anonymous>)
    at NamespaceRegistry.forEach (namespaceRegistry.js?6159:38:44)
    at Bank.<anonymous> (3c9471dd-2c4d-4a09-a64f-78e644fe279d:720:25)
    at typeName.<computed> (mod.js?6159:840:52)
    at Player.unequipItem (player.js?6159:221:93)
    at typeName.<computed> (mod.js?6159:838:28)
    at HTMLButtonElement.<anonymous> (player.js?6159:219:38)
validSlotNameToItemRegistrySlot @ 3c9471dd-2c4d-4a09-a64f-78e644fe279d:590
(anonymous) @ 3c9471dd-2c4d-4a09-a64f-78e644fe279d:722
forEach @ namespaceRegistry.js?6159:38
(anonymous) @ 3c9471dd-2c4d-4a09-a64f-78e644fe279d:720
typeName.<computed> @ mod.js?6159:840
unequipItem @ player.js?6159:221
typeName.<computed> @ mod.js?6159:838

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?6159

### Are you using any mods?

Yes

**Comment by 04Slash** [comment]
> 3c9471dd-2c4d-4a09-a64f-78e644fe279d:590 Uncaught Error: Unknown slot translation Shield
> at validSlotNameToItemRegistrySlot (3c9471dd-2c4d-4a09-a64f-78e644fe279d:590:19)

3c9471dd-2c4d-4a09-a64f-78e644fe279d is likely a mod. These names are randomized each time you start the game so I can't tell which one this is but in the console you can click on this and it'll open the file. From there you can try looking for a name.

**Comment by g0lpebaix0** [comment]
Not only you cant unequip if you try equip any 2 hand weapon or  anything on the shield slot it will be deleted of the game. please i need do my progress my combat skill on Throne of Herald areas but is impossible without a shield

**Comment by coolrox95** [comment]
As stated, this issue is due to one of your installed mods.
