### ISSUE TITLE
Goblin raid issue, draining prayer.

### ISSUE THREAD

**Issue by Swiilsis** [MelvorIdle/melvoridle.github.io#354]
**Describe the bug**
If you have prayer active before entering Goblin Raid, it'll drain points whilst fighting. 

**To Reproduce**
1. Go to 'Go turn on prayer'
2. Click on 'Jump into Raid'
3. Scroll down to 'start attacking'

**Expected behavior**

**Screenshots**

**Browser**
Firefox 79

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
SEMI And melvor Combat Simulator

**Comment by MelvorIdle** [comment]
Hotfixed
