### ISSUE TITLE
[Bug]: Fire Shard drop rate

### ISSUE THREAD

**Issue by NubeSkills** [MelvorIdle/melvoridle.github.io#3540]
### Describe the bug

Fire shards are not dropping at the rate they are supposed to (according to wiki).
I ran Infernal Stronghold 10 times for the Infernal Cores to upgrade the Ancient claws to Infernal Claws. I only received 94 shards the entire 10 runs.
If the wiki is correct I should have acquired 950 in 10 runs.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

6159

### Are you using any mods?

Yes

**Comment by Flurryous** [comment]
Fire shards are from the Fire God dungeon, not Infernal.

**Comment by NubeSkills** [comment]
Ah shoot. You right. I didn't think I started doing it yet but I might have attempted it once or twice before I did the infernal claw grind and just forgot to pick them out of the invy.
