### ISSUE TITLE
[Bug]: 69696969 Un-mineable Onyx 

### ISSUE THREAD

**Issue by DavidMagda** [MelvorIdle/melvoridle.github.io#3543]
### Describe the bug

Logged in after 13 days (left on mining gold) to find that my Onyx gem vein says there are 69696969 of them and I cannot mine them. Clicking it will alter the status to 'Mining', but nothing happens.

### Reproduction Steps

Unknown. 

### Expected behaviour

I expected to be able to mine Onyx like a normal ore.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/31215899/477d7cdb-1519-41df-822b-44b2ab5b57c3)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?6159

### Are you using any mods?

No

**Comment by ekuland** [comment]
You have zero out of the maximum 6969696969.

**Comment by DavidMagda** [comment]
Understood. Closing issue.
