### ISSUE TITLE
[Bug]: Game Unplayable

### ISSUE THREAD

**Issue by KathleenCadeen** [MelvorIdle/melvoridle.github.io#3548]
### Describe the bug

After completing the tutorial, all skills except combat become locked and require 10,000 GP to unlock, which is not provided, making it impossible to replenish food and play the game.

### Reproduction Steps

1. Start a new game
2. Skip the tutorial or play the tutorial
3. You encounter bug

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/143298226/b25b3749-1873-4e2a-a419-4d5cb92dad3c)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [x] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?6164

### Are you using any mods?

No

**Comment by icedtrumpets** [comment]
This is the point of adventure mode. Read the description of it.
You can make money in combat

**Comment by Draedon123** [comment]
You're playing adventure mode. This is how it's meant to be played. I'll give you a little hint into how you progress
Kill plants for potatoes for food
Slowly get gear from enemies
If you're not at 10k gp, go kill cows and turn their leather into green d-hide from the shop and sell them
You can refer to the [HCCO Guide](https://wiki.melvoridle.com/w/HCCO/Guide/1)
