### ISSUE TITLE
[Bug]: Accidental reset of app state

### ISSUE THREAD

**Issue by kabirsky** [MelvorIdle/melvoridle.github.io#3549]
### Describe the bug

When I use Android Beta version of the game - "return-swipe" (from the edge of the screen to the center) does reset of game state - I must wait ~7-8 seconds on loading screen and load game back every time I accidentally return swipe my game 

### Reproduction Steps

1. Use beta android version
2. Be in the game
3. Swipe from the edge of the screen to the center
4. Be sad that you need to wait to go back to the game

### Expected behaviour

I think game should at least show me "Do you really want to quit?" modal window

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?6164

### Are you using any mods?

No

**Comment by samosbor** [comment]
+1 
Would love a confirmation before returning to character select screen. Would save me from all the times I fat finger my back button on Android.

**Comment by lister169126** [comment]
+1
it does every where i tested - browser (ff, chrome), andoid app, beta android. epic, steam... It's terible, but I can wait to fix before buy dlc's.
