### ISSUE TITLE
[Bug]: <Gem Gloves Does Not exist>

### ISSUE THREAD

**Issue by Deathblo** [MelvorIdle/melvoridle.github.io#3553]
### Describe the bug

When i start mining, and want to equip Gem Gloves, it says the item is not in my bank.
if i go buy a new glove i can see it add 2000 charges, but i still dont get a glove.
I can see the icon under mining "quick equip" but it keeps saying "there's no gem gloves in your bank"

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/143737590/ec3a42c1-71a7-411b-af0e-2323a8b92603)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/143737590/6aea517c-72ff-47f2-8f6d-1b69fc3f8f30)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?6164

### Are you using any mods?

No

**Comment by 04Slash** [comment]
Are the gloves in one of your other equipment sets?

**Comment by Deathblo** [comment]
I see, just found it in another equipment set xD
Dident even notice i had 2. :/
