### ISSUE TITLE
[Bug]: Quick equip in farming menu doesn't implement level 2 of "Seed Pouch"

### ISSUE THREAD

**Issue by sillawned** [MelvorIdle/melvoridle.github.io#3555]
### Describe the bug

Inside the farming tab, I want to select "Seed Pouch" in the Quick Equip menu but I can't equip this item because I have only the version 2 (Seed Pouch II) in my inventory.

### Reproduction Steps

1. Buy "Seed Pouch" at the Township trader
2. Buy "Consumable enhancer" at the Township trader
3. Upgrade "Seed Pouch" with the "Consumable enhancer" -> It gives "Seed Pouch II"
4. Go to the farming tab and see that only one button for "Seed Pouch" is present

### Expected behaviour

The quick equip should equip the item "Seed Pouch" or "Seed Pouch II".

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/30218969/ae2d50da-ad4f-4d2e-aeaa-005eeb1302c9)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/30218969/70aa82de-def1-437b-8316-8e069505efea)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?6164

### Are you using any mods?

No

**Comment by 04Slash** [comment]
If you click on the item in the bank and click the cog, you can select which skill's Quick Equip menu you want that item to show up in. You can do this for any equip-able item.

**Comment by sillawned** [comment]
Thank you, I didn't notice this option was there. This solves the problem and will enhance my future gameplay.
