### ISSUE TITLE
[Bug]: Pig+Octopus synergy does not work for large blowfish

### ISSUE THREAD

**Issue by TheRealIceCracker** [MelvorIdle/melvoridle.github.io#3558]
### Describe the bug

Using the pig and octopus synergy does not consume tablets and thus does not yield cooked large blowfish.

### Reproduction Steps

1. Equip pig and octopus tablets.
2. Fish large blowfish.

### Expected behaviour

1 Pig and 2 Octopus tablets are consumed and 1 cooked large blowfish is yielded 75% of the time.

Instead, only 1 Octopus tablet is consumed and cooked large blowfish are never generated.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?6164

### Are you using any mods?

No

**Comment by 04Slash** [comment]
Cooked Large Blowfish isn't an item that exists in the game.

Both the Raw Blowfish and Raw Large Blowfish cannot be cooked.

**Comment by TheRealIceCracker** [comment]
lmao I'm dumb my bad
