### ISSUE TITLE
Golbin Raid : Weapon reset

### ISSUE THREAD

**Issue by Voldrethar** [MelvorIdle/melvoridle.github.io#356]
I chose the Cloudburst staff at the end of wave 23, I only had the runes provided at the start of the raid so defaulted to wind strike, tested others by clicking fire surge, this caused me to start whacking the golbin with the staff - as it should.
A small popup appeared, I presume telling me I didnt have the runes.
Selected wind strike again, but continued to beat the golbin instead of casting.

Cloudburst has now become Bronze scimmy \o/

**To Reproduce**
-Raid
-RNG a Cloudburst
-Try casting spells you dont have the runes for
-Free Bronze Scimmy

**Expected behavior**
Self-explanatory i think.
Expected it to not delete the staff

**Browser**

Firefox Version 79(64bit)

**Are you using any scripts?**
SEMI and Combat sim are loaded but inactive

**Comment by MelvorIdle** [comment]
This is intended behaviour (See the important info section). However, I will make adjustments so it doesn't unequip straight away without you selecting a spell first.
