### ISSUE TITLE
[Bug]: equipping township skillcape doesn't enable building

### ISSUE THREAD

**Issue by JaySchenk** [MelvorIdle/melvoridle.github.io#3561]
### Describe the bug

I'm trying to build town hall, when I equip the township skillcape I've got enough money but the build button stays disabled.
This bug happens in both browser and android app.

### Reproduction Steps

1. Don't have enough resourced to build in township.
2. Equip skillscape
3. done.

### Expected behaviour

Build button should be enabled once a player has all the resources.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?7587

### Are you using any mods?

No

**Comment by JaySchenk** [comment]
Even when I have enough gold in my stash I'm not able to build the Town hall (trying to upgrade from tier 3 to tier 4), have Aeris as god at 100%.

**Comment by JaySchenk** [comment]
Seems like the gold cost display is still interacting with the reduction from Aeris / cape which isn't in line with the update:

Township Modifiers

    Increased/decreased building cost no longer affects GP cost of buildings, only Township resource costs.

**Comment by bashcans** [comment]
This also happens with iOS

**Comment by AleisterTJMraz** [comment]
Same for me in Firefox.

<img width="1614" alt="Screenshot 2023-09-06 at 09 20 07" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/52040605/aac49915-b2db-4d3c-b9e7-18ea1ff56984">

**Comment by AleisterTJMraz** [comment]
I sold some things to get to 100M, then it let me purchase the upgrade, but only subtracted 75M.

**Comment by MelvorIdle** [comment]
A hotfix has now been released to the game for this issue.
