### ISSUE TITLE
[Bug]: Stun image not shown properly on item description reception notification

### ISSUE THREAD

**Issue by xapex** [MelvorIdle/melvoridle.github.io#3562]
### Describe the bug

When recieving item from Bane item description does not show correct image.

### Reproduction Steps

1. kill bane
2. recieve item
3. check item reception notification

### Expected behaviour

Correctly shown item description

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/23164561/420ea8e7-375b-40e6-853f-bdbf01cb347f)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

7582

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
A hotfix has now been released for this issue
