### ISSUE TITLE
[Bug]: New notifications are dark when in light mode

### ISSUE THREAD

**Issue by AlsoNotNik** [MelvorIdle/melvoridle.github.io#3564]
### Describe the bug

When in Light Mode
New notifications are still in Dark mode

--> There should be a light mode version of the new notifications

### Reproduction Steps

Toggle Dark Mode off
Ensure legacy notifications off
Observe

### Expected behaviour

New notifications shouldn't be dark mode

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/144001490/3dd6b839-2de8-4dc7-bfc1-068f9ca63302)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7587

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
A hotfix has now been released for this issue
