### ISSUE TITLE
[Bug]: Reduce CPU & GPU usage toggle with steam not reducing usage when minimized

### ISSUE THREAD

**Issue by lassus** [MelvorIdle/melvoridle.github.io#3565]
### Describe the bug

Doesn't seem to reduce CPU usage while minimized.

Windows 10.

### Reproduction Steps

1. Start game as steam app
2. Check that Reduce CPU & GPU usage... is turned on
3. Minimize window
4. Observe cpu usage not changing (Resource Monitor)

### Expected behaviour

cpu usage to reduce..

### Screenshots

**
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/1275581/5b307602-82be-4f6d-81e7-e8291e6d6e08)
**

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7593

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Thanks for the report. It looks like the Steam client isn't activating the pause function correctly. Will look into this and get a fix out.
