### ISSUE TITLE
[Bug]: Township Repairs are LESS expensive during Winter

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#3566]
### Describe the bug

Re-opened since this either returned or is still a bug: All images and details have been updated prior to being reopened.

With the new changes, repairs should be MORE expensive during the winter due to the increased repair costs.

Due to `getSingleResourceRepairCostForBuilding` adding both `game.modifiers.decreasedTownshipRepairCost` and `game.modifiers.increasedTownshipRepairCost` together (both positive values), this results in Winter being cheaper to repair instead of more expensive.

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/69f3255b-0b28-4171-ab19-f6881a2ddc27)

### Reproduction Steps

1. Open Township
2. Change season to Winter
3. Repair everything
4. Change Worship
5. See repair costs: ![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/b8033ce4-4b1f-45b8-89bc-439e898e9fc9)
6. Change season to Spring
7. Repair everything
8. Change Worship
9. See repair costs: ![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/cc87033c-514f-4fc8-bfe9-cdab06941f52)

Summer/Fall Repair Costs: ![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/5c9d4349-dc0a-4778-ae8f-8b1fd681e01d)

### Expected behaviour

Repair costs should be increased during the Winter, not decreased.
I have created a test mod which subtracts increasedTownshipRepairCost from decreasedTownshipRepairCost
```js
patch(Township, 'getSingleResourceRepairCostForBuilding').replace(function(o, building, biome, resourceQuantity) {
    const baseCost = this.modifyBuildingResourceCost(resourceQuantity) * this.countNumberOfBuildings(building) * this.getRepairCostModifier(building, biome);
    return ((baseCost * (1 - (this.game.modifiers.decreasedTownshipRepairCost - this.game.modifiers.increasedTownshipRepairCost) / 100)) / 3);
});
```
This results in the following repair values:
Spring: ![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/cb1be13e-e4b0-4131-a7f2-b9f12e4868b3)
Summer/Fall: ![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/5c9d4349-dc0a-4778-ae8f-8b1fd681e01d)
Winter: ![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/4bf44ceb-1bb4-452b-944f-144e5b302ce9)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7610

### Are you using any mods?

No

**Comment by 04Slash** [comment]
Fixed as of ?7600.

**Comment by 04Slash** [comment]
This is either still happening or happening again in ?7610. All images and details have been updated prior to being reopened.

**Comment by MelvorIdle** [comment]
This has now been hotfixed
