### ISSUE TITLE
[Bug]: Game crashes when selecting normal goblin raid negative modifier

### ISSUE THREAD

**Issue by t1rantt** [MelvorIdle/melvoridle.github.io#3567]
### Describe the bug

Game crashes when selecting normal goblin raid negative modifier

### Reproduction Steps

1. Go to Goblin Raid
2. Select Normal Mode
3. Start Raid
4. Select modifiers
5. Game freezes and crashes

### Which platforms are you experiencing this bug on?

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7604

### Are you using any mods?

No

**Comment by t1rantt** [comment]
tested on browser

**Comment by MelvorIdle** [comment]
This has now been hotfixed
