### ISSUE TITLE
[Bug]: Loot quantity in loot box is not centered

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#3568]
### Describe the bug

The quantity number for loot box items is not centered on the image. See picture.

### Reproduction Steps

1. Raid the Golbin Village
2. Fight Golbin
3. See mis-aligned quantity number in loot box

### Expected behaviour

The number should be centered to not trigger OCD :)

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/094db266-4da3-4b05-910c-6d7356fda5a9)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7610

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This issue has now been hotfixed
