### ISSUE TITLE
[Bug]: Missing some icons on pc/steam version

### ISSUE THREAD

**Issue by jjcamus** [MelvorIdle/melvoridle.github.io#3570]
### Describe the bug

So i just purchased and download the game in steam, and some of the icons of activities and tabs are missing, while others are just fine.

### Expected behaviour

Images to appear..

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/RZj054d3

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/26444177/0cef43dc-e214-4b50-a5ba-3a4127027c20)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7610

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This is usually fixed on reload. Not sure why it occurs but recently there seems to be some intermittent issues with out CDN provider. Looking into this over time.
