### ISSUE TITLE
[Bug]: Forced Offline Mode when changing tabs within a non-Combat Skill

### ISSUE THREAD

**Issue by Galahad1155** [MelvorIdle/melvoridle.github.io#3571]
### Describe the bug

Whenever I use tabs to swap sections within most non-Combat Skills (ie Township: Town, Tasks, The Trader, Manage Storage; Smithing: Bars, Bronze Gear, Iron Gear, ..., Divine Gear; Fletching: Arrows, ..., Javelins; Crafting: Leather Armour, ..., Hardwood Armor; Runecrafting: Standard Rune, ..., Lighting Magic Gear; Heblore: Both tabs; Summoning: Marks, Tablets/Familiars, Synergies; only found exceptions being Farming and Astrology) my windowed Steam copy of Melvor would force me into an "Offline mode activated" mode with a greyed screen that will not respond to clicks itself -- except exiting the program -- until I click off onto my browser and then click back into the windowed Melvor, "waking it" back up.

### Reproduction Steps

1. Open a listed non-Combat Skill
2. Swap between any listed tabs

### Expected behaviour

1. Open a listed non-Combat Skill
2. Swap between any listed tabs
3. Continue playing as normal

### Screenshots

Looking at the Herblore Skill's Combat Potions section
![before](https://github.com/MelvorIdle/melvoridle.github.io/assets/144090875/b51ba62a-f598-4155-a417-d2622e50a450)
Clicking the Skill Potions tab leads to forced Offline mode
![after](https://github.com/MelvorIdle/melvoridle.github.io/assets/144090875/4153d109-f762-4279-b787-6fb663d5e57e)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7634

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
We have now removed this functionality from the game and will reintroduce it once there are less bugs. Please reload the game for this change to take effect.
