### ISSUE TITLE
[Bug]: Master experience gains doubled since the last patch

### ISSUE THREAD

**Issue by Dohtt** [MelvorIdle/melvoridle.github.io#3572]
### Describe the bug

Since the previous patch mastery gains have increased to up to 2.1x the amount previous to the patch.

### Reproduction Steps

1. check the mastery gains of the patch before the current one
2. compare to the mastery gains of the current patch

### Expected behaviour

The mastery experience shouldn't have increased prior to AoD release. It should remain the same until the purchase of AoD added the extra items to the pool.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/17968897/97c1db0f-378d-4a5d-9729-0d6d34812614)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/17968897/9be64395-d50b-43bf-a056-a8ee69ee462b)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7636

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Can you please provide a save example so we can do some testing? Thanks!

**Comment by MelvorIdle** [comment]
This has now been hotfixed.

The game was applying mastery modifiers to skills twice, causing substantially increased MXP rates.
