### ISSUE TITLE
[Bug]: Visual - Game Window Blurry - V1.2 (Steam)

### ISSUE THREAD

**Issue by Dinosqueezins** [MelvorIdle/melvoridle.github.io#3574]
### Describe the bug

I'm seeing weird blurring of the game window since the update to V1.2. I'm playing via Steam and have played 700+ hours with no issues until this update.

 I'm on Windows 10, with an i7-10700K (3.8GHz) CPU, 64GB RAM, NVIDIA GeForce RTX 3080 Ti GPU.

I'm including my CPU/GPU usage in screenshots, if that helps. Please let me know if anything further is required. Thank you!

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/49462461/d3092e7c-f58f-4350-b004-f8f565c01f46)

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/49462461/2f2c7880-5a60-42fe-95b6-25f065154fa5)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7650

### Are you using any mods?

No

**Comment by Dinosqueezins** [comment]
I would like to add that I tried the web version of the game (via Mozilla Firefox) and it has no display issues. 

I will play that for now, but would like to have the Steam version instead if possible.

**Comment by MelvorIdle** [comment]
This is very odd and is something I've never seen before. What happens if you reinstall the game?

**Comment by Dinosqueezins** [comment]
Reinstalling the game did not resolve the issue. Please let me know what else I can try. Thanks!

**Comment by Dinosqueezins** [comment]
I've noticed that the issue is present (in the Steam version) most noticeably when I have Mozilla Firefox open and am on Twitch watching a stream, which was never an issue before. I hope this helps narrow it down.

**Comment by DianTrex** [comment]
I know this post is old but maybe I can bump it with this comment. But I'm having this same issue and was wondering if there's any kind of fix to this?

**Comment by Daelnis** [comment]
Hello,

Sorry to say, but still happening on steam. Game goes blur without reason. Any kind of fix on this ? Ty

**Comment by Dinosqueezins** [comment]
I haven't heard anything yet for a fix. The blurring is still happening for me on current version via Steam, even after re-installation.

For now, I've been using the web version instead. @MelvorIdle please let me know if I can try anything else. Thank you!

**Comment by Dinosqueezins** [comment]
Hi, this is not fixed for me still:
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/49462461/250753b8-97c6-4ad6-8a5a-8a5222e5a5a8)
