### ISSUE TITLE
[Bug]: Item is added to inventory when I try to take it off

### ISSUE THREAD

**Issue by kasiakreis** [MelvorIdle/melvoridle.github.io#3576]
### Describe the bug

After I try to take off Book of Scholars, it is addedd in the inventory and I think I can do it forever.
So far I only can reproduce this bug on Book of Scholars, for example when I try to do it with my Jewelled Necklacle (I lock it in my inventory and then to try take it off) it doesn't work. 

Pls see the video in screenshots section, it's probably better than the description

### Reproduction Steps

1. Go to BANK account and search for Book of Scholars, go to this tab
2. Open EQ set 1 and try to take off Book of Scholars
3. Book of scholar is not taken off, but it adds up in the inventory

### Expected behaviour

Book of scholar is taken off and the amount doesn't change

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/Ru7issfy

### Screenshots

Video desktop: https://drive.google.com/file/d/1payrKorwGprveug4Ck2rTBkqT2S2wSdb/view?usp=sharing
Video iOS: https://drive.google.com/file/d/1bOdIsXJociXtfM-oOiVHrhn-BhK4HGF5/view?usp=sharing

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7650

### Are you using any mods?

Yes

**Comment by kasiakreis** [comment]
After a little bit of an investigation, I see that after disabling this mod it works https://mod.io/g/melvoridle/m/quick-equip-manager

**Comment by MelvorIdle** [comment]
Thank for you confirming what caused the issue
