### ISSUE TITLE
[Bug]: Reward from township task caused bank to go overcapacity.

### ISSUE THREAD

**Issue by LazyCoyote** [MelvorIdle/melvoridle.github.io#3578]
### Describe the bug

I currently have a full bank with 12 bank slots. When I claimed the kill 100 plants township task and received the 2000 potatoes it put them in my bank and caused my bank to go over its 12 bank slot capacity. After the item was claimed my bank shows 13/12.

I am doing a no-shop (no selling), 12 bank run and I will typically use the full bank to "delete" items I farm since there is nowhere for the item to go. I had thought that claiming township rewards would act the same but it still put items in my inventory even though my bank was already full.

![MicrosoftTeams-image](https://github.com/MelvorIdle/melvoridle.github.io/assets/144167138/ccbb7f99-0136-4373-9683-fed9d6e15fa1)

### Reproduction Steps

1. Get your bank to full
2. Claim a township task that gives items

### Expected behaviour

I would expect the claimed reward items to be "deleted" similar to how other skills function when the game tries to add items to a full bank. 

### Screenshots

![MicrosoftTeams-image](https://github.com/MelvorIdle/melvoridle.github.io/assets/144167138/a3dbdaf2-5f1e-4fa8-b77b-f6d065722474)

I have circled the overcapacity of the bank with the "13/12" and circled the 2000 potatoes that were added that caused the bank to go over capacity. 

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7650

### Are you using any mods?

Yes

**Comment by 04Slash** [comment]
This is an intended feature. See #3531

**Comment by MelvorIdle** [comment]
Slash is correct, this is intended so you do not lose the rewards when claiming.
