### ISSUE TITLE
[Bug]: Mastery notification incorrectly displays levels gained

### ISSUE THREAD

**Issue by BeowulfDragon** [MelvorIdle/melvoridle.github.io#3580]
### Describe the bug

If the mastery level for a given item increases while a notification for a previous increase for the same item is still displayed, the levels are reached are added together for the notification.

### Reproduction Steps

1. Level up an item's mastery
2. Before the mastery level notification dissapears, level it up again

### Expected behaviour

The mastery notification instead displays the level just achieved, rather than the sum of the current and last

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/8277613/ded164c6-e910-4494-b0b8-20d036b65a89)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7650

### Are you using any mods?

No

**Comment by DarkPulse** [comment]
Can confirm. It looks even more ridiculous when you're doing mass mastery types of stuff. 🙂

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/5454684/9c4fd350-a186-4d3a-bef0-09cceb686def)

**Comment by MelvorIdle** [comment]
This should now be hotfixed
