### ISSUE TITLE
[Bug]: Skill XP Modifier Amount

### ISSUE THREAD

**Issue by dburgess560** [MelvorIdle/melvoridle.github.io#3581]
### Describe the bug

It seems that the skill XP indicator doesn't seem to indicate decimal amounts, but also there is a discrepancy in the notification amount vs the amount added to my total skill XP.

You'll see in the UI on hover it shows 11xp. The notification also reports 11xp. However when a tablet gets created, I receive 12xp.

I have an Ancient Ring of Skills adding a 8% skill XP bonus, but no pets, no other equippables, etc. modifying skill XP bonuses. So I'm getting 11.88 XP per tick, but it seems some places in the game take that as 11xp, and some round up to 12xp.

The UI:
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/5413080/051476e5-3288-4930-8259-6e6b2e768fed)

Notification:
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/5413080/6d98a114-e2c3-47cc-b76b-106ff0c9a6ce)

Before:
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/5413080/08b45d65-78a7-450d-97ab-51b9fadf6201)
After one tablet creation tick:
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/5413080/d0b360ed-f8eb-4eae-9080-7b9dc4317ee5)

### Reproduction Steps

Equip an Ancient Ring of Skills for 8% skill XP bonus.
Head over to Summoning
Select either the Wolf or Octopus tablets
Hover over the Skill XP, see that it is 11xp and you have 0 bonus XP from modifiers.
Create one of these two tablets, your skill XP will increment by 12 instead of the stated 11.

### Expected behaviour

I'd expect the skill XP hover to show either 0.88 bonus XP as an 8% of 11 would give, or round up to say 1 bonus XP

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7651

### Are you using any mods?

No

**Comment by joakweb** [comment]
Came here to post that same bug, thanks @dburgess560 for saving me the trouble. Can still reproduce this bug on build ?8284
