### ISSUE TITLE
[Bug]: Game reloads after few minutes

### ISSUE THREAD

**Issue by UmbraLord** [MelvorIdle/melvoridle.github.io#3588]
### Describe the bug

While playing the game, the app will suddenly show a full white screen and then a game reload. It acts as if I restarted the game. It seems to occur after a few minutes of being in the game, regardless of whatever action I’m doing. I can switch between skills while working towards completing a task or I can leave the game running while fighting monsters and it’ll still restart after a few minutes.

### Reproduction Steps

1. Start playing the game
2. After a few minutes (roughly 5-10 minutes), the whole screen goes white and the game restarts
3. The above two steps repeat

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7712

### Are you using any mods?

No

**Comment by SergeyLozitsky** [comment]
Absolutely the same case with my iOS app

**Comment by joshmiller-dev** [comment]
This is happening to me as well on my iPad (9th gen). Play for a bit and then suddenly white screen and back to character select. Memory leak maybe?
