### ISSUE TITLE
visual bug - dungeon name persisting after changed enemy

### ISSUE THREAD

**Issue by drboomtown** [MelvorIdle/melvoridle.github.io#359]
**Describe the bug**
The name of the dungeon i cleared persisted after i swapped to a different enemy.
in this case "spider forest" persisted over "plant"

**To Reproduce**
1. Disable auto restart dungeon
2. Clear spider forest
3. fight a plant

**Expected behavior**
like for it to not say spider forest and give me a heart attack

**Screenshots**
https://i.imgur.com/aLAUJSX.png

**Browser**
Chrome
Version 84.0.4147.125 (Official Build) (64-bit)

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Initialy saw it with SEMI loaded, but recreated with no scripts loaded

**Comment by Falterfire** [comment]
The bug goes a bit deeper than this - It'll also keep the combat bar at the bottom of the screen indefinitely after the dungeon ends even if you're doing other skills.
