### ISSUE TITLE
[Bug]: nwjs

### ISSUE THREAD

**Issue by Calydor** [MelvorIdle/melvoridle.github.io#3591]
### Describe the bug

I know, that title looks like spam, but I promise it's not. It should just make it easy for others to spot if they want to report the same.

After the pre-expansion update, Melvor Idle has listed as 'nwjs' in Windows Task Manager, at least on Win10. If you expand the listing it shows Melvor Idle a little ways down for some reason, but mostly just 'nwjs', whatever that is supposed to mean. Internal program name? Even the icon is wrong, though.

### Reproduction Steps

1. Start Melvor Idle.
2. Open Task Manager.
3. Find the 'nwjs' entry.
4. No profit.

### Expected behaviour

I expected it to show as Melvor Idle so I didn't get a heart attack thinking I had some malware running in the background!

### Screenshots

https://cdn.discordapp.com/attachments/844332638293983254/1149377415957708830/image.png

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7727

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
NW.js is an open source chromium platform that Melvor Idle runs on. You can read about it here: https://nwjs.io/

**Comment by Calydor** [comment]
I'm sorry, but that feels like saying that all games written in Unity should just say 'Unity' in the Task Manager. The Task Manager is specifically to see what's running without knowing which programming languages, frameworks, platforms etc. are used for each program. What changed with the pre-expansion update to make Melvor Idle no longer identify itself as such?
