### ISSUE TITLE
[Bug]: Maximum and Superior Maximum Skillcapes breaking layout in Shop

### ISSUE THREAD

**Issue by LeHvass** [MelvorIdle/melvoridle.github.io#3593]
### Describe the bug

When looking at the skillcapes and superior skillcapes in the shop, currently the Maximum Skillcapes are breaking the layout, because they list every single skill requirement.

### Reproduction Steps

1. Go to the shop
2. Go to the Skillcapes or Superior Skillcapes tabs

### Expected behaviour

I'm not completely certain about this, but I seem to remember that they used to just show a requirement "Requires Level 99 in all skills", without listing off every individual skill.

### Screenshots

<img width="1484" alt="Screenshot 2023-09-07 at 20 28 23" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/5744255/c97592fb-7720-43a3-8c33-9b1216dbd1fb">

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7731

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Thanks for reporting. This has now been hotfixed.
