### ISSUE TITLE
[Bug]: Gem Gloves not working when mining crystal. 

### ISSUE THREAD

**Issue by Number34sss** [MelvorIdle/melvoridle.github.io#3595]
### Describe the bug

I am using gem gloves while mining crystal and pure crystal, but although crystal and pure crystal are listed as an ore, the gem gloves are not working and don't grant me any gems or use any glove charges. If I switch to a different ore, such as gold, the gem gloves do work fine. 

### Reproduction Steps

1. Equip gem gloves
2. Go to the mining skill
3. Attempt to mine the crystal or pure crystal.
4. Fail to use any charges on the gem gloves. 

### Expected behaviour

I expected to earn a gem and use a gem glove charge every time I mine crystals or pure crystals as long as I had the gem gloves equipped with charges on them. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?

### Are you using any mods?

No

**Comment by IndigoSushi** [comment]
Can confirm this is still an issue. V1.2 (?7737) using Google Chrome. Mining Gloves work as expected for an Ore vein, but Gem Gloves do not.

**Comment by ChaeyoungTWICE** [comment]
Since it hasn't been mentioned yet, can confirm on the Steam APP not working as well.

**Comment by MelvorIdle** [comment]
This was fixed a few patches ago. Forgot to close this issue
