### ISSUE TITLE
[Bug]: A few crystal fletching items only grant 1 exp on creation

### ISSUE THREAD

**Issue by Flurryous** [MelvorIdle/melvoridle.github.io#3596]
### Describe the bug

As title, the UI display shows that the crystal and pure crystal versions of the javelins, crossbows, shortbows, and longbows all only give 1 fletching exp upon creation. I haven't had the opportunity to check the actual exp drops on them, but at the very least, it's visually bugged. I'm assuming this isn't intentional since I checked a few other crystal items and they seem to be granting the appropriate amount of exp for their tiers. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7737

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This was fixed a few patches ago. Forgot to close this issue.
