### ISSUE TITLE
[Bug]: Woodcutting logs have wrong image/still gives old logs

### ISSUE THREAD

**Issue by Xplendit** [MelvorIdle/melvoridle.github.io#3597]
### Describe the bug

When you cut carrion tree you still get carrion logs, but the image beneeth it shows cursed logs.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/10973992/c41b6230-b61f-4876-a4e5-3bace634e2d4)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7737

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This is a bug relating to the mod "ETA"
