### ISSUE TITLE
Custom amount to sell

### ISSUE THREAD

**Issue by Deadvimz** [MelvorIdle/melvoridle.github.io#36]
Pretty basic, just an option to sell a custom amount to not sell all the resource and to control how much you want to sell without excessive clicking :)

![unknown](https://user-images.githubusercontent.com/17806130/68899226-d9649780-0739-11ea-8641-d001c071a368.png)

**Comment by MelvorIdle** [comment]
Sell X is being introduced in v0.10 :)
