### ISSUE TITLE
[Bug]: Don't work township skillcape

### ISSUE THREAD

**Issue by Klavisz** [MelvorIdle/melvoridle.github.io#3603]
### Describe the bug

Don't work township skillcape, he It doesn't reduce the cost of upgrading buildings

### Expected behaviour

for example, if initially the town hall costs 100 million, then after putting on the township skillcape it should be 80 million

### Screenshots

![Снимок экрана (11)](https://github.com/MelvorIdle/melvoridle.github.io/assets/50041802/5fa5acee-e286-44d1-9b7c-888fdae2da7b)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7747

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This was fixed a few patches ago. Missed this issue to close it.
