### ISSUE TITLE
Summoning charge preservation not working for noncombat skills. 

### ISSUE THREAD

**Issue by MsManhattan** [MelvorIdle/melvoridle.github.io#3604]
### Describe the bug

I am currently leveling astrology, but it seems that the Eagle/Owl synergy is not working, and I am using up all of my tablets regardless of me having a total of 40% charge preservation. 

### Reproduction Steps

1. Equip full summoner set, summoning scrolls, and eagle/owl synergy. Use Runic Trail and Rune Crawl agility courses. 
2. Study in Astrology. 
 

### Expected behaviour

I expected to see some tablet charge preservation in astrology, since I have all the necessary gear equipped. 

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/FEjDqF9f

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7747

### Are you using any mods?

No

**Comment by MsManhattan** [comment]
I made an edit, since the issue also seems to be present in combat. I was just killing them too fast before the summon attacked them lol

**Comment by Flurryous** [comment]
Can vouch for this, I stacked up to 63% charge preserve ( Necro Palace set,  Sup Comp cape, Mark and Harold pets, and Qimican) but still saw tablets being eaten up.

**Comment by MelvorIdle** [comment]
This was fixed in an update back in early October. Closing
