### ISSUE TITLE
[Bug]: Bone Ring not giving prayer points on monster kill

### ISSUE THREAD

**Issue by Neonarg** [MelvorIdle/melvoridle.github.io#3606]
### Describe the bug

The bone ring's description currently says +3 prayer points gained per monster kill but nothing happens when the monster dies.

### Reproduction Steps

1.Equip ring
2.Kill monster
3.Nothing

### Expected behaviour

You should get 3 prayer points per monster killed

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/s5vWjsFv

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7747

### Are you using any mods?

No

**Comment by Kr4pper** [comment]
@Neonarg This was fixed in yesterday's patch https://www.reddit.com/r/MelvorIdle/comments/16i8n39/game_update_v12_7809/
