### ISSUE TITLE
[Bug]: Monster recieve positive Prayer buffs

### ISSUE THREAD

**Issue by Zabbad** [MelvorIdle/melvoridle.github.io#3608]
### Describe the bug

After upgrading from Throne of the Herald expansion to Atlas of Discovery, Prayer buffs such as Hawk Eye, Eagle Eye, Sharp Vision and Rigour is also applied for Wicked Greater Dragon.

### Reproduction Steps

1. Go to Perilous Peaks
2. Fight Greater Wicked Dragon
3. Apply either Prayer of Hawk Eye, Eagle Eye, Sharp Vision or Rigour

### Expected behaviour

Only the player should benefit from the buffs.

### Screenshots

![Buffs](https://github.com/MelvorIdle/melvoridle.github.io/assets/64752242/a4311572-a076-4da2-bb75-362d36802b00)
![Nobuffs](https://github.com/MelvorIdle/melvoridle.github.io/assets/64752242/e346c470-2d70-4a63-beb9-c88d21be7c10)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7756

### Are you using any mods?

No

**Comment by 04Slash** [comment]
WGD does 75% of your maximum hit value. The prayers you are enabling are increasing your maximum hit which will increase WGD's maximum hit with Confusion.

**Comment by MelvorIdle** [comment]
This is intended as per 04Slash's comment
