### ISSUE TITLE
[Spelling/Grammar]: Broken Odd Weapon description

### ISSUE THREAD

**Issue by Fiagra27** [MelvorIdle/melvoridle.github.io#3609]
### What text is wrong?

"towards and Enemy." should be "towards an enemy."
"don't actual understand" should be "don't actually understand" 

much love, the game is a joy!

### What is the correct spelling or grammar?

and -> an
actual -> actually

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.1
