### ISSUE TITLE
[Bug]: <Completion % display error>

### ISSUE THREAD

**Issue by Blowarium** [MelvorIdle/melvoridle.github.io#3610]
### Describe the bug

In the Completion Log when filtered on Atlas of Discovery, Thieving Mastery displays 0/0 as 0%, which I think should be 100%.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/144541001/dfcd8a57-7d9f-4013-8c4e-5f87cee091db)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7729

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.1
