### ISSUE TITLE
[Bug]: <Fishing displays next groups fish>

### ISSUE THREAD

**Issue by domsgarrity** [MelvorIdle/melvoridle.github.io#3612]
### Describe the bug

In the fishing menu, the fish selected shows the next groups fish in the inventory item. 

### Expected behaviour

Fish selected in group displays the fish selected in inventory 

### Screenshots

![Screenshot_20230909-135921](https://github.com/MelvorIdle/melvoridle.github.io/assets/34172044/1bff3344-e240-41f9-acb1-9b9c36db50ae)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7764

### Are you using any mods?

Yes

**Comment by nat-om** [comment]
That's a bug in the ETA mod.

**Comment by MelvorIdle** [comment]
This bug relates to a Mod
