### ISSUE TITLE
[Bug]: When bank is full, item is crafted but both it and its inputs are now gone.

### ISSUE THREAD

**Issue by Michael-Yongshi** [MelvorIdle/melvoridle.github.io#3613]
### Describe the bug

When inventory / bank is full, crafting an item is still possible, using up its inputs, but is never placed in the bank. ironically the objective of creating the item is still completed.

This actually breaks the tutorial as some inputs aren't available once you progress furher in the tutorial. In my case I already made headless arrows, tried to make bronze arrows when this happens. The bronze arrows never appeared, my headless arrows used up and the tutorial expects me to equip the arrows. As we now progressed in the tutorial, no new arrows can be bought, so no new headless arrows made and thus also not bronze arrows.

### Reproduction Steps

1. go to tutorial and fill up your bank with stuff, including headless arrows (more than needed) and bronze arrow tips (also more than needed).
2. progress to the step to create bronze arrows and start crafting bronze arrows
3. when completed the bronze arrows never arrive (bank is full), the tutorial progresses nonetheless and shop does not offer any new feathers anymore

### Expected behaviour

Crafting is never started until a free bank spot is freed up that the item can move to.

and

persist unlocking shop items that are needed for the tutorial until the tutorial is completely finished (you can also accidentally sell stuff) 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7764

### Are you using any mods?

Yes

**Comment by nightblade9** [comment]
Same issue here - got stuck in the tutorial crafting arrows because I ran out of inventory space.

Allowing the user to buy feathers after you need them, would make this less game-breaking.
