### ISSUE TITLE
Runecrafting Lesser Relic incorrect description

### ISSUE THREAD

**Issue by simondel** [MelvorIdle/melvoridle.github.io#3614]
### What text is wrong?

The description of the Runecrafting Lesser Relic item states that it helps to get additional resources in cooking. That sounds odd because it’s a Relic for Runecrafting

![IMG_0282](https://github.com/MelvorIdle/melvoridle.github.io/assets/4221997/330fa106-4efa-492e-a06b-2ee00b578db9)

### What is the correct spelling or grammar?

‘Runecrafting’

**Comment by MelvorIdle** [comment]
This is intended. Most Lesser Relics dropped from skills assist in other areas around the game. Runecrafting helps Cooking (When you eventually unlock it).
