### ISSUE TITLE
[Bug]: The game does not launch anymore on steam in steamdeck

### ISSUE THREAD

**Issue by Kris1309** [MelvorIdle/melvoridle.github.io#3615]
### Describe the bug

Whenever I start the game i gets stuck in the launching screen of steam.
I play on the steam deck with an external screen.
It also does not work in the desktop mode. (Then it acts like its launched and you can only press stop)
I tried the provided solutions of Steam.
This has been happening since 2 September.
I have the Throne DLC.
I have the music en archaeology modds.
I can still log in with my tablet, but thats not convenient. 

### Reproduction Steps

Press Play in Steam on the Steam deck.

### Expected behaviour

The screen is stuck on launching.
I can only abort.

### Screenshots

![Screenshot_20230909_223526](https://github.com/MelvorIdle/melvoridle.github.io/assets/144562444/bb4269a7-f727-4ca0-9b60-c2b5e704be0d)
****

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
So, we have no control over whether or not the game is available on the Steam Deck. We submitted the game for a re-review to Valve but they are yet to respond to this issue.

Also, I reside in Australia so we don't even have the Steam Deck available to purchase here. Its quite hard for us to test.

**Comment by Kris1309** [comment]
Oke, thnx for the feedback.
I will just wait then.

**Comment by Kris1309** [comment]
Got it to work by changing the compatibility tool to Steam Linux Runtime. Not perfect, but it works.
