### ISSUE TITLE
Quick Equip

### ISSUE THREAD

**Issue by IronGiant27** [MelvorIdle/melvoridle.github.io#3616]
### Describe the bug

The quick equip menu will not stay in place when trying to select items to equip. If I move the cursor over the gear wheel it will display, but when I move the cursor over to click on the various items the menu disappears.

### Reproduction Steps

1. move cursor to quick equip gear wheel
2. quick equip items appear directly to the left
3. move cursor to items
4. (issue) menu disappears when it should remain.

### Expected behaviour

menu should remain displayed to click on various items.

### Screenshots

I cannot, I need the cursor to take the screen shot but its also needed to display the menu.

### Console output

I am using the desktop client.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7694

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This issue was fixed a few patched ago. Forgot to close this issue
