### ISSUE TITLE
[Bug]: <title>loading offline progress

### ISSUE THREAD

**Issue by Shadow23091995** [MelvorIdle/melvoridle.github.io#3617]
### Describe the bug

as i load the game up and login to my account it gets stuck at loading your offline progress please wait.
i have tried to uninstall the game restart my phone multiple times to no avail, so because of this i was forced to request a refund from google play. this is not acceptable at all the game worked absolutely fine till i paid for the full version and expansion packs.
could this be caused from me using the free version of melvor and paid for the full version and both expansion packs yesterday but now it wont load my offline progress, not good at all i expect a full refund and will never play this game again. 
I have already wasted 3 hours of my time on trying to get it to work not happy at all! dreadful service

### Expected behaviour

I expected the game to work!

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

v1.2

### Are you using any mods?

Yes

**Comment by Shadow23091995** [comment]
very dissapointing

**Comment by MelvorIdle** [comment]
Based on the report, you are using Mods. There is a good chance you are using a Mod which attempts to perform calculations during offline progress. This can cause this issue. Please disable mods and confirm if you can load into the game.

**Comment by Shadow23091995** [comment]
how can i disable mods when the game wont load?

**Comment by OSwoboda** [comment]
> Based on the report, you are using Mods. There is a good chance you are using a Mod which attempts to perform calculations during offline progress. This can cause this issue. Please disable mods and confirm if you can load into the game.

But even if one uses mods shouldn't it be possible to finish the calculations eventually. I have the same problem. It also depends on how long I was offline. In the browser the calculations finish eventually, but not in the android beta. I have no problem with waiting, but if it never finishes because of some bug and that's what it sounds like that's pretty annoying and I have to use my PC again to load my game.
