### ISSUE TITLE
[Spelling/Grammar]: Mining Relic 1 incorrectly named as Mining Relic 5

### ISSUE THREAD

**Issue by Flokirie** [MelvorIdle/melvoridle.github.io#3618]
### What text is wrong?

Both Relic 1 and 5 are called "Mining Relic 5"
Pic:
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/141149203/37fb43fd-b04e-4956-9936-b46931fd05dd)

### What is the correct spelling or grammar?

Mining Relic 5 -> Mining Relic 1

**Comment by datcactus** [comment]
@MelvorIdle this is still present in 1.3?11455 with mods disabled.
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/107456394/f5d0d7e1-a5f9-4ce3-a60b-b2f555fcfc23)
