### ISSUE TITLE
Cartography hex mastery bonus not working[Bug]: <title>

### ISSUE THREAD

**Issue by Rappo01** [MelvorIdle/melvoridle.github.io#3621]
### Describe the bug

Cartography hex mastery bonus is not recognizing the total hexes fully surveyed. Per skill stats section, i have fully surveyed 120 hexes however the mastery on the Cartography area is not reflecting completion of 100 hexes.

### Expected behaviour

Hex mastery bonus should change from red to green and provide the described bonus.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/144607683/0a1cfe06-c064-4396-a204-48f20c6aa38d)

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/144607683/3081b59f-e556-44d8-965b-2dc8a5c16de5)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7764

### Are you using any mods?

No

**Comment by daria-mianne** [comment]
I'm having the same issue, with 124 traveled / 140 fully surveyed

**Comment by MelvorIdle** [comment]
A hex is only mastered when it reaches level 5. While initially surveying the map, only POIs can go to Level 5. When you survey the whole map, it will unlock the ability to survey all Hexes to Level 5.

We've got an update coming to the Hex Mastery popup explaining this system.
