### ISSUE TITLE
[Bug]: Cartography surveying map dragging lags behind and map get's revealed.

### ISSUE THREAD

**Issue by 123456687548** [MelvorIdle/melvoridle.github.io#3622]
### Describe the bug

Device used: IPhone X, iOS 15.4.1
While surveying is active the map get's partly revealed and dragging the map results in the map lagging like the old Windows window drag bug.

Dragging without surveying active doesn't result in the bug

### Reproduction Steps

1. Start game on mobile
2. Go to Cartography
3. Start Surveying
4. Drag map

### Expected behaviour

1. No map reveal
2. No dragging effect

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/KMtfDleA

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/9483513/5f9f12c4-1082-4f26-bb8c-7598b5c5aa36)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7764

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
We recommend using at least iOS 16 for Melvor Idle. Can you confirm if the issue is resolved when you update your device?

**Comment by 123456687548** [comment]
I updated to iOS 16.6.1 and that solved the issue, thanks
