### ISSUE TITLE
[Bug]: Superior comp cape, Superior max cape and Comp cape all do not recieve Carto bonus

### ISSUE THREAD

**Issue by Dohtt** [MelvorIdle/melvoridle.github.io#3627]
### Describe the bug

The only cap that currently integrates the 99 cartography bonus is the regular max cape.
I might've misunderstood, but i thought the other capes were meant to also integrate the 99's as we obtained them.

### Reproduction Steps

1. Get 99 Cartography
2. Check the map making interval
3. See it only goes down for the Carto cape or max cape, not the Comp cape, Superior max cape and Superior comp cape.

### Expected behaviour

The bonus might have to be added to all the capes?

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/17968897/1e8cdc9f-53ff-4169-aeb7-65fbb2228265)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7764

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This is now fixed as of Game Update v1.2 ?7809
