### ISSUE TITLE
[Bug]: Mining gloves not working in new Ancient Relics mode

### ISSUE THREAD

**Issue by beat-tick** [MelvorIdle/melvoridle.github.io#3628]
### Describe the bug

The mining gloves don't seem to work on Copper and Tin ore. 
They consume charges but only provide 1 ore. 
Can't check other ores since I only have lvl 10 mining

### Reproduction Steps

1. Equip mining gloves
2. Start mining
3. Loot 1x ore

### Expected behaviour

Expecting 2x ore when mining 

### Screenshots

![Screenshot 2023-09-11 111407](https://github.com/MelvorIdle/melvoridle.github.io/assets/76086744/1928304b-ef61-464f-b612-c1c7b508b4c8)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7764

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Ancient relics mode disables all doubling.
