### ISSUE TITLE
[Bug]: Gem gloves not working on crystal ore

### ISSUE THREAD

**Issue by t1rantt** [MelvorIdle/melvoridle.github.io#3629]
### Describe the bug

Gem gloves not working on crystal ore

### Screenshots

![bug](https://github.com/MelvorIdle/melvoridle.github.io/assets/33431926/bd45ec5f-a70c-4e92-bef7-a875473081f8)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7764

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This is now fixed as of Game Update v1.2 ?7809
