### ISSUE TITLE
Cartography mastery bonus

### ISSUE THREAD

**Issue by MartinG1997** [MelvorIdle/melvoridle.github.io#3631]
### Describe the bug

I am uploading cartography, I must have explored more or less 40% of the map, but I have not received the first mastery bonus and neither the following ones.

### Screenshots

![cartografia](https://github.com/MelvorIdle/melvoridle.github.io/assets/18308488/b628f7ad-76de-4651-ac48-808bcaf90666)

I am uploading cartography, I must have explored more or less 40% of the map, but I have not received the first mastery bonus and neither the following ones.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7764

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
We have released an update today which adds extra information to the popup menu which explains how the Hex Mastery system works.
