### ISSUE TITLE
[Bug]: Various Perfect foods unable to be downgraded

### ISSUE THREAD

**Issue by D-Scaduto** [MelvorIdle/melvoridle.github.io#3632]
### Describe the bug

As title states, compared to other foods, perfect carrot cake doesn't have an option to be downgraded.

### Reproduction Steps

None

### Expected behaviour

carrot cake (Perfect) downgraded to regular carrot cake

### Screenshots

![Capture](https://github.com/MelvorIdle/melvoridle.github.io/assets/4481192/c40aaa3d-725e-4775-a049-65777c1dd852)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7764

### Are you using any mods?

Yes

**Comment by D-Scaduto** [comment]
linking related issue that is closed 
https://github.com/MelvorIdle/melvoridle.github.io/issues/2684

**Comment by MelvorIdle** [comment]
This is now fixed as of Game Update v1.2 ?7809
