### ISSUE TITLE
[Bug]: Ancient Relics - Impending Darkness

### ISSUE THREAD

**Issue by Bladekill990** [MelvorIdle/melvoridle.github.io#3634]
### Describe the bug

After clearing the Impending Darkness event on the new Ancient Relic gamemode, cooking and fishing stay locked, and the level cap on combat stats isn't raised.

Mods were used to speed up progress before the event, but disabled for the entire event.

### Reproduction Steps

1. Clear all dungeons before Impending Darkness
2. (possibly) have the Solar Eclipse running from township relic
3. (possibly) be on the Perilous Peaks cartography space
4. Clear impending darkness
5. Get the pet and book, but nothing else

### Expected behaviour

Level cap on at least Slayer should be raised to 100 (for next dungeon access), and Fishing and Cooking should be unlocked.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/R0DtCkIu

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/37010357/dc3548b9-0a00-4d66-886c-301c497d9c96)

### Console output

"AssignedEventIds": [
            "336e77bbcea744289ebe1f376718f664",
            "282accdb93344412938c473750c1b50b",
            "5fcb0dea911e483ba5d17c71baa858b9",
            "2a4618a6b546480eb32e3e5f65305558"
]

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7785

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This has now been hotfixed. Thanks for the report.

Please send me your save for a manual fix if you already completed it.
