### ISSUE TITLE
[Bug]: Ancient Relics, Gem Gloves and Lesser Mining Relic

### ISSUE THREAD

**Issue by ChrisMenne** [MelvorIdle/melvoridle.github.io#3636]
### Describe the bug

Lesser Mining relic and gem gloves both give a gem per mining action but when both are equipped they only give one gem instead of two they should be giving.

### Reproduction Steps

1. Equip gem gloves and lesser mining relic 
2. mine something other than rune essence (or crystal it seems).

### Expected behaviour

Get two random gems instead of only one according to the text of both equippables

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7794

### Are you using any mods?

No

**Comment by Allemweich** [comment]
I have the same issue.
V1.2 (?7794)
