### ISSUE TITLE
[Bug]: Archeology does not consume mastery magnets

### ISSUE THREAD

**Issue by Jovasa** [MelvorIdle/melvoridle.github.io#3637]
### Describe the bug

Archeology seems to be benefiting from mastery magnets, however training archeology does not consume them.

### Reproduction Steps

1. Equip mastery magnets
2. Start training archeology

### Expected behaviour

Mastery magnets are consumed while training archeology.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7794

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This has now been fixed as of Game Update - v1.2 ?7841
