### ISSUE TITLE
[Bug]: Rarity of Artefacts mixed up? Monuments Medium Artefacts

### ISSUE THREAD

**Issue by bonzei123** [MelvorIdle/melvoridle.github.io#3641]
### Describe the bug

Is the rarity of "Broken Brush" and "Aranite Brush" mixed up?
Statistically without upgrades one would take more than 24h of nonstop Excavating for 25 Aranite Brushes which seems for a more or less lowlevel upgrade exceedingly high

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7794

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This is intended and not a bug
