### ISSUE TITLE
[Bug]: Cartography refinements update not automatically

### ISSUE THREAD

**Issue by bonzei123** [MelvorIdle/melvoridle.github.io#3644]
### Describe the bug

After refinging a map for a certain sized Artefact the displayed percentage value for that tool will only change to the new higher value if the tool is deactivated and activated again.

Don't know if the bug is only visual, the differences in values are to small to check empirically

Problem occures in Browser (Fiorefox) as well as on the Android App

### Reproduction Steps

1. In Archaeology activate medium tool on a map for eg. -> Value says something like 11.250%
2. in Cartography refine the map and choose the "-5 on medium" for that map from step 1
3. Back under Archaeology the value with the medium and said map will still be displayed as 11.250%
4. deactivate and activate the medium tool again and the value is now 11.842%

### Expected behaviour

Value should update automatically even if the tool is already activated

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7794

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This is now fixed as of Game Update v1.2 ?7809
