### ISSUE TITLE
[Bug]: Unexpected Behaviour Autosurvey

### ISSUE THREAD

**Issue by EOBG** [MelvorIdle/melvoridle.github.io#3645]
### Describe the bug

I did some surveying over night with the game closed and came back to still undiscovered Hexes right next to my location, while new locations much further out got revealed.

On a sidenote: Not sure if intended behaviour, is it intended you can only queue up Hexes directly adjacent to your location when manually surveying? I would've liked to go at least 2 squares out.

### Reproduction Steps

It looks like autosurvey goes further out as soon as it encounters an already discovered Hex and does not check if all nearby Hexes were already surveyed (see 2nd screenshot)

### Expected behaviour

If I understand correctly, autosurvey should survey all hexes around your location, starting with the closest first and moving further out. 

### Screenshots

![grafik](https://github.com/MelvorIdle/melvoridle.github.io/assets/4649721/99a0534e-c1a5-4892-b64f-703be2c4051b)
![grafik](https://github.com/MelvorIdle/melvoridle.github.io/assets/4649721/60392ea6-03d8-4158-8eff-8c20f4a18ad3)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7796

### Are you using any mods?

No

**Comment by EOBG** [comment]
The Hex to the bottom left of my location might have already been revealed. Not 100% sure about that one.

**Comment by lupusagax** [comment]
Can reproduce on Web v1.2.2?8287

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/14250227/f90ebf7f-bc61-4da2-a9a9-09893b600983)
