### ISSUE TITLE
[Bug]: <title>Tortoise is required to unlock Mark

### ISSUE THREAD

**Issue by Flurryous** [MelvorIdle/melvoridle.github.io#3646]
### Describe the bug

As title, since the latest dlc dropped, it seems that the Mark pet is no longer obtainable by getting all base game marks to level 4. In the game's code, it checks for marks below 100, which becomes a problem because the new dlc summon Tortoise is a level 70 mark. So far I've seen one person run into this problem, but they have all the dlcs, so I'm not completely certain this affects anyone who only owns the base game. Since this seems to be a problem with how obtaining Mark is coded, I believe this would affect all platforms. 

### Reproduction Steps

1. Get all base game marks to max level.
2. Expect Mark to be unlocked, but nothing happens.

### Expected behaviour

I expect Mark to be unlocked immediately after hitting level 4 on all base game marks. 

### Screenshots

https://cdn.discordapp.com/attachments/625841473731952688/1151653072007860296/image.png

Credits to Slash for the code screenshot. This shows that the game checks for all summoning marks below 100 before rolling Mark, which would include Tortoise. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [x] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7796

### Are you using any mods?

No

**Comment by Kr4pper** [comment]
@Flurryous This was fixed in yesterday's patch https://www.reddit.com/r/MelvorIdle/comments/16i8n39/game_update_v12_7809/

> Fixed issue where Mark, the Summoning Pet, would require the new Atlas of Discovery familiar marks to be located to unlock (Pet should only require base game Marks).

**Comment by Flurryous** [comment]
Resolved.
