### ISSUE TITLE
Summoning relic stopped randomly

### ISSUE THREAD

**Issue by Propheski** [MelvorIdle/melvoridle.github.io#3648]
### Describe the bug

Summoning Relic 5 was working... stopped working when I purchased green summoning shards

### Expected behaviour

Tin ore should be at 35 not 50

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/144969009/b02068a9-1415-405e-882a-cd9cdaeb3b3a)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/144969009/ef94d27e-b4da-429e-b431-e4f760c3dc2d)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

V1.2(?7796)

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Can you please provide a copy of your save?

**Comment by KoyoteKyle** [comment]
I am also having this issue. Except mine never worked.
Here is a copy of my save if it helps any.
[https://melvoridle.com/save/agQfkINh]

**Comment by datcactus** [comment]
@MelvorIdle Noticed this today as well when I unlocked the relic upon hitting 99 Summoning. Would be great to have the relic work as intended especially since relic mode already lacks preservation/doubling. Save link: https://melvoridle.com/save/LuWkYqn4
