### ISSUE TITLE
[Bug]: Runecrafting Lesser Relic gets used in Combat

### ISSUE THREAD

**Issue by EOBG** [MelvorIdle/melvoridle.github.io#3653]
### Describe the bug

The Runecrafting Lesser Relic gets consumed with each Combat action when equiped despite not granting any combat bonus.

### Reproduction Steps

1. Equip Lesser Relic
2. Fight

### Expected behaviour

I'd expect it not to be consumed, similar to when you do a non-combat skill while having a lesser relic equiped that doesnt provide a bonus to that skill.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7810

### Are you using any mods?

Yes

**Comment by EOBG** [comment]
Correction: I'm not using any mods.

**Comment by MelvorIdle** [comment]
This has now been fixed as of Game Update - v1.2 ?7841
