### ISSUE TITLE
[Bug]: <Ancient Whetstone consumes charges when player is damaged>

### ISSUE THREAD

**Issue by dizzledaz** [MelvorIdle/melvoridle.github.io#3654]
### Describe the bug

Ancient Whetstones use up charges both when the player attacks and is attacked.

### Reproduction Steps

1 - Equip Ancient Whetstone
2 - Fight an enemy with different attack interval

### Expected behaviour

The other two Whetstones only consume charges when the player attacks, not when they receive damage. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7810

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This has now been fixed as of Game Update - v1.2 ?7841
