### ISSUE TITLE
[Bug]: Prayer Relic 2 displayed value incorrect

### ISSUE THREAD

**Issue by Kr4pper** [MelvorIdle/melvoridle.github.io#3658]
### Describe the bug

![grafik](https://github.com/MelvorIdle/melvoridle.github.io/assets/20116607/3bd23423-87f6-4492-aed2-2644140c0e0e)

Player relic 2 displays a prayer point gain rate of 0.25% of dmg taken, equating to 1 prayer point gained per 400 dmg taken. However both the behavior observable in game as well as the value contained in the modifier "increasedDamageTakenAddedAsPrayerPoints" suggest a gain rate of 2.5%. This appears to be a visual display issue inside the relic menu.

### Reproduction Steps

1. Unlock Prayer Relic 2
2. Observe current prayer points (value A)
3. Take at least 40 dmg in a single hit in combat
4. Observe prayer points again (greater than value A)

### Expected behaviour

Player relic 2 displays a prayer point gain rate of 2.5%

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7810

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.1
