### ISSUE TITLE
[Bug]: <title>Several upgraded items seem to be downgrades

### ISSUE THREAD

**Issue by Flurryous** [MelvorIdle/melvoridle.github.io#3659]
### Describe the bug

There seems to be a mixup between the stats of the Unholy Staff and Cursed Staff. Cursed Staff is the upgraded version of the Unholy Staff but all of its stats are lower than that of Unholy Staff's. In a similar manner, according to their descriptions, it seems that all of the (B) equipment lose their % chance to dodge Crystallization in exchange for a 1% chance to apply Crystallization when upgraded to their (C) counterpart. 

Edit: From their descriptions, Crystal Helmet seems to downgrade from 20% chance to dodge Crystallization to 15% chance to dodge Crystallization when upgraded to (S). The other base crystal armors start out at 5%, so Crystal Helmet should actually be 5% instead of 20%.
(S) Pure Crystal Body also seems to lose 50 defense and 48 ranged defense when upgrading to (G). I'm not sure if this is intentional since the platebody does gain some other stats, but other armor upgrades don't see such a steep drop in defense. 

While I'm at it, there are also quite a few items that lose certain stats upon upgrading, but I'm not quite sure if it's worth pointing out since the loss is quite minor compared to the gain. 

### Expected behaviour
I expect the upgraded items to be upgrades to their original versions, or at least to retain the gimmick that makes them valued (crystallization dodging). 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7815

### Are you using any mods?

Yes

**Comment by Flurryous** [comment]
Several reddit posts by other players have pointed out these oversights, but I thought I should post them here.

**Comment by MelvorIdle** [comment]
This has now been fixed as of Game Update - v1.2 ?7841
