### ISSUE TITLE
[Bug]: Cartography map puts heavy load on cpu

### ISSUE THREAD

**Issue by braron-droid** [MelvorIdle/melvoridle.github.io#3660]
### Describe the bug

When opening the cartography map Cpu goes to 98-100% load. When surveying having the game tab in focus cpu goes to 100% load even when looking at another skill.

### Reproduction Steps

1. Go to Cartography skill/surveying
2. Cpu load increases to 100%

### Expected behaviour

Cpu staying roughly the same as before.

### Screenshots

![Cartography](https://github.com/MelvorIdle/melvoridle.github.io/assets/78756699/1bd9112e-75aa-4ffb-bd5c-c8a57d82e57c)

### Console output

index_game.php:52     GET https://melvoridle.com/style.css?2 net::ERR_ABORTED 404
index_game.php:3500     GET https://static.cloudflareinsights.com/beacon.min.js/v8b253dfea2ab4077af8c6f58422dfbfd1689876627854 net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for https://melvoridle.com/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/basis.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
cloudManager.js?7815:236 Silent Sign in with JWT
cloudManager.js?7815:236 Validating Melvor Cloud token
cloudManager.js?7815:236 Storing Melvor Cloud Token
cloudManager.js?7815:236 Initializing PlayFab login. Method: customID
cloudManager.js?7815:236 Logging in with Custom ID via PlayFab
cloudManager.js?7815:236 Login with custom ID success
cloudManager.js?7815:236 Getting account info
cloudManager.js?7815:236 Account info retrieved
cloudManager.js?7815:236 Authenticated w/ Melvor Cloud: true
cloudManager.js?7815:236 Authenticated w/ PlayFab: true
cloudManager.js?7815:236 Checking for valid full version
cloudManager.js?7815:236 Checking for valid TotH purchase
cloudManager.js?7815:236 Checking for valid Atlas of Discovery purchase
cloudManager.js?7815:236 Loading Game Data...
cloudManager.js?7815:75 Registered Demo Data.
cloudManager.js?7815:75 Registered Full Version Data.
cloudManager.js?7815:76 Registered Throne of the Herald Data.
cloudManager.js?7815:77 Registered Atlas of Discovery Data.
cloudManager.js?7815:236 Initializing Mod Manager...
cloudManager.js?7815:236 Loading Local Saves...
cloudManager.js?7815:236 Loading Cloud Saves...
cloudManager.js?7815:236 Getting saves from playfab
cloudManager.js?7815:236 Saves retrieved
characterSelect.js?7815:5 Loading character selection
cloudManager.js?7815:372 Connected to PlayFab successfully
main.js?7815:18 Game Loaded
cloudManager.js?7815:372 Connected to PlayFab successfully
cloud.js?7815:102 updatePlayerTags
cloudManager.js?7815:236

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7815

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Please enable Hardware Acceleration in the Chrome settings as Cartography needs to utilize your GPU.
