### ISSUE TITLE
[Bug]: High GPU usage when on the map screen in Cartography

### ISSUE THREAD

**Issue by oauo** [MelvorIdle/melvoridle.github.io#3662]
### Describe the bug

I have a GTX 980 and cartography uses a 30-40% of my GPU, vs for instance in the shop where it uses 4-6% (which is still higher than I would expect)

I'm currently playing cartography with the game closed most of the time because my GPU's fans start spinning up when playing it

Sidenote, filling out this form and being asked for the subversion the image makes it look like it's going to be at the top of the sidebar but since that screenshot was taken it's now at the bottom

### Reproduction Steps

1. Use an old but otherwise decent GPU
2. Go to cartography
3. Look at nwjs

### Expected behaviour

I would expect the GPU usage to be much much lower as I'd expect that it would just be an image with a mask and text on top.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/46975001/055f53b4-7ac2-4842-8589-a826b57a0190)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7836

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Cartography utilises a library called Pixi.js to handle rendering, which in turn uses WebGL and therefore needs resources from your GPU.

Cartography does look like "just an image", but we're dealing with a lot of different variables that require the GPU to do some work.

We're looking into ways of optimising this further and will keep hotfixing where needed.

In the mean time, you can take a look at some of the Settings to reduce the map quality, adjust FPS/refresh rate of the Map etc.

**Comment by oauo** [comment]
That's far more manageable, it's down to 10% active, 1.5% inactive
