### ISSUE TITLE
[Bug]: Ancient Relics - Earth God Clear Awards No Skills

### ISSUE THREAD

**Issue by AshenMask** [MelvorIdle/melvoridle.github.io#3663]
### Describe the bug

Cleared Earth God for the first time - no skills were awarded after dungeon completion, despite the confirmation of completion. There are no skills to claim under the bank tank/shop. Completions until next skills shows as 0. I have never modded the game.

### Expected behaviour

Skills to be awarded on completion.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/kjI3ug4S

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7836

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Do you by chance hold down enter to eat while defeating dungeons? This information will help me source the bug.

**Comment by AshenMask** [comment]
I had done for the Air God Dungeon but saw that it auto-selected the first skill choice. As a result I was careful not to to hold for the following dungeons - I'm 99.5% my skills didn't increase after the dungeon.
