### ISSUE TITLE
[Bug]: Incorrect image for Unholy Potions

### ISSUE THREAD

**Issue by Southier9** [MelvorIdle/melvoridle.github.io#3664]
### Describe the bug

All 4 tiers of Unholy Potions are using Unholy Potion I image,

### Expected behaviour

Each tier show it's own image

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/36991161/75d06b50-4550-464e-aa22-fdc6a73676c8)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7836

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This has now been fixed as of Game Update - v1.2 ?7841
