### ISSUE TITLE
[Bug]: Centaur Tablets require wrong number of redwood bows

### ISSUE THREAD

**Issue by LeHvass** [MelvorIdle/melvoridle.github.io#3667]
### Describe the bug

It seems like the Centaur summoning tablets currently require an incorrect number of Redwood short- & longbows.

### Reproduction Steps

1. Go to Summoning
2. Choose Centaur tablets
3. Observe cost using redwood short- & longbows

### Expected behaviour

I would expect them to cost 1, since redwood logs are a higher level resource than magic logs, and require a higher fletching level.

### Screenshots

<img width="256" alt="Screenshot 2023-09-17 at 06 18 21" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/5744255/78a1e39a-8e5c-47dd-83f4-eb8b596ecfb8">

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7836

### Are you using any mods?

Yes

**Comment by ekuland** [comment]
The cost is determined by GP value. Magic is worth more.

**Comment by LeHvass** [comment]
@ekuland, interesting. Perhaps the question then should be why Redwood logs and Redwood bows are worth less than their Maple equivalents, given the higher requirements.

**Comment by MelvorIdle** [comment]
Redwood Logs are classed as "High XP/Low GP". They're the fasted XP in the base game for Woodcutting as you acquire many logs with ease. The trade off is the low sale cost of them, which in turn flow to Redwood items.
