### ISSUE TITLE
[Bug]: <title>Aranite Shield and Crystallization Potion only give 1 exp

### ISSUE THREAD

**Issue by Flurryous** [MelvorIdle/melvoridle.github.io#3668]
### Describe the bug

Title. Like most of the crystal fletching items, Aranite Shield  and Crystallization Potion only give 1 exp for their respective skills upon creation. 

### Reproduction Steps

1. Go to the smithing page.
2. Select Special items, then Aranite Shield
3. The UI display shows that it only grants 1 smithing exp. 
4. Repeat for Crystallization Potion in the herblore page, under Combat Potions. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7836

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This has now been fixed as of Game Update - v1.2 ?7841
