### ISSUE TITLE
[Bug]: External wiki link in skill's Game Guides opening red njws browser

### ISSUE THREAD

**Issue by Sam-318** [MelvorIdle/melvoridle.github.io#3669]
### Describe the bug

When clicking any extrernal wiki links shown after pressing the Game Guide button on any skill, the wiki tab will open a new browser called njws with a red square logo. This unknown browser application is not on my computer and doesn't show up in task manager, but closing melvor does close the browser. The "njws" browser has no search capabilites other than the melvor wiki, no dark mode, no multiple tabs and no back button. Any other external wiki link buttons in the game (such as the ones on items in bank) open the links through Firefox (my default browser) with no issues. 

### Reproduction Steps

Click any skill:
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/66730151/8e0bab2b-7f23-4d96-8d18-e57760520d15)

Click game guide at the top of the screen under the skill name:
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/66730151/aa46e43d-b26e-4ef5-8527-8605912d1c0c)

Click any external wiki link shown in the window:
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/66730151/c1a986bb-882e-4f12-87e8-986526af5f04)

The unkown browser will then open with the wiki:
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/66730151/90f81631-99af-447e-b80e-4f51e45b0fbc)

### Expected behaviour

Pressing any external wiki link button in the game guide section should instead open though the players default browser, this is what happens when opening links on specific items in bank.

### Screenshots

This is what the browser looks like in my taskbar (windows 10) :
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/66730151/41ecce4e-2b03-4bfa-8cbe-6feedfefa73b)

This is how the browser opens on my screen after clicking the combat game guide external wiki link (Melvor Idle is open behind the smaller window):
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/66730151/d08b38be-e1a2-4864-867e-be39e003e156)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7836

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This has now been fixed as of Game Update - v1.2 ?7841
