### ISSUE TITLE
Woodcutting double-log drop do not award 2 mastery progress for that log type

### ISSUE THREAD

**Issue by Discipol** [MelvorIdle/melvoridle.github.io#367]
**Describe the bug**
I have been fishing and double-fish / even quad-fish always increase that fish's mastery by the same amount of points. It makes sense to me as I go closer to 99 that there's a helping mechanic to compensate for huge waiting times, with a little bit of assistance.

**To Reproduce**
1. Go to Woodcutting
2. Click on any tree type with enough mastery to % proc extra logs
4. See when you get double logs, it only counts as +1 to mastery

**Expected behavior**
If I get 2 logs, I get 2 mastery. If I get 4 logs, I get 4 mastery, etc.

**Browser**
PC, Chrome, latest

**Are you using any scripts?**
SEMI

**Comment by MelvorIdle** [comment]
This is intended. Woodcutting is only 1 xp per action regardless of item Qty
