### ISSUE TITLE
[Bug]: Archaeology dig-site showing as undiscovered when Cartography is completed.

### ISSUE THREAD

**Issue by TechWarren** [MelvorIdle/melvoridle.github.io#3670]
### Describe the bug

I have the entire Cartography map finished and multiple Archaeology dig-sites are still saying undiscovered. Level 32, level 75, level 90, level 110, and level 118 are all doing the same thing in Archaeology despite 100% cartography.

### Reproduction Steps

No clue, I just did an auto survey of the entire map for the most part. 

### Expected behaviour

Expected behavior is to have all dig-sites unlocked once Cartography is complete. I verified with other links that the coordinates in the screenshot should be discovered as a dig-site. 

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/32377802/c1dcfa6c-54ef-453e-8113-8562124b1f63)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/32377802/1e43b671-4c1c-46ee-88d4-b33f29daf9a7)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7841

### Are you using any mods?

No

**Comment by TechWarren** [comment]
Second screenshot has a item use mod but removed to test. Removed the mod and still occurs.

**Comment by SILENT-MK** [comment]
You probably never travel to this coords

**Comment by TechWarren** [comment]
I have traveled to every bugged location lol. Nothing changed unfortunately

**Comment by SILENT-MK** [comment]
Maybe you didn't find in Archaeology large artifact for Bazaar - City Chart, Large (Very Rare) from Ancient Market. Some of digsite you have to unlock through Archaeology first to digsite appears.

**Comment by TechWarren** [comment]
Ah okay interesting. That must be it then because I haven’t done much
actual archaeology itself. Maybe the requirements for the five I have
listed as a “bug” should also have their additional requirements listed?
Just food for thought ;-)
