### ISSUE TITLE
[Bug]: iOS app crash/logout with AoD update

### ISSUE THREAD

**Issue by vvp000** [MelvorIdle/melvoridle.github.io#3671]
### Describe the bug

On the day before AoD came live, there was a balance patch pushed into the iOS game client. After this update, I started experiencing crashes (they persisted after purchasing/unlocking AoD as well).
The game's screen turns white, and it logs the player out to the main menu. It is possible to resume the play without losing progress (unless the player was doing a manual boss battle). Sometimes, the menu graphics glitch out after this crash. It appears that the save is intact after this.

### Reproduction Steps

I cannot seem to find any reliable way to trigger the issue, but it always eventually happens (a few times a day when actively interacting with the game). It can occur during:
- Skilling
- Fighting
- Switching between skills and menus
- Opening the app after not interacting with it for a while
- Looking at the same in-game menu for too long

I tried changing some of the Cartography settings, and it seems that various interactions with these settings can prolong the time period between crashes, but I cannot find a reliable combination of settings and do not have good statistics to confirm if changing anything in Cartography actually has any effect.

### Expected behaviour

The expected behavior is to not have spontaneous logouts/crashes.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7841

### Are you using any mods?

No

**Comment by rhinotastic** [comment]
same issue. pretty annoying really. just have to leave the game open in any of the screens, bank, any of the skills or crafting sections etc and it will eventually happen.
