### ISSUE TITLE
[Bug]: Steam MacOS client is buggy due to the low version on NW.js

### ISSUE THREAD

**Issue by youyinnn** [MelvorIdle/melvoridle.github.io#3672]
### Describe the bug

Low version NW.js means low version chromedriver, therefore leading to mods failures.

For instance, the Adventuring Mod

<img width="1345" alt="image" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/23525754/0849f05a-7967-48fb-90ae-b14dd9b744fc">

### Reproduction Steps

Bugs exist. The following shows how to identify them. Basically, it is to enable the DevTools.

1. Locate the steam client. Open the content of the app, and you will see the version of that is 86.0.4240.111:
    <img width="350" alt="image" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/23525754/31c472fd-4f27-460d-8890-86c3dd751e97">

2. Download the SDK. Based on your build for Linux, we download the version: https://dl.nwjs.io/v0.49.2/.
    Open the content of `nwjs.app` and gets:
    <img width="366" alt="image" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/23525754/40e5af22-1546-4ab8-a20a-2a2c5f47c696">

3. Replace all files under the folder `nwjs Framework.framework` of the steam client with the one from sdk's.
4. Open the game and toggle the DevTools. Then, you will see a bunch of bugs.
    <img width="417" alt="image" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/23525754/aaee510f-b54c-4eda-93d1-ec6f994d59f4">

5. Version check (look, man, this is tooooo old...):
    ``` bash
    navigator.userAgent
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36"
    ```

### Expected behaviour

This is what it is like in Chrome 117. And the Adventuring is working.

<img width="777" alt="image" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/23525754/ffe15e4c-4d72-4cf1-a56e-7846830b6236">

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7841

### Are you using any mods?

Yes

**Comment by youyinnn** [comment]
From my understanding, upgrading the nwjs version to the latest one should be easy (though I have never used it before...), which fixed all of those bugs.

And~~~~!!!!!

**If you could, please use the ARM version of nwjs.**

**Comment by MelvorIdle** [comment]
Updating NW.js on Mac is on our radar, but the codesigning process is beyond painful (Needs to be signed properly otherwise latest versions of MacOS won't let you run it at all)

**Comment by youyinnn** [comment]
Sure. I am looking forward to it.
