### ISSUE TITLE
[Bug]: Sandstorm ring doesn't show tooltip

### ISSUE THREAD

**Issue by thomastdh** [MelvorIdle/melvoridle.github.io#3673]
### Describe the bug

When hovering over the sandstorm ring it doesn't show its effect, while any other ring i have or item, it does. 
Intended or not?

Using Opera

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/63539718/989740a0-e582-4ed6-84b5-c2ac66064e0a)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/63539718/ed1ea10e-6e4a-4946-b47a-7f254f17d7c1)

### Reproduction Steps

Equipe a sandstorm ring.

### Expected behaviour

Show the tooltip for the ring. It only shows in the bank.

### Screenshots

in bug discription

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7841

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.1
