### ISSUE TITLE
[Bug]: Astrology Study Stops on Full Bank

### ISSUE THREAD

**Issue by stevenjackson121** [MelvorIdle/melvoridle.github.io#3675]
### Describe the bug

Identical to https://github.com/MelvorIdle/melvoridle.github.io/issues/2023, but present in current game.

### Reproduction Steps

1. Sell Astrology Resources (Dust)
2. Get any other resources to fill the bank (mining, runecrafting, smithing, chopping, etc.)
3. Begin Studying Astrology
4. Astrology Stops intermittently, whenever a drop would be added to the full bank.

### Expected behaviour

Astrology continues despite being unable to add resources to bank

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/30Ojk8iJ

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7841

### Are you using any mods?

Yes

**Comment by 04Slash** [comment]
From what I can gather, you have the 'Toggle Ignore Bank Full' setting disabled. If you wish for actions to continue when your bank is full, enable this setting.

**Comment by stevenjackson121** [comment]
Sorry for the false report. The search terms I used found me the Github issue but not the settings :/

Thank you for the instructions on how to fix it!
