### ISSUE TITLE
[Bug]: Digsite hex and normal hex have initial survey level switched (spoiler for digsite location)

### ISSUE THREAD

**Issue by martijnvaneeghem** [MelvorIdle/melvoridle.github.io#3676]
### Describe the bug

The two hexes with the coordinates/coords (24,14) and (24,15) are respectively a digsite hex and a normal/empty hex. The digsite has an initial survey level of 2, while the normal/empty hex has an intitial survey level of 5.

### Reproduction Steps

Go to the Cartography skill.
Explore the map towards coordinates (24,14) and (24,15).
See that the digsite has an initial survey level of 2, while the normal/empty hex has an intitial survey level of 5.

### Expected behaviour

According to the in-game Cartography Mastery Menu, the initial survey level of the digsite hex should be 5, and the initial survey level of a normal/empty hex should be 2. Starting zone excluded.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/30408660/e066ed9c-78e7-4075-a0a4-584603ead58f)

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/30408660/0b6c5ea0-e051-4e5a-802c-f35e298496cb)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7841

### Are you using any mods?

Yes

**Comment by BenLubar** [comment]
in ?7937, I'm getting this:
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/4257305/ff003bc1-7944-4db6-95da-7568967787fa)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/4257305/65a4889b-780a-4bcb-956b-403b2744bc56)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/4257305/ef7795e7-238f-49f1-8519-f74a8dd3726a)

**Comment by BenLubar** [comment]
still occurring on ?7937
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/4257305/dbfffae7-2c7a-4c8b-838b-113c453f6022)

**Comment by AaronSzaboo** [comment]
Still occuring on ?8452
