### ISSUE TITLE
[Bug]: Lesser Astrology Relic does not perform its prayer reduction effect

### ISSUE THREAD

**Issue by supersting** [MelvorIdle/melvoridle.github.io#3677]
### Describe the bug

With Astrology Lesser Relic equipped in the consumable slot, activating thick skin and initiating combat causes both prayer points and consumable count to go down.
Might be capped at minimum 1 point spend, but that's not stated.

### Reproduction Steps

1. Start a new Ancient Relics run
2. Give yourself 1000 lesser astrology relics and 1000 prayer points
3. Activate Thick Skin prayer and Equip relic
4. Fight a monster, watch prayer points deplete.

### Expected behaviour

No prayer points consumed, only relics.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7841

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Prayer points are capped at 1 minimum spend. We'll get some information displayed to depict this scenario.
