### ISSUE TITLE
[Bug]: Township Repair Glitch after buying dlc

### ISSUE THREAD

**Issue by kjbye5252** [MelvorIdle/melvoridle.github.io#3678]
### Describe the bug

I had a maxed out township before downloading both dlc. Now specifically the Clothiers Estate and Large Academy are stuck at repair 100% with a repair button instead of a buy button. When I click the repair button it does nothing besides subtract 1gp. They will not go below 100% repair and I can't but them.

### Reproduction Steps

1. Have maxed township without dlc
2. Download dlc
3. Check if all building can be repaired

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/DoXKpil0

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/37642604/4e11ae64-c243-46c8-8589-29358397ef8d)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7841

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This is now fixed as of [Game Update - v1.2 ?7889](https://www.reddit.com/r/MelvorIdle/comments/16o3no7/game_update_v12_7889/)
