### ISSUE TITLE
[Bug]: Cartography Skillcape not working.

### ISSUE THREAD

**Issue by Lumpytoad** [MelvorIdle/melvoridle.github.io#3679]
### Describe the bug

The Cartography Skill cape (lvl 99), when equipped, is *not* decreasing map upgrade interval by -20% as described.

To be clear, the cape is not decreasing the interval in any way. There is no change to map upgrade interval what-so-ever.

### Expected behaviour

I expected map upgrade action to be faster when having the Cartography Skillcape equipped.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7841

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
I can't seen to reproduce this bug. Do you have any further information? Here is what I see:

Showing no cape equipped: https://i.golb.ink/u/nFT7K2.png
Showing interval with no cape: https://i.golb.ink/u/jZNPoY.png

Showing 99 cape is now equipped: https://i.golb.ink/u/Mi0bK9.png
Showing reduced interval from the cape is working as intended: https://i.golb.ink/u/MOblam.png

**Comment by Avallach160** [comment]
I think it's an interaction with Old Spyglass and some values aren't updating without restarting the game.
Fresh start:
No cape, no spyglass: 4.15s.
Equip spyglass, no cape: 3.65s
Add on the cape: 2.65s
Remove cape: stays at 2.65s
Remove spyglass: goes to 3.15s
From this point equipping either one doesn't affect the duration.

Save attached
[melvoridlesave_Avallach_9-21-2023_62304AM.txt](https://github.com/MelvorIdle/melvoridle.github.io/files/12685051/melvoridlesave_Avallach_9-21-2023_62304AM.txt)

**Comment by MelvorIdle** [comment]
Hmm, odd. I followed your steps exactly and still can't reproduce the bug. When I removed my cape, the interval correctly changed back to the intended 3.65s. Any order of equipping/unequipping those items works as intended for me.

I used both the Max Cape and Superior Cape of Completion for this testing.

There might be some hidden variable we aren't noticing which is causing this

**Comment by roodwarrior** [comment]
My experience is roughly the same. It seems that if you equip the skillcape and the spyglass in no particular order, they will be applied.  And if you remove them the times will go back up.

However, I've done some troubleshooting and it seems that if you have the Cartography Skillcape and the Spyglass equipped and you use the quick equip menu to equip the (in my case) Superior Cape of Completion, the time does not go back up and you get the bonuses from the CoC as well, _e.g._ I see the XP go up.
