### ISSUE TITLE
[Spelling/Grammar]: Crystal Battlestaff description typo

### ISSUE THREAD

**Issue by Kr4pper** [MelvorIdle/melvoridle.github.io#3681]
### What text is wrong?

![grafik](https://github.com/MelvorIdle/melvoridle.github.io/assets/20116607/26f7393e-129c-4386-b020-bbcaaedfcbcc)

On a hit there is a 3% chance apply Crystallization for 1 Attack Turn

### What is the correct spelling or grammar?

On a hit there is a 3% chance *to* apply Crystallization for 1 Attack Turn

**Comment by MelvorIdle** [comment]
This is now fixed as of [Game Update - v1.2 ?7889](https://www.reddit.com/r/MelvorIdle/comments/16o3no7/game_update_v12_7889/)
