### ISSUE TITLE
[Bug]: Circlet of Pain Headgear Disappearing On First Hit in Combat

### ISSUE THREAD

**Issue by RebopBebop** [MelvorIdle/melvoridle.github.io#3682]
### Describe the bug

The Circlet of Pain head slot item is listed as a consumable in the code, and therefore disappears when one wears it, enters combat and a single turn passes. I’m very sure this is a bug as it seems to be a headgear item and it’s fairly rare. I will provide screenshots for proof of the code and the issue.

### Reproduction Steps

1. Spawn in/attain Circlet of Pain
2. Enter combat and let one turn pass
3. Circlet of Pain head gear disappears, seemingly consumed as it is listed as a consumable in the code

### Expected behaviour

I expected the Circlet of Pain to act like a normal head slot item, providing me the reflect damage while wearing it and be like any other headgear in the game.

### Screenshots

![IMG_1135](https://github.com/MelvorIdle/melvoridle.github.io/assets/145468309/e8234428-a14d-4105-aaf8-19c58578f7c2)
![IMG_1136](https://github.com/MelvorIdle/melvoridle.github.io/assets/145468309/d834b060-571d-4387-8c13-a64d4b310d93)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/145468309/61ee58be-0628-4254-8fb4-766da11f3e72)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [ ] Safari
- [ ] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7841

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This is now fixed as of [Game Update - v1.2 ?7889](https://www.reddit.com/r/MelvorIdle/comments/16o3no7/game_update_v12_7889/)
