### ISSUE TITLE
[Bug]: Ports can be used before they are visited

### ISSUE THREAD

**Issue by Spiritomi** [MelvorIdle/melvoridle.github.io#3684]
### Describe the bug

In Cartography, after fully surveying a hex that contains a Port, the player is able to use the hex for fast travel before they have visited the hex.

Encountered using Opera GX, which is built on Chromium.

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/13985801/8f3419be-650e-4fd0-9d73-1859ecea1d51)

### Reproduction Steps

1. In Cartography, have at least one Port fully surveyed and visited.
2. Fully survey another hex that contains a Port, but do not visit it.
3. Select a discovered Port to travel to.
4. If the Port you selected is cheaper to reach using the undiscovered Port, the pathfinding will use the undiscovered Port as part of the routing.

### Expected behaviour

A Port should not be factored into the pathfinding until it has been not only fully surveyed but also visited.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7841

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This is now fixed as of [Game Update - v1.2 ?7889](https://www.reddit.com/r/MelvorIdle/comments/16o3no7/game_update_v12_7889/)
