### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by Alan2041** [MelvorIdle/melvoridle.github.io#3685]
### Describe the bug

I’m only a few days into my first Melvor run and I just recently got 98 Fishing Skill Level.
I’m wondering that why it shows almost the same XP in Mastery XP / Mastery Pool XP (1:1) but Pool XP takes me more time to leveling?

There are 3 kinds fishing XP / per fish (Raw Whale):
661 Skill XP
858 Mastery XP
817 Mastery Pool XP

The Truth Is:

662 Skill XP = 12,613,419 - 12,612,757
624 Mastery XP = 4,583,418 - 4,582,794 

“156” Mastery Pool XP = 6,962,541 - 6,962,385

The results is whatever fish I got, the Skill Level is alway High then my Master Pool Level.

### Reproduction Steps

1. Go to ‘Fishing’
2. Choose on “any” kinds of Fish.
3. Wait to see Mastery Pool XP.

### Expected behaviour

Show what the XP should be like:
661 Skill XP
858 Mastery XP
817 Mastery Pool XP

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/h5vAFJAS

### Screenshots

![IMG_1234](https://github.com/MelvorIdle/melvoridle.github.io/assets/143476476/35cbdb6c-a246-4612-ba8e-e1d52bae7272)
![IMG_1237](https://github.com/MelvorIdle/melvoridle.github.io/assets/143476476/e6a5b49d-7a2c-4ef0-be64-0b9b04d2fc2f)
![IMG_1238](https://github.com/MelvorIdle/melvoridle.github.io/assets/143476476/e3c35fa6-4895-4c23-bb95-5560a713309e)
![IMG_1235](https://github.com/MelvorIdle/melvoridle.github.io/assets/143476476/bafc42b7-5d22-4883-a5d7-8b85ec9baaec)
![IMG_1236](https://github.com/MelvorIdle/melvoridle.github.io/assets/143476476/e02a45d4-f66e-4e98-9ab7-bb876e83e481)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7845

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Thanks for the report. This is just a visual error with the icons and the XP you are obtaining is accurate. A fix is on the way.

**Comment by MelvorIdle** [comment]
This is now fixed as of [Game Update - v1.2 ?7889](https://www.reddit.com/r/MelvorIdle/comments/16o3no7/game_update_v12_7889/)
