### ISSUE TITLE
[Bug]: Meteorite Spellcaster Ring reducing Infernal Runes in Passive Slot

### ISSUE THREAD

**Issue by Flurryous** [MelvorIdle/melvoridle.github.io#3686]
### Describe the bug

Title. The Meteorite Spellcaster Ring's description says it reduces infernal rune cost when equipped in the ring slot. However, this effect also works when the ring is equipped in the passive slot. 

### Reproduction Steps

1. Go to the Alt Magic page.
2. Click on Rags to Riches III (need to toggle combination runes on). 
3. Check the infernal rune cost of the spell, it should be at 20.
4. Equip the Meteorite Spellcaster Ring to your passive slot.
5. Check the cost of Rags to Riches III again, it should now show 14 infernal runes. 

### Expected behaviour

The Meteorite Spellcaster Ring should only be providing infernal rune cost reduction when it is equipped in the ring slot. If reducing the cost while in the passive slot is intentional, then the description should be updated to reflect this. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7845

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This is now fixed as of [Game Update - v1.2 ?7889](https://www.reddit.com/r/MelvorIdle/comments/16o3no7/game_update_v12_7889/)
