### ISSUE TITLE
Android beta - After a while, using the android recent apps to switch back to Melvor white screen

### ISSUE THREAD

**Issue by jjrrw174** [MelvorIdle/melvoridle.github.io#3687]
### Describe the bug

After a while if you use the recent apps feature on Android to switch back to melvor, it loads as a white screen and nothing happens

Happens on non beta
Happens with or without mods

Using a Samsung a53 5g on Adroid 13, one ui 5.1. Have melvor listed as an unrestricted app for battery usage

Have tried clearing cache and data. Tried reinstalling

### Reproduction Steps

Open melvor
Wait 3 - 5 mins
Switch back to melvor with the recent apps function

### Expected behaviour

For the app to load back in

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/nO6ZP35e

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7846

### Are you using any mods?

Yes

**Comment by Skipper-is** [comment]
Same issue in Android Beta. (Redmi Note 10 Pro) 
No mods on mine.
If I lock screen with Melvor open, it doesn't white out, but if I switch apps it does.

**Comment by jjrrw174** [comment]
This has mysteriously fixed itself for me. I don't remember what I did but I think I

1. Settings > Developers Options > Background Processes Limit set to standard and Don't keep activities set to off

2. Settings > Applications > Melvor Idle > Battery > Unrestricted

I have a feeling it's do with aggressive dozing of more recent Android versions but I'm not sure
