### ISSUE TITLE
[Bug]: Unformatted description for Crafting Potion

### ISSUE THREAD

**Issue by Southier9** [MelvorIdle/melvoridle.github.io#3688]
### Describe the bug

On Select Potion screen, the Crafting Potion description is showing text format code. I'm using Opera GX to play.

### Reproduction Steps

1. Go to Crafting Tab
2. Click on Select Potion button
3. See description

### Expected behaviour

Show formatted text on disabled buff on Ancient Relics

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/36991161/e6b519e7-3493-4ce6-a105-c240b410b1a1)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7846

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This is now fixed as of [Game Update - v1.2 ?7889](https://www.reddit.com/r/MelvorIdle/comments/16o3no7/game_update_v12_7889/)
