### ISSUE TITLE
[Spelling/Grammar]: Typo when selecting Worship for Township

### ISSUE THREAD

**Issue by kocsirtamas** [MelvorIdle/melvoridle.github.io#3689]
### What text is wrong?

When selecting Worship, the text ends to this: "There is a cost 50M cost to do so." See picture.
![kép](https://github.com/MelvorIdle/melvoridle.github.io/assets/142602141/20996e5c-ff16-47a1-ae0e-aa3ec2d23b41)

### What is the correct spelling or grammar?

It should be either "There is a cost of 50M GP to do so." or "There is a 50M GP cost to do so."

**Comment by MelvorIdle** [comment]
This is now fixed as of [Game Update - v1.2 ?7889](https://www.reddit.com/r/MelvorIdle/comments/16o3no7/game_update_v12_7889/)
