### ISSUE TITLE
[Bug]: <Mastery XP for Archaeology does not increase>

### ISSUE THREAD

**Issue by Rasmus-Developer** [MelvorIdle/melvoridle.github.io#3690]
### Describe the bug

Sometimes the Mastery XP for Archaeology gets stuck and does not increase at all, even though I restart the game and restart the excavation. 

### Reproduction Steps

1. Go to archaeology.
2. Press excavate on Old Village.
3. Wait.

### Expected behaviour

Should get Mastery XP for every time it excavates?

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7846

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
You only receive Master XP when you obtain an Artefact. This is mentioned just above the XP icons on the Dig Site.
