### ISSUE TITLE
melantis clue 2

### ISSUE THREAD

**Issue by aserrew** [MelvorIdle/melvoridle.github.io#3692]
### Describe the bug

Melantis clue2 is not coming out

I've already done 120 levels of cartography

And I already have "Clue 1"

And if you go to the pyramid with clue 1, you'll find it, but it doesn't come out as a bug

### Reproduction Steps

ㅣ

### Expected behaviour

ㄱ

### Console output

ㅣ

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7846

### Are you using any mods?

Yes

**Comment by Flurryous** [comment]
You also need to wear expert water robe set and a mystic water staff while going to that hex.

**Comment by MelvorIdle** [comment]
It seems the clue wasn't followed 100%. Once you go to the hex with all the requirements, you will receive clue 2
