### ISSUE TITLE
[Spelling/Grammar]: Fish size variable not displayed properly at the end of fishing contest

### ISSUE THREAD

**Issue by kocsirtamas** [MelvorIdle/melvoridle.github.io#3693]
### What text is wrong?

See image:
![kép](https://github.com/MelvorIdle/melvoridle.github.io/assets/142602141/9189a285-d59e-44c6-ab55-1051d1b0e198)

### What is the correct spelling or grammar?

The size should appear instead of the variable.

**Comment by MelvorIdle** [comment]
Hotfix was applied. Thanks for the report :)
