### ISSUE TITLE
[Bug]: button to start clue hunt doesn't work in Android beta

### ISSUE THREAD

**Issue by srmols** [MelvorIdle/melvoridle.github.io#3694]
### Describe the bug

Nothing happens when I click the button to start the clue hunt (birthday event) in Android beta. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

? 7893

### Are you using any mods?

Yes

**Comment by Draedon123** [comment]
when you click the button, the first clue scroll gets added to you bank. go read it and start the hunt

**Comment by MelvorIdle** [comment]
You received the clue item in your bank.
