### ISSUE TITLE
[Bug]: Item doesn’t exist

### ISSUE THREAD

**Issue by kloprete** [MelvorIdle/melvoridle.github.io#3695]
### Describe the bug

Received this error message after idling for a few hours.

An error occured while processing ticks offline:
Error Name: Error
Error Message: Invalid item ID melvorF:Birthday_Present_Combat

### Screenshots

![IMG_8841](https://github.com/MelvorIdle/melvoridle.github.io/assets/57902761/28cab788-8357-4b81-84a8-645a423f310a)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7893

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This issue has been hotfixed and won't occur again when reload the game to the latest version. Thanks for the report.
