### ISSUE TITLE
Birthday event won't start

### ISSUE THREAD

**Issue by lgd6644** [MelvorIdle/melvoridle.github.io#3696]
### Describe the bug

Hi There, when i press click to start on the birthday event,  nothing happens. I tried on both the wed app as well as steam

### Reproduction Steps

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/122545434/c7cdceb2-b2ca-43cd-8b39-ab62499a54b4)

### Expected behaviour

expect the event to start when I click press to start, it doesn't start. I expected it to start

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/122545434/645d7ca7-d849-4b2a-9065-c9006c0a58f9)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7893

### Are you using any mods?

No

**Comment by srmols** [comment]
It works. A item has been added to your bank.

**Comment by lgd6644** [comment]
sorry,  appears I am not so smart,  thanks so much

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by srmols** [comment]
It happened to me, too! Maybe a confirmation message would help!
