### ISSUE TITLE
Areas disappear after death

### ISSUE THREAD

**Issue by RedSparr0w** [MelvorIdle/melvoridle.github.io#37]
**Describe the bug**
All areas disappear after you die in a dungeon _(haven't tested elsewhere)_

**To Reproduce**
1. Run final dungeon
2. `combatData.player.hitpoints = 1;` to die quicker
3. Die
4. All areas are gone

**Expected behavior**
All areas should remain accessible.

**Screenshots**
![image](https://user-images.githubusercontent.com/7288322/68901840-9fc47880-079b-11ea-94e3-9dc26ef0fc4f.png)

**Browser**
Windows 10
Chrome `Version 78.0.3904.97 (Official Build) (64-bit)`

**Console output**
No console errors.

**Comment by MelvorIdle** [comment]
Thanks. A hotfix has been applied (No need to force refresh).
This was due to leaving in an old function for a previous version of how dungeons were handled prior to me changing it for release.
