### ISSUE TITLE
[Bug]: Agility NaN Error / No Obstacle 1

### ISSUE THREAD

**Issue by TwisterMonkey** [MelvorIdle/melvoridle.github.io#3700]
### Describe the bug

Agility skill is bugged and showing NaN experiance, and has obstacle 8 instead of obstacle 1.

### Reproduction Steps

Login to account

### Expected behaviour

Obstacle 1 is displayed properly, NaN is replaced with a normal number

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/P0oyVVUg

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/43807561/7773d01a-0618-4df5-9020-d1189eec7ed2)

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/43807561/dbffc442-1022-44a0-a61b-babc832680dd)

### Which platforms are you experiencing this bug on?

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7893

### Are you using any mods?

Yes

**Comment by Draedon123** [comment]
Here's your fixed [save](https://melvoridle.com/save/iFii8SpA) for now

**Comment by TwisterMonkey** [comment]
Thanks, that seems to work now
