### ISSUE TITLE
[Bug]: Birthday Event Challenges finished but game mode not unlocked

### ISSUE THREAD

**Issue by HolgerFe** [MelvorIdle/melvoridle.github.io#3703]
### Describe the bug

Hi,

I've finished all 3 challenges for the Birthday Event 2023. The hunting clues, the fishing contest and locating all 4 presents (all marked green) but the game mode isn't unlocked.

I restarted unknown the clue hunt while I was on hint #4 once but finished the clue hunt afterwards. 

See screenshot

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/3NaNKHn3

### Screenshots

![Screenshot_20230922-084025](https://github.com/MelvorIdle/melvoridle.github.io/assets/65410712/3d752b21-92cc-4e3c-b3f9-d376ffb2d45f)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

7899

### Are you using any mods?

Yes

**Comment by Flurryous** [comment]
To be clear, you need to make a new character to be able to select the new game mode. It's not something that changes your current save. If you're not seeing the ??? game mode option when creating a new character, disregard my comment.

**Comment by HolgerFe** [comment]
Ahhh sorry my mistake, it wasn't that clear. I thought it is like the goblin minigame.
Thank you for your answer :)
