### ISSUE TITLE
[Bug]: Birthday Clue #1 not granting Clue #2

### ISSUE THREAD

**Issue by LedgerShredder** [MelvorIdle/melvoridle.github.io#3704]
### Describe the bug

When going through and working on the first clue for the birthday event, following steps as other people have confirmed does not grant the second clue. Have tried disabling mods, clearing cache, uninstalling and reinstalling game. 

### Expected behaviour

After completing the requisite for Clue #1, Clue #2 should be granted. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7899

### Are you using any mods?

Yes

**Comment by spaceturtle11** [comment]
Same Issue on Firefox

**Comment by DorindavW** [comment]
Also on chrome and steam for me

**Comment by Senester91** [comment]
I've been having the same issue. I've killed hundreds, if not thousands of plants and still no clue #2

**Comment by Senester91** [comment]
> Same Issue on Firefox



> ### Describe the bug
> When going through and working on the first clue for the birthday event, following steps as other people have confirmed does not grant the second clue. Have tried disabling mods, clearing cache, uninstalling and reinstalling game.
> 
> ### Reproduction Steps
> _No response_
> 
> ### Expected behaviour
> After completing the requisite for Clue #1, Clue #2 should be granted.
> 
> ### Save Link - Required if issue occurs with a save
> _No response_
> 
> ### Screenshots
> _No response_
> 
> ### Console output
> _No response_
> 
> ### Which platforms are you experiencing this bug on?
> * [ ]  Chrome
> * [ ]  Firefox
> * [ ]  Edge
> * [ ]  Safari
> * [ ]  Steam
> * [ ]  Mobile App (iOS)
> * [x]  Mobile App (Android)
> * [ ]  Mobile App (Android Beta)
> * [ ]  Other (Please Specify)
> 
> ### Which version of the game are you experiencing this bug on?
> v1.2
> 
> ### Game Subversion
> ?7899
> 
> ### Are you using any mods?
> Yes

Sell the clue and get a new one. I literally just did this and got clue #2

**Comment by MelvorIdle** [comment]
I believe this issue was hotfixed and should not longer occur
