### ISSUE TITLE
[Bug]: An error occured while processing ticks offline: Invalid item ID melvorF:Birthday_Present_Combat

### ISSUE THREAD

**Issue by Patashu** [MelvorIdle/melvoridle.github.io#3705]
### Describe the bug

An error occured while processing ticks offline:
Error Name: Error
Error Message: Invalid item ID melvorF:Birthday_Present_Combat
Stack Trace:
Error: Invalid item ID melvorF:Birthday_Present_Combat
    at CombatManager.dropBirthdayPresent (https://melvoridle.com/assets/js/built/combatManager.js?7846:136:7)
    at CombatManager.rewardForEnemyDeath (https://melvoridle.com/assets/js/built/combatManager.js?7846:118:174)
    at CombatManager.onEnemyDeath (https://melvoridle.com/assets/js/built/combatManager.js?7846:105:11)
    at CombatManager.checkDeath (https://melvoridle.com/assets/js/built/baseManager.js?7846:26:72)
    at Game.tick (https://melvoridle.com/assets/js/built/game.js?7846:203:148)
    at Game.runTicks (https://melvoridle.com/assets/js/built/game.js?7846:200:96)
    at https://melvoridle.com/assets/js/built/game.js?7846:273:109

Active Action: melvorD:Combat
Current Equipment:
Helmet: melvorD:Dragon_Helmet_T_G
Platebody: melvorD:Dragon_Platebody_T_G
Platelegs: melvorD:Dragon_Platelegs_T_G
Boots: melvorD:Dragon_Boots_T_G
Weapon: melvorD:Dragon_2H_Sword
Amulet: melvorD:Amulet_of_Fishing
Ring: melvorD:Gold_Topaz_Ring
Gloves: melvorD:Dragon_Gloves
Cape: melvorD:Mining_Skillcape

Action Information:
Is In Combat: true
Fight in Progress: true
-- Start of Player Information --
Next Action: Attack
Next Attack: melvorD:Normal
Is Attacking: false
Standard Spell Selected: melvorD:WindStrike
Ancient Spell Selected undefined
Aurora Selected: undefined
Curse Selected: undefined
Active Prayers: None
Equipped Food:
Item: melvorD:Hearty_Soup, Qty: 24
Item: melvorD:Manta_Ray_Perfect, Qty: 7504
Item: melvorD:Basic_Soup, Qty: 5972
-- End Player Information --
-- Start of Enemy Information --
Enemy: melvorD:ElerineArcher
Next Action: Attack
Next Attack: melvorD:Normal
Is Attacking: false
Standard Spell Selected: melvorD:WindStrike
Ancient Spell Selected undefined
Aurora Selected: undefined
Curse Selected: undefined
-- End Enemy Information --
Current Area Type: Combat
Current Area ID: melvorD:ElerineBattlegrounds
Modding Disabled

### Reproduction Steps

1. use my save file (link given). Chrome, Windows 10, demo version
2. go offline overnight fighting master farmers (short periods of time seem to work ok, but it happens when I go to bed and wake up)
3. error message appears and offline combat is interrupted

### Expected behaviour

I expected offline combat to work without a bug.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/VFR9256G

### Which platforms are you experiencing this bug on?

- [] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7846

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This issue has been hotfixed and should no longer occur
