### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by caljparks** [MelvorIdle/melvoridle.github.io#3707]
### Describe the bug

Possibly not a bug but my character uses 14 rune preservation scrolls per 1 single cast of incinerate?

### Reproduction Steps

Use incinerate
with rune preservation scrolls equipped
watch the number drop fast. 

### Expected behaviour

I understand that incinerate attacks 14 times however I doubt it uses 1 cast of runes / x number of attacks

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

atlas of discovery 

### Are you using any mods?

Yes

**Comment by Flurryous** [comment]
IIRC if you're using an aurora like Surge it uses  runes per hit.

**Comment by caljparks** [comment]
Oh no wonder I keep running out of runes. I think there should be a tooltip
for that.

**Comment by MelvorIdle** [comment]
Not a bug, but we will add some more wording to the Aurora's noting the Rune usage mechanic in a future update

**Comment by caljparks** [comment]
Sweet thanks, great game btw I love it.
