### ISSUE TITLE
[Bug]: <title> clue 4 for birthday event

### ISSUE THREAD

**Issue by Growlu** [MelvorIdle/melvoridle.github.io#3709]
### Describe the bug

Impossible to have the clue n°5, i think there are à bug because i'm sure, i make everything to give him..

### Reproduction Steps

1. Equip  luth and necklace 
2. Equip sharp eye 
3. Try to kill wandering bard without food and any equipments 
4. But , clue number 5 is not here..

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7902

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
I am unable to reproduce this bug. Clue 4 works as intended for me. Double check the steps were completed correctly and see if this bug still exists for you.
