### ISSUE TITLE
[Bug]: Crystal Mining Node Not Respawning

### ISSUE THREAD

**Issue by bobalobalo1** [MelvorIdle/melvoridle.github.io#3710]
### Describe the bug

When I initially unlocked the crystal mining node and mined it to depletion, it did not start regenerating or respawning. This was around 3 days ago, and it still has not even begun the process of respawning. I am playing on browser

### Expected behaviour

Crystal mining node to respawn

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/QNDEcrIi

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/32527683/0960330d-514e-4e4b-8d40-633662fdb6c2)
My mastery has not changed as I have not been able to mine it. This is what it looks like all the time.

### Console output

style.css:1     Failed to load resource: the server responded with a status of 404 ()
cloudManager.js?7902:236 Silent Sign in with JWT
cloudManager.js?7902:236 Validating Melvor Cloud token
cloudManager.js?7902:236 Storing Melvor Cloud Token
cloudManager.js?7902:236 Initializing PlayFab login. Method: customID
cloudManager.js?7902:236 Logging in with Custom ID via PlayFab
cloudManager.js?7902:236 Login with custom ID success
cloudManager.js?7902:236 Getting account info
cloudManager.js?7902:236 Account info retrieved
cloudManager.js?7902:236 Authenticated w/ Melvor Cloud: true
cloudManager.js?7902:236 Authenticated w/ PlayFab: true
cloudManager.js?7902:236 Checking for valid full version
cloudManager.js?7902:236 Checking for valid TotH purchase
cloudManager.js?7902:236 Checking for valid Atlas of Discovery purchase
cloudManager.js?7902:236 Loading Game Data...
cloudManager.js?7902:75 Registered Demo Data.
cloudManager.js?7902:75 Registered Full Version Data.
cloudManager.js?7902:75 Registered Birthday Event 2023 Data.
cloudManager.js?7902:76 Registered Throne of the Herald Data.
cloudManager.js?7902:77 Registered Atlas of Discovery Data.
cloudManager.js?7902:236 Initializing Mod Manager...
cloud.js?7902:35 PlayFab Data Stored successfully.
mod.js?7902:716 [Boogies More Combat] The icon file "assets/icon.png" does not exist.
update @ mod.js?7902:716
cloudManager.js?7902:236 Checking for Mod Updates...
cloudManager.js?7902:236 Loading Mods...
cloudManager.js?7902:236 Loading Mods (1/57): SEMI Core (v1.7.2)
cloudManager.js?7902:236 Loading Mods (2/57): Unlimited Offline (vv0.1.5)
cloudManager.js?7902:236 Loading Mods (3/57): SEMI Drop Chances (v1.6.1)
cloudManager.js?7902:236 Loading Mods (4/57): SEMI Auto Loot (v1.3.0)
cloudManager.js?7902:236 Loading Mods (5/57): SEMI Auto Farming (v0.3.2)
cloudManager.js?7902:236 Loading Mods (6/57): SEMI Save on Close (v1.1.0)
cloudManager.js?7902:236 Loading Mods (7/57): SEMI Auto Runecrafting (v1.1.0)
cloudManager.js?7902:236 Loading Mods (8/57): SEMI Auto Collect Stockpiles (v1.1.0)
cloudManager.js?7902:236 Loading Mods (9/57): SEMI Auto Bonfire (v0.1.0)
cloudManager.js?7902:236 Loading Mods (10/57): SEMI Auto Bury (v0.0.4)
cloudManager.js?7902:236 Loading Mods (11/57): SEMI Auto Open (v1.3.0)
cloudManager.js?7902:236 Loading Mods (12/57): SEMI Auto Sell (v1.1.1)
cloudManager.js?7902:236 Loading Mods (13/57): Restore Speedruns (v0.1.0)
cloudManager.js?7902:236 Loading Mods (14/57): Mastery Pool Can Overflow (v1.3.8)
cloudManager.js?7902:236 Loading Mods (15/57): dev.Console (v1.2.4)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (16/57): Godwars Recreation (v1.4)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (17/57): Snipeshot (v1.5.1)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 [melvor_hcco/chance_to_hit_precision] Loading...
c3ca0398-4638-49da-b9c7-a49f33455e30:29 [melvor_hcco/chance_to_hit_precision] Done!
c3ca0398-4638-49da-b9c7-a49f33455e30:29 [melvor_hcco/autoeat_threshold] Loading...
c3ca0398-4638-49da-b9c7-a49f33455e30:29 [melvor_hcco/autoeat_threshold] Done!
c3ca0398-4638-49da-b9c7-a49f33455e30:29 [melvor_hcco/slayer_extension_info] Loading...
c3ca0398-4638-49da-b9c7-a49f33455e30:29 [melvor_hcco/slayer_extension_info] Done!
c3ca0398-4638-49da-b9c7-a49f33455e30:29 [melvor_hcco/maxhit_highlight] Loading...
c3ca0398-4638-49da-b9c7-a49f33455e30:29 [melvor_hcco/maxhit_highlight] Done!
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (18/57): Hide Notifications (v1.0.8)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (19/57): SEMI Auto Slayer (v1.2.0)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (20/57): Item Township Task Info (v0.0.5)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (21/57): ETA (v1.0.5)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (22/57): Mob Death Timer (v1.1)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (23/57): Expansion Summoning Recipes (v0.2.0)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (24/57): Forgot My Hat (v1.2.3)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (25/57): Add Items (v1.0.2)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (26/57): Save Game Converter (v0.1.4)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (27/57): Pokeworld (Generation 1) (v6.4)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Welcome to Pokeworld
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (28/57): Shop Item Owned Indicator (v1.4.0)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (29/57): Combat Indicators (v1.1.1.5)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (30/57): QuickShards (v1.0.0)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (31/57): Show Skill Modifiers (v5.2.2)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (32/57): Show Locked Astrology Modifiers (v0.0.3)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (33/57): Combat Only Mode (HCCO / MCCO) (v3.1.1)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (34/57): Do I have room? (v1.0.18)
c3ca0398-4638-49da-b9c7-a49f33455e30:41 [Do I have room?] Possible mod conflict - BankSelectedItemMenu.setItem has already been patched by the following mods: "Item Township Task Info"
console.warn @ c3ca0398-4638-49da-b9c7-a49f33455e30:41
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (35/57): Better Summoning Menu (v1.0.3)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (36/57): Adventuring (v0.1978)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Adventuring Templates
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Adventuring Module
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering Adventuring Skill
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Adventuring constructor done
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering Adventuring Data
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 20 Stats
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 9 Buildings
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 4 Town Actions
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 6 Products
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 20 Jobs
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 14 Generators
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 15 Spenders
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 2 Passives
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 3 Buffs
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 6 Debuffs
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 3 Areas
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 12 Monsters
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 11 Tiles
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 12 Item Slots
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 35 Item Types
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 7 Materials
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 36 Base Items
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registered Adventuring Data.
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (37/57): Kills in Combat (v0.0.3)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (38/57): Falterfire's Auto Rocking (v0.2.05)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (39/57): Consistent Summon Ordering (v0.0.0)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (40/57): Will I Die? (v4.3.0)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (41/57): Bypass Agility Costs (v1.13.3)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (42/57): Mini Max Capes (v1.3.0)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (43/57): Buyable Dungeon Chests (v1.1)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (44/57): Astrology Cap Changer (v1.1.1)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (45/57): Tiny Passive Icons (v1.3.0)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (46/57): Better Auto Eat (v1.2)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Better Auto Eat : Loading...
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Better Auto Eat : Loaded!
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (47/57): [Myth] Music (v1.13.8)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (48/57): Better Offline Recap (v4.0.5)
c3ca0398-4638-49da-b9c7-a49f33455e30:41 [Better Offline Recap] Possible mod conflict - Game.createOfflineModal has already been patched by the following mods: "Combat Only Mode (HCCO / MCCO)"
console.warn @ c3ca0398-4638-49da-b9c7-a49f33455e30:41
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (49/57): Show Dungeon Completion Count (v1.7.0)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (50/57): 2nd Cel's Divine Familiars (v1.0.1)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (51/57): Rune Consumption (v1.0.0)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (52/57): [Myth] Combat Simulator (v2.1.31)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (53/57): Enchanting (v0.411)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Enchanting Templates
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Enchanting Stylesheet
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Enchanting Module
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering Enchanting Data
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Invention registerData
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Specials
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Actions
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registered Enchanting Data.
c3ca0398-4638-49da-b9c7-a49f33455e30:41 [Enchanting] Possible mod conflict - Bank.addItem has already been patched by the following mods: "Shop Item Owned Indicator"
console.warn @ c3ca0398-4638-49da-b9c7-a49f33455e30:41
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (54/57): Adventuring Expanded (v0.1.0)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering Adventuring Extra Data
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 4 Buildings
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 29 Products
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 5 Jobs
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 8 Generators
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 5 Spenders
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 3 Areas
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 16 Monsters
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 5 Item Types
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 1 Materials
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registering 27 Base Items
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Registered Adventuring Extra Data.
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (55/57): Show Item Sources And Uses (v1.0.13)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (56/57): Priority Miner (v1.0.4)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 [Priority Miner v1.0.4] Loading...
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Mods (57/57): Boogies More Combat (v0.50)
c3ca0398-4638-49da-b9c7-a49f33455e30:41 [Bypass Agility Costs] Possible mod conflict - Player.getMonsterSpawnTime has already been patched by the following mods: "Mob Death Timer"
console.warn @ c3ca0398-4638-49da-b9c7-a49f33455e30:41
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Adventuring postDataRegistration
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Local Saves...
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading Cloud Saves...
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Getting saves from playfab
c3ca0398-4638-49da-b9c7-a49f33455e30:35 Error: invalid zlib data
    at mt (fflate.min.js:1:12641)
    at Object.Ht [as unzlibSync] (fflate.min.js:1:17469)
    at SaveWriter.setDataFromSaveString (saveWriter.js?7902:99:120)
    at SaveWriter.getHeaderFromSaveString (saveWriter.js?7902:92:65)
    at Game.<anonymous> (game.js?7902:322:154)
    at Generator.next (<anonymous>)
    at language.js?7902:5:58
    at new Promise (<anonymous>)
    at __awaiter (language.js?7902:2:8)
    at Game.getHeaderFromSaveString (game.js?7902:322:51)
console.error @ c3ca0398-4638-49da-b9c7-a49f33455e30:35
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Saves retrieved
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Loading character selection
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Connected to PlayFab successfully
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Appending Adventuring Page
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Appending Enchanting Page
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Enchanting save decoding
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Decoding Equipment
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Got enchanting:eaehua, decoding
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Got enchanting:e4i27h, decoding
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Got enchanting:evpioe, decoding
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Got enchanting:efeuxu, decoding
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Got enchanting:wzi7mp, decoding
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Got enchanting:euvmo8, decoding
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Got enchanting:e4rw2p, decoding
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Got enchanting:eordlr, decoding
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Got enchanting:esp4fh, decoding
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Got enchanting:ev3w3e, decoding
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Got enchanting:e0ecmh, decoding
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Got enchanting:eyfyer, decoding
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Got enchanting:egjici, decoding
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Got enchanting:wm6s0c, decoding
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Got enchanting:e624xs, decoding
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Got enchanting:el2flv, decoding
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Got enchanting:e6feza, decoding
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Got enchanting:ejjeum, decoding
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Got enchanting:eidq3y, decoding
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Read 292 bytes for Enchanting save
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Adventuring onLoad
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Game Loaded
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Connected to PlayFab successfully
c3ca0398-4638-49da-b9c7-a49f33455e30:29 updatePlayerTags
c3ca0398-4638-49da-b9c7-a49f33455e30:41 [SEMI Auto Bury] Possible mod conflict - Bank.addItem has already been patched by the following mods: "Shop Item Owned Indicator", "Enchanting"
console.warn @ c3ca0398-4638-49da-b9c7-a49f33455e30:41
c3ca0398-4638-49da-b9c7-a49f33455e30:41 [SEMI Auto Open] Possible mod conflict - Bank.addItem has already been patched by the following mods: "Shop Item Owned Indicator", "Enchanting", "SEMI Auto Bury"
console.warn @ c3ca0398-4638-49da-b9c7-a49f33455e30:41
c3ca0398-4638-49da-b9c7-a49f33455e30:41 [SEMI Auto Sell] Possible mod conflict - Bank.addItem has already been patched by the following mods: "Shop Item Owned Indicator", "Enchanting", "SEMI Auto Bury", "SEMI Auto Open"
console.warn @ c3ca0398-4638-49da-b9c7-a49f33455e30:41
c3ca0398-4638-49da-b9c7-a49f33455e30:41 [SEMI Auto Slayer] Possible mod conflict - SlayerTask.setTask has already been patched by the following mods: "Will I Die?"
console.warn @ c3ca0398-4638-49da-b9c7-a49f33455e30:41
c3ca0398-4638-49da-b9c7-a49f33455e30:29 CO Gamemode not detected, mod will not be loaded.
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Rocking out!
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Empty Item enchanting:exjwc9
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Removed Augmented Item: enchanting:exjwc9 Uncommon Old Modded Content
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Empty Item enchanting:wedl6f
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Removed Augmented Item: enchanting:wedl6f Uncommon Old Modded Content
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Empty Item enchanting:eqc8jm
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Removed Augmented Item: enchanting:eqc8jm Uncommon Old Modded Content
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Empty Item enchanting:wfvyyo
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Removed Augmented Item: enchanting:wfvyyo Uncommon Old Modded Content
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Empty Item enchanting:evoi7c
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Removed Augmented Item: enchanting:evoi7c Uncommon Old Modded Content
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Empty Item enchanting:el7a0e
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Removed Augmented Item: enchanting:el7a0e Uncommon Old Modded Content
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Empty Item enchanting:ejzrvs
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Removed Augmented Item: enchanting:ejzrvs Uncommon Old Modded Content
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Empty Item enchanting:egtqrc
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Removed Augmented Item: enchanting:egtqrc Uncommon Old Modded Content
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Empty Item enchanting:e236uu
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Removed Augmented Item: enchanting:e236uu Uncommon Old Modded Content
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Empty Item enchanting:epi2hm
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Removed Augmented Item: enchanting:epi2hm Uncommon Old Modded Content
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Empty Item enchanting:ezo1mp
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Removed Augmented Item: enchanting:ezo1mp Uncommon Old Modded Content
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Empty Item enchanting:e24yh3
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Removed Augmented Item: enchanting:e24yh3 Uncommon Old Modded Content
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Empty Item enchanting:wcek9l
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Removed Augmented Item: enchanting:wcek9l Uncommon Old Modded Content
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Empty Item enchanting:eubeaf
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Removed Augmented Item: enchanting:eubeaf Uncommon Old Modded Content
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Empty Item enchanting:e7xvvu
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Removed Augmented Item: enchanting:e7xvvu Uncommon Old Modded Content
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Empty Item enchanting:eodg0r
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Removed Augmented Item: enchanting:eodg0r Uncommon Old Modded Content
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Empty Item enchanting:ezqzqr
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Removed Augmented Item: enchanting:ezqzqr Uncommon Old Modded Content
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Empty Item enchanting:ed1bwk
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Removed Augmented Item: enchanting:ed1bwk Uncommon Old Modded Content
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Empty Item enchanting:e98xyc
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Removed Augmented Item: enchanting:e98xyc Uncommon Old Modded Content
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Empty Item enchanting:wpa10m
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Removed Augmented Item: enchanting:wpa10m Uncommon Old Modded Content
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Empty Item enchanting:eh05cg
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Removed Augmented Item: enchanting:eh05cg Uncommon Old Modded Content
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Empty Item enchanting:eyr428
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Removed Augmented Item: enchanting:eyr428 Uncommon Old Modded Content
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Empty Item enchanting:eyu45p
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Removed Augmented Item: enchanting:eyu45p Uncommon Old Modded Content
c3ca0398-4638-49da-b9c7-a49f33455e30:29 [Priority Miner v1.0.4] Merging stored config
c3ca0398-4638-49da-b9c7-a49f33455e30:29 [Priority Miner v1.0.4] Patching game functions
c3ca0398-4638-49da-b9c7-a49f33455e30:41 [Hide Notifications] Possible mod conflict - NotificationQueue.notify has already been patched by the following mods: "[Myth] Music"
console.warn @ c3ca0398-4638-49da-b9c7-a49f33455e30:41
c3ca0398-4638-49da-b9c7-a49f33455e30:41 [Hide Notifications] Possible mod conflict - Mining.postAction has already been patched by the following mods: "Falterfire's Auto Rocking"
console.warn @ c3ca0398-4638-49da-b9c7-a49f33455e30:41
c3ca0398-4638-49da-b9c7-a49f33455e30:41 [Hide Notifications] Possible mod conflict - Farming.growPlots has already been patched by the following mods: "SEMI Auto Farming"
console.warn @ c3ca0398-4638-49da-b9c7-a49f33455e30:41
c3ca0398-4638-49da-b9c7-a49f33455e30:29 ETA : Loading...
c3ca0398-4638-49da-b9c7-a49f33455e30:29 ETA : added settings menu!
c3ca0398-4638-49da-b9c7-a49f33455e30:29 ETA : Loaded!
c3ca0398-4638-49da-b9c7-a49f33455e30:29 Rocked & Loaded!
2c3ca0398-4638-49da-b9c7-a49f33455e30:29 Wrote 292 bytes for Enchanting save
c3ca0398-4638-49da-b9c7-a49f33455e30:29 PlayFab save updated successfully
VM364:61 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'minimum')
    at self.CloneData.restoreModifierData (eval at <anonymous> (3fdc5427-ead6-42b0-9c40-5b181882d011:165:21), <anonymous>:61:61)
    at 3fdc5427-ead6-42b0-9c40-5b181882d011:240:27
    at Generator.next (<anonymous>)
    at 3fdc5427-ead6-42b0-9c40-5b181882d011:28:71
    at new Promise (<anonymous>)
    at __awaiter (3fdc5427-ead6-42b0-9c40-5b181882d011:24:12)
    at onmessage (3fdc5427-ead6-42b0-9c40-5b181882d011:61:28)
c3ca0398-4638-49da-b9c7-a49f33455e30:29 MICSR: [Myth] Combat Simulator v2.1.31 loaded.
c3ca0398-4638-49da-b9c7-a49f33455e30:29 [Priority Miner v1.0.4] Finished loading!
2c3ca0398-4638-49da-b9c7-a49f33455e30:29 Wrote 292 bytes for Enchanting save
style.css:1     Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/basis.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
8c3ca0398-4638-49da-b9c7-a49f33455e30:29 Wrote 292 bytes for Enchanting save

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7902

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
You can paste this command into console to manually beging the respawning process of the rock:

`game.mining.startRespawningRock(game.mining.actions.getObjectByID("melvorAoD:Crystal"))`

**Comment by Murphy540** [comment]
If I had to guess, Falterfire's Auto Rocking not being updated is breaking the crystal rock.
