### ISSUE TITLE
[Bug]: Toggle Birthday Event Item Drops setting does nothing

### ISSUE THREAD

**Issue by Murphy540** [MelvorIdle/melvoridle.github.io#3711]
### Describe the bug

"Toggle Birthday Event Item Drops" doesn't work.

### Reproduction Steps

Go to "Settings"
Toggle "Toggle Birthday Event Item Drops" OFF (left)
Perform actions.

### Expected behaviour

Not to get Birthday Present (X) while skilling

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7902

### Are you using any mods?

No

**Comment by Maqer4lif** [comment]
Experiencing same issue on IOS.
Using the Ancient Relics game mode.

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.1
