### ISSUE TITLE
[Bug]: Golden Wreath doesn't work with Thieving

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#3712]
### Describe the bug

Duplicate of #3655 (The issue is not fixed).

The Golden Wreath increases the GP range when viewing an NPC's drops however the modifier `increasedGPFlat` is not considered when an action is completed.

Additionally, "Flat GP" increases are being modified by any percentage modifiers. Unsure if this is intended.

### Reproduction Steps

1. Go to Thieving
2. Look at the NPCs GP range
3. Equip Golden Wreath `game.bank.addItemByID('melvorAoD:Golden_Wreath', 1)`
4. See NPC gold GP range increase
5. Thieve target; Gold drops will be below the value shown in the NPC's GP range
5a. This is easier to see if done on a fresh account or a target with a lower GP range. A save has been provided for this.

### Expected behaviour

GP should be increased when Thieving with the Golden Wreath equipped.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/bFguf2ic

### Screenshots

NPC GP Range: ![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/8d89b148-7254-4907-9834-355c0f7b5934)
`get actionRewards()`:
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/82fb685f-117e-4d7b-a861-1d3395e73305)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7902

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.1
