### ISSUE TITLE
[Bug]: Magma Eel (Perfect) Bank Image Not Working

### ISSUE THREAD

**Issue by Brajo22** [MelvorIdle/melvoridle.github.io#3713]
### Describe the bug

The item image is not populating. It has the rectangular ripped paper image. However, when clicking on that, the detailed description shows the image. 

### Reproduction Steps

1. Go to bank
2. Find magma eel (perfect)
3. Look at bank image

### Expected behaviour

The bank image should show the cooked magma eel with the star to indicate it is a perfect cook

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7902

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This seems to have been a minor hiccup with our CDN provider which broke the image.
