### ISSUE TITLE
[Bug]: Ancient Relics Game Mode, Can't 100% Base Game Completion due to Urns Being Automatically Enchanted. 

### ISSUE THREAD

**Issue by apelpapa** [MelvorIdle/melvoridle.github.io#3716]
### Describe the bug

I can't get 100% base game completion due to crafting relic that automatically enchants urn. 

### Reproduction Steps

1. Get all Crafting relics before crafting urns,
2. Try to craft urns and you cant

### Expected behaviour

Option to disable auto urn enchanting

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7902

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.1
