### ISSUE TITLE
[Bug]: Game is detecting the wrong steam account

### ISSUE THREAD

**Issue by DGurrera-Portfolio** [MelvorIdle/melvoridle.github.io#3718]
### Describe the bug

I have family sharing active on steam with my girlfriend and even when logged into my account and purchased through my account it is only detecting her steam account. When family sharing gets disabled I lose all access to the game and it reverts me to the demo version. 

I have attempted turning off family sharing and relogging into steam with my account to get it to link properly but the game insists it is her game even though it is definitely under my account.

Screenshots provided show that it is in my (RealityThief) library and in game it will only link to my girlfriend (SilentDawn).
Second screenshot is from my girlfriends library and it states she has access to it from my library.
First screenshot shows her steam ID and name.

### Screenshots

![MelvorIdle Bug](https://github.com/MelvorIdle/melvoridle.github.io/assets/35077276/5a2c27a0-3bfc-4cff-b4d1-47e2533b76af)
![MelvorBug 2](https://github.com/MelvorIdle/melvoridle.github.io/assets/35077276/cd75ac7a-146d-44e7-a7bf-9f46e3e779a5)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7902

### Are you using any mods?

Yes

**Comment by GitBlasphemous** [comment]
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/125527952/b19f44b1-cabd-4598-bea2-d2ffa1ff8985)
