### ISSUE TITLE
[Spelling/Grammar]: Ceramic Jar

### ISSUE THREAD

**Issue by Toxers** [MelvorIdle/melvoridle.github.io#3719]
### What text is wrong?

Description of **Ceramic Jar**, says the following:
_+30 chance to receive an additional Soup from Cooking (Cannot be doubled)_

Item Name: melvorAoD:Ceramic_Jar

### What is the correct spelling or grammar?

It should be:
_+30% chance to receive an additional Soup from Cooking (Cannot be doubled)_?
- With _%_ after _+30_

Item Name: melvorAoD:Ceramic_Jar

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.1
