### ISSUE TITLE
Signet (a) farming skill

### ISSUE THREAD

**Issue by CashMMT** [MelvorIdle/melvoridle.github.io#372]
https://www.reddit.com/r/MelvorIdle/comments/if8mss/impossible_to_get_a_signet_ring_halfa_from/
![1](https://user-images.githubusercontent.com/70365034/91530463-1ec51080-e8d9-11ea-8960-52e734dddd6d.png)
![2](https://user-images.githubusercontent.com/70365034/91530471-21276a80-e8d9-11ea-9104-f9b604a2377b.png)

**Comment by CashMMT** [comment]
I wouldn't remember a 1-2am discord convo LOL

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
