### ISSUE TITLE
[Bug]: Slayer Relic 1 not working properly in AR

### ISSUE THREAD

**Issue by Ignorancia** [MelvorIdle/melvoridle.github.io#3720]
### Describe the bug

The relic says that 100% of poison damage is gained as slayer coins, yet I only get 2 coins doing ticks of 20 damage using the poisonous gem. While I am currently using Better offline recap mod, I also experienced this bug before installing any mods.

### Reproduction Steps

1. Hit enemy
2. Deal poison damage
3. only get 10% of damage dealt as coins

### Expected behaviour

100% gain rather than 10%

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/146131893/789b7b05-f21d-4169-b1c6-41c5af3df96f)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7903

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.1
