### ISSUE TITLE
[Bug]:Gloves error

### ISSUE THREAD

**Issue by AbezOnline** [MelvorIdle/melvoridle.github.io#3721]
### Describe the bug

When I bought 10x mining gloves, 10x cooking gloves, 10x smithing gloves and 10x thieving gloves I only received 1x glove of each at 5000 charges. Instead of 10x each glove with 5000 charges for each.

### Reproduction Steps

1 purchase 10x gloves
2 check bank 
3 receive only 1 glove

### Expected behaviour

Preferably I would like this bug fixed and to be reimbursed my in-game currency back.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/Upbjte0N

### Screenshots

![IMG_4931](https://github.com/MelvorIdle/melvoridle.github.io/assets/146167278/9acb9780-b56a-4356-9643-c6d6eccbe505)
![IMG_4930](https://github.com/MelvorIdle/melvoridle.github.io/assets/146167278/aa7b51cc-22f3-47ea-ba3d-bff36de42b63)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7903

### Are you using any mods?

No

**Comment by Murphy540** [comment]
You get 500 charges per purchase, and the base glove if you don't already have one. This is working as intended.

**Comment by MelvorIdle** [comment]
The charges listed in the shop indicate the total charges you receive when purchasing, inclusive of the multiplier.
