### ISSUE TITLE
[Bug]: <title> thieving only works for coins, not items.

### ISSUE THREAD

**Issue by Smittyishigh** [MelvorIdle/melvoridle.github.io#3723]
### Describe the bug

Started thieving from bob the farmer before i went to bed. 7.5 hours later, i woke up, and checked melvor. I had gathered about 4.5m in coins, but 0 items. Not nearly as important, but i didnt get any birthday presents either. 

### Reproduction Steps

No idea, didnt do anything different than literally every other night. 

### Expected behaviour

I expected to thieve items as well as coins. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7903

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Did you have enough Bank Space to fit the items?

If you can, please provide a copy of your save and we will take a look.
