### ISSUE TITLE
[Bug]: Elite Pillar of Expertise with Atlas skills.

### ISSUE THREAD

**Issue by Vonkriegor** [MelvorIdle/melvoridle.github.io#3724]
### Describe the bug

The -3% interval bonus from the Elite Pillar of Expertise does not apply to Cartography/Archaeology.

### Reproduction Steps

I should have -38% interval for Cartography, however I am only getting -35%

99 cape -20%
Spyglass -10%
Ocean Drifting Course -5%
Elite Pillar of Expertise -3%

### Expected behaviour

The -3% interval bonus from Elite Pillar of Expertise should apply to all non-combat.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7903

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.2. If issue persists, please open a new issue.
