### ISSUE TITLE
[Bug]: Game window gets bigger after every launch

### ISSUE THREAD

**Issue by Poggle566** [MelvorIdle/melvoridle.github.io#3725]
### Describe the bug

Every time I launch the game, the window is bigger than it was last time.
It has gone from taking up about a third of my screen, to nearly all of it over many restarts.
Seems to have started when the Atlas of Discovery DLC was released.

### Reproduction Steps

1. Open game
2. Close game
3. Open game

I have both DLCs enabled.

### Expected behaviour

The game window should be the same size upon launching as it was when the game was last closed.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7903

### Are you using any mods?

No

**Comment by MiniHerc** [comment]
Came here to submit this bug.. sad to see it's still a problem half a year later.
