### ISSUE TITLE
[Bug]: No monsters show up

### ISSUE THREAD

**Issue by jetro400** [MelvorIdle/melvoridle.github.io#3726]
### Describe the bug

I'm trying to start a new game mode but every other game mode then the normal one wont let me fight monsters.
I try to fight but no monster shows up

### Screenshots

![Knipsel 2](https://github.com/MelvorIdle/melvoridle.github.io/assets/146389070/e350156a-63cc-4296-8959-215d6ee3defe)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7903

### Are you using any mods?

Yes

**Comment by icedtrumpets** [comment]
Disable your mods that make you run from monsters.

**Comment by MelvorIdle** [comment]
There is a mod you have enabled that automatically runs from monsters when you hit a certain HP. Because this gamemode has 1HP only, you will always automatically run from a Monster
