### ISSUE TITLE
[Bug]: Cartography Superior Cape and AoD Completion Cape have different Interval reductions

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#3727]
### Describe the bug

See attached pictures;
The Superior Cartography skillcape reduces Survey interval by 30%
The AoD Completion skillcape reduces Survey interval by 35% and Cartography skill interval by an additional 10%.

### Reproduction Steps

1. View superior skillcape stats: `game.items.getObjectByID('melvorAoD:Superior_Cartography_Skillcape')`
2. Compare to completion skillcape stats: `game.items.getObjectByID('melvorAoD:Cape_of_Completion_AoD')`

### Expected behaviour

1. Either the Superior cape should be increased to 35% or the AoD Completion cape should be lowered to 30%.
2. The Superior skillcape should either have 10% interval reduction added to it or the AoD Completion cape should have it removed. If it is added, the list of modifiers shown on the item will need to be updated to reflect this change.

### Screenshots

(The last cape is the AoD Completion Cape, not the Superior Cape of Completion)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/8463c8d1-a051-46ae-93d8-a1d6b495b43f)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/9d4a4baa-8ddc-426d-8e72-67283f64bfac)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/39d97bb6-4804-40ab-87f5-391664c5cb46)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7903

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.1
