### ISSUE TITLE
[Bug]: Loot missing from notification

### ISSUE THREAD

**Issue by kocsirtamas** [MelvorIdle/melvoridle.github.io#3728]
### Describe the bug

Doing combat in a Slayer area (not Slayer Task) and when I click the Loot button, then Holy Dust does not appear in the notification.
But when I manually click only on Holy Dust to loot it, it appears in the notification.

(BTW this image is no longer correct: https://raw.githubusercontent.com/MelvorIdle/melvoridle.github.io/master/images/subversionExample.png since the subversion number is now at the bottom)

### Reproduction Steps

1. Start doing combat in the Holy Isles (Fairy)
2. Wait until there are multiple loots in the loot tab (do not equip Amulet of Looting)
3. Click the Loot button
4. See that Holy Dust is missing from the notification
5. It appears in the notifications when I manually click on Holy Dust only

### Expected behaviour

I expect Holy Dust to be displayed in the norification area when I loot it by clicking on the Loot button.

### Screenshots

I made a video, but it is too big to upload (40MB), so here is 3 screenshots instead.
![kép](https://github.com/MelvorIdle/melvoridle.github.io/assets/142602141/c5770cbb-f91c-42d0-b324-dd576d0347e5)
![kép](https://github.com/MelvorIdle/melvoridle.github.io/assets/142602141/aacb50ab-6180-4f09-8352-e9a0c2ed399f)
![kép](https://github.com/MelvorIdle/melvoridle.github.io/assets/142602141/7e0d7361-e9d4-4754-a060-219f12344bd1)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7903

### Are you using any mods?

No

**Comment by BerghsJelmer** [comment]
I have a similar problem. This is in the android beta app:
Offline overview shows there is 11 raw chicken to loot.
The loot area shows indeed 11 raw to loot.
But when i click loot all. It only shows 6 raw chicken in the notification.
The same problem occurs with the feathers.
![Screenshot_20231206-132650](https://github.com/MelvorIdle/melvoridle.github.io/assets/43340072/fa028a38-78de-4ef9-8dca-ae94ad795ab6)
![Screenshot_20231206-132654](https://github.com/MelvorIdle/melvoridle.github.io/assets/43340072/96542638-88d6-4188-872a-809b545695c2)
![Screenshot_20231206-132659](https://github.com/MelvorIdle/melvoridle.github.io/assets/43340072/182e29ff-13c2-4906-a634-e986086b9873)
