### ISSUE TITLE
[Bug]: game ui bug

### ISSUE THREAD

**Issue by eden2299** [MelvorIdle/melvoridle.github.io#3729]
### Describe the bug

ui is broken
game is unplayable 
only on steam

### Reproduction Steps

1. open the game

### Expected behaviour

i expect the game to no have a broken ui

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/146557195/5f668dae-8573-4082-8875-6278f0cc27f8)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/146557195/cd581dab-60a1-4b6d-88fc-139c9443a5ac)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/146557195/ed403efa-8084-4bfd-9ca1-cc07e305e309)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/146557195/c8b0daca-5143-4292-8647-dd7edb653b5e)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7903

### Are you using any mods?

No

**Comment by ekuland** [comment]
Make sure you have a cloud save or a backup of your local ones as this method _**will**_ delete them.

Navigate to `%localappdata%\Melvor Idle`
Delete the entire folder
Boot the game, see if it's fixed.

**Comment by eden2299** [comment]
it worked 
thank you very much
