### ISSUE TITLE
[Bug]: Equipment Event Unassigners grows without ever being cleared

### ISSUE THREAD

**Issue by mythridium** [MelvorIdle/melvoridle.github.io#3730]
### Describe the bug

The array of `equipmentEventUnassigners` grows forever and never gets cleared after the handlers are unassigned. This array gets added to every time an item that creates event handlers is equipped, this includes switching equipment sets.

While this array may potentially be small, this could grow to a sizable amount if someone plays for an extended amount of time without refreshing the game and switches equipment a lot, or runs out of consumables a lot.

This would also impact golbin raid as the same function is called on item equip.

### Reproduction Steps

Equip items that have a `consumesOn`, `consumesChargesOn` or `consumesItemOn` property into multiple equipment sets.
Continually switch between the equipment sets.
Place a breakpoint inside the `assignEquipmentEventHandlers` function.
Switch an equipment set to trigger the breakpoint.
View the amount of items in the `equipmentEventUnassigners` array continually grow.

### Expected behaviour

This array should probably get cleared after the `unassignMatchers` function is called, or the elements that have been unassigned removed from the array in any other fashion.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/2TKiqDBu

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/132613374/ebd8d886-9716-43c1-af29-8a0076fcbf68)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari
- [X] Steam
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

7903

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.1
