### ISSUE TITLE
[Bug]: Negative gp modifiers result in gold be removed per monster kill/dungeon clear

### ISSUE THREAD

**Issue by mythridium** [MelvorIdle/melvoridle.github.io#3731]
### Describe the bug

When you have a negative gp modifier, if you kill monsters or clear dungeons, you will have gp removed from you.

If you end up having 0 gold, you end up automatically taking out a 0% interest loan that grows forever.

This is easily achievable with Cartography 'Unhallowed Wasteland' -100% GP and Agility 14 - Freezing Climb -75% GP and minimal +GP increases.

### Reproduction Steps

Load the attached save.
Clear the chicken coop.
Note that gp is removed.

### Expected behaviour

Not sure if this is entirely a bug, this could be intended, however it should probably not reduce the player below 0 gold.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/d9quh4Bn

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/132613374/10361f90-aa8c-40c4-bcc9-ac8edd86cc22)

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/132613374/0cebb830-2302-456d-ba9d-92f39db839d5)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari
- [X] Steam
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

7903

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.1
