### ISSUE TITLE
[Bug]: Enchanted and Arcane bolts have no level requirement

### ISSUE THREAD

**Issue by mythridium** [MelvorIdle/melvoridle.github.io#3732]
### Describe the bug

Level requirements for enchanted and arcane bolts are weird.

Topaz, Sapphire, Emerald and Ruby Enchanted and Arcane bolts have no level requirements at all.
Diamond Enchanted and Arcane bolts require level 70, while the base bolts require level 80
Jadestone Enchanted and Arcane bolts require level 85, while the base bolts required 90

This means you could create a bunch of Topaz, Emerald, Ruby or Sapphire bolts, upgrade them and use them with level 1 ranged skill.

Using the following console command to output the data easily (ignore the golbin raid bolts):

```
game.items.equipment.filter(equipment => equipment.validSlots.includes('Quiver') && ['Topaz', 'Ruby', 'Sapphire', 'Emerald', 'Diamond', 'Jadestone'].some(match => equipment.localID.includes(match))).map(equipment => ({ name: equipment.name, equipRequirements: equipment.equipRequirements.map(r => `${r.type} - ${r.skill.localID} - ${r.level}`).join(', ') }))
```

### Reproduction Steps

Look at equip requirements of enchanted and arcane topaz, ruby, emerald, sapphire, diamond and jadestone bolts.

### Expected behaviour

Enchanted and Arcane bolts should have the same level requirement as the normal bolt.

Enchanted and Arcane diamond bolts should match the base diamond bolt skill requirement of 80.

Enchanted and Arcane jadestone bolts should match the base diamond bolt skill requirement of 90.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/132613374/fdc532a7-a28e-4b0a-bd16-a764b0204d0b)

### Console output

```
[{
    "name": "Enchanted Topaz Bolts",
    "equipRequirements": ""
},
{
    "name": "Enchanted Sapphire Bolts",
    "equipRequirements": ""
},
{
    "name": "Enchanted Ruby Bolts",
    "equipRequirements": ""
},
{
    "name": "Enchanted Emerald Bolts",
    "equipRequirements": ""
},
{
    "name": "Enchanted Diamond Bolts",
    "equipRequirements": "SkillLevel - Ranged - 70"
},
{
    "name": "Enchanted Jadestone Bolts",
    "equipRequirements": "SkillLevel - Ranged - 85"
},
{
    "name": "Topaz Bolts",
    "equipRequirements": "SkillLevel - Ranged - 1"
},
{
    "name": "Sapphire Bolts",
    "equipRequirements": "SkillLevel - Ranged - 20"
},
{
    "name": "Ruby Bolts",
    "equipRequirements": "SkillLevel - Ranged - 40"
},
{
    "name": "Emerald Bolts",
    "equipRequirements": "SkillLevel - Ranged - 60"
},
{
    "name": "Diamond Bolts",
    "equipRequirements": "SkillLevel - Ranged - 80"
},
{
    "name": "Jadestone Bolts",
    "equipRequirements": "SkillLevel - Ranged - 90"
},
{
    "name": "Topaz Bolts (Enchanted)",
    "equipRequirements": ""
},
{
    "name": "Ruby Bolts (Enchanted)",
    "equipRequirements": ""
},
{
    "name": "Sapphire Bolts (Enchanted)",
    "equipRequirements": ""
},
{
    "name": "Emerald Bolts (Enchanted)",
    "equipRequirements": ""
},
{
    "name": "Diamond Bolts (Enchanted)",
    "equipRequirements": "SkillLevel - Ranged - 70"
},
{
    "name": "Jadestone Bolts (Enchanted)",
    "equipRequirements": "SkillLevel - Ranged - 85"
},
{
    "name": "Topaz Bolts (Arcane)",
    "equipRequirements": ""
},
{
    "name": "Ruby Bolts (Arcane)",
    "equipRequirements": ""
},
{
    "name": "Sapphire Bolts (Arcane)",
    "equipRequirements": ""
},
{
    "name": "Emerald Bolts (Arcane)",
    "equipRequirements": ""
},
{
    "name": "Diamond Bolts (Arcane)",
    "equipRequirements": "SkillLevel - Ranged - 70"
},
{
    "name": "Jadestone Bolts (Arcane)",
    "equipRequirements": "SkillLevel - Ranged - 85"
}]
```

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari
- [X] Steam
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

7903

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.1
