### ISSUE TITLE
[Bug]: required materials missing pop-up wrongfully showing

### ISSUE THREAD

**Issue by dev-bas** [MelvorIdle/melvoridle.github.io#3733]
### Describe the bug

In smithing, when your bank is full and you try to smith something it displays the “you don’t have the required materials to smith that” pop-up even though you do. 

### Reproduction Steps

1. Have a full bank
2. Try smith something

### Expected behaviour

The message not to show as the required materials are present.

### Screenshots

![IMG_1677](https://github.com/MelvorIdle/melvoridle.github.io/assets/70659371/47510ed7-af21-421d-ba24-547da699c960)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7903

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.1
