### ISSUE TITLE
[Bug]: Completing Unholy Forest 100 times doesn’t unlock store item

### ISSUE THREAD

**Issue by Tayonnaise** [MelvorIdle/melvoridle.github.io#3734]
### Describe the bug

The store item to purchase +1 Archeology dig site remains unavailable even after (I) completing the Unholy Forest =>100 times, and (ii) having Archeology =>80.

### Screenshots

![IMG_9651](https://github.com/MelvorIdle/melvoridle.github.io/assets/146737893/eab282a5-6ede-4807-aa10-b0f709df60cb)
![IMG_9652](https://github.com/MelvorIdle/melvoridle.github.io/assets/146737893/0318beed-3e96-4f41-8e41-b560ad1a5eb2)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7937

### Are you using any mods?

Yes

**Comment by Tayonnaise** [comment]
Addendum: This issue also exists when using Steam, Chrome, and Edge.

**Comment by ekuland** [comment]
Check the completion log for how many times you've killed the boss, not chest count. You can double chest drops.

**Comment by Tayonnaise** [comment]
Well slap me around and call me Susan. I’m dumb. thanks
