### ISSUE TITLE
[Bug]: [AOD] Ancient Stone Tablet Dungeon Access 

### ISSUE THREAD

**Issue by xx1guardian1xx** [MelvorIdle/melvoridle.github.io#3735]
### Describe the bug

The Ancient Stone Tablet from the Monuments Archaeology site has the descrption of giving you access to the Golem dungeon, despite the Dungeon not actually requring the tablet.

Either the description is incorrect or the dungeon isn't locked correctly.

### Reproduction Steps

1. Get Ancient Stone Tablet from Monument Site
2. Read description

### Expected behaviour

Description correct to what the item does.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/3170050/c2c3f767-7cdf-4e77-bf4c-f60657631003)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

7937

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This requirement is accurate, however you must be playing Ancient Relics mode which has custom Dungeon entry requirements for AoD dungeons. This is done to prevent softlocking your character.
