### ISSUE TITLE
[Bug]: Archeology and Cartography do not produce mysterious stones nor rhaelyx circlets/jewels

### ISSUE THREAD

**Issue by Jovasa** [MelvorIdle/melvoridle.github.io#3736]
### Describe the bug

While training Archeology and Cartography nothing related to Crown of Rhaelyx is produced.

### Expected behaviour

Both Archeology and Cartography randomly produce mysterious stones, and Archeology produced jewels and Cartography circlets.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7937

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Fixed with Game Update - v1.2.1 ?7958
