### ISSUE TITLE
[Bug]: Pure Crystal Sell Price not updated - Steam Client

### ISSUE THREAD

**Issue by vikinglief** [MelvorIdle/melvoridle.github.io#3737]
### Describe the bug

Patch notes say that price was adjusted for both Crystal and Pure Crystal.  Price for Crystal was properly adjusted down to 100, but price for Pure Crystal was not properly adjusted up to 1000.  Pure Crystal still sells for 750.

### Reproduction Steps

1. Mine pure crystal
2. Go to bank
3. Select Pure crystal - it will show price is 750
4. Sell Pure crystal - gold total will increase by 750

### Expected behaviour

I expected both the in-game text related to the sale price of Pure Crystal to be updated to 1000 from 750, and the actual sell price to likewise be updated to 1000 from 750, as per the patch notes.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/33608127/c6cf2804-aee4-413c-b8bd-d3ae58a4bb3f)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7937

### Are you using any mods?

No

**Comment by Sycamore5** [comment]
I think that was only for **refined** pure crystal.

**Comment by MelvorIdle** [comment]
The price was only adjusted for the refined version of pure crystal, not the regular one.
