### ISSUE TITLE
[Bug]: Barrier on enemies prevents DoTs on player

### ISSUE THREAD

**Issue by rjclaasen** [MelvorIdle/melvoridle.github.io#3739]
### Describe the bug

Hello, while trying to beat the Cult Grounds dungeons I noticed some strange behavior; the boss' burn DoT deals 0 damage while the boss has barrier up, but starts dealing damage again when I bring the boss' barrier to 0.

After dying and trying again, this also seems to happen with poison and bleed during this dungeon.

Can't test it outside of this dungeon because I haven't unlocked any barriered monsters that deal DoT afaik

### Reproduction Steps

1. Go to Cult Grounds dungeon all the way up until the boss, the Soul Taker Witch
  1.1. Notice u take no damage from poison/bleed while dungeon mobs have barrier up.
3. Become burnt by its Spirit Burn attack while the boss still has barrier
4. Take 0 damage per tick from the burn
5. Reduce boss' barrier to 0
6. Take many damage from the burn

### Expected behaviour

I expect DoTs to deal damage to the player while the enemy has barrier up.

### Screenshots

![burn barriered](https://github.com/MelvorIdle/melvoridle.github.io/assets/18427451/8493a33e-ba63-422e-9142-afbfa4bd542a)
![burn burns](https://github.com/MelvorIdle/melvoridle.github.io/assets/18427451/fa1af19c-7b83-484b-89bb-e7c8b25fcc93)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7937

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Should be fixed with Game Update - v1.2.1 ?7958
