### ISSUE TITLE
[Bug]: Cartography and Archaeology show up in the "base game" completion log

### ISSUE THREAD

**Issue by BenLubar** [MelvorIdle/melvoridle.github.io#3741]
### Describe the bug

The completion log thinks Cartography and Archaeology can go up to level 99 in the base game.

### Reproduction Steps

1. Completion log
2. Skills
3. Base game

### Expected behaviour

These skills should not be visible under the base game filter.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/4257305/1c2e9496-fe7e-496a-b7d2-a5fa42b028b3)

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/4257305/4992afdf-9517-41a0-b20b-87747cee8c58)

Enabled mods (none of these should be affecting the completion log screen at all)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/4257305/5cd237b2-0bfb-42d8-a084-c24e87df78e7)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/4257305/458b63b3-7c12-430f-991b-db18ae8be4c4)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7937

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Fixed with Game Update - v1.2.1 ?7958
