### ISSUE TITLE
[Bug]: Ring of Deception's downside only applying in dungeons

### ISSUE THREAD

**Issue by Flurryous** [MelvorIdle/melvoridle.github.io#3742]
### Describe the bug

Title. The ring of deception has a 3% chance of receiving no drops from monsters or dungeons. However, it seems from digging into the item's code, this attribute is only applied to dungeons. This bug was noticed a little bit before the latest patch, so I'm not completely sure it's been fixed, but I haven't seen any other references to this oversight. 

### Expected behaviour

The negative attribute should be applied to both dungeons and monsters outside of dungeons. 

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/98805830/d2179663-1177-4bc2-b6a1-22d315e83895)

Credits to Mythridium for pointing out this oversight in the discord, as well as for the screenshot. From the screenshot, the increased chance to receive no combat drop code is applied to the dungeon portion of the code, but according to Myth, it is applied nowhere else. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7937

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Fixed with Game Update - v1.2.1 ?7958
