### ISSUE TITLE
[Bug]: Mask of Confusion applies curse with incorrect magnitude

### ISSUE THREAD

**Issue by farteous** [MelvorIdle/melvoridle.github.io#3744]
### Describe the bug

AoD Mask of Confusion applies a debuff dealing 6% of an enemy's current HP as damage each time it completes an attack, where casting the curse normally ticks for 3%. Both debuff tooltip and the actual damage numbers observed match, it's really doing 6%.
Also they can both be applied simultaneously, which is doing great things for my time-to-kill but is probably not intended.
Lastly, and least likely to be a bug imo, is this intended to last the entire fight or just apply it for 3 turns at the start?

Mask debuff on it's own, including damage on tick
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/32852568/ebade6a4-0a26-41e4-9ac8-e3758e1e2e77)

Double debuff, including damage number on tick
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/32852568/19f87f86-75fc-428c-9338-afac551e3ed5)

The only mod I have installed is [Myth] Combat Sim

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7937

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Fixed with Game Update - v1.2.1 ?7958
