### ISSUE TITLE
[Bug]: AoD Mask of Weakening applies curse with incorrect magnitude

### ISSUE THREAD

**Issue by farteous** [MelvorIdle/melvoridle.github.io#3745]
### Describe the bug

Much like the Mask of Confusion, the Mask of Weakening also has wacky numbers; Weakening 1 manually applied reduces enemy max hit by 5%, using the mask applies a debuff reducing enemy max hit by 3%, though item description clearly states it applies Weakening 1. These buffs can also stack, though I don't think this enables any shenanigans that weren't already idle-able with other gear options.

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/32852568/91c48df9-7e35-4c17-b703-c5704d79844f)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7937

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Fixed with Game Update - v1.2.1 ?7958
