### ISSUE TITLE
[Bug]: cooked chicken not appearing in bank

### ISSUE THREAD

**Issue by TristanGah** [MelvorIdle/melvoridle.github.io#3746]
### Describe the bug

When I actively cook chicken in the strong furnace it won't appear in any bank slot. If I cook it passively, it appears in the stockpile and I can take it from there but active just disappears.

### Reproduction Steps

go to cooking
cook chicken actively on the strong furnace

### Expected behaviour

chicken should appear in bank, cooked

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7937

### Are you using any mods?

No

**Comment by Draedon123** [comment]
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/118961726/20603afa-293b-40f5-a4a1-79ac2b0dada3)
your food is most likely going into your equipped food slots. make sure to turn this off.

**Comment by MelvorIdle** [comment]
You have the setting mentioned above ticked, which means the food is being equipped automatically.

**Comment by TristanGah** [comment]
You were right, thanks and sorry
