### ISSUE TITLE
[Bug]: Blessed Bone Offering shop upgrade does not work

### ISSUE THREAD

**Issue by LunaPresent** [MelvorIdle/melvoridle.github.io#3747]
### Describe the bug

After purchasing the Blessed Bone Offering upgrade from the shop, every bone that is buried should give one additional prayer point. This is not the case. Results with the upgrade are the exact same as without. This is not just a visual bug.

Tested by burying 10k regular bones at currently 1,336k prayer points, amount of prayer points rose to 1,346k in both sidebar and on combat page. Went back to character select screen and reloaded latest local save after burying, still 1,346k.

Also tested, albeit less extensively, with other bones.

Disabled all my mods, reloaded properly, tried again and the problem still occurs

### Reproduction Steps

0. Make note of your prayer points balance and make sure you're not spending any
1. Buy Blessed Bone Offering from the shop
2. Go to bank
3. Select Bones
4. Bury a large amount
5. Prayer points have increased by that amount

### Expected behaviour

Prayer points should have increased by 2x that amount.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/wnR3wl9d

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7937

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Fixed with Game Update - v1.2.1 ?7958
