### ISSUE TITLE
Fire Runes Disappearing

### ISSUE THREAD

**Issue by Fer0nn** [MelvorIdle/melvoridle.github.io#375]
**Describe the bug**
Twice today my fire runes have disappeared while using Ignite. Both times while killing Seething Horned Elites

**To Reproduce**

**Expected behavior**
Not have my fire runes disappear.

**Browser**
Firefox - newest edition

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
SEMI

**Comment by MelvorIdle** [comment]
I believe this was confirmed to be due to an external extension causing the issue.
