### ISSUE TITLE
[Bug]: Superheat II not requiring fire runes

### ISSUE THREAD

**Issue by vikinglief** [MelvorIdle/melvoridle.github.io#3751]
### Describe the bug

On one save only (standard mode), Superheat II is not requiring or using fire runes.

### Reproduction Steps

1. Sell off any Fire runes
2. Have some Nature & Earth runes
3. Go to Alt Magic
4. Select Superheat II
5. Select any Bar you can make
6. It will show the Nature & Earth runes required & in stock, but not the Fire
7. Click Cast
8. It will successfully cast Superheat II and you will get the bar

### Expected behaviour

I expect that Superheat II would require Fire runes and would fail to cast if none are present

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/Ug4e1hUy

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/33608127/c8823aaa-7a6a-4839-a345-3e90da0e7aeb)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/33608127/9c045ddb-93a8-4665-9da7-5754553f9851)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7937

### Are you using any mods?

No

**Comment by Draedon123** [comment]
You probably have a fire weapon equipped. Something like a fire battlestaff. This reduces fire rune cost.

**Comment by MelvorIdle** [comment]
Hi, you have a Fire Battlestaff equipped which reduces the Fire Rune cost of Magic Spells.
