### ISSUE TITLE
[Bug]: TotH cooking pot upgrade unlocked by purchasing furnace

### ISSUE THREAD

**Issue by BenLubar** [MelvorIdle/melvoridle.github.io#3753]
### Describe the bug

It appears that by purchasing the final base game cooking furnace upgrade, I have unlocked the ability to purchase both the first TotH furnace upgrade AND the first TotH cooking pot upgrade. I don't know if this is actually what happened, but you can probably verify this much easier than I can.

<details><summary>Mods (shouldn't be anything that affects this)</summary>

```
SEMI Core
[Myth] Combat Simulator
SEMI Auto Master
SEMI Drop Chances
Semi Auto Township
SEMI Auto Bury
Tiny Passive Icons
Show Slayer Task Attack Style
AutoSort
Shining Star
Item Uses
ETA
QuickShards
SEMI Auto Bonfire
```

</details>

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/7wIvXNYp

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/4257305/89fc0518-f7fb-401f-abe1-5dd19d492525)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7937

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Thanks for the report. Fixed in Game Update - v1.2.1 ?7993
