### ISSUE TITLE
[Bug]: Sudden death in Tricky Temple, cause unknown Game asked me to share the console out

### ISSUE THREAD

**Issue by tbridleman** [MelvorIdle/melvoridle.github.io#3756]
### Describe the bug

Im not sure what happened, i was in the Tricky Temple Dungeon for the first time, i dont think with the gear i was wearing and level i was i should have been able to die but i got a print out from the game to share, Hope this helps, im still not sure what happened

### Reproduction Steps

Unknown, was the first time I had been in the Tricky Temple, I had just unlocked it and I died suddenly and with little warning

### Expected behaviour

Death

### Console output

An error occurred while processing ticks:

Error due to the following mods:
Will I Die? (v4.3.0)

Error Name: Error
Error Message: Invalid damage type: Reflection
Stack Trace:
Error: Invalid damage type: Reflection
    at WidMonsterUtil.damageRoll (Will I Die?:setup.mjs:798:23)
    at WIDMonster._getMaxDamage (Will I Die?:setup.mjs:1241:31)
    at Will I Die?:setup.mjs:1213:30
    at Array.forEach (<anonymous>)
    at WIDMonster._specialAttackDamage (Will I Die?:setup.mjs:1212:23)
    at Will I Die?:setup.mjs:1021:33
    at Array.map (<anonymous>)
    at new WIDMonster (Will I Die?:setup.mjs:1020:51)
    at Will I Die?:setup.mjs:2485:65
    at Array.map (<anonymous>)

Active Action: melvorD:Combat
Current Equipment:
Helmet: melvorAoD:Pure_Crystal_Helmet
Platelegs: melvorTotH:Vorloran_Protector_Platelegs
Boots: melvorAoD:Pure_Crystal_Boots
Weapon: melvorTotH:Agile_Wings_Rapier
Shield: melvorAoD:Pure_Crystal_Shield_T_G
Amulet: melvorAoD:Old_Summoning_Amulet
Ring: melvorAoD:Ring_of_Summoning
Gloves: melvorTotH:Gloves_of_Greater_Shade_Summon
Cape: melvorAoD:Ancient_Infernal_Cape
Passive: melvorF:Wasteful_Ring
Summon1: melvorTotH:Summoning_Familiar_Spectre
Summon2: melvorTotH:Summoning_Familiar_Spider
Consumable: melvorF:Whetstone
Gem: melvorAoD:Agile_Gem

Action Information:
Is In Combat: false
Fight in Progress: false
-- Start of Player Information --
Next Action: Attack
Next Attack: melvorD:Normal
Is Attacking: false
Standard Spell Selected: undefined
Ancient Spell Selected undefined
Aurora Selected: undefined
Curse Selected: undefined
Active Prayers: None
Equipped Food:
Item: melvorTotH:Mystic_Shark, Qty: 13142
Item: melvorTotH:Starfruit_Cake_Perfect, Qty: 246689
Item: melvorTotH:Frozen_Manta_Ray_Perfect, Qty: 36770
-- End Player Information --
-- Start of Enemy Information --
Enemy: melvorAoD:PuppetMaster
Next Action: Attack
Next Attack: melvorAoD:Marionette
Is Attacking: false
Standard Spell Selected: melvorD:FireBlast
Ancient Spell Selected undefined
Aurora Selected: undefined
Curse Selected: undefined
-- End Enemy Information --
Current Area Type: Dungeon
Current Area ID: melvorAoD:Trickery_Temple
Modding Enabled. Loaded mods:
Will I Die?
Potion Downgrade

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7958

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This bug was caused by the mod "Will I Die". Please contact the developer of the mod for a fix.

For reference, you can view what mods cause a crash in the console output you provided:

```
Error due to the following mods:
Will I Die? (v4.3.0)
```
