### ISSUE TITLE
Ancient artifacts mode, gem glove and mining lesser relic

### ISSUE THREAD

**Issue by Graptharr** [MelvorIdle/melvoridle.github.io#3758]
### Describe the bug

These items do no stack despite nothing saying otherwise, having both equipped does not generate 2 random gems per mining action

### Reproduction Steps

Equip gem glove
Equip mining lesser relic
Mine gold ore

### Expected behaviour

Recieve 2 random gems

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7958

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Related #3636
