### ISSUE TITLE
[Bug]: Golden Wreath doesn't seem to be synergizing with Old Crafting Gloves

### ISSUE THREAD

**Issue by DimitrisPapas** [MelvorIdle/melvoridle.github.io#3759]
### Describe the bug

So, the "Old Crafting Gloves", the small artefact from the Monuments dig site, give you a chance to obtain GP while crafting and Golden Wreath is supposed to add a flat +100 GP on top of that amount. I have tried crafting the hard leather body, hard leather chaps and the golden sapphire necklace and it doesn't seem to be working for any of them, with the first two giving me just 7 GP when the gloves' effect procs and the necklace 37 if i recall correctly.

### Reproduction Steps

1. Equip both the Golden Wreath & the Old Crafting Gloves,
2. Go to the crafting tab and attempt to craft: Hard Leather Body, Hard Leather Chaps, Gold Sapphire Necklace, but presumably anything else too,
3. Check your GP amount before and after a proc of the gloves' effect

### Expected behaviour

I expected that whenever the "+10% chance to gain GP equal to 30% of the base sale price of the item crafted in Crafting" part of the Old Crafting Gloves rolled a success I would be getting an extra 100GP on top thanks to the "+100GP gained when earning GP, except Alt. Magic and Item Sales" effect of the Gloden Wreath.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7958

### Are you using any mods?

No

**Comment by Flurryous** [comment]
On a similar note, I noticed the peasant shirt's negative global gp modifier doesn't affect the crafting glove's effect either.

**Comment by MelvorIdle** [comment]
Thanks for the report. Fixed in Game Update - v1.2.1 ?7993
