### ISSUE TITLE
[Bug]: Prayer Relic 4 not working correctly

### ISSUE THREAD

**Issue by TheUberNoob1** [MelvorIdle/melvoridle.github.io#3760]
### Describe the bug

Prayer relic 4 not reducing prayer costs by 2.

Using only Incredible reflexes and 3 prayer points are still being deducted from prayer points total, instead of 1.

This was working previously.

### Reproduction Steps

Have Prayer relic 4
Use prayer with cost of more than one prayer point in combat
prayer point deduction not made

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/901pbUze

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7958

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Hello. The save you provided has the Cliff Balance agility obstacle active, which negates the bonus provided from the Ancient Relic.
