### ISSUE TITLE
[Bug]: Back button cause restart whole game

### ISSUE THREAD

**Issue by lister169126** [MelvorIdle/melvoridle.github.io#3761]
### Describe the bug

I use the back button every day many times. On mobile, especially as a gesture. In every game works fine and as expected. In every website written by other programmers works as intended, even as a smart back step in FE frameworks on single-views. In windows it works, in Linux it works. Nowhere else it causes restart of the application. 
I found some threads where the gamers talked about "one small issue". I found even the [mod](https://mod.io/g/melvoridle/m/back-button/). Why it isn't fixed yet? In the first three minutes of the game, I restarted it three times, in browser just once... It's unbelievable to trust that it is a small issue or no problem or just one issue.

### Reproduction Steps

1) open game
2) select save
3) click to back button on mouse / make back gesture / click on back button

### Expected behaviour

close window / action or back to last step

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7958

### Are you using any mods?

No

**Comment by samosbor** [comment]
+1 duplicate of https://github.com/MelvorIdle/melvoridle.github.io/issues/3549
