### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by ArcAngles84** [MelvorIdle/melvoridle.github.io#3762]
### Describe the bug

On birthday clue four. I am attacking bars with loot and sharp eye and looting amulet. I have not had clue 5 drop. What should I do?

### Expected behaviour

Clue 5 to drop

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

Notsure

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Can you please provide your save so we can take a look?

**Comment by Flurryous** [comment]
Some possible fixes: 
-Try relogging/relaunching the game. 
-Disable any mods you might have and relog/relaunch the game.
-See if the hunt reset by checking if clue 2 drops again 
-Sell and reclaim the clue from item log a few times to see if that works. Remember to reread the clue.  
-Reset the entire hunt by clicking the start hunt button in the birthday event page

If you don't mind using console, you can follow this: 
https://old.reddit.com/r/MelvorIdle/comments/16pd2mx/modconsole_command_to_unlock_the_5th_scroll/k1q8sg5/
