### ISSUE TITLE
[Bug]: Township - Casual Tasks - Unable to complete "Defeat Turkul General with Rune Shield equipped" when using gilded version

### ISSUE THREAD

**Issue by georgeRobertson2** [MelvorIdle/melvoridle.github.io#3763]
### Describe the bug

Possibly not a bug but definitely feels bad that upgrading your rune shield to a gilded version means you can't complete the task. I guess it's not much of an issue in standard mode as you can just make a new one, but it's definitely feels bad when in Ancient Relic mode or any other mode that places restrictions on the ways you can obtain items.

### Reproduction Steps

1. Get the `Defeat 0 / 10 Turkul General with **Rune Shield** equipped` casual task
2. Try to defeat Turkul General with Gilded Rune Shield
3. Task does not increase

### Expected behaviour

I would expect that you could complete the task with any variation of the Rune Shield. Why punish the player for upgrading the shield?

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7958

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This is not a bug and is intended. Casual tasks will sometimes make you do things that are outside your progression. If you're playing a gamemode with heavy restrictions, then you need to adapt to those restrictions. You can also Skip the task when you have enough GP.
