### ISSUE TITLE
[Bug]: Barrier burn doing no damage

### ISSUE THREAD

**Issue by wolfdyke** [MelvorIdle/melvoridle.github.io#3765]
### Describe the bug

Barrier burn ticks for 0 damage. Specter/Tortoise with no synergy active, with barrier burn being achieved via Barrier Burn shield in passive slot. Noticed and tested in particular on Crystal Shatterer. Valor and Battleborn active.
I typically use mods but disabled them all when attempting to reproduce the issue, and reproduced it successfully.

### Reproduction Steps

1. Equip item that causes barrier burn (barrier burn shield in passive slot was mine) and summons
2. Enter combat with Barrier enemy
3. Wait for barrier burn proc while barrier is up
4. Watch it tick for 0 dmg

### Expected behaviour

Was hoping it would do damage.

### Screenshots

![caughtoncamera](https://github.com/MelvorIdle/melvoridle.github.io/assets/147443068/d3392888-af09-436f-9ef4-936adbaf7091)
![Screenshot 2023-10-09 155712](https://github.com/MelvorIdle/melvoridle.github.io/assets/147443068/254499cd-2c0b-48ff-b5d1-0ed4bfc41ab0)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7958

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Thanks for the report. Fixed in Game Update - v1.2.1 ?7993
