### ISSUE TITLE
[Bug]: Visual bug: Basic Shortbow no longer has its modifier for its description

### ISSUE THREAD

**Issue by Flurryous** [MelvorIdle/melvoridle.github.io#3767]
### Describe the bug

The Basic Shortbow has a modifier that gives +1 hidden ranged level for every 2 ranged levels. Previously, this was listed in its item description, like with the Basic 2H Sword and Basic Staff. After the latest patch, it seems like the modifier is gone in the bow's description, though the other basic weapons still retain theirs. The modifier still works, so it's just a visual bug. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7958

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.2. If issue persists, please open a new issue.
