### ISSUE TITLE
[Bug]: Game still shows up as discord status even when set to be invisible

### ISSUE THREAD

**Issue by toadmilk** [MelvorIdle/melvoridle.github.io#3768]
### Describe the bug

Game still shows up as discord status even when set to be invisible. As I constantly have melvor open I would prefer it to instead be the game im actually playing.

There seems to be no in game setting to stop this and its starting to seriously annoy me.

### Reproduction Steps

1. Set melvor idle to be invisible on discord
2. Play another game
3. Observe status is still melvor idle

### Expected behaviour

I expected that it would no longer show up as my discord status. 

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/48373163/ffe07cf4-a5be-484a-94da-7f00fe83f4c9)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/48373163/53698841-8314-46da-890b-f095934b3e88)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7958

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
A setting is on the way with the next update which will allow you to disable this from within Melvor.

**Comment by toadmilk** [comment]
> A setting is on the way with the next update which will allow you to disable this from within Melvor.

Cheers mate

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.2. If issue persists, please open a new issue.

**Comment by Founntain** [comment]
Is there any ETA on this when the toggle will be available, I slowly starting to get a bit annoyed by the fact, that the Melvor Idle basically Hides all activities on Discord because the game runs all the time in the background.

Cheers

**Comment by CodeyFlex** [comment]
You can disable the Discord RPC by deleting the discord.js file in the package.nw located in the game folder.

**Comment by Founntain** [comment]
> You can disable the Discord RPC by deleting the discord.js file in the package.nw located in the game folder.

Finally an answer that is actually helpful if the devs don't want to implement a very simple toggle after all this time.

**Comment by Lyssa112** [comment]
sorry for replying but thank you, it helped me. tried to figure it out and didnt find a solution till I stumbled upon this post. should be a priority imo as it's an idle game running mostly 24/7 on the 2nd monitor
