### ISSUE TITLE
[Bug]: Barrier Igniter Potion does no damage to the barrier.

### ISSUE THREAD

**Issue by Cheese269** [MelvorIdle/melvoridle.github.io#3769]
### Describe the bug

Title.
It does however do HP damage if and only when the barrier is down.

### Reproduction Steps

Kill shit with barriers. 
I tried **Crystal Shatterer**s and **Crystal Behemoth**s.

### Expected behaviour

Damage to Barrier.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7958

### Are you using any mods?

Yes

**Comment by Cheese269** [comment]
Apparently it's already been reported and I missed it when I made the post. 
I'm unsure how to delete it.

**Comment by MelvorIdle** [comment]
I'll leave this one up but will tag the original report - #3765

**Comment by MelvorIdle** [comment]
Fixed in Game Update - v1.2.1 ?7993
