### ISSUE TITLE
[Bug]: Crow + Octo applied twice

### ISSUE THREAD

**Issue by mythridium** [MelvorIdle/melvoridle.github.io#3770]
### Describe the bug

Crow + Octo synergy is applied twice when creating water based runes, with the first allowing for doubling while the second does not

### Reproduction Steps

Equip Crow + Octo tablets
Create some water based runes

### Expected behaviour

Should only apply once

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/132613374/7e7eb225-fb6a-4c3e-83d6-0411622ef6c5)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari
- [X] Steam
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

7958

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Fix in Game Update - v1.2.1 ?7993
