### ISSUE TITLE
[Bug]: Lemon Season does not show up in the list of seasons

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#3771]
### Describe the bug

The Lemon season is not shown in the list of season when the player has access to said season. Nightfall and Solar Eclipse currently have this functionality already.

### Reproduction Steps

1. Obtain Lemon season Ancient Relic
2. Open Season list
3. Where Lemon???

### Expected behaviour

The Lemon season and it's modifiers should be shown in the Season list if the player has the respective modifier that enables the season and hidden otherwise, same as Nightfall and Solar Eclipse.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/b2fa83fb-a06b-4138-97f9-5ac7b2da5cb1)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/4cb91412-ac05-4a4a-83c1-3f4a45c88382)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7958

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.2. If issue persists, please open a new issue.
