### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by Sirfr3d** [MelvorIdle/melvoridle.github.io#3772]
### Describe the bug

Shows wrong idle screen

### Reproduction Steps

Start combat with autoslayer, go to cooking while in combat, log out/exit app. Next screen will be loot screen and cooked items.

### Expected behaviour

Shows wrong idle screen.

### Screenshots

![IMG_0761](https://github.com/MelvorIdle/melvoridle.github.io/assets/147586036/c74b9741-e386-4628-aeb6-9886a99f1c00)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7958

### Are you using any mods?

No

**Comment by DimitrisPapas** [comment]
If you left the loot on the ground when you went cooking then I think the game just informs you that you still have unclaimed loot lying there. Not necessarily that you farmed it while you were offline.

**Comment by MelvorIdle** [comment]
The Offline popup will always display what loot is sitting inside the Loot Container waiting to be collected as a reminder to grab it incase it disappears.
