### ISSUE TITLE
[Bug]: Melvor idle Birthday event

### ISSUE THREAD

**Issue by jetro400** [MelvorIdle/melvoridle.github.io#3777]
### Describe the bug

I can"t get past clue nr 4 i don't know what i'm doing wrong.
This is the description i've been following.
Things start getting tricky with Clue Scroll #4. The solution here is to defeat the Wandering Bard with three specific things equipped. You can only find the Wandering Bard via Normal Slayer Tasks—they cannot be found in a dungeon or combat area. You need to defeat the Wandering Bard while having the Almighty Lute, Amulet of Looting, and Sharp Eye Prayer equipped. The Almighty Lute actually drops off the Wandering Bard, so you will have to kill them more than once if you have not before.

### Console output

![Knipsel](https://github.com/MelvorIdle/melvoridle.github.io/assets/146389070/0f717666-a1a5-4577-a184-f3ca9b7a5d44)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

V1.2.1 (?7993)

### Are you using any mods?

Yes

**Comment by Flurryous** [comment]
Some possible fixes:
-Try relogging/relaunching the game.
-Disable any mods you might have and relog/relaunch the game.
-See if the hunt reset by checking if clue 2 drops again
-Sell and reclaim the clue from item log a few times to see if that works. Remember to reread the clue.
-Reset the entire hunt by clicking the start hunt button in the birthday event page

If you don't mind using console (there's also a mod for a dev console), you can follow this:
https://old.reddit.com/r/MelvorIdle/comments/16pd2mx/modconsole_command_to_unlock_the_5th_scroll/k1q8sg5/
