### ISSUE TITLE
[Bug]: Steam account not recognized in Melvor

### ISSUE THREAD

**Issue by GokuK67** [MelvorIdle/melvoridle.github.io#3783]
### Describe the bug

I bought the full version of Melvor Idle + the two DLC's on Steam. The Melvor game I bought only 2 days ago, the both DLCs I  bought today. I'm a fresh player. 

When I start playing Melvor from the Steam launcher, the game does not get the SteamID correctly and it plays the free version. My Steam account and the DLC are both marked in red on the top left, and appear not recognized.
The popup screen says to log in to the correct Steam account and relaunch, but it doesn't make any difference. 
I have only 1 Steam account BTW, and my other games launch fine.
I am on SteamOS, not Windows nor MacOS.

### Reproduction Steps

Every time I start the game, it does not register that I bought the full version, the same goes for both DLC's as well. The game is playable, but it is probably a demo version.

### Expected behaviour

I should have all the commercial functionality available. One of which is cap to lvl 120 instead of the original 99.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?

### Are you using any mods?

No

**Comment by Flurryous** [comment]
Try verifying the game files or reinstalling.

**Comment by GokuK67** [comment]
Thanks for the suggestion, I failed to mention that I reinstalled twice and also tried to switch to compatibility with several versions of Proton. Had to switch back to SteamOS version, as at least the demo version runs.

**Comment by Flurryous** [comment]
Try switching compatibility to Steam Linux Runtime. That seems to resolve another issue involving the Steam Deck or SteamOS, so it could work here. If not, hopefully this gets around to being fixed.

**Comment by GokuK67** [comment]
I fixed it, by installing Melvor on my Steam Deck. Figured that I didn't want to play Melvor on the Deck, but that did the trick. Appearently my Steam Account got linked to my Melvor Account through the Steam Deck, where it wouldn't through the PC launcher. The Deck showed all green marks on the purchases.
Not sure if cloudsave on Deck was necessary, but I did that before checking on the PC again.
Anyways, the PC now recognizes my purchase as well.

**Comment by GokuK67** [comment]
Actually for Melvor players who do not own a Steam Deck, the issue may not be solved. So I reopen the issue for now.

**Comment by gykfSAFF** [comment]
not warking

**Comment by MelvorIdle** [comment]
The original issue was resolved, so I will close this. In the event someone else is having trouble, they will need to open a new issue with relevant information to their specific setup.
