### ISSUE TITLE
Cartography won't load on m1 macbook pro [Bug]: <title>

### ISSUE THREAD

**Issue by mmark1994** [MelvorIdle/melvoridle.github.io#3784]
### Describe the bug

Running MacOS 12.5.1. Just purchased cartography expansion and having fun so far on Windows systems. When I click on the skill, the page does not load so I can not click on anything. The background art is a night sky in a valley, with a tower and moon on the right, which load. The left pane loads, as does the top pane. However, when I click on any other skill or page AFTER clicking on cartography, nothing changes and those pages won't load either. I have to refresh melvor to access the game again, and cannot click on cartography at all.

EDIT: As I was taking a screenshot, another bug popped up that seems to only happen when selecting cartography. This bug says the following:

An error occurred while rendering:
Error Name: TypeError
Error Message: this.hexOverview.updateQuantities is not a function
Stack Trace:
TypeError: this.hexOverview.updateQuantities is not a function
    at HTMLElement.updateOverviewQuantities (https://melvoridle.com/assets/js/built/cartographyMenu.js?7994:49:45)
    at Cartography.renderHexOverviewQuantities (https://melvoridle.com/assets/js/built/cartography.js?7994:62:23)
    at Cartography.render (https://melvoridle.com/assets/js/built/cartography.js?7994:42:61)
    at https://melvoridle.com/assets/js/built/game.js?7994:206:63
    at Map.forEach (<anonymous>)
    at NamespaceRegistry.forEach (https://melvoridle.com/assets/js/built/namespaceRegistry.js?7994:43:44)
    at Game.render (https://melvoridle.com/assets/js/built/game.js?7994:206:39)
    at Game.loop (https://melvoridle.com/assets/js/built/game.js?7994:237:35)

Active Action: melvorD:Agility
Current Equipment:
Helmet: melvorD:Crown_of_Rhaelyx
Platebody: melvorF:Sailors_Top
Boots: melvorF:Boots_Of_Stealth
Weapon: melvorD:Bobs_Rake
Amulet: melvorD:Clue_Chasers_Insignia
Ring: melvorD:Ancient_Ring_Of_Skills
Gloves: melvorF:Thieving_Gloves
Cape: melvorD:Firemaking_Skillcape
Summon1: melvorF:Summoning_Familiar_Ent

Action Information:
Is Active: true

Active Obstacle Tier: 7
Built Obstacles (tier|obstacleID):
0:melvorF:CargoNet
1:melvorF:BalanceBeam
2:melvorF:PitJump
3:melvorF:GapJump
4:melvorF:CliffBalance
7:melvorF:TreeHang
6:melvorF:HeatTrap
5:melvorF:RaftDrifting
Modding Disabled

### Reproduction Steps

Click on cartography
That's it. Nothing loads after that, even when clicking back to other skills which work if selected before clicking on cartography.

Note: A new bug appeared telling me to refresh cache on Android. Included in screenshot

### Expected behaviour

I expect that the cartography map loads properly.

### Screenshots

![SCR-20231018-9ol](https://github.com/MelvorIdle/melvoridle.github.io/assets/56123723/d25d6495-846e-4d1f-89e7-111261744a0b)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7994

### Are you using any mods?

No

**Comment by jonesey438** [comment]
I am also having this issues on Windows/Firefox.

**Comment by JopV** [comment]
I have the Same issue on Chrome on an Macbook Air M2.  
Even after completely clearing my Cache and reloading, the bug persists.  


```
An error occurred while rendering:
Error Name: TypeError
Error Message: this.hexOverview.updateQuantities is not a function
Stack Trace:
TypeError: this.hexOverview.updateQuantities is not a function
    at HTMLElement.updateOverviewQuantities (https://melvoridle.com/assets/js/built/cartographyMenu.js?8448:49:45)
    at Cartography.renderHexOverviewQuantities (https://melvoridle.com/assets/js/built/cartography.js?8448:62:23)
    at Cartography.render (https://melvoridle.com/assets/js/built/cartography.js?8448:42:61)
    at https://melvoridle.com/assets/js/built/game.js?8448:206:63
    at Map.forEach (<anonymous>)
    at NamespaceRegistry.forEach (https://melvoridle.com/assets/js/built/namespaceRegistry.js?8448:43:44)
    at Game.render (https://melvoridle.com/assets/js/built/game.js?8448:206:39)
    at Game.loop (https://melvoridle.com/assets/js/built/game.js?8448:237:35)

Active Action: melvorD:Combat
Current Equipment:
Helmet: melvorF:Slayer_Helmet_Elite
Platebody: melvorF:Slayer_Platebody_Elite
Platelegs: melvorF:Ragnar_God_Platelegs
Boots: melvorAoD:Elusive_Boots
Weapon: melvorF:Infernal_Claw
Shield: melvorF:Knights_Defender
Amulet: melvorD:Bone_Necklace
Ring: melvorF:Ring_Of_Wealth
Gloves: melvorF:Ragnar_God_Gloves
Cape: melvorAoD:Ancient_Infernal_Cape
Passive: melvorF:Blazing_Lantern
Consumable: melvorF:Looter_Pouch
Gem: melvorAoD:Accuracy_Gem

Action Information:
Is In Combat: true
Fight in Progress: true
-- Start of Player Information --
Next Action: Attack
Next Attack: melvorD:Normal
Is Attacking: false
Standard Spell Selected: melvorD:WindStrike
Ancient Spell Selected undefined
Aurora Selected: undefined
Curse Selected: undefined
Active Prayers: None
Equipped Food:
Item: melvorTotH:Magma_Fish_Perfect, Qty: 8672
-- End Player Information --
-- Start of Enemy Information --
Enemy: melvorF:BountyHunter
Next Action: Attack
Next Attack: melvorD:Normal
Is Attacking: false
Standard Spell Selected: melvorD:WindStrike
Ancient Spell Selected undefined
Aurora Selected: undefined
Curse Selected: undefined
-- End Enemy Information --
Current Area Type: Slayer
Current Area ID: melvorF:Shrouded_Badlands
Modding Enabled. Loaded mods:
[Myth] Combat Simulator
