### ISSUE TITLE
[Bug]: You were gone for 0 seconds

### ISSUE THREAD

**Issue by HamR88** [MelvorIdle/melvoridle.github.io#3785]
### Describe the bug

Since the release of Throne of the Herald I've had multiple instances where I locked my phone on Melvor Idle before going to bed, to be greeted by a message saying 0 seconds of progress had been gained the following morning.
About 8 hours have passed but I get none of the progress, this has happened at least 5 times.

This doesn't occur when fully closing the application before locking for longer periods of time.

Warning: This problem is hard to reproduce, it doesn't happen every time.

### Reproduction Steps

Open Cartography world map
Lock phone (physical button)
Wait
Unlock phone
There's about a 25% chance that the time has not been tracked.

### Expected behaviour

I expect to see the progress pop-up with an accurate account of the time passed since the phone was locked.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7994

### Are you using any mods?

No

**Comment by daveslutzkin** [comment]
I've seen this, the workaround is just to kill the app and reload your cloud save. You'll then get all the progress you were due.

**Comment by HamR88** [comment]
> I've seen this, the workaround is just to kill the app and reload your cloud save. You'll then get all the progress you were due.

Last night I've turned on crafting refined pure crystals, I turned Melvor on this morning and had 0 seconds of progress again. Closed the app and reloaded my save but I still got nothing, I've got 500 refined pure crystals and they've all been made sitting here typing this.

**Comment by daveslutzkin** [comment]
@HamR88 that's weird, did you reload your cloud save or your local save?

**Comment by HamR88** [comment]
> @HamR88 that's weird, did you reload your cloud save or your local save?

Well I tried the local save first, that doesn't help, the cloud save is usually from the night before but some progress may still be lost if not saved before exiting.
 
> If you're worried about it happening just kill the app/swipe it away before you go to bed. When you open it again and reload in the morning it will just do all the offline progress and you'll get your crystals.

Yeah I'll probably do that from now on until (and if) this is resolved.

**Comment by RayRayToo** [comment]
I also experience this 0 second around 3-4 times a week. I cant reload the cloud save, because as soon as I enter the game it saves into the cloud. I have tried reloading the cloud save instead of local, but the same thing happens.

I have noticed this error happening more often if I am doing combat when exiting the game. No experience or loot and my plants did not grow at all.

**Comment by MelvorIdle** [comment]
Its best practice to always minimise the app or close it when going offline. If you lock your phone when the app is active, then the game doesn't have time to process its "pause" because the device has already killed that connection.
