### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by Forhowmuch** [MelvorIdle/melvoridle.github.io#3788]
### Describe the bug

Unable to "bury item" Medium Urn (Enchanted).
The icon "button" for "burry item" is grayed out / transparrent.

### Expected behaviour

Medium Urn (Enchanted) should have the icon not grayed out / transparrent and be able to be used to gain prayer points.

### Screenshots

![Skjermbilde 2023-10-19 142030](https://github.com/MelvorIdle/melvoridle.github.io/assets/148455172/893e5950-22a7-4b7d-bd91-99e436dfcadd)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7994

### Are you using any mods?

Yes

**Comment by 04Slash** [comment]
You cannot bury locked items. You need to unlock it first.
