### ISSUE TITLE
[Spelling/Grammar]: Astrology Game Guide - Continueing

### ISSUE THREAD

**Issue by OrdinaryOx** [MelvorIdle/melvoridle.github.io#3791]
### What text is wrong?

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/92575838/bbc0c89e-7a54-461c-85ec-7068e47e41ac)
--> ![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/92575838/ae4db98b-9f23-4baf-9e9e-ebf97433fd1c)

### What is the correct spelling or grammar?

Continuing

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.2. If issue persists, please open a new issue.
