### ISSUE TITLE
[Bug]: slayer armor not unlocking in shop

### ISSUE THREAD

**Issue by dmlarson** [MelvorIdle/melvoridle.github.io#3792]
### Describe the bug

Stats say I have more than 6 normal or higher tasks complete
![Screenshot_20231020-164133](https://github.com/MelvorIdle/melvoridle.github.io/assets/3615330/793d3498-eb38-48f6-a803-7a162ecd3291)

I have enough slayer coins
![Screenshot_20231020-164142](https://github.com/MelvorIdle/melvoridle.github.io/assets/3615330/e2145faa-cc19-42bf-81f3-4a0df9a35a3d)

Won't let me buy slayer armor
![Screenshot_20231020-164156](https://github.com/MelvorIdle/melvoridle.github.io/assets/3615330/ab184468-b652-47f9-9d98-8d4f01a44921)

Google chrome app on Android 14 device
Melvore and 1st expansion bought

### Expected behaviour

I should be able to purchase the armor

### Save Link - Required if issue occurs with a save

https://melvoridle.com/b93f3ae7-db62 -481a-b3b7-87dfa83b8897

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

7994

### Are you using any mods?

No

**Comment by Flurryous** [comment]
It says you need to complete 6 more normal or higher tasks. You need 15 total to unlock them., and you're currently at 8 normal + 1 hard = 9 total.

**Comment by dmlarson** [comment]
Misread

**Comment by dmlarson** [comment]
> It says you need to complete 6 more normal or higher tasks. You need 15 total to unlock them., and you're currently at 8 normal + 1 hard = 9 total.

Misread, thank you
