### ISSUE TITLE
[Bug]: Old Crafting Gloves interaction

### ISSUE THREAD

**Issue by Flurryous** [MelvorIdle/melvoridle.github.io#3793]
### Describe the bug

The old crafting gloves' description states that it has a 10% chance of gaining gp equal to 30% of the base sale price of the crafted item. However, it seems the gloves are actually converting to 10% of the base sale price instead of 30%. 

### Reproduction Steps

1. Equip the old crafting gloves.
2. Create something in crafting, let's say refined pure crystal (1000 gp base sale price).
3. Notice that you only get 100 gp when the gloves' effect activate, 10% of the base sale price. 

### Expected behaviour

The base gp gained from the crafting glove effect should be either be 30% or the description should say the correct value if 30% wasn't the intended amount. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [x] Throne of the Herald
- [x] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7994

### Are you using any mods?

Yes

**Comment by Flurryous** [comment]
I just realized that lep + beaver synergy shares the exact same wording as old crafting gloves ("base sale price") and actually works the same way, being unaffected by global gp bonuses, so this is probably intentional for old crafting gloves too. I'll edit out that part of the bug report, but it still seems like the gloves are still giving less than the intended amount.

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.2. If issue persists, please open a new issue.
