### ISSUE TITLE
[Bug]: Summoning Centaur tablet

### ISSUE THREAD

**Issue by StressedEnd** [MelvorIdle/melvoridle.github.io#3796]
### Describe the bug

In the Summoning tab when wanting to create the Centaur tablet, the requirements don't add up. When selecting the type of bow, 3 magic bows are required, but 50 redwood bows are required for the next step.

### Expected behaviour

You'd expect the last obtainable wood/bow type to cost 1 instead of 50.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/148707843/d870ebf6-5d6e-48c7-9baa-321cdfdff608)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7994

### Are you using any mods?

No

**Comment by Flurryous** [comment]
The amount of materials used to make tablets is based off sale price. Magic bows have a much higher sale price than redwood bows.
