### ISSUE TITLE
[Spelling/Grammar]: Stone Statue name-ID discrepancy

### ISSUE THREAD

**Issue by Tamaru** [MelvorIdle/melvoridle.github.io#3798]
### What text is wrong?

While the "Stone Statue" archaeology item's Wiki link and Item ID point to/are "Stone_statue", the page for the item is at https://wiki.melvoridle.com/w/Stone_Statue vs. https://wiki.melvoridle.com/w/Stone_statue

### What is the correct spelling or grammar?

Either fix the Wiki URL or the item ID, whichever is appropriate.

**Comment by Auron956** [comment]
I have made an amend on the wiki side so that users will now land on the correct page when using the in-game link. Perhaps worth leaving open should the developers wish to amend the in-game implementation of wiki links separately (I'm unsure if anything else is impacted by this).
