### ISSUE TITLE
[Spelling/Grammar]: Incorrect item description on Aorpheat's Signet Ring

### ISSUE THREAD

**Issue by Knyffen** [MelvorIdle/melvoridle.github.io#3799]
### What text is wrong?

The item description for Aorpheat's Signet Ring states "+100% GP granted from all sources except Alt. Magic and Item Sales".
The GP increase also doesn't affect Township taxes and tasks, so Township should be added to the list.

### What is the correct spelling or grammar?

"+100% GP granted from all sources except Alt. Magic, Township, and Item Sales"

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.2. If issue persists, please open a new issue.
