### ISSUE TITLE
Adventure Log

### ISSUE THREAD

**Issue by mrDLSable** [MelvorIdle/melvoridle.github.io#38]
I would like for there to be an adventure log with the following things:

- How many times you have defeated each dungeon.
- How often you have defeated each monster.
- What you have gotten from chests.
- What unique drops you have gotten.

**Comment by MelvorIdle** [comment]
Would this be specifically for dungeons? I really like this idea.

**Comment by mrDLSable** [comment]
Also for normal monsters and drops. I think this would add another sense of achievement for late game players. Plus, I suspect there would be a lot of code overlap with the quest system. The whole keeping track of killed monsters and received drops.

**Comment by MelvorIdle** [comment]
Monster kills will be tracked in the next update, so I'll see what other things I could add to it to make it more in-depth.

**Comment by mrDLSable** [comment]
Very nice :) If I have any other ideas for an adventure log I'll post them :)

**Comment by mrDLSable** [comment]
It might be nice for the adventure log to show the enemy drop table. But only if you have killed an x number of enemies. Like 100 for example.
