### ISSUE TITLE
[Bug]: Cartography's Spider Forest Hex bonus not working against Underwater Ruins passive

### ISSUE THREAD

**Issue by Flurryous** [MelvorIdle/melvoridle.github.io#3801]
### Describe the bug

Spider Forest's hex bonus is a 50% chance to ignore slow effects, doubled to 100% once you achieve all hex masteries. Underwater Ruins mobs have a passive that applies a slow effect to the player that persists until the end of the fight. However, it seems that the Spider Forest hex does not counter this passive effect. 

I tested the hex with Alraune and Umbora who both have an attack that slows and it seems like the hex bonus works in that case, so it seems like it's only a problem if the slow is part of a passive effect. 

### Reproduction Steps

1. With full hex mastery, set your active cartography point of interest to Spider Forest. 
2. Fight any mob in the Underwater Ruins.
3. See that the passive slow effect for the area applies to you. 

### Expected behaviour

Spider Forest's hex bonus should work on the passive slow effect of the Underwater Ruins. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7994

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.2. If issue persists, please open a new issue.
