### ISSUE TITLE
[Bug]: Goblin Raid broke my save

### ISSUE THREAD

**Issue by NeonGreenYogurt** [MelvorIdle/melvoridle.github.io#3802]
### Describe the bug

I was just playing through the Goblin Raid and around wave 18 I had the Umbra sword as an option, when I clicked it the game showed the sword go into my weapon slot, but the select screen didn't/wouldn't close. Tried to click other options, and the nothing option and nothing would happen. I was able to leave the Goblin Raid, but I came to the main screen with all my skills saying lv1 until I clicked on them which would bring them back to their proper levels. Though, I couldn't DO any skills and I can't start combat or anything. Save is completely locked up. I also can't get back into the Goblin Raid minigame either.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7994

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Please provide a copy of your save so we can take a look and provide a fix.
