### ISSUE TITLE
[Bug]: Having issue on closing the game in Steam

### ISSUE THREAD

**Issue by IF-chan** [MelvorIdle/melvoridle.github.io#3803]
### Describe the bug

Today I close the game in steam. The game is closed but it shows that it's still running in Steam.
And I can't force to stop it and restart the game. (I must quit Steam)

### Reproduction Steps

Just start the game in Steam and close

### Expected behaviour

I must quit Steam to restart the game.

### Screenshots

![QQ截图20231024200617](https://github.com/MelvorIdle/melvoridle.github.io/assets/98469234/f90dc92b-be7c-4094-9f8b-6a973b7a8efe)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7994

### Are you using any mods?

No

**Comment by Kyoj1n** [comment]
I am having this exact same problem as well.

**Comment by IF-chan** [comment]
Now on v1.2.2 it happens again

**Comment by IF-chan** [comment]
> After a while it does not occur **BUT** now on v1.2.2 ?8604 it happens again

But I can avoid it by closing the game when on selecting character screen
