### ISSUE TITLE
[Bug]: Incorrect Prayer Points Consumed

### ISSUE THREAD

**Issue by Sphynxtank** [MelvorIdle/melvoridle.github.io#3804]
### Describe the bug

From testing, it appears all prayers are consuming 2 extra points and it's compounding. 

### Reproduction Steps

1. Activate any single prayer
2. Attack Hill Giants
3. Have Dragon Sword and either no shield, shield, or defender equipped
4. Monitor prayer points
5. Profit

### Expected behaviour

When prayer states: "Prayer Point Cost: 2 per attack" only for it to consume 2 per attack, not 4.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/XJ34ACH0

### Screenshots

![Screenshot_20231024_082032_Melvor Idle](https://github.com/MelvorIdle/melvoridle.github.io/assets/148871898/efcd3f4e-4690-4ee7-a13a-f82098f44160)
![Screenshot_20231024_082034_Melvor Idle](https://github.com/MelvorIdle/melvoridle.github.io/assets/148871898/cc3d1d3c-9b2a-44a0-a9b9-ca139965ea39)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

? 7994

### Are you using any mods?

No

**Comment by 04Slash** [comment]
Seems to be working as intended:
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/9ee3ff80-188d-4174-8950-5b30bba2db6b)
