### ISSUE TITLE
[Bug]: <title> equipment swapping in impending darkness

### ISSUE THREAD

**Issue by Batvincey** [MelvorIdle/melvoridle.github.io#3805]
### Describe the bug

While doing the impending darkness event when i swap to the optimal equipment according to combat triangle it will miss every attack until switched back to the original gear setup. is this intentional?

### Reproduction Steps

1 go to impending doom
2 start combat in any of the available areas
3 switch gear to take advantage of combat triangle
4 miss every attack
5 switch back to first gear used when going into particular combat area
6 hit as normal

### Expected behaviour

when switching gear i expect to be able to hit as normal not be unable to hit at all

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7994

### Are you using any mods?

No

**Comment by ekuland** [comment]
Bane, Instrument of Fear:
Afflicted Might:
All attacks have +50% chance to inflict affliction. **Immune to all attack types other than their own.** Immune to Stun, Freeze, Sleep, Curses and Slow.

**Comment by Batvincey** [comment]
Is not the issue, i used melee for all monsters as that was my initial gear
selected but was able to kill ranged and mage monsters all the same just
not in optimal gear. It would work when going into a new Slayer area and
selecting different gear before starting the area

Op wo 25 okt. 2023 20:22 schreef ekuland ***@***.***>:

**Comment by Batvincey** [comment]
resolved, it was me not wearing a slayer cape/max cape in the other equipment setups.
