### ISSUE TITLE
[Bug]: Ceramic Pot not functional

### ISSUE THREAD

**Issue by Flurryous** [MelvorIdle/melvoridle.github.io#3806]
### Describe the bug

Ceramic Pots have a 30% chance to give an additional soup when making soup. However, it doesn't seem like it activates at all. 

### Reproduction Steps

1. Equip Ceramic Pots.
2. Go to the cooking skill page, make any soup.
3. As you're making soup, notice that at no point you're getting an additional soup, though if you had the Divine Pot and Divine Furnace upgrades from ToTH, you can see an additional soup from them. 

### Expected behaviour

I expect Ceramic Pots to work with cooking soup. 

### Screenshots

https://cdn.discordapp.com/attachments/625841473731952688/1166914031647477760/image.png?ex=654c3861&is=6539c361&hm=6b518de90f58ed7e15fea96b74b54d1f64dfcad3657d8bdf347c87b0dd95f05e&

"[Ceramic Pot] will never match any soup because it checks against _soup in lowercase, but the localID never gets toLowerCase() "

-Credit to Mythridium from the discord for the screenshot and explanation on why the item is bugged. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [x] Throne of the Herald
- [x] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7994

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.2. If issue persists, please open a new issue.
