### ISSUE TITLE
[Bug]: Fishing level reset to level 3??

### ISSUE THREAD

**Issue by mcardlemi** [MelvorIdle/melvoridle.github.io#3807]
### Describe the bug

I have an old account from before tutorial island was made. I got 99 fishing first and have the cape to prove it. When logging in today my fishing level is lvl 3 and i can't equip my cape. 
you can even see I have mastery levels on my account for 96.73%  and if possible to look at i have mastery levels for everything including the whale. currently at 63
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/146790048/4516e397-4cbc-44f7-a263-cc5263a84358)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/146790048/80cad979-4308-43a2-bc84-80e2d2d6964d)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/146790048/e1f41467-9eb5-4246-ac34-f5f186542140)

### Reproduction Steps

have an account with level 99 fishing.
fish on tutorial island gaining experience?
switch to a new task before leaving tutorial island?
when you load the game next your level might be reset?

Those are the only steps i could think happen with fishing.

### Expected behaviour

I would expect that I still have level 99. 

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/Dgl03ZiD

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/146790048/4516e397-4cbc-44f7-a263-cc5263a84358)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/146790048/80cad979-4308-43a2-bc84-80e2d2d6964d)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/146790048/e1f41467-9eb5-4246-ac34-f5f186542140)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7994

### Are you using any mods?

No

**Comment by Zarrck** [comment]
Same issue here with multiple skills. An old account, playing without expansions on chrome. Game Version V1.2.1?7994
I think it might have something to do with offline progression but not sure. In my case Strength, HP & Farming were affected
