### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by iBreakEverything** [MelvorIdle/melvoridle.github.io#3809]
### Describe the bug

[Gold Sapphire Ring](https://wiki.melvoridle.com/w/Gold_Sapphire_Ring) has a value of 266 and [Silver Sapphire Ring](https://wiki.melvoridle.com/w/Silver_Sapphire_Ring) has a value of 296. Unless this was intentional the values do not respect the norm set by the other crafted jewelry.

### Expected behaviour

Gold Sapphire Ring should have a higher GP value than Silver Sapphire Ring.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7994

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Not a bug, these are the intended prices.
