### ISSUE TITLE
Obtaining mysterious stones without crown of rhaelyx equipped

### ISSUE THREAD

**Issue by jotun00** [MelvorIdle/melvoridle.github.io#3811]
### Describe the bug

In Ancient Relic mode, I got crown of rhaelyx, equipped it, and then unequipped it and sold it.  I continue to get mysterious stones ad infinitum without the crown equipped or existing anymore on this save.  People have been posting about this problem online for almost a year.  Maybe fix it?  

Also, this system of reporting bugs is cancer.  Maybe find a better method, since you're charging for this buggy shit show.

### Reproduction Steps

Equip crown of rhaelyx.  Unequip crown of rhaelyx.  Sell crown of rhaelyx.  Do anything.

### Expected behaviour

When you don't have Crown of Rhaelyx equipped.... You shouldn't be getting mysterious stones..... which are created by having the crown of rhaelyx equipped..............

### Screenshots

![Capture](https://github.com/MelvorIdle/melvoridle.github.io/assets/149296188/1c3c4314-690d-4c73-b1dd-82eea45c7cf7)

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/149296188/84186c5a-b734-4eb6-a11b-cd5d50aefe62)

### Console output

n/a

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [x] Throne of the Herald
- [x] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

1.2.1

### Are you using any mods?

Yes

**Comment by ekuland** [comment]
Having crown equipped or even owned is not the requirement for stones. Having found a crown, ever, is.

**Comment by MelvorIdle** [comment]
This is not a bug. The requirement to get stones to drop is that you need to have **found** the Crown, whether its currently in your bank or not.
