### ISSUE TITLE
[Bug]: Monkey-Salamander summoning synergy is not applying to all jewelry

### ISSUE THREAD

**Issue by Arzonite** [MelvorIdle/melvoridle.github.io#3812]
### Describe the bug

The summoning synergy between Monkey and Salamander does not work on "Ring of Barrier Touch", "Amulet of Barrier Touch", "Unholy Ring" or "Unholy Amulet".

### Reproduction Steps

1. Equip Monkey and Salamander summoning tablets
2. Make sure the synergy is active (level 4 on both marks)
3. Navigate to "special items" tab within Crafting page
4. See that your preserve chance has, indeed, not increased

### Expected behaviour

The summoning synergy between Monkey and Salamander is supposed to give 33% preserve chance in crafting when making jewelry.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7994

### Are you using any mods?

No

**Comment by Arzonite** [comment]
This bug also applies to "Gem Preserver Scroll", and _presumably_ any effect that gives bonuses when crafting jewelry

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.2. If issue persists, please open a new issue.
