### ISSUE TITLE
[Bug]: Combat Minibar Text Interaction With Equipment Set

### ISSUE THREAD

**Issue by Sphynxtank** [MelvorIdle/melvoridle.github.io#3813]
### Describe the bug

The enemy health text is overlapped by your health when equipment set Minibar is disabled

### Reproduction Steps

1. While in combat, go to settings
2. Toggle: ON "Toggle Combat Minibar"
3. Toggle: OFF "Combat Minibar - Display Equipment Set Selection
4. Profit

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/gXPhS6qq

### Screenshots

![Screenshot_20231030_052151_Melvor Idle](https://github.com/MelvorIdle/melvoridle.github.io/assets/148871898/165a8e89-d3f1-4e9d-bea7-96669c7f70c6)
![Screenshot_20231030_052146_Melvor Idle](https://github.com/MelvorIdle/melvoridle.github.io/assets/148871898/31f714af-1011-4309-8093-29c7e4910288)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7994

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Related #3795
