### ISSUE TITLE
Cannot build in agility 

### ISSUE THREAD

**Issue by Playinagame** [MelvorIdle/melvoridle.github.io#3815]
### Describe the bug

Unable to build obstacles in agility causing the skill to be unusable. 

### Reproduction Steps

Got to agility and tap "obstacle 1". Select the obstacle to build and see no build button, confirmation, prompt pop up. 

### Expected behaviour

A prompt to confirm building the obstical to pop up when selecting the obstical

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7994

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This is due to you not having the required GP, Items or levels to build the obstacle
