### ISSUE TITLE
[Bug]: cartography

### ISSUE THREAD

**Issue by Sixtybones** [MelvorIdle/melvoridle.github.io#3816]
### Describe the bug

I’ve explored the entire cartography map and am currently mastering all the tiles, I’m at 155+ and I’ve noticed the task for discovering 132 points of interest may be incorrect as I’ve only found 123. 
![IMG_1119](https://github.com/MelvorIdle/melvoridle.github.io/assets/149625699/cafe6a76-6e00-4b04-af26-6586a8288596)
![IMG_1120](https://github.com/MelvorIdle/melvoridle.github.io/assets/149625699/85cbbb8a-d178-46db-b066-eeac6114c5e4)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7994

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Can you please provide your save? I can't reproduce this on my end.

**Comment by Sixtybones** [comment]
https://melvoridle.com/save/2Q6aNBPu

Jordan R
________________________________
