### ISSUE TITLE
[Bug]: Visual Bug: Farming exp and mastery show the value of the last thing planted

### ISSUE THREAD

**Issue by Flurryous** [MelvorIdle/melvoridle.github.io#3818]
### Describe the bug

The farming exp and mastery display only shows the exp and mastery of the last crop you planted, regardless of what crop you're looking at. For example, if you only plant apple trees, you'll see that the exp for harvesting them is accurate. However, if you plant potatoes right after planting apple trees, the exp and mastery displayed on the apple trees will change to the exp and mastery  for harvesting potatoes. 

### Reproduction Steps

1. Plant an apple tree. Check the exp and mastery.
2. Plant a potato. Check the exp and mastery of the tree again. Notice that they changed to match the values of the potato's. 

### Expected behaviour

I expect the exp and mastery values to match instead of changing into the values of the last crop planted.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7994

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.2. If issue persists, please open a new issue.
