### ISSUE TITLE
Offline woodcutting with multi-tree calls rollForRhaelyx twice as much as it should

### ISSUE THREAD

**Issue by 8992scripts** [MelvorIdle/melvoridle.github.io#382]
You need to be cutting two trees at once for it to happen and has to be offline.
The bug can easily be seen if you change the Rhaelyx droprate to 100%, you get twice as many Rhaelyx as you get logs.
Looking at the code I think it may be in this part:
if (offline.action[1] !== undefined) {

Looks likely that pet drop and signet may also be affected by this bug (rolls total actions of both trees for each tree from my understanding)

**Comment by MelvorIdle** [comment]
Wow, how did I manage to pull that off. I can't believe I treated it as separate actions per tree. Totally a brain fart on my end.

Thanks for the report. I just applied a hotfix to this.
