### ISSUE TITLE
[Bug]: Big Ol' Ron damage decreasing over time.

### ISSUE THREAD

**Issue by BigRanch** [MelvorIdle/melvoridle.github.io#3820]
### Describe the bug

While AFKing Earth God Dungeon with Big Ol' Ron, over the course of 2-3 hours, minimum and maximum hit continuously decreases periodically. 

I have replicated this issue 3 times. 

The damage dealt is decreased, not just displayed incorrectly. 

Possibly an interaction with ring of blade echoes. 

Lowest I have seen it go is 0 min, 400 max after coming back after 3 hours (The game is running continuously, and NOT offline progressing). Unequipping and Re-Equipping restores damage stats to proper damage ~100 min ~1000 max.

Setup:
Full Ragnar Set
Passive - Wasteful Ring
Cape - Infernal Cape
Neck - Elite Glory
Consumable - Whetstone
Ring - Ring of Blade Echoes
Weapon - Big Ol' Ron
No Summons
DR% Prayers
Diamond Luck Potions

### Reproduction Steps

1. Equip Set Up Above
2. Enter Earth God Dungeon
3. Minimize the game for a few hours
4. Come back and observe damage decrease
5. Unequip and Re-equip Big Ol' Ron to reset
6. Repeat

### Expected behaviour

Normal Combat Behavior

### Screenshots

![Before](https://github.com/MelvorIdle/melvoridle.github.io/assets/149914387/a5ed8a9b-78ca-417d-bb98-ac3189a31cb9)
![Fixed](https://github.com/MelvorIdle/melvoridle.github.io/assets/149914387/d51450b5-3dfe-499a-82e0-b94e2f75eee8)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7994

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
I can't seem to reproduce this one on my end with the setup you provided. Can you provide a save so I can take a look if there is something else at play here?
