### ISSUE TITLE
[Bug]: Summoning Master Relic - Synergies not active on reload

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#3822]
### Describe the bug

The summoning master relic unlocks all synergies. When reloading the game, the synergies are inactive until you re-equip the summoning relic. Everything is visually updated however the modifiers are not updated.

From what I can gather, `this.game.modifiers.unlockAllSummoningSynergies` is being checked in `isSynergyUnlocked` but at the time of loading the save, it is returning 0 with the master relic unlocked.

### Reproduction Steps

1. Unlock Summoning Master Relic
2. Use a synergy that is not unlocked without said relic
3. Reload the game
4. View the modifier that is given by the synergy

A test save has been provided; The synergy being used gives the 30% `game.modifiers.increasedChanceForArrowShaftsWoodcutting`

### Expected behaviour

If the summoning master relic is found, the modifiers from a locked synergy should be active immediately after loading a save without having to re-equip items or force an update through other means.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/reCf10EW

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7994

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.2. If issue persists, please open a new issue.
