### ISSUE TITLE
Spelling: Lower case "and" after period

### ISSUE THREAD

**Issue by kocsirtamas** [MelvorIdle/melvoridle.github.io#3824]
### What text is wrong?

The description of Burning Amulet of Gold says:
"+20% GP from Firemaking. and +10% Firemaking Skill XP"
The description of Superior Astrology Skillcape says:
"+2 to base drop quantity of Stardust and Golden Stardust from Astrology. and -10% Astrology Interval
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/142602141/4a2a8201-9476-4d5e-9fdd-67b924b81268)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/142602141/32c133ae-d4d2-438f-bc1c-67c3932f75f6)

### What is the correct spelling or grammar?

I expect the correct spelling to not have a period before the lower case "and".

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.2. If issue persists, please open a new issue.
