### ISSUE TITLE
[Bug]: Temp POIs last for 9 moves

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#3826]
### Describe the bug

Upon moving the player, the game discovers any POIs at which point temp modifiers are activated. Immediately after, the game checks for any temp modifiers then removes 1 move from them.
This results in temp modifiers only lasting 9 moves instead of the intended 10.

### Reproduction Steps

1. Survey a POI with a temporary modifier
2. Move to that POI
3. Check how many moves are left `game.cartography.activeDiscoveryModifiers`

### Expected behaviour

Temporary POI modifiers should be active for 10 moves.

It would seem this would be achieved by changing the ordering of the code in movePlayer so the temp bonuses are removed first then the POI is discovered afterwards.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/5f4b3dbf-112a-4118-9aa8-587213aff3cd)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7994

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.2
