### ISSUE TITLE
[Bug]: Ancient Relic Magic: +40 minimum Spell Damage does not affect Nature's Call

### ISSUE THREAD

**Issue by ROFLconda** [MelvorIdle/melvoridle.github.io#3827]
### Describe the bug

When using the Nature's Call spell while having obtained the Ancient Relic "+40 minimum Spell damage" the spell does not take this into account while all other spell that I have obtained work with it. This seems counter intuitive since the relic does not specify any spells that it would not work with. This bug might also affect other spells but I can not try this as I have not unlocked them yet.

### Reproduction Steps

1. Begin game on Ancient Relics mode
2. Acquire the Magic Ancient Relic "+40 minimum Spell damage
3. Acquire the Nature's Call Staff
4. Use the Nature's Call Staff and equip the Nature's Call Spell
5. The minimum damage of the Spell will be too low

### Expected behaviour

The minimum damage of the Nature's Call should be increased by 40.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/HzazideE

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/150296528/f2da8f19-cba8-48ef-8cf6-44c91b29a4e2)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/150296528/37b7da1d-5cb7-4141-a2c4-b030e78bd512)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7994

### Are you using any mods?

Yes / now retested without mods. The issue persists.

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.2
