### ISSUE TITLE
[Bug]: Attack Master Relic provides Global Evasion instead of Melee Evasion

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#3828]
### Describe the bug

The Attack master relic description says it reduces Melee Evasion however the modifier reduces Global Evasion.

### Reproduction Steps

1. Look at Attack Master Relic description
2. Compare description with code

### Expected behaviour

Either the description should state "Global Evasion" or the modifier should be specific to melee evasion.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/0e19dcf8-00ab-4935-bbc8-d223adb8292a)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/8bd0f0b9-e9d8-460f-bdf8-e24d2288e852)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7994

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.2
