### ISSUE TITLE
[Bug]: Recognition of purchase from Steam on Ubuntu 20.04

### ISSUE THREAD

**Issue by EgeSekerci** [MelvorIdle/melvoridle.github.io#3829]
### Describe the bug

-Game doesn't recognize the purchase on Ubuntu. After buying the game and logging in the game can't see that I've logged in from Steam and I already bought the full game and DLCs of the game. After logging in on a Windows PC it recognized that I've Steam and I bought the game.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [X] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7994

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Can you please provide screenshots of what you see when loading the game on Windows?

**Comment by EgeSekerci** [comment]
Which part do you need to see? Because there is bunch of different loading text if that's the thing you want to see.
