### ISSUE TITLE
Experimental pause+offline progress feature bugged with crafting skill

### ISSUE THREAD

**Issue by Waha-nonono** [MelvorIdle/melvoridle.github.io#383]
**Describe the bug**
The experimental offline progress option gives approximately 5 times more progress that it should, with crafting, when using the god upgrade, pet and cape. This does not happen with normal offline progress, only the experimental feature.

This happens on firefox and chrome. And with a fresh account with the crafting interval bonuses added with console.

**To Reproduce**
1. Have the god upgrade, pet and cape.
2. Enable the experimental skill pause feature in settings.
3. Start crafting something.
4. Switch to a different tab for a few seconds.
5. Switch back to melvor.
6. Note that the number of items crafted is way more than it should be.

**Additional note**
Don't know if this is related but the crafting interval calculation for offline progress is different from the online one, because the bonuses are applied in a different order.

**Comment by MelvorIdle** [comment]
Thank you. This has been hotfixed!

**Comment by Waha-nonono** [comment]
Still getting the bug.
