### ISSUE TITLE
[Spelling/Grammar]: <title>

### ISSUE THREAD

**Issue by Narux04** [MelvorIdle/melvoridle.github.io#3831]
### What text is wrong?

In the Chinese translation, "Active Prayer" is translated as "主动祝祭", this is inaccurate because "主动" implies that action need to be taken for prayers to be casted.

### What is the correct spelling or grammar?

The correct translation for "Active Prayer" should be "生效祝祭", meaning "Prayer In Effect".

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.2
