### ISSUE TITLE
[Bug]: Fox-Salamander synergy is setting bar requirements to 1

### ISSUE THREAD

**Issue by Avallach160** [MelvorIdle/melvoridle.github.io#3832]
### Describe the bug

Use fox/salamander and making salamander is causing bar usage to be 1 across the board while still getting 200% tablet creation.

Save file:
[melvoridlesave_Avallach_11-11-2023_43838PM.txt](https://github.com/MelvorIdle/melvoridle.github.io/files/13326849/melvoridlesave_Avallach_11-11-2023_43838PM.txt)

### Expected behaviour

Expected cost reduction to be ignored.

### Screenshots

Gear: 
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/6992987/4dfed11b-17db-4e8e-80c8-cace14221126)

Bar cost:
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/6992987/30f3eac0-0bf6-437c-bf99-4a139d9ff0bf)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7998

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.2
