### ISSUE TITLE
[Bug]: Cherry seeds

### ISSUE THREAD

**Issue by grumbold99** [MelvorIdle/melvoridle.github.io#3833]
### Describe the bug

This is probably not going to be seen as a bug but a bit of pedantry, but cherries come from cherry trees. Why are they allotment seeds rather than fruit tree seeds like apple?

### Reproduction Steps

Farming
Try to plant cherries

### Expected behaviour

obvious

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7994

### Are you using any mods?

No

**Comment by BartRoozen** [comment]
Also, the seeds are 1 coin instead of a more logical increment for it's tier of seed. Is this by design?
