### ISSUE TITLE
[Bug] Still not playable without internet connection

### ISSUE THREAD

**Issue by zibb0zz** [MelvorIdle/melvoridle.github.io#3834]
### Describe the bug

If you not already played the game at least once, you can not play it, if you dont have a internet connection. If you played it already, some files are cached and those files are working.

### Reproduction Steps

1. Install game on a fresh machine
2. Install the game while internet is still on
3. Disconnect internet connection
4. Start the game

### Expected behaviour

The game should contain all files needed to play and only call to the servers if you are trying something that needs a connection. Examples for needed connection:

- Savegame management
- News/Changelog

### Screenshots

<img width="1230" alt="image" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/132283986/374308ef-4222-4fce-a0f7-c764c9453d8d">

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7998

### Are you using any mods?

No

**Comment by scrollsjay** [comment]
I think this is a very important feature, especially for the longevity of the game. Would be really great if this would be supported.

**Comment by MelvorIdle** [comment]
Offline Client has been recently announced: https://news.melvoridle.com/announcing-offline-client-roadmap/
