### ISSUE TITLE
[Bug]: Mole+Crow Synergy works for Pure Essence but only consumes tablets on Rune Essence

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#3835]
### Describe the bug

Mole+Crow synergy gives 2x essence. This works on both Rune Essence and Pure Essence but the synergy is only consumed on Rune Essence resulting in just 1 mole tablet being consumed per action instead of 2 mole + 1 crow.

### Reproduction Steps

1. See images;
2. Mine Pure Essence with Mole+Crow synergy
3. Watch tablet usage and Pure Essence gain

### Expected behaviour

Either 2 mole and 1 crow tablet should be consumed per action when mining Pure Essence or the synergy should not work for Pure Essence.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/52c2e1e3-a098-45c1-bf16-15a52d0e4540)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/a1a0956d-30ab-4164-8d70-7e38f1e1b17c)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7998

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This should now be fixed as of Game Update - v1.2.2
