### ISSUE TITLE
[Bug]: android beta - cannot scroll down on welcome back menu

### ISSUE THREAD

**Issue by somesortofrescuetoaster** [MelvorIdle/melvoridle.github.io#3836]
### Describe the bug

When returning to the game in android and getting the welcome back popup, if there are many lines of items recieved, the "ok" button is pushed off the bottom of the screen and I am unable to click ok.  I have to exit and close and then reopen app immediately so that only a few lines of items appear on the screen.  Lately this has been happening very often when away several hours excavating during archaeology.

### Reproduction Steps

Begin excavating
Close app for several hours
Open app and load in to welcome back screen

### Expected behaviour

Should be able to swipe down in welcome back screen to click ok and exit welcome back screen.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

cant find this in android app

### Are you using any mods?

No

**Comment by Hietamaki** [comment]
I get this all the time with the latest beta. Basically every time I open the game. It's so annoying.
