### ISSUE TITLE
[Bug]: Township task amount not updating

### ISSUE THREAD

**Issue by scrollsjay** [MelvorIdle/melvoridle.github.io#3837]
### Describe the bug

While tracking the normal task "200 Raw Carp / 200 Carp" while cooking Carp the amount of cooked Carp is not updated in the task view. Switching back/forth to easy tasks / normal tasks does update the Carp to the right amount though.

### Reproduction Steps

1. Try to tackle normal task "200 Raw Carp / 200 Carp"
2. Cook Carp
3. Go to Township / normal tasks
4. Observe the amount of cooked Carp while cooking
5. Carp amount is not updated

### Expected behaviour

Carp amount should update

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.1

### Game Subversion

?7998

### Are you using any mods?

No

**Comment by gunnaro** [comment]
I'm having the same issue, but I want to add a little detail I noticed:
Tasks that needs defeating enemies are being counted/updated visually in Tasks, but gathereing tasks don't update automatically. They still update if you refresh the Tasks window. Hope it helps.
