### ISSUE TITLE
[Translation Error]: <title>v1.2.2 简体中文  僵尸乱码  

### ISSUE THREAD

**Issue by AXsss** [MelvorIdle/melvoridle.github.io#3839]
### Which text in the game has a translation error?

错误地点：战斗区域-墓地-僵尸   
错误描述：文本乱码，显示内容是“？？尸”
版本信息：v1.2.2 简体中文

**Comment by VariableVictor** [comment]
![Snipaste_2024-01-26_16-34-52](https://github.com/MelvorIdle/melvoridle.github.io/assets/22555507/84defc77-08b3-4884-8ac9-19e9025da92a)
As you can see. This bug is still existed
