### ISSUE TITLE
[Bug]: donate generic items

### ISSUE THREAD

**Issue by JDOGWIN** [MelvorIdle/melvoridle.github.io#3848]
### Describe the bug

The donate all generic items button will take items even if they haven't triggered the item specific option. So when you have items that haven't been "discovered" by donating them to museum it will still take them and not discover them in the museum even though you donate them.

### Reproduction Steps

1. Go to museum in archeology
2. Hit donate all generic items button
3. Realize and regret that you donated a super rare drop and it didn't show as discovered even though you still donated it.

### Expected behaviour

Check off the donation for specific items that are undiscovered when you hit donate all generic items and donate them.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/5VH4lBVi

### Screenshots

![Screenshot_20231115_110423_Melvor Idle](https://github.com/MelvorIdle/melvoridle.github.io/assets/105834161/c150eb71-9d81-410c-a6e1-09cc27e7a26a)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

8112

### Are you using any mods?

Yes

**Comment by Zarremgregarrok** [comment]
Same behaviour on an unmodded game with all expansions.

**Comment by sesi200** [comment]
Also present on Firefox, game version 1.2.2 (8605), no mods
