### ISSUE TITLE
[Translation Error]: Summoning attack bar tooltip doesn't account for interval reductions

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#3849]
### Which text in the game has a translation error?

The tooltip for the summoning progress bar will always show `3s` instead of the actual summoning attack interval. `SUMMON_BAR_TT`
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/7d336677-6c8c-4224-85b1-5105575952fc)

**Comment by AlexDerr** [comment]
Not sure if I would consider this a localization bug, but I am seeing the same thing and the interval does not reflect the updated timing when using the new familiar attack interval reduction. Although the interval reduction does seem to work as expected

**Comment by 04Slash** [comment]
Closing as this was fixed in ?11742.
