### ISSUE TITLE
[Bug]: Worship pop-up missing 2x worship bonuses during ${Season}

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#3850]
### Describe the bug

The pop-up for Worship has no mention of worship modifiers being doubled during specific seasons. This is only shown on the "Change Worship" menu.

### Reproduction Steps

1. Go to Township
2. View Change Worship pop (image 2)
4. Hover over Worship in the Township overview (image 1)
5. See "All positive Worship modifiers are increased by 2x during ${season}" text missing

### Expected behaviour

The pop-up in the overview for Worship should show that modifiers are doubled during certain seasons.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/7ea5e2b0-f940-4649-8e48-138c3039af67)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/7c131fce-ed6a-40eb-a1d5-2b83e07115f0)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [x] Throne of the Herald
- [x] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8112

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Should now be fixed as of [Game Update - v1.2.2 ?8126](https://news.melvoridle.com/game-update-v1-2-2-8126/). If the issue persists, please open a new issue.
