### ISSUE TITLE
[Bug]: Missed Signets Ring stats doesn't increase, when you get a Gold Topaz Ring, since last patch.

### ISSUE THREAD

**Issue by dodder** [MelvorIdle/melvoridle.github.io#3853]
### Describe the bug

Missed Signets Rin doesn't increase, when you get a Gold Topaz Ring, since last patch.

I've gotten several, and the statistic doesn't increase. This is the most important stat, naturally.

### Expected behaviour

Don't equip a Gold Topaz Ring, and do things. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

8112

### Are you using any mods?

Yes

**Comment by dodder** [comment]
This is only applicable to Golden Topaz's acquired through skilling. If you miss a signet ring in combat it still counts.

**Comment by mythridium** [comment]
fwiw, this has been the case for at least 8 months since I started playing melvor, not just since last patch.

The stat only increases from combat.

I talked about this back in May.

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/132613374/f02960d4-8547-46a2-8208-0402250b0279)

**Comment by achristoforides** [comment]
Just wanted to add to this…

This is still not resolved and I experienced it today. Skilling astrology offline without a gold topaz ring equipped and when seeing the information when logging back in after being AFK, saw I received 2 gold topaz rings but the stat for missed ring halves was never increased.

Game version: v1.2.2 ?8417
