### ISSUE TITLE
[Bug]: Slayer Relic #1 in AR, is bugged in combination with the barrier mechanic.

### ISSUE THREAD

**Issue by dodder** [MelvorIdle/melvoridle.github.io#3854]
### Describe the bug

In Ancient Relics mode, if you have the Slayer Relic #1, that states #+100% of Poison damage dealt is gained as Slayer Coins"

This isn't entirely the case. Any poison tics, on a monster with it's barrier up, also grants these coins, even if it does no damage.

This makes you able to farm Slayer Coins, doing Barrier content up to like 800-900k/h, with weapons such as Royal Toxins Spear. 

### Reproduction Steps

1. Equip RTS (or another item that applies poison)
2. Attack a monster with it's barrier up.
3. Wait for poison to Tic.
4. Get free slayer coins. 

### Expected behaviour

It should not give Slayer coins, as the tics don't actually do any damage, since the barrier is up.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

8112

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Should now be fixed as of [Game Update - v1.2.2 ?8126](https://news.melvoridle.com/game-update-v1-2-2-8126/). If the issue persists, please open a new issue.
