### ISSUE TITLE
[Bug]: Dig sites not available even though they are all uncovered in cartography and traveled to.

### ISSUE THREAD

**Issue by JDOGWIN** [MelvorIdle/melvoridle.github.io#3857]
### Describe the bug

I have discovered a ton of the dig sites (at least where they should be) in cartography but I can't make maps or dig them at all.

### Reproduction Steps

1. Discover sites in cartography 
2. Realize there's no dig site available even though you found the dig site
3. Cry

### Expected behaviour

1. Discover dig sites in cartography
2. Make maps and dig the sites
3. Rejoice for the system works as intended.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/5VH4lBVi

### Screenshots

![Screenshot_20231116_090425_Melvor Idle](https://github.com/MelvorIdle/melvoridle.github.io/assets/105834161/50db3f89-a0e4-4326-87dd-8f366c9f736b)
![Screenshot_20231116_090411_Melvor Idle](https://github.com/MelvorIdle/melvoridle.github.io/assets/105834161/871d632a-4b7e-4814-89ef-3b2ec0667f6d)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

8112

### Are you using any mods?

Yes

**Comment by 04Slash** [comment]
Certain Digsites require items from Archaeology to be able to unlock.

I do think this information should be more clearly displayed ingame however the wiki should be able to tell you what items you need to find and where to get them.

For example. the [Bazaar](https://wiki.melvoridle.com/w/Bazaar) requires you to find the [City Chart](https://wiki.melvoridle.com/w/City_Chart) before you can discover it by travelling to the hex.

**Comment by MelvorIdle** [comment]
I've attempted to recreate this bug using the save you provided and can't see the bug occuring.

- Loading the save shows the dig sites loading fine.
- Discovering a dig site on your save (the 2nd dig site) unlocks it as intended, and I am able to start excavating.

Is this bug still ocurring for you?

**Comment by JDOGWIN** [comment]
Yes it is still happening, but 04slash's response may be my issue
