### ISSUE TITLE
[Bug]: Superior Skill cape not showing in quick equip

### ISSUE THREAD

**Issue by carsonhatch94** [MelvorIdle/melvoridle.github.io#3859]
### Describe the bug

I am level 120 farming and own the superior skill cape. I went to harvest some crops and normally use the quick equip menu. However, only the basic farming skill cape shows up, which I no longer own since I own the superior one.

### Reproduction Steps

1. Own the superior farming skill cape
2. Be level 120 farming
3. Make sure that the cape isn't equipped but is in your bank
4. Go to farming
5. Hover over quick equip menu

### Expected behaviour

I expected the superior skill cape to be in the quick equip menu but it is not

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ X] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8112

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Hey, this is not a bug. You are able to select which items appear on the minibar from the Bank.

Click the item you want -> Gear icon -> Set the pages you want it to show in the quick equip

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/45249614/a5a6c1c7-ff6a-465f-b8b2-166e9f848ba8)

**Comment by carsonhatch94** [comment]
Ah! Thank you for the clarification.

**Comment by Edilson41** [comment]
Excuse me, but... Wouldn't it be easier/simpler if the 120 capes appeared in the quick menu just like the 99 capes do?
