### ISSUE TITLE
[Bug]: Summon Max Hit and Summon Max Hit on Barrier are reduced by the players own damage reduction when out of combat

### ISSUE THREAD

**Issue by mythridium** [MelvorIdle/melvoridle.github.io#3860]
### Describe the bug

When looking at the out of combat stats, the summon max hit and max hit on barrier are impacted by the players own damage reduction and are not accurate unless naked.

This is only a visual issue when out of combat and does not impact actual combat from what I can tell.

This happens because the target is set to the player when out of combat.

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/132613374/9102be21-f015-49cb-8002-d55e989800a9)

### Reproduction Steps

Equip combat summon
Equip gear with damage reduction

Note summon max hit is affected by players own damage reduction

Unquip gear with damage reduction

Note summon max hit goes up

### Expected behaviour

The players own damage reduction should not modify the display of summon max hit and barrier max hit.

### Screenshots

Max Hit is 192, but the players own dr is reducing the numbers.

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/132613374/71889613-8325-45b5-be7d-3f92ece77c46)

If I remove some damage reduction, the max hit goes up

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/132613374/75bf29c5-6645-4625-a979-6a912a8219a4)

And when I have no dr at all, it's correct

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/132613374/379c2cab-8768-481a-9ed0-c6d36121c5b9)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari
- [X] Steam
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [X] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

8112

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Should now be fixed as of [Game Update - v1.2.2 ?8126](https://news.melvoridle.com/game-update-v1-2-2-8126/). If the issue persists, please open a new issue.
