### ISSUE TITLE
[Visual Bug]: <Charge Stone of Rhaelyx "Upgrade" indicator>

### ISSUE THREAD

**Issue by StankWaffle** [MelvorIdle/melvoridle.github.io#3861]
### Describe the bug

Charge Stone of Rhaelyx "Upgrade"-indicator (little green circle with an up-arrow in the top right of the image) should probably be the Downgrade-icon.

Would also make sense to change the upgrade button into "Downgrade"

"Mysterious Stone" feels like it's a downgrade to "Charge Stone of Rhaelyx" 

This is just my opinion.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8116

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Should now be fixed as of [Game Update - v1.2.2 ?8126](https://news.melvoridle.com/game-update-v1-2-2-8126/). If the issue persists, please open a new issue.
