### ISSUE TITLE
[Bug]: "increasedDamageReductionWithActivePrayer" presumably stronger/weaker than supposed to

### ISSUE THREAD

**Issue by KumaV1** [MelvorIdle/melvoridle.github.io#3863]
### Describe the bug

As I was checking the damage reduction calculation, in order to create some custom modifiers, I noticed something off, with a modifier presumably placed at the wrong point of the overall calculation chain.

I will just go and explain my train of thought (most important being point 4). Also, the issue is specific to the mentioned modifier, meaning it's specific to the `Player` class. The `Enemy` class is a little simpler and overall I didn't really see problems with it.

1. So, first of all, a bunch of flat DR% increasing/decreasing are summed up. Simple and easy.
    * At this point, both `Player` and `Enemy` have jumped into/called the base method of the `Character` class
2. Now, the first multiplication happens, where the up to now flat result is overall multiplied by increased/decreased DamageReduction**Percent** - understandable, there is a flat equivalent so those modifiers are clearly meant to be multiplicative
3. Another multiplication happens (if necessary) based on `halveDamageReduction` - again, understandable
    * This, btw, is the end result for the `Enemy` class
4. However **now** the `increasedDamageReductionWithActivePrayer` modifier is **additively** applied to the current value of the calculation - based on the calculation itself and the modifier name, it's clearly meant to be additive. But, if so, shouldn't it have been added **before** multiplications started?
5. Another multiplication based on combat triangle happens - this one is, once again, understandable to happen

### Expected behaviour

I would have expected `increasedDamageReductionWithActivePrayer` to be part of the additive sum initially calculated before multiplications start taking place. So to be added to the current reduction right **before** `super.modifyDamageReduction(reduction)` is called

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8116

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Should now be fixed as of [Game Update - v1.2.2 ?8126](https://news.melvoridle.com/game-update-v1-2-2-8126/). If the issue persists, please open a new issue.
