### ISSUE TITLE
[Bug]: Completion modal has "/h5>" on the end of it

### ISSUE THREAD

**Issue by Draedon123** [MelvorIdle/melvoridle.github.io#3864]
### Describe the bug

The completion modal has, in text, "/h5>" on the end.
"Character age: x years, x days, x hours, x minutes, x seconds/h5>"
<img width="285" alt="image" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/118961726/98764129-ec39-4677-96fe-776b93e9de86">

### Reproduction Steps

1. Complete the game, or get the completion modal up in general
2. Look at the bottom of the modal, at the end of "Character age:"

### Expected behaviour

The "/h5>" is removed. It is probably just a typo and is meant to be </h5>, closing off the h5 tag.

### Screenshots

<img width="285" alt="image" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/118961726/c4910727-f0cb-4925-b93d-4b72be4dd4d3">

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8116

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Should now be fixed as of [Game Update - v1.2.2 ?8126](https://news.melvoridle.com/game-update-v1-2-2-8126/). If the issue persists, please open a new issue.
