### ISSUE TITLE
[Bug]: Barrier burn results in negative barrier hitpoints.

### ISSUE THREAD

**Issue by roodwarrior** [MelvorIdle/melvoridle.github.io#3865]
### Describe the bug

When a barrier burn is in effect and burns the barrier down, it goes negative. I also believe that the barrier burn starts affecting regular hitpoints as well, but it is happening too fast to tell.

### Expected behaviour

Barrier burn should go to zero.

### Screenshots

![Barrier](https://github.com/MelvorIdle/melvoridle.github.io/assets/147214183/d8649192-be21-48b4-b06d-0cd2f2dac69f)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8116

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Should now be fixed as of [Game Update - v1.2.2 ?8126](https://news.melvoridle.com/game-update-v1-2-2-8126/). If the issue persists, please open a new issue.
