### ISSUE TITLE
[Bug]: <title>Use Redwood Shortbow/Longbow create the Centaur Familiar in the wrong number

### ISSUE THREAD

**Issue by SmingSoong** [MelvorIdle/melvoridle.github.io#3872]
### Describe the bug

To create the Centaur Familiar, need 50 use Redwood Shortbows/Longbows. is that a wrong number？

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/68635040/a09d53be-2ae7-49eb-b2d7-b0bdc269411a)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8131

### Are you using any mods?

No

**Comment by coolrox95** [comment]
The item requirements for summoning familiars are determined by the base sale price of the item. As redwood short/longbows have a low sale price you require 50.

Working as intended.
