### ISSUE TITLE
[Bug]: Ancient relics 120 exp cap

### ISSUE THREAD

**Issue by Martinmagi1** [MelvorIdle/melvoridle.github.io#3878]
### Describe the bug

Im playing ancient relics mode.
I cleared some but not all of the toth dungeons. I unlocked Astrology to 120.
But now that im training Astrology it getting capped at 115,126,837 exp.
Even tho i have virtual levels enabled. 

### Reproduction Steps

Ancient relics mode
Clear all dungeons except afew, make sure to have a skill, in this case Astrology, unlocked to 120.
Train it to 120.
Have virtual levels enabled.
See that you stop gaining exp.

### Expected behaviour

Expected behavior would be that because its 120,it shoudent get capped as a skill does in ancient relics mode.
I expect that it gets fixed if you clear all dungeons and get everything to 120 cap. 

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/oIbDeI4s

### Screenshots

![Screenshot_20231123_065315_Firefox](https://github.com/MelvorIdle/melvoridle.github.io/assets/39439809/867312fd-05ac-4a03-9a13-3ba66d43ed65)
![Screenshot_20231123_065327_Firefox](https://github.com/MelvorIdle/melvoridle.github.io/assets/39439809/c6149d57-e117-4196-b8e9-86b236cf34be)
![Screenshot_20231123_065528_Firefox](https://github.com/MelvorIdle/melvoridle.github.io/assets/39439809/1d8ed867-4a45-48f2-a526-e14d3120bd1a)
2 screenshots showing my exp stays while mastery goes up.
1 screenshot of the back from idle recap. With mod better recap. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

? 8135

### Are you using any mods?

Yes

**Comment by FriHo** [comment]
Im pretty sure this isn't a bug. You can't get virtual levels over your combat level in adventure mode either. If it would be a bug, then i think it would have been fixed a while ago
