### ISSUE TITLE
[Bug]: <Missing EXP in archeology>

### ISSUE THREAD

**Issue by Zartss** [MelvorIdle/melvoridle.github.io#3880]
### Describe the bug

I am doing level 55 of archeology, looking for tiny objects in particular, for this level it says that the reward for finding an artifact is 353, but many times when I find it I receive only 7 EXP.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8135

### Are you using any mods?

No

**Comment by SolidKalium** [comment]
Are you actually getting an artifact when you receive the 7xp?

Note that bones can be received randomly, but they don't count as an artifact.
