### ISSUE TITLE
[Bug]: <title>Deedree is the Only Constellation Unlocked for me (level 64 Astrology atm)

### ISSUE THREAD

**Issue by Boredom4me** [MelvorIdle/melvoridle.github.io#3882]
### Describe the bug

I have been playing Melvor Idle since before October 12, and the only unlocked Constellation this whole time is the Deedree constellation, though I am level 64 and Deedree is 99 Mastery.  There is a chance I gained the Deedree mastery checkpoints (if the wiki is correct) while offline.  Could that be the reason I have no other constellations?

### Reproduction Steps

1. Go to the Astrology Skill page
2. See that no other Constellations are unlocked, outside of the base Deedree, despite skill level, skill mastery, and Constellation mastery

### Expected behaviour

At this point, I should have 6 other Constellations unlocked, based on overall Astrology level (this is coming from someone who has not had a normal Astrology experience, so I can't even be sure of that).  I should have Iridan, Ameria, Terra, Vale, (**not** Nysa--no AoD expansion) Syllia, and Arachi.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/QfbSPrjy

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/152238214/2b9be6d3-e78a-4289-9473-9d15cb1fa6db)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8135

### Are you using any mods?

No

**Comment by ekuland** [comment]
Click "Go Back" under the Deedree icon.
