### ISSUE TITLE
[Bug]: No preview image for Crafting Mastery Token in bank

### ISSUE THREAD

**Issue by ironkunai** [MelvorIdle/melvoridle.github.io#3887]
### Describe the bug

When viewing your bank, if you have a crafting Mastery token, the preview image is not visible

### Reproduction Steps

1. Log into Melvor idle 
2. Go to your bank
3. Must have crafting Mastery token is bank
4. View crafting Mastery token

### Expected behaviour

Preview image for Crafting Mastery token should be visible 

### Screenshots

![Screenshot_20231130-170120](https://github.com/MelvorIdle/melvoridle.github.io/assets/152516545/4dc0d255-eb24-4d35-8874-f83c68b4b8d1)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8156

### Are you using any mods?

No

**Comment by icedtrumpets** [comment]
Did you try closing and reopening the game before submitting this?
