### ISSUE TITLE
[Bug]: Unable to repair individual buildings if they cannot be upgraded

### ISSUE THREAD

**Issue by NazrinUFO** [MelvorIdle/melvoridle.github.io#3890]
### Describe the bug

If a township building is not fully upgraded but also cannot be upgraded further (due to level or population requirements) the button to repair that specific building does not appear.

### Reproduction Steps

1. Wait for a building that has been upgraded as far as it can be upgraded, but not to the maximum level possible to need repairs
2. Locate the building that requires repairs
3. Observe the lack of a repair button

### Expected behaviour

1. Wait for a building that has been upgraded as far as it can be upgraded, but not to the maximum level possible to need repairs
2. Locate the building that requires repairs
3. Witness and be able to click on the repair button

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/1322447/f338a3d4-ce8b-4592-b945-0615d28b781c)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8126

### Are you using any mods?

Yes

**Comment by rjclaasen** [comment]
I'm running into an issue that might be similar to yours. Does the "Repair All" button actually repair the buildings that you can't repair individually?

**Comment by NazrinUFO** [comment]
Repair all functions as normal, it's just the individual button that's missing.
