### ISSUE TITLE
[Bug]: Confetti Crossbow won't equip

### ISSUE THREAD

**Issue by OhKayee** [MelvorIdle/melvoridle.github.io#3892]
### Describe the bug

Purchased Confetti Crossbow and cannot equip in weapon slot from my Bank.
Other weapons/tools can be equipped.

### Reproduction Steps

1. Go to Bank
2. Select Confetti Crossbow
3. Select Equip Weapon
4. No response from item

### Expected behaviour

1. Go to Bank
2. Select Confetti Crossbow
3. Select Equip Weapon
4. Item appears in weapon slot

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/AWY9j2JS

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8156

### Are you using any mods?

No

**Comment by ekuland** [comment]
You do not meet the level requirement to equip the weapon.
