### ISSUE TITLE
[Bug]: Archaeology Relic 5 is not affected by +% GP modifiers

### ISSUE THREAD

**Issue by ajclaasen** [MelvorIdle/melvoridle.github.io#3898]
### Describe the bug

Archaeology relic 5 states:
> Gain GP equal to +10 per Archaeology Skill Level per excavation action that locates no Artefacts

Aorpheat's Signet Ring states:
> When equipped - +100% GP granted from all sources except Alt. Magic, Township and Item Sales, ...

However, equipping the Signet Ring has no effect on the GP gained from the relic

Golden Wreath's does add 100 GP!
> +100 GP gained when earning GP, except Alt. Magic and Item Sales, ...

Also checked out the Jeweled Necklace and Fine Coinpurse, and they don't seem to add any GP either! Maybe only additive modifiers work?

### Reproduction Steps

1. Get Archaeology Relic 5
2. Get the Signet Ring
3. Perform some Archaeology action & fail to locate an artefact
4. Equip the Signet Ring
5. Perform some Archaeology action & fail to locate an artefact
6. Notice no difference in GP gained

### Expected behaviour

I expect the Aorpheat's Signet Ring to modify the GP gained by failing to locate an artefact while having Archaeology Relic 5 unlocked.

### Screenshots

![xpringmoni](https://github.com/MelvorIdle/melvoridle.github.io/assets/18427451/9a483938-138f-4a77-b9ce-4f935301d5fb)
![signetringmoni](https://github.com/MelvorIdle/melvoridle.github.io/assets/18427451/11defb38-0205-4532-94cf-208027f8f069)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8156

### Are you using any mods?

No

**Comment by amulder87** [comment]
Does this intentionally not work with Aorpheat's Signet Ring still? All the other +% GP modifiers are working with the relic except that one.
