### ISSUE TITLE
[Bug]: <title>An error occurred when processing ticks

### ISSUE THREAD

**Issue by archtua** [MelvorIdle/melvoridle.github.io#3899]
### Describe the bug

Started to attack Magic fire demon, and when the attack interval bar reached the end, this error message popped up.  This is happening on steam version and also android version.

### Reproduction Steps

Go to Attach
Click on Slayer areas
Click Lava lake
Fight Magic fire demon

### Expected behaviour

Melee attack on a Magic Fire Demon

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/74814283/a4cf3ddb-b0ce-4a77-ac80-68b7206d63ca)

### Console output

An error occurred while processing ticks:
Error Name: Error
Error Message: Tried to start timer: Act with invalid tick amount: -1
Stack Trace:
Error: Tried to start timer: Act with invalid tick amount: -1
    at Timer.start (https://steam.melvoridle.com/assets/js/built/combatManager.js?8156:302:7)
    at Player.queueNextAction (https://steam.melvoridle.com/assets/js/built/character.js?8156:422:77)
    at Player.queueNextAction (https://steam.melvoridle.com/assets/js/built/player.js?8156:46:42)
    at Player.act (https://steam.melvoridle.com/assets/js/built/character.js?8156:393:6)
    at Player.timers.act [as action] (https://steam.melvoridle.com/assets/js/built/player.js?8156:3:1261)
    at Timer.tick (https://steam.melvoridle.com/assets/js/built/combatManager.js?8156:299:89)
    at Player.activeTick (https://steam.melvoridle.com/assets/js/built/character.js?8156:362:30)
    at Player.activeTick (https://steam.melvoridle.com/assets/js/built/player.js?8156:41:20)
    at CombatManager.activeTick (https://steam.melvoridle.com/assets/js/built/combatManager.js?8156:59:61)
    at Game.tick (https://steam.melvoridle.com/assets/js/built/game.js?8156:203:123)

Active Action: melvorD:Combat
Current Equipment:
Helmet: melvorTotH:Vorloran_Protector_Helmet
Platebody: melvorTotH:Ward_of_Flame_Platebody
Platelegs: melvorTotH:Vorloran_Protector_Platelegs
Boots: melvorTotH:Vorloran_Protector_Boots
Weapon: melvorTotH:Agile_Wings_Rapier
Shield: melvorTotH:Leviathan_Shield
Amulet: melvorD:Fury_of_the_Elemental_Zodiac
Ring: melvorF:Ring_Of_Power
Gloves: melvorTotH:Vorloran_Protector_Gauntlets
Quiver: melvorTotH:Decay_Bolts
Cape: melvorTotH:Superior_Slayer_Skillcape
Passive: melvorTotH:Voodoo_Trinket

Action Information:
Is In Combat: true
Fight in Progress: true
-- Start of Player Information --
Next Action: Attack
Next Attack: melvorD:Normal
Is Attacking: true
Standard Spell Selected: melvorD:WindStrike
Ancient Spell Selected undefined
Aurora Selected: undefined
Curse Selected: melvorTotH:Despair
Active Prayers: None
Equipped Food:
Item: melvorD:Lobster, Qty: 1228
Item: melvorD:Crab, Qty: 996885657
Item: melvorD:Trout, Qty: 500
-- End Player Information --
-- Start of Enemy Information --
Enemy: melvorTotH:MagicFireDemon
Next Action: Attack
Next Attack: melvorTotH:LavaWave
Is Attacking: false
Standard Spell Selected: melvorD:FireBlast
Ancient Spell Selected undefined
Aurora Selected: undefined
Curse Selected: undefined
-- End Enemy Information --
Current Area Type: Slayer
Current Area ID: melvorTotH:LavaLake
Modding Enabled. Loaded mods:
SEMI Core
Unlimited Offline
Better Offline Recap
Shop Item Owned Indicator
Item Uses
QuickShards
Bank Tab Values
ETA
Show Slayer Task Attack Style
Combat Only Mode (HCCO / MCCO)
Save Game Converter
Repeat Current Slayer Task
SEMI Auto Bonfire
SEMI Auto Loot
SEMI Auto Eat
Township Un-Nerf
Priority Miner
Show Item Sources And Uses
dev.Console

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8156

### Are you using any mods?

Yes

**Comment by icedtrumpets** [comment]
This is caused by autoeat mods. Disable your autoeat mods

**Comment by archtua** [comment]
Thanks.  It seems quite strange that I can still fight monsters in other areas of the game, however only when I attempt to fight this specific monster the crash occurs.  I noticed this after my bug report.
