### ISSUE TITLE
[Bug]: Township Repair All does not (visually?) repair buildings that are capped by your level

### ISSUE THREAD

**Issue by ajclaasen** [MelvorIdle/melvoridle.github.io#3900]
### Describe the bug

I have buildings that are damaged from changing worship. They are maxed out to my current level, but not to the max level of the building because I'm capped by my Township level. Whenever I try to repair them with "Repair All", they don't seem to get repaired!

### Reproduction Steps

1. Max out a building until you are capped by your township level & pop
2. Change worship
3. Click "Repair All"
4. Notice they are not repaired,

### Expected behaviour

I expect the damaged building to be repaired.

### Save Link - Issue occurs with this save

https://melvoridle.com/save/aKBDaTcI

### Screenshots

![LOOKATTHEPRICE](https://github.com/MelvorIdle/melvoridle.github.io/assets/18427451/f9034c65-8d16-4e8a-836f-7ee42a6da82a)
![STILLNOREPAIREDSAD](https://github.com/MelvorIdle/melvoridle.github.io/assets/18427451/faa2032b-11f7-41b1-83ac-072785e3d9a4)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8156

### Are you using any mods?

No

**Comment by rjclaasen** [comment]
Alright so I previously thought the cost was bugged, but it's just town hall repairs really being that expensive

**Comment by rjclaasen** [comment]
Maybe related to #3890
