### ISSUE TITLE
[Bug]: Quick Equip

### ISSUE THREAD

**Issue by bravemacaroni** [MelvorIdle/melvoridle.github.io#3901]
### Describe the bug

**Quick equipping a stackable item like a scroll or a summoning tablet will always leave one behind in the inventory.**

### Example 1:
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/153141398/f46612a5-fefb-4631-8828-2ed65fa9ca8e)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/153141398/140c0e9e-1bc0-44b8-9d28-8d13752d550e)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/153141398/1ae8fd3b-50c2-4732-a847-8bc6cb238774)

### Example 2:
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/153141398/03a726b3-67e5-4d6a-a4e9-535b7b4827f1)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/153141398/693b3ee0-e918-43a4-a100-1af5d9e94fbf)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/153141398/4728a04c-f1ba-41ac-9c3d-caf5df26b15c)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

(?8156)

### Are you using any mods?

No

**Comment by Onmlock** [comment]
Also getting this on android. I'm wondering if this is intentional (All But 1) or a bug

**Comment by MelvorIdle** [comment]
This is intentional behaviour

**Comment by Emilronn** [comment]
> This is intentional behaviour

Why? I was about to report it as a bug as well. It should be an option if anything. Why would we want to omit 1?
