### ISSUE TITLE
[Bug]: blank white screen when I open up the game after minimizing it.

### ISSUE THREAD

**Issue by dhansnic** [MelvorIdle/melvoridle.github.io#3903]
### Describe the bug

When I leave the app and open it again it just shows a white screen. I then have to manually close the app and restart it.
I have tried deleting the cache and reinstalling it 
Phone Poco f3
Battery Saving for the app is disabled

### Reproduction Steps

Minimize the app and maximize it again.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

8156

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Same as #4322 (Closing this one to clean issues)
