### ISSUE TITLE
[Bug]: Can't upgrade to arnite brush

### ISSUE THREAD

**Issue by jaroldo3** [MelvorIdle/melvoridle.github.io#3908]
### Describe the bug

I am unable to purchase the arnite brush upgrade on the shop, even though I have all the requirements. It shows that I'm missing brushes

### Reproduction Steps

Open shop
Try to purchase arnite brush

### Expected behaviour

To be able to purchase the brush when I meet the stated requirements 

### Screenshots

![Screenshot_20231212-172627](https://github.com/MelvorIdle/melvoridle.github.io/assets/72932313/49b2ca18-6ba9-40a1-8e29-2da5cd1756aa)
![Screenshot_20231212-172641](https://github.com/MelvorIdle/melvoridle.github.io/assets/72932313/7b10ae73-de48-432a-aa78-5faec4b5faaf)

First screenshot shows I meet all but the number of brushes needed.

Second screen shot shows I have significantly more brushes than needed

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8156

### Are you using any mods?

No

**Comment by icedtrumpets** [comment]
"Ancient" and "Aranite" are, in fact, two different words

**Comment by jaroldo3** [comment]
Ah. Thank you for the abrasive response. But you are correct, I was getting confused.
