### ISSUE TITLE
fishing amulet in the toolbar

### ISSUE THREAD

**Issue by KoelBox** [MelvorIdle/melvoridle.github.io#391]
Please be as detailed as possible when making suggestions.

Why are you suggesting this?
I want to have amulet of fishing in the toolbar, like bob's rake.

How does your suggestion benefit the game?
it's a very specific item, that's usefull even after 99 fishing. i often forget to put it on.

![afbeelding](https://user-images.githubusercontent.com/70796543/92386533-40619b80-f114-11ea-85e4-5bff31f0c5ab.png)

**Comment by MelvorIdle** [comment]
Added to the coming update
