### ISSUE TITLE
[Bug]: <title>MISSING ALL the ICONS!!!!

### ISSUE THREAD

**Issue by linshianwei** [MelvorIdle/melvoridle.github.io#3916]
### Describe the bug

There's no any icon. It seems to be some missing problem.

### Screenshots

![螢幕擷取畫面 2023-12-22 002054](https://github.com/MelvorIdle/melvoridle.github.io/assets/154541259/ede21efe-9fb5-4b38-a833-0be3ce93aed5)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8274

### Are you using any mods?

No

**Comment by SnepaiX** [comment]
Same for me

![Безымянный](https://github.com/MelvorIdle/melvoridle.github.io/assets/81552340/eb08267e-28dd-4bf9-8fd3-0358660c84af)

**Comment by BobbyFails** [comment]
Same for me

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/154541994/101a3af6-a120-404b-971e-d9bb75c4ac97)

**Comment by hemanth850** [comment]
+1

**Comment by Bagh33r4** [comment]
+1

**Comment by valrorapa** [comment]
I solved it by verifying the game files

**Comment by TadeLauda** [comment]
como se verifican los archivos del juego?
