### ISSUE TITLE
no image appears

### ISSUE THREAD

**Issue by Alistair5** [MelvorIdle/melvoridle.github.io#3918]
### Describe the bug

no game image wants to appear

### Reproduction Steps

i start game

### Expected behaviour

for the images to appear

### Screenshots

![unknown_2023 12 21-13 21](https://github.com/MelvorIdle/melvoridle.github.io/assets/154541641/576b2915-10ea-4ead-b1de-4f5b2fded94b)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8274

### Are you using any mods?

No

**Comment by valrorapa** [comment]
I solved it by verifying the game files
