### ISSUE TITLE
[Bug]: Missing all icons

### ISSUE THREAD

**Issue by dbogs98700** [MelvorIdle/melvoridle.github.io#3919]
### Describe the bug

All of the icons within the client are broken/missing.

### Reproduction Steps

1. Open game through epic games launcher
2. Login/continue with character
3. No images are loading

### Expected behaviour

Images should be loading

### Screenshots

![Capturessss](https://github.com/MelvorIdle/melvoridle.github.io/assets/154541936/5db09c99-d841-4ec7-aecc-1407da061812)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [X] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8274

### Are you using any mods?

No

**Comment by hemanth850** [comment]
+1

**Comment by Bagh33r4** [comment]
+1

**Comment by SnowWolf1985** [comment]
+1

**Comment by Mrladdd** [comment]
me too

**Comment by rzarectha** [comment]
just got it on Epic Games and I have the same issue

**Comment by valrorapa** [comment]
I solved it by verifying the game files

**Comment by hemanth850** [comment]
> I solved it by verifying the game files

This helped, thanks
