### ISSUE TITLE
Rags to Riches I doesn't show item required

### ISSUE THREAD

**Issue by YaBoyBeartato** [MelvorIdle/melvoridle.github.io#392]
**Describe the bug**
After selecting a junk item to use for Rags to Riches I, it does not show that item as a required ingredient. This way you're unable to see how many items are remaining or how many you have total before starting without going back to bank tab.

**To Reproduce**
1. Go to Alt Magic tab
2. Click on Rags to Riches I
3. Select a junk item
4. Item dopes not show up in ingredients

**Expected behavior**
I expected it to work like high alchemy where it would then show the item

**Screenshots**
![Annotation 2020-09-07 103336](https://user-images.githubusercontent.com/70904289/92399522-6b3df680-f0f8-11ea-9746-1699f5268cbf.png)
![Annotation 2020-09-07 103415](https://user-images.githubusercontent.com/70904289/92399523-6bd68d00-f0f8-11ea-8ba3-5f708294846c.png)

**Browser**
Firefox 80.0

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

**Comment by Deedasmi** [comment]
Confirmed, and it's somehow tied to save. Tried multiple devices and browsers.

**Comment by coolrox95** [comment]
Issue was resolved in Alpha v0.21.
![image](https://user-images.githubusercontent.com/58208131/132107213-21559f1a-27d7-445e-af9a-e20b07f1a966.png)
