### ISSUE TITLE
[Bug]: MISSING ALL ICONS 

### ISSUE THREAD

**Issue by 9neon** [MelvorIdle/melvoridle.github.io#3922]
### Describe the bug

Hey , i have just started playing the game and its quite fun if you know what do to and when. The most annoying issue i am facing is - all the in game icons are missing . Clearly i dont see any icons in the game , everything icon is replaced by a file picture 

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

1.2.2

### Are you using any mods?

No

**Comment by staticf0x** [comment]
Did you try reloading the tab? This happens in Firefox too sometimes, and a refresh fixes that. However since the last update, I'm missing the museum token icon in archaelogy tab (not in inventory) on steam version.
