### ISSUE TITLE
[Bug]: Museum Token in Museum Tab icon is broken

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#3923]
### Describe the bug

The src for the Museum Token image in the Archaeology Museum tab is incorrect.

### Reproduction Steps

1. Open Archarology
2. Open Museum
3. See broken image
4. Inspect broken image
5. See src

### Expected behaviour

The domain should not exist twice in the image src.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/fe57d0e3-cb2b-40b9-a854-18b905da9b1a)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8282

### Are you using any mods?

Yes

**Comment by staticf0x** [comment]
I think this will be all platforms from the nature of the bug, here's steam:
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/44530786/e983727f-41ba-457c-89f0-6d009290de64)

**Comment by SchabeeHun** [comment]
I have the exact same issue via Epic without using any mods. 
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/155221584/4be8c761-2d4e-44be-ac31-e15c6d0fa79e)

**Comment by CMDMC12** [comment]
The image on the main Museum page now appears to be fixed, but the image on the donation confirmation window is still misconfigured. 
<img width="386" alt="image" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/27746140/e81d8aea-f62e-4d30-8123-7bc629650669">
