### ISSUE TITLE
[Bug]: white screen when returning to app after minimizing 

### ISSUE THREAD

**Issue by ThomasCox42** [MelvorIdle/melvoridle.github.io#3924]
### Describe the bug

Galaxy S21+
Leaving the app or switching to another app causes the screen to be white, unable to tap or do anything to fix, requires quitting the app and starting again to fix. 

### Reproduction Steps

1. Leave the app through any means
2. Re-enter to see a white screen

### Screenshots

![Screenshot_20231221_211208_Melvor Idle](https://github.com/MelvorIdle/melvoridle.github.io/assets/24656942/46d738da-bbe7-4b54-9f21-b98988f7c48b)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8282

### Are you using any mods?

No

**Comment by pddenhar** [comment]
Same problem on Pixel 6A, specifically if I leave the app and open enough other applications to evict Melvor Idle from RAM. If I leave the app and come right back this does not occur.

Same game version and sub version. 
![Screenshot_20231223-170941](https://github.com/MelvorIdle/melvoridle.github.io/assets/1697414/e66e0910-0e9f-44bd-b95b-b205cf46ef2a)

**Comment by kilbasar** [comment]
Same here on Samsung Galaxy S20 FE running Android 13. Didn't happen in the pre-beta app. Thanks!

**Comment by MelvorIdle** [comment]
Same as #4322 (Closing this one to clean issues)
