### ISSUE TITLE
[Bug]: Can't Submit Township Potion Task With High Level Potions

### ISSUE THREAD

**Issue by sadume** [MelvorIdle/melvoridle.github.io#3925]
### Describe the bug

Because I can only make higher level potions and can't select what tier to make or downgrade I can't submit the township task.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8282

### Are you using any mods?

No

**Comment by sadume** [comment]
same with cooking can't submit burnt fish tasks

**Comment by MelvorIdle** [comment]
Low tier herblore potions come from Herblore Potions and Potion boxes in Township.

The burnt fish task is a drop from a monster in combat.
