### ISSUE TITLE
[Bug]: Select Recipe should show on each recipe the amount you have in bank

### ISSUE THREAD

**Issue by thadguidry** [MelvorIdle/melvoridle.github.io#3931]
### Describe the bug

Currently when choosing WHAT to cook on any Cooking Utilities, you would normally like to see which recipes have a non-zero amount.  To make things even simpler, the Select Recipe dialog should show the quantity you have.  On other areas of the game such as Smithing this idea is already in place.  But for some reason it is still lacking in the Select Recipe dialog.

### Reproduction Steps

1. Go to Cooking
2. Click on Select Recipe to Cook
3. Notice on each Recipe before Selecting that it is impossible to determine what is available to cook on this dialog, without moving away from it and clicking on the Bank to see quantities available.
4. 

### Expected behaviour

On each Recipe, show the "You Have:" as is done on other dialogs in the game.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/986438/7175f40d-5486-47cd-844c-1238cf8042d0)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [x] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8284

### Are you using any mods?

No

**Comment by coolrox95** [comment]
This issue tracker is only for Bug Reports. Suggestions can be made on our [official discord server](https://discord.com/invite/melvoridle).
