### ISSUE TITLE
[Bug]: Township Task Cant Be Completed

### ISSUE THREAD

**Issue by ShovelBucket** [MelvorIdle/melvoridle.github.io#3932]
### Describe the bug

It appears to be impossible to complete the easy tier township task for delivering 1 burnt cave fish if you have max level cooking and max cave fish mastery as you can no longer burn cave fish.

I also tried using the scroll consumable that reduces cooking success chance but that also appears to replace whatever you burn with coal instead.

So it seems if you arent aware of the township task and max out cooking before hand you get soft locked with this task.

### Reproduction Steps

Have max level cooking
Have max cave fish mastery

### Screenshots

![Screenshot_20231223-095534_Melvor Idle](https://github.com/MelvorIdle/melvoridle.github.io/assets/154689906/156bc682-dbb2-4ee4-99a3-3a1705e1a302)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

8284

### Are you using any mods?

No

**Comment by softgame** [comment]
Hint: A monster drops this item.
