### ISSUE TITLE
[Spelling/Grammar]: Spelling in Astrology game guide

### ISSUE THREAD

**Issue by PtElnor** [MelvorIdle/melvoridle.github.io#3933]
### What text is wrong?

First sentence: "Astrology involves the study of constellations and **gain** knowledge [...]"
Second sentence: "By **continueing** to study these [...]"

### What is the correct spelling or grammar?

First sentence: "[...] and **gaining** knowledge [...]"
Second sentence: "By **continuing** to [...]"

**Comment by arphox** [comment]
Came to say the same.
Found this closed issue, was marked as completed by v1.2.2 but it seems it didn't get fixed.
https://github.com/MelvorIdle/melvoridle.github.io/issues/3791

**Comment by PtElnor** [comment]
Edited original comment to add a second error in the same paragraph (first sentence).
