### ISSUE TITLE
During combat, the same type of drop from the same enemy does not stack

### ISSUE THREAD

**Issue by MrMathewRogers** [MelvorIdle/melvoridle.github.io#394]
When fighting a mob that has drops, only bones are stacked correctly in the 'looting' inventory -- All other items stack separately (e.g. Feathers x24, Feathers x25, Feathers x21... will each take up an inventory spot).

**Comment by RonaldKooij** [comment]
Thats working as intended, you should try to get the amulet of looting from the spider forest dungeon
