### ISSUE TITLE
Farming times (minimally for trees) should be hours and minutes.

### ISSUE THREAD

**Issue by softgame** [MelvorIdle/melvoridle.github.io#3943]
### Describe the bug

Farming times (minimally for trees) should be hours and minutes.

### Reproduction Steps

Go to farming page.
All times are in minutes. Must guess hours or be very good at math.
I know, the 69 Easter egg wouldn't work, but hey.

### Expected behaviour

Have hours to easily estimate harvest time.

### Screenshots

![Untitled](https://github.com/MelvorIdle/melvoridle.github.io/assets/6053601/f4f59587-e0c6-48dd-bf8c-e4b1e4f279ec)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8284

### Are you using any mods?

No

**Comment by coolrox95** [comment]
This issue tracker is only for Bug Reports. Suggestions can be made on our [official discord server](https://discord.com/invite/melvoridle).
