### ISSUE TITLE
[Bug]: Fishing offline 

### ISSUE THREAD

**Issue by Porki1234** [MelvorIdle/melvoridle.github.io#3947]
### Describe the bug

fter fishing online for 4 hours i only recived 24 raw lobster

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [X] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8284

### Are you using any mods?

No

**Comment by Jovasa** [comment]
Is your bank full?

**Comment by Porki1234** [comment]
> Is your bank full?

No

**Comment by coolrox95** [comment]
This issue contains insufficient information to reproduce.
