### ISSUE TITLE
[Bug]: Game unaccessible if the acqueror platform is not working

### ISSUE THREAD

**Issue by francois123456** [MelvorIdle/melvoridle.github.io#3958]
### Describe the bug

Today, 28 of December 2023, Epic games has crashed and this has bring many users not to be able to play their game.

### Reproduction Steps

Connect to the software on any platform (Like the web one) While the acqueror's platform is down

### Expected behaviour

I would like the software to detect if the platform  linked to the account is down (For example, in my case, we can see that my epic account is linked, but my name is considered as undefined du to the crash, this could be a way)

If we see your account linked to a platform that is not responding, we should consider you as owning the full game, and if your saves already contains the extension, it should let you play it.

In the worst case scenario this Logic would bring some people who dont own the game to be able to play the game when a platform is down.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8284

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Closing this as we added purchase verification caching to the game shortly after this issue was reported.
