### ISSUE TITLE
[Bug]: I can't change my username

### ISSUE THREAD

**Issue by kotenok2000** [MelvorIdle/melvoridle.github.io#3962]
### Describe the bug

I want to change username from kotemok2000 to kotenok2000

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/8822292/7f7d200b-490b-4745-a2a1-a1ef73b78b4d)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [X] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8284

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Melvor Cloud does not currently support username changes.

**Comment by kotenok2000** [comment]
Then how can i delete my account and create new?
