### ISSUE TITLE
[Bug]: Golem Territory throws an error when loading offline data

### ISSUE THREAD

**Issue by Lewissss** [MelvorIdle/melvoridle.github.io#3971]
### Describe the bug

When loading a character that was fighting in the Golem Territory dungeon, I get the below error:

`An error occured while processing ticks offline:
Error Name: Error
Error Message: Tried to start timer: Act with invalid tick amount: -1
Stack Trace:
start@https://android.melvoridle.com/assets/js/built/combatManager.js?8284:302:7
queueNextAction@https://android.melvoridle.com/assets/js/built/character.js?8284:422:77
queueNextAction@https://android.melvoridle.com/assets/js/built/player.js?8284:46:42
act@https://android.melvoridle.com/assets/js/built/character.js?8284:393:6
Player/this.timers.act<@https://android.melvoridle.com/assets/js/built/player.js?8284:3:1261
tick@https://android.melvoridle.com/assets/js/built/combatManager.js?8284:299:89
activeTick@https://android.melvoridle.com/assets/js/built/character.js?8284:362:30
activeTick@https://android.melvoridle.com/assets/js/built/player.js?8284:41:20
activeTick@https://android.melvoridle.com/assets/js/built/combatManager.js?8284:59:61
tick@https://android.melvoridle.com/assets/js/built/game.js?8284:203:123
runTicks@https://android.melvoridle.com/assets/js/built/game.js?8284:200:96
processOffline/</<@https://android.melvoridle.com/assets/js/built/game.js?8284:273:109

Active Action: melvorD:Combat
Current Equipment:
Helmet: melvorF:Terran_God_Helmet
Platebody: melvorF:Terran_God_Platebody
Platelegs: melvorF:Terran_God_Platelegs
Boots: melvorF:Terran_God_Boots
Weapon: melvorF:Twin_Exiles
Amulet: melvorAoD:Lesser_Summoning_Amulet
Ring: melvorF:Guardian_Ring
Gloves: melvorF:Terran_God_Gloves
Cape: melvorF:Infernal_Cape
Summon1: melvorF:Summoning_Familiar_Minotaur
Consumable: melvorF:Looter_Pouch
Gem: melvorAoD:Sapping_Barrier_Gem

Action Information:
Is In Combat: true
Fight in Progress: true
-- Start of Player Information --
Next Action: Attack
Next Attack: melvorD:Normal
Is Attacking: true
Standard Spell Selected: melvorD:FireSurge
Ancient Spell Selected undefined
Aurora Selected: undefined
Curse Selected: undefined
Active Prayers:melvorF:Chivalry, 
Equipped Food:
Item: melvorD:Lobster, Qty: 165457
Item: melvorD:Crab, Qty: 14455
Item: melvorD:Swordfish, Qty: 53572
-- End Player Information --
-- Start of Enemy Information --
Enemy: melvorAoD:EarthGolem
Next Action: Attack
Next Attack: melvorD:Normal
Is Attacking: false
Standard Spell Selected: melvorD:WindStrike
Ancient Spell Selected undefined
Aurora Selected: undefined
Curse Selected: undefined
-- End Enemy Information --
Current Area Type: Dungeon
Current Area ID: melvorAoD:Golem_Territory
Modding Enabled. Loaded mods:
SEMI Core
SEMI Drop Chances
SEMI Auto Open
SEMI Auto Master
SEMI Auto Loot
SEMI Auto Smith Bars
SEMI Auto Collect Stockpiles
SEMI Auto Runecrafting
SEMI Auto Farming
SEMI Auto Sell
SEMI Auto Bury
SEMI Auto Bonfire
SEMI Auto Slayer
Mastery Pool Can Overflow
ETA
Shop Item Owned Indicator
AutoSort
Do I have room?
Kills in Combat
Show Slayer Tier
Better Auto Eat
Better Offline Recap
Show Dungeon Completion Count
Item Uses
SEMI Save on Close
Item Township Task Info
Tiny Icons
Show Skill Modifiers
Skip Township Casual Tasks For Free
Semi Auto Township
Priority Miner
Reveal Cartography Map
Bypass Agility Costs
Action Workflows
Upgrade All Potions
Reveal Thieving Loot
Completion Log Icons`

Google Pixel 7 - Android 14 using Android app

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8284

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This was due to the "Better Auto Eat" mod which has since been removed from Mod.io
