### ISSUE TITLE
[Bug]: Buying gem gloves steals money

### ISSUE THREAD

**Issue by HookC1ty** [MelvorIdle/melvoridle.github.io#3973]
### Describe the bug

Hello!
Bought 4 gem gloves (on accident to be fair) and it took all 2000k but only gave me 1 gem gloves (500k worth of gloves.)

(told me to tell what mods and what platform but I did not see a box)  I am on Epic games. Only mod used: Show Item Sources And Uses

### Reproduction Steps

I cannot reproduce because I am out of money and these are expensive (to me) xD

### Expected behaviour

Maybe the 1.5 mil refunded? would be neat but I get it, guppy in the ocean.

Other than that, it fixed?

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [X] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8284

### Are you using any mods?

Yes

**Comment by ekuland** [comment]
You do not receive multiple gloves, instead the one glove you have receives charges. Inspect the glove, it should show 2 million gp worth of uses.

**Comment by HookC1ty** [comment]
> You do not receive multiple gloves, instead the one glove you have receives charges. Inspect the glove, it should show 2 million gp worth of uses.

It was my first time buying them, my apologies for the assumption. I see how it is, 2,000 Charges per 500k gold.

Thank you for the reply!
