### ISSUE TITLE
[Bug]: Cartography map stuck at level 98

### ISSUE THREAD

**Issue by dacahill7** [MelvorIdle/melvoridle.github.io#3975]
### Describe the bug

I left cartography over night and it finished the nodes that I knew of that were left, except the ones that need level 100. My current level is 98. I can't find any nodes by hovering that look like they still need to be mastered in order to continue leveling. If theres anything I should run for Survey XP or Survey level to help debug, I can run it.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/bBQuCjgx

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8284

### Are you using any mods?

Yes

**Comment by softgame** [comment]
Making paper, upgrading maps and refining maps earns XP.
