### ISSUE TITLE
[Bug]: Can Get Past Welcome Screen 

### ISSUE THREAD

**Issue by G00MBA69** [MelvorIdle/melvoridle.github.io#3976]
### Describe the bug

Can't get past this screen for over a week now. I have cleared cache and memory, and uninstalled and reinstalled multiple times without any fix to this issue, yet can even get past this screen.
![Screenshot_20240103_000022_Melvor Idle](https://github.com/MelvorIdle/melvoridle.github.io/assets/94741696/cc70f28d-79ea-4d3a-88b8-a02bbcae45dc)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

1

### Are you using any mods?

Yes

**Comment by nightblade9** [comment]
It looks like this is fixed on the Android beta app; it loads in, like, a second.

@G00MBA69 try that and see if it works for you, too.
