### ISSUE TITLE
[Bug]: Magic Ray attack in Golbin Raid with no corresponding item

### ISSUE THREAD

**Issue by RoninXX** [MelvorIdle/melvoridle.github.io#3998]
### Describe the bug

The attack bar at the top if the player container shows my character frequently using the Magic Ray special, despite not being equipped with any item that grants this power. They are still attacking normally, and with the Tidal Wave special from the sword and the healing attack special from the amulet of healing, but also frequently magic ray (which is annoying because it has very low hit chance and has some sort of major delay at the end of the action).

### Reproduction Steps

Unknown. Have played Golbin Raid on a previous run with essentially the same gear and never saw this issue.

### Expected behaviour

Attacks alternate between standard and tidal wave at 25% chance, with an occasional healing attack from the amulet when health is down.

### Screenshots

![BEC9B1EA-FD97-4093-B3FF-535A7F2EBED0](https://github.com/MelvorIdle/melvoridle.github.io/assets/59519005/2df216f3-6824-41c9-bea3-b46b0936aa5d)
![9EFD1AB6-8F20-47D7-BF2D-FE9BECD3DE7C](https://github.com/MelvorIdle/melvoridle.github.io/assets/59519005/299149bd-010a-47ee-8276-83b237765dc6)
![D626AB57-D63F-4721-8496-5C64ABBC0014](https://github.com/MelvorIdle/melvoridle.github.io/assets/59519005/2be3f656-6232-4ba8-800f-44df8badb13b)
![06C64B5C-F2CA-4B1A-8F47-76C0587A810B](https://github.com/MelvorIdle/melvoridle.github.io/assets/59519005/5d52ed1b-05ae-4326-b11b-6a838ee9b915)
![1DF436A5-0F77-4A22-96C5-2995FA119D43](https://github.com/MelvorIdle/melvoridle.github.io/assets/59519005/a3031f84-7b52-46f4-a72e-fb630ea4964a)
![A1DC9DA9-C033-4EC5-A714-E514779DEF5D](https://github.com/MelvorIdle/melvoridle.github.io/assets/59519005/99a7bbd4-b008-418b-9087-76ff9c70b7bc)
![87EAB128-688B-4B07-9FCF-91F30A49866C](https://github.com/MelvorIdle/melvoridle.github.io/assets/59519005/c3c9fef7-8142-47a9-9597-493c01b37c9f)
![51823E57-9939-477B-AFB8-394F475934C7](https://github.com/MelvorIdle/melvoridle.github.io/assets/59519005/6bc0c3be-2660-425c-913c-2f53aaff4ebb)
![BC72482C-B07B-4911-9744-C2CC70E5AA39](https://github.com/MelvorIdle/melvoridle.github.io/assets/59519005/d03b34d2-7ef7-4fd5-b637-931526ccb70c)
![8773E04D-EC8D-40AB-BC3A-6D5F6ABC083D](https://github.com/MelvorIdle/melvoridle.github.io/assets/59519005/c1f5a146-ec4a-44a4-8050-741a6a5e7c31)
![43D445F3-2A17-407E-86CC-89DFB8F522F3](https://github.com/MelvorIdle/melvoridle.github.io/assets/59519005/a43da839-3ff8-4111-ab7c-019a97c75556)
![226A6742-B1C3-4116-9B06-7021B2C872DB](https://github.com/MelvorIdle/melvoridle.github.io/assets/59519005/7e048316-07d7-4a11-9c39-04cd1bc3c479)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8284

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
The Magic Ray special attack came from selecting an "Alt" weapon within the raid which provides a random special attack

**Comment by RoninXX** [comment]
I never selected any Alt weapons as upgrade options, and you can see in the screenshots that no alt weapon is equipped.
