### ISSUE TITLE
[Bug]: Remove quick access items not owned

### ISSUE THREAD

**Issue by hayward706** [MelvorIdle/melvoridle.github.io#4000]
### Describe the bug

When you put items in your quick access for a skill, there is no way to then remove those items if  you no longer possess the item. For example in the bar below I no longer have a herblore skillcape so would neet to buy a new one to remove it from this set.
![Screenshot_20240109-180921](https://github.com/MelvorIdle/melvoridle.github.io/assets/48442351/cac7ea63-eb0c-47e8-a8c7-45fef55ba9f6)

### Reproduction Steps

See image
Add an item to quick equip on a non combat skill
Open quick equip on a non-combat skill:selectable 
Remove the item from the bank
Open quick access again : item still on quick equip and can't be removed until reobtained

### Expected behaviour

A method to remove items from quick equip irrespective of current ownership state (potentially a bin to drag them to at the bottom of the tray?)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8284

### Are you using any mods?

No

**Comment by staticf0x** [comment]
I would appreciate this so much as well
