### ISSUE TITLE
[Bug]: Mastery Master Achievement not popping up

### ISSUE THREAD

**Issue by maskeci** [MelvorIdle/melvoridle.github.io#4003]
### Describe the bug

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/119742567/b2a630d5-9fce-4d5f-858f-d03df834c8d0)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/119742567/5436a791-f33e-4dd4-8518-f3d9d620a79c)
Hello!
I have made 100% completion as you see but achievement is not popping up. 

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/119742567/eb906c42-b509-4c2e-be40-ea3268ade358)
Cocking is over-completed somehow
Others are ok.
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/119742567/43204425-b3c2-4355-bb01-61dc31a9e7e8)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8284

### Are you using any mods?

Yes

**Comment by 04Slash** [comment]
This is a bug with SEMI Auto Master. It adds mastery XP to a hidden item in Cooking. You can delete the mastery in that item by entering the following into the console: `game.cooking.actionMastery.delete(game.cooking.actions.getObjectByID('melvorF:Lemon_Cake'));`

To open the console, you can either press F12 on the web version of the game or use the dev.Console mod for other versions.
