### ISSUE TITLE
[Bug]: High tier 0/x buildings don't degrade

### ISSUE THREAD

**Issue by Balor64** [MelvorIdle/melvoridle.github.io#4009]
### Describe the bug

With multi-tier buildings, if you have 0 built of any tier except the first, that building slot does not degrade, even though you have built things in that slot.

For example, if you have 0/25 Cottages in Arid Plains, your Cottage building slot does not degrade, which means the Basic Shelters, Wooden Huts, and Houses in that slot will continue to give their 1810 population, without ever needing to be repaired.

This is admittedly a minor issue, but those lower tier buildings were built, so they should need to be repaired to keep their efficiency up.

From what I understand of the code, `if a building is fully built (x/x) and a higher tier of that building exists in the code`, that building doesn't degrade. I think this should be changed to `if a building is fully built (x/x) and a higher tier of that building has been built in that biome`.

If it helps, there was some discussion about this on Discord [here](https://discord.com/channels/625838709203271680/625840209531240469/1195532062048919642).

### Reproduction Steps

1. Go to Township and build 20 Basic Shelters in Grasslands, so that you have 0/30 Wooden Huts.
2. Wait a day.
3. See that Wooden Hut is still at 100% efficiency.

### Expected behaviour

Wooden Hut should degrade.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/HWMYf04o

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/156492849/cca56251-3d9d-4461-a906-8f38cb547580)

### Console output

I'm playing on Epic Games.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [X] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8284

### Are you using any mods?

No

**Comment by dwentz-fss** [comment]
This issue still exists as originally reported, as of subversion 8381.

**Comment by Balor64** [comment]
This issue still exists as originally reported, as of subversion 8381.
