### ISSUE TITLE
Slayer pet hover text bug

### ISSUE THREAD

**Issue by duncansclarke** [MelvorIdle/melvoridle.github.io#402]
**Describe the bug**
Minor text bug in slayer pet hover text

**To Reproduce**
1. Go to pets
2. Hover over Asura slayer pet
3. See error - text that reads "Created by Patron ([])"

**Expected behavior**
A patron's name, or no text at all aside from the pet name and bonus description.

**Screenshots**
https://i.imgur.com/zhd8NVK.png

**Browser**
Chrome

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
[ ] is actually the name of the Patreon who created the item :)
