### ISSUE TITLE
password email[Bug]: <title>

### ISSUE THREAD

**Issue by LostRothschild** [MelvorIdle/melvoridle.github.io#4021]
### Describe the bug

Program logged out of android version.
Password forgotten / incorrect
Used forgotten password button to reset
No email received

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

v1.2.2

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
If no email was received, this either means the wrong email was added or there is not email attached to the account.
