### ISSUE TITLE
[Bug]: <pushing back button>

### ISSUE THREAD

**Issue by Spilden** [MelvorIdle/melvoridle.github.io#4023]
### Describe the bug

Pushing the back button or swiping back on Android app, closes the game immediately, making you have to reload the game when you open it again. 

### Reproduction Steps

1. Open the game
2. Be anywhere in the game
3. Push the phone's back button

### Expected behaviour

Ask if you really want to quit the game.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8287

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Same as #4222 (Closing this one to clean issues)
