### ISSUE TITLE
[Bug]: mithril platebody not upgrade

### ISSUE THREAD

**Issue by Estileto** [MelvorIdle/melvoridle.github.io#4025]
### Describe the bug

I tried 3 times to upgrade mithril platebody, in each one it discounts me gold and silver bar but no one got upgraded. Not sure if there ir any log for this.

For reference, helmet, shield and boots was correctly upgraded.

I'm using the demo version until now.

### Reproduction Steps

Go to bank
Select mithril platebody
Select upgrade item
Select yes or whatever it says

### Expected behaviour

Have a mithril platebody upgraded

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8287

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Can you please provide a screenshot? I believe it is in your bank, and you can use the bank search to locate it.
