### ISSUE TITLE
feather storm crossbow [Bug]: <title>

### ISSUE THREAD

**Issue by Nrose1988** [MelvorIdle/melvoridle.github.io#4028]
### Describe the bug

The feather storm crossbow in goblin raid special attack does not trigger 

### Reproduction Steps

Start goblin raid 
Get crossbow
See now special attack triggering

### Expected behaviour

I’d like to see it working 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [x] Throne of the Herald
- [x] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8287

### Are you using any mods?

No

**Comment by Nrose1988** [comment]
![IMG_4119](https://github.com/MelvorIdle/melvoridle.github.io/assets/157327047/e394e5a6-e352-46ae-a45a-d1c3078d4195)

**Comment by MelvorIdle** [comment]
This is due to the weapon selected as an "Alt" weapon, which means it was given a random special attack.
