### ISSUE TITLE
Main account that wasn't hc had turned into hc.

### ISSUE THREAD

**Issue by badgehunter** [MelvorIdle/melvoridle.github.io#403]
**Describe the bug**

Main account that wasn't hc had turned into hc.

**To Reproduce**

No idea whats the steps are for this bug but, after months prior to hc, i returned today and hc was implemented, i started it to start it as side project along with my main account which wasn't hc. i then logged to my account to save it to my cloud account, i hopped to main account and boom, my main had turned into hc. i managed to turn my account back to normal account thanks to discord

**Expected behavior**
i expected my main account that wasn't hc before hc was even implemented to be turned into hc after it was implemented.
**Screenshots**
https://media.discordapp.net/attachments/625838709744599088/754798048932135112/unknown.png?width=1089&height=612 177013 is my main save and the one on middle was the hc that i started today as side project.
**Browser**
Please tell us what browser you are using and what version.

Versio 85.0.4183.83 (Virallinen koontiversio) (64-bittinen) (sorry too lazy to translate to english, its Finnish)

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.
not that i would remember any scripts.

**Comment by Nomeru** [comment]
I thought I'd add that I went messing around and managed to get some variation of this to happen, maybe the added info can be of help.

Process: Cleared away a character slot, started new HC, went to import and imported a normal save from June. It loaded as hardcore. Note it did not happen if I chose Normal from the new character screen. I have no idea if this is at all like what happened to BadgeHunter, but it's at least repeatable. I did this in chrome.
