### ISSUE TITLE
[Bug]: <title>cool rock

### ISSUE THREAD

**Issue by andylkf1995** [MelvorIdle/melvoridle.github.io#4030]
### Describe the bug

I have the pet cool rock for a few days, but I still can buy any pet related to the cool rock.
the system claimed that I do not have one, 

### Screenshots

![IMG_7362](https://github.com/MelvorIdle/melvoridle.github.io/assets/157551847/e6e09287-7e71-435a-a9bd-6b9f2b920d34)
![IMG_7363](https://github.com/MelvorIdle/melvoridle.github.io/assets/157551847/c786d4fe-e4fb-4af3-b06d-b05d3d9b86a9)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

8287

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
"Cool Rocks" is a building you construct in Township, and has no relation to the Cool Rock pet itself.
