### ISSUE TITLE
[Bug]: <title> New steam update flagged

### ISSUE THREAD

**Issue by DeathDoors** [MelvorIdle/melvoridle.github.io#4031]
### Describe the bug

The new update tried to send 9 UDP requests and 5 TCP without a valid signature and was flagged by AV.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?????

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
The Melvor Idle client runs on NW.js, and the new version was updated to v0.82.0 so support the new Steamworks SDK. It's build using `nw-builder`: https://github.com/nwutils/nw-builder

Can you send the notification of what your AV was warning? I'll try and find the source of this within Chromium. There will most likely be a flag I can use to disable whatever it's doing (I assume "phoning home" or similar).

**Comment by DeathDoors** [comment]
1) 10.5.0.2,                  60296   - Outbound UDP,ssdp
2) 169.254.200.16,      port^    - Outbound UDP,ssdp
3) 169.252.200.16      5353      - Outbound UDP
Tried to open port 60296 4 more times
4) Tcp attempts on ports 52709 , 52724 , 52725 for local web browser call (10.5.0.2)
14 actions blocked on program MelvorIdle.exe
