### ISSUE TITLE
[Bug]: Game crashes on start on m1 mac (steam)

### ISSUE THREAD

**Issue by jwmccowan** [MelvorIdle/melvoridle.github.io#4032]
### Describe the bug

Game crashes on start on m1 mac (steam)

Starting the game will immediately crash with message `Melvor idle is damaged and cannot be opened`.

This started happening today, and I think it might have to do with an update to the javascript library used to render the game.

### Reproduction Steps

n/a, 

### Expected behaviour

Game doesn't crash :D

### Screenshots

<img width="260" alt="Screenshot_2024-01-24_at_11 10 06" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/1703264/8ea0c7b0-1497-4095-934d-0e1b171dae34">

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

??? I can't tell because I can't open the game

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Does the issue still occur after reinstalling the game? I have no issues loading it on my M1 MacBook

**Comment by jwmccowan** [comment]
I did the usual: restart mac, I reinstalled the game, then reinstalled steam (Steam games have been acting up a lot recently). The issue still occurs after all of that.

Happy to provide crash/debug logs if you tell me where to look.

**Comment by jwmccowan** [comment]
I do have a software update for osx, maybe the upgrade to nwjs doesn't play nice with my version of Sonoma.  I'm updating now, I'll check back in a while with whether that fixes the issue, it's getting late in my timezone.

**Comment by MelvorIdle** [comment]
If the issue still occurs after that, you can try deleting the Client data folder. This will sign you out of the cloud and delete your local saves:

1) Navigate to `~/Library/Application Support/Melvor Idle`
2) Delete everything in this folder.

If you can't see the folder in finder, you can use the Terminal to access it.

**Comment by mihil99** [comment]
I have the same problem. Clearing `~/Library/Application Support/Melvor Idle` doesn't seem to fix it. Contrary to original report, I am not using any mods. Verifying game files inside Steam doesn't seem to fix it either.

**Comment by EvilAdd** [comment]
> I have the same problem. Clearing `~/Library/Application Support/Melvor Idle` doesn't seem to fix it. Contrary to original report, I am not using any mods. Verifying game files inside Steam doesn't seem to fix it either.

Same here, can't start the game, I'm on a MacOS Monterey if that help

**Comment by jwmccowan** [comment]
The game is still crashing on start after updating to Sonoma 14.3 and clearing out `Application Support/Melvor Idle`.

**Comment by MelvorIdle** [comment]
There seems to be another issue where Apple believes this app is not signed by an "identified developer", even though when running the codesign verification on the app, it clearly shows its signed by me with an identified developer attached.

Follow these steps and see if it gets the app to load:

1. Reinstall the Melvor Idle.
2. Select "Play" from the Steam library.
3. After the "Verifying" prompt appears and completes, close the damaged error prompt.
4. Then, open the Mac System Settings.
5. Select "Privacy and Security".
6. Select "Security Settings"
7. In the Security Settings, you should see a prompt saying "Melvor Idle was blocked..."
8. Click the "Open Anyway" button under this text.
9. Enter your system password if prompted.
10. Then select "Open" on the security prompt.
11. The game should now launch

**Comment by jwmccowan** [comment]
Yep that cleared it up for me

**Comment by MelvorIdle** [comment]
Thanks for confirming. I'm currently researching a permanent solution to this problem as the steps I provided definitely aren't ideal for everyone.

**Comment by MelvorIdle** [comment]
A client update has been released for MacOS (Steam) only. This update addresses the issue where the app was being blocked from opening due to it not being signed by a "verified developer" (The error produce mentioned that the app was damaged)

This issue has now been resolved.

If simply updating still produces the same error - uninstalling and reinstalling will fix it. This is due to Apple's "Gatekeeper" caching app verification checks. Reinstalling the app clears this cache.

**Comment by MelvorIdle** [comment]
Closing this issue as the original report was successfully resolved. If you are still having issues launching Melvor Idle on MacOS, please post details here: #4034
