### ISSUE TITLE
[Bug]: Game will not launch via Steam on Windows 11 since latest update

### ISSUE THREAD

**Issue by jducci25** [MelvorIdle/melvoridle.github.io#4033]
### Describe the bug

When I got to launch the game via Steam, it doesn't seem to launch. When i check task manager, i see five instances of the game running but nothing past that. I'm able to close the processes in task manager but am not able to successfully launch the game. Tried running the game just using the executable, but same result. 

### Reproduction Steps

1. Open Steam
2. Click on Library at the top
3. Click on the play button for Melvor Idle
4. Game does not launch
5. Check task manager, and see five instances of the game running under processes
6. Game still doesn't launch

### Expected behaviour

Just for the game to launch properly as it would prior to the latest update

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/48848177/55a6ca9a-957b-4486-a803-eba4f2b4795d)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

Unknown at this time as game will not launch

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
I'm currently using Windows 11 and the game is loading fine for me without issues.

First thing to try is verify the game files via Steam and try and launch the game. If that fails, uninstall the game via Steam and reinstall it.

If that fails, try the below.

If you have a copy of your local saves, or have update to date cloud saves, you can try and reset the client by following these steps. Note that this will log you out of the cloud and remove your local saves:
- Navigate to `%LocalAppData%` in your file explorer and delete the `Melvor Idle` folder.

**Comment by 11uhafnk** [comment]
I have same problem after update yesterday
and many another people in "Steam" discussion https://steamcommunity.com/app/1267910/discussions/0/4140564660379581847/ 

I used mac 
Macos 14.2.1

Steam Beta Branch:  Stable Client
Steam Version:  1705108172

App version: i don't sure where i can check it
file info show 1.1 
<img width="1146" alt="image" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/5215020/f1a7b01f-a1cb-4e19-9582-acf43d802b3f">
<img width="691" alt="image" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/5215020/1c7ab24b-9df4-4d73-8b01-95b50a29b854">


problem: after running application have status "running" but haven't any window
<img width="1259" alt="image" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/5215020/502804e9-64bb-4ec7-846e-84e022f3c500">

I haven't use any mods
installed and active both dlc

I try: 
steam verify files - it show ok
reinstall application - same result
rm userdata files - same result

**Comment by MelvorIdle** [comment]
@11uhafnk This thread is primarily for W11 specific issues, can you post your details in the MacOS report thread? #4034

I'll keep the details separate to help locate the issue.

**Comment by 11uhafnk** [comment]
ok, I duplicated message in that thread

**Comment by MelvorIdle** [comment]
@jducci25 Hey, is there a chance your anti-virus may be blocking Melvor Idle from opening?
