### ISSUE TITLE
[Spelling/Grammar]: drop down menu (golbin* raid)

### ISSUE THREAD

**Issue by Wozbi95** [MelvorIdle/melvoridle.github.io#4035]
### What text is wrong?

Goblin is misspelled in the drop down menu where the Goblin Raid is located...I just noticed Goblin was spelt like "golbin" 👍

### What is the correct spelling or grammar?

Goblin

**Comment by pokeball99** [comment]
this is an intended spelling and not a typo, as seen in the [171 results that turn up for the term on the wiki](https://wiki.melvoridle.com/index.php?search=golbin&title=Special%3ASearch&go=Go&fulltext=1) vs the [8 (which are mostly redirects](https://wiki.melvoridle.com/index.php?search=goblin&title=Special%3ASearch&go=Go&fulltext=1) for the traditional spelling

**Comment by Wozbi95** [comment]
You learn something NEW everyday and TIL about Golbins .... thanks for in
the insight!
