### ISSUE TITLE
[Bug]: <Error loading extension>

### ISSUE THREAD

**Issue by InclassAdam** [MelvorIdle/melvoridle.github.io#4037]
### Describe the bug

When I attempt to launch the game on steam I get this error message. I'm on Windows 10, I've been playing the game on steam since it came out and the only recent change was the recent update.

### Reproduction Steps

Click launch on steam.

### Expected behaviour

The game to open

### Screenshots

![melvor bug](https://github.com/MelvorIdle/melvoridle.github.io/assets/62788661/39b40c24-036d-45a6-8fb1-b9c892d9451e)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8256 not sure

### Are you using any mods?

Yes

**Comment by InclassAdam** [comment]
I've tried uninstalling and reinstalling, I don't have an anti virus that would interfere with the game.

**Comment by Meooowriphiphip** [comment]
I have the same issue

**Comment by 04Slash** [comment]
Try going into Steam, right clicking Melvor > Manage > Browse local files then either remove everything or delete it.

Then go back into Steam, right click Melvor > Properties > Installed Files and click "Verify integrity of game files". The previous step must be done first.

**Comment by InclassAdam** [comment]
> Try going into Steam, right clicking Melvor > Manage > Browse local files then either remove everything or delete it.
> 
> Then go back into Steam, right click Melvor > Properties > Installed Files and click "Verify integrity of game files". The previous step must be done first.

This worked, thank you! I'm going to attempt to compare the files and see if I can find the culprit

**Comment by InclassAdam** [comment]
Update: I have a sneaking suspicion this is caused by early day modding on steam where you had to create an autorun.js file to load mods or whatever it was used for way back when.

**Comment by Meooowriphiphip** [comment]
> Try going into Steam, right clicking Melvor > Manage > Browse local files then either remove everything or delete it.
> 
> Then go back into Steam, right click Melvor > Properties > Installed Files and click "Verify integrity of game files". The previous step must be done first.

Would this delete my savefile, and I have to go back to my backup from 22 days ago?
No way for me to save my save file?

**Comment by InclassAdam** [comment]
> > Try going into Steam, right clicking Melvor > Manage > Browse local files then either remove everything or delete it.
> > Then go back into Steam, right click Melvor > Properties > Installed Files and click "Verify integrity of game files". The previous step must be done first.
> 
> Would this delete my savefile, and I have to go back to my backup from 22 days ago? No way for me to save my save file?

I was going to just load my cloud save but my local saves were still there, however, I would backup the folder first then do the above just incase your saves aren't there.

**Comment by Meooowriphiphip** [comment]
> > > Try going into Steam, right clicking Melvor > Manage > Browse local files then either remove everything or delete it.
> > > Then go back into Steam, right click Melvor > Properties > Installed Files and click "Verify integrity of game files". The previous step must be done first.
> > 
> > 
> > Would this delete my savefile, and I have to go back to my backup from 22 days ago? No way for me to save my save file?
> 
> I was going to just load my cloud save but my local saves were still there, however, I would backup the folder first then do the above just incase your saves aren't there.

Ah. Thanks.

I didn't have any recent cloud save. I turned off automatic cloud save a while back. (Don't remember why. It was long ago) And just relied on in-frequent manual saves to text document.
Last one was 23 days ago
But I'm glad my local save was still there when I tried your solution.

**Comment by 04Slash** [comment]
> Update: I have a sneaking suspicion this is caused by early day modding on steam where you had to create an autorun.js file to load mods or whatever it was used for way back when.

I'm fairly certain this is the cause of it as someone else had the same issue and also did modding prior to the mod browser.

> Would this delete my savefile, and I have to go back to my backup from 22 days ago?
No way for me to save my save file?

Save files are stored in `%LocalAppData%`. The files that need to be deleted are just the game files. The reason they must be manually deleted is because (from what I've heard) Steam doesn't delete files that were modified/created by the user. As mentioned above, this issue is due to having the old modding files.

**Comment by InclassAdam** [comment]
> > Update: I have a sneaking suspicion this is caused by early day modding on steam where you had to create an autorun.js file to load mods or whatever it was used for way back when.
> 
> I'm fairly certain this is the cause of it as someone else had the same issue and also did modding prior to the mod browser.
> 
> > Would this delete my savefile, and I have to go back to my backup from 22 days ago?
> > No way for me to save my save file?
> 
> Save files are stored in `%LocalAppData%`. The files that need to be deleted are just the game files. The reason they must be manually deleted is because (from what I've heard) Steam doesn't delete files that were modified/created by the user. As mentioned above, this issue is due to having the old modding files.

Good to know, as soon as I compared the old and new files I noticed autorun. something and it all came back to me and it would make sense because it was running the mods and the error is an issue with running extensions which, in my basic mind, sounds like they are related.

Thanks for the help!
