### ISSUE TITLE
Adamant, Adamant (S) and Adamant (G) platebodies still have the old style borders

### ISSUE THREAD

**Issue by Adds3000** [MelvorIdle/melvoridle.github.io#404]
**Describe the bug**
Adamant, Adamant (S) and Adamant (G) Plate-bodies still have the old style borders

**To Reproduce**
Seen in both the Item log and in the Smithing page for Addy Platebody

**Expected behavior**
Updated model applied as per other platebodies.

**Screenshots**
![image](https://user-images.githubusercontent.com/71256119/93063457-34bf2900-f66e-11ea-8d50-049629a5549f.png)
![image](https://user-images.githubusercontent.com/71256119/93063562-5b7d5f80-f66e-11ea-973b-99ae54e3aa03.png)

**Browser**
Vivaldi	3.2.1967.47 (Stable channel) (64-bit)

**Console output**
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/assets/media/shop/assets/media/shop/perpetual_haste.svg:1 Failed to load resource: the server responded with a status of 404 ()
save.js?410:56 Loading Save Game...
save.js?410:179 Save Game Loaded...
smithing2.js?402:221 Loading Smithing...
mastery.js?401:187 Updating Masteries
mastery.js?401:23 Loading Masteries...
main.js?423:537 Game Loaded
cloud.js?430:106 1
cloud.js?430:477 Connected to PlayFab successfully
DevTools failed to load SourceMap: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://melvoridle.com/sm/13c28911820333eb6a51103a0e2096477a38941cc79afbf16b59f3d5a5f63086.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://melvoridle.com/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://melvoridle.com/assets/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
