### ISSUE TITLE
[Bug]: Goblin Raid Shockwave weapon uses Frozen Wind attack

### ISSUE THREAD

**Issue by pxtang** [MelvorIdle/melvoridle.github.io#4044]
### Describe the bug

In Goblin raid, the Shockwave crossbow weapon uses Frozen Wind effect instead of Shockwave effect.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/U5BDluxW

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/9750575/c5512904-221a-4e0c-a5fa-fd6e2ad07c04)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/9750575/1f29969e-0316-421e-975c-4e19428541a6)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8380

### Are you using any mods?

Yes

**Comment by 04Slash** [comment]
Items with special attacks can roll as 'ALT' items in Golbin Raid. ALT items will roll a random special ability instead of using their normal special attack(s). The tooltip on the item will not be updated to reflect this (however this could be considered a bug).

It would appear your Shockwave was an ALT item.
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/f54eacff-4e4d-4dd2-b5eb-05ba01536798)

**Comment by pxtang** [comment]
Oh, that's what it means! Thank you!

**Comment by Deuxis** [comment]
I just got the same problem with Gloves of Greater Shade Summon having Frostburn as special attack without changing the tooltip or indicating that this is intended in any other way besides the [ALT] in the name on selection screen. I didn't know what it means and it doesn't display when I hover over the gloves in equipment UI, so I was about to report it as a bug. This also harmed my build a bit as I also had the Ultima Godsword and its special attacks became less likely in favour of inferior Frostburn.

It would be best if ALT items displayed what their special attack will change into on selection screen, but if that's not possible or desired please adjust the tooltip of equipped item and preferably add an explanation of what ALT means.
