### ISSUE TITLE
Unknown Error when signing in.

### ISSUE THREAD

**Issue by Aramiis2001** [MelvorIdle/melvoridle.github.io#4045]
### Describe the bug

Everytime I try to login it says; Unkown Error; Sorry, the redirect url you are using is not allowed for this client.
I'm on Epic Games.
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/158370695/6add6234-0053-4048-ab34-a4a3c854d268)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
I have now released a hotfix for this issue. Thanks for the report.
