### ISSUE TITLE
[Translation Error]: <Chicken is Korean in Chinese Translation>

### ISSUE THREAD

**Issue by StrawHat-Melvor** [MelvorIdle/melvoridle.github.io#4047]
### Which text in the game has a translation error?

![Korean-Chinese chicken Error](https://github.com/MelvorIdle/melvoridle.github.io/assets/94126126/20257781-6232-4f1b-adb7-8f2b44e44df4)
The chicken is written in Korean, but it is for a Chinese user.

**Comment by MelvorIdle** [comment]
This issue has now been hotfixed.
