### ISSUE TITLE
[Bug]: Mastery Magnets (still) don't get consumed in Archaeology

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#4054]
### Describe the bug

Same issue as #3637  but the issue still remains. Archaeology does not consume Mastery Magnets while benefiting from them.

### Reproduction Steps

1. Equip 1 Mastery Magnet
2. Excavate in Archaeology
3. Get token, see Mastery Magnet still in consumables slot

### Expected behaviour

For bugs not to re-appear :)
(Mastery magnets should be consumed per Archaeology action)

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/0ad97e6f-cc4d-480b-9e34-1834c1a4dda8)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/b8cff939-ddab-4fde-a5c2-b4c0044c525b)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8381

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This issue has now been hotfixed (again).
