### ISSUE TITLE
[Bug]: Amulet of grudge is applying -100% evasion on the enemy

### ISSUE THREAD

**Issue by FriHo** [MelvorIdle/melvoridle.github.io#4062]
### Describe the bug

The -evasion% effect on Amulet of Grudge is 5x stronger than it's supposed to be

### Reproduction Steps

1. Equip amulet of Grudge
2. Fight any enemy
3. Hover your mouse over the Grudge effect on the enemy

### Expected behaviour

On the first turn the Grudge effect should apply -20% evasion

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/VVx4ym5F

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/152061332/ed9b3c3f-88fa-4459-bfea-a8f56cf7fc8e)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8394

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Fix has now been released: https://news.melvoridle.com/game-update-v1-2-2-8360-2/
