### ISSUE TITLE
[Bug]: Can't mine Onyx

### ISSUE THREAD

**Issue by Expakun** [MelvorIdle/melvoridle.github.io#4066]
### Describe the bug

I can't mine Onyx. Every time I click on it says mining but nothing happens and the HP of the Onyx Vain is also extremely high

### Reproduction Steps

1. Go to the mining tab
2. Try to mine Onyx
3. wait and see

### Expected behaviour

If I click on Onyx to mine it, it should mine it

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/45179004/5875ac60-a54d-4c16-839f-d8c03dc4bf2e)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8394

### Are you using any mods?

No

**Comment by 04Slash** [comment]
Your current HP for Onyx is 0 out of a maximum of 69696969.

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/3570b8f3-aaa4-4f83-91bf-3e7f92b21eb2)
You gain gem vein HP by mining any ores above Dragonite.
