### ISSUE TITLE
[Bug]: Incorrect Auto Eat Values

### ISSUE THREAD

**Issue by SocietalShip** [MelvorIdle/melvoridle.github.io#4068]
### Describe the bug

The values for the Auto Eat healing threshold and food efficiency are incorrect. I have Auto Eat Tier 3 purchased and the Astrology Ashtar constellation +8% Auto Eat Efficiency. To my understanding the values should be as follows:
1. Heal to 80% HP when at or below 40% HP
2. Food Efficiency 108%

Until recently, the values were correct. However, at some unknown time the values changed to the this:
1. Heal to 80% HP when at or below 42% HP
2. Food Efficiency 58%

This issue is specific to my main (unmodded) save. My second save does not currently have this issue. Hopefully something can be done about this, otherwise it'll really make doing late game dungeons a drain on the food stores!

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/ZsDy8VOj

### Screenshots

![Screenshot 2024-02-07 220441](https://github.com/MelvorIdle/melvoridle.github.io/assets/159409863/1c1ff498-269b-4a39-92e2-94576a5c79d6)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8394

### Are you using any mods?

No

**Comment by 04Slash** [comment]
You're currently sitting on "The Shimmering Oasis" Point of Interest in Cartography which reduces Auto Eat Efficiency by 50% and increasing Auto Eat Threshold by 2%.
https://wiki.melvoridle.com/w/Cartography#TheShimmeringOasis
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/1bd6205c-c1f0-4149-aa0d-579235500f58)

**Comment by SocietalShip** [comment]
> You're currently sitting on "The Shimmering Oasis" Point of Interest in Cartography which reduces Auto Eat Efficiency by 50% and increasing Auto Eat Threshold by 2%. https://wiki.melvoridle.com/w/Cartography#TheShimmeringOasis ![image](https://private-user-images.githubusercontent.com/57328541/303228232-1bd6205c-c1f0-4149-aa0d-579235500f58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNzI5NDYsIm5iZiI6MTcwNzM3MjY0NiwicGF0aCI6Ii81NzMyODU0MS8zMDMyMjgyMzItMWJkNjIwNWMtYzFmMC00MTQ5LWFhMGQtNTc5MjM1NTAwZjU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDA2MTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0ZjkwNGQzMWQ5MGRlNDRhMjRhNTdiZTRlOWMzYTkxNTJmYjQxZjcxYjc4Nzg0NDJlMWRlN2U0YzRmZTA3YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pYAMhJR8uDqarGeFO2s8czbvsuLZTvfjSsKPKVQUEIo)

Oof... thanks. I was looking all over the wiki to see if there was something that caused something like this, but I couldn't find anything. Assumed it was a bug, my bad!
