### ISSUE TITLE
Big ol Ron Bank Visual "nuisance"

### ISSUE THREAD

**Issue by Cappuchinoo** [MelvorIdle/melvoridle.github.io#407]
**Describe the bug**
Surely it's been said before, and perhaps it's intended, but when you have a Big ol Ron in the bank, the row it's in is pushed slightly to the left.

**To Reproduce**
Just have a Big ol Ron in the bank, in any slot that isn't the very last.

**Expected behavior**
I expected the row to be just like the others. I'm not sure if this is exactly what you're asking, but oh well.

**Screenshots**

![My_OCD](https://user-images.githubusercontent.com/71291488/93135164-46c1bb80-f6b0-11ea-8d45-51b2c4fb4f73.png)

**Browser**
I'm using the latest version of Firefox as of 14/09/2020.

**Console output**
I'm really not sure of what I'm meant to copy paste, I apologize :(. Hope it won't be necessary.

**Are you using any scripts?**
I'm not using any scripts.

**Comment by fewfre** [comment]
Similar issue with dragon scimitar

![image](https://user-images.githubusercontent.com/10587648/93689740-5c175b00-fa9f-11ea-9c17-36ee00d49ea5.png)

**Comment by MelvorIdle** [comment]
Fixed in upcoming Bank rework
