### ISSUE TITLE
[Bug]: Melvor not closing properly on Windows 10

### ISSUE THREAD

**Issue by NomadElf** [MelvorIdle/melvoridle.github.io#4073]
### Describe the bug

Sometimes, Melvor refuses to close properly. I can't reproduce this all the time, but it happens often enough since the last update. The game window closes, but the process stays open in the background. I have to kill the process with the task manager.

### Reproduction Steps

n/a

### Expected behaviour

Melvor's process ending when you close the game.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

8417

### Are you using any mods?

Yes

**Comment by ModernKiwi** [comment]
I am also having a similar issue on windows 11. However, when I close the game steam says its still running, yet checking processes in task manager shows no game process running.

Im running the latest steam version, no mods, both DLC.

**Comment by NomadElf** [comment]
Still happening here on 8448 too.

Clicking "stop" on steam works sometimes, sometimes not even steam can close it. Task manager works 100% of the time, though.

**Comment by coolrox95** [comment]
Duplicate of #3786
