### ISSUE TITLE
[Bug]: Enlarged Icons & Misaligned Clickboxes

### ISSUE THREAD

**Issue by protowyn** [MelvorIdle/melvoridle.github.io#4074]
### Describe the bug

In combat, all monster images are blown up to a very large size. The 'fight' and 'drops' seem to be pushed out to the wrong place, so the boxes are unclickable, and so I can not do any combat.

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/159602083/beda94dc-0a0e-4b21-a6c7-76f12cf4c9af)

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/159602083/ab4b5f82-5bef-40c3-90bf-89d3db0ceebc)

Additionally, some of the skill icons on the left sidebar are blown up and covering up the words:
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/159602083/bd66df3f-81ea-4358-8fad-d3a7b6942e2d)

Also, the current active skill's icon is blown up even further and is on the bottom of everything, visible when I scroll down:
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/159602083/cd020b8e-55fd-4eda-82e6-e5c0c95e7705)

The code that comes after the V1.2.2 is also covered up by the icons, so I can't find what that is:
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/159602083/164d9b21-d63f-43c6-9750-5578dd15b1b0)

### Reproduction Steps

This occurs every time I play now. I have tried reinstalling from scratch, verifying integrity of game files, and computer reset.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?

### Are you using any mods?

No

**Comment by 04Slash** [comment]
You should be able to fix this by navigating to (**Windows**: `%LocalAppData%`, **Mac**: Open Finder and Command+Shift+G: `~/Library/Application Support`) and move the Melvor Idle folder (aka the "Backup") elsewhere. This will log you out of your Melvor Idle and Epic Accounts and remove your local saves. After doing so, launch the game.

If you wish to restore your saves, open the the newly created Melvor Idle folder and the "Backup" from earlier, and navigate to: (Windows will have `Userdata` first)  `Default/Local Storage` and copy `leveldb` from the "Backup" into the same location in the new Melvor Idle folder.

This is a valid issue and I've seen a few people have it now so you can keep this report open.

**Comment by protowyn** [comment]
That worked perfectly, thank you for the help!
