### ISSUE TITLE
[Bug]: Paladins Drop Gold Topaz Rings

### ISSUE THREAD

**Issue by dozn** [MelvorIdle/melvoridle.github.io#4076]
### Describe the bug

Was doing hard Slayer tasks, received Paladins, extended the task, and one of the kills shortly thereafter dropped a Gold Topaz Ring.

This isn't the first time it has occurred, and I'm uncertain (though I _believe_) it was also a Paladin last time as well.

### Reproduction Steps

Not sure if it _only_ occurs when killing them as a Slayer task, so I'll simply say:
1) Kill Paladins

### Expected behaviour

They should never drop Gold Topaz Rings.

### Screenshots

Worn equipment:
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/16659513/99cccb92-0127-4284-86eb-a0a31e3c6f4e)

### Which platforms are you experiencing this bug on?

- [X] Epic Games

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8417

### Are you using any mods?

No

**Comment by Torun-S** [comment]
This is fully intended behaviour, maybe the game is trying to tell you you should wear it in combat... Or skills... Or all the time until something else drops instead.

If you don't mind spoilers, check the Melvor Wiki entry for the ring.

**Comment by dozn** [comment]
Ah, fair. I already owned the ring and forgot about this "feature" continuing even so.

Thanks!
