### ISSUE TITLE
[Bug]: Lost Temple (Dig Site) - Not showing up as Dig Site

### ISSUE THREAD

**Issue by Gaviscon69** [MelvorIdle/melvoridle.github.io#4077]
### Describe the bug

This "Dig Site" is not showing up as a dig site and is currently just showing up as a normal Hex.
<img width="1586" alt="Lost Temple" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/159728250/bdd88016-611d-4c70-9d98-b638ed0c6151">

### Reproduction Steps

Cartography - Survey
Once surveyed, this is showing up as a normal surveyed Hex.

### Expected behaviour

According to https://wiki.melvoridle.com/w/Lost_Temple_(Dig_Site)

This is meant to be a dig site that gives Crystalized Dragon Fragments.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/wstbTqTN

### Screenshots

<img width="1586" alt="Lost Temple" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/159728250/4436ac64-66ad-4fb3-b018-6d46eb5fe7c9">

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

8417

### Are you using any mods?

No

**Comment by 04Slash** [comment]
Certain dig sites require you to find an item first before you are able to discover it. Lost Temple is one of them. You can see which item you need on the right side of the wiki under "Discovery Requirements:".

**Comment by Gaviscon69** [comment]
> Certain dig sites require you to find an item first before you are able to discover it. Lost Temple is one of them. You can see which item you need on the right side of the wiki under "Discovery Requirements:".

I'm an idiot sandwich. I didn't realise that....
Sorry for wasting your time, and thank you!!!
