### ISSUE TITLE
[Bug]: Game ownership often not recognized

### ISSUE THREAD

**Issue by Eldenwel** [MelvorIdle/melvoridle.github.io#4080]
### Describe the bug

When I launch the game on Epic Games and on Android or when I switch character, about 50% of the times or a bit more since this morning (2024-02-13) the game doesn't recognize that I own either the base game, one of the DLC or any combination of them. I have the relaunch the game for it to work again.

### Reproduction Steps

1. Launch the game on Epic/Android or try to switch to another character
2. Content ownership not recognized. 
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/159937477/04bbaafa-107f-446f-97a8-fa116f775c8b)
3. Relaunching the game (Still not working, but only one DLC now not recognized)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/159937477/61e77d55-314a-4330-b711-2940da5f1f73)
4. Relaunching the game (Everything working now)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/159937477/bc248770-589b-46f4-b9dd-321407b08693)

### Expected behaviour

The game ownership should be recognized on every launch.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8417

### Are you using any mods?

Yes

**Comment by redawgts** [comment]
I'm having the same problem. I'm playing on Chrome.

**Comment by jmr609** [comment]
I'm also having the same problem. Own base game and both expansions on Epic, currently away from home and unable to load on Android app or chrome on Android.

**Comment by mbushman789** [comment]
Same problem - Epic, base and both expansions, trying to play on desktop via Epic Game Launcher. Also having problems with Force Cloud Saving game progress (and have lose some progress in the process).

**Comment by staticf0x** [comment]
For me it's always missing AoD on iOS, sometimes it helps to kill the app, if that doesn't work I have to logout from cloud and log back in. Can't check the steam version now but it was fine as of 13 Feb ~3PM UTC.

**Comment by Monoxide8969** [comment]
I've had this issue multiple times today too.

I only have the base game on Epic Games, no DLC and no mods. v1.2.2?8417
I have played on desktop (chrome) and on mobile (firefox).

**Comment by njoudyk** [comment]
I am also experiencing this issue.  It takes anywhere between 1 and 5 tries to get the game to recognize that I've purchased both the base game and the two expansions.

Interestingly, if I click on the 'Epic Games' icon at the top left does pop up with recognition of some of the purchases, but purchases also sometimes have errors (and not the same as the indicators below the white line).

Screenshot where the indicators in game show no purchases, but the Epic link status shows base game and throne of the herald: 
![link_status](https://github.com/MelvorIdle/melvoridle.github.io/assets/64479392/f73b7cdd-b76b-4c34-b4c4-ab3b9596d32c)

Another one where the 'Demo mode' indication isn't prevent (recognizes the base game purchase) and the check mark is next to throne of the herald as well, but the 'Epic Games Link Status' shows no base game purchase and both expansions.
![link_status2](https://github.com/MelvorIdle/melvoridle.github.io/assets/64479392/1b6746e2-934e-4218-83ee-d1b252a6f7d0)

**Comment by mbushman789** [comment]
Perhaps some more info to help? It seems the game is not recognizing the (via Epic) purchase of the expansions (sometimes)
![EpicStatus](https://github.com/MelvorIdle/melvoridle.github.io/assets/159959519/87b6e24a-29ee-47ce-9630-46a5c69faf85)

**Comment by MelvorIdle** [comment]
Always love when issues like this occur while I'm asleep... :(

We haven't made any changes to the game recently, so this issue is stemming from PlayFab, as all our purchase verifications/caching runs through their system.

I've made contact with PlayFab as soon as I woke up in hopes to get this issue resolved. In the mean time, reloading the game until the purchases show up is the best course of action.

Reports have been dying down recently, so they may have fixed the issue on their end. Although I'm yet to receive confirmation from PlayFab at this stage.

**Comment by MelvorIdle** [comment]
We have received confirmation from PlayFab that the issue has now been mitigated and the game has returned to normal functionality. If you are still facing issues loading entitlements, please create a new GitHub report.

**Comment by Felixthedogbat** [comment]
Experiencing this bug a fair amount. I am not using mods.
