### ISSUE TITLE
[Bug]: The 25% proficiency bonus of Runes is not working

### ISSUE THREAD

**Issue by alagaG** [MelvorIdle/melvoridle.github.io#4084]
### Describe the bug

The buff is 250% EXP from basic runes crafting, but it's not being applied. For example: my Death Rune crafting give me 45 experience even with the 250% buff.

### Expected behaviour

In the previous example the Death Rune crafting should give me 112 XP ( 45 + 45 + 22.5 ).

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/6d4ew34t

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/103577452/45e51b01-fefe-4962-8e82-eae677a8ed8c)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8417

### Are you using any mods?

No

**Comment by 04Slash** [comment]
The base XP for Death Runes is 18xp. A 250% increase would bring it to 45xp. The box that shows the XP includes any XP modifiers.
