### ISSUE TITLE
[Bug]: <game crashes when loading>

### ISSUE THREAD

**Issue by Tf8562** [MelvorIdle/melvoridle.github.io#4085]
### Describe the bug

When I want to launch the game, the app crashes. I can see the game saves.

### Screenshots

![Screenshot_20240214-215859_Melvor Idle](https://github.com/MelvorIdle/melvoridle.github.io/assets/160089049/42d0acfc-07d3-46c1-9ffa-570f8dec8807)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

Cannot see it

### Are you using any mods?

No

**Comment by Melikoth** [comment]
I am also experiencing this issue on the PC/Steam version. Started the client this morning (2/15), opened two saves without issue, but after attempting to open my 3rd save received the crash dialog. Restarting the game results in receiving the error message immediately upon relaunching. 

Error Data:

Error: Element with id: shop-purchase-required does not have the correct tag name
    at getElementFromFragment (https://steam.melvoridle.com/assets/js/built/utils.js?8447:250:7)
    at new WoodcuttingTreeElement (https://steam.melvoridle.com/assets/js/built/woodcuttingMenu.js?8447:1:663)
    at https://steam.melvoridle.com/assets/js/built/woodcuttingMenu.js?8447:14:95
    at Array.forEach (<anonymous>)
    at WoodcuttingMenu.createTreeMenus (https://steam.melvoridle.com/assets/js/built/woodcuttingMenu.js?8447:14:61)
    at Woodcutting.onLoad (https://steam.melvoridle.com/assets/js/built/woodcutting.js?8447:81:41)
    at https://steam.melvoridle.com/assets/js/built/game.js?8447:197:65
    at Map.forEach (<anonymous>)
    at NamespaceRegistry.forEach (https://steam.melvoridle.com/assets/js/built/namespaceRegistry.js?8447:43:44)
    at Game.onLoad (https://steam.melvoridle.com/assets/js/built/game.js?8447:197:41)

**Comment by Silverfyree** [comment]
> I am also experiencing this issue on the PC/Steam version. Started the client this morning (2/15), opened two saves without issue, but after attempting to open my 3rd save received the crash dialog. Restarting the game results in receiving the error message immediately upon relaunching.
> 
> Error Data:
> 
> Error: Element with id: shop-purchase-required does not have the correct tag name at getElementFromFragment (https://steam.melvoridle.com/assets/js/built/utils.js?8447:250:7) at new WoodcuttingTreeElement (https://steam.melvoridle.com/assets/js/built/woodcuttingMenu.js?8447:1:663) at https://steam.melvoridle.com/assets/js/built/woodcuttingMenu.js?8447:14:95 at Array.forEach () at WoodcuttingMenu.createTreeMenus (https://steam.melvoridle.com/assets/js/built/woodcuttingMenu.js?8447:14:61) at Woodcutting.onLoad (https://steam.melvoridle.com/assets/js/built/woodcutting.js?8447:81:41) at https://steam.melvoridle.com/assets/js/built/game.js?8447:197:65 at Map.forEach () at NamespaceRegistry.forEach (https://steam.melvoridle.com/assets/js/built/namespaceRegistry.js?8447:43:44) at Game.onLoad (https://steam.melvoridle.com/assets/js/built/game.js?8447:197:41)

this is now fixed, just reload game.
