### ISSUE TITLE
[Bug]: Mobile version doesnt see that I own game, causes a loop to be unable to load game saves on mobile or steam client

### ISSUE THREAD

**Issue by badamg** [MelvorIdle/melvoridle.github.io#4086]
### Describe the bug

If i open the game on my phone, account shows that I cannot open my save as it doesnt think I own the base game + exp. Steam account link sometimes shows I have them both. I went into steam and launched the game and it launched 1 time. the next time on both mobile and steam game fails to load due to error. reading error notes that it doesnt think I own the games. 

pic from phone not seeing that I own games:
![IMG_3793](https://github.com/MelvorIdle/melvoridle.github.io/assets/22848469/93c9e757-4596-4de4-8fbd-4bf1b7aba65e)

![IMG_3794](https://github.com/MelvorIdle/melvoridle.github.io/assets/22848469/542da117-ab38-448a-b053-f55b4e65c0d8)

=============
Error that generates when game does see I own exp and base game but will not load:

Error: Element with id: shop-purchase-required does not have the correct tag name
    at getElementFromFragment (https://steam.melvoridle.com/assets/js/built/utils.js?8447:250:7)
    at new WoodcuttingTreeElement (https://steam.melvoridle.com/assets/js/built/woodcuttingMenu.js?8447:1:663)
    at https://steam.melvoridle.com/assets/js/built/woodcuttingMenu.js?8447:14:95
    at Array.forEach (<anonymous>)
    at WoodcuttingMenu.createTreeMenus (https://steam.melvoridle.com/assets/js/built/woodcuttingMenu.js?8447:14:61)
    at Woodcutting.onLoad (https://steam.melvoridle.com/assets/js/built/woodcutting.js?8447:81:41)
    at https://steam.melvoridle.com/assets/js/built/game.js?8447:197:65
    at Map.forEach (<anonymous>)
    at NamespaceRegistry.forEach (https://steam.melvoridle.com/assets/js/built/namespaceRegistry.js?8447:43:44)
    at Game.onLoad (https://steam.melvoridle.com/assets/js/built/game.js?8447:197:41)

### Reproduction Steps

1. launch mobile (iphone)
2. login
3. account doesnt see that I own games on steam but I do (see images above)
4. go to account and restore purchases 
5. log out
6. force close game
7. launch game in steam
8. save game to cloud
9. close out and log out of steam
10. launch mobile and login
11. IF it now see steam account if i try to load game from cloud or local I  get the error that it fails to load
11.b IF it doesnt see steam account repeat 1-10 until it does

this is also the point that steam client has a chance to also fail to load game. with same error as pasted above.

### Expected behaviour

I would sometimes expect mobile to get errors checking if I own steam however relaunching should resolve to check for purchases. currently wondering if I just tanked my save. 

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/fotGst9S

### Screenshots

![IMG_3794](https://github.com/MelvorIdle/melvoridle.github.io/assets/22848469/14578f9d-d507-4b3c-a0f3-8cbcbd00196b)
![IMG_3793](https://github.com/MelvorIdle/melvoridle.github.io/assets/22848469/49f5a12a-38f8-4288-951d-8bc7c13cab02)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8448

### Are you using any mods?

No

**Comment by LostBoyGeorge** [comment]
Same thing happened to me.

This reset my cartography and archeology.....

**Comment by njoudyk** [comment]
This is a re-occurence of issue #4080.

It was occurring for me this morning in chrome and through the epic games launcher as well.

For the time being a workaround is just reloading until it finally works (at least in Chrome- you may need to close and relaunch the app on mobile).

**Comment by mbushman789** [comment]
I could re-write it all, but basically - 'what njoudyk said (above)'
