### ISSUE TITLE
DLC not recognized

### ISSUE THREAD

**Issue by Felixthedogbat** [MelvorIdle/melvoridle.github.io#4087]
### Describe the bug

When I try to load a character, a high percentage of the time it tells me I don't own Atlas of Discovery (I think that's the only one.) If I reload, usually it gets it right, but sometimes I have to reload multiple times. 

### Reproduction Steps

Start the game.  Click on character. Sometimes I get the error message. Quit out of the game and start again.  Repeat until it recognizes I own the dlc.

### Expected behaviour

I expected to load in without the error message.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8448

### Are you using any mods?

No

**Comment by Sugaredyeti** [comment]
im having the same issues myself force saved the game reset my pc for a update and went to log back on and it says i dont own any of the dlc
