### ISSUE TITLE
Not getting skill xp for praying.

### ISSUE THREAD

**Issue by Somp13** [MelvorIdle/melvoridle.github.io#4093]
### Describe the bug

I did not get any skill xp when i was burying some bones,ash and medium enchantd urn (300)
Would get lika 180k xp from lvl 6. Would be some lvls up..

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [x] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8448

### Are you using any mods?

No

**Comment by Somp13** [comment]
Does not get xp when im at pc aswell

**Comment by MelvorIdle** [comment]
Prayer XP is granted by using Prayers, not by burying bones.
