### ISSUE TITLE
Birthday event broke

### ISSUE THREAD

**Issue by ChimeraGaming** [MelvorIdle/melvoridle.github.io#410]
Mobile, all online, still no cake pieces. 

![A1B8C49A-AE15-487E-BF50-63B62FF946C5](https://user-images.githubusercontent.com/54367698/93148990-b41a2000-f6a1-11ea-9bbb-676b270baed2.png)
![6F01D0CB-7F46-4BD0-A983-C99F9ADBBDE7](https://user-images.githubusercontent.com/54367698/93148992-b4b2b680-f6a1-11ea-86ce-562ee8784583.png)
![BB32D06D-40EE-4297-8DAF-6BDDCBE3682A](https://user-images.githubusercontent.com/54367698/93148994-b4b2b680-f6a1-11ea-8d16-499f8184b99e.png)
![02F0B577-25A7-4D2C-ABC9-C5BC5BC968DA](https://user-images.githubusercontent.com/54367698/93148995-b54b4d00-f6a1-11ea-8fd3-a2169d76ca4f.png)
![B4CB0918-0677-4414-B6BB-C18973F031E0](https://user-images.githubusercontent.com/54367698/93148996-b54b4d00-f6a1-11ea-9b00-b47a0e3f3797.png)

![B0E406CC-19F5-4711-9E04-3A377387BEB5](https://user-images.githubusercontent.com/54367698/93148984-b2505c80-f6a1-11ea-859c-fd613d412bfe.jpeg)
![7F5CCEF3-7E51-42C8-A764-6AE1319879BE](https://user-images.githubusercontent.com/54367698/93148987-b3818980-f6a1-11ea-8f7e-6341fec70475.png)

**Comment by ChimeraGaming** [comment]
Says that it only takes 500 actions and everyone says they get it at 500 or sooner (actions) and I’ve yet to get it....

**Comment by MelvorIdle** [comment]
You're doing something wrong. This isn't a bug report. Double check "What everyone says"
