### ISSUE TITLE
[Bug]: Cooking whale does not increment invetory count of cooked whale

### ISSUE THREAD

**Issue by taggedzi** [MelvorIdle/melvoridle.github.io#4104]
### Describe the bug

In Cooking Skill. When Active Cooking item Raw Whale. When the timer reports having finished cooking a raw whale, it does not increment the count of cooked whale in my inventory properly.  It does accurately increment perfect cooks of whale, just not the normal cooked version.  It displays the "Whale +1    0" at the bottom of the screen over and over again when it completes the cooking action.

I have verified I have the inventory space.
I have gone through every available inventory tab to confirm.
It does consume a Raw Whale from my inventory.
It does report as having successfully cooked a whale.
It **does not** increment existing cooked whale, nor add cooked whale if it was not in the inventory.
It **does** increment Perfect cooks properly.

### Reproduction Steps

1. With Raw Whale in inventory, and enough inventory space to receive cooked whales (and perfects if allowed) 
2. With the required skills/equipment to cook a Raw Whale
3. Goto the Non-combat skill "Cooking"
4. Select Recipe to cook as 1 x Whale
5. Click on the button to "Active Cook" the Raw Whale.
6. On successful cook notice that 
     A. IF you had Cooked Whale in your inventory it did not increment the amount. (**I do not have a screen shot for this but I did confirm it.** I unfortunately sold all mine to test before deciding it was a bug and can no longer get them in my inventory.)
     B. IF you did NOT have cooked Whale in your inventory it did not ADD the item to your inventory. 
![successful cook bug](https://github.com/MelvorIdle/melvoridle.github.io/assets/15974146/ca866ba9-65d8-4586-8782-fbcdba7a8915)
![another successful cook bug](https://github.com/MelvorIdle/melvoridle.github.io/assets/15974146/96cc1557-d0fc-4351-a126-d733bb510de8)
     C. It does decrement the Raw Whale from your inventory in either case.
     D. It does successfully increment Perfect cooks
![successful perfect cook](https://github.com/MelvorIdle/melvoridle.github.io/assets/15974146/103aaeee-dcdc-40c8-b8bd-d170f3c41a71)

Here are the potions I was using:
![potion used](https://github.com/MelvorIdle/melvoridle.github.io/assets/15974146/36a307ff-2b98-4ba7-aaee-afa0e2dbddd4)

Here is the equipment I was using:
![equipped](https://github.com/MelvorIdle/melvoridle.github.io/assets/15974146/2609d4c3-2ae3-45f6-a3c3-cca74de0fc28)

I have tested with/without potions and with/without summons and got same results.

### Expected behaviour

When successfully active cooking a Raw Whale, I expect the resultant Cooked Whale to go into my inventory.

### Screenshots

![potion used](https://github.com/MelvorIdle/melvoridle.github.io/assets/15974146/f2414feb-0d9c-4613-b631-074cafca662b)
![equipped](https://github.com/MelvorIdle/melvoridle.github.io/assets/15974146/5459bf61-832b-4b14-9c3d-e61d7d0858db)
![successful perfect cook](https://github.com/MelvorIdle/melvoridle.github.io/assets/15974146/5843c6a7-5163-42b1-8c8f-5ce29fcbfa1c)
![another successful cook bug](https://github.com/MelvorIdle/melvoridle.github.io/assets/15974146/bddc8c0a-823f-4363-9a5b-40018997c3be)
![successful cook bug](https://github.com/MelvorIdle/melvoridle.github.io/assets/15974146/53bad96d-1824-4e4b-8a4c-27cd29dc1a64)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8448

### Are you using any mods?

No

**Comment by 04Slash** [comment]
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/07304f78-3755-4ca7-b6f4-9797c1f9c006)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/83edf910-43a9-48b7-8795-70d0b0e801ca)
Probably going directly into your food slots due to this upgrade.

**Comment by taggedzi** [comment]
Wow. You are correct. I'm sorry to have wasted your time.  I did not look there, I forget it holds inventory items.
