### ISSUE TITLE
[Bug]: white screen when coming bacj to the app

### ISSUE THREAD

**Issue by Alurian-ux** [MelvorIdle/melvoridle.github.io#4105]
### Describe the bug

So I ope the app, then I navigate to another app on my phone. When I come back to Melvor, it is just a white screen. To fix it I need to close the app completely and open it again.

Sometimes it does load, but I still see the white screen first. But more often than not it doesn't.

### Reproduction Steps

1. Open app
2. Wait until loading is finished
3. Navigate to other app
4. Navigate back

### Expected behaviour

Well, just melvor loading up again and not a white screen

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8448

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Same as #4322 (Closing this one to clean issues)
