### ISSUE TITLE
Quick Equip requires several mouse overs to stay long enough to interact with.

### ISSUE THREAD

**Issue by Felixthedogbat** [MelvorIdle/melvoridle.github.io#4107]
### Describe the bug

I mouse over the gear icon (The quick equip button) all the time, but usually it opens, but disappears as soon as I try to interact with it by taking the mouse off the gear button. Usually I have to put the mouse on and off it several times before it will stay so I can click items within it. Clicking on the gear icon will make it have a slightly thicker border, but doesn't seem to affect if it stays around or not. The number of times I have to mouse over it is not static, and does change. Eight is the most common amount of times however, I believe.

### Reproduction Steps

Go to any screen that would have a quick equip button in the lower right hand side. 
Mouse over it. The panel pops up. 
I move the mouse to the panel.
It disappears.
I return to the gear icon.
I repeat until the panel with all the equipment choices stays when I take the mouse off the icon. 

### Expected behaviour

I expect the panel to remain for interaction if I mouse over or click the gear icon.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8448

### Are you using any mods?

No

**Comment by Balor64** [comment]
I have this issue too, and in my experience it depends on how long you hover the mouse over the gear icon. If you don't hover over the gear icon for long enough before switching to the panel, it disappears.

**Comment by Felixthedogbat** [comment]
Thanks!

**Comment by davidac9** [comment]
I'm also having this issue or possibly just a similar issue. It seems like there's a small space maybe a couple pixels wide between the quick equip icon and the quick equip menu and if your cursor lands on this space for any amount of time it can cause the quick equip menu to disappear before you can interact with it. 

One way to recreate this is by hovering your cursor over the quick equip icon and very slowly moving your cursor to the quick equip menu.
