### ISSUE TITLE
[Bug]: <Ancient Relics - Archaeology>

### ISSUE THREAD

**Issue by alchemist55** [MelvorIdle/melvoridle.github.io#4110]
### Describe the bug

Playing on Ancient Relics Mode and I have only unlocked two ancient relics (level 20/99) for Archaeology and I just capped archaeology at 120 today.  

### Expected behaviour

To have at least gotten one relic from leveling archaeology to level 120.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/4TsdGshv

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/60719008/c41c2544-d673-4a8b-be3c-cd08b06a8ab3)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/60719008/8eb6bacf-0471-4972-99ed-ab7970b6809a)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/60719008/75126b94-cf76-4df5-8968-5edf4f30db2e)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8448

### Are you using any mods?

Yes

**Comment by Manynugget** [comment]
Just wanted to double-check, isn't this expected behaviour? The Ancient Relic screenshot says one would be granted at Level 20 and Level 99, but doesn't mention Level 120.

**Comment by alchemist55** [comment]
Yes that is how it is supposed to work, but I find it odd to not have received a relic while grinding the skill to 120.  It is possible I have that bad of luck, but I felt like I should bring it up in case there is a bug with the odds.
