### ISSUE TITLE
[Bug]: Cartography Map Doesn't Load

### ISSUE THREAD

**Issue by thebrianlenz** [MelvorIdle/melvoridle.github.io#4116]
### Describe the bug

Cartography map doesn't load.
When the skill is selected, the map says it's loading but never progresses and hangs at either 4% or 19%>

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8448

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Related #4218 (Closing to clean issues)
