### ISSUE TITLE
[Bug]: Mastery Magnet

### ISSUE THREAD

**Issue by hbindel26** [MelvorIdle/melvoridle.github.io#4117]
### Describe the bug

I am not receiving a mastery token every time the item is consumed. It is once in a while. 

### Reproduction Steps

1. equipped mastery magnet 2. train skill 3. wait

### Expected behaviour

 I should obtain a mastery token every time. Or what the prescription tells me: +1 Mastery Tokens received(One item is consumed per skilling action).

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8448

### Are you using any mods?

No

**Comment by ekuland** [comment]
+1 received... when you receive one.
