### ISSUE TITLE
[Bug]: Engulfing Vortex Longbow Goblin Raid

### ISSUE THREAD

**Issue by WigWam79** [MelvorIdle/melvoridle.github.io#4118]
### Describe the bug

Engulfing Vortex Longbow shows up in Goblin Raid but when equipped it acts as the Grappling Hook.

### Reproduction Steps

1. Enter Goblin Raid
2. Equip Engulfing Vortex Longbow while having arrows
3. Attacks are the same as Grappling Hook

### Expected behaviour

Should act with the Engulfing Vortex Longbow with 100% special attack with 10 hits

### Screenshots

![Melvor Bug](https://github.com/MelvorIdle/melvoridle.github.io/assets/161984067/cf614366-740a-4ddf-9880-a13385bd73e6)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8448

### Are you using any mods?

No

**Comment by ekuland** [comment]
You got an ALT item. The special attack on it is a different, random one. This is intended.

**Comment by WigWam79** [comment]
Whenever I was looking at the effect in the selection screen it detailed the actual effect of it instead of the grappling hook. 
Either it provided the wrong effect or the selection screen had the wrong description written.

**Comment by WigWam79** [comment]
Also as I have seen the Grappling Hook but have never taken it I am not sure but I believe that it actually has 2 effects 1 labeled bad throw and 1 labeled good throw so even if it were to be as you said then it should have both effects or its quite useless.

**Comment by 04Slash** [comment]
ALT items don't take every special from a weapon, it just picks a random one. As you mentioned, grappling hook has 2 specials.

If you provide your save, we can take a look at the data and it will confirm if the item you have is an ALT item or not. There is no indication to whether an item and an ALT item or not in-game.

**Comment by WigWam79** [comment]
I just became aware that ALT items don't show the effects they will be given in the selection screen. most likely it indeed was an ALT item. Very confusing that it shows the old effect on the screen instead of saying "will gain random effect" or something along those lines.
