### ISSUE TITLE
-1 Woodcutting Capes in Bank

### ISSUE THREAD

**Issue by Ness-9** [MelvorIdle/melvoridle.github.io#412]
**Describe the bug**
I somehow ended up with -1 woodcutting capes in my bank today. It has a quantity of -1 and a sell value of -250,000 gold. If I equip the cape then remove it, it returns to a quantity of 1 in my bank. 

**To Reproduce**
I am not sure how to reproduce the issue but I was switching capes using the quick menu in the lower right to switch between cooking and farming cape based on what I was doing at the time. I exported my save before attempting to equip the cape and will attach it to the bug for proof of the bug

**Expected behavior**
Items in the bank should never have a negative quantity

**Screenshots**
https://cdn.discordapp.com/attachments/625840209531240469/755444352871956540/unknown.png
https://cdn.discordapp.com/attachments/625840209531240469/755444410543767642/unknown.png
[Melvor_Save_Negative_Skillcape_Quantity.txt](https://github.com/MelvorIdle/melvoridle.github.io/files/5226034/Melvor_Save_Negative_Skillcape_Quantity.txt)

**Browser**
Google Chrome 85.0.4183.102 (Official Build)

**Console output**
DevTools failed to load SourceMap: Could not load content for https://melvoridle.com/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
index.php?l=1:8811 GET https://melvoridle.com/assets/media/shop/assets/media/shop/perpetual_haste.svg 404
prebid.min.js:3 fun-hooks: referenced 'registerAdserver' but it was never created
(anonymous) @ prebid.min.js:3
(anonymous) @ prebid.min.js:3
ready.t.ready @ prebid.min.js:3
S.processQueue @ prebid.min.js:3
(anonymous) @ prebid.min.js:36
DevTools failed to load SourceMap: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://melvoridle.com/assets/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
adthrive.min.js?threshold=0:17 AdThrive::init started
DevTools failed to load SourceMap: Could not load content for https://melvoridle.com/sm/13c28911820333eb6a51103a0e2096477a38941cc79afbf16b59f3d5a5f63086.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
VM1110 amp4ads-v0.js:420 Powered by AMP ⚡ HTML – Version 2009010507000 https://melvoridle.com/index.php?l=1
save.js?410:56 Loading Save Game...
save.js?410:179 Save Game Loaded...
smithing2.js?405:220 Loading Smithing...
mastery.js?401:187 Updating Masteries
mastery.js?401:23 Loading Masteries...
main.js?432:537 Game Loaded
cloud.js?430:106 0
amp-inabox.js:136 Powered by AMP ⚡ HTML – Version 2009010507000 https://melvoridle.com/index.php?l=1

**Are you using any scripts?**
The only script I have is the Melvor Combat Simulator 0.10.1 (extension)

**Comment by MelvorIdle** [comment]
This should be fixed in the upcoming Bank Rework
