### ISSUE TITLE
[Bug]: 0/x built buildings don't lose efficiency

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#4122]
### Describe the bug

Buildings in Township that are 0/x built (has an upgrade, but they have not been built yet) will show a lower efficiency number in the top left however this has no actual effect on the amount of resources produced.

### Reproduction Steps

1. Load provided save
2. Go to Township
3. Fully repair town
4. Use below script to grab resource generation amounts
5. Skip an entire year so buildings are degraded (Ensure the season is the same)
6. Pick one of the following
6.1 Repair Library, Orchards, Chapels (these builds are not 0/x built and therefor will degrade)
6.2 Only compare Clothing, Planks, Leather, Herbs, Bars in Step 7
7. Run script again and compare values to step 4

```js
game.township.resources.forEach(({name, generation}) => {
	console.log(name, generation)
});
```

### Expected behaviour

The amount of Resources, Population (Housing), and Education (Schools, not Libraries) that buildings provide should be reduced by a building's efficiency even when the building is 0/x built.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/5GcDS0bM

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8448

### Are you using any mods?

No

**Comment by nicosemp** [comment]
Please prio this!
I can provide screenshots as proof of the bug:

Here is the Miners Estate with 0/25 built and the production that **doesn't decrease** at 98% health.
<img width="266" alt="Screenshot 2024-04-24 at 17 58 51" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/8838305/ef44372a-6ec9-4dac-b181-2f3c57fe041d">
<img width="266" alt="Screenshot 2024-04-24 at 18 06 10" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/8838305/3c34454a-efc3-48cb-ae4c-f3bf8ff5293e">

The **Hunters Villa** has 1/20 built instead, and the production at 65% health is correctly reduced compared to 100%.
<img width="267" alt="Screenshot 2024-04-24 at 17 59 06" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/8838305/e3d99e75-4065-4616-a784-051ff235209c">
<img width="265" alt="Screenshot 2024-04-24 at 17 59 19" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/8838305/543ccd98-edde-488d-9bb9-efe100f098b1">
