### ISSUE TITLE
[Bug]: Visual Bug with Bank Tab Prices of Lesser Relics

### ISSUE THREAD

**Issue by rhythm2107** [MelvorIdle/melvoridle.github.io#4131]
### Describe the bug

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/125750897/55566f39-b03b-4d4c-b47d-eb7ce056af64)
The tab seems to show 3 mil worth of lesser relics in the tab, but all of them are worth 1 gp each so that's not possible considering i have around 300k of them.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8452

### Are you using any mods?

Yes

**Comment by ekuland** [comment]
Please add a save.
