### ISSUE TITLE
[Bug]: Even if have an Ancient Stone Tablet, still cannot enter the Golem Territory

### ISSUE THREAD

**Issue by LenKiMo** [MelvorIdle/melvoridle.github.io#4134]
### Describe the bug

In standard game mode, even though I have an Ancient Stone Tablet in my bank, I can't enter the Golem Territory dungeon. The game will tell you that you need to find the Ancient Stone Tablet before you can do this.

I tried to reacquire the tablet through Archaeology after selling all of my stock Ancient Stone Tablet, but the dungeon still refuses to let me in.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/UmeScD9H

### Console output

Mod List
```
SEMI Core
Skill Boosts
Unlimited Offline
SEMI Auto Farming
SEMI Drop Chances
SEMI Auto Master
SEMI Auto Loot
SEMI Auto Bonfire
SEMI Auto Sell
SEMI Auto Bury
SEMI Auto Smith Bars
SEMI XP Per Hour
Mastery Virtual Levels
hack multiplier
Semi Auto Township
SEMI Auto Slayer
SEMI Auto Runecrafting
SEMI Auto Open
SEMI Auto Collect Stockpiles
XP Township Mod
Equipment Presets
Absurdly High Max Township Storage
Add Items
10K (100千 to 10万)
dev.Console
Time Skip
Show Dungeon Completion Count
attack interval
Will I Die?
Faster Atlas of Discovery
SOS! Save Preserver
```

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8452

### Are you using any mods?

Yes

**Comment by 04Slash** [comment]
This is a mod bug. The mod "hack multiplier" is not returning the "found" property when it adds items. This results in the game thinking you never found the item even if it's inside your bank.

**Comment by LenKiMo** [comment]
Thank you for your information. After disabling this mod, I conducted archaeological excavations again and obtained the stone slabs. I am now able to enter the dungeon.
