### ISSUE TITLE
[Bug]: Township - Storage is not full, yet it displays the message/marks it red

### ISSUE THREAD

**Issue by Kelutra103** [MelvorIdle/melvoridle.github.io#4136]
### Describe the bug

My current maximum of storage for resources is 116.029.249.
At some point saving up/collecting resources after it surpasses ~113.7 mil (I think the exact number is 113.708.664) the message appears saying I have no space left and marks the numbers red (as expected when you reach the current maximum) but its actually lower than the max.

I can still gain resources normally.
I have all buildings for storage completly built, I have the pet of the Township, Aeris calamity and as of astrology: I have 5% (of 8%) in the Heamir constellation for more storage. I think that all adds up to my current maximum (see above/screenshot).

### Expected behaviour

As said before: the display should appear after reaching maximum.

### Screenshots

![Screenshot (1)](https://github.com/MelvorIdle/melvoridle.github.io/assets/163602251/6edbf118-600d-4a7e-89c0-8618dcb74619)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8452

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Intended as it is designed to show that your storage is full when you are _close_ to that. It provides a buffer and time to adjust your town, that way you don't lose out on possible resources when the next tick arrives.
