### ISSUE TITLE
[Bug]: <title> skill modifiers not working 

### ISSUE THREAD

**Issue by chilawhari** [MelvorIdle/melvoridle.github.io#4142]
### Describe the bug

so about 2 days into my ancient relic mode playthrough all of my skill modifiers decided to stop working they all show zero percent and when i go to click on it to see why its showing -696969 percent.

### Reproduction Steps

not a clue how it actually happened but its happening even when i start a new game so im assuming its a coding issue.

### Expected behaviour

.

### Screenshots

![Capture](https://github.com/MelvorIdle/melvoridle.github.io/assets/74803789/34cc33f1-9c87-467c-aefc-e3ced09d75b6)

### Console output

.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

doesnt show it just shows expansions

### Are you using any mods?

Yes

**Comment by 04Slash** [comment]
Ancient Relics does not allow for Doubling or Preservation. It's one of the limitation of the gamemode. It does this by giving -696969% preservation and doubling.
If you are having issues with the mod providing the wrong values, this should be reported to the mod developer. The game developer does not handle mod bugs.
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/a862d0cb-d2fb-4cec-b47d-d756c7917daf)

**Comment by chilawhari** [comment]
but that wasnt the case for the first 2 days. so was i just getting lucky and the modifiers were working for some reason at first?
