### ISSUE TITLE
[Bug]: Firemaking log selection bug

### ISSUE THREAD

**Issue by Baapie** [MelvorIdle/melvoridle.github.io#4148]
### Describe the bug

i cant see the full firemaking log selection menu

### Reproduction Steps

Go to firemaking
Select your logs
Error

### Screenshots

![938d9ece9c3c4a274e575f17f9483da6](https://github.com/MelvorIdle/melvoridle.github.io/assets/164159724/c05fbf8b-16b6-47f6-90e3-9815ae6abd7f)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8452

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
It only displays logs you have in your Bank. If a Log is missing from the menu, it means you don't have any of them in your Bank.
