### ISSUE TITLE
Attack Interval incorrect[Bug]: <title>

### ISSUE THREAD

**Issue by gj747** [MelvorIdle/melvoridle.github.io#4153]
### Describe the bug

All weapons I use are .2 seconds slower than listed. If I equip Sand Treaders this is reduced to .1 second slower than it should be. I am not fighting in an areas with reduced attack speed nor have anything else that should impact this. I've attached two screenshots. I've unequipped all gear, logged in and out, checked all other areas for passive impact (nothing in agility for instance). Nothing has fixed this. 

### Expected behaviour

For the attack interval to match the tool tip. 

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/164414750/1211a5f6-78b2-4836-ba2d-316b1b4cde25)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/164414750/6016811a-7f26-4f65-bacc-64f32f6c872b)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8452

### Are you using any mods?

No

**Comment by Moridin63** [comment]
Are you standing on spider forest in carto?

**Comment by gj747** [comment]
Old Village, then moved to sacrificial site. I verified files and now it seems to be okay?
