### ISSUE TITLE
[Bug/maybe Request?]: Graphical setup with auto-eat and maxdamage

### ISSUE THREAD

**Issue by Soulprayer79** [MelvorIdle/melvoridle.github.io#4155]
### Describe the bug

Dear Melvor-Team, 

the one thing, i really like to see - it would be fantastic - would be an indicator (or text), if the enemy can do more damage than auto-eat threshold.

At the moment I really have to stretch Melvor the whole 19" screen to even check if the mob does more damage than auto-eat to react accordingly - here in the golbinraid (see picture), it's extreme, because of box for skip wave and box for passives.

I think it would be beneficial, if I can see the maxdamage of the mob in the vicinity of autoeat. 

Maybe Autoeat Healing GREEN for "everythings fine", YELLOW for "it might be" and RED for "dangerous".

Or just some text like (heart) 152/270 (crab) (81) - (sword/range/magic) (92)

If you like feedback in another way, sorry. I've not seen any other possibility.

### Screenshots

![grafik](https://github.com/MelvorIdle/melvoridle.github.io/assets/82806099/6a0fe59f-9e18-458b-b073-6396ada68852)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8452

### Are you using any mods?

No

**Comment by Ayarez** [comment]
Try using a mod called "combat indicators" that will do exactly what you want
