### ISSUE TITLE
[bug] Township repairs exceed repair capabilities or time

### ISSUE THREAD

**Issue by neilfw** [MelvorIdle/melvoridle.github.io#4156]
### Describe the bug

This bug lookslike a re-occurance of #3463.
![Screenshot 2024-03-23 112113](https://github.com/MelvorIdle/melvoridle.github.io/assets/22427016/89dacb59-9fd6-4053-95ca-2805e0d81ddd)
The orchard needs 113750 logs which at +432/t on a storage of 165000 is not achievable in a time that other structures will not need repairing requiring the consumption of other resources and taking total demand over 165000 storage even if 113730 wood could be generated and stored.

### Reproduction Steps

Create 100/100 orchard, leave game running for > 1 week, possibly 2.  Once repair of orchard drops to a low % of repair, the values become unachievable.

### Expected behaviour

Partial repair should be possible, or a change to the volume of materials to repair a structure, or a ceiling value of maximum repair cost

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8452

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
You're currently in Winter which severely increases repair costs. Wait it out until a season that doesn't have these repair modifiers and work your way through repairing other buildings and health to get back to 100%.
