### ISSUE TITLE
[Bug]: Combat not updating offline

### ISSUE THREAD

**Issue by RogueWizard16** [MelvorIdle/melvoridle.github.io#4157]
### Describe the bug

It will show doing combat in the save but won’t give any rewards. This has happened multiple times. It works with other skills. When you open the save the combat will not have happened

### Reproduction Steps

On mobile, démo account
Do any combat
Log off
It will show doing combat in the save but won’t give any rewards. This has happened multiple times. It works with other skills.

### Expected behaviour

Rewards / exp or even just lost health and food

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

Not shown/couldn’t find it

### Are you using any mods?

No

**Comment by 04Slash** [comment]
Did you enable offline combat in the settings?

**Comment by RogueWizard16** [comment]
No, sorry, I had toggled it on my other save but didn't realise it had to be done for every save. thank you!
________________________________
