### ISSUE TITLE
Bug: Cartography pop-up travels to unexpected

### ISSUE THREAD

**Issue by cottrela** [MelvorIdle/melvoridle.github.io#4158]
### Describe the bug

In cartography, after surveying a Point of Interest (POI), a pop-up appears asking if you want to view it immediately. However, if you have other POIs that you've opted not to visit yet (e.g., ones you might be  saving until later), the game might direct you to one of these instead of the one you just completed. Not sure if this a bug or a feature?

### Reproduction Steps

1. Survey one or more POIs but click "View later"
2. Survey another POI, but this time click "View now"
3. You travel to one of the other first POI (i.e. not the one that you just surveyed)

### Expected behaviour

The pop-up appears immediately after completing a survey, and so user would reasonably expect the "View now" to be related to the current POI, not the other POIs that were surveyed earlier.

Note: this was discovered by following the wiki guide for cartography.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

8452

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This is currently an intended mechanic where the POIs are saved in a queue in the order they were surveyed.
