### ISSUE TITLE
[Bug]: DLC Mastery Pool Items Are Not Displaying

### ISSUE THREAD

**Issue by Capnmaf** [MelvorIdle/melvoridle.github.io#4163]
### Describe the bug

When viewing the "Spend Mastery Pool XP" menu, it does not show any items from the DLCs. Example being archaeology no longer shows anything in this menu. It looks like it's appending the "d-none" class to those items but they still exist and function as expected if you were to remove that class (see screenshots). I also booted up a new character and this issue does not seem to be present. This issue is present for items from both DLCs.

### Reproduction Steps

1. Go to my specific save
2. Go to any skill that gives mastery xp
3. Click on the "Spend Master Pool XP" at the top
4. Will not show any DLC items

### Expected behaviour

Should show mastery pool items from DLC if you own the DLC.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/5bmuVeSI

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/155021286/ff3bf799-d492-4d78-be56-83467d91d392)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/155021286/753ee91e-6488-4033-9ed9-60e88cfeebbb)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/155021286/be0b0022-f601-4ea7-bcf2-5454149b9a3e)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8453

### Are you using any mods?

No

**Comment by 04Slash** [comment]
You have Atlas of Discovery unchecked which will hide any mastery items from AoD.
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/5fd7f111-6002-446e-b7bb-511464855823)

**Comment by Capnmaf** [comment]
Well dang, now I feel dumb. I've never used those checkboxes before and didn't realize they were there! Not sure how those got unchecked. I can close this then.
