### ISSUE TITLE
[Bug]: Next Town Update Inconsistence

### ISSUE THREAD

**Issue by DozyXYZ** [MelvorIdle/melvoridle.github.io#4167]
### Describe the bug

Hi Melvor Idle Dev,

I am running into an issue with Next Town Update tick.
Usually my town will update around XX:17 (hh:mm). 
However, the Town Update is delay or some time reset without advancement. As a result, progress is loss.
It started to happen this morning for me. I live in Northern Europe.
It would be great if you can look into the matter.

Thank you.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8590

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This has now been hotfixed. Thanks for the report
