### ISSUE TITLE
[Bug]: Necromancer Crown & Mandramonte Crown in AR

### ISSUE THREAD

**Issue by Ayarez** [MelvorIdle/melvoridle.github.io#4170]
### Describe the bug

Both items double bones and logs respectively and still work in AR

### Reproduction Steps

Equip crown, kill a monster with necromancer or chop a log with madramonte crown > receive 2x loot

### Expected behaviour

No doubling

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

1.2.2

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This has now been hotfixed. Thanks for the report.
