### ISSUE TITLE
[Bug]: Golbinraid - Ultima Godsword is in Equipment

### ISSUE THREAD

**Issue by Soulprayer79** [MelvorIdle/melvoridle.github.io#4175]
### Describe the bug

I was lucky enough for a ultima Godsword in Golbin Raid, but it was categorized as equipment and it was equipped in my armor slot for body. I've paused the Golbinraid and uploaded the save if you want to see it yourself. :)

### Expected behaviour

it should be in weapon and should go to the weapon slot.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/LtfipbVB

### Screenshots

![grafik](https://github.com/MelvorIdle/melvoridle.github.io/assets/82806099/d00dbe3e-dc64-4599-8ffc-c32293368ca9)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8594

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This has now been hotfixed. Thanks for the report.
