### ISSUE TITLE
[Bug]: <Steam Version Keeps Running After Closing Game>

### ISSUE THREAD

**Issue by SevnirOG** [MelvorIdle/melvoridle.github.io#4177]
### Describe the bug

After new update, when you play using Steam, after you logout and close the game, it still keeps running in Steam.  Even if you force it to stop, it then changes from "Running" indefinitely to "Stopping" indefinitely.

### Reproduction Steps

1. Launch game in Steam.
2. Force Save
3. Logout
4. Close game
5. Check Steam library...it's still "Running" forever
6. Force stop...now it's "Stopping" forever

### Expected behaviour

It used to stop running after you closed the game.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8590 I think

### Are you using any mods?

No

**Comment by Ayarez** [comment]
If you open the wiki using Chrome, this happens, close chrome beforehand and it will close properly

**Comment by MelvorIdle** [comment]
Same as #3786 (Closing this one to clean issues)
