### ISSUE TITLE
[Bug]: Minotaur uses to many redwood bows

### ISSUE THREAD

**Issue by eumel2** [MelvorIdle/melvoridle.github.io#4178]
### Describe the bug

The centaur summoning tablet uses 50 redwood short-or longbows. 

### Reproduction Steps

Open summoning go to centaur and choose redwood

### Expected behaviour

I would expect this to be just 1, similar to how the minotaur only takes one dragon battle-axe

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8569

### Are you using any mods?

No

**Comment by AeroCross** [comment]
Confirmed with AOD and TOH on Ancient Relics mode, Desktop / Safari.

The wiki however says it takes 50, which I assume it happens because it's autogenerated.

**Comment by MelvorIdle** [comment]
This is intended as summoning recipes are based on the sale price of the item
