### ISSUE TITLE
[Translation Error]: Two runes with the same name

### ISSUE THREAD

**Issue by Dagorent** [MelvorIdle/melvoridle.github.io#4181]
### Which text in the game has a translation error?

![runa](https://github.com/MelvorIdle/melvoridle.github.io/assets/166237696/28ab638e-9625-40cc-99ed-f650905c25f4)

Hello,

I have detected that there are two runes with the same name in Spanish:

Chaos Rune and Havoc Rune

Chaos Rune should be in Spanish: "Runa de caos" or "Runa del caos" or even "Runa caótica"

Havoc Rune is not as clear to me as the previous one, because Havoc would technically be "estragos" but it is not very used in Spanish, we use more the synonym "destrucción" in this context (Destruction in English) so I think that "Runa de destrucción" or "Runa de la destrucción" would be more appropriate and would avoid duplicity.

All the best.

PS: Sorry for my English

**Comment by JarWarren** [comment]
I'm getting this issue on v1.3.1 in Spanish

<img width="475" alt="Image" src="https://github.com/user-attachments/assets/5bfbc149-961e-4c8e-8ef6-3fd6f310f441" />
