### ISSUE TITLE
[Bug]: Ancient Relics Combat Only Speedrun - Cannot reach 95 slayer for Unhallowed Wasteland

### ISSUE THREAD

**Issue by ShadowGull** [MelvorIdle/melvoridle.github.io#4184]
### Describe the bug

In Hardcore Ancient Relics Combat Only Speedrun, Unhallowed Wasteland still has a requirement of 95 slayer. This is a problem as 90 slayer is the maximum one can reach and start IDE with, as barrier dungeons can't be cleared. This makes the event impossible to complete.

### Reproduction Steps

1. Clear all possible dungeons prior to IDE, to have a cap of 90 slayer.
2. Look at Unhallowed Wasteland, and see that it still requires 95 slayer.

### Expected behaviour

Unhallowed Wasteland for this specific game-mode needs the 95 slayer requirement lowered to 90 slayer (Or some other effective change) to be accessible.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/30505273/0a1a2382-4d03-4e96-a0f9-5c015ca1168c)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/30505273/a90e2903-e281-4137-a1b3-41d17e51ede6)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8596

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
I have now released a hotfix for this issue
