### ISSUE TITLE
[Bug]: Unable to launch game

### ISSUE THREAD

**Issue by yasuoooooo** [MelvorIdle/melvoridle.github.io#4186]
### Describe the bug

After launch the game, stay on the “Confirming Expansions to load"  page.

### Reproduction Steps

launch game

### Screenshots

![捕获](https://github.com/MelvorIdle/melvoridle.github.io/assets/62107913/3503fe3f-38f0-4901-834a-2bc58ab48206)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

Unable to enter the game

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
We are unable to reproduce this bug. If the issue persists, please submit a new ticket
