### ISSUE TITLE
Melee Accuracy Potion higher tiers have two spaces in the name

### ISSUE THREAD

**Issue by Falterfire** [MelvorIdle/melvoridle.github.io#419]
**Describe the bug**
Okay this is incredibly petty, but when automating stuff on the wiki I noticed that the names of Melee Accuracy Potion tiers 2-4 have an extra space between Accuracy and Potion.

This is a problem for me specifically and nobody else because it means if I'm iterating through getting item data for '[potion name] I', '[potion name] II', and so on, Melee Accuracy potions don't work.

**To Reproduce**
1. Open items.js
2. Find Melee Accuracy Potion I
3. Look at the other three tiers right below it
4. See that there is an extra space

**Expected behavior**

**Screenshots**

**Browser**
Irrelevant

**Console output**
Irrelevant

**Are you using any scripts?**
Irrelevant

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
