### ISSUE TITLE
[Bug]: Logging in shows DEMO account

### ISSUE THREAD

**Issue by iliogr** [MelvorIdle/melvoridle.github.io#4190]
### Describe the bug

Logging in is showing that my account is a DEMO account even though I have purchased all expansions.
It was working fine as of 10 minutes ago. Tried to log out and login again but didnt work

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?1341

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Thanks for the report. It looks like the issue was picked up by PlayFab and has now been resolved: https://status.playfab.com/
