### ISSUE TITLE
[Bug]: Steam achievement "Mastery Master" not popping after getting true completion in game

### ISSUE THREAD

**Issue by prozinworz** [MelvorIdle/melvoridle.github.io#4195]
### Describe the bug

After getting 100% in each section of the completion log with all expansions, I have tried saving and restarting the game multiple times, but Steam does not seem to recognize that it has been done. The only variable I could see being an issue for this is that during some event I ended up with cooking mastery levels in a temporary item so now my cooking mastery value is listed as 5410/5346 (101.20%). This resulted in the following numbers for my completion log percentages:
Completion Log: 100.01%
Mastery: 100.07%
Others: 100%

I could imagine Steam is checking for exactly 100% in each of these values for the achievement, but I'm not sure.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/jV4J7Kxt

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [x] Throne of the Herald
- [x] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8604

### Are you using any mods?

Yes

**Comment by ekuland** [comment]
You used auto master mod.

Put this in console to remove the over 100% mastery.
`game.cooking.actionMastery.delete(game.cooking.actions.getObjectByID('melvorF:Lemon_Cake'));`

**Comment by prozinworz** [comment]
Beautiful, thank you. Those stinking lemons...
