### ISSUE TITLE
[Bug]: Missing Tortoise Mastery

### ISSUE THREAD

**Issue by Colinmkh** [MelvorIdle/melvoridle.github.io#4197]
### Describe the bug

In the Summoning Mastery pool where I spend my Mastery XP, there is no “Tortoise” Mastery to spend points in. 

### Reproduction Steps

1. Go to Summoning skill.
2. Click Spend Mastery Pool Xp. 
3. Scroll until “Tortoise”… (you won’t find it, it is missing)

### Expected behaviour

Should be able to spend Mastery XP there on “Tortoise”.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

Unk

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Please ensure the Expansion toggle options are correctly set to display the Tortoise. If issue persists, please open a new report.
