### ISSUE TITLE
Task Missing[Bug]: <title>

### ISSUE THREAD

**Issue by butternutbutter** [MelvorIdle/melvoridle.github.io#4211]
### Describe the bug

This task (2x Confetti Crossbow & 2x Skull Cape) is suddenly missing from the task list for me. I am sure I didn't complete it already because I just purchased the items and they glowed in my inventory. 

First occurred while using the browser version (in Firefox) and then confirmed I have the same issue in the iOS mobile app. 

### Reproduction Steps

1. Go to Tasks, Hard, cannot locate task. 

### Expected behaviour

I had seen the task previously and was saving Slayer coins to complete it. I realized I had enough today and made the purchases. I expected that when I went to Tasks to complete it, it would be there and I could complete it. 

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/EbxuQJVA

### Screenshots

![Screen Shot 2024-04-24 at 1 12 48 PM](https://github.com/MelvorIdle/melvoridle.github.io/assets/168017448/2dee5027-347d-40a3-9ee8-84bf0083e948)
![Screen Shot 2024-04-24 at 1 13 07 PM](https://github.com/MelvorIdle/melvoridle.github.io/assets/168017448/d1226a55-ec7a-4914-9d8d-95a3d13a4fc3)

### Console output

SessionStore: The session file is invalid: TypeError: state.windows[0] is undefined [SessionStore.sys.mjs:1231:19](resource:///modules/sessionstore/SessionStore.sys.mjs)
Sync encountered an error - see about:sync-log for the log file. [policies.sys.mjs:972:15](resource://services-sync/policies.sys.mjs)
Referrer Policy: Ignoring the less restricted referrer policy “unsafe-url” for the cross-site request: https://www.youtube.com/embed/?enablejsapi=1&rel=0&autoplay=0&playsinline=1&expflag=embeds_enable_muted_autoplay%3Atrue&fs=1 [embed](https://www.youtube.com/embed/?enablejsapi=1&rel=0&autoplay=0&playsinline=1&expflag=embeds_enable_muted_autoplay%3Atrue&fs=1)
The resource at “https://adservice.google.com/adsid/google/ui” was blocked by OpaqueResponseBlocking. Reason: “nosniff is true and mimeType is an opaque-blocklisted MIME type or its essence is 'text/plain'”. 2

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8604

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This is something that we can't reproduce, however the upcoming v1.3 upgrade rewrites the TS Task logic so I'll mark this as "In progress" under the assumption it was a bug that has been fixed
