### ISSUE TITLE
[Bug]: Carrot Cake not added to inventory

### ISSUE THREAD

**Issue by armand2c** [MelvorIdle/melvoridle.github.io#4213]
### Describe the bug

I received some **perfect** carrot cakes from some town quest.
when cooking carrot cakes:
all **regular** carrot cakes **are not added** to the inventory, but all other things seem to be normal: displays: +1(0)
all perfect carrot cakes are added to the inventory and all other things seem to be normal
![Fail_1](https://github.com/MelvorIdle/melvoridle.github.io/assets/168081935/5d721314-5c31-473b-a7d5-13ce63953f5a)

### Reproduction Steps

get some perfect carrot cakes via town quest [without having any experience in cooking carrot cakes]
go to cooking
cook carrot cake
normal [not-perfect] carrot cake are not added to bank [there should be plenty of space in the bank]

### Expected behaviour

normal [not-perfect] carrot cake should be added to bank [there should be plenty of space in the bank]

### Screenshots

![Fail_0](https://github.com/MelvorIdle/melvoridle.github.io/assets/168081935/2509a1c3-8625-4c73-96b8-7db90c8792e5)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8604

### Are you using any mods?

No

**Comment by Ayarez** [comment]
Guessing you purchased Cooking Upgrade 1 and have the Carrot Cakes equiped as food. This will automatically add the food to your food inventory. Check the combat page

**Comment by armand2c** [comment]
hey there :)
thanks for your feedback!
I do have all cooking upgrades purchased, but I have the following equipped as food:
1. perfect basic soup
2. perfect tomato soup
3. standard tomato soup
Best regards,
Armand
