### ISSUE TITLE
Firemaking cape not working

### ISSUE THREAD

**Issue by TedzaB** [MelvorIdle/melvoridle.github.io#423]
**Describe the bug**
I get the same experience for all my skills regardless of if I have the firemaking cape equipped or not.

**To Reproduce**
1. Equip the Firemaking skillcape
2. Create Generous Harvest potion
3. 118 or 119 xp gained
4. Stop creating Generous Harvest potion
5. Unequip Firemaking Skillcape
6. Create Generous Harvest potion
7. 118 or 119 xp gained

**Expected behavior**
More xp should have been gained while the Firemaking skillcape was equipped. Note: I have tested with multiple actions on all my <99 non-combat skills and didn't get the 5% bonus xp.

**Browser**
Google Chrome Version 85.0.4183.121 (Official Build) (64-bit).

**Console output** (While creating Generous Harvest potions with the Firemaking skillcape equipped)
VM419:25 GET https://ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js net::ERR_BLOCKED_BY_CLIENT
?l=1:8805 GET https://melvoridle.com/assets/media/shop/assets/media/shop/perpetual_haste.svg 404
DevTools failed to load SourceMap: Could not load content for https://melvoridle.com/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://melvoridle.com/sm/13c28911820333eb6a51103a0e2096477a38941cc79afbf16b59f3d5a5f63086.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
save.js?410:56 Loading Save Game...
save.js?410:179 Save Game Loaded...
DevTools failed to load SourceMap: Could not load content for https://melvoridle.com/assets/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
smithing2.js?406:215 Loading Smithing...
mastery.js?401:187 Updating Masteries
mastery.js?401:23 Loading Masteries...
main.js?436:539 Game Loaded
cloud.js?434:106 1
cloud.js?434:477 Connected to PlayFab successfully

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Please double check your calculations. It works correctly for me (113 XP without cape, 119 with the cape).

Also note that the offline XP displayed is visually incorrect as it does not account for XP bonuses, but the correct XP is still applied.
