### ISSUE TITLE
[Bug]: Golbin raid - Sunset rapier uses "dual strike" from dragon claws

### ISSUE THREAD

**Issue by V3ntrue** [MelvorIdle/melvoridle.github.io#4230]
### Describe the bug

After changing weapon to sunset rapier - my char still used "previous weapon" special attacks instead of normal attack.
Sunset stab "appears" from time to time.``

### Reproduction Steps

1. Go to Golbin raid
2. Obtain dragon claw
3. switch to sunset rapier

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/169095155/4355e931-54a1-4625-90af-94ff0bcfaad2)

### Expected behaviour

No dual strike should occur

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8605

### Are you using any mods?

No

**Comment by V3ntrue** [comment]
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/169095155/dad08f5f-cf25-4bb5-a009-36ac8affe047)

**Comment by MelvorIdle** [comment]
This is due to receiving an (ALT) weapon in the raid which provides a random special attack
