### ISSUE TITLE
dig sites disappeared 

### ISSUE THREAD

**Issue by dickensign** [MelvorIdle/melvoridle.github.io#4232]
### Describe the bug

my ancient market dig site maps have disappeared. i have the option to pay to create a new one. i had been digging there for the last day or so. i went to sleep with archaeology on digging that site and then this morning it was just gone. i did however finish the first initial round of cartography, getting it up to level 101. 

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/32607654/254f08dd-5dc1-4499-9ee9-2b84c17ea176) 
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/32607654/dc816687-6922-442b-a788-91f116d58188)
 
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/32607654/284aadeb-537b-46ef-bfc1-0e4ea86f2b89)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8605

### Are you using any mods?

No

**Comment by dickensign** [comment]
as you can see, it still shows the digging progress/discoveries previously made 

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/32607654/28bd51b0-9a3e-433d-92e6-65120f068638)

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/32607654/e5470d79-15ef-4b62-b1e8-1e0a50d7f116)

**Comment by MelvorIdle** [comment]
Dig site maps have a set amount of actions until it depletes.
