### ISSUE TITLE
[Bug]: Astrology interval with synergy not decreasing

### ISSUE THREAD

**Issue by Depetson** [MelvorIdle/melvoridle.github.io#4235]
### Describe the bug

Currently with owl i have 0.25s interval in astrology.
When eagle added to synergy, interval is not changing. Also it's consuming owl and eagle but summoning xp looks like with only owl equipped.

### Reproduction Steps

Build agi, eq and everything without eagle+owl synergy for astrology (nightfall).
Add eagle to synergy.

### Expected behaviour

Interval reduced.
Summoning XP greater than 3.

### Screenshots

<img width="1504" alt="WithoutSynergy" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/34315263/052503d0-4012-4bf0-b198-f5aecd1f5ebd">
<img width="1503" alt="WithSynergy" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/34315263/cd7a9514-ad5e-434c-a8dd-5e65d5820bda">

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8605

### Are you using any mods?

No

**Comment by 04Slash** [comment]
Intervals are capped at 0.25 seconds. This is done for performance reasons.

**Comment by Depetson** [comment]
Ok i suspected this might be the case. What about summoning XP? Should i create another issue?
