### ISSUE TITLE
[Bug]: <the warning: "not enough regular runes" but it are really enough>

### ISSUE THREAD

**Issue by glbLeb** [MelvorIdle/melvoridle.github.io#4236]
### Describe the bug

when I try fight using magic I receive warning like "not enough regular runes"
but I have enough runes I need for attack in my bank

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/169842138/920f5aba-570b-43dd-88b3-2f1068583de6)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/169842138/686ed7dc-134f-4a12-8eac-eb39b9b0772d)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/169842138/4b8e532d-3afc-4899-81a2-9b60d3fc5ace)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8605

### Are you using any mods?

No

**Comment by 04Slash** [comment]
Do you have the Ring of Spirit Power equipped? If so, you need Spirit Runes to use that item.

**Comment by glbLeb** [comment]
> Do you have the Ring of Spirit Power equipped? If so, you need Spirit Runes to use that item.

Yes you are right! Thank you so much man. Closing the issue :)

**Comment by glbLeb** [comment]
Not a bug
