### ISSUE TITLE
Add "next ore" visual to mining

### ISSUE THREAD

**Issue by Delurielle** [MelvorIdle/melvoridle.github.io#424]
Woodcutting shows a "Locked" mystery tree for the next one to be unlocked, but Mining doesn't show a "Locked" mystery ore. These being inconsistent is a bit weird.

I guess Thieving is also missing a next unlock indicator.

Meanwhile, most other skills show all possible unlocks instead of next level, but maybe this is okay, since they have a different layout, so it's more intuitive to have different behavior.

**Comment by MelvorIdle** [comment]
Added to the upcoming update :)
