### ISSUE TITLE
Unable to keep perfect cooked items

### ISSUE THREAD

**Issue by DavidKoenig55** [MelvorIdle/melvoridle.github.io#4242]
### Describe the bug

When cooking items on my Carrion Cooking Fire, anything that results in a perfect cook shows the icon at the bottom of how many were made and the counter representing the total in my bank. The number in my bank is always zero and I never get to keep any of them.

### Reproduction Steps

1. Select any recipe from cooking fire
2. Click on "Active Cook"
3. Wait for perfect cook to proc

### Screenshots

![perfect](https://github.com/MelvorIdle/melvoridle.github.io/assets/104761133/2bcff025-2c22-4a7f-b892-423bf6923294)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8605

### Are you using any mods?

No

**Comment by 04Slash** [comment]
Is the food going directly into your food slots due to [Cooking Upgrade 1](https://wiki.melvoridle.com/w/Cooking_Upgrade_1)?

**Comment by DavidKoenig55** [comment]
That was it. I didn't realize I had already emptied a slot for it to go into. Thank you
