### ISSUE TITLE
[Bug]: Nysa constellation does not appear in 'spend mastery pool xp' interface

### ISSUE THREAD

**Issue by twalks1** [MelvorIdle/melvoridle.github.io#4243]
### Describe the bug

Nysa constellation not appearing in 'spend mastery pool xp' interface

### Reproduction Steps

1. go to astrology skill
2. click on 'spend mastery pool xp' interface
3. Nysa constellation does not appear

### Expected behaviour

Nysa constellation should be visible and interactive on this interface

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8605

### Are you using any mods?

Yes

**Comment by 04Slash** [comment]
Do you have Atlas of Discovery checked?
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/10db96da-198b-49cb-b61e-65f988a358ef)
