### ISSUE TITLE
I cant cvook manta Rays. [Bug]: <title>

### ISSUE THREAD

**Issue by joeyhelmick1** [MelvorIdle/melvoridle.github.io#4253]
### Describe the bug

When i try to cook my manta rays, the progress bar fills, i get the "+1" notification, but my manta rays does not increase or decrease. I can passive cook during manta ray progress bar and those go into the stockpile like normal.

### Reproduction Steps

Cooking tab> raw manta rays

### Expected behaviour

cooked manta rays

### Screenshots

![Manta](https://github.com/MelvorIdle/melvoridle.github.io/assets/94400238/f21addc4-08c0-4d66-ae51-6f91a0cac0b2)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8625

### Are you using any mods?

No

**Comment by 04Slash** [comment]
The food is likely going directly into your food slots due to [Cooking Upgrade 1](https://wiki.melvoridle.com/w/Cooking_Upgrade_1). You can disable this on the cooking page.
