### ISSUE TITLE
[Bug]: getTaskCompletionsForTierAndAbove incorrectly gets completed tasks

### ISSUE THREAD

**Issue by PsyDrag** [MelvorIdle/melvoridle.github.io#4256]
### Describe the bug

`SlayerTask.getTaskCompletionsForTierAndAbove(category)` is adding that category's completed tasks along with all completed tasks from lower tier categories (`.previousCategory`). This is causing slayer upgrade kit requirements to be met early within the shop (see screenshot below)

### Reproduction Steps

1. in chrome console, run `game.combat.slayerTask.categories.registeredObjects.get('melvorF:Normal').tasksCompleted = 16`
2. reload shop (i just clicked on "shop" in sidebar)
3. you should see something similar to attached screenshot

### Expected behaviour

`getTaskCompletionsForTierAndAbove` should check and add higher tier categories' (`.nextCategory?`) completed tasks to total

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/6046220/47cfab5a-0baa-464b-aeb7-bb227ee83f48)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3 (public_test)

### Game Subversion

?11020

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This is now fixed as of v1.3 ?11090. Thanks for the report!
