### ISSUE TITLE
[Bug]: missing tooltip for abyssal slayer coins in shop

### ISSUE THREAD

**Issue by PsyDrag** [MelvorIdle/melvoridle.github.io#4257]
### Describe the bug

hovering over the abyssal slayer coins at the top of the shop doesn't show a tooltip

### Reproduction Steps

1. go to shop
2. hover mouse over abyssal slayer coins icon

### Expected behaviour

tooltip should show

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3 (public_test)

### Game Subversion

?11020

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
I am unable to reproduce this bug. Could you please provide a save this occurs on?

**Comment by PsyDrag** [comment]
here's two save files. i believe they're both new saves (skipped tutorial, went straight to shop). no mods enabled on either.
https://melvoridle.com/save/fa5Nz1eL
https://melvoridle.com/save/c0pIiY6J

**Comment by PsyDrag** [comment]
i am no longer seeing this bug now that ItA has released
