### ISSUE TITLE
Firemaking Softlocked

### ISSUE THREAD

**Issue by Vaelkyrie** [MelvorIdle/melvoridle.github.io#426]
![Screenshot_20201001-043647](https://user-images.githubusercontent.com/72194005/94787799-c7670400-03a0-11eb-8a60-94d2fbf94b6d.png)

Literally unable to access first tier of logs to start firemaking with because the list pushes it put of view 

Android/Mobile

**Comment by Vaelkyrie** [comment]
Obviously I could sell some log types, but I would prefer (hopefully understandably)- not to, as it would invalidate the time spent getting them

**Comment by MelvorIdle** [comment]
I've got some minor adjustments coming in the next update to hopefully fit all of those logs on small screens.

You can position your scroll and it should show the first log by default which can temporarily fix it. I think if the dropdown is near the top of the screen, it will allow you to see it.
