### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by Kira-Bella** [MelvorIdle/melvoridle.github.io#4261]
### Describe the bug

Warehouse item values, some combat attributes, and gold values become NaN. The correct values appear only when the mouse cursor is placed over the item. Values have not been modified using cheaters, but some mods have been used

### Expected behaviour

All values converted to NaN return to normal

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/jLhLLj6D

### Screenshots

![屏幕截图 2024-06-07 212714](https://github.com/MelvorIdle/melvoridle.github.io/assets/172046804/cc6700c5-41d1-4ed6-af6a-b16deba41d65)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

？8625

### Are you using any mods?

Yes

**Comment by 04Slash** [comment]
This is probably a mod conflict. The mod "Decimals" and "10K (100千 to 10万)" both overwrite the function that is used to format numbers. This formatting is removed when hovering over the bank icon.

"10K (100千 to 10万)" also adds 2 decimal places to numbers which makes the mod "Decimals" not necessary.
