### ISSUE TITLE
[Bug]: Equipments/Summoning Tablets cannot be useded in multiple Equipment Sets

### ISSUE THREAD

**Issue by gs2015** [MelvorIdle/melvoridle.github.io#4264]
### Describe the bug

When a  equipment/summoning tablet is equiped in one Equipment Set, it cannot be used in other  Equipment Sets.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8625

### Are you using any mods?

Yes

**Comment by Ayarez** [comment]
They can, just adjust this slider when equiping them
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/151032073/a9659526-9827-4d1f-8349-5f53bfe3b641)
