### ISSUE TITLE
[Bug]: <Cartography Map stuck at 4%>

### ISSUE THREAD

**Issue by Waalsneer** [MelvorIdle/melvoridle.github.io#4265]
### Describe the bug

Map stuck loading at 4%
![Screenshot_2024-06-10-09-31-08-409_com malcs melvoridle](https://github.com/MelvorIdle/melvoridle.github.io/assets/172228213/562f96da-706c-410e-8f6a-e2d24e7aa29c)

### Expected behaviour

Load to 100% 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [x] Throne of the Herald
- [x] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3 (public_test)

### Game Subversion

?8625

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Related #4218 (Closing to clean issues)
