### ISSUE TITLE
[Bug]: Auto Survey seems to leave some closer hexes undiscovered

### ISSUE THREAD

**Issue by jschpp** [MelvorIdle/melvoridle.github.io#4266]
### Describe the bug

When using "Auto Survey" there seems to be some kind of problem when selecting which hexes to survey next.

As you can See from the attached screenshots, auto survey seems to leave some hexes to discover last, even if they are much closer than others.

As to the screenshot you can see that I'm standing on 24,27 and started discovery on 22,27. Somhow the three hexes "below" the hex I'm standing on (23,27 24,28 and 25,27) seem to be pushed back to the end of the survey queue.

This happened some time ago as well as you can see around the "Capital City Lighthouse"(27,13) there you can see the lower three hexes undiscovered as well.

### Reproduction Steps

Not sure how to reproduce this one

### Expected behaviour

Closer Hexes should be surveyed first

### Screenshots

![Screenshot 2024-06-10 115747](https://github.com/MelvorIdle/melvoridle.github.io/assets/1764320/90b66150-e014-4316-a0cd-33c2c4527d38)
Current location and survey queue around me

![Screenshot 2024-06-10 115756](https://github.com/MelvorIdle/melvoridle.github.io/assets/1764320/a75fcec8-27d3-491b-a36e-03fbc24923c4)
Next hexes in queue as well as last location where this happend last time

![Screenshot 2024-06-10 115803](https://github.com/MelvorIdle/melvoridle.github.io/assets/1764320/7e1e8356-f657-4ef1-8dc3-8aa7ebc3e9dd)
Last Locations in queue

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8625

### Are you using any mods?

Yes

**Comment by durron597** [comment]
This is expected behavior, it follows a spiral pattern starting from your hex and doesn't change no matter which hex in that spiral you click. After the entire map is surveyed, the "cursor" goes back to you and surveys those near tiles.

This is actually a good thing for the player, as you can do something else and then come back and have available hexes to auto-survey.

**Comment by jschpp** [comment]
But shouldn't a spiral include all hexes closest to me?

If this is indeed intended feel free to close this.

**Comment by durron597** [comment]
I can't close it, I'm just another player 🤣 I just know it's been like this forever, wiki guides talk about it, etc.
