### ISSUE TITLE
[Bug]: Goblin Raid: Ragnar Godsword 2h attacks as poison hit and does not use ability

### ISSUE THREAD

**Issue by levlazarev** [MelvorIdle/melvoridle.github.io#4267]
### Describe the bug

After equipping the Ragnar Godsword as a weapon reward attack interval changed to poison hit and does not trigger infernum attack either.

### Reproduction Steps

Select weapon
Select Ragnar Godsword 2h
Attack is incorrect

### Expected behaviour

Ragnar Godsword should attack and proc Infernum with expected 20% chance

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/74716293/bb3f5658-6967-4bee-9ad6-58f88dcec36d)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8625

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
You have selected an (ALT) weapon in the Raid, which gives you the weapon alongside a randomised special attack.
