### ISSUE TITLE
[Bug]: XP Modifier Details Inaccurate with Ancient Ring of Skills

### ISSUE THREAD

**Issue by ImAlsoMango** [MelvorIdle/melvoridle.github.io#4268]
### Describe the bug

When training non combat skills, I do not receive details for an increase to my XP modifiers when the Ancient Ring of Skills is equipped, however the XP modifier is still active and applies to training done.

### Reproduction Steps

1. Equip ancient ring of skills 
2. Go to train a skill (astrology in this case, fishing tested too)
3. XP received is increased by expected amount, but info to XP modifiers listed in the details for the total improvements to XP gained from modifiers

### Expected behaviour

The hover summary for XP gained per action when performing a non combat skill should be detailed to include the bonus 8% from the ancient ring of skills.

### Screenshots

![ring_on](https://github.com/MelvorIdle/melvoridle.github.io/assets/64700041/5ae0af4f-93ce-495a-ab5d-4d97fd7f0ee5)
![ring_on2](https://github.com/MelvorIdle/melvoridle.github.io/assets/64700041/999360fb-4043-48cf-b9ce-69b126b9eae7)
![ring_off](https://github.com/MelvorIdle/melvoridle.github.io/assets/64700041/a75873f9-dbb3-4e58-98f9-e6999b1ca724)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3 (public_test)

### Game Subversion

?11181

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue was resolved in hotfix.
