### ISSUE TITLE
[Bug]: Mobile Combat Popup Misaligned 

### ISSUE THREAD

**Issue by GalaxyGirl230** [MelvorIdle/melvoridle.github.io#4269]
### Describe the bug

After the 1.3 update, the combat popup at the bottom of the screen got misaligned. The run button got pushed to the left, and the box for the player health and attack is slightly shifted a couple pixels rather than aligned with the box above it. The gray bars for the combat timer are also missing.

### Screenshots

![Screenshot_20240610_231409_Melvor Idle](https://github.com/MelvorIdle/melvoridle.github.io/assets/12107631/de39ce3b-fefe-4989-8f51-aa73ea4933b4)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11183

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of version 1.3 (?11262)
