### ISSUE TITLE
Options : Disable Desktop Ads selection not saving

### ISSUE THREAD

**Issue by Grimpickle** [MelvorIdle/melvoridle.github.io#427]
**Describe the bug**

When I **open** or **refresh** the melvoridle.com site and choose my save, the ad at the top returns. Neither of the  **Disable Desktop Ads** radio buttons are checked, even though I had previously enabled this setting.

**To Reproduce**

0. Become a Patreon supporter (I think) to get the option to disable ads.
1. Go to melvoridle.com or refresh the game.
2. Click on the save you are using.
3. Look at the top of the game page.
4. See the error; the ad is showing despite having enabled the **Disable Desktop Ads** setting.

**Expected behavior**

The ad should be hidden.

**Screenshots**

N/A

**Browser**

Google Chrome
Version 85.0.4183.121 (Official Build) (64-bit)

**Console output**

Failed to load resource: the server responded with a status of 404 (Not Found)
mraid.js:1 Failed to load resource: the server responded with a status of 403 ()
mraid.js:1 Failed to load resource: the server responded with a status of 403 ()
﻿
**Are you using any scripts?**

None

**Comment by MelvorIdle** [comment]
Hopefully getting this one fixed for the next update
