### ISSUE TITLE
[Spelling/Grammar]: <title>Typo in the slayer coin necklace description?

### ISSUE THREAD

**Issue by Flurryous** [MelvorIdle/melvoridle.github.io#4272]
### What text is wrong?

The Palladium Onyx, Oricha, and Runestone Necklaces all have their descriptions changed to "+1 slayer coins from Melee/Ranged/Magic slayer tasks equal to the enemy's combat level." Previously, their texts mentioned "Killing a Melee/Ranged/Magic Slayer Task Enemy grants Slayer Coins equal to Enemy Combat Level." The "+1" seems out of place with the rest of the description, and may confuse readers. 

Onyx corresponds to melee, Oricha with ranged, and Runestone with magic for the descriptions above. 

### What is the correct spelling or grammar?

Something like "+1 slayer coin per enemy combat level from Melee/Ranged/Magic slayer tasks" might make more sense if we're changing the old description.

**Comment by MelvorIdle** [comment]
This is now hotfixed as of v1.3 ?11203
