### ISSUE TITLE
[Bug]: mastery seemingly broken 

### ISSUE THREAD

**Issue by colewarn** [MelvorIdle/melvoridle.github.io#4273]
### Describe the bug

My mastery levels seem to be broken, went in to turn off my mods in advance of the update and now my mastery seems to be broken. 

### Reproduction Steps

1.) have mastery overflow mod on
2.) go to load game to try and turn mods off to no avail
3.) notice that skilling had been interrupted and now the mastery level for thieving acolytes is NaN as opposed to 99 as I just achieved earlier today
4.) submit this report, thanks for your help!

### Expected behaviour

I still expected to gain mastery benefits and see my 99 mastery level for thieving acolytes. 

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/u3kHhiAz

### Screenshots

![IMG_2534](https://github.com/MelvorIdle/melvoridle.github.io/assets/16833661/692d31ee-f631-4916-80e3-ec698ae045d8)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?11186

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This bug was caused by broken mods for the v1.3 update. Please disable your mods and only re-enable once you have confirmed they are updated.

To fix the NaN issue, please follow these steps: https://www.reddit.com/r/MelvorIdle/comments/1dd3d2a/uhh_anyone_else_seeing_this_for_mastery/l82oxi8/
