### ISSUE TITLE
[Bug]: Skill matery with more than 100% matery exp  displayed as NaN

### ISSUE THREAD

**Issue by gs2015** [MelvorIdle/melvoridle.github.io#4274]
### Describe the bug

After update,  Skill matery with more than 100% matery exp  displayed as NaN
![微信图片_20240611122100](https://github.com/MelvorIdle/melvoridle.github.io/assets/15153868/ce44e264-7219-4140-831b-c23b831f9b83)
![111-微信截图_20240611122351](https://github.com/MelvorIdle/melvoridle.github.io/assets/15153868/0b82fe74-c469-425c-bd95-2422ebf86b09)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

11183

### Are you using any mods?

Yes

**Comment by gs2015** [comment]
After traning a skill with 100% mastery and relogin, the master becomes NaN.
![微信截图_20240611122854](https://github.com/MelvorIdle/melvoridle.github.io/assets/15153868/84119ed8-bd92-4b58-b304-9067a72e67eb)

**Comment by MelvorIdle** [comment]
This bug is caused by broken mods for the v1.3 update. Please disable your mods and only re-enable once you have confirmed they are updated.

To fix the NaN issue for your save, please follow these steps: https://www.reddit.com/r/MelvorIdle/comments/1dd3d2a/uhh_anyone_else_seeing_this_for_mastery/l82oxi8/
