### ISSUE TITLE
NaN Mastery pool XP

### ISSUE THREAD

**Issue by FrostyxFeet** [MelvorIdle/melvoridle.github.io#4275]
### Describe the bug

Loaded v1.3 with Mastery XP can Overflow mod when fishing Ghost Fish and when opening the game it said the mod broke and caused my actions to stop and forced me to close the game and turn off the mod. After doing so the master xp for Raw Ghost Fish is NaN and total mastery xp for Fishing is NaN

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/vb9LcS4s

### Screenshots

![NaN](https://github.com/MelvorIdle/melvoridle.github.io/assets/172350888/e76a8be3-1fe6-41f1-9c63-4531bcb6f362)
![NaN2](https://github.com/MelvorIdle/melvoridle.github.io/assets/172350888/5089c7cc-88f5-48d3-a16f-fb3b9cefa028)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11183

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This bug was caused by broken mods for the v1.3 update. Please disable your mods and only re-enable once you have confirmed they are updated.

To fix the NaN issue, please follow these steps: https://www.reddit.com/r/MelvorIdle/comments/1dd3d2a/uhh_anyone_else_seeing_this_for_mastery/l82oxi8/
