### ISSUE TITLE
[Bug]: golbin raid crash

### ISSUE THREAD

**Issue by UMC049** [MelvorIdle/melvoridle.github.io#4278]
### Describe the bug

click into golbin raid then the game crash.
now the save is stuck and can't be played for now.

An error occurred while rendering:
Error Name: TypeError
Error Message: Cannot set properties of null (setting 'textContent')
Stack Trace:
TypeError: Cannot set properties of null (setting 'textContent')
    at https://steam.melvoridle.com/assets/js/built/raidPlayer.js?11186:59:139
    at Array.forEach (<anonymous>)
    at RaidPlayer.renderLevels (https://steam.melvoridle.com/assets/js/built/raidPlayer.js?11186:59:34)
    at RaidPlayer.render (https://steam.melvoridle.com/assets/js/built/raidPlayer.js?11186:58:6)
    at RaidManager.render (https://steam.melvoridle.com/assets/js/built/baseManager.js?11186:79:22)
    at RaidManager.render (https://steam.melvoridle.com/assets/js/built/raidManager.js?11186:35:16)
    at Game.render (https://steam.melvoridle.com/assets/js/built/game.js?11186:303:48)
    at Game.loop (https://steam.melvoridle.com/assets/js/built/game.js?11186:335:35)

Active Action: melvorD:GolbinRaid
Current Equipment:
melvorD:Helmet: melvorF:Slayer_Helmet_Strong
melvorD:Platebody: melvorD:Ancient_Platebody_T_S
melvorD:Platelegs: melvorD:Dragon_Platelegs_T_S
melvorD:Boots: melvorD:Black_Wizard_Boots
melvorD:Weapon: melvorF:Glacia_Godsword
melvorD:Amulet: melvorD:Amulet_of_Calculated_Promotion
melvorD:Ring: melvorF:Sandstorm_Ring
melvorD:Gloves: melvorF:Elementalist_Gloves
melvorD:Quiver: melvorF:Sapphire_Bolts
melvorD:Cape: melvorD:Attack_Skillcape

Action Information:
Is In Combat: true
Fight in Progress: false
-- Start of Player Information --
Next Action: Attack
Next Attack: melvorD:LifeLeech
Is Attacking: false
Attack Spell Selected: melvorD:WindStrike
Aurora Selected: undefined
Curse Selected: undefined
Active Prayers: None
Equipped Food:
Item: melvorD:Beef_Pie_Perfect, Qty: 63
-- End Player Information --
-- Start of Enemy Information --
Enemy: melvorTemp:RaidGolbin
Next Action: Attack
Next Attack: melvorD:Normal
Is Attacking: false
Attack Spell Selected: undefined
Aurora Selected: undefined
Curse Selected: undefined
-- End Enemy Information --
Modding Enabled. Loaded mods:

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11183

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Can you please provide a copy of your save so we can take a look? Thank you.

**Comment by UMC049** [comment]
> Can you please provide a copy of your save so we can take a look? Thank you.

[melvoridlesave_1sek_2024-6-11_153416.txt](https://github.com/user-attachments/files/15783999/melvoridlesave_1sek_2024-6-11_153416.txt)

**Comment by MelvorIdle** [comment]
This is now hotfixed as of v1.3 ?11203

**Comment by UMC049** [comment]
> This is now hotfixed as of v1.3 ?11203

Ok.Thanks
