### ISSUE TITLE
[Bug]: Rune reduction from staves not working

### ISSUE THREAD

**Issue by FelixAbrahamsson** [MelvorIdle/melvoridle.github.io#4279]
### Describe the bug

When using air mystic/battlestaff and any basic magic spell, it still always uses at least 1 air rune. Even on wind strike. I haven't tried with other rune reduction staves or items.

### Reproduction Steps

Equip mystic air staff or air battlestaff, use wind strike and watch the air runes deplete 1 at a time.

### Expected behaviour

I would expect to not lose any air runes at all.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11186

### Are you using any mods?

No

**Comment by cleshams** [comment]
Experiencing this on Epic (Mac) and for fire staff

**Comment by MelvorIdle** [comment]
v1.3 fixed the bug relating to Rune costs being able to be reduced below 0, as this was unintended functionality.

**Comment by FelixAbrahamsson** [comment]
> v1.3 fixed the bug relating to Rune costs being able to be reduced below 0, as this was unintended functionality. This change was noted under the "Fixes" section of the changelog.

Well it should still be allowed to be reduced TO zero, shouldn't it? Or is it expected behaviour that wind strike still costs an air rune with mystic air staff equipped? If so the tooltip is confusing. I'm very sad if this is the case, ruins my combat only, magic only account :(
