### ISSUE TITLE
Elder Dragon isn't considered a boss

### ISSUE THREAD

**Issue by Falterfire** [MelvorIdle/melvoridle.github.io#428]
**Describe the bug**
surprise i discovered this because it screwed with wiki stuff.

Basically: Elder Dragon is missing the 'isBoss: true' line in Monsters.js, which mostly just matters to me because it means it doesn't properly register as a boss when I'm determining whether or not its drops count in the wiki data.

**Comment by MelvorIdle** [comment]
Fixed in the coming update :)
