### ISSUE TITLE
[Bug]: Monkey and Pig synergy increases crafting cost instead of decreasing it

### ISSUE THREAD

**Issue by Hellfirem4ge** [MelvorIdle/melvoridle.github.io#4281]
### Describe the bug

Equip monkey and pig
Cost of dragon hide equipment increases by 1 instead of decreasing due to synergy 

### Reproduction Steps

Equip both summoning familiar for synergy bonus
Check crafting costs 

### Expected behaviour

Cost should decrease by 1

### Screenshots

. 

### Console output

. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

. 

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This is now hotfixed as of v1.3 ?11207. Thanks for the report!
