### ISSUE TITLE
[Bug]: Viewing Astro Modifiers is reporting inflated values

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#4283]
### Describe the bug

A lot (not all) of modifiers in the 'View All Active Modifiers' in Astrology are being inflated. This seems to just be a visual bug.

### Reproduction Steps

1. Go to Astrology
2. Add 1 point into a Mastery XP node such as Deedree's +Woodcutting/Farming Mastery XP
3. See the reported value in active modifier list
4. Value should be reported as 2% instead of 1%.

### Expected behaviour

The modifiers in the list should be reporting their correct values.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/0ed28a11-e097-400a-962e-e40827f8a430)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/c4cf0574-ec77-449b-9572-85b4c53e2106)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11194

### Are you using any mods?

No

**Comment by muniategui** [comment]
When full constellations with ancient relics or without (doubling the bonus) the values displayed are absurd (but they are not applied however just visual), the double does not seem to change the values:
![imagen](https://github.com/MelvorIdle/melvoridle.github.io/assets/14365006/76ee18c1-2d55-44e9-9399-10a551bc2416)

All skills +128% mastery xp, absurd double chances and so on.

**Comment by coolrox95** [comment]
Issue has been resolved as of version 1.3 (?11262)
