### ISSUE TITLE
NaN values after last update (v.1.3)[Bug]: <title>

### ISSUE THREAD

**Issue by HarryKalantzopoulos** [MelvorIdle/melvoridle.github.io#4284]
### Describe the bug

Probably because I had left open the mods by Semi. It caused to show "NaN" values in mastery (Farming, Mining). Also, I cannot gather the aforementioned resources anymore. I turned off all the mods, but the problem persists.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/poVWVl3e

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/18500976/7304d5ef-f241-45db-b087-1c03f277bb9a)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/18500976/c67e3e8c-92b0-42b8-8d35-85e7c37a8d46)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11194

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This bug was caused by broken mods for the v1.3 update. Please disable your mods and only re-enable once you have confirmed they are updated.

To fix the NaN issue for your save, please follow these steps: https://www.reddit.com/r/MelvorIdle/comments/1dd3d2a/uhh_anyone_else_seeing_this_for_mastery/l82oxi8/
