### ISSUE TITLE
[Bug]: <title> Resource Preservation cap not increasing with cap increasers equipped.

### ISSUE THREAD

**Issue by Flurryous** [MelvorIdle/melvoridle.github.io#4287]
### Describe the bug

As title. Herblore's preservation cap does not seem to be going past 80% even with Bear + Fox and/or Herblore Preservation Scrolls equipped. Fletching's preservation cap seems to have the same issue, with Bear + Beaver not increasing the cap. 

At the moment I can only recall these two skills having cap increasers, can't remember if there were more.

### Reproduction Steps

1. Gather enough resource preservation so that it goes past 80% for herblore/fletching.
2. Equip the items that should increase the cap.
3. Check the UI to see that the preservation rate is staying at 80% even if you have more bonuses than that.

### Expected behaviour

The preservation cap increasers should be increasing the cap by their described amount. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11203

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of version 1.3 (?11262)
