### ISSUE TITLE
[Bug]: Currency values over 1M missing decimal places

### ISSUE THREAD

**Issue by PsyDrag** [MelvorIdle/melvoridle.github.io#4288]
### Describe the bug

according to the v1.3 changelog under UI Adjustments "Currency values now show decimal places over 1M." however, no decimals are being added to values over 1M.

seen on a new account with no mods installed

### Reproduction Steps

1. create new account with no mods installed
2. set number format setting to "1M" (if using "1,000K", use a larger number in step 4)
3. refresh
4. set GP/SC to value over 1M. I used 1.1M (1100000)
5. rendered quantity shows as "1M"

### Expected behaviour

rendered quantity should show as "1.1M" (or more decimal places. i don't know how many it's supposed to have)

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/caPkUw7H

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/6046220/8041f249-5844-4349-98d2-5ccdfdfc9621)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11203

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of version 1.3 (?11262)
