### ISSUE TITLE
[Bug]: Crafting cost are higher with Synergie (Pig & Monkey)

### ISSUE THREAD

**Issue by k33per13013** [MelvorIdle/melvoridle.github.io#4289]
### Describe the bug

The synergy of the pig and the monkey causes it to cost 1 more and not 1 less

### Expected behaviour

cost 1 less

### Screenshots

The synergy of the pig and the monkey causes it to cost 1 more and not 1 less
![with](https://github.com/MelvorIdle/melvoridle.github.io/assets/172376616/fba70af3-994c-491c-ae41-320bcb960e1e)
![without](https://github.com/MelvorIdle/melvoridle.github.io/assets/172376616/7a7d8658-76f6-4f1d-bf1b-9dbbb599b3c0)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [X] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

V1.3 (?11195)

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been resolved in hotfix
