### ISSUE TITLE
[Bug]: bonus calculations incomplete : Thievery - stealth bonus on double chance

### ISSUE THREAD

**Issue by Perrin3088** [MelvorIdle/melvoridle.github.io#4291]
### Describe the bug

The double chance on thievery is only displaying the bonuses for my astrology signs, and not the bonuses I get from stealth.

### Reproduction Steps

Thievery
Double chance tooltip
Bonuses don't add up to total.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/131163250/9208f4d8-a09b-48b5-a2bf-dfa48df3082d)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11207

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of version 1.3 (?11262)
