### ISSUE TITLE
[Bug]: <! mark on township tasks after completion of that task>

### ISSUE THREAD

**Issue by Ssniper98** [MelvorIdle/melvoridle.github.io#4292]
### Describe the bug

The ! green mark still visible at the tasks on township after I claimed the task that I completed. This was not a problem before the new 1.3 update.

### Reproduction Steps

1. Complete a task
2. Go to township tasks and claim the reward
3. See all tasks and at the tasks button the ! mark is still there, but you cannot see it on with level.

### Expected behaviour

The ! mark should disapear on the tasks button after claiming the reward

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/170647623/1b0728d7-094e-4fc5-946a-89712b13cbfa)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11207

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of version 1.3 (?11262)
