### ISSUE TITLE
[Bug]: Can't damage any creatures in fighting

### ISSUE THREAD

**Issue by jthe111** [MelvorIdle/melvoridle.github.io#4294]
### Describe the bug

Before the update I had a run going where I was attacking multiple instances the volcano dungeon. Now I can't hit a simple bat from the same dungeon. It's just constant misses. 

### Expected behaviour

I would like to be able to progress through du geons again. 

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/EvzWgURQ

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11207

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
I am unable to reproduce this issue with the save provided.

This issue is more than likely due to one of your installed mods. Please disable your mods and try to reproduce issues without them before filing bug reports.
