### ISSUE TITLE
[Bug]: Mastery Pools empty and Herblore Mastery broken after update

### ISSUE THREAD

**Issue by RwSlagathor** [MelvorIdle/melvoridle.github.io#4297]
### Describe the bug

After logging in I noticed all of my mastery pools are now empty except for cooking. I can still earn mastery XP but the pools have been reset  for every skill. Herblore was the skill that I was training offline overnight and the mastery pool is now showing "NaN/26,000,000 (NaN%) Skill XP". I was making the Multicooker Potion which is also showing NaN mastery for the item. All of the other Herblore potions are now at 99 mastery as well, when they should mostly be somewhere between 70 to 80. My bank also shows that I have an Herblore mastery token but when I tried to claim it, it now shows that I have NaN tokens and gives 0 XP.

Last night, I did load my save with some mods enabled but was given an error message so I closed the game and reloaded from a cloud save with no mods and it was working fine. When I re-enabled the mods that had been updated this morning, that is when I noticed that all of the mastery pools were empty. I have tried loading the save with no mods enabled but the mastery pools are still empty and herblore mastery pool is still broken.

EDIT: I just tried making a melee accuracy potion to see what would happen with the mastery pool and now the melee accuracy potion is also showing NaN mastery level. Upgrading the melee accuracy potions in my bank also deleted all off them.
EDIT: The NaN Mastery bug is also happening with farming. So it seems that by loading the save with mods that hadn't been updated, the skills that made progress while offline had their mastery pool value set to NaN.

Pre Update, this was my mod load order:
SEMI Core
[Myth] Combat Simulator
Show Skill Modifiers
Mastery Pool Can Overflow
Reveal Unlocks
Bypass Agility Costs
SEMI Auto Farming
SEMI Auto Master
Upgrade All Potions
SEMI Drop Chances
Rune Shop

Post Update mod load order:
SEMI Core
[Myth] Combat Simulator
Mastery Pool Can Overflow
Reveal Unlocks
SEMI Auto Farming
SEMI Auto Master
SEMI Drop Chances

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/BgJS46lr

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

V1.3 ?11207

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
This bug was caused by broken mods for the v1.3 update. Please disable your mods and only re-enable once you have confirmed they are updated.

To fix the NaN issue, please follow these steps: https://www.reddit.com/r/MelvorIdle/comments/1dd3d2a/uhh_anyone_else_seeing_this_for_mastery/l82oxi8/
