### ISSUE TITLE
[Bug]: Automatically equip food check before the upgrade

### ISSUE THREAD

**Issue by TheGha** [MelvorIdle/melvoridle.github.io#4298]
### Describe the bug

The check for "Automatically equip food when it is made?" appears. The check is non functional tho and does not equip the food when checked.

### Reproduction Steps

1. go to cooking tab on a character who does not have the upgrade

### Expected behaviour

no button should be there

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11207

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue has been resolved as of version 1.3 (?11262)
