### ISSUE TITLE
[Bug]: Centaur Familiar Creation - incorrect recipe cost

### ISSUE THREAD

**Issue by knoxdak** [MelvorIdle/melvoridle.github.io#4299]
### Describe the bug

While summoning Centaur familiars, I would expect the recipe for redwood short/long bows to be cheaper than magic short/long bows, but it requires 50 of them to craft.

### Reproduction Steps

1. go to summoning page 
2. click tablets/familiars
3. click centaur
4. click select recipe
5. scroll down to redwood recipes at bottom
6. see they require 50 to craft 

### Expected behaviour

Like other summoning recipes, I would expect the recipe at the bottom to use the least materials, because they are high level

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11207

### Are you using any mods?

No

**Comment by knoxdak** [comment]
Just realized the wiki shows the recipe should be 50 short/long redwood bows to craft a Centaur familiar, so I guess it's working as intended, but I'm confused on the design philosophy. It seems other recipes require fewer mats as the quality goes up, why is this different?

**Comment by knoxdak** [comment]
Are you sure that this isn't a case of long standing bug is documented by wiki, and then becomes a feature? Most summoning recipes that take created materials require less of said materials as you choose higher tier recipes. The only exceptions here are the Ent, which requires more redwood (also confusing), and the summoning recipes that require runes, which makes more sense that they're all consistent.

**Comment by SolidKalium** [comment]
The costs in the wiki are pulled from game data. I believe the pattern happens to look like fewer high-level resources are required, but it's actually that fewer high-sell-price resources are required. Redwood bows sell for 20gp while magic bows sell for 315gp, which explains why ents need 50 redwood bows or 4 magic bows.
