### ISSUE TITLE
[Bug]: skill interval bar incorrectly resets, visual only

### ISSUE THREAD

**Issue by lukas-ghl** [MelvorIdle/melvoridle.github.io#4300]
### Describe the bug

In Astrology and Cartography (Dig Site Upgrade), the skill interval bar sometimes starts loading from 0 when in reality the timer is not at 0. It becomes noticable when the small popup shows that I gained Astrology or Cartography XP at a point where the progress bar was not near the end, and the bar prematurely resets. It happens when I switch the current display to something else and then back again, e.g. check out a different constellation from the one I currently study or switch from upgrading a dig site map to Dig Site Map Refinement and back again. 

### Reproduction Steps

In Cartography:
1. Go to Cartography -> Dig Site Map Creation, select a dig site and start Upgrading Dig Site Map
2. Go to Dig Site Map Refinement
3. Go back to Dig Site Map Refinement at any time before the current skill interval is finished
4. Progress bar starts from 0, while Timer is (apparently) not at 0 
5. Finished Skill Action pop up will show up and progress bar will reset before having reached the end 

In Astrology: 
1. Choose a Constellation and start Studying it
2. "Explore" a different constellation
3. Go back to the main list with all constellations
4. Progress bar starts from 0, while Timer is (apparently) not at 0 
5. Finished Skill Action pop up will show up and progress bar will reset before having reached the end 

### Expected behaviour

When getting back to the menu with the currently performed skill action, I expect the progress bar to start at the current progress for the current skill action (e. g. when I'm halfway done, it should start in the middle of the bar) and not from 0 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11207

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of version 1.3 (?11262)
