### ISSUE TITLE
[Bug]: Township upgrade available icon persists at 100% completed

### ISSUE THREAD

**Issue by AustinNotAustin** [MelvorIdle/melvoridle.github.io#4302]
### Describe the bug

After the update, I have an icon in my township region that shows I have an available upgrade. I am 100% complete in my township buildings.
![Screenshot_20240611_095734_Melvor Idle](https://github.com/MelvorIdle/melvoridle.github.io/assets/41271157/e9c75e46-30fe-42c7-9263-482fca0e2d11)

### Reproduction Steps

I have 100% township buildings.
I logged out for a bit (not my first time logging in on this patch, just 1st time noticing)
Log in later and repair buildings, icon is showing.

### Expected behaviour

Icon go away.

### Screenshots

![Screenshot_20240611_095734_Melvor Idle](https://github.com/MelvorIdle/melvoridle.github.io/assets/41271157/885c6af7-6134-4a23-9da2-91a70b1cd07c)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11217

### Are you using any mods?

No

**Comment by durron597** [comment]
Is your town hall fully repaired? I'm getting the same thing with my town halls damaged

**Comment by AustinNotAustin** [comment]
Yes it is fully repaired, I used the repair all button to repair.

**Comment by MelvorIdle** [comment]
Could you please provide a save for us to take a look? Thanks!
