### ISSUE TITLE
[Bug]: Superior Max Skillcape does not inherit all bonuses from Superior Summoning Skillcape

### ISSUE THREAD

**Issue by Nota-gh** [MelvorIdle/melvoridle.github.io#4303]
### Describe the bug

Superior Max Skillcape does not inherit the "+10 base primary resource quantity gained in Summoning" portion of the perk of the Superior Summoning skillcape, it does keep the interval reduction and resource preservation. Does not occur with regular skillcape versions.

### Reproduction Steps

Switching between Superior Summoning skillcape and Superior max skillcape while creating tablets, tablet creation amount is not increased by 10 while the Superior Max skillcape is equipped.

### Expected behaviour

Expected behavior is the same amount of tablets being created while the Superior Max skillcape is equipped.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11207

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue has been resolved as of version 1.3 (?11262)
