### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by wakasm** [MelvorIdle/melvoridle.github.io#4306]
### Describe the bug

After loading the new patch, I am not getting NaN for a bunch of things.  Mainly, the skill that I was leveling before the update, my item completion.  I also cannot use Mastery XP anymore, everything shows as red no matter what I do.  

Since I was unaware of the update (just instantly clicked play) I was using these mods: 

Will I Die
Bypass Agility Costs

I have a few other mods installed but not turned on.

I immediately turned these two mods off after noticing something was broken. 

### Reproduction Steps

1.  Load Game
2. Everything above is exactly how it is - things show as NaN 
3. Try and use Mastery XP - can't do it
4. Try and view completion log - can't see anythign and shows NaN

### Expected behaviour

I expect to have XP on the skill, and be able to use Mastery XP, and view the comletionion log. 

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/FIZfbyVt

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11217

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This bug was caused by broken mods for the v1.3 update. Please disable your mods and only re-enable once you have confirmed they are updated.

To fix the NaN issue, please follow these steps: https://www.reddit.com/r/MelvorIdle/comments/1dd3d2a/uhh_anyone_else_seeing_this_for_mastery/l82oxi8/
