### ISSUE TITLE
[Bug]: Error: No suitable description exists for value: 0

### ISSUE THREAD

**Issue by edisonhello** [MelvorIdle/melvoridle.github.io#4307]
### Describe the bug

There is an error description in agility's "View All Global Active Passives from Agility".

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/15229692/f0c58c70-3da2-4487-ab3f-1f2dbeed2f1a)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/15229692/9531415d-d63d-47ca-bd96-e2e77be22197)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/15229692/3c1f9b67-8abe-4469-a4be-183a6d8db023)

After comparison, I found that my summation of all damage reduction modifiers is 1% + 1% - 2% = 0%, and that's the only one modifier that does not appear on the list.

The problem persists even with all mods disabled.

### Reproduction Steps

1. Choose "Lake swim", "Spike Trap", and "Raft Building" and choose obstacles that don't include any about damage reduction.
2. See the "View All Global Active Passives from Agility".

### Expected behaviour

Maybe the line should not appear, or display "0% damage reduction".

### Console output

```
Silent Sign in with JWT
cloudManager.js?11217:329 Validating Melvor Cloud token
cloudManager.js?11217:329 Storing Melvor Cloud Token
cloudManager.js?11217:329 Initializing PlayFab login. Method: customID
cloudManager.js?11217:329 Logging in with Custom ID via PlayFab
cloudManager.js?11217:329 Login with custom ID success
cloudManager.js?11217:329 Getting account info
cloudManager.js?11217:329 Account info retrieved
cloudManager.js?11217:329 Authenticated w/ Melvor Cloud: true
cloudManager.js?11217:329 Authenticated w/ PlayFab: true
cloudManager.js?11217:329 Checking for valid full version
cloudManager.js?11217:329 Checking for valid TotH purchase
cloudManager.js?11217:329 Checking for valid Atlas of Discovery purchase
cloudManager.js?11217:329 Checking for valid Into the Abyss purchase
cloudManager.js?11217:329 Getting keys from playfab
cloudManager.js?11217:329 Loading Game Data...
cloudManager.js?11217:83 Registered Demo Data.
cloudManager.js?11217:83 Registered Full Version Data.
cloudManager.js?11217:85 Registered Throne of the Herald Data.
cloudManager.js?11217:86 Registered Atlas of Discovery Data.
cloudManager.js?11217:329 Initializing Mod Manager...
cloudManager.js?11217:329 Checking for Mod Updates...
cloudManager.js?11217:329 Loading Mods...
cloudManager.js?11217:329 Loading Local Saves...
cloudManager.js?11217:329 Loading Cloud Saves...
cloudManager.js?11217:329 Getting saves from playfab
cloudManager.js?11217:329 Saves retrieved
characterSelect.js?11217:5 Loading character selection
cloudManager.js?11217:468 Connected to PlayFab successfully
main.js?11217:18 Game Loaded
cloudManager.js?11217:468 Connected to PlayFab successfully
cloud.js?11217:91 updatePlayerTags
game.js?11217:364 Took 2.12960000038147s to run 283 ticks. Average TPS: 132.88880538566252.
cloudManager.js?11217:329 PlayFab save updated successfully
```

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11217

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of version 1.3 (?11262)
