### ISSUE TITLE
[Bug]: Shop Header  is no longer always visible

### ISSUE THREAD

**Issue by MadeOfMagicAndWires** [MelvorIdle/melvoridle.github.io#4308]
### Describe the bug

With the recent UI update the QoL feature where the Shop header is supposed to always be visible which was introduced in v1.2.2 ?8590 seems to have reverted. The Bank tabs header seems not to be affected by this

### Reproduction Steps

0. (Disable mods)
1. Go to the Store
2. Scroll Down
3. Watch the header disappear out of sight 

### Expected behaviour

The Shop header should remain visible while scrolling down, as introduced in v1.2.2 ?8590

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/3438658/320144b1-a55c-4b81-b6a5-57612ebbb204)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11217

### Are you using any mods?

No

**Comment by BelberithBlack** [comment]
Can confirm this is happening on mobile too. Particularly, the android beta.

**Comment by spanhol** [comment]
Bank tabs header are affected on Android app.
I'm on Android 13
