### ISSUE TITLE
[Bug]: Times fled from monster stat is not updating

### ISSUE THREAD

**Issue by psyborg0ne** [MelvorIdle/melvoridle.github.io#4309]
### Describe the bug

All other stats increase normally, but times fled from monster stays at 0. Even through console the value is undefined

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/50668125/0578a490-297b-4698-b782-44ff11b3ffb6)

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/50668125/0e85f752-50b2-49f2-874d-aba12faaf0bd)

### Reproduction Steps

1. Check completion log entry for selected monster.
2. Engage the monster and try to leave either from combat screen > run or from the combat minibar flee icon
3. Check completion log entry again

### Expected behaviour

The 'Times fled from monster' stat should increase accordingly when you perform the steps mentioned in the reproduction section.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [x] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [x] Throne of the Herald
- [x] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11217

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue has been resolved as of version 1.3 (?11262)
