### ISSUE TITLE
[Bug]: Mining doesn't work

### ISSUE THREAD

**Issue by KorumJI** [MelvorIdle/melvoridle.github.io#4315]
### Describe the bug

Mining doesn't work after the update. All mods are disabled. When you click on any ore, nothing happens.

### Screenshots

![2024-06-12_09-41](https://github.com/MelvorIdle/melvoridle.github.io/assets/61777937/12698e28-df84-4ee2-8bed-56898f51eff8)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [x] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11217

### Are you using any mods?

No

**Comment by coolrox95** [comment]
This bug was caused by broken mods for the v1.3 update. Please disable your mods and only re-enable once you have confirmed they are updated.

To fix the NaN issue, please follow these steps: https://www.reddit.com/r/MelvorIdle/comments/1dd3d2a/uhh_anyone_else_seeing_this_for_mastery/l82oxi8/

**Comment by KorumJI** [comment]
I clearly wrote that ALL MODS ARE DISABLED!

**Comment by durron597** [comment]
Opening the game with certain mods enabled permanently breaks your save, even if you turn them off after
