### ISSUE TITLE
[Bug]: Att xp not displayed on welcome back screen

### ISSUE THREAD

**Issue by AustinNotAustin** [MelvorIdle/melvoridle.github.io#4316]
### Describe the bug

After logging back into the game, while fighting a barrier monster, my welcome back screen failed to display my gained attack xp.

### Reproduction Steps

Load save
afk for few seconds
come back
Witness no att xp

### Expected behaviour

Me see xp gained.

I've created 3 reports this patch, but that doesn't degrade from the work. I still love the QoL updates. Thanks dev team!

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/R00ExeuB

### Screenshots

![Screenshot_20240611_220441_Melvor Idle](https://github.com/MelvorIdle/melvoridle.github.io/assets/41271157/0be3fdcd-f93d-4d84-af0d-1afe12807623)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11217

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Your save is in ancient relics mode and has reached the experience/level cap for Attack.

**Comment by AustinNotAustin** [comment]
It is, however, I get the xp/hr from township on another account with max township.

See: https://melvoridle.com/save/WWfcvpPk
![Screenshot_20240612_072832_Melvor Idle](https://github.com/MelvorIdle/melvoridle.github.io/assets/41271157/198d0cb4-6d8a-4d97-be47-35c2e5d22d3a)
![Screenshot_20240612_072838_Melvor Idle](https://github.com/MelvorIdle/melvoridle.github.io/assets/41271157/76bf7711-ad49-4394-8a8b-edd60c92f65e)

**Comment by durron597** [comment]
AR mode doesn't have virtual level progression, standard does
