### ISSUE TITLE
[Bug]: Stronghold swap enhancements while enemy spawning

### ISSUE THREAD

**Issue by muniategui** [MelvorIdle/melvoridle.github.io#4318]
### Describe the bug

I have bought the upgrade to swap items in stronghold. While in undead augmented with the 3 standards the stronghold works perfectly. If i try to swap the enhancement for an augmented one a message appears displaying that i can not change it. However, if this is done while the enemy is spawning, there is no message and you miss 100% of the hits.

Moreover, even failing the hits I can still apply burn to enemies somehow (using cloudburst staff)

I am using mods however can reproduce without them.

### Reproduction Steps

1. Enter stronghold augmented level with standard enhancements
2. Try to swap standard enhancement for an augmented one while fighting enemy
3. While the enemy is spawning, swap one enhancement for an augmented one
4. Check how all the hits are missed

### Expected behaviour

Or you can not swap them while enemy spawning since you need them to fight in stronghold so preventing the swap would be understandable or upgraded versions of enchantments do not restrict previous stronghold levels (if developer wants to add the feature)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11265

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11330)
