### ISSUE TITLE
[Bug]: Mastery pool displaying as 'NaN%'

### ISSUE THREAD

**Issue by JeiceQuintero** [MelvorIdle/melvoridle.github.io#4319]
### Describe the bug

Crafting page displays mastery pool and red d-hide body mastery as "NaN%", when I had over 100% previously using the 'mastery pool can overflow' mod. The mod has been updated for version 1.3. This occurred when I pressed 'claim token' on some crafting mastery tokens in the bank, when the crafting mastery pool was already over 100%. I no longer get mastery pool bonuses for crafting, and the crafting token value in the bank is also 'NaN'.
![Screenshot_20240612_184440_Melvor Idle](https://github.com/MelvorIdle/melvoridle.github.io/assets/172486427/da9fdc0a-364a-41bf-b893-1e21f86f9b24)

### Expected behaviour

I expected an error to pop up when trying to claim the token, and for nothing to happen.

### Screenshots

![Screenshot_20240612_184440_Melvor Idle](https://github.com/MelvorIdle/melvoridle.github.io/assets/172486427/a9aa9fb5-f4f8-487e-9e75-96d88435e212)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11265

### Are you using any mods?

Yes

**Comment by durron597** [comment]
These NaN issues are caused by loading the game with broken mods. See [the discord message with instructions.](https://discord.com/channels/625838709203271680/625840209531240469/1249951088136814603)

**Comment by coolrox95** [comment]
This bug was caused by broken mods for the v1.3 update. Please disable your mods and only re-enable once you have confirmed they are updated.

To fix the NaN issue, please follow these steps: https://www.reddit.com/r/MelvorIdle/comments/1dd3d2a/uhh_anyone_else_seeing_this_for_mastery/l82oxi8/
