### ISSUE TITLE
water expert wizard gear

### ISSUE THREAD

**Issue by Misfit42069** [MelvorIdle/melvoridle.github.io#432]
**Describe the bug**
the level requirement for the water expert wizard gear requires 65 magic in the milestone menu but when I made the item it said it requires 69 magic 

**To Reproduce**
1. click on water expert wizard gear in bank
2. click on magic milestone tab

**Expected behavior**
im expecting the number in milestone to change from 65 to 69

**Screenshots**
![2020-10-02 (1)](https://user-images.githubusercontent.com/72289036/94981967-c2bb6080-0504-11eb-9e8c-1a7604f1c771.png)

![2020-10-02 (2)](https://user-images.githubusercontent.com/72289036/94981971-d36bd680-0504-11eb-9aaa-33905dd55827.png)

**Browser**
google chrome

**Console output**
Please open the console by pressing F12 and copy it [here.]

**Are you using any scripts?**
nope

**Comment by MelvorIdle** [comment]
Fixed in the coming update :)
