### ISSUE TITLE
[Bug]: cannot select +skill max level in Ancient Relic mode

### ISSUE THREAD

**Issue by xvain** [MelvorIdle/melvoridle.github.io#4320]
### Describe the bug

The "level up" button (when you have skill level up that have not used) disappeared

### Reproduction Steps

1. finish a dungeon, save and don't spend the level up (before today's update)
2. update to latest version
3. you can't access the level up

### Expected behaviour

able to access the level up menu

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/9iMTuBC3

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/4558091/df3038ea-0604-471f-af22-c9f795444edd)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11265

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11330)
