### ISSUE TITLE
[Bug]: Renderer error in astrology on latest release using fresh character and no mods

### ISSUE THREAD

**Issue by RealCyberkraken** [MelvorIdle/melvoridle.github.io#4321]
### Describe the bug

I was taking a little peek around the new update on a completely new unmodded character in update 1.3 just now and I went into the astrology skill and pressed the explore button on the Deedree astrology constellation to see what UI changes were made there and then pressed the "go back" button and got the below error report, I tried clicking off the error to get back to poking around the UI of the update but the error immediately popped back up again, please be aware I am on Garuda Linux running steam native

Error report:

An error occurred while rendering:
Error Name: Error
Error Message: Tried to get active constellation, but none is being studied.
Stack Trace:
Error: Tried to get active constellation, but none is being studied.
    at get activeConstellation [as activeConstellation] (https://steam.melvoridle.com/assets/js/built/astrology.js?11271:53:7)
    at Astrology.renderProgressBar (https://steam.melvoridle.com/assets/js/built/astrology.js?11271:133:69)
    at Astrology.render (https://steam.melvoridle.com/assets/js/built/astrology.js?11271:131:30)
    at https://steam.melvoridle.com/assets/js/built/game.js?11271:304:63
    at Map.forEach (<anonymous>)
    at NamespaceRegistry.forEach (https://steam.melvoridle.com/assets/js/built/namespaceRegistry.js?11271:50:44)
    at Game.render (https://steam.melvoridle.com/assets/js/built/game.js?11271:304:39)
    at Game.loop (https://steam.melvoridle.com/assets/js/built/game.js?11271:335:35)

Active Action: undefined
Current Equipment:

No Active Action Information

Modding Enabled. Loaded mods:

### Reproduction Steps

See above

### Expected behaviour

To be able to close the explore section of an astrology constellation without getting an error dialog let alone one I can't close

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

Latest as of the time of this report

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11330)
