### ISSUE TITLE
[Bug]: Strength XP gain shows incorrectly in Barbarian Fishing

### ISSUE THREAD

**Issue by SomeoneSom** [MelvorIdle/melvoridle.github.io#4323]
### Describe the bug

The amount of Strength XP you'll gain from a fish in Barbarian Fishing shows as `${qty} ${skillName} Skill XP`/`${qty} Base ${skillName} XP`.

### Reproduction Steps

1. Equip Barbarian Gloves.
2. Hover over the Strength icon on one of the Barbarian Fishing fish.

### Expected behaviour

The (probably) intended behavior is for the `${qty}` template to resolve to the amount of Strength XP you'll gain per fish, and the `${skillName}` template to just resolve to `Strength`.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/52360990/6df3018f-15c8-4d51-b8c2-b0dce9419dbe)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11271

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11330)
