### ISSUE TITLE
[Bug]: Can't equip Gods Enhancementt 2 (Augmented)

### ISSUE THREAD

**Issue by Fortuon** [MelvorIdle/melvoridle.github.io#4324]
### Describe the bug

Can't equip Gods Enhancementt 2 (Augmented) while inside the Augmented Stronghold of the Gods to replace the non Augmented version of the same enhancement. I had bought the shop purchase that enables equipment swapping while inside a stronghold. I was able to equip the Gods Enhancementt 1 (Augmented).

### Reproduction Steps

in description

### Expected behaviour

To be able to equip the Augmented version.

### Screenshots

![Melvor_Idle_bug_1](https://github.com/MelvorIdle/melvoridle.github.io/assets/172500804/ebf2e4b2-76ff-4bfd-9102-b8638f703817)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11271

### Are you using any mods?

Yes

**Comment by durron597** [comment]
This is expected behavior, you aren't supposed to use the augmented version in the stronghold until you go to the superior tier.

[See Malcs statement to this effect in the discord](https://discord.com/channels/625838709203271680/625840209531240469/1250071889968365598)

**Comment by Fortuon** [comment]
Okay thanks for the clarification! Just assumed you should be able to use the "better" ones with no knowledge.
