### ISSUE TITLE
[Bug - ancient relics mining 

### ISSUE THREAD

**Issue by Balthuzarrrr** [MelvorIdle/melvoridle.github.io#4327]
### Describe the bug

Since the latest update when you are mining pure essence with all relics found it no longer produces coal. Please fix ASAP

### Reproduction Steps

Have all relics for mining. Play relic mode. Mine pure essence.

### Expected behaviour

To receive coal when mining pure essence 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

V1.3 (? 11271)

### Are you using any mods?

No

**Comment by muniategui** [comment]
As far as i know essence does not count as an ore, and the ancient relic states that the coal is dropped in ore veins
