### ISSUE TITLE
[Bug]: Pool progress bar says "Skill XP"

### ISSUE THREAD

**Issue by durron597** [MelvorIdle/melvoridle.github.io#4329]
### Describe the bug

The pool progress bar says Skill when it should be "Pool XP" or "Mastery XP" or something.

### Reproduction Steps

1. Go to any non-combat skill
2. Look at pool bar. It says Skill XP

### Expected behaviour

I would expect the template to be using a template that uses Pool instead of explicitly skill. Here's the code that needs to change:

```
class MasteryPoolDisplayElement extends HTMLElement {
    /* snip */
    createRealmDisplay() {
        /* snip */
        const xpSpan = createElement('span');
        /* snip */
        xpSpan.append(currentXP, ' / ', totalXP, ' (', percentXP, ')');
        /* THIS TEMPLATE DOES NOT SEEM TO INDICATE POOL SPECIFIC TEXT */
        labelContainer.append(...templateLangStringWithNodes('MENU_TEXT_XP_AMOUNT', {
            xp: xpSpan
        }, {}, false));
        return {
            /* snip */
        };
    }
}
```

### Screenshots

![skill_not_pool](https://github.com/MelvorIdle/melvoridle.github.io/assets/502260/cd07c795-01e6-4a8e-94e7-773eac662ab4)

### Console output

![console_skill](https://github.com/MelvorIdle/melvoridle.github.io/assets/502260/8df676d8-b03b-4e04-8c6a-0fc0407c089e)

```
templateLangStringWithNodes('MENU_TEXT_XP_AMOUNT', { xp: createElement('span') }, {}, false);
(3) ['', span, ' Skill XP']
```

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11271

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11330)
