### ISSUE TITLE
Alt Magic - Combo Runes Dont Work Offline

### ISSUE THREAD

**Issue by Erico9002** [MelvorIdle/melvoridle.github.io#433]
I've only tested with superheat so far, but if you are relying on using combination runes for offline alt magic training, it attempts to use your regular non-combination runes. If you have 0 Earth runes, and have the button clicked to use combination runes in order to exhaust your lava runes, when you close tab and reopen you will have gained 0 experience due to "lacking runes," since it attempts to use earth and fire instead of lava.

**Comment by MelvorIdle** [comment]
Fixed in the upcoming update :)
