### ISSUE TITLE
[Bug]: Rune Cost Reduction Bug with Battlestaves in Version 1.3(?11271)

### ISSUE THREAD

**Issue by horaceli91** [MelvorIdle/melvoridle.github.io#4330]
### Describe the bug

System Information:

Operating System: Mac (Steam)
Game Version: 1.3 (?11271)
Bug Description:
In the Alternative Magic section, when equipping any Battlestaves, there is an issue with Rune Cost Reduction. All reductions are applied correctly, but the rune consumption cannot be reduced to 0; the minimum is always 1. For example, the spell Item Alchemy II normally requires 1 Nature Rune and 4 Fire Runes. After equipping a Fire Battlestaff (which provides a 5 Fire Rune reduction), it still indicates that 1 Fire Rune is needed. This issue did not exist before the 1.3 update.

### Reproduction Steps

1. Go to the Alternative Magic section.
2. Select the spell Item Alchemy II.
3. Equip a Fire Battlestaff.
4. Check the rune consumption.

### Screenshots

![123](https://github.com/MelvorIdle/melvoridle.github.io/assets/42882477/276a866b-ab27-4f28-bbb3-1494cfffad73)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11271

### Are you using any mods?

Yes

**Comment by durron597** [comment]
This is expected behavior, in previous versions, this was a bug.

> * Fixed Rune Costs being able to go below 1.

[Patch notes](https://news.melvoridle.com/upcoming-v1-3-changlog-need-to-knows/)
