### ISSUE TITLE
[Bug]: 5 smithing relic bonus doesn't work

### ISSUE THREAD

**Issue by Vendesum** [MelvorIdle/melvoridle.github.io#4331]
### Describe the bug

When you get 5 smithing relics, you should not use coal at all, but it still uses it after updating to new version.

### Reproduction Steps

Play relics, get 5 total smithing relics, smith any bar.

### Expected behaviour

No coal used.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11271

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11330)
