### ISSUE TITLE
[Bug]: NaN gp

### ISSUE THREAD

**Issue by Mrrjokerftw** [MelvorIdle/melvoridle.github.io#4335]
### Describe the bug

All of my gold has gone to NaN, I had 33b gp that is no longer there and I cannot spend/use. I also have a thieving token in my bank that says 0 on it, so it can not be sold or used. 

### Expected behaviour

I expect the gp to be back on my save. Worst case my gold to be reset and I will ground up the gold.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/LM0kderG

### Screenshots

[
![IMG_1475](https://github.com/MelvorIdle/melvoridle.github.io/assets/172580206/3e0d09a8-0edb-4635-8d87-204475774602)
]

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

11302

### Are you using any mods?

Yes

**Comment by arugad** [comment]
Me too, and I have the same problem for the Slayer Coins
I tried turning off all mods and clearing the cache, but it still didn't work.

**Comment by Mrrjokerftw** [comment]
Yeah, I disabled them all and cleared my cache too, still not able to get rid of NaN. It’s stopping me from earning any additional gold so I essentially cannot play.

**Comment by Mrrjokerftw** [comment]
Found resolution of discord under desktop fixes, below:

Same as the MXP console steps but use this command instead

```js
game.gp.set(69);
```

Change `69` to q/w it was and also disable mods until you figure out which one is breaking it
