### ISSUE TITLE
[Bug]: Summon experience using summon tablets wrongly calculated (At least in agility)?

### ISSUE THREAD

**Issue by muniategui** [MelvorIdle/melvoridle.github.io#4339]
### Describe the bug

I am leveling up agility with eagle + monkey + agility obstacles to reduce intervals.

I have some obstacles that reach speed of 0.25 some others of 1-3 seconds.

The fun fact is that all of them are giving me 41 summoning experience points.

As far as i know the longer the duration the more experience, and if i remember properly i was earning far less experience especiallly in the 0.25 seconds obstacles.

### Reproduction Steps

1. Equip eagle + monkey
2. Use agility obstacles and check summoning experience earned
3. Reduce interval with lesser relic, obstacles that reduce agility interval, potions...
4. Check that the earned experience is the same

### Expected behaviour

To earn a properly calculated experience. Probably the 0.25 is wrongly calculated and is giving too much experience? Maybe the longer ones are giving too little if the 0.25 are properly calculated?

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11313

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11375)
