### ISSUE TITLE
[Bug]: Slayer Blinding Scroll works wrongly.

### ISSUE THREAD

**Issue by shenao1003** [MelvorIdle/melvoridle.github.io#4340]
### Describe the bug

Now the effect of Slayer Blinding Scroll is:
-10% Enemy Global Evasion Rating

### Reproduction Steps

1.Select a monster to fight.
2.Equip Slayer Blinding Scroll.
3.Enemy Global Evasion Rating decrease by 10%.

### Expected behaviour

The correct effect of Slayer Blinding Scroll should be:
-10% Enemy Accuracy Rating

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11321

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11375)
