### ISSUE TITLE
[Bug]: Missing modifier sources in Cartography

### ISSUE THREAD

**Issue by Voscor** [MelvorIdle/melvoridle.github.io#4341]
### Describe the bug

XP and action time tooltips don't show reduction sources in Cartography

### Reproduction Steps

1. Go to Cartography
2. Start surveying anything or start creating paper or upgrading maps
3. Hover over XP per action or action time

### Expected behaviour

It should show sources of XP increase and action time reduction (like any other skill)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11330

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11375)
