### ISSUE TITLE
Not getting notification for abyssal slayer coins

### ISSUE THREAD

**Issue by durron597** [MelvorIdle/melvoridle.github.io#4342]
### Describe the bug

I'm definitely getting abyssal slayer coins, but not getting notification. I have confirmed that the setting is on.

https://github.com/MelvorIdle/melvoridle.github.io/assets/502260/998a958e-953a-4790-8a60-95ddacbce944

### Reproduction Steps

1. Select abyssal slayer task
2. Kill task enemy
3. See that no notification on kill 
4. See coins in sidebar

### Expected behaviour

I should see an abyssal coin notification 

### Screenshots

Settings screenshot
![IMG_9467](https://github.com/MelvorIdle/melvoridle.github.io/assets/502260/36a312af-8dac-43b2-8231-a861f07c73d5)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11330

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11375)
