### ISSUE TITLE
[Bug]: Skill Tree Points can be missed in Adventure Mode by increasing Abyssal XP over Level Cap

### ISSUE THREAD

**Issue by randy1212** [MelvorIdle/melvoridle.github.io#4346]
### Describe the bug

not exactly sure how but some of my skills are missing skill points to not be able to max tree, I think the cause is from skilling over the abyss cap before you raise the cap

### Reproduction Steps

skilling over the abyss cap before you raise the cap in 

### Expected behaviour

I think maybe I am wrong, but every skill tree can be maxed?

### Screenshots

![mel1](https://github.com/MelvorIdle/melvoridle.github.io/assets/31143890/5a368e13-a6d5-4642-a957-6949bce12d9b)
![mel2](https://github.com/MelvorIdle/melvoridle.github.io/assets/31143890/c54d752d-fd4a-4f71-8e61-73f15c501ae4)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11330

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11375)
