### ISSUE TITLE
Mining tokens can get applied to 99 skills and get used up.

### ISSUE THREAD

**Issue by Brad-Cole** [MelvorIdle/melvoridle.github.io#435]
**Describe the bug**
Mining tokens can get applied to skills that are already at 99 mastery and get used up.

**To Reproduce**
I checked this today by stopping activity. I had 16 mining tokens and took a screenshot of my current mastery levels of which only 4 are not at 99. After using the 16 tokens i had only gained 7 levels. I've also noticed this when using single tokens.

**Expected behavior**
I would think if a token is used it should either check for a skill not at 99 or if it does land on a skill that is at 99 it should not consume the token.

**Browser**
Chrome

**Are you using any scripts?**
no

**Comment by MelvorIdle** [comment]
This is not a bug. The game also tells you that the token was used on a 99, so nothing happened.
