### ISSUE TITLE
[Not a Bug]: Ability to disable Discord RPC in the settings

### ISSUE THREAD

**Issue by Founntain** [MelvorIdle/melvoridle.github.io#4350]
### Describe the bug (not a bug, more an annoyance)

New setting in the settings to give players the ability to disable the Discord-RPC completely.

Reason for this is, that I and many other players leave the game open in the background while playing other stuff and hiding other games they actually play. 
> *This was mentioned in #3768 in a different way, but is now marked as stale.*

However my issue is, that there should be a simple toggle in the settings to disable the Discord-RPC completely so Melvor doesn't hide actual games that are played when it runs in the background.

### Expected behaviour

Add a toggle to the settings to give users the option to disable the Discord-RPC completely

### Which platforms are you experiencing this bug on?

- [X] Steam

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11375

### Are you using any mods?

Yes (not relevant)

**Comment by WitheredRose7** [comment]
How is it not a bug? It's the only game that I know of that hides other games whenever it comes into focus, despite being toggled off in discord activity. Moreover despite being toggled off it also shows on profile activity whenever it's launched after discord, reloading discord or launching it after the game makes it not appear on profile's acitivity.
