### ISSUE TITLE
[Bug]: Summoning Abyssal Marks not showing Level Req

### ISSUE THREAD

**Issue by Grizzalbee** [MelvorIdle/melvoridle.github.io#4352]
### Describe the bug

Summoning skill, Abyssal Marks screen only (not on Abyssal Tablets/Familiars). All Marks show up as if the minimum Abyssal Summoning Level has already been achieved. Contrast to Melvor Realm shows "Requires level N" as does Abyssal Tablets/Familiars page.

### Expected behaviour

Would expect consistent display behavior, may be confusing to players who don't go look at the Abyssal Tablets/Familiars page and see that they can't actually discover those marks yet.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/8880784/13680269-809a-4f0e-998c-418142bba410)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/8880784/860dee33-f3bd-4b60-9dd9-ecd99b3cc3c3)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/8880784/9f3a68b0-948f-4dd6-8bcc-75cf80aa46a0)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11390

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11431)
