### ISSUE TITLE
Mastery stuck at “NaN%”

### ISSUE THREAD

**Issue by KBo91** [MelvorIdle/melvoridle.github.io#4356]
### Describe the bug

Had mastery can overflow mod turned on prior to update for expansion. Mastery percentage was well over standard pool amount, but now is stuck at NaN% even with mod disabled. All mastery perks in farming are also disabled and unable to be reattained.

### Expected behaviour

Request for mastery on farming skill to be reset

### Screenshots

![IMG_4226](https://github.com/MelvorIdle/melvoridle.github.io/assets/24508809/d76807c3-f40b-4e01-92d6-4bcad8735e1a)
![IMG_4227](https://github.com/MelvorIdle/melvoridle.github.io/assets/24508809/451f87a7-36cf-4f82-bba5-340eb3c1e5c6)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11392

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
This bug was caused by broken mods for the v1.3 update. Please disable your mods and only re-enable once you have confirmed they are updated.

To fix the NaN issue, please follow these steps: https://www.reddit.com/r/MelvorIdle/comments/1dd3d2a/uhh_anyone_else_seeing_this_for_mastery/l82oxi8/
