### ISSUE TITLE
[Bug]: Synergy Fox + Ent does only use one fox

### ISSUE THREAD

**Issue by Alurian-ux** [MelvorIdle/melvoridle.github.io#4359]
### Describe the bug

When creating the Fox,  using the synergy Fox + Ent, only one Fox gets used instead of 2 Fox and 1 Ent.
You still get the synergy bonus and exp though.

### Reproduction Steps

1. Go to summoning
2. Create Foxes
3. Select synergy Fox + Ent
4. Check synergy to see that only one fox gets used

### Expected behaviour

2 foxes and 1 ent to be used when creating fox tablets with this synergy

### Console output

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/74683784/207740ba-053d-420d-a762-db7ec7640392)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

<11392

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11431)
