### ISSUE TITLE
[Bug]: Dragons Den chests lost items

### ISSUE THREAD

**Issue by Smetana69** [MelvorIdle/melvoridle.github.io#4364]
### Describe the bug

I grinded 50 chests from dragons den and proceeded to open them, Of all the 50 rewards only 5 vambraces and 1 body appeared in my bank.

### Reproduction Steps

1. go to dragons den and clear it 50 times
2. open 50 elder chests
3. get scammed :(

### Expected behaviour

I expected to get 50 chests worth of items.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11392

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Please ensure this setting is disabled 
![image](https://github.com/user-attachments/assets/100fb4fe-c1b3-4187-a195-50192a48f69c)
