### ISSUE TITLE
[Bug]: Firemaking log selection isn't updated on level up

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#4367]
### Describe the bug

When leveling up in Firemaking, the unlock requirement is not updated in the log selection dropdown. This is a visual bug and the log can be selected.

### Reproduction Steps

1. Set yourself to level 9 `game.firemaking.setXP(exp.levelToXP(10))`
2. Burn 1 log
3. Look at Oak Logs in the log selection

### Expected behaviour

Upon leveling up, the log selection menu should be updated.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/f80f124e-ab49-455b-87a5-b04511888726)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11392

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11431)
