### ISSUE TITLE
[Bug]: Melvor Realm Passive cooking not gaining Melvor Realm XP while Active Abyssal Cooking

### ISSUE THREAD

**Issue by Rill-I-Am** [MelvorIdle/melvoridle.github.io#4372]
### Describe the bug

When actively cooking Crimson Biter and passively cooking Apple Pie and Hearty soup I gain no Melvor Realm XP or Mastery XP (Pool and item). The passively cooked items are still cooked however and uses resources and gives cooked product.

### Reproduction Steps

1. Actively cook Crimson Biter on Spruce Cooking Firm.
2. Passively cook Apple Pie on Corundum Furnance.
3. Passively Cook Hearty Soup in Magic Pot.
4. See Abyssal Realm experience gain only, while Melvor Realm experience or mastery experience doesn't increase.

### Expected behaviour

I expected to gain experience in both Melvor and Abyssal Realms. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11392

### Are you using any mods?

No

**Comment by Ayarez** [comment]
Passive cooking never gave experience or mastery, only items
