### ISSUE TITLE
[Bug]: Mastery XP hover over shows benefits from logs no matter the skill

### ISSUE THREAD

**Issue by heavyhuntr** [MelvorIdle/melvoridle.github.io#4373]
### Describe the bug

When you hover over the mastery xp gained from any action it shows that your mastery xp is increased because of your mastery of logs, I believe these masteries are coming from the Firemaking skill.

### Reproduction Steps

1. Go to any skill (except Firemaking)
2. Hover over the Mastery XP you get from the skill
3. See that the Mastery XP modifiers are shown as the logs mastery

### Expected behaviour

Mastery XP should be modified by the masteries of the relevant skill being trained and not from Firemakings masteries.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/23704821/63c9054c-d3c6-4f77-9130-b5f897e7b903)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/23704821/99ff2a88-d74b-42e4-bdcb-0c0544a27eb5)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/23704821/94b813e4-e0f7-4db4-9f9e-ce8cefb162c5)

### Console output

index_game.php:5 
        
        
       GET https://plausible.io/js/script.js net::ERR_BLOCKED_BY_CLIENTUnderstand this error
index_game.php:41 
        
        
       GET https://melvoridle.com/style.css?2 net::ERR_ABORTED 404 (Not Found)Understand this error
index_game.php:4109 
        
        
       GET https://static.cloudflareinsights.com/beacon.min.js/vcd15cbe7772f49c399c6a5babf22c1241717689176015 net::ERR_BLOCKED_BY_CLIENTUnderstand this error
cloudManager.js?11392:329 Silent Sign in with JWT
cloudManager.js?11392:329 Validating Melvor Cloud token
cloudManager.js?11392:329 Storing Melvor Cloud Token
cloudManager.js?11392:329 Initializing PlayFab login. Method: customID
cloudManager.js?11392:329 Logging in with Custom ID via PlayFab
cloudManager.js?11392:329 Login with custom ID success
cloudManager.js?11392:329 Getting account info
cloudManager.js?11392:329 Account info retrieved
cloudManager.js?11392:329 Authenticated w/ Melvor Cloud: true
cloudManager.js?11392:329 Authenticated w/ PlayFab: true
cloudManager.js?11392:329 Checking for valid full version
cloudManager.js?11392:329 Checking for valid TotH purchase
cloudManager.js?11392:329 Checking for valid Atlas of Discovery purchase
cloudManager.js?11392:329 Checking for valid Into the Abyss purchase
cloudManager.js?11392:329 Getting keys from playfab
cloudManager.js?11392:329 Loading Game Data...
cloudManager.js?11392:83 Registered Demo Data.
cloudManager.js?11392:83 Registered Full Version Data.
cloudManager.js?11392:85 Registered Throne of the Herald Data.
cloudManager.js?11392:86 Registered Atlas of Discovery Data.
cloudManager.js?11392:87 Registered Into the Abyss Data.
cloudManager.js?11392:329 Initializing Mod Manager...
cloudManager.js?11392:329 Checking for Mod Updates...
cloudManager.js?11392:329 Loading Mods...
cloudManager.js?11392:329 Loading Local Saves...
cloudManager.js?11392:329 Loading Cloud Saves...
cloudManager.js?11392:329 Getting saves from playfab
cloudManager.js?11392:329 Saves retrieved
characterSelect.js?11392:5 Loading character selection
cloudManager.js?11392:468 Connected to PlayFab successfully
utils.js?11392:253 Tried to format non-number.
numberWithCommas @ utils.js?11392:253
updateValues @ masteryDisplays.js?11392:7
(anonymous) @ skill.js?11392:447
updateMasteryDisplays @ skill.js?11392:447
(anonymous) @ skill.js?11392:364
renderActionMastery @ skill.js?11392:364
render @ skill.js?11392:359
render @ skill.js?11392:518
render @ artisanSkill.js?11392:23
onLoad @ artisanSkill.js?11392:15
(anonymous) @ game.js?11392:284
forEach @ namespaceRegistry.js?11392:50
onLoad @ game.js?11392:284
(anonymous) @ main.js?11392:12
(anonymous) @ nativeManager.js?11392:5
__awaiter @ nativeManager.js?11392:2
updateWindow @ main.js?11392:5
(anonymous) @ main.js?11392:83
(anonymous) @ nativeManager.js?11392:5
__awaiter @ nativeManager.js?11392:2
onSaveDataLoad @ main.js?11392:83
(anonymous) @ save.js?11392:140
fulfilled @ nativeManager.js?11392:2Understand this warning
utils.js?11392:253 Tried to format non-number.
numberWithCommas @ utils.js?11392:253
updateValues @ masteryDisplays.js?11392:7
(anonymous) @ skill.js?11392:447
updateMasteryDisplays @ skill.js?11392:447
(anonymous) @ skill.js?11392:364
renderActionMastery @ skill.js?11392:364
render @ skill.js?11392:359
render @ skill.js?11392:518
render @ artisanSkill.js?11392:23
render @ summoning.js?11392:74
onLoad @ artisanSkill.js?11392:15
onLoad @ summoning.js?11392:72
(anonymous) @ game.js?11392:284
forEach @ namespaceRegistry.js?11392:50
onLoad @ game.js?11392:284
(anonymous) @ main.js?11392:12
(anonymous) @ nativeManager.js?11392:5
__awaiter @ nativeManager.js?11392:2
updateWindow @ main.js?11392:5
(anonymous) @ main.js?11392:83
(anonymous) @ nativeManager.js?11392:5
__awaiter @ nativeManager.js?11392:2
onSaveDataLoad @ main.js?11392:83
(anonymous) @ save.js?11392:140
fulfilled @ nativeManager.js?11392:2Understand this warning
main.js?11392:18 Game Loaded
cloudManager.js?11392:468 Connected to PlayFab successfully
cloud.js?11392:91 updatePlayerTags
game.js?11392:365 Took 1.9173999999761582s to run 257 ticks. Average TPS: 134.03567330927072.
utils.js?11392:253 Tried to format non-number.
numberWithCommas @ utils.js?11392:253
updateValues @ masteryDisplays.js?11392:7
(anonymous) @ skill.js?11392:447
updateMasteryDisplays @ skill.js?11392:447
(anonymous) @ skill.js?11392:364
renderActionMastery @ skill.js?11392:364
render @ skill.js?11392:359
render @ skill.js?11392:518
render @ harvesting.js?11392:39
(anonymous) @ game.js?11392:305
forEach @ namespaceRegistry.js?11392:50
render @ game.js?11392:305
loop @ game.js?11392:336
setInterval (async)
startMainLoop @ game.js?11392:255
(anonymous) @ main.js?11392:85
fulfilled @ nativeManager.js?11392:2
Promise.then (async)
step @ nativeManager.js?11392:4
fulfilled @ nativeManager.js?11392:2
Promise.then (async)
step @ nativeManager.js?11392:4
(anonymous) @ nativeManager.js?11392:5
__awaiter @ nativeManager.js?11392:2
onSaveDataLoad @ main.js?11392:83
(anonymous) @ save.js?11392:140
fulfilled @ nativeManager.js?11392:2Understand this warning
cloudManager.js?11392:329 PlayFab save updated successfully
game.js?11392:365 Took 0.057299999982118606s to run 15 ticks. Average TPS: 261.7801047937346.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11392

### Are you using any mods?

No

**Comment by Flurryous** [comment]
Unless I misread, I believe those log masteries are the bonus global mastery xp you get from having 99 fm mastery in those logs.

**Comment by heavyhuntr** [comment]
> Unless I misread, I believe those log masteries are the bonus global mastery xp you get from having 99 fm mastery in those logs.

I don't see this documented anywhere, can you point me in the right direction if that's the case? As I only see the 95% Firemaking mastery checkpoint for 5% Global Mastery XP in Melvor Realm, but this is in Abyssal Realm as well.

**Comment by 04Slash** [comment]
A log will give 0.25% Global Mastery XP when it has reached mastery level 99.
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/e49c95ed-66fb-4226-9293-18efad8215bb)

**Comment by heavyhuntr** [comment]
> A log will give 0.25% Global Mastery XP when it has reached mastery level 99. ![image](https://private-user-images.githubusercontent.com/57328541/340058346-e49c95ed-66fb-4226-9293-18efad8215bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MDMyNTgsIm5iZiI6MTcxODUwMjk1OCwicGF0aCI6Ii81NzMyODU0MS8zNDAwNTgzNDYtZTQ5Yzk1ZWQtNjZmYi00MjI2LTkyOTMtMThlZmFkODIxNWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDAxNTU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmMmE4MGRkNmUyMmEzODRjNTFjY2UzMzczNDIwNzM1YmE0YmQzODhiYWRhNTVhNzhmNzhjYWVkYTRhY2JlNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UhgbxM3ohzEObJBpxQyeh5YQbH9aKz7k3z6QewBsA_4)

Thanks, but can you tell me where I can see that information? I can't find it in any Firemaking menu.

**Comment by euanduffy** [comment]
![image_2024-06-16_175242070](https://github.com/MelvorIdle/melvoridle.github.io/assets/146883962/b6794691-d32a-4241-9d2c-90c6db4d3a92)
![image_2024-06-16_175223432](https://github.com/MelvorIdle/melvoridle.github.io/assets/146883962/9dc84c55-b0c2-4681-b048-fc27b328f888)

You just need to click the trophy, it is in the expandable menu at the bottom right of the skill page

**Comment by euanduffy** [comment]
Although not a bug maybe it would be better to add them all up and display as something like "Log Masteries: +X.XX%" to reduce the clutter?

**Comment by heavyhuntr** [comment]
> ![image_2024-06-16_175242070](https://private-user-images.githubusercontent.com/146883962/340119111-b6794691-d32a-4241-9d2c-90c6db4d3a92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NjUyMzEsIm5iZiI6MTcxODU2NDkzMSwicGF0aCI6Ii8xNDY4ODM5NjIvMzQwMTE5MTExLWI2Nzk0NjkxLWQzMmEtNDI0MS05ZDJjLTkwYzZkYjRkM2E5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQxOTA4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmUyOThmOTdjODgzOTYxNjViNzExOWU3M2EyZTgxMmE1MmIyNDg3N2U3NzI5OGQ2MThhNTQxN2VhZTIxZTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EdzFM2YfRNpAKlRs2M0_8VaxhbEqdfTsGnsELv_qDZw) ![image_2024-06-16_175223432](https://private-user-images.githubusercontent.com/146883962/340119098-9dc84c55-b0c2-4681-b048-fc27b328f888.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NjUyMzEsIm5iZiI6MTcxODU2NDkzMSwicGF0aCI6Ii8xNDY4ODM5NjIvMzQwMTE5MDk4LTlkYzg0YzU1LWIwYzItNDY4MS1iMDQ4LWZjMjdiMzI4Zjg4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQxOTA4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Y2E4OWRmMjBlODI2YjU4ZGJlYWM1OTJiMDg2ZWJiMTVlMDFlZmI2OGUzOWQ1Zjk4NDllZGJkYmJhYWEwMDZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HFsI7QWfVc56OUy2-XAF4pbAmWJwoHIXZNc_KCK1-vk)
> 
> You just need to click the trophy, it is in the expandable menu at the bottom right of the skill page

Aha! Thank you! It didn't even cross my mind to click there, my bad.



> Although not a bug maybe it would be better to add them all up and display as something like "Log Masteries: +X.XX%" to reduce the clutter?

That would be great, hopefully Malcs sees this idea, right now it's annoying to sort through especially since those are the top of the list and there's so many.

Guess I'll close this issue, and hope they still see the suggestion.
