### ISSUE TITLE
[Bug]: Museum donation reverted

### ISSUE THREAD

**Issue by Warw-ck** [MelvorIdle/melvoridle.github.io#4374]
### Describe the bug

My character has the golden trowel. When donating misc leftover generic artifacts, I noticed I was 270/271. The mermaid pendant shows as (?) despite having donated one previously and having another in my bank. I think this was my 271th artifact initially, maybe relevant.

### Expected behaviour

Should still be 271/271

### Screenshots

![Melvor_Idle_gXZOxwq4WZ](https://github.com/MelvorIdle/melvoridle.github.io/assets/172940475/632b74a3-c37d-4019-8d98-0bd11978b060)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11392

### Are you using any mods?

Yes

**Comment by Flurryous** [comment]
The 1.3 update removed the merman pendant from the digsite's drop pool and replaced it with a merman pendant piece. The museum did not retroactively include that item if you donated the pendant prior to the patch, so you would need to find that piece and donate it.
