### ISSUE TITLE
[Bug]: NaN for mastery progress in multiple skills

### ISSUE THREAD

**Issue by GabberTitan** [MelvorIdle/melvoridle.github.io#4378]
### Describe the bug

When the new update launched on June 11th, it changed the status of my overall mastery progress to NaN. According to my progress, the fishing and farming skills show NaN/1386 (NaN%) and  NaN/1188 (NaN%), respectively. I am able to access the "View Checkpoints" and "Spend Mastery Pool XP" windows, in which the latter shows NaN for some, but not all, resources (Fishing only has the Raw Mystic Shark NaN while Farming has plenty more). 

I used multiple mods prior to the update without issue, including ones that influence masteries for skilling. I initially loaded my save file with mods enabled when the new update dropped. After disabling all my mods with the new update, the problem still persists.

### Reproduction Steps

Not applicable

### Expected behaviour

Masteries showing up in regular numbers or percentages.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/5eonesQj

### Screenshots

![Capture1232](https://github.com/MelvorIdle/melvoridle.github.io/assets/78278499/9839bebd-0b4a-403a-a945-9bc9012f872b)
![Capture1234](https://github.com/MelvorIdle/melvoridle.github.io/assets/78278499/5f1e0778-ebe8-45bc-ab9c-961d23e3a2be)
![Capture1235](https://github.com/MelvorIdle/melvoridle.github.io/assets/78278499/e9937c90-588a-4476-aae7-c62a828cbd5b)
![Capture1236](https://github.com/MelvorIdle/melvoridle.github.io/assets/78278499/ac17f7df-a196-475d-a46d-a9426d2cfd90)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11410

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This bug was caused by broken mods for the v1.3 update. Please disable your mods and only re-enable once you have confirmed they are updated.

To fix the NaN issue, please follow these steps: https://www.reddit.com/r/MelvorIdle/comments/1dd3d2a/uhh_anyone_else_seeing_this_for_mastery/l82oxi8/
