### ISSUE TITLE
Making tablets unaffected by cost modifiers other than item mastery

### ISSUE THREAD

**Issue by durron597** [MelvorIdle/melvoridle.github.io#4379]
### Describe the bug

If you try to craft tablets with cost modifiers, it doesn't change the amount required of non-shard materials.

### Reproduction Steps

1. Go to imp creation 
2. Scroll to abyssal potatoes
3. Equip hourglass (upright)
4. Observe unchanged cost. It's not a display issue, can be checked by switching to abyssal pumpkins
5. Equip hourglass (inverted)
6. Observe unchanged cost

### Expected behaviour

With 10% cost increase, should cost 110.
With 10% cost decrease, should cost 90.

### Screenshots

![IMG_9481](https://github.com/MelvorIdle/melvoridle.github.io/assets/502260/2a9cfcf0-0747-41e7-8072-fa62024ca758)
![IMG_9482](https://github.com/MelvorIdle/melvoridle.github.io/assets/502260/3f05d153-33a8-450f-a9e2-b830250d6f36)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11410

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11431)
