### ISSUE TITLE
Alt magic when reopening game

### ISSUE THREAD

**Issue by ffasplit** [MelvorIdle/melvoridle.github.io#438]
**Describe the bug**
When you reopen the game the alch keeps trying to run but it deselects the item being arched items so an error keeps occurring until you choose an item again.

**To Reproduce**
1. Start using alch 3 on alt magic
2. Choose an item to alch
3. Close game
4. Reopen game

Also along side this, could the spell stop trying to cast if we run out of something so it stops closing the choose item screen when it fails to use a spell.

**Expected behavior**
When you reopen the game it should continue alching as normal

**Screenshots**

**Browser**
Chrome

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Should be fixed in v0.18
