### ISSUE TITLE
[Bug]: Mastery pool not working

### ISSUE THREAD

**Issue by somesanAdrian** [MelvorIdle/melvoridle.github.io#4382]
### Describe the bug

Mastery pool not working

### Reproduction Steps

1. go to thieving
2. take a look at the mastery pool
3. it should show something like: 100/1000
4. it actually says NaN/1000

### Screenshots

![Screenshot 2024-06-17 at 13 58 10](https://github.com/MelvorIdle/melvoridle.github.io/assets/57897685/877e5412-aecc-452d-bbbb-05f3c78e6c04)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [X] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11416

### Are you using any mods?

No

**Comment by coolrox95** [comment]
This bug was caused by broken mods for the v1.3 update. Please disable your mods and only re-enable once you have confirmed they are updated.

To fix the NaN issue, please follow these steps: https://www.reddit.com/r/MelvorIdle/comments/1dd3d2a/uhh_anyone_else_seeing_this_for_mastery/l82oxi8/

**Comment by BrivoAdrianSomesan** [comment]
awesome, thank you for the answer!
