### ISSUE TITLE
[Bug]: Fighter Amulet not stunning.

### ISSUE THREAD

**Issue by Flurryous** [MelvorIdle/melvoridle.github.io#4385]
### Describe the bug

As title. Fighter amulet does not seem to stun the monster if they hit you for more than 30% of your max hp. However, the stun immunity buff does apply to them. 

### Reproduction Steps

1. Equip the Fighter Amulet
2. Fight any monster that can deal over 30% of your hp 
3. Check the monster's statuses when they hit you for 30% of your max hp and see that the stun immunity buff has been applied, but no stun debuff shows up. 

### Expected behaviour

Fighter amulet should be stunning the monster when they hit you for 30%+ of your max hp. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11434

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11455)
