### ISSUE TITLE
[Bug]: Barrier Regeneration, missing texture

### ISSUE THREAD

**Issue by ottotsuma** [MelvorIdle/melvoridle.github.io#4387]
### Describe the bug

Barrier Regeneration texture seems to be missing.

### Reproduction Steps

Go fight a merman in the combat area and see the missing texture.

### Expected behaviour

There to be a texture.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/51743227/2b6aac77-2c6b-4e98-8d3f-6de780cadbb6)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11434

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11455)
