### ISSUE TITLE
[Bug]: <title> cannot equip steel gloves

### ISSUE THREAD

**Issue by Thaniel-FallFather** [MelvorIdle/melvoridle.github.io#4388]
### Describe the bug

Iron gloves will equip, steel gloves will not. Playing on iOS

### Expected behaviour

Equip steel gloves

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11416

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
You most likely do not have the level required to equip the Steel Gloves.
