### ISSUE TITLE
[Bug]: (AoD + TotH Relics) Skill increase 100 -> 99 after beating IDE

### ISSUE THREAD

**Issue by TautvisStan** [MelvorIdle/melvoridle.github.io#4389]
### Describe the bug

I beat the Impending Darkness Event on Ancient Relics mode, the game set all skills to 100, but then the "Increase Level Cap" still showed up, asking to increase the level cap from 100 to 99. I noticed something was wrong so I selected Choose Later. If I select a skill, it will set that skill to 99.

For reference, this happened when I beat the dungeon a couple days after ItA got released, but the "Level Increase Available!" stays.

### Reproduction Steps

1. Beat the Impending Darkness Event on Ancient Relics mode, while also having Throne of the Herald purchased.

### Expected behaviour

It doesn't offer level increases after it sets all max levels to 100.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/ZCwNB4HY

### Screenshots

![image_2024-06-18_171912158](https://github.com/MelvorIdle/melvoridle.github.io/assets/60960357/3a18a735-8cdb-42af-a944-576794eede19)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11434

### Are you using any mods?

No

**Comment by 04Slash** [comment]
Just a message for the devs: The levelCapIncreases for Pre99Dungeons has IDE in it and Post99Dungeons has Throne of the Herald in it.
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/c16e5fb7-93b9-4d1d-90ca-72ecaae06513)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/9c09a7fb-4bb0-4660-873a-660e4cf898fd)

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11455)
