### ISSUE TITLE
[Bug]: Relic mode, Herblore relic not working

### ISSUE THREAD

**Issue by Stormfallip** [MelvorIdle/melvoridle.github.io#4392]
### Describe the bug

the +10 charges relic in herblore is not working/applying to the potions

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11434

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Unable to reproduce. The increased charges effect applies correctly when a potion is activated.
