### ISSUE TITLE
Alt Magic idling combined runes

### ISSUE THREAD

**Issue by Ctave6** [MelvorIdle/melvoridle.github.io#440]
The bug:
When idling alt magic on mobile (At least Item Alchemy) combined runes don't work, it defaults to basic runes.

To reproduce:
Start alching with combined runes, take note of your normal runes (fire & earth), go idle, come back.

It should:
Use lava runes when selected but does not.

I play on mobile, no scripts.

**Comment by MelvorIdle** [comment]
Fixed in most recent update
