### ISSUE TITLE
[Bug]: Incorrect Summoning Tablet Item Cost Calculation

### ISSUE THREAD

**Issue by Jamesl2k5** [MelvorIdle/melvoridle.github.io#4400]
### Describe the bug

Cost of items for Summoning Tablet Creation is increased compared to base game, even with cost reduction from Mastery.
Prior, base it cost 2 Carp / 1 Perfect Carp+ to craft Wolf. With my current Mastery (68) it cost 1 Perfect Crab+.
Now, with my 68 Mastery, it costs 2 Perfect Crab - Shark.

### Reproduction Steps

1. Boot up game on old version, check base costs
2. Increase Wolf mastery to example level (68)
3. Check item costs for Perfect Crab+ recipes
4. Boot up game on latest version with same save
5. Observe costs went up.

### Expected behaviour

Item costs should not increase.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11455

### Are you using any mods?

No

**Comment by Jamesl2k5** [comment]
Likely root cause as per discussion on Discord:

Cheeezburger — Today at 2:45 PM
anyone else getting a bug where summon tablet item costs are higher than base?
for example, my wolf is at mastery 68, but it costs 2 perfect carp / 2 shark / 2 cave fish, etc
shrimp, sardine, and herring are correctly at 35 though
icing — Today at 2:47 PM
with 1.3 they started rounding up instead of down
Cheeezburger — Today at 2:50 PM
that doesn't explain why it costs 2 where base it costs 1. I'm guessing there's a bug with the rouding implementation?
I don't see another bug report with the same description, so I guess I should create a new one?
icing — Today at 2:52 PM
if it costs 1.55 cave fish
it used to round down to 1
now it rounds up to 2
and it determines how many you need based on sale price
Cheeezburger — Today at 2:53 PM
oh so not a bug? just a change to the base game's costs?
icing — Today at 2:53 PM
idk if its a bug or not but thats whats different at least

**Comment by MelvorIdle** [comment]
With the modifier rework, cost reductions have become standardized to rounding up, with a minimum cost set to 1 (Unless otherwise specified)
