### ISSUE TITLE
[Bug]: Pig plus Octopus synergy not working when fishing in Melvor

### ISSUE THREAD

**Issue by webdevguy1** [MelvorIdle/melvoridle.github.io#4408]
### Describe the bug

After 8 hours of fishing, no cooked fish were received despite the tablets being equipped properly.  I was fishing raw ghost fish in Melvor (not the abyss)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11482

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Raw ghost fish cannot be cooked, so the synergy has no effect when fishing them.

Working as intended.
