### ISSUE TITLE
cake gives NaN hp

### ISSUE THREAD

**Issue by rhysdog1** [MelvorIdle/melvoridle.github.io#441]
**Describe the bug**
eating the cake from the 1st anniversary event gives NaN hp, which makes you unkillable

**To Reproduce**
eat cake

**Expected behavior**
previously, it gave a small amount of hp

**Screenshots**

**Browser**
chrome 

**Are you using any scripts?**
no

**Comment by MelvorIdle** [comment]
This has been hotfixed.
