### ISSUE TITLE
[Bug]: Summoning pouches dissapearing when doing abyssal thieving

### ISSUE THREAD

**Issue by Cptswag** [MelvorIdle/melvoridle.github.io#4411]
### Describe the bug

Was doing abyssal thieving with the regular Leprechaun pouches, stack dissapeared without dying, Not sure if reproduceable

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

1,3

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Summoner's bag provides summoning charge preservation, so it uses a charge while consuming tablets for other Skills.
