### ISSUE TITLE
[Bug]: <title> Slayer task button not working

### ISSUE THREAD

**Issue by FinanceBroQ** [MelvorIdle/melvoridle.github.io#4416]
### Describe the bug

Can’t use the new task button on slayer tab. 

### Expected behaviour

I expected to be able to use the button to choose a slayer assignment difficulty

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11482

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
We have been unable to reproduce this issue. Please create a new issue with more information + a save if the issue persists.
