### ISSUE TITLE
[Bug]: Mining gloves x2 ore in ancient relics mode do not work everytime.

### ISSUE THREAD

**Issue by CazacuRadu** [MelvorIdle/melvoridle.github.io#4417]
### Describe the bug

in ancient relics mode with mining gloves equipped there are some ticks where I don't get x2 ores just 1.
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/11628331/3539b784-5b8c-4f42-afdf-6c660d14fc68)

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/11628331/4b164d01-797e-4895-a078-dae3676627ba)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11482

### Are you using any mods?

No

**Comment by LoadedGuns** [comment]
Then why can you buy them... seems like a waste of money and a flaw in programming to leave them in the shop
