### ISSUE TITLE
[Bug]: Slayer Task Extention in Ancient Relics gives Abyssal Slayer Coins instead of costing 0

### ISSUE THREAD

**Issue by Ayarez** [MelvorIdle/melvoridle.github.io#4418]
### Describe the bug

With all the Slayer Extension Cost Reductions from Master Relic, Skill Tree and the Shop, the cost to extend a Slayer Task goes to -50,000 instead of costing 0 for a Dissolution Task, thus giving you ASC when you extend it

### Expected behaviour

Extension costing 0 with all the buffs

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/151032073/525a1dc1-13f9-4b91-8ee4-a1e7a10cf88c)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11482

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11516)
