### ISSUE TITLE
[Bug]: Enhanced Township Wood Scroll has +3% firemaking interval

### ISSUE THREAD

**Issue by markogle** [MelvorIdle/melvoridle.github.io#4419]
### Describe the bug

Enhance Township Wood Scroll has +3% firemaking interval, assuming it's supposed to be the abyssal equivalent of the melvor realm scrolls it should probably be -2% (like Quick Burner) or -3% instead.

Checked in firemaking and it does give the increased interval, so it's not just a display issue.

### Screenshots

<img width="280" alt="wood_scroll" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/13482807/1840e2ab-9d22-4ab8-bbe1-3014db1bea6b">

![Screenshot 2024-06-21 123510](https://github.com/MelvorIdle/melvoridle.github.io/assets/13482807/dab16265-f004-41f4-b0c9-d3025ce53ec3)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11482

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11516)
