### ISSUE TITLE
[Bug]: <Redwood Sells for 37 while Magic wood for 600>

### ISSUE THREAD

**Issue by Waalsneer** [MelvorIdle/melvoridle.github.io#4420]
### Describe the bug

Is it normal for red wood selling price for 37 while Magic wood sells for 600?

### Screenshots

![Uploading Screenshot_2024-06-21-20-27-24-465_com.malcs.melvoridle.jpg…]()
![Uploading Screenshot_2024-06-21-20-27-27-868_com.malcs.melvoridle.jpg…]()

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11485

### Are you using any mods?

No

**Comment by coolrox95** [comment]
This is intended.
