### ISSUE TITLE
 [Bug]: <New DLC breaks Base Game Completion Log>

### ISSUE THREAD

**Issue by CircusCookie74** [MelvorIdle/melvoridle.github.io#4422]
### Describe the bug

After adding new items in v1.3, the Completion Log has Into The Abyss items added into the base game.
My Base Game progress was almost to 100%, and the 1.3 update occured. There are now new potions, items, pets that I cannot get without purchasing the DLC. Base Game cannot be 100% completed.

### Reproduction Steps

Have save before update
Update release
Load that save after update release.
View Completion Log - Items

### Expected behaviour

For the new DLC items to be in its own completion tab, seperate from the base game.

### Screenshots

<img width="871" alt="image" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/173490596/2cd87e02-ffac-4195-a6bb-d52b81dcee07">

<img width="1401" alt="image" src="https://github.com/MelvorIdle/melvoridle.github.io/assets/173490596/99a7d026-53d4-49a4-9f25-a0598c1ec082">

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11485

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Those items are the new drops from the Strongholds that were added to the base game as part of the v1.3 update.
