### ISSUE TITLE
[Bug]: Abyssal Crow and Abyssal Bear Summoning Synergy effect does not match description

### ISSUE THREAD

**Issue by Southier9** [MelvorIdle/melvoridle.github.io#4423]
### Describe the bug

The sinergy of Abyssal Crow and Abyssal Bear is not working, they are both Tier 4, the potion is already been used, but I'm not getting any random combination abyssal rune from runecrafting.

### Reproduction Steps

1. Equip both Abyssal Crow and Abyssal Bear to activate Synergy
2. Equip the Abyssal Combination Potion to activate Summon Synergy
3. Nothing happens from the Synergy itself.

### Expected behaviour

Random abyssal combination runes being made.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/36991161/8d205abd-b226-4e43-bad8-b09e006da64c)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [X] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?111485

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11524)
