### ISSUE TITLE
[Bug]: <title> Notification section is not showing properly

### ISSUE THREAD

**Issue by H3rbatnik** [MelvorIdle/melvoridle.github.io#4424]
### Describe the bug

Many notifications/popups are partialy hidden at the bottom of the screen.
For example offline results
![obraz_2024-06-21_210058255](https://github.com/MelvorIdle/melvoridle.github.io/assets/173498777/af74fdf5-527a-437d-be8e-cd2fe9b56187)
Viewing chest contents, checking monster drop and warnings before selling items are also bugged

### Reproduction Steps

1. Make sure in the settings you have turned on warnings before selling
2. Pick an items you want to sell
3. In the section "Sell item" click All and then Sell Item
4. Page is scrolled down to the bottom without any warning showing
5. Item was not sold
=========
1. Go to Combat screen
2. Pick any monster and click Drops next to monster name
3. Page is scrolled down to the bottom and 50% of the info about drops is outside of the screen

### Expected behaviour

Easy to see popups/notifications. On mobile everythings works properly

### Screenshots

![obraz_2024-06-21_210756034](https://github.com/MelvorIdle/melvoridle.github.io/assets/173498777/3fc2c0f3-c7d8-443c-8d69-e92f5fe0b876)
![melvor idle bug2](https://github.com/MelvorIdle/melvoridle.github.io/assets/173498777/a935a3cc-8678-400c-8177-9dc08dccbfe0)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11485

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
We have been unable to reproduce this issue. Please make another issue if this issue persists.
