### ISSUE TITLE
[Bug]: Township Easy Quest broken

### ISSUE THREAD

**Issue by Slowcountry** [MelvorIdle/melvoridle.github.io#4428]
### Describe the bug

I have to complete the township easy quest with 25 tier 1 bird nest potions, but I am only able to produce tier 2 bird nest potions. 

### Expected behaviour

Need the option to downgrade potions or produce different tier potions after leveling up.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11485

### Are you using any mods?

No

**Comment by yuriks** [comment]
If you can't manually produce Tier I potions anymore, you can still use Herblore potions (which gives you a random tier of the same potions you're crafting) to get Tier I potions. I believe the task description has a hint about this too.

**Comment by Slowcountry** [comment]
Ah - I see that now. I was only level ~25 Herblore, but working on getting
those now.

Thank you!
Dylan
