### ISSUE TITLE
[Bug]: can’t click new task 

### ISSUE THREAD

**Issue by Thefriebster** [MelvorIdle/melvoridle.github.io#4429]
### Describe the bug

Can not click new task on either PC or IOS for Slayer [

https://github.com/MelvorIdle/melvoridle.github.io/assets/63893988/78cd0233-09a5-4391-8fb6-600ac35cf5ec

](url)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [X] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11485

### Are you using any mods?

Yes

**Comment by 04Slash** [comment]
This is most likely a mod bug. Disable all mods and see if the issue persists.

'Will I Die?' is known to cause this issue. There could be more that cause it as well.
