### ISSUE TITLE
NAN Mastery (I can’t upgrade my mastery.)

### ISSUE THREAD

**Issue by xxAsura123** [MelvorIdle/melvoridle.github.io#4431]
### Describe the bug

I cannot improve the mastery of anything nor can I fill the mastery pool.

I currently use no mods and I have all currently released versions.

### Reproduction Steps

For one amongst many go to the archeology skill and you will see the weird mastery pool and mastery skills. (View attached pictures.)
![IMG_9375](https://github.com/MelvorIdle/melvoridle.github.io/assets/162391748/75518014-172f-4553-bd2e-f822752928e1)
![IMG_9376](https://github.com/MelvorIdle/melvoridle.github.io/assets/162391748/adac18b2-cd1b-4afa-9567-d5b278af1db3)

### Expected behaviour

Please fix it so that I can finish the game?

### Screenshots

![IMG_9375](https://github.com/MelvorIdle/melvoridle.github.io/assets/162391748/46121adc-b64b-4014-8b06-17a1448ad664)
![IMG_9376](https://github.com/MelvorIdle/melvoridle.github.io/assets/162391748/892a329c-4206-4fc1-928c-fb42c10cde7f)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11485

### Are you using any mods?

No

**Comment by coolrox95** [comment]
You have run into the NaN mastery bug caused by mods that are not compatible with v1.3. Please disable your mods and only re-enable once you have confirmed they are updated and work today.

To fix the NaN issue, please follow these steps: https://www.reddit.com/r/MelvorIdle/comments/1dd3d2a/uhh_anyone_else_seeing_this_for_mastery/l82oxi8/
