### ISSUE TITLE
[Bug]: Cartography relics are not unlocked in Ancient Relics mode

### ISSUE THREAD

**Issue by PaulK007P** [MelvorIdle/melvoridle.github.io#4434]
### Describe the bug

Cartography relics are not unlocked in Ancient Relics mode
Attention: excluding guaranteed relics of levels 20 and 99. Everything is alright with them.
I checked it on my save and on the newly created one, relics don’t open on both for a huge number of hours.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11485

### Are you using any mods?

No

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11516)
