### ISSUE TITLE
[Bug]: Cartography Map stuck on 4%

### ISSUE THREAD

**Issue by Saintwest3030** [MelvorIdle/melvoridle.github.io#4435]
### Describe the bug

The cartography map won’t load and is either stuck on 4% or 50%, I’ve tried changing the map quality to low and tried all the other cartography settings but still no change.

### Expected behaviour

The map would load.
![IMG_4096](https://github.com/MelvorIdle/melvoridle.github.io/assets/173609726/cfd97573-9f51-4c71-b6ac-fdad610a2026)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11485

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Related #4218 (Closing to clean issues)
