### ISSUE TITLE
[Bug]: Cannot mine in the Abyssal Realm

### ISSUE THREAD

**Issue by Jhingerkid** [MelvorIdle/melvoridle.github.io#4437]
### Describe the bug

I disabled all mods then loaded an exported string of the save (from before the abyss had been loaded though mods had previously been active), and am still seeing the issue occur. When I go to the mining skill, click on the abyssal realm, then click on either the Abyssal Essence or the Abyssium Ore I cannot mine it; my character will continue to do the previous action he was assigned.

### Reproduction Steps

1. Go to the abyssal realm for mining
2. Click on either Abyssal Essence or Abyssium Ore

### Expected behaviour

When either resource is clicked, my character should begin that gathering process as their current task

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/ygYeriJe

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

11485

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
You have run into the NaN mastery bug caused by mods that are not compatible with v1.3. Please disable your mods and only re-enable once you have confirmed they are updated and work today.

To fix the NaN issue, please follow these steps: https://www.reddit.com/r/MelvorIdle/comments/1dd3d2a/uhh_anyone_else_seeing_this_for_mastery/l82oxi8/
