### ISSUE TITLE
[Bug]: "Cost reduction applied to product costs.." can go below 0%

### ISSUE THREAD

**Issue by BenLubar** [MelvorIdle/melvoridle.github.io#4438]
### Describe the bug

The cost reduction *can* go below 0% despite saying it cannot.

### Reproduction Steps

1. Equip abyssal hourglass.
2. Hover over the cost reduction icon for any recipe.

### Expected behaviour

The line about 0% being the minimum isn't there.

\- OR -

The cost of the recipe isn't increased because the minimum cost reduction is 0%.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/cum8zeuo

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11485

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11516)
