### ISSUE TITLE
[Bug]: <Some skills and all mastery broken>

### ISSUE THREAD

**Issue by Author4867** [MelvorIdle/melvoridle.github.io#4439]
### Describe the bug

Some of my skills no longer operate, whether that's abyss or melvor/previous content. Additionally, all my mastery displays as NaN. This appears on all platforms. 
![Can't be selected](https://github.com/MelvorIdle/melvoridle.github.io/assets/173687699/b5fa7c11-9d62-4805-b3ae-8180fca6c73a)
![Broken Mastery](https://github.com/MelvorIdle/melvoridle.github.io/assets/173687699/ada86f5f-f8e2-4c99-952a-40cc084faed0)

### Reproduction Steps

Both of these errors appear on loading. 

### Expected behaviour

I expect the skills to start to start perform when clicked.  

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/lJUfnd1v

### Screenshots

![Can't be selected](https://github.com/MelvorIdle/melvoridle.github.io/assets/173687699/79dc2923-ffda-4ecf-a5ee-4a64b7d80798)
![Broken Mastery](https://github.com/MelvorIdle/melvoridle.github.io/assets/173687699/876b0e48-17ec-4771-a476-dc118a085e72)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

11485

### Are you using any mods?

No

**Comment by coolrox95** [comment]
You have run into the NaN mastery bug caused by mods that are not compatible with v1.3. Please disable your mods and only re-enable once you have confirmed they are updated and work today.

To fix the NaN issue, please follow these steps: https://www.reddit.com/r/MelvorIdle/comments/1dd3d2a/uhh_anyone_else_seeing_this_for_mastery/l82oxi8/
