### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by david1wong1** [MelvorIdle/melvoridle.github.io#4441]
### Describe the bug

Cartography is missing the interval bar.

### Reproduction Steps

1. Go to Cartography
2. Start Auto Surveying or Regular Surveying.

### Expected behaviour

There should be a bar to just show the progress/interval like all other skills

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11181

### Are you using any mods?

Yes

**Comment by ReadySetHeal** [comment]
Surveying progress bar is that little spyglass in the hex you are surveying. Unless you don't have it?

**Comment by david1wong1** [comment]
![Capture](https://github.com/MelvorIdle/melvoridle.github.io/assets/84152417/0ee79002-8343-4ef3-a9c2-f743d729cea5)
Hmm I dont see it am I blind? Is it possibly a mod thats causing this?

**Comment by david1wong1** [comment]
I see the progress bar of the hex itself but not each interval. I know its a small thing but yeh.
