### ISSUE TITLE
[Bug]: Agility Obstacle 6-2 providing the wrong type of experience

### ISSUE THREAD

**Issue by Dohtt** [MelvorIdle/melvoridle.github.io#4443]
### Describe the bug

Obstacle 6-2 in ITA is providing Astrology Skill XP, which is not the abyssal variant.

### Reproduction Steps

1. Go to agility
2. Build obstacle 6-2

### Expected behaviour

It should provide +4% Abyssal Astrology XP

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/17968897/1b1eed9a-f131-4020-9c2b-4065b0116dc2)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11485

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11516)
