### ISSUE TITLE
[Bug]: Android Layout Persisted Over to Steam

### ISSUE THREAD

**Issue by NalihznehC** [MelvorIdle/melvoridle.github.io#4444]
### Describe the bug

I started out using the Steam PC platform, and then switched back and forth between the Android version and the Steam PC version a few times without any problems, but this time, the page layout of the Android platform persisted over to the Steam one. Both platforms are using v1.3 ?11485

### Reproduction Steps

Log in the same character using Steam PC Platform and Android Platform,
Switch between these two platforms.

### Expected behaviour

Eventually, the PC layout will be contaminated by the mobile layout(?)

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/frV35zWt

### Screenshots

My previous experience was consistent with the image shown on your official Wiki page:
https://wiki.melvoridle.com/w/File:Combat_Page_Map.png

However, This is what my Steam game looks like now:
![Screenshot 2024-06-24 223902](https://github.com/MelvorIdle/melvoridle.github.io/assets/39670573/8c2334a6-31cd-4347-9c04-9f7a465b4cd8)

I could not find any setting switches or online resources to help me with this display issue.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11485

### Are you using any mods?

No

**Comment by NalihznehC** [comment]
It went back to the original Steam layout today. I do not know what happened, but I suspect this issue might happen again sometime.
The new save file:
https://melvoridle.com/save/fsz7nlMD

**Comment by DMNinja** [comment]
To my understanding, this issue happens if the window is launched in a somewhat vertical aspect ratio. I can observe this issue on linux, using a tiling WM. When melvor opens up as a 2nd window it has a size of (1920/2 * 1080) where the above behavior is observed. 
Fullscreening that window later on doesn't affect the layout, and the only solution is to relaunch melvor in a completely empty window
