### ISSUE TITLE
Item does not move to tab

### ISSUE THREAD

**Issue by krakow10** [MelvorIdle/melvoridle.github.io#446]
**Describe the bug**
Sometimes items do not get moved to the tab it is clicked and dragged to, instead a different item is moved.

**To Reproduce**
Drag item to tab

**Expected behavior**
Item is moved to tab

**Screenshots**
https://www.youtube.com/watch?v=NdgLaqfLQAQ

**Browser**
Chromium Version 86.0.4240.75 Manjaro Linux (64-bit) chromium-vaapi AUR package

**Console output**
https://pastebin.com/M2LCtemP

**Are you using any scripts?**
No

Note: The item can be moved by sorting the bank and then moving the item

**Comment by MelvorIdle** [comment]
Hotfixed :)
