### ISSUE TITLE
[Bug]: Cost Reduction not applying to Summoning 

### ISSUE THREAD

**Issue by Ayarez** [MelvorIdle/melvoridle.github.io#4461]
### Describe the bug

Only tested in Ancient Relics myself but have heard other people mention this in standard too
The Cost Reduction does not seem to apply to making Tablets.

Base cost for added Screenshot is 50 Abyssal Stones, cost with 77% Cost Reduction is still 50 Abyssal Stones.

Shard cost does seem to go down, reagents dont

### Reproduction Steps

1 - Look at cost to make summoning Tablets
2 - increase the Cost Reduction
3 - Cost remains the same

### Expected behaviour

Cost going down with Cost Reduction

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/151032073/5ffab378-f38d-4cbc-84ad-7b14dd3c7130)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11517

### Are you using any mods?

Yes

**Comment by durron597** [comment]
Somehow I don't think they will change this again... https://github.com/MelvorIdle/melvoridle.github.io/issues/4379#issue-2355945144

It's hitting some sort of cap now that is much easier to hit in AR than in standard. But the tooltip isn't reflecting item mastery's impact on cost reduction.

**Comment by Ayarez** [comment]
Seems the values on the wiki got updated since the last time I checked. Seems it is working correctly then!
