### ISSUE TITLE
[Bug]: Amulet of Torture farming / Fierce Devil kills

### ISSUE THREAD

**Issue by xpucto777** [MelvorIdle/melvoridle.github.io#4466]
### Describe the bug

I'm farming Amulet of Torture by killing Fierce Devil. Randomly getting Gold Topaz Ring while it's not in the loot table at all. And seems that the Amulet of Torture is drop rate is much smaller to the listed in the Wiki.

I'm farming for 4-5 days already. Still not enough amulets for the task

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/172144420/f048aa75-791c-4fce-ad87-d701d0fd49e9)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11517

### Are you using any mods?

No

**Comment by Flurryous** [comment]
You're getting the topaz ring because the game is rolling a signet half drop for you, but because you're not wearing the topaz ring, you're getting that as a drop instead.
