### ISSUE TITLE
[Bug]: Ancient Relics choices after clearing dungeon not working properly

### ISSUE THREAD

**Issue by Ayarez** [MelvorIdle/melvoridle.github.io#4469]
### Describe the bug

After defeating a dungeon the skill cap choices pop up. Choosing 1 of the options doesnt always work. You can select 1 of the options but it just wont register. You have to click the "choose later" option then open the choice selection again for it to actually work.

This has never been an issue before the ItA launch, has however been an issue since the ItA launch for almost everybody 

### Reproduction Steps

1) Clear a new dungeon
2) go through choices as regular
3) one of the options will not work
4) select choose later
5) both options now work

### Expected behaviour

Both choices working without having to close the choice window and reopen it

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11517

### Are you using any mods?

Yes

**Comment by 04Slash** [comment]
The issue here is the onClick for the button sets the new caps then nulls the onClick for the button that was pressed. This results in the last button selected always being null forcing you to either close the pop-up or select the other option.
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/a65eb6e5-5f15-40ab-9017-38831343a9fd)

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11550)
