### ISSUE TITLE
Smithing (sometimes) Doesn't Consume or Create Resources

### ISSUE THREAD

**Issue by lucidobservor** [MelvorIdle/melvoridle.github.io#447]
**Describe the bug**
After having acquired plenty of coal and mithril ore, I tried to start crafting mithril bars for the first time. Instead of the expected behavior, the smelting action repeated continuously, _without_ consuming either coal or mithril ore, and without creating mithril bars. However, smelting XP and mastery XP were still awarded as normal. In the bottom of the Smithing action box, where "You Have: <number> <mithril bar icon>" is displayed, I observed the <number> value to alternate between 1 and -3.

Going to the Bank while this was happening, I observed the values for coal and mithril ore remaining unchanged, while seeing a single mithril bar appear and disappear in time with the smithing action.

I attempted to resolve the issue by changing to the mining tab, mining a few ore, and going back to smithing. The error described above still occurred. 

I _successfully_ resolved the issue by taking the following steps:
- Go to the Bank
- Observe Tab 0, where I can see 1 mithril bar appearing and disappearing. There are no other items in this tab.
- Click on the mithril bar when it is present
- Change the default tab to Tab 1
- Observe Tab 1, where I can see mithril bars now incrementing as expected.

**To Reproduce**
I am unable to reproduce this issue after successfully resolving it.

**Expected behavior**
When smithing mithril bars, coal and mithril ore are consumed to create mithril bars.

**Browser**
Google Chrome Version 86.0.4240.80 (Official Build) (x86_64)

**Console output**
```
?l=1:1 [DOM] Found 2 elements with non-unique id #bank-sell-x: (More info: https://goo.gl/9p2vKq) <input type=​"text" class=​"form-control" id=​"bank-sell-x" name=​"bank-sell-x" placeholder=​"Sell x">​ <input type=​"text" class=​"form-control m-1" id=​"bank-sell-x" name=​"bank-sell-x" placeholder=​"Sell x">​
save.js?500:56 Loading Save Game...
save.js?500:195 Save Game Loaded...
smithing2.js?500:204 Loading Smithing...
mastery.js?500:23 Loading Masteries...
main.js?511:392 Game Loaded
cloud.js?500:516 Connected to PlayFab successfully
```

**Are you using any scripts?**
None

**Comment by MykeMcG** [comment]
I ran into this issue with tier 1 Bird Nests Potions, and was able to resolve the issue using steps described above.
