### ISSUE TITLE
[Bug]: Gem preservation scrolls being used when crafting non-jewelry items

### ISSUE THREAD

**Issue by Pwaite2** [MelvorIdle/melvoridle.github.io#4471]
### Describe the bug

When I was crafting leather items (hard leather vambraces to be specific) I noticed that my gem preservation scrolls were being consumed (the ones obtained from Township trader).

Their effect only applies when crafting jewelry so I assume it being spent when crafting other items is a bug.

### Reproduction Steps

1. Buy Gem Preservation Scrolls from Township trader
2. Equip them
3. Go in Crafting and craft any leather item
4. Watch your number of scrolls go down

### Expected behaviour

I expect gem preservation scrolls to not be consumed unless I craft jewelry items (like mining gloves charges not being spent on rune essence for example)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [X] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11524

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Issue has been resolved as of v1.3 (?11550)
