### ISSUE TITLE
[Bug]: Void Runes Missing or Intended?

### ISSUE THREAD

**Issue by Ayarez** [MelvorIdle/melvoridle.github.io#4483]
### Describe the bug

As stated in Topic, not sure if this was overlooked or intended but Void Runes cannot be crafted in Runecrafting. It does have the auto-generated Runecrafting Tag on the wiki so would assume their source would be Runecrafting (outside drops, like almost all other runes have too)

The 4 highest Tier Spells all use Void Runes so wouldnt be surprised if it was intended

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

??11555

### Are you using any mods?

Yes

**Comment by Ayarez** [comment]
If it is intended I would love some feedback about that so I can make a note of this on the Wiki

**Comment by MelvorIdle** [comment]
This is intended. There are a few late-game runes that can only be obtained via Combat.
