### ISSUE TITLE
[Bug]: <title>stronghold pet drop rate is strange

### ISSUE THREAD

**Issue by var-lllll963247** [MelvorIdle/melvoridle.github.io#4488]
### Describe the bug

Many people on reddit reported that Stronghold’s pet drop rate is very low, and many people have cleared more than 1,000 superior level and still can’t get it.
Your wiki says the drop rate is 1/250. This is obviously wrong. Otherwise, there wouldn’t be so many people reacting. You can see there are a lot of articles on reddit to reacting.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11560

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
The drop rate is correct. Pets can only be obtained from Superior tier of Strongholds. The Total completion count everyone is looking as is inclusive of the other 2 lower tiers where the Pet does not drop from.

**Comment by Kirjath-Sepher** [comment]
I'm farming superior Stronghold of magic for 3 days and still no pet. I need it for completion it's cape. This and pet from god stronghold pet is last thing I need.
