### ISSUE TITLE
[Bug]: <title>Cooking Cromson Biter does not increase owned, despite saying +X

### ISSUE THREAD

**Issue by VincentValensky** [MelvorIdle/melvoridle.github.io#4489]
### Describe the bug

Something happened and now cooking Crimson Biter does not increase the amount of Crimson Biter, even when it says +3 or +2. I've left it going and I end up with the same amount that I started. It still gives XP. Passive cooking it still works.

### Reproduction Steps

Unfortunately I'm not 100% sure what triggered this, but it was after I was passive cooking CrimsonBiter while active cooking Baked Biter Pie. 

### Expected behaviour

Active cooking should increase the amount I have.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11560

### Are you using any mods?

No

**Comment by Ayarez** [comment]
You have them equiped and bought the Cooking upgrade 1, which automatically equips them when cooked
