### ISSUE TITLE
[Spelling/Grammar]: <title>

### ISSUE THREAD

**Issue by ChangedForsomethingNew** [MelvorIdle/melvoridle.github.io#4491]
### What text is wrong?

linden log's is a transgender dick joke. 
going to the wc. 

taken wrong or to far can be detrimental to my future health.

i haven't zaw it. 

whit the way it can be mistaken and as soon as the 4th wall is started to break this sort of stuff is not help full. 

when they misunderstand what the log is or what the three it is an in meme joke. 
is what is wrong whit the linden log joke.

### What is the correct spelling or grammar?

i am a trans woman.

it is i have seen it. 
you fucking psychopath's.

**Comment by MelvorIdle** [comment]
Tilia is a genus of about 30 species of trees or bushes, native throughout most of the temperate Northern Hemisphere. The tree is known as **linden** for the European species, and basswood for North American species.

Source: https://en.wikipedia.org/wiki/Tilia
