### ISSUE TITLE
Summoning synergy octopus leprechaun inverted?[Bug]: <title>

### ISSUE THREAD

**Issue by Matopatch** [MelvorIdle/melvoridle.github.io#4496]
### Describe the bug

My synergy for summoning and leprechaun gives " +50 Thieving Skill Interval" for the fisherman. Shouldn't it be -50 percent? It's increasing the time it 
![Screenshot_20240710-051430](https://github.com/MelvorIdle/melvoridle.github.io/assets/175203363/1e775a8d-91cf-4987-8dec-fee39aa5f9c2)
takes for me to thieve the fisherman, from 2.65 w/o synergy to 4.15 with synergy active. 

### Reproduction Steps

I equip leprechauns while thieving, getting normal interval. I equip octopus, interval increases. 

Even the synergy page on summoning lists it as a +50% interval increase

### Expected behaviour

I thought it's supposed to be -50 interval?

I've seen online forum posts talking about it being effective as a buff, not a debuff.

### Screenshots

![Screenshot_20240710-051430](https://github.com/MelvorIdle/melvoridle.github.io/assets/175203363/831b5260-6630-4837-83b6-4e0db92eeceb)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11574

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This is the intended bonus for it. You receive +2 base item quantity as the balance to the increased interval. Even with +50% interval, this is still a buff to the amount of items you can acquire from the Fisherman
