### ISSUE TITLE
Herblore 95% checkpoint doesn't do anything in Harvesting

### ISSUE THREAD

**Issue by durron597** [MelvorIdle/melvoridle.github.io#4500]
### Describe the bug

The Herblore 95% checkpoint is supposed to be +4 charges per potion. However, the harvester potion did not change after I got that checkpoint.

### Reproduction Steps

1. Get Herblore 95% checkpoint 
2. Get Tier IV harvesters potion
3. Ensure no other modifiers on potion charges present (consumable, pillar of generosity, etc)
4. Go to harvesting
5. Select harvesters potion.
6. Begin harvesting

### Expected behaviour

I expect to have 8 charges per potion. Not 4

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

??11574

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
The bonus is applied when a potion is used in the Skill. You can see the charges provided when using a new potion in havesting is above what is stated on the potion itself.

**Comment by joshkel** [comment]
I'm seeing a similar issue too - the chargers when using a new potion in harvesting and mining don't reflect the abyssal herblore 95% pool mastery bonus. I am checking when the potion is used in the skill.

In checking the source code, I noticed that `this.game.modifiers.flatPotionCharges` is accessed directly - does that mean that the abyssal-only modifier query isn't getting evaluated?
