### ISSUE TITLE
[Suggestion]: Firemaking oil consumed at a rate of 10 per oil burn. Should be 1 oil at 10x cost.

### ISSUE THREAD

**Issue by roodwarrior** [MelvorIdle/melvoridle.github.io#4504]
### Describe the bug

Firemaking oil is consumed at a rate of 10 per oil burn.

### Expected behaviour

It should be consumed at 1 per burn and maybe cost 10x more?

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11585

### Are you using any mods?

No

**Comment by roodwarrior** [comment]
Actually, I just noticed that the button says that it costs 10 oil to use, but it would make a lot more sense to eliminate that and then charge 10x the price.

**Comment by roodwarrior** [comment]
It would be better to just make it cost 10x more.

**Comment by roodwarrior** [comment]
Sorry, I have been messing with the open and close function trying to figure out how to best present this. Basically, my suggestion is to make the oil cost 10X more and leave it at that. That way you don't have to use 10 to oil the logs, just one, and it would make more sense.

**Comment by coolrox95** [comment]
This issue tracker is only for Bug Reports. Suggestions can be made on our [official discord server](https://discord.com/invite/melvoridle).
