### ISSUE TITLE
I can't create Summoning Abyssal Tablets 

### ISSUE THREAD

**Issue by Tangarz** [MelvorIdle/melvoridle.github.io#4505]
### Describe the bug

The new tablets at level 5 didn't unlock properly. I can't create (not select either) Abyssal Ent or Abyssal Goblin Thief tablets with the correct level requirements.

### Expected behaviour

Select and create Abyssal Summoning Tablets.

### Screenshots

![Abyssal Summoning bug](https://github.com/user-attachments/assets/409121ce-8190-4ec0-9288-e3c535e13bc2)
![Abyssal Summoning bug 2](https://github.com/user-attachments/assets/6d6f3465-2105-4fe7-abcb-9cc38200ed79)
![Abyssal Summoning bug 3](https://github.com/user-attachments/assets/41cc5c7a-3afe-4298-bcad-f0c9d7dcd01d)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11585

### Are you using any mods?

No

**Comment by Flurryous** [comment]
You need to find a mark first before you can make tablets for that summon.

**Comment by Tangarz** [comment]
> You need to find a mark first before you can make tablets for that summon.

Oh my... In the Abyss it's the opposite... Thanks!!

**Comment by Flurryous** [comment]
> > You need to find a mark first before you can make tablets for that summon.
> 
> Oh my... In the Abyss it's the opposite... Thanks!!

No, it's the same? Base game tablets functioned the same way. You needed to find 1 mark first before you could make tablets even there.

**Comment by Tangarz** [comment]
> > > You need to find a mark first before you can make tablets for that summon.
> > 
> > 
> > Oh my... In the Abyss it's the opposite... Thanks!!
> 
> No, it's the same? Base game tablets functioned the same way. You needed to find 1 mark first before you could make tablets even there.

Sorry, I explained myself badly. What I meant was that in the base game you get the very first mark automatically when you hit the minimun level so you can create the tablet that same moment(at least that's how I remember, maybe I'm wrong :/). In the abyss you need to train a bit the require skill first to discover the very first mark, then create the first tablets and then keep training the skill to discover the rest marks. Sorry for the misunderstaning :/

**Comment by Flurryous** [comment]
Oh, no, the first mark for base game isn't automatic. You had to do some skilling for that mark after you hit the summoning requirement in order to find the first one.
