### ISSUE TITLE
[Bug]: Abyssal Bear + Abyssal Salamander Synergy impossible to use

### ISSUE THREAD

**Issue by Flurryous** [MelvorIdle/melvoridle.github.io#4508]
### Describe the bug

The Abyssal Bear + Abyssal Salamander synergy is listed as: 

x2 Azurian and Obsidian Bars gained from Smithing while Abyssal Miner Potion is active.

However, the tablets involved with the synergy are for herblore and smithing, but Abyssal Miner potions are used for mining. There also doesn't seem to be a mixup with the potion, either, as abyssal smithing has no potion associated with it. It seems that this synergy is impossible to use given the effect.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11585

### Are you using any mods?

Yes

**Comment by 04Slash** [comment]
You can go into the Mining tab then drink the potion and the synergy should work.

**Comment by Flurryous** [comment]
So this is intended? Kinda weird that this is the only potion based synergy that works like that but I guess I'll close this if it works.
