### ISSUE TITLE
[Bug]: Abyssal Leprechaun + Golem synergy providing no AP on activation

### ISSUE THREAD

**Issue by Flurryous** [MelvorIdle/melvoridle.github.io#4509]
### Describe the bug

The Abyssal Leprechaun + Golem synergy is as follows:
"+5% chance to gain 50 AP per Vein Harvesting Level when Harvesting"

When the synergy activates, a popup showing the AP icon appears, but no number is shown. It seems like no AP is received at all. 

### Reproduction Steps

1. Equip Abyssal Leprechaun and Golem tablets while you have the synergy unlocked.
2. Harvest any veins. 
3. Eventually, a popup will appear with the AP icon but no number. 

### Expected behaviour

The synergy as described in-game is expected to work.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11585

### Are you using any mods?

Yes

**Comment by ecterun** [comment]
Adding I am also running into this issue on Steam/ Firefox with No Mods.
