### ISSUE TITLE
NaN health value for goblin in goblin raid

### ISSUE THREAD

**Issue by TheodoreRamey** [MelvorIdle/melvoridle.github.io#451]
**Describe the bug**
On wave 4 of the goblin raid after an attack a goblin reached NaN health. I had received the following items: Slayer Cape, Ice Sword, Fighter Amulet. I took a [screenshot](https://imgur.com/a/kdrcWNg)

**To Reproduce**
This doesn't seem easily reproducible to me as a user, as items are randomized in goblin raid.
Try the combo of fighter amulet & ice sword.

**Expected behavior**
I expected the goblin to have its health decrease each time I hit for damage, but damage never actually happened after reaching NaN health

**Screenshots**
As linked in the description, [here](https://imgur.com/a/kdrcWNg)

**Browser**
Google Chrome | 86.0.4240.75 (Official Build) (64-bit)

**Console output**
Well I already died and moved on so it might not help but:

www.googletagmanager.com/gtag/js?id=UA-129674422-1:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/assets/media/shop/assets/media/shop/perpetual_haste.svg:1 Failed to load resource: the server responded with a status of 404 ()
index.php?l=1:1 [DOM] Found 2 elements with non-unique id #bank-sell-x: (More info: https://goo.gl/9p2vKq) <input type=​"text" class=​"form-control" id=​"bank-sell-x" name=​"bank-sell-x" placeholder=​"Sell x">​ <input type=​"text" class=​"form-control m-1" id=​"bank-sell-x" name=​"bank-sell-x" placeholder=​"Sell x">​
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
save.js?500:56 Loading Save Game...
save.js?500:195 Save Game Loaded...
smithing2.js?500:204 Loading Smithing...
mastery.js?500:23 Loading Masteries...
main.js?511:392 Game Loaded
DevTools failed to load SourceMap: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://melvoridle.com/sm/13c28911820333eb6a51103a0e2096477a38941cc79afbf16b59f3d5a5f63086.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://melvoridle.com/assets/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://melvoridle.com/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Hotfixed
