### ISSUE TITLE
[Bug]: Herblore 95% checkpoint not functioning

### ISSUE THREAD

**Issue by Flurryous** [MelvorIdle/melvoridle.github.io#4510]
### Describe the bug

This is basically a rehash of report #4500, which was pre-emptively closed. According to users who have reached the 95% herblore checkpoint, they are not seeing an increase in potion charges as they are using their potions. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11585

### Are you using any mods?

Yes

**Comment by Bigmike4470** [comment]
I have been experiencing this bug as well. I have the 95% herblore checkpoint unlocked and am still getting 4 charges per shadeveil potion in abyssal combat

![image](https://github.com/user-attachments/assets/731e8e00-77a2-4529-b88e-c4e021ce4506)


https://github.com/user-attachments/assets/1f47e67d-ca77-4592-9041-96602c148b3c

**Comment by durron597** [comment]
https://github.com/user-attachments/assets/136fa7e4-245c-4714-9292-102672060353

I made this after my original report, that's why it wasn't included in #4500
