### ISSUE TITLE
[Bug]: harvesting summon xp

### ISSUE THREAD

**Issue by arion-yedinak** [MelvorIdle/melvoridle.github.io#4511]
### Describe the bug

while harvesting with summoning tablets, I'm only getting 99xp for my abyssal summon skill. It doesn't matter which summon synergy I use, or just use the golem, it's only 99 summon xp. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11585

### Are you using any mods?

Yes

**Comment by Flurryous** [comment]
Do you have any of the synergies unlocked? You need to level up the marks a few times before you can unlock them.

**Comment by arion-yedinak** [comment]
Yes, I'm currently using the golem and raven which should be a lot since
raven is level 30. But the xp doesn't change if I use a synergy or not.
Regular golem is 99 XP, golem and ent is 99, golem and raven is 99.

**Comment by Flurryous** [comment]
To be clear, you need to gain enough marks for each of the summons to unlock their synergy. It seems like you haven't done that yet, from the sound of it. 

Either that or a mod is interfering with things if you do have the synergies unlocked. I've been using golem synergies and haven't encountered this issue.

**Comment by arion-yedinak** [comment]
I have disabled every mod. The only two synergies that add more XP is golem
and ent and golem and mole. Octopus, pig, and raven only give 99xp. I
understand how marks and synergies work, trust me. Have you used any
synergy besides ent or mole? If not, try so and let me know. But it sounds
like you only have two synergies unlocked, and are not experiencing the
same bug.

**Comment by Flurryous** [comment]
Ent, mole, octopus, pig, and leprechaun work for me. 

Though Golem + Leprechaun is bugged in that the synergy bonus itself isn't working, but you do get the boosted exp. 

The synergies with octopus and pig only work with fishing and cooking, respectively. I haven't gotten enough raven marks yet, but I can try to test it later. 

You mentioned that golem + ent wasn't working in a previous post, so I guess you managed to fix that one?

**Comment by Flurryous** [comment]
Yeah, it seems like for the Golem + Crow synergy, tablets are not being consumed upon synergy activation.
