### ISSUE TITLE
Slayer monsters can be fought without the required item by starting combat and switching loadouts

### ISSUE THREAD

**Issue by TheDeviantCrafter** [MelvorIdle/melvoridle.github.io#452]
**Describe the bug**

In order to fight Lots of Eyes, the mirror shield is required. It's possible to fight the monster without a mirror shield by starting combat with the shield equipped, then switching to a different loadout without the mirror shield equipped.

Without the shield I can't actually do any damage, but it's odd that this is permitted.

**To Reproduce**
1. Equip a mirror shield in your current combat loadout, but not in every loadout
2. Begin killing a monster that requires the mirror shield (ie: Lots of Eyes)
3. Open the combat menu by clicking one of the combat skills in the sidebar
4. Select a different combat loadout with no mirror shield equipped

**Expected behavior**
Normally, fighting attempting to fight Lots of Eyes without the mirror shield produces an error message that says "You must have a mirror shield equipped to fight that monster." Until the player equips the required item it cannot be fought. I expect trying to switch loadouts to produce the same error message, either preventing the player from switching tabs or ending combat.

**Screenshots**

![image](https://user-images.githubusercontent.com/18755309/96328067-d1297200-1004-11eb-89f1-ea9d14f53bdb.png)

**Browser**
Google Chrome Desktop Version 86.0.4240.75 (Official Build) (64-bit)

**Console output**
https://pastebin.com/36ry8imE

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Yes, you can fight them but you deal 0 damage unless you have the item equipped.
