### ISSUE TITLE
[Bug]: Cannot get normal carp from cooking

### ISSUE THREAD

**Issue by ckdehd200** [MelvorIdle/melvoridle.github.io#4524]
### Describe the bug

When I cook carp, I cannot obtain normal carps. 
(Awkwardly I can obtain perfect carps)

### Expected behaviour

Can get carp in cooking

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11585

### Are you using any mods?

No

**Comment by 04Slash** [comment]
Are they going directly into your food slots due to [Cooking Upgrade 1](https://wiki.melvoridle.com/w/Cooking_Upgrade_1)?

You can disable this on the cooking screen by unchecking 'Automatically equip food when it is made?'.

**Comment by ckdehd200** [comment]
@04Slash Oh, holy... yeah you're right, I turn on that option. Thanks for your help.
