### ISSUE TITLE
[Bug]: Melvor Realm's Summoning pool applying to Abyssal Summoning

### ISSUE THREAD

**Issue by Flurryous** [MelvorIdle/melvoridle.github.io#4527]
### Describe the bug

Melvor Realm's Summoning mastery pool checkpoint at 25% mentions reducing shard cost of tier 1 and 2 summons by 1 shard, and the checkpoint at 95% mentions reducing shard cost of tier 3 summons by 1 shard. 

From what I can tell, it seems these bonuses are also applying to abyssal realm summons. 

### Reproduction Steps

1. Get to 25% Melvor Realm summoning pool (or 95% if testing tier 3s). Make sure you have no abyssal cost reduction bonuses or any abyssal shard reduction bonuses. 
2. Swap to the abyssal summoning tablet menu.
3. Select a tier 1 or tier 2 summon (or tier 3 with a 95% pool)
4. Confirm that the amount of shards needed to make tablets is one less than the base amount shown on the wiki.

### Expected behaviour

Since it seems that every other Melvor Realm mastery pool doesn't work with their abyssal counterpart, the shard cost reduction from the Melvor Realm summoning pool should not be working with abyssal summoning. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11585

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
As the modifier doesn't specifically mention that it only works in the Melvor Realm, it will indeed work for Abyssal content. This is intended.
