### ISSUE TITLE
[Bug]: <title> Permanently in a dizzy state

### ISSUE THREAD

**Issue by AZUMAYUKIKAZE** [MelvorIdle/melvoridle.github.io#4529]
### Describe the bug

Permanently in a dizzy state

### Reproduction Steps

Choose the theft， Level 1. The. It happened now I can do nothing in my account 

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/menpH5Az

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11585

### Are you using any mods?

No

**Comment by Flurryous** [comment]
Can use the console and input one of these commands to see if it breaks you out of the stun:

`game.thieving.stunState = 0`
`game.thieving.stunned(this.stop)`
`game.thieving.resetActionState()`

Not a permanent fix though, unfortunately.
