### ISSUE TITLE
NaN: Coins unusable.

### ISSUE THREAD

**Issue by tdel2** [MelvorIdle/melvoridle.github.io#4532]
### Describe the bug

A bug involving mastery tokens bugging out making all of your coins unusable and displays NaN indefinitely, as well as being unable to sell mastery tokens.

### Reproduction Steps

1. Click on any mastery token for any skill you already have 100% mastery in.
2. Try to claim/use mastery token. 
3. Token now displays as quantity "0" in bank, but is still there. Bank now displays weird "NaN" message indefinitely. Gold is unusable, token is unsellable.

### Expected behaviour

Usually, if you try to claim a token for a skill you have already mastered, you are unable to claim it, but the other weird bugs should not happen. 2 of my accounts are now unplayable because of this.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11585

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
You have run into the NaN mastery bug caused by mods that are not compatible with v1.3. Please disable your mods and only re-enable once you have confirmed they are updated and work today.

To fix the NaN issue, please follow these steps: https://www.reddit.com/r/MelvorIdle/comments/1dd3d2a/uhh_anyone_else_seeing_this_for_mastery/l82oxi8/
