### ISSUE TITLE
Item Alchemy III does not reflect in Woodcutting bonuses

### ISSUE THREAD

**Issue by Skaitavia** [MelvorIdle/melvoridle.github.io#454]
When you have 50% Mastery Pool exp for Woodcutting, you get the following bonus:

“All Logs sell for +50% GP Value”

When I go to Magic Logs and look at the sell price, it’s 450 GP, which is correct because its previous sell value before the Mastery Pool bonus is 300 GP.

Item Alchemy III states:

“Convert selected item into GP worth 160% of the item sell value.”

When I choose Magic Logs as the item for Item Alchemy III, the produced GP from that spell is 480 GP, which is 160% of the value of Magic Logs before the Mastery Pool bonus.

This value should be 720 GP (450 GP * 1.6).

Please see attached images.

Thank you.

![1A2AA19B-BDEB-4722-ACAA-29BB399D5F0E](https://user-images.githubusercontent.com/20800458/96354565-03d77700-10a6-11eb-9a62-4dffbac5ddfa.jpeg)
![0FFB4F16-D12A-407F-9E25-FF8F68C692BE](https://user-images.githubusercontent.com/20800458/96354566-05a13a80-10a6-11eb-95c9-1cd80d073e1e.jpeg)
![1AA8C8E6-8268-41F7-AC1B-3155CABEC3E4](https://user-images.githubusercontent.com/20800458/96354567-0639d100-10a6-11eb-9410-70ca847c9733.jpeg)

**Comment by MelvorIdle** [comment]
Technically you're not actually selling the item when Alching it, but I see what you mean with how Item Alchemy itself is worded.
