### ISSUE TITLE
[Bug]: Unable to restore Township health on mobile

### ISSUE THREAD

**Issue by gapplebach** [MelvorIdle/melvoridle.github.io#4541]
### Describe the bug

Playing on iOS and the buttons to restore township health do not register an action. I can click them as much as I want, in any order, and the health does not go up. 

### Reproduction Steps

1. Go to Township
2. Scroll to the township menu 
3. Click any of the buttons to restore health
4. Nothing happens

### Expected behaviour

Click the buttons should restore health

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

11585

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
You most likely cannot afford the cost to increase the Health.
