### ISSUE TITLE
[Bug]: Necromancer's crown not doubling Ectoplasm drops from Spectre

### ISSUE THREAD

**Issue by webdevguy1** [MelvorIdle/melvoridle.github.io#4542]
### Describe the bug

I have the spectre as my slayer task.  I equipped the necro crown to my passive slot and watched for several kills but I only got one ecto drop per kill.  The wiki indicates the crown should work on ecto.  I have not tested with the other two enemies that drop ectoplasm.

### Reproduction Steps

See above

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11585

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
The Wiki description was unfortunately incorrect. I've updated the Wiki page now to reflect the correct mechanics.
