### ISSUE TITLE
[Bug]: Runecrafting skillcape doesn't add to produces rune in UI, but still works.

### ISSUE THREAD

**Issue by DayKk17** [MelvorIdle/melvoridle.github.io#4543]
### Describe the bug

its only affecting the UI display where it tells you how much rune its producing for each action. If i have my cape or not its still at 16, without the cape i produce 16 and with i produce 21. So the math still works.

### Reproduction Steps

No matter how i equip the cape (from bank or from quick equip) still doesnt change the UI.

### Expected behaviour

changing the produce rune when wearing or not the skillcape.

### Screenshots

![Screenshot (26)](https://github.com/user-attachments/assets/d0e5aedd-809e-4f41-9f6a-99c3e8df5074)
![Screenshot (27)](https://github.com/user-attachments/assets/928427d9-89a2-479d-82c0-be465b4d0891)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11585

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
The "produces" quantity shows the value prior to any doubling. As the Skillcape bonuses does not work alongside doubling, it is added after the craft and won't be displayed in the UI where you circled.

**Comment by DayKk17** [comment]
Thanks for the reply! I figured after I posted that it was normal behaviour 😅 but forgot to delete (if i could) the "bug"Thanks!Le 9 août 2024 à 00:45, Melvor Idle ***@***.***> a écrit :﻿
The "produces" quantity shows the value prior to any doubling. As the Skillcape bonuses does not work alongside doubling, it is added after the craft and won't be displayed in the UI where you circled.
