### ISSUE TITLE
[Bug]: <Superior Stronghold of the gods gem droprate>>

### ISSUE THREAD

**Issue by Yelklo** [MelvorIdle/melvoridle.github.io#4545]
### Describe the bug

The drop rate is stated to be 1% but I'm not seeing it. I've ran the Superior Stronghold of the gods 603 times and have only seen 2 gems drop.

### Expected behaviour

Run the stronghold at the Superior level.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11585

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Being unlucky is not a bug.

**Comment by Yelklo** [comment]
It's not being unlucky when the 1% drop rate is a lie.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
