### ISSUE TITLE
Stuck on infinite loading screen (Mobile/PC)

### ISSUE THREAD

**Issue by dralics** [MelvorIdle/melvoridle.github.io#4551]
### Describe the bug

My game is stuck on "Fetching Account Info." I have no mods enabled, I have tried clearing cache, uninstalling/reinstalling, and verifying integrity of game files on steam. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

3.0.1

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This bug was caused by a PlayFab outage and was automatically rectified shortly thereafter
