### ISSUE TITLE
[Bug]: <title>Permanent loading for "receipt of data account"

### ISSUE THREAD

**Issue by Stanislav-PSV** [MelvorIdle/melvoridle.github.io#4552]
### Describe the bug

Permanent loading for "receipt of data account"

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11182

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This bug was caused by a PlayFab outage and was automatically rectified shortly thereafter
