### ISSUE TITLE
[Bug]: <title>This error was encountered while logging in. PlayFab API request failure，"api": "/Server/GetUserReadOnlyData"

### ISSUE THREAD

**Issue by MROBBB** [MelvorIdle/melvoridle.github.io#4553]
### Describe the bug

I couldn't log in to the game since July 31, 2024.
Stuck in the process of obtaining account information. 
I checked the message on the web version and found that the PlayFab API request failure. 
{
  "FunctionName": "checkAppOwnership",
  "Revision": 243,
  "Logs": [
    {
      "Level": "Error",
      "Message": "PlayFab API request failure",
      "Data": {
        "api": "/Server/GetUserReadOnlyData",
        "request": {
          "PlayFabId": "72CAD9DA9A84F312",
          "Keys": [
            "steamTicketTotH"
          ]
        },
        "error": "Timeout"
      }
    }
  ],
  "ExecutionTimeSeconds": 8.1547469,
  "ProcessorTimeSeconds": 0.002445,
  "MemoryConsumedBytes": 11672,
  "APIRequestsIssued": 4,
  "HttpRequestsIssued": 0,
  "Error": {
    "Error": "InternalServerError",
    "Message": "InternalServerError",
    "StackTrace": "Error\n    at Object.server_request (Script:162:24)\n    at server.GetUserReadOnlyData (Script:568:76)\n    at getCachedSteamTicket (E3855-main.js:617:25)\n    at checkOwnershipViaSteam (E3855-main.js:1242:30)\n    at handlers.checkAppOwnership (E3855-main.js:1215:23)\n    at Object.invokeFunction (Script:117:33)"
  }
}

### Save Link - Required if issue occurs with a save

https://melvoridle.com/index_mobile.php

### Console output

{
  "FunctionName": "checkAppOwnership",
  "Revision": 243,
  "Logs": [
    {
      "Level": "Error",
      "Message": "PlayFab API request failure",
      "Data": {
        "api": "/Server/GetUserReadOnlyData",
        "request": {
          "PlayFabId": "72CAD9DA9A84F312",
          "Keys": [
            "steamTicketTotH"
          ]
        },
        "error": "Timeout"
      }
    }
  ],
  "ExecutionTimeSeconds": 8.1547469,
  "ProcessorTimeSeconds": 0.002445,
  "MemoryConsumedBytes": 11672,
  "APIRequestsIssued": 4,
  "HttpRequestsIssued": 0,
  "Error": {
    "Error": "InternalServerError",
    "Message": "InternalServerError",
    "StackTrace": "Error\n    at Object.server_request (Script:162:24)\n    at server.GetUserReadOnlyData (Script:568:76)\n    at getCachedSteamTicket (E3855-main.js:617:25)\n    at checkOwnershipViaSteam (E3855-main.js:1242:30)\n    at handlers.checkAppOwnership (E3855-main.js:1215:23)\n    at Object.invokeFunction (Script:117:33)"
  }
}

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari
- [X] Steam
- [X] Epic Games
- [X] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11182

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This bug was caused by a PlayFab outage and was automatically rectified shortly thereafter
