### ISSUE TITLE
[Bug]: Unobtainable Completion Log items in Demo version

### ISSUE THREAD

**Issue by LindaS993** [MelvorIdle/melvoridle.github.io#4555]
### Describe the bug

These items appear in the **Demo Version** Completion Log, but they are unobtainable, as they are **Full Version** items:
- Light Rune
- Mist Rune
- Dust Rune
- Smoke Rune
- Blood Rune

### Expected behaviour

- Should not appear in the Demo Version Completion Log.

### Screenshots

![Screenshot_20240802-155823_Iceraven](https://github.com/user-attachments/assets/9ecdbc9a-7675-4bd5-ab6d-467af57592b4)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11585

### Are you using any mods?

No

**Comment by johnkuyt** [comment]
Bump - I am also experiencing the same issue.

**Comment by LindaS993** [comment]
@TheMalcs @MelvorIdle This is a quick and easy thing to fix. Bump.
