### ISSUE TITLE
[Bug]: <title>考古學118無法找到

### ISSUE THREAD

**Issue by pan71136** [MelvorIdle/melvoridle.github.io#4557]
### Describe the bug

考古學118無法找到並開啟

### Screenshots

![IMG_5912](https://github.com/user-attachments/assets/44387348-9753-4637-a7e8-7b969b784674)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

？11585

### Are you using any mods?

Yes

**Comment by Flurryous** [comment]
You need to follow the clues to unlock the 118 area. 

https://wiki.melvoridle.com/w/Melantis_Clue_1
