### ISSUE TITLE
Farming Mastery Seed Returns Inaccurate

### ISSUE THREAD

**Issue by breadbocks** [MelvorIdle/melvoridle.github.io#456]
**Describe the bug**
The farming mastery seed return rewards are misleading for 16, 31, 46, 61, 76, 91, and false for 99. For the non-99 masteries, they do not indicate that the most recently unlocked amount is less likely based on the mastery level. For the 99 mastery, an outcome of 8 seeds returned is impossible.

**To Reproduce**
From the farming mastery code:
`if (masteryLevel >= 15 && items[seed].tier != "Tree") {
    let seedQty = Math.floor(Math.random() * (masteryLevel / 15));
    if (masteryLevel >= 99) seedQty = Math.floor(Math.random() * 8);
    if (seedQty > 0) addItemToBank(newFarmingAreas[areaID].patches[patchID].seedID, seedQty);
}`
**Expected behavior**
For the first seedQty result:
`let seedQty = Math.floor(Math.random() * (Math.floor(masteryLevel / 15)+1));`
will normalize seed returns such that, for example, at level 60, 0-4 are equally likely outcomes for the seed return. This will have the side effect of lowing current mastery unlocks back to even multiples of 15. If the current scaling behavior of highest reward is intended, disregard this change

For the second issue, 
`if (masteryLevel >= 99) seedQty = Math.floor(Math.random() * 9);` 
will fix the behavior of never giving an 8th seed, while simply changing the 99 mastery perk text to read "Receive up to **7** Allotment or Herb seeds back from harvesting" will fix the false text without buffing the perk if undesired. 

**Screenshots**

**Browser**
Vivaldi 3.something

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Hotfixed :)
