### ISSUE TITLE
[Bug]: Base Artefact value in Archaeology doesn't seem to change with 99 mastery 

### ISSUE THREAD

**Issue by Flurryous** [MelvorIdle/melvoridle.github.io#4563]
### Describe the bug

One of the bonuses for having 99 mastery with a digsite in Archaeology is that the base artefact value is reduced by 3 for that digsite's maps. However, it seems like the bonus is not working at all. 

### Reproduction Steps

1. Have 99 mastery in a digsite.
2. Create a map for that digsite.
3. Check that the artefact values for that map are all 69, which is the base value for a poor map without 99 mastery. 

### Expected behaviour

The bonus either needs to be working or the description should be removed from Archaeology's list of item mastery unlocks if this bonus is not supposed to exist. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11585

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Can you please provide as save so we can look into it? I cannot reproduce this bug on my end.

**Comment by Flurryous** [comment]
Here's my save copy: https://melvoridle.com/save/IuBZXipk

I've had full mastery in Arch for several months and created a second map for Cathedral yesterday. It's a poor tier map with 69 artefact values across the board. Relogging has not changed those values.
