### ISSUE TITLE
[Bug]: Unable to purchase "Slayer Gear Upgrade Kit (Strong)"

### ISSUE THREAD

**Issue by IQAndreas** [MelvorIdle/melvoridle.github.io#4567]
### Describe the bug

I am unable to purchase the `Slayer Gear Upgrade Kit (Strong)` even after meeting requirements.

The requirements are:
_Unlocks after 7 more Hard or higher Slayer Task Completions_
_50,000 slayer coins_
![slayer bug 1](https://github.com/user-attachments/assets/fea0c0c9-e5e0-4453-8e5d-d54e5241ffeb)

I have completed 17 hard slayer tasks (and have **plenty** of slayer coins):
![slayer bug 2](https://github.com/user-attachments/assets/0b0442d6-d536-42b9-9e9e-399142be455b)
Yet, I am unable to purchase the upgrade kit.

### Reproduction Steps

1. Complete 7 or more Hard Slayer Tasks
2. Earn 50,000 or more Slayer Coins
3. Go to shop to purchase `Slayer Gear Upgrade Kit (Strong)`
4. Item cannot be purchased

### Expected behaviour

`Slayer Gear Upgrade Kit (Strong)` should be able to be purhcased in the shop

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/5wKDquWe

### Screenshots

![slayer bug 1](https://github.com/user-attachments/assets/fea0c0c9-e5e0-4453-8e5d-d54e5241ffeb)
![slayer bug 2](https://github.com/user-attachments/assets/0b0442d6-d536-42b9-9e9e-399142be455b)

### Console output

```
Failed to load resource: the server responded with a status of 404 ()
cloudManager.js?11585:329 Silent Sign in with JWT
cloudManager.js?11585:329 Validating Melvor Cloud token
cloudManager.js?11585:329 Storing Melvor Cloud Token
cloudManager.js?11585:329 Initializing PlayFab login. Method: customID
cloudManager.js?11585:329 Logging in with Custom ID via PlayFab
cloudManager.js?11585:329 Login with custom ID success
cloudManager.js?11585:329 Getting account info
cloudManager.js?11585:329 Account info retrieved
cloudManager.js?11585:329 Authenticated w/ Melvor Cloud: true
cloudManager.js?11585:329 Authenticated w/ PlayFab: true
cloudManager.js?11585:329 Checking for valid full version
cloudManager.js?11585:329 Checking for valid TotH purchase
cloudManager.js?11585:329 Checking for valid Atlas of Discovery purchase
cloudManager.js?11585:329 Checking for valid Into the Abyss purchase
cloudManager.js?11585:329 Getting keys from playfab
cloudManager.js?11585:329 Loading Game Data...
cloudManager.js?11585:83 Registered Demo Data.
cloudManager.js?11585:83 Registered Full Version Data.
cloudManager.js?11585:329 Initializing Mod Manager...
cloudManager.js?11585:329 Checking for Mod Updates...
cloudManager.js?11585:329 Loading Mods...
cloudManager.js?11585:329 Loading Mods (1/5): ETA (v1.1.36)
cloudManager.js?11585:329 Loading Mods (2/5): Mastery Pool Can Overflow (v13.3)
cloudManager.js?11585:329 Loading Mods (3/5): QuickShards (v1.1.2)
cloudManager.js?11585:329 Loading Mods (4/5): Item Uses (v1.0.4)
cloudManager.js?11585:329 Loading Mods (5/5): Unlimited Offline (v0.1.6)
cloudManager.js?11585:329 Loading Local Saves...
cloudManager.js?11585:329 Loading Cloud Saves...
cloudManager.js?11585:329 Getting saves from playfab
cloudManager.js?11585:329 Saves retrieved
characterSelect.js?11585:5 Loading character selection
cloudManager.js?11585:468 Connected to PlayFab successfully
main.js?11585:18 Game Loaded
cloudManager.js?11585:468 Connected to PlayFab successfully
cloud.js?11585:91 updatePlayerTags
style.css:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
0be5d90f-946e-4970-a3ac-e8ddb5b71fbb:586 ETA : Loading...
0be5d90f-946e-4970-a3ac-e8ddb5b71fbb:586 ETA : added settings menu!
0be5d90f-946e-4970-a3ac-e8ddb5b71fbb:586 ETA : Loaded!
cloudManager.js?11585:329 PlayFab save updated successfully
```

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11585

### Are you using any mods?

Yes

**Comment by Ayarez** [comment]
8 more, so 25 total, not 8 or more
