### ISSUE TITLE
[Bug]: <Abyssal Farming will complete infinite times with no cooldown>

### ISSUE THREAD

**Issue by Vincze-Farago-Zsolt** [MelvorIdle/melvoridle.github.io#4569]
### Describe the bug

I can plant all and instantly harvest after with no time spent waiting for the plots to grow. The seeds, etc. do get used in the process.

### Reproduction Steps

1. Go to Farming
Any section of the 4 - Allotments, Herbs, Trees, or Special
3. Plant all 
4. Notice how you can harvest immediately after planting. 

Extra information: I am on Ancient Relics mode, and I had Gloomgrowth Potion IV active, and after disabling it, I encountered the above issue. Please also check my save game:

(https://melvoridle.com/save/xEbaiSWp)

### Expected behaviour

Time should pass for plots to grow.

### Save Link - Required if issue occurs with a save

ttps://melvoridle.com/save/xEbaiSWp

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11585

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
I can't seem to reproduce this bug on the save provided. Does this issue still occur for you?

**Comment by Vincze-Farago-Zsolt** [comment]
It stopped occurring and I can't seem to reproduce it. Must of been a one time thing.
