### ISSUE TITLE
[Translation Error]: <title> Amulet of Incantation

### ISSUE THREAD

**Issue by SeigneurLancelot** [MelvorIdle/melvoridle.github.io#4576]
### Which text in the game has a translation error?

The description for the Amulet of Incantation is " UNDEFINED TRANSLATION: :ITEM_DESCRIPTION_Amulet_Of_Incantation " I am playing Standard Mode in english, on desktop with the Epic Game Store.

**Comment by goodtk** [comment]
Also, seems that the effect of the amulet doesn't work.
