### ISSUE TITLE
[Bug]: <golbin raid weapon bug>

### ISSUE THREAD

**Issue by Froggy123000** [MelvorIdle/melvoridle.github.io#4577]
### Describe the bug

In golbin raid after equipping royal toxins sphere, it didn’t apply the effects, instead it applied the effects of a slingshot. 

### Screenshots

![IMG_4647](https://github.com/user-attachments/assets/a9d9c732-3fc7-4cc0-a2dc-32252ec68987)
![IMG_4646](https://github.com/user-attachments/assets/13060b57-7e62-43cc-b9a1-2508286626d6)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11742

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
You picked an (ALT) weapon, which has a random special attack. Working as intended.
