### ISSUE TITLE
[Bug]: <Ancient Relic 1 for Abyssal Summoning not functioning>

### ISSUE THREAD

**Issue by DudeInATunic** [MelvorIdle/melvoridle.github.io#4578]
### Describe the bug

Ancient Relic 1 for Abyssal Summoning is not functioning properly. It claims that costs (other than shards) are reduced by 50%. However nothing changed. The leprechaun is still 1000 AP, the cyclops is still 500 abyssal slayer coins, bear is still 50 herbs, etc.

If the intent is shard cost reduction, that should be more clear. The skill tree specifically distinguishes between the two, and says "shard cost reduction" 

### Reproduction Steps

Reproduce by checking item costs for summoning. Then activate Ancient Relic 1 for Abyssal Summoning 

### Expected behaviour

Costs should be half

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11742

### Are you using any mods?

No

**Comment by 04Slash** [comment]
The base cost for Abyssal Leprechaun is 5,000 AP. If your cost is at 1,000 AP then you've hit the cap of 80% cost reduction.

This relic is not shown in the cost reduction sources which has been reported: #4453
