### ISSUE TITLE
[Bug]: <Unable to fulfill completion log for Herblore.>

### ISSUE THREAD

**Issue by recline187** [MelvorIdle/melvoridle.github.io#4582]
### Describe the bug

Completion log for base game requires Melee Evasion Potion(and other potions) tiers: I, II, III and IV. A player can spend several points of Mastery XP mastering a potion from Tier I to Tier IV without ever crafting a potion. This leaves a player unable to fulfill the crafting requirement for Tier I, II or III. This locks out progression for Cape of Completion.

### Reproduction Steps

Step 1: Craft potions.
Step 2: Use mastery experience to move past tier 2 for a potion a player has never crafted. This gives the player the ability to craft tier 3 potions.
Step 3: Craft a tier 3 potion, never being able to craft Tier 2.

### Expected behaviour

Crafting a tier IV potion should qualify as crafting a tier I, II and III potion as well.
If not possible, the ability to craft separate tiers of potions, or the ability to downgrade a potion should be possible (even though it's never beneficial). 

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/584n3PWH

### Screenshots

![potion-bugtier4](https://github.com/user-attachments/assets/3ae92e5d-201a-422e-b145-02d6c2c2b144)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

V1.3 (?11743)

### Are you using any mods?

Yes

**Comment by Ayarez** [comment]
![image](https://github.com/user-attachments/assets/3a7ffe0c-42e4-40c1-9b89-09f439273852)
Thats why these exist

They give a chance to get a random tier potion of the potion you're crafting when crafting potions
