### ISSUE TITLE
[Bug]: <title>NaN Money & Slayer Points

### ISSUE THREAD

**Issue by DankSAK** [MelvorIdle/melvoridle.github.io#4588]
### Describe the bug

NaN for money and Slayer Points. 

Randomly lost all 

### Reproduction Steps

Login to account

### Screenshots

![Screenshot_20240821-191420](https://github.com/user-attachments/assets/0ebd6182-6f5f-45de-ba18-553825aafdd6)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11743

### Are you using any mods?

No

**Comment by 04Slash** [comment]
Have you used mods at any point? If so, which mods?

Providing the save URL might be useful since this issue is specific to your save.
