### ISSUE TITLE
Skill Capes

### ISSUE THREAD

**Issue by mrDLSable** [MelvorIdle/melvoridle.github.io#46]
Having Skill capes would be nice. This could be another gp sink. For a price I would think somewhere between 1 and 5 mil gp each. And, of course, there could then be trimmed versions which would cost event more to make.

As for what they would do, I think a nice bonus would be a mastery xp bonus while wearing it.

Some quick calculations with the price:
- If they are 1 mil each: 15 mil
- If silver trimming costs 2.5 mil each: 37.5 mil
- If gold trimming costs 10 mil each: 150 mil

Then this would be a gold sink of more than 200 mil and give us some nice collectibles to take up bank slots which we will then have to buy again...

**Comment by MelvorIdle** [comment]
Skillcapes are coming in v0.10
