### ISSUE TITLE
[Bug]: Wandering Bard does not appear in Ancient Relics mode

### ISSUE THREAD

**Issue by Vela-RUS** [MelvorIdle/melvoridle.github.io#4607]
### Describe the bug

I did more than 1000+ easy tasks in auto-slayer mode - no bard. Needs checking please.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11753

### Are you using any mods?

No

**Comment by Ayarez** [comment]
It's a normal task, not an easy one
