### ISSUE TITLE
[Bug]: Cannot load save in Beta

### ISSUE THREAD

**Issue by MiccWan** [MelvorIdle/melvoridle.github.io#4609]
### Describe the bug

In the Beta server, an error occurred while loading save.

I tried to trace the bug and found the problem in the `recipeSelection.js:102`.
The `RealmedCategoryMenuElement.realmNameClass` defaults to `""` and `setRealmNameColour` tried to remove the default class.
But `classList.remove` throws an error(`Failed to execute 'remove' on 'DOMTokenList': The token provided must not be empty.`) when argument is empty string,

![image](https://github.com/user-attachments/assets/a3c98d25-21b6-4a73-bf4b-ea7dbd510b02)

Full log:
```
An error occured while loading your save:
Error Name: SyntaxError
Error Message: Failed to execute 'remove' on 'DOMTokenList': The token provided must not be empty.
Stack Trace:
Error: Failed to execute 'remove' on 'DOMTokenList': The token provided must not be empty.
    at RealmedCategoryMenuElement.setRealmNameColour (https://melvoridle.com/beta/assets/js/built/recipeSelection.js?11895:102:55)
    at RealmedCategoryMenuElement.addOptions (https://melvoridle.com/beta/assets/js/built/recipeSelection.js?11895:101:93)
    at initMenus (https://melvoridle.com/beta/assets/js/built/combat.js?11895:8:2806)
    at https://melvoridle.com/beta/assets/js/built/save.js?11895:123:563
    at Generator.next (<anonymous>)
    at fulfilled (https://melvoridle.com/beta/assets/js/built/nativeManager.js?11895:2:98)

Modding Enabled. Loaded mods:
```

### Reproduction Steps

1. Load any save in [Beta server](https://melvoridle.com/beta/index_game.php).
2. The error pop up.

### Expected behaviour

Load the save successfully.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/ay5Ivp1H

### Screenshots

![image](https://github.com/user-attachments/assets/726508bb-7ea1-4f68-94dd-c7df9d659941)

### Console output

Failed to load resource: the server responded with a status of 404 ()Understand this error
index_game.php:1 [DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) <input type=​"password" class=​"form-control form-control-lg form-control-alt py-4" id=​"formElements-characterSelect-changePassword-currentPassword" name=​"formElements-characterSelect-changePassword-currentPassword">​
index_game.php:1 [DOM] Input elements should have autocomplete attributes (suggested: "new-password"): (More info: https://goo.gl/9p2vKq) <input type=​"password" class=​"form-control form-control-lg form-control-alt py-4" id=​"formElements-characterSelect-changePassword-newPassword" name=​"formElements-characterSelect-changePassword-newPassword">​
index_game.php:1 [DOM] Input elements should have autocomplete attributes (suggested: "new-password"): (More info: https://goo.gl/9p2vKq) <input type=​"password" class=​"form-control form-control-lg form-control-alt py-4" id=​"formElements-characterSelect-changePassword-confirmNewPassword" name=​"formElements-characterSelect-changePassword-confirmNewPassword">​
cloudManager.js?11895:329 Silent Sign in with JWT
cloudManager.js?11895:329 Validating Melvor Cloud token
cloudManager.js?11895:329 Storing Melvor Cloud Token
cloudManager.js?11895:329 Initializing PlayFab login. Method: customID
cloudManager.js?11895:329 Logging in with Custom ID via PlayFab
cloudManager.js?11895:329 Login with custom ID success
cloudManager.js?11895:329 Getting account info
cloudManager.js?11895:329 Account info retrieved
cloudManager.js?11895:329 Authenticated w/ Melvor Cloud: true
cloudManager.js?11895:329 Authenticated w/ PlayFab: true
cloudManager.js?11895:329 Checking for valid full version
cloudManager.js?11895:329 Checking for valid TotH purchase
cloudManager.js?11895:329 Checking for valid Atlas of Discovery purchase
cloudManager.js?11895:329 Checking for valid Into the Abyss purchase
cloudManager.js?11895:329 Getting keys from playfab
cloudManager.js?11895:329 Loading Game Data...
cloudManager.js?11895:83 Registered Demo Data.
cloudManager.js?11895:83 Registered Full Version Data.
cloudManager.js?11895:85 Registered Throne of the Herald Data.
cloudManager.js?11895:86 Registered Atlas of Discovery Data.
cloudManager.js?11895:87 Registered Into the Abyss Data.
cloudManager.js?11895:329 Initializing Mod Manager...
cloudManager.js?11895:329 Checking for Mod Updates...
cloudManager.js?11895:329 Loading Mods...
cloudManager.js?11895:329 Loading Local Saves...
cloudManager.js?11895:329 Loading Cloud Saves...
cloudManager.js?11895:329 Getting saves from playfab
cloudManager.js?11895:329 Saves retrieved
characterSelect.js?11895:5 Loading character selection
cloudManager.js?11895:468 Connected to PlayFab successfully
style.css:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()Understand this error

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3.1 (Beta)

### Game Subversion

v1.3.1 ?11895

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Thanks for the report. The issue is now hotfixed on the Beta server.
