### ISSUE TITLE
cannot cast combat spells with wand

### ISSUE THREAD

**Issue by cowboybibimbap** [MelvorIdle/melvoridle.github.io#461]
**Describe the bug**
I cannot cast combat (elemental) spells of any kind when I have a wand of any kind equipped, with the message "you do not have enough runes" when I have 10,000s of the appropriate runes. Spells cast as usual when I unequip wand or equip a staff.

**To Reproduce**
1. Equip wand (powerful)
2. Go to combat screen
3. Engage with any enemy
4. Select spell from spellbook

**Expected behavior**
Spells cast as usual, dealing damage to enemy HP

**Screenshots**

**Browser**
Both mobile app and Google Chrome (current version)

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

**Comment by arielessar** [comment]
Hi, I am adding on to this as I also have the issue except with staffs. I am using chrome as well, attached are some screen shots. I am not using scripts
![not enough runes alt](https://user-images.githubusercontent.com/31738437/99969974-2fb2e000-2d69-11eb-9bf9-7ff397c7b46d.PNG)
![not enough runes](https://user-images.githubusercontent.com/31738437/99969976-304b7680-2d69-11eb-8992-1eb6dec31aa3.PNG)


**Here is my console output:**
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
widget.png:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
index.php?l=1:1 [DOM] Found 2 elements with non-unique id #bank-sell-x: (More info: https://goo.gl/9p2vKq) <input type=​"text" class=​"form-control" id=​"bank-sell-x" name=​"bank-sell-x" placeholder=​"Sell x">​ <input type=​"text" class=​"form-control m-1" id=​"bank-sell-x" name=​"bank-sell-x" placeholder=​"Sell x">​
melvorcdn.fra1.cdn.digitaloceanspaces.com/current/assets/media/shop/assets/media/shop/perpetual_haste.svg:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
v017_bank_tabs.png:1 Failed to load resource: the server responded with a status of 404 ()
v017_bank_sidebar.png:1 Failed to load resource: the server responded with a status of 404 ()
v017_bank_sell_mode.png:1 Failed to load resource: the server responded with a status of 404 ()
save.js?549:8 Loading Save Game...
save.js?549:24 Save Game Loaded...
smithing2.js?549:9 Loading Smithing...
mastery.js?549:2 Loading Masteries...
main.js?549:6 Game Loaded
main.js?549:197 Array(1)
/cloud/versionCheck.php:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://melvorcdn.fra1.cdn.digitaloceanspaces.com/sm/13c28911820333eb6a51103a0e2096477a38941cc79afbf16b59f3d5a5f63086.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://melvorcdn.fra1.cdn.digitaloceanspaces.com/current/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://melvorcdn.fra1.cdn.digitaloceanspaces.com/current/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://melvorcdn.fra1.cdn.digitaloceanspaces.com/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by arielessar** [comment]
Actually something I just noticed, I had use combo runes enabled. Removing that allows it to work again. @cowboybibimbap might want to try that and see if it works.
