### ISSUE TITLE
Unable to claim any mastery tokens

### ISSUE THREAD

**Issue by SarcasticNoob** [MelvorIdle/melvoridle.github.io#4621]
### Describe the bug

Unable to claim mastery tokens.  I do not have any mods installed 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11753

### Are you using any mods?

No

**Comment by LindaS993** [comment]
Is the skill in question's Mastery Pool at 100%? If so you can't claim tokens until you spend some of your Mastery Pool XP.
