### ISSUE TITLE
[Bug]: <title> Wrong special attacks listed and used in the Golbin Raid

### ISSUE THREAD

**Issue by Nick2718** [MelvorIdle/melvoridle.github.io#4622]
### Describe the bug

I have wrong special attacks being listed and being used in Golbin Raid. I have Torrential Blast Crossbow and Meteorite Bolts equipped. Special attacks being used: Ghostly Scimitar; Corundum wounds.

### Reproduction Steps

1. Go to Golbin Raid; 2. See special attacks.

### Expected behaviour

Special attacks being shown: Ghostly Scimitar; Corundum wounds.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/eGHzZqxR

### Screenshots

![photo_2024-09-03_20-08-04](https://github.com/user-attachments/assets/c6e9fbe7-445b-43a9-9b35-0e52aba5fbdb)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11753

### Are you using any mods?

No

**Comment by Flurryous** [comment]
Items in golbin raid can roll specials of other items. They're usually tagged with  "ALT" during the item selection window, if I recall correctly.
