### ISSUE TITLE
[Bug]: Runecrafting mastery bonuses aren't clear

### ISSUE THREAD

**Issue by SolidKalium** [MelvorIdle/melvoridle.github.io#4626]
### Describe the bug

The Runecrafting Mastery Unlocks reduce rune cost for runecrafting items.
These stack additively with cost reduction, but only for runes. The 80% cost reduction cap is shared between normal cost reduction and rune-specific cost reduction. This isn't obvious in-game without experimenting.

Edit: Also, the text of the Unlocks say "cannot be reduced below 1", but it the truth is that they can't be reduced below 20% of the original cost.

### Expected behaviour

I don't know what the "correct" behavior is, but I don't think the current behavior is ideal.

- IMO if an item's cost is only runes, then the mastery bonus should be included in the cost reduction box.
- Potentially, the rune-specific cost reduction could be labelled in a separate section of the cost reduction box. This would be similar to interval reductions having separate sections for % and seconds, except that instead of two modifiers on a single value, it would be modifiers on different kinds of values (rune vs. non-rune cost).
- Potentially, the cost reduction being specific to runes could be expanded to all resources. This would impact the following resources: logs (probably ok), runestones, wands and staves, meteorite bars. So that might end up being too broad and impact the intended balance.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11765

### Are you using any mods?

No

**Comment by sluki** [comment]
I think this is related to cost reduction from pre-ITA content not being displayed for summoning and runecrafting. I mean for summoning it says I have 25% cost reduction but I am actually capped at 80% because of mastery and summoning relic 5 from melvor realm.

**Comment by sluki** [comment]
What about summoning? Basically same issue, but it was not fixed.
