### ISSUE TITLE
[Bug]: Prayer XP only earned on first of multiple hits

### ISSUE THREAD

**Issue by SolidKalium** [MelvorIdle/melvoridle.github.io#4627]
### Describe the bug

When using a weapon with multiple attacks in a single turn, only the initial hit gives prayer XP. But other skills like health and strength get XP on all hits, and when I have bonuses that give me Abyssal Slayer Coins for damage, I also get those on both hits.

### Reproduction Steps

1. Equip a weapon with a special attack that can do multiple hits
2. Equip prayers that give xp
3. Fight an enemy
4. Observe that when multiple hits land after a special attack, you get multiple ticks of xp for every involved skill except prayer

### Expected behaviour

When I attack and deal damage that gains xp, all involved skills should gain xp.

### Screenshots

In the screenshot I'm using a Witherite Dagger (2 avoidable attacks that deal 105% of my normal damage over 0.5s). I have Ravage and Cruelty prayers active. I first noticed this earlier in the expansion, so it's not specific to this weapon and these prayers.

<img width="284" alt="Screenshot 2024-09-04 at 12 04 08 PM" src="https://github.com/user-attachments/assets/2015b0df-f0a1-4e76-aef4-b8aa4c66b850">

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11765

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This is intended. Prayer XP is only gained "per Attack" (as per the Prayer tooltip) instead of "per Hit".
