### ISSUE TITLE
Superheat II is broken

### ISSUE THREAD

**Issue by Firesparq** [MelvorIdle/melvoridle.github.io#463]
**Describe the bug**
The Superheat II alt magic spell doesn't always function; sometimes getting to the end of the use action bar, and reporting "missing materials for spell".

It should be noted I can fix this issue by selecting an alternative alt spell to cast (not necessarily begin casting), and select Superheat II again. 

**To Reproduce**
1. Have Nature and Earth runes available in bank
2. Equip a fire battlestaff (to provide the required three fire runes)
3. Have enough adamantite, and coal ore
4. Select adamantite bars as superheat target
5. See error

**Expected behavior**
 The "You do not have the required raw materials to Cast that" error pops up.

**Browser**
Firefox 82.0 (64-bit)

**Console output**

> Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-129674422-1”. melvoridle.com:6:1
Loading failed for the <script> with source “https://ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js”. melvoridle.com:25:1
Loading Save Game... save.js:56:10
Save Game Loaded... save.js:195:10
Loading Smithing... smithing2.js:203:10
Loading Masteries... mastery.js:23:10
Game Loaded main.js:392:11
Connected to PlayFab successfully cloud.js:516:11
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Should be fixed in v0.18
