### ISSUE TITLE
[Bug]: Trapped in goblin raid can't quit

### ISSUE THREAD

**Issue by MrMao14** [MelvorIdle/melvoridle.github.io#4632]
### Describe the bug

Cant quit the goblin raid and my HP always keep in 100/2120
I can use pause but cant use quit
Click button has no effect
![image](https://github.com/user-attachments/assets/1378ee83-ba3a-457a-b983-0f83e0a95d5f)

### Reproduction Steps

I dont know how to reproduction
maybe use skip and choose weapon method in console

### Expected behaviour

Cant quit goblin raid
Sometime can't get afk items and exps
ATK sometime and back get nothing

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/1J9xWKDw

### Screenshots

![image](https://github.com/user-attachments/assets/56e8193a-9c61-4a6d-95f8-5bf40964dfb2)

### Console output

index_game.php:41 
        
        
        GET https://melvoridle.com/style.css?2 net::ERR_ABORTED 404 (Not Found)
index.js:2589 
        
        
        GET https://melvoridle.com/assets/css/assets/media/main/bg_9.jpg 404 (Not Found)
getOKResponse @ index.js:2589
loadAsDataURL @ index.js:2608
getDataURL @ index.js:2706
(匿名) @ index.js:2672
getImageDetails @ index.js:2667
(匿名) @ index.js:3481
await in (匿名)
(匿名) @ index.js:3610
(匿名) @ index.js:3610
(匿名) @ index.js:5429
(匿名) @ index.js:5426
modifySheet @ index.js:5307
buildOverrides @ index.js:5984
render @ index.js:5997
(匿名) @ index.js:7433
createDynamicStyleOverrides @ index.js:7432
runDynamicStyle @ index.js:7535
createThemeAndWatchForUpdates @ index.js:7543
success @ index.js:7784
ready @ index.js:7797
createOrUpdateDynamicThemeInternal @ index.js:7801
createOrUpdateDynamicTheme @ index.js:7745
onMessage @ index.js:8243
显示 22 更多框架
显示简略信息
index.js:2650 [Violation]'requestAnimationFrame' handler took 116ms
index_game.php:1 [DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://www.chromium.org/developers/design-documents/create-amazing-password-forms) <input type=​"password" class=​"form-control form-control-lg form-control-alt py-4" id=​"formElements-characterSelect-changePassword-currentPassword" name=​"formElements-characterSelect-changePassword-currentPassword">​
index_game.php:1 [DOM] Input elements should have autocomplete attributes (suggested: "new-password"): (More info: https://www.chromium.org/developers/design-documents/create-amazing-password-forms) <input type=​"password" class=​"form-control form-control-lg form-control-alt py-4" id=​"formElements-characterSelect-changePassword-newPassword" name=​"formElements-characterSelect-changePassword-newPassword">​
index_game.php:1 [DOM] Input elements should have autocomplete attributes (suggested: "new-password"): (More info: https://www.chromium.org/developers/design-documents/create-amazing-password-forms) <input type=​"password" class=​"form-control form-control-lg form-control-alt py-4" id=​"formElements-characterSelect-changePassword-confirmNewPassword" name=​"formElements-characterSelect-changePassword-confirmNewPassword">​
cloudManager.js?11765:329 Silent Sign in with JWT
cloudManager.js?11765:329 Validating Melvor Cloud token
cloudManager.js?11765:329 Storing Melvor Cloud Token
cloudManager.js?11765:329 Initializing PlayFab login. Method: customID
cloudManager.js?11765:329 Logging in with Custom ID via PlayFab
cloudManager.js?11765:329 Login with custom ID success
cloudManager.js?11765:329 Getting account info
cloudManager.js?11765:329 Account info retrieved
cloudManager.js?11765:329 Authenticated w/ Melvor Cloud: true
cloudManager.js?11765:329 Authenticated w/ PlayFab: true
cloudManager.js?11765:329 Checking for valid full version
cloudManager.js?11765:329 Checking for valid TotH purchase
cloudManager.js?11765:329 Checking for valid Atlas of Discovery purchase
cloudManager.js?11765:329 Checking for valid Into the Abyss purchase
cloudManager.js?11765:329 Getting keys from playfab
cloudManager.js?11765:329 Loading Game Data...
cloudManager.js?11765:83 Registered Demo Data.
cloudManager.js?11765:83 Registered Full Version Data.
cloudManager.js?11765:85 Registered Throne of the Herald Data.
cloudManager.js?11765:86 Registered Atlas of Discovery Data.
cloudManager.js?11765:87 Registered Into the Abyss Data.
cloudManager.js?11765:329 Initializing Mod Manager...
cloudManager.js?11765:329 Checking for Mod Updates...
cloudManager.js?11765:329 Loading Mods...
cloudManager.js?11765:329 Loading Local Saves...
cloudManager.js?11765:329 Loading Cloud Saves...
cloudManager.js?11765:329 Getting saves from playfab
cloudManager.js?11765:329 Saves retrieved
characterSelect.js?11765:5 Loading character selection
cloudManager.js?11765:468 Connected to PlayFab successfully
index.js:460 [Violation]'setTimeout' handler took 214ms
[Violation]Added non-passive event listener to a scroll-blocking <某些> 事件. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation]Added non-passive event listener to a scroll-blocking <某些> 事件. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation]Added non-passive event listener to a scroll-blocking <某些> 事件. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation]Added non-passive event listener to a scroll-blocking <某些> 事件. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation]Added non-passive event listener to a scroll-blocking <某些> 事件. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation]Added non-passive event listener to a scroll-blocking <某些> 事件. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation]Added non-passive event listener to a scroll-blocking <某些> 事件. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation]Added non-passive event listener to a scroll-blocking <某些> 事件. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation]Added non-passive event listener to a scroll-blocking <某些> 事件. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation]Added non-passive event listener to a scroll-blocking <某些> 事件. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation]Added non-passive event listener to a scroll-blocking <某些> 事件. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation]Added non-passive event listener to a scroll-blocking <某些> 事件. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation]Added non-passive event listener to a scroll-blocking <某些> 事件. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation]Added non-passive event listener to a scroll-blocking <某些> 事件. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation]Added non-passive event listener to a scroll-blocking <某些> 事件. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation]Added non-passive event listener to a scroll-blocking <某些> 事件. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation]Added non-passive event listener to a scroll-blocking <某些> 事件. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation]Added non-passive event listener to a scroll-blocking <某些> 事件. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation]Added non-passive event listener to a scroll-blocking <某些> 事件. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation]Added non-passive event listener to a scroll-blocking <某些> 事件. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation]Added non-passive event listener to a scroll-blocking <某些> 事件. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation]Added non-passive event listener to a scroll-blocking <某些> 事件. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
main.js?11765:17 Game Loaded
cloudManager.js?11765:468 Connected to PlayFab successfully
cloud.js?11765:91 updatePlayerTags
index.js:460 [Violation]'setTimeout' handler took 425ms
[Violation]'setInterval' handler 用时 <N> 毫秒
[Violation]'setInterval' handler 用时 <N> 毫秒
[Violation]'setInterval' handler 用时 <N> 毫秒
[Violation]'setInterval' handler 用时 <N> 毫秒
[Violation]'setInterval' handler 用时 <N> 毫秒
[Violation]'setInterval' handler 用时 <N> 毫秒
[Violation]'setInterval' handler 用时 <N> 毫秒
[Violation]'setInterval' handler 用时 <N> 毫秒
[Violation]'setInterval' handler 用时 <N> 毫秒
[Violation]'setInterval' handler 用时 <N> 毫秒
[Violation]Forced reflow while executing JavaScript 用时 <N> 毫秒
[Violation]Forced reflow while executing JavaScript 用时 <N> 毫秒
[Violation]Forced reflow while executing JavaScript 用时 <N> 毫秒
[Violation]Forced reflow while executing JavaScript 用时 <N> 毫秒
[Violation]Forced reflow while executing JavaScript 用时 <N> 毫秒
[Violation]Forced reflow while executing JavaScript 用时 <N> 毫秒
[Violation]Forced reflow while executing JavaScript 用时 <N> 毫秒
[Violation]Forced reflow while executing JavaScript 用时 <N> 毫秒
[Violation]Forced reflow while executing JavaScript 用时 <N> 毫秒
[Violation]Forced reflow while executing JavaScript 用时 <N> 毫秒
[Violation]Forced reflow while executing JavaScript 用时 <N> 毫秒
[Violation]Forced reflow while executing JavaScript 用时 <N> 毫秒
[Violation]Forced reflow while executing JavaScript 用时 <N> 毫秒
[Violation]Forced reflow while executing JavaScript 用时 <N> 毫秒
[Violation]Forced reflow while executing JavaScript 用时 <N> 毫秒
[Violation]Forced reflow while executing JavaScript 用时 <N> 毫秒
[Violation]Forced reflow while executing JavaScript 用时 <N> 毫秒
[Violation]Forced reflow while executing JavaScript 用时 <N> 毫秒
oneui.core.min.js:6 [Violation]'setTimeout' handler took 60ms
notifications.js?11765:106 [Violation]'setTimeout' handler took 77ms

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11765

### Are you using any mods?

Yes

**Comment by MrMao14** [comment]
If you can pls help me delete current goblin raid progress rate,thanks

**Comment by 04Slash** [comment]
You should be able to stop the golbin raid by entering the following into the console:
```js
game.golbinRaid.isActive = true;
game.golbinRaid.stop(true);
```

**Comment by MrMao14** [comment]
@04Slash  It looks work thanks bro
