### ISSUE TITLE
[Bug]: Cooked Whales aren't being added to bank

### ISSUE THREAD

**Issue by raudakelly** [MelvorIdle/melvoridle.github.io#4634]
### Describe the bug

Just cooking Whales and the number is staying the same. (All perfectly cooked, but neither normally cooked or perfect is going up)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

11765

### Are you using any mods?

No

**Comment by Ayarez** [comment]
You most likely have the "cooking upgrade I" bought and have the whales equiped as food. In that case they automatically get equiped to your food

**Comment by raudakelly** [comment]
Yup, that's it.
