### ISSUE TITLE
[Bug]: <Golden Golbin and Golden Crate not spawning>

### ISSUE THREAD

**Issue by UncleFlipp** [MelvorIdle/melvoridle.github.io#4640]
### Describe the bug

According to the Wiki, once you find the Special Key and the Treasure Map, as long as they're in your bank, the next time you get the Special Key or Treasure Map random Travel Event, the Special Key or Treasure Map will be consumed and the player will receive the Golden Crate or Golden Golbin. 

I currently have 5 Treasure Maps and 3 Special Keys in my inventory. If I'm misunderstanding then no problem I will keep grinding until I get them, but currently it feels like I will never be able to get 100% for AoD.

### Reproduction Steps

1. Cartography
2. Click on random Water tile.
3. Click Travel
4. Click another random water tile. 
5. Click Travel.
6. Repeat until you get items.

### Expected behaviour

I expected to get the Golden Golbin instead of another Treasure Map. I also expected to get a Golden Crate instead of another Special Key.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/VQuOWc3E

### Screenshots

![image](https://github.com/user-attachments/assets/66d6d378-8f19-4af8-a200-2ea5978afc85)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11765

### Are you using any mods?

Yes

**Comment by 04Slash** [comment]
The information on the wiki is incorrect and has been corrected. You can get multiple travel events in a row and the travel event that rewards the key and map are different than the ones that reward the statue and create.
