### ISSUE TITLE
[Bug]: Top bar text wrapping hides xp bar

### ISSUE THREAD

**Issue by JimmenyCrickets** [MelvorIdle/melvoridle.github.io#4641]
### Describe the bug

Hi, huge fan, had this bug since I started playing again: 

The bar at the top of the screen when Skilling (which says the name of the skill, equipment/potion buttons, and cloud save info) seems to be wrapping incorrectly on mobile, causing the bar to get thicker and cover the do bar and half of the skill level indicator and the top of the skill page.

I recon if the last cloud save readout was also in a button or hidden/shortened somehow, this might fix it, but you guys would know a lot better than me :)
![IMG_0339](https://github.com/user-attachments/assets/2eb44208-9a06-4d9f-967a-27814804da8a)
![IMG_0340](https://github.com/user-attachments/assets/4e3f3d13-8168-4e0b-891b-b85dff1fd82f)
![IMG_0341](https://github.com/user-attachments/assets/2f62075f-41b6-447b-a657-74483cb51718)

### Reproduction Steps

1. Have an iPhone 15 pro
2. Get Melvor idle
3. Enable cloud saves
4. Miss the sight of your do bar when levelling 

### Expected behaviour

Erm to be able to see the xp bar as it fills

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11765

### Are you using any mods?

Yes

**Comment by 04Slash** [comment]
This is caused by the mod that adds the book into the header (Show Skill Modifiers). That mod has a setting to hide the book and instead allow clicking/tapping the header to open the menu.

**Comment by JimmenyCrickets** [comment]
Oh thank you so much what a relief!!! Terribly sorry to have taken your
time for a non genuine issue, thanks again :)
