### ISSUE TITLE
[Bug]: Double Progression if reduced CPU setting is disabled

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#4644]
### Describe the bug

> Reduce CPU & GPU usage by pausing actions for all skills when the game is minimised or placed in the background to activate offline progression upon return.

If you are playing on the browser and disable the above setting, the amount of progress you gain while offline will be (roughly) doubled when you come back from being offline.

### Reproduction Steps

1. Load the game on browser
2. Turn the setting mentioned above off
3. If using an existing character, write down the current XP value of the skill
4. Start an action (such as Woodcutting) then immediately tab out of the game
5. Let the game idle for 5-10 minutes in a background tab
6. Tab back into the game and look at the xp value on the offline progression modal
7. Calculate the XP difference in the skill itself then compare that to the amount seen on the offline progression modal
8. The XP should be roughly 2x higher than the amount on the offline progression modal

### Expected behaviour

If the player spends 10 minutes offline, they should receive 10 minutes of progression, not 20.

### Screenshots

![image](https://github.com/user-attachments/assets/64121cd4-3668-4b3d-b91e-912336c2f500)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11765

### Are you using any mods?

Yes

**Comment by bonesbro** [comment]
On desktop (11770) I've also noticed significant extra progress several times.  This morning my offline progress report said that I leveled up slayer from 95 to 97 after ~10 hours offline.  The leftnav showed Slayer skill 98, and according to the skill progress in the Combat page I'm actually at 98.70%.

Using mods, Base+ToTH.
