### ISSUE TITLE
[Bug]: <title>Cooking Carp is not working

### ISSUE THREAD

**Issue by Oosks** [MelvorIdle/melvoridle.github.io#4645]
### Describe the bug

I've been trying to cook Carp to complete my township task, but when I try to cook my raw carp, I do not receive any cooked ones. The mastery for cooking them is working though. It will say that I'm getting 1-2 of them per action, but the cooked ones are not populating. my bank is not full, i have the cooking level required.  (I have the expansions and play the game with 0 mods fwiw)

edit: perfect carp seem to be working, its just the normal cooked ones that are not.

### Expected behaviour

Just hope this issue can be corrected

### Screenshots

![carpbug](https://github.com/user-attachments/assets/0a2bbda4-6371-47d3-818f-c7c57cbc466f)

### Console output

TypeError: "fetch" is read-only vendor.js:142:209686
Silent Sign in with JWT cloudManager.js:329:31
Validating Melvor Cloud token cloudManager.js:329:31
Storing Melvor Cloud Token cloudManager.js:329:31
Initializing PlayFab login. Method: customID cloudManager.js:329:31
Logging in with Custom ID via PlayFab cloudManager.js:329:31
Login with custom ID success cloudManager.js:329:31
Getting account info cloudManager.js:329:31
Account info retrieved cloudManager.js:329:31
Authenticated w/ Melvor Cloud: true cloudManager.js:329:31
Authenticated w/ PlayFab: true cloudManager.js:329:31
Checking for valid full version cloudManager.js:329:31
Checking for valid TotH purchase cloudManager.js:329:31
Checking for valid Atlas of Discovery purchase cloudManager.js:329:31
Checking for valid Into the Abyss purchase cloudManager.js:329:31
Getting keys from playfab cloudManager.js:329:31
Loading Game Data... cloudManager.js:329:31
Registered Demo Data. cloudManager.js:83:167
Registered Full Version Data. cloudManager.js:83:322
Registered Throne of the Herald Data. cloudManager.js:85:132
Registered Atlas of Discovery Data. cloudManager.js:86:173
Initializing Mod Manager... cloudManager.js:329:31
Loading Local Saves... cloudManager.js:329:31
Loading Cloud Saves... cloudManager.js:329:31
Getting saves from playfab cloudManager.js:329:31
Saves retrieved cloudManager.js:329:31
Loading character selection characterSelect.js:5:297
Connected to PlayFab successfully cloudManager.js:468:134
WebGL context was lost. index.mjs:3:36
Game Loaded main.js:17:282
Connected to PlayFab successfully cloudManager.js:468:134
updatePlayerTags cloud.js:91:16
PlayFab save updated successfully cloudManager.js:329:31
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features! index_game.php
Source map error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://dc8f824e-367f-49a4-821b-ec0f9cdc2207/vendor.js
Source Map URL: sourcemap/vendor.js.map
Source map error: map is undefined
Resource URL: moz-extension://dc8f824e-367f-49a4-821b-ec0f9cdc2207/vendor.js
Source Map URL: sourcemap/vendor.js.map
Source map error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://dc8f824e-367f-49a4-821b-ec0f9cdc2207/guide.js
Source Map URL: sourcemap/guide.js.map
Source map error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://dc8f824e-367f-49a4-821b-ec0f9cdc2207/content.js
Source Map URL: sourcemap/content.js.map
Source map error: request failed with status 404
Resource URL: https://melvoridle.com/assets/js/tippy-bundle.umd.min.js
Source Map URL: tippy-bundle.umd.min.js.map
Source map error: request failed with status 404
Resource URL: https://melvoridle.com/assets/js/basis.min.js
Source Map URL: basis.min.js.map
Source map error: request failed with status 404
Resource URL: https://melvoridle.com/assets/js/popper.min.js
Source Map URL: popper.min.js.map
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://dc8f824e-367f-49a4-821b-ec0f9cdc2207/vendor.js
Source Map URL: sourcemap/vendor.js.map

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11765

### Are you using any mods?

No

**Comment by Ayarez** [comment]
Then you have cooked carp equipped as your food and bought cooking upgrade 1 which automatically equips cooked food if its equipped.

Check your equipped food.
