### ISSUE TITLE
[Bug]: <title>additional cooker scroll not working

### ISSUE THREAD

**Issue by DaDucklingwhofell** [MelvorIdle/melvoridle.github.io#4652]
### Describe the bug

When using the additional cooker scroll, it doesn't increase the percentage to double items.

### Reproduction Steps

While cooking switch use any of the scrolls in the scroll slot (besides cooking scroll), check the percentage chance to double items.
Switch to the additional cooker scroll item, the percentage will be the same

### Expected behaviour

The percentage chance to double items while cooking should have increased.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/hxfX4lDE

### Screenshots

![Screenshot 2024-09-18 200928](https://github.com/user-attachments/assets/83f2e5b5-088d-49ed-851a-6f1399c33f8c)
![Screenshot 2024-09-18 200940](https://github.com/user-attachments/assets/6838be28-1889-43ce-82f3-8fe1e170cc17)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11766

### Are you using any mods?

No

**Comment by 04Slash** [comment]
That scroll doesn't give doubling chance. It gives a +5% chance to gain +1 item.
