### ISSUE TITLE
[Bug]: <title> Incorrect special attacks

### ISSUE THREAD

**Issue by Rsw783** [MelvorIdle/melvoridle.github.io#4655]
### Describe the bug

In goblin raid (but maybe in the general game, I don't have the items to test with) the ancient sword and ancient 2h sword use the wrong special attacks and instead use 'No Damage' and 'Frozen Wind' respectively

### Reproduction Steps

Enter the goblin raid
Get an ancient sword or ancient 2h
Wait for a special attack to trigger

### Expected behaviour

The ancient sword should use the 'Lifeleech' special and the 2h should use 'Crushing Double Slash'

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/YWBTDqCM

### Screenshots

![Screenshot_20240920-135835](https://github.com/user-attachments/assets/003c4cf5-ed2e-4b3e-9cab-77f224a4d634)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11766

### Are you using any mods?

No

**Comment by Flurryous** [comment]
Golbin Raid can roll different specials on items sometimes. They are identified by an (ALT) tag or something similar to that at the item selection.
