### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by bob2246ai** [MelvorIdle/melvoridle.github.io#4660]
### Describe the bug

钓鱼技能显示15级可以解锁海马，实际在游戏中没有解锁

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

？11768

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Translation of report via Google Translate:

> The fishing skill shows that the seahorse can be unlocked at level 15, but it is not actually unlocked in the game

Issue Resolution:

The seahorse is contained within the Secret Area, which must be unlocked by reading the Message in a Bottle first.
