### ISSUE TITLE
[Bug]: <Multi-Tree cutting problems>

### ISSUE THREAD

**Issue by Psyogenic** [MelvorIdle/melvoridle.github.io#4661]
### Describe the bug

Tried to switch from normal/oak to oak/willow, somehow double tree was disabled and I couldn't cut two trees suddenly. Tried quickly clicking on different trees, and several things happened.
-At one point normal trees gave 2 logs instead of 1, so it started spitting out 4 per action o.o lol. I clicked off it and back on, and it went back to 1/2 per action.
-Could cut 2 trees, but only 1 would stay hilighted. (Any trees)
-Eventually I guess I broke it because it got to where no trees would stay highlighted, but up top it would show I was still cutting whatever trees. 

So this has been an interesting little experience lol. What was frustrating is how at first multi-tree just turned off and selecting a 2nd tree became switching to that tree. (Single tree cutting)

### Reproduction Steps

1)Obviously have multi-tree active
2) Click fast on different trees for a few seconds, and you may or may not get the things I've listed to happen. I can't get any tree besides normal to give double (4 logs/action)
--Also maybe have to restart phone because closing Melvor/reopening starts me with the no highlights or 1/2 highlighted status.

### Expected behaviour

Umm..Expected behavior trying to reproduce bug or simply cut a different 2nd tree? Lol
Clicking back and forth on diff trees seems to produce the above stated effects at random. So one of the issues may happen, they may not. I realized it was that the game/app couldn't keep up with the selecting of different trees if done quick enough, thus confusing it and leaving some switches still on before moving onto a different process. 

This box and the previous box are the best explanations I could give on the issues, hope they're understandable.
After finishing this I'm gonna see if the fast clicking affects any other skills.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/xX5BVVR1

### Screenshots

![Screenshot_20241002-103338_Melvor Idle](https://github.com/user-attachments/assets/82aca653-dcb1-45e3-82be-85ef40d6ceea)

![Screenshot_20241002-103601_Melvor Idle](https://github.com/user-attachments/assets/4a157038-887a-4e8d-a399-f01106ab00e3)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

V1.3 (?11768)

### Are you using any mods?

No

**Comment by Psyogenic** [comment]
If anyone else is able to reproduce this/has this problem please tell me your details (Which skill was it/which items/process was it?) Thank you! 
- D

**Comment by MelvorIdle** [comment]
The highlight isn't to display the active Trees. That'st just a visual indicator of a click/tap. Your active trees are shown via the green progress bar on the Tree.

You need to disable a tree to then cut a different one. In both of your screenshots, you're cutting Oak + Willow, so to choose a new Tree you need to disable one of those and select a new one.

For the quantity of logs - these are weighted based on selected tree intervals. See here for information on how multi-tree calculates values: https://wiki.melvoridle.com/w/Multi-Tree
