### ISSUE TITLE
[Bug]: <title> Cannot Turn Ancient Magik Off

### ISSUE THREAD

**Issue by Mister-Purplez** [MelvorIdle/melvoridle.github.io#4664]
### Describe the bug

when i unlocked ancinent magik i decided not to use it for a while. When I was doing the dungeon where you fight malcs and get the fire cape, which I did like 50 times for the township task, I died while doing melee. So I decided to switch to magic because its better into melee, and I turned on the ancient magic to see what it did. after I did I could not turn it off on iPad no matter how many times I clicked it. I switched to mac, on steam, to turn it off there, same issue. i looked on wiki and saw that they could not be used with auras, so I thought I could turn it off with aura, to no avail. if this is intended, please let there be a warning. I'm able to deal with this, but I don't want to have to make runes while I farm for 10000 clears of the cave for the necklace for the z amulet that gives a s**t load of good stats. Thank you, have a nice day, awesome game, freaking love this thing. gonna play it again after I get all DLC(after I beat it, I'm no cheat;)

### Reproduction Steps

new acc. make all the way through all levels of base game without ancient magic. die at malcs dungeon with melee. switch to magic, all ancient gear, spirit ring, upgraded magic amulet. turn on ancient magic in malcs dungeon for dmg. cant turn off. click 10 times, go to wiki, switch back, click (literally no exaggerate) 103 times to break bug, go back to wiki, see you cant use aura, go click aura 50 times, try to make bug, make github ACC, and get here.

### Expected behaviour

turn off ancient magic when i click it like a prayer

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11768

### Are you using any mods?

No

**Comment by Mister-Purplez** [comment]
in explanation before "get hub acc" i meant, 'report bug' not make.

**Comment by 04Slash** [comment]
How are you trying to "turn ancient magicks off"? They're just another spell type so to "turn it off" you just choose a spell from the Standard spellbook (or any other spellbook).
