### ISSUE TITLE
[Bug]: <title>Whale Cooking

### ISSUE THREAD

**Issue by Nifoom** [MelvorIdle/melvoridle.github.io#4668]
### Describe the bug

When trying to cook a raw whale with my carrion fire, the action processes and grants xp, says +1 or +2 cooked whales but the amount of cooked whales doesn't actually go up.

### Reproduction Steps

1. Cooking skill 2. Cook fish 3. Cook Whale 4. No profit

### Expected behaviour

Whale cooks but doesn't actually increase amount in cooked pile. Unsure if it's taking away raw whales while doing this.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

11769

### Are you using any mods?

No

**Comment by Ayarez** [comment]
Look at your equipped food. You have the equip cooked food option enabled

**Comment by MelvorIdle** [comment]
The Whales are being automatically equipped based on your cooking settings
