### ISSUE TITLE
[Bug]: <title>Cant Get Prayer Point

### ISSUE THREAD

**Issue by lgj2006** [MelvorIdle/melvoridle.github.io#4676]
### Describe the bug

Cant Get Prayer Point

### Reproduction Steps

https://melvoridle.com/save/PKs94vGo

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/PKs94vGo

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11769

### Are you using any mods?

No

**Comment by lgj2006** [comment]
https://melvoridle.com/save/E44yPzIj

**Comment by 04Slash** [comment]
You have it set to show Soul Points in the sidebar. You can see how much prayer points you have (132) on the Combat screen at the bottom of the 'Stats' panel. On PC, this will be in the middle of the screen. On mobile, it will be under your character's equipment.
![image](https://github.com/user-attachments/assets/20f7ef84-6fe9-4f45-9a93-88b30801ca28)
![image](https://github.com/user-attachments/assets/8a972fe4-ab4d-4807-8d01-3b48a66fd7d4)

**Comment by lgj2006** [comment]
> You have it set to show Soul Points in the sidebar. You can see how much prayer points you have (132) on the Combat screen at the bottom of the 'Stats' panel. On PC, this will be in the middle of the screen. On mobile, it will be under your character's equipment. ![image](https://private-user-images.githubusercontent.com/57328541/378222404-20f7ef84-6fe9-4f45-9a93-88b30801ca28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MjkyNjcsIm5iZiI6MTcyOTUyODk2NywicGF0aCI6Ii81NzMyODU0MS8zNzgyMjI0MDQtMjBmN2VmODQtNmZlOS00ZjQ1LTlhOTMtODhiMzA4MDFjYTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE2NDI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNzRhNmRkNDVjYmNhMjMyZmFlMGU4ZjViNTJiMWI4ODQ0NTk3MDBkOGMyNzEwNzYyODhmMTc5ZGM4YzkxZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XnYBYWTS7evIZP4HY8RJsllD3jlOw83ZXeSeZQuDLNQ) ![image](https://private-user-images.githubusercontent.com/57328541/378222610-8a972fe4-ab4d-4807-8d01-3b48a66fd7d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MjkyNjcsIm5iZiI6MTcyOTUyODk2NywicGF0aCI6Ii81NzMyODU0MS8zNzgyMjI2MTAtOGE5NzJmZTQtYWI0ZC00ODA3LThkMDEtM2I0OGE2NmZkN2Q0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE2NDI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjYWY0OTNjNDM4Yzc2ZjU4MmQ4NTZhOTEwZWU0YTgzMjY2NmRjOTRmMzc4MzM0ZjI3OGI0MzE5M2JiNzE5OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Q_3Ry69wbbF8VfG3CzxPxt026j60bq0IOmDjDyZUGyM)

Thank you!
