### ISSUE TITLE
[Bug]: <title> Occultism v0.6 crashes myx Game

### ISSUE THREAD

**Issue by DecoyFrost** [MelvorIdle/melvoridle.github.io#4677]
### Describe the bug

I play with many mods and also wants to play with Occultism. But everytime I enable Occultism and reload the game an "error occurred while rendering" saying that Occultism v0.6 causes the error.

### Reproduction Steps

1. go to mods
2. enable Occultism
3. reload the game
4. see Error

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/pnekpb8P

### Screenshots

An error occurred while rendering:

Error due to the following mods:
Occultism (v0.6)

Error Name: Error
Error Message: Tried to update skill nav for invalid skill: occultism:Occultism
Stack Trace:
getNavs@https://melvoridle.com/assets/js/built/skillNav.js?11770:59:7
updateSkillLock@https://melvoridle.com/assets/js/built/skillNav.js?11770:45:40
renderLockStatus@https://melvoridle.com/assets/js/built/skill.js?11770:80:17
render@https://melvoridle.com/assets/js/built/skill.js?11770:58:31
render@https://melvoridle.com/assets/js/built/skill.js?11770:365:16
render@https://melvoridle.com/assets/js/built/skill.js?11770:524:16
render@Occultism:src/occultism.mjs:849:15
render/<@https://melvoridle.com/assets/js/built/game.js?11770:308:63
forEach@https://melvoridle.com/assets/js/built/namespaceRegistry.js?11770:50:44
render@https://melvoridle.com/assets/js/built/game.js?11770:308:39
loopOnline@https://melvoridle.com/assets/js/built/game.js?11770:355:35
loop@https://melvoridle.com/assets/js/built/game.js?11770:342:31

Active Action: mythMusic:Music
Current Equipment:
melvorD:Helmet: melvorD:Mithril_Helmet
melvorD:Platebody: melvorD:Mithril_Platebody_T_G
melvorD:Platelegs: melvorD:Mithril_Platelegs
melvorD:Boots: melvorD:Mithril_Boots
melvorD:Weapon: melvorD:Mithril_Sword
melvorD:Shield: melvorD:Mithril_Shield_T_G
melvorD:Amulet: melvorD:Amulet_of_Looting
melvorD:Ring: melvorD:Pirates_Lost_Ring
melvorD:Gloves: melvorD:Mithril_Gloves
melvorD:Quiver: melvorD:Bronze_Arrows
melvorD:Cape: melvorD:Mining_Skillcape

Action Information:
Is Active: true

Modding Enabled. Loaded mods:
Custom Modifiers in Melvor
SEMI Core
[Myth] Combat Simulator
Skill Boosts
Unlimited Offline
SEMI Drop Chances
Show Item Sources And Uses
Show Skill Modifiers
Better Offline Recap
Shop Item Owned Indicator
Item Uses
SEMI Auto Sell
Kills in Combat
Show Dungeon Completion Count
Better Summoning Menu
Completion Log Icons
QuickShards
ETA
Show Locked Astrology Modifiers
Quick Item/Bank Wiki
Show Slayer Tier
Shining Star
[Myth] Music
Combat Indicators
Sidebar Progress Bars
Forgot My Hat
Absurdly High Max Township Storage
Necromancy
(Skill) Classes and Species
Equipment Set Auto Swap
Shamanism
Mastery Pool Can Overflow
Anciny's Cheaper Bank Slots
Construction
Sailing (Beta)
Skillcape Tailor
Create Maps in Archaeology

![occErr](https://github.com/user-attachments/assets/1261de5c-963d-42ee-bdf0-5503aa3553d1)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [X] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11770

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This bug relates to a mod. Please contact the mod developer to issue a fix.
