### ISSUE TITLE
HP change text in HP area is covered up

### ISSUE THREAD

**Issue by zlynx** [MelvorIdle/melvoridle.github.io#468]
The small red text that shows changes to the character HP is not readable. At least on my screen it is under the current hit points number.

I am not sure how much of this is necessary to reproduce it.

I have maximum HP + 30, so 1030 total.
I have the maximum level auto-eat which adds a small icon to the right of the HP text and pushes it left.
Get into a fight.
When your character takes damage the red "-198" text will be underneath the "823/1030" text.

I expected the red text to be to the left of the hitpoints and readable.

![Screenshot from 2020-10-29 23-43-35](https://user-images.githubusercontent.com/18293918/97665331-d3e28900-1a40-11eb-80b3-12df215f66a6.png)

**Browser**
This happens to me on Firefox on Linux and on Windows. I haven't tried it on other browsers.
This particular browser is Firefox 82.0 on Ubuntu 20.04

**Comment by MelvorIdle** [comment]
Fixed in v0.18
