### ISSUE TITLE
[Bug]: Account gone.

### ISSUE THREAD

**Issue by Coverednbees** [MelvorIdle/melvoridle.github.io#4681]
### Describe the bug

Went to log in. Email is not detected.
Email. Gemoreland1995@gmail.com
Char name; imcoverednbees

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [X] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

11181

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
It looks like you spelt the email wrong during registration. I've updated it now. Please login using your username (not email) and password. If you don't remember your password, please reset it.
