### ISSUE TITLE
[Bug]: Bank Search function resets when clicking on bank tabs

### ISSUE THREAD

**Issue by Flurryous** [MelvorIdle/melvoridle.github.io#4684]
### Describe the bug

Before 1.3.1, you could type keywords into the bank search function and click through the bank tabs to see items that match the keyword in each tab.

After the update, clicking on the tab after searching resets the search results so you see every item in a specific tab instead of filtering that tab with keywords. 

### Reproduction Steps

1. Search something up in the bank, like "cape".
2. The tab you're in will only display items associated with "cape", and other tabs with "cape" associated items will be highlighted.
3. Click on another highlighted tab. You'll see that all items in that tab will be displayed instead of just "cape" items. 

### Expected behaviour

Clicking on tabs when using the bank search should not reset the search results. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3.1

### Game Subversion

?11964

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
This has now been hotfixed
