### ISSUE TITLE
[Bug]: Bank filter "show items with normal damage reduction" does not filter out slayer equipment

### ISSUE THREAD

**Issue by Ayarez** [MelvorIdle/melvoridle.github.io#4685]
### Describe the bug

Normal slayer items aren't hidden when  "show items with normal damage reduction" is toggled. this includes all tiers

Same thing happens for the Abyssal variant when "show items with abyssal resistance" is toggled

### Reproduction Steps

1. go to bank
2. toggle filter items with normal damage reduction
3. slayer items still there

### Expected behaviour

hiding slayer equipment too

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3.1

### Game Subversion

?11964

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Thanks for the report. This is now hotfixed.
