### ISSUE TITLE
[Translation Error]: <title> Incorrect translation of the Blacksmith's Gloves into Russian

### ISSUE THREAD

**Issue by ShestakovArt** [MelvorIdle/melvoridle.github.io#4691]
### Which text in the game has a translation error?

Incorrect translation of the Blacksmith's Gloves, translated as if the gloves give combat experience, and should not give the experience of a blacksmith

![image](https://github.com/user-attachments/assets/6c153ef7-d775-46a5-b656-9db65ddbd304)

**Comment by MelvorIdle** [comment]
Hello, what should the correct translation be?

**Comment by coolrox95** [comment]
Closing in favor of #4739 as it provides a corrected translation
