### ISSUE TITLE
[Bug]: Incorrect Task Time

### ISSUE THREAD

**Issue by Bchapp1558** [MelvorIdle/melvoridle.github.io#4692]
### Describe the bug

In crafting and in mining I have gotten buffs that would make the task completion interval 0.05 seconds but the game will only show it at 0.25 seconds. I’ve attached a screen shot of the interval buffs. Incase the image cannot be seen, total there is a 31% time reduction combined with a total of -2 seconds.

![IMG_8983](https://github.com/user-attachments/assets/796a056a-7ce5-4a43-8d85-54b0f4466441)

### Reproduction Steps

1. Get crafting interval buffs shown in image
2. Interval time stays at .25 when it should be less

### Expected behaviour

Interval time should be 0.05 seconds

### Screenshots

![IMG_8983](https://github.com/user-attachments/assets/f6625e56-52dd-4e25-8e7e-104ff19ec105)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3.1

### Game Subversion

?11975

### Are you using any mods?

No

**Comment by 04Slash** [comment]
Action times are intentionally capped at 0.25s.
