### ISSUE TITLE
[Bug]: Smithing gloves purchased, but not received

### ISSUE THREAD

**Issue by Siophrae** [MelvorIdle/melvoridle.github.io#4693]
### Describe the bug

I purchased the smithing gloves from the shop and the GP is deducted but no popup for the item gained. The shop shows them as owned and the number of charges. 

They are not in my bank and cannot be equipped from the quick access menu in the smithing view. 

### Reproduction Steps

1. Go to shop
2. Purchase smithing gloves
3. Go to bank to verify item not received
4. Go to smithing page
5. Open quick access menu and click smithing gloves

### Expected behaviour

I expected the purchased smithing gloves to be in my bank and equipable. 

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/ofbLEdiD

### Screenshots

![Screenshot_20241101-085108](https://github.com/user-attachments/assets/f8fe61ae-b432-4106-9ad6-d40fa8b7557a)
![Screenshot_20241101-085045](https://github.com/user-attachments/assets/f27c614e-9871-4354-863d-08eb200f69c7)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3.1

### Game Subversion

?11975

### Are you using any mods?

Yes

**Comment by 04Slash** [comment]
The gloves are equipped in the third equipment set.

The way these gloves work is they will only allow you to own 1 of them. If you already have the item, it will just add more charges.

**Comment by Siophrae** [comment]
Sorry! Thanks for you time and the explanation :)
