### ISSUE TITLE
[Bug]: Game crashes and reloads on loading save

### ISSUE THREAD

**Issue by Perilex** [MelvorIdle/melvoridle.github.io#4698]
### Describe the bug

On loading the provided save, the game client crashes and reloads back to the "Select your Character"-screen. Some clients seem to get further along the loading process than others, but the few that I've tried still all crash.

The crash also occurs with mods disabled.

Mods used:
- [Myth] Combat Simulator 3.1.13

### Reproduction Steps

1. Import the provided save file
2. Try loading the game
3. The game will crash and reset

### Expected behaviour

For the save file to load properly.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/cDCSfJY6

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3.1

### Game Subversion

?11975

### Are you using any mods?

Yes

**Comment by 04Slash** [comment]
The game isn't crashing, your character died. There's red text at the bottom of character select that will tell you when your last HC character died, what it died to, and what level it was.

Looking at the character just before death, it appears it died because it ran out of food and the auto swap food setting was disabled.

**Comment by Perilex** [comment]
Oh huh, you're right. Didn't even catch that with the text being all the way at the bottom of the CS screen. Thanks for the heads-up!
