### ISSUE TITLE
[Bug]: Getting Tidal Wave ability in Golbin Raid with no source

### ISSUE THREAD

**Issue by Ledivin** [MelvorIdle/melvoridle.github.io#4699]
### Describe the bug

In Golbin Raid (not sure if it extends to the main game or not), I have the Tidal Wave ability when I shouldn't. I _believe_ it's coming from the Dragon Head Helmet, because I've never seen Firebreathing used and have had the helmet for many waves.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/HRnp4Smh

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3.1

### Game Subversion

?11975

### Are you using any mods?

No

**Comment by Flurryous** [comment]
That likely means the helmet has its special replaced with the Tidal Wave special.

In Golbin Raid, items that have specials can sometimes have specials of other items, which is indicated by an (ALT) tag when you're choosing such an item.

**Comment by Ledivin** [comment]
None of the equipment shows as ALT, and the helmet definitely still says Firebreathing - does that change not display on hover/tap of my equipment?

**Comment by Flurryous** [comment]
It's been a while so I can't remember if that was always the case, but that might be it.
