### ISSUE TITLE
[Bug]: The Madness spells tool tip not displaying values.

### ISSUE THREAD

**Issue by OrangeROTT** [MelvorIdle/melvoridle.github.io#4701]
### Describe the bug

On mobile the madness spell shows code instead of values for accuracy decrease and number of turns the debuff lasts. Damage  values display correctly. 

### Reproduction Steps

Hold down on Madness spell to reveal tool tip

### Screenshots

![Screenshot_20241106_120611_Samsung Internet](https://github.com/user-attachments/assets/e8b1bfc0-2e9c-42c9-b855-601fd5c2a2e7)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3.1

### Game Subversion

11987

### Are you using any mods?

No

**Comment by Sellyme** [comment]
Also experiencing this on Steam v1.3.1 (11975)

**Comment by MelvorIdle** [comment]
Thank you for the report. A fix has now been applied to the game.
