### ISSUE TITLE
[Bug]: <title>cooking bug

### ISSUE THREAD

**Issue by CharliQt** [MelvorIdle/melvoridle.github.io#4703]
### Describe the bug

I’ve been cooking terrorfish for almost a day and my inventory won’t increase past 1,027

### Expected behaviour

I should have at least 14k more in my inventory, whenever I cook one I should get at least one per action

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3.1

### Game Subversion

?11182

### Are you using any mods?

No

**Comment by Flurryous** [comment]
They're ending up auto equipping to your food slot.

**Comment by CharliQt** [comment]
Omg duhhhh Tysm for pointing that out, you’re totally right
