### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by Magrein** [MelvorIdle/melvoridle.github.io#4705]
### Describe the bug

In the cartography there are only cells with the requirement of level 100, and I have 99. What should I do in this case? 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [x] Throne of the Herald
- [x] Atlas of Discovery
- [x] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3.1

### Game Subversion

?11987

### Are you using any mods?

No

**Comment by 04Slash** [comment]
You can gain an infinite amount of XP through making paper and maps.
