### ISSUE TITLE
[Bug]: Cannot use mastery tokens to level up Unholy Logs

### ISSUE THREAD

**Issue by Kclee7** [MelvorIdle/melvoridle.github.io#4706]
### Describe the bug

In the wood cutting skill when trying to spend mastery tokens, the unholy tree is not listed as an option

### Expected behaviour

The Unholy Tree should an option to spend mastery

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3.1

### Game Subversion

?11987

### Are you using any mods?

No

**Comment by 04Slash** [comment]
Do you have Atlas of Discovery checked? You should be able to spend mastery in any action that's below level 99.
![image](https://github.com/user-attachments/assets/f1750819-3b5c-4de9-a446-1ba7485a9399)
