### ISSUE TITLE
[Bug]: 0/696969 in my mining nodes

### ISSUE THREAD

**Issue by Olray** [MelvorIdle/melvoridle.github.io#4707]
### Describe the bug

Shortly after buying "Throne of the Herald" I ran into the problem shown in the screenshot. Some of my new mining nodes have 0/69696969 duration. The problem is the same on iPad and Windows (Epicgames)
Can I repair my savegame?

### Reproduction Steps

Load my savegame

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/YJvRqpyV

### Screenshots

![Clipboard_11-09-2024_01](https://github.com/user-attachments/assets/ecd1dbd2-32eb-45db-a8ee-5301a2cd6cad)
![Mods](https://github.com/user-attachments/assets/54ff65e4-31c7-4975-a03a-ada39434766a)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3.1

### Game Subversion

?11987

### Are you using any mods?

Yes

**Comment by Ayarez** [comment]
This is working as intended.
Those gem veins require you to "find" them while mining other nodes, once they are located you gain health in said gem veins.
It's explained in the blue text below those gem veins.

As for meteorite, those are located in Starfalls in Astrology

**Comment by Olray** [comment]
Ist the "Meteorite" vein also a gem vein? And what about that 69696969? If it's not supposed to be mined through the mining skill, why are they listed in Mining?

**Comment by Olray** [comment]
I think I understand now. It's the 69696969 that is pretty misleading. Suggest to change it to 1000000 or something that doesn't look like a bit-flipped savegame error.
