### ISSUE TITLE
Regeneration Potions seem to be bugged

### ISSUE THREAD

**Issue by Falterfire** [MelvorIdle/melvoridle.github.io#471]
**Describe the bug**
I was digging into the math of how Regen Potions worked to update the wiki page, and it seems that Regeneration Potions are actually even worse than they should be.

Looking at Combat.js, I found this code: (Formatting adjusted slightly to look as readable as possible here)

```
if (herbloreBonuses[13].bonus[0] === 7 && herbloreBonuses[13].charges > 0 
         && !isGolbinRaid) {
    let chance = Math.floor(Math.random() * 100);
    if (herbloreBonuses[13].bonus[1] > chance) 
        regen *= Math.floor(1 + items[herbloreBonuses[13].itemID].potionBonus / 100);
    updateHerbloreBonuses(herbloreBonuses[13].itemID);
}
```

As best I can tell, the game is actually rolling a chance to apply the bonus and then only applying the flat bonus. Or, in other words, instead of either having a 12% chance to double the HP regenerated or always increasing the HP regenerated by 12%, the tier IV version of the potion provides a 12% chance to increase the HP regenerated by 12%.

... actually no, reading through it again, that `Math.floor()` around the potion bonus will result in it having a 12% chance to multiply the HP regenerated by 1. So that's two bugs for the price of one.

[DISCLAIMER: JavaScript isn't a language I have a ton of time in, it's possible I'm missing something obvious]

**Comment by MelvorIdle** [comment]
Fixed in v0.18
