### ISSUE TITLE
[Bug]: Debuffing a Barrier Enemies max hitpoints causes them to drop less barrier dust

### ISSUE THREAD

**Issue by cookb0065** [MelvorIdle/melvoridle.github.io#4711]
### Describe the bug

Merman is supposed to drop 15 barrier dust, yet it only drops 13. I suspect this has to do with the effects of HP relic 2.

### Reproduction Steps

1) Have HP relic 2 (might not actually be causing the issue, but it is the best explanation I can think of)
2) Kill Merman
3) Get 13 barrier dust

### Expected behaviour

1) Kill Merman
2) Get 15 barrier dust

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/MRL3WGws

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3.1

### Game Subversion

?11987

### Are you using any mods?

No

**Comment by cookb0065** [comment]
Update: other barrier monsters also drop less barrier dust than they should, such as cult member and lich.

**Comment by cookb0065** [comment]
It does not, it says 15 even though you receive 13. It is specified nowhere that amount of barrier dust dropped is based on max barrier.

**Comment by MelvorIdle** [comment]
Thank you for the report. A fix has now been applied to the game.
