### ISSUE TITLE
[Bug]: Combat submenu UI doesn't indicate selected Rune Realm

### ISSUE THREAD

**Issue by SolidKalium** [MelvorIdle/melvoridle.github.io#4715]
### Describe the bug

Main bug: When tapping a tab for Runes, the UI can highlight that "tab header" as "focused". But when you tap elsewhere, there is no style remaining on the tab to distinguish it as being "selected". The first screenshot shows how both tab headers are styled the same. This isn't a huge deal, because the rune colors are distinct, but it's still less than ideal.

Edited to add: this same tab style and issue is also present on the "plant a seed" modal.

Secondary bug: Most of the "tab selectors" in the Combat Menus, such as for spells, highlight only three border sides when selected. The rightmost cell highlights all 4 sides. I'm guessing this is related to how css is generating the borders and is a minor issue, but I figured I should mention it. See second screenshot for example.

### Screenshots

![IMG_6350](https://github.com/user-attachments/assets/afb40767-5390-46ba-95bf-93b3740505e4)
![IMG_6349](https://github.com/user-attachments/assets/25b48420-2ccc-4685-a077-85fc0729c66b)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3.1

### Game Subversion

?11987

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Thank you for the report. A fix has now been applied to the game.
