### ISSUE TITLE
[Bug]: Abyssal sidebar background only covers part of sidebar

### ISSUE THREAD

**Issue by SolidKalium** [MelvorIdle/melvoridle.github.io#4716]
### Describe the bug

It's not a major issue, but the background of the sidebar cuts off part way across (see screenshot).

I'm guessing that the image width is set for non-mobile views where the sidebar is always visible and therefore has a width you've defined instead of needing to match the mobile device's width. I can't quite tell, but it looks like the background might be able to just tile horizontally and fill that space.

### Screenshots

![IMG_6348](https://github.com/user-attachments/assets/29fc65f5-bb6b-4436-8216-1f9f10bea359)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3.1

### Game Subversion

?11987

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
Thank you for the report. A fix has now been applied to the game.
