### ISSUE TITLE
[Bug]: Climbing Boots Purchased Not Appearing in Bank

### ISSUE THREAD

**Issue by JacobVorstenbosch** [MelvorIdle/melvoridle.github.io#4724]
### Describe the bug

Upon purchasing the "Climbing Boots" from the slayer portion of the shop, the coins are taken from my slayer cache but the boots never appeared in my inventory, even after a search of my Bank. 

### Reproduction Steps

1. Launch Melvor Idle
2. Have 500k Slayer Coins
3. Go to the Shop
4. Purchase the "Climbing Boots"
5. Look for them in your inventory.

### Expected behaviour

They should have the climbing boots in the inventory after purchase.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/iWSOeteY

### Screenshots

(Screenshot is from after the purchase was made, hence why the slayer coins are below 500k)

![image](https://github.com/user-attachments/assets/04aab675-1c44-40d0-8ea4-5cf8e58a3618)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Steam (Offline Beta)
- [X] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3.1

### Game Subversion

?12002

### Are you using any mods?

No

**Comment by 04Slash** [comment]
According to the item stats, you sold them.

![image](https://github.com/user-attachments/assets/983019bc-0adb-47f9-9837-9b83adac2bad)

**Comment by JacobVorstenbosch** [comment]
That's strange, I don't know how I would've - I bought them to equip them for the region and immediately went looking for them only to find nothing. Will try buying them again after acquiring enough coins and see if it was just a one off.

**Comment by JacobVorstenbosch** [comment]
Purchased them again, appeared as normal, something must've went wrong for me. Thanks again!
