### ISSUE TITLE
[Bug]: Unable to launch into Offline Beta

### ISSUE THREAD

**Issue by ninjacob555** [MelvorIdle/melvoridle.github.io#4725]
### Describe the bug

I am not able to launch the game while the game is enrolled into the Offline Client Stage 2 Beta on steam. It appears on my task manager, but not as an application, as a background process.

### Reproduction Steps

1. Select the "offline-client-stage-2 - Offline Client Stage 2 - Steam Client Testing" beta on steam
2. allow the game to update to the beta
3. Click the "PLAY" button on steam
4. wait, to no avail.

### Expected behaviour

I would expect the game to launch. Very confusing to me.

### Screenshots

![image](https://github.com/user-attachments/assets/931f7b4e-a0ee-4c25-b88d-6e3b6b7a6f6a)
![image](https://github.com/user-attachments/assets/e650430f-4945-4720-b1d9-3b85a095ebe6)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Steam (Offline Beta)
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3.1

### Game Subversion

?12002

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment]
Thanks for the report. Does the client launch if you verify the game files?

Also - what OS are you currently using?

**Comment by ninjacob555** [comment]
I verified the game files once, then swapped back to the non-beta version, verified the files, logged in, made sure I could play the game, closed it, swapped to the beta, verified the files again, and then launched and it still would not. 

I'm on Windows 11, on the latest update.

**Comment by ninjacob555** [comment]
Hm. tried to add it to the exceptions list, and it didn't work. But I turned OFF my antivirus and it works. I use Webroot SecureAnywhere. I'll try and add more things in the folder to the exceptions list!

**Comment by ninjacob555** [comment]
Update on this, Today I've been able to launch normally. I assume it's my antivirus realizing that this is fine. Thanks for your advice!
