### ISSUE TITLE
[Bug]: <title>Bank issues

### ISSUE THREAD

**Issue by SalmonsWillRise** [MelvorIdle/melvoridle.github.io#4729]
### Describe the bug

While in my bank menu, the names of the items are displayed. 
![Melvor Idle Bug](https://github.com/user-attachments/assets/29763779-bae9-4b9d-9eb5-a7517ea6ff58)

### Reproduction Steps

No idea. It just happened one day. 

### Expected behaviour

It shouldn't display the item names, only the amounts. 

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/QEvdICv3

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Steam (Offline Beta)
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3.1

### Game Subversion

?12002

### Are you using any mods?

No

**Comment by coolrox95** [comment]
This is intended functionality from the Minor Accessibility Features setting.

![image](https://github.com/user-attachments/assets/f56637aa-5e41-4366-a720-5bdc4270b0e7)
