### ISSUE TITLE
[Bug]: Long Combat encounters can be quick completed with defective behavior

### ISSUE THREAD

**Issue by ColMcWill** [MelvorIdle/melvoridle.github.io#4730]
### Describe the bug

Unintended ability to skip long combat.

When you begin a combat that is expected to be long ( I was fighting the Depths of Fear in the Abyss), you can skip the main boss by saving your game during the fight, and loading the save in a browser on 2 tabs.

### Reproduction Steps

Begin fight in Depths of Fear on Steam client.
Complete battles up to the boss Karn, the Fear Bringer
Save the game while fighting Karn, the Fear Bringer
Open a browser tab, and navigate to the webclient for Melvor Idle
Load the save in cloud save in the browser
The fight will have completed, you'll have received the reward, and will have started back in the dungeon at the beginning.

### Expected behaviour

You will rejoin the fight and see what progress was made during time away

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/cEV82a1C

### Screenshots

![image](https://github.com/user-attachments/assets/239ff657-c7e3-44dc-84df-8e762d53052d)

### Console output

Failed to load resource: the server responded with a status of 404 ()Understand this errorAI
cloudManager.js?12002:1848 Silent Sign in with JWT
cloudManager.js?12002:1848 Validating Melvor Cloud token
cloudManager.js?12002:1848 Storing Melvor Cloud Token
cloudManager.js?12002:1848 Initializing PlayFab login. Method: customID
cloudManager.js?12002:1848 Logging in with Custom ID via PlayFab
cloudManager.js?12002:1848 Login with custom ID success
cloudManager.js?12002:1848 Getting account info
cloudManager.js?12002:1848 Account info retrieved
cloudManager.js?12002:1848 Authenticated w/ Melvor Cloud: true
cloudManager.js?12002:1848 Authenticated w/ PlayFab: true
cloudManager.js?12002:1848 Checking for valid full version
cloudManager.js?12002:1848 Checking for valid TotH purchase
cloudManager.js?12002:1848 Checking for valid Atlas of Discovery purchase
cloudManager.js?12002:1848 Checking for valid Into the Abyss purchase
cloudManager.js?12002:1848 Getting keys from playfab
cloudManager.js?12002:1848 Loading Game Data...
cloudManager.js?12002:509 Registered Demo Data.
cloudManager.js?12002:512 Registered Full Version Data.
cloudManager.js?12002:523 Registered Throne of the Herald Data.
cloudManager.js?12002:528 Registered Atlas of Discovery Data.
cloudManager.js?12002:532 Registered Into the Abyss Data.
cloudManager.js?12002:1848 Initializing Mod Manager...
cloudManager.js?12002:1848 Loading Local Saves...
cloudManager.js?12002:1848 Loading Cloud Saves...
cloudManager.js?12002:1848 Getting saves from playfab
cloudManager.js?12002:1848 Saves retrieved
characterSelect.js?12002:21 Loading character selection
cloudManager.js?12002:2783 Connected to PlayFab successfully
main.js?12002:138 Game Loaded
cloudManager.js?12002:2783 Connected to PlayFab successfully
cloud.js?12002:519 updatePlayerTags
web-client-content-script.js:2 Uncaught (in promise) Error: Could not find identifiable element
    at web-client-content-script.js:2:353706
    at Array.map (<anonymous>)
    at web-client-content-script.js:2:353651
    at f (web-client-content-script.js:2:196974)
    at Generator.<anonymous> (web-client-content-script.js:2:198311)
    at Generator.next (web-client-content-script.js:2:197337)
    at u (web-client-content-script.js:2:203989)
    at a (web-client-content-script.js:2:204192)Understand this errorAI
cloudManager.js?12002:1848 PlayFab save updated successfully
style.css:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()Understand this errorAI

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Steam (Offline Beta)
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3.1

### Game Subversion

?12002

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
As this is a 100% singleplayer game, we won't be implementing any sort of anti-cheat of methods to stop "defective behaviour". It's ultimately up to the player in how they choose to experience the game.
