### ISSUE TITLE
[Bug]: Dark Ritual potion doesn't reduce cost of summoning

### ISSUE THREAD

**Issue by staticf0x** [MelvorIdle/melvoridle.github.io#4737]
### Describe the bug

The description says:
> +25% Cost Reduction for Summoning, excluding Shards, for Abyssal Realm only

but when active, the cost of tablets is still the same. Cost reduction tooltip doesn't include the potion either. However, charges are consumed. The items are being consumed at the price without any reduction. Same for all 4 potion tiers.

### Expected behaviour

For example, Abyssal Bear is at 50 echosnap herb, with tier 4 25% reduction it should be around ~38 herbs.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Steam (Offline Beta)
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3.1

### Game Subversion

?12002

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
Cost Reduction is capped at 80%. As the base cost for Abyssal Bear tablets is 250 Echosnap herbs, it is not possible to reduce this below 50.
