### ISSUE TITLE
[Bug]: <title>Smithing Skill Cape

### ISSUE THREAD

**Issue by belseyOSRDL** [MelvorIdle/melvoridle.github.io#4738]
### Describe the bug

Smithing skill cape does not apply it's -50% coal usage to Augite bar smithing.

### Expected behaviour

Augite bar smithing recipe calls for 10 coal per craft. Smithing skill cape reduces coal requirements by 50% for smithing. Augite bar smithing is still consuming 10 coal ore per craft with the smithing skill cape equipped.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/E5HkXrSh

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Steam (Offline Beta)
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3.1

### Game Subversion

?12002

### Are you using any mods?

No

**Comment by 04Slash** [comment]
The base coal cost for Augite is 20: https://wiki.melvoridle.com/w/Augite_Bar

If you're seeing 10 with the cape equipped, then it seems to be working as intended.

**Comment by belseyOSRDL** [comment]
Ah, I see my mistake. Recipe requirements update in the ui. Thanks @04Slash
