### ISSUE TITLE
[Bug]: <title> base hp

### ISSUE THREAD

**Issue by Dabomb18** [MelvorIdle/melvoridle.github.io#4742]
### Describe the bug

I have purchased AoD and ToH expansions and I have 120 hit points skill, but my max hit points is only 1160.

### Expected behaviour

I have read where at level 120 hit points I should have 2000 max hp.

### Screenshots

![Screenshot_20241208_010046_Melvor Idle](https://github.com/user-attachments/assets/8f47b86f-d13f-4d62-84ad-32d865ab96fc)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Steam (Offline Beta)
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3.1

### Game Subversion

?12002

### Are you using any mods?

Yes

**Comment by cookb0065** [comment]
There are many things that could be affecting your health - namely equipment, potions, and agility obstacles. You should have your HP level x 10 base HP. This would mean that your base health should be 1200, not 2000. Therefore you should have health modifiers totaling to -40 HP.
