### ISSUE TITLE
[Bug]: Randomly losing weapon in Golbin raids

### ISSUE THREAD

**Issue by Rothlan284** [MelvorIdle/melvoridle.github.io#4750]
### Describe the bug

I have used bows and magic staves so far, and each time I run out of runes (even if they don't require them), my weapon will switch back to a bronze scimitar. I lost a 2h Lightning Coil Staff which shouldn't even be possible, but it is, and it caused a run to be lost.

### Reproduction Steps

1. Equip a spell
2. Equip a bow or stave that allows casting with runes (but NOT necessary)
3. Wait until the runes run out
4. Watch your weapon turn into a bronze scimitar

### Expected behaviour

What I expect to happen, is the game to stop casting spells and instead just use it's on hit effects instead. At least then I can repair the damages done to running out of runes instead of starting all over because of a crucial issue

### Screenshots

![image](https://github.com/user-attachments/assets/b9f1ba05-7bfd-4d38-9e11-bc14f651bc0c)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Steam (Offline Beta)
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3.1

### Game Subversion

?12015

### Are you using any mods?

No

**Comment by Ayarez** [comment]
This is working as intended.

When you don't have runes for Magic or Arrows/Bolts for Ranged, your weapon disappears and you're given a bronze weapon to at least be able to continue
