### ISSUE TITLE
[Bug]: Last Save location is the current and not last save's

### ISSUE THREAD

**Issue by kocsirtamas** [MelvorIdle/melvoridle.github.io#4752]
### Describe the bug

I was travelling to another country recently and when got off the plane after not having internet access, I was surprised to see on the login page that the Last Save showed my current location instead of the country I last saved, next to the time of last save.

### Reproduction Steps

1. Save the game
2. Travel to another city or country while not opening the game
3. Open the app and be surprised that the Last Save shows your current city/country
(4. Alternatively I guess you could use a VPN to simulate you are in another country)

### Expected behaviour

I always expected this text to show the time and location of my last save, not just the time of last save and my current location, because that does not make much sense.

### Screenshots

![kép](https://github.com/user-attachments/assets/eed93960-474a-4951-910b-3ab3991c3291)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Steam (Offline Beta)
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3.1

### Game Subversion

?12015

### Are you using any mods?

No

**Comment by coolrox95** [comment]
The Country/City indicates the current local time zone you are in, not where the save was created.

**Comment by kocsirtamas** [comment]
Why does the game have to show my current location?
