### ISSUE TITLE
Bug with "Brute Force" Special on the Magic Weapons

### ISSUE THREAD

**Issue by ScTigerFang** [MelvorIdle/melvoridle.github.io#478]
**Describe the bug**
The  "Brute Force" Special on the Magic Weapon "Fire Imbued Wand" does not seem to work with the spell "Ignite"
Brute Force has a 20% chance to do double damage, so it should hit 1600+ but it only does the normal 800+ damage increase

**To Reproduce**
-Equip the  "Fire Imbued Wand" (Could be broken with other wands of the same tier)
-Set to cast "Ignite"
-Start combat with a monster with 2k+ health(Seething Horned Elite is what I was attacking for testing)
-Wait for Special Attack to trigger

**Expected behavior**
-You will see it does the base damage and does not do double damage as described in the Special Attack tooltip.

**Comment by MelvorIdle** [comment]
This is working as intended. Damage modifying special attacks do not affect Ancient Magicks.
