### ISSUE TITLE
Uncontrollable Crashing

### ISSUE THREAD

**Issue by Graceclaw** [MelvorIdle/melvoridle.github.io#479]
**Describe the bug**
I am playing on mobile, and I have essentially been unable to play on any of my three accounts because, after loading into my game, the app closes without notice or reason within 30 seconds. Sometimes it takes longer, but for at least 3-4 days I have not had a sustained play session

**To Reproduce**
1. Log into your account
2. Wait up to 30 seconds
3. Game will close without a message

**Expected behavior**
Game will not close 

**Screenshots**
None available- no error message

**Browser**
Mobile - Android

**Console output**
Unavailable 

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Is this on Android or iOS? Have you tried reinstalling the app?

**Comment by Graceclaw** [comment]
Android. Uninstall/reinstall appears to have fixed it, for now. I will update if it occurs again, I'm not optimistic

**Comment by Graceclaw** [comment]
![Screenshot_20201112-123317_One UI Home](https://user-images.githubusercontent.com/74369890/99001317-443ce000-2500-11eb-9a47-14a154ba9647.jpg)

And we're back where we started, with rapid automatic closures.

**Comment by MelvorIdle** [comment]
Please confirm this is fixed since the latest release of the App on the App Store

**Comment by Graceclaw** [comment]
> Please confirm this is fixed since the latest release of the App on the App Store

So far, so good! I didn't have to go to the app store to download a new version, but maybe it got pushed overnight. Either way, I haven't had any issues since  the push notification came out
