### ISSUE TITLE
Dragonite ore doesn’t respawn

### ISSUE THREAD

**Issue by TheDreamStrider** [MelvorIdle/melvoridle.github.io#480]
IOS// dragonite ore doesnt respawn

**To Reproduce**
1. Dragonite ore depleted on app start-up
2. Click on mithril ore before ore respawned
3. Proceed to not respawn
![45575FDC-DB72-4232-A156-B4F068B6CECA](https://user-images.githubusercontent.com/74470502/99155970-4009f180-26bd-11eb-98b5-d745e5c734fd.png)

**Comment by MelvorIdle** [comment]
How long have you left the game open waiting? Ore takes roughly 2-5 minutes to respawn, and this timer is restarted when loading up a character.
