### ISSUE TITLE
Mastry lvl bugged with multiple tree and afk

### ISSUE THREAD

**Issue by joshboss070** [MelvorIdle/melvoridle.github.io#481]
**Describe the bug**
logged into my challenge acc and saw that my maple tree was mastery 92 while my teak was only 84½, (started both on 82) so it seems like the mastery calt for the 2nd tree is broken when you afk

**To Reproduce**
1. have multiple tree, dragon axe. 82 mastery on both teak and maple
2. click maple then teak
3. AFK
4. log in later and there should be a big difference in mastery gain

**Expected behavior**
that the mastery levels where atleast somewhat similier (i know different trees gets mastery faster/slower)

**Screenshots**
https://cdn.discordapp.com/attachments/625841473731952688/777269639099973732/Screenshot_20201114-212942.jpg

**Browser**
Phone add free version, aplha v 0.17

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Should be fixed in v0.18
