### ISSUE TITLE
Runecrafting 95% checkpoint doesn't work when offline

### ISSUE THREAD

**Issue by dizzystem** [MelvorIdle/melvoridle.github.io#482]
**Describe the bug**
The 95% mastery pool bonus for runecrafting is to give +5 runes per craft. This works normally when crafting online, but when crafting offline, this bonus does not apply.

**To Reproduce**
1. Start runecrafting with 99 mastery in a rune and at least 95% mastery pool.
2. Switch tabs for a few minutes.
3. When returning to the game tab, the offline runes produced will be a multiple of 11 (the amount of runes made per craft without the bonus), not of 16 (the amount of runes made per craft with the bonus)
4. Alternatively, switch tabs for just two seconds to see the results of just one craft action, which will be 11 instead of 16.

**Expected behavior**
It should apply the bonus when offline too.

**Browser**
Firefox

**Console output**
06:54:30.256 Synchronising with Cloud cloud.js:11:181
06:54:41.336
Array(6) [ 391, 389, 392, 393, 478, 890 ]
main.js:197:9
06:59:30.219 Synchronising with Cloud 2 cloud.js:11:181
07:04:50.923
Array [ 398, 391 ]
main.js:197:9
07:05:54.695
Array(5) [ 398, 393, 389, 391, 392 ]
main.js:197:9
07:07:33.257
Array(5) [ 398, 391, 393, 392, 389 ]
main.js:197:9
07:09:31.153 Synchronising with Cloud cloud.js:11:181
07:11:50.401
Array(5) [ 398, 389, 391, 392, 393 ]

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixed in v0.18
