### ISSUE TITLE
Sell amount not really updating when changing the number

### ISSUE THREAD

**Issue by Wondertje** [MelvorIdle/melvoridle.github.io#486]
**Describe the bug**
When using a button such as "all but one" or "all" - the amount being sold does not change if you later change the number with the number box. It changes visually but will ask to sell the previous amount when clicking sell.

**To Reproduce**
**1)** Click item in inventory
**2)** Click "all but one" and see all the information (sell value, etc)
**3)** Change the number of items to sell to a different one using the number box and see the information update
**4)** Click sell and see that the sell information it asks you to confirm is for the previous information in step 2, not 3.

**Expected behavior**
Expected is to be asked to sell the amount you changed to. This will happen **if** you use the slider. The bug only happens when changing the number in the box, as far as my testing shows.

**Screenshots**
After choosing all but one:
![All but one](https://user-images.githubusercontent.com/43150426/99770766-46a6c780-2b08-11eb-8d31-88ac4e8a8f4c.png)

Changing the number to 8:
![8](https://user-images.githubusercontent.com/43150426/99770801-558d7a00-2b08-11eb-8242-96ea949447c8.png)

Clicking the sell button to confirm:
![Sell 13](https://user-images.githubusercontent.com/43150426/99770814-5a522e00-2b08-11eb-9f8b-6305450165ac.png)

**Browser**
Chrome on Windows 10.

**Are you using any scripts?**
No, no scripts are or have been used before.

**Comment by GronbergInfo** [comment]
I would like to add to this bug.

When mining with gem glove, you get one gem each time.
If you mass sell and select the pile where you get another gem into during the selection, the numbers does not update, 
so you sell more gems for less value because the total sum does not update. but the recieved gems after selection are also removed (= I.E. sold for 0 GP)

**Comment by MelvorIdle** [comment]
Fixed in v0.18
