### ISSUE TITLE
Still running in steam despite closing

### ISSUE THREAD

**Issue by wghughes95** [MelvorIdle/melvoridle.github.io#489]
**Describe the bug**
When closing steam version of the game, the game says it's still running. Clicking stop does nothing and I can't reopen the game. I can still open and play other games however while it says this, and the game loads fine once I restart steam.

**To Reproduce**
Exiting the game by clicking close on window in top right (unsure if there is another exit method)

**Expected behavior**
When exiting the game I expect it stop running in steam. 

**Screenshots**
![image](https://user-images.githubusercontent.com/52975694/99788249-c0df4800-2b18-11eb-9f37-2d77380cd321.png)

**Browser**
N/A (using steam version)

**Console output**
N/A as not in a browser

**Are you using any scripts?**
No

**Comment by martinspp** [comment]
I've noticed the same. It is not consistent, but I have had it happen twice now.

**Comment by MelvorIdle** [comment]
Latest client update should hopefully address this. Closing now, please create a new bug report if the issue returns.
