### ISSUE TITLE
Active play boost/rewards

### ISSUE THREAD

**Issue by Unlimited307** [MelvorIdle/melvoridle.github.io#49]
Rewards for active play for idle skills, in the form of random events or minigames, maybe a combination of the two.
For example perhaps there could something to "catch" while fishing that gives you bonus fishing XP, a rare fish maybe.
An implementation more directly inspired by runescape random events would be random minigame popups that reward specific XP. Rewards could instead be temporary boosts to certain skills, pushing players to train differently and change the experience for different players or playthroughs.
The appeal of this might most shines in a multiplayer environment, where it of course promotes involvement at all and skill expression for the competitive players.

**Comment by mrDLSable** [comment]
This is a good idea. Currently the only thing that is sort of like this in game is the bonfire for firemaking, but perhaps a couple more things like this would be nice.

**Comment by mrDLSable** [comment]
I have an idea to boost active play: the Ritual Casting skill. Rituals would give the player a boost in a certain aspect of the game for a certain amount of time. These boosts could be something as simple as a bonus to xp or mastery xp gained, higher chance for double ores, higher chance for rare drops, etc.

The rituals would last for a certain amount of time (say minimum about 10 minutes, maximum 8 hours) and the time would increase with the mastery.

Rituals would require various ingredients which have to be gathered with various skills, making this an end-game skill. But a couple of simple rituals could be available to lower level players to encourage active play.
