### ISSUE TITLE
Navigation panel on left disappears and won't reappear

### ISSUE THREAD

**Issue by djsch** [MelvorIdle/melvoridle.github.io#493]
**Describe the bug**
Navigation panel on left disappears and won't reappear

**To Reproduce**

Steam Platform

Not really sure; I resized the window a number of times to fit it onto my second monitor, but at some point it disappeared and wouldn't reappear. I resized the window a number of times trying to get it back, but I couldn't get it to show up. I eventually had to quit the program and relaunch which fixed it.

**Expected behavior**
The left navigation panel shouldn't disappear, or should reappear when resizing the window.

**Screenshots**

**Browser**
Steam, latest version as of 2pm US EST 11/23/20

**Console output**
n/a

**Are you using any scripts?**
No

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
