### ISSUE TITLE
goblin raid allows you to use unlearned spells outside of minigame

### ISSUE THREAD

**Issue by redrhetoric** [MelvorIdle/melvoridle.github.io#494]
Bug:
using a spell in the goblin raid minigame allows you to use the spell outside of the minigame, even if your magic skill isn't high enough to know that spell

To Reproduce:
1. start goblin raid minigame
2. select a spell that your magic skill isn't high enough to use normally
3. run away

**Expected behavior**
i expected that when i exited goblin raid i would not have access to magic skills higher than my level.

**Browser**
using google chrome Version 86.0.4240.198 (Official Build) (64-bit)

**Console output**
Failed to load resource: the server responded with a status of 403 (Forbidden)
index.php?l=1:1 [DOM] Found 2 elements with non-unique id #bank-sell-x: (More info: https://goo.gl/9p2vKq) <input type=​"text" class=​"form-control" id=​"bank-sell-x" name=​"bank-sell-x" placeholder=​"Sell x">​ <input type=​"text" class=​"form-control m-1" id=​"bank-sell-x" name=​"bank-sell-x" placeholder=​"Sell x">​
v017_bank_tabs.png:1 Failed to load resource: the server responded with a status of 404 ()
v017_bank_sidebar.png:1 Failed to load resource: the server responded with a status of 404 ()
v017_bank_sell_mode.png:1 Failed to load resource: the server responded with a status of 404 ()
save.js?549:8 Loading Save Game...
save.js?549:24 Save Game Loaded...
smithing2.js?549:9 Loading Smithing...
mastery.js?549:2 Loading Masteries...
main.js?549:6 Game Loaded
prebid.min.js:3 fun-hooks: referenced 'registerAdserver' but it was never created
(anonymous) @ prebid.min.js:3
cloud.js?549:93 Connected to PlayFab successfully
main.js?549:197 Array(0)
adthrive.min.js?threshold=0:17 AdThrive::init started
(unknown) [Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
(anonymous)
cdn.ampproject.org/rtv/012010270040000/amp4ads-v0.mjs:9 Powered by AMP ⚡ HTML – Version 2010270040000 https://melvoridle.com/index.php?l=1
data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=:1 Uncaught SyntaxError: Invalid or unexpected token
cloud.js?549:11 Synchronising with Cloud
index.html:21 MAIN CSS LOADED
index.html:31 MAIN JS LOADED
cloud.js?549:11 Synchronising with Cloud
cloud.js?549:11 Synchronising with Cloud
DevTools failed to load SourceMap: Could not load content for https://melvorcdn.fra1.cdn.digitaloceanspaces.com/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not parse content for https://content.quantcount.com/adchoices/v2/css/300x50.css.map: Unexpected token � in JSON at position 0
DevTools failed to load SourceMap: Could not load content for https://melvorcdn.fra1.cdn.digitaloceanspaces.com/current/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://melvorcdn.fra1.cdn.digitaloceanspaces.com/current/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://melvorcdn.fra1.cdn.digitaloceanspaces.com/sm/13c28911820333eb6a51103a0e2096477a38941cc79afbf16b59f3d5a5f63086.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
no

**Comment by MelvorIdle** [comment]
Hotfixed pushed to live game. Alpha v0.21 (?1093)
