### ISSUE TITLE
Queue up actions

### ISSUE THREAD

**Issue by MirrorImageQS** [MelvorIdle/melvoridle.github.io#495]
I propose the ability to queue up a limited number of actions for the game to carry out one after the other. This would take the form of a new "Queue" button alongside a given action button. At a basic level, this could allow you to pick one of three options:

- "Repeat X times": perform the associated action a certain number of times. EX: "Mine Iron Ore 200 times"
- "Repeat until X quantity": perform the associated action as many times as necessary until you receive a certain number of an item (the item usually being the primary output of the action). EX: "Fish Lobster until I have 200 Raw Lobster" (would run for around 250 actions on average because of Junk Items)
- "Repeat until I return": essentially the current offline action that runs either until you sign back in or the 12 hour idle timer runs out, usually used as the last action in a queue when all other desired tasks are done

A trivial example of this: it takes around 80 bronze bars, smelted and smithed, to go from level 1 to level 10 in Smithing. However, it involves collecting two separate resources from Mining to create them - Copper and Tin. If I wanted to queue up only enough actions to get myself to Level 10 Smithing so I could start working with Iron immediately, I could queue the following:

1. Mining Copper Ore - Repeat 80 times
2. Mining Tin Ore - Repeat 80 times
3. Smithing Bronze Bars - Repeat 80 times
4. Smithing Bronze Daggers - Repeat 80 times
5. (any other action) - Repeat until I return (whatever other skill I want to passively train now that I've reached a Smithing goal)

Another trivial example: You want to craft the necessary number of runes for all 4 elemental staves:

1. Runecrafting Air Rune - Repeat until 100 Air Runes
2. Runecrafting Water Rune - Repeat until 100 Water Runes
3. Runecrafting Earth Rune - Repeat until 100 Earth Runes
4. Runecrafting Fire Rune - Repeat until 100 Fire Runes

For mid- or late-game, this potentially becomes more useful to avoid either having to check in on the game too often or to avoid overspending resources and having to use that much more time to recollect them. For the Runecrafting example, replace 100 with 11,000 if you wanted to craft the necessary runes for each Mystic Battlestaff from scratch, or even queueing up the Normal and Maple logs that are necessary as well.

Practical limitations that could be applied to this to prevent it from becoming too much of a full "play the entire game by itself" feature before late game:
- You can only queue up actions that you are otherwise able to do now. In the Bronze example above, you would have to have the Bronze Bars available in the first place to queue Smithing items out of it, and you have to have the Ores to queue up the Smelting. So maybe that one has to be split into three separate queues that you have to set up after each one completes - one to mine the relevant ore, one to smelt the bars, and one to smith then bars, with some other action on "Repeat until I return" to run when they complete until you check in.
- You can't queue up an action you don't have the Skill level for yet, even if you've queued up enough actions to get there. The queue doesn't let you do things as soon as you become able to do it, it just helps you get there with your resources efficiently
- For actions with multiple possible outputs, "Repeat until X quantity" will either need to be told which item to track quantity on, or it needs to be specified by the action itself. For example, a Mining Iron Ore queue of "Repeat until 5 Diamonds" conceptually makes sense, but gemstones aren't the primary output of Mining Iron Ore, so maybe the queue should be limited to checking Iron Ore. Functionally, this could either be the guaranteed output of an action or the single item with the greatest chance of being returned (e.g. you can queue Cooking for Cooked fish, but not Burnt fish).
- The number of queued up steps can be a shop unlock. Having two queue steps at the beginning of the game could help make the early level grind a bit easier without feeling like wasting resources, while saving large and more expansive queues for making complicated late-game items.
- To avoid trivializing early levels too much like the Bronze example somewhat does, require a certain Skill level, Mastery level on an action, or Mastery XP in the pool before you're allowed to add it to a queue (25 Mastery on an action? 1% checkpoint for the entire skill? Level 30 in the skill itself?)

Implementation concerns that would have to be watched for:
- Queueing up multiple actions that consume the same resource could make it where the second action doesn't have enough resources available to complete the entire action. In that case, it would merely do as much as possible (like current offline actions)
- It doesn't make sense for more than one "Repeat until I return" action to be queued up at once. If more than one is picked, the new one should overwrite the previous one. It may even be reasonable to have "Repeat until I return" not take up a queue slot and instead works as a default "Do this when nothing is in the queue".
- The queue shouldn't allow you to bypass the 12 hour limit. If you queue up actions that take longer than 12 hours, then the queue will freeze in place at the relevant time and restart when you check in and reset the timer.

**Comment by aceg00** [comment]
@MirrorImageQS I don't think this feature should be added to the base game, but here is a script that does exactly what you described. https://greasyfork.org/en/scripts/412689-melvor-action-queue

See wiki page https://wiki.melvoridle.com/index.php?title=Scripting_and_Extensions for more info on scripts and extensions.
