### ISSUE TITLE
Cut off tip

### ISSUE THREAD

**Issue by PsykoPyro89** [MelvorIdle/melvoridle.github.io#496]
Not entirely sure this is a bug, but when I equipped the mining gloves, when I hover over them in the bottom right hand quick menu (I think that's what it's called), it sends the tip outside of the window (happens in both full and small screen).  Another thing that happens when you highlight over the icon, if you scroll using the right arrow it allows for infinite scrolling to the right until the screen refresh catches up and sends it back to the activity you're doing.

Malvor Idle, Steam edition, v. Alpha 0.17

![cut off highlight tip](https://user-images.githubusercontent.com/74994561/100163756-60d40300-2e84-11eb-91f6-9054c983c546.jpg)

**Comment by Adds3000** [comment]
This seems to be related to zoom within Steam.  It only happens on zoom levels <100%.
