### ISSUE TITLE
Menu Translucent box overlay visible when zoom settings used on steam.

### ISSUE THREAD

**Issue by Adds3000** [MelvorIdle/melvoridle.github.io#497]
**Describe the bug**
Within steam, when zoom settings are active you can see the edges of the translucent box overlay when opening some windows (plant all, mastery etc).

**To Reproduce**
Activate any of the zoom settings <100%
Open plant all interface

**Expected behavior**
Translucent box overlay covers entire screen rather than it being adjusted to the zoom size.

**Screenshots**
https://cdn.discordapp.com/attachments/625840209531240469/780842535111229490/unknown.png

**Browser**
Steam

**Console output**
N/A

**Are you using any scripts?**
No.

**Comment by Angamara** [comment]
Another problem related to the zoom: The slider of the number of items to sell in the bank has a problem.
