### ISSUE TITLE
Change quick sort order

### ISSUE THREAD

**Issue by RedSparr0w** [MelvorIdle/melvoridle.github.io#5]
Update the quick sort order to bring related items nearer to each other.

Currently:
![image](https://user-images.githubusercontent.com/7288322/68283891-472d1580-00e1-11ea-9c0f-20348c716a11.png)

Would be good to sort by category then id maybe.

**Comment by MelvorIdle** [comment]
I will investigate new sorting methods after the release of v0.09 for this one.

**Comment by RedSparr0w** [comment]
The following will sort items to be ordered by category then item ID:
_Categories are ordered by when they first appear in the item list (woodcutting comes first)_
```javascript
const categories = [...new Set(items.flatMap(item=>item.catergory))];
bank.sort( function ( a, b ) {
	const diff = categories.indexOf(items[a.id].catergory) - categories.indexOf(items[b.id].catergory);
	return diff ? diff : a.id - b.id;
});
loadBank();
```
![image](https://user-images.githubusercontent.com/7288322/68617764-ca5cca00-052c-11ea-99d1-6e01921e3c56.png)

**Comment by mrDLSable** [comment]
![image](https://user-images.githubusercontent.com/1783781/68618083-de6ee000-04c8-11ea-8344-71035ac2c1ad.png)
A lot better, but not yet perfect. Perhaps add another sorting tier with the type attribute?

**Comment by RedSparr0w** [comment]
What category is that axe?
```javascript
categories = [...new Set(items.flatMap(item=>item.catergory))];
bank.sort( function ( a, b ) {
	const diff = categories.indexOf(items[a.id].catergory) - categories.indexOf(items[b.id].catergory);
	const type = parseInt(items[a.id].type, 36) - parseInt(items[b.id].type, 36);
	return diff ? diff : (type ? type : a.id - b.id);
});
loadBank();
```

**Comment by mrDLSable** [comment]
Very nice 
![image](https://user-images.githubusercontent.com/1783781/68623152-1d566300-04d4-11ea-8d50-c2e89b4e8279.png)

**Comment by MelvorIdle** [comment]
Thanks for this! Adding this to v0.09.1 which is due for release very soon.
