### ISSUE TITLE
"Trimming" weapons with gems

### ISSUE THREAD

**Issue by mrDLSable** [MelvorIdle/melvoridle.github.io#50]
As suggested by BurntJoint in the discord.

This would be a nice use for gems. And of course if you implement a gold requirement for trimming another nice gold sink. I would personally suggest something along the lines of 2500 gems per trim.

You can have different gems be required for different types of upgrades.

**Comment by Eusmusia** [comment]
Each gem could correspond to adding a different effect to the weapon as well, like Topaz decreasing attack time, Diamond could ignore defense stats when it activates. And these could be added in tiers.

So a Dragon helm that's gem studded would have a weaker effect to a dragon helm (g) that's gem studded.
