### ISSUE TITLE
No timer when lighting bonfire with exact logs

### ISSUE THREAD

**Issue by KaasChuig** [MelvorIdle/melvoridle.github.io#500]
**Describe the bug**
In Firemaking if you have exactly 10 logs that you use to light a bonfire, it will acknowledge the bonfire bonus is active while you burn other logs, but will not give a timer to let you know how long the bonus will be active.

**To Reproduce**
1. Go to 'Firemaking'
2. Click on "Light bonfire" when you have exactly 10 of the selected logs.

**Expected behavior**
The bonus activates with a timer alerting you to time remaining on bonus.

**Browser**
Chrome
Version 86.0.4240.198 (Official Build) (64-bit)

**Are you using any scripts?**
No

**Comment by coolrox95** [comment]
Issue has been hotfixed as of Alpha v0.21 (?1119).
