### ISSUE TITLE
Using mastery in herblore stops action

### ISSUE THREAD

**Issue by KO4JZT** [MelvorIdle/melvoridle.github.io#501]
**Describe the bug**
When redeeming mastery XP, the action you're currently doing in herblore is stopped.

**To Reproduce**
1. Go to herblore and start making potions.
2. Spend mastery XP on anything in Herblore.

**Expected behavior**
Potions would continue production.

**Browser**
Latest version - Chrome.

**Are you using any scripts?**
No, happens with all scripts disabled.

**Comment by Razorflamekun** [comment]
I'd like to addend this issue with the fact that this issue is still present on the Steam version of the game.

**Comment by coolrox95** [comment]
Closing this as I cannot reproduce this bug in the current version of the game (Alpha v0.21 ?1098).
