### ISSUE TITLE
Bank Tab icon is not updated when items are added/removed from empty bank tab

### ISSUE THREAD

**Issue by mazunki** [MelvorIdle/melvoridle.github.io#502]
**Describe the bug**
Icons for bank tabs are not updated on enemy drops.

**To Reproduce**
1. Go to bank
2. Make any item go to a tab
3. Empty tab by selling all items
4. Collect said item which goes into tab
5. Tab appears as if no items are in it

**Expected behavior**
Collected item becomes tab icon

**Browser**
Steam

**Are you using any scripts?**
No

**Comment by mazunki** [comment]
As a note: Moving any item afterwards between any tabs will update unregistered tab icons. Still annoying, as I use a tab for all items I want to sell, and that happens more often than me moving items around.

**Comment by coolrox95** [comment]
This seems to be a general issue with the bank tab image not updating when items are added/removed from the bank.
Was able to reproduce simply by calling `addItemToBank(CONSTANTS.item.Water_Rune,1)` when the first tab of the bank was empty. Similarly equipping an item when it is the only item in a tab, will not update the tab to show as empty after.

**Comment by MelvorIdle** [comment]
Fix has been applied to the game
