### ISSUE TITLE
Cannot buy normal cooking fire

### ISSUE THREAD

**Issue by hamilc1603** [MelvorIdle/melvoridle.github.io#503]
I have all relevant material and money but when clicking on the item nothing happens.

I have a screen recording to show but no way to attach

**Comment by geoff-maddock** [comment]
I'm running into the same issue.  If I click "Normal Cooking Fire", nothing happens - it isn't purchased and there is no error flash.
I looked in the dev console and I don't see any errors, and no network request is sent.

LMK if there is more I can do to troubleshoot.

**Comment by MelvorIdle** [comment]
Make sure you have the correct logs required to purchase it. This is generally why you are not able to purchase it.
