### ISSUE TITLE
Firemaking mastery and Art control decrease interval

### ISSUE THREAD

**Issue by Japasjp** [MelvorIdle/melvoridle.github.io#504]
**Describe the bug**
Art Control and Firemaking mastery decrease BASE interval therefore should be additive but in reality they are multiplicative like the 25% firemaking mastery pool.

**To Reproduce**
1. Start Firemaking
2. Have Art of Control and Mastery pool perks

**Expected behavior**
Expected: Burn interval = base burn interval*(1-20% [from art control] - Mastery Level*0.1%[ from mastery])*(1-10%[from 25% mastery pool perk])

Real: Burn interval = base burn interval*(1-20% [from art control])*(1- Mastery Level*0.1%[ from mastery])*(1-10%[from 25% mastery pool perk])

Example Magic Log, 99 mastery.
base burn = 10s 
Expected burn interval = 10*(1-20%-99*0.1%)*(1-10%) = 6.417s
Real burn interval = 10*(1-20%)*(1-99*0.1%)*(1-10%) = 6.5736s

**Browser**
Chrome Version 87.0.4280.66

**Are you using any scripts?**
SEMI and Combat Simu

**Comment by coolrox95** [comment]
This was fixed in Alpha v0.19.
