### ISSUE TITLE
Small statistic bug

### ISSUE THREAD

**Issue by ReZeroed** [MelvorIdle/melvoridle.github.io#505]
**Describe the bug**
The gold gained from thieving does not count towards total gp acquired in the statistics

**To Reproduce**
1. Check total gold acquired in statistics
2. Steal from any NPC and gain some gold
3. Check total gold acquired in statistics again

**Expected behavior**
I expected the total gold acquired to go up with each successful thieving action

**Screenshots**
You can see I have over 10k gold, but no total gold acquired https://gyazo.com/6c4cd7853f8e7c3fef317c0cde0bfb08

**Browser**
Playing on latest steam version

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Fixed in v0.18
