### ISSUE TITLE
Woodcutting xp bug (idle)

### ISSUE THREAD

**Issue by Smeder78** [MelvorIdle/melvoridle.github.io#509]
**Describe the bug**
I don't get the full xp when idle woodcutting 

**To Reproduce**
1. Go to the woodcutting skill
2. Click on magic/redwood tree and go idle
3. go back to the game 
4 and see that i'm not getting full exp

**Expected behavior**
I did this test without any xp boosting gear, so fully naked with a d axe and twin cutting perk. I got redwood logs (180xp) and magic logs (100xp). I did a really quick test and got 17 redwood logs and 14 magic logs so i should be getting 4460xp instead i got 2780 xp

**Screenshots**
added a screenshot of the welcome back with xp and logs
![Schermafdruk 2020-12-03 15 30 32](https://user-images.githubusercontent.com/75433772/101042202-31588100-357d-11eb-95ac-5eeb4e0c37fd.png)

**Browser**
Steam version Alpha V0.17

**Are you using any scripts?**
not using any scripts

**Comment by rainmankk** [comment]
Was wondering why Oak Trees didnt go up in mastery lvls as fast as the other first three trees:

![wood](https://user-images.githubusercontent.com/3008679/101769128-cbbd4500-3ae6-11eb-8e6e-9ea3a3f1a6b0.jpg)

Closed the website and came back roughly 10 hours later:

![Wood2](https://user-images.githubusercontent.com/3008679/101769181-ded01500-3ae6-11eb-9431-cc6d6a848e9d.jpg)

It seems Oak Tree doesnt get any master exp while farming offline. Could be related with the exp issue OP has

**Comment by MelvorIdle** [comment]
Should be fixed in v0.18

**Comment by Smeder78** [comment]
> Should be fixed in v0.18

Thank you for your work, this game is amazing i bought the ad free playstore version and the steam version to support you!

**Comment by Smeder78** [comment]
still not fixed!
