### ISSUE TITLE
Alt. Magic Bug - Offline progression; Times passed no exp gained.

### ISSUE THREAD

**Issue by Phaloax** [MelvorIdle/melvoridle.github.io#511]
I have had a problem with superheat 3 and alchemy 3 in Alt. Magic. I have selected proper things for it to work and have the resources for the offline progression to work for at least an hour. Even if an hour has passed, I come back to shown time passed and no exp gained with none of the resources used.

I select Alt. Magic and clicked on Superheat 3 to produce mithril bars.
Then I close the tab of Google Chrome.
I come back and select the following to access my account.
Lastly, end up with no exp gained and indication of time has passed.

The behaviour that I expected to happen is my resources not used, no exp gained, and indication of time wasted.

<img width="625" alt="Screen Shot 2020-12-07 at 9 50 28 AM" src="https://user-images.githubusercontent.com/75627055/101367342-0a979480-3874-11eb-9b8a-30be726452e5.png">

**Browser**
Please tell us what browser you are using and what version.
I am on Google chrome and I noticed the problem occurring first with my mobile. The Google Chrome version is Version 86.0.4240.198 (Official Build) (x86_64) and my iPhone is an iPhone 6s Plus.

**Console output**

Uncaught TypeError: Cannot read property 'addEventListener' of undefined
    at lib._201800_728x90.frame_0 (index.html:558)
    at a.d._runActionsRange (VM7 createjs.min.js:19)
    at a.b._runActions (VM7 createjs.min.js:19)
    at a.b._runActionsRange (VM7 createjs.min.js:19)
    at a.b._runActions (VM7 createjs.min.js:19)
    at a.b.setPosition (VM7 createjs.min.js:19)
    at lib._201800_728x90.c._updateTimeline (VM7 createjs.min.js:14)
    at lib._201800_728x90.c.advance (VM7 createjs.min.js:14)
    at lib._201800_728x90.c._tick (VM7 createjs.min.js:14)
    at lib.Stage.b._tick (VM7 createjs.min.js:13)
frame_0 @ index.html:558
d._runActionsRange @ VM7 createjs.min.js:19
b._runActions @ VM7 createjs.min.js:19
b._runActionsRange @ VM7 createjs.min.js:19
b._runActions @ VM7 createjs.min.js:19
b.setPosition @ VM7 createjs.min.js:19
c._updateTimeline @ VM7 createjs.min.js:14
c.advance @ VM7 createjs.min.js:14
c._tick @ VM7 createjs.min.js:14
b._tick @ VM7 createjs.min.js:13
b.tick @ VM7 createjs.min.js:13
b.update @ VM7 createjs.min.js:13
b.handleEvent @ VM7 createjs.min.js:13
b._dispatchEvent @ VM7 createjs.min.js:12
b._dispatchEvent @ VM7 createjs.min.js:12
b.dispatchEvent @ VM7 createjs.min.js:12
a._tick @ VM7 createjs.min.js:12
a._handleTimeout @ VM7 createjs.min.js:12
setTimeout (async)
a._setupTick @ VM7 createjs.min.js:12
a._setInterval @ VM7 createjs.min.js:12
a.init @ VM7 createjs.min.js:12
a.addEventListener @ VM7 createjs.min.js:12
a._register @ VM7 createjs.min.js:19
b._setPaused @ VM7 createjs.min.js:19
b._init @ VM7 createjs.min.js:19
a @ VM7 createjs.min.js:19
a.get @ VM7 createjs.min.js:19
lib._201800_728x90 @ index.html:573
handleComplete @ index.html:743
init @ index.html:737
onload @ index.html:854
Enabler.js:166  [  1.008s] [studio.sdk] Using default ad parameters in test environment. Simulating local events.

**Are you using any scripts?**
I am not using any scripts or any extensions for Melvor idle.

Thank you in advance and keep up the amazing work.

**Comment by MelvorIdle** [comment]
Should be fixed in v0.18
