### ISSUE TITLE
Offline Fishing Spam

### ISSUE THREAD

**Issue by Abstrusle** [MelvorIdle/melvoridle.github.io#516]
**Describe the bug**
Should offline progress be enabled while fishing, one can receive dual items at rapid rate by expeditiously transitioning tabs.

**To Reproduce**
1. Enter fishing tab.
2. Select any fish (I had used raw trout upon discovery).
3. Exit game for but a second, long enough for offline progress to become applicable.
4. Receive two of randomly-selected item from your fishing pool (although one item's worth of experience).

**Expected behavior**
Offline fishing should not generate immediate income.

**Browser**
Firefox 83.0

**Comment by MelvorIdle** [comment]
Fixed in v0.18
