### ISSUE TITLE
Runecrafting 25% Pool Checkpoint

### ISSUE THREAD

**Issue by MrSankey** [MelvorIdle/melvoridle.github.io#517]
**Describe the bug**
I am not given a multiple of 250% of base rune XP with this checkpoint. I am still only getting 45 Skill XP per action for nature runes. 
**To Reproduce**
1. Try to craft runes with 25% mastery pool.
2. Don't earn the bonus experience.
**Expected behavior**
45 × 2.5 = 112.5 Skill XP per action on nature runes.

**Screenshots**

**Browser**
Android free app

**Console output**

**Are you using any scripts?**
No.

**Comment by aceg00** [comment]
@MrSankey Nature rune gives 18xp. 18 * 2.5 = 45. See wiki page https://wiki.melvoridle.com/index.php?title=Runecrafting#Runes

**Comment by MrSankey** [comment]
It applied. I was mistaken.
