### ISSUE TITLE
"Show Confirmation when Attempting to close the game" setting currently does nothing on Steam Version

### ISSUE THREAD

**Issue by Adds3000** [MelvorIdle/melvoridle.github.io#518]
**Describe the bug**
"Show Confirmation when Attempting to close the game" setting currently does nothing on Steam Version, there is no confirmation when going to char selection page or closing the window.

**To Reproduce**
1. Enable the Setting
2. Restart game within Steam and load a char
3a. Navigate to char select screen clicking the Melvor icon in top left (no confirmation asked)
3b. Close the game by clicking the "x" in top right (no confirmation asked)

**Expected behavior**
A confirmation box to navigate away or close game similarly to in browser.

**Screenshots**
N/A

**Browser**
Vivaldi browser works 
Steam does not 

**Console output**
N/A.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
This is intended to be disabled in settings. I will remove the option entirely from the Steam version
