### ISSUE TITLE
Superheat 1 & 2 recipe deselects when swapping characters

### ISSUE THREAD

**Issue by ItsPandatory** [MelvorIdle/melvoridle.github.io#519]
When I swap between my HC and standard character or when I reopen the game I get the expected bars from superheat 1 or 2 but then a "you don't have the required raw materials to Cast that" message. This may also happens with superheat 3&4 but I don't have them unlocked yet.

**To Reproduce**
1. Go to Alt. Magic
2. Click on Superheat 1 or 2
3. Select a bar and start casting
4. Close game or switch characters
5. Switch back to character that is super heating

**Expected behavior**
I expect superheat to continue functioning upon resuming the game similar to other skills.

**Screenshots**
https://imgur.com/a/Tegxadm

**Browser**
Steam version

**Console output**
Steam version

**Are you using any scripts?**
No scripts

**Comment by MelvorIdle** [comment]
Should be fixed in v0.18
