### ISSUE TITLE
Woodcutting - not gaining mastery while offline

### ISSUE THREAD

**Issue by rainmankk** [MelvorIdle/melvoridle.github.io#520]
**Describe the bug**
While offline some trees (Oak, Teak) do not gain mastery while offline. There might be other trees also affected but I have not gotten there on my road to full mastery woodcutting.

**To Reproduce**
1. Go to 'Woodcutting'
2. Start 'Oak Tree' and 'Teak Tree'
3. Make a screenshot of your current progress of those two
4. Go offline for a while
5. Come back and compare the current progress with your screenshot

**Expected behavior**
Well, to gain mastery while farming those trees while offline

**Screenshots**
Oak Tree before going offline:
![wood](https://user-images.githubusercontent.com/3008679/101984195-263dd900-3c80-11eb-9f43-6e0b3087baed.jpg)

Oak Tree after beeing offline for ~10h:
![Wood2](https://user-images.githubusercontent.com/3008679/101984204-2c33ba00-3c80-11eb-86aa-d4c8660c9a8e.jpg)

Teak Tree before going offline:
![Wood3](https://user-images.githubusercontent.com/3008679/101984206-2dfd7d80-3c80-11eb-9408-e6eb6fcef424.jpg)

Teak Tree after beeing offline for ~7h
![wood4](https://user-images.githubusercontent.com/3008679/101984208-2fc74100-3c80-11eb-9b5f-40fbf1e651e1.jpg)

**Browser**
Firefox Browser Developer - 84.0b8 (64-Bit)

**Are you using any scripts?**
Melvor TimeRemaining

**Comment by MelvorIdle** [comment]
Fixed in v0.18
