### ISSUE TITLE
Rags to Riches 1 continues to repeat when item is exhausted

### ISSUE THREAD

**Issue by ItsPandatory** [MelvorIdle/melvoridle.github.io#523]
**Describe the bug**
Rags to Riches 1 continues to attempt to cast repeatedly when the item being converted runs out. I suspect this is a bug because I haven't seen any other crafted item work this way

**To Reproduce**
1. Cast rags to riches 1 with any junk item
2. Let it cast until junk item is exhausted

**Expected behavior**
A clear and concise description of what you expected to happen:
To be more consistent with other crafting I expect the craft to fail once and then stop.

**Screenshots**
In the screenshot the beginning of the second "item doesn't exist" error message is visible.
![R2R 1](https://user-images.githubusercontent.com/75848979/102039222-6dae8d00-3d86-11eb-9d53-c15e1e1e85e4.png)

**Browser**
Steam

**Console output**
Steam

**Are you using any scripts?**
No scripts

**Comment by MelvorIdle** [comment]
Should be fixed in v0.18
