### ISSUE TITLE
View Item Stats bug

### ISSUE THREAD

**Issue by ItsPandatory** [MelvorIdle/melvoridle.github.io#524]
**Describe the bug** (using helmet as example)
When comparing a helmet to one in the second gear set the window instead compares it to the helmet in the first set if both sets have a helmet equipped. If the second gearset has no helmet equipped then the stats correctly compare to the empty slot.

**To Reproduce**
1. Have at least two equipment sets with helmets equipped
2. Select first set and view item stats of a helmet from inventory
3. Select the second set and view item stats of the helmet
4. It will compare it to the helmet on gear set1 even when set2 is selected.

**Expected behavior**
I would expect the item to compare to the currently selected gear set

**Screenshots**
Screenshots show an Ice Helmet compared to a (G) Dragon Helm and then to a Hard Leather Cowl and they show  the same stat change.
![view item stats](https://user-images.githubusercontent.com/75848979/102160082-00603200-3e42-11eb-9889-9ed6fbc5874a.png)

**Browser**
Steam

**Comment by MiccWan** [comment]
I think this should be a `suggestion` instead of a `bug`? Currently it shows the comparison of the set you are "wearing(using)".

**Comment by travisderouen** [comment]
To give more details on this bug, the current way it works is that the item you want to compare is always getting compared whatever item is on the set that you are currently wearing. For example, I'm idling Water God dungeon using gear in Set 2. I am setting up gear in Set 3 for use to idle my next dungeon. When I go to compare gear in my bank against the gear in Set 3, it instead compares to the gear I'm currently using in Set 2.

https://i.imgur.com/i6s0hAN.png
This is comparing Terran gloves (bank) to Aeris gloves (Set 2).

https://i.imgur.com/DaEdnLc.png
This is supposed to compare Terran gloves (bank) to Ragnar gloves (Set 3).

As you can see, the stat differences are the same when compared to 2 very different gloves.

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
