### ISSUE TITLE
Affliction procs on miss when Protect from X prayer active

### ISSUE THREAD

**Issue by TrickleDownEconomics** [MelvorIdle/melvoridle.github.io#526]
**Describe the bug**
Enemies in Into the Mist Dungeon still stack Affliction debuff when missing while any Protect from X prayers are active. It seems to happen inconsistently, which leads me to believe it's proccing only on the attacks that would have otherwise landed if the prayer wasn't active.

**To Reproduce**
1. Go to 'Into the Mist Dungeon"
2. Activate appropriate Protect from X prayer
3. See health decrease by 1% on "Miss"

**Expected behavior**
Gain no Affliction stacks on missed enemy attack

**Screenshots**

**Browser**
Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
yes but also ran the dungeon with them disabled

**Comment by TrickleDownEconomics** [comment]
double checked, also happens on mobile (IOS)

**Comment by coolrox95** [comment]
Affliction has a 70% chance to apply on the first attack of an enemy's turn. This is intended behavior.
