### ISSUE TITLE
Able to reset attack by selecting same equipment slot (e.g. to use special every attack)

### ISSUE THREAD

**Issue by MatthewThompson** [MelvorIdle/melvoridle.github.io#528]
**Describe the bug**
When on the combat screen, selecting "Change Equpment Set" but selecting the same set that is currently in use, it resets the attack. This means you can keep clicking it to ensure every attack will be a special. Obviously a big buff when using Ragnar Godsword, for example.

**To Reproduce**
1. Enter combat.
2. Click on "Change equipment set" number that is currently green (in use).
3. See that your current attack is reset, step 2 can be quickly repeated until your attack changes to special.

**Expected behavior**
The selected slot button should be disabled, or it should do nothing.

**Browser**
Chrome, latest version I think.

**Are you using any scripts?**
No scripts.

**Comment by MelvorIdle** [comment]
Hotfix coming out today
