### ISSUE TITLE
Smithing cape does not reduce coal requirement

### ISSUE THREAD

**Issue by sefto1jr** [MelvorIdle/melvoridle.github.io#529]
**Describe the bug**
After 0.18 update, equipping the Smithing Cape does not reduce coal requirements.  Smithing Dragonite Bars still results in using 6 coal each time (when resources are not retained through mastery)

**To Reproduce**
Happens every time.  I tried unequipping the cape and switching activities and then re-equipping the cape and resuming smithing, but this does not fix the issue. Restarting the game doesn't fix this either.

**Expected behavior**
I expected my coal to reduce by 3 when crafting each dragonite bar, rather than 6.

**Are you using any scripts?**
no

**Comment by Tharyz** [comment]
Just noticed this too. Tried everything(Other bars, re-equip cape etc.) but it's not reducing coal requirements.

**Comment by MelvorIdle** [comment]
Not sure what the bug is? The original Coal Requirements for Dragonite Ore is 12 Coal.

https://puu.sh/GYi0i/f732a88c51.png

**Comment by Tharyz** [comment]
Yep, you are right. I got confused.

**Comment by sefto1jr** [comment]
I guess I was too.
