### ISSUE TITLE
Kutul behaviour

### ISSUE THREAD

**Issue by MLuneth** [MelvorIdle/melvoridle.github.io#530]
**Describe the bug**
Ku-Tul occasionally autoattacks 1-2 times after using elusiveness

**To Reproduce**
1. Fight Ku-Tul
2. Sometimes it does weird shit

**Expected behavior**
It should only cast elusiveness or Curse of the Deep

**Screenshots**
![image](https://user-images.githubusercontent.com/76060656/102241922-6f747e00-3f49-11eb-864d-8927b71f6ec3.png)
This is the gear I was using to fight it 
Only prayer active is protect item

**Browser**
Chrome, Alpha V0.18

**Console output**
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/57190bf….map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
VM1764 index.php:10783 GET https://cdn.melvor.net/core/v018/assets/media/shop/assets/media/shop/perpetual_haste.svg 403 (Forbidden)
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/13c2891….map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
save.js?604:9 Loading Save Game...
save.js?604:25 Save Game Loaded...
smithing2.js?604:9 Loading Smithing...
mastery.js?604:2 Loading Masteries...
main.js?604:6 Game Loaded
cloud.js?604:93 Connected to PlayFab successfully
prebid.min.js:3 fun-hooks: referenced 'registerAdserver' but it was never created
adthrive.min.js?threshold=0:17 AdThrive::init started
Enabler.js:166  [  0.000s] [studio.sdk]  
Enabler.js:166  [  1.179s] [studio.sdk] Using default ad parameters in test environment. Simulating local events. 

**Are you using any scripts?**
No scripts or addons

**Comment by Falterfire** [comment]
Not a bug - Elusiveness can't stack, so when it would use Elusiveness while still under the effects of a previous use of it, it'll instead do an auto-attack.
