### ISSUE TITLE
Miolite Sceptre not behaving as a melee weapon

### ISSUE THREAD

**Issue by Tardivex** [MelvorIdle/melvoridle.github.io#533]
**Describe the bug**
The Miolite Sceptre behaves as a wand instead of a melee weapon, this means that its attack style is magic and defensive like other magic weapons, it uses runes and spells from the standard, curse, aurora and ancient spellbooks to attack, and when it comes to the combat triangle, it gets bonuses against melee enemies and negatives against ranged enemies just like other magic weapons.

**To Reproduce**
1. Simply equip the Miolite Sceptre and use it in combat

**Expected behavior**
As a melee weapon it should have the standard attack styles like stab, slash or block while benefiting from the strength and attack stat bonuses inherent to the item. It also shouldn't be able to cast standard or ancient spells.

**Screenshots**
Magic attack styles, negative chance to hit because it's using magic and not melee bonuses.
![miolite1](https://user-images.githubusercontent.com/76079819/102293657-4abadf00-3f26-11eb-896c-67362b2ed79f.png)

Casting ancient magicks with the sceptre.
![miolite2](https://user-images.githubusercontent.com/76079819/102293660-4c84a280-3f26-11eb-8d26-725774fafd16.png)

**Browser**
Firefox 83.0 (64-bit)

**Comment by MelvorIdle** [comment]
Hotfix coming out today
