### ISSUE TITLE
[Minor] Bogus tooltip for "Teak cooking fire"

### ISSUE THREAD

**Issue by nicolasalt** [MelvorIdle/melvoridle.github.io#534]
There is a bogus tooltip when hovering over the "teak" icon: 
![Screenshot 2020-12-16 at 13 42 47](https://user-images.githubusercontent.com/1146358/102350627-77faa200-3fa5-11eb-86f9-c7acb32c5a7d.png)

**Browser**
Chrome 87.0.4280.88

**Console output**
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
?l=1:10785 GET https://cdn.melvor.net/core/v018/assets/media/shop/assets/media/shop/perpetual_haste.svg 403 (Forbidden)
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/13c28911820333eb6a51103a0e2096477a38941cc79afbf16b59f3d5a5f63086.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
save.js?606:9 Loading Save Game...
save.js?606:25 Save Game Loaded...
smithing2.js?606:9 Loading Smithing...
mastery.js?606:2 Loading Masteries...
main.js?606:6 Game Loaded
main.js?606:214 [388]
cloud.js?606:93 Connected to PlayFab successfully

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Hotfix coming out today

**Comment by nicolasalt** [comment]
Thanks for the quick fix!
