### ISSUE TITLE
Ancient ring of skill does not boost strength experience gained from fishing

### ISSUE THREAD

**Issue by aceg00** [MelvorIdle/melvoridle.github.io#535]
**Describe the bug**
Ancient ring of skill does not boost strength experience gained from fishing in barbarian fishing area. 

**To Reproduce**
1. Equip ancient ring of skill and barbarian gloves
2. Fish any leaping fish, for example, leaping broad fish
3. See strength exp gain in combat screen

**Expected behavior**
Should be 27xp per fish. Now it is 25xp

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
That's because Strength does not fall under the category of "Skills", just like all other combat skills.
