### ISSUE TITLE
Hunting Greater Dragon Agility special attack incorrect damage

### ISSUE THREAD

**Issue by Falterfire** [MelvorIdle/melvoridle.github.io#536]
**Describe the bug**
The Hunting Greater Dragon's Agility special attack has a description that says it does 650 damage, but the setDamage value on the attack is only 60 so it actually only does 600 damage.

**To Reproduce**
1. Fight a Hunting Greater Dragon with 0% DR
2. Get attacked with Agility
3. Take 600 damage instead of 650

**Expected behavior**
Either the description needs to be changed or the damage dealt needs to be increased to match the current descriptoin.

**Browser**
Chrome

**Console output**
No relevant console output

**Are you using any scripts?**
Yes, but none that are relevant here.

**Comment by MelvorIdle** [comment]
Hotfix coming out today
