### ISSUE TITLE
Superheat3 failing due to full inventory but showing no error

### ISSUE THREAD

**Issue by ItsPandatory** [MelvorIdle/melvoridle.github.io#537]
**Describe the bug**
Tried to cast superheat3 with full inventory and nothing happened. The progress bar would fill once and then stop and no error message was shown. Also tested with SH1, SH2, and Bone Offering and had the same result. I have "ignore bank full" disabled in settings.

**To Reproduce**
1. Have a full inventory
2. Attempt to cast superheat3 for a bar that is not already in inventory

**Expected behavior**
I expect a "Bank Full" error message

**Browser**
Steam.

**Comment by MelvorIdle** [comment]
Hotfix coming out today
