### ISSUE TITLE
Ku-tul's Curse of the Deep description/effect mismatch

### ISSUE THREAD

**Issue by Falterfire** [MelvorIdle/melvoridle.github.io#538]
**Describe the bug**
Ku-tul's Curse of the Deep special attack has an attackCount of two, but the description just says "an avoidable attack that deals 970 damage"

**To Reproduce**
1. Fight Ku-tul
2. Get hit by Curse of the Deep
3. Watch two hits happen

**Expected behavior**
Either the description should reflect that it hits twice or the attack should only hit once

**Screenshots**
[Gif somebody posted on Discord](https://cdn.discordapp.com/attachments/625838709744599088/788851505809719316/kutul_2_hits.gif)

**Browser**
Chrome

**Console output**
None relevant

**Are you using any scripts?**
None that are relevant.

**Comment by MelvorIdle** [comment]
Hotfix coming out today
