### ISSUE TITLE
In the Item Tab, Normal Logs have "Total Attacks", "Attacks Missed" and "Damage Dealt"

### ISSUE THREAD

**Issue by RubyPiec** [MelvorIdle/melvoridle.github.io#539]
**Describe the bug**
In the Item Tab, Normal Logs have "Total Attacks", "Attacks Missed" and "Damage Dealt"

**To Reproduce**
1. Completion Log
2. Items
3. Hover over Normal Logs
4. See it

**Expected behavior**
For that not to appear

**Screenshots**
https://cdn.discordapp.com/attachments/625838709744599088/788857257923313704/unknown.png

**Browser**
Chrome 87

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
No

**Comment by coolrox95** [comment]
Issue was fixed with #821
