### ISSUE TITLE
[Minor] Dungeon Paused box stays when changing creature

### ISSUE THREAD

**Issue by 47Y** [MelvorIdle/melvoridle.github.io#540]
**Describe the bug**
The DUNGEON PAUSED box stays on screen if you switch to a different combat creature while Into the Mist is paused.

**To Reproduce**
1. Defeat the first 20 monsters in Into the Mist.
2. While the dungeon is paused, start fighting another creature.
3. The box for DUNGEON PAUSED along with the button to Start the Fight will remain.

**Expected behavior**
The DUNGEON PAUSED box goes away when no longer in the dungeon.

**Screenshots**
![Screenshot](https://i.imgur.com/y65gaPQ.png)

**Browser**
This happened with both Firefox and the Steam game.

**Console output**
No errors upon switching monsters, but if you click the button after switching:
![Console](https://i.imgur.com/00D8REc.png)

**Are you using any scripts?**
No scripts were used.

**Comment by MelvorIdle** [comment]
Hotfix coming out today
