### ISSUE TITLE
No option to equip items to passive slot on mobile

### ISSUE THREAD

**Issue by Stewartish** [MelvorIdle/melvoridle.github.io#541]
**Describe the bug**
After beating ITM, I read the book and could not find any option to equip items such as the chapeau noir into the new passive slot. There is not even an indication on their selection page in the bank tab that they would be equippable to this slot, as said in the patch notes

**To Reproduce**
1. Finish ITM
2. Run away from combat
3. Change equipment sets to refresh equipment popup - passive slot is now visible
4. Go to bank tab
5. Open & read lore book
6. Select chapeau noir (or any passive-equippable item)
7. See there is no indication that they would be equippable
8. See there is no button to equip them

**Expected behavior**
To be able to identify which items are equippable to the passive slot and to have a button to equip them there.

**Screenshots**
![Screenshot_20201216-154259](https://user-images.githubusercontent.com/76130791/102406539-b5b4f600-3fb8-11eb-8b7a-ca5b4ee18299.png)
![Screenshot_20201216-154136](https://user-images.githubusercontent.com/76130791/102406556-bc436d80-3fb8-11eb-819b-a63e467cbe48.png)
![Screenshot_20201216-154150](https://user-images.githubusercontent.com/76130791/102406578-c4031200-3fb8-11eb-9718-3947a43f99ac.png)

**Browser**
Mobile/google play store/paid version/Alpha V0.18

**Console output**
Please open the console by pressing F12 and copy it here.
(I'm on mobile)

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.
(No)

**Comment by MelvorIdle** [comment]
Thanks, looks like the button doesn't exist on the sidebar (But it will be sitting at the bottom). Will get it fixed

**Comment by MelvorIdle** [comment]
Hotfix coming today
