### ISSUE TITLE
Autoeat throwing undefined errors in golbin raid

### ISSUE THREAD

**Issue by 8992scripts** [MelvorIdle/melvoridle.github.io#543]
If you have not bought autoeat then eatFood function will throw errors in golbin raid when autoeat triggers

The error is on this line:
if (autoEat && combatData.player.hitpoints < maxHitpoints * (autoEatData[currentAutoEat - 1].maxHP / 100))

autoEatData[currentAutoEat - 1].maxHP is undefined if you haven't bought it. It should be using the golbin autoeat if you're in a golbin raid not currentAutoEat

**Comment by MelvorIdle** [comment]
Hotfixed
