### ISSUE TITLE
Sand Treaders no work with Ancient Knives

### ISSUE THREAD

**Issue by scwhellum** [MelvorIdle/melvoridle.github.io#546]
**Describe the bug**
When using Sand Treaders with Ancient Knives, it doesnt seem to either show the attack speed change correctly or doesnt change it at all.

**To Reproduce**
Equip Sand Treaders.
Kill something with knives on rapid.
Still shows as 1.6s attack speed

Tried equipping aeris godsword and speed reduction showed correctly. (3.2s down to 3.1s)

**Expected behavior**
Shouldda been 1.5s

**Screenshots**

Knives attack speed
![image](https://user-images.githubusercontent.com/76149658/102455279-3b0ada00-408f-11eb-9bad-79419cdc08aa.png)

AGS attack speed
![image](https://user-images.githubusercontent.com/76149658/102455418-802f0c00-408f-11eb-873a-62e1045d14c8.png)

**Browser**
Steam Version

**Console output**
Pressing F12 made me do a steam screenshot. Thanks >.>

**Are you using any scripts?**
Nah fam no scripts

Thanks for being sexy btw <3

**Comment by scwhellum** [comment]
Another one its happening to.
Ancient Crossbow attack speed is not reduced either.

![image](https://user-images.githubusercontent.com/76149658/102455889-46123a00-4090-11eb-819a-bb443cd0ee9a.png)

**Comment by scwhellum** [comment]
To add on to this I did a bit more testing.
I tried about 5 different melee weapons and their attack speed was changed correctly.
I tried about 5 different magic weapons and their attack speed was changed correctly.
However, all ranged weapons I had did not change at all. Tried all throwing knives, Stormsnap, ACB and Slayer Cbow.

Hope that helps with finding the problem.

**Comment by MelvorIdle** [comment]
Hotfix coming out today for this one
