### ISSUE TITLE
Slayer 'Cancel' new task selection button disappaers when monster respawns.

### ISSUE THREAD

**Issue by Silberdrachi** [MelvorIdle/melvoridle.github.io#548]
**Describe the bug**
When clicking "New Task" in the combat window, if you do not choose a new task before a monster respawns it will change the "Cancel" button to "New Task" again. While still leaving up the selection for slayer type.

WORKAROUND: Clicking new task again will not change the slayer options, but will change "New Task" back to "Cancel". And when clicking cancel, or any of the slayer options they work as intended

**To Reproduce**
1. Go to Combat window
2. Start combat with any monster
3. Click on "New Task" in the Slayer Task pane
4. Wait for monster to die and then respawn to continue combat
5. See error

**Expected behavior**
Cancel button should still be available after monsters respawn.

**Screenshots**
![image](https://user-images.githubusercontent.com/76179203/102526974-73e48800-406a-11eb-9a96-f34e67a7633d.png)

**Browser**
Firefox 83.0 (64-bit)

**Console output**
No abnormal console output

**Are you using any scripts?**
No scripts

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
