### ISSUE TITLE
Mastery Checkpoint Confirmation Pops Up Despite Safe XP Spending

### ISSUE THREAD

**Issue by JinNada** [MelvorIdle/melvoridle.github.io#549]
While you are in the Spend XP mastery tab, should your mastery pool increase enough that spending exp will no longer dip you below a mastery checkpoint, the mastery checkpoint notification will still pop up. 

1. Go to the Fishing skill
2. Click on the Spend XP tab while are you are actively fishing for something
3. Wait until the level up option goes from "yellow" to "green" for any mastery
4. Try to level up the mastery and the popup will still appear

The popup should no longer be appearing as it is now safe to level up that mastery despite it not being safe when the tab was initially opened.  The color cue correctly notes and updates with the changing mastery pool properly.  Upon clicking confirm that you are okay with spending the mastery points despite supposedly dropping below the checkpoint, the points are spent appropriately and you remain above the checkpoint.

The bug occurred using Chrome Version 87.0.4280.88 (Official Build) (64-bit) and the Steam client BuildID 5866995

No scripts were in use at the time this bug occurred.

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
