### ISSUE TITLE
Invading extradimensional army

### ISSUE THREAD

**Issue by mrDLSable** [MelvorIdle/melvoridle.github.io#55]
The idea for this quest line is the fairly cliché one where and extradimensional army invades the dimension. This could be a demon army, orcs, or even space elves or something. I imagine this being a quite long quest line that can be rolled out over time.

If the world event / raids system is implemented it can be tied into that.

# Storyline
A gate from the underworld / another dimension has opened up and resources are needed to defend Melvor. Scouting parties have been seen exiting the portal. The rulers of Melvor presume that an invading army will be coming out soon, so preparations have to be made.

The player, as a known adventurer, is sent out to help prepare for the war. Wood is needed to build palisades. Weapons and armour are needed to arm soldiers that are being recruited for the conflict. Food is needed to feed that army.

These needs can be rolled out over multiple quests as various factions fight over how to respond to the threat. Some will be all for preparing a large army while others don't think there is anything to worry about. We could even have spies in the ruling class of Melvor who actively work to disorganize the preparations and the player has to root them out.

# Quests

1. A gate has appeared
2. Drive back the scouts
3. Build a palisade around the Gate
4. Arm the peasants
5. The general's assistant has gone missing
6. Feed the army

## 1. A gate has appeared
In the plains north of Edobridge near the Edo river a large Gate made of black stone has appeared. It is said to be twenty meters wide and a hundred meters tall. The king wants more information and sends you on an exploration mission.

Depending on how the world system is implemented I either suggest something like an investigate option on a location, or a new enemy called scouts of which you have to defeat a certain amount.

## 2. Drive back the scouts
The army general thinks that striking early and hard is the best option. You are tasked with driving back the scouts with as little information as possible. You have to defeat an X number of scouts.

## 3. Build a palisade around the Gate
Now that the immediate threat is gone, the economy minister doesn't want to divert resources to build up defenses around the Gate. So now the king, who thinks that the threat is not over yet, has tasked you with building up some palisades around the Gate.

For this you will have to gather different types of wood and nails and then if construction is already implemented build the palisades.

## 4. Arm the peasants
Even though the scouts have been driven back, the army general doesn't think that the threat is gone, and thus wants to expand the army. But the finance minister still thinks that there is no need for action and thus won't make a lot of funds available. Thus there is no money for buying weapons and armour.

You have to supply the following items in large quantities:
- Iron armour
- Iron swords
- Oak bows
- Iron arrows

## 5. The general's assistant has gone missing
The assistant of the general has gone missing. You have to find out why. When you investigate you find out that he has been abducted by a few of the remaining scouts. You have to defeat scouts to get a special quest item on which the location where he is kept is written down. On that piece of paper it also states that there is someone working inside the government helping the invaders. Then you have to go to the location specified in the note and investigate to find the assistant. But you only find his dead body.

## 6. Feed the army
The increase in soldiers has caused the old army food suppliers to be unable to cope. The army general has asked you to help him fill the gap and supply the needed food.

You have to supply the following items in large quantities:
- Trout
- Potatoes
- Cabbage

## More to come
I have more ideas, but I don't have time to type them up right now...

**Comment by TBNRBoom** [comment]
pog?
