### ISSUE TITLE
Auto Eat icon remains after Golbin Raid

### ISSUE THREAD

**Issue by Izzy4900** [MelvorIdle/melvoridle.github.io#550]
**Describe the bug**
The Auto Eat indicator is still visible after ending a Golbin Raid despite not having bought the upgrade

**To Reproduce**
1. Go to Golbin Raid
2. Start a raid, which gives you Auto Eat as intented
3. End the raid
4. The Auto Eat icon will still be there, until the game is closed 

**Expected behavior**
The Auto Eat icon to disappear I guess, since I don't have the upgrade from the store

**Browser**
Playing on Steam

**Are you using any scripts?**
No scripts

**Comment by coolrox95** [comment]
Fixed with update v0.21
