### ISSUE TITLE
Desert hat could display before Magical ring

### ISSUE THREAD

**Issue by ItsPandatory** [MelvorIdle/melvoridle.github.io#551]
Why are you suggesting this?
I think The Desert Hat should display first because it comes before the ring in progression and the rest of the "grants access" items are displayed in order. I suspect the ring is there from its legacy A0.17 position.

How does your suggestion benefit the game?
Improves the continuity of the items and makes them slightly more intuitive. In the current order someone may accidentally buy the ring first and be mildly annoyed.

It is suggested that you provide (mockup) art to ilustrate things where relevant in order to make your suggestion more clear.
![slayer gear sugg](https://user-images.githubusercontent.com/75848979/102560004-6b9e4400-408e-11eb-968d-f295da24cc56.png)

**Comment by MelvorIdle** [comment]
Fair suggestion that makes sense. I'll sneak this change into the game

**Comment by sbabudro** [comment]
Seems like the change got reverted? The Desert Hat is once again listed after the Magical Ring, though with a new Mirror Shield item before the Ring.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
