### ISSUE TITLE
Chapeau Noir has no affect on thieving loot

### ISSUE THREAD

**Issue by CollinHeist** [MelvorIdle/melvoridle.github.io#552]
**Describe the bug**
Looking through the `thieving.js` code, it appears the Chapeau Noir has no effect on any items received during Thieving actions.

**To Reproduce**
1. Equip the Chapeau Noir (and ideally no other doubling equipment/effects).
2. Enter the Thieving skill.
3. Perform any thieving actions 
4. Wait...

**Expected behavior**
After some statistically significant number of samples, it would be expected that the doubling effect of the Chapeau would be observable - however, either by observing the thefts (or more easily - examining the code), it can be seen this is not the case.

**Browser**
Firefox 81.0.2 64-bit - however this is likely unrelated.

**Comment by MelvorIdle** [comment]
Hotfix coming out today for this
