### ISSUE TITLE
Item Count Error

### ISSUE THREAD

**Issue by IndexIllusion** [MelvorIdle/melvoridle.github.io#553]
**Describe the bug**
I have -16,609 Green Dragonhide in my inventory. This number is supposed to be positive, and because I have a negative amount, I am unable to sell it or use it for crafting in any manner.

**To Reproduce**
Unfortunately, I have no way to tell on how to recreate this issue. No idea when it occurred as I only noticed it logging on today.
The only information that I can give regarding this issue is that all of this dragonhide I had obtained from mob drops, and the night before this bug I had bought 50,000 leather which is something I had never done before, so maybe the two events are related?

EDIT:
Finally discovered what is happening here. Oddly enough, when I craft offline using regular leather, it consumes my green leather, and when I used my green leather offline (which I had to fix using a cheat engine), my red leather got used? Regardless, as of this morning I logged on to have negative black leather after crafting with red leather overnight.

>>It would appear that the wrong item IDs are being used somewhere here?

**Expected behavior**
I expected to have 16,609 Green Dragonhide as opposed to -16,609.

**Screenshots**
![image](https://user-images.githubusercontent.com/53729381/102636027-2166a280-4122-11eb-8381-7af23a0914e8.png)

**Browser**
I am playing Melvor Idle via the steam release.
Alpha V0.18
I had logged into my browser, Opera GX, to check and see if the result was any different and it is not.

**Console output**
Unsure if there is an in-game console that was supposed to open, but I instead opened my browser console.
![image](https://user-images.githubusercontent.com/53729381/102636430-a18d0800-4122-11eb-82ee-04c94fcaf5dd.png)

**Are you using any scripts?**
No, I am playing the game entirely vanilla.

**Comment by Knowlue** [comment]
I have the same error on my barrentoe seeds. Negative count.

**Comment by NealAJohnson** [comment]
There's another bug open about this. Facing the same issue with runes. 
![Uploading Screenshot_20201224-174448_Melvor Idle.jpg…]()
