### ISSUE TITLE
Make glove and item buy quantity dropdowns independent

### ISSUE THREAD

**Issue by evanrenaud** [MelvorIdle/melvoridle.github.io#554]
Why are you suggesting this?
Myself and others have purchased way too many gloves. I assumed the glove dropdown would be set to 1 since I had never touched it, not realizing it was synced to the item dropdown

How does your suggestion benefit the game?
It is a more intuitive UX in my opinion, and could help avoid mis-clicks

It is suggested that you provide (mockup) art to ilustrate things where relevant in order to make your suggestion more clear.
in shop.js:
new var
```
var gloveBuyQty = 1;
```
in updateShop:
```
updateGloveBuyQty(gloveBuyQty);
```
new function
```
function updateGloveBuyQty(qty) {
    gloveBuyQty = parseInt(qty, 10);
    $("[id=shop-buy-qty-glove-btn]").text("Buy x" + formatNumber(qty));
    updateShopPrices();
}
```
lines 651-654 in updateShopPrices:
```
    for (let i = 0; i < glovesCost.length; i++) {
        $("#shop-gloves-charges-" + i).text(numberWithCommas(gloveBuyQty * glovesActions[i]));
        $("#shop-gloves-" + i).text(numberWithCommas(gloveBuyQty * glovesCost[i]));
    }
```
in `buyGloves` change buyQty to gloveBuyQty
in the shop html, change the id of the glove dropdown to `shop-buy-qty-glove-btn` and have its dropdown items call `updateGloveBuyQty` instead of `updateBuyQty`

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
