### ISSUE TITLE
Mining bug ? 

### ISSUE THREAD

**Issue by Smeakel** [MelvorIdle/melvoridle.github.io#556]
Uhm, if i close the tab to quickly and re-open it again. It happens on my pc and my friends. We are both using the latest from google chrome. But it happens on mobile as well. 
The bug is:
Mining stops, it stops the process
When does it happened:
When quickly reopening the tab just after you swapped to another tab
When you close it and re open it on phone
----------------------------------------------------------
Its like it stops mining exactly as you open the tab again.
It also happens a lot when the note is re-charging and you re open the tag/app

**Comment by Smeakel** [comment]
Oh it primarily happends on Addy, rune or dragon for some reason.

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
