### ISSUE TITLE
Goblin Raid- Instantly killing mobs (persisted outside of raid)

### ISSUE THREAD

**Issue by Dev-kris** [MelvorIdle/melvoridle.github.io#558]
**Describe the bug**
While in a run in the Goblin Raid I encountered a bug that made my attack speed faster than I could measure (maybe 100 per second), while the enemy attack speed remained normal. This meant that each stage in the goblin raid was completed before I could even click on a reward.

This is incredibly big since it actually continued outside of the raid, allowing me to kill almost any mob or even dungeon almost instantly. 

**To Reproduce**
I suspect the sandstorm ring caused this behavior. Due to it's special attack, but since it originated in the Goblin Raid, I am unlikely to be able to reproduce this bug.

**Expected behavior**
Attack speed should be at a normal value, and checks should be put in place to ensure nothing from Goblin Raid carries over.

**Screenshots**
![image](https://user-images.githubusercontent.com/61651282/102712125-da61e400-42be-11eb-8c2f-4b9c421a2e20.png)

**Browser**
Brave v 1.18.75

**Console output**
I am sorry, I hit F5 before reading this. (it did fix the bug)

**Are you using any scripts?**
No

**Comment by coolrox95** [comment]
Issue fixed with update v0.21.
