### ISSUE TITLE
Superheat III stops working on mithril bars

### ISSUE THREAD

**Issue by ArcChris518** [MelvorIdle/melvoridle.github.io#559]
When starting Superheat III at least on mithril bars, if you leave the app/close the app, and return at any time from one minute to one day. It will stop superheating bars and say you do not have the required materials (even when you do) it continues to work and craft bars when AFK from the app but upon returning is when it stops.

**Comment by coolrox95** [comment]
Alt. Magic was rewritten as of v1.0.2.
