### ISSUE TITLE
Attack milestones window - "Wield Godswords" image broken

### ISSUE THREAD

**Issue by Shamus03** [MelvorIdle/melvoridle.github.io#560]
**Describe the bug**
The image next to "Wield Godswords" in the attack milestones window is broken.

It links to https://cdn.melvor.net/core/v018/assets/media/bank/aeris_godsword.png

I think the correct link is https://cdn.melvor.net/core/v018/assets/media/bank/weapon_sword_ancient.svg (svg extension)

**To Reproduce**
1. Go to the "Milestones" menu
2. Click on "Attack"
3. See the broken image

**Expected behavior**
A non-broken image

**Screenshots**
![image](https://user-images.githubusercontent.com/739815/102727280-650c0880-42ea-11eb-9ac2-e8d7000c0d5f.png)
![image](https://user-images.githubusercontent.com/739815/102727329-b4eacf80-42ea-11eb-983c-52626b5d1284.png)

**Browser**
Chrome

**Are you using any scripts?**
Yes, I use SEMI and Melvor Action Queue - but those do not affect this part of the game.

**Comment by MelvorIdle** [comment]
Related #585
