### ISSUE TITLE
Negative blue dragonhide count

### ISSUE THREAD

**Issue by Jongy1** [MelvorIdle/melvoridle.github.io#561]
**Describe the bug**
After crafting green dragonhide bodies overnight, in the morning my stack of ~200 blue dragonhide became -25k. I am unsure if the correct amount of green dragonhide was used.

**To Reproduce**
Cannot reproduce.

**Expected behavior**
Green dragonhide count to decrease, blue dragonhide count to be unaffected.

**Screenshots**
![image](https://user-images.githubusercontent.com/76436506/102780183-67736e80-438d-11eb-9bab-09086cd3b6ed.png)

**Browser**
Google Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Console output**
Please open the console by pressing F12 and copy it here.
![image](https://user-images.githubusercontent.com/76436506/102780419-c933d880-438d-11eb-8dff-7b7da1901ea7.png)

**Are you using any scripts?**
No scripts used.

**Comment by NealAJohnson** [comment]
I have negative of two time types, but I play on mobile so I have no console to open.
