### ISSUE TITLE
Mystic Prayers have different description

### ISSUE THREAD

**Issue by ItsPandatory** [MelvorIdle/melvoridle.github.io#563]
**Describe the bug**
Mystic Will and Lore state "+5/10% Magic Accuracy and Evasion Rating" while Mystic Might states "+15% Magic Accuracy and Defense Rating". However, mystic might still increases accuracy and evasion.

**To Reproduce**
1. Go to prayers
2. Click on Mystic Will or Lore and then Might

**Expected behavior**
I would either expect the description for mystic might to match the first two, or (less likely) for mystic might's function to be different in a way that matches the current description.

**Screenshots**
![Mystic Prayers](https://user-images.githubusercontent.com/75848979/102826582-33ed1000-439e-11eb-8b13-d3be189cd563.png)

**Browser**
Steam

**Comment by MelvorIdle** [comment]
Fixed the description in the upcoming update
