### ISSUE TITLE
Green Dragonhide buy and sell prices are the same

### ISSUE THREAD

**Issue by ItsPandatory** [MelvorIdle/melvoridle.github.io#564]
Why are you suggesting this?
Buy/sell prices of Leather are 100/50, Blue D-hide 350/300, Red D-hide 550/400. Only the Green D-hide is 200/200. I can buy and sell it with no penalty when leveling crafting. I suspect this is unintended because the other 3 lose value when I buy/sell.

How does your suggestion benefit the game?
Lowering Green D-hide sell price (maybe to 150) would make it more consistent with the other crafting mats.

Edit: looking at the crafted Green D-hide items this equal buy/sell price extends to them too. If you think this is an issue, maybe increasing the green d-hide buy price to 150+leather (for 250 total) and making it 250/200 buy/sell is the easiest way to fix it.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
