### ISSUE TITLE
Slayer not being highlighted while training but thieving is.

### ISSUE THREAD

**Issue by ItsPandatory** [MelvorIdle/melvoridle.github.io#568]
**Describe the bug**
In the screenshot I am fighting a Druid using ranged. Slayer is not highlighted green but thieving is. 

I didn't find any condition that causes slayer to be highlighted. I tested slayer tasks and fighting in slayer areas with all three combat types.

I did some testing with the other attack types and it seems to only be ranged that turns thieving green.

**To Reproduce**
1. Fight anything as ranged
2. Look at thieving in skills list
3. See error

**Expected behavior**
I would expect Slayer to get the green highlight in areas where it was being trained and also that thieving not be highlighted while training ranged.

**Screenshots**
![Slayer-Theiving](https://user-images.githubusercontent.com/75848979/102948957-56f1ef80-4484-11eb-88df-722ff0ff947e.png)

**Browser**
Steam

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
