### ISSUE TITLE
Hover Text Misaligned When "Set Zoom Level" is  Changed

### ISSUE THREAD

**Issue by Ness-9** [MelvorIdle/melvoridle.github.io#571]
**Describe the bug**
When changing the "Set Zoom Level" in the steam version of the game, Hover text becomes severely misaligned and can even be extended below the bottom of the window (unable to be seen).

**To Reproduce**
1. Launch the steam version of the game
2. Go to "Settings"
3. Change "Set Zoom Level" to 70%
4. Go to the Smithing page (Any page with hover text works)
5. Mouse over any of the bars.
6. Hover text will be much lower on the screen than your mouse.

**Expected behavior**
Hover Text should appear near the cursor and remain within the window.

**Screenshots**
![image](https://user-images.githubusercontent.com/69043252/103002511-a7a13100-44f4-11eb-92d6-904e7f274e5a.png)

**Browser**
N/A - this is the steam version

**Console output**
N/A - this is the steam version.

**Are you using any scripts?**
No scripts are in use.

**Comment by mazunki** [comment]
This also affects the "shortcut icons" on the right side for me, leaving a horizontal scrollbar which is useless.

I would really love to change the scale to 70%, or even lower if possible, but due to the bugs presented, I don't.

**Comment by Delekates** [comment]
Same issue for me!

**Comment by InfinitySamurai** [comment]
Yep I've also run into this issue

**Comment by MelvorIdle** [comment]
Same bug as #497

Closing this to clean up.
