### ISSUE TITLE
Christmas update seems to have brought back the white scroll bar for Steam version

### ISSUE THREAD

**Issue by HellFiraga** [MelvorIdle/melvoridle.github.io#572]
**Describe the bug**
The white scroll bar is back after receving the christmas update earlier today.
Only appears to be affecting Steam versions. Browser and Mobile are fine.

**To Reproduce**
Open Melvor on Steam, Check scroll bar on left hand side.

**Expected behavior**
Should be invisible and then show a thing line for scroll when hovered over

**Screenshots**

![image](https://user-images.githubusercontent.com/76149658/103010206-d5838580-4587-11eb-95c4-c4e5e28258a5.png)

**Browser**
Steam

**Console output**
N/A

**Are you using any scripts?**
No sir

**Comment by Revolyze** [comment]
This also removes space for this panel, so when you set it to 70% zoom, some skills will take up 2 lines instead of 1.
