### ISSUE TITLE
Steam Version Does Not Save Zoom Setting Between Restarts

### ISSUE THREAD

**Issue by Ness-9** [MelvorIdle/melvoridle.github.io#577]
**Describe the bug**
When launching the Steam version of the game, the zoom version will always be set to 100%, regardless of setting last time the game was run.

**To Reproduce**
1. Launch the Steam version of the game.
2. Set the zoom level to 70%
3. Close the game
4. Restart the Steam version of the game
5. Zoom Level will have returned to 100%

**Expected behavior**
Zoom level should remain across restarts of the game.

**Screenshots**
N/A

**Browser**
N/A - steam version

**Console output**
N/A - no console on steam version

**Are you using any scripts?**
No scripts used.

**Comment by SirNubius** [comment]
Was just about to write this bug report until I noticed you had already written it. Have a good day.

**Comment by Delekates** [comment]
same as SirNubius. Please fix :)

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
