### ISSUE TITLE
Farming pet increasing harvest quantity more than expected (V0.18.1)

### ISSUE THREAD

**Issue by Auron956** [MelvorIdle/melvoridle.github.io#578]
**Describe the bug**
Currently, the Farming pet is granting more than the +5 harvest quantity due to the order of operations. The +5 quantity is added prior to the quantity being multiplied by 7 for trees and 3 for allotments/herbs, so effectively the pet is increasing the harvested quantity by 35 for trees and 15 for allotments/herbs.

**To Reproduce**
1. Harvest a Farming plot while the Farming pet is unlocked
2. Receive more items from the harvest than expected

**Expected behavior**
The Farming pet should grant a flat +5 increase to the harvest quantity in all circumstances.

**Screenshots**
N/A

**Browser**
Issue independent of browser, but: Firefox 84.0.1 (64-bit)

**Console output**
N/A

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Fixed in next update
