### ISSUE TITLE
Thieving offline gains bug

### ISSUE THREAD

**Issue by Malchron** [MelvorIdle/melvoridle.github.io#580]
**Describe the bug**
(relogging did fix this but this is what happened)
So I logged in, recieved the snek pet and nothing else, odd as I should have got my Knight rewards and thieving exp. I refreshed the page and then recieved my rewards.

**To Reproduce**
1. be 98 thieving and pickpocket knights when u go offline
2. get lucky and get pet drop
3. login and wonder where your gains are
4. refresh page to log back in to get your gains you should have got before.

**Expected behavior**
I'd get my pet and exp/drops in 1 login.

**Screenshots**
Unfortunately didn't screenshot.

**Browser**
Version 87.0.4280.88 (Official Build) (64-bit)
Google Chrome

**Console output**
I closed melvor a few times since then so not sure this would help. (I use adblocker as I've been patreon in past but don't want to keep spending monthly)

www.googletagmanager.com/gtag/js?id=UA-129674422-1:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cdn.melvor.net/core/v018/assets/media/shop/assets/media/shop/perpetual_haste.svg:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
save.js?621:9 Loading Save Game...
save.js?621:25 Save Game Loaded...
smithing2.js?621:9 Loading Smithing...
mastery.js?621:2 Loading Masteries...
main.js?621:6 Game Loaded
main.js?621:215 Array(29)0: 721: 662: 813: 644: 735: 656: 717: 828: 1349: 6310: 7411: 9012: 13513: 9814: 13715: 8816: 8017: 7918: 13619: 8720: 9621: 8922: 9723: 9524: 10525: 10426: 89027: 48228: 630length: 29__proto__: Array(0)
cloud.js?621:94 Connected to PlayFab successfully
cloud.js?621:12 Synchronising with Cloud
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/13c28911820333eb6a51103a0e2096477a38941cc79afbf16b59f3d5a5f63086.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
None, I used semi in past versions though.

**Comment by MelvorIdle** [comment]
Should be fixed next update
