### ISSUE TITLE
Slayer Update Not Working Properly

### ISSUE THREAD

**Issue by Ximon581** [MelvorIdle/melvoridle.github.io#581]
**Describe the bug**
Receiving easy tasks after finishing other difficulties of slayer tasks, and the New Task button not displaying difficulty options, but automatically just giving you an easy task. Works properly in incognito currently, but uninstalling SEMI and closing and reopening the main Chrome window still gives the same problems.

**To Reproduce**
1. Click New Task to start a Slayer task
2. Pick any difficulty of task but Easy
3. Finish task
4. Watch as it gives you an easy task afterward
5. Try to click New Task to get another non-Easy task
6. Instead receive a different Easy task
7. Refresh to be able to select a different difficulty every time

**Expected behavior**
I expected that when finishing a normal task, I would receive a new normal task. I also expected New Task to give me the option to select which difficulty of task I receive.

**Screenshots**
The following screenshots are in order of each change that happens on screen, without anything happening inbetween.
![2020-12-26](https://user-images.githubusercontent.com/76610586/103147863-0a7a0e80-4727-11eb-89b1-191f4ed957e4.png)
![2020-12-26 (1)](https://user-images.githubusercontent.com/76610586/103147865-0fd75900-4727-11eb-9181-4b58896e1e14.png)
![2020-12-26 (2)](https://user-images.githubusercontent.com/76610586/103147866-106fef80-4727-11eb-9289-f844ed3ca4d7.png)
![2020-12-26 (3)](https://user-images.githubusercontent.com/76610586/103147867-11088600-4727-11eb-9215-412718ac6668.png)

**Browser**
Google Chrome v 87.0.4280.88 (Official Build) (64-bit)

**Console output**
![2020-12-26 (4)](https://user-images.githubusercontent.com/76610586/103147888-54fb8b00-4727-11eb-9117-f4064b5a3974.png)

**Are you using any scripts?**
I was using SEMI's autoslayer and autoslayerequip before it updated and those are no longer options. Was using autofarm as well, but uninstalling SEMI doesn't help.

**Comment by OilyHands** [comment]
I'm also having exactly this issue, with hard tasks. I've attached my save too. Scripts I use: SEMI, an action queue & slayer task notifiction one.

[melvoridlesave_Coco.txt](https://github.com/MelvorIdle/melvoridle.github.io/files/5761001/melvoridlesave_Coco.txt)

**Comment by MelvorIdle** [comment]
This is confirmed to be an issue with scripts being used.
