### ISSUE TITLE
Clue Chasers Insignia lowers the Rhaelyx pieces chance

### ISSUE THREAD

**Issue by Alci8** [MelvorIdle/melvoridle.github.io#582]
**Describe the bug**
in function rollForRhaelyx() the CCI equipped actually 

1) lowers the drop chance for circlet and jewel 
2) doesn't affect mystery stone at all

**Expected behavior**
CCI should either help with all chances, for circlet, jewel and mystery stone
or not touch any of those at all, as those are not skill specific drops

Also would be nice if it affected SignetB **if** it affects SignetA

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
