### ISSUE TITLE
minor: Ancient Wizard Set, and Water Acolyte Wizard Hat bonus does not match description

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#584]
**Describe the bug**
In items.js there are some misspelled property names:
Ancient Wizard Hat, Robes, Bottoms, and Boots have `increasedEarthFireSpellDmg`, should be: `increasedMinEarthSpellDmg`
Water Acolyte Wizard Hat has `increasedWaterAirSpellDmg`, should be: `increasedMinWaterSpellDmg`
**To Reproduce**
1. Equip one of the aforementioned items
2. Inspect `increasedMinSpellDmg` in console and note that the items do not provide the bonus in their description

**Expected behavior**
The items should provide the min spell damage increases as per their descriptions.

**Browser**
Browser Agnostic Bug

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
