### ISSUE TITLE
Broken image

### ISSUE THREAD

**Issue by Katorone** [MelvorIdle/melvoridle.github.io#585]
**Describe the bug**
A broken image on the Attack milestone (Wield Godwords)

**To Reproduce**
1. Go to 'milestones'
2. Click on 'attack'
3. Scroll down to 'N/A'

**Expected behavior**
Not a broken image

**Screenshots**
![image](https://user-images.githubusercontent.com/918422/103159554-36e76680-47cb-11eb-9ce5-5246f9b04185.png)

Inspecting the broken image gives:
`<Error>
<Code>AccessDenied</Code>
<BucketName>melvorcdn</BucketName>
<RequestId>tx000000000000006f648da-005fe17612-2e63dbc-fra1b</RequestId>
<HostId>2e63dbc-fra1b-fra1-zg02</HostId>
</Error>`

**Browser**
Firefox 84.0 (64-bit)

**Console output**
N/A

**Are you using any scripts?**
SEMI

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
