### ISSUE TITLE
low: Some items have duplicate properties

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#586]
**Describe the bug**
In items.js the following items have duplicate property names. This does not currently cause any issues, but may result in future bugs if the values of these properties need to be changed.
Item | Duplicate Property | Notes
---- | ------------------- | -----
Bronze Arrows | `fletchingXP`|
Iron Arrows | `fletchingXP`|
Slayer Helmet (Basic) | `canUpgrade`| Duplicates Conflict: Should be `true`
Slayer Platebody (Basic) | `canUpgrade`| Duplicates Conflict: Should be `true`
Slayer Helmet (Strong) | `canUpgrade`| Duplicates Conflict: Should be `true`
Slayer Platebody (Strong) | `canUpgrade`| Duplicates Conflict: Should be `true`
Slayer Helmet (Elite) | `canUpgrade`| Duplicates Conflict: Should be `true`
Slayer Platebody (Elite) | `canUpgrade`| Duplicates Conflict: Should be `true`
(U) Ancient D-hide Shield| `rangedStrengthBonus`|

**Browser**
Browser Agnostic Bug

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
