### ISSUE TITLE
low: Invalid Javascript syntax is declaring unwanted globally scoped variables

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#587]
**Describe the bug**
`let a = (b = c = ... = z = literalValue);` is invalid javascript syntax to declare multiple block scoped variables to `literalValue`.
This is causing all of the variables, `b, c, ... z` to become globally scoped variables.

**Example**
In combat.js the function `selectNewSlayerTask` uses this invalid syntax as follows:
`let minLevel = (maxLevel = taskCost = 0);`
As a result `maxLevel` and `taskCost` are now in global scope, as shown by the console here:
![image](https://user-images.githubusercontent.com/58208131/103159678-85741100-4789-11eb-957d-04bf87aa6c7a.png)

**Expected behavior**
Variables `b, c, ... z` should be block scoped.

**Fix**
Unfortunately there isn't a super concise way to do this in javascript (without using ugly hacks with arrays and de-structuring assignment). The most concise syntax that I've found is:
`let a = literalValue, b = literalValue, c = literalValue, ... z = literalValue;`

**Browser**
Browser Agnostic Bug

**Current occurrences**
File | Function | Invalid Code | Fixed Code | Notes
-- | -- | -- | -- | --
bank.js | `createBankItem` |`  let potionCharges = (description = spec = bankClassPopoverBorder = bankClassImg = bankClassPopover = bankClassQty = bankMinWidth = bankQtyPositioning = hp = bankLocked = bankContainer ='');`|`let potionCharges = '', description = '', spec = '', bankClassPopoverBorder = '', bankClassImg = '', bankClassPopover = '', bankClassQty = '', bankMinWidth = '', bankQtyPositioning = '', hp = '', bankLocked = '', bankContainer = '';`
combat.js|`selectNewSlayerTask`|`let minLevel = (maxLevel = taskCost = 0);`|`let minLevel = 0, maxLevel = 0, taskCost = 0;`
combat.js|`updateCombatInfoIcons`|`let dmgReducAdjustment = (dmgAdjustment = 'No Change');`|`let dmgReducAdjustment = 'No Change', dmgAdjustment = 'No Change';`
combat.js|`attackPlayer`|`let stunDamageMultiplier = (lifestealMultiplier = sleepDamageMultiplier = 1);`|`let stunDamageMultiplier = 1, lifestealMultiplier = 1, sleepDamageMultiplier = 1;`
firemaking.js|`burnLog`|`let firemakingInterval = (baseFiremakingInterval = logsData[selectedLog].interval);`|`let firemakingInterval = logsData[selectedLog].interval;` | `baseFiremakingInterval` is never used, so it can be removed
stats.js|`openItemLog`|`  let timesFound = (ignoreCompletion = timesSold = gpFromSale = deathCount = damageTaken = damageDealt = missedAttacks = timesEaten = healedFor = totalAttacks = amountUsedInCombat = timeWaited = timesDied = timesGrown = harvestAmount = enemiesKilled = timesOpened = '');`|`let timesFound = '', ignoreCompletion = '', timesSold = '', gpFromSale = '', deathCount = '', damageTaken = '', damageDealt = '', missedAttacks = '', timesEaten = '', healedFor = '', totalAttacks = '', amountUsedInCombat = '', timeWaited = '', timesDied = '', timesGrown = '', harvestAmount = '', enemiesKilled = '', timesOpened = '';`
stats.js|`updateBankItemStats`|`let timesFound = (timesSold = gpFromSale = deathCount = damageTaken = damageDealt = missedAttacks = timesEaten = healedFor = totalAttacks = amountUsedInCombat = timeWaited = timesDied = timesGrown = harvestAmount = enemiesKilled = timesOpened = '');`|`let timesFound = '', timesSold = '', gpFromSale = '', deathCount = '', damageTaken = '', damageDealt = '', missedAttacks = '', timesEaten = '', healedFor = '', totalAttacks = '', amountUsedInCombat = '', timeWaited = '', timesDied = '', timesGrown = '', harvestAmount = '', enemiesKilled = '', timesOpened = '';`
stats.js|`openMonsterLog`|`let damageDealtToPlayer = (damageTakenFromPlayer = killedByPlayer = killedPlayer = hitsToPlayer = hitsFromPlayer = enemyMissed = playerMissed = seen = ranAway = '');`|`let damageDealtToPlayer = '', damageTakenFromPlayer = '', killedByPlayer = '', killedPlayer = '', hitsToPlayer = '', hitsFromPlayer = '', enemyMissed = '', playerMissed = '', seen = '', ranAway = '';`

**Comment by MelvorIdle** [comment]
Thanks, fixed in next update
