### ISSUE TITLE
minor: New bank items are not sorted correctly when using Stack GP Value options

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#588]
**Describe the bug**
When an item is added to the `bank` array and does not already exist in it, the `stackValue` property is not set. As a result, sorting the bank using the Stack GP Value option immediately after adding the  new item causes it to not be sorted properly.

**To Reproduce**
1. Set bank sort option to Stack GP Value
2. Add an item to the bank that is not already in it
3. Click the Sort button
4. Note how the newly added item is not sorted correctly

**Expected behavior**
`stackValue` should be defined on newly added bank items, so the sort function works correctly.

**Fix**
In the file bank.js, the function `addItemToBank` needs to be modified so that: 
```javascript
bank.push({
  id: itemID,
  qty: quantity,
  tab: tab,
  sellsFor: items[itemID].sellsFor,
});
```
is changed to:
```javascript
bank.push({
  id: itemID,
  qty: quantity,
  tab: tab,
  sellsFor: items[itemID].sellsFor,
  stackValue: quantity * items[itemID].sellsFor,
});
```
**Browser**
Browser Agnostic Bug

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
