### ISSUE TITLE
Mastery bar under logs for firemaking momentarily displays incorrect log mastery

### ISSUE THREAD

**Issue by Starnub** [MelvorIdle/melvoridle.github.io#592]
**Describe the bug**
When switching log type, the value (and only the value) on the mastery progress bar switches back to the mastery value of the previously selected log type when you burn a log, then switches back to the correct one after burning another log.

**To Reproduce**
1. Switch log type. Mastery value is correct.
2. Burn a log. Mastery value is the mastery of the previously selected log.
3. Burn another log. Mastery value is correct.

**Expected behavior**
The mastery shouldn't change when you burn a log.

**Browser**
Firefox, latest version.

**Console output**
1992 firemaking.js:2:9
2994

**Are you using any scripts?**
No.

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
