### ISSUE TITLE
Smithing progressing much faster offline than online

### ISSUE THREAD

**Issue by levgre** [MelvorIdle/melvoridle.github.io#594]
**Describe the bug**
In approximately 3 hours online I crafted about 2.2k steel gloves. I progressed from mastery 82 to 87
In approximately 2 hours offline i crafted about 6.1k steel scimitars. I progressed from mastery 82 to 92

**Browser**
 Chrome 87.0.4280.88

**Console output**
ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cdn.melvor.net/core/v018/assets/media/shop/assets/media/shop/perpetual_haste.svg:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
save.js?622:9 Loading Save Game...
save.js?622:25 Save Game Loaded...
smithing2.js?622:9 Loading Smithing...
mastery.js?622:2 Loading Masteries...
main.js?622:6 Game Loaded
VM117:3 Melvor Completion Log Helper Loaded
main.js?622:152 Total actions: 4698
main.js?622:152 Actual actions (Prior to preservation): 4698
main.js?622:159 Actual actions (After to preservation): 4698
smithing2.js?622:1 1600
main.js?622:215 Array(2)
smithing2.js?622:1 1600
cloud.js?622:94 Connected to PlayFab successfully
3smithing2.js?622:1 1600
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/13c28911820333eb6a51103a0e2096477a38941cc79afbf16b59f3d5a5f63086.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
no

**Comment by MelvorIdle** [comment]
I am unable to reproduce this bug as of today. I believe this to be fixed. Please recreate a new report if issue persists.
