### ISSUE TITLE
Idle Fish Cooking

### ISSUE THREAD

**Issue by serenity776** [MelvorIdle/melvoridle.github.io#596]
I play Melvor on my phone, so with the mobile app, the bug isn’t an error code just a minor inconvenience, when I go to cook food then proceed to go idle/off the app, then come back later it says 0 “whatever food” has been cooked, it’ll say I have been gone for 0 minutes this preventing me from getting event items like presents in the current event and all my food from being cooked.
![8F55FC33-68FB-4D47-BA37-15CD9ED22258](https://user-images.githubusercontent.com/76703481/103236634-f8f15c00-490a-11eb-93c5-17b33c688876.png)

I hope this helps with the progression of the game and hopefully gets fixed sometime, the game itself is enjoyable so good luck Devs.

-Friendly User

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
