### ISSUE TITLE
Runic Ruins -30% magic evasion bug

### ISSUE THREAD

**Issue by ScoobyDooner** [MelvorIdle/melvoridle.github.io#597]
**Describe the bug**
Fighting elementalists in Runic Ruins using magic (ancient magicks) and it still seems to apply -30% magic evasion even though I'm fighting them with magic

**To Reproduce**

**Expected behavior**
Expected magic evasion to stay at its usual value but I still get the -30% debuff

**Screenshots**
[https://imgur.com/a/0yqIAEu](url)

There are 2 screenshots there. You can see that when fighting, my magic evasion is ~11k but when the mob is re-spawning, you can see the proper value of ~16k.

**Browser**
Google Chrome v.  87.0.4280.88

**Console output**
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cdn.melvor.net/core/v018/assets/media/shop/assets/media/shop/perpetual_haste.svg:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
save.js?622:9 Loading Save Game...
save.js?622:25 Save Game Loaded...
smithing2.js?622:9 Loading Smithing...
mastery.js?622:2 Loading Masteries...
main.js?622:6 Game Loaded
cloud.js?622:94 Connected to PlayFab successfully
cloud.js?622:12 Synchronising with Cloud
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/13c28911820333eb6a51103a0e2096477a38941cc79afbf16b59f3d5a5f63086.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

(Not sure if thats the right thing needed from console, sorry!)

**Are you using any scripts?**
No scripts, playing vanilla

**Comment by coolrox95** [comment]
This error is a result of updatePlayerStats in combat.js having an error:
```js
  if (
    selectedCombatArea === 'Runic Ruins' &&
    !equippedItems[CONSTANTS.equipmentSlot.Weapon].isMagic // This line needs to index into items
//Replace with this: !items[equippedItems[CONSTANTS.equipmentSlot.Weapon]].isMagic
  )
    magicEvasionDebuff = calculateAreaEffectValue(
      slayerAreas[CONSTANTS.slayerArea.Runic_Ruins].areaEffectValue
    );
```

**Comment by MelvorIdle** [comment]
Fixed in coming update
