### ISSUE TITLE
Combat looting duplication bug

### ISSUE THREAD

**Issue by ReZeroed** [MelvorIdle/melvoridle.github.io#598]
**Describe the bug**
When looting items as a monster dies, it is possible to duplicate the item you click on.

**To Reproduce**
1. Have any item drop in the loot to collect
2. Kill any monster with a 100% drop rate
3. As the next monster is about to die/dies, click on the previous item drop.
4. If timed right the 1st item will be sent to your bank and also remain in the loot to collect, while the item that was to the left of the clicked item will have been deleted.

**Expected behavior**
The looted item would be sent to your inventory and the item to the left of the collected item would be unaffected.

**Screenshots**
https://imgur.com/a/u4SnnH6

**Browser**
Latest steam version

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
No

**Comment by ReZeroed** [comment]
Here is a better example. 



https://user-images.githubusercontent.com/75293942/103254400-04678480-49ea-11eb-88ec-2aa12a956268.mp4

**Comment by MelvorIdle** [comment]
Related #656
