### ISSUE TITLE
Dungeons icons broken while fighting the second+ monster

### ISSUE THREAD

**Issue by Zidane3838** [MelvorIdle/melvoridle.github.io#599]
**Describe the bug**
EVERY Dungeon passed the first monster the dungeon icon breaks and shows question.svg instead of the dungeon icon

**To Reproduce**
1. Go to 'combat' or 'attack' or 'strength' or 'defence' or 'hitpoints' or 'ranged' or 'magic' or 'prayer' or 'slayer' (lol sorry)
2. Click on 'Browse Dungeons'
3. Click on any dungeon
4. Fight to any second monster
5. See error
6. profit?

**Expected behavior**
DUNGEON ICON show up

**Screenshots**
https://i.imgur.com/oiqq50J.jpg

**Browser**
steam

**Console output**
no u

**Are you using any scripts?**
ew no them stinky yuck

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
