### ISSUE TITLE
Login session should be persistent not just last the browser session

### ISSUE THREAD

**Issue by RedSparr0w** [MelvorIdle/melvoridle.github.io#6]
Currently you are logged out from the "cloud" after you close the browser,
Would be better if this was persistent and kept you logged in.

Maybe even if it was optional with a `remember me` checkbox.

- [ ] Remember me

**Comment by mrDLSable** [comment]
I think this is redundant with the 0.9 login system @RedSparr0w

**Comment by RedSparr0w** [comment]
It's kind of more relevant now, as currently when your browser session ends, you will have to re-login.
Rather than if the cookie persisted you wouldn't be logged out until the cookie expires.

**Comment by mrDLSable** [comment]
Quick question, do browser sessions persist between closing the browser and reopening it? Because if so, then the logged in state already persists...

**Comment by mrDLSable** [comment]
I just restarted my PC and was still logged in...

**Comment by RedSparr0w** [comment]
Most browsers delete the cookie, [chrome won't always delete the cookie though.](https://stackoverflow.com/questions/10617954/chrome-doesnt-delete-session-cookies)

**Comment by mrDLSable** [comment]
Tested in edge. I see now what you mean and agree with you. Thanks for explaining it :)
