### ISSUE TITLE
Auroras don't seem to get the skull cape effect of no rune usage.

### ISSUE THREAD

**Issue by HellFiraga** [MelvorIdle/melvoridle.github.io#601]
**Describe the bug**
When using Surge 1, the Skull cape doesnt seem to help reduce the cost of the spell. Tested with about 400 casts and none seem to have the free cast granted by the Skull cape.

**To Reproduce**
Equip a Skull Cape.
Use an Aurora + Standard Spell.
Fight a monster.

**Expected behavior**
The aurora should have a 20% chance to negate the rune cost. Skull cape works for standard, curses and ancient spells. Confirmed by Prat that Auroras should also be affected by Skull cape.

**Screenshots**
GIF of a short snippet of my testing.
https://i.imgur.com/CMrQ9H3.gif

**Browser**
Steam Version

**Console output**
N/A unless theres something specific here.
Feel free to contact me on Discord or here for more info.
HellFire#6666

**Are you using any scripts?**
No sir

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
