### ISSUE TITLE
Christmas Presents not generating

### ISSUE THREAD

**Issue by ochabox** [MelvorIdle/melvoridle.github.io#603]
**Describe the bug**
The Christmas presents don't generate. And the icon isn't avaible.

**Expected behavior**
Expect a present to generate evert 10 minutes of real-time.

**Browser**
Brave 
Version 1.18.77 Chromium: 87.0.4280.101 (Official Build) (64-bit)

**Console output**
www.googletagmanager.com/gtag/js?id=UA-129674422-1:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cdn.melvor.net/core/v018/assets/media/shop/assets/media/shop/perpetual_haste.svg:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
save.js?622:9 Loading Save Game...
save.js?622:25 Save Game Loaded...
smithing2.js?622:9 Loading Smithing...
mastery.js?622:2 Loading Masteries...
main.js?622:6 Game Loaded
cloud.js?622:94 Connected to PlayFab successfully
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/13c28911820333eb6a51103a0e2096477a38941cc79afbf16b59f3d5a5f63086.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
var presentCount = xmasPresents;
for (var i = 0; i < presentCount; i++) {
  var item = getItemForScratch();
  finishScratch(item);
}

**Comment by duplaja** [comment]
This event ended on Dec 30th, according to the in-game text.
