### ISSUE TITLE
Earth Adept Wizard Hat has incorrect magic level required on crafting page

### ISSUE THREAD

**Issue by fradigit** [MelvorIdle/melvoridle.github.io#604]
**Describe the bug**
The Earth Adept Wizard Hat shows that level 39 magic is required to equip on the crafting screen, when it is intended to be level 43. Unknown if actual item has incorrect requirement or not.

**To Reproduce**
1. Go to 'Runecrafting'
2. Click on 'Earth Magic Gear'
3. Click on 'Earth Adept Wizard Hat'
4. Click on 'View item stats'
5. See error (Magic Level Required: 39)

**Expected behavior**
Expect to see requirement of 43 in line with other Earth Adept gear

**Screenshots**
![image](https://user-images.githubusercontent.com/76832865/103434792-16e4e800-4bbb-11eb-8f4c-2b97a86cb5e5.png)

**Browser**
Steam 0.18.1

**Console output**
I don't believe this works on Steam - F12 took a screenshot

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
