### ISSUE TITLE
Background combat speed issue.

### ISSUE THREAD

**Issue by yugo0075** [MelvorIdle/melvoridle.github.io#605]
I kill monsters in a set amount of time thanks to the ancient magicks that never fails. However, that time changes drasticly depending on whether Melvor is open in front of me or running in the background.
As an example, I take down one greater chaotic dragon in 36 seconds (respawning time included), but after 11 minutes running in the background I only killed 6 of them (according to the number of kills in the completion log).
And as far as I can tell, the same "error" occurs on any given monster.

I run Melvor on Google Chrome Version 87.0.4280.88 (Build officiel) (64 bits) and I don't use any script.

As for the "console output" unfortunately I know basically nothing of computer science so I'm not even sure if what I'm about to paste here is what you're asking for. But feel free to DM "yugo0075" on discord if you need any other info. And thank you for your work as always.

cdn.melvor.net/core/v018/assets/media/shop/assets/media/shop/perpetual_haste.svg:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
prebid.min.js:3 fun-hooks: referenced 'registerAdserver' but it was never created
(anonymous) @ prebid.min.js:3
gdpr.bundle.js:16 WARN - (CMP) Invalid CMP config values not applied: restrictForEU, supressUI
l.reduce.e.<computed> @ gdpr.bundle.js:16
gdpr.bundle.js:16 DEBUG - (CMP) Read local locale:  null
gdpr.bundle.js:16 DEBUG - (CMP) Using configuration:  {"env":"production","cmpId":3,"configVersion":26,"appId":"7f035220-1751-4684-bb7f-a1c0d45657df","logo":"https://gdpr.privacymanager.io/1/fingerprint-logo.png","backdrop":"rgba(0,0,0,0.5)","storeConsentGlobally":false,"thirdPartyCookieSync":false,"useSecondLevelDomain":true,"useCookies":true,"preferenceLink":{"enabled":false,"apiKey":null,"identifyingField":null},"logging":true,"topics":{"en":[{"displayPurposes":false,"showOnNotice":false,"expanded":false,"icon":"how-is-my-data-used","tip":null,"text":"<p>This site and its partners store and access personal data based on unique identifiers such as cookies, and the EU’s General Data Protection Regulation calls for freely-given consent prior to processing any personal data. As such, to provide the best experience for you on our properties, we ask for your consent to allow us and our partners to process your data.</p><p>By consenting to data processing on this site, you agree to share your personal data with us and our partners on this property. If you do not consent to or withdraw consent from data processing from all vendors, this may adversely affect site functions and your experience.</p><p>To see the list of vendors processing your data, click on the “Our Partners” link below.</p>","title":"Why Do You Need My Consent?"},{"displayPurposes":true,"showOnNotice":false,"expanded":false,"icon":"consent","tip":null,"text":"<p>We process your data for a variety of purposes, these purposes and the features they enable can be reviewed below. By consenting to all data processing on this property, you agree to have your personal data processed by us and our partners for the purposes and features listed to enable us to improve our services and facilitate a better experience for you. Not consenting or withdrawing consent, may adversely affect certain features and functions of our sites or apps.</p>","title":"Why Do You Use My Data?"},{"displayPurposes":false,"showOnNotice":false,"expanded":false,"icon":"cookie","tip":null,"text":"<ul><li>Withdrawing Consent</li></ul><p>You may withdraw your consent and update your preferences at any time. However, please be aware that not all vendors request consent and – while you have the right to object processing on these grounds – some may process data on the basis of legitimate interest. Click “Our Partners” below to see the list of vendors processing data based on legitimate interest.</p><ul><li> How to resurface the Privacy Manager?</li></ul><p>You can review and update your privacy settings at any time by clicking the Privacy Settings Icon in the bottom of the screen.</p>","title":"Withdrawing My Consent"}],"de":[{"displayPurposes":false,"showOnNotice":false,"expanded":false,"icon":"how-is-my-data-used","tip":null,"text":"<p>Diese Webseite und ihre Partner speichern personenbezogene Daten auf der Grundlage von eindeutigen Identifizierungsmerkmalen wie Cookies und greifen auf diese Daten zu. Die Datenschutz-Grundverordnung (DSGVO) der Europäischen Union verlangt nach einer freiwillig erteilten Einwilligung, bevor personenbezogene Daten verarbeitet werden dürfen. Wir bitten daher um Ihre Einwilligung in die Verarbeitung Ihrer personenbezogenen Daten durch uns und unsere Partner. So können wir Ihnen das bestmögliche Nutzungserlebnis auf unseren Plattformen garantieren. \n\nDurch die Annahme oder Ablehnung der Einwilligung geben Sie Ihre ausdrückliche Zustimmung oder Ablehnung zur Datenverarbeitung auf dieser Webseite. Sie stimmen zu, Ihre personenbezogenen Daten mit uns und unseren Partnern auf dieser Webseite zu teilen. Wenn Sie der Datenverarbeitung durch uns und unsere Anbieter nicht zustimmen oder Ihre Zustimmung widerrufen, kann dies die Funktionen der Webseite und Ihr Nutzungserlebnis beeinträchtigen.\n\nUm die Liste der Drittanbieter einzusehen, die Ihre Daten verarbeiten, klicken Sie auf den unten stehenden Link „Unsere Partner\". \n</p>","title":"Warum ist meine Einwilligung erforderlich?"},{"displayPurposes":true,"showOnNotice":false,"expanded":false,"icon":"consent","tip":null,"text":"<p>Indem Sie die aufgeführten Zwecke und Funktionen überprüfen und Ihre Einwilligung diesbezüglich erteilen, stimmen Sie der Verarbeitung Ihrer personenbezogenen Daten durch uns und unsere Partner zu. Dies ermöglicht uns, unsere Dienstleistungen zu verbessern und Ihnen ein optimiertes Nutzungserlebnis zu ermöglichen. Wenn Sie nicht zustimmen oder Ihre Zustimmung widerrufen, kann sich dies nachteilig auf bestimmte Funktionsweisen und Bereiche unserer digitalen Plattformen auswirken.\n\nWir verarbeiten Ihre Daten zu verschiedenen Zwecken. Diese Zwecke sowie die Funktionen, die diese Zwecke unterstützen, sind im Folgenden aufgeführt \n</p>","title":"Wofür werden Ihre Daten verwendet?"},{"displayPurposes":false,"showOnNotice":false,"expanded":false,"icon":"cookie","tip":null,"text":"<ul><li>Widerruf Ihrer Einwilligung</li></ul><p>Sie können jederzeit Ihre Einwilligung widerrufen und Ihre Präferenzen anpassen, indem Sie die Datenschutzeinstellu
gdpr.bundle.js:16 DEBUG - (CMP) Read local consent data:  CO_VSzJO_VS6cADABBFRBHCsAP_AAH_AAAAAGSIF5C5URAFD4GJsIJIUIAEXwFQAAGAgBgQBA4AACBCAEAwEkAAAEAAAIAAAAAAAIAIAAAAACAkAAAAAQIAAAQAAAAQAIAAAIAIACAAAEAAAAAgAAoAQEAAAAAAAAAAAgAAAAAYAQMkAJAFSoAACEgMCQQAAoQAIAgCAAAEAABAACBAAAECAAABgAIAAAAAAAAAAAAAAAQAQAAAAAABIAAAAAgQAAAgAAAAgAQAAAAAQAAAAAAAAAABAAAQAgAAAAAAAAAAABAAAAAAgAgAA.YAAAAAAAAAA
gdpr.bundle.js:16 DEBUG - (CMP) Read local consent data:  CO_VSzJO_VS6cADABBFRBHCgAPwAAAAAAAABmbwIgAEgAMAA6AGEAUIAqoBpAGnANoA24BwAHCAOsAeIA9gCKAEWAI0AR0ApQBdADAicXE9kKMgUaApCRUOCpzFeeLPwXsoxABiZjFiGXSMzcAAAAAA.YAAAAAAAAAA
gdpr.bundle.js:16 DEBUG - (CMP) Read local AC string:  1~7.162.440.448.505.780.867.1215.1516.2133.2544.2595.2642.3033.3111
gdpr.bundle.js:16 DEBUG - (CMP) Comparing consent data
gdpr.bundle.js:16 DEBUG - (CMP) Sync with PL disabled
gdpr.bundle.js:16 DEBUG - (CMP) Read local last interaction timestamp:  1609493263.632
gdpr.bundle.js:16 DEBUG - (CMP) Read local config version:  26
gdpr.bundle.js:16 DEBUG - (CMP) Successfully loaded CMP version: 1 in 7ms, CMP id: 3
gdpr.bundle.js:16 INFO - (CMP) Notify event: isLoaded
gdpr.bundle.js:16 DEBUG - (CMP) PL Consent data out of sync
gdpr.bundle.js:16 DEBUG - (CMP) Sync with PL disabled
gdpr.bundle.js:16 DEBUG - (CMP) Consent data synced
gdpr.bundle.js:16 DEBUG - (CMP) Vendor List Set
gdpr.bundle.js:16 INFO - (CMP) Notify event: vendorListChanged
gdpr.bundle.js:16 DEBUG - (CMP) Read local last interaction timestamp:  1609493263.632
gdpr.bundle.js:16 DEBUG - (CMP) Read local config version:  26
gdpr.bundle.js:16 DEBUG - (CMP) Consent Status:  FULL_CONSENT
gdpr.bundle.js:16 INFO - (CMP) Process 1 queued commands
gdpr.bundle.js:16 INFO - (CMP) Proccess command: addEventListener, parameter: undefined, version: 2
gdpr.bundle.js:16 INFO - (CMP) Notify event: cmpReady
gdpr.bundle.js:16 DEBUG - (CMP) CMP Ready in: 63ms
gdpr.bundle.js:16 DEBUG - (CMP) Notice should not be shown
gdpr.bundle.js:16 DEBUG - (CMP) Read local daily active user:  true
save.js?622:9 Loading Save Game...
save.js?622:25 Save Game Loaded...
smithing2.js?622:9 Loading Smithing...
mastery.js?622:2 Loading Masteries...
main.js?622:6 Game Loaded
gdpr.bundle.js:16 INFO - (CMP) Proccess command: addEventListener, parameter: undefined, version: 2
gdpr.bundle.js:16 INFO - (CMP) Proccess command: removeEventListener, parameter: 2, version: 2
gdpr.bundle.js:16 INFO - (CMP) Proccess command: getTCData, parameter: 91, version: 2
cloud.js?622:94 Connected to PlayFab successfully
gdpr.bundle.js:16 INFO - (CMP) Proccess command: addEventListener, parameter: undefined, version: 2
gdpr.bundle.js:16 INFO - (CMP) Proccess command: removeEventListener, parameter: 3, version: 2
2gdpr.bundle.js:16 INFO - (CMP) Proccess command: addEventListener, parameter: undefined, version: 2
gdpr.bundle.js:16 INFO - (CMP) Proccess command: getTCData, parameter: 126, version: 2
gdpr.bundle.js:16 INFO - (CMP) Proccess command: addEventListener, parameter: undefined, version: 2
gdpr.bundle.js:16 INFO - (CMP) Proccess command: removeEventListener, parameter: 6, version: 2
cloud.js?622:12 Synchronising with Cloud
gdpr.bundle.js:16 INFO - (CMP) Proccess command: addEventListener, parameter: undefined, version: 2
gdpr.bundle.js:16 INFO - (CMP) Proccess command: removeEventListener, parameter: 7, version: 2
gdpr.bundle.js:16 INFO - (CMP) Proccess command: addEventListener, parameter: undefined, version: 2
gdpr.bundle.js:16 INFO - (CMP) Proccess command: removeEventListener, parameter: 8, version: 2
gdpr.bundle.js:16 INFO - (CMP) Proccess command: addEventListener, parameter: undefined, version: 2
gdpr.bundle.js:16 INFO - (CMP) Proccess command: removeEventListener, parameter: 9, version: 2
gdpr.bundle.js:16 INFO - (CMP) Proccess command: addEventListener, parameter: undefined, version: 2
gdpr.bundle.js:16 INFO - (CMP) Proccess command: removeEventListener, parameter: 10, version: 2
gdpr.bundle.js:16 INFO - (CMP) Proccess command: addEventListener, parameter: undefined, version: 2
gdpr.bundle.js:16 INFO - (CMP) Proccess command: removeEventListener, parameter: 11, version: 2
gdpr.bundle.js:16 INFO - (CMP) Proccess command: addEventListener, parameter: undefined, version: 2
gdpr.bundle.js:16 INFO - (CMP) Proccess command: removeEventListener, parameter: 12, version: 2
gdpr.bundle.js:16 INFO - (CMP) Proccess command: getTCData, parameter: undefined, version: 2
data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=:1 Uncaught SyntaxError: Invalid or unexpected token
cloud.js?622:12 Synchronising with Cloud
gdpr.bundle.js:16 INFO - (CMP) Proccess command: addEventListener, parameter: undefined, version: 2
gdpr.bundle.js:16 INFO - (CMP) Proccess command: removeEventListener, parameter: 13, version: 2
gdpr.bundle.js:16 INFO - (CMP) Proccess command: getTCData, parameter: undefined, version: 2
data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=:1 Uncaught SyntaxError: Invalid or unexpected token
2cloud.js?622:12 Synchronising with Cloud
gdpr.bundle.js:16 INFO - (CMP) Proccess command: addEventListener, parameter: undefined, version: 2
gdpr.bundle.js:16 INFO - (CMP) Proccess command: removeEventListener, parameter: 14, version: 2
z.moatads.com/havasfrorangedcmdisplay758646212611/moatad.js:120 The deviceorientation events are blocked by feature policy. See https://github.com/WICG/feature-policy/blob/master/features.md#sensor-features
c.xc.ynds @ z.moatads.com/havasfrorangedcmdisplay758646212611/moatad.js:120
gdpr.bundle.js:16 INFO - (CMP) Proccess command: addEventListener, parameter: undefined, version: 2
gdpr.bundle.js:16 INFO - (CMP) Proccess command: removeEventListener, parameter: 15, version: 2
cloud.js?622:12 Synchronising with Cloud
4cloud.js?622:12 Synchronising with Cloud
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/13c28911820333eb6a51103a0e2096477a38941cc79afbf16b59f3d5a5f63086.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by MelvorIdle** [comment]
This is a browser limitation unfortunately that I cannot fix. You either need to keep Melvor in its own window without minimising or use the Steam Client which doesn't get throttled by the browser.
