### ISSUE TITLE
30% Slow Not Applied in Dark Waters

### ISSUE THREAD

**Issue by Erico9002** [MelvorIdle/melvoridle.github.io#606]
It seems that all the time in Dark Waters that the 30% Slow area effect is not happening? I used a stopwatch to time my attack rate with slayer crossbow at rapid and it was 2.8s as usual. I'm not wearing any slayer gear, just the air god dungeon gear
![image](https://user-images.githubusercontent.com/57814950/103451211-de124500-4c86-11eb-9fad-358e44fcf154.png)
![image](https://user-images.githubusercontent.com/57814950/103451215-ee2a2480-4c86-11eb-9115-dd59fbeeaae3.png)

**Comment by MelvorIdle** [comment]
Being hotfixed today :)
