### ISSUE TITLE
rollForPet function is causing Uncaught ReferenceError: xpToLevel is not defined

### ISSUE THREAD

**Issue by Slimmmo** [MelvorIdle/melvoridle.github.io#607]
**Describe the bug**
`rollForPet` function is causing `Uncaught ReferenceError: xpToLevel is not defined` because the `if(PETS[petID].skill>=0){` condition's closing bracket is too early. Only effects petID's 7, 22 and 23 (Larry, Peri and Otto)

**Browser**
Firefox 84.0.1

**Console output**
Uncaught ReferenceError: xpToLevel is not defined
    rollForPet https://melvoridle.com/assets/js/game/pets.js?622:4
    harvestSeed https://melvoridle.com/assets/js/game/farming.js?622:40
    setTimeout handler*harvestSeed https://melvoridle.com/assets/js/game/farming.js?622:40
    onclick https://melvoridle.com/?l=1:1
pets.js:4:14

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Thanks! Hotfixing today :)
