### ISSUE TITLE
Incorrect mastery level on Oak Tree

### ISSUE THREAD

**Issue by fradigit** [MelvorIdle/melvoridle.github.io#608]
**Describe the bug**
Oak tree was at level 1 mastery after idling woodcutting and then switching to fletching. By the time I noticed, I had already leveled firemaking to 25, purchased the Oak Cooking Fire in the shop, and had approximately 10,000 Oak Logs in my inventory. This is a hardcore save. I believe I purchased Multi-Tree before starting so Normal Tree and Oak Tree would have been active for the same amount of time (see screenshot)

**To Reproduce**
1. N/A

**Expected behavior**
I would expect Oak Tree mastery to be at whatever mastery is appropriate for having 10,000 Oak Logs

**Screenshots**
![image](https://user-images.githubusercontent.com/76832865/103487486-af958680-4dba-11eb-9261-be873cfa8465.png)
![image](https://user-images.githubusercontent.com/76832865/103487495-bde3a280-4dba-11eb-8aea-ec2a77894188.png)

**Browser**
Steam 0.18.1

**Console output**
F12 doesn't work on Steam. I have uploaded the save file.
[melvoridlesave_Chloe hardcore 2.txt](https://github.com/MelvorIdle/melvoridle.github.io/files/5762184/melvoridlesave_Chloe.hardcore.2.txt)

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
This is a known bug that is being hotfixed today L:)
