### ISSUE TITLE
Dying while Thieving in Hardcore - Save not deleted

### ISSUE THREAD

**Issue by mguillan** [MelvorIdle/melvoridle.github.io#610]
**Describe the bug**
If you die while Thieving in hardcore gameplay mode, your save will not be deleted.

Once you die, you will be presented with the standard death screen, the health bar then returns to 20 and you will be able to continue progressing, in the statistics window it will indicate one death via combat

**To Reproduce**
1. Create a hardcore Save
2. Pickpocket Man with no food till death.

**Expected behavior**
Upon death the save should be deleted and you will be returned to the character selection screen

**Screenshots**
![Death](https://user-images.githubusercontent.com/76988885/103612672-0e086380-4f79-11eb-8007-5c6a7dd8ad59.png)
![Statistics](https://user-images.githubusercontent.com/76988885/103612683-13fe4480-4f79-11eb-9587-367c43e2ee5b.png)

**Browser**
Chromium Edge Version 87.0.664.66 (Official build) (64-bit)

**Console output**
discord.js?622:1 Uncaught TypeError: Cannot read property 'name' of undefined
    at sendDiscordEvent (discord.js?622:1)
    at stopCombat (combat.js?622:146)
    at thieving.js?622:6
main.js?622:215 Array(0)
cloud.js?622:12 Synchronising with Cloud
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/13c28911820333eb6a51103a0e2096477a38941cc79afbf16b59f3d5a5f63086.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Fixed in upcoming update :)
