### ISSUE TITLE
minor: Fishing Mastery provides incorrect chance to double fish

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#611]
**Describe the bug**
The chance to double fish from fishing mastery is incorrectly implemented, it is giving
```javascript
  Math.ceil(fishingMastery * 0.4) // % chance to double fish
```
So instead of gradually increasing it steps up by 1% every 2-3 mastery level. 
This is because the random roll is floored in startFishing():
```javascript
let chanceToDouble = Math.floor(Math.random() * 100);
// Some other code here...
if (fishingMastery * 0.4 > chanceToDouble || fishingMastery >= 99) itemQty *= 2;
```
See #609 for details on why this results in higher doubling chance than expected.

**Expected behavior**
Fishing mastery should smoothly increase the chance to double fish by 0.4% per level.

**Fix**
Easy fix, just need to remove the floor from `chanceToDouble`. 
Or make RNG for rolling a percentage chance into a function, e.g.
```javascript
function rollPercentage(chance) {
    return chance > Math.random() * 100;
}
```
Which simplifies the above code to:
```javascript
if (rollPercentage(fishingMastery * 0.4) || fishingMastery >= 99) itemQty *= 2;
```
(and could replace all the other duplicate RNG code that has been copy pasted 90+ times)

**Browser**
Browser agnostic Bug

**Comment by MelvorIdle** [comment]
Hotfixing with today's update. Will create the function and swap all duplicate instances for the next major update
