### ISSUE TITLE
Statistics - Woodcutting "Seconds spent cutting" does not count up while offline. 

### ISSUE THREAD

**Issue by fuzzybear3232** [MelvorIdle/melvoridle.github.io#612]
**Describe the bug**
Just the title. In the statistics page for Woodcutting, the counter that tells you how many seconds you have spent training woodcutting doesn't seem to go up while you're offline. I have it at level 90, and it's only said I've been woodcutting for 45k seconds which is like half a day. It's been at least 4-5 to get it there. All the other skills seems to work out. 

**To Reproduce**
1. Go to statistics and write down your current "Seconds spent cutting"
2. Start cutting a tree and then go offline 
3. Return after a few minutes to see the counter not go up. 

**Expected behavior**
The counter to work offline as it does for all the other skills I've trained.

**Screenshots**
Doesn't really help here. 

**Browser**
I use Brave - v1.18.77

**Console output**
I don't think this applies? 

**Are you using any scripts?**
Nope

**Comment by MelvorIdle** [comment]
This will be addressed in statistics 2.0
