### ISSUE TITLE
Switching mid fight on character A to HC character B caused character B to die.

### ISSUE THREAD

**Issue by Whitepawn016** [MelvorIdle/melvoridle.github.io#615]
**Describe the bug**
Switching mid fight on character A to HC character B caused HC character B to die. Character A was fighting Rancora spiders at the time of the switch. Character B was cooking shrimp when I switched to him. But also while the death appeared within the ingame-events on the discord (see SS), my HC character B is still playable.

This also caused my character A file to become corrupted, was able to restore the account via a import after several failed attempts. The desktop version is also stuck on the growing M logo on startup, still after multiple reinstalls. Browser (chrome) version works fine, and both characters are fine.

**Expected behavior**
Just to log into my other character without the possibility of a monster that I'm fighting on another character killing him.

**Screenshots**
https://imgur.com/a/PY6P6x2

**Browser**
Steam on windows.

Also here is the save for that HC char, no way he could have been fighting the spider since he lacks the slayer level req.

H4sIAAAAAAAAA+2da3MbN9Lvv4pKz1uKZ3AH/M5xbnsqTnwiZ/c5teUXI2kk8ZgiubzYcW3lu5/uuREcgkPhr2w2T9VaMWNh0BgA3Wg0fgBn/nl5P1tvtu9nT9Xlq2JyudtU60XJv1z+7XG2rVbl58Xl5JKT3jyWi4dqU2d7WF2+skoapZ2fXN7u1utqsf2qXHysr0a//7J6WJd3VJwNk8vNx9l8/t/vLl/9XRhVSGfMROnCKB/C1JmJUM54KwX/O/hCqql1pmj+2Ik0hZLCqqmvE4SWEyFl8NqoSTERzlmn7FQa/kUYTf8zjgqmpND+oSTltLWqmIY+zVGuqaRL7c+Htpo/VJ+qOdWUsjT/6eYffiImjj8E3WdiHX14qpzmlOaHSlhUv27rAt6tlw/rarPhJls3FaGwmtpkvLPSUj2nXlIXCqqnDsopOTFqqpxzhSioNd4oYSfWTI0rQlEE47iL9MQLaoBRRkvqIOGoc3QxJQlBPUq96SV1BrXF22nw1opCUW8VhXdtG42eKm+NEYHuTEVwuiINaCWoxzT1sab2UHVNkHzD5tMf9NF2XVVvy822Wn/5utyW1L4Pvd5f/0r6dk2eN7vtD7On2fbylZxc3tQG8vd/Xs7uLl9RayaX/9h+uXylKWt5U1vOpprPN98u180v2/L241/L+Y5N87dJK9YKSUEdmhIUh4J1vk6YOqMTT4kGO7irCLK/sexEReFF8s5yeGfqyF5at9JKJEUHN7bRfW1X5eRN/VF7fd9c2XeWTYkq5Q5l2So7WdU1N6TvOmisU4XvRWV322Qvi4I746DO0she2nSVDp6cQbIAGuSHapLKOBpWvZqLtgivbdK4BHutgxJMYcnO+wJGGy+H2hLkrXrRrvFJbdliUHVNVe9ERV9vUSRvTIN4IK1sUezFe+NOSlMHDU0l6jPRV9yc6PMjE42Fe/NOa7wY1lxxUt9nrtO5D8Wzqm7rmWEvX4y5EuWPKs/zz14+FHKs+tKaYfVdiG4vtemqf7L1A/lmDusK0KZXfPL+5riAJq0vwL60AKNfVoC1nQpN0vDdURdqGatQqe7+QaWH7HDI7X1roLlppPKnZhKad8cmA3FU49hkRN9hNKU/o76UqxPtVOWCsp2oGBGt8/X37Qxd6pSoGY7waB7p+kjYkLzrcIhQvr16up4qCiNT0kOXqCmC0fuu7icEk6y2GtTbeb+/t+krnmzx4MYmmga6vgoueVc3uCsFYMVeuotOOPRRyUoP7UMI6XTY20hnldrXbj/RaUfzmDDkaPc21rXcBtG1QB5Mw8MaKIoYZTQoO1uTSrrCp4o48owUtRgdObfetVLgalMlHDlnpQx55Mi5uH5G78e2GrFaHSim7YW7XgxUalJaqKNetEr1c7nu44lCh5T8UAtSWrlXgulGnKdoW6Tk7UDeaGeD3RfQR0Nei2QBfhCMsGcVdh8Q9a7RCK2SPXBkiZxzr4DeV9HCwKRLGI7AeqFk9o3oTdEYa5K9MPB3SkUj2PZDOASXvP8gnKTqB9s7+H6lwIFisv5qGB+Qre7vL/azC5WQNAIzcLoU3cgi9BXoJxjrdbL5vBw9VKIK1NioCv1kU3iTNANjhu5AGCfJJe3L6H14IdL9QCLH41kLvXdryndtIR+bHlCnJsza+hqf2I8kMzJxUa69aG+ChUuJDpteRGFxH14Jl77tsMku6nfd2Z4rUrJHoXzk+oQerlDNmM1Fjlf0XkumJPVRNLgX7LyVSPbScLKL4pFhBHggOJzqXN+7ug/cbErQD52b2I9q0UlqmZQdmAPl6mvbi4q6qxKdO2wqBRQ+8mj9iE52sJSD0aj13pnI3puk7zzQTSTYL6eT9mCPfJjf+3DZBwNJ2aEZeh81dRimHnby0JhkLLqf/5PKHU48tDL/7UPDad6WvzbQbvawWK4rZnnf7ubzy1f35XxT1XLbzXfVolqX85rpcMLlq8v3y205v/ju3UVVrhfby0ldkcv/4qtXD032q4fVVXf1drmj/7NfDZ7nXa76QUmzbfW0udgs53fpsurrV+31tjRNc1ShoqJebynXaru5KLcXHeG8uG15ZrJYznG1z9EWLLl36pb/bbm8u91tt7PFw3HrGXxtLujyxf+6+GbxabZeLp6qBV/5y9OqvB30yud9UVe15BX9FnWNs3FTflg+pLojLmROWQY9QtGfi0vp9HNxv14+XczPl9mprC48qlwhjWnHZVv0dXW7XNxReStq8kXXRycL3jTZr+rsV/vs7Q1oUvTTUPR/PGuA69DCxwY81ir5draunsqPA43U/XWzO7LF+z53019dlq5hIRx211ejRVD3DAoIQvmTvcJ5j3olKu6wU/a527IpCJlSMKm7ThHRjb5aLrigi5vlYre5+O93J+9x02S8qjNe/braF+8KRvDc0fezzeNBR7eE9+dls0Bq+33zOOh0Trq4LXcPj0ddVuet/3/VZ+jue2CidRn35Wxe3V1sl1Ta9vZxpLAm576w0ybZiqXLOuj5SJtKu8JMXfAhBK9V3OMsmhg9B7U7HI0UkoXCnRyOoxU89p3B0ZpPNfFSW97/3i0+jvb//6MMx/0fe9/rVXU7Y49V+9+xsjZNzqPivKwH6+1yyfa2N6N/Xj51/6aZrf037wrVKvvPtT/5NVLprtnUu3u//JknyMOY4E2j7wN3QP7+gu2gGoyR1jau7inDVZ+hn1uciZ1wXUrCkx8UcuTGG0z4fC/clbadUQAw8AJK0gKaO+Cuui938+278qH6afHDsmyo3tOMi/tp3W2MRXPT2/pS3CeUbXNBEsMuaQq5opBrc9Vd7tw+bwDGk8o3FNN8uVg2JVWLdEkc+Hzh8mLfuHfl72a3H8t2w66u6vXTbDv051+Va+o0vjCs7qbNfXVDWei3ar6Nq0yrYK9iV9y4k32+VFFtSNffritLhIP48FCZdZFH2uzL7P36PlsXYUhaa5wykruLroSz5fbZ4k6e8ybwL6vrW4rrFvVYeqDA8pfVXbmtflxuZ/czmtdmywXHqPPVY3nxqZgKP5VUTPWP3Wy1qu7qHuONaGP3O7CTQKsNRasGpXhbW9OykXdlyy1H89fbL/NmN/92+XRTbpsN2n9erubll2rN/3qcbVfL2WK76dnRbsGmth/Iu8V7Gh3NZv9NualeNyWvKs6l682Acp/0dXWzu7+vMx+l7suZLagbqKy7r8snGjk/V3e726bxfBPKFhXzWG7aGai5875qcepfvm7GWLnbLr8pt9/cU3/SQLj90rarTX//SEPkkafgZuld98NrqgsJVLfbH6uHWgnvqvVtVavudJ5v52WXoapW+1rxb/uWUow/+1Q1zdn0me4G/XFXtf3x+pYGY8m1Ztn7+/nslkbHNbewyflUrj/+dP91VW4f+9KitH2RUWIsXlH1vvlUbqgBUR+v2XnfHaeTcma3w+TfyCIX1dMXNh8eCAtaDE5iQyLBqu4qanmjnfYIRV3ir7On3VOT/PNyPj/Mfk3LnsXD9vFIoLtwLPJ1dU96ro4k2vReoNHEVwd6OGGVb6NeOrzyc9xRA6Gor5pOre7nVMW6sDihKeMgC4umx8zZkbR5s1tvogF7y7/W13+o7hsDrX7drstmpL2luWq2ms+qBsr0dpdo1+Yrqvdd7f4jX3DaN/RlHfXe/sqwi9J2fzigWnU2NRwqtb1YFzy8dpfyLXSzlM8ZdUiDIU0O6V252ZAx9XVcNb93ToiGwfL9Y/V2ttn2Wfo7HPjPQ+U2Y+m33/op+U3ttTncaRTZTgRNAp+eoRmBb7o/Z9Fw1ja5x1TtHkiXu8dIDcVoJ6zjWKW5fTz9v10uONPmgg9GHcdwnP3qqc1z1edJLMSafr4g/zQ/CuLqUhrtXd21GU4X8b78WC3Giti2GRJFNLrgmGmzOdGaRj0cgbVZUjVhL7tJ16G7lBCrw9g31Fu7pxM3rwNZKuFU/b/n3nm8eCg5PGyXjGwbqbIe67xXnOmqzXQQBC4XFA3tqvePs+oTB6+Laxrel6+26x1Z77ZNPbCR+3L99J/13H+u/RvWnRTDfeZwuI6cmywP8+WnavOeZpGPPLuRMbanV7tlKM9pr+sgoHfKjMDqtdHr2ttv2ju3gu1SLVvuOloo5El2gy9f8jteGsRSzbhNCX2Ippe6ZxiX1gfc1svbj+0ZTu7+X79/x2dOupm03jK4q1bzahsFARRP88lgPja8buevSVJYFS+R1uIl0i+69cvq/RLh8BLhf1+H6Rc1+plGxvMPZbo9ilxu1+X9dphYPj0tm4DxC+9f/ZXCkzq6022k0w+8ox2cze72ttps7nfzi9Xs9uOKhki1Hcz13ex4tc98dZg5MXc3xbdY+3zRTcbzxbZRUR30NBHBj+/enCr0fIQ0QCvtCiBdWgPK+ixxdNFsDzTxwnEfl/P5csv7YpuLx3JNXvyICLWhxtU+51Wcs2N8Qh3wG4pfV8tNvdF3orzbJsfV7mRs92a9XG0u7makpLtdxfsPFN1TBch8qOaL6oEXcCcKZ9ErFn1O334uZ2y2FMCtL2pJvtfDevk5XXiKSkqn3NgWXPIWVL9zd7hq8iSa8Ldqtr67+G6+XK4ufjnZyw98fdDHUkSG0Q3k2DRer6ntF9ePNJo3F7x2OjaKTuyq5LxXmzpvbA4m3gppgGMjdLqoBjlGufZ7GCa2LfZF3TZSX/0TZaZ0xYfrjOSzcf1qq3VccSe0ey585WiJ0GZva7zP09FML9PV7QRPFJesrNO2rSqDtJ9p3JXr7dc7WpKzF229NF+6Lj9Vb+bL3V0XgWwqHiDVHS1w23X5ereokk76rlx/fLu864OXm92X/9OeY+E2/rB8aJfXzS9f7Wbz/fr6rqkMD3meO940Ff97MRn9+dAcgqhvY0P/02rk56imz9RK3LhTmily9HJQYEo3fTz83bsuGm66r1qUN/PqdT0jzW5m8xk3slPVbS39HQWP/Vwo+HstqzXTzncdEvbG171RM9A3lLqJmOj7cvOxpQV0+2+YCV73X5jaQ7aWB1xzjzaRZZPAKKJoezqtqQ91iLDPLbJyy6zcKiu3zsptsnLbrNwuK7fPyh3ytJOpzDxtijx1ijx9ijyFijyNijyVijydijylijytyjytyswxmqdVmadVmadVmadVmadVmadVmadVmadVladVladVlel687Sq8rSq8rSq8rSq8rSq8rSq8rSq87Sq87Sq87SqM2fUPK3qPK3qPK3qPK3qPK3qPK2aPK2aPK2aPK2aPK2azEApT6smT6smT6smT6smT6s2T6s2T6s2T6s2T6s2T6s2M/7N06rN06rN06rN06rL06rL06rL06rL06rL06rL06rLXNbkadXladXladXnadXnadXnadXnadXnadXnadXnadVnrlbztOrztBrytBrytBrytBrytBrytBrytBrytBrytBoyIUQuhcjEEEUmhygyQUSRSSKKTBRRZLKIIhNGFJk0osjEEUWmfrMxU6Z+c0FTLmnKRU25rCkXNuXSplzclMmbRCZwEpnESWQiJ5HJnEQmdBKZ1ElkYieRyZ1EJngSmeRJZKInkcmeRCZ8Epn0SWTiJ5HJn0QmgBKZBEpkIiiRyaBEJoQSmRRKZGIokcmhRCaIEpkkSmSiKJHJokQmjBJnaVS743rd5tmfI44U7VVRuGPhxK074UjrztAcfVqOn2Y2lI5sQPDjo8bFj+8e2YQsjJEj8sfCkYFI45QeEZSev48zkI8MZrzlx7eObMcU3o8J8+MchuKRKQVNOpvU3wafdN/dfnY1IhPTgSPQnDZE9qat4odnSn7sWfP5bPMZ9zJjkuP+Zkxy3POMSUb2Foz1k/pDKe19RiHjjmlMMrK45glSWdLjDmtMctx1jUmOO7ExyXF3NiIZB57CSUMTEwVPzhvSllfeZVhnHJPSAocMh1bgImQUAJvamXB1TDKyL28nhmosMnzCmTh2TDIyMC/5xlqbUZ9yKA5b2ZlQd0wysjJrJ34i+dTQc6XPhMBjkpFhUaAVJvy01edLy3jmybtxZFb1gxmzhGHPdSZ4HpOEvdaZgHpMEranM0H2iOSZcHtMEp4Iz4TgY5KwdzoTlo9JxrOfMUWe7cbhulK8uhTOkuNQRprnj/g4iNe0hM+LleOQ3kpaEWc2ITIuks4M1OPtZ37o3Wijj6XFgd/wmb0f704ry0+BzpKOnVb9yMQs6TjOrx+XmCV9YHWWbCWIiRnvvcMCIsNrnpaYdfvI4PhZq4FmqInLiDbj3W9A7SFWuzfUdgrMpBpdqQ2WOvHyUjtLwdhEMh15dgGx6VHIPeGHcz9fOl5iqomdKKsypGE/d2ZvfUwSnivP7LiPScJz5Zl9+DFJeK48szs/JgnPlWf27MckYRs6s5M/Jgnb0Jn9/TFJ2IbO7PqPScI2dOYswJgkbENnTgiMScI2dObcwJgkbENnThOMSUY2RGsk+k+KjIXRmYMGY5KwIZ05fjAmCRvSmUMJY5KwIcVHFaQKspg0n9YGZzP4wpkzDGOSsFmdOdkwJglb1JnzDiOS544+jIriVPTMgYhRUdiqzh2TGBWFLenc4YlRURyGnjlSMSqKW9NLEDtuTS+A7GdOYoyK4tZ05nzGqChuTS9A6y9g6zFcVwUF4oYme1nocTYulLKDjZTItFwYnafph3IMxF+whYObF07Wz50JGRXFzevMSZFRUdy8YqgeyD54s8sbRwGZsc7L5wOAg5MlyjI6aj5JEzIonVGnGLgrXe+91Z8iCG9kVkmR6cnCU+CoqGmFURntijE8TbwNm5EhZARDB6dWmldZZCkJJ/LnzrOMiuIGiUP5cwdeRkXx2RPn8udOxIyK4u4tRvP8apCUiPBO1lYqVLKIONQXaV4qfXPQQCYLiKEprQbrd2vmlRBTU59mplrxcxfoHx3QGxQRmZow6SIoOBLN4qXbRxuU4Q+GeLIMR66yqUa6M2Pvl64FO7FGHcm+OCD3aQfBb5mqS7DJAiJDVDSHdX/T9tReGRQRA/y6x+0pe1SpGqihuDgZaiTlY4ssmEKTw28+0oXUmY6LiexSO0cmxB/Ki5ONqTMclxNZZ/0Co/7jVDl1huNyIhP1pFr+S7PAyVZ5cXwWSMSEX1Kr+S8tyk9tc8hkx8RbS3J8AjuWjhE/h+BiohNF8KtX62SdLONwRzz145g31CUlx2pM+mV6g4kfQN4Wka5EZKbp4aG8HmtEZKZ520wCp/4Cx/4C5/4CB/8CJ/8CR/8CZ/8Ch/8Cp/8Cx/8C5/8C3wAQ+A6AwLcABL4HIPBNAIHvAgh8G0Dg+wAC3wgQ+E6AwLcCxJkvGY6K4taEbwQIfCdA4FsBAt8LEPhmgDjzxcVRUdya8B0AgW8BCHwPQOCbABLfBJD4JoDENwEkvgkg8U0AiW8CSHwTQOKbABLfBJD4JoDENwEkvgkg8U0AiW8CSHwTQOKbABLfBJD4JoDENwHkC07Yn/lu56gobk0vOEz/gtP0OPOXLzhKjzN/+YJz9C84SH/m66NjovgxennmS6Wjoi/4agZuTTiwlziwlziwlziwlziwlziwlziwlziwlziwl/hZeokfppcxoj+3cTsUxa3pzJdgR0Vxazrz1dgx0UP2TqqqP4ITGd9rOvMkt1FR3KzOPOFtVBQ3qzNPfhsVxc0q5ug20KTQf+QUEm94e1ql1h9Ce52x2S0PSDp/0WTSfAZFysyozZnnyo2K4vZ25nlzo6K4veFn5SWOzSWOzSWOzSWOzSWOzSWOzSWOzSWOzSWOzSWOzSWOzaU7+JpP/aXb8e++HhWA2xQOz6ULg/ktSxrn5xLn5xLn5xLn5xLn5xLn5zLm59Zl6yd+UIQq8g4XyZiiS2HHZ6+EOO6uYpIuJ3KSc75choOdZN6tVXy60YaMWTwcHO0q+Ckcniby1Lb26TJwW8PpusTpusTpuozpuqGhzX+1MhlfE5Q4ZZc4ZVc4ZVc4ZVc4ZVc4ZVc4ZVc4ZVc4ZVc4ZVc4ZVc4ZVc4ZVc4ZVc4ZVc4ZVc4ZVc4ZVc4ZVc4ZVc4ZVc4ZVcHD7LJFMWtCafsCqfsCqfsCqfsCqfsCqfsCqfsCqfs6gUPq8Epu8Ipu8Ipu3rBg2pe8KSaFzyq5gXPqnnBw2piyp7pYHDKrnDKrnDKrnDKrnDKrs48VHJUFLcmnLIrnLIrnLKrM69GGRXFrQmH6wqH6wqH6wqH6wqH6+rM61ZGRXFrOvMaljFRHJ0rHJ0rHJ0rHJ0rHJ0rHJ0rHJ0rHJ0rHJ0rHJ0rHJ0rHJ0rHJ0rHJ0rHJ0rHJ0r/MS5wqG5wqG5wk+cK5yYK5yYK5yYK5yYK5yYK5yYK/zEucJPnKuYlYcQbOaDNXFWrvBT5wo/da7wU+cK5+IK5+IK5+IK5+IKP3WucB6ucB6ucR6ucR6ucR6ucR6ucR6ucR6ucR6ucR6ucR6ucR6ucR6ucR6ucR6ucR6ucR6ucR6ucR6ucR6ucR6ucR6u8VPnGufhGufhGufhGufhGufhGufhGufhGufhGufhGufhGufhGufhGufhGufhGufhGufhGufhGufh+gVPb3/B49tf8Pz2FzzA/SVPcMetCefhGufhGufhGufhWsO7K9rAO78a5+Ea5+Ea5+E65uG5bcWtCefhGufhGufhGufh2uLWhPNwjfNwjfNwjfNwjfNwjfNwjfNwjfNwHfPwvDcCaJyH65iH67zDqDoG4pnHYHVMxGXufSODyn3dR8zEhc29cXygfPyVUwnh+Dna46cwE8KRXY2/pyEhG096MvPlRDqm4zJXNn6io8isNg7INQ7INQ7INQ7INQ7INQ7INf5IFo3DcY3DcY3DcY3DcY3DcY3DcY3DcY3DcY3DcY3DcY3DcYPDcYPDcYPDcYPDcYPDcYPDcYPDcYPDcYPDcYPDcYPDcYPDcYPDcYPDcYPDcYPDcYPDcYPDcYPDcRPDcYaxpwXbq4fiOCA3OCA3OCA3OCA3OCA3OCA3OCA3MSA/8bjZ0D6VOSTl45c15759L/5SeqZszMll5rvzDp6ynimKW1UMynPvilsVDsoNDsoNDsoNDsoNDsoNDsoNDsoNDsoNDsoNDsoNDsoNDsoNDsoNDsoNfnDc4AfHDQ7KDQ7KDQ7KDX5w3OCg3OCg3OCg3OCg3OCg3OAHxw0Oyg0Oyg0Oyg0Oyg0Oyg0Oyg0Oyg0Oyg1+cNzgoNzgB8cNfnDc4AfHDX5w3OAHxw1+cNzgB8cNfnDc4AfHDX5w3OAHxw3OxQ3OxQ3OxQ3OxQ3OxQ3OxQ3OxQ3OxQ3OxQ3OxQ3OxQ3OxQ3OxQ3OxQ3OxQ3OxQ3OxQ3OxS3OxS3OxS3OxS3OxS3OxS3OxS3OxS3OxS3OxS3OxS3OxS3OxS3OxS3OxS3OxS3OxS3OxS3OxS3OxS1+aNzGTNyce9Ct8QNh3J5wKm5xKm5xKm5xKm5xKm7xY+MWPzZu8WPjFj82bg9oeN6ZHIvjcIufG7c4Drc4Drc4Drc4Drc4Drc4Drc4Drc4Drc4Drc4Drc4Drc4Drc4Drc4DrcHLw51NPE0H7oY/2bwoJD4MJ2zbtJ8aDF+Ku+wkMMnmJPnaz4MfxXl+YVEtiY8BTzNh+ZjIs8vJH6oZiAH0XwYPvb3/ELiFyYHitqaD8NPr3x+IfqgOXLSfGidVUhkk7KwalJ/CC35+TvPLwU3T5yvW5yvW5yvW3uwlSxdkffiAWvh7WSLQ3aLQ3aLQ3aLQ3YbQ3YKnW1mqBGDdgpT6D+tnMl48q2NeTt5GfrPF1nysd+jdQ5Zq1Ymq4gYvucdeLA4fLc4fLc4fLc4fLc4fLc4fLc4fLc4fLcHR9NF5juOLc7fLc7fLc7fLc7fLc7fLc7fLc7fLc7fLc7fLc7fLc7fLc7fLc7fLc7fLc7fLc7fLc7fLc7fLc7fLc7fHc7fHc7fHc7fHc7fHc7fHc7fHc7fHc7fHc7fHc7fHc7fHc7fHc7fHc7fHc7fHc7fHc7fHc7fHc7fHc7fHX4m3eH03eH03eH03eH03eH03eH03eH03eH03eH03eH03eEPbXE4fHc4fHc4fHc4fHc4fHc4fHc4fHc4fHc4fHc4fHc4fHc4fHc4fHc4fHc4fHc4fHf4WXSHn0V3+Fl0h59Fd/hZdIefRXf4WXSHn0V3OCt3OCt3OCt3OCt3+Fl0h59Fdzgmdzgmdzgmdzgmd/hZdIefRXf4WXSHn0V3+Fl0h+Nwh+Nwh+Nwh+Nwh+Nwh+Nwh+Nwh+Nwh59FdzgLdzgLdzgLdzgLdzgLdzgLdzgLdzgLdzgLdzgLdzgLdzgLdzgLdzgLdzgLdzgLdzgLdzgLdzgLdzgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgL9zgLDzgLDzgLDzELz3tebMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeMBZeIhZuJ+ceUnfQDSyprznRISYhee9qy7ELNxPzjwF5VDUHjzY4kyVB6LxQ3zERJyp9EA4sic7OfNIkQ+/fZhc3i4X97P1U7mdLRc/Ld7Ml5vq8tV9Od9Uk8v5bLP966z6fPlqu97R74/V+ma+XFdvy822Wn+he1ABi+rzt+X6abZ4eL2uSr4x1efu8hX1QEkJP5ZPVODl6/l8uX2qFlSzyeWq3N4+Vk3W7ZfVwXW6vKmqO26NYP9zu3xaLTdb+o3XydvZU/VuXi62Fd1B2CIE560qVB3iVtu/0IX1p3Jef6Oxzb7cbdsn+j+Wm+/Wy8+Lvn27xXx5+5GLatr3MF8uV90v8+pTRQUJrgLfv+CO/qNqq19aW1P8ofU1v0N9f8cK18uW0QpbtMJFV2PxR1fZgVWWfZXlH11lD1ZZ9VXWxe9bZXGuygGssu6rbH/nXj5XZZ5roCqbvsr+D+5lnuOgKtv98CueUeciqvGwvkPjjSu42M3nozVsE9oqdtNlU0e3r6P8s9bRH7qxP2Udw95vNbpuQp27etaIQovvKSo5EVXwpagZ9dvdnmPCWtWb3nGzjB6YsERH3YEFRx3/r6wsGv2YAxX8PpUdBhNHlYWDn762yvxxtUVDH2Xi2OePqi0a92hzaq74V9YWDXmMOTlNgNW1opBnRxka7th9dYch2qC6/54JzZycLP4M1fPm1DwhD+aJ9+uqOjFP8KU41GHn/gyj0EVD/uNmKT+0CjSiFCcdxL+yug6NJvcx+9GYe0F97dn6vjyUlGf6998coenOqj9MLqt/7GYrDs6uq21jwX0K/caIbc93GAbxGk0pflOt1vRJJZRPT8sWZsSipxDRCwQ+cNfMq1vqp2+iatd9FLfjzXLHJTIK2K3XlPZ6t11+U/I0Pmjwu936lrqTu+7vtS7rLvuwB1NfLRe7TTu0OyZGd7vhZEqsFcIfzL0ey/UDZ+WWHf+XJf4/MfOfpyb/8zKzkZONvlsyNO0HLif9sqmuV9XtrJy/3m7L24/9xc3j8vP3734kifsvnSOqQe33renWNssp5H+agjcXT+Ud+yGeyi7/i69ddYZ+tWqyXLVZbpsxVLejLeQ9uaGLzYqGzsXNuvo8WzycKIr91VWdMV1QV5sdD7zx2rRZEoW8aXpvrJC2g48Kod5e3t/PZwvqIyrv42w+r11Dedt0f2hcLhX2tGonDy+t9yKY3/YuqNHH9fbLvKq9l5rYD41a3iyfnphbt0qhlL/O1ttdOf+BPfGmV+H9kjH5j7unm2pN3mjLPVr7e9L7mjT+frZqPA9X7FO57T08d0OUxvcZJD0z2/OSmsK4ceWn6v2JnuGOuV1XW2b2vwxmy73P/VyuIp/bTVfLu19WD2s2vFd/b9KOPunuTZl/oUG1aTYKuGevy3lVD4LZbb3jcNDt14/LVfLiqiSb+Kmxgde3R3KkwJty+3a2mN2U65MXml+6y3V/Va936+W67Gbqdvr5jsLFpyW3jqakVbXdd0806Zz5fHbG538eFckJXbfyoBh2AGn/mgZY9VVFllv9XPKYYz08LOc3swX//v1sQ6b7ZZh83e/viWhaX9OVN8sZdz0Z/d1sU97Mq9d3+/Fx/c3793/58btrHqU35eJj9/+vluu7at2EUU0P1+HA19V9uZv3Crlrfv2KBK6X6yZKaNPYht6XN8NZfctJIvbcIpUoU4kqlahTiTaV6FKJPlkl2SWrw+SQTFZFOlmkk2UyWXRlm4NkrdLJOp1s0sk2nezSyT6dnK6gKVLJ2p7I3fVJcZgsk8m2SCenC7EnClHpZJ1Krp9kf5ysfXdLfWCQPm0nJn1Lk7yl6HQmDyrSt/0gWSZTdbIa2plUpbWz6WSXTDbJom0q1STHQW9lh3mT5Zp0uekS0o0+MURVumoh1WaTHLgmWUSv08PU5BjXTidvl/RgMjmuTNpNGJV0EzUnSyWnC5HJgW96PzZI3lfwA4VsT93xgn9ePs7uqrflrz80a+J2oomPLLx5rG4/rmhaaieS30j+7evr99/8/H9ZvuCP1XLJBFN5GpJ+qqXXgf5QVX5d8fGMwhsp3dQpEYLT/GhVWbjCmSmNsiB8wc+3d0ZIVUwLZY3ygU/Akx1YTb5TkF8luakSNM7qnwnFWE7TjUTwVtAffrGKU8GoqScfZ4IkTUvtCnKPkpKc1EKLCclICs3oroFcng38ksNLsa+/KIJySrmpDypYqziGqxtgQiH5C/90Jz6xpZTi58YIqiplEV4XVLgx/IYpaUPQgZrhlDZBSRqnVgY5MQXZguF3C9b/klYoJ52cUsuVpPu2Gfijzk8VV3pCtfDOqzAtglXGUAo5X6unXhnqCrIjfs+tJT9NnWU1jTynHL8OUAtqMr+ViqY1ZaaBy6B+5+bKWF38Li41ZTZDXWy61mrtxEQVUvrQ1qMpT0pduK4PAqmJ9DY11PHG8OuvvCOteTuVoaCeCeS46N6B76n29zSOLtipLwolvKifXFLfk9Vm/VQWQnK/eIqLRn64UB0VKoMhi5hKqq3Xksdza3dkAXbiXBBCTQvvyf40ZWLro273U1sI46iW3DZD9/XF1AnqV0c65eZq69iM+OtTVAJ1kVJTV2gjBe+veprYqSesJWOgEkSQ/EwUMnRqg5lqaoU3ZGeaa2ui2tKddGHctCArFVp2XUCRidL8MjJqDVkH6bpL2P+DbFZToXpKNs4POOuvtHWJRLqxU2vr3/S/0yejaJC4QhZTVVAHBOqzc+fGDn72g+XU/Uar8zsKsYm/pLzaA0UulNlr0RrE8TG0SxF7K8H+hIYvuQRlXKE6sycLpp4lJ0eD2tMAoIHtDfk0Gus0sgtHqRMap6bwTvY/7LnIDUzJHzX5aJiRlxJBTJ02lv0huzHyMkKS1sjLcdn8Jj7FbtvWo8MJ/vqRDOSop5pNsb4dRSXCBTMtrPFkpNIze57QTWWhp87S7KBUwe+6t1RHaahi1CCuOPnOgtzQVFuKCykLPw2wHv/OkttyNADIhigsUPbYPYjI6TinaTxQJS2N0aJ+QGvdUVTzMBXUCnIGNNRN4m2ClIPaK+lP8ORM4q9xCUkeecre17JnEYcmrGlsOzulqJju6Pi7JbSWEPTrlPuFslPMTe7IaPIDgtwBGQM/AY2L5elHKtv98BFDCjCkFFOeYOvEut/Jjwjytu0d1ITLoE4hryY933L0FX4n2DL3nI5nROq7gpwZzZaaPbbtbIz+ST6VbKZx4y5vAJOnD45m1fbn7KnRZD0jn0pKkCcHzp/1p25E2DdC1bsQWBs+cFS221SMYGaLOm77ebeoIrQ2W2+2jKp+WJZ70LSZl1+q9fty85EEV/OqwX37m7cY9rrO9stwV2V/qU/igHPzer6uyrsv3y53i7sWcsiJmtAAn7iJn5DDpHjF0CxMkybNr+R6yGfQaOAX5JGzICdJyxBaJml28mTWFFuR55lQfEPLCPK3tNqi6ZdWkPW8TMVJHjY0wvh9noqdsuDRxpPghNfkvADn1TYvrXkdzYtmXiHzcpgXubyi5WUgr/mE4TdxUj66m2DfTjfjNSwvWHl1yktRqfltgFR7yiMpj6RYh2axiST/REOP/np2ghMO5MjO+y0iXoHyJpEmWW35L/2bJnpe+/FCj1d1vMrhBSy/OJXfe8pBJb91lF8ayu/85Fd2skfnJSe/oZDfMcjvCeS1MEXWE96gooil3priOI6XJhSKTPjdovziZcnvEOToOPAkPOFj1HwKm89/87loXrLwF1f53Yn8mklB2WniIDv4ldYM79bVpj5gTIvi/w+ZNyBCX18BAA==

**Comment by MelvorIdle** [comment]
This is most likely fixed in the coming update
