### ISSUE TITLE
Most recent save not actually the most recent one. 

### ISSUE THREAD

**Issue by glassabilen1** [MelvorIdle/melvoridle.github.io#619]
**Describe the bug**
Most of the time when loading a save it's correct but sometimes the most recent save is not the actual most recent one when comparing between local and cloud save. 

**To Reproduce**
Run the game for any amount. Save and quit. Go back to the select save screen. 

**Expected behavior**
Most recent save to be marked as such. 

**Screenshots**
Cloud save
![image](https://user-images.githubusercontent.com/16068105/103949172-258f4a00-513b-11eb-9fd9-31b80dd0cecb.png)

Local save
![image](https://user-images.githubusercontent.com/16068105/103949152-19a38800-513b-11eb-86ac-884ae40f7889.png)

Only a few seconds difference here. 

**Browser**
Please tell us what browser you are using and what version.
Firefox 84.0.2 (64-bit)

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.
Combat simulation addon

**Comment by Physalix** [comment]
Someone else had this occur as well, this time with not just a few seconds difference, but over 900 hours.
https://www.reddit.com/r/MelvorIdle/comments/kvshoe/old_save_vs_most_recent_save_bug_says_my_most/
"Most Recent Save" was 936 hours from the time the screenshot was taken, and the "Old Save" was from 23 hours from the time the screenshot was taken.

**Comment by MelvorIdle** [comment]
Most likely fixed in the upcoming update

**Comment by glassabilen1** [comment]
I noticed something that might have been useful in the original upload. I have more than one save and mostly use the second one. The problem seems to have been fixed for save #1 but it's consistently wrong every time for save #2. With save #3 I have deleted my local save but the cloud save still says old on it.
