### ISSUE TITLE
WC only gives half the XP when offline

### ISSUE THREAD

**Issue by spontaani** [MelvorIdle/melvoridle.github.io#622]
When cutting both redwood tree and yew tree offline with a dragon axe for 8 hours (no skillcape) I only received around 450k xp. When doing the math that's only around 16 xp/s. 
However when I do it while the game is open I receive around 37,8 xp/s which would give over a million in 8 hours. My cut time for redwood is 7,5s and for yew wood it's 5,8s with dragon axe.
Could it be possible that WC is ignoring the dragon axe or maybe all interval reduction in general when offline?

**Comment by pliiick** [comment]
I am having similar issues with offline XP but also offline item counts. I have pet, god upgrades, max cape, t4 birds nest potions and clue chasers insignia on cutting normal logs and redwoods and doing different 12 hour offline tests my redwood count is sporadic. Getting about 6k birds nest offline for 12 hours, sometimes I get 20 mysterious stones sometime I get 0. Feel like woodcut is totally bonked offline right now.

**Comment by MelvorIdle** [comment]
I have applied a hotfix for this to the game :)
