### ISSUE TITLE
Cannot restore purchase for ad removal iOS 0.18.2

### ISSUE THREAD

**Issue by eric-saindon** [MelvorIdle/melvoridle.github.io#623]
![3247625E-B706-459C-86A9-96B1B9C48B26](https://user-images.githubusercontent.com/22131988/104058132-7c833680-51b0-11eb-85c8-75a47ab251c1.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

When clicking “restore purchases” the button is not responding. I’ve uninstalled, reinstalled, restarted my device.

**Screenshots**

**Browser**
Please tell us what browser you are using and what version.

**Console output**
Please open the console by pressing F12 and copy it here.

iOS

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

no scripts

**Comment by Magerz** [comment]
I’m also experiencing this problem, happened after I switched internet providers for some reason. I also get the exact same message of “You need to enable ads!” when trying to purchase the ad-free version again.

My username is Magerz, if that helps.

**Comment by MelvorIdle** [comment]
This should be fixed now with the latest iOS update
