### ISSUE TITLE
FireMaking Mastery Bugged Online

### ISSUE THREAD

**Issue by bobjoelol** [MelvorIdle/melvoridle.github.io#624]
**Describe the bug**
Firemaking offline is producing significantly more mastery exp/h then online

This is a 5 hour test online through steam with save file
[Steam save no semi access currently bonfire potions used Online.txt](https://github.com/MelvorIdle/melvoridle.github.io/files/5789786/Steam.save.no.semi.access.currently.bonfire.potions.used.Online.txt)

![fm steam online](https://user-images.githubusercontent.com/77177672/104075436-d00d7880-51e0-11eb-9de4-c9a778998295.PNG)

This is from 5 hours offline doing fire making mastery with the save file
![Fm offline](https://user-images.githubusercontent.com/77177672/104075463-de5b9480-51e0-11eb-8250-9732db775ad2.PNG)

[Offline File with semi access.txt](https://github.com/MelvorIdle/melvoridle.github.io/files/5789783/Offline.File.with.semi.access.txt)

**To Reproduce**
Firemake online with the same save file load one initial from cloudsave to start the test from force save. Leave online running after force saving to create start point for offline.

**Expected behavior**
Same results

**Screenshots**
Online
![fm steam online](https://user-images.githubusercontent.com/77177672/104075587-385c5a00-51e1-11eb-9a6a-8796aecd51eb.PNG)

Offline
![Fm offline](https://user-images.githubusercontent.com/77177672/104075590-3b574a80-51e1-11eb-99a1-46da0d4860ad.PNG)

**Browser**
Chrome Has semi enabled for combat simulator and time remaining. 

**Console output**
I do not have the console output currently mite still be saved in the linked save files. 

**Are you using any scripts?**
Semi was allowed access before and after testing on offline version.

**Comment by bobjoelol** [comment]
Online 2 hour test to double confirm ignore I spent mastery pool in this screen shot forgot I was doing this >.<
![Steam_online_test_2](https://user-images.githubusercontent.com/77177672/104075716-a43ec280-51e1-11eb-8f08-4710eb49c278.png)
Mobile 2 hour test
![Screenshot_20210108-182114](https://user-images.githubusercontent.com/77177672/104075718-a6088600-51e1-11eb-9391-dc0ed2aa96ed.png)

**Comment by bobjoelol** [comment]
"the timePerAction replacements added to addMasteryXP() don't get applied when getMasteryXpToAdd() is called directly from updateOffline()" 

info from GRC copied right from discord they did additional testing.

**Comment by Razorflamekun** [comment]
I can also confirm that online Firemaking is much slower than offline Firemaking.  I don't have any photographic proof, but the couple of tests I did showed a couple of interesting points:

15m of online FM gave me 50K less XP than 15m of offline FM.

Sorry if this doesn't help, but I figured I'd post my own test.  I forgot to take pictures :(

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
