### ISSUE TITLE
iOS Spotify Bug

### ISSUE THREAD

**Issue by Defilantema** [MelvorIdle/melvoridle.github.io#625]
**Describe the bug**
I had Spotify playing in the background, and when opening the Melvor Idle app, if not closed and reopened again, would stay at a loading screen unless the game was restarted. Once restarted, it lets me enter one of my profiles, but shortly after it’ll either kick me back to a loading screen, or it’ll send me back to the profile selection page

**To Reproduce**
1. Open spotify and play any song
2. Open Melvor Idle with Spotify on in the background
3. Start any of the dungeons

**Expected behavior**
Spotify to be able to run in the background while Melvor Idle sits next to my bed on the Spider Forest Dungeon

**Screenshots**
N/A

**Browser**
Melvor Idle Version 1.0.5
iPad 6th Generation - Software Version 14.3

**Console output**
N/A

**Are you using any scripts?**
No scripts were used.

**Comment by MelvorIdle** [comment]
I believe this is either hotfixed, or will be fixed in the next update
