### ISSUE TITLE
Sandstorm Ring not working in Infernal dungeon

### ISSUE THREAD

**Issue by bekfst** [MelvorIdle/melvoridle.github.io#626]
**Describe the bug**

In infernal stronghold, Using darksteel dagger and sandstorm ring 
Sandstorm ring didnt proc a single time in the whole dungeon
Not sure if this is a dungeon mechanic

Im too computer illiterate to record or anything so just sus it yourself i guess,

hope this helps.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser**
Please tell us what browser you are using and what version.

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

**Comment by MelvorIdle** [comment]
A weapon special attack with a 100% chance to activate will override any other potential special attacks.

This is intended.
