### ISSUE TITLE
Plant Instantly killed my Hardcore Character.

### ISSUE THREAD

**Issue by GitDavriel** [MelvorIdle/melvoridle.github.io#628]
I had just unlocked the ability to mine and smelt drogonite. I was level 3 in combat. I decided to farm plants as they are relatively weak, I didn't want to take major risks with my character as I'd devoted much time to reaching my current standing. I was equipped with full iron armor, including sword and shield. This was the strongest armor I could currently equip. I had 3 cooked shrimp to eat when I needed. My character was 100/100 hit points. I attacked the plant about 5 times before it instantly killed me. It took all of my hit points in a single blow. I believe that this event was unintended by the developer, I'd like this not to happen to others as it is very disheartening.

**Comment by Platmo** [comment]
He later confirmed on discord that he had the candy cane equipped so there is no bug here.
