### ISSUE TITLE
Mining Mastery Tokens much more common than they should be

### ISSUE THREAD

**Issue by Razorflamekun** [MelvorIdle/melvoridle.github.io#629]
According to the Wiki, the odds of getting one Mining Mastery Token is 1 in 1,667.  I mainly idle Mining online overnight, and almost every single day that I come back to the game, I have 15-25 Mining Mastery Tokens waiting for me.  I didn't think it was strange until I did the calculations of how rare this actually is.  According to my calculations for the 22 tokens I got last night, the chance I came up with was 0.000001271% over a short 8 hour period.  This to me seems highly unlikely and extremely ridiculous.

1. Start Mining Adamantite or Mithril ore.
2. Idle overnight ONLINE for a period of time.
3. Get lots of Mining Mastery Tokens

The expected behavior of this is that with odds of 1/1667, I would expect to get 1 Mining Mastery Token for every 1,667 ores than I mined. (given that you always have the chance to get ONE every 1,667 ores).

I play on the latest Steam version, on a Windows 10 machine. 

Thanks!

**Comment by ethan-yxchen** [comment]
What is your action per second for mining? If it's 1.3 sec per action, then it's around 22000 actions over 8 hours; given a binomial distribution where n=22000 and p = 1/1667, the chance of getting exactly 22 tokens is 0.737%. Not that low.

**Comment by Razorflamekun** [comment]
Well, it seems like something was changed because I'm no longer getting the obscene amounts from Mining any longer.
