### ISSUE TITLE
Magic/Runecrafting

### ISSUE THREAD

**Issue by Eusmusia** [MelvorIdle/melvoridle.github.io#63]
Adding Magic as another means of combat would farther expand on how we do combat. Using runes, created via Runecrafting, would give an option for many more NPCs, dungeons, and new equipment types.

Runecrafting would use essence gathered from Mining. Each node in Runecrafting would required the talisman, which is from drops, chests, thieving, etc, but the air talisman would be the easiest to get as Air Runes are needed for basically everything and introduces players to Runecrafting.

Mastery levels would increase the amount of runes created per essence. ranging from 2 up to 10 (only for basic elemental runes).

When magic is used for combat, a drop down menu would include any combat spells you have the level to cast (if too much clutter, remove the lowest tier spells first) and if you have the runes to cast, you will begin casting in combat, like range with arrows. Would have the option for pure magic experience or defensive casting (Magic + Defence exp)

Various pieces of equipment could come from crafting, as the armor is cloth. Cloth could be gained from fighting NPCs, chests or thieving (depending on the tier of the cloth) or similar to how leather to dragon hide works in the shop.

**Comment by mrDLSable** [comment]
Also, the spell drop down menu could hide spells you don't have the runes for.

**Comment by Eusmusia** [comment]
Also Magic could bring back the combat triangle as well. Magic > Melee > Range > Magic so certain types of equipment would outweigh others. Like you wouldn't wear Melee armor to fight mages as you'll get hit significantly more.

**Comment by MelvorIdle** [comment]
Added to v0.10
