### ISSUE TITLE
Possibly Unobtainable Cape of Completion

### ISSUE THREAD

**Issue by logam555** [MelvorIdle/melvoridle.github.io#630]
**Describe the bug**
I am not at a point in the game where I can prove this yet, but I believe it is very easy to lock yourself out of the Cape of Completion. Since you need 100% Completion Log meaning you need all items, except for certain exclusions, which would require every tier of every Herblore potion. This should normally not be a problem, but you can spend Global Mastery Pool Exp to increase mastery on a potion to 20+ easily before even unlocking the potion let alone making it.

**To Reproduce**
Steps to reproduce the lockout:
1. Get some Global Mastery Pool Exp in Herblore
2. Level a potion that has not been crafted yet to Mastery level 20+
3. Craft tier 2, without ever being able to craft a tier 1 of it afterward.

**Expected behavior**
Things occur as expected. Due to this, a player can unintentionally lock themselves out of the Cape.

**Screenshots**
![Divine T2](https://user-images.githubusercontent.com/33184510/104114280-8c923780-52d0-11eb-9038-3448849d5149.png)

**Some Possible Fixes**
-Selectable Potion Tiers
-Tier 1-3 potions are excluded from % completion, like event type items are
-Crafting a potion unlocks all tiers below it. aka crafting a T2 with no T1 in log unlocks T1 in the log.
-The check for upgrading potions tiers occurs only on successful craft of the potion (doesn't help any accounts currently locked)

**Comment by Razorflamekun** [comment]
There is a potion later on in the Herblore skill that allows you to gain a random tier of a random potion at a low rate, which means that you can still obtain it, it will just be a lot more RNG.
