### ISSUE TITLE
Master Slayer Gear description is incorrect

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#631]
**Describe the bug**
Master Slayer Gear says it provides a chance to double loot from thieving despite the fact that it does not.

**Expected behavior**
Master Slayer Gear descriptions should not say they provide a chance to double loot from thieving, or the bonus should be added to thieving.

**Screenshots**
![image](https://user-images.githubusercontent.com/58208131/104118878-3ed5f900-52e9-11eb-9337-bc797b6f5390.png)
This is the code for item doubling in thieving. As you can see it doesn't include master slayer gear.
```js
                let itemQtyChance = 0;
                if (
                  herbloreBonuses[14].bonus[0] === 0 &&
                  herbloreBonuses[14].charges > 0
                ) {
                  itemQtyChance += herbloreBonuses[14].bonus[1];
                  updateHerbloreBonuses(herbloreBonuses[14].itemID);
                }
                if (
                  equippedItems.includes(CONSTANTS.item.Aorpheats_Signet_Ring)
                )
                  itemQtyChance +=
                    items[CONSTANTS.item.Aorpheats_Signet_Ring]
                      .chanceToDoubleLoot;
                if (equippedItems.includes(CONSTANTS.item.Chapeau_Noir))
                  itemQtyChance +=
                    items[CONSTANTS.item.Chapeau_Noir].chanceToDoubleLoot;
                if (
                  getMasteryPoolProgress(CONSTANTS.skill.Thieving) >=
                  masteryCheckpoints[2]
                )
                  itemQtyChance += 10;
```
**Browser**
Browser agnostic bug

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Fixed in upcoming update.

Related #688
