### ISSUE TITLE
Alt Magic fills console with errors

### ISSUE THREAD

**Issue by glowinghands** [MelvorIdle/melvoridle.github.io#632]
**Describe the bug**
Error in console while casting alt magic
```
TypeError: Cannot read property 'xp' of undefined
    at getTotalMasteryLevelForSkill (mastery2.js?638:55)
    at calcMasteryXpToAdd (<anonymous>:481:25)
    at calcExpectedTime (<anonymous>:596:44)
    at timeRemaining (<anonymous>:675:27)
    at window.selectMagic (<anonymous>:948:17)
    at magic.js?638:2
```

**To Reproduce**
1. Go to alt magic
2. Cast Blessed Offering
3. Go to console

**Expected behavior**
Not fill console with errors on every cast

**Browser**
Chrome Version 87.0.4280.141 (Official Build) (64-bit)

**Console output**
See above

**Are you using any scripts?**
default SEMI but this appears to be all Melvor code based on the stack trace.

**Comment by MelvorIdle** [comment]
This is not a Melvor code stack trace. This is an external script.
