### ISSUE TITLE
Rags to Riches II Combo rune nature rune cost issue

### ISSUE THREAD

**Issue by dsmky117** [MelvorIdle/melvoridle.github.io#634]
**Describe the bug**
Rags to riches II has a different nature rune cost when using combination runes.

**To Reproduce**
1. Mouseover rags to riches II in the alt magic page.

**Expected behavior**
Nature rune cost shouldn't be affected by whether or not you use combo runes.

**Screenshots**
![image](https://user-images.githubusercontent.com/19257672/104215459-c6655a00-5406-11eb-9014-7ee2bd163723.png)

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
