### ISSUE TITLE
Incorrect image scaling [mobile]

### ISSUE THREAD

**Issue by eviltwigster** [MelvorIdle/melvoridle.github.io#635]
**Describe the bug**
Some images are incorrectly scaled on mobile, displaying far too large to fit within the UI or even on the screen. The issue appears to only occur on the "upgrade item" interface, but will always occur. I encountered the bug on my Google pixel 5 and replicated on my Motorola moto g7.

**Screenshots**
![Screenshot_20210112-120733](https://user-images.githubusercontent.com/69431056/104258840-2e33a780-54d0-11eb-845a-d1e2f91047d8.png)
![Screenshot_20210112-121135](https://user-images.githubusercontent.com/69431056/104258860-35f34c00-54d0-11eb-8e1e-3332778fec0f.png)
![Screenshot_20210112-121416](https://user-images.githubusercontent.com/69431056/104258882-3ee41d80-54d0-11eb-82c8-e3b2e16539e5.png)

**Browser**
Android app (premium/ad free version) v 0.18.2

**Are you using any scripts?**
No scripts

**Comment by Xanthus179** [comment]
This is also happening in the same version on iOS.
