### ISSUE TITLE
Steam achievement is not working

### ISSUE THREAD

**Issue by Faedon** [MelvorIdle/melvoridle.github.io#636]
**Describe the bug**
Lose a hardcore character achievement is not working in Steam. One of my HC characters just died and I didn’t get the achievement. 

**To Reproduce**
1. Go to one of the HC characters
2. Click on combat and die
3. Scroll down to achievement in Steam

**Expected behavior**
When a HC character died, achievement should immediately popup. I think this relates to an another issue which is achievements are unlocking when you close the game and open it again and then go inside the character which got the achievement. Since there isn’t a save file anymore when you died in HC, you can not get the ach. 

**Screenshots**

**Browser**
Steam. Version 18.02

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using scripts?**
No.

**Comment by ZephyrToad** [comment]
Can confirm, this just happened to me and didn't trigger. RIP.

**Comment by MelvorIdle** [comment]
I believe I hotfixed this. If not, its confirmed fixed for the upcoming update
