### ISSUE TITLE
Ocean Song special attack does not work with ancient magicks and/or displays the wrong attack name.

### ISSUE THREAD

**Issue by Stormageddons** [MelvorIdle/melvoridle.github.io#637]
**Describe the bug**
Since Ancient Magicks each attack is coded as a special attack when using the wand Ocean Song the special attack does not trigger, (attack bar says "Using Ocean Song") followed by the normal Ancient Magicks cast. 

**To Reproduce**
Equip Ocean Song while casting any single hit Ancient Magick (ex. Frostbite)
Fight an enemy with more than 3k health (to get a chance to see it easier)
Wait for special attack it will display ocean song but the attack preformed is just the standard Frostbite

**Expected behavior**
My assumption is that since Ocean Song is a separate attack not modifying your current spell is that it would have been usable with ancient magick (similar to stormsnap no matter what arrows you are using/other gear for accuracy it still hits the same). As it is you can "miss" while it says casting Ocean Song a guaranteed hit.  Otherwise would just expect to see the bar always display casting frostbite etc and never show casting ocean song with the wand.

**Browser**
Chrome

**Console output**
NA

**Are you using any scripts?**
Nope

**Comment by Physalix** [comment]
It literally says, in the ancient magic spellbook:
"Ancient Magicks are not affected by any Damage Modifiers, except for the Combat Triangle"
Ocean song special attack is a damage modifier, therefore it does not work with ancient magicks

**Comment by MileB** [comment]
> ... Ocean Song is a **separate attack not modifying your current spell**

> Ocean song special attack is a **damage modifier**, therefore it does not work with ancient magicks

(Emphasis mine)

@Physalix I'm not sure I would call Ocean Song a damage modifier. I haven't dug down in to that definition much, but it's supposed to be a flat damage attack, no?

I think what you're saying could be happening down in the codes, but I'm not sure if that's supposed to be the intent. I think @Stormageddons 's comparison to Storm Snap as a separate attack is apt here.

**Comment by Physalix** [comment]
I agree that it is not a damage modifier after looking at it again, however I still feel like ancient magicks shouldn't benefit from ocean song's special attack, due to ancients already being BIS to use pre-ocean song, and when obtaining Ocean Song normal magics finally get a use again.
I feel like it's intended to not be able to used with ancient magicks, thats why the damage doesn't just get nulled but the ancient's cast still goes through.

**Comment by MelvorIdle** [comment]
Special attacks do not work with Ancient Magicks.

I will update the description in the next update.
