### ISSUE TITLE
Game Crashes Every Few Minutes

### ISSUE THREAD

**Issue by heartrate160** [MelvorIdle/melvoridle.github.io#640]
**Describe the bug**
Every few minutes, the game shows a “Loading” screen and takes me back to the development disclaimer. It generally loops a few times before letting me play the game for a few minutes and then repeats. This only started happening yesterday, will happen if I’m just sitting on a title screen, and still happened on a new save. I do have my game saved to the cloud so i also tried deleting the app and reinstalling.

**To Reproduce**
Happens on any screen seemingly at random

**Expected behavior**
Previously the game wouldn’t reboot so much

**Screenshots**

Not sure if this helps but this is the typical progression
![AE300BDD-A493-4CDF-9A2B-4DDEEA1C4946](https://user-images.githubusercontent.com/10319495/104401427-2997df00-5522-11eb-9dc5-c06a5b110b34.png)
![0CA09E94-2187-4F0C-BB4B-EA653B9F51AC](https://user-images.githubusercontent.com/10319495/104401428-2997df00-5522-11eb-99dc-3764843c04f4.png)
![1E0201C4-9C0C-439B-AE8F-B8DD517F11AB](https://user-images.githubusercontent.com/10319495/104401429-2a307580-5522-11eb-8939-d3e00a05b528.png)

**Browser**
iPhone app (using an iPhone 8 on latest OS)

**Console output**
I think this might not apply to the app?

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Should be fixed next update
