### ISSUE TITLE
Steam wont load. 

### ISSUE THREAD

**Issue by Ejjen** [MelvorIdle/melvoridle.github.io#641]
I tried to get the achievement on steam to lose a HC character, so created a new one and lost it. Easy. 
Though I did not get the achievement, I tried twice - So that in itself might be a bug? 
Though the biggest issue I am having now is that I can't load up the game at all on steam anymore, from what I've seen it still works on my tablet and on the website. 
I can't even get to select character, it's the first "loadscreen" I'm stuck on. 

I have tried to validate my files, reinstalled and completely remove files. Nothing have helped. 
Have never used any scripts or alike on melvor.

**Comment by 0vertime** [comment]
I tried the same thing. Clicked "Load Old Save" on the empty slot where the HC character died. Got prompt to create a new character while there was background of already existing fresh character. Closed the game with X. Couldn't boot since. Forever looping on the M logo with dark background.

**Comment by Ejjen** [comment]
(I don't know how to properly reply here. ) But I will try doing that as well, Overtime. 
Ty for update~
