### ISSUE TITLE
[Steam] Rich presence - Total level does not update

### ISSUE THREAD

**Issue by C0rn3j** [MelvorIdle/melvoridle.github.io#642]
**Describe the bug**
Currently, the game sets rich presence seemingly only on game load, but not on level up, so it stays out of date.

Using Select Character menu from within the game and selecting the current save updates the rich presence.

**To Reproduce**
1. Start game
2. Level up
3. Realize you're missing bragging rights

**Expected behavior**
Rich presence being updated on each levelup

**Screenshots**
![image](https://user-images.githubusercontent.com/1641362/104712733-33d4fb80-5723-11eb-84d8-ef066733d786.png)

**Are you using any scripts?**
No.

**Additional info**
Running Arch Linux, cloud saves enabled.

**Comment by MelvorIdle** [comment]
I believe this may already be fixed

**Comment by C0rn3j** [comment]
![image](https://user-images.githubusercontent.com/1641362/108262349-1b626180-7165-11eb-87ce-2936eef51ca5.png)
![image](https://user-images.githubusercontent.com/1641362/108262371-21f0d900-7165-11eb-8cb4-1fd3e057149e.png)

It's not.

**Comment by MelvorIdle** [comment]
Can confirm it is now fixed (Please restart the game)

It checks for an update to your Total level every 10 seconds.

**Comment by C0rn3j** [comment]
I can confirm it works

>Please restart the game

Sorry about that, I may have left it running overnight before testing
