### ISSUE TITLE
When you equip/bury something from the bank or change attack style the Hitpoints label is unhighlighted until the next new monster is refreshed to fight.

### ISSUE THREAD

**Issue by Silberdrachi** [MelvorIdle/melvoridle.github.io#644]
**Describe the bug**
When you equip/bury something from the bank or change attack style the Hitpoints label is unhighlighted until the next new monster is refreshed to fight.

**To Reproduce**
1. Start Combat with any monster
2. Go to Bank
2. Click on Bones (Or arrows/bolts/gear)
3. Check currently highlighted green skills in side bar
4. Bury bury all bones (Or equip all arrows/bolts/gear)
5. Check side bar to see which skills are highlighted after action is completed

**Expected behavior**
Highlighted skills should accurately reflect which skills are in use.

**Browser**
Firefox

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
