### ISSUE TITLE
Bank search filter doesnt handle new items added to bank

### ISSUE THREAD

**Issue by Silberdrachi** [MelvorIdle/melvoridle.github.io#645]
**Describe the bug**
When you equip something from the bank while searching for it, the thing that it replaces (when something is already in that equip slot) shows up in the bank even if it doesn't match the search parameters. Pressing the sort button refreshes the bank and the item goes away correctly.

**To Reproduce**
1. Go to Bank
2. Equip any gear from your bank into your equipment set
2. Use search bar to select a _different_ piece of gear (IE: "Aries Godsword")
3. Click the item in the bank, and equip the god sword
4. See that the gear equipped in step 2, that was replaced by the gear in step 3, is now in your bank despite the filter not allowing it

**Expected behavior**
Search filter should apply consistently at all times.

**Browser**
Firefox

**Are you using any scripts?**
No

**Comment by benanderson1** [comment]
The following is another way to reproduce the same issue:

1. Search for any item in bank
2. Go fight stuff to receive some new items
3. Go back to bank, still on filtered view list, but with the new drops you just received shown as well rather than only the filtered items.
