### ISSUE TITLE
Hunter's Ring passives not processing correctly

### ISSUE THREAD

**Issue by DrChemEng** [MelvorIdle/melvoridle.github.io#647]
**Describe the bug**
Testing Hunters Ring today shows that the +10% Slayer XP, while showing on Equipment Stats, does not process on the actual Slayer XP earned post-battle.

**To Reproduce**
1. Defeat Slayer Task Monster to obtain given Slayer XP based on current formula (0.15 x Max HP for Slayer Task x Equipment Bonus (60% with Elite Slayer Gear) - Hunter Greater Dragon -> Awarded 1649 Slayer XP
2. Equip Hunter Ring
3. Defeat Slayer Task Monster to obtain given Slayer XP based on current formula (0.15 x Max HP for Slayer Task x Equipment Bonus (70% with Elite Slayer Gear + Hunters Ring) - Hunting Greater Dragon -> Awarded 1649 Slayer XP

**Expected behavior**
Upon wearing Hunters Ring, I expected the awarded Slayer XP to increase to 1751 for representative slayer monster.  This would be a 1.71667 multiplier on the expected 1020 Slayer XP (0.15*6800), versus the 1.61667 factor used without  Hunter Ring.  Slayer Coins seem to be calculated correctly.

**Screenshots**

**Browser**
I am running the game on IOS 14.3, using game version Alpha V0.18.2

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
No scripts

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
