### ISSUE TITLE
Offline Mining does not give Mastery Pool XP

### ISSUE THREAD

**Issue by Razorflamekun** [MelvorIdle/melvoridle.github.io#649]
When logging back into my HC character that was mining offline and only play on Browser, I noticed that my character gained all of the item mastery XP (iron ore), but did not gain **any** skill mastery XP (the mastery XP pool in the top of the skill tab) over a full 12h period of time offline mining.

To reproduce this error, all one has to do is start mining on an HC character and then go offline and come back to it about 10 minutes later.  You'll have to write down the skill mastery XP and the item mastery XP, and then when you come back online, compare the two and you should get the same result I did, where you get little to no skill mastery XP.

The expected behavior of these actions is that you gain the skill mastery XP commensurate to the amount of item mastery XP you got while offline.

I use Google Chrome Version 87.0.4280.141 (Official Release) (64-bit)

I was unable to get the console information as I was just dumbfounded and closed the game before I knew that I would need that information.

I do not use ANY scripts.

Thanks!

**Comment by Razorflamekun** [comment]
I'm going to run a test right now and see if it does it on the Steam client as well.

**Comment by Razorflamekun** [comment]
After more testing, I've found that this only happens in offline mode and it only happens when you do prolonged offline sessions.  This may be triggered by the same thing that causes offline Woodcutting to not work properly.

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
