### ISSUE TITLE
Managing Miscellania style activity

### ISSUE THREAD

**Issue by Eusmusia** [MelvorIdle/melvoridle.github.io#65]
The Managing Miscellania mini-game in Runescape allows you to put gp into a coffer and assign workers to various activities to receive materials ranging from herbs to logs, fish or coal.

With how Melvor is, an idle game, having another way to gather resources would prove handy. While you are gathering logs to fletch or firemake, you can have your workers gather coal for you. This would help speed up certain processes while also taking some gp out of the game. 

Using this, shop upgrades could be added to further increase your workers for more resources at the cost increasing gp costs for the mini-game itself. More gp consumed, more resources.

**Comment by mrDLSable** [comment]
A tie in with a construction skill might also be nice.

**Comment by mrDLSable** [comment]
Also, perhaps this could be implemented as a management skill?
