### ISSUE TITLE
Fighter Amulet and Glacia Godsword Stun Interaction and Glacia Godsword Stunning in General

### ISSUE THREAD

**Issue by WindwalkingBM** [MelvorIdle/melvoridle.github.io#650]
**Describe the bug**
When using a Glacia Godsword and a Fighter Amulet, the priority of the Fighter Amulet is higher than the Glacia godsword. For example, if I hit a creature and deal over 70% damage and trigger the fighter amulet stun while also using the special attack of the Glacia Godsword, the enemy is only stunned a single time instead of twice.

Furthermore, the procs of the Stun do not stack when attacking. For example, if I hit an enemy and it gets stunned twice, a second proc of the Glacia Godsword does not refresh the stun stack. So if I stun and the creature attacks twice and I stun in the middle of his second attack, the stun duration is not increased back to two and the monster is instead unstunned. 

**To Reproduce**

**Expected behavior**

With the fighter amulet and the Glacia godsword, I would expect the Glacia GS to take higher priority over the Fighters Amulet. With the Glacia Stun, I would expect another proc of the special to refresh the stack on the monster, although this might just be intentional. 

**Screenshots**

None

**Browser**

Chrome v0.18.2

**Are you using any scripts?**

No

**Comment by MelvorIdle** [comment]
This is intended.

All debuffs including stuns, slows, freezes, bleeds etc etc do not stack. This goes for enemy attacks on the player as well.

Some items take priority over others, so this needs to be managed when finding an efficient setup for combat.
