### ISSUE TITLE
Ocean Song special slows enemy for 3 ATTACKS, not 3 TURNS, or is cancelled by channeled attacks by enemies

### ISSUE THREAD

**Issue by MrMathewRogers** [MelvorIdle/melvoridle.github.io#651]
**Describe the bug**
Ocean Song special slows enemy for 3 ATTACKS, not 3 TURNS, or is cancelled by channeled attacks by enemies. The slowing effect works correctly for enemies which do not use channelled attacks

**To Reproduce**
1. Equip Ocean Song, 
2. Using any standard spellbook spell,
3. Attack Chaotic Greater Dragon

**Expected behavior**
Chaotic Greater dragon attack speed should be recuced for 3 attack TURNS

**Screenshots**
N/A

**Browser**
Chrome Browser, latest version

**Console output**
Synchronising with Cloud
11:52:06.781 MICSR.js:7 MICSR: Object
11:52:06.783 MICSR.js:7 MICSR: Object
11:52:07.725 MICSR.js:7 MICSR: Elapsed Simulation Time: 4423.200000047684ms
11:55:20.021 cloud.js?640:12 Synchronising with Cloud
11:58:37.486 DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
11:58:37.487 DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
11:58:37.487 DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/13c28911820333eb6a51103a0e2096477a38941cc79afbf16b59f3d5a5f63086.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
11:58:37.950 DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
SEMI and Combat Simulator are enabled.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
