### ISSUE TITLE
Check for death isnt done until the end of a multi-attack

### ISSUE THREAD

**Issue by Silberdrachi** [MelvorIdle/melvoridle.github.io#653]
**Describe the bug**
When a special attack that causes multiple hits is used, the monster isn't checked for death until all attacks were performed even if the monster dies on the first attack.

**To Reproduce**
1. Equip a weapon (Twin Exiles) or spell (Gust) that causes multiple attacks
2. Start combat with an enemy
3. Observe the damage dealt at the end of an enemy's life, seeing the last attacks marked as "miss"  because no damage is dealt because there is no HP left

**Expected behavior**
Once a monsters health reaches 0 combat should end.

**Browser**
Firefox 84.0.2 (64-bit)

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
