### ISSUE TITLE
Redemption Prayer does not function as intended

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#654]
**Describe the bug**
The current implementation of the redemption prayer has a number of flaws that makes it function differently to the description.
1. The prayer only triggers upon taking damage from an enemy attack, when it should trigger from any source of damage.
2. The prayer currently heals the player by 120% of their max hitpoints instead of the listed 20%.

**To Reproduce**
1. Activate the redemption prayer
2. Take some damage to put you under 10% hitpoints
3. Player is healed to full

**Expected behavior**
Redemption should heal the player by 20% of their max hitpoints when taking damage from any source that puts them under 10% of their maximum,

**Screencapture**
(https://streamable.com/9ch87v)

**Browser**
Browser agnostic bug.

**Fixes**
This is the current implementation in attackPlayer() in combat.js
```js
    if (
      prayerBonusHitpointHeal > 0 &&
      combatData.player.hitpoints > 0 &&
      combatData.player.hitpoints <= maxHitpoints * 0.1
    )
      updatePlayerHitpoints(
        Math.floor(maxHitpoints * (1 + prayerBonusHitpointHeal / 100))
      );
```
This should be ammended to:
```js
    if (
      prayerBonusHitpointHeal > 0 &&
      combatData.player.hitpoints > 0 &&
      combatData.player.hitpoints <= maxHitpoints * 0.1
    )
      updatePlayerHitpoints(
        Math.floor(maxHitpoints * prayerBonusHitpointHeal / 100)
      );
```
and migrated into the damagePlayer() function to fix. Note: This may also require an additional check for thieving as it would provide free healing at no cost, and require a change to the description to reflect this.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
