### ISSUE TITLE
Duplicate Combat Loot

### ISSUE THREAD

**Issue by Revolyze** [MelvorIdle/melvoridle.github.io#656]
**Describe the bug**
You can double the loot that drops minus the initial item by clicking fast on the first item. Basically you collect the loot and then the system updates it visually but you already got the loot so you get it again.
Note: Probably easier to reproduce with some minor lag and with more items.

**To Reproduce**
1. Fight a monster without auto-loot.
2. Get at least 2 items in the loot to collect, more the better.
3. Spam click on the first item.
4. Obtain double of every item in your loot to collect minus the initial item.

**Expected behavior**
No duplications

**Screenshots**

**Browser**
Steam 0.18.2

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixed in next update
