### ISSUE TITLE
focus change sometimes dequeues actions

### ISSUE THREAD

**Issue by NFodrea** [MelvorIdle/melvoridle.github.io#657]
**Describe the bug**
Quickly switching focus away from and back to a tab cancels the queued action

This doesn't happen all the time and seems to be pretty inconsistent. I've been trying to reproduce it and have only had luck getting the issue to happen with mining. The same issue will also happen sometimes if I start an action and alt tab away to go do something else, when I come back I haven't mined anything. 

**To Reproduce**
1. start mining 
2. switch tabs
3. go back to tab.
4.  A pop up showing 0 xp is shown, however the resource you were mining is no longer being mined.

**Expected behavior**
The queued action should remain in effect until canceled or switched

**Browser**
Windows Chrome 87.0.4280.88 

**Console output**
none

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Should be fixed next update, if not already hotfixed
