### ISSUE TITLE
Looting items manually doesn't check if bank is full

### ISSUE THREAD

**Issue by mazunki** [MelvorIdle/melvoridle.github.io#658]
**Describe the bug**
Looting items from a monster doesn't check if bank is full, but disappears from the loot when clicked. Avoidable if careful, but annoying if bank was full and you hadn't noticed.

**To Reproduce**
1. Fill bank
2. Try to loot an item you don't have in bank
3. Item is gone, but notification saying "Bank is full" appears
4. Lost a drop you really wanted

**Expected behavior**
Leaves the item in the monster's loot box

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Should be fixed in next update, if not already hotfixed
