### ISSUE TITLE
Reindeer pet appears in pet list even if not obtained

### ISSUE THREAD

**Issue by mazunki** [MelvorIdle/melvoridle.github.io#659]
**Describe the bug**
Unlike items in item list of completion log, pressing pets shows Reindeer pet as a pet you still haven't found. Since it is unobtainable / an exclusive event item, I believe it should be hidden unless you already have found it.

**To Reproduce**
1. Get a new account
2. Click on Completion Log
3. Press Pets
4. Hover last pet
5. Hint: Christmas Event 2020

**Expected behavior**
Unless you found it already, it shouldn't appear in list at all.

**Screenshots**
![image](https://user-images.githubusercontent.com/32819373/105245599-5c6d5300-5b72-11eb-9eed-6353d66d854a.png)

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
