### ISSUE TITLE
Opening chests resets number

### ISSUE THREAD

**Issue by mazunki** [MelvorIdle/melvoridle.github.io#660]
**Describe the bug**
When opening N chests, I would expect it to remember my choice of N, and not reset to all of said chest. If I want to open 2 chests at a time, i have to re-select 2 as the number.

**To Reproduce**
1. Press a chest in bank you got a M amount of.
2. Drag bar to some number N, less than M/2.
3. Open N chests.
4. See bar has reset to M-N.

**Expected behavior**
If there is more than N chests in bank after opening N, it should stay at N, instead of resetting bar.

**Are you using any scripts?**
No

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
