### ISSUE TITLE
Selecting 1 if you only have one item of something makes it look like you are selecting none

### ISSUE THREAD

**Issue by mazunki** [MelvorIdle/melvoridle.github.io#661]
**Describe the bug**
When selecting the amount of items to open/sell, but you only have one of said item, it sets the bar to "minimum", and not "all".

**To Reproduce**
1. Press something you have only one thing of in bank
2. Try to move bar to max.
3. Compare to max items of any other item

**Expected behavior**
The bar would be entirely to the right side, and not the left, and thus entirely blue and not white.

**Screenshots**
I only have one of this dagger:
![image](https://user-images.githubusercontent.com/32819373/105248999-a86ec680-5b77-11eb-9257-c99ba09a5689.png)

But I have four of these chests:
![image](https://user-images.githubusercontent.com/32819373/105249014-b1f82e80-5b77-11eb-9424-aa877fac5985.png)

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixes applied to game - Alpha v0.21 (?1119)
