### ISSUE TITLE
Fishing stats displaying incorrectly

### ISSUE THREAD

**Issue by ItsPandatory** [MelvorIdle/melvoridle.github.io#662]
**Describe the bug**
In the stats window my fishing is displaying a very low number of fish caught. It is counting properly when I watch it.

**Screenshots**
![Fishing](https://user-images.githubusercontent.com/75848979/105554377-76b74600-5cc4-11eb-94b0-c1fdc105d25f.PNG)

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
