### ISSUE TITLE
Infernal Claw upgrade window

### ISSUE THREAD

**Issue by ItsPandatory** [MelvorIdle/melvoridle.github.io#664]
**Describe the bug**
When upgrading the ancient claw to infernal it doesn't display the +6 in green to the right of the slash bonus.

**Screenshots**
![Infernal claw](https://user-images.githubusercontent.com/75848979/105624541-998a4d00-5ddf-11eb-955d-17e365908a9d.jpg)

**Browser**
Steam version

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
