### ISSUE TITLE
Alt Magic Rune Numbers Don't Update While Crafting

### ISSUE THREAD

**Issue by alexhoward-ps** [MelvorIdle/melvoridle.github.io#669]
**Describe the bug**
While runecrafting runes, the rune amounts do not update on the selected "skill" under alt. magic. Navigating to a different recipe fixes the issue and displays the correct rune amounts temporarily, but it will not update again.

**To Reproduce**
1. Go to "Runecrafting"
2. Begin crafting a rune of your choice used in alt magic
3. Navigate to "Alt. Magic"
4. Choose a recipe using the rune you are crafting
5. See described error.

**Expected behavior**
Like the other pages, while crafting the numbers update consistently regardless of what you're crafting. These numbers on this page should increase as you are crafting.

**Screenshots**
N/A

**Browser**
Brave - Chromium based. Also replicated on the steam application and iOS/

**Console output**
Waaaaay too long to copy and paste as the same error pops up every time when trying to fetch the rune amount stored in the db. GameAnalytics.min.js:2 Warning/GameAnalytics: Event queue: Failed to send events to collector - Retrying next time
r.sendNotificationMessage @ GameAnalytics.min.js:2
r.w @ GameAnalytics.min.js:2
C.processEventsCallback @ GameAnalytics.min.js:2
y.sendEventInArrayRequestCallback @ GameAnalytics.min.js:2
a.onreadystatechange @ GameAnalytics.min.js:2
XMLHttpRequest.send (async)
y.sendRequest @ GameAnalytics.min.js:2
y.sendEventsInArray @ GameAnalytics.min.js:2
C.processEvents @ GameAnalytics.min.js:2
a.processEventQueue @ GameAnalytics.min.js:2
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
GameAnalytics.min.js:2 POST https://api.gameanalytics.com/v2/c924273e39face38ff3218ef6a871b54/events net::ERR_BLOCKED_BY_CLIENT
y.sendRequest @ GameAnalytics.min.js:2
y.sendEventsInArray @ GameAnalytics.min.js:2
C.processEvents @ GameAnalytics.min.js:2
a.processEventQueue @ GameAnalytics.min.js:2
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2
setTimeout (async)
a.run @ GameAnalytics.min.js:2

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixes applied to game - Alpha v0.21 (?1119)
