### ISSUE TITLE
Offline cooking doesn't use potions (correctly)

### ISSUE THREAD

**Issue by Alci8** [MelvorIdle/melvoridle.github.io#670]
Offline cooking with potions yields a lot less products then expected for using potions. 

First reported here: 
![obrazek](https://user-images.githubusercontent.com/7593022/106069880-b4243500-6103-11eb-8ed1-14a4495ed8a1.png)

The faulty code responsible is probably this (main.js/updateOffline): 

```
let doubleCookChance = 0;
if (herbloreBonuses[9].bonus[0] === 0 && herbloreBonuses[9].charges > 0) {
  let chance = Math.floor(Math.random() * 100);
  if (herbloreBonuses[9].bonus[1] > chance) doubleCookChance += herbloreBonuses[9].bonus[1];
```

it probably shouldn't use the `chance` as a condition to use a `chance`. The result is 30% of 30% chance.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
