### ISSUE TITLE
Cannot start other skill actions after depleting rock in mining until it respawns

### ISSUE THREAD

**Issue by CoderRichard** [MelvorIdle/melvoridle.github.io#671]
When Mining an Ore (Adamantite) that goes into a depleted status, then switching over to a different Skill, the Skill will not execute

Steps to reproduce:

1. Mine Adamantite Ore until depleted
2. Switch to new Skill, for example Smithing
3. Attempt to start Crafting on that new skill

Expected Behavior:
It will start Crafting the new request

Actual Behavior:
The progress bar will move forward on the new crafted item for a split second, then stop.

**Comment by KeelanPiispanen** [comment]
I had this same issue but with mining Runite, and trying to train another skill (Runecrafting) or trying to mine a different ore had the same behavior you described.

**Comment by jttheghost** [comment]
> When Mining an Ore (Adamantite) that goes into a depleted status, then switching over to a different Skill, the Skill will not execute
> 
> Steps to reproduce:
> 
> 1. Mine Adamantite Ore until depleted
> 2. Switch to new Skill, for example Smithing
> 3. Attempt to start Crafting on that new skill
> 
> Expected Behavior:
> It will start Crafting the new request
> 
> Actual Behavior:
> The progress bar will move forward on the new crafted item for a split second, then stop.

I am able to easily duplicate this on the steam version 0.18.2 with mithril/adamantite/runite

Any time a rock is depleted, you are unable to switch actions by clicking off of it, and it also does not show you are training any skill. The only way to switch to another skill is to click on the depleted node again as if you're cancelling the action. "This node is depleted" pops up with no other visual difference, you are able to then train another skill. This is more noticeable at higher level mining levels when the rocks take a significant respawn time.

**Comment by jttheghost** [comment]
> > When Mining an Ore (Adamantite) that goes into a depleted status, then switching over to a different Skill, the Skill will not execute
> > Steps to reproduce:
> > 
> > 1. Mine Adamantite Ore until depleted
> > 2. Switch to new Skill, for example Smithing
> > 3. Attempt to start Crafting on that new skill
> > 
> > Expected Behavior:
> > It will start Crafting the new request
> > Actual Behavior:
> > The progress bar will move forward on the new crafted item for a split second, then stop.
> 
> I am able to easily duplicate this on the steam version 0.18.2 with mithril/adamantite/runite
> 
> Any time a rock is depleted, you are unable to switch actions by clicking off of it, and it also does not show you are training any skill. The only way to switch to another skill is to click on the depleted node again as if you're cancelling the action. "This node is depleted" pops up with no other visual difference, you are able to then train another skill. This is more noticeable at higher level mining levels when the rocks take a significant respawn time.

Still happens in 0.19 (Offline progress hotfix)

Slight different from above repro steps: You have to switch from another character to this character, and if the node is depleted when you switch to it, this will happen until the node regens.

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
