### ISSUE TITLE
AROS/AROM don’t drop (offline/skeleton fish)

### ISSUE THREAD

**Issue by pisastrish** [MelvorIdle/melvoridle.github.io#672]
Something is wrong with the aros/arom drop rate. With dragon rod and fishing amulet, I fished skeleton fish at 99 mastery and 95% pool and fast forwarded 12h 13 times and didn’t get either ancient ring. If the wiki is accurate, on average, I should get a fish/special item once every .6*.8*(4+12)/2=3.84 seconds. With a special rate of 8%, it should roll a special item on average 3.84*.08=.3072 times per second, plus whenever the last mastery pool bonus activates, but I don’t know if that has the same rates for each special item so I’ll ignore it. Over 13 12 hour intervals, this means I should roll special items 12*13*60*60*.3072~=170,000 times on average, I’ll assume unrealistically bad odds and round down to 100,000. The chance of not getting either ancient ring when you get a special item is 1-2/6722<.99971, so the chance to not get either in 100,000 rolls <.99971^100,000~=2.5e-11%

Mobile, no scripts

**Comment by pisastrish** [comment]
Sorry ios to be more specific

**Comment by Alci8** [comment]
your math is wrong. With 3.86s per catch and 8% chance, it's special every 3.84/0.08=48s which is 1800/day. Go from there. 

AROM/AROS can be dropped offline. There is another bug that real chance is somewhat different (can't say if lower or higher, it's very time/item specific) but for 12h offlines it will be rather close to the one on wiki, with just some error. But it can roll AROM/AROS still well. 

It's just really rare and being within 5% of population pushes you pretty far from average. It's like that for any very rare drop. Yet is not super impossible event. It still happen to many people.
