### ISSUE TITLE
Darksteel Dagger

### ISSUE THREAD

**Issue by dingwendamn** [MelvorIdle/melvoridle.github.io#673]
**Describe the bug**
Shows incorrect descriptions or item performs wrong damages.

**To Reproduce**
1. Click on 'Darksteel Dagger' item
2. Go to 'Special Attack' section
3. See 'Deadly Cut(100%) - Perform a normal attack. Enemy bleeds for 5% of **their Max HP** as dmg over 10 seconds.'

**Expected behavior**
1. Wear 'Darksteel Dagger' item in combat
2. See Special Attack(bleeding part) deals dmg according to 5% of **Player's Max Hit** instead of **enemy's Max HP**.

**Browser**
Google Chrome 87.0.4280.141

**Are you using any scripts?**
no
![needstobefix](https://user-images.githubusercontent.com/78194347/106240150-bc34bf80-623e-11eb-9a22-454d7e588cd1.png)

**Comment by dingwendamn** [comment]
![needtofix](https://user-images.githubusercontent.com/78194347/106240056-97d8e300-623e-11eb-8ccb-df057e74829a.png)

**Comment by imperialboy3** [comment]
5% of their Max HP over 10 seconds. It does 20 bleeds every 0.5 seconds. 5800*0.05/20=14.5 which gets truncated to 14.

**Comment by dingwendamn** [comment]
you're right
