### ISSUE TITLE
Ancient Ring of Skills does not apply bonus to Alt. Magic. 

### ISSUE THREAD

**Issue by sonicdm** [MelvorIdle/melvoridle.github.io#675]
---
name: Bug report
about: Ancient Ring of Skills does not apply bonus to Alt. Magic. 
title: Ancient Ring of Skills does not apply bonus to Alt. Magic. 
labels: bug
assignees: ''

---

**Describe the bug**
When equipped the xp bonus does not apply despite the description saying it works . Only fire cape and the fire pet apply. Theres a check in the code that disqualifies it for being a combat skill. 

**To Reproduce**
Equip the ring and look at the xp multiplier returned from the xpbonuses function

**Expected behavior**
Alt Magic getting an 8% xp boost from the ancient  ring of skills

**Browser**
Chrome

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
