### ISSUE TITLE
Controlled Heat Potion - Incorrect Bonfire

### ISSUE THREAD

**Issue by ZephyrToad** [MelvorIdle/melvoridle.github.io#676]
**Describe the bug**
When the potion relights the bonfire for free, the type will switch to whichever log you are currently burning.

**To Reproduce**
1. Go to 'Firemaking'
2. Have 'Controlled Heat Potion' active.
3. Light Bonfire with 'Normal Logs'
4. Change Log type to higher tier.
5. Wait for bonfire to relight.

**Expected behavior**
Bonfire should remain the type and EXP bonus of the logs used to start them.

**Screenshots**
![image](https://user-images.githubusercontent.com/17329308/106372531-3431e100-6336-11eb-8c35-6b0b266a05c7.png)

**Browser**
Steam | Alpha V0.18.2

**Console output**
N/A

**Are you using any scripts?**
N/A

**Comment by MelvorIdle** [comment]
This is intended. The bonfire is lit with the logs that are currently selected.

I'll update the description in the next update to notify players of this mechanic.
