### ISSUE TITLE
Mobile no offline progress

### ISSUE THREAD

**Issue by SumAmerican** [MelvorIdle/melvoridle.github.io#677]
**Describe the bug **
Alot of the time whenever i wake up after afking a task like mining, i will see that i only get a few of the item when i should have 1000x more. Ive noticed this happens over longer periods of time away from my phone, so mostly when i sleep. To be clear, I just turn off my phones power button without swiping the tab up to close it, and when i wake up, i sometimes have only made a few seconds of progress. This has cost me about 30 hours of idle time. The fix for me seems to be swiping up the app before i turn off my phone, but i forget that a lot and newer players might get extremely dissatisfied after this happens to them
**To Reproduce**
1. Go to a skill tab
2. Click on any task
3. Leave the game (without swiping up melvor/fully closing it) 
4. %50 of the time see the error

**Expected behavior**
For a night of afking with a mining cape and mining gloves, i would get 90k coal (or something like that) +gems

**screenshots**
Not a screenshot but after a whole night of afk it will say i only mined 14 coal
**Browser**
Please tell us what browser you are using and what version
IOS 14 iPhone 10
**Console output**
N/A, im on mobile
**Are you using any scripts?**
Nope

**Comment by MelvorIdle** [comment]
When you use the power button while the game is open, it is incredible hard for the game to figure out that it is in idle mode because the phone shuts off the function before the game can detect it.

It's best practice to simply close or minimize the app.
