### ISSUE TITLE
Special attack percentages are off by 1

### ISSUE THREAD

**Issue by imperialboy3** [MelvorIdle/melvoridle.github.io#678]
**Describe the bug**
Successful roll determined by: floor(random()*100) <= event_chance.
Just get rid of the equal sign and it works correctly.

**To Reproduce**
1. roll=floor(random()*100)
2. event_chance = 25
4. floor(0.25999999*100) <= 25
5. roll <= event_chance TRUE

**Where to find**
Combat.js if(chanceForSpec<=specChances[i]+specCount)
Combat.js if(chanceForSpec<=combatData.enemy.specialAttackChances[i]+specCount)

**Comment by Delurielle** [comment]
Better yet, get rid of the floor.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
