### ISSUE TITLE
Slight Disagreement Between a Skill's Mastery Percentage

### ISSUE THREAD

**Issue by Erico9002** [MelvorIdle/melvoridle.github.io#679]
I stopped firemaking right when I hit the threshold where it said at the top I was at 95%, but for the checkpoint bonus to activate I had to burn one more log. I guess there's just a slight difference in how the two handle rounding. If you do the math, I was at 0.949955111... mastery exp for firemaking.

![image](https://user-images.githubusercontent.com/57814950/106826709-11ad0a00-664d-11eb-8d19-4d4588ed11b2.png)

**Comment by MelvorIdle** [comment]
Fixed in upcoming update.

The mastery pool percentage will now be accurate.
