### ISSUE TITLE
Gold Emerald Ring does not give the expected 7% bonus xp to Prayer

### ISSUE THREAD

**Issue by gmiclotte** [MelvorIdle/melvoridle.github.io#682]
**Describe the bug**
Update v0.18 claims to nerf base prayer exp. What happened instead is that the Gold Emerald Ring bonus xp for Prayer was halved. So this leaves two issues:
 - Gold Emerald Ring does not give the expected 7% bonus xp to Prayer
 - base prayer exp was not nerfed

**To Reproduce**
1. Go to the combat tab
2. Do some combat with prayers that give xp activated
3. Do some combat with prayers that give xp activated and a Gold Emerald Ring equipped
4. See that (3) gives 3.5% more xp / damage than (2)

**Expected behavior**
 - The Gold Emerald Ring gives 7% more prayer exp.
 - Base prayer exp is halved, or the nerf is removed from the v0.18 change log.

**Screenshots**
Item description claims it should provide 7% exp for all combat except slayer:
![2021-02-04_21-14](https://user-images.githubusercontent.com/12995926/106950072-244b4000-672e-11eb-8ec0-d508361a3de2.png)
Here's the relevant part of the code in v0.18.2 (combat.js?664)
![2021-02-04_21-12](https://user-images.githubusercontent.com/12995926/106949774-b43cba00-672d-11eb-9546-cc95433d509d.png)
Here's the same code, but from v0.17 (combat.js?549)
![2021-02-04_21-18](https://user-images.githubusercontent.com/12995926/106950351-93289900-672e-11eb-9387-743e2d821af3.png)
Relevant part of the v0.18 change log
![2021-02-04_21-28](https://user-images.githubusercontent.com/12995926/106951393-02eb5380-6730-11eb-9337-11e4c8756069.png)

**Browser**
Steam client and others.

**Console output**
No relevant console output.

**Are you using any scripts?**
Yeah, but when I disable them the bug is still there.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update. I did indeed halve the wrong value. Whoops...
