### ISSUE TITLE
(Steam) Did not Receive Achievement for beating Mumma Chicken

### ISSUE THREAD

**Issue by ShynyMagikarp** [MelvorIdle/melvoridle.github.io#684]
(Apologies if this has already been reported. I noticed how on Steam the mastery achievement was marked as "bugged" so I assumed if this one was known to be working improperly it would've been tagged as well) In addition, I did a ctrl+f on this page and didn't see any mention of Mumma Chicken or Dungeon.

**Describe the bug**
I beat the Chicken Coop dungeon for the first time but did not receive the achievement for beating the dungeon.

**To Reproduce**
1. Go to the Chicken Coop dungeon
2. Defeat the dungeon
3. Check Steam achievements
4. Notice it's missing

**Expected behavior**
I expected to receive the achievement, but I didn't.

**Screenshots**
![Melvor_Idle_Aw5hj3KxfV](https://user-images.githubusercontent.com/78581575/106992779-a2eebe80-67bc-11eb-9f5a-0dfa64636aef.png)
![Melvor_Idle_T0rBFvaj0a](https://user-images.githubusercontent.com/78581575/106992782-a5e9af00-67bc-11eb-9f73-2238194eb434.png)
![YfCFdwKsLG](https://user-images.githubusercontent.com/78581575/106992790-a84c0900-67bc-11eb-8088-60092f34ff4d.png)

**Browser**
Steam Client - V0.18.2

**Console output**
(on Steam so)

**Are you using any scripts?**
No.

**Comment by ShynyMagikarp** [comment]
I didn't notice when or how but the achievement registered on my Steam now. Unsure how or why. Sorry about that.

**Comment by egroenestein** [comment]
I have the same issue on Hardcore mode, 
killed her twice but no achievment yet. 
I died after the first try the death achievement poped but no mam chicken.

killed her for a second time, no achievement (Hardcore mode)
