### ISSUE TITLE
Alpha warning loop

### ISSUE THREAD

**Issue by Dracogenius250** [MelvorIdle/melvoridle.github.io#685]
**Describe the bug**
There is a random possibility of a continuous loop of the starting screen where you’re notified about this games Alpha status and agree to the terms of play, followed by the screen where you create or load a character. The screen can randomly appear at any point during gameplay, after agreeing and selecting which character to use the screen will immediately reappear asking you to repeat the steps. The number of times this can happen is completely random but I’ve had it go beyond 7.

**To Reproduce**
Unfortunately I cannot find what causes the login screen to appear, it can appear at any point during gameplay with seemingly no preference for when

**Expected behavior**
After selecting the account you wish to play on the same screen will immediately re-interrupt your game to have you select which account you wish to play on.

**Screenshots**
Screenshots have been attached of which warning screen I’m describing.

**Browser**
iPhone IOS 14.3

**Are you using any scripts?**
I am not using any scripts as far as I am aware.

![27947D78-8787-42DE-94F9-B7875D8AB697](https://user-images.githubusercontent.com/78589282/107010884-eae1f700-6764-11eb-8486-4fdeaf154b03.png)
![0D1A8CF3-3752-4F3E-BD22-B48C9DD6FBAB](https://user-images.githubusercontent.com/78589282/107010888-eb7a8d80-6764-11eb-8bd5-48c44055e74f.png)
![17FDFE4B-5DEC-4716-B492-AEBA6CCD0F6D](https://user-images.githubusercontent.com/78589282/107010890-eb7a8d80-6764-11eb-89b6-f5d118c04ea6.png)

**Comment by MelvorIdle** [comment]
This should hopefully be fixed in the upcoming update
