### ISSUE TITLE
Master Slayer Gear does not affect thieving drops

### ISSUE THREAD

**Issue by Falterfire** [MelvorIdle/melvoridle.github.io#688]
**Describe the bug**
I assume this is going to be fixed as part of the unification of bonuses in v0.19.0, but just in case it isn't: Right now, despite the description for Master Slayer gear using the same wording as Chapeau Noir and the Signet Ring, it does not (from what I can tell looking at the code) provide a boost to thieving loot.

(And on a related note, the Golden Golbin stands out as being a slightly weird exception - All other effects of this type say they affect both combat and theiving, but the Golbin only affects combat. Dunno if this is intentional or not, but figured I'd mentioned it)

**Comment by MelvorIdle** [comment]
Confirmed fixed with the unification of bonuses in v0.19.
