### ISSUE TITLE
Enemies fall back to normal attack when a special is unavailable

### ISSUE THREAD

**Issue by Delurielle** [MelvorIdle/melvoridle.github.io#689]
**Describe the bug**
(Possibly intended behavior, but surprising to me if so.) When an enemy's special attack is unavailable and it rolls for its next attack, it has a chance to do a normal attack instead.

E.g. after Ku-tul uses Elusiveness, it has a 50% chance to use normal attacks with Max Hit 4 for the next 2 turns. This feels a little silly.

**Expected behavior**
At least when the total chances of special attacks are 100%, I expected normal attacks to never occur.
(It's less obvious what the intuitive behavior would be if e.g. there's a 50% total chance and half of that is disabled.)

**Comment by MelvorIdle** [comment]
This is intended.

An enemy cannot stack a buff, so if it rolls a buff while it is already active then it will perform a normal attack. This is why the normal attack amount is always shown. All damage numbers need to be accounted for.
