### ISSUE TITLE
Progress loss when switching device

### ISSUE THREAD

**Issue by Philipp766** [MelvorIdle/melvoridle.github.io#693]
**Describe the bug**
I just started to play this game because it got recommended to me. So i dowloaded the app on android and started playing. shortly after, i discovered the Web version
I created an account to sync my progress and started to progress on the PC. after i came back to the phone, i discovered, that the app still had the old state and synced it over the newer web save.

**To Reproduce**
1. Start the Game on your mobile device (do not close the app!)
2. play on another device and sync it in the cloud.
3. go. back to the now old version on your phone. it orobably will save very soon
4. your further progressed web save state is now overwritten with the older, afked phone state and you have probably lost progress.

**Expected behavior**
The app version should check, if the cloud save is newer than the app save and should ask the user, which one to load, without first having to close and reopen the app.

**Browser**
-Firefox (probably not important for this issue)
-Android app

**Comment by MelvorIdle** [comment]
I'll look into solutions for this. In the mean time, please remember to close the app as this is what should be done
