### ISSUE TITLE
Decay does not defeat enemies properly

### ISSUE THREAD

**Issue by aermolae** [MelvorIdle/melvoridle.github.io#694]
**Describe the bug**
Recoil damage from the Decay curse spell will not cause an enemy to die, instead causing it to go into negative health while it continues attacking. The next attack you make against the enemy, whether or not it succeeds, will cause the enemy to die properly.

**To Reproduce**
1. Lower an enemy's health below 2% of maximum.
2. Allow the enemy to successfully hit you while the Decay curse spell is active

**Expected behavior**
Enemy should die when its health goes below 1 and should not get a chance at an additional combat round.

**Screenshots**
![Screenshot_20210211-175542_Melvor Idle](https://user-images.githubusercontent.com/47756431/107708971-6b878280-6c92-11eb-9637-faa324a1433f.jpg)
![Screenshot_20210211-173700_Melvor Idle](https://user-images.githubusercontent.com/47756431/107709025-8528ca00-6c92-11eb-91dd-221887299ec6.jpg)
![Screenshot_20210211-175951_Melvor Idle](https://user-images.githubusercontent.com/47756431/107709312-fe282180-6c92-11eb-9243-2b60cb7b9b6a.jpg)

**Browser**
Latest Android release of Melvor Idle from Google Play

**Console output**
n/a

**Are you using any scripts?**
n/a

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
