### ISSUE TITLE
Sell price inconsistency

### ISSUE THREAD

**Issue by timefreer** [MelvorIdle/melvoridle.github.io#696]
**Describe the bug**
The sell price on some items (noticed so far: Oak Logs, Maple Logs, Yew Logs) is inconsistent. The individual sale price above the number of items to sell range selector is different from the price listed under the "Sell Item" button when 1 item is selected.

**To Reproduce**
1. Have Oak/Maple/Yew Logs in inventory
2. Click any one of those logs
3. Change quantity to sell to 1
4. See the difference between the two sell prices

**Expected behavior**
The unit sell price should match the sell price for 1 item.

**Screenshots**
![image](https://user-images.githubusercontent.com/70162015/107862519-335f7b80-6e1b-11eb-87cf-057ab51194e0.png)
![image](https://user-images.githubusercontent.com/70162015/107862523-43775b00-6e1b-11eb-8937-ceb2578f4b4f.png)
![image](https://user-images.githubusercontent.com/70162015/107862553-5853ee80-6e1b-11eb-81ab-fad56f37a7a8.png)

**Browser**
Using desktop client on Ubuntu 20.10.

**Console output**
N/A

**Are you using any scripts?**
No scripts being used.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
