### ISSUE TITLE
Mining Nodes not respawning when returning to game after depleted

### ISSUE THREAD

**Issue by hailrev** [MelvorIdle/melvoridle.github.io#697]
**Describe the bug**
If I'm mining a node and I return to the app and the node is depleted then it will not respawn and the skill text in the menu will not indicate that I am training mining.

**To Reproduce**
1. Start mining a node
2. Close out of and return to the app when the node is depleted
3. The node will not respawn.

**Expected behavior**
The node should respawn on its timer.

**Screenshots**
I have a video of the bug in process and what I have to do to "reset" the node. Please dm me on discord Velhari#0666 

**Browser**
Iphone Xs Max 
Melvor version 0.18.2

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
