### ISSUE TITLE
Confetti Crossbow effect description is inaccurate (V0.18.2)

### ISSUE THREAD

**Issue by Auron956** [MelvorIdle/melvoridle.github.io#698]
**Describe the bug**
The Confetti Crossbow description states that the GP multiplier is "Capped at 250% of damage dealt when you have 50M GP", however this is untrue as the cap of 250% is actually applied when the player has at least 62.5M GP.

**To Reproduce**
1. Equip the Confetti Crossbow with more than 50M & less than 62.5M GP
2. Attack any enemy
3. The amount of additional GP granted by the Confetti Crossbow effect will be between 200% and 250% of damage dealt rather than being capped at 250% as the description states

**Expected behavior**
The cap is either applied at 50M as stated or the description is updated to state the cap applies at 62.5M GP.

**Screenshots**
N/A

**Browser**
Firefox 85.0.2 (64-bit)

**Console output**
N/A

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Fixed in coming update
