### ISSUE TITLE
Gem Gloves, very few gems...

### ISSUE THREAD

**Issue by Moordac** [MelvorIdle/melvoridle.github.io#699]
**Describe the bug**
I purchased three "Gem Gloves" last night and set the game to mine over night. This morning I had only about 65,000gp worth of gems and the gloves were gone.  I purchased another pair this morning and in about 15 minutes I am over 100,000gp worth of gems.

**To Reproduce**
No error Message shown

**Expected behavior**
I expected to have roughly 6,000 Gems by this morning

**Screenshots**
No errors or issues to screenshot

**Browser**
Firefox 85.0.2 (64-bit) (I found that I was not logged into Firefox)

**Console output**
Please open the console by pressing F12 and copy it here.
I was using the steam version.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.
No Scripts

**Comment by Moordac** [comment]
Malcs,
After thinking this through and going over what I was doing at the time, I am pretty sure  I caused it. I was messing around with both my Android and PC version at the same time. Pretty sure I inadvertently over wrote a save going from one to the other. So stand down, this was on me. 

By the way, I am loving the game!!! Never played an idle game before so I am totally new to this. Very cool to say the least!!! Mike

**Comment by MelvorIdle** [comment]
No worries, thanks for the clarification!
