### ISSUE TITLE
Change log divs are nested into each other

### ISSUE THREAD

**Issue by RedSparr0w** [MelvorIdle/melvoridle.github.io#7]
Not sure if this is intended,
But the change log `<div>`s seem to be nested into each other:
![image](https://user-images.githubusercontent.com/7288322/68521596-86d54680-0307-11ea-9903-df135cf7e2bb.png)
![image](https://user-images.githubusercontent.com/7288322/68521628-cdc33c00-0307-11ea-9547-799ccfd59866.png)

Which means they will eventually end up very very small width wise.

**Comment by mrDLSable** [comment]
At the beginning of a version 6 divs are created and 1 is closed. At the end of a version only 4 more are closed.

- The start of the container opens 2
- The title section opens 1 and closes 1
- The date section opens 3

**Comment by MelvorIdle** [comment]
Fixed v0.10
