### ISSUE TITLE
Cannot launch the game

### ISSUE THREAD

**Issue by LordCh33se** [MelvorIdle/melvoridle.github.io#700]
**Describe the bug**
I just bought the game on steam and every time I attempt to play the game it loads forever and displays the screen shown in the screenshot below.

**To Reproduce**
1. Click play on steam
2. The game loads for a long time and nothing ever happens

**Expected behavior**
I expect the game to launch and be playable

**Screenshots**
![image](https://user-images.githubusercontent.com/79074398/107910381-48760080-6f28-11eb-863e-7e7d9a91e033.png)

**Browser**
This is on the steam client

**Console output**
Unable to on console

**Are you using any scripts?**
No scripts

**Comment by MelvorIdle** [comment]
Hey Lord, just want to check in and see if this has been resolved by chance?

**Comment by mararyb87** [comment]
Got the same today with my standard cable internet connection. When I enabled Hotspot Shield VPN game launched fine. Maybe internet provider or router blocks something.
