### ISSUE TITLE
Game Crashes on Startup and does not quit when closed

### ISSUE THREAD

**Issue by walterb123** [MelvorIdle/melvoridle.github.io#701]
**Describe the bug**
Every time i close the game it says that it is still running on steam when i go to its page. Then when I go to task manager and end the task for steam and reopen steam, running the game causes a crash. Other applications on my pc are crashing from this too.

**Comment by mararyb87** [comment]
I'm using Steam version on Windows 7. And currently game can crash
- in a couple seconds after start
- just before showing save list
- at the begining of the save loading
- just after loading
And after that it usually stays in the process list in the task manager.
And the most annoying thing - the game crashes almost every time when I open shop page and sometimes in random moments when I just moving mouse somewhere.
