### ISSUE TITLE
Runic Ruins Magic Evasion debuff being applied while using magic

### ISSUE THREAD

**Issue by AtlitYam** [MelvorIdle/melvoridle.github.io#702]
While training slayer in the Runic Ruins I noticed my Magic Evasion dropping by 30% while using Magic to fight the enemies.
This has been observed while using a variety of weapons, such as Magic Wand (Basic), Staff of Air, Staff of Fire, Fire Battlestaff, Mystic Fire Staff.
A friend of mine has also reproduced this behavior on his account while using a Mystic Air Staff.
I have also discussed this with another player on discord who was unable to see this behavior while using an Ocean Song.

Steps to reproduce:
1. Equip Staff of Air, select a magic spell to use
2. Start fighting enemies in the Runic Runes
3. Watch as the Magic Evasion rating drops when a monster is found

Combat stats and gear:
![image](https://user-images.githubusercontent.com/79282747/108417040-c7707f00-722f-11eb-8b5b-e01f43b51eae.png)
![image](https://user-images.githubusercontent.com/79282747/108417077-d2c3aa80-722f-11eb-9478-94e6592e53dd.png)

**Expected behavior**
As the message for the Runic Runes states, you'd expect the Magic Evasion debuff not being applied while using magic.

**Browser**
Google Chrome, latest

Hopefully this should give enough leads to finding the source of this behavior.

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
