### ISSUE TITLE
Alt. Magic 'Just Learning' breaks skill gloves

### ISSUE THREAD

**Issue by nifsara** [MelvorIdle/melvoridle.github.io#703]
I'm doing a challenge run where inventory space is limited. To save space, I converted my Cooking Gloves into Rune Essence with Just Learning. When I wanted to buy a new pair, it said I already had one in my bank, which I don't. Buying charges added 500, but the gloves are nowhere to be found.

1. Buy skill gloves
2. Convert them into Rune Essence with Just Learning
3. The game thinks you have a pair, even though you don't
4. You can't buy new ones

I expected the game to behave as if the gloves were sold, removed from the bank until you bought them anew.

I'm playing vanilla with the Steam client.

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
