### ISSUE TITLE
Goblin Raid - No Rune Scimitar

### ISSUE THREAD

**Issue by imTURBObro** [MelvorIdle/melvoridle.github.io#706]
Eo I had Javelins equipped and as soon as I ran out I expected to get a bronze scimitar but I ended up dying because I had no weapon.

This has happened to me twice now.

![Screenshot_20210221-171847_Chrome.png](https://user-images.githubusercontent.com/68685674/108642277-c165e280-7469-11eb-931d-6d47c4acca78.png)

**Comment by MelvorIdle** [comment]
Hotfixed pushed to live game. Alpha v0.21 (?1093)
