### ISSUE TITLE
Item Alchemy III offline

### ISSUE THREAD

**Issue by SirAlex419** [MelvorIdle/melvoridle.github.io#710]
**Describe the bug**
Item Alchemy III does not work offline.  After leaving the game with Alchemy active it will record a small bit of progress.  Then when returning, the game says the item does not exist.  I have over 40,000 items to alch...  the item does not disapear, the game just stops alching.

**To Reproduce**
1. Go to 'item alchemy iii’
2. Click on 'dragon javelins’
3. Start aching dragon javelins
4. Leave game
5. Return to game

**Expected behavior**
I expected the game to continue to alch dragon javelins.

**Screenshots**

**Browser**
Iphone 12 mini app

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

**Comment by narrowsoul** [comment]
I am having this issue as well, alching yew longbows (u) on iPhone 8+. It doesn't always give an "item does not exist" error, sometimes when I log back in it just says I gained 0 magic xp while I was gone, but goes right back to alching as soon as I log in.

**Comment by SKukreja** [comment]
I have this issue as well. Dragon Javelins for me too. 

It keeps casting the spell but the item gets de-slotted after about 5000 casts, so it repeatedly says the item does not exist. You have to reselect the item and click Cast again.

**Comment by coolrox95** [comment]
Alt. Magic was rewritten as of v1.0.2.
