### ISSUE TITLE
Typo in levelUpMasteryWithPool

### ISSUE THREAD

**Issue by Slimmmo** [MelvorIdle/melvoridle.github.io#712]
function levelUpMasteryWithPool contains a line

`if (getMasteryLevel(skill, masteryID >= 99)) showSpendMasteryXP(skill);`

it should be

`if (getMasteryLevel(skill, masteryID) >= 99) showSpendMasteryXP(skill);`

Thanks.

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
