### ISSUE TITLE
Herblore IV Offline Potion Bug

### ISSUE THREAD

**Issue by Iveljetorox** [MelvorIdle/melvoridle.github.io#717]
**Describe the bug**

**To Reproduce**
1. Have 89 Mastery in any Herblore Potions
2. Begin making the potion
3. Continue action offline
4. See upon returning to the game after passing 90 Mastery, the lack of IV potions being made (From 90-94 Mastery I only made 2k potions)

**Expected behavior**
Potions should automatically switch to IV and begin making them upon reaching level 90 mastery

**Browser**
Steam

**Are you using any scripts?**
No Scripts are running

**Comment by benw25** [comment]
Known case for offline progression, documented here: https://wiki.melvoridle.com/w/Offline_Progression

> Mastery Experience will be credited when the game is re-opened. Mastery levels will still increase, however the player won't receive the benefits of the new levels until after the game is reopened and the new levels are applied. Whatever action performed during the offline progression will not have any new Mastery Bonuses applied to them.

**Comment by coolrox95** [comment]
This behavior is currently intended. (But may change in the future).
