### ISSUE TITLE
Limit number of ingredients bought in store

### ISSUE THREAD

**Issue by mrDLSable** [MelvorIdle/melvoridle.github.io#72]
This might be controversial, but I think it would be a good idea to limit the rate at which items like feathers and leather can be bought in the shop. I think that players should be encouraged to gather these items themselves and the items in the shop should only be used if the player needs a few of the item for a specific task.

Perhaps a limit like 250 per day would be enough.

**Comment by MelvorIdle** [comment]
I haven't actually thought about this, and its a good idea.

Maybe instead of limiting the buy amount, I can implement a formula to increase the price every X purchases. This resets on a daily basis.

**Comment by mrDLSable** [comment]
that's a good idea.
