### ISSUE TITLE
Offline progression not happening randomly

### ISSUE THREAD

**Issue by tomsaee** [MelvorIdle/melvoridle.github.io#720]
**Describe the bug**
This has happened to me twice now. Last night I left my account fishing whales. Next morning I opened the game and the offline progression thing said ”You were gone for roughly 0 minutes” and didn’t get anything. Although I was gone for 10 hours.

Same thing hour after. 

**To Reproduce**
I don’t know what produces this bug. I installed iOS 14.5 DB3 before going to bed, so it might be related to that but why? None of the betas I’ve used before haven’t affected and I’ve been using betas for years now.

**Expected behavior**
I expected to get thousands of whales after my well rested night which I could sell and be financially independent.

**Screenshots**
I have no screenshot of it and it wouldn’t tell anything as it’s like normal welcoming back screen but with 0 minutes and no stuff gathered.

**Browser**
iPhone 8, iOS 14.5 Developer Beta 3

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
No

**Comment by Amnon1982** [comment]
This also happens to me. I’ve experienced this at lease a dozen times and seems more common with mining, though it has happened with other skills as well. 

It seems tied to having the app open in the background and when I jump back to the app after a few hours it refreshes, takes me to the home page, and says “you were gone roughly 0 minutes” thereby losing all progression.
