### ISSUE TITLE
When all plots are full you can still click plant all and be charged for planting crops

### ISSUE THREAD

**Issue by NFodrea** [MelvorIdle/melvoridle.github.io#721]
**Describe the bug**
When farming if you have all allotments full you can click plant all. The modal still appears and if you go through the process you are charged the gold, however the seeds are not used.

**Expected behavior**
The button to plant all should be disabled when there are no available allotments

**Screenshots**

**Browser**
Firefox 86.0

**Are you using any scripts?**
No

**Comment by NFodrea** [comment]
This still occurs in  0.19

**Comment by MelvorIdle** [comment]
Fixes applied to game - Alpha v0.21 (?1119)
