### ISSUE TITLE
Number of charges for gloves no longer appears in shop interface

### ISSUE THREAD

**Issue by kyldvs** [MelvorIdle/melvoridle.github.io#724]
**Describe the bug**
Before v0.19 update the number of charges gloves had appeared in the shop UI. That information no longer appears in the shop UI.

**To Reproduce**
1. Go to 'shop ui'
2. Click on 'gloves'
3. See error

**Expected behavior**
The shop UI should show the existing number of charges you own for each pair of gloves.

**Screenshots**

![image](https://user-images.githubusercontent.com/1830497/110066444-500a1780-7d26-11eb-91b2-acddd4b72a80.png)

**Browser**
Steam

**Console output**
(F12 didn't open console, let me know if you need more info)

**Are you using any scripts?**
No

**Comment by kaboom3r** [comment]
Yes, I have the same issue too.
Number of charges no longer shown in Shop. I remember seeing it earlier in v0.18.
When v0.19 came out and I updated my game, the number of charges can no longer be seen.

**Comment by kyldvs** [comment]
This has been resolved
