### ISSUE TITLE
Hitpoints and Thieving not displaying properly in 0.19

### ISSUE THREAD

**Issue by Derkeagle** [MelvorIdle/melvoridle.github.io#725]
**Describe the bug**
The thieving and hitpoints displays in the sidebar use 2 lines rather than the 1 line they are supposed to use.

**Expected behavior**
I expected the hitpoints and thieving displays to use 1 line instead of 2, like previous

**Screenshots**
![image](https://user-images.githubusercontent.com/80085076/110066645-9156f300-7d37-11eb-8c6e-4465ec58385d.png)

**Browser**
Please tell us what browser you are using and what version.
Steam, most recent

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.
No

**Comment by MelvorIdle** [comment]
Has this been fixed now by refreshing / reloading the game?
