### ISSUE TITLE
Agility obstacles are carrying over to other characters.

### ISSUE THREAD

**Issue by JamieDriveCentric** [MelvorIdle/melvoridle.github.io#726]
**Describe the bug**
Seems like agility obstacles are account bound :) 
I went to start agility on my 2nd character (reached level 30 on my main) and the second character had the first character's obstacles available. They were also usable by character 2 even though it was level 1.

**To Reproduce**
1. Unlock multiple obstacles on a normal character
2. Log into character 2 that hasn't touched agility yet
3. Go to agility skill
4. Observe

**Expected behavior**
character 2 starts at level 1 agility, fresh skill

**Screenshots**
![image](https://user-images.githubusercontent.com/41797578/110070359-d08d4000-7d47-11eb-8038-92428357ee8a.png)

**Browser**
Steam .exe

**Console output**
Not sure console is relevant here

**Are you using any scripts?**
No

**Comment by JamieDriveCentric** [comment]
@TheMalcs hit me up on discord if you need further clarification on reproduction.

KingQuickDraw#6083

**Comment by MelvorIdle** [comment]
I believe this has been fixed now temporarily with the Adventure Mode bug fix.
