### ISSUE TITLE
Green background on Agility skill is very similar to green text of active passives

### ISSUE THREAD

**Issue by RansomTime** [MelvorIdle/melvoridle.github.io#730]
**Describe the bug**
The green background of the active course Agility skill is very similar to green text of the active passives, making it very hard to read the current course' effects.

**To Reproduce**
1. Go to Agility
2. Start a course with at least one Globally active passive obstacle
3. Wait until that obstacle becomes the active obstacle

**Expected behaviour**
The text changes colour to be readable on the background, or the text/background's colour is different to begin with to allow users to read the passive without pausing the skill.

**Screenshots**
![image](https://user-images.githubusercontent.com/47819665/110110683-1c230680-7da7-11eb-9c51-8fb0a1e0d4d6.png)

**Browser**
Firefox 85.0.2

**Console output**
I don't believe this is relevant. Can copy/paste in a reply if it is

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Working on an update to address this.

**Comment by coolrox95** [comment]
Issue was resolved sometime between this report and Alpha v0.21, Active agility obstacles in light mode have a blue background instead of green.
