### ISSUE TITLE
Agility: Cliff balance impact on prayers 

### ISSUE THREAD

**Issue by tjoyal** [MelvorIdle/melvoridle.github.io#732]
**Describe the bug**

- Agility "Cliff balance" (rank 5)
- Description is "-2 Flat Prayer Cost Reduction" in **red**
- ~~Prayers UI apply it as -2 making it a buff which should be **green** instead of **red**?~~
- ~~Does not seems right as it would not make it an obstacle very balanced (should be +2)?~~
- ~~Tested briefly, still cost original prayer cost to activate said prayer.~~

Looks like I should have read the update notes more carefully:
> [CHANGE] Stone Skin Prayer now provides +3% Damage Reduction, down from +5%
> [CHANGE] Stone Skin now costs 3 Prayer Points per enemy Attack, up from 2

So it "works as expected", except that the prayer selection UI does not reflect it. If this is working as expected, then lets close this 😓 .

<img width="802" alt="Screen Shot 2021-03-05 at 12 11 21 PM" src="https://user-images.githubusercontent.com/207902/110149405-049a4c80-7dac-11eb-96be-fd29ebf72008.png">
<img width="510" alt="Screen Shot 2021-03-05 at 12 11 30 PM" src="https://user-images.githubusercontent.com/207902/110149412-05cb7980-7dac-11eb-82e5-030dd9a52867.png">
<img width="175" alt="Screen Shot 2021-03-05 at 12 11 46 PM" src="https://user-images.githubusercontent.com/207902/110149414-06641000-7dac-11eb-9e11-09c8f473a714.png">

**Expected behavior**
TBD. 

Probably to affect cost of prayer as an increase and to be reflected in both UI and activation cost

**Screenshots**

**Browser**
Chrome latest (88.0.4324.190)

**Console output**
N/A

**Are you using any scripts?**
None (Native)

**Comment by MelvorIdle** [comment]
This has been hotfixed
