### ISSUE TITLE
Gem Gloves Magically Missing - Even after Re-buy from Shop

### ISSUE THREAD

**Issue by kaboom3r** [MelvorIdle/melvoridle.github.io#733]
**Describe the bug**
I used to have Gem Gloves, but it magically disappeared from my bank overnight.
No problem, I go to Shop, buy some more, Shop says Gem Gloves [In Bank] and I have around 100k charges.
I click on the mini Gem Glove item in the Mining page to equip and I get the message [There's no Gem Gloves in your bank *shrug*].
I go to my Bank to manually look for it and it isn't there, I can't find it. I use the search function and still can't find it. Gem Gloves have magically disappeared from my bank. I manually checked all my tabs too. Also manually check for every item bank says I have, 174/210, so my Gem Gloves magically disappeared.
I go back to Shop to buy some more Gem Gloves and it keeps saying I already have it in bank, and that my charges keep on increasing, but I don't see any Gem Gloves!
Game is just as confused as I am as to whether I have Gem Gloves or not.
No, I did not accidentally or intentionally sell my Gem Gloves.
Already tried refreshing/restarting app. I play on both PC + app.
Happened overnight, next morning I realized when I was mining, I'm not getting Gems, thought I was being silly and forgot to press the Gem Glove icon to equip.
I tried to report the bug but there's no in-game bug report feature.
With the new Alpha v0.19 update, the Shop no longer indicates whether gloves are in the bank or not.

**To Reproduce**
1. Go to Mining page
2. Click on Gem Gloves Icon
3. See error: There's no Gem Gloves in your bank *shrug*
4. Go to shop, re-buy Gem Gloves, paid money for it, and still no gloves. v0.18, it says [In Bank], now I can't tell in v0.19

**Expected behavior**
I should see and be able to use Gem Gloves which I paid a lot of money for (like 100k charges)

**Screenshots**
![image](https://user-images.githubusercontent.com/80115950/110139866-773c1400-7e0e-11eb-88ca-49b23ab70503.png)

**Browser**
I play on both app + browser (Win10, Chrome, most updated)

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
No.

Recommendation
Gem Gloves should not be an actual item, it should be an automatic built-in bonus, similar to the Cooking Fire "upgrades". So everyone starts out with Gem Gloves (built-in, also doesn't take up bank slot), 0 charges, buy charges at Shop. It will also help prevent unnecessary glitches.

**Comment by Alci8** [comment]
check other loadouts. If gloves are equipped in other then active loadout it will behave exactly as you've described (having them already when purchasing charges, but unavailable when you try to wear them)

**Comment by kaboom3r** [comment]
> check other loadouts. If gloves are equipped in other then active loadout it will behave exactly as you've described (having them already when purchasing charges, but unavailable when you try to wear them)

Not in other loadouts. Checked.
