### ISSUE TITLE
Problem with the Exp Skill progress

### ISSUE THREAD

**Issue by Nickbedard** [MelvorIdle/melvoridle.github.io#735]
When i'm in combat and I click the eye to toggle skill progress, all my level 99 shows like it's 99 % complete and some of these even show less, like if the EXP needed to be level 99 increased or something. I don't have Virtual level On.

**To Reproduce**
1. Go to Combat
2. Click on the eye

**Expected behavior**
I think when you're 99/99, you should be at 100 % and all the progress bars should be green

**Screenshots**
![image](https://user-images.githubusercontent.com/80121391/110152144-58f2fb80-7daf-11eb-9383-c42b132222bd.png)

**Browser**
I'm using your game from steam

**Console output**
I couldn't get it out unfortunately.

**Are you using any scripts?**
None, this is the game from steam

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
