### ISSUE TITLE
Golbin Raid

### ISSUE THREAD

**Issue by MeltSC** [MelvorIdle/melvoridle.github.io#736]
**Describe the bug**
Specials carrying over to the bronze scimitar in Golbin Raid.

**To Reproduce**
1. Get a special weapon (did this with ocean song)
2. Don't have enough runes to cast a spell, gives you bronze scimitar
3. Bronze scimitar now has ocean song special.

**Expected behavior**
Bronze scimitar gets specials of weapons that use ammunition when you lack said ammunition.

**Screenshots**

**Browser**
Google Chrome

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
No.

**Comment by coolrox95** [comment]
Fixed with update v0.21
