### ISSUE TITLE
stopped gaining fishing xp in adventure mode

### ISSUE THREAD

**Issue by icedragons88** [MelvorIdle/melvoridle.github.io#737]
Im doing fishing and my xp gain has stopped at lvl 33 1 point before 34
![Screenshot (1)](https://user-images.githubusercontent.com/80129775/110175979-55fb1800-7e4e-11eb-90bf-48beda634f7d.png)

**Comment by coolrox95** [comment]
Not a bug. Adventure mode caps the level of non-combat skills to your combat level.

**Comment by MrSapient** [comment]
https://i.imgur.com/eE90XN7.png

**Comment by icedragons88** [comment]
ah right sorry i forgot about that
