### ISSUE TITLE
Low: Some enemySpecialAttacks have duplicate properties

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#740]
**Describe the bug**
In combat.js the following enemy special attacks have duplicate property names. This does not currently cause any issues, but may result in future bugs if the values of these properties need to be changed.
Attack| Duplicate Property | Notes
---- | ------------------- | -----
Hunter Expertise | `activeBuffs`| Duplicates Conflict: Should be `true`
Agility | `activeBuffs`| Duplicates Conflict: Should be `true`
Elusiveness | `activeBuffs`| Duplicates Conflict: Should be `true`
Burning Trail | `activeBuffs`| Duplicates Conflict: Should be `true`
Shadowstep | `activeBuffs`| Duplicates Conflict: Should be `true`
Shadow Burst | `activeBuffs`|
Fallen Light | `activeBuffs`|

**Browser**
Browser Agnostic Bug

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Fixed in upcoming hotfix release
