### ISSUE TITLE
Low: Some playerSpecialAttacks have duplicate properties

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#741]
**Describe the bug**
In combat.js the following player special attacks have duplicate property names. This does not currently cause any issues, but may result in future bugs if the values of these properties need to be changed.
Attack| Duplicate Property | Notes
---- | ------------------- | -----
Tidal Wave | `stunDamageMultiplier`|
Ocean Song| `stunDamageMultiplier`|

**Browser**
Browser Agnostic Bug

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Fixed in upcoming hotfix release
