### ISSUE TITLE
Low: combatPassive "Swing First" has duplicate property

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#742]
**Describe the bug**
In combat.js the following combatPassive has a  duplicate property name. This does not currently cause any issues, but may result in future bugs if the value of this property need to be changed.
Combat Passive| Duplicate Property | Notes
---- | ------------------- | -----
Swing First | `description`|

**Browser**
Browser Agnostic Bug

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Fixed in upcoming hotfix update
