### ISSUE TITLE
Adventure Mode - Force save/Reload corrupted save

### ISSUE THREAD

**Issue by LexLeach** [MelvorIdle/melvoridle.github.io#744]
**Describe the bug**
Last night there was an announcement for Cloud saves that said to force save and refresh. I was sleep so I waiting till morning to do it. Now after I force saved and reloaded the save itself is saying I'm total level 43, but when I click the save it says total level 6. I lost all my trained skills for combat, and 2 unlocked skills cooking and fishing. 

**To Reproduce**
1. Go to 'Force save'
2. Click on 'Force Save'

**Expected behavior**
The changes that happened over night to be saved. 
**Screenshots**
![image](https://user-images.githubusercontent.com/55722511/110189186-4945d800-7dec-11eb-9b6c-e99571d6289d.png)
![image](https://user-images.githubusercontent.com/55722511/110189210-55ca3080-7dec-11eb-9807-c78e0b3036d9.png)

**Browser**
Please tell us what browser you are using and what version.

**Console output**
Please open the console by pressing F12 and copy it here.
![image](https://user-images.githubusercontent.com/55722511/110189259-814d1b00-7dec-11eb-922f-10ebac0ae1fb.png)

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.
No I'm not even sure what this means

**Comment by LexLeach** [comment]
After I turned off AdBlock this happened right when an announcement popped.
![image](https://user-images.githubusercontent.com/55722511/110189412-fe789000-7dec-11eb-9d4c-cc5ce3ebca23.png)

**Comment by MelvorIdle** [comment]
You're looking at and comparing the wrong levels.

Your TOTAL LEVEL is 43, but your COMBAT LEVEL is 6. These are different stats.

**Comment by LexLeach** [comment]
Yea but when I went to bed last night my atk was 38, streagth 14, def 34, hp 36, had cooking and fishing unlocked and now none of them are there. Is all been wiped. Why...

**Comment by MelvorIdle** [comment]
Sorry... your bug report focused on the total level component of the screenshots and didn't mention anything about losing those specific levels.

**Comment by LexLeach** [comment]
Sorry that my fault, I guess I should also mention when I down the save and import it, it changes to normal mode and says I was woodcutting.
