### ISSUE TITLE
Herblore Action Interrupted By Spending Mastery

### ISSUE THREAD

**Issue by breadbocks** [MelvorIdle/melvoridle.github.io#745]
**Describe the bug**
Herblore gets interrupted if you spend mastery pool on the action you're doing, would be cool if it didn't. Might be true for other skills, or might be unique to herblore because of potion tiers.

**To Reproduce**
1. Begin doing action in herblore
2. Spend mastery pool on the current action
3. Observe that you're no longer making that potion

**Expected behavior**
You keep making that potion
**Screenshots**

**Browser**
Please tell us what browser you are using and what version.

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

**Comment by coolrox95** [comment]
I cannot reproduce this issue using the provided steps on the current version of the game (Alpha v0.22.1).
