### ISSUE TITLE
Low: Several functions unintentionally create globally scoped variables

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#746]
**Describe the bug**
A number of the game's functions create global variables due to missing let/const statements. Some of them are completely unused and may also be removed.

File | Function | Invalid Code | Fixed Code | Notes
-- | -- | -- | -- | --
bank.js | `updateSellRangeSlider` | ` selectedBankID = getBankId(selectedBankItem);`| `const selectedBankID = getBankId(selectedBankItem);`
combat.js|`attackPlayer`|`setDOTDamage = enemySpecialAttacks[specID].setDOTDamage;`|| Unused variable, can be removed.
combat.js|`updatePlayerChanceToHit`|`let enemyDefenceRoll`|`let enemyDefenceRoll, playerAccuracy;`| playerAccuracy needs to be declared before if statement.
combat.js|`togglePrayer`|`notifyPlayer(CONSTANTS.skill.Prayer, "You don't have enough Prayer Points", (type = 'danger'));`|`notifyPlayer(CONSTANTS.skill.Prayer, "You don't have enough Prayer Points", 'danger');`
combat.js|`togglePrayer`|`notifyPlayer(CONSTANTS.skill.Prayer, 'You can only have a max of 2 Prayers active simultaneously', (type = 'danger'));`|`notifyPlayer(CONSTANTS.skill.Prayer, 'You can only have a max of 2 Prayers active simultaneously', 'danger');`
cooking.js|`startCooking`|`cookingInterval = calculateSkillInterval(`|`const cookingInterval = calculateSkillInterval(`
farming.js|`addCompost`|`compostQty = 5;`|`let compostQty = 5;`
golbinraid.js|`updateGolbinRaid`|`showEquipmentSelection((init = true), (category = 0));`|`showEquipmentSelection(true, 0);`
magic.js|`selectItemForMagic`|`let itemProduce, itemProduceCurrent, itemProduceName, itemRequiredName;`|`let itemProduce, itemProduceCurrent, itemProduceName, itemRequiredName, itemQtyCurrent;`
magic.js|`selectItemForMagic`|`let itemProduce, itemProduceCurrent, itemProduceName;`|`let itemProduce, itemProduceCurrent, itemProduceName, itemQtyCurrent;`| Found in 2 places in this function.
magic.js|`selectItemForMagic`|`itemQty = getItemQty(items[selectedMagicItem[0]].smithReq[i].id);`|`const itemQty = getItemQty(items[selectedMagicItem[0]].smithReq[i].id);`| Found in 2 places in this function.
magic.js|`selectItemForMagic`|`itemQty = getItemQty(selectedMagicItem[1]);`|`const itemQty = getItemQty(selectedMagicItem[1]);`
main.js|`updateOffline`|`totalBaseActions = 0;`|`let totalBaseActions = 0;`|Part of the woodcutting case, was this variable mixed up with `baseTotalActions`?
main.js|`updateOffline`|`birdNest = true;`||Unused variable, can be removed.
main.js|`generateGaussianNumber`|`$randNumA = Math.random();`|`const $randNumA = Math.random();`
main.js|`generateGaussianNumber`|`$randNumB = Math.random();`|`const $randNumB = Math.random();`
main.js|`generateGaussianNumber`|`$randNumNorm =...`|`const $randNumNorm =...`
mastery2.js|`populateMasteryObject`|`masteryConverted = true;`||Unused variable, can be removed.
save.js|`resetVariablesToDefault`|`fishingArea = fishingArea = [...];`||Unused variable, can be removed. May also be deleted from save files, as this is from pre-fishing rework.
save.js|`resetVariablesToDefault`|`showSkillNav = true;`||Unused variable, can be removed. May also be deleted from save files.
herblore.js|`loadHerblore`|`tooltip = "<small class='text-warning'>Requires:</small><br>";`|`let tooltip = "<small class='text-warning'>Requires:</small><br>";`
stats.js|`openPetLog`|`let tooltop;`|`let tooltip;`|Typoed variable name
woodcutting.js|`updateWCMilestone`|`nextMilestone = 0;`|`let nextMilestone = 0;`
woodcutting.js|`updateWCMilestone`|`milestoneMessage=...`||Unused variable, can be removed.
smithing2.js|`var smithingReqCheck = [];`|`var smithReqCheck = [];`||This is a typo

In addition to these there are a large number of loops using the iterator `i` that are missing their `let` statement.

File | Function | Invalid Code | Fixed Code | Notes
-- | -- | -- | -- | --
combat.js|`loadEquippedFood`|`for (i = 0; i < 3; i++) {`|`for (let i = 0; i < 3; i++) {`
combat.js|`equipFood`|`for (i = 0; i < 3; i++) {`|`for (let i = 0; i < 3; i++) {` | Found twice in this function
combat.js|`loadDungeons`|`for (i = 0; i < DUNGEONS.length; i++) {` | `for (let i = 0; i < DUNGEONS.length; i++) {`
cooking.js|`updateAvailableFood`|`for (i = 0; i < bank.length; i++) {`|`for (let i = 0; i < bank.length; i++) {`
firemaking.js|`checkLogExists`|`for (i = 0; i < bank.length; i++) {`|`for (let i = 0; i < bank.length; i++) {`|This one could probably be replaced with one of the bank functions
woodcutting.js|`updateWCMilestone`|`for (i = 0; i < trees.length; i++) {`|`for (let i = 0; i < trees.length; i++) {`

If you fix all of those errors, there will also be some bugs introduced in `selectCraft`. some sections of jquery seem to append some elements with id: `id="craft-item-produce-' + i` and `id="craft-item-produce-xp-' + i`.
This will also impact `selectFletch` which has a similar issue with `id="fletch-item-produce-' + i`, `#fletch-item-produce-xp- + i`
And `selectHerblore` with `id="herblore-item-produce-img-' + i`, `id="herblore-item-produce-current-img-' + i`, `#herblore-item-produce-img-' + i`, `'#herblore-item-produce-current-img-' + i`, `'#herblore-item-produce-xp-' + i`,
And `selectSmith` with `id="smith-item-produce-' + i`, `id="smith-item-produce-xp-' + i`,`'#smith-item-produce-' + i`,`'#smith-item-produce-xp-' + i`
These functions currently use whatever value i was set by the last loop that ran.

**Browser**
Browser agnostic bug.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
