### ISSUE TITLE
Browser - Cloud Saves - Settings button unclickable

### ISSUE THREAD

**Issue by Luunae** [MelvorIdle/melvoridle.github.io#747]
**Describe the bug**
In the character select/cloud saves page of the browser, the settings button to the right of each save does nothing when clicked. The mouse does not change to indicate that this is clickable.

**To Reproduce**
1. Go to the Character selection page.
2. Click "Show Cloud Saves"
3. [Mouse over/click] the "Settings" button to the right of an existing character slot.
4. Nothing happens to indicate this is a clickable button.

**Expected behavior**
On mouseover, the standard pointer mouse cursor should change to a hand to indicate this is clickable.  On click it should open the Save Settings dialogue box with the options of Download Save, Export Save, Import Save, and Delete Save.

**Browser**
Applies on Firefox 86.0 and Chrome 89.0.4389.82 

**Console output**
Object { skill: null, action: null, timestamp: null }
main.js:248:426
Object { skill: null, action: null, timestamp: null }
main.js:248:426
Object { skill: null, action: null, timestamp: null }
main.js:248:426
Object { skill: null, action: null, timestamp: null }
main.js:248:426

**Are you using any scripts?**
No scripts are being used on either browser.

**Comment by MelvorIdle** [comment]
This is intended as the settings are currently only implemented for Local Saves.

Once that button is enabled, it will work for Cloud
