### ISSUE TITLE
No "favicon" on Firefox

### ISSUE THREAD

**Issue by FLKone** [MelvorIdle/melvoridle.github.io#748]
**Describe the bug**
When running the web version of the game on firefox, the tab or pinned tab doesn't have a favicon, displaying a bland black and white globe instead of the glorious red M logo of the game.

**To Reproduce**
1. Go to 'https://melvoridle.com' on Firefox (v86.0 64 bits)
2. See no favicon. When pinned no favicon either

**Expected behavior**
Having a favicon like on Chrome or Edge

**Screenshots**
![melvorfavicon](https://user-images.githubusercontent.com/484397/110204178-2100bc80-7e72-11eb-8a1e-da60801402b3.png)

**Browser**
Firefox (v86.0 64 bits)

**Console output**
n/a

**Are you using any scripts?**
n/a

**Comment by coolrox95** [comment]
Fixed with update v0.21.
