### ISSUE TITLE
Achievement System

### ISSUE THREAD

**Issue by Eusmusia** [MelvorIdle/melvoridle.github.io#75]
Adding an Achievement system could be beneficial. 

Achievements would be progression and incremental.

Achievements would be broken down to Tiers, ranging from 1 to 5, 1 being the lowest and easiest to accomplish, while 5 would be the hardest, most time consuming achievements. These achievements would range from "Burn 200 normal logs" to "Burn 10,000 Magic Logs" based on progression. Rewards would be based on a number of different factors such as: A. Difficulty, B. Time, and C. Progression. Achievement 1 wants us to chop 500 normal logs. This would be a Tier 1 Achievement, while Achievement 8 wants us to chop 10,000 Magic Logs would be a Tier 5 Achievement. 

Rewards would be standardized from a loot pool, much like chests but various rare and unique rewards would be obtainable from these Achievement Chests, with harder achievements granted more rolls for loot, larger loot pools and better chances for unique rewards.

After each completed achievement in a category, it would increase. Going back to Achievement 1 with "Chop 500 normal logs," after that achievement has been completed, it would go up to "Chop 1000 Normal Logs" and so on and so forth. 

These achievements would show up under Statistics with a Total AS (Achievement Score) and could possibly be used for future updates.

Achievements would be located on the left panel near the bottom where Settings, Mastery, etc are currently located.

**Comment by mrDLSable** [comment]
Is this something you feel would still be relevant given the completion log?

**Comment by Eusmusia** [comment]
Possibly because Achievements are different. Completion log shows things you've collected or unlocked. Achievements are for things such as "Kill 500 Bandits."

**Comment by mrDLSable** [comment]
Very true.
