### ISSUE TITLE
Unintuitive Fletching/Crafting Interval calculation

### ISSUE THREAD

**Issue by iang2** [MelvorIdle/melvoridle.github.io#751]
**Describe the bug**
Action time reduction bonuses with the same descriptive text applies different bonuses.
The Mastery Pool action time reduction for Fletching applies BEFORE Perpetual Haste god upgrade percentage based time reduction, and the action time reduction bonus from Quill the Fletching pet applies AFTER Perpetual Haste god upgrade reduction.  This results in the Mastery Pool effect only resulting in an action time reduction of 0.17s after purchasing Perpetual Hate, not 0.2s as described.

**To Reproduce**
1. Have Perpetual Haste, Quill, and the 95% pool bonus from Fletching.
2. Go to the Fletching tab
3. View the action time display.
4. It is 1.33 seconds.  If the 0.2s action time reduction bonuses behaved consistently, this would be either 1.36s or 1.3s.

![fletching](https://user-images.githubusercontent.com/16178422/110210311-ae361800-7e56-11eb-92fa-c548c78d7001.PNG)

In the switch statement in the calculateSkillInterval function in main.js, the intervals for Fletching & Crafting are updated directly instead of acting  on the decreasedSkillInterval variable.

![calculateSkillInterval](https://user-images.githubusercontent.com/16178422/110210500-90b57e00-7e57-11eb-9075-b422624fce7f.PNG)

**Comment by MelvorIdle** [comment]
Fixed and corrected in upcoming update to be more consistent
