### ISSUE TITLE
fast weapons from golbin raid 

### ISSUE THREAD

**Issue by rhysdog1** [MelvorIdle/melvoridle.github.io#752]
**Describe the bug**
all weapons in golbin raid attacking extremely fast
**To Reproduce**
turn on "use combination runes", obtain a cloudburst staff , it attempts to use a combination rune which immediately fails and replaces the staff with a bronze scimitar, now that scimitar and any replacement weapons will  take around .1 seconds to use, with magic weapons draining runes even faster than you attack

**Expected behaviour**
bar fill up before sword go whack
**Screenshots**

**Browser**
Chrome
**Console output**

**Are you using any scripts?**
No 

extra details: changing weapons does not fix, equipping or removing gear that changes attack interval does not fix, swapping on and off rapid for range weapons does not fix, fleeing or dying does not fix, and it continues to work outside the raid. it does not make any non combat skills happen quicker. when using ranged weapons ammo seems to go down 2 at a time, and will go down between waves. when using magic, runes will deplete faster than ranged weapons, and attempting to use a curse without the necessary runes will cause the popup telling me I don't have the runes to be spammed extremely fast. the bar does not fill up faster, the attacks will just happen before the bar fills up, and will reset the bar. refreshing does fix the issue.

attempting to replicate the issue was unreliable, but did succeed, however was a lot less impactful than when first experienced, and often stopped occurring after the first golbin was killed. 

at my best guess, i have multiple invisible bars of weapons attacking, possibly my long play session is related to why after refreshing my successful attempts were still weaker.

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
