### ISSUE TITLE
Circlet of Rhaelyx cannot be obtained from online Agility training (V0.19)

### ISSUE THREAD

**Issue by Auron956** [MelvorIdle/melvoridle.github.io#754]
**Describe the bug**
Currently the `rollForRhaelyx()` function does not include Agility as a circlet skill, therefore it is currently not possible to obtain the Circlet of Rhaelyx (or any Mysterious Stones) while training Agility online.

**Expected behavior**
Agility is able to drop circlets when trained online.

**Browser**
Issue is browser independent.

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
