### ISSUE TITLE
Playing goblin raid will lock paryers

### ISSUE THREAD

**Issue by Youmod** [MelvorIdle/melvoridle.github.io#756]
Only the first thick skin prayer is available after playing goblin raid.

**To Reproduce**
1. Go to goblin raid minigame.
2.  Play the game
3. Start the raid
4. Run from the raid
5. Go to combat
6. Only thick skin prayer is available even though prayer level is high.

**Expected behavior**
At prayer level 107 all prayers should be available after playing goblin raid.
**Screenshots**
![Sieppaa](https://user-images.githubusercontent.com/80174112/110218730-f9d2db00-7ec3-11eb-898e-f92071297c4b.PNG)

**Browser**
Please tell us what browser you are using and what version.
Steam
**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.
No

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
