### ISSUE TITLE
Golbin Raid Double Alt Special

### ISSUE THREAD

**Issue by KnKravlegard** [MelvorIdle/melvoridle.github.io#759]
**Describe the bug**
Got Sandstorm Ring (ALT) which gave me a Sandstorm special attack on my weapon.
Later i got a Ocean Song Weapon. But i Instantly lost it because i had no runes to cast spells. 
Which gave me a bronze Scimitar.
BUT! I now had both Sandstorm AND Ocean song Special attack on my Bronze Scimitar. 
I assume it has something to do with the Sandstorm ring making sure to not clear my special attack when i swap weapon or something. 
This bug made so i had a 1.2s attackspeed melee weapon that had Ocean song. 
http://prntscr.com/10esulf

**To Reproduce**
1. Start Golbin raid
2. Get Sandstorm Ring (ALT) (It has the original Sandstorm ring special attack)
3. Get Ocean Song (Have no runes so you lose it instantly (PleaseFix))
4. Have Scimitar with both special attacks

**Expected behavior**
Expected it to not have the Ocean song special attack. 

**Screenshots**
http://prntscr.com/10esulf

**Browser**
Chrome

**Console output**
Not a error message

**Are you using any scripts?**
Using the Combat Simulator only.

**Comment by coolrox95** [comment]
Fixed with update v0.21.
