### ISSUE TITLE
Show the amount of runes of the type you have a staff for equipped

### ISSUE THREAD

**Issue by mrDLSable** [MelvorIdle/melvoridle.github.io#76]
Currently the amount of runes of the type you have a staff of equipped is not shown. It would be good to show the amount (perhaps in a mouseover tooltip) for ease of use. I have just had to switch back a couple of times between my bank and the combat screen to see if I should switch my equipped staff and that checking should all be done in the combat window.

**Comment by MelvorIdle** [comment]
Don't you like the happy rune :(

**Comment by PegasusEpsilon** [comment]
@MelvorIdle The happy rune is nice, but info is better.

This could relatively easily be implemented as a userscript, but having it in the base game (as a configurable option, maybe?) would be nifty.
