### ISSUE TITLE
Minor: modifiers "increasedRangedEvasion" and "increasedMagicEvasion" and their decreased counterparts not implemented

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#760]
**Describe the bug**
The modifiers `increasedRangedEvasion` and `increasedMagicEvasion` are currently not implemented. This breaks any of the subsystems of the game that provide this bonus (e.g. Prayer, Pets)

**To Reproduce**
1. Activate a prayer that has one of those modifiers (e.g. Mystic Lore)
2. Note that the player evasion ratings do not change.

**Root of problem**
In combat.js `calculatePlayerEvasionRating` was updated to use `increasedMeleeEvasion` and `decreasedMeleeEvasion`. But was not updated for the aforementioned modifiers.

**Browser**
Browser agnostic bug.

**Are you using any scripts?**
No,

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
