### ISSUE TITLE
Minor: Modifiers increasedMaxHitPercent, decreasedMaxHitPercent, increasedMaxHitFlat and decreasedMaxHitFlat not implemented

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#762]
**Describe the bug**
As per the title these modifiers are not currently implemented in game. I could not find references to them in the source code.
The Pet "Ren" has the modifier `increasedMaxHitPercent`, which currently does nothing if you unlock it.
![image](https://user-images.githubusercontent.com/58208131/110224479-29b8b900-7e99-11eb-8af7-0dd084f70f55.png)

**Expected behavior**
`increasedMaxHitPercent`, `increasedMaxHitFlat`, `decreasedMaxHitFlat` and `decreasedMaxHitPercent` should be applied to `baseMaxHit` in the function `calculatePlayerMaxHit` in combat.js

**Browser**
Browser agnostic bug.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update

**Comment by gmiclotte** [comment]
Looks like the fix in `calculatePlayerMaxHit` is commented out?

**Comment by MelvorIdle** [comment]
> Looks like the fix in `calculatePlayerMaxHit` is commented out? Or is it still upcoming, been a few updates since you commented that, but idk.

This fix broke the game due to not being implemented correctly by me.

Reopened until fixed again

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
