### ISSUE TITLE
Minor: Modifiers `increasedHiddenSkillLevel` and `decreasedHiddenSkillLevel` have some implementation issues

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#764]
**Describe the bug**
The modifiers `increasedHiddenSkillLevel` and `decreasedHiddenSkillLevel` have some implementation problems as follows:

**`decreasedHiddenSkillLevel` is calculated wrong in `getSkillHiddenLevels` in combat.js**
```js
function getSkillHiddenLevels(skill) {
  let hiddenLevels = 0;
  for (let i = 0; i < playerModifiers.increasedHiddenSkillLevel.length; i++) {
    if (playerModifiers.increasedHiddenSkillLevel[i].id === skill)
      hiddenLevels += playerModifiers.increasedHiddenSkillLevel[i].value;
  }
  for (let i = 0; i < playerModifiers.decreasedHiddenSkillLevel.length; i++) {
    if (playerModifiers.decreasedHiddenSkillLevel[i].id === skill)
      hiddenLevels -= playerModifiers.increasedHiddenSkillLevel[i].value; // This is a typo, it should be decreasedHiddenSkillLevel not increasedHiddenSkillLevel
  }
  return hiddenLevels;
}
```
**`getSkillHiddenLevels` is not used for computing combat stats in the following circumstances**
1. Hidden Defence levels are not applied to Melee, Ranged or Magic Evasion. This requires changes to `calculatePlayerEvasionRating` in combat.js
2. Hidden Magic levels are not applied to Magic Evasion. This requires changes to `calculatePlayerEvasionRating` in combat.js
3. Hidden Magic levels are not applied to Standard Spell Max Hits. This requires changes to `calculatePlayerMaxHit` in combat.js

**Note:** These issues currently don't impact the game as they are not used in the bugged cases, but may cause issues in future 
updates.

**Browser**
Browser agnostic bug.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
