### ISSUE TITLE
Low: Modifier `increasedGPFromSales` and `decreasedGPFromSales` not represented in sale prices in UI

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#765]
**Describe the bug**
This is a purely visual bug. `increasedGPFromSales` and `decreasedGPFromSales` are currently not accounted for in
`getItemSalePrice` in bank.js. As a result various bank UI elements will display the incorrect value.

**Expected behavior**
`getItemSalePrice` should include the modifiers in it's calculation.

```js
function getItemSalePrice(itemID) {
  let saleModifier =
    1 +
    (playerModifiers.increasedGPFromSales -
      playerModifiers.decreasedGPFromSales) /
      100;
  if (
    getMasteryPoolProgress(CONSTANTS.skill.Woodcutting) >=
      masteryCheckpoints[2] &&
    items[itemID].type === 'Logs'
  )
    saleModifier += 0.5;
  return Math.floor(items[itemID].sellsFor * saleModifier);
}
```
**Note**: This modifier is currently not present on any modifier providing things in the game, so it should have no impact currently.
**Browser**
Browser agnostic bug.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update.
