### ISSUE TITLE
Minor: Modifiers `increasedChanceToDoubleLootThieving` and `decreasedChanceToDoubleLootThieving` are not implemented

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#767]
**Describe the bug**
The modifiers `increasedChanceToDoubleLootThieving` and `decreasedChanceToDoubleLootThieving` are currently not implemented. I have found no references to them in the source code (other than their description).

**Expected behavior**
`increasedChanceToDoubleLootThieving` and `decreasedChanceToDoubleLootThieving` should increase `itemQtyChance` in the function `pickpocket` in thieving.js. 

This can be accomplished by either adding it to the function `calculateChanceToDouble`, or changing all references to these modifiers to `increasedChanceToDoubleItemsSkill: [[CONSTANTS.skill.Thieving, <value>]]` and `decreasedChanceToDoubleItemsSkill: [[CONSTANTS.skill.Thieving, <value>]]` respectively.

**Browser**
Browser agnostic bug.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixed in upcoming hotfix
