### ISSUE TITLE
Minor: Modifiers `increasedMiningNodeHP` and `decreasedMiningNodeHP` are not implemented

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#768]
**Describe the bug**
The modifiers `increasedMiningNodeHP` and `decreasedMiningNodeHP` are not implemented. I could not find any references to them in the source code (other than `printPlayerModifier`).

**Expected behavior**
`increasedMiningNodeHP` and `decreasedMiningNodeHP` should be implemented in `updateRockHP` in rockHitting.js.
(While doing so, the references to `petUnlocked[4]` should also be removed to prevent the bonus from being duplicated)

**Browser**
Browser agnostic bug.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixed in upcoming hotfix
