### ISSUE TITLE
Minor: Modifiers `increasedChanceToDoubleItemsSkill` and `decreasedChanceToDoubleItemsSkill` do not work for Mining

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#769]
**Describe the bug**
The modifiers `increasedChanceToDoubleItemsSkill` and `decreasedChanceToDoubleItemsSkill` do not work for Mining.
This impacts the agility obstacle 'Rock Climb' as it provides this bonus.

**Expected behavior**
`increasedChanceToDoubleItemsSkill` and `decreasedChanceToDoubleItemsSkill` should be added to mining (both online and offline, and made to work with gems as the description implies this), or usage of these modifiers for Mining should be replaced with `increasedChanceToDoubleOres` and `decreasedChanceToDoubleOres`.

**Browser**
Browser agnostic bug.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixed in upcoming hotfix
