### ISSUE TITLE
Show thieving calculation in the game

### ISSUE THREAD

**Issue by TheKingOfLight** [MelvorIdle/melvoridle.github.io#771]
**Suggestion:**
Thieving describes how GP and the Success Rate are calculated and show the Xp per action.

**Why are you suggesting this?**
In all other skills you can calculate well thanks to the information (e.g. the xp per action, resource prevention chance, double item chance).
Only in Thieving you have to read the wiki to understand how much XP each action gives and how much GP the actions give. 
Also how the success rate is calculated is not explained in the game.
After visiting the wiki several times for this reason, I wondered why thieving is the only skill where the mechanics are not explained.

**How does your suggestion benefit the game?**
It would make it more understandable for users how this skill works. Without looking at the wiki it is extremely incomprehensible and confusing. Especially when thieving is the only skill where the level has an influence on the action. This should at least be mentioned.
With the missing XP and GP rates, the problem is that this information is given with the other skills and thus displaying it would make the game more consistent.
Therefore, the change would help especially new players and players who are starting to get more technical in the game.

**Comment by MelvorIdle** [comment]
This is something that is planned to be implemented universally once all the bonuses in the game are transitioned to the new system
