### ISSUE TITLE
[Mobile] Herblore select potion type text dark on dark background

### ISSUE THREAD

**Issue by Balake** [MelvorIdle/melvoridle.github.io#773]
**Describe the bug**
In the Herblore skill on mobile (iOS), the select potion type drop down text is dark on a dark background, making it difficult to read. See screenshot. Dark mode is enabled in OS, but not sure if it matters. Dark mode enabled in app settings. 

**To Reproduce**
1. Go to Herblore
2. Observe

**Expected behavior**
Easy to read text. 

**Screenshots**
![image](https://user-images.githubusercontent.com/12928604/110246420-624da680-7f1c-11eb-94d0-cf81a65f42ec.png)

**Browser**
iOS app from App Store, 1.0.9

**Console output**
N/A

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Fixed in upcoming hotfix
