### ISSUE TITLE
Minor: Extra bank slots from Bank Slot Tokens are converted to Shop Upgrades on refresh

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#775]
**Describe the bug**
When you claim a Bank Slot Token, bankMax is increased by the number of tokens claimed
```js
function claimBankToken() {
  let itemID = selectedBankItem;
  let bankID = getBankId(itemID);
  let qty = claimTokenQty;
  if (bankID >= 0) {
    updateItemInBank(bankID, itemID, -qty);
    bankMax += qty;
    updateBank();
    selectBankItem(selectedBankItem);
  }
}
```
However, when you load the game, the tokens are converted into shop upgrades in `cleanSaveFile`. (coincidentally this is also converting them to 1 less because the loop starts at 1)
```js
for (let i = 1; i < bankMax; i++) shopItemsPurchased.push(['General', 0]);
```

I believe bank slot tokens were supposed to be implemented as a Misc Modifier via:
```js
function calculateMiscModifiers() {
  let bankID = getBankId(CONSTANTS.item.Bank_Slot_Token);
  if (bankID >= 0)
  // Found - in bank - sold, oh this is bugged because typo
    playerModifiers['increasedBankSlots'] +=
      itemStats[CONSTANTS.item.Bank_Slot_Token].stats[0] -
      bank[bankID].qty -
      itemStats[CONSTANTS.item.Bank_Slot_Token].stats[1];
  else
    playerModifiers['increasedBankSlots'] +=
      itemStats[CONSTANTS.item.Bank_Slot_Token].stats[0] -
      itemStats[CONSTANTS.item.Bank_Slot_Token].stats[1];
}
```
But this code has a typo, as `increasedBankSlots` should be `increasedBankSpace`.

**Reproduction steps**
1. Acquire some bank slot tokens `addItemToBank(CONSTANTS.item.Bank_Slot_Token,3)`
2. Claim those tokens in the bank
3. Save the game
4. Refresh the page and load the save again
5. Note that your bank slots are now 1 lower than expected, and that the price of bank upgrades in the shop have gone up

**Expected behavior**
Bank slot tokens should not increase `bankMax`. Instead they should call `updateAllPlayerModifiers` after the quantity has been deducted from the bank.

In addition, Bank Space Shop Upgrades that were given as the result of Bank Slot Tokens will need to be removed from save files once, when this change is implemented to prevent free bank space from getting added.

**Browser**
Browser agnostic bug.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixed in upcoming hotfix
