### ISSUE TITLE
Goblin Raid next wave continues while item select screen still open

### ISSUE THREAD

**Issue by levgre** [MelvorIdle/melvoridle.github.io#776]
**Describe the bug**
Goblin Raid next wave continues while item select screen for finishing a wave is still open.  I got an ice 2h sword with deadly cut special so the bug may be related to bleed damage.  As an aside the bleed damage doesn't seem to work, it might have been working when I first got the weapon.

**Browser**
Firefox 86.0

**Console output**
12:34:37.574 MICSR: setting up playerSpecialNames MICSR.js:7:31
12:34:37.575 MICSR: Unknown stat setHPDamageMinimum for player special attacks:  
Array [ "Sandstorm" ]
MICSR.js:7:31
12:34:37.575 MICSR: Unknown stat setDOTDamage for player special attacks:  
Array [ "Sandstorm" ]
MICSR.js:7:31
12:34:37.575 MICSR: Unknown stat DOTInterval for player special attacks:  
Array [ "Sandstorm" ]
MICSR.js:7:31
12:34:37.575 MICSR: Unknown stat DOTMaxProcs for player special attacks:  
Array [ "Sandstorm" ]
MICSR.js:7:31
12:34:37.575 MICSR: Unknown stat activeBuffs for player special attacks:  
Array [ "Sandstorm" ]
MICSR.js:7:31
12:34:37.575 MICSR: Unknown stat extraBleedDmg for player special attacks:  
Array [ "Deadly Cut" ]
MICSR.js:7:31
12:34:37.575 MICSR: Unknown stat setDOTDamage for enemy special attacks:  
Array(53) [ "Volley", "Razor-Sharp Claws", "Dragonbreath", "Barrage", "Wind Blade", "Whirlwind", "Tornado", "Cyclone", "Icy Chill", "Frozen Spears", … ]
MICSR.js:7:31
12:34:37.575 MICSR: Unknown stat attackSpeedSlow for enemy special attacks:  
Array [ "Cyclone" ]
MICSR.js:7:31
12:34:37.575 MICSR: Unknown stat attackSpeedSlowTurns for enemy special attacks:  
Array [ "Cyclone" ]
MICSR.js:7:31
12:34:37.576 MICSR: TabCard is waiting for Card MICSR.js:7:31
12:34:37.577 MICSR: main is waiting for App MICSR.js:7:31
12:34:37.589 MICSR: setting up statNames MICSR.js:7:31
12:34:37.593 MICSR: Unknown stat modifiers for items:  
Array(131) [ "Amulet of Fishing", "Gold Topaz Ring", "Gold Ruby Ring", "Gold Emerald Ring", "Ranger Hat", "Ranger Boots", "Ancient Wizard Hat", "Ancient Wizard Robes", "Ancient Wizard Bottoms", "Ancient Wizard Boots", … ]
MICSR.js:7:31
12:34:37.594 MICSR: setting up Import MICSR.js:7:31
12:34:37.594 MICSR: setting up Card MICSR.js:7:31
12:34:37.594 MICSR: setting up Menu MICSR.js:7:31
12:34:37.594 MICSR: setting up Plotter MICSR.js:7:31
12:34:37.595 MICSR: setting up Loot MICSR.js:7:31
12:34:37.595 MICSR: setting up Simulator MICSR.js:7:31
12:34:37.598 MICSR: App is waiting for TabCard MICSR.js:7:31
12:34:37.691 Loading Save Game... save.js:13:9
12:34:37.699 Save Game Loaded... save.js:29:95
12:34:37.702
Array [ 20, 2 ]
main.js:413:527
12:34:37.702
Array [ 20, 2 ]
main.js:413:527
12:34:37.702
Array [ 20, 2 ]
main.js:413:527
12:34:37.706
Array [ 18, 5 ]
main.js:413:527
12:34:38.080
Array [ 20, 2 ]
main.js:413:527
12:34:38.080
Array [ 20, 2 ]
main.js:413:527
12:34:38.080
Array [ 20, 2 ]
main.js:413:527
12:34:38.082
Array [ 18, 5 ]
main.js:413:527
12:34:38.126
Array [ 20, 2 ]
main.js:413:527
12:34:38.126
Array [ 20, 2 ]
main.js:413:527
12:34:38.126
Array [ 20, 2 ]
main.js:413:527
12:34:38.131
Array [ 18, 5 ]
main.js:413:527
12:34:38.155 Loading Masteries... mastery.js:2:35
12:34:38.721
Array [ 20, 2 ]
main.js:413:527
12:34:38.721
Array [ 20, 2 ]
main.js:413:527
12:34:38.721
Array [ 20, 2 ]
main.js:413:527
12:34:38.725
Array [ 18, 5 ]
main.js:413:527
12:34:38.733
Array [ 20, 2 ]
main.js:413:527
12:34:38.734
Array [ 20, 2 ]
main.js:413:527
12:34:38.734
Array [ 20, 2 ]
main.js:413:527
12:34:38.738
Array [ 18, 5 ]
main.js:413:527
12:34:38.745
Array [ 20, 2 ]
main.js:413:527
12:34:38.745
Array [ 20, 2 ]
main.js:413:527
12:34:38.745
Array [ 20, 2 ]
main.js:413:527
12:34:38.750
Array [ 18, 5 ]
main.js:413:527
12:34:38.790 Game Loaded main.js:6:380
12:34:40.118 Synchronising with Cloud cloud.js:12:151
12:34:40.334 fun-hooks: referenced 'registerAdserver' but it was never created prebid.min.js:3:45867
12:34:40.637 MICSR: setting up TabCard MICSR.js:7:31
12:34:40.637 MICSR: setting up App MICSR.js:7:31
12:34:48.660 Connected to PlayFab successfully cloud.js:96:144
12:34:48.749 MICSR: setting up main MICSR.js:7:31
12:34:48.750 Melvor Completion Log Helper Loaded melvoridle.com:3:11
12:34:52.351 MICSR: Melvor Combat Sim was not Loaded due to game version incompatibility. MICSR.js:8:32
12:39:40.146 Synchronising with Cloud cloud.js:12:151
12:43:28.042 Confiant: ad blocked 
Arguments { 0: 10, 1: "2", 2: 0, 3: "mOinGM9MTu5v-Lto835XLhlrSPY", 4: "bU9pbkdNOU1UdTV2LUx0bzgzNVhMaGxyU1BZLzI4MDY5MjU3MTk6MXgx", 5: {…}, 6: true, … }
config.js:16:13
12:44:28.211 Confiant: ad blocked 
Arguments { 0: 10, 1: "2", 2: 0, 3: "mOinGM9MTu5v-Lto835XLhlrSPY", 4: "bU9pbkdNOU1UdTV2LUx0bzgzNVhMaGxyU1BZLzI4MDY5MjU3MTk6MXgx", 5: {…}, 6: true, … }
config.js:16:13
12:44:40.141 Synchronising with Cloud 2 cloud.js:12:151
12:53:05.992 Confiant: ad blocked 
Arguments { 0: 10, 1: "2", 2: 0, 3: "mOinGM9MTu5v-Lto835XLhlrSPY", 4: "bU9pbkdNOU1UdTV2LUx0bzgzNVhMaGxyU1BZLzI4MDY5MjU3MTk6MXgx", 5: {…}, 6: true, … }
config.js:16:13
12:54:40.141 Synchronising with Cloud cloud.js:12:151
12:58:32.591
Array [ 20, 2 ]
main.js:413:527
12:58:32.591
Array [ 20, 2 ]
main.js:413:527
12:58:32.591
Array [ 20, 2 ]
main.js:413:527
12:58:32.593
Array [ 18, 5 ]
main.js:413:527
12:58:32.828
Array [ 20, 2 ]
main.js:413:527
12:58:32.829
Array [ 20, 2 ]
main.js:413:527
12:58:32.829
Array [ 20, 2 ]
main.js:413:527
12:58:32.830
Array [ 18, 5 ]
main.js:413:527
12:59:40.189 Synchronising with Cloud cloud.js:12:151
13:03:05.828
Uncaught TypeError: monsterStats[enemyInCombat] is undefined
    attackPlayer https://melvoridle.com/assets/js/game/combat.js?774:124
    enemyTimer https://melvoridle.com/assets/js/game/combat.js?774:26
combat.js:124:191
13:03:16.302
Uncaught TypeError: monsterStats[enemyInCombat] is undefined
    attackPlayer https://melvoridle.com/assets/js/game/combat.js?774:124
    enemyTimer https://melvoridle.com/assets/js/game/combat.js?774:26
combat.js:124:191
13:04:24.402 Source map error: Error: request failed with status 403
Resource URL: https://cdn.melvor.net/core/v018/assets/js/popper.min.js
Source Map URL: popper.min.js.map

13:04:24.402 Source map error: Error: request failed with status 403
Resource URL: https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js
Source Map URL: tippy-bundle.umd.min.js.map

13:04:24.569 Source map error: Error: request failed with status 403
Resource URL: https://static.yieldmo.com/partner.min.html?partners=a%2Cb%2Cc%2Cd%2Ce%2Cf%2Cg%2Cm%2Cn%2Cp%2Cs%2Ct%2Cz%2Cl%2Ci%2Cr%2Cx%2Ceb%2Ca9%2Cdv360%2Caa&gdpr=0
Source Map URL: partner.js.map

13:04:40.191 Synchronising with Cloud

**Are you using any scripts?**
Combat simulator but didn't activate it on prompt when game started

**Comment by coolrox95** [comment]
This bug is due to an error in `applyBleedToEnemy` in combat,js
When the enemy dies due to bleed `updateCombat` is called once via `damageEnemy`. But then it gets called again, which starts raid behind the menu.

```js
function applyBleedToEnemy(bleedHPPerProc, interval, bleedCount) {
  combatData.enemy.isBleeding = true;
  $('#combat-enemy-debuffs-bleed').removeClass('d-none');
  let count = 0;
  enemyBleedInterval = setInterval(function () {
    if (count >= bleedCount || combatData.enemy.isDead)
      removeEnemyBleedDebuff();
    else {
      damageEnemy(bleedHPPerProc); // Enemy is killed by bleed  here, and death processing should clear the bleed DOT and call updateCombat
      if (equippedItems.includes(CONSTANTS.item.Elder_Crown))
        updatePlayerHitpoints(bleedHPPerProc);
      if (combatData.enemy.hitpoints < 1) {
        removeEnemyBleedDebuff();
        updateCombat(); // This second call to updateCombat is what starts raid again
      }
      count++;
    }
  }, interval);
}
```

The entire code block for `combatData.enemy.hitpoints < 1` should just be removed.

**Comment by MelvorIdle** [comment]
Fixed in upcoming hotfix
