### ISSUE TITLE
Bank slot tokens not redeeming correctly

### ISSUE THREAD

**Issue by tevoul** [MelvorIdle/melvoridle.github.io#779]
**Describe the bug**
When I use a bank slot token it increases my number of slots until I load a save, at which point the slots revert back and I still lose the token

**To Reproduce**
1. Use bank slot token
2. Force a cloud save
3. Refresh page
4. Bank slots have reverted back to previous value, token has been used

**Expected behavior**

**Screenshots**

**Browser**
Firefox browser, but tried loading cloud save in android as well and still incorrect bank slots

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Fixed in upcoming hotfix
