### ISSUE TITLE
xp in sidebar tooltip not updating

### ISSUE THREAD

**Issue by mrDLSable** [MelvorIdle/melvoridle.github.io#78]
**Describe the bug**
The xp in the tooltip on the skill in the sidebar does not update when you gain xp.

**To Reproduce**
1. mouse over the skill in the sidebar
2. gain xp
3. mouse of the skill in the sidebar
4. notice the same xp as before

**Expected behavior**
The xp updates

**Screenshots**
![image](https://user-images.githubusercontent.com/1783781/70369544-91a9d980-18bb-11ea-81da-02c2b7f97eb7.png)

**Browser**
Chrome

**Console output**
Normal

**Comment by MelvorIdle** [comment]
Fixed in v0.10.1
