### ISSUE TITLE
Priest Hat not functioning correctly

### ISSUE THREAD

**Issue by Periana** [MelvorIdle/melvoridle.github.io#780]
**Describe the bug**
Priest Hat does not reduce the cost of prayer if the prayer costs 1 prayer point.

**To Reproduce**
1. Equip Priest Hat
2. Activate one of the 1 point Prayers

**Expected behavior**
My prayer points to remain the same number if I have the Priest Hat equipped and activate one prayer with a cost of 1 point.

**Browser**
Google Chrome Version 88.0.4324.190

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Not a bug. Prayer's were never meant to be free.

There is always a 1 cost limit on Prayers. Most recent updated fixes this bug, listed in the bug fixes section of the changelog.
