### ISSUE TITLE
Alt. Magic spells that produce items do not benefit from `increasedChanceToDoubleItemsGlobal` and `increasedChanceToDoubleItemsSkill` (and their decreased counterparts)

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#781]
**Describe the bug**
Alt. Magic spells which produce items do not benefit from `increasedChanceToDoubleItemsGlobal` and `increasedChanceToDoubleItemsSkill`. (Both online and offline) They appear appear to not have been updated to the new modifier system:
```js
                    let chanceToDouble = 0;
                    if (
                      equippedItems.includes(
                        CONSTANTS.item.Aorpheats_Signet_Ring
                      )
                    )
                      chanceToDouble +=
                        items[CONSTANTS.item.Aorpheats_Signet_Ring]
                          .chanceToDoubleResources;
```

**Expected behavior**
Alt. Magic spells should use `calculateChanceToDouble(CONSTANTS.skill.Magic)` for item doubling chance instead of the hard coded check for Signet Ring.

**Browser**
Browser agnostic bug.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixed in upcoming hotfix
