### ISSUE TITLE
99 Agility Cape Equip Shortcut

### ISSUE THREAD

**Issue by ggjacky** [MelvorIdle/melvoridle.github.io#783]
At least on IOS, the cape it tries to equip is the MAX cape (am not maxed)

**Comment by ggjacky** [comment]
![image0 1](https://user-images.githubusercontent.com/46613318/110284397-9cf42500-7f96-11eb-9824-d6982ef6a57d.png)

**Comment by logam555** [comment]
I can confirm that this occurs on the browser version as well.

**Comment by MelvorIdle** [comment]
Fixed in upcoming hotfix
