### ISSUE TITLE
GP Earned is Less than Indicated on Obstacle - Agility

### ISSUE THREAD

**Issue by Bulletphil** [MelvorIdle/melvoridle.github.io#785]
Currently, the GP value that I receive when completing an obstacle appears less than what the obstacle tile indicates. Please see the screenshot below, but if it doesnt work, I will write out my example:

Obstacle 9: 
Tile indicates 10,964
Receives: 6091

This appears to be occurring for each obstacle at this time. As I brought this up in Discord, it appears that other people are experiencing this as well.

![image](https://user-images.githubusercontent.com/80265675/110329711-968b9a80-7fe2-11eb-9b3b-23712d97f700.png)

**Comment by MelvorIdle** [comment]
Should be fixed in the upcoming update/hotfix
