### ISSUE TITLE
[HC] Unknown bank slots

### ISSUE THREAD

**Issue by MildanWorld** [MelvorIdle/melvoridle.github.io#788]
**Describe the bug**

Have unlocked a total of 80 bank spaces by shop, and have gotten 25 bank slot tokens. This should give a total of 105 bank slots. However I logged in shortly after agility update and I now have 130 slots.

**To Reproduce**

Unknown how to reproduce. Mainly just an explorative bug report.

**Expected behavior**

Should have 105 bank slots.

**Screenshots**

![Bank slots](https://user-images.githubusercontent.com/7522800/110354218-37f10b80-8038-11eb-9fa7-baed0b77ed0d.png)
![Bank slot tokens](https://user-images.githubusercontent.com/7522800/110354273-47705480-8038-11eb-8df3-c676f09b5f8e.png)

**Browser**
Please tell us what browser you are using and what version.

Firefox v86.0 64-bit.

**Console output**
Please open the console by pressing F12 and copy it here.

Not relevant.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

No scripts.

**Comment by MildanWorld** [comment]
Talking to other people on the discord #bug-report-discussion channel others have also gotten a varying amount of extra bank slots. Maybe this is a bug that doubles the amount of slots given by the bank slot tokens?

**Comment by MildanWorld** [comment]
So it seems like other people who have also gotten more bank slots have all gotten extra bank slots amounting to their number of bank slot tokens.
Seems like a bug that counted the tokens twice somehow?

**Comment by MelvorIdle** [comment]
There was a bug during the initial conversion to the new bank-end shop system that placed bank token slots in the incorrect modifier resulting in increased bank spaces provided to players when that was then later fixed.

Please let me know if you would like a manual fix to this, which can be done on PC only
