### ISSUE TITLE
"decreased(Ranged|Magic)Evasion" and Peri effect applied twice in "calculatePlayerEvasionRating"

### ISSUE THREAD

**Issue by gmiclotte** [MelvorIdle/melvoridle.github.io#790]
**Describe the bug**
Two bugs in `calculatePlayerEvasionRating`
 - [x] Same bug as #761, but that issue (and the fix) only applied to `decreasedMeleeEvasion`. The same bug exists for `decreasedRangedEvasion` and `decreasedMagicEvasion`. In `calculatePlayerEvasionRating`, the modifier `decreasedRangedEvasion` (resp. `decreasedMagicEvasion`) is first applied to `maximumRangedDefenceRoll` (resp. `maximumMagicDefenceRoll`) with `applyModifier`, then it is applied *again* in the debuff application.
 - [x] Similarly, Peri is applied twice to `maximumRangedDefenceRoll` and `maximumMagicDefenceRoll`. Peri's bonus is first applied with `applyModifier`, and then *again* before buffs/debuffs are applied.

**To Reproduce**
1. Hop on an account without Peri, note player evasion ratings
2. Unlock Peri (`unlockPet(22)`)
3. Notice that melee evasion rating increase ~5%, while ranged and magic evasion ratings increase with ~10%

**Expected behavior**
Should behave like the Melee evasion calculation earlier in the same method, i.e.
```diff
    maximumDefenceRoll = Math.floor(maximumDefenceRoll * (1 - combatData.player.meleeEvasionDebuff / 100));
[...]
-   if (petUnlocked[22])
-       maximumRangedDefenceRoll = Math.floor(maximumRangedDefenceRoll * 1.05);
[...]
-   maximumRangedDefenceRoll = Math.floor(maximumRangedDefenceRoll * (1 - (combatData.player.rangedEvasionDebuff + playerModifiers.decreasedRangedEvasion) / 100));
+   maximumRangedDefenceRoll = Math.floor(maximumRangedDefenceRoll * (1 - combatData.player.rangedEvasionDebuff / 100));
[...]
-   if (petUnlocked[22])
-       maximumMagicDefenceRoll = Math.floor(maximumMagicDefenceRoll * 1.05);
[...]
-   maximumMagicDefenceRoll = Math.floor(maximumMagicDefenceRoll * (1 - (combatData.player.magicEvasionDebuff + playerModifiers.decreasedMagicEvasion) / 100));
+   maximumMagicDefenceRoll = Math.floor(maximumMagicDefenceRoll * (1 - combatData.player.magicEvasionDebuff / 100));
```

**Browser**
browser agnostic bug

**Are you using any scripts?**
no

**Comment by MelvorIdle** [comment]
Fixed in upcoming hotfix
