### ISSUE TITLE
Longrange Ranged Attack Style bonus defence levels do not work

### ISSUE THREAD

**Issue by gmiclotte** [MelvorIdle/melvoridle.github.io#791]
**Describe the bug**
Longrange tooltip says: `+3 Defence Level (hidden)`, but as far as I can tell, this style does not give any bonus at all.

**To Reproduce**
1. Equip some ranged gear
2. Swap between styles
3. Notice that melee evasion rating is the same no matter which attack style you use

**Expected behavior**
Longrange gives a higher melee evasion rating

**Browser**
browser agnostic bug

**Are you using any scripts?**
no

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
