### ISSUE TITLE
Cannot Minimize "Gloves" or "Materials" sections of shop

### ISSUE THREAD

**Issue by SkuliAdams** [MelvorIdle/melvoridle.github.io#793]
**Describe the bug**
The "Gloves" and "Materials" sections of the shop cannot be minimized.

**To Reproduce**
Attempt to minimize these sections like one can with the other parts of the shop.

**Expected behavior**
These sections of the shop should be minimizable.

**Screenshots**

![Shop](https://user-images.githubusercontent.com/25968150/110431801-43febc80-807c-11eb-80d1-06b37da98526.png)

**Browser**
Steam Version.

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
