### ISSUE TITLE
Offline Woodcutting Potion usage being calculated incorrectly

### ISSUE THREAD

**Issue by Timothy-1990** [MelvorIdle/melvoridle.github.io#794]
**Describe the bug**
Game character was cutting normal and oak logs at intervals of 0.85s and 1.2s respectively, while using Bird Next IV potions and while the Woodcutting mastery pool was above 95%. The game was closed and opened 1 hour and 59 minutes later (I slightly missed the 2 hours mark, hence why the screenshot shows 1 hour of offline time). 

During this time, according to the game, 5990 actions were performed and the amount of bird nests were assigned accordingly (5990 * 0.3 * 2) = 3594 ~ 3628. According to my calculations a total of 14470 actions should have been performed in 2 hours. It seems like the game is onlu counting the actions of 1 tree (7200/1.2=6000 ~ 5990).

**To Reproduce**
1. Have the double tree shop upgrade unlocked;
2. Equip Woodcutting skillcape;
3. Equip Tier IV Bird Nest potion;
4. Start cutting normal and oak trees;
5. Close the game;
6. Open the game x time later;
7. The game will have counted too little offline actions.

**Expected behavior**
Expected behavior is to have all offline Woodcutting actions be counted as such by the game.

**Screenshots**
![image](https://user-images.githubusercontent.com/71520839/110467962-eef09400-80d7-11eb-9d03-d3bf238500c5.png)

**Browser**
Google Chrome, version 89.0.4389.82

**Console output**
![image](https://user-images.githubusercontent.com/71520839/110468064-10518000-80d8-11eb-818d-ed083db25854.png)

**Are you using any scripts?**
None

**Comment by MelvorIdle** [comment]
Yep, the real bug here is Bird Nest potions are being incorrectly calculated and used. You still performed the correct amount of actions, just the bug has to do with the potion count

**Comment by coolrox95** [comment]
I'd also like to add that the conversion of potions to the modifier system in v0.19.1 has not been done for the offline woodcutting code. (I assume that will be corrected when this bug gets fixed).

**Comment by MelvorIdle** [comment]
Correct assumption. Got about 3 bugs relating to offline woodcutting that I’ll sort out in 1 go

**Comment by Timothy-1990** [comment]
Woohoo, soon my nest farming potential will reach new heights! ;)
