### ISSUE TITLE
IOS cant see cloud save with 2 or more characters

### ISSUE THREAD

**Issue by Devyyx** [MelvorIdle/melvoridle.github.io#797]
**Describe the bug**
IOS cant see cloud save with 2 or more characters
**To Reproduce**
1. after the new update i went ot mobile ios versio n of melvor idle and i couldnt get my cloud saves cause 2 or more characters block it from view

**Expected behavior**
See my cloud save so i can load it on ios and not lose hours because i cant log in to the cloud

**Screenshots**
https://www.reddit.com/r/MelvorIdle/comments/lzamz6/how_to_access_cloud_saves_on_ios_i_only_get_local/

**Browser**
Please tell us what browser you are using and what version.

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

**Comment by MelvorIdle** [comment]
This seems to be an iOS 12 issue that I am looking into
