### ISSUE TITLE
Offline Herblore Missing Tiers

### ISSUE THREAD

**Issue by ZephyrToad** [MelvorIdle/melvoridle.github.io#798]
**Describe the bug**
Crafting potions offline (Skilled Fletching Potions)
Never made Tier II potion.
Cannot complete completion/item log.

**To Reproduce**
1. Go to Herblore
2. Craft potion of choice
3. Return after level 50 mastery, skipping 20-49 
4. No Tier II Potions will have been crafted offline

**Expected behavior**
A Tier II potion to have been made while mastery was between 20-49

**Screenshots**
![image](https://user-images.githubusercontent.com/17329308/110589204-ae2a6680-813b-11eb-91a5-724507dedb9d.png)

**Browser**
Steam V 0.19

**Console output**
N/A

**Are you using any scripts?**
N/A

**Comment by ZephyrToad** [comment]
I guess with Herblore Potions you can get the missing tiers, still seems strange that it skipped that mastery tho.

**Comment by MelvorIdle** [comment]
This is intended.

Offline Mastery bonuses are based on the mastery level from the time you went offline, and is used to calculate all progress based on that level.
