### ISSUE TITLE
All prayers deduct one prayer point on select and deselect

### ISSUE THREAD

**Issue by pwnagenerd13** [MelvorIdle/melvoridle.github.io#801]
**Describe the bug**
Upon select or deselecting any prayer, my prayer point total was reduced by one, even out of combat.

**To Reproduce**
1. Go to Combat
2. Select/Deselect any prayer
3. Observe prayer points total decrease

**Expected behavior**
Expected no prayer point deduction for selecting/deselecting prayer, only deduction on player/enemy attack turn.

**Browser**
Chrome Version 88.0.4324.190

**Are you using any scripts?**
Combat Simulator Reloaded, v0.18, but not loaded due to version mismatch

**Comment by pwnagenerd13** [comment]
I can also mention that this was with agility obstacles inactive. When Cliff Balance, a *-2* prayer point cost (I know this plus/minus sign has been brought up already), was activated, the select/deselect decrease became two points.

**Comment by MelvorIdle** [comment]
Fixed in upcoming hotfix update
