### ISSUE TITLE
Minor: Hitpoints Skillcape and capes that provide its bonus gives +100 HP regen per interval instead of +10. Description is also wrong in adventure mode.

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#802]
**Describe the bug**
The data for the skillcape in items.js
```js
  {
    category: 'Combat',
    type: 'Armour',
    tier: 'Skillcape',
    name: 'Hitpoints Skillcape',
    description: '+10 HP Regen per interval',
    canUpgrade: false,
    equipmentSlot: CONSTANTS.equipmentSlot.Cape,
    buysFor: 1000000,
    sellsFor: 250000,
    media: 'assets/media/bank/skillcape_hitpoints.svg',
    attackBonus: [0, 0, 0],
    strengthBonus: 0,
    defenceBonus: 9,
    damageReduction: 0,
    rangedAttackBonus: 0,
    rangedDefenceBonus: 9,
    magicDefenceBonus: 9,
    rangedStrengthBonus: 0,
    modifiers: {
      increasedHPRegenFlat: 10,
    },
  },
```
has `increasedHPRegenFlat` set to 10, which is multiplied by `numberMultiplier` before being added to `regen` in `regenerateHitpoints`. As a result the cape is providing 100 regen per interval in standard mode and +1000 in adventure.

In addition the description is wrong in adventure mode. 

**Expected behavior**
Hitpoints skillcape should provide +10 HP regen per interval in standard mode and +100 HP regen per interval in adventure mode. The description should change based on game mode.

**Fix**
Replace `increasedHPRegenFlat: 10,` with `increasedHPRegenFlat: 1,` for the 'Hitpoints Skillcape', 'Max Skillcape' and 'Cape of Completion'.

Change the description of the `Hitpoints Skillcape' to a getter method:
```js
    get description() {
      return `+${getNumberMultiplierValue(this.modifiers.increasedHPRegenFlat)} HP Regen.`;
    },
```

**Screenshots**
I breakpointed `regenerateHitpoints` in standard mode with the cape equipped and as you can see it added +100 per interval.
![image](https://user-images.githubusercontent.com/58208131/110691580-8b7f6880-81a2-11eb-9341-10fc02f03bb6.png)

**Browser**
Browser Agnostic Bug.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
