### ISSUE TITLE
Stormsnap damage much lower than it should be

### ISSUE THREAD

**Issue by INoob2000** [MelvorIdle/melvoridle.github.io#803]
**Describe the bug**
Stormsnap damage/accuracy is much lower than it should be (divided by 5500?). Seems like damage was calibrated down or something. It used to have a minimum damage slightly higher than ancient longbow, but now its much much lower. Damage still changes based on enemy magic level though, scaling is just off

**To Reproduce**
1. Equip stormsnap (i used ancient arrows and full aeris on the side to reproduce)
2. Fight some mob
3. Look at max hit/accuracy
4. Compare with any other longbow to see error

**Expected behavior**
Damage to be much higher

**Screenshots**
With redwood longbow max hit/acc
![image](https://user-images.githubusercontent.com/80449991/110754987-aa631680-8205-11eb-91b2-efcf59fcacf7.png)
(Same mob same equips) with stormsnap max hit/acc
![image](https://user-images.githubusercontent.com/80449991/110755052-bd75e680-8205-11eb-8229-a01663b00ab6.png)

**Browser**
Most recent 1.9, from mar11. Issue noticed for sure on mobile, steam, and firefox versions. 

Edit: Others also reporting this on discord 

**Console output**
Edit: think people may have found the code for this. See screenshot below (taken off discord)
![263FE1F8-C0C4-4D6C-B799-CBFD683F0EB5](https://user-images.githubusercontent.com/80449991/110866066-ce643d80-8281-11eb-9573-4d268a82ba28.png)

**Are you using any scripts?**
No scripts

**Comment by coolrox95** [comment]
Issue is due to stormsnap overwriting the existing strength/attackBonus values from other equipment. Easy fix, just need to change the `=` to a `+=` when modifying `combatData.player.baseStats`
```js
  if (
    equippedItems[CONSTANTS.equipmentSlot.Weapon] === CONSTANTS.item.Stormsnap
  ) {
    if (isInCombat && combatData.enemy.id !== null && !newEnemyLoading) {
      if (!isGolbinRaid) {
        combatData.player.baseStats.strengthBonusRanged = Math.floor(
          110 + (1 + (combatData.enemy.magicLevel * 6) / 33)
        );
        combatData.player.baseStats.attackBonusRanged = Math.floor(
          102 * (1 + (combatData.enemy.magicLevel * 6) / 5500)
        );
      } else {
        combatData.player.baseStats.strengthBonusRanged = Math.floor(
          110 + (1 + (getGolbinLevel() * 6) / 33)
        );
        combatData.player.baseStats.attackBonusRanged = Math.floor(
          102 * (1 + (getGolbinLevel() * 6) / 5500)
        );
      }
    }
```
to

```js
  if (
    equippedItems[CONSTANTS.equipmentSlot.Weapon] === CONSTANTS.item.Stormsnap
  ) {
    if (isInCombat && combatData.enemy.id !== null && !newEnemyLoading) {
      if (!isGolbinRaid) {
        combatData.player.baseStats.strengthBonusRanged += Math.floor(
          110 + (1 + (combatData.enemy.magicLevel * 6) / 33)
        );
        combatData.player.baseStats.attackBonusRanged += Math.floor(
          102 * (1 + (combatData.enemy.magicLevel * 6) / 5500)
        );
      } else {
        combatData.player.baseStats.strengthBonusRanged += Math.floor(
          110 + (1 + (getGolbinLevel() * 6) / 33)
        );
        combatData.player.baseStats.attackBonusRanged += Math.floor(
          102 * (1 + (getGolbinLevel() * 6) / 5500)
        );
      }
    }
```

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
