### ISSUE TITLE
Firemaking Skillcape Wording

### ISSUE THREAD

**Issue by KnKravlegard** [MelvorIdle/melvoridle.github.io#804]
**Describe the bug**
In v0.19 you changed "Skills" wording changed to "Non-Combat" in the Sidebar/Menu
But Firemaking Skillcape still says Skills, implying it would increase the exp you get in the Combat skills aswell now. 

https://wiki.melvoridle.com/index.php?title=Firemaking_Skillcape

**Comment by MelvorIdle** [comment]
Firemaking Skillcape always worked with Combat XP, hence the "Global Skilling" part of the wording.
