### ISSUE TITLE
Agility training gets stuck when an obstacle is about to hit 99 mastery

### ISSUE THREAD

**Issue by GeminiQvQ** [MelvorIdle/melvoridle.github.io#805]
When training Agility, the process seems to get stuck if the current obstacle's mastery gain would push it over from 98 to 99 mastery. Stopping and starting the training manually will make it correctly roll over to 99 upon hitting the obstacle next time.

So far I have experienced this with Tree Balance and Gap Jump.

**To Reproduce**
1. Train Agility until an obstacle is 1 iteration away from hitting 99 mastery.
2. Attempt to train the final iteration of mastery on said obstacle.
3. Observe that the process gets stuck.

**Expected behavior**
The obstacle should hit 99 mastery without blocking the agility training process.

**Browser**
I've only tested this in the Steam version of the game.

**Are you using any scripts?**
No.

**Comment by coolrox95** [comment]
Testing this myself:
![image](https://user-images.githubusercontent.com/58208131/110889139-d4badf80-82aa-11eb-9820-73ffa445c73e.png)
And it seems to work and continue fine on all the obstacles. I can't reproduce this issue, and believe it was fixed as per: #743
![image](https://user-images.githubusercontent.com/58208131/110889279-13509a00-82ab-11eb-96fc-9c046ac8e750.png)

For reference I just did this in console
`MASTERY[CONSTANTS.skill.Agility].xp.fill(exp.level_to_xp(99)-10)`
refreshed the game after saving and then started agility.

**Comment by MelvorIdle** [comment]
Waiting on confirmation before closing this one

**Comment by GeminiQvQ** [comment]
Ah, I see. I can't say 100% when I last updated my Steam game version. I just updated this morning, so I'll run Agility training overnight again to see if it's addressed.

**Comment by GeminiQvQ** [comment]
Yep, it's no longer an issue. Thanks for addressing it!
