### ISSUE TITLE
"Chance to double items globally" does not work globally

### ISSUE THREAD

**Issue by MemeMastodon69** [MelvorIdle/melvoridle.github.io#809]
Tested with Ice Jump agility obstacle's +5% chance.

Killed 300 master farmers and received 303 bones, the extra bones being the expected result of having the Golden Golbin pet. The chance of this outcome occuring if "global" item doubling affected combat is less than 0.0001%

Either the bonus is worded poorly (should specify non-combat) or implemented incorrectly.

**Comment by MelvorIdle** [comment]
Fixed in upcoming hotfix
