### ISSUE TITLE
Minor: Shop items with slayer task requirements do not update if task is completed while shop is open

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#810]
**Describe the bug**
When the shop is open, and you complete a slayer task the "Unlocks after X more Y Slayer Task Completions"  text doesn't update.
![image](https://user-images.githubusercontent.com/58208131/110869893-9c0a0e80-8288-11eb-9723-53a7d9f61737.png)

**To Reproduce**
1. Start fighting a slayer task.
2. Open the shop.
3. Wait for task to finish.
4. Note that the text does not update.

**Expected behavior**
The requirement text should update on task completion.
**Fix**
- [x] Replace the call to the deprecated `updateSlayerShop` in `updateSlayerTask` with `updateShopCosts` in combat.js

In a similar vein to this there is an unnecessary call to a deprecated function when the game loads that can be removed for a minor speedup in loading
- [x] Remove the call to the deprecated `loadSlayerShop` in `updateWindow` in main.js

**Browser**
Browser Agnostic Bug.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixed in upcoming hotfix
