### ISSUE TITLE
Pipe Balance Doesn't Correctly apply +10 Mining Node HP

### ISSUE THREAD

**Issue by Pandorian6008** [MelvorIdle/melvoridle.github.io#811]
**Describe the bug**
Agility Obstacle Pipe Balance (Obstacle 3) States +10 Mining Node HP, +3% Chance to Preserve Resources in Skills.
+10 Mining Node HP is not being applied

**To Reproduce**
1. Build Agility Obstacle "Pipe Balance"
2. Mine low mastery ore that isn't at 10 hits itself
3. Ore exhausted before 10 hits, as if +10 is not applied

**Expected behavior**
Node should last longer and produce more ore before being exhausted.

**Screenshots**
![image](https://user-images.githubusercontent.com/75744619/110877317-3bd69500-82a7-11eb-9767-946c98a97060.png)
![image](https://user-images.githubusercontent.com/75744619/110877375-4d1fa180-82a7-11eb-89a9-bc36c7414e60.png)
![image](https://user-images.githubusercontent.com/75744619/110877399-5872cd00-82a7-11eb-9eac-f95c9a493704.png)
![image](https://user-images.githubusercontent.com/75744619/110877431-67f21600-82a7-11eb-89eb-b258536632e3.png)
![image](https://user-images.githubusercontent.com/75744619/110877455-6f192400-82a7-11eb-857f-7dc687848826.png)
![image](https://user-images.githubusercontent.com/75744619/110877488-7f310380-82a7-11eb-927f-e9efd3f07879.png)

**Browser**
Steam version

**Console output**
N/A Steam

**Are you using any scripts?**
No

**Comment by coolrox95** [comment]
Copy pasting code strikes again.
`updateRockHP` in mining.js only had `increasedMiningNodeHP` and `decreasedMiningNodeHP` implemented for the calculation when the game loads (`initialise=true`) (I believe this means it works properly for offline mining). Needs to be implemented in the else block of the `if (initialise)` statement as well. (or better yet just make a `getMaxRockHP` function and use that in both places).

**Comment by MelvorIdle** [comment]
God I hate my old code lol.

Fixed in upcoming hotfix
