### ISSUE TITLE
Minor: Agility Obstacles do not update their XP or GP values when items that impact them are equipped or unequipped

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#813]
**Describe the bug**
The GP and XP display of agility obstacles does not update when you equip or unequip an item that would modify them. (e.g Aorpheat's Signet Ring, Ancient Ring of Skills)

This may be the cause of issue. #785 
**To Reproduce**
1. Equip Aorpheat's Signet Ring
2. Go to Agility page
3. Unequip Aorpheat's Signet Ring
4. Note that the Course breakdown values will update, but the individual obstacles do not.

**Expected behavior**
Equipping/unequipping an item that modifies agility xp or gp gains should update the individual obstacle displays.

**Browser**
Browser agnostic bug.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Should be fixed in the next hotfix
