### ISSUE TITLE
Minor: Aorpheat's Signet Ring providing bonuses that differ from description

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#814]
**Describe the bug**
Aorpheat's Signet Ring has modifier data that differs from what the description says:
"+100% GP granted from all sources except Alt. Magic and Item Selling, +5% chance to obtain double loot from slain monsters or Thieving, +10% chance to gain double resources from any skill."

The modifers give:
```js
    modifiers: {
      increasedChanceToDoubleLootCombat: 5,
      increasedChanceToDoubleItemsSkill: [[CONSTANTS.skill.Thieving, 5]],
      increasedChanceToDoubleItemsGlobal: 10,
      increasedGPFromAgility: 100,
      increasedGPFromMonsters: 100,
      increasedGPFromThieving: 100,
    },
```

As a result it is giving +15% chance for double items in thieving, and once issue #809 is fixed will be giving +15% chance to double loot from monsters.

**Fix**
The modifiers should be adjusted so the combat and thieving bonuses are negative. That way the total will be 5% for them.
```js
    modifiers: {
      decreasedChanceToDoubleLootCombat: 5,
      decreasedChanceToDoubleItemsSkill: [[CONSTANTS.skill.Thieving, 5]],
      increasedChanceToDoubleItemsGlobal: 10,
      increasedGPFromAgility: 100,
      increasedGPFromMonsters: 100,
      increasedGPFromThieving: 100,
    },
```

**Browser**
Browser agnostic bug.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixed in upcoming hotfix
