### ISSUE TITLE
Prayer does not work at all in Golbin Raid

### ISSUE THREAD

**Issue by Erico9002** [MelvorIdle/melvoridle.github.io#815]
**Describe the bug**
You do not gain prayer points at the end of the wave. I'm not even sure if prayer works at all to be honest.

**To Reproduce**
Go into golbin raid and complete a wave. Even with prayer unlocked, you will not gain prayer points on completing the wave.

**Expected behavior**
You are expected to receive prayer points on completing a wave.

**Browser**
This happens cross-platform.

**Are you using any scripts?**
No

**Comment by swcisel** [comment]
I came here to report this. I'll elaborate by saying that this is the case even after purchasing one or more levels of the "Increase Prayer Points gained per Wave Completion" upgrade.

**Comment by Mackabre** [comment]
![Goblin Raid prayer points](https://user-images.githubusercontent.com/81534605/112767905-7bef8480-8fd6-11eb-9e51-3273133191c4.gif)

**Comment by MelvorIdle** [comment]
Should be fixed in next major update. Feel free to reopen if not
