### ISSUE TITLE
[Minor, Visual] Cloudburst Staff icon missing

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#817]
**Describe the bug**
The Cloudburst Staff is missing an icon in Milestones, Magic.

**To Reproduce**
1. Go to Milestones
2. Click on Magic
3. Scroll down to Cloudburst Staff

**Expected behavior**
For the image to load

**Screenshots**
![](https://i.imgur.com/6ABP9Vs.png)

**Browser**
Chrome/Firefox

**Console output**
Failed to load resource: the server responded with a status of 403 ()
https://cdn.melvor.net/core/v018/assets/media/bank/cloudburst_staff.png

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
