### ISSUE TITLE
Wasted prayer points

### ISSUE THREAD

**Issue by someoneyouspite** [MelvorIdle/melvoridle.github.io#818]
**Describe the bug**
Prayer points are consumed when toggling a prayer off.

**To Reproduce**
1. Initiate a fight with a monster.
2. Turn a prayer on.
3. Turn a prayer off.

**Expected behavior**
Prayer points should only be consumed when damage is dealt/received.
The current behavior results in accidental wasted prayer points.

**Screenshots**
N/A

**Browser**
Chrome

**Console output**
N/A

**Are you using any scripts?**
N/A

**Comment by swcisel** [comment]
This seems to be a duplicate of #801

**Comment by someoneyouspite** [comment]
This does seem to be the case, my fault for only searching for duplicates in open issues. Ideally though an issue shouldn't be closed until a fix has been pushed to production and tested.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
