### ISSUE TITLE
Slayer skill

### ISSUE THREAD

**Issue by Eusmusia** [MelvorIdle/melvoridle.github.io#82]
Adding in the Slayer skill.

As joked about in the Suggestions of the Discord, this skill would give you various tasks of hunting down monsters in various areas. These tasks would be a range from a small amount up to a large amount and will varying depending on Combat level (which would be added with this skill).

Slayer tasks will reward various items and Slayer Points. Slayer Points would be used in a special shop that will unlock blocking certain monsters (searchable), priority tasks (searchable) and unlocking a new item: the Slayer Helm.

The Slayer helm would increase damage and accuracy for all 3 combat styles while fighting your slayer task monster, similar to Old School Runescape and Runescape 3. The Slayer helm would be upgraded in terms of dmg% and accuracy% by using items obtained from new monsters.

Certain monsters would require a certain slayer level to harm, also similar to how OSRS/RS3 does slayer. New items introduce would be items like an Abyssal Whip style item, items similar to Leaf-bladed weapons that are only used to certain monsters due to immunity from other weapons/damage types, etc. New NPCs would be high level monsters like demons, new dragons, and various lower level NPCs.

**Comment by mrDLSable** [comment]
I support the idea of this skill. Especially in combination with the combat log this would be amazing.
