### ISSUE TITLE
Steam version not calculating offline mining progress correctly

### ISSUE THREAD

**Issue by kazmcdemon** [MelvorIdle/melvoridle.github.io#820]
**Describe the bug**
Leaving a character on mining and going offline will result in less XP, mastery and resources than expected when returning to that character. 

**To Reproduce**
1. Click Dragonite
2. Load a different character
3. Load the mining character after multiple few hours
4. Upon loading, your offline progress will result in receiving roughly 200 dragonite ore, a few thousand XP, and very little mastery points. The rock will be depleted.

This was tested with level 98 mining, half-full mastery pool, hardcore mode, dragon pickaxe, and 7/80 bank slots open.

**Expected behavior**
The resulting mastery, XP, and resources should be much higher after a few hours offline. But the dragonite rock has been at mastery 75 for me for a day or two on my hardcore character.

**Screenshots**
![image](https://user-images.githubusercontent.com/76035856/110989267-7c292800-8326-11eb-935e-bb9d057eccd6.png)

**Browser**
Steam

**Console output**
N/A

**Are you using any scripts?**
N/A

**Comment by cassiohmp** [comment]
I got this one too. Mining is like 3x slower than it should be when offline. The only similarity is that my char is also Hardcore. It doesn't happen to my standard char.

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
