### ISSUE TITLE
Minor: Combat stat tracking is occuring for empty equipment slots

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#821]
## Describe the bug
Due to several errors in combat.js Combat statistics are added to Normal Logs. This is the source of issue #539, but full resolution to that issue would require erasing the bad statistics as well.
### In combat.js replace all:
- [x]  Replace all `itemStats[equippedItems[CONSTANTS.equipmentSlot.Weapon]] !=` with `equippedItems[CONSTANTS.equipmentSlot.Weapon] !=`
- [x] Replace all `itemStats[equippedItems[CONSTANTS.equipmentSlot.Quiver]] !=` with `equippedItems[CONSTANTS.equipmentSlot.Quiver] !=`

**Expected behavior**
Combat statistics should not be added to Normal logs.

**Browser**
Browser agnostic bug.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
