### ISSUE TITLE
"View All Global Active Passives from Agility" not updating obstacle reductions

### ISSUE THREAD

**Issue by cmcruzer** [MelvorIdle/melvoridle.github.io#822]
**Describe the bug**
After an obstacle reaches level 99, while on and remaining on the Agility screen, the displayed list of all active passives after clicking the "View all Global Active Passives from Agility" button does not reflect the newly 99'd obstacle reductions.

**To Reproduce**
1. Go to Agility Screen
2. On an obstacle with a negative active passive (such as Heat Trap), spend Mastery XP to make that obstacle level 99
3. Click on "View All Global Active Passives from Agility"
4. See error (image attached)

![image](https://user-images.githubusercontent.com/7342722/111015098-bf0dee80-836c-11eb-883e-88bb824850a6.png)

**Expected behavior**
I would expect the list of active passives to reflect the correctly halved negative attributes.

**Screenshots**
Attached

**Browser**
Steam

**Console output**
N/A

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
I believe this is fixed in the coming update
