### ISSUE TITLE
Clean Up Unused Global Variables and Functions

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#823]
# Clean Up Unused Global Variables and Functions
## Why are you suggesting this?
The codebase contains a lot of dead code that makes readability and maintenance harder.
## How does your suggestion benefit the game?
It will make the game's files load faster, and reduce bandwidth usage by reducing their size.
## File-by-File Analysis of what can be removed
Using eslint I found candidate unused variables. From there I manually checked to make sure they weren't being used in any HTML. (Obviously some of these are WIP variables, or may be used in some event that isn't active, so feel free to remove at your discretion)
### main.js
- [x] `var birthday = true;`
- [x] `var announcementID = '';`
- [x] `var mapLoaded = false;`
- [x] `var playerStatsPlayFab = {};`
- [x] `var menuitems = {`
- [x] `function masteryNotify(mastery, skill, level) {`
- [x] `function notifyBirdNest(message, type) {`
- [x] `function notifyGemRock(message) {`
- [x] `function timestamp(achievement, skill = null, itemID = null) {`
- [x] `function loadProfile() {`
- [x] `function httpsCheck() {`
- [x] `function resetTutotialTips() {`
- [x] `function rollForPetsOffline(`
- [ ] `function getMiscMedia(localURL) {`
- [ ] `function resetSteamAchievements() {`
- [ ] `function agreeToNotice(noticeID) {`
- [x] `function getOfflineRhaelyxActions(totalActions, useStones = true) {`
- [x] `var currentBank = 0;` Unused, except for in `allVars`. Can likely be removed to reduce save file size.
- [x] `var itemLogBuilt = false;`Unused, except for in `allVars`. Can likely be removed to reduce save file size.
### save.js
- [x] `var gameSaved = false;`
- [x] `function getSaveRaw() {`
- [x] `function initiateLoad() {` Present but commented out
- [x] `function getSaveTimestamp(save) {`
- [x] `function getSaveTotalXP(save) {`
- [x] `function getSaveDetails(save) {`
- [x] `function setBackupSave() {` Present but commented out.
### updates.js
- [x] The entire file is unused. Can be removed from index.html
### pets.js
- [x] `var offlinePet = false;` This variable is "used" in that it is set to different values in `updateOffline`, but otherwise does not contribute to any logic.
### shop.js
This file probably has a lot more than I listed. Once the deprecated functions are removed the list can be updated.
- [x] `var cookingRangeCost = 500000;`
- [x] `const pickaxeBonus = `
- [x] `const pickaxeBonusSpeed`
- [x] `const rodBonusSpeed`
- [x] `const dhideCost = [`
- [x] `function buyAutoSlayer(confirmed = false) {`
- [x] `function updateShopPrices() {`
- [x] `function upgradeBank(confirmed = false) {`
- [x] `function upgradeAxe(confirmed = false) {`
- [x] `function upgradeRod(confirmed = false) {`
- [x] `function upgradePickaxe(confirmed = false) {`
- [x] `function upgradeMultiTree(confirmed = false) {`
- [x] `function upgradeCookingFire(confirmed = false) {`
- [x] `function buyBowstring(confirmed = false) {`
- [x] `function buyLeather(confirmed = false) {`
- [x] `function buyDhide(dhide, confirmed = false) {`
- [x] `function buyCompost(confirmed = false) {`
- [x] `function buyFeathers(confirmed = false) {`
- [x] `function buyPartyHat(confirmed = false) {`
- [x] `function loadSlayerShop() {`
- [x] `function updateSlayerShop() {`
- [x] `function buySlayerItem(itemID, confirmed = false) {`
- [x] `function upgradeAutoEat(confirmed = false) {`
- [x] `function upgradeEquipmentSet(set, confirmed = false) {`
- [x] `function buyItem(itemID, confirmed = false) {`
- [x] `function upgradeEquipmentSwap(confirmed = false) {`
- [x] `function buyGodUpgrade(id, confirmed = false) {`
### bank.js
- [x] `const bankVersion = 3;`
- [x] `var tokenInterval = null;`
- [x] `let itemSaleGP = [];`
- [x] `var bankTokensClaimed = 0;`
- [x] `function listener() {`
- [x] `function clearItemInView() {`
- [x] `var itemInView = null;` Variable is only ever set to values. Reference also needs to be removed from `sellItem`
- [x] `function convertDefaultItemTabs() {`
### settings.js
- [x] `var autoSave = true;`
- [ ] `function adjustZoom(zoomLevel) {`
### cloud.js
- [x] `var cloudCheck = false;`
- [x] `var cloudSync = null;`
- [x] `var isPatreon = false;`
- [x] `function showForm(id) {`
- [x] `function getSync(playFab = false) {` Is referenced in commented out code
- [x] `function syncSave() {`
- [x] `function viewMelvorCloudProfile() {}`
- [ ] `function cloudSaveAndExit() {`
### woodcutting.js
- [x] `var axeBonusSpeed`
- [x] `var treeAutoHandler = [`
### fishing2.js
- [x] `function updateFishingMasteryArray() {`
### cooking.js
- [x] `var isFireBurning = false;`
- [x] `var cookingCount;`
- [x] `var cookingCache = null;`
- [x] `var upgradedToFire = false;`
- [x] `var cookCount = 0;`
- [x] `function lightCookingFire(upgradeToFire = false) {`
### rockHitting.js
- [x] `var miningItemID = [];`
- [x] `const gemSpawnInterval = 60000;`
- [x] `const gemXP = 500;`
### combat.js
- [x] `var activeSpecialAttacks = {};`
- [x] `var activeCombatPassives = {};`
- [x] `var runeCheck = [];`
- [x] `var useSpecialAttack = false;`
- [x] `var autoEatNotify = true;`
- [x] `var chanceToDoubleLoot = 0;`
- [x] `var damageMultiplier = 1;`
- [x] `var enemyAttackSpeedMultiplier = 1;`
- [x] `var bleedMultiplier = 0;`
- [x] `var enemySlowTimer = null;`
- [x] `var ammoPreservation = 0;`
- [x] `var equipmentSetCount = 0;`Old save variable. Requires cleanup in a number of other places.
- [x] `var autoEatTier = 0;`
- [x] `var playFabCounter = 0;`
- [x] `var combatModifiers = {};`
- [x] `var specialAttackModifiers = {};`
- [x] `var xmasPresentTimer = 0;`
- [x] `function updatePlayerMarkOfDeath() {`
- [x] `function updatePlayerValues() {`
- [x] `function updateRunes() {`
- [x] `function viewCombatDetails(combatArea) {`
- [x] `function viewDungeonDetails(dungeon) {`
- [x] `function loadDungeons() {`
- [x] `function loadCombatAreas() {`
- [x] `function switchView() {`
- [ ] `var prayerBonusHitpoints = 1;` Also needs to be removed from `togglePrayer`
- [x] `var previousSlayerTask = null;` Also needs to be removed from `updateSlayerTask`
- [x] `function updateDebuffs() {`
- [ ] `function togglePlayerContainer() {`
### mastery.js
- [x] `function updateMasteryArrays() {`
- [x] `function updateCurrentMastery(skill, masteryArray) {`
- [x] `function showMasteryProgress(skill, masteryArray) {`
- [x] `function repairMastery() {`
### mastery2.js
- [x] `function setMasteryProgressBar(id, progress, style = 'bg-info') {`
- [x] `function getMasteryLevelFromCache(skill, masteryID) {`
### farming.js
- [x] `var seedContainer;`
- [x] `var goldDeductionTracker = 0;`
### crafting.js
- [x] `var craftingReqCheck = [];`
### runecrafting.js
- [x] `var runecraftingReqCheck = [];`
### herblore.js
- [x] `function getHerbloreMasteryID(itemID, tier) {`
### golbinraid.js
- [x] `var raidShopUpgrades = [];`
- [x] `var isWeaponAlt = false;` Needs to be removed from `resetGolbinEquipment` as well
- [x] `var altWeaponSelected = false;` Needs to be removed from `resetGolbinEquipment` as well
### agility.js
- [x] `function updateAgilityPassiveBonuses() {`
- [x] `function storeAgilityPassiveBonus(bonus, value) {`

**Comment by MelvorIdle** [comment]
Wow, thanks so much for this.

I've gone through and combed 98% of this. Some of the function seen as "not used" are actually used on Mobile or Steam versions of the game, but grabbing the source code from the main domain won't show you where these functions are used.
