### ISSUE TITLE
Low: Pirate's Lost Ring effect is inconsistent with other xp bonuses

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#824]
**Describe the bug**
Currently the pirate's lost ring states that it gives '+15% Fishing XP when equipped.'.

This is inconsistent with the other XP modifiers in the game, as it is currently hard-coded as a multiplicative bonus to fishing xp.

**Expected behavior**
Pirate's lost ring should be additive with other XP modifiers.

**Implementation checklist**
- [ ] Add modifier data to Pirates Lost Ring in items.js
```js
    modifiers: {
      increasedSkillXP: [[CONSTANTS.skill.Fishing,15]]
    }
```
- [ ] Remove the old property from the items array `fishingBonusXP: 15`
- [ ] Remove the hardcoded implementation in fishing.js
```js
          if (equippedItems.includes(CONSTANTS.item.Pirates_Lost_Ring))
            xpToAdd *=
              1 + items[CONSTANTS.item.Pirates_Lost_Ring].fishingBonusXP / 100;
```
- [ ] Remove the hardcoded implementation for offline progress in main.js
```js
                if (equippedItems.includes(CONSTANTS.item.Pirates_Lost_Ring))
                  xpToAdd *=
                    1 +
                    items[CONSTANTS.item.Pirates_Lost_Ring].fishingBonusXP /
                      100;
```
**Browser**
Browser agnostic bug.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Looks like I forgot to switch this one over, fixed in upcoming update
