### ISSUE TITLE
Visual bug on Android app

### ISSUE THREAD

**Issue by Inwah** [MelvorIdle/melvoridle.github.io#825]
**Describe the bug**
It's like the bottom part of the UI has moved up in the screen (HP bar in combat and gathering resources/items pop-up). 

**To Reproduce**
Doing any skill, practically. 

**Expected behavior**
The UI should be at bottom of screen. 

**Screenshots**
![Screenshot_20210313_010538](https://user-images.githubusercontent.com/80573673/111025559-c4cdf900-8399-11eb-806b-b6895c7e905d.jpg)
![Screenshot_20210313_010631](https://user-images.githubusercontent.com/80573673/111025561-c5ff2600-8399-11eb-8cf6-7350428f89e4.jpg)

**Browser**
Not using PC, it happens on Android 10.

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
No scripts.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
