### ISSUE TITLE
Insane amount of damage

### ISSUE THREAD

**Issue by batkiller1** [MelvorIdle/melvoridle.github.io#826]
**Describe the bug**
Unsure what the problem is but monsters seem to just spam attack.

**To Reproduce**

Unable to reproduce. My best guess is that it started in the fire god dungeon.

**Expected behavior**

**Screenshots**
Video: 
https://discord.com/channels/625838709203271680/625840209531240469/820441068625068093

**Browser**

Chrome on Windows | 89

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Semi: auto eat

**Comment by MelvorIdle** [comment]
I believe this has been hotfixed recently
