### ISSUE TITLE
Ku-tul's "Curse of the Deep" is unavoidable (indicator says its avoidable)

### ISSUE THREAD

**Issue by INoob2000** [MelvorIdle/melvoridle.github.io#827]
**Describe the bug**
Curse of the Deep (Ku-tul's attack) is unavoidable. I stared at this for like 5 mins to see if the skill would ever miss—it didnt. Tried using the protect from magic prayer and it still couldnt be avoided. 

**To Reproduce**
1. Fight ku-tul
2. Notice that Curse of the Deep never fails to miss
3. Note: You will see misses, but those will be from the basic attack or elusiveness, probably not from curse of the deep

**Expected behavior**
The special attack description states the attack should be avoidable.

**Screenshots**
Probably not too helpful, but heres a shot of the attack not missing
![image](https://user-images.githubusercontent.com/80449991/111057221-f51da200-8442-11eb-9526-750950b9106e.png)

**Browser**
I've reproduced the bug on firefox and mobile

**Console output**
Sorry, dont know how :(

**Are you using any scripts?**
No scripts being used

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
