### ISSUE TITLE
Minor: Pet Ty rolling is bugged when through online agility

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#828]
**Describe the bug**
The mastery pet Ty uses a skill level of 1 when rolled through online Agility.
This is due to a typo in agility.js
```js
        rollForPet(
          21,
          interval *
            (1 + getMasteryPoolProgress(CONSTANTS.skill.Agility) / 100),
          false,
          CONSTANTS.skill.Agiliy // Typo here
        );
```

**Fix**
- [ ] Change `CONSTANTS.skill.Agiliy` to `CONSTANTS.skill.Agility` in `startAgility` in agility.js

**Browser**
Browser agnostic bug.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
