### ISSUE TITLE
Aorphet's Signet Ring reduces doubled combat loot chance by 5%

### ISSUE THREAD

**Issue by CaptainJim** [MelvorIdle/melvoridle.github.io#829]
**Describe the bug**
Aorphet's Signet Ring reduces the doubled combat loot chance by 5%, rather than increasing it by 5%.

**To Reproduce**
Kill green dragons with just Aorphet's Signet Ring as the only source of combat loot doubling. 5% of the time, you should receive 2 Dragon Bones instead of 1. Notice that you never receive doubled loot and receive 1 Dragon Bones every time.
Then kill green dragons with both Aorphet's Signet Ring and Chapeau Noir as the only sources of combat loot doubling. 15% of the time, you should receive 2 Dragons Bones instead of 1. Instead, it only happens 5% of the time. Verified by killing green dragons over night, receiving 3197 bones in 3047 kills (1.049 bones/kill instead of 1.15).
Finally, kill dragons with just Chapeau Noir equipped, and notice that the expected number of doubled combat drops occurs. That indicates the problem lies with Aorphet's Signet Ring.

**Expected behavior**
Aorphet's Signet Ring should increase the chance of doubled combat loot by 5%, rather than decrease it.

**Browser**
Firefox 86.0

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
None

**Comment by CaptainJim** [comment]
The problem appears to be related to issue #814 and #809.
The bonuses for the ring are reversed to compensate for the global doubling fix, but global doubling combat loot is broken.
Specifically, both dropBones() and dropLoot() in combat.js don't use increasedChanceToDoubleItemsGlobal when rolling for loot (lines 6165 and 6232).

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
