### ISSUE TITLE
Item grades / quality

### ISSUE THREAD

**Issue by mrDLSable** [MelvorIdle/melvoridle.github.io#83]
I suggest implementing a system of item grades. In my opinion this would improve the longevity of the content in the game.

The system would give every item crafted or looted a quality which would influence the boosts given by the item. And certain recipes would require items of at least a certain quality.

The qualities could for example be like this:

1. Very Poor: -50% effectiveness
2. Poor: -25% effectiveness
3. Common
4. Rare: +10% effectiveness
5. Epic: +25% effectiveness
6. Legendary: +50% effectiveness

As the mastery of crafting a certain item increases, so does the chance of creating a higher quality item.

**Comment by Eusmusia** [comment]
So typical RPG Fashion? I support this. This will also make boss runs more useful instead of getting the same item over and over again with no change except to sell them for gp.

**Comment by mrDLSable** [comment]
Exactly. And of course for full completion of the completion log you will have to get legendary quality of the item.

**Comment by Eusmusia** [comment]
I'd even go as far as increasing sell values as well, not just combat stats. Selling a Legendary Quality Ancient Sword would be worth more than a Poor Ancient Sword.

And I agree with the log as well.

**Comment by mrDLSable** [comment]
Great idea.

Tying it with a WoW style enchanting skill would also be great. Destroy items to gain materials which can be used to enchant other items. Perhaps even allow you to upgrade the quality of an item to a certain level.

**Comment by Eusmusia** [comment]
I was thinking of a Skill for just that tbh. I was about to type it out but decided against it. It would function very similar to how you just mentioned but on a deeper level.
