### ISSUE TITLE
Woodcutting "Multi-Tree" Offline XP Calculation: Only one Tree gives XP. Tested a few times

### ISSUE THREAD

**Issue by christophdaniel** [MelvorIdle/melvoridle.github.io#830]
multi-tree woodcutting:
Yew tree (80xp/6sec) + Magic tree (100xp/10sec): offline for 106min
XP gained: **84617**

rough calculation: 80/6 * 106min*60 = **84800**xp
-> yew tree XP OK, magic tree XP = zero?

**Comment by MelvorIdle** [comment]
Fixed in next major update
