### ISSUE TITLE
"Attempts at username changes" statistic is wrong

### ISSUE THREAD

**Issue by gmiclotte** [MelvorIdle/melvoridle.github.io#832]
**Describe the bug**
The count is increased by 1 when clicking "Change Character Name" (which just opens an input form, it doesn't change the name yet), and then is again increased by 1 when actually changing the name and confirming the name change with "Ok". 

**To Reproduce**
1. Open the statistics page, under "General" note the number next to "Attempts at username changes"
2. Open the account dropdown (top right of the screen)
3. Click "Change Character Name"
4. See the count increase by 1
5. [optional] pick a new name
6. [optional] click "Ok"
7. [optional] See the count increase by 1 again

**Expected behavior**
The count is only increased when confirming the name change.

**Screenshots**
Count is at 0 originally, then we click a button
![2021-03-14_20-31](https://user-images.githubusercontent.com/12995926/111081751-1fd02f00-8505-11eb-95df-9b9d058bf53a.png)

Count is at 1 after the first click, let's confirm a name change now
![2021-03-14_20-31_1](https://user-images.githubusercontent.com/12995926/111081760-29599700-8505-11eb-8614-db350889ecbb.png)

Count is now at 2
![2021-03-14_20-31_2](https://user-images.githubusercontent.com/12995926/111081767-35455900-8505-11eb-80d3-925fa90e2c0e.png)

**Browser**
Chromium Version 89.0.4389.82

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
This will be addressed in statistics 2.0
