### ISSUE TITLE
Minor: Activating prayers does not always change the text of Prayer in the sidebar green

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#833]
**Describe the bug**
When activating a prayer the Prayer in the sidebar should turn green, but this doesn't work for any of the prayers that were transitioned to using the new modifier system.

**To Reproduce**
1. Activate a prayer that uses modifiers.
2. The colour of Prayer in the sidebar does not change.

**Expected behavior**
When the player has prayers active, Prayer in the sidebar should be green.

**Screenshots**
Example of prayer being active but the sidebar text not being green:
![image](https://user-images.githubusercontent.com/58208131/111084044-2dba8b80-84d6-11eb-8912-171b31fa43a2.png)
Example of it being green for a prayer that was not converted to the new modifier system:
![image](https://user-images.githubusercontent.com/58208131/111084077-45920f80-84d6-11eb-90df-122a4f4a6b79.png)

**Bug Source**
Seems to be an issue with `togglePrayer` in combat.js
The global variable `isPrayer` does not seem to be consistently set to true when there are prayers active.
**Browser**
Browser agnostic bug.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
