### ISSUE TITLE
Agility XP frozen in Adventure Mode

### ISSUE THREAD

**Issue by TheCurti** [MelvorIdle/melvoridle.github.io#835]
**Describe the bug**
In adventure mode, Agility XP is not increasing online or offline.  When logging back in it will say "You gained xxx Agility XP" but the amount of XP does not change.  Mastery and GP are still increasing but the XP is stuck.

**To Reproduce**
I have had this happen to an adventure mode save, then decided to restart because it was broken and I assumed it was my save.  The first time I noticed the error I had obstacles 1-3 active, this time I just have obstacles 1 & 2 active.

**Expected behavior**
I expected my Agility XP to increase

**Screenshots**
![1](https://user-images.githubusercontent.com/80685609/111147412-912fe080-85de-11eb-9e72-cd84e1bafc7d.jpg)
![2](https://user-images.githubusercontent.com/80685609/111147426-97be5800-85de-11eb-85e8-f5bf6610ef43.jpg)

**Browser**
Chrome on desktop

**Console output**
That's a lot of text, I'll skip this for now...

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
You have reached the skill level cap that is based on your combat level. You need to increase your combat level to increase the skill levels
