### ISSUE TITLE
Aeris can use her basic attack, but only does so very rarely.

### ISSUE THREAD

**Issue by TempestMK7** [MelvorIdle/melvoridle.github.io#838]
Managed to die in Air God Dungeon to the final boss when my DR and auto-eat threshold should have been high enough to prevent that.  I had no idea how I died until I went back in the next day and watched the fight more closely.  

Aeris used her basic attack one time during the 2-4 minute fight against me, which explains how I could have died previously.  Her special attack probabilities all add up to 100%, so she shouldn't be able to use her basic attack.  Not sure if this is a bug or known behavior or what, but I thought I would report it.  

Got a screenshot of it happening again the next time I went into the fight.  It seems to be happening less than 1% of the time.

![Aeris Attack](https://user-images.githubusercontent.com/23249127/111208810-3cb64200-8599-11eb-9547-07d25bdda696.PNG)

**Comment by MarcelJulian** [comment]
No screenshots, but I encountered the same problem; posted a [Reddit post](https://www.reddit.com/r/MelvorIdle/comments/m2r3g5/kept_dying_in_air_god_dungeon_despite_having/)  about this. The last comment also said that this also occurs to other enemies, such as Into The Mist's 3 bosses.

**Comment by coolrox95** [comment]
Seems there is a more general issue with `enemySpecialAttacks` that have `activeBuffs: true,` but do not have a `activeBuffTurns` value. In this circumstance the enemy gets `combatData.enemy.buffTurns` set to the `attackCount` property of the special, which is far longer than just the time that the attack is going off.
```js
      if (
        enemySpecialAttacks[specID].activeBuffTurns !== null &&
        enemySpecialAttacks[specID].activeBuffTurns !== undefined
      )
        combatData.enemy.buffTurns =
          enemySpecialAttacks[specID].activeBuffTurns;
      else combatData.enemy.buffTurns = enemySpecialAttacks[specID].attackCount;
```
As a result Cyclone is being replaced with a normal attack if it is rolled again within 7 subsequent enemy attacks.

Making the attack default set to 2 buff turns also doesn't quite fit the description as the buff would persist for 1 attack. A value of 1 would just make it do nothing, so some additional logic is needed to make the buff only last as long as the attack itself.

- [ ] Add logic to the end of a multi-hit special to remove buffs that should only last as long as the attack does.
```js
            enemyAttackTimer = setInterval(function () {
              attackPlayer(enemySpec, specID);
              count++;
              if (
                (count >= enemyAttackCount ||
                  combatData.player.hitpoints <= 0) &&
                combatData.enemy.hitpoints > 0
              ) {
                clearInterval(enemyAttackTimer);
                if (combatData.enemy.intoTheMist) {
                  combatData.enemy.intoTheMist = false;
                  combatData.enemy.increasedDamageReduction = 0;
                  activateEnemyBuffs();
                }
                // Insert some extra logic to remove the active buffs when the spec finishes
                const specialAttack = enemySpecialAttacks[specID];
                if (specialAttack.activeBuffs && specialAttack.activeBuffTurns === undefined) {
                  combatData.enemy.activeBuffs = false;
                  removeEnemyBuffs();
                }
                // End of inserted logic
                let enemyCombatStatus = checkCombatStatus(0);
                //Repeat if not ded
                if (enemyCombatStatus) startCombat(2);
                else {
                  //DEATH
                  monsterStats[enemyInCombat].stats[3]++;
                  stopCombat(true, true);
                }
              }
            }, count * attackInterval);
          }
```
- [ ] Change the default buffturns to be 2
```js
      if (
        enemySpecialAttacks[specID].activeBuffTurns !== null &&
        enemySpecialAttacks[specID].activeBuffTurns !== undefined
      )
        combatData.enemy.buffTurns =
          enemySpecialAttacks[specID].activeBuffTurns;
     // Changed the default for when not defined to be 2
      else combatData.enemy.buffTurns = 2;
```

Applying those changes and making a Black Dragon have the attack appears to produce the desired effect:
```js
enemySpecialAttacks[7].chance = 50;
MONSTERS[66].hasSpecialAttack = true;
MONSTERS[66].specialAttackID = [7];
```
The enemy is buffed when the attack is happening (evasion values go up), and as soon as it finishes they go back to normal.
