### ISSUE TITLE
Magic Armor bonus Adventure mode

### ISSUE THREAD

**Issue by Nemo296** [MelvorIdle/melvoridle.github.io#839]
**Describe the bug**
Magic gear is not providing appropriate bonus on Adventure mode.

**To Reproduce**
1. Equip Magic gear
2. See bonus applied is only +20 damage

**Expected behavior**
On Adventure mode, mobs HP is x10, so should the bonus not be +50 per piece?

**Screenshots**
![image](https://user-images.githubusercontent.com/10834785/111231587-ed373c80-85bf-11eb-80c6-c6a6bf954a49.png)

**Browser**
Chrome Version 89.0.4389.90 (Official Build) (64-bit)

**Console output**
![image](https://user-images.githubusercontent.com/10834785/111231697-1526a000-85c0-11eb-97ee-32645b52e4af.png)

**Are you using any scripts?**
No scripts, vanilla melvor.

**Comment by MelvorIdle** [comment]
Thanks, this is fixed in the next update. It was only visual though with the description. The correct amount of damage was still being applied
