### ISSUE TITLE
Minor: Simultaneous death of Enemy and Player in combat does not kill player

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#841]
**Describe the bug**
When an enemy attacks the player and dies to Decay, while also killing the player, combat does not stop. Instead the next enemy spawns, and the player can cheat death by eating food/having hitpoint regeneration go off.

**To Reproduce**
1. Modify an enemy to produce the edge case:
```js
enemySpecialAttacks[10].chance = 100;
MONSTERS[0].hasSpecialAttack = true;
MONSTERS[0].specialAttackID = [10];
```
2. Setup a breakpoint for the enemy attack:
![image](https://user-images.githubusercontent.com/58208131/111240604-2fad4900-85c1-11eb-8a20-fae9bd2f892b.png)

3. Setup the player to be using the decay curse
3. Fight the black knight
4. At the breakpoint set the player and enemy to near death
```js
 combatData.player.hitpoints = 1;
 combatData.enemy.hitpoints = 1;
```
5. Let the game continue.
6. Note that the player does not die, and we are left with a console error.

It seems that by the time the player death check is happening an enemy is spawning in. Thus, `enemyInCombat` is `undefined` and the game errors out, preventing `stopCombat` from getting called to kill the player.
**Expected behavior**
The player should die when they kill the enemy at the same time.

**Screenshots**

**Browser**
Browser agnostic bug.

**Console output**
![image](https://user-images.githubusercontent.com/58208131/111240721-5ff4e780-85c1-11eb-8dc7-f81dac283939.png)

**Are you using any scripts?**
None, other than the setup for the edge case.

**Comment by MelvorIdle** [comment]
I believe this is fixed in the next update
