### ISSUE TITLE
[Android] Bird Nest doubling From Woodcutting Milestone 4 not applying.

### ISSUE THREAD

**Issue by cognitive-rift** [MelvorIdle/melvoridle.github.io#842]
**Describe the bug**
When playing on Android and resuming play from a background state, Bird Nest Acquisition is not doubled.

**To Reproduce**
1. On Android, with a character that has 95% mastery pool or above, Start woodcutting.
2. Put the Melvor Idle app into the background with back or other method.
3. Allow enough time to pass for a Birds Nest to likely be found.
4. Open the app from the background to see "While you were gone" message. Observe 50% of the time the amount of birds nest is odd, which should be impossible if the Nests are found in twos.

**Expected behavior**
A doubled, and thus even amount of Birds Nests to be found while AFK.

**Browser**
Android 0.03.4

**Console output**
N/A

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Related to #794
