### ISSUE TITLE
Make standard steam achievements achievable in any game mode

### ISSUE THREAD

**Issue by ilysia** [MelvorIdle/melvoridle.github.io#843]
The exact suggestion:
Remove the suffix "in standard mode" from every achievement that has it, because it does not benefit the game design and has no purpose.
For example:
"Defeat Malcs, the Guardian of Melvor in the Volcanic Cave in Standard Mode" -> "Defeat Malcs, the Guardian of Melvor in the Volcanic Cave"
This change makes even more sense with Adventure mode in the game.

Why:
It's incredibly annoying to do everything twice for some additional achievements, even if you already did it in hardcore. It makes perfect sense for a game to have hardcore-only achievements, especially if they resemble the hardcore nature of the game-mode itself. (like beating a specific dungeon in HC specifically.)
But I think it makes no sense to have achievements like this
'Reach Level 99 for Crafting in Standard Mode', because the standard does not make it more challenging. Just make this a general achievement for reaching lvl 99 crafting skill in any game mode.

**Comment by MelvorIdle** [comment]
This will be added/changed in an upcoming update :)

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
