### ISSUE TITLE
Add new agility steam achievement

### ISSUE THREAD

**Issue by ilysia** [MelvorIdle/melvoridle.github.io#844]
Add new achievements to the game:

- [ ]  "Reach Agility lvl 99 in any game mode" Name suggestion: Parkour Master
- [ ]  "Build every agility obstacle at least one" (optional)

Why:
Good achievements are fun. With the agility skill added, the lvl99 achievement feels missing. It's good to keep it consistent and it's probably not a big amount of work.

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
