### ISSUE TITLE
Add adventure mode steam achievments

### ISSUE THREAD

**Issue by ilysia** [MelvorIdle/melvoridle.github.io#845]
Why:
Adventure mode is incredibly fun. Let's make it even more fun by adding some global goals (achievements)

My personal ideas (feel free to skip or add new ones):
- [ ] Unlock all locked skills in Adventure Mode (Skillful)
- [ ] Unlock your first skill in Adventure Mode (A wise choice)
- [ ] Reach combat level 99 in Adventure Mode (Maximalist) //This could be specific to this game mode because combat level has a special function here.
- [ ] Reach combat level 99 without ever dying (Safe place)
- [ ] Unlock all skills in adventure mode, after unlocking all combat skills first

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
