### ISSUE TITLE
Ammend Enemy Special Attack descriptions to indicate that a normal attack is performed if the enemy is already buffed

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#847]
# Why are you suggesting this?
Currently, Enemy Special Attacks that buff the enemy will default to a normal attack if the enemy is already buffed. This is not communicated in game, and in some cases has contrary information in the special attack description.
# How does your suggestion benefit the game?
Many players are confused by this hidden mechanic, so adding it to the description should help clear that up.
# Implementation
I suggest adding something like: `If already buffed, perform a normal attack instead.` to the end of the description 
- [ ] Change the description of `Stone Wall` to 
```js
    get description() {
      return `Puts up a wall that provides +${
        this.increasedDamageReduction
      }% damage reduction for ${
        this.activeBuffTurns - 1
      } Attack Turns. If already buffed, perform a normal attack instead.`;
    }
```
- [ ] Change the description of `Hunter Expertise`
- [ ] Change the description of `Agility`
- [ ] Change the description of `Elusiveness`
- [ ] Change the description of `Burning Trail`
- [ ] Change the description of `Shadowstep`

**Comment by MelvorIdle** [comment]
Added in upcoming update
