### ISSUE TITLE
Tradeskill Gloves IDs and ShopIDs don't match.

### ISSUE THREAD

**Issue by kurosnow** [MelvorIdle/melvoridle.github.io#848]
In the shop.js's index array, the gloves are indexed as
Cooking [0], Mining [1], Smithing [2], Thieving [3], Gems [4]

But in the items.js, they're given the manual IDs of
Cooking [0], Mining [1], Gems [2], Smithing [3] Thieving [4]

So, shop.gloves.Gem_Gloves for example returns the Smithing gloves.

**Comment by coolrox95** [comment]
Fixed with update v0.21.
