### ISSUE TITLE
Slayer XP

### ISSUE THREAD

**Issue by Zoffax** [MelvorIdle/melvoridle.github.io#850]
**Describe the bug**

Grinding mobs off task is still granting slayer XP in slayer areas.

**To Reproduce**
1. Go to any slayer area
2. Start fighting a monster
3. Gain slayer XP for kills

**Expected behavior**
I don't believe you should be awarded slayer XP unless you're on task. I feel this cheapens the skill as a whole.

**Screenshots**
N/A

**Browser**
Mobile Alpha 1.19

**Console output**
Not sure this is accessible on mobile

**Are you using any scripts?**
No scripts are in use

**Comment by MelvorIdle** [comment]
This is intended. Monsters in Slayer areas provide base Slayer XP regardless of task or not (I think it's only half XP or less)

**Comment by ilysia** [comment]
@Zoffax 
From the wiki: "Slayer experience can be earned by killing monsters in Slayer Areas or through Slayer Tasks. Killing"
So it's extremely simple to verify that this is not a bug at all.
