### ISSUE TITLE
Leather drops from killing Cow does not stack

### ISSUE THREAD

**Issue by Lachette** [MelvorIdle/melvoridle.github.io#852]
when attacking cow for leather, the bones stack, but the leather does not. fills up loot area very fast. using Web interface. 

![image](https://user-images.githubusercontent.com/62121400/111515206-81201a00-8720-11eb-9425-87ecdbe4f762.png)

**Comment by MelvorIdle** [comment]
This is intended, and not a bug. Only bones stack.
