### ISSUE TITLE
Ranged and Magic disabled in Golbin Raids as Adventurer

### ISSUE THREAD

**Issue by MidasB28** [MelvorIdle/melvoridle.github.io#855]
**Describe the bug**
When playing Golbin Raid as an Adventurer character and you have not yet unlocked ranged or magic, they are also disabled in the Golbin Raids.

**To Reproduce**
1. Create a new character in 'Adventure Mode'
2. Click on 'Golbin Raid' and start a raid
3. Click on 'View spellbook' beneath the Menu in the combat interface
4. See error 'Skill locked - You need to unlock magic to use this'
5. After finishing a wave, Click on 'New weapon' and hopefully find a ranged or magic weapon
6. See that the weapon is not equipped and your bronze scimitar is still there

**Expected behavior**
I expected Golbin Raids to be playable in Adventure Mode, before the skills have been unlocked.

**Screenshots**
![image](https://user-images.githubusercontent.com/11226909/111563576-7d2fde80-8798-11eb-9580-5b22e867f404.png)

**Browser**
Google Chrome	89.0.4389.82 (Official Build) (64-bit) (cohort: Stable)
Revision	8d785cc4e2b89bff35f6a21710215271fb8fd782-refs/branch-heads/4389@{#1433}
OS	Windows 10 OS Version 2004 (Build 19041.867)
JavaScript	V8 8.9.255.20

**Console output**
Not too sure that's necessary in this case.

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Hotfixed pushed to live game. Alpha v0.21 (?1093)
