### ISSUE TITLE
Game not loading

### ISSUE THREAD

**Issue by Linyx-Multi** [MelvorIdle/melvoridle.github.io#856]
**Describe the bug**
When I try and create a character it just shows a mountan and then doesn't load.
I am signed into cloud when this happens.
This happens on the Steam version and Steam version website.

**To Reproduce**
1. Go to select character
2. Click on new character
3. Name character
4. Press create.
5. Game freeze on mountain

**Expected behavior**
The game should freeze on character creation.

**Screenshots**
![image](https://user-images.githubusercontent.com/33364846/111570910-a9844300-880a-11eb-8d7c-8345b8f30200.png)

**Browser**
Google chrome, Latest version.

**Console output**
Cannot open console.

**Are you using any scripts?**
No.

**Comment by SixPennyGibbon** [comment]
I have the exact same problem. Tried creating an Adventure character. Can't return to the menu to try something else. Running the game on macOS BigSur 11.2.3. 

Just bought the game, so kind of disappointed.

**Comment by gmiclotte** [comment]
Simply reloading the page fixed this for me. Reload brought me back to the character selection screen, there I could select the new character and then it properly loaded.

**Comment by MelvorIdle** [comment]
I believe this has been rectified. Should load all OK now.
