### ISSUE TITLE
Divine potions wrong effect value

### ISSUE THREAD

**Issue by gmiclotte** [MelvorIdle/melvoridle.github.io#857]
**Describe the bug**

1. Divine potions all have `increasedChanceToPreservePrayerPoints: 10` as modifier, instead of [10, 15, 20, 35] as in the description
![2021-03-18_09-13](https://user-images.githubusercontent.com/12995926/111593930-c39e3100-87ca-11eb-9501-62532e3a4687.png)

2. Divine potions apply their effect as a modifier (incorrect values, as in (1)), and then apply it again in the old way (with the correct values). See `applyModifiersToPrayerCost`

**To Reproduce**
1. Fresh account
2. equip divine potion
3. check prayer preservation as it is calculated in `applyModifiersToPrayerCost`
4. notice that it is 10 higher than expected (10% from the modifier and expected% from the old way)

Screenshot shows this in action, the first prayer preservation calculation shows the baseline on a fresh account (0)
![2021-03-18_09-20](https://user-images.githubusercontent.com/12995926/111594434-59d25700-87cb-11eb-8672-0a63a87948a7.png)

**Expected behavior**
Divine potions [I, II, III, IV] give [10, 15, 20, 35]% chance to preserve prayer points.

**Browser**
chromium and firefox

**Are you using any scripts?**
no

**Comment by MelvorIdle** [comment]
Hotfixed
