### ISSUE TITLE
Skill does not level up anymore

### ISSUE THREAD

**Issue by Oxydation** [MelvorIdle/melvoridle.github.io#858]
**Describe the bug**
After unlocking the first skill (fishing) of a new adventure character the level is stuck at 21 and 5623 exp. After multiple hours it has still the same level. The normal exp does not go up - but the Mastery exp does as normal. I do have 1.4M Mastery Exp and Mastery Lvl 90 for fishing trouts. Loading save from other devices and apps did not work (web, steam and android). Items are received normally. 

**To Reproduce**
Not sure how to reproduce this bug. I've attached the save file, which can be loaded and you can see, that the fishing level does not increase.

**Expected behavior**
Received exp is added and levels up the skill.

**Screenshots**
![image](https://user-images.githubusercontent.com/8331862/111597888-f0544780-87ce-11eb-8353-f192702529d5.png)

**Browser**
Android 11 (Mobile Version), Windows 10 (Steam and Chrome)

**Console output**
Not applicable. 
Save file: 
[savefile_lvl_bug.txt](https://github.com/MelvorIdle/melvoridle.github.io/files/6162493/savefile_lvl_bug.txt)

**Are you using any scripts?**
No scripts used.

**Comment by MelvorIdle** [comment]
You are on Adventure Mode. Skill Levels cannot go above your Combat Level.

**Comment by Oxydation** [comment]
@MelvorIdle Oh you are so right. I totally forgot that, thank you for time. It would maybe make sense to add a hint or a warning icon next to the skill level (maybe only on the skill page itself). That way the user is reminded, that the skill level is locked based on the combat level.
