### ISSUE TITLE
Diamond Luck potions decrease chance to hit

### ISSUE THREAD

**Issue by gmiclotte** [MelvorIdle/melvoridle.github.io#859]
**Describe the bug**
Diamond luck potions add additional attack rolls, but the *worst* roll is kept.

**Expected behavior**
Diamond luck potions add additional attack rolls, and the *best* roll is kept.

**Screenshots**
![2021-03-18_10-13](https://user-images.githubusercontent.com/12995926/111602401-95711f00-87d3-11eb-9b2b-4f327cb4ca01.png)
To the left: the old implementation, if `chanceToHit` is smaller than the player accuracy, then the attack hits, as such, smaller is better. Here this is clearly working as intended: the lowest roll is kept.

To the right: `chanceToHit` starts at 0, this would actually be the best possible hit roll, but then it is overwritten by the actual rolls until the lowest roll is kept.

Possible fix: `chanceToHit` should start at 100, and the lower roll should be kept.
Also, `chanceToHit` is a confusing name for this variable.

**Browser**
no
**Console output**
no
**Are you using any scripts?**
no

**Comment by MelvorIdle** [comment]
Whoops... hotfixed
