### ISSUE TITLE
levelUp function does not cap levels to 99

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#86]
**Describe the bug**
The levelUp(skill) function does not properly cap skillLevel[skill] to 99. Instead it has a cap of 100.
This can cause combat stats to be higher than intended.

**To Reproduce**
1. Create a new save file
2. Use addXP(skill,13100000) to gain experience to level 99.
3. Use addXP(skill,2000000) to gain further experience.
4. Inspect skillLevel[skill] and note that it is now level 100, instead of capping at 99

**Expected behavior**
skillLevel[skill] should have a maximum value of 99.

**Screenshots**
![image](https://user-images.githubusercontent.com/58208131/70725482-afab7b80-1cb9-11ea-8d70-55eabc2cb065.png)

**Browser**
Firefox 71.0

**Solution**
Change the logical expression in levelUp(skill) from skillLevel[skill]<=99 to skillLevel[skill] <99.
![image](https://user-images.githubusercontent.com/58208131/70725635-fdc07f00-1cb9-11ea-9ac5-9c0ce5715292.png)

**Comment by mrDLSable** [comment]
This might also be why the progress bar does weird things when reaching lvl 99

**Comment by MelvorIdle** [comment]
Fixed in v0.11

**Comment by ariehfabbro** [comment]
I don't know if i should open a new ticket besides being the same bug, but this bug keeps happening.

![image](https://user-images.githubusercontent.com/8531737/79407987-a33d7500-7f70-11ea-9e19-67e354079f77.png)

**Browser**
Chrome 81.0.4044.113 64 bits

**Console output**
Melvor Cloud Connection: Success
save.js?280:47 Loading Save Game...
save.js?280:208 Save Game Loaded...
smithing2.js?280:189 Loading Smithing...
mastery.js?280:181 Updating Masteries
mastery.js?280:23 Loading Masteries...
main.js?288:1112 Game Loaded
2cloud.js?280:192 Cloud synced
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
