### ISSUE TITLE
Minor: Fishing potions are still updating the UI as if they had the old bonus

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#860]
**Describe the bug**
Seems that when fishing potions had their bonus changed the code that updated the fish/special/junk chances didn't get updated to remove them.

**Fix**
- [x] Remove the fishing potion code from `updateFishingAreaWeights` in fishing2.js
```js
  if (herbloreBonuses[7].bonus[0] === 0 && herbloreBonuses[7].charges > 0) {
    junkChance -= herbloreBonuses[7].bonus[1];
  }
```
- [x] Remove the `updateFishingWeights` calls from `usePotion` in herblore.js
```js
  if (items[itemID].potionSkill === CONSTANTS.skill.Fishing) {
    for (let i = 0; i < fishingAreas.length; i++) {
      if (selectedFish[i] !== null)
        updateFishingAreaWeights(i, selectedFish[i]);
    }
  }
```

**Expected behavior**
Fishing potions should not reduce the displayed junk chance.

**Browser**
Browser agnostic bug.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Hotfixed
