### ISSUE TITLE
Pirate's Lost Ring doesn't do anything

### ISSUE THREAD

**Issue by micromism** [MelvorIdle/melvoridle.github.io#861]
**Describe the bug**
I put the ring on and the amount of fishing xp I get doesn't change.

**To Reproduce**
1. Put Pirate's Lost Ring on
2. Go fishing

**Expected behavior**
I was farming up fanfish, so with 120 xp per fanfish base I was expecting to get 138 xp with the ring. But it stayed at 120 xp.

**Screenshots**
Not applicable

**Browser**
Firefox 86.0 64-bit

**Console output**
Loading Save Game... save.js:13:9
Save Game Loaded... save.js:29:95
Loading Masteries... mastery.js:2:35
Game Loaded main.js:6:380
Connected to PlayFab successfully - Offline Mode cloud.js:90:158

**Are you using any scripts?**
No scripts

**Comment by Falterfire** [comment]
Rather than open a separate ticket for this I figure I'll include the reason: Right now the item definition for Pirates Lost Ring sets the modifier for CONSTANTS._item_.Fishing instead of CONSTANTS._skill_.Fishing.

**Comment by MelvorIdle** [comment]
This is now hotfixed... whoops.

**Comment by Phillipcodes** [comment]
still not fixed? have the same issuue
