### ISSUE TITLE
Fletching gives more mastery xp than expected

### ISSUE THREAD

**Issue by gmiclotte** [MelvorIdle/melvoridle.github.io#862]
**Describe the bug**
Mastery xp for production skills is typically balanced around the fastest action time, however for Fletching it is balanced around a 1.5s action time (see `getTimePerActionModifierMastery`), while the fastest possible action time is 1.3s (2000ms base, -15% god upgrade, -200ms pool, -200ms pet). 

As a result, Fletching now gives ~15% more mastery xp/hr more than other skills (assuming fastest possible action speed).

**Expected behavior**
Fletching should be balanced around it's fastest action, like all other production skills.

**Screenshots**
![2021-03-18_17-12](https://user-images.githubusercontent.com/12995926/111659012-26182100-880d-11eb-9f16-df3df44783b5.png)

**Browser**
chromium
**Console output**
no
**Are you using any scripts?**
no

**Comment by MelvorIdle** [comment]
Hotfixed
