### ISSUE TITLE
Darksteel dagger showing incorrect bleed damage

### ISSUE THREAD

**Issue by Cyrojelly** [MelvorIdle/melvoridle.github.io#863]
**Describe the bug**
The special attack of the Darksteel Dagger states that the "Enemy bleeds for 200 + 4% of their Max HP as dmg over 10 seconds". Note that this becomes 2000 in adventure mode due to everything being multiplied by 10. However, when actually using the weapon, the bleed damage is only doing 4% of the enemies' max hp with no flat value of 200 or 2000 being added on. 

**To Reproduce**
1. Equip Darksteel dagger
2. Fight something
3. Look at the bleed damage

**Expected behavior**
Bleed damage should be a lot higher than what it currently is.
Example: Currently an enemy with 600 hp (giant crab) takes 1 damage every tick when it should be 11 with the 200 being added on.
(600 x 0.04)/20 = 1.2 (rounded down is 1); current
(600 x 0.04 + 200)/20 = 11.2 (rounded down is 11); expected

**Screenshots**
![image](https://user-images.githubusercontent.com/80912151/111666895-648fea80-87d1-11eb-951a-91894e77a58a.png)

**Browser**
Google Chrome, Alpha V0.19.1

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Fixed in coming update.
