### ISSUE TITLE
New notification 12 hours

### ISSUE THREAD

**Issue by Fyobl** [MelvorIdle/melvoridle.github.io#864]
**Describe the bug**
I have logged into the game multiple times today but still I got a notification saying I haven’t logged in for 12 hours.

**To Reproduce**

Wait 12 hours it will happen again.

**Expected behavior**
If logged in the timer for the notification should reset to 0 then Start once logged out.

**Screenshots**
I will update this with screen shot next time it happens.

**Browser**
I’m on the app on IPhone 12 Pro Max.

**Console output**
N\A

**Are you using any scripts?**
None

**Comment by Minichurro5** [comment]
Bump, also having this issue

**Comment by MelvorIdle** [comment]
Seems to be an issue with the game not clearing the notification upon logging in. Will look into it

**Comment by MelvorIdle** [comment]
I have pushed some changes to the game, can you confirm if the spam is still occurring after loading into the hotfixes?

**Comment by MelvorIdle** [comment]
Old scheduled push notifications will still most likely show up, so it could take up to 8-10 hours to see the full effect of the fixes

**Comment by Minichurro5** [comment]
Yeah no issues here after you pushed the update. Thanks!

**Comment by Fyobl** [comment]
![8173ADB5-952E-4B9C-8595-826AE2FE0365](https://user-images.githubusercontent.com/66086323/111752085-2c4de200-888d-11eb-8a6c-0ef3bf43c357.png)

still having the issue.

I have logged in twice today.

**Comment by MelvorIdle** [comment]
> ![8173ADB5-952E-4B9C-8595-826AE2FE0365](https://user-images.githubusercontent.com/66086323/111752085-2c4de200-888d-11eb-8a6c-0ef3bf43c357.png)
> 
> still having the issue.
> 
> I have logged in twice today.

That might be an old scheduled notification that you see. These still need to process before the fix is 100% implemented. So 12 hours after my fix was added would be enough time to wait to see the changes in effect.
