### ISSUE TITLE
Cloud saves occur less often

### ISSUE THREAD

**Issue by FullofQuarks** [MelvorIdle/melvoridle.github.io#865]
**Describe the bug**
Cloud saves happen less often (6+ hours) than before v0.19.1, or sometimes not at all. 

**To Reproduce**
1. Load MelvorIdle in a browser
2. Play the game (I was in combat)

**Expected behavior**
Cloud saves should happen somewhat frequently.

**Browser**
Chrome 89.0.4389.90

**Console output**
cloud.js?809:8 Synchronising with Cloud
cloud.js?809:8 Synchronising with Cloud
cloud.js?809:8 Synchronising with Cloud
cloud.js?809:8 Synchronising with Cloud
/cloud/syncSave.php:1 Failed to load resource: net::ERR_QUIC_PROTOCOL_ERROR.QUIC_IETF_GQUIC_ERROR_MISSING
cloud.js?809:8 Synchronising with Cloud
cloud.js?809:8 Synchronising with Cloud
cloud.js?809:8 Synchronising with Cloud
cloud.js?809:8 Synchronising with Cloud
/cloud/syncSave.php:1 Failed to load resource: net::ERR_QUIC_PROTOCOL_ERROR.QUIC_IETF_GQUIC_ERROR_MISSING
cloud.js?809:8 Synchronising with Cloud
cloud.js?809:8 Synchronising with Cloud
cloud.js?809:8 Synchronising with Cloud
cloud.js?809:8 Synchronising with Cloud
cloud.js?809:8 Synchronising with Cloud
/cloud/syncSave.php:1 Failed to load resource: net::ERR_QUIC_PROTOCOL_ERROR.QUIC_IETF_GQUIC_ERROR_MISSING
cloud.js?809:8 Synchronising with Cloud
cloud.js?809:8 Synchronising with Cloud
cloud.js?809:8 Synchronising with Cloud
cloud.js?809:8 Synchronising with Cloud
/cloud/syncSave.php:1 Failed to load resource: net::ERR_QUIC_PROTOCOL_ERROR.QUIC_IETF_GQUIC_ERROR_MISSING

**Are you using any scripts?**
Combat simulator enhanced is installed, but disabled by pressing "cancel" upon first page load

**Comment by MelvorIdle** [comment]
Hello, this is intended. See my response here; https://www.reddit.com/r/MelvorIdle/comments/m7on1p/cloud_save_issues_with_new_update/grchosz/
