### ISSUE TITLE
Minor: Offline Agility is using base obstacle interval instead of modified interval to calculate mastery xp

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#866]
**Describe the bug**
Offline Agility is using base obstacle interval instead of modified interval to calculate mastery xp.
In main.js in `updateOffline` the masteryXP is calculated like so
```js
                  masteryXPToGive[i] = getMasteryXpToAdd(
                    CONSTANTS.skill.Agility,
                    chosenAgilityObstacles[i],
                    agilityObstacles[chosenAgilityObstacles[i]].interval *
                      masteryXPActions[i]
                  );
```
But this uses the base agility interval, so it gives the wrong amount.
**Fix**
- [x] Change offline agility to use the calculated interval for each obstacle instead of the base value.
```js
                  masteryXPToGive[i] = getMasteryXpToAdd(
                    CONSTANTS.skill.Agility,
                    chosenAgilityObstacles[i],
                    agilitySkillIntervals[i] *
                      masteryXPActions[i]
                  );
```
**To Reproduce**
1. Go offline for agility
2. Wait a bit
3. Go online
4. See that more mastery xp has been earned than expected

**Browser**
Browser agnostic bug.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixed in upcoming hotfix
