### ISSUE TITLE
Rancora spider undefined slow % in special attack description

### ISSUE THREAD

**Issue by Erico9002** [MelvorIdle/melvoridle.github.io#867]
**Describe the bug**
In the description for the rancora spider's special attack Webshot, the slow % is -undefinded

**To Reproduce**
Fight a rancora spider, and it's always saying that for me right now at least, I refreshed and it still says it. Idk. It is a slayer task.

![image](https://user-images.githubusercontent.com/57814950/111700990-25c95700-8808-11eb-8b77-7ca86b9fb0b9.png)

**Browser**
Firefox 86.0.1 (64-bit)

**Are you using any scripts?**
Never

**Comment by MelvorIdle** [comment]
Fixed in upcoming hotfix
