### ISSUE TITLE
Offline push notification

### ISSUE THREAD

**Issue by Mumblesnake** [MelvorIdle/melvoridle.github.io#869]
**Describe the bug**
The bug is that every so often the max offline progression push notification would pop up on my phone and tell me how I haven't been on the app in 12 hours but when I click the notification it shows that I've only been offline for 2 hours.
**To Reproduce**

**Expected behavior**
To get a notification when I haven't been on the app for 12 hours.
**Screenshots**

**Browser**
Please tell us what browser you are using and what version.

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

**Comment by MelvorIdle** [comment]
Closing this, see #864
