### ISSUE TITLE
Add additional options for selling items in the bank

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#87]
# New Sale Options
## Sell All
Re-add to the game. Sells all of an item.
## Sell All but One
Sells all of an item except for one.
## Sell None
Setting so that Confirm Sale does not sell anything. Useful for preventing accidental sales.

**Comment by mrDLSable** [comment]
I agree that these need to be added. Perhaps in a submenu, but they need to be there.

**Comment by coolrox95** [comment]
All suggestions have been implemented into the game in some form.
