### ISSUE TITLE
Rolling for player special attacks seems broken when multiple specials are possible

### ISSUE THREAD

**Issue by gmiclotte** [MelvorIdle/melvoridle.github.io#872]
**Describe the bug**
When the player has multiple special attacks available, the odds of special attacks and regular attacks are not as one would expect.

**To Reproduce**
In this example we roll 100k special attacks using a copy of the code in `startCombat` in `combat.js`, and some mock data (2 special attacks both with 20% chance)
```js
{
    // mock data
    combatData={player:{specialAttackID:[0,1]}}
    playerSpecialAttacks=[{chance:20}, {chance: 20}]
    let specs = [0, 0];
    let reg = 0;

    // need this function too
    function rollPercentage(chance) {
        return chance > Math.random() * 100;
    }

    for (let j = 0 ; j < 100000; j++) {

        // start of code from combat.js
        let specChances = [];
        let specCount = 0;
        let specID = false;
        for (let i = 0; i < combatData.player.specialAttackID.length; i++) {
            specChances.push(playerSpecialAttacks[combatData.player.specialAttackID[i]].chance);
            if (rollPercentage(specChances[i] + specCount)) {
                specID = i;
                break;
            }
            specCount += specChances[i];
        }
        // end of code from combat.js

        // counting different rolls
        if(specID === false) {
            reg++;
        } else {
            specs[specID]++;
        }
    }
    console.log(reg, ...specs);
}

// sample output: 48241 19792 31967
```
You can see 48% chance of regular attack, 20% of first special, and 32% of second special, as opposed to the desired 60%, 20%, 20%.
Indeed, using the code above we have 20% chance of rolling the first special attack, then (1 - 20%) * 40% = 32% chance of rolling the second special attack.

**Expected behavior**
Each special triggers on average as often as expected. Enemy special attack rolls are correctly implemented, so just reuse that code. The main issue is rolling multiple times, should only roll once, and compare that roll to multiple thresholds (20% and 40% in the example above).

**Browser**
no
**Console output**
no
**Are you using any scripts?**
no

**Comment by coolrox95** [comment]
Fixed as of update v0.21
