### ISSUE TITLE
Special attack persists after "weapon swap" (goblin raid)

### ISSUE THREAD

**Issue by abcras** [MelvorIdle/melvoridle.github.io#873]
**Describe the bug**
After equipping the dragon fire shield during the goblin raid it correctly cleared the Twin exiles which had the special attack Dual attack. While you can attack with a shield the dual attack special attack remained which is not intended behavior.

**To Reproduce**

1. Begin goblin raid
2. Get Twin exiles (or an alt 2 handed weapon with the Dual attack special attack maybe?)
3. Get a shield
4. You can now attack with the shield using the dual attack special attack but at the shield/bare hand attack speed

Extra point switching weapon removed the bug. I got the "big ol' ron" afterward and the special attack disappeared along with my shield ofc.

**Expected behavior**
Lose the special attack and attack with shield/bare hand

**Screenshots**
See attack speed at 2 seconds instead of 1 second for Twin Exile, equipment, and the special attack indicator. It also completed the 2 consecutive strikes as per the special attack so it was not just for show.
![Untitled](https://user-images.githubusercontent.com/3748122/111828690-f5f37f80-88eb-11eb-9400-f5e6ab4bf641.png)

**Browser**
Please tell us what browser you are using and what version.
Chrome the most up to date version (eighty-something

)

**Console output**
Please open the console by pressing F12 and copy it here.
![image](https://user-images.githubusercontent.com/3748122/111828532-bf1d6980-88eb-11eb-8943-db19331d4b8e.png)

**Are you using any scripts?**
No scripts, but the combat simulator plugin is installed and active.

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
