### ISSUE TITLE
Mobile app not loading. 

### ISSUE THREAD

**Issue by Juztinn** [MelvorIdle/melvoridle.github.io#875]
When I go to open the mobile app, it doesn't enter any login screen or anything, it just times out. Sometimes it shows a cloudflare browser saying I couldn't connect to the host, other times it's just a white screen.

![Screenshot_20210319-152404_Melvor Idle](https://user-images.githubusercontent.com/80989328/111847982-3d1b4980-88c7-11eb-8413-6aecb09e0669.jpg)

**Comment by DrJMKatz** [comment]
Same here. Also, in the browser it just sits at "Checking connection to the cloud..." My guess is the server is just down at the moment.
