### ISSUE TITLE
HC events not showing in #ingame-events discord

### ISSUE THREAD

**Issue by ItsPandatory** [MelvorIdle/melvoridle.github.io#878]
My HC character Spic3 Panda (ItsPandatory) doesn't have any of his events displaying in the #ingame-events channel

I killed a couple HC chars in December and they showed up but none of the 99s on this guy did.

I'm available in discord @itspandatory7070 if you need anymore info.

![Spic3 Panda](https://user-images.githubusercontent.com/75848979/111890872-e129f100-89aa-11eb-850a-9a1e26e4d95a.jpg)

**Comment by MelvorIdle** [comment]
Were you logged into the Cloud? They only post if you are.
