### ISSUE TITLE
[Minor] `Greater Dragons`'s special attack `Greater Dragonbreath` description

### ISSUE THREAD

**Issue by MiccWan** [MelvorIdle/melvoridle.github.io#879]
**Describe the bug**
The description of `Greater Dragonbreath` should be `An unavoidable attack that deals 2400 dmg over 3 seconds`.

NOTE: Each of the `Great Dragons` have same problem.

**To Reproduce**
None

**Expected behavior**

The value should be **2400** instead of **120**, since it is actually dealing 120 dmg for 20 times.

**Screenshots**
![image](https://user-images.githubusercontent.com/16610454/111912772-1ff0a180-8aa6-11eb-9f6e-3e3b463ac397.png)

**Browser**
None

**Console output**
None

**Are you using any scripts?**
None

**Comment by MelvorIdle** [comment]
Thanks, it was already setup to display the correct damage but it was referencing an unused variable. Fixed in upcoming update.
