### ISSUE TITLE
Frozen Chest gives NAN Ice Platebodies

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#88]
**Describe the bug**
When you get Ice platebodies from a frozen chest, NaN of them are added to the bank.

**To Reproduce**
1. Open Frozen Chests
2. Get Ice Platebodies from the chest
3. Check amount in bank

**Expected behavior**
Frozen chests should give only 1 Ice platebody

**Screenshots**
![image](https://user-images.githubusercontent.com/58208131/70741361-530b8900-1cd8-11ea-89c4-ed04f988f56c.png)

**Console output**
![image](https://user-images.githubusercontent.com/58208131/70741382-5f8fe180-1cd8-11ea-9f27-51a19274ec1d.png)

**Solution**
Define a dropQty for Ice Platebody for Frozen Chests.

**Comment by MelvorIdle** [comment]
Hotfixed a while ago
