### ISSUE TITLE
Second Story Book not dropping

### ISSUE THREAD

**Issue by thebigcheesish** [MelvorIdle/melvoridle.github.io#880]
**Describe the bug**
I am completing the Infernal Dungeon and not recieving the book "The First Hero and an Unknown Evil"
I have completed the dungeon 12 times now, and the book is not in my items completion tab
**To Reproduce**
Not sure how to reproduce

**Expected behavior**
Expected behavior is recieving the book after the first time I completed the dungeon

**Screenshots**

**Browser**
Google Chrome Version 89.0.4389.90 (64-bit)

**Console output**
[Violation] 'requestAnimationFrame' handler took 119ms

**Are you using any scripts?**
No scripts have ever been used on my game

**Comment by MelvorIdle** [comment]
This book is not dropped from the Infernal Dungeon. It is dropped upon completing the Fire God Dungeon.
