### ISSUE TITLE
Minor: Item statistic for "Damage Taken" is being added to "Damage Dealt"

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#882]
**Describe the bug**
In combat.js in `attackPlayer()` the itemStat tracking code is as follows:
```js
    for (let i = 0; i < equippedItems.length; i++) {
      if (
        i != CONSTANTS.equipmentSlot.Weapon &&
        i != CONSTANTS.equipmentSlot.Quiver
      ) {
        if (equippedItems[i] != 0) {
          itemStats[equippedItems[i]].stats[5] += damageToPlayer;
        }
      }
    }
```
However stats[5] corresponds to the damage dealt stat, not the damage taken stat, which is stats[4].
**Fix**
- [x] Change `itemStats[equippedItems[i]].stats[5] += damageToPlayer;` to ``itemStats[equippedItems[i]].stats[4] += damageToPlayer;``

**Browser**
Browser agnostic bug.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
