### ISSUE TITLE
Minor: Combat related Item Statistics for Javelins and Throwing Knives are being added twice.

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#883]
## Describe the bug
Since throwing knives and javelins occupy both the Quiver and Weapon equipment slots, statistics that are tracked for both the quiver and weapon are added to them twice.

## Expected behavior
Throwing knives and javelins should only have their stats tracked once.
The stats that are being double counted are:
- Damage Dealt: stats[5]
- Missed Attacks: stats[6]
- Total Attacks: stats[9]

## Screenshots
I tested this with ancient throwing knives and killed a single golbin.
![image](https://user-images.githubusercontent.com/58208131/111935055-430c5880-8a88-11eb-95fa-c79148ea4d22.png)
As you can see it tracked that I have done 100 damage, and performed 4 attacks instead of the 50 damage and 2 attacks that actually occurred.

## Browser
Browser agnostic bug.

## Are you using any scripts?
No.

**Comment by Tykothorpe** [comment]
Seems this also produces incorrect equipment "item stats" such as ranged strength:

- Click "view stats" on javelins/knives in the bank
- Note the ranged strength (for example)
- Equip them (without any other ranged equipment)
- Click "view equipment stats" on the combat page
- Note the reported ranged strength is doubled

**Comment by coolrox95** [comment]
Both the original issue and comment have been fixed as of update v0,21.
