### ISSUE TITLE
Clean up Unused Global Variables and Functions: Round 2

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#884]
# Clean Up Unused Global Variables and Functions: Round 2
## Why are you suggesting this?
After cleaning up the first batch of unused variables and functions #823, some more have been revealed.
## File-by-File Analysis of what can be removed
Once again I've used eslint to find variables. I've hopefully excluded the ones that you did not remove last time.
### save.js
- [x] `function saveBackup(save) {`
- [x] `function checkSaveBackupVersion(save) {`
### shop.js
- [x] `const tiers = [`
- [x] `const axeLevels = [1, 1, 10, 20, 35, 50, 60, 80];`
- [x] `const axeCost = [0, 50, 750, 2500, 10000, 50000, 200000, 2000000];`
- [x] `const rodLevels = [1, 1, 10, 20, 35, 50, 60, 80];`
- [x] `const rodCost = [0, 100, 1000, 5000, 20000, 75000, 300000, 2000000];`
- [x] `const pickaxeLevels = [1, 1, 10, 20, 35, 50, 60, 80];`
- [x] `const pickaxeCost = [0, 250, 2000, 10000, 50000, 200000, 1000000, 5000000];`
- [x] `const multiTreeCost = [1000000];`
- [x] `const autoSlayerCost = 150000;`
- [x] `const equipmentSetData = [`
- [x] `const equipmentSwapData = [`
- [x] `const slayerItems = [`
- [x] `function buySkillcape(cape, confirmed = false) {`
### bank.js 
- [x] `function updateSalePrice() {`
### cooking.js
- [x] `var cookingFireActive = false;`
- [x] `var cookingFireHandler = null;`
- [x] `const fireIntervalMin = 15000;`
- [x] `const fireIntervalMax = 60000;`
- [x] `var logsForFire = [];`
### combat.js
- [x] `var listView = true;` Must also be removed from `allVars` and `resetVariablesToDefault`
- [x] `var enemyBleeding = false;`
### mastery.js
- [x] `function getMasteryMedia(masteryID, skill) {`
- [x] `var masteryMedia = {` Not needed after cleaning up getMasteryMedia

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
