### ISSUE TITLE
Minor: Cloudburst Staff Description is wrong in adventure mode

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#885]
**Describe the bug**
The description of the Cloudburst staff does not dynamically update based on the value of numberMultiplier.
**Fix**
- [x] Change Cloudburst Staff description to getter method: 
```js
get description() { return `All water spells gain +${this.increasedWaterSpellDamage*numberMultiplier} max hit. Reduces the Water Rune cost of Magic Spells by ${this.providesRuneQty} when equipped as a Weapon.`},
```
**Browser**
Browser agnostic bug.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
