### ISSUE TITLE
Passive slot bug from golbin raid

### ISSUE THREAD

**Issue by JJustop** [MelvorIdle/melvoridle.github.io#886]
Just noticed that i have passive slot unlocked even thought i have not done the end game dungeon. I have unlocked golbin raid upgrade for passive slot today and it stayed for the main game

![image](https://user-images.githubusercontent.com/56999869/112046262-7a483b80-8b54-11eb-9c69-76e27f8a8483.png)

Cant equip anything to it though on the main game

**Comment by MelvorIdle** [comment]
Should be fixed next major update.
