### ISSUE TITLE
Crashing on opening (Android)

### ISSUE THREAD

**Issue by Triplb** [MelvorIdle/melvoridle.github.io#887]
**Describe the bug**
Game crashes within a second of opening.

**To Reproduce**
1. Open Melvor on Android
2. Crash

**Expected behavior**
No crash.

**Screenshots**
Screenshots of Android crash reporter:
![Screenshot_20210322-231509](https://user-images.githubusercontent.com/81197538/112070115-fba7ca00-8b64-11eb-89a5-94de60a38c1e.jpg)
![Screenshot_20210322-231210](https://user-images.githubusercontent.com/81197538/112070120-fd718d80-8b64-11eb-9890-55d2b4933ce6.jpg)
![Screenshot_20210322-231203](https://user-images.githubusercontent.com/81197538/112070125-fe0a2400-8b64-11eb-8fb5-f54c9f94b76f.jpg)

**Browser**
Melvor for Android, details above.

**Console output**
N/A

**Are you using any scripts?**
No

**Comment by Triplb** [comment]
Seems like this is related to the issues a lot of apps are having with Android Web View

**Comment by MelvorIdle** [comment]
This was related to a Google Play Webview update. Not related to Melvor.
