### ISSUE TITLE
Game crash after open it

### ISSUE THREAD

**Issue by oscarcapote** [MelvorIdle/melvoridle.github.io#888]
**Describe the bug**
Hello, I have a Pocophone F1 and the paid version of Melvor, and suddenly, everytime that I open the game, it crashes. After reinstall it the game works fine, I put the screenshot below with the error appears. 

**To Reproduce**
1. Go to 'Open the game'
4. See error It crushes

**Expected behavior**

**Screenshots**

**Browser**
Please tell us what browser you are using and what version.
![WhatsApp Image 2021-03-23 at 01 03 34](https://user-images.githubusercontent.com/11536635/112073378-44b34a80-8b74-11eb-9760-5d289be42a45.jpeg)

![WhatsApp Image 2021-03-23 at 01 03 34 (1)](https://user-images.githubusercontent.com/11536635/112073398-50067600-8b74-11eb-908f-29b7ff670572.jpeg)
**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

**Comment by MelvorIdle** [comment]
This was related to a Google Play Webview update. Not related to Melvor.
