### ISSUE TITLE
Last sync text not updating with auto save

### ISSUE THREAD

**Issue by mrDLSable** [MelvorIdle/melvoridle.github.io#89]
**Describe the bug**
The last sync text only updates when forcing a save, and not with an auto save.

**To Reproduce**
1. Have a save with Melvor cloud
2. Load the game
3. Wait
4. See that the text doesn't appear

**Expected behavior**
After five minutes there should be text saying when the last sync was.

**Screenshots**
![image](https://user-images.githubusercontent.com/1783781/70847258-bd503500-1e62-11ea-9eb0-41aeaaa66fa3.png)

**Browser**
Version 79.0.3945.79 (Official Build) (64-bit)

**Comment by MelvorIdle** [comment]
Hotfixed a little while ago
