### ISSUE TITLE
Mahogany sell price shows 2 different values

### ISSUE THREAD

**Issue by Solorail** [MelvorIdle/melvoridle.github.io#892]
The wood price if hovered shows 50, sell price on side shows 75, not a big deal or game changing, just thought you might want to see.

![image_2021-03-25_080100](https://user-images.githubusercontent.com/64572615/112469781-3ca80600-8d40-11eb-85a3-a675d41bb240.png)

**Comment by Solorail** [comment]
Quickly after reviewing that, I notice the hover prices of the other 2 woods in inventory are also different from sell price on right side.

**Comment by MelvorIdle** [comment]
Fixed in next major update
