### ISSUE TITLE
Ancient Magicks not showing unlocked until refresh

### ISSUE THREAD

**Issue by Silverfyree** [MelvorIdle/melvoridle.github.io#893]
Ancient magicks (the spells you unlock after clearing god dungeons 100 times such as gust) don't show as unlocked until you clear 100 of the boss and THEN refresh the game to force it to update.

This is reproducible 100% of the time

**Comment by MelvorIdle** [comment]
Confirmed fixed in upcoming major update (It will also dynamically update the count now)
