### ISSUE TITLE
Farming Mastery XP Total for Mastery 99+

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#894]
There's currently no easy way to see how much Mastery xp you have for each skill within Farming after it has reached 99.

**Why are you suggesting this?**

Every other skill allows you to see the total mastery xp for each item after it's 99. For example:
![](https://i.imgur.com/t8sgJf9.png)

**How does your suggestion benefit the game?**

It allows people to plan ahead for future content. We are aware that there is a level 120 update and with this I'd imagine mastery will also increase with it. I can work towards getting 120 mastery for every other skill because I can see how much mastery xp I have and assume the mastery xp for 120 will match Runescape's xp curve. It's still possible to get this information but requires you to go to third party websites, paste in your save, then search the raw, deobfuscated save file for the mastery xp amounts then match the numerical Mastery IDs to the corresponding items. This is less than ideal to do.

**It is suggested that you provide (mockup) art to ilustrate things where relevant in order to make your suggestion more clear.**

![](https://i.imgur.com/QWhGyDS.png)

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
