### ISSUE TITLE
Infernal Claw has Ocean Song special in raids

### ISSUE THREAD

**Issue by Hluebbers** [MelvorIdle/melvoridle.github.io#896]
**Describe the bug**
Infernal Claw has Ocean Song special in raids, it uses the special attack and isn't just a name mix up.

**To Reproduce**

Pick infernal claw in raids? I didnt do anything else different from normal

**Expected behavior**
Having the correct attack

**Screenshots**
![image](https://user-images.githubusercontent.com/81532397/112765473-f9b19100-8fd2-11eb-9de5-6ea324511194.png)

**Browser**
Steam fully updated

**Console output**
Please open the console by pressing F12 and copy it here.
I cant get an output without restarting my game

**Are you using any scripts?**
no

**Comment by MelvorIdle** [comment]
You received an ALT weapon. Be sure to pay attention to the name of the item when selecting it.
