### ISSUE TITLE
Stunned enemies take more damage than expected

### ISSUE THREAD

**Issue by elverange** [MelvorIdle/melvoridle.github.io#897]
**Describe the bug**
When using tidal edge and fighting amulet, the first hit does 550 and stuns while the second hit does 700.
Without fighting amulet, both hits do 550 damage as expected.

**To Reproduce**
1. Equip both tidal edge and fighter amulet 
2. Fight a monster with more than 1100 hp
3. Wait for tidal edge's spec and notice the second hit is higher than it should

I believe I also noticed the same thing happening with glacia godsword, but it's harder to know for sure as I cannot as easily guarantee a max hit with this weapon.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update. Stunned enemies do take more damage, but there was a bug where they would take even further damage than expected.
