### ISSUE TITLE
Magical Ring sometimes nullifies Perilous Peaks evasion penalty

### ISSUE THREAD

**Issue by AThomsonSMC** [MelvorIdle/melvoridle.github.io#899]
**Describe the bug**
If wearing the Magical Ring when fighting Greater Dragons in the Perilous Peaks, it will negate the Evasion penalty that is supposed to be applied. Does not occur if you equip the Magical Ring while already fighting a dragon, but running away and starting fight again will reset.

**To Reproduce**
1. Go to Bank
2. Equip Magical Ring (for accessing High Lands)
3. Start fighting one of the Greater Dragons
4. Note that enemy's chance to hit is much lower than it should be
5. Unequip Magical Ring
6. Note that enemy's chance to hit is normal

**Expected behavior**
Magical Ring should not effect enemy's chance to hit

**Screenshots**
![Magical Ring Both](https://user-images.githubusercontent.com/5577119/112888053-20360180-9091-11eb-9b21-d3ca4adbd05c.png)

**Browser**
Chrome 89.0.4389.90 

**Console output**
N/A

**Are you using any scripts?**
N/A

**Comment by MelvorIdle** [comment]
I am unable to reproduce this one. More information is required.

The Magical ring has no stats, and there is no interaction with the Perilous Peaks like you mentioned. Testing will need to take place on items other than the Magical Ring to see if it relates to the unequipping or equipping of any item.

**Comment by AThomsonSMC** [comment]
Changing any equipment at all while this is happening will cause it to stop. Running away and using "Jump to Enemy" (or manually from enemy select) will usually start it again

**Comment by MelvorIdle** [comment]
This may be fixed next major update. Feel free to reopen if not.
