### ISSUE TITLE
Cape of Completion not available in shop section

### ISSUE THREAD

**Issue by OndrejSynak** [MelvorIdle/melvoridle.github.io#900]
**Describe the bug**
After the completion log is at 100% the cape of completion is still not unlocked in store.

**To Reproduce**
1. Have 100% completion log
2. Go to the shop
3. There is no cape

**Expected behavior**
Cape of Completition should be available to be purchased in the shop.

**Problem**
In shop.js `function updateShop(identifier)` there are these lines that should handle the item to be visible.
```
   if (identifier === "skillcapes" || identifier === "all") {
        let completion = true;
        if (completionStats < 100)
            completion = false;
        $("#shop-skillcape-bonus-completion").text(items[CONSTANTS.item.Cape_of_Completion].description);
        $("#shop-skillcape-cost-completion").text(formatNumber(items[CONSTANTS.item.Cape_of_Completion].buysFor));
    }
```
but the `shop-skillcape-bonus-completion` does not exist at all in HTML and also the `completion` is not used no matter to which flag it is set to.

**Comment by MelvorIdle** [comment]
Fixed in upcoming update
