### ISSUE TITLE
Change Agility Obstacle Interface

### ISSUE THREAD

**Issue by Draught3d** [MelvorIdle/melvoridle.github.io#901]
Add a chart to the Agility Passives window to show available passives for each slot. Chart would only show unlocked obstacles, and each row could link to the "View Obstacle Selection" option for that obstacle. Possible layout attached (made with Chrome inspect element so it's not amazing, but shows it's easily doable in code)

Why are you suggesting this?
I made a spreadsheet for planning out my agility bonuses, and realized it would be pretty simple to add a resource in-game for simplicity.

How does your suggestion benefit the game?
Having an in-game resource for agility passives would make it easier for players to verify if they're missing a bonus they could have, or otherwise affecting their efficiency.

Possible format in attached image: 
Button next to existing global actives button:
![image](https://user-images.githubusercontent.com/2012135/112914930-2ba61e80-90cb-11eb-96ff-cd311f1d77b7.png)
Sample image of table with all levels unlocked:
![image](https://user-images.githubusercontent.com/2012135/112925371-c01a7c00-90df-11eb-9f48-aa6eaacadfda.png)

**Comment by MelvorIdle** [comment]
Thanks for the suggestion. We have noted this, but are closing all suggestions on GitHub to clean up as this issue tracker will not be used for Bugs only.
