### ISSUE TITLE
[TYPO] Typo in the game guide page of the Agility Skill

### ISSUE THREAD

**Issue by qrss** [MelvorIdle/melvoridle.github.io#902]
The last word of
the first sentence of
the third paragraph of
the Obstacles section of the game guide page of the Agility skill contains the following typo: 

(Obstacle Coure) instead of (Obstacle Course)

Context:
Obstacles will become inactive if there is a gap in your Obstacle Coure.

**Comment by MelvorIdle** [comment]
Fixed in next major update
