### ISSUE TITLE
Amulet of fishing disappeared. 

### ISSUE THREAD

**Issue by mikewzz** [MelvorIdle/melvoridle.github.io#904]
Logged on to my account and noticed fishing times increased. Checked my character's equipped items and saw an empty slot for the amulet. The amulet of fishing icon still exists on the right when I go to the fishing page but when I click on it it says: "There's no Amulet of Fishing in your bank *shrug*". Is this a bug?

**Comment by nightblade9** [comment]
Same thing happened to me a couple of days ago. I restarted from a local save on another machine to make sure I didn't sell it by mistake. It disappeared again.

@mikewzz did you ever get it back or figure out what happened to it? It's taking ages to fish up another one.
