### ISSUE TITLE
ALT Magic stops casting when going from offline to online - spells that require items

### ISSUE THREAD

**Issue by Silverfyree** [MelvorIdle/melvoridle.github.io#906]
Alt magic works both offline and online, however as soon as you log back online after claiming offline progress your spell will not remember which item you picked to Alch/convert/superheat etc (any spell that requires you to choose an item).

This is 100% reproducible once you come back online.

"the item does not exist" is the message it gives until you reselect the item

**Comment by MelvorIdle** [comment]
Fixed in coming update
