### ISSUE TITLE
Weird Gloop is giving +0.10% harvest quantity, not +10%

### ISSUE THREAD

**Issue by CollinHeist** [MelvorIdle/melvoridle.github.io#907]
**Describe the bug**
`harvestBonus` of *Weird Gloop* is written as float percentage (`0.10`) instead of integer value (`10`). Resulting in the item not having any effect. 

**To Reproduce**
1. Go to Farming.
2. Plant any seed.
3. Plant same seed as (2) with Weird Gloop applied.
4. Harvest both items.

**Expected behavior**
`harvestBonus` modifier should be 10. Giving the expected +10% harvest quantity.

**Comment by MelvorIdle** [comment]
Thanks, fixed in upcoming update
