### ISSUE TITLE
Skill grid in menu

### ISSUE THREAD

**Issue by mrDLSable** [MelvorIdle/melvoridle.github.io#91]
Right now I have to scroll if I want to switch between my bank and mastery. I find this annoying when checking things for my completion log. I propose an option to have the skills shown in a grid like in RuneScape so that the menu can be more compact.

In my opinion this should be an option and not the default in order to give advanced players the option to use it, but give new players the best possible experience.

**Comment by MelvorIdle** [comment]
Added something similar in v0.11
