### ISSUE TITLE
After death, heath being reset to zero

### ISSUE THREAD

**Issue by Mitchell1111** [MelvorIdle/melvoridle.github.io#910]
**Describe the bug**
I died in chaos mode and now every time I die my heath is set to 1M (20 %) an about 1 sec later it drops to 0 without talking damage and i'm unable to eat food, the next hit kills me.
 
**To Reproduce**
1. I Pickpocket to get killed.
2. Heath jumps up.
3. wait 1-2 sec
4. heath drops (unable to heal)
Not sure what caused it in the first place I died fighting in Volcanic Cave.

**Expected behavior**
I expected auto eat to heal me or to be able to heal.

**Screenshots**
![image](https://user-images.githubusercontent.com/81789621/113376725-649af900-9340-11eb-9d5a-28e5a93a8827.png)

**Browser**
Was using Microsoft edge, also unable to heal on chrome but issue started on edge

**Console output**
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cdn.melvor.net/core/v018/assets/media/shop/assets/media/shop/perpetual_haste.svg:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
save.js?828:13 Loading Save Game...
save.js?828:29 Save Game Loaded...
mastery.js?828:2 Loading Masteries...
main.js?828:7 Game Loaded
2cloud.js?828:8 Synchronising with Cloud
cloud.js?828:76 Connected to PlayFab successfully
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
3cloud.js?828:8 Synchronising with Cloud

**Are you using any scripts?**
Not using any scripts.

**Comment by David-vz** [comment]
I came across the same issue. 
The april fools mechanics, specifically the item corruption has a chance of spawning a negative health regen debuff...

That seems to be interacting really badly. See if you can find what is causing the debuff and reroll it. Worked for me for now.
