### ISSUE TITLE
x All option for upgrading to Crown of Rhaelyx

### ISSUE THREAD

**Issue by ItsPandatory** [MelvorIdle/melvoridle.github.io#912]
Very minor issue, but sometimes I have a few sets of circlets/jewels lying around from leveling mastery. Would be nice to be able to click xAll instead of upgrade -> x1 a few times.

Edit: this could also be added to the Amulet -> Elite Amulet upgrades

**Comment by MelvorIdle** [comment]
Fixed in coming update
