### ISSUE TITLE
Pet Master achievement unlocked at 97% pet completion

### ISSUE THREAD

**Issue by Bregann** [MelvorIdle/melvoridle.github.io#917]
**Describe the bug**
I unlocked the Pet Master achievement only at 97% pet completion (missing 1 pet)

**To Reproduce**
1. Have all but 2 pets unlocked (in my case Dark Waters pet and Perilous Peaks pet)
2. Unlock the Perilous Peaks pet (I had unlocked this on browser and reloaded my Steam save)
3. Load Steam save and the achievement will unlock

**Expected behavior**
The pet achievement should unlock at 100%

**Screenshots**
![image](https://user-images.githubusercontent.com/35966588/113501551-e4ca8580-951d-11eb-96ed-06336a367d4e.png)
![image](https://user-images.githubusercontent.com/35966588/113501530-ba78c800-951d-11eb-9573-eaf50cfaa59f.png)

**Browser**
Steam

**Console output**
N/A
**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Fixed in next major update
