### ISSUE TITLE
Sandstorm ring draining prayerpoints

### ISSUE THREAD

**Issue by OSRSEdenGuard** [MelvorIdle/melvoridle.github.io#918]
**Describe the bug**
Sandstorm ring drains prayerpoints for every proc the special attack does. As the ring states the damage scales with the players HP and is unavoidable, and thus should not drain prayer in the first place.

**To Reproduce**
1. Have the Sandstorm ring equiped, and an offensive prayer active (I used Chivalry).
2. Fight an enemy
3. Wait for the Sandstorm ring special attack
4. See the prayer points rapidly drain during the special attack.

**Expected behavior**
As stated above, the Sandstorm ring special attack should not drain prayer at all. The special attack is unavoidable, and scales with the players current HP, thus should not be affected by prayer bonuses in the first place.

**Browser**
Firefox v. 87.0

**Are you using any scripts?**
Not using any scripts.

**Comment by Silberdrachi** [comment]
#944 Related issue

**Comment by MelvorIdle** [comment]
Fixed in coming major update
