### ISSUE TITLE
Minor: Doubling chance for offline woodcutting does not work correctly for the second tree

### ISSUE THREAD

**Issue by coolrox95** [MelvorIdle/melvoridle.github.io#920]
**Describe the bug**
The item doubling chance for offline woodcutting seems to only properly apply to the first tree you start cutting.
I was looking through the offline code and it seems like this happens when the game adds rare items, which changes the actions array:
```js
              if (rareItems.length) {
                for (let f = 0; f < rareItems.length; f++) {
                  if (itemsGained.includes(rareItems[f].itemsGained))
                    actions[itemsGained.indexOf(rareItems[f].itemsGained)] +=
                      rareItems[f].actions;
                  else {
                    itemsGained.push(rareItems[f].itemsGained);
                    actions.push(rareItems[f].actions);
                  }
                }
              }
```
when it does the log doubling for the second tree
```js
              let doubleLogActions = Math.floor(
                generateGaussianNumber(
                  getMean(actions[i], doubleLog / 100),
                  getStdDev(actions[i], doubleLog / 100)
                )
              );
              if (doubleLogActions > 0) actions[i] += doubleLogActions;
```
it would apply that to whatever is at index 1 of the array, which would be the rare items rolled for the first tree. So effectively it is applying the doubling chance to the wrong item.
**Expected behavior**
Doubling chance should apply to both logs. It should not apply to rare items.
**Screenshots**
Here's an example from chaos mode, where my intervals were identical.
![image](https://user-images.githubusercontent.com/58208131/113526653-1a9c5800-9578-11eb-944d-0a0977d912f8.png)

**Browser**
Browser agnostic bug.

**Console output**
None.
**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Confirmed fixed in next major update
