### ISSUE TITLE
Starting HP exp should be 1155 not 1154 - causes hp to load as lvl 9 on cloud save

### ISSUE THREAD

**Issue by Silverfyree** [MelvorIdle/melvoridle.github.io#923]
As per above, starting exp for hp should be 1155 for new accounts as loading a cloud save with this exp forces you down to level 9 instead of 10. At level 9 hp, regen is disabled due to flooring down to level 0.

![image](https://user-images.githubusercontent.com/77082862/113661339-7978e300-96d8-11eb-8be3-fe3b2c206f2a.png)

**Comment by MelvorIdle** [comment]
Fixed in coming major update
