### ISSUE TITLE
Sometimes certain mastery xp goes from 0 to 1 when (re)loading the game

### ISSUE THREAD

**Issue by gmiclotte** [MelvorIdle/melvoridle.github.io#924]
**Describe the bug**
Some masteries increase from 0 xp to 1 xp when loading the game. I think it originates from these lines in the code:
![2021-04-06_09-28](https://user-images.githubusercontent.com/12995926/113674550-96062280-96ba-11eb-8ca8-82a862f12af1.png)
But I haven't really investigated further.

**To Reproduce**
1. Make a new account
2. Notice that you have 1 mastery xp for all bar making actions in smithing, these should be 0
3. Notice that you have 0 mastery xp for all farming actions, which makes sense
4. Notice that you have 0 mastery xp for all cooking actions, which makes sense
5. Reload the page
6. Notice that you now have 1 mastery xp for all farming actions, these should still be 0
7. Notice that you now have 1 mastery xp for all cooking actions, these should still be 0

**Expected behavior**
Mastery xp does not increase without performing the action or spending pool xp.

**Screenshots**
Smithing mastery on new save
![2021-04-06_09-23](https://user-images.githubusercontent.com/12995926/113673920-dca74d00-96b9-11eb-9610-023b3c49b2f6.png)

Farming mastery on new save
![2021-04-06_09-15](https://user-images.githubusercontent.com/12995926/113673294-175cb580-96b9-11eb-8f56-eebc287536c8.png)

Farming mastery after reloading
![2021-04-06_09-15_1](https://user-images.githubusercontent.com/12995926/113673300-1a57a600-96b9-11eb-9c14-4bf3b4c7a720.png)

Cooking mastery after reloading
![2021-04-06_09-27](https://user-images.githubusercontent.com/12995926/113674523-8f77ab00-96ba-11eb-8b27-755c5f9a71c1.png)

**Browser**
Chromium Version 89.0.4389.114 (Official Build) snap (64-bit)

**Console output**
When first loading the fresh account:
```
Smithing Mastery +1
```
is logged 9 times (once for each bar), originating from `save.js?832`. Indeed, this file contains
```js
smithingMastery.push({ mastery: 1, masteryXP: 0 });
console.log("Smithing Mastery +1");
```

Nothing is logged when reloading the game (when the farming and cooking masteries increases).

**Are you using any scripts?**
no

**Comment by coolrox95** [comment]
Seems this is also related to `populateMasteryObject` in mastery2.js. I believe that is what is setting the `MASTERY` object to have this 1 xp. Guessing by pushing to the old mastery arrays, the game is trying to convert the old object format into the new one.

Seems to be triggering the conversion code since this if statement triggers with 0 xp being a falsey value.
```js
      if (!MASTERY[items[i].masteryID[0]].xp[items[i].masteryID[1]]) {
```
Should be changed to:
```js
      if (MASTERY[items[i].masteryID[0]].xp[items[i].masteryID[1]] === undefined) {
```
to prevent the conversion code from running when it shouldn't.

**Comment by MelvorIdle** [comment]
Fixed in coming update
