### ISSUE TITLE
[TYPO] Cap Is Misspelled in the Settings

### ISSUE THREAD

**Issue by kinsellasam** [MelvorIdle/melvoridle.github.io#929]
**Describe the bug**
In the settings, the hover description of 'Enable Offline Time Cap Push Notifications' has a typo. Cap is spelled 'Cao'
**To Reproduce**
1. Go to 'Settings' on a browser edition of MelvorIdle
2. Scroll down to 'Mobile Push Notification Settings'
3. Hover over 'Enable Offline Time Cap Push Notifications'

**Expected behavior**
Cap should be spelled properly

**Screenshots**
![image](https://user-images.githubusercontent.com/57734208/114226224-eb4f6780-9938-11eb-959b-00e062781907.png)

**Browser**
All current versions: Edge, Chrome, Firefox

**Comment by MelvorIdle** [comment]
Fixed in next major update
