### ISSUE TITLE
burning effect can kill you twice

### ISSUE THREAD

**Issue by luckystarfsh** [MelvorIdle/melvoridle.github.io#930]
**Describe the bug**
When you die while inflicted with burning the burning can kill you a 2nd time before your hp restores

**To Reproduce**
1. Go to an enemy that inflicts burning
2. die while inflicted with burning (might need to be early in the burning effect)
3. the message pops op telling you you died followed by another message telling you you died a second later
4. if protect item is used an item can still be lost on the 2nd death

**Expected behavior**
1 message pops op telling you you died and no item lost if using protect item

**Screenshots**

**Browser**
Opera GX version 73.0.3856.427

**Console output**

**Are you using any scripts?**
2 scripts running with tampermonkey:
Melvor offline cap remover
Melvor show modifiers

**Comment by MelvorIdle** [comment]
I believe this is fixed in the next major update.

Feel free to reopen if not.
