### ISSUE TITLE
Old Save vs. Recent Save is backwards

### ISSUE THREAD

**Issue by caspiown** [MelvorIdle/melvoridle.github.io#931]
**Describe the bug**
In my #2 save slot, switching between local vs. cloud save shows the oldest save as the newest save (green bar) and the most recent save as the old save (red bar).  These are backwards for this save slot.  It is in adventure mode.  The 1st save slot shows it correct, which is the original game mode and a very old save.    This behaves the same using the web browser and the mobile app.

**To Reproduce**
Look at the character select screen and click between cloud and local saves and observe that the most recent save for Slot 2 is the oldest.

**Expected behavior**
Most Recent Save should have the latest date, not the oldest.

**Screenshots**
![MostRecentOlder](https://user-images.githubusercontent.com/82250844/114257625-4ad86200-998f-11eb-891f-e90907efe477.png)
![OldSaveNewer](https://user-images.githubusercontent.com/82250844/114257629-4dd35280-998f-11eb-9cc6-487b538448a3.png)

**Browser**
Chrome, latest.

**Console output**
VM680 index.php:24 GET https://ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
index.php?l=1:10668 GET https://cdn.melvor.net/core/v018/assets/media/shop/assets/media/shop/perpetual_haste.svg 403
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
2DevTools failed to load SourceMap: Could not load content for chrome-extension://gannpgaobkkhmpomoijebaigcapoeebl/bundle.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
cloud.js?832:76 Connected to PlayFab successfully

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
I have reason to believe this may be fixed in the next major update.

Feel free to reopen if you see this again in the next major update.
