### ISSUE TITLE
keep getting back to character select page 

### ISSUE THREAD

**Issue by Blackolf** [MelvorIdle/melvoridle.github.io#932]
## Describe the bug
hi , im **IPhone 12** mini user ,
sometime when i'm doing the dungeon or something else ,it will send me on the character select page for no reason , is so annoying

## **To Reproduce**
no step to reproduce , it happen random , it cloud on be any action when i tap my screen 

**Expected behavior**
not going back to the character select page ,

**Browser**
Iphone 12 mini

**Comment by aprbrown** [comment]
I've also noticed similar behaviour on my iPhone 11 Pro Max, I have noticed it happens more frequently in areas of the house with a poor wi-fi signal.
