### ISSUE TITLE
Cooking Mastery Offline Rate Incorrect - Roughly 50% Higher than Online Mastery Rate

### ISSUE THREAD

**Issue by Erico9002** [MelvorIdle/melvoridle.github.io#934]
**Describe the bug**
The rate at which you accumulate offline cooking mastery experience is significantly higher than the rate at which you accumulate online cooking mastery experience. Calculations shown below reveal that training cooking offline yields a bit over 1.5x the mastery experience. I first noticed something was up after I went from around 54% mastery pool to 100% mastery pool in only 10 hours. I then set out to verify that there was an issue through calculations.

**Context**
- Maxed account.
- Tested with both cave fish and manta rays. Happens with both (presumably, all fish)
- I am using Agility obstacle modifiers, if it is relevant. I am including which ones in the screenshot section.
- I do have purchased all god dungeon boosts.
- This affects both the item's mastery level and the amount of experience added to the mastery pool.

**Calculation for Manta Rays**

Mastery pool xp when closing: 4251121
Mastery pool xp when opening: 4492913
Xp difference: 241792 xp
Time between sessions: 3171 seconds

Online rate of mastery pool gain = 128 xp / 2.55s = 50.2 xp/s
Offline rate of mastery pool gain: = 241792 xp / 3171 s = 76.25 xp/s

**Calculation for Cave Fish**

Mastery pool when closing: 4136058
Mastery pool when opening: 4142529
Xp difference: 6471 xp
Time between sessions: 71 seconds
Cooked this many fish: 28

Online rate of mastery pool gain = 149 xp / 2.55s = 58.43 xp/s
Offline rate of mastery pool gain = 6471 xp / 71 s = 91.14 xp/s
Online mastery per fish = 149 xp / fish
Offline mastery per fish = 6471 xp / 28 fish = 231.1 xp/fish

**Screenshots**
(note: time can be determined by my clock at the bottom right hand side, which includes seconds)

Manta Ray screenshot on closing the game:
![image](https://user-images.githubusercontent.com/57814950/114621422-4b644780-9c72-11eb-855a-5e6afef2bcf2.png)
Manta Ray screenshot directly after opening the game:
![image](https://user-images.githubusercontent.com/57814950/114621438-50c19200-9c72-11eb-871e-c1df4de8ff57.png)

Cave Fish screenshot on closing the game:
![image](https://user-images.githubusercontent.com/57814950/114621538-6f278d80-9c72-11eb-87a2-541c71afed4e.png)
Cave Fish screenshot after opening the game:
![image](https://user-images.githubusercontent.com/57814950/114621675-9b430e80-9c72-11eb-8810-9f79bbe714fc.png)

Agility obstacles and summed modifiers:
![image](https://user-images.githubusercontent.com/57814950/114621752-b31a9280-9c72-11eb-93c7-010b2ca3a4c3.png)

**Browser**
Firefox 87.0

**Are you using any scripts?**
No, never.

**Comment by MelvorIdle** [comment]
Fixed in upcoming major update
