### ISSUE TITLE
Minimum damage glove or potion to help in leveling combat skills

### ISSUE THREAD

**Issue by Seanana92** [MelvorIdle/melvoridle.github.io#935]
It seems that combat stats really bog down at higher ranks, no help due to the fact that minimum damage of all attacks(excluding magic) is 1. I understand that the average dpm means that over enough attacks and samples, it would even out over a long period of time.. but what if there was something to help speed that along a bit?

I'm suggesting this in an effort to help the grind for ranged, strength, defense, and attack. I feel as if a Herblore potion or pair of buy-able gloves from the shop that would work in the same way as either the mage gear craft-able through rune crafting or the combat pillar through agility. It would provide either a minor flat increase to the source of damage's minimum or adding a small percent of your max damage to your minimum damage.

If this were in the game, it would speed up your training by increasing your average damage and xp gain/hour of the stat. As not to leave out magic, it would apply to it as well. 

"Balancing Potion"
My first idea in question would be to add a craft-able potion, (level 30, x2 Mantalyme herb x2 Bones or x2 of a weapon of some form? Steel Daggers maybe?) that provides 3/5/7/10% of your max hit as minimum damage (or 10/20/30/40 minimum damage) to your next 5/5/5/10 attacks. I feel as if these values are modest and wouldn't encroach on the power that the more used and effective potions have like diamond or strength potions. They could just be used as stepping stones to get stronger. This would also increases Herblore's potion selection to level with. 

OR

"Gloves of Balance"
My other idea would to be to add a buy-able glove in the shop. 100k gold, 500 charges, 1 consumed on player attack with stats somewhere in the middle of what was mentioned above. They would also give zero combat stats to the player like the other skill gloves. This way, the gloves would not be a necessity to use and would just be a bonus to the player willing to use their resources towards them instead of something else.

Thank you for your time to anyone who decides to read this essay.. Obviously all stats mentioned are just spitball values, would NOT be final, and would be left to Malcs to decide. Feel free to drop a DM @Seanana#3627 for further discussions/ideas and I will edit this page accordingly.

**Comment by MelvorIdle** [comment]
Closing suggestion to clean up GitHub (but I still read suggestions even if closed)
