### ISSUE TITLE
Agility Global active passives bug 

### ISSUE THREAD

**Issue by CarlosBaezFumero** [MelvorIdle/melvoridle.github.io#937]
**Describe the bug**
When you hit 99 Mastery all passive red debuffs are halved. This shows appropiately in each obstacle course when you hit 99 mastery, but when you hit the top right button to see all global passives, the number doesn't reflect the halved debuff. 

**To Reproduce**
1. Go to agility
2. Hit 99 Mastery on a course that has a red debuff
3. click on global passives to see that the number isn't halved there.

**Expected behavior**
I expected to see the halved debuff

**Screenshots**
![image](https://user-images.githubusercontent.com/23174357/114859267-cc464f00-9dea-11eb-88ec-98f99eb35bc0.png)

**Browser**
steam

**Console output**
doesnt work steam

**Are you using any scripts?**
no

**Comment by CarlosBaezFumero** [comment]
![image](https://user-images.githubusercontent.com/23174357/114859304-d8caa780-9dea-11eb-97fd-40f4d433d3ef.png)

![image](https://user-images.githubusercontent.com/23174357/114859315-de27f200-9dea-11eb-9803-47a284fd86e4.png)

**Comment by MelvorIdle** [comment]
This one is fixed in next major update
