### ISSUE TITLE
Golbin Raid display wrong number of coins

### ISSUE THREAD

**Issue by taior3** [MelvorIdle/melvoridle.github.io#938]
**Describe the bug**
Golbin raid main window shows wrong number of Total Raid Coins as well as "Raid coins" shown on Raid History

**To Reproduce**
1. Go to Golbin Raid
2. Check how many coins you have in shop
3. Perform Golbin Raid
4. Check how many does main window show and how many is actually added to your wallet.

**Expected behavior**
It should show same number everywhere. As you can see in my situation it shows that in total I made 20k but I have in shop 57k. In my opinion it divides it by 3.

**Screenshots**
![image](https://user-images.githubusercontent.com/82634695/114976905-082ef200-9e87-11eb-9fba-dd73d220f9e5.png)
![image](https://user-images.githubusercontent.com/82634695/114976918-1250f080-9e87-11eb-9a38-22916a912751.png)

**Browser**
Chrome

**Console output**
No output for Golbin

**Are you using any scripts?**
Combat Simulator
Melvor ETA
Completionist Log

**Comment by MelvorIdle** [comment]
Fixed in coming major update
