### ISSUE TITLE
Sandstorm ring does not show special attack in Golbin Raid

### ISSUE THREAD

**Issue by taior3** [MelvorIdle/melvoridle.github.io#939]
**Describe the bug**
Sandstorm ring does not show special attack in Golbin Raid

**To Reproduce**
Drop Sandstorm in Golbin Raid

**Expected behavior**
Visible Special for the Ring

**Screenshots**
![image](https://user-images.githubusercontent.com/82634695/114988711-eb021f80-9e96-11eb-98ef-4eb2e9af828a.png)

**Browser**
Chrome

**Are you using any scripts?**
Combat Simulator
Melvor ETA
Completionist Log Helper
Melvor drop chance

**Comment by MelvorIdle** [comment]
This screen does not currently show any special attacks.
