### ISSUE TITLE
Higher tiers of gloves

### ISSUE THREAD

**Issue by Eusmusia** [MelvorIdle/melvoridle.github.io#94]
mrDLSable and I were discussing a post from reddit and came up with an idea based on that post.

The original post talked about a glove mastery that as you used that glove, the mastery went up, resulting in a chance to not use charges.

mrDLSable and I came up with a higher tier of glove. So an example was the gem gloves. normally 500 charges, 125k for the charges and you get 1 gem per ore you mine.

We talked about having a Gem Gloves T2 that doubled or tripled the effect for triple or quadruple the cost. And this format could be used for other higher tiers of gloves, with the cost being more for a greater effect.

**Comment by mrDLSable** [comment]
The relevant [reddit threat](https://www.reddit.com/r/MelvorIdle/comments/eb1zm1/suggested_feature_glove_mastery/).

**Comment by mrDLSable** [comment]
The conversation on the discord
 
EusmusiaToday at 18:54
That's an interesting thought ^
 
mrDLSable [58%]Today at 18:58
not really. The gloves are meant to be a money sink. this would reduce that effect
 
EusmusiaToday at 18:59
Ah yeah. this is true.
Raising the price perhaps.
Counteract the "saving" effect
But that's just putting a bandaid over it
 
mrDLSable [58%]Today at 19:00
I would be more in favour of unlocking a higher tier, more expensive glove
which would have a higher effect
 
EusmusiaToday at 19:00
like gem gloves 2 giving double gems but at a higher cost? I like it
 
mrDLSable [58%]Today at 19:00
exactly
but like double effect, but triple cost
 
EusmusiaToday at 19:01
That could be nice
 
mrDLSable [58%]Today at 19:01
Will you write it up on the github?
 
EusmusiaToday at 19:02
Yeah
 
mrDLSable [58%]Today at 19:02
:thumbsup:
 
EusmusiaToday at 19:05
Wait. Double effect and triple cost, couldn't others just get numerous regular glove charges for the same effect but cheaper?
 
mrDLSable [58%]Today at 19:15
yes
you're paying for the speed
gloves in general are just a speed thing
you could get 1000 diamonds by mining for a couple of days, or you could spend a million on gloves and get them in an hour
the higher level gloves would be in the same line just extrapolated
