### ISSUE TITLE
Slayer Armour pulling XP Bonuses from wrong modifier

### ISSUE THREAD

**Issue by Silverfyree** [MelvorIdle/melvoridle.github.io#940]
Elite Slayer Platebody (Melee) has only 5% slayer exp bonus instead of 30% that reads in the item description. Seems to only affect elite slayer platebody (melee) having the wrong modifier applied.

from discussion in wiki channel:

![image](https://user-images.githubusercontent.com/77082862/115039304-ebd09b00-9f02-11eb-8b38-3f8c1684d8d4.png)

**Comment by MelvorIdle** [comment]
Fixed in coming major update
