### ISSUE TITLE
Switch Tabs Bug

### ISSUE THREAD

**Issue by dinhngocdat** [MelvorIdle/melvoridle.github.io#941]
**Describe the bug**
After choosing the character and the loading screen appears, I switch tabs for a few second, and when i go back, the action I am currently training stopped

**To Reproduce**
1. Go to Melvor Idle 
2. Select your character
3. Wait for the loading screen appear
4. Switch to another tab immediately
5. Wait a minute
6. Switch back to Melvor's tab
7. Action that are currently training stopped

**Expected behavior**
Action that are currently training not being stopped

**Browser**
Google Chrome, 89.0.4389.114

**Console output**
Melvor CombatDropChance

**Comment by Silverfyree** [comment]
Hi!

By training stopped do you mean it loads offline progress again?

This is a setting you have enabled in game called the "experimental setting".
Its enabled by default to prevent throttling when you tab out of the game - especially on browser or phone platforms.

My suggestion is that you either disable the setting but understand you may slow your game down, or move Melvor to its own window without any other tabs on it. You can put another window on top of your Melvor one without any throttling.
