### ISSUE TITLE
Looting Amulet yeets items if bank is full

### ISSUE THREAD

**Issue by Silverfyree** [MelvorIdle/melvoridle.github.io#942]
I don't know if this is a bug or a suggestion, but currently the looting amulet will destroy items if bank is full when it tries to loot. Instead I believe it should leave items in the loot box instead and they can be destroyed once the loot box is full.

This way players have the chance to collect items if they are able to make space before items get destroyed without warning.
Probably a bank is full warning would also be nice.

**Comment by MelvorIdle** [comment]
Fixed in coming major update
