### ISSUE TITLE
Golbin Raid Passive Item not visible in Equipment Stats View

### ISSUE THREAD

**Issue by taior3** [MelvorIdle/melvoridle.github.io#943]
**Describe the bug**
As title say (check screenshot)

**To Reproduce**
1. Open Golbin Raid
2. Click Equipment Status

**Screenshots**
![image](https://user-images.githubusercontent.com/82634695/115195396-fe0f2c80-a0ee-11eb-8168-8d35d51ebf72.png)
![image](https://user-images.githubusercontent.com/82634695/115196074-cce32c00-a0ef-11eb-8d33-f626d372266e.png)

**Browser**
Chrome

**Are you using any scripts?**
Melvor ETA
Melvor drop chance
Melvor Completion Log Helper
Combat Simulator

**Comment by MelvorIdle** [comment]
Confirmed fixed in coming major update
