### ISSUE TITLE
Sandstorm drains runes

### ISSUE THREAD

**Issue by yggrr** [MelvorIdle/melvoridle.github.io#944]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser**
Please tell us what browser you are using and what version.

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

**Comment by MelvorIdle** [comment]
Confirmed fixed in next major update
