### ISSUE TITLE
completion cape visual checkpoint bug

### ISSUE THREAD

**Issue by CoopatroopaX** [MelvorIdle/melvoridle.github.io#945]
![crafting checkpoints](https://user-images.githubusercontent.com/82892923/115420013-cf658480-a1c8-11eb-9e51-5fa5fc042491.PNG)
![checkpoints](https://user-images.githubusercontent.com/82892923/115420030-d2607500-a1c8-11eb-8fbc-03b8504157d0.PNG)

seems to be a visual bug, completion cape grants access to all mastery checkpoints but has a few visual problems

1. it shows pool at 100% even when it's not
2. the checkpoint does not lightup green if not at the correct checkpoint (confirmed the 95% checkpoint works with crafting as I produced 2 rings everytime.

**Comment by MelvorIdle** [comment]
Confirmed fixed in next major update
