### ISSUE TITLE
max hit keeps fluctuating vs. Rokken with Tidal Edge.

### ISSUE THREAD

**Issue by PrinceAhmedofEgypt** [MelvorIdle/melvoridle.github.io#946]
https://cdn.discordapp.com/attachments/625838709744599088/834263809161429045/unknown.png
https://cdn.discordapp.com/attachments/625838709744599088/834264391665975336/unknown.png
images above are screenshots of the difference in max hit.
the gear worn at that time is: 
https://cdn.discordapp.com/attachments/625838709744599088/834261228498321438/unknown.png
the agility obstacles running at that time:
https://cdn.discordapp.com/attachments/625838709744599088/834263996264874004/unknown.png
https://cdn.discordapp.com/attachments/625838709744599088/834264084659830824/unknown.png
SEMI or other scripts were disabled.

**Comment by Falterfire** [comment]
Rokken's Elusiveness special attack temporarily provides it with 30% damage reduction, which will result in your max hit changing. Are you sure this isn't a result of that?

**Comment by MelvorIdle** [comment]
This one is hard to reproduce (Well, I'm unable to at all).

I will close this report for now. If the bug persists in the next major update, open a new ticket (following the template) with all information you can gather
