### ISSUE TITLE
typo: "your potion as depleted" instaed of "your potion has depleted" 

### ISSUE THREAD

**Issue by RansomTime** [MelvorIdle/melvoridle.github.io#948]
**Describe the bug**
The message string "your potion as depleted" should read "your potion has depleted". This is probably a typo

**To Reproduce**
1. Ensure auto-reuse potions is off
2. use a potion
3. perform the action that uses potion charges until it depletes
4. inspect the message

**Screenshots**
![image](https://user-images.githubusercontent.com/47819665/115955644-be31b600-a4ef-11eb-9bc0-d58d61c878e2.png)

**Browser**
FF 87

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Fixed in next update
