### ISSUE TITLE
Rerolling chests

### ISSUE THREAD

**Issue by Azemari** [MelvorIdle/melvoridle.github.io#949]
**Describe the bug**
If you force save the game before opening a chest, you can keep re-rolling the chest(s) until you get the item that you want.

**To Reproduce**
- Have a chest of any kind.
- Force save your game
- Open the chest
- If you don't like what you get re-load from cloud save
- Repeat

**Expected behavior**
When you open a chest, I would expect the game to force a cloud save to stop the user from loading up the save and re-opening the chest. A similar thing can be done with the offline timer and fishing to acquire the ancient rings. Keep re-loading until you get the rare item that you want.

**Browser**
Tested on Mobile and Steam App

**Are you using any scripts?**
No Scripts

**Comment by MelvorIdle** [comment]
This is something that is hard to combat at the moment due to the nature of the game. It may be fixed in the future but it will require a lot of work. 

Closing for now
