### ISSUE TITLE
Fishing bug with offline progress on very small internvals

### ISSUE THREAD

**Issue by Silverfyree** [MelvorIdle/melvoridle.github.io#953]
Hi,

By enabling the experimental setting whilst fishing whales and flicking between tabs on about a 1-2 second interval you can acquire the minimum threshold to get a guaranteed 1 action even though average timer should be a lot higher. Easily reproducible on fishing when flicking tabs and loading offline progress each time, leading to much higher fishing exp rates than should be possible.

Most likely need to add some kind of minimum timer before offline progress triggers such as 10s or so.

You can find further info here: https://discord.com/channels/625838709203271680/625840209531240469/837585246613536808

**Comment by MelvorIdle** [comment]
Fixed in upcoming major update. Now it actually checks if you have caught 1 fish instead of giving 1 action by default.
