### ISSUE TITLE
Skull Cape works for Alt Magic

### ISSUE THREAD

**Issue by 04Slash** [MelvorIdle/melvoridle.github.io#955]
**Describe the bug**
The Skull Cape states it gives a 20% chance to preserve runes **in combat.** This gives the impression that the Skull Cape should not work in Alt Magic. Doing a test on this appears that the Skull Cape does work in Alt Magic.

**To Reproduce**
1. Give and Equip Skull Cape `addItemToBank (818, 1)`
2. Give Runes `addItemToBank (389, 10000)` `addItemToBank (821, 1000)`
3. Go to Alt Magic and cast 'Just Learning'
4. See that after 1,000 casts you have (roughly 20%) more than 1,000 Rune Essence

The above was done 3 times. One "Control Test" without the cape which gave the expected 1,000 Rune Essence after 1,000 'Just Learning' casts. Then Two tests with a Skull Cape equipped which provided roughly 20% more Rune Essence from the same number of casts(1,231 and 1,243). Each test a brand new account was made to ensure there was no benefits from anything else.

**Expected behavior**
I would expect, based on the Skull Cape's description, for the cape to not work in Alt Magic and only in Combat unless the description is wrong and thus it should be changed to indicate it works in all areas of magic.

**Comment by MelvorIdle** [comment]
Confirmed fixed in next major update
