### ISSUE TITLE
Non-Combat tab disappears when minimised

### ISSUE THREAD

**Issue by Shoryuken2** [MelvorIdle/melvoridle.github.io#956]
**Describe the bug**
If I minimise the non-combat tab on the left, to reduce the amount of icons visible, the non-combat section disappears completely and i’m unable to open it back up again unless I restart the app.

![233ECC2E-6FF5-4D51-A14C-AFB4BDA2102A](https://user-images.githubusercontent.com/83644364/116996067-cc8f8700-acd2-11eb-9283-a3d6a9b9857b.jpeg)
If I minimise the “Combat” section, i’m able to maximise again no issues.

![7C2E7882-A07E-4FD9-BBFD-2AFD4968BBBB](https://user-images.githubusercontent.com/83644364/116995149-9b628700-acd1-11eb-8051-a8827332067c.jpeg)

**To Reproduce**
1. Go to 'Main UI' - (Bug found using iPad Pro 10.5, iOS 14)
2. Click on 'eye-icon to hide/minimize the Non-Combat skills '
3. Notice that the Non-Combat section is no longer visible so can’t be opened again
4. If you close App down and reopen, the Non-Combat section is again visible.
5. This doesn’t happen for Combat skills section this can be minimised and maximised multiple times.

**Expected behavior**
It should be possible to minimise and maximise the Combat and Non-Combat tabs on the left.

**Browser**
iPad app version 0.19.2

**Comment by MelvorIdle** [comment]
Confirmed fixed in the next major update

**Comment by earchibald-lv** [comment]
Not fixed.

**Comment by earchibald-lv** [comment]
This is still happening on iOS 1.0.5 (?2077).
