### ISSUE TITLE
Everyday level-loss

### ISSUE THREAD

**Issue by thisismyusernamenotyoursgoaway** [MelvorIdle/melvoridle.github.io#958]
Every morning I get back into my game and I’ve lost lots of saved exp and levels. It gets worse each day. Today I just lost all my crafting, all my slayer, all my attack, and all my strength levels. The only thing I’ve been left with is my defense levels. 

I don’t know what triggers this but it happens every day the first time I get on. 

This is without use of anything outside the game, I play normally through a google web browser.

**Comment by MelvorIdle** [comment]
Please confirm that you are loading the **Local Save**, and not the Cloud Save?
