### ISSUE TITLE
Mastery 99 Production Skills turn white upon spending mastery points

### ISSUE THREAD

**Issue by Tekila15** [MelvorIdle/melvoridle.github.io#960]
If you have 99 mastery on an item, say Dragonite Bars it'll have a yellow number, beside the requirements
![image](https://user-images.githubusercontent.com/83763486/117290887-3d1add00-ae66-11eb-937e-0fec4ea2c6e1.png)

If you then spend mastery points for that skill, say increase Iron Bars from 87 to 88, 
![image](https://user-images.githubusercontent.com/83763486/117291127-8408d280-ae66-11eb-8409-06be84c420b4.png)
, the yellow number as previously shown will turn white until it's clicked out of, another is crafted or just clicking it again
![image](https://user-images.githubusercontent.com/83763486/117291162-8d923a80-ae66-11eb-87a8-e981dc2e958a.png)

Others on the discord seem to be having this "problem", and it seems to be the same for steam and browser users regardless of scripts etc

Love you <3

**Comment by MelvorIdle** [comment]
Should be fixed in upcoming update
