### ISSUE TITLE
Lost progress due to infinite loading issue.

### ISSUE THREAD

**Issue by agent8364** [MelvorIdle/melvoridle.github.io#961]
The bug is simple, but not easily repeatable. What happens is if you tab out, and load back in (generally after long periods of time), sometimes the loading screen never leaves. This forces you to have to refresh or close out of the tab and lose all of your progress. You cannot save because you're in the loading screen, and it just kinda sucks all around. Has made me lose a total of around 30-40 hours of free mining so far.

It's kinda difficult to repeat, as it is not always guaranteed to happen. Basically, just tab out, and tab back in a few hours or so later. Sometimes it happens, sometimes it doesn't.

I expected for it to work like normal, show me the items I got and let me continue on with life.

I use the Google Chrome

As I wanted to get this report done by next year, I did not place a console output. If It happens to me again, I will update this with the output.

I was not using any scripts at the time.

**Comment by MelvorIdle** [comment]
This should be fixed in the upcoming update
