### ISSUE TITLE
Tidal edge keeps fluctuating damage (before/after triangle)

### ISSUE THREAD

**Issue by Space-Owl** [MelvorIdle/melvoridle.github.io#962]
The tidal edge in game continues to fluctuate listed damage heavily, but also goes above max hit listed before/after combat triangle application.

You can reproduce it by using the tidal edge at all and changing stances, fighting "weak" enemies in the triangle

The expected behaviour is that it doesn't do this and properly adjusts damage based on the triangle after combat buffs have been applied.

https://www.reddit.com/r/MelvorIdle/comments/n79ijn/wrong_damage_calculation_vs_elder_vampire/ There's a reddit post i made on the melvor idle page with screenshots.

Using steam version

It's the steam version so using F12 makes screenshots happen.

No scripts used.

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
