### ISSUE TITLE
Aorpheat's Signet Ring

### ISSUE THREAD

**Issue by Glacyte** [MelvorIdle/melvoridle.github.io#963]
**Describe the bug**
The ring does not give the bonus gold when training agility.

**To Reproduce**
1. Equip Aorpheat's Signet Ring
2. Go to agility skill
3. Start training agility
4. GP bonus not being applied

**Expected behavior**
The ring description says +100% GP from all sources excluding Alt. Magic and Item Selling. Was expecting to receive +100% GP from Agility course obstacles.

**Screenshots**

**Browser**
Steam app

**Console output**

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Yes it does, the GP value shown within the Agility screen is inclusive of the +% GP bonuses from equipment and passives.
