### ISSUE TITLE
Side menu opens when moving items between bank tabs in a narrow window

### ISSUE THREAD

**Issue by kfactor072** [MelvorIdle/melvoridle.github.io#964]
**Describe the bug**
When I have Melvor in a narrow Google Chrome window (Windows 10), and I move items between tabs in my bank, the collapsible side menu opens up approximately 50% of the time. Seems to happen more with skill capes.

**To Reproduce**
1. Open Melvor in Chrome
2. Snap the window to the right side of your screen
3. Make the window as narrow as possible
4. Move items between bank tabs

**Expected behavior**
I expected the side menu not to open.

**Screenshots**
This is a 20 second screen recording.
https://youtu.be/LFWaABChZo8

**Browser**
Google Chrome 90.0.4430.93

**Console output**
empty

**Are you using any scripts?**
no

**Comment by MelvorIdle** [comment]
Thanks. Confirmed fixed for the next update :)

(Will close when update is released)

**Comment by MelvorIdle** [comment]
Will close now to clean up GitHub
