### ISSUE TITLE
Pet Completion Achievement at 97%

### ISSUE THREAD

**Issue by MyAngelKei** [MelvorIdle/melvoridle.github.io#966]
Pretty much the title. I got the Pet Completion Achievement on Steam, while missing the Crafting Pet. The achievement got added once I got my second to last pet, in this case herblore.

I don't know how to try to reproduce this bug, maybe im just an anomaly.

Following this bug report layout, I expected Pet Completion to be awarded at 100%.

It's not like they prove anything, but here goes:
![image](https://user-images.githubusercontent.com/84016474/117803507-01618800-b257-11eb-869a-9f977460b2aa.png)
![image](https://user-images.githubusercontent.com/84016474/117803568-10483a80-b257-11eb-81ad-a01b096a6cf5.png)

No Browser, Steam.

F12 does Screenshot on Steam :(

No scripts used.

**Comment by MelvorIdle** [comment]
Confirmed fixed in next major update. Thank you
