### ISSUE TITLE
Book of Occults Passive Not Working

### ISSUE THREAD

**Issue by LordHaplo** [MelvorIdle/melvoridle.github.io#969]
**Describe the bug**
With the Book of Occults equipped in the off-hand it does not reduce the casting cost of 1 body rune.  I have tried all of the curses and it does not reduce them at all.

**To Reproduce**
1. Equip Book of occults  and any one-handed magic combat weapon (wand)
2. Select damage spell (any) and a curse that consumes a body rune (Soul Split 1 for example)
3. Attack any enemy 

**Expected behavior**
The casting cost of the curse would be 0 for one that consumes 1 body rune or 1 less for a curse that consumes more than 1

**Browser**
Steam App ID 1267910 
Build 5866995

**Console output**
Steam does not have this available 

**Are you using any scripts?**
no scripts, stock steam version

**Comment by LordHaplo** [comment]
People on reddit have been apparently reporting this issue for a few months:

https://www.reddit.com/r/MelvorIdle/comments/kq8tts/book_of_occults_passive_bugged/
https://www.reddit.com/r/MelvorIdle/comments/m68twb/book_of_occults/

**Comment by MelvorIdle** [comment]
Confirmed fixed in next major update
