### ISSUE TITLE
The fourth line of text in the book A Tale of the Past... is grammatically incorrect.

### ISSUE THREAD

**Issue by Dwake5** [MelvorIdle/melvoridle.github.io#970]
**Describe the bug**
The fourth line of text in the book A tale of the past, a future prophecy part 1 or 3 is incorrect.

**To Reproduce**
Read the book

**Expected behavior**
To be able to read text with no mistakes

The text currently says:
As time went on, so did the complexity in their positions grew.
It should be grow in instead of grew.

**Comment by MelvorIdle** [comment]
These are currently being rewritten :)
