### ISSUE TITLE
Deleting Local Save Deleted All Saves

### ISSUE THREAD

**Issue by Hoppnerd** [MelvorIdle/melvoridle.github.io#973]
**Describe the bug**
Hey, when I loaded up my Steam version on Saturday I went to delete an old local save but it ended up deleting both that save and my main's Local and Cloud saves. 

I had been running off my Mobile App's Local Save before that so I haven't lost anything. 

I loaded my account on Chrome Browser after this and the Cloud Save was gone before I re-Cloud Saved on Mobile. 

Ever since this, my Steam version is just stuck on the spinny M logo, not loading even after waiting about half an hour. Neither verifying files nor uninstalling and reinstalling the game on Steam have resolved the issue. 

I'm currently running off Browser so not a huge deal but to be able to run on Steam would be highly preferred. Thanks in advance and sorry if the below information doesn't leave much to work with.

**To Reproduce**
Steps to reproduce the behaviour:
1. Load Melvor via Steam
2. Click on 'Settings'
3. Click 'Delete Save'
4. On page reload, all saves were gone including Cloud saves...

**Expected behaviour**
For only one save to be deleted, not all saves.

**Screenshots**
I didn't take any screenshots at the time of the incident.

**Browser**
The incident occurred on the Steam version.
Currently running on Chrome Version 90.0.4430.212 (Official Build) (64-bit)

**Console output**
[Copied 2 days post-incident via web browser as Steam version will no longer load]
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cdn.melvor.net/core/v018/assets/media/shop/assets/media/shop/perpetual_haste.svg:1 Failed to load resource: the server responded with a status of 403 ()
save.js?839:13 Loading Save Game...
save.js?839:29 Save Game Loaded...
mastery.js?839:2 Loading Masteries...
main.js?839:7 Game Loaded
2cloud.js?839:8 Synchronising with Cloud
cloud.js?839:76 Connected to PlayFab successfully
151cloud.js?839:8 Synchronising with Cloud
cloud.js?839:76 Connected to PlayFab successfully
147cloud.js?839:8 Synchronising with Cloud
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
I have never used any scripts with Melvor.

**Comment by MelvorIdle** [comment]
Hi Hoppnerd. The best thing to do is delete all files associated with the Steam Client, specifically in the AppData/Local/Melvor Idle folder.

**Comment by Hoppnerd** [comment]
Thanks, I'll give that a go!
