### ISSUE TITLE
Golbin raid prayer bug

### ISSUE THREAD

**Issue by thunders-1234** [MelvorIdle/melvoridle.github.io#974]
![image](https://user-images.githubusercontent.com/84316910/118466119-c2d33e00-b72c-11eb-9ecd-182ea208c2b5.png)
As you can see, I can use the stone skin prayer even though I have level 72 prayer. This can be recreated by maxing the prayer level on golbin raid, and then you start a raid, and immediately run away, after that, you can access all the prayer you have on golbin raid despite the prayer level you have, but this bug will be fixed when you refresh.

**Comment by MelvorIdle** [comment]
Confirmed fixed in next major update
