### ISSUE TITLE
Ability to use Items in Combat Equipment in more than 1 set at a time

### ISSUE THREAD

**Issue by Nytherio** [MelvorIdle/melvoridle.github.io#975]
So while training combat, I often swap between different sets for magic, skilling, melee, etc and have found that if I have a necklace equipped on 1 set, I don't have the option of equipping the same necklace on a second set since it removes the item from my bank. I believe it would be more useful if you could 'allocate' the same item to multiple combat equipment sets and it would transfer the item between sets when swapping. This rule applies to any item equipped on a combat set.

I'm suggesting this because in my experience, needing to unequip my amulet of looting and ring and then click on my second equipment set which has no necklace or ring slotted and still needing to go into my bank and equip those items manually just becomes a nuisance. 

This becomes a QOL change that would just streamline swapping combat sets since with the current system, you would need to obtain 2 different amulets of looting just in order to equip it on 2 different sets simultaneously.

**Comment by MelvorIdle** [comment]
Unfortunately this is a lot more than a "QoL" change, as you are basically requesting a major change to the core mechanics and balance of the game.

Basically if you want to equip items in more than one set, you will need to acquire more another one. This is part of how the game has been balanced. If I were to implement this change, all rare items would be 3-5x more rare than they are now
