### ISSUE TITLE
Golbin Raid - Sandstorm Ring (ALT) - Increased Trigger Frequency Bug

### ISSUE THREAD

**Issue by Valericoe** [MelvorIdle/melvoridle.github.io#976]
**To Reproduce**
The Sandstorm Ring's Alternate Special Attack seems to be triggering 100x(?) more often than it should be, and is persisting across Golbin Raids instances.
I don't believe it's using the current weapon's damage value. (Seemingly 5-15% damage, not 100% accurate, 10+ times per second)
Prayer is also draining at a rate of about 10 attacks per second when toggled on.
The Attack bar is resetting rapidly as well.

**To Reproduce**
1. Start a Golbin Raid
2. Get an (ALT) weapon that consumes ammo (In my case, ice bow + dragon)
3. Get an (ALT) sandstorm ring (Unsure, the alt effect of sandstorm rings is never listed for me)
4. Run out of ammo for the weapon so the primary weapon is replaced with a bronze scimitar

**Expected behavior**
Normal bronze scimitar attacks + Sandstorm Ring attacks.

I'm guessing the Sandstorm Ring's alternate special attack is referencing the character's primary weapon. When it was replaced with a different weapon it potentially lost an attribute of when to end the special attack. (e.g. In the middle of attack 2 of 3 -> attack 2 of undefined)

**Browser**
Steam Alpha V0.19.2

**Are you using any scripts?**
None.

**Comment by Valericoe** [comment]
Also, it appears to persist into standard gameplay as well.

**Comment by MelvorIdle** [comment]
Thanks. I am removing the Sandstorm Ring from being able to turn into an "ALT" item in the raid in the coming major update.
