### ISSUE TITLE
Locked logs in the Firemaking dropdown menu have the "text-danger" class but are white because of the dark mode

### ISSUE THREAD

**Issue by nicosemp** [MelvorIdle/melvoridle.github.io#977]
**Describe the bug**
In Firemaking, if you still have some logs which are unavailable due to your mastery level they show as "Level X Required".
This line should take the red color from the "text-danger" class, but instead it's white because the dark mode creates a higher priority rule.

**To Reproduce**
1. You must have at least 1 log in your bank which you can't burn in Firemaking because you don't have enough experience.
2. Open the Firemaking dropdown menu e see the unavailable log(s) text in white.

**Expected behavior**
The unavailable logs should be red and not white

**Screenshots**
![image](https://user-images.githubusercontent.com/8838305/119225065-ec5fe100-bb01-11eb-9bef-75bfdf1f1a28.png)

**Browser**
Chrome Beta 91 -> irrelevant imo, it's a CSS problem

**Console output** -> this is also irrelevant here: it's a CSS problem
Loading Save Game...
save.js?839:29 Save Game Loaded...
mastery.js?839:2 Loading Masteries...
main.js?839:7 Game Loaded
cloud.js?839:8 Synchronising with Cloud
cloud.js?839:8 Synchronising with Cloud
cloud.js?839:76 Connected to PlayFab successfully
cloud.js?839:8 Synchronising with Cloud
cloud.js?839:8 Synchronising with Cloud
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
cloud.js?839:8

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Thanks. Confirmed fixed in next major update.
