### ISSUE TITLE
Leveling pop up going past 99

### ISSUE THREAD

**Issue by weier-c** [MelvorIdle/melvoridle.github.io#986]
**Describe the bug**
The Crafting level up message received after opening the iOS app said level 100 was reached instead of 99

**To Reproduce**
1. Begin crafting red dhide chaps with lvl 98 crafting
2. Close app and leave idling for 12 hours 
3. When app is reopened, pop up says level 100 has been reached

**Expected behavior**
Pop up should be lvl 99 as this is the cap

**Screenshots**
![image](https://user-images.githubusercontent.com/68737549/120906718-2e128f00-c69f-11eb-88c6-eb874eea4eca.png)

**Browser**
iOS app v0.19.2

**Console output**
N/A

**Are you using any scripts?**
N/A

**Comment by coolrox95** [comment]
Fixed as of Alpha v0.22 (?1164).
