### ISSUE TITLE
Wrong numbers

### ISSUE THREAD

**Issue by abvgdika** [MelvorIdle/melvoridle.github.io#987]
Malcs, the leader of dragons, it says his max damage per 1 hit of razor sharp claws is 327, but he always inflicts 328 damage
![Снимок экрана (166)](https://user-images.githubusercontent.com/85437245/120921138-f588aa80-c6ca-11eb-8f2b-0b2833202c73.png)

**Comment by coolrox95** [comment]
Fixed in update v0.21
