### ISSUE TITLE
Agility - Frozen Lake Crossing not adding Auto-Eat Efficiency 

### ISSUE THREAD

**Issue by morckpr** [MelvorIdle/melvoridle.github.io#989]
The 10% bonus from this agility pillar isn't being added. I have auto-eat tier 3 purchased and with or without this pillar I stay at the 40% threshold. When hovering over the crab icon in combat it shows 40% as well as during actual combat my character will not eat until it's below 40%.

**Comment by coolrox95** [comment]
Auto-eat efficiency improves the amount of healing you get per food item when auto-eat triggers. This is not to be confused with Auto Eat Threshold. 
E.g. A Food item that heals 100 HP with 50% efficiency will heal 50 HP.
