### ISSUE TITLE
Mining XP/Level Advance Bug

### ISSUE THREAD

**Issue by djavoprokleti** [MelvorIdle/melvoridle.github.io#995]
**Describe the bug**
Mining stuck 1XP below Level 27 and does not advance.

**To Reproduce**
1. Go to Mining
2. Choose to mine any ore available (Rune Essence, Copper, Tin, Iron)
3. Mastery XP advances but level XP does not advance
4. No Error Messages produced

**Expected behavior**

**Screenshots**
https://postimg.cc/sQ7wYbtM

https://postimg.cc/1gLvNyYx

**Browser**
Steam Version

**Console output**
No Console Output Available

**Are you using any scripts?**
No scripts in use.

**Comment by MelvorIdle** [comment]
Not a bug. You are playing adventure mode. Double check the rules of the gamemode.

**Comment by djavoprokleti** [comment]
Thanks, makes sense, apologies for the bug in my bug report :)
