### ISSUE TITLE
Equipment Bug

### ISSUE THREAD

**Issue by Madiluxx** [MelvorIdle/melvoridle.github.io#998]
**Describe the bug**
There seems to be an issue with what the game is recognizing as equipment.  A screenshot will be provided.

**To Reproduce**
Simply click an item that is to be equipped from the bank.

**Expected behavior**
A true description of what is to be replaced

**Screenshots**
![image](https://user-images.githubusercontent.com/85723602/121631319-db452880-ca4c-11eb-834c-d4d23a40c6bd.png)

**Browser**
Steam Client

**Console output**
Steam Client

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
Hotfixed :)
