### ISSUE TITLE
Smithing "Chance to double items" icon never moves from "0%"

### ISSUE THREAD

**Issue by Eraldoe** [MelvorIdle/melvoridle.github.io#999]
Client: Steam desktop
Scripts/mods: none

The new doubling icon always reads "0." At Mastery 77 (and no other bonus present) I expect this to read "20%"

![image](https://user-images.githubusercontent.com/16160354/121632263-8813ab80-ca35-11eb-84ef-4db41164b68f.png)

Flyout also reads 0:

![image](https://user-images.githubusercontent.com/16160354/121632335-a8436a80-ca35-11eb-91dc-7c853a2f7bbb.png)

Doubling still appears to work as expected:
![image](https://user-images.githubusercontent.com/16160354/121632375-bdb89480-ca35-11eb-8030-5931bf41bbc9.png)

**Comment by thijsvm03** [comment]
![image](https://user-images.githubusercontent.com/75121134/121695882-cb205e00-cacb-11eb-80be-dd35482cf8c1.png)
its just a visual bug for because im still getting dublicates

**Comment by ChaosLegion** [comment]
Yep its visual. I get 15% at 1 mastery on bronze swords.

**Comment by dilien** [comment]
got the same issue, its just a visual bug.

**Comment by MelvorIdle** [comment]
This should be hotfixed now. Please confirm

**Comment by Eraldoe** [comment]
@MelvorIdle  still seems broken in 0.20?915 (was also not working in ?913)

![image](https://user-images.githubusercontent.com/16160354/121760852-b64ec500-cae1-11eb-96d9-fe8a721b56fe.png)

**Comment by Eraldoe** [comment]
(slowly grinding a new character in 0.20?915 atm with the aim of testing if it might be save data related)

**Comment by Eraldoe** [comment]
I have created a new character on 0.20?915 and aim to report in later today if the behaviour is any different on a "fresh save."

**Comment by Eraldoe** [comment]
I can report that with a new save, everything so far is working as expected. Doubling increased to 5, then again to 10. Note that  if I start mastering a new smithing item on my original save, it never progresses beyond 0% for doubling.

![Melvor_Idle_2021-06-11_21-12-42](https://user-images.githubusercontent.com/16160354/121764570-cd99ac80-caf9-11eb-82ba-f2f592a0a947.png)


This is my current primary save which has the issue:

[melvoridlesave_Eraldoe (1).txt](https://github.com/MelvorIdle/melvoridle.github.io/files/6641620/melvoridlesave_Eraldoe.1.txt)


This is the test save which thus far has reached 10% double chance on bronze bars:
[melvoridlesave_TEST SMITH BUG.txt](https://github.com/MelvorIdle/melvoridle.github.io/files/6641648/melvoridlesave_TEST.SMITH.BUG.txt)

**Comment by NineRed** [comment]
I can confirm that the issue is persisting.  While it's fortunately a cosmetic issue, it's nonetheless misleading.

![firefox_2021-06-13_08-01-55](https://user-images.githubusercontent.com/20262747/121810365-d4214480-cc1d-11eb-9483-5ee5950ea55a.png)

**Comment by dmk218** [comment]
![image](https://user-images.githubusercontent.com/85874650/121877321-1acf7700-ccd0-11eb-97a8-20c9df5ba71f.png)
i also see this issue in adventure mode. Even though it is showing 0% i still get double bars once in a while.

**Comment by Eraldoe** [comment]
No longer experiencing this issue on Steam 0.20 ?936. Both new things I have never smithed before and old things that previously had the 0% doubling chance now show the correct %. @dmk218 @NineRed  @thijsvm03   etc can a few of you update your client and confirm the issue is fixed? If so let's close this off :)

**Comment by NineRed** [comment]
![Capture](https://user-images.githubusercontent.com/20262747/122460471-63f12680-cf6f-11eb-900e-6f5148c42154.PNG)

Values now appear to appropriate, for both old and newly mastered items. Looks fixed to me. Web ?936

**Comment by dmk218** [comment]
seams to be working.

**Comment by Eraldoe** [comment]
Confirmed fixed by multiple users, closing.
